package com.sliverzfx.gothicquest

internal object ArcholosChapter4Part1Data {
    val quests: List<Quest> = listOf(
        Quest(
            id = "AR-C4-001",
            chapter = 4,
            playOrder = 1,
            title = "Silver Lining (Part II)",
            category = "MAIN STORY — Guild/story route",
            giver = "Automatic from Silver Lining (Part I) / Volker",
            location = "Archolos → Wolf’s Den",
            prerequisites = "Chapter 4; complete Silver Lining (Part I) at the end of Chapter 3 and travel to Wolf's Den.",
            summary = "Follow Volker's lead to Ulryk's fortress and gain entry by resolving the refugees' presence.",
            walkthroughSteps = listOf("After the Chapter 4 transition, travel toward Wolf's Den north-west of Archolos. Ivy may accompany you, but she is not required.", "At the fortress gate, speak with Crednar. He refuses entry until the refugees outside are dealt with.", "Complete Things They Deserve by relocating or removing the refugee group through Fabio or the Yezegan/Duster plan.", "Return to Crednar to enter the keep. Ask about local smith Einar and meet Ivy inside to begin investigating the special crossbow bolthead."),
            reward = "The Wolf’s Den becomes the main Chapter 4 hub.",
            warnings = "Wolf's Den entry requires Things They Deserve; you cannot simply gain Ulryk's audience by asking nearby guards.",
            searchTags = listOf("CHAPTER 4 — A HEART OF STONE", "", "Guild/story route", "Canonical quest"),
        ),
        Quest(
            id = "AR-C4-002",
            chapter = 4,
            playOrder = 2,
            title = "Things They Deserve",
            category = "MAIN STORY — Guild/story route",
            giver = "Crednar / refugees / Duster",
            location = "Wolf’s Den outer settlement",
            prerequisites = "Route: Guild/story route",
            summary = "Remove the refugees blocking access to Wolf’s Den using persuasion, relocation or Duster’s demolition plan.",
            walkthroughSteps = listOf("Speak with Crednar and the refugees outside the fortress and hear both sides before attacking anyone.", "Choose a solution. For the demolition route, obtain the powder supply through Yezegan/Duster and meet Duster at the Harbour breakwater when directed.", "Return to Wolf’s Den around midnight, take the Powder Keg and climb the cliff/waterfall route above the refugees.", "Place the keg at the marked collapse point and ignite it with a torch, or finish one of the non-explosive relocation solutions instead.", "Speak with Fabio after the refugees leave, then return to Crednar at the main gate."),
            reward = "Completing a refugee-removal option earns 250 XP from Crednar and opens Wolf's Den. The Duster demolition route offers another 1,000 XP on Fabio's cooperation.",
            warnings = "Be careful with Fabio's relocation option: refugees sent into the Misty Marshes later reappear as undead. Duster requires a night meeting; do not set the powder keg on fire until ready to commit.",
            searchTags = listOf("CHAPTER 4 — A HEART OF STONE", "", "Guild/story route", "Canonical quest"),
        ),
        Quest(
            id = "AR-C4-003",
            chapter = 4,
            playOrder = 3,
            title = "One Thing Leads To Another (Part I)",
            category = "MAIN STORY — Guild/story route",
            giver = "Einar / Ulryk",
            location = "Wolf’s Den",
            prerequisites = "Route: Guild/story route",
            summary = "Trace the unusual bolthead through Einar’s recent customers and identify Jon as the key lead.",
            walkthroughSteps = listOf("Locate blacksmith Einar behind Wolf's Den's column hall and show him the special bolthead. He confirms he forged it.", "Investigate his recent customers Arethe, Gron, Henk and Legrif, checking each account rather than assuming the first one is guilty.", "Obtain Arethe's bolt by pickpocketing or searching his chest at night; it does not match the murder bolt.", "Inspect Gron's training target and the projectile lodged in it. Question Henk, who can be found up on a ledge above the camp.", "Continue investigating until the clues lead to Jon and Ulryk's further mine investigation."),
            reward = "The bolthead investigation identifies Jon and the story advances.",
            warnings = "Prematurely pickpocketing Arethe's bolt can make the journal look out of order but does not block completion. Einar's expensive weapons may become reward alternatives after the mine.",
            searchTags = listOf("CHAPTER 4 — A HEART OF STONE", "", "Guild/story route", "Canonical quest"),
        ),
        Quest(
            id = "AR-C4-004",
            chapter = 4,
            playOrder = 4,
            title = "The Only Way To Jon",
            category = "MAIN STORY — Guild/story route",
            giver = "Ulryk / Wolf’s Den",
            location = "Wolf’s Den / mine",
            prerequisites = "Route: Guild/story route",
            summary = "Clear the minecrawlers from the open mine so Ulryk will allow you to meet Jon.",
            walkthroughSteps = listOf("Speak with Ulryk and ask for access to Jon.", "Go to the open mine near the refugee camp outside the fortress.", "Kill the minecrawlers; if they are too strong, lure them toward friendly Wolf Sons.", "Return to Ulryk and report that the mine is safe.", "Use the granted access to continue toward Jon."),
            reward = "You gain permission to see Jon and the Chapter 4 investigation advances.",
            warnings = "",
            searchTags = listOf("CHAPTER 4 — A HEART OF STONE", "", "Guild/story route", "Canonical quest"),
        ),
        Quest(
            id = "AR-C4-005",
            chapter = 4,
            playOrder = 5,
            title = "Journey To The Centre Of The Mine",
            category = "MAIN STORY — Guild/story route",
            giver = "Ulryk / Wolf Sons",
            location = "Wolf’s Den mine",
            prerequisites = "Route: Guild/story route",
            summary = "Assemble enough helpers, descend into the mine and reach Jon’s trail.",
            walkthroughSteps = listOf("Recruit the miners/helpers requested for the descent: Henk wants smelling salts, Legrif wants Lucy’s travel pillow, Gron responds to the news and Dalmon requires the truthful handling of Rosaline’s letter.", "Complete Hunter’s Blood first if you need Lucy to hand over the pillow.", "Report the recruited helpers and enter the mine with the group.", "Clear minecrawlers and other underground enemies room by room; keep the squad together and loot keys/notes from bodies.", "Follow the mine route to the story confrontation/evidence connected to Jon and complete the return dialogue."),
            reward = "After the mine expedition, Ulryk gives 1,000 XP, 1,000 gold, an Elixir of Strength and either a Decorated Axe or Dueling Saber based on Marvin's build.",
            warnings = "Complete Hunter's Blood first if Lucy's pillow dialogue is missing. Henk, Legrif, Gron and Dalmon have different personal recruitment prerequisites; keep the mine team together.",
            searchTags = listOf("CHAPTER 4 — A HEART OF STONE", "", "Guild/story route", "Canonical quest"),
        ),
        Quest(
            id = "AR-C4-006",
            chapter = 4,
            playOrder = 6,
            title = "One Thing Leads To Another (Part II)",
            category = "MAIN STORY — Guild/story route",
            giver = "Ivy / Jon’s house",
            location = "Wolf’s Den",
            prerequisites = "Route: Guild/story route",
            summary = "Search Jon’s house, survive the ambush and decode the package/evidence he left behind.",
            walkthroughSteps = listOf("After the mine sequence, look for Ivy at the Inn; Dirk explains she is missing and tells you where Jon lived.", "Enter Jon’s house and loot Jon’s Chest for Jon’s Package.", "Immediately prepare for combat: three Suspicious Guys ambush you as you leave the chest. Fight them inside or run outside to gain help from the Wolf Sons.", "Open/read the package contents and the Key To Cipher; reread the Strange Note once the key is available.", "Follow the decoded clue until the journal sends you back toward Archolos."),
            reward = "Jon’s evidence is decoded and Part III begins.",
            warnings = "",
            searchTags = listOf("CHAPTER 4 — A HEART OF STONE", "", "Guild/story route", "Canonical quest"),
        ),
        Quest(
            id = "AR-C4-007",
            chapter = 4,
            playOrder = 7,
            title = "One Thing Leads To Another (Part III)",
            category = "MAIN STORY — Guild/story route",
            giver = "Ludwig / guild leadership",
            location = "Archolos",
            prerequisites = "Route: Guild/story route",
            summary = "Use the Bloody Map and city contacts to continue Jon’s trail, pausing for the Royal Envoy decision when the story interrupts.",
            walkthroughSteps = listOf("Return to Archolos with the decoded evidence and Bloody Map.", "Show the map to cartographer Ludwig and let him work on clearing/reading it.", "When your guild summons you for In The Service Of His Majesty, resolve that decision first; Ludwig’s map work does not advance until this branch is started.", "Return to Ludwig after the interruption and collect the interpreted map/information.", "Follow the final lead to Long Awaited Meeting and the Ring of Water story."),
            reward = "Jon’s trail converges with the larger conspiracy and Chapter 4 main story continues.",
            warnings = "IMPORTANT: Ludwig does not finish cleaning Jon's Bloody Map until the Chapter 4 guild/Royal Envoy decision is underway. Start In the Service of His Majesty first if Ludwig appears stuck.",
            searchTags = listOf("CHAPTER 4 — A HEART OF STONE", "", "Guild/story route", "Canonical quest"),
        ),
        Quest(
            id = "AR-C4-008",
            chapter = 4,
            playOrder = 8,
            title = "Long Awaited Meeting",
            category = "MAIN STORY — Guild/story route",
            giver = "Trigger quest",
            location = "Archolos Slums",
            prerequisites = "Route: Guild/story route",
            summary = "Break into the north-west Slums hideout, discover Jorn's fate and escape with Kessel.",
            walkthroughSteps = listOf("Before finishing this quest, loot Volker's mansion if desired; access to the mansion closes afterward.", "Go to the house with a ramp in the north-west Slums and approach the rear door. Fight the two heavily armed bodyguards for their key, or hide in the barrel to bypass their initial ambush.", "Go downstairs past the sleeping bodyguards. Move the crates to barricade the door even if those guards are already dead.", "Use the stove to open the hidden bookcase, enter the underground prison and check the coffins, opening the center one LAST to discover Jorn.", "Survive the cutscene with Sachs and Kessel. Optionally use the switch and two Meatbug Transformation scrolls to access a hidden Amulet of the Thief in the cells.", "Re-equip your weapons after the scripted scene, follow Kessel through the hidden dock, pull the lever to lift the grate and escape to the beach."),
            reward = "5,000 XP after escaping the underground hideout to the beach; progresses into The Ring of Water.",
            warnings = "The route requires moving crates, using the STOVE to shift the bookcase, and the coffin scene. Re-equip weapons after the cutscene. Volker's manor closes after this sequence.",
            searchTags = listOf("CHAPTER 4 — A HEART OF STONE", "", "Guild/story route", "Canonical quest"),
        ),
        Quest(
            id = "AR-C4-009",
            chapter = 4,
            playOrder = 9,
            title = "The Ring Of Water",
            category = "FACTION QUEST — Ring of Water",
            giver = "Kessel",
            location = "Starting beach → mountains east of Silbach → Ring of Water meeting place",
            prerequisites = "Chapter 4; finish Long Awaited Meeting and meet Kessel on the beach where Marvin first arrived.",
            summary = "Meet Kessel and the Ring of Water above Silbach, survive Bradlock's ambush and escape over the waterfall to begin Chapter 5.",
            walkthroughSteps = listOf("After escaping Long Awaited Meeting, talk to Kessel on the starting beach. Ask about the Ring of Water and why Jorn was targeted.", "Before proceeding, visit Kurt's old house in Silbach for an optional 500 XP and complete outstanding Bermar's Farm quests; the upcoming ambush changes the region.", "Leave Silbach by the east gate, follow the rising mountain path on the right just beyond the pond, and meet Kessel near the river on the route toward Valerio's Vineyard.", "MAKE A MANUAL SAVE before talking with Kessel at the secret meeting location. His Ring of Water comrades are ambushed by Volker's men.", "Fight alongside Kessel to survive Bradlock and his soldiers. Collect useful elixirs from the fallen if safe.", "Follow Kessel to the WATERFALL and escape over it; this event ends Chapter 4 and begins the monastery crisis in Chapter 5."),
            reward = "Opens the Chapter 5 main storyline and the Ring of Water sequence; optional 500 XP available at Kurt's house before the ambush.",
            warnings = "CRITICAL POINT OF NO RETURN: this is an ambush and WATERFALL ESCAPE, not a purification ritual. Complete Bermar's Farm and other Chapter 4 side quests first.",
            searchTags = listOf("CHAPTER 4 — A HEART OF STONE", "", "Ring of Water", "Canonical quest"),
        ),
        Quest(
            id = "AR-C4-010",
            chapter = 4,
            playOrder = 10,
            title = "Everything Is Fine",
            category = "FACTION QUEST — Royal Envoy",
            giver = "Arcas / Grayson",
            location = "Archolos / Silbach",
            prerequisites = "Chapter 4; choose to LEAVE your original City Guard or Merchants' Guild during In the Service of His Majesty.",
            summary = "Investigate the missing Royal scout and prove yourself to the Royal Envoy.",
            walkthroughSteps = listOf("This route is available if you leave your guild and pursue Royal Envoy service in Chapter 4.", "Speak with Arcas outside the former guild area, then meet Grayson and accept the missing-scout problem.", "Travel toward Silbach and ask Albyn about Burkhard and recent Royal movements.", "Check the west-gate / road leads and speak with Harry or other named witnesses as the journal updates.", "Find the scout/evidence, resolve the threat and return to Grayson with a complete report."),
            reward = "The Royal Envoy route advances.",
            warnings = "Royal Envoy path EXCLUSIVE to characters who leave their prior guild; if you remain, this quest does not appear.",
            searchTags = listOf("CHAPTER 4 — A HEART OF STONE", "", "Royal Envoy", "Canonical quest"),
        ),
        Quest(
            id = "AR-C4-011",
            chapter = 4,
            playOrder = 11,
            title = "In The Service Of His Majesty (Part I)",
            category = "FACTION QUEST — Royal Envoy",
            giver = "Lorenzo / Grayson",
            location = "Archolos",
            prerequisites = "Route: Royal Envoy",
            summary = "Decide whether to work for the Crown and begin reporting on Grayson.",
            walkthroughSteps = listOf("After Journey To The Centre Of The Mine, answer the Mercenary summons and return to Lorenzo.", "Listen to Lorenzo’s request concerning Grayson and the Royal Envoy.", "Meet Grayson and hear the Crown’s side before committing yourself.", "Make a permanent save, then decide whether Marvin will enter Royal service / act as Lorenzo’s informant.", "Complete the first assigned report before continuing One Thing Leads To Another."),
            reward = "The Royal service branch is established.",
            warnings = "Your choice to stay in the City Guard/Merchants' Guild or enter Royal service gates later faction quests. Ludwig's Bloody Map work pauses until this decision is underway.",
            searchTags = listOf("CHAPTER 4 — A HEART OF STONE", "", "Royal Envoy", "Canonical quest"),
        ),
        Quest(
            id = "AR-C4-012",
            chapter = 4,
            playOrder = 12,
            title = "Vengard Dresses",
            category = "MAIN STORY — Guild/story route",
            giver = "Roderich / Grayson",
            location = "Archolos City Guard / Harbour",
            prerequisites = "Route: Guild/story route",
            summary = "Sabotage the Royal Envoys’ armour shipment so Roderich can keep the Guard barracks.",
            walkthroughSteps = listOf("After In The Service Of His Majesty starts, speak with Grayson, then Roderich and Lennart about the Royal armour arrangement.", "At night in the Marketplace, meet Lennart/Arwid as directed and obtain the plan for ruining the shipment.", "Ask Ramha for five rusting mixtures, paying the required cost.", "Use Arwid’s distraction at the Harbour warehouse to get inside without starting a fight.", "Apply the rusting mixture to all five armour chests, then leave and wait until the next day.", "Inspect the ruined shipment, take the standardized/rusted armour sample to Ramha, then report through Roderich, Grayson and the Guard contacts as the journal directs."),
            reward = "The Royal armour shipment is discredited and the City Guard branch advances.",
            warnings = "",
            searchTags = listOf("CHAPTER 4 — A HEART OF STONE", "", "Guild/story route", "Canonical quest"),
        ),
        Quest(
            id = "AR-C4-013",
            chapter = 4,
            playOrder = 13,
            title = "For The Public Good",
            category = "MAIN STORY — Guild/story route",
            giver = "Grayson / Lorenzo",
            location = "Archolos Old Town / Harbour",
            prerequisites = "Route: Guild/story route",
            summary = "Secure alternative quarters for Grayson’s Royal Envoys by forcing Kaleb to sell his Harbour house.",
            walkthroughSteps = listOf("Meet Grayson on the third floor of Town Hall and hear his demand for the Merchants’ Guild barracks.", "Report to Lorenzo; he proposes buying Kaleb’s large Harbour house instead. Speak with Caramon and inspect the target property with him.", "Collect the props for the haunting setup, including the old bones/blood and a rusty weapon; Einar in Wolf’s Den can supply the weapon.", "At midnight, enter Kaleb’s house while Caramon distracts him. Place the bones in the fireplace, the sword beside it and splash the blood at the instructed spot.", "Leave, sleep until morning, then meet Caramon and speak with Kaleb as the frightened staff refuse to enter.", "Report the successful purchase first to Lorenzo, then Grayson, then Lorenzo again for the full reward."),
            reward = "The Royal Envoys receive the house, the Merchants’ Guild keeps its barracks and the Chapter 4 guild mission is complete.",
            warnings = "",
            searchTags = listOf("CHAPTER 4 — A HEART OF STONE", "", "Guild/story route", "Canonical quest"),
        ),
        Quest(
            id = "AR-C4-014",
            chapter = 4,
            playOrder = 14,
            title = "Extreme Home Makeover",
            category = "SIDE QUEST — All routes",
            giver = "Bidding Announcement / Danis",
            location = "Archolos Old Town",
            prerequisites = "Chapter 4 for the auction itself; requires Old Town access from In Broad Daylight. The bidding notice can first arrive in Chapter 3.",
            summary = "Read the Bidding Announcement, post five auction notices, hire Kazeem as your fake bidder, then report the purchase to Danis.",
            walkthroughSteps = listOf("After gaining Old Town access through In Broad Daylight, a Mercenary eventually gives you the Bidding Announcement. Read it to start the quest.", "The quest cannot properly continue until Chapter 4. Find the Worker hammering on the Old Town house, then speak with magistrate Danis nearby.", "Visit Venzel at the Three Sailors Writing Workshop. He gives you five Notifications Of Bidding and a list of the noticeboards.", "Post one notice at each required board: Marketplace, Artisans' District, Fish Market, Old Town opposite Valley Of Gold, and Old Town opposite Ernesto's.", "After posting the Harbour notice, speak with Kazeem. Recruit him to bid on your behalf.", "Buy a Rich Merchants' Outfit from the Insignia tailor in the Marketplace for 400 gold and give it to Kazeem together with 1,000 gold for the bid.", "Rest until the journal tells you to meet Kazeem at the property. Pay the agreed 1,000 gold; he gives you the House Key.", "Report to Danis in the magistrate's office."),
            reward = "Ownership and House Key to the Old Town property; the bid requires roughly 1,000 gold for Kazeem plus his arrangement and a 400-gold rich merchant outfit.",
            warnings = "The quest can start in Chapter 3 but cannot be completed until Chapter 4. Paying Kazeem 2,000 instead of the agreed 1,000 gives NO extra benefit.",
            searchTags = listOf("LATE-GAME REGIONAL SIDE QUESTS", "ARCHOLOS — LATE GAME", "All routes", "Canonical side quest"),
        ),
        Quest(
            id = "AR-C4-015",
            chapter = 4,
            playOrder = 15,
            title = "A Plate Of Hot Food",
            category = "SIDE QUEST — All routes",
            giver = "Ernesto, Old Town",
            location = "Archolos",
            prerequisites = "Route: All routes",
            summary = "Cook and deliver Fisherman’s Cauldron to Laudus.",
            walkthroughSteps = listOf("Speak with Ernesto and learn/obtain the Fisherman’s Cauldron recipe.", "Cook the dish at a stove.", "Take it to Laudus at the Temple of Adanos.", "Choose whether to tell the truth about who cooked it or credit Ernesto.", "Return if the quest requests a final report."),
            reward = "Cook and deliver Fisherman’s Cauldron to Laudus.",
            warnings = "",
            searchTags = listOf("LATE-GAME REGIONAL SIDE QUESTS", "ARCHOLOS — LATE GAME", "All routes", "Canonical side quest"),
        ),
        Quest(
            id = "AR-C4-016",
            chapter = 4,
            playOrder = 16,
            title = "Bruised Face Theatre",
            category = "SIDE QUEST — All routes",
            giver = "Bodyguard",
            location = "Archolos Old Town",
            prerequisites = "Route: All routes",
            summary = "Stage a fake attack so the Bodyguard can prove his usefulness.",
            walkthroughSteps = listOf("Speak with the Bodyguard in Old Town.", "Return to the agreed street corner at midnight.", "Threaten the Old Man as planned.", "Allow the Bodyguard to beat/knock you down instead of fighting back.", "Wait until the following midnight and collect the reward."),
            reward = "The staged attack convinces the employer.",
            warnings = "",
            searchTags = listOf("LATE-GAME REGIONAL SIDE QUESTS", "ARCHOLOS — LATE GAME", "All routes", "Canonical side quest"),
        ),
        Quest(
            id = "AR-C4-017",
            chapter = 4,
            playOrder = 17,
            title = "Unhappy Husband",
            category = "SIDE QUEST — All routes",
            giver = "Barnaba, outside Dark Mysteries",
            location = "Archolos",
            prerequisites = "Route: All routes",
            summary = "Help Barnaba after feeding him and hearing his story.",
            walkthroughSteps = listOf("Speak with Barnaba and give him the requested meal and beer.", "Talk again once he is willing to explain the problem.", "Pay/accept the 100-gold arrangement and follow the lead concerning his wife.", "Investigate the named people/location and return with the truth."),
            reward = "Help Barnaba after feeding him and hearing his story.",
            warnings = "",
            searchTags = listOf("LATE-GAME REGIONAL SIDE QUESTS", "ARCHOLOS — LATE GAME", "All routes", "Canonical side quest"),
        ),
        Quest(
            id = "AR-C4-018",
            chapter = 4,
            playOrder = 18,
            title = "The Culprit",
            category = "SIDE QUEST — All routes",
            giver = "Valerio’s Vineyard",
            location = "Valerio’s Vineyard",
            prerequisites = "Route: All routes",
            summary = "Investigate who is responsible for the vineyard problem.",
            walkthroughSteps = listOf("Speak with the vineyard workers and owner.", "Inspect the damaged/stolen area and question everyone involved.", "Follow the physical clue or witness statement to the culprit.", "Confront the responsible person and choose the resolution.", "Report back to the vineyard."),
            reward = "Investigate who is responsible for the vineyard problem.",
            warnings = "",
            searchTags = listOf("LATE-GAME REGIONAL SIDE QUESTS", "VALERIO’S VINEYARD", "All routes", "Canonical side quest"),
        ),
        Quest(
            id = "AR-C4-019",
            chapter = 4,
            playOrder = 19,
            title = "Treasures Of Archolos",
            category = "SIDE QUEST — All routes",
            giver = "Valerio’s Vineyard contact",
            location = "Valerio’s Vineyard / world",
            prerequisites = "Route: All routes",
            summary = "Follow the treasure clues connected to Valerio’s estate.",
            walkthroughSteps = listOf("Obtain/read the first map or clue.", "Follow each landmark in sequence and dig/search where the clue indicates.", "Keep all intermediate notes/maps instead of selling them.", "Return/report after the final cache is recovered."),
            reward = "Follow the treasure clues connected to Valerio’s estate.",
            warnings = "",
            searchTags = listOf("LATE-GAME REGIONAL SIDE QUESTS", "VALERIO’S VINEYARD", "All routes", "Canonical side quest"),
        ),
        Quest(
            id = "AR-C4-020",
            chapter = 4,
            playOrder = 20,
            title = "Not To Be Lifted",
            category = "SIDE QUEST — All routes",
            giver = "Lucas",
            location = "Wolf’s Den",
            prerequisites = "Route: All routes",
            summary = "Find out what happened to the missing elevator crew.",
            walkthroughSteps = listOf("Speak with Lucas after entering the fortress.", "Follow the path outside the walls toward the planned elevator site.", "Kill the Dragon Snapper on the route and read the Bloody Note it carries.", "Continue following the evidence to the workers’ fate.", "Return to Lucas with the conclusion."),
            reward = "Lucas learns why the elevator project failed.",
            warnings = "",
            searchTags = listOf("LATE-GAME REGIONAL SIDE QUESTS", "WOLF’S DEN — LATE", "All routes", "Canonical side quest"),
        ),
        Quest(
            id = "AR-C4-021",
            chapter = 4,
            playOrder = 21,
            title = "Breakthrough Discovery",
            category = "SIDE QUEST — All routes",
            giver = "Yezegan",
            location = "Wolf's Den / Scoundrels' Haven",
            prerequisites = "Route: All routes",
            summary = "Test Yezegan's three transformation potions on Spirit, Ripper and Dan; save the Strong Potion for Dan, then track and kill him after the experiment goes wrong.",
            walkthroughSteps = listOf("Speak with Yezegan and take the three Transformation Potions. Make a safety save before handing any of them out.", "Travel to Scoundrels' Haven. Give either the weak or regular potion to Spirit: provoke and beat him, then pretend to offer a healing potion.", "Join Ripper on his swamp expedition. After he has fought a few creatures, give him the other weak/regular potion.", "Save the Strong Transformation Potion for Dan. Give it to him when he talks to you; he transforms and runs into the swamp.", "Track Dan to the cave on the western edge of the swamp. Help him survive the local danger if necessary, then listen to his plea for help.", "Return to Yezegan. He claims the transformation should wear off and gives you recovery rewards.", "Go back to Dan's cave. His condition has worsened and he is now a snapper; kill him.", "Loot the Pirate Armor left behind, then return to Yezegan for the final report."),
            reward = "Yezegan rewards you with permanent-stat elixirs and the experiment chain ends.",
            warnings = "",
            searchTags = listOf("LATE-GAME REGIONAL SIDE QUESTS", "WOLF’S DEN — LATE", "All routes", "Canonical side quest"),
        ),
        Quest(
            id = "AR-C4-022",
            chapter = 4,
            playOrder = 22,
            title = "New Liquors",
            category = "SIDE QUEST — All routes",
            giver = "Dirk",
            location = "Wolf’s Den Inn",
            prerequisites = "Route: All routes",
            summary = "Find an alcohol Dirk actually likes, negotiate a Dark Paladine supply deal and report it to Tomas.",
            walkthroughSteps = listOf("Offer Dirk different alcohols for small XP until it becomes clear he wants something special.", "Ask Helga in Siren’s Wail for advice, then visit Tomas at the Dark Paladine Brewery and buy one Dark Paladine.", "Give the Dark Paladine to Dirk. When he asks for crates, negotiate the 150-gold-per-case option for the best long-term payout.", "Return to Tomas and report the new Wolf’s Den customer and negotiated price."),
            reward = "Tomas begins supplying Dirk; the 150-gold deal grants the best immediate and weekly reward.",
            warnings = "",
            searchTags = listOf("LATE-GAME REGIONAL SIDE QUESTS", "WOLF’S DEN — LATE", "All routes", "Canonical side quest"),
        ),
        Quest(
            id = "AR-C4-023",
            chapter = 4,
            playOrder = 23,
            title = "Decision Time",
            category = "SIDE QUEST — All routes",
            giver = "Loria",
            location = "Wolf’s Den inn",
            prerequisites = "Route: All routes",
            summary = "Bet on Kylid or Devir and help your chosen fighter win.",
            walkthroughSteps = listOf("Speak with Loria and choose which fighter to back.", "Talk to your chosen fighter and complete the available preparation/sabotage that gives him an edge.", "Watch or participate in the arranged fight.", "Collect your winnings from Loria if your fighter wins.", "Speak with the winner for the extra stat-elixir reward."),
            reward = "Kylid rewards Dexterity; Devir rewards Strength if your chosen fighter wins.",
            warnings = "",
            searchTags = listOf("LATE-GAME REGIONAL SIDE QUESTS", "WOLF’S DEN — LATE", "All routes", "Canonical side quest"),
        ),
        Quest(
            id = "AR-C4-024",
            chapter = 4,
            playOrder = 24,
            title = "The Beast Of Archolos",
            category = "SIDE QUEST — All routes",
            giver = "Ramsey, Wolf’s Den hall",
            location = "Wolf’s Den / island",
            prerequisites = "Route: All routes",
            summary = "Track and uncover the truth about the Beast of Archolos.",
            walkthroughSteps = listOf("Take the hunt after Ulryk allows you to meet Jon.", "Follow Ramsey/Den clues to the attack sites and question the hunters involved.", "Inspect tracks/corpses and follow the trail instead of simply hunting random beasts.", "Use the later evidence around the north-west beach/cage and Old Town connections to identify what is really happening.", "Return through the quest’s final confrontation and report."),
            reward = "Track and uncover the truth about the Beast of Archolos.",
            warnings = "This is a multi-stage mystery; avoid killing or dismissing named hunters until their dialogue is exhausted.",
            searchTags = listOf("LATE-GAME REGIONAL SIDE QUESTS", "WOLF’S DEN — LATE", "All routes", "Canonical side quest"),
        ),
        Quest(
            id = "AR-C4-025",
            chapter = 4,
            playOrder = 25,
            title = "Silver And Steel",
            category = "SIDE QUEST — All routes",
            giver = "Einar",
            location = "Wolf’s Den smithy",
            prerequisites = "Route: All routes",
            summary = "Help Einar complete his wolf-head alloy work.",
            walkthroughSteps = listOf("Speak with Einar and complete his preliminary smithing/material request.", "Perform the bear-skin step when instructed and cut out the required material.", "Take Einar’s key and open his chest in the first smithy room.", "Take the mold and return it to him.", "Wait through the crafting dialogue and collect the armor-upgrade offer."),
            reward = "Einar offers one free upgrade to a non-upgraded armor piece.",
            warnings = "",
            searchTags = listOf("LATE-GAME REGIONAL SIDE QUESTS", "WOLF’S DEN — LATE", "All routes", "Canonical side quest"),
        ),
        Quest(
            id = "AR-C4-026",
            chapter = 4,
            playOrder = 26,
            title = "Wolf Skins",
            category = "SIDE QUEST — All routes",
            giver = "Baes",
            location = "Wolf’s Den",
            prerequisites = "Route: All routes",
            summary = "Bring Baes the wolf pelts he wants.",
            walkthroughSteps = listOf("Take the quest from Baes if he still trusts you.", "Buy pelts from Lucy outside the fortress or hunt wolves/black wolves yourself.", "Bring the required skins back to Baes.", "Resolve the payment/dialogue before starting Night Sentry if you want maximum options."),
            reward = "Bring Baes the wolf pelts he wants.",
            warnings = "Baes may refuse the quest depending on choices in The Only Way To Jon / Night Sentry.",
            searchTags = listOf("LATE-GAME REGIONAL SIDE QUESTS", "WOLF’S DEN — LATE", "All routes", "Canonical side quest"),
        ),
        Quest(
            id = "AR-C4-027",
            chapter = 4,
            playOrder = 27,
            title = "Night Sentry",
            category = "SIDE QUEST — All routes",
            giver = "Arethe",
            location = "Wolf’s Den walls",
            prerequisites = "Route: All routes",
            summary = "Complete a night patrol and light the wall torches.",
            walkthroughSteps = listOf("Start after about 20:00 and meet Arethe on the high wall.", "Walk to the far patrol point, return to Arethe’s position, then walk back to the target point.", "Light all four torches along the wall with a handheld torch.", "Handle the patrol event that follows and report back."),
            reward = "Night watch completes.",
            warnings = "Do Wolf Skins first if you want maximum freedom in how to handle Baes.",
            searchTags = listOf("LATE-GAME REGIONAL SIDE QUESTS", "WOLF’S DEN — LATE", "All routes", "Canonical side quest"),
        ),
        Quest(
            id = "AR-C4-028",
            chapter = 4,
            playOrder = 28,
            title = "An Unforgettable Lesson",
            category = "SIDE QUEST — All routes",
            giver = "Berter",
            location = "Scoundrels’ Haven pier",
            prerequisites = "Chapter 4; complete Molerats Might Fly in Chapter 3, then speak with Berter on the Haven dock.",
            summary = "Help Berter fire the cannon at Saul’s hut, then decide whether to report him.",
            walkthroughSteps = listOf("This appears in Chapter 4 only if Molerats Might Fly was completed. Meet Berter at the pier while he is pushing the cannon.", "Before moving on, collect the four cannonballs around the pier and make sure you have a torch.", "Push/interact with the cannon, then load/use the cannonballs and torch as Berter instructs.", "Fire at Saul’s hut; go inside afterward, inspect Saul’s body and take any useful loot.", "Return to Berter and choose whether to keep quiet or report him; Rodrigo then asks what happened."),
            reward = "Saul's Sailor's Belt from his body; the outcome and Berter's extra items depend on whether you conceal his role in the fatal cannon prank.",
            warnings = "This ends in Saul's DEATH. Bring four cannonballs and a torch, then decide whether to expose Berter. If Molerats Might Fly was skipped, the follow-up never appears.",
            searchTags = listOf("LATE-GAME REGIONAL SIDE QUESTS", "SCOUNDRELS’ HAVEN — CHAPTER 4", "All routes", "Canonical side quest"),
        ),
    )
}
