package com.sliverzfx.gothicquest

internal object ArcholosChapter3Part1Data {
    val quests: List<Quest> = listOf(
        Quest(
            id = "AR-C3-001",
            chapter = 3,
            playOrder = 1,
            title = "Amongst The Villains (Part I)",
            category = "MAIN STORY — All routes",
            giver = "Automatic chapter transition; Thiago and Cortez advance the quest",
            location = "Archolos → Scoundrels’ Haven",
            prerequisites = "Chapter 3; finish the faction-specific route into Scoundrels' Haven in Chapter 2.",
            summary = "Follow your guild-specific lead until you gain access to the Scoundrels’ Haven.",
            walkthroughSteps = listOf("Enter Scoundrels' Haven at the start of Chapter 3. Talk to THIAGO at the entrance before visiting Cortez, otherwise his hut encounter can fail to advance.", "City Guard characters should also speak with Slasher before Cortez to hear the lead toward Big Ben.", "Go upstairs into Cortez's hut, hear him out and accept the faction-specific test: Who Killed Stan? for City Guard or Blood Money for Araxos.", "Complete your guild test and follow the emerging leads toward Big Ben and Jorn's disappearance."),
            reward = "The Scoundrels’ Haven becomes a full quest hub.",
            warnings = "IMPORTANT: speak with Thiago (and Slasher for City Guard) BEFORE Cortez. Unlike some NPC warnings, you can still leave Scoundrels' Haven before the tournament by swimming or teleporting.",
            searchTags = listOf("CHAPTER 3 — AMONG THE SCOUNDRELS", "", "All routes", "Canonical quest"),
        ),
        Quest(
            id = "AR-C3-002",
            chapter = 3,
            playOrder = 2,
            title = "Who Killed Stan? (City Guard)",
            category = "MAIN STORY — City Guard",
            giver = "Cortez / Oscar",
            location = "Scoundrels’ Haven",
            prerequisites = "Route: City Guard",
            summary = "Investigate Stan’s murder and determine who is responsible.",
            walkthroughSteps = listOf("After Cortez assigns the investigation, visit Oscar's inn, examine Stan's body and pick up Stan's Dish.", "Question Oscar, Rosita and Tara. Bring the contaminated dish to alchemist Hierro; ask Cortez to let him use the alchemy table and learn that it contains wolfberries.", "Confront Rodrigo and his bodyguard Simon, then search Rodrigo's hut DIRECTLY BELOW Cortez's hut for the chest. Pickpocket Rodrigo's key or pick its lock; take Rodrigo's diary and Strange Powder.", "Show the powder to Hierro, who identifies Dragon's Dust; read the diary carefully.", "Return to Cortez ONLY when the evidence is complete and accuse Rodrigo to finish the City Guard test."),
            reward = "2,000 XP after accusing Rodrigo with sufficient evidence, plus progression of the main Scoundrels' Haven quest.",
            warnings = "DANGER: asking Cortez about Stan before solving the case can get Marvin killed. The relevant hut is underneath Cortez, not the house Rodrigo stands near.",
            searchTags = listOf("CHAPTER 3 — AMONG THE SCOUNDRELS", "", "City Guard", "Canonical quest"),
        ),
        Quest(
            id = "AR-C3-003",
            chapter = 3,
            playOrder = 3,
            title = "Blood Money (Merchants’ Guild)",
            category = "MAIN STORY — Merchants’ Guild",
            giver = "Cortez / Coyote",
            location = "Scoundrels’ Haven",
            prerequisites = "Route: Merchants’ Guild",
            summary = "Trace the Strange Coin, set a trap for the attackers and survive the ambush.",
            walkthroughSteps = listOf("Show the Strange Coin/evidence to Coyote and exhaust his questions about the guards, their equipment and approximate numbers.", "Speak with Simon and Rodrigo for the local leads, then travel to Rita’s Vineyard and use the false-order route with Antonio/Gonzalo when the journal directs you there.", "Follow the suspects toward the northern bridge and decide whether to warn the target immediately or use the situation as bait; save before this choice.", "Return toward the cave/trap area, use a pickaxe where the journal indicates and gather the leaves/bush material required to disguise the trap.", "Set the ambush, defeat the attackers and return to Cortez/Coyote with the result."),
            reward = "The Araxos version of the Haven investigation advances.",
            warnings = "Do not rush the bridge choice; the warning-versus-bait decision changes how the encounter plays out.",
            searchTags = listOf("CHAPTER 3 — AMONG THE SCOUNDRELS", "", "Merchants’ Guild", "Canonical quest"),
        ),
        Quest(
            id = "AR-C3-004",
            chapter = 3,
            playOrder = 4,
            title = "Old Friends",
            category = "MAIN STORY — All routes",
            giver = "Automatic story event following the Haven investigation",
            location = "Coast / wreck site",
            prerequisites = "Route: All routes",
            summary = "Search the wreck, recover the important cargo and rescue surviving crew.",
            walkthroughSteps = listOf("Search the wreck and nearby shore systematically; read the ship manifest so the cargo objectives are added correctly.", "Recover the jewelry box, ore bag, decorated sword and weapon packages from the wreckage and underwater search areas.", "Find Harri, Herdis and Millie and exhaust their dialogue so each survivor is counted.", "Collect palm wood and craft the paddle when the escape/rescue route requires it.", "Return the recovered cargo and survivors to the quest’s report point before leaving the area."),
            reward = "Roughly 2,000–3,000 XP and Ring of Strength from Cortez depending on your decisions; killing Beckett after the report adds 500 XP. Preserving Javad can allow his later Vardhal recruitment.",
            warnings = "Saving/recruiting Javad changes a later tournament fight and the Vardhal roster. Search the wreck for the ship manifest, cargo, Bag of Ore and Decorated Sword before returning to Cortez.",
            searchTags = listOf("CHAPTER 3 — AMONG THE SCOUNDRELS", "", "All routes", "Canonical quest"),
        ),
        Quest(
            id = "AR-C3-005",
            chapter = 3,
            playOrder = 5,
            title = "The Tournament",
            category = "MAIN STORY — All routes",
            giver = "Proximo / arena",
            location = "Scoundrels’ Haven",
            prerequisites = "Chapter 3; complete Old Friends for Cortez. Prepare BEFORE entering the tournament arena.",
            summary = "Qualify for the arena tournament, prepare through the local fight quests, then win the tournament.",
            walkthroughSteps = listOf("Before registering, complete A Few Mugs To Beat and related Haven fights if possible; victories can reduce the entry fee.", "Speak with Proximo and pay/waive the entry cost.", "Fight each scheduled opponent, healing and saving between rounds.", "Use the arena boundaries carefully; ranged builds should create distance while melee builds punish recovery windows.", "Win the final round and collect the tournament reward before advancing the main Haven plot."),
            reward = "Tournament winnings scale with rounds completed; Proximo later gives 1,200 gold and the Pirate's Amulet during the celebration.",
            warnings = "MAJOR POINT OF NO RETURN: signing up to fight advances events elsewhere and can fail outstanding quests (including Boy's Farm). Complete A Few Mugs to Beat, Larry's Bag and Abducted first; if you leave the arena mid-tournament, you cannot reenter.",
            searchTags = listOf("CHAPTER 3 — AMONG THE SCOUNDRELS", "", "All routes", "Canonical quest"),
        ),
        Quest(
            id = "AR-C3-006",
            chapter = 3,
            playOrder = 6,
            title = "Amongst The Villains (Part II)",
            category = "MAIN STORY — All routes",
            giver = "Cortez / Big Ben",
            location = "Scoundrels’ Haven",
            prerequisites = "Route: All routes",
            summary = "Use your tournament victory to reach Big Ben, then realize you need another way to make him talk.",
            walkthroughSteps = listOf("After the tournament celebration, speak with the Haven NPCs and collect any reward/dialogue, especially from Proximo.", "Speak with Cortez, who warns that Big Ben may hold a grudge.", "Wait until Ben’s access is available; go behind Gregor and ask the sentry at the stairs to let you upstairs.", "Confront Big Ben and exhaust his dialogue. He refuses to provide the information you need.", "Return downstairs and speak with Oscar/Cortez as the poison/interrogation plan develops."),
            reward = "After the tournament Proximo provides 1,200 gold and the Pirate's Amulet, an excellent Dexterity/one-handed accessory; opens the Big Ben interrogation plan.",
            warnings = "The post-tournament celebration temporarily freezes time at 19:00 and blocks travel out of the Haven. Speak to Proximo for his reward and wait for Cortez to arrange Ben's upstairs access.",
            searchTags = listOf("CHAPTER 3 — AMONG THE SCOUNDRELS", "", "All routes", "Canonical quest"),
        ),
        Quest(
            id = "AR-C3-007",
            chapter = 3,
            playOrder = 7,
            title = "Loosening Tongues",
            category = "MAIN STORY — All routes",
            giver = "Cortez / Haven investigation",
            location = "Scoundrels’ Haven",
            prerequisites = "Route: All routes",
            summary = "Prepare the coercion mixture, deal with Big Ben and extract the needed information.",
            walkthroughSteps = listOf("Speak with Hierro to order poison and antidote for Big Ben. Bring two swampweed, one bloodfly stinger and four swampshark teeth.", "Specify poison strong enough for an ORC if you want both delivery choices; the troll-strength option only allows poisoning the barrel.", "Poison the beer barrel behind Gregor, OR pay Rosita to poison Ben's wine (150 gold if you frame it as wanting him removed, 300 gold for a break); advanced pickpocketing offers another method.", "Sleep or wait for the poisoning to take effect, then SAVE before talking to Ben. Discuss Jorn's kidnapping, showing Kurt's blue-stone ring for extra dialogue if you kept it.", "Choose whether to give Ben the antidote and spare him, preserving his later Vardhal recruitment, or kill him and loot Ben's Hammer.", "Leave the Haven and continue the main investigation in Archolos."),
            reward = "Information about Jorn and the Order to Kidnap Jorn; saving Ben preserves him as a recruit for A Job for Tough Guys, while killing him allows looting his unique two-handed hammer.",
            warnings = "Save before the final Ben dialogue: older builds can crash on the kill choice. Choosing ORC-strength poison preserves multiple delivery routes; a spared Big Ben may join Vardhal.",
            searchTags = listOf("CHAPTER 3 — AMONG THE SCOUNDRELS", "", "All routes", "Canonical quest"),
        ),
        Quest(
            id = "AR-C3-008",
            chapter = 3,
            playOrder = 8,
            title = "Amongst The Villains (Part III)",
            category = "MAIN STORY — All routes",
            giver = "Cortez",
            location = "Scoundrels’ Haven",
            prerequisites = "Route: All routes",
            summary = "Finish the Haven investigation after Loosening Tongues and bring the resulting lead back to your city faction.",
            walkthroughSteps = listOf("Complete Loosening Tongues and read every document/quest item obtained from the interrogation.", "Speak with Cortez and the relevant Haven contacts so all journal updates are exhausted.", "Follow the final lead out of the Haven, dealing with any ambush or evidence pickup on the return route.", "Return to Archolos and report to your faction contact rather than starting unrelated Chapter 3 cleanup first."),
            reward = "The Haven segment closes and Work Report / In Broad Daylight becomes the next main-story stage.",
            warnings = "",
            searchTags = listOf("CHAPTER 3 — AMONG THE SCOUNDRELS", "", "All routes", "Canonical quest"),
        ),
        Quest(
            id = "AR-C3-009",
            chapter = 3,
            playOrder = 9,
            title = "Work Report",
            category = "MAIN STORY — All routes",
            giver = "Guild superior",
            location = "Archolos",
            prerequisites = "Route: All routes",
            summary = "Report the Scoundrels’ Haven results to your City Guard or Merchants’ Guild superior.",
            walkthroughSteps = listOf("Leave Scoundrels' Haven after speaking with Ivy and return to Archolos to report your mission.", "Fast-travel INTO Archolos is disabled by the city's state of emergency, so travel near the gates and enter ON FOOT.", "Report to your guild leader to learn of the assassination attempt on Volker and the refugee crisis.", "Follow the new investigation into In Broad Daylight. Fast-travel access into the city is restored later."),
            reward = "The Haven assignment is formally closed and the city investigation resumes.",
            warnings = "Do not assume the Archolos teleport is broken: fast-travel into the city is deliberately disabled by the Chapter 3 emergency. The gates remain usable on foot.",
            searchTags = listOf("CHAPTER 3 — AMONG THE SCOUNDRELS", "", "All routes", "Canonical quest"),
        ),
        Quest(
            id = "AR-C3-010",
            chapter = 3,
            playOrder = 10,
            title = "In Broad Daylight (Part I)",
            category = "MAIN STORY — All routes",
            giver = "Main investigation",
            location = "Archolos",
            prerequisites = "Route: All routes",
            summary = "Investigate the Leaflet, Bolthead and Prisoner leads before committing to a conclusion.",
            walkthroughSteps = listOf("Read the quest journal carefully and work all three available leads in parallel.", "For the Leaflet lead, trace the printed material through the people/workshops connected to its production.", "For the Bolthead lead, inspect the weapon/projectile evidence and question the craftsmen who can identify it.", "For the Prisoner lead, visit the relevant prisoner/guard contacts and extract the information needed for the case.", "Return to the investigation hub only after all useful evidence has been collected."),
            reward = "All three leads converge into In Broad Daylight (Part II).",
            warnings = "Do not rush the accusation; incomplete leads can cost dialogue, XP or alternate outcomes.",
            searchTags = listOf("CHAPTER 3 — AMONG THE SCOUNDRELS", "", "All routes", "Canonical quest"),
        ),
        Quest(
            id = "AR-C3-011",
            chapter = 3,
            playOrder = 11,
            title = "In Broad Daylight (Leaflet Lead)",
            category = "MAIN STORY — All routes",
            giver = "Main investigation",
            location = "Archolos",
            prerequisites = "Route: All routes",
            summary = "Trace the suspicious leaflet to the person who produced it.",
            walkthroughSteps = listOf("Take/read the leaflet so the printing clue is active.", "Go to the Three Sailors area and locate Venzel in the writing/printing workshop.", "Show Venzel the leaflet and question him about who commissioned or handled the work.", "Take the silver coin/evidence he provides and let the journal update before leaving.", "Return to the main investigation once the Leaflet lead is marked complete."),
            reward = "The Leaflet branch of In Broad Daylight is complete.",
            warnings = "",
            searchTags = listOf("CHAPTER 3 — AMONG THE SCOUNDRELS", "", "All routes", "Canonical quest"),
        ),
        Quest(
            id = "AR-C3-012",
            chapter = 3,
            playOrder = 12,
            title = "In Broad Daylight (Bolthead Lead)",
            category = "MAIN STORY — All routes",
            giver = "Main investigation",
            location = "Archolos cemetery",
            prerequisites = "Route: All routes",
            summary = "Exhume Norman and inspect the evidence connected to the bolthead.",
            walkthroughSteps = listOf("Bring a Shovel before starting the cemetery step.", "Go to the indicated grave at night so you can work without unnecessary attention.", "Dig up Norman’s grave and inspect the body/items for the bolthead evidence.", "Take every quest-marked item and let the journal update.", "Return to the investigation hub after the Bolthead lead is marked complete."),
            reward = "The Bolthead branch is complete.",
            warnings = "A shovel is mandatory; arriving without one wastes the night window.",
            searchTags = listOf("CHAPTER 3 — AMONG THE SCOUNDRELS", "", "All routes", "Canonical quest"),
        ),
        Quest(
            id = "AR-C3-013",
            chapter = 3,
            playOrder = 13,
            title = "In Broad Daylight (Prisoner Lead)",
            category = "MAIN STORY — All routes",
            giver = "Main investigation / Osip",
            location = "Archolos prison / harbour",
            prerequisites = "Route: All routes",
            summary = "Use Osip to reach the prisoner and follow the lead to the hidden harbour house.",
            walkthroughSteps = listOf("Speak with Osip and give him the solution/information he asks for so he can manipulate the prison access.", "Let Osip distract or trick Guido and use the opening to speak with the prisoner.", "Follow the new lead out of the prison toward the harbour.", "Locate the mysterious house opposite the Slums/harbour side and investigate it thoroughly.", "Return once the journal confirms the Prisoner lead has converged with the other evidence."),
            reward = "The Prisoner branch is complete and Part II can proceed.",
            warnings = "",
            searchTags = listOf("CHAPTER 3 — AMONG THE SCOUNDRELS", "", "All routes", "Canonical quest"),
        ),
        Quest(
            id = "AR-C3-014",
            chapter = 3,
            playOrder = 14,
            title = "In Broad Daylight (Part II)",
            category = "MAIN STORY — All routes",
            giver = "Main investigation",
            location = "Archolos / Old Town",
            prerequisites = "Route: All routes",
            summary = "Finish the Leaflet, Bolthead and Prisoner leads, meet Ivy, then report to your guild leader and present the evidence at the Old Town hearing.",
            walkthroughSteps = listOf("Make sure the three investigation branches are finished: the agitation leaflet trail, the Spiked Bolt trail, and the Ars/Osip prisoner trail.", "Meet Ivy again. Depending on which lead you completed last, she can be outside the shipyard, the Three Sailors Writing Workshop, or near the Merchants' Guild entrance.", "If you followed Osip's information to the mysterious Harbour house, finish that sequence first: confront Blake upstairs and decide whether to protect him or fight him.", "Return to your guild leader. He takes you to the judge in Old Town for the formal hearing.", "Present the investigation results. You can reveal Venzel's role in printing the leaflets or protect him; the hearing still reaches a verdict on Ars.", "Let the hearing conclude. Marvin is recognized as an honorary citizen of Old Town, opening the district permanently."),
            reward = "5,000 XP on completing the tribunal, honorary Old Town citizenship and permanent access to the district; outcome of the accusation affects later character dialogue.",
            warnings = "Choosing whether to expose Venzel can send Ervalt to prison instead. Finish all three evidence leads before the hearing; the verdict proceeds regardless of the Venzel choice.",
            searchTags = listOf("CHAPTER 3 — AMONG THE SCOUNDRELS", "", "All routes", "Canonical quest"),
        ),
        Quest(
            id = "AR-C3-015",
            chapter = 3,
            playOrder = 15,
            title = "Silver Lining (Part I)",
            category = "MAIN STORY — All routes",
            giver = "Ivy / Volker",
            location = "Archolos → Wolf's Den",
            prerequisites = "Route: All routes",
            summary = "Meet Ivy outside after the hearing, then report to Volker upstairs in his mansion; he sends Marvin to Wolf's Den, ending Chapter 3.",
            walkthroughSteps = listOf("Finish any remaining Chapter 3 side quests, shopping and training before continuing. Advancing this quest ends the chapter.", "Leave the hearing area and meet Ivy outside. The final sentence from the In Broad Daylight case is carried out during this sequence.", "Ivy then leaves for Volker's mansion. Go there and find her upstairs in Volker's office.", "Speak with Ivy first if you want her newly available training options.", "Talk to Volker. He gives you travel money and orders you to go to Ulryk's fortress, the Wolf's Den.", "Finish the conversation and allow the chapter transition to trigger."),
            reward = "800 or 1,000 gold from Volker depending on the prior hearing choice; advances the story into Chapter 4 and opens free/cheap Pick Locks instruction from Ivy.",
            warnings = "CHAPTER TRANSITION: speaking with Volker to finish Silver Lining advances the story. Ivy can teach Pick Locks for 0 LP before departure; close outstanding Chapter 3 quests first.",
            searchTags = listOf("CHAPTER 3 — AMONG THE SCOUNDRELS", "", "All routes", "Canonical quest"),
        ),
        Quest(
            id = "AR-C3-016",
            chapter = 3,
            playOrder = 16,
            title = "Food Shortages",
            category = "FACTION QUEST — City Guard",
            giver = "Lennart (City Guard quartermaster)",
            location = "Archolos",
            prerequisites = "Chapter 3; City Guard route; Lennart summons Marvin to investigate missing food from Bermar's Farm.",
            summary = "Find five missing City Guard food packets after wild animals overrun the road east of Bermar's Farm.",
            walkthroughSteps = listOf("A Guard summons you to Lennart at the City Guard barracks. Ask about the missing supply squad.", "Visit Bermar's Farm and question Bermar; follow the eastern road toward the wounded City Guard.", "Give the wounded guard a healing potion for help, then search the road and nearby woods for the FIVE food packets.", "Four are around the roadside attack; one is by the dangerous shadowbeast down the route toward Sailor's Retreat. The fifth is farther north, toward the Haunted Cemetery, on another corpse.", "Collect all five and return to Lennart. A journal update after fewer packets does not guarantee the turn-in dialogue will appear."),
            reward = "1,250 XP and 250 gold from Lennart for recovering the full supplies.",
            warnings = "ALL FIVE packets are necessary even though the journal can update after only three. A dangerous shadowbeast patrols one packet location; the wounded guard can offer fast travel if healed.",
            searchTags = listOf("CHAPTER 3 — CITY GUARD", "", "City Guard", "Canonical quest"),
        ),
        Quest(
            id = "AR-C3-017",
            chapter = 3,
            playOrder = 17,
            title = "A Few Nuggets (Winstan)",
            category = "FACTION QUEST — City Guard",
            giver = "Winstan",
            location = "Archolos Slums",
            prerequisites = "Route: City Guard",
            summary = "Collect four suspicious ore nuggets and bring them to Winstan.",
            walkthroughSteps = listOf("Speak with Winstan and accept the request before selling any stray ore nuggets.", "Find the suspicious thug near Dorran’s blacksmith area in the Slums and deal with him.", "Search him and the nearby quest locations until you have all 4 required nuggets.", "Keep the nuggets separate from crafting/selling stock and return directly to Winstan.", "Choose the follow-up training/progression dialogue only after saving if you are comparing Guard specializations."),
            reward = "Winstan receives the four nuggets.",
            warnings = "This branch interacts with the New Techniques / Providence specialization choice.",
            searchTags = listOf("CHAPTER 3 — CITY GUARD", "", "City Guard", "Canonical quest"),
        ),
        Quest(
            id = "AR-C3-018",
            chapter = 3,
            playOrder = 18,
            title = "New Techniques (Winstan, Swordsman's Unit)",
            category = "FACTION QUEST — City Guard",
            giver = "Winstan",
            location = "City Guard barracks / field assignment",
            prerequisites = "Route: City Guard",
            summary = "Join Winstan’s swordsman unit after A Few Nuggets and complete his advanced combat assignment.",
            walkthroughSteps = listOf("Finish A Few Nuggets and return to Winstan with the ore-nugget result.", "Have at least 40% in one-handed or two-handed weapons, then accept Winstan’s offer to join the swordsman unit.", "Buy/equip the stronger Guard Swordsman armour Lennart recommends before leaving on the field assignment.", "Follow Winstan’s journal directions to the target combat area, stay with the squad and clear the hostile group in the order they engage.", "Return to Winstan once the journal marks the field objective complete."),
            reward = "The swordsman-unit training/assignment is completed and Winstan’s branch advances.",
            warnings = "Choosing this unit blocks Weigar’s Providence From Above route.",
            searchTags = listOf("CHAPTER 3 — CITY GUARD", "", "City Guard", "Canonical quest"),
        ),
        Quest(
            id = "AR-C3-019",
            chapter = 3,
            playOrder = 19,
            title = "Providence From Above (Weigar, Crossbowmen’s Unit)",
            category = "FACTION QUEST — City Guard",
            giver = "Weigar",
            location = "Archolos City Guard",
            prerequisites = "Route: City Guard",
            summary = "Complete Weigar’s crossbowmen assignment and commit to that specialization.",
            walkthroughSteps = listOf("Make sure Sambor has returned to the Guard before attempting this assignment.", "Speak with Weigar and accept the Crossbowmen’s Unit route.", "Follow the journal to the elevated/ambush position and resolve the target encounter using ranged support.", "Collect any quest evidence from the scene and return to Weigar.", "Confirm the specialization only after saving if you are comparing it with New Techniques."),
            reward = "The Crossbowmen’s Unit progression advances.",
            warnings = "New Techniques and Providence are specialization alternatives; do not expect to complete both on one branch.",
            searchTags = listOf("CHAPTER 3 — CITY GUARD", "", "City Guard", "Canonical quest"),
        ),
        Quest(
            id = "AR-C3-020",
            chapter = 3,
            playOrder = 20,
            title = "Who Is Who (Part I)",
            category = "FACTION QUEST — Merchants’ Guild",
            giver = "Lorenzo",
            location = "Araxos Gold Mine",
            prerequisites = "Route: Merchants’ Guild",
            summary = "Work undercover in the gold mine and learn which miners are loyal, frightened or plotting against Araxos.",
            walkthroughSteps = listOf("Take several Pickaxes before travelling to the Araxos Gold Mine; tools can break during the heavy mining work.", "Report as a worker and speak with the miners/foremen before choosing sides. Complete their small work requests and use mining opportunities to raise Extraction.", "Explore the normally restricted section once the relevant guard/worker route allows it. A miner eventually approaches and leads you toward the secret meeting near the area where Naars was previously found.", "Attend the meeting and survive the confrontation when the miners’ true intentions are exposed.", "Keep any letters/evidence and return toward the mine leadership only after the journal updates."),
            reward = "Marvin identifies the key factions inside the mine and the investigation advances to Part II.",
            warnings = "",
            searchTags = listOf("CHAPTER 3 — MERCHANTS’ GUILD", "", "Merchants’ Guild", "Canonical quest"),
        ),
        Quest(
            id = "AR-C3-021",
            chapter = 3,
            playOrder = 21,
            title = "A Golden Deal",
            category = "FACTION QUEST — Merchants’ Guild",
            giver = "Araxos / Lorenzo",
            location = "Gold mine",
            prerequisites = "Route: Merchants’ Guild",
            summary = "Go undercover at the gold mine, secure the deal/evidence and return to Lorenzo.",
            walkthroughSteps = listOf("Speak with Lorenzo and accept the undercover assignment; keep Araxos clothing/dialogue options available.", "Travel to the mine and use the contract/work cover rather than starting a fight at the entrance.", "Work through the mine contacts until you identify the extraction/deal Lorenzo wants exposed.", "Collect the contract, ore or other quest evidence named by the journal and leave without losing it.", "Return to Lorenzo and give a full report."),
            reward = "The undercover operation is complete and the Araxos Chapter 3 route advances.",
            warnings = "",
            searchTags = listOf("CHAPTER 3 — MERCHANTS’ GUILD", "", "Merchants’ Guild", "Canonical quest"),
        ),
        Quest(
            id = "AR-C3-022",
            chapter = 3,
            playOrder = 22,
            title = "Who Is Who (Part II)",
            category = "FACTION QUEST — Merchants’ Guild",
            giver = "Lorenzo / mine leadership",
            location = "Araxos Gold Mine → Archolos",
            prerequisites = "Route: Merchants’ Guild",
            summary = "Resolve the mine conspiracy, decide what to do with the involved miners and report the result to Lorenzo.",
            walkthroughSteps = listOf("Continue from the secret-meeting confrontation and search defeated NPCs/containers for evidence.", "Question the surviving miners and foreman about Naars, Loafs and the internal plot.", "Make the required decision about the conspirators rather than leaving the mine with unresolved dialogue.", "Finish any mining/training you want before reporting because the mine state changes after the conclusion.", "Return to Lorenzo with the complete report."),
            reward = "Lorenzo closes the mine investigation and the Merchants’ Guild Chapter 3 route continues.",
            warnings = "",
            searchTags = listOf("CHAPTER 3 — MERCHANTS’ GUILD", "", "Merchants’ Guild", "Canonical quest"),
        ),
        Quest(
            id = "AR-C3-023",
            chapter = 3,
            playOrder = 23,
            title = "New Orders (Garos)",
            category = "FACTION QUEST — Merchants’ Guild",
            giver = "Garos",
            location = "Araxos / island routes",
            prerequisites = "Route: Merchants’ Guild",
            summary = "Complete the Tracker-guideline checks at Silbach, Rita’s Vineyard and the Amber Coast.",
            walkthroughSteps = listOf("Read the Tracker guidelines Garos gives you before leaving so all inspection objectives register.", "Travel south of Silbach and check on Gerke; inspect the nearby scavenger corpses and resolve the local problem.", "Go to Rita’s Vineyard and investigate the burned hut; kill the 3 Skeleton Warriors there and inspect the site.", "Travel to the Amber Coast and deal with the young seasharks at the marked location.", "Do any extra-credit kills the journal allows, then return to Garos with the completed report."),
            reward = "Garos accepts the field report and the Tracker route advances.",
            warnings = "",
            searchTags = listOf("CHAPTER 3 — MERCHANTS’ GUILD", "", "Merchants’ Guild", "Canonical quest"),
        ),
        Quest(
            id = "AR-C3-024",
            chapter = 3,
            playOrder = 24,
            title = "Dealing With Recon (Garos, Trackers’ Unit)",
            category = "FACTION QUEST — Merchants’ Guild",
            giver = "Garos",
            location = "Archolos / east gate",
            prerequisites = "Route: Merchants’ Guild",
            summary = "Secure both scouting routes and expose the hostile reconnaissance team.",
            walkthroughSteps = listOf("Take the mission from Garos and inspect the high road first, checking all four evidence spots named by the journal.", "Clear the rocky tunnel near the east gate by killing the Bear and 4 Giant Rats.", "Before approaching Ernesto or other suspicious contacts, remove obvious Araxos armor if the walkthrough/journal warns it will expose you.", "Follow the Suspicious Guy without losing him until he reaches the shipyard meeting.", "Defeat the hostile leader, loot the Plan/document and return it to Garos."),
            reward = "The reconnaissance threat is exposed and the Trackers’ Unit route advances.",
            warnings = "Save before tailing the Suspicious Guy; getting too close can spoil the follow sequence.",
            searchTags = listOf("CHAPTER 3 — MERCHANTS’ GUILD", "", "Merchants’ Guild", "Canonical quest"),
        ),
        Quest(
            id = "AR-C3-025",
            chapter = 3,
            playOrder = 25,
            title = "It's Not Yours (Adelard)",
            category = "FACTION QUEST — Merchants’ Guild",
            giver = "Adelard / Solis",
            location = "Archolos Harbour / Slums",
            prerequisites = "Route: Merchants’ Guild",
            summary = "Recover all ten stolen beer barrels for Helga and report the thieves’ route.",
            walkthroughSteps = listOf("After Eyes On The West, speak with Adelard, then go to the basement door behind Siren’s Wail and talk to Solis.", "Collect the two barrels in the sewers opposite the basement after clearing the alligators.", "Climb to the roof north of Siren’s Wail for two more; collect the barrel near Marvin’s harbour bed/house and the two beside the broken western crane.", "Collect the barrel behind the shop south of the Harbour, the one in the narrow gap near the Slums blacksmith, and the final barrel behind the eastern Harbour buildings / under the Golden Gate area as marked by the route.", "Taste each barrel for maximum reward if desired, then “take” it so it counts.", "Return all ten to Solis and report to Helga/Adelard."),
            reward = "Helga’s beer is recovered and Adelard’s swordsman route becomes available.",
            warnings = "Collecting/tasting all ten produces the best reward.",
            searchTags = listOf("CHAPTER 3 — MERCHANTS’ GUILD", "", "Merchants’ Guild", "Canonical quest"),
        ),
        Quest(
            id = "AR-C3-026",
            chapter = 3,
            playOrder = 26,
            title = "They Shall Not Pass (Adelard, Swordsman's Unit)",
            category = "FACTION QUEST — Merchants’ Guild",
            giver = "Adelard / Griz",
            location = "Silbach north road",
            prerequisites = "Route: Merchants’ Guild",
            summary = "Escort Griz’s group, clear the road and survive the Shadowbeast attack.",
            walkthroughSteps = listOf("Meet Griz and the two farmers/guards at Silbach’s north gate after accepting Adelard’s route.", "Escort them north and clear every hostile group on the road instead of sprinting ahead.", "At the stone arch/camp area, light the campfire when the journal prompts you.", "Follow the blood trail back toward the threatened group and prepare for a Shadowbeast fight.", "Kill the Shadowbeast while protecting Griz, then report the result to Adelard."),
            reward = "The Swordsman’s Unit assignment is complete.",
            warnings = "Griz can die; save before the Shadowbeast encounter if you want the best outcome.",
            searchTags = listOf("CHAPTER 3 — MERCHANTS’ GUILD", "", "Merchants’ Guild", "Canonical quest"),
        ),
        Quest(
            id = "AR-C3-027",
            chapter = 3,
            playOrder = 27,
            title = "The Legendary Recipe (Odgar)",
            category = "APPRENTICESHIP — All routes",
            giver = "Odgar",
            location = "Archolos → Amber Coast",
            prerequisites = "Route: All routes",
            summary = "Recover the lost weapon diagram from the dead hunter.",
            walkthroughSteps = listOf("Take the Chapter 3 request from Odgar.", "Go to the Amber Coast and ask Duncan about the trader/hunter who was chasing trolls.", "Climb the cliffs above the city toward the troll family until the journal updates.", "Return down toward the beach and find the fallen hunter’s corpse.", "Loot the special diagram and return to Odgar.", "Tell the truth to keep the diagram, or claim the hunter wanted 1000 gold to scam Odgar but lose the diagram."),
            reward = "Odgar’s special-recipe quest closes; reward depends on your honesty.",
            warnings = "",
            searchTags = listOf("CHAPTER 2 — APPRENTICESHIPS", "", "All routes", "Canonical quest"),
        ),
        Quest(
            id = "AR-C3-028",
            chapter = 3,
            playOrder = 28,
            title = "The Merchants' War (Frida)",
            category = "APPRENTICESHIP — Merchants’ Guild",
            giver = "Frida",
            location = "Archolos Harbour",
            prerequisites = "Route: Merchants’ Guild",
            summary = "Recover the deed Alice obtained for Frida’s shop.",
            walkthroughSteps = listOf("Take the Chapter 3 quest from Frida after completing Work For A Bowyer.", "Confront Alice; she refuses to surrender the deed.", "Return at night and sneak into Alice’s bedroom.", "Search all four hiding places even though they initially come up empty.", "Follow the resulting clue/encounter until the Deed is recovered.", "Return the Deed to Frida."),
            reward = "Frida keeps her shop and rewards you.",
            warnings = "",
            searchTags = listOf("CHAPTER 2 — APPRENTICESHIPS", "", "Merchants’ Guild", "Canonical quest"),
        ),
        Quest(
            id = "AR-C3-029",
            chapter = 3,
            playOrder = 29,
            title = "Cheap Guards",
            category = "SIDE QUEST — All routes",
            giver = "Lewko",
            location = "Royal Mine",
            prerequisites = "Route: All routes",
            summary = "Kill the four stone golems in the lower tunnels.",
            walkthroughSteps = listOf("Read the security notice in Archolos or simply visit the Royal Mine in Chapter 3.", "Speak with foreman Lewko.", "Enter the lower tunnels and kill all four Stone Golems.", "Return to Lewko."),
            reward = "Mining resumes; Lewko pays gold and gives an Awaken Golem scroll.",
            warnings = "",
            searchTags = listOf("REGIONAL SIDE QUESTS — CHAPTERS 1–3", "ROYAL MINE", "All routes", "Canonical side quest"),
        ),
        Quest(
            id = "AR-C3-030",
            chapter = 3,
            playOrder = 30,
            title = "Every Little Bit Helps",
            category = "SIDE QUEST — All routes",
            giver = "Malen",
            location = "Royal Mine",
            prerequisites = "Route: All routes",
            summary = "Find missing miners Ogis and Reez, expose what happened and help restore order at the mine.",
            walkthroughSteps = listOf("Speak with Malen at the rockface, then question Lewko about Ogis and Reez.", "Talk with Refir, Neral and Elvart; Refir gives part of the key and the others provide the search leads.", "Find Ogis’ corpse near the green crystals and take the Miner’s Shoe/key fragment evidence.", "Deal with the attacker/guard connected to the disappearance and return the key fragments to Malen so he can repair the key.", "At about 3 a.m., use the repaired key on the target chest and take Lewko’s incriminating letter/evidence.", "Bring the evidence to Roderich and finish the follow-up so the surviving miners are safe."),
            reward = "The mine corruption/missing-miner case is resolved; Refir and Neral can later be recruited for Vardhal.",
            warnings = "",
            searchTags = listOf("REGIONAL SIDE QUESTS — CHAPTERS 1–3", "ROYAL MINE", "All routes", "Canonical side quest"),
        ),
    )
}
