package com.sliverzfx.gothicquest

internal object ArcholosChapter3Part2Data {
    val quests: List<Quest> = listOf(
        Quest(
            id = "AR-C3-031",
            chapter = 3,
            playOrder = 31,
            title = "Buried Treasures",
            category = "SIDE QUEST — All routes",
            giver = "Moritz",
            location = "Scoundrels’ Haven / world map",
            prerequisites = "Route: All routes",
            summary = "Follow Moritz through several failed treasure digs.",
            walkthroughSteps = listOf("Bring a pickaxe and speak with Moritz.", "Meet him at the lake south-west of Rita’s Vineyard and dig all three spots near the large rock.", "Meet him again beside the river north of Silbach and dig the three spots by the tree.", "Continue following each new clue/location he gives you until the treasure-hunt chain resolves.", "Return to Moritz after the final dig."),
            reward = "The multi-location treasure hunt concludes.",
            warnings = "Bring a PICKAXE before following Moritz. Every site has three dig spots, and the later steps only appear after reporting the unsuccessful digs.",
            searchTags = listOf("REGIONAL SIDE QUESTS — CHAPTERS 1–3", "SCOUNDRELS’ HAVEN", "All routes", "Canonical side quest"),
        ),
        Quest(
            id = "AR-C3-032",
            chapter = 3,
            playOrder = 32,
            title = "Molerats Might Fly",
            category = "SIDE QUEST — All routes",
            giver = "Saul",
            location = "Scoundrels’ Haven",
            prerequisites = "Route: All routes",
            summary = "Help Saul prank Berter by putting an acceptable ingredient into Berter’s pea soup.",
            walkthroughSteps = listOf("Speak with Saul and show him the prank ingredients you have.", "Use peppercorns, a pearl or another ingredient Saul explicitly approves.", "Enter the hut beside Saul and interact with the soup cauldron to add the ingredient.", "Return to Saul after the soup has been tampered with."),
            reward = "600 XP and five bottles of rum from Saul for sabotaging Berter's pea soup; unlocks the Chapter 4 An Unforgettable Lesson quest.",
            warnings = "Complete this in Chapter 3 if you want Berter's Chapter 4 cannon prank quest. Pepper or a pearl can be used on his soup.",
            searchTags = listOf("REGIONAL SIDE QUESTS — CHAPTERS 1–3", "SCOUNDRELS’ HAVEN", "All routes", "Canonical side quest"),
        ),
        Quest(
            id = "AR-C3-033",
            chapter = 3,
            playOrder = 33,
            title = "Larry's Bag",
            category = "SIDE QUEST — All routes",
            giver = "Larry",
            location = "Scoundrels’ Haven",
            prerequisites = "Route: All routes",
            summary = "Recover Larry’s gold bag from Ripper and return it.",
            walkthroughSteps = listOf("Speak with Larry outside the Inn and hear how Ripper took his bag.", "Find Ripper and demand Larry’s property back.", "If Ripper has not already been beaten, defeat him in the duel; otherwise he may surrender the bag immediately.", "Take Larry’s Bag back to Larry rather than keeping it."),
            reward = "600 XP and 20 gold if you return Larry's purse honestly. Keeping the purse instead fails the quest.",
            warnings = "Give Larry his purse BACK before challenging him as an opponent in A Few Mugs to Beat; beating him later can yield the money anyway.",
            searchTags = listOf("REGIONAL SIDE QUESTS — CHAPTERS 1–3", "SCOUNDRELS’ HAVEN", "All routes", "Canonical side quest"),
        ),
        Quest(
            id = "AR-C3-034",
            chapter = 3,
            playOrder = 34,
            title = "Sting",
            category = "SIDE QUEST — All routes",
            giver = "Oscar",
            location = "Scoundrels’ Haven",
            prerequisites = "Chapter 3; complete Who Killed Stan? or Blood Money, then ask Oscar about collecting a swamp bloodfly sting.",
            summary = "Kill the target insect/creature and bring Oscar its sting.",
            walkthroughSteps = listOf("Take the job from Oscar.", "Travel to the marked hunting area.", "Kill the target and loot the Sting.", "Return to Oscar."),
            reward = "Kill the target insect/creature and bring Oscar its sting.",
            warnings = "Thiago can teach sting extraction; the target is a SWAMP bloodfly in the Southern Marshes, not a common bloodfly.",
            searchTags = listOf("REGIONAL SIDE QUESTS — CHAPTERS 1–3", "SCOUNDRELS’ HAVEN", "All routes", "Canonical side quest"),
        ),
        Quest(
            id = "AR-C3-035",
            chapter = 3,
            playOrder = 35,
            title = "Escape",
            category = "SIDE QUEST — All routes",
            giver = "Homer",
            location = "Scoundrels’ Haven arena cave",
            prerequisites = "Route: All routes",
            summary = "Help Homer with his escape plan.",
            walkthroughSteps = listOf("Find Homer inside the arena cave.", "Listen to the plan and gather/perform the requested preparation.", "Move through the Haven carefully so the escape is not exposed prematurely.", "Return to Homer or escort him as the journal directs."),
            reward = "1,000 XP from Homer after he is jailed, plus recovery of the loaned teleport rune and a Pirate Ring from Logar; as a merchant the follow-up can cost 150 gold.",
            warnings = "BLUFF Dinkel rather than fighting him; a fight fails the quest. Homer needs a city teleport rune, which he returns through Logar after his capture.",
            searchTags = listOf("REGIONAL SIDE QUESTS — CHAPTERS 1–3", "SCOUNDRELS’ HAVEN", "All routes", "Canonical side quest"),
        ),
        Quest(
            id = "AR-C3-036",
            chapter = 3,
            playOrder = 36,
            title = "A Few Mugs To Beat",
            category = "SIDE QUEST — All routes",
            giver = "Oscar / arena crowd",
            location = "Scoundrels’ Haven",
            prerequisites = "Route: All routes",
            summary = "Beat the listed Haven fighters before entering the Tournament.",
            walkthroughSteps = listOf("Start the bar/arena fighting challenge before registering with Proximo.", "Fight the listed opponents one at a time; save between bouts.", "Do Ripper after also starting Larry’s Bag so one knockout can advance both quests.", "Fight Morty before Abducted can remove him, and Larry after finishing Larry’s Bag.", "Fight Rodrigo last if needed; he requires a gold-ring wager.", "Report your victories to Oscar, then register with Proximo."),
            reward = "500 XP when registering with Proximo after winning the local fights, plus a tournament entry-fee reduction that can reach zero.",
            warnings = "Finish Larry's Bag before knocking down Larry. Fight Ripper, Morty, Larry, Rodrigo, Vicente and Dan BEFORE tournament registration; beating everyone can waive the fee.",
            searchTags = listOf("REGIONAL SIDE QUESTS — CHAPTERS 1–3", "SCOUNDRELS’ HAVEN", "All routes", "Canonical side quest"),
        ),
    )
}
