package com.sliverzfx.gothicquest

internal object ArcholosChapter2Part2Data {
    val quests: List<Quest> = listOf(
        Quest(
            id = "AR-C2-031",
            chapter = 2,
            playOrder = 31,
            title = "The Troublesome Three (Helga)",
            category = "FACTION QUEST — Merchants’ Guild",
            giver = "Helga, Siren’s Wail",
            location = "Archolos",
            prerequisites = "Route: Merchants’ Guild",
            summary = "Remove Helga’s three unwanted drinkers without getting yourself blacked out.",
            walkthroughSteps = listOf("Ask Helga at the Siren's Wail Inn to deal with Arnold, Tom and Mikkel.", "Buy a bottle of Black Troll from Helga for 50 gold. Either insult the thugs to fight all three, or offer them Black Troll while YOU drink three other alcoholic drinks.", "On the drinking route, repeatedly give the thugs Black Troll and drink your own weaker alcohol without blacking out. After three rounds they leave for the Slums.", "Return to Helga for the reward and her Merchants' Guild endorsement."),
            reward = "750 XP, 100 gold and Helga's guild-approval vote; fighting the thugs grants an additional 30 gold. The Black Troll costs 50 gold.",
            warnings = "Do not drink Black Troll yourself: passing out on the pier FAILS the quest. The trick route requires at least three other alcoholic drinks.",
            searchTags = listOf("CHAPTER 2 — MERCHANTS’ GUILD ROUTE", "", "Merchants’ Guild", "Canonical quest"),
        ),
        Quest(
            id = "AR-C2-032",
            chapter = 2,
            playOrder = 32,
            title = "This Fish Doesn't Stink (Armar)",
            category = "FACTION QUEST — Merchants’ Guild",
            giver = "Armar",
            location = "Archolos Harbour / western beach",
            prerequisites = "Route: Merchants’ Guild",
            summary = "Convince fisherman Liman to supply Araxos and repair his net.",
            walkthroughSteps = listOf("Accept Armar's proposal at his Archolos stall and travel west to Liman at Sailor's Retreat.", "Liman asks you to find the missing fisherman and fishing net. Swim east of the bay, defeat two lurkers and loot the fisherman's corpse for the destroyed fishnet.", "Find Balni in the cave at the western end of the beach. Pay gold or fish for repairs, or carefully complete his three-part persuasion dialogue.", "Bring the repaired net back to Liman; ask about the Araxos fish agreement and report the arrangement to Armar."),
            reward = "Armar's approval toward Merchants' Guild membership and the additional quest payment; exact amount depends on dialogue and route.",
            warnings = "Balni can refuse further repairs after a bad persuasion answer. Save before trying to bluff him or be prepared to pay for the repair.",
            searchTags = listOf("CHAPTER 2 — MERCHANTS’ GUILD ROUTE", "", "Merchants’ Guild", "Canonical quest"),
        ),
        Quest(
            id = "AR-C2-033",
            chapter = 2,
            playOrder = 33,
            title = "Weed Him Out (Ernesto)",
            category = "FACTION QUEST — Merchants’ Guild",
            giver = "Ernesto",
            location = "Archolos",
            prerequisites = "Route: Merchants’ Guild",
            summary = "Find Kaf, beat him and survive the brothers’ ambush.",
            walkthroughSteps = listOf("Accept Ernesto’s Guild-approval job.", "Track Kaf to the indicated upstairs room where he is found wearing only a towel.", "Beat Kaf in the initial fight and follow him when he leads you across town.", "Prepare for the three-on-one ambush by drawing the group toward guards or using ranged attacks.", "Defeat Kaf and his brothers, then return to Ernesto."),
            reward = "Ernesto supports your membership and pays the extra reward.",
            warnings = "May be unavailable if For Connoisseurs already ruined Ernesto’s business.",
            searchTags = listOf("CHAPTER 2 — MERCHANTS’ GUILD ROUTE", "", "Merchants’ Guild", "Canonical quest"),
        ),
        Quest(
            id = "AR-C2-034",
            chapter = 2,
            playOrder = 34,
            title = "Unfair Competition",
            category = "FACTION QUEST — Merchants’ Guild",
            giver = "Lorenzo / Caramon",
            location = "Archolos Harbour → Amber Coast",
            prerequisites = "Route: Merchants’ Guild",
            summary = "Investigate the human-trafficking smugglers with Caramon and trace their operation to the Amber Coast.",
            walkthroughSteps = listOf("Make an archive save before accepting the quest; wear neutral clothes instead of Araxos Runner gear and meet Caramon.", "Follow Caramon to Siren’s Wail. Question the drunk fishermen until they name Finbar, then pay Helga for smuggler information and say the smugglers may be linked to your brother’s disappearance.", "Search the crane/pier area for the Unsent Letter and follow the blood/rubbish trail toward the Dark Mysteries brothel. Pay the guard 50 gold to inspect Finbar’s corpse, then read the letter found on him.", "Go to the warehouse beneath the In Exile bowyer workshop, pick the lock and defeat Pablo plus the smugglers. Spare Pablo and follow him to Caramon on the beach.", "Win the four-thug ambush, then sail with Caramon and Pablo to Amber Coast. Question the fishing village; talk to at least one villager before confronting the green-shirt fisherman so he runs to your companions.", "Interrogate him about the smugglers’ cave and finish the Amber Coast investigation."),
            reward = "The smuggling lead is exposed and the route into The One Who Comes And Goes opens.",
            warnings = "This quest is notoriously bug-prone. Save before Helga, Finbar and the warehouse stages and use the specified dialogue choices.",
            searchTags = listOf("CHAPTER 2 — MERCHANTS’ GUILD ROUTE", "", "Merchants’ Guild", "Canonical quest"),
        ),
        Quest(
            id = "AR-C2-035",
            chapter = 2,
            playOrder = 35,
            title = "The One Who Comes And Goes",
            category = "FACTION QUEST — Merchants’ Guild",
            giver = "Lorenzo / Willem",
            location = "Bermar’s Farm → Sailor’s Retreat → Southern Marshes",
            prerequisites = "Route: Merchants’ Guild",
            summary = "Trace Hod’s death and use Yannick to reach the Southern Marshes.",
            walkthroughSteps = listOf("Speak with Willem at Bermar’s Farm and search the north-west woods ravine for Hod’s corpse.", "Optionally clear the Orc Scout in the far cliff cave before returning; this can affect later events.", "Report to Willem and say you are looking for Jorn; he sends you to Yannick at Sailor’s Retreat with a passcode.", "Find Yannick behind his hut after speaking with Liman/Zachary and ask who he wants removed.", "Resolve the guard problem around his boat by the available dialogue/combat route.", "Return to Yannick and explicitly choose “Let’s go!” so he rows you to the Southern Marshes."),
            reward = "The Araxos story reaches the Southern Marshes and its next investigation stage.",
            warnings = "Leaving for the Southern Marshes with Yannick progresses the main plot toward Scoundrels' Haven and Chapter 3. Finish chapter-specific city and mine activities first.",
            searchTags = listOf("CHAPTER 2 — MERCHANTS’ GUILD ROUTE", "", "Merchants’ Guild", "Canonical quest"),
        ),
        Quest(
            id = "AR-C2-036",
            chapter = 2,
            playOrder = 36,
            title = "Night Watch",
            category = "FACTION QUEST — Merchants’ Guild",
            giver = "Otmar",
            location = "Archolos Harbour / Slums",
            prerequisites = "Route: Merchants’ Guild",
            summary = "Unload illegal cargo from the Avenal and escort it to the warehouse.",
            walkthroughSteps = listOf("After accepting Unfair Competition, speak with Otmar outside the Guild HQ.", "Go to the Harbour at night and meet Fulko and his assistant at the Avenal.", "Pick up both cargo chests on deck; the others take their own.", "Follow them into the Slums warehouse and deposit your chests in the large corner chest.", "Stay with the smugglers through the complication that follows, then return to Lorenzo when sent."),
            reward = "1,500 XP and 400 gold from Lorenzo for completing the Avenal night unloading and reporting the smuggling complication.",
            warnings = "Hostile Slums NPCs can freeze Fulko's route. Clear dangerous enemies before starting, place BOTH carried chests into the warehouse's larger chest, and return for the second load.",
            searchTags = listOf("CHAPTER 2 — MERCHANTS’ GUILD ROUTE", "", "Merchants’ Guild", "Canonical quest"),
        ),
        Quest(
            id = "AR-C2-037",
            chapter = 2,
            playOrder = 37,
            title = "Eyes On The West",
            category = "FACTION QUEST — Merchants’ Guild",
            giver = "Lorenzo / Adelard",
            location = "Archolos → road to Bermar’s Farm",
            prerequisites = "Route: Merchants’ Guild",
            summary = "Recruit hunter Darthe for Araxos.",
            walkthroughSteps = listOf("Ask Lorenzo about promotion and receive Adelard’s recruitment job.", "Find Darthe at his camp on the road between Archolos and Bermar’s Farm.", "Make the Guild offer and follow his requested proof/errand.", "When you return, Darthe has moved west and is fighting boars; help immediately so he does not die.", "Speak with him after the fight, then report to Adelard."),
            reward = "Darthe joins Araxos and you receive the promotion credit.",
            warnings = "Darthe is vulnerable to the boars and can die before the recruitment dialogue. Reach him quickly and help fight instead of leaving the battle unattended.",
            searchTags = listOf("CHAPTER 2 — MERCHANTS’ GUILD ROUTE", "", "Merchants’ Guild", "Canonical quest"),
        ),
        Quest(
            id = "AR-C2-038",
            chapter = 2,
            playOrder = 38,
            title = "Working With Ramha",
            category = "FACTION QUEST — Merchants’ Guild",
            giver = "Lorenzo → Garos → Ramha",
            location = "Araxos mine road",
            prerequisites = "Route: Merchants’ Guild",
            summary = "Escort Ramha to the rock-root site and save her after the experiment.",
            walkthroughSteps = listOf("Ask Lorenzo for promotion work, then speak with Garos outside the Guild HQ.", "Visit Ramha at Sister’s Cauldron and agree to help.", "Meet Ramha and Figaro on the road east of the Araxos Gold Mine.", "Escort Ramha to the special rock root.", "Defend her against scavengers, wolves and finally a bear.", "When Ramha collapses after smelling the root, run back to Figaro and bring the required help/remedy."),
            reward = "Ramha survives and the promotion assignment is completed.",
            warnings = "",
            searchTags = listOf("CHAPTER 2 — MERCHANTS’ GUILD ROUTE", "", "Merchants’ Guild", "Canonical quest"),
        ),
        Quest(
            id = "AR-C2-039",
            chapter = 2,
            playOrder = 39,
            title = "Work For A Carpenter (Davis)",
            category = "APPRENTICESHIP — All routes",
            giver = "Davis",
            location = "From The Life Of A Thief workshop / Harbour",
            prerequisites = "Route: All routes",
            summary = "Rob Davis’ competitor warehouse, empty the three target chests and steal the locksmith tools.",
            walkthroughSteps = listOf("Speak with Davis and show that you have at least Beginner Pick Locks; accept his apprenticeship test and take the lockpicks.", "Go to the competing warehouse in the Harbour, preferably at night to reduce witnesses.", "Open and loot all three target chests, taking the three Chest Purchase Certificates.", "Search the workshop/warehouse for the Locksmith Tool Kit and take it as well.", "Return to Davis with the certificates and tools and discuss becoming his apprentice."),
            reward = "Davis accepts the proof of skill and his apprenticeship becomes available.",
            warnings = "You need Beginner Pick Locks; save before trespassing because being seen can provoke guards/workers.",
            searchTags = listOf("CHAPTER 2 — APPRENTICESHIPS", "", "All routes", "Canonical quest"),
        ),
        Quest(
            id = "AR-C2-040",
            chapter = 2,
            playOrder = 40,
            title = "Work For An Alchemist (Hershlik)",
            category = "APPRENTICESHIP — All routes",
            giver = "Hershlik",
            location = "Archolos alchemist / nearby habitats",
            prerequisites = "Route: All routes",
            summary = "Extract seeds from four plant groups and plant them in Hershlik’s three garden plots.",
            walkthroughSteps = listOf("Speak with Hershlik and demonstrate basic Alchemy so he offers the test.", "Learn/use Extract Seeds and obtain two seed samples from each requested plant group: knotweed near scavengers, healing plants around rats, fire nettles around molerats and blue elder near bloodflies.", "Return to Hershlik with the seed collection and follow him behind the shop.", "Interact with the three planting plots and plant the required seed sets.", "Speak with Hershlik once the garden work is complete."),
            reward = "Hershlik accepts Marvin as a viable apprentice and his apprenticeship option remains open.",
            warnings = "",
            searchTags = listOf("CHAPTER 2 — APPRENTICESHIPS", "", "All routes", "Canonical quest"),
        ),
        Quest(
            id = "AR-C2-041",
            chapter = 2,
            playOrder = 41,
            title = "Work For A Butcher (Slager)",
            category = "APPRENTICESHIP — All routes",
            giver = "Slager, Slaughterhouse",
            location = "Archolos",
            prerequisites = "Route: All routes",
            summary = "Bring Slager 10 raw boar meat, 5 raw sheep meat and 2 crab pincers.",
            walkthroughSteps = listOf("Collect 10 raw boar meat; boars west of the Royal Mine are a reliable source.", "Buy/gather 5 raw sheep meat from food traders such as Bastian/Remy.", "Buy or loot 2 raw crab pincers; fried pincers do not count.", "Give Slager the boar meat FIRST, then the other ingredients.", "Accept the apprenticeship only if this is the master you want."),
            reward = "Slager offers apprenticeship and useful meat/seed-related training.",
            warnings = "Hand in raw boar meat first; leaving it until last can break the dialogue.",
            searchTags = listOf("CHAPTER 2 — APPRENTICESHIPS", "", "All routes", "Canonical quest"),
        ),
        Quest(
            id = "AR-C2-042",
            chapter = 2,
            playOrder = 42,
            title = "Work For A Blacksmith (Odgar)",
            category = "APPRENTICESHIP — All routes",
            giver = "Odgar",
            location = "Archolos",
            prerequisites = "Route: All routes",
            summary = "Impress Odgar with magic ore or a forged Shiv.",
            walkthroughSteps = listOf("Tell Odgar you have an idea for proving yourself.", "Easy route: give him one piece of magic ore.", "Smith route: if you know beginner forging, take the Shiv diagram and gather 2 iron nuggets, 3 quartz and 1 sheep skin.", "Use the forge fire, then the anvil, to create the Shiv and hand it to Odgar.", "Choose whether to sign the apprenticeship contract."),
            reward = "Odgar accepts you and can teach all forging levels.",
            warnings = "",
            searchTags = listOf("CHAPTER 2 — APPRENTICESHIPS", "", "All routes", "Canonical quest"),
        ),
        Quest(
            id = "AR-C2-043",
            chapter = 2,
            playOrder = 43,
            title = "Work For A Bowyer (Frida)",
            category = "APPRENTICESHIP — All routes",
            giver = "Frida",
            location = "Archolos Harbour",
            prerequisites = "Route: All routes",
            summary = "Release Alice’s caged harpy and return to Frida.",
            walkthroughSteps = listOf("Speak with Frida about apprenticeship and her rival Alice.", "Visit the Traveller variety shop in the Harbour and buy anything you want before sabotaging it.", "Get behind Alice’s counter and use the switch that opens the harpy cage.", "Kill the harpy if needed; Alice becomes hostile/angry regardless.", "Return to Frida and decide whether to become her apprentice."),
            reward = "Frida approves you and can teach Bowmaking.",
            warnings = "Afterward Alice can demand 200 gold before allowing you to shop normally again.",
            searchTags = listOf("CHAPTER 2 — APPRENTICESHIPS", "", "All routes", "Canonical quest"),
        ),
        Quest(
            id = "AR-C2-044",
            chapter = 2,
            playOrder = 44,
            title = "Cleaning The Shore",
            category = "SIDE QUEST — All routes",
            giver = "Carden",
            location = "Silbach river / Lurker Coast",
            prerequisites = "Route: All routes",
            summary = "Destroy all five lurker nests along the flooded western shoreline and report to Carden.",
            walkthroughSteps = listOf("Speak with Carden after Chapter 2 begins.", "Travel to the west-river shoreline; destroy the first three nest pairs along the near bank.", "Continue toward the shipwreck beach for the fourth nest.", "Push past the sea-lurker section to locate and destroy the fifth nest.", "Use the nearby cave/return route and report to Carden."),
            reward = "All five nests are gone and Carden rewards the cleanup.",
            warnings = "Only the nests are mandatory; you can bypass some monsters if under-levelled.",
            searchTags = listOf("REGIONAL SIDE QUESTS — CHAPTERS 1–3", "SILBACH & LURKER’S COAST", "All routes", "Canonical side quest"),
        ),
        Quest(
            id = "AR-C2-045",
            chapter = 2,
            playOrder = 45,
            title = "Hot Sands",
            category = "SIDE QUEST — All routes",
            giver = "Duncan",
            location = "Amber Coast",
            prerequisites = "Route: All routes",
            summary = "Recover Duncan’s Robust Net and optionally kill the fire lizards later.",
            walkthroughSteps = listOf("Speak with Duncan.", "Run along the beach to the net guarded by fire lizards.", "Use speed/Snapperweed if under-levelled; grab the net and retreat.", "Return to Duncan.", "In Chapter 5, kill all four fire lizards and report for bonus XP."),
            reward = "Duncan gets his net.",
            warnings = "",
            searchTags = listOf("REGIONAL SIDE QUESTS — CHAPTERS 1–3", "AMBER COAST / ARAXOS", "All routes", "Canonical side quest"),
        ),
        Quest(
            id = "AR-C2-046",
            chapter = 2,
            playOrder = 46,
            title = "Bear Trouble",
            category = "SIDE QUEST — All routes",
            giver = "Beekeepers’ Camp",
            location = "Araxos region",
            prerequisites = "Route: All routes",
            summary = "Kill or drive off the bear threatening the beekeepers.",
            walkthroughSteps = listOf("Speak with the beekeeper/foreman about the attacks.", "Follow the path from the camp toward the bear’s feeding area.", "Kill the bear, using trees/terrain to break charges if necessary.", "Return to the camp."),
            reward = "Kill or drive off the bear threatening the beekeepers.",
            warnings = "",
            searchTags = listOf("REGIONAL SIDE QUESTS — CHAPTERS 1–3", "AMBER COAST / ARAXOS", "All routes", "Canonical side quest"),
        ),
        Quest(
            id = "AR-C2-047",
            chapter = 2,
            playOrder = 47,
            title = "That Special Kind Of Honey",
            category = "SIDE QUEST — All routes",
            giver = "Beekeepers’ Camp",
            location = "Araxos region",
            prerequisites = "Route: All routes",
            summary = "Obtain the special honey requested by the camp.",
            walkthroughSteps = listOf("Ask the beekeepers about their unusual honey.", "Gather the required ingredients/comb from the nearby hives and hostile area.", "Return the materials to the beekeeper.", "Collect the special-honey reward/product."),
            reward = "Obtain the special honey requested by the camp.",
            warnings = "",
            searchTags = listOf("REGIONAL SIDE QUESTS — CHAPTERS 1–3", "AMBER COAST / ARAXOS", "All routes", "Canonical side quest"),
        ),
        Quest(
            id = "AR-C2-048",
            chapter = 2,
            playOrder = 48,
            title = "A Reluctant Student",
            category = "SIDE QUEST — All routes",
            giver = "Bermar",
            location = "Bermar’s Farm",
            prerequisites = "Route: All routes",
            summary = "Find a suitable occupation for Bermar’s son Kyle.",
            walkthroughSteps = listOf("Talk to Bermar, then speak with Kyle while he is sawing planks outside.", "Discuss the possible trades/adventures with Kyle.", "Try the available work options such as potion brewing, fishing or hunting.", "Return to Bermar after Kyle settles on a direction."),
            reward = "Kyle’s future is decided and Bermar rewards you.",
            warnings = "",
            searchTags = listOf("REGIONAL SIDE QUESTS — CHAPTERS 1–3", "BERMAR’S FARM", "All routes", "Canonical side quest"),
        ),
        Quest(
            id = "AR-C2-049",
            chapter = 2,
            playOrder = 49,
            title = "A Seaside Find",
            category = "SIDE QUEST — All routes",
            giver = "Willem",
            location = "Bermar’s Farm beach",
            prerequisites = "Route: All routes",
            summary = "Clear the beach, collect fish and investigate Vrazka’s corpse.",
            walkthroughSteps = listOf("Speak with Willem and go down to the nearby beach.", "Clear the crabs while moving from north to south and pick up the fish along the shore.", "Continue until you reach Vrazka’s body.", "Search the body and surrounding trail, then return to Willem."),
            reward = "The beach is cleared and Vrazka’s fate is discovered.",
            warnings = "",
            searchTags = listOf("REGIONAL SIDE QUESTS — CHAPTERS 1–3", "BERMAR’S FARM", "All routes", "Canonical side quest"),
        ),
        Quest(
            id = "AR-C2-050",
            chapter = 2,
            playOrder = 50,
            title = "Destroyed Crops",
            category = "SIDE QUEST — All routes",
            giver = "Willem",
            location = "Bermar’s Farm",
            prerequisites = "Route: All routes",
            summary = "Poison the rat holes damaging the fields.",
            walkthroughSteps = listOf("Complete A Seaside Find and ask Willem for more work.", "Read the Rat Poison recipe he gives you.", "Use the alchemy bench in the hut behind the farmhouse to prepare 5 Rat Poisons.", "Visit the large field and apply poison to each rat hole.", "Return to Willem."),
            reward = "The crop problem is stopped.",
            warnings = "",
            searchTags = listOf("REGIONAL SIDE QUESTS — CHAPTERS 1–3", "BERMAR’S FARM", "All routes", "Canonical side quest"),
        ),
        Quest(
            id = "AR-C2-051",
            chapter = 2,
            playOrder = 51,
            title = "Razor Sharp",
            category = "SIDE QUEST — All routes",
            giver = "Helmud",
            location = "Charcoal Burners’ Camp",
            prerequisites = "Route: All routes",
            summary = "Kill the snappers west of the camp.",
            walkthroughSteps = listOf("Speak with Helmud and take the snapper job.", "Go west/down the slope toward the river and cave.", "Target the loose rock above the first group and shoot it to crush some of the snappers, or fight them normally.", "Clear the cave/remaining snappers and return to Helmud."),
            reward = "The camp is safe from the snappers.",
            warnings = "Much easier in Chapter 2; it can also help with To The Town (Knut).",
            searchTags = listOf("REGIONAL SIDE QUESTS — CHAPTERS 1–3", "CHARCOAL / WOODCUTTERS", "All routes", "Canonical side quest"),
        ),
        Quest(
            id = "AR-C2-052",
            chapter = 2,
            playOrder = 52,
            title = "Howls In The Night",
            category = "SIDE QUEST — All routes",
            giver = "Detlow",
            location = "Woodcutters / shrine",
            prerequisites = "Route: All routes",
            summary = "Join Detlow’s midnight wolf hunt.",
            walkthroughSteps = listOf("Take the quest and sleep until midnight.", "Meet Detlow at the shrine on the hill.", "Follow him and kill the first wolf pack.", "Continue downhill past the haunted house and kill the second pack.", "Speak with Detlow after the hunt."),
            reward = "The night hunt ends and later Beast-related clues become possible.",
            warnings = "",
            searchTags = listOf("REGIONAL SIDE QUESTS — CHAPTERS 1–3", "CHARCOAL / WOODCUTTERS", "All routes", "Canonical side quest"),
        ),
        Quest(
            id = "AR-C2-053",
            chapter = 2,
            playOrder = 53,
            title = "There Will Be No Peace",
            category = "SIDE QUEST — All routes",
            giver = "Haunted chapel clue",
            location = "Woodcutters / Vardhal overlook",
            prerequisites = "Route: All routes",
            summary = "Follow the confession pages to their final clue.",
            walkthroughSteps = listOf("Investigate the haunted chapel and locate the first confession clue.", "Shoot/interact with the head/fixture at the chapel front to reveal the route to Page II.", "Read Page II and travel toward Vardhal as instructed.", "Climb the ruined wall before the bridge and go up the tower stairs.", "Read Page III at the lookout and follow the final objective."),
            reward = "The confession mystery is resolved.",
            warnings = "",
            searchTags = listOf("REGIONAL SIDE QUESTS — CHAPTERS 1–3", "CHARCOAL / WOODCUTTERS", "All routes", "Canonical side quest"),
        ),
        Quest(
            id = "AR-C2-054",
            chapter = 2,
            playOrder = 54,
            title = "Eternal Rest",
            category = "SIDE QUEST — All routes",
            giver = "Fane",
            location = "Misty Marshes",
            prerequisites = "Route: All routes",
            summary = "Help the talking skeleton Fane finally die.",
            walkthroughSteps = listOf("Find Fane in the open grave on the west edge of the marshes.", "Speak with him; normal weapons will not solve his problem.", "Acquire a suitable Destroy Evil/holy magic solution later in the game (Candac/Monastery routes can provide one).", "Return to Fane and use the required magic/dialogue resolution."),
            reward = "Fane is released from undeath.",
            warnings = "This quest is intentionally long-term; you may not be able to finish it when first found.",
            searchTags = listOf("REGIONAL SIDE QUESTS — CHAPTERS 1–3", "MISTY MARSHES", "All routes", "Canonical side quest"),
        ),
        Quest(
            id = "AR-C2-055",
            chapter = 2,
            playOrder = 55,
            title = "Clean Streets",
            category = "SIDE QUEST — All routes",
            giver = "Matey, Final Decision Office",
            location = "Archolos",
            prerequisites = "Route: All routes",
            summary = "Sweep all nine dirt piles in the city.",
            walkthroughSteps = listOf("Take the broom from Matey.", "Sweep three piles on Main Street (two by the Writing Workshop and one beneath the hostel).", "Sweep three in the Artisans District (two by the Slaughterhouse and one by the Pawn Shop).", "Sweep three in the Marketplace (Bakery, Tailor, Bowyer).", "Return to Matey."),
            reward = "Matey pays per pile and waives the citizenship fee if this is used for Citizen Marvin.",
            warnings = "",
            searchTags = listOf("REGIONAL SIDE QUESTS — CHAPTERS 1–3", "ARCHOLOS CITY", "All routes", "Canonical side quest"),
        ),
        Quest(
            id = "AR-C2-056",
            chapter = 2,
            playOrder = 56,
            title = "Gold Rush",
            category = "SIDE QUEST — All routes",
            giver = "Kurt",
            location = "Archolos / Valerio’s Vineyard",
            prerequisites = "Route: All routes",
            summary = "Collect Volker’s debt from Holdwig and investigate why the vineyard owner is poisoned.",
            walkthroughSteps = listOf("After receiving Kurt’s message, meet him on the top-floor balcony of Siren’s Wail, then travel to Valerio’s Vineyard.", "Speak with Holdwig and investigate his illness through either Gumbert’s kitchen/pantry route or Terry’s lead.", "If using the pantry route, enter at night, inspect the three suspicious wines and drink/test the correct evidence, then speak with Dennis and Holdwig.", "Once Holdwig is able to settle the debt, collect the Payment.", "Return to Kurt before his story state changes later in the chapter."),
            reward = "Kurt receives the payment and the debt quest closes.",
            warnings = "Time-sensitive: complete it before Kurt disappears from this stage of the story.",
            searchTags = listOf("REGIONAL SIDE QUESTS — CHAPTERS 1–3", "ARCHOLOS CITY", "All routes", "Canonical side quest"),
        ),
        Quest(
            id = "AR-C2-057",
            chapter = 2,
            playOrder = 57,
            title = "Boy’s Farm",
            category = "SIDE QUEST — All routes",
            giver = "Volker’s Man / Bradlock / Andreas",
            location = "Old Town / Valerio’s Vineyard",
            prerequisites = "Route: All routes",
            summary = "Resolve the struggle over the vineyard by backing Holdwig, backing Andreas, or engineering a reconciliation.",
            walkthroughSteps = listOf("After Gold Rush, answer Volker’s Man and obtain Bradlock’s Order From Volker; speak with Andreas in Old Town, then travel to the vineyard and question the farmers.", "Holdwig route: investigate Gerhard through Gerstand’s account book, remove Gerhard, clear the field-raider cave and defend the vineyard.", "Andreas route: sabotage five grape bushes, burn two carts, steal tools at night, transform/use the Field Raider method to destroy seven hay sheaves, then take part in the assault.", "Reconciliation route: speak with Old Liam and all twenty-one farmers, then use Venzel to forge/produce the will evidence needed for a peaceful settlement.", "Return to the relevant leader and close the chosen branch."),
            reward = "The vineyard ownership dispute is resolved according to your chosen branch.",
            warnings = "Finish before entering the Arena/Tournament stage or the quest can fail.",
            searchTags = listOf("REGIONAL SIDE QUESTS — CHAPTERS 1–3", "ARCHOLOS CITY", "All routes", "Canonical side quest"),
        ),
        Quest(
            id = "AR-C2-058",
            chapter = 2,
            playOrder = 58,
            title = "My New Home",
            category = "SIDE QUEST — All routes",
            giver = "Sailor in the Harbour",
            location = "Archolos",
            prerequisites = "Route: All routes",
            summary = "Buy the sailor’s “house” and inspect what you purchased.",
            walkthroughSteps = listOf("Find the Sailor near the red-haired courtesan south of Dark Mysteries.", "Buy the deed/key (normally 150 gold).", "Go down to the unfinished large building north-east of him.", "Ask trader Kaleb where the property actually is.", "Follow him to your new bed/home."),
            reward = "Buy the sailor’s “house” and inspect what you purchased.",
            warnings = "",
            searchTags = listOf("REGIONAL SIDE QUESTS — CHAPTERS 1–3", "ARCHOLOS CITY", "All routes", "Canonical side quest"),
        ),
        Quest(
            id = "AR-C2-059",
            chapter = 2,
            playOrder = 59,
            title = "Against Pledge",
            category = "SIDE QUEST — All routes",
            giver = "Luna, Payback Time pawn shop",
            location = "Archolos",
            prerequisites = "Route: All routes",
            summary = "Collect or resolve the debts owed by Kuno, Dima and Frida.",
            walkthroughSteps = listOf("Speak with Kuno; you can cover his 100-gold debt or report his refusal to Luna.", "Mind Dima’s stall, deal with the drunk mercenary, then use Dima’s key for the customer request.", "Investigate Frida’s problem with the Man With The Scar; fight him or involve Volker/Bradlock.", "Return to Luna after all three debts are accounted for."),
            reward = "200 gold and 1,000 XP from Luna after resolving all three debts; returning Frida's bellows honestly can add 200 XP.",
            warnings = "Finish ALL three debtor leads before visiting Luna for the final reward; the Frida bellows contains 50 gold and can be handed over honestly.",
            searchTags = listOf("REGIONAL SIDE QUESTS — CHAPTERS 1–3", "ARCHOLOS CITY", "All routes", "Canonical side quest"),
        ),
        Quest(
            id = "AR-C2-060",
            chapter = 2,
            playOrder = 60,
            title = "Supply Of Materials",
            category = "SIDE QUEST — All routes",
            giver = "Ewald, south of Merchants’ Guild gate",
            location = "Archolos",
            prerequisites = "Route: All routes",
            summary = "Survive Ewald’s fake contract ambush.",
            walkthroughSteps = listOf("Follow Ewald into the alley.", "Refuse the 200-gold protection “contract” if you want to keep your money.", "Fight Ewald and the mercenaries, pulling toward guards if needed.", "Loot/report as the journal directs."),
            reward = "Paying Ewald's false 200-gold contract awards 750 XP; refusing and defeating his ambush gives 320 XP but saves your gold.",
            warnings = "Ewald's supposed Merchants' Guild contract is a SCAM and does not grant faction membership. Choose the high-XP payment or win the fight for less XP.",
            searchTags = listOf("REGIONAL SIDE QUESTS — CHAPTERS 1–3", "ARCHOLOS CITY", "All routes", "Canonical side quest"),
        ),
    )
}
