package com.sliverzfx.gothicquest

internal object ArcholosChapter3Part2Data {
    val quests: List<Quest> = listOf(
        Quest(
            id = "AR-C3-031",
            chapter = 3,
            playOrder = 31,
            title = "Buried Treasures",
            category = "SIDE QUEST — All routes",
            giver = "Moritz",
            location = "Scoundrels’ Haven / world map",
            prerequisites = "Route: All routes",
            summary = "Follow Moritz through several failed treasure digs.",
            walkthroughSteps = listOf("Bring a pickaxe and speak with Moritz.", "Meet him at the lake south-west of Rita’s Vineyard and dig all three spots near the large rock.", "Meet him again beside the river north of Silbach and dig the three spots by the tree.", "Continue following each new clue/location he gives you until the treasure-hunt chain resolves.", "Return to Moritz after the final dig."),
            reward = "The multi-location treasure hunt concludes.",
            warnings = "Keep a pickaxe in your inventory for the entire chain.",
            searchTags = listOf("REGIONAL SIDE QUESTS — CHAPTERS 1–3", "SCOUNDRELS’ HAVEN", "All routes", "Canonical side quest"),
        ),
        Quest(
            id = "AR-C3-032",
            chapter = 3,
            playOrder = 32,
            title = "Molerats Might Fly",
            category = "SIDE QUEST — All routes",
            giver = "Saul",
            location = "Scoundrels’ Haven",
            prerequisites = "Route: All routes",
            summary = "Help Saul prank Berter by putting an acceptable ingredient into Berter’s pea soup.",
            walkthroughSteps = listOf("Speak with Saul and show him the prank ingredients you have.", "Use peppercorns, a pearl or another ingredient Saul explicitly approves.", "Enter the hut beside Saul and interact with the soup cauldron to add the ingredient.", "Return to Saul after the soup has been tampered with."),
            reward = "Saul pays the reward and the later An Unforgettable Lesson quest becomes possible.",
            warnings = "Required for An Unforgettable Lesson in Chapter 4.",
            searchTags = listOf("REGIONAL SIDE QUESTS — CHAPTERS 1–3", "SCOUNDRELS’ HAVEN", "All routes", "Canonical side quest"),
        ),
        Quest(
            id = "AR-C3-033",
            chapter = 3,
            playOrder = 33,
            title = "Larry's Bag",
            category = "SIDE QUEST — All routes",
            giver = "Larry",
            location = "Scoundrels’ Haven",
            prerequisites = "Route: All routes",
            summary = "Recover Larry’s gold bag from Ripper and return it.",
            walkthroughSteps = listOf("Speak with Larry outside the Inn and hear how Ripper took his bag.", "Find Ripper and demand Larry’s property back.", "If Ripper has not already been beaten, defeat him in the duel; otherwise he may surrender the bag immediately.", "Take Larry’s Bag back to Larry rather than keeping it."),
            reward = "Larry gets his money back and pays the quest reward.",
            warnings = "Keeping the bag fails the intended completion.",
            searchTags = listOf("REGIONAL SIDE QUESTS — CHAPTERS 1–3", "SCOUNDRELS’ HAVEN", "All routes", "Canonical side quest"),
        ),
        Quest(
            id = "AR-C3-034",
            chapter = 3,
            playOrder = 34,
            title = "Sting",
            category = "SIDE QUEST — All routes",
            giver = "Oscar",
            location = "Scoundrels’ Haven",
            prerequisites = "Route: All routes",
            summary = "Kill the target insect/creature and bring Oscar its sting.",
            walkthroughSteps = listOf("Take the job from Oscar.", "Travel to the marked hunting area.", "Kill the target and loot the Sting.", "Return to Oscar."),
            reward = "Kill the target insect/creature and bring Oscar its sting.",
            warnings = "",
            searchTags = listOf("REGIONAL SIDE QUESTS — CHAPTERS 1–3", "SCOUNDRELS’ HAVEN", "All routes", "Canonical side quest"),
        ),
        Quest(
            id = "AR-C3-035",
            chapter = 3,
            playOrder = 35,
            title = "Escape",
            category = "SIDE QUEST — All routes",
            giver = "Homer",
            location = "Scoundrels’ Haven arena cave",
            prerequisites = "Route: All routes",
            summary = "Help Homer with his escape plan.",
            walkthroughSteps = listOf("Find Homer inside the arena cave.", "Listen to the plan and gather/perform the requested preparation.", "Move through the Haven carefully so the escape is not exposed prematurely.", "Return to Homer or escort him as the journal directs."),
            reward = "Homer’s escape route is resolved.",
            warnings = "",
            searchTags = listOf("REGIONAL SIDE QUESTS — CHAPTERS 1–3", "SCOUNDRELS’ HAVEN", "All routes", "Canonical side quest"),
        ),
        Quest(
            id = "AR-C3-036",
            chapter = 3,
            playOrder = 36,
            title = "A Few Mugs To Beat",
            category = "SIDE QUEST — All routes",
            giver = "Oscar / arena crowd",
            location = "Scoundrels’ Haven",
            prerequisites = "Route: All routes",
            summary = "Beat the listed Haven fighters before entering the Tournament.",
            walkthroughSteps = listOf("Start the bar/arena fighting challenge before registering with Proximo.", "Fight the listed opponents one at a time; save between bouts.", "Do Ripper after also starting Larry’s Bag so one knockout can advance both quests.", "Fight Morty before Abducted can remove him, and Larry after finishing Larry’s Bag.", "Fight Rodrigo last if needed; he requires a gold-ring wager.", "Report your victories to Oscar, then register with Proximo."),
            reward = "Tournament entry becomes cheaper or free depending on how many fighters you beat.",
            warnings = "Sequence matters because several opponents are used by other quests.",
            searchTags = listOf("REGIONAL SIDE QUESTS — CHAPTERS 1–3", "SCOUNDRELS’ HAVEN", "All routes", "Canonical side quest"),
        ),
    )
}
