package com.sliverzfx.gothicquest

internal object ArcholosChapter2Part1Data {
    val quests: List<Quest> = listOf(
        Quest(
            id = "AR-C2-001",
            chapter = 2,
            playOrder = 1,
            title = "Without A Trace",
            category = "MAIN STORY — All routes",
            giver = "Trigger quest",
            location = "Silbach → Archolos",
            prerequisites = "Route: All routes",
            summary = "Investigate Kurt’s disappearance, question the witnesses and reach the gates of Archolos.",
            walkthroughSteps = listOf("Search Kurt’s hut: sweep the rubbish, take both of Kurt’s pouches and inspect the Ring With Blue Stone.", "Question Rupert, Folkard, Viktor, Kazeem and Maiwen; then ask Bastian about the unfamiliar guard he saw.", "Speak with Felix at Silbach’s east gate and give him beer if needed for the next lead.", "Follow the road toward Archolos and question Gerke to confirm Kurt passed that way.", "At the city gate, learn that you need a legal pass; the Araxos Runner explains the available ways to enter."),
            reward = "Reaching the city gate and learning about the pass requirement completes this stage and opens the Chapter 2 city-entry routes.",
            warnings = "",
            searchTags = listOf("CHAPTER 2 — WITHOUT A TRACE", "", "All routes", "Canonical quest"),
        ),
        Quest(
            id = "AR-C2-002",
            chapter = 2,
            playOrder = 2,
            title = "To The Town (Albyn)",
            category = "MAIN STORY — All routes",
            giver = "Albyn",
            location = "Silbach / Archolos gate",
            prerequisites = "Route: All routes",
            summary = "Talk to Kurt in Silbach, ask Albyn for help entering Archolos, complete Aid For Flood Victims, then collect the City Permit and use it at either city gate.",
            walkthroughSteps = listOf("After Without A Trace tells you that Jorn was taken toward Archolos, use the Araxos Runner to travel to Silbach.", "On the way to Albyn's mansion, speak with Kurt. This conversation is required before Albyn's dialogue properly updates.", "Tell Albyn you need a way into Archolos. He will not simply hand over a pass; instead he asks you to help Silbach through Aid For Flood Victims.", "Speak with Uwe first. If Debt Payment is already resolved and Bastian has the timber, Uwe gives you a saw. Use the saw in his workshop to prepare the wood, then follow him to the flooded crossing.", "Jump into the river and interact with every construction point to finish the bridge. Speak with Uwe again.", "Speak with Maik. Cross the new bridge and recover his four packages. The fourth is held by a Suspicious Guy; fight him for the package or accept his bribe and return only three.", "Maik then wants the rocks cleared from the riverbed. Either defeat the two fake farmers and order them to help, or jump into the river and dig out the five rocks yourself.", "Return to Maik, then go back to Albyn. He gives you the City Permit and Reference From Albyn.", "Take the City Permit to either Archolos gate and present it to the guards. Entering the city completes To The Town."),
            reward = "You enter Archolos legally and keep Albyn's reference for later citizenship / Merchants' Guild progression.",
            warnings = "This is the cleanest first entry route, but you can still explore the other entry methods for extra XP and rewards before going through the gate.",
            searchTags = listOf("CHAPTER 2 — WITHOUT A TRACE", "", "All routes", "Canonical quest"),
        ),
        Quest(
            id = "AR-C2-003",
            chapter = 2,
            playOrder = 3,
            title = "Aid For Flood Victims",
            category = "MAIN STORY — All routes",
            giver = "Albyn",
            location = "Silbach / flooded river crossing",
            prerequisites = "Route: All routes",
            summary = "Repair the ruined crossing and recover the stranded supplies so Albyn can issue your city permit.",
            walkthroughSteps = listOf("Ask Albyn about both the riverbank repair and the carrier problem.", "Speak with Uwe first, then Maik. If Debt Payment’s wood work is done, Uwe provides the saw needed for the bridge.", "Operate the saw and follow Uwe to Silbach’s west gate; use each “Start working” point in the water to repair the crossing.", "Cross the river and recover all four packages for Maik; the Suspicious Guy has the fourth and can be fought or bribed.", "Deal with the two “farmers” blocking the rocks: convince/fight them or dig the five rocks yourself.", "Return to Albyn once both halves are complete."),
            reward = "Albyn gives the City Permit and Reference From Albyn.",
            warnings = "",
            searchTags = listOf("CHAPTER 2 — WITHOUT A TRACE", "", "All routes", "Canonical quest"),
        ),
        Quest(
            id = "AR-C2-004",
            chapter = 2,
            playOrder = 4,
            title = "To The Town (Knut)",
            category = "MAIN STORY — All routes",
            giver = "Knut / Woodcutters",
            location = "Woodcutters’ Camp → Archolos",
            prerequisites = "Route: All routes",
            summary = "Use Knut’s woodcutter connection as a legal route toward the city.",
            walkthroughSteps = listOf("Complete Knut’s preliminary work and the Elco/woodcutters chain far enough that he trusts Marvin.", "Ask Knut directly about a way into Archolos.", "Take the Letter From Woodcutters when offered and keep it in your inventory.", "Travel to the shipyard in Archolos and present/deliver the letter to Dack when the route becomes available."),
            reward = "The woodcutter recommendation provides a valid city-entry/citizenship route.",
            warnings = "Do this before bypassing the woodcutter chain if you want this specific option.",
            searchTags = listOf("CHAPTER 2 — WITHOUT A TRACE", "", "All routes", "Canonical quest"),
        ),
        Quest(
            id = "AR-C2-005",
            chapter = 2,
            playOrder = 5,
            title = "Debt Payment",
            category = "MAIN STORY — All routes",
            giver = "Bastian",
            location = "Silbach / woodcutters",
            prerequisites = "Route: All routes",
            summary = "Obtain the wood Bastian needs to settle his debt, using either or both supply routes.",
            walkthroughSteps = listOf("Ask Bastian about the debt and the roughly twenty pieces of wood he needs.", "Signal Tower route: obtain Ghost Light wine, give it to Johan and gain access to the wood store.", "Woodcutters route: speak with Knut, then find Elco near the Charcoal Burners and resolve his problem to secure the wood.", "You may use both routes for extra experience and supplies.", "Bring the required wood back to Bastian and finish the payment dialogue."),
            reward = "Bastian’s debt problem is resolved; the woodcutter route also helps later city-entry options.",
            warnings = "",
            searchTags = listOf("CHAPTER 2 — WITHOUT A TRACE", "", "All routes", "Canonical quest"),
        ),
        Quest(
            id = "AR-C2-006",
            chapter = 2,
            playOrder = 6,
            title = "Wood For Sale",
            category = "MAIN STORY — All routes",
            giver = "Knut / woodcutters",
            location = "Woodcutters’ Camp → Archolos",
            prerequisites = "Route: All routes",
            summary = "Earn the woodcutters’ recommendation letter and deliver it to the shipyard.",
            walkthroughSteps = listOf("Complete Knut/Elco’s woodcutter requirements and the associated camp work such as Razor Sharp and Howls in the Night when available.", "Return to Knut after proving yourself and ask about work or a way into the city.", "Receive the Letter From Woodcutters if your route remains eligible.", "Take the letter to Dack at the Archolos shipyard and hand it over for the delivery reward."),
            reward = "The letter serves as one legal route toward city access and gives the shipyard reward.",
            warnings = "This route can become unavailable if you bypass Elco’s chain or certain stat/dialogue conditions; do it early if you want it.",
            searchTags = listOf("CHAPTER 2 — WITHOUT A TRACE", "", "All routes", "Canonical quest"),
        ),
        Quest(
            id = "AR-C2-007",
            chapter = 2,
            playOrder = 7,
            title = "To The Town (Salzer)",
            category = "MAIN STORY — All routes",
            giver = "Salzer",
            location = "Road west of Silbach → Archolos",
            prerequisites = "Route: All routes",
            summary = "Repair Salzer’s cart and use the transport/hiding route into the city.",
            walkthroughSteps = listOf("Find Salzer on the northern road west of Silbach.", "Complete Unwheeling To Move by bringing him a replacement wheel.", "After the cart is repaired, ask about travelling toward Archolos.", "Use the barrel/cart hiding option when the dialogue appears and let the transport sequence play out."),
            reward = "Marvin reaches Archolos using Salzer’s cart route.",
            warnings = "",
            searchTags = listOf("CHAPTER 2 — WITHOUT A TRACE", "", "All routes", "Canonical quest"),
        ),
        Quest(
            id = "AR-C2-008",
            chapter = 2,
            playOrder = 8,
            title = "Unwheeling To Move",
            category = "MAIN STORY — All routes",
            giver = "Salzer",
            location = "Road west of Silbach",
            prerequisites = "Route: All routes",
            summary = "Replace Salzer’s missing wheel and use his cart as a possible way into Archolos.",
            walkthroughSteps = listOf("Find Salzer on the northern road west toward Bermar’s Farm, beneath/near the rock bridge.", "Locate a usable wheel in the nearby region and bring it back to him.", "Negotiate the reward before handing it over if the dialogue allows.", "After the cart is repaired, use the barrel/cart hiding option if you want this as your city-entry route."),
            reward = "Salzer’s cart is repaired and the smuggling route into Archolos becomes available.",
            warnings = "",
            searchTags = listOf("CHAPTER 2 — WITHOUT A TRACE", "", "All routes", "Canonical quest"),
        ),
        Quest(
            id = "AR-C2-009",
            chapter = 2,
            playOrder = 9,
            title = "To The Town (Rasco)",
            category = "MAIN STORY — All routes",
            giver = "Rasco",
            location = "Silbach → Archolos west gate",
            prerequisites = "Route: All routes",
            summary = "Side with Rasco during Tidying Up and use his bribed guard contact to enter Archolos.",
            walkthroughSteps = listOf("During Tidying Up, warn Rasco instead of completing Otho’s prank against him.", "Follow Rasco’s counter-plan and plant the dung in Albyn’s manor sacks as instructed.", "Ask Rasco about getting into Archolos after the prank is resolved.", "At the west gate, speak with the guard near Edgar, repeat the greeting sequence and pay the 75-gold bribe."),
            reward = "The bribed gate guard lets Marvin into Archolos.",
            warnings = "",
            searchTags = listOf("CHAPTER 2 — WITHOUT A TRACE", "", "All routes", "Canonical quest"),
        ),
        Quest(
            id = "AR-C2-010",
            chapter = 2,
            playOrder = 10,
            title = "Tidying Up",
            category = "MAIN STORY — All routes",
            giver = "Otho / Rasco",
            location = "Silbach",
            prerequisites = "Route: All routes",
            summary = "Collect sheep dung and choose whether to help Otho or Rasco, opening Rasco’s bribery route into the city.",
            walkthroughSteps = listOf("Speak with Otho near the barn after the Bastian work and collect all six piles of Sheep Dung.", "Otho route: place the dung in Rasco’s garden bed as instructed.", "Alternative Rasco route: warn Rasco, then plant the dung in the sacks at Albyn’s manor instead.", "If you side with Rasco, follow his directions to the west-gate guard near Edgar; greet the guard three times and pay the 75-gold bribe when the dialogue appears."),
            reward = "The prank is resolved; siding with Rasco can provide an additional city-entry method.",
            warnings = "",
            searchTags = listOf("CHAPTER 2 — WITHOUT A TRACE", "", "All routes", "Canonical quest"),
        ),
        Quest(
            id = "AR-C2-011",
            chapter = 2,
            playOrder = 11,
            title = "To The Town (Sewers)",
            category = "MAIN STORY — All routes",
            giver = "Exploration / hidden entrance",
            location = "East of Archolos → Harbour sewers",
            prerequisites = "Route: All routes",
            summary = "Use the hidden sewer system as an unofficial route into Archolos.",
            walkthroughSteps = listOf("Find the hidden entrance downhill from the teleport circle above the Amber Coast, east of the city.", "Kill or bypass the old lurker/alligator and search the corpse for the sewer map, lockpicks and torches.", "Use the first elevator and follow the northern tunnel through the sewer network.", "Use the second elevator at the far end to emerge in the Harbour district near Helga."),
            reward = "You enter Archolos through the Harbour without using a standard gate pass.",
            warnings = "",
            searchTags = listOf("CHAPTER 2 — WITHOUT A TRACE", "", "All routes", "Canonical quest"),
        ),
        Quest(
            id = "AR-C2-012",
            chapter = 2,
            playOrder = 12,
            title = "A Needle In A Haystack",
            category = "MAIN STORY — All routes",
            giver = "Helga",
            location = "Archolos Harbour",
            prerequisites = "Route: All routes",
            summary = "Ask Helga about Kurt and follow her lead to Matey.",
            walkthroughSteps = listOf("Find Helga in the Siren’s Wail Inn in the Harbour.", "Ask specifically about Kurt and any recent strangers matching his description.", "Follow Helga’s lead to Matey and question him thoroughly.", "Return to the main investigation once the journal records the new information."),
            reward = "The Kurt investigation advances and the citizenship/information hunt continues.",
            warnings = "",
            searchTags = listOf("CHAPTER 2 — WITHOUT A TRACE", "", "All routes", "Canonical quest"),
        ),
        Quest(
            id = "AR-C2-013",
            chapter = 2,
            playOrder = 13,
            title = "Citizen Marvin (Part I)",
            category = "MAIN STORY — All routes",
            giver = "Matey, Final Decision Office",
            location = "Archolos",
            prerequisites = "Route: All routes",
            summary = "Pay the citizenship fee and secure three citizen references.",
            walkthroughSteps = listOf("Find Matey at the Final Decision Office and ask how to become a citizen.", "Pay the standard fee, or complete Clean Streets if you want to avoid the 200-gold payment.", "Complete at least three reference quests from Hunting With Allan, For Connoisseurs, Worker’s Honor, Royal Gambit and Natural Methods.", "Return to Matey after three citizens agree to vouch for you."),
            reward = "Matey prepares the final citizenship decision.",
            warnings = "Several reference quests have their own choices; doing all five before turning in is best for XP.",
            searchTags = listOf("CHAPTER 2 — WITHOUT A TRACE", "", "All routes", "Canonical quest"),
        ),
        Quest(
            id = "AR-C2-014",
            chapter = 2,
            playOrder = 14,
            title = "Hunting With Allan",
            category = "MAIN STORY — All routes",
            giver = "Frida / Allan",
            location = "Archolos west gate",
            prerequisites = "Route: All routes",
            summary = "Go hunting with Allan and survive the scavenger-to-bear route.",
            walkthroughSteps = listOf("Ask Frida for a citizenship reference and agree to prove yourself as a hunter.", "Meet Allan outside the west gate and follow him rather than sprinting ahead.", "Kill the first scavengers, then the stronger forest scavengers.", "Continue until the bear encounter; let Allan share aggro if your gear is weak.", "Return to Frida after the hunt for her reference."),
            reward = "Frida becomes one of your citizenship references.",
            warnings = "Having trophy-harvesting skills makes this route more profitable.",
            searchTags = listOf("CHAPTER 2 — WITHOUT A TRACE", "", "All routes", "Canonical quest"),
        ),
        Quest(
            id = "AR-C2-015",
            chapter = 2,
            playOrder = 15,
            title = "For Connoisseurs",
            category = "MAIN STORY — All routes",
            giver = "Tomas",
            location = "Dark Paladine Brewery, Archolos",
            prerequisites = "Route: All routes",
            summary = "Market Tomas’ Dark Paladine beer to five influential customers and secure his citizenship reference.",
            walkthroughSteps = listOf("Ask Tomas about brewing and about help becoming a citizen; accept six sample bottles and his minimum price of 100 gold per crate.", "Visit Lorenzo in the Merchants’ Guild. Agree to sabotage Ernesto’s wine, place/sell the spoiled bottle through the market as instructed, then report back.", "Visit Lennart and use the dialogue that reminds him guards are human too.", "Visit Gerstand and describe the beer as having a rich/surprising flavour.", "Visit Vlada and complete her tasting dialogue.", "Visit Helga in the Siren’s Wail, pay for the tasting drink if required, and secure her order.", "Return to Tomas after all five customers are handled and settle the sales/recommendation reward."),
            reward = "Tomas supports Marvin’s citizenship and the beer-distribution quest closes.",
            warnings = "If you are pursuing the Merchants’ Guild, complete Weed Him Out before actions here that can damage Ernesto’s business.",
            searchTags = listOf("CHAPTER 2 — WITHOUT A TRACE", "", "All routes", "Canonical quest"),
        ),
        Quest(
            id = "AR-C2-016",
            chapter = 2,
            playOrder = 16,
            title = "Worker's Honor",
            category = "MAIN STORY — All routes",
            giver = "Ramona",
            location = "Archolos Harbour / City Guard barracks",
            prerequisites = "Route: All routes",
            summary = "Investigate the broken crane, find the missing gearwheel and decide whether to expose the real culprit or frame Recon and Veigo.",
            walkthroughSteps = listOf("Meet Ramona at the northern docks and follow her, Recon and Veigo to the City Guard barracks.", "Investigate the missing crane part and trace the lead through Sall/Borr/Alder until you obtain the gearwheel.", "If helping Recon and Veigo, tell Alder you are going to a man named Sall so the investigation continues correctly; bring the truth into the barracks confrontation.", "If framing them instead, ask Helga for Recon’s room, go to the top floor of Siren’s Wail, first door on the right, and plant the gearwheel in Recon’s chest.", "Return to the barracks, reconnect with the waiting guard and trigger the final confrontation."),
            reward = "Truth route preserves Recon/Veigo and their later benefits; frame route gives Ramona’s reference and gold.",
            warnings = "Veigo can later become a Vardhal expedition worker if you help him, so the honest route has a late-game benefit.",
            searchTags = listOf("CHAPTER 2 — WITHOUT A TRACE", "", "All routes", "Canonical quest"),
        ),
        Quest(
            id = "AR-C2-017",
            chapter = 2,
            playOrder = 17,
            title = "Heaven's Will",
            category = "MAIN STORY — All routes",
            giver = "Tengral",
            location = "Temple of Innos / east-gate shrine",
            prerequisites = "Route: All routes",
            summary = "Help Tengral test Runar’s zealotry with a staged miracle, then decide whether to protect or betray the young paladin.",
            walkthroughSteps = listOf("Speak with Tengral at the Temple of Innos and accept the task concerning Runar.", "Find Runar in or around the Fire Mages’ Quarters; learn that cheap fake relics will not fool him.", "Visit Huug at the Golden Gate Variety Shop, call out his fake holy merchandise and arrange the staged demonstration.", "Return to Runar and agree to meet him at midnight in front of the Temple.", "Escort him to the Innos shrine outside the east gate, where the setup becomes an ambush.", "Choose whether to protect Runar from the attackers or betray/abandon him according to your route, then return to Tengral."),
            reward = "Tengral grants the citizenship reference; protecting Runar yields better long-term utility and keeps him available as a trainer.",
            warnings = "",
            searchTags = listOf("CHAPTER 2 — WITHOUT A TRACE", "", "All routes", "Canonical quest"),
        ),
        Quest(
            id = "AR-C2-018",
            chapter = 2,
            playOrder = 18,
            title = "Royal Gambit",
            category = "MAIN STORY — All routes",
            giver = "Kuno, marketplace",
            location = "Archolos",
            prerequisites = "Route: All routes",
            summary = "Expose Leon’s cheating in the chess dispute and obtain Kuno’s reference.",
            walkthroughSteps = listOf("Speak with Kuno and agree to investigate why Leon keeps winning.", "Question Leon and inspect/read the chess material connected to the match.", "Use the discovered rule — the bishop cannot take the queen in the disputed position — to challenge the cheating story.", "Resolve the dispute in Kuno’s favor and return to him."),
            reward = "Kuno gives the citizenship reference.",
            warnings = "",
            searchTags = listOf("CHAPTER 2 — WITHOUT A TRACE", "", "All routes", "Canonical quest"),
        ),
        Quest(
            id = "AR-C2-019",
            chapter = 2,
            playOrder = 19,
            title = "Natural Methods",
            category = "MAIN STORY — All routes",
            giver = "Ruud, harbour",
            location = "Archolos",
            prerequisites = "Route: All routes",
            summary = "Find a non-magical cure for Ruud’s shoulder through Figaro.",
            walkthroughSteps = listOf("Speak with Ruud in the harbour and agree to find treatment.", "Visit alchemist Figaro and ask for a natural remedy.", "Bring 5 River Myrtle if you want the inexpensive/free treatment instead of simply paying.", "Follow Figaro to Ruud or return as instructed and let the treatment play out.", "Speak with Ruud afterward."),
            reward = "Ruud gives a citizenship reference.",
            warnings = "",
            searchTags = listOf("CHAPTER 2 — WITHOUT A TRACE", "", "All routes", "Canonical quest"),
        ),
        Quest(
            id = "AR-C2-020",
            chapter = 2,
            playOrder = 20,
            title = "Citizen Marvin (Part II)",
            category = "MAIN STORY — All routes",
            giver = "Matey",
            location = "Archolos",
            prerequisites = "Route: All routes",
            summary = "Return after securing the references and collect your citizenship papers.",
            walkthroughSteps = listOf("Make sure at least three qualifying references have been completed.", "Speak with Matey and go through the final paperwork dialogue.", "Collect the Documentary Evidence of Citizenship and read any new message delivered afterward."),
            reward = "You become a citizen and can join either the City Guard or Araxos Merchants’ Guild.",
            warnings = "Make a permanent save here if you want to experience both guild routes.",
            searchTags = listOf("CHAPTER 2 — WITHOUT A TRACE", "", "All routes", "Canonical quest"),
        ),
        Quest(
            id = "AR-C2-021",
            chapter = 2,
            playOrder = 21,
            title = "Training Of Recruits",
            category = "FACTION QUEST — City Guard",
            giver = "City Guard training square",
            location = "Archolos",
            prerequisites = "Route: City Guard",
            summary = "Complete enough recruit training events for Winstan.",
            walkthroughSteps = listOf("Arrive at the training square around 08:00 and speak with the instructor.", "Win the one-on-one bout, then the two-on-one fight. The three-on-one challenge is optional but valuable.", "Follow the recruits toward the south gate for the ranged exercise.", "Shoot the required apples/targets and finish the remaining drills.", "Report to Winstan after the training quota is satisfied."),
            reward = "You progress the City Guard initiation and gain combat experience.",
            warnings = "Save before the multi-opponent fights if your build is still weak.",
            searchTags = listOf("CHAPTER 2 — CITY GUARD ROUTE", "", "City Guard", "Canonical quest"),
        ),
        Quest(
            id = "AR-C2-022",
            chapter = 2,
            playOrder = 22,
            title = "A Blade For A Guardsman",
            category = "FACTION QUEST — City Guard",
            giver = "Arwid / Odgar",
            location = "Archolos City Guard",
            prerequisites = "Route: City Guard",
            summary = "Acquire a proper Guard weapon by duelling Arwid or commissioning Odgar.",
            walkthroughSteps = listOf("After Roderich asks you to obtain a Guard-worthy weapon, leave his office and speak with Arwid.", "Choose one route: duel Arwid and wager on yourself to win his sword, OR visit Odgar and have a suitable blade forged.", "If you choose Odgar, gather/pay for his requested materials and collect the finished sword.", "Equip or carry the qualifying weapon and return to Roderich."),
            reward = "The weapon requirement for joining the Guard is satisfied.",
            warnings = "The Arwid and Odgar solutions are mutually exclusive.",
            searchTags = listOf("CHAPTER 2 — CITY GUARD ROUTE", "", "City Guard", "Canonical quest"),
        ),
        Quest(
            id = "AR-C2-023",
            chapter = 2,
            playOrder = 23,
            title = "The Night Patrol (Weigar)",
            category = "FACTION QUEST — City Guard",
            giver = "Weigar, outside Roderich’s office at midnight",
            location = "Archolos",
            prerequisites = "Route: City Guard",
            summary = "Patrol the city with Weigar and investigate every suspicious event.",
            walkthroughSteps = listOf("Wear the required Guard clothing and meet Weigar at midnight.", "Follow him to the Slums; kill the Giant Rat when it appears.", "Search the alley north of the Arena and confront the Mysterious Man with his two thugs.", "Continue the patrol through each district and stop to investigate any unusual NPC/event even when Weigar does not explicitly prompt you.", "Finish the route and report as the journal directs the following morning."),
            reward = "The patrol is accepted and later opens Old Scores.",
            warnings = "",
            searchTags = listOf("CHAPTER 2 — CITY GUARD ROUTE", "", "City Guard", "Canonical quest"),
        ),
        Quest(
            id = "AR-C2-024",
            chapter = 2,
            playOrder = 24,
            title = "Missing In Action",
            category = "FACTION QUEST — City Guard",
            giver = "Roderich",
            location = "Archolos → Silbach",
            prerequisites = "Route: City Guard",
            summary = "Find out what happened to Sergeant Gerwin, Berto and Till.",
            walkthroughSteps = listOf("Take the assignment from Roderich.", "Travel to Silbach and question Albyn and Bastian about the missing Guards and nearby bandits.", "Follow the leads outside the village and inspect each Guard/bandit scene rather than skipping corpses or documents.", "Trace the renegade activity to Salvi and the cave network connected to the kidnappers.", "Preserve the evidence/armor you find and report back to Roderich before starting the final tracking quest."),
            reward = "Roderich accepts the report; Tracking Guilty Kidnappers becomes the Chapter 2 closing mission.",
            warnings = "",
            searchTags = listOf("CHAPTER 2 — CITY GUARD ROUTE", "", "City Guard", "Canonical quest"),
        ),
        Quest(
            id = "AR-C2-025",
            chapter = 2,
            playOrder = 25,
            title = "Tracking Guilty Kidnappers",
            category = "FACTION QUEST — City Guard",
            giver = "Roderich / evidence from Missing In Action",
            location = "Archolos / Scoundrels’ Haven route",
            prerequisites = "Route: City Guard",
            summary = "Use the kidnapping evidence to locate the Scoundrels’ Haven.",
            walkthroughSteps = listOf("Report Missing In Action to Roderich first even if the journal already shows the new quest.", "Follow the lead given by the surviving witness/evidence toward the hidden criminal route.", "Clear or bypass the bandits blocking the path.", "Use the discovered entrance/transport route to reach Scoundrels’ Haven.", "Speak with the first Haven contacts to secure access rather than attacking the camp."),
            reward = "Entering the Haven completes the City Guard Chapter 2 route and starts Chapter 3.",
            warnings = "Mine important ore deposits and finish Chapter 2 cleanup before completing this transition.",
            searchTags = listOf("CHAPTER 2 — CITY GUARD ROUTE", "", "City Guard", "Canonical quest"),
        ),
        Quest(
            id = "AR-C2-026",
            chapter = 2,
            playOrder = 26,
            title = "This One Will Do",
            category = "FACTION QUEST — City Guard",
            giver = "Oktav / Arwid",
            location = "Archolos west fields",
            prerequisites = "Route: City Guard",
            summary = "Help Arwid clear the field raiders and report to Oktav.",
            walkthroughSteps = listOf("Accept the side assignment at the barracks and meet Arwid.", "Follow him out the west gate to Tespi’s field.", "Kill all six field raiders.", "Talk to Arwid, then Tespi, then Arwid again.", "Return to Oktav at the barracks for payment."),
            reward = "The field is safe and Old Scores can become available.",
            warnings = "",
            searchTags = listOf("CHAPTER 2 — CITY GUARD ROUTE", "", "City Guard", "Canonical quest"),
        ),
        Quest(
            id = "AR-C2-027",
            chapter = 2,
            playOrder = 27,
            title = "Old Scores",
            category = "FACTION QUEST — City Guard",
            giver = "Weigar",
            location = "Archolos Slums",
            prerequisites = "Route: City Guard",
            summary = "Broker a meeting between Weigar and the Mysterious Man, then survive the ambush.",
            walkthroughSteps = listOf("After This One Will Do, find Weigar on the path between the Temple of Innos enclosure and the Slums during the day.", "Wait until evening and return to the Slums location from The Night Patrol.", "Negotiate with the Mysterious Man and propose the meeting by the tree.", "Return to Weigar and relay the agreement.", "Follow/meet Weigar at the meeting point and let the cutscene/dialogue start before drawing weapons.", "Deal with the resulting confrontation and report the outcome."),
            reward = "Weigar settles the score; the Mysterious Man thread continues elsewhere.",
            warnings = "Do not attack the group leader before his dialogue triggers or the encounter can break.",
            searchTags = listOf("CHAPTER 2 — CITY GUARD ROUTE", "", "City Guard", "Canonical quest"),
        ),
        Quest(
            id = "AR-C2-028",
            chapter = 2,
            playOrder = 28,
            title = "Contractor",
            category = "FACTION QUEST — City Guard",
            giver = "Lennart",
            location = "City Guard barracks / west road",
            prerequisites = "Route: City Guard",
            summary = "Test Lorenzo's Demonstration Crossbow with Docan, tell Lennart whether it is worth buying, and—if you reject it—recruit Detlow so Lorenzo will renegotiate the contract.",
            walkthroughSteps = listOf("After Missing In Action, speak with quartermaster Lennart. He wants you to investigate a crossbow offer from the Merchants' Guild.", "Visit Lorenzo upstairs in the Merchants' Guild HQ. He gives you the Demonstration Crossbow and tells you to test it with Docan.", "Leave Archolos through the west gate and meet Docan at the crossroads by the tree stump.", "Make a safety save before the demonstration. Your inventory is temporarily disabled during the first test and accessing inventories at the wrong time can break the sequence.", "Follow Docan to the boars. Let him draw the animals while you test the crossbow; the weapon is deliberately poor. Tell Docan what you think afterward.", "Follow him to the second test against three Renegade deserters. Your normal inventory is available again here, so switch back to your real equipment and kill them.", "Return to Lennart. Recommending the crossbow ends the quest immediately, but telling him it is rubbish opens the better-paying negotiation route.", "For the better route, return to Lorenzo. He agrees to lower the price only if you recruit hunter Detlow, found in the field outside Archolos' east gate.", "Offer Detlow the maintenance job. He asks for supplies from Bodowin near Silbach. Buy the Packet Of Herbs for 100 gold, or distract Bodowin with the scavenger in his garden and bluff that you already paid.", "Bring the herbs to Detlow, then report to Lorenzo and finally to Lennart."),
            reward = "The City Guard secures the contract on better terms; the full negotiation route gives the superior reward.",
            warnings = "",
            searchTags = listOf("CHAPTER 2 — CITY GUARD ROUTE", "", "City Guard", "Canonical quest"),
        ),
        Quest(
            id = "AR-C2-029",
            chapter = 2,
            playOrder = 29,
            title = "The Story Of The Plague",
            category = "FACTION QUEST — City Guard",
            giver = "Corum, Guard alchemist",
            location = "Archolos Sewers",
            prerequisites = "Route: City Guard",
            summary = "Poison all five rat nests in the sewers.",
            walkthroughSteps = listOf("Take Corum’s Rat Poison and read his recipe.", "Craft at least four additional Rat Poisons at an alchemy bench.", "Enter the sewers, preferably through the sunken alley behind the Siren’s Wail; buy a sewer map from Ludwig if needed.", "Fight northward and poison the first three nests.", "When Baluen appears, finish his dialogue before touching the final nests.", "Poison all five nests and return to Corum; choose whether to expose Baluen or protect him."),
            reward = "The infestation ends; your final reward depends on what you tell Corum/Oktav.",
            warnings = "Talking to Baluen after destroying the last nest can break the quest.",
            searchTags = listOf("CHAPTER 2 — CITY GUARD ROUTE", "", "City Guard", "Canonical quest"),
        ),
        Quest(
            id = "AR-C2-030",
            chapter = 2,
            playOrder = 30,
            title = "Dima's Messenger (Dima)",
            category = "FACTION QUEST — Merchants’ Guild",
            giver = "Dima, marketplace",
            location = "Archolos → Silbach / forest",
            prerequisites = "Route: Merchants’ Guild",
            summary = "Find Dima’s missing messenger by tracing him from Silbach into the forest.",
            walkthroughSteps = listOf("Speak with Dima and accept the delivery/messenger investigation.", "Go to Silbach and find Sunder in the Molerat Inn. If he is too drunk to help, use Bastian’s sludge/remedy to sober him.", "Follow the directions toward the north-western forest and look for blood/tracks rather than staying on the main road.", "Find the messenger’s body near a tree and inspect it for the quest item/evidence.", "Return to Sunder if required, then report the outcome to Dima."),
            reward = "The missing-messenger job closes and counts toward the Araxos route.",
            warnings = "",
            searchTags = listOf("CHAPTER 2 — MERCHANTS’ GUILD ROUTE", "", "Merchants’ Guild", "Canonical quest"),
        ),
    )
}
