package com.sliverzfx.gothicquest

internal object ArcholosChapter2Part3Data {
    val quests: List<Quest> = listOf(
        Quest(
            id = "AR-C2-061",
            chapter = 2,
            playOrder = 61,
            title = "Drunken Guide",
            category = "SIDE QUEST — All routes",
            giver = "Otmar, outside Merchants’ Guild",
            location = "Archolos / harbour",
            prerequisites = "Route: All routes",
            summary = "Find and hire Otmar’s drunken guide.",
            walkthroughSteps = listOf("Ask Helga for information.", "Find the drunk guide in the eastern harbour area near the houses.", "Hire him and follow the ride/escort sequence.", "When he passes out, return to Otmar."),
            reward = "Find and hire Otmar’s drunken guide.",
            warnings = "",
            searchTags = listOf("REGIONAL SIDE QUESTS — CHAPTERS 1–3", "ARCHOLOS CITY", "All routes", "Canonical side quest"),
        ),
        Quest(
            id = "AR-C2-062",
            chapter = 2,
            playOrder = 62,
            title = "Pearls Of Water",
            category = "SIDE QUEST — All routes",
            giver = "Kobus, Temple of Adanos",
            location = "Archolos",
            prerequisites = "Route: All routes",
            summary = "Bring eight pearls and consecrate them in the water.",
            walkthroughSteps = listOf("Collect 8 Pearls from shells or fishmongers.", "Return to Kobus.", "Place the pearls in the water bucket/ritual container.", "Wait roughly half a minute for the interaction to update.", "Talk to Kobus and take the Pearl of Water."),
            reward = "Bring eight pearls and consecrate them in the water.",
            warnings = "",
            searchTags = listOf("REGIONAL SIDE QUESTS — CHAPTERS 1–3", "ARCHOLOS CITY", "All routes", "Canonical side quest"),
        ),
        Quest(
            id = "AR-C2-063",
            chapter = 2,
            playOrder = 63,
            title = "Fight Club",
            category = "SIDE QUEST — All routes",
            giver = "Alena, Slums warehouse",
            location = "Archolos",
            prerequisites = "Route: All routes",
            summary = "Win the underground fighting series.",
            walkthroughSteps = listOf("Find Alena in the Slums warehouse and register.", "Save before each match.", "Use Boxer Rings for fist bouts if available.", "Defeat the sequence of fighters; the final Nordmar opponent uses a heavy hammer.", "Collect the final gold/weapon reward from Alena."),
            reward = "Win the underground fighting series.",
            warnings = "Several matches are significantly harder than normal street fights; leave and level up if necessary.",
            searchTags = listOf("REGIONAL SIDE QUESTS — CHAPTERS 1–3", "ARCHOLOS CITY", "All routes", "Canonical side quest"),
        ),
        Quest(
            id = "AR-C2-064",
            chapter = 2,
            playOrder = 64,
            title = "A Northern Breeze",
            category = "SIDE QUEST — All routes",
            giver = "Gard near the church",
            location = "Archolos → Wolf’s Den",
            prerequisites = "Route: All routes",
            summary = "Tell Gard about the Wolf’s Den and meet him there.",
            walkthroughSteps = listOf("Speak with Gard on the bench near the church.", "Suggest the Wolf’s Den as a destination.", "Travel there and find Gard after he relocates.", "Discuss the volcano/area with him to finish the quest."),
            reward = "Tell Gard about the Wolf’s Den and meet him there.",
            warnings = "",
            searchTags = listOf("REGIONAL SIDE QUESTS — CHAPTERS 1–3", "ARCHOLOS CITY", "All routes", "Canonical side quest"),
        ),
        Quest(
            id = "AR-C2-065",
            chapter = 2,
            playOrder = 65,
            title = "What It Likes?",
            category = "SIDE QUEST — All routes",
            giver = "Sigrid",
            location = "Archolos / Third Warrior Blacksmith area",
            prerequisites = "Route: All routes",
            summary = "Feed the Old Dog different meats until it trusts Marvin, then pet it for the final reward.",
            walkthroughSteps = listOf("Find Sigrid and the Old Dog behind the Third Warrior Blacksmith.", "Offer different meat foods; the dog only accepts a limited amount per day and does not like repeats.", "Use good items such as sausage and avoid rat meat, which it dislikes.", "Return on later days and continue feeding until the journal indicates sufficient trust.", "Pet the dog after the trust threshold is reached."),
            reward = "The dog accepts Marvin and the quest awards the final experience.",
            warnings = "",
            searchTags = listOf("REGIONAL SIDE QUESTS — CHAPTERS 1–3", "ARCHOLOS CITY", "All routes", "Canonical side quest"),
        ),
        Quest(
            id = "AR-C2-066",
            chapter = 2,
            playOrder = 66,
            title = "Green Lighthouse",
            category = "SIDE QUEST — All routes",
            giver = "Nevil, outside Helga’s tavern",
            location = "Archolos coast",
            prerequisites = "Route: All routes",
            summary = "Clear the old lighthouse and recover the sealed package.",
            walkthroughSteps = listOf("Speak with Nevil.", "Swim or travel east to the lighthouse.", "Kill the two smugglers guarding it.", "Loot the sealed package and other useful lighthouse items.", "Return to Nevil, or choose the alternative report to Oktav if available."),
            reward = "Clear the old lighthouse and recover the sealed package.",
            warnings = "",
            searchTags = listOf("REGIONAL SIDE QUESTS — CHAPTERS 1–3", "ARCHOLOS CITY", "All routes", "Canonical side quest"),
        ),
        Quest(
            id = "AR-C2-067",
            chapter = 2,
            playOrder = 67,
            title = "New To Archolos?",
            category = "SIDE QUEST — All routes",
            giver = "Bruno, tavern south-east city",
            location = "Archolos / mine",
            prerequisites = "Route: All routes",
            summary = "Follow Bruno to a supposed job and survive the trap.",
            walkthroughSteps = listOf("Meet Bruno at the tavern and agree to work.", "Meet him again at the west gate and follow him to the basin.", "Use a pickaxe on the rubble and enter the mine.", "Mine the available iron deposits, then confront Bruno and the mercenaries when the trap is revealed.", "Side with the workers, defeat the hostile group and report to Lorenzo/Roderich according to your guild."),
            reward = "Follow Bruno to a supposed job and survive the trap.",
            warnings = "",
            searchTags = listOf("REGIONAL SIDE QUESTS — CHAPTERS 1–3", "ARCHOLOS CITY", "All routes", "Canonical side quest"),
        ),
        Quest(
            id = "AR-C2-068",
            chapter = 2,
            playOrder = 68,
            title = "Abducted",
            category = "SIDE QUEST — All routes",
            giver = "Nadine, City Guard barracks",
            location = "Archolos / Southern Marshes / Haven",
            prerequisites = "Route: All routes",
            summary = "Find Nadine’s missing daughter Lena and report her fate.",
            walkthroughSteps = listOf("Speak with Nadine in the east passage of the City Guard barracks.", "Pay Helga for information, then search the Southern Marshes for the dead hunter and read his diary.", "At Scoundrels’ Haven, reach the prison cave behind Lorietta; bribe, beat or bypass Morty.", "Speak with the imprisoned girl, Gregor, Oscar and Ivan to identify Lena and her captors.", "Pay Gregor’s demand or defeat Gregor and Morty, then open Lena’s cell.", "When Cortez blocks the rescue, take Lena’s Amulet and return to Nadine with the truth."),
            reward = "Nadine learns Lena’s fate; you can give back or keep the amulet depending on the dialogue.",
            warnings = "Finish before Crownless King in Chapter 5 or Lena can disappear.",
            searchTags = listOf("REGIONAL SIDE QUESTS — CHAPTERS 1–3", "ARCHOLOS CITY", "All routes", "Canonical side quest"),
        ),
        Quest(
            id = "AR-C2-069",
            chapter = 2,
            playOrder = 69,
            title = "Heartbreaker",
            category = "SIDE QUEST — All routes",
            giver = "Lutz, marketplace",
            location = "Archolos / Silbach",
            prerequisites = "Route: All routes",
            summary = "Help Lutz repair his relationship with Martha.",
            walkthroughSteps = listOf("Speak with Lutz and carry his apology to Martha in the Molerat Inn.", "Return after Martha rejects him and make Lutz admit what he did.", "Have him repay what he owes, then arrange the Silbach date: food, wine, location and musician.", "Attend/let the date happen, sleep until the next morning and meet Lutz in the inn.", "Take the magic-ore sword reward and speak with Martha for her final reward/recipe."),
            reward = "Help Lutz repair his relationship with Martha.",
            warnings = "",
            searchTags = listOf("REGIONAL SIDE QUESTS — CHAPTERS 1–3", "ARCHOLOS CITY", "All routes", "Canonical side quest"),
        ),
        Quest(
            id = "AR-C2-070",
            chapter = 2,
            playOrder = 70,
            title = "Where Words Abound",
            category = "SIDE QUEST — All routes",
            giver = "Trimegisto",
            location = "Archolos Old Town / Slums",
            prerequisites = "Route: All routes",
            summary = "Help Trimegisto investigate Huug’s illegal operation.",
            walkthroughSteps = listOf("This requires the earlier Heaven’s Will quest.", "Meet Trimegisto near the Fire Mages’ Quarters and accompany him to Huug’s Golden Gate shop.", "When Huug traps you inside, talk to Trimegisto, try the door, then drink his temporary-strength essence and kick the door open.", "Chase Huug into the harbour and confront him on/near the wall behind the shipyard.", "Return upstairs to the Fire Mages’ Quarters for the judgment scene."),
            reward = "Huug is imprisoned and the case against Marvin is cleared/resolved.",
            warnings = "",
            searchTags = listOf("REGIONAL SIDE QUESTS — CHAPTERS 1–3", "ARCHOLOS CITY", "All routes", "Canonical side quest"),
        ),
        Quest(
            id = "AR-C2-071",
            chapter = 2,
            playOrder = 71,
            title = "Golden Innoses",
            category = "SIDE QUEST — All routes",
            giver = "Candac, Temple of Innos",
            location = "Archolos",
            prerequisites = "Route: All routes",
            summary = "Expose the operation selling fake Innos figurines.",
            walkthroughSteps = listOf("Speak with Candac outside the temple.", "Question Mailor and Groen about their permits and suppliers.", "Trace the permits through Matey/Dima and locate the hidden workshop.", "Remove conspicuous gear if the undercover route asks for it, get inside, and obtain proof such as the contract/unfinished figurine.", "Return the evidence to Candac."),
            reward = "Expose the operation selling fake Innos figurines.",
            warnings = "",
            searchTags = listOf("REGIONAL SIDE QUESTS — CHAPTERS 1–3", "ARCHOLOS CITY", "All routes", "Canonical side quest"),
        ),
        Quest(
            id = "AR-C2-072",
            chapter = 2,
            playOrder = 72,
            title = "Late For Work",
            category = "SIDE QUEST — All routes",
            giver = "Rita",
            location = "Rita’s Vineyard / river cave",
            prerequisites = "Route: All routes",
            summary = "Find missing guard Nek, recover his family amulet from the river and bring him back.",
            walkthroughSteps = listOf("Speak with Rita and ask about the missing guard.", "From the Araxos Runner near the vineyard, follow the river west until it enters the mountain cave.", "Take the side opening and kill the molerats attacking Nek.", "Speak with Nek; he refuses to return without his family amulet. Dive into the river directly in front of the cave section and pick the amulet up from the bottom.", "Give the amulet to Nek, then return to Rita."),
            reward = "Nek returns to work and Rita rewards Marvin.",
            warnings = "",
            searchTags = listOf("REGIONAL SIDE QUESTS — CHAPTERS 1–3", "RITA’S VINEYARD", "All routes", "Canonical side quest"),
        ),
        Quest(
            id = "AR-C2-073",
            chapter = 2,
            playOrder = 73,
            title = "Let There Be Light",
            category = "SIDE QUEST — All routes",
            giver = "Nayla",
            location = "Rita’s Vineyard cellar",
            prerequisites = "Route: All routes",
            summary = "Give Nayla a permanent light source so she can count the wine bottles in the dark cellar.",
            walkthroughSteps = listOf("Find Nayla working in the vineyard’s wine cellar and ask what is wrong.", "Bring either a torch or a Light scroll.", "Give Nayla the light source through dialogue.", "Prefer the torch if you want the cellar to remain permanently illuminated; the Light spell eventually expires."),
            reward = "Nayla can finish her work and the cellar is illuminated according to the chosen solution.",
            warnings = "A torch is the practical long-term solution because it does not expire.",
            searchTags = listOf("REGIONAL SIDE QUESTS — CHAPTERS 1–3", "RITA’S VINEYARD", "All routes", "Canonical side quest"),
        ),
        Quest(
            id = "AR-C2-074",
            chapter = 2,
            playOrder = 74,
            title = "Danger Around",
            category = "SIDE QUEST — All routes",
            giver = "Rita",
            location = "Rita’s Vineyard / surrounding roads",
            prerequisites = "Route: All routes",
            summary = "Inspect the threats around the vineyard and reinforce its security.",
            walkthroughSteps = listOf("Speak with Rita in Chapter 2 and accept the request to assess the area around the farm.", "Patrol the paths and immediate perimeter named by the journal, clearing the dangerous creatures/groups you encounter.", "Inspect the vineyard storage for the wood/materials required by the security step; the needed wood is inside a crate in the storeroom.", "Use/deliver the materials at the indicated defensive point and finish the remaining perimeter check.", "Return to Rita once the journal shows all security objectives complete."),
            reward = "Rita’s vineyard security is improved; this also makes her available as a provision contact for the later Vardhal expedition.",
            warnings = "",
            searchTags = listOf("REGIONAL SIDE QUESTS — CHAPTERS 1–3", "RITA’S VINEYARD", "All routes", "Canonical side quest"),
        ),
        Quest(
            id = "AR-C2-075",
            chapter = 2,
            playOrder = 75,
            title = "What Goes Around, Comes Around",
            category = "SIDE QUEST — All routes",
            giver = "Sven",
            location = "Sailor’s Retreat",
            prerequisites = "Route: All routes",
            summary = "Deal with Sven’s request to sabotage Harold’s fishing boat.",
            walkthroughSteps = listOf("Speak with Sven and refuse to be baited into a pointless fight.", "Hear his plan to sabotage Harold before the fishing competition.", "Inspect Harold’s boat and choose whether to carry out or expose the sabotage.", "Return to the appropriate fisherman and resolve the competition outcome."),
            reward = "The fishing feud is resolved according to your choice.",
            warnings = "",
            searchTags = listOf("REGIONAL SIDE QUESTS — CHAPTERS 1–3", "SAILOR’S RETREAT / CEMETERY", "All routes", "Canonical side quest"),
        ),
        Quest(
            id = "AR-C2-076",
            chapter = 2,
            playOrder = 76,
            title = "Behind The Closed Door",
            category = "SIDE QUEST — All routes",
            giver = "Zachary",
            location = "Sailor’s Retreat",
            prerequisites = "Route: All routes",
            summary = "Open the sealed western cave storehouse, kill the skeleton goblins and discover what happened to the missing man.",
            walkthroughSteps = listOf("Speak with Zachary and take Zachary’s Key.", "Go to the cave at the west end of the beach and turn left to the locked storehouse door.", "Open it, kill the three Skeleton Goblins (or lure them toward Balni/NPC help if needed) and search the deepest room.", "Loot the missing man’s corpse and pick up the bloodstained map if found.", "Return to Zachary; show him the map as well for the extra clue/reward."),
            reward = "Zachary learns what happened and rewards Marvin.",
            warnings = "",
            searchTags = listOf("REGIONAL SIDE QUESTS — CHAPTERS 1–3", "SAILOR’S RETREAT / CEMETERY", "All routes", "Canonical side quest"),
        ),
        Quest(
            id = "AR-C2-077",
            chapter = 2,
            playOrder = 77,
            title = "Hunter's Blood",
            category = "SIDE QUEST — All routes",
            giver = "Nelson",
            location = "Wolf’s Den",
            prerequisites = "Route: All routes",
            summary = "Help Nelson choose between hunting life and studying at the Monastery.",
            walkthroughSteps = listOf("Talk to Nelson and compliment his bow.", "Discuss his wish to study with the Fire Mages.", "Before sending him away, buy any unique hunting skills you still need from him.", "Complete the dialogue/errands that let Nelson leave for the Monastery.", "Later visit him at the Monastery for the follow-up reward."),
            reward = "Nelson leaves the Den and can later be found at the Monastery.",
            warnings = "Nelson teaches useful hunting skills before Chapter 3; learn them first.",
            searchTags = listOf("REGIONAL SIDE QUESTS — CHAPTERS 1–3", "WOLF’S DEN — EARLY", "All routes", "Canonical side quest"),
        ),
    )
}
