package com.sliverzfx.gothicquest

internal object ArcholosChapter5Part1Data {
    val quests: List<Quest> = listOf(
        Quest(
            id = "AR-C5-001",
            chapter = 5,
            playOrder = 1,
            title = "From Bad To Worse",
            category = "MAIN STORY — Guild/story route",
            giver = "Automatic — chapter opens at the Water Mages' monastery",
            location = "Monastery",
            prerequisites = "Chapter 5; survive the Ring of Water ambush and the waterfall escape at the end of Chapter 4.",
            summary = "Recover at the monastery and solve the monastery medical trials to brew Dagobert's Potion with Ana.",
            walkthroughSteps = listOf("Wake in the monastery infirmary with Kessel injured nearby. Ask Riordian and healer Rierol about treatment; speak to novice Ana. You cannot heal normally by sleeping yet.", "After resting, Ana provides a Water Novice's Robe. Follow her stealth plan and hide behind crates while she distracts Rierol. Search the infirmary study for medical recipe clues.", "Complete Riordian's material-gathering assignments: retrieve the six library books (the last on a high shelf needs Telekinesis); obtain the Alchemical Measures volume in the dark cellar using Light; use Meatbug Transformation for the storeroom's alembic and key.", "Get a large cauldron by using the rat-growth trick to scare Stefan, and help Curtis win his grape contest with a slowdown spell to obtain a wooden mortar.", "Deliver all required equipment to Riordian and sleep. Use Ana's novice-cell key to find the completed instructions in the Almanac of Alchemical Measures and collect the Herbal Chest.", "Ask Ana to prepare the medicine, in EXACT order: half a bottle of milk, King's Sorrel, three Healing Roots, Earth Aloe, Dragonroot and two tablespoons of honey.", "The correct mixture awards 900 XP and +50 maximum HP. Save before the ensuing scripted scenes: Ana describes throwing away the remaining potion, and the Water Mages summon you for a hearing.", "Attend the monastery cathedral judgment for another 1,000 XP. After this resolution you can once again rest to restore health."),
            reward = "Best medicine sequence: 900 XP and a permanent +50 maximum HP, followed by 1,000 XP after the mages' hearing. The chapter's monastery equipment recovery comes next.",
            warnings = "The order of Dagobert's ingredients matters. Earlier vague recovery advice missed important Light, Meatbug and Telekinesis puzzles. Save before the ending cutscenes; some builds can stall there.",
            searchTags = listOf("CHAPTER 5 — STABILITY", "", "Guild/story route", "Canonical quest"),
        ),
        Quest(
            id = "AR-C5-002",
            chapter = 5,
            playOrder = 2,
            title = "The Coming Storm (Part I)",
            category = "MAIN STORY — Guild/story route",
            giver = "Automatic after the Water Mages' hearing; Kessel and Riordian advance it",
            location = "Monastery → Vardhal",
            prerequisites = "Chapter 5; complete From Bad to Worse and the monastery tribunal.",
            summary = "Recover all confiscated equipment, hear the mages' decision and arrange the Vardhal expedition with Kessel and Riordian.",
            walkthroughSteps = listOf("Follow the novice to the tower in the FIRST monastery courtyard and open the storage chest to recover all confiscated equipment. Open the recovered BAG in your inventory and re-equip the items, including the Monastery Teleportation Rune.", "Talk with Kessel by the cathedral entrance; he can give you the Report of the Interrogations about Jorn.", "Enter the cathedral with Kessel and Riordian for the council's answer. Kessel rejects the decision to remain passive and proposes retrieving the Peacemaker in Vardhal.", "Riordian approves and gives you the Corridors of Vardhal book; ask about the mysterious library deep in the fortress.", "Leave the monastery. Riordian and Kessel travel to Vardhal; faction and Royal Envoy side quests can still be completed before you join them."),
            reward = "All previously confiscated equipment and the Monastery Teleportation Rune are recovered; receive Corridors of Vardhal and access to the Vardhal expedition storyline.",
            warnings = "The equipment is in a CHEST in the tower of the first courtyard, not loose in the infirmary; open the bag inside inventory after collecting it. Later routes to Bermar's Farm and Sailor's Retreat can be blocked by the orc invasion.",
            searchTags = listOf("CHAPTER 5 — STABILITY", "", "Guild/story route", "Canonical quest"),
        ),
        Quest(
            id = "AR-C5-003",
            chapter = 5,
            playOrder = 3,
            title = "Crownless King",
            category = "MAIN STORY — Guild/story route",
            giver = "Guild leader / Winstan",
            location = "Archolos → Scoundrels’ Haven",
            prerequisites = "Route: Guild/story route",
            summary = "Deliver the surrender terms to Cortez, defeat him and help clear the Haven.",
            walkthroughSteps = listOf("Before accepting/advancing, finish every trader, teacher and side quest you still need in Scoundrels’ Haven; the settlement is emptied afterward.", "Meet Winstan outside the City Guard HQ and take Roderich’s Terms Of Surrender.", "Teleport/travel to Scoundrels’ Haven and find Cortez training in the Arena.", "Present the terms; Cortez refuses, so defeat him in the duel.", "Deal with the remaining Haven inhabitants/fighters as the allied City Guard and Merchants’ Guild assault unfolds.", "Speak with Winstan and Garos outside, then return to your guild leader for the final promotion/reward."),
            reward = "Scoundrels’ Haven is destroyed/emptied and Marvin receives the highest guild promotion.",
            warnings = "This permanently removes most Haven NPCs and services. Shop and finish quests before starting.",
            searchTags = listOf("CHAPTER 5 — STABILITY", "", "Guild/story route", "Canonical quest"),
        ),
        Quest(
            id = "AR-C5-004",
            chapter = 5,
            playOrder = 4,
            title = "In The Service Of His Majesty (Part II)",
            category = "FACTION QUEST — Royal Envoy",
            giver = "Grayson",
            location = "Archolos Town Hall",
            prerequisites = "Route: Royal Envoy",
            summary = "Continue working for Grayson and accept the political destabilisation assignment.",
            walkthroughSteps = listOf("After returning to the city in Chapter 5, go to the top floor of Town Hall and speak with Grayson.", "Confirm that you are still serving the Royal Envoy.", "Exhaust his briefing about the political situation and the band In Extremo.", "Accept In Extreme Conditions and read any note/instructions he gives you before leaving."),
            reward = "In Extreme Conditions becomes active.",
            warnings = "",
            searchTags = listOf("CHAPTER 5 — STABILITY", "", "Royal Envoy", "Canonical quest"),
        ),
        Quest(
            id = "AR-C5-005",
            chapter = 5,
            playOrder = 5,
            title = "In Extreme Conditions",
            category = "FACTION QUEST — Royal Envoy",
            giver = "Grayson / Huxley",
            location = "Archolos Harbour",
            prerequisites = "Route: Royal Envoy",
            summary = "Create evidence that In Extremo insulted the King, either personally at the concert or through Huxley’s framing plan.",
            walkthroughSteps = listOf("Ask Grayson whether you will frame the band yourself or use Huxley. Make a save before choosing.", "If doing it yourself, attend the evening concert at the Harbour fish market and use the dialogue responses that steer Unicorn toward the required insulting statements without openly mentioning the King too soon.", "If using Huxley, follow his instructions for planting/producing the incriminating evidence and meet him at the specified time/location.", "Return to Grayson with the resulting proof/testimony and finish the report."),
            reward = "Grayson gains the political pretext he wanted and the Royal Envoy line continues.",
            warnings = "",
            searchTags = listOf("CHAPTER 5 — STABILITY", "", "Royal Envoy", "Canonical quest"),
        ),
        Quest(
            id = "AR-C5-006",
            chapter = 5,
            playOrder = 6,
            title = "A Ship In Port Is Safe",
            category = "FACTION QUEST — Royal Envoy",
            giver = "Grayson / Huxley",
            location = "Archolos shipyard",
            prerequisites = "Route: Royal Envoy",
            summary = "Investigate shipyard sabotage, lure out Anskar and resolve the confrontation without killing him.",
            walkthroughSteps = listOf("Speak with Grayson, then meet Huxley outside the shipyard.", "Perform enough fake sabotage from Huxley’s list to draw out the real culprit: steal Dack’s documents, damage the tool crates, ruin the stored wood and/or spread rat bait.", "Search upward through the shipyard building until you find Huxley tied up on the third floor with Anskar and Richard.", "Demand that Anskar release Huxley; Richard attacks, so defeat Richard only.", "Do not attack Anskar. Free Huxley and let the sequence return you to Grayson.", "Watch Grayson and Anskar resolve the misunderstanding and complete the report."),
            reward = "The shipyard sabotage case is resolved and Anskar survives to face Grayson.",
            warnings = "Do not kill Anskar; the intended resolution requires him alive.",
            searchTags = listOf("CHAPTER 5 — STABILITY", "", "Royal Envoy", "Canonical quest"),
        ),
        Quest(
            id = "AR-C5-007",
            chapter = 5,
            playOrder = 7,
            title = "Org Plague",
            category = "FACTION QUEST — Royal Envoy",
            giver = "Grayson",
            location = "Archolos / island-wide orc camps",
            prerequisites = "Route: Royal Envoy",
            summary = "Lead the coordinated campaign against five Orc camps around Archolos.",
            walkthroughSteps = listOf("Read Grayson’s Scouting Report, then deliver his letters to Roderich and Lorenzo and attend the command briefing.", "Clear the five major Orc positions with the assigned officers: the western start-beach area, western marsh/Haven coast, lighthouse island, the cave between Rita’s Vineyard and the southern marshes, and Bermar’s Farm.", "At each camp, speak with the named commander before attacking so the allied squad engages correctly. Let the immortal/essential officer draw aggro and target shamans/archers yourself.", "Loot healing items and weapons between battles, then report back to headquarters after each stage if the journal requests it.", "After the large Bermar’s Farm assault, return to Grayson in Old Town."),
            reward = "Grayson considers the Orc invasion contained and completes the Royal Envoy questline.",
            warnings = "This is a very long combat quest. Stock healing and ranged ammunition before starting.",
            searchTags = listOf("CHAPTER 5 — STABILITY", "", "Royal Envoy", "Canonical quest"),
        ),
        Quest(
            id = "AR-C5-008",
            chapter = 5,
            playOrder = 8,
            title = "In The Service Of His Majesty (Part III)",
            category = "FACTION QUEST — Royal Envoy",
            giver = "Grayson",
            location = "Archolos Town Hall",
            prerequisites = "Route: Royal Envoy",
            summary = "Complete Grayson’s final service term after the shipyard and Orc crisis.",
            walkthroughSteps = listOf("Return to Grayson after the preceding Royal Envoy missions and exhaust his final debrief.", "Complete any remaining Royal Envoy objective named in the journal before asking about passage/status on the mainland.", "Collect the promised rank/armour/title rewards once Grayson recognizes the completed service.", "Finish all Town Hall dialogue so the Royal Envoy branch closes cleanly."),
            reward = "Grayson’s service chain is complete and Marvin receives the promised recognition.",
            warnings = "",
            searchTags = listOf("CHAPTER 5 — STABILITY", "", "Royal Envoy", "Canonical quest"),
        ),
        Quest(
            id = "AR-C5-009",
            chapter = 5,
            playOrder = 9,
            title = "Where There Is Gold, There Is Trouble",
            category = "MAIN STORY — Guild/story route",
            giver = "Oktav / City Guard",
            location = "Cave from Missing In Action",
            prerequisites = "Route: Guild/story route",
            summary = "Lead the Guard strike on the gold-related bandit operation.",
            walkthroughSteps = listOf("Take the final Guard assignment from Oktav and return to the cave network used during Missing In Action.", "Choose the upper or lower entrance based on your build; scout both before committing the squad.", "Wait for evening if the journal/plan calls for a night assault.", "Lead the Guard force through the cave, focusing dangerous ranged enemies first so your allies survive.", "Search the operation for gold/evidence and report the result to Oktav."),
            reward = "The late City Guard operation is complete.",
            warnings = "Save before choosing the assault entrance; allied survival can depend on the route.",
            searchTags = listOf("CHAPTER 5 — STABILITY", "", "Guild/story route", "Canonical quest"),
        ),
        Quest(
            id = "AR-C5-010",
            chapter = 5,
            playOrder = 10,
            title = "Closing The Business",
            category = "MAIN STORY — Guild/story route",
            giver = "Lorenzo / Araxos",
            location = "Amber Coast",
            prerequisites = "Route: Guild/story route",
            summary = "Sabotage the smugglers’ operation and complete the final Araxos assignment.",
            walkthroughSteps = listOf("Speak with Lorenzo and prepare the requested Rat Poison and Speed potion/consumable before leaving.", "Travel to the Amber Coast in the evening as instructed.", "Scout the smugglers’ camp and identify the sabotage targets before attacking anyone.", "Use the poison/speed plan to compromise the operation, then deal with surviving smugglers only when necessary.", "Return to Lorenzo and close the Araxos business."),
            reward = "The final Merchants’ Guild assignment is complete.",
            warnings = "Make a safety save before entering the Amber Coast camp; stealth/sabotage choices can be difficult to undo.",
            searchTags = listOf("CHAPTER 5 — STABILITY", "", "Guild/story route", "Canonical quest"),
        ),
        Quest(
            id = "AR-C5-011",
            chapter = 5,
            playOrder = 11,
            title = "Keeper Of The Balance (Part I)",
            category = "FACTION QUEST — Ring of Water",
            giver = "Kessel / Ring of Water",
            location = "Archolos",
            prerequisites = "Route: Ring of Water",
            summary = "Read the Shouters information and begin silencing Volker’s propaganda network.",
            walkthroughSteps = listOf("Speak with Kessel and accept the Ring of Water assignment.", "Read About Volker’s Shouters so the target locations become clear.", "Visit the propaganda speaker locations and investigate who is organizing each crowd.", "At the first major target near the high bridge between Old Town and the Guard area, speak with Oktav and then Venzel about a forged speech/solution.", "Complete the first set of interventions and return to Kessel when the journal updates."),
            reward = "The Ring of Water operation advances to Silence The Screamer.",
            warnings = "",
            searchTags = listOf("CHAPTER 5 — STABILITY", "", "Ring of Water", "Canonical quest"),
        ),
        Quest(
            id = "AR-C5-012",
            chapter = 5,
            playOrder = 12,
            title = "Silence The Screamer",
            category = "FACTION QUEST — Ring of Water",
            giver = "Kessel / Ring of Water",
            location = "Archolos",
            prerequisites = "Route: Ring of Water",
            summary = "Neutralize all three propaganda speakers without turning the whole city hostile.",
            walkthroughSteps = listOf("Use the target list from About Volker’s Shouters and visit each of the three speaker locations.", "For the bridge/Guard-side speaker, use the Oktav → Venzel forged-speech route if available.", "At the other two locations, exhaust peaceful/intimidation options before drawing weapons in crowded streets.", "Confirm in the journal that all three speakers are neutralized.", "Return to Kessel for the next Keeper of the Balance stage."),
            reward = "All three Shouters are silenced and the Ring of Water route advances.",
            warnings = "",
            searchTags = listOf("CHAPTER 5 — STABILITY", "", "Ring of Water", "Canonical quest"),
        ),
        Quest(
            id = "AR-C5-013",
            chapter = 5,
            playOrder = 13,
            title = "Keeper Of The Balance (Part II)",
            category = "FACTION QUEST — Ring of Water",
            giver = "Kessel",
            location = "River southwest of Silbach / ruined temple",
            prerequisites = "Route: Ring of Water",
            summary = "Complete the Ring of Water purification rite and receive full membership.",
            walkthroughSteps = listOf("After Silence The Screamer, speak with Kessel and agree to the initiation.", "Meet him at the river southwest of Silbach, on the far side of the bridge built earlier with Uwe.", "Follow Kessel uphill through the ruined temple and past the frogmen to the ritual pool.", "Remove your armour, enter the water and wash when instructed.", "Speak with Kessel after the rite."),
            reward = "Marvin joins the Ring of Water and receives the Ring armour/ring plus the associated training access.",
            warnings = "Store guild armour outside the old guild compound before leaving that guild, or nameless members may confiscate it.",
            searchTags = listOf("CHAPTER 5 — STABILITY", "", "Ring of Water", "Canonical quest"),
        ),
        Quest(
            id = "AR-C5-014",
            chapter = 5,
            playOrder = 14,
            title = "The Coming Storm (Part II)",
            category = "MAIN STORY — Guild/story route",
            giver = "Riordian / Kessel",
            location = "Road beyond Bermar Farm",
            prerequisites = "Route: Guild/story route",
            summary = "Reach the Vardhal expedition camp and prepare to enter the ruins.",
            walkthroughSteps = listOf("Travel northwest beyond Bermar Farm using the newly opened passage.", "Find Riordian and Kessel at the expedition staging area and exhaust both dialogues.", "Check your recruited workers/guards and buy healing, food and ammunition before entering Vardhal.", "Follow the expedition toward the bridge and courtyard.", "Save before activating the ruin mechanisms that close the gate behind you."),
            reward = "The expedition reaches Vardhal and Castle Ruins begins.",
            warnings = "Vardhal entry is a near point of no return. Check your unfinished faction quests and recruitments before committing to the inner fortress.",
            searchTags = listOf("CHAPTER 5 — VARDHAL EXPEDITION", "", "Guild/story route", "Canonical quest"),
        ),
        Quest(
            id = "AR-C5-015",
            chapter = 5,
            playOrder = 15,
            title = "Castle Ruins",
            category = "MAIN STORY — Guild/story route",
            giver = "Kessel / expedition",
            location = "Vardhal",
            prerequisites = "Route: Guild/story route",
            summary = "Explore the besieged Vardhal courtyard, defeat the Undead Battle Mage and reunite the three fragments needed to open its inner gate.",
            walkthroughSteps = listOf("Follow Kessel and Riordian into Vardhal's outer courtyard. The entrance closes and undead repeatedly attack; allied companions can absorb their first waves.", "Climb the collapsed section of outer wall and run past endlessly respawning zombies to the tower teleport circle. Step on it to fight the UNDEAD BATTLE MAGE controlling them.", "Defeat the mage, loot his body for the FIRST Key Fragment, and use the nearby winch to open the inner gate before teleporting back to the ramparts.", "Beyond the inner gate, examine the corpse by the huge double door for Orders and the SECOND Key Fragment. Try to open the door, then show the fragments to Riordian.", "Return to Archolos's Shadows of the Past museum near Volker's mansion. Buy the THIRD fragment from Miron for 1,000 gold, reduced to 500 if you previously acquired the Old Town house through Extreme Home Makeover.", "Bring all three fragments to Riordian at Vardhal (2,500 XP). The fortress outer gate and courtyard teleport rune allow revisits during this preparation phase."),
            reward = "2,500 XP for returning all three Key Fragments to Riordian, plus access to the later expedition-preparation quests and Ring of Water recruitment.",
            warnings = "KILL THE BATTLE MAGE instead of trying to kill the endlessly respawning undead; all his minions fall when he dies. Loot both fragments in Vardhal and buy the third from museum curator Miron. The earlier generic courtyard account omitted this puzzle.",
            searchTags = listOf("CHAPTER 5 — VARDHAL EXPEDITION", "", "Guild/story route", "Canonical quest"),
        ),
        Quest(
            id = "AR-C5-016",
            chapter = 5,
            playOrder = 16,
            title = "Preparations For The Expedition (Part I)",
            category = "MAIN STORY — Guild/story route",
            giver = "Kessel",
            location = "Vardhal / whole island",
            prerequisites = "Chapter 5; finish Castle Ruins, obtain all three fragments and discuss expedition support with Kessel.",
            summary = "Gather provisions and complete the three personnel subquests for the Vardhal expedition.",
            walkthroughSteps = listOf("After Castle Ruins, speak with Kessel and exhaust every preparation topic.", "Ask former quest contacts for provisions; useful suppliers include Bastian, Helga, Rita, Tomas, Zachary, completed apprenticeship masters and other NPCs you helped earlier.", "Start and complete Trained People, A Job For Tough Guys and Workforce.", "Return to Kessel whenever a category is complete and let him acknowledge the recruits/supplies.", "Do not proceed to Part II until you have finished all optional preparation you want; stronger recruitment makes Vardhal easier."),
            reward = "All expedition preparation categories are ready and Kessel can move to the final departure stage.",
            warnings = "Supplier support is optional but valuable; existing side-quest completions determine Bastian, Bevin, Dima, Ezekiel, Pablo, Rita, Tomas and other donors. Complete your existing faction work before assigning its NPCs to Vardhal.",
            searchTags = listOf("CHAPTER 5 — VARDHAL EXPEDITION", "", "Guild/story route", "Canonical quest"),
        ),
        Quest(
            id = "AR-C5-017",
            chapter = 5,
            playOrder = 17,
            title = "Trained People",
            category = "MAIN STORY — Guild/story route",
            giver = "Kessel",
            location = "Vardhal / earlier quest contacts",
            prerequisites = "Route: Guild/story route",
            summary = "Provide Kessel with two miners and two woodworkers from people Marvin helped earlier.",
            walkthroughSteps = listOf("Finish Kessel’s initial preparation dialogue, then choose “As for the workers…” to unlock the recruitment list.", "Name two suitable woodworkers from options such as Lowell, Ruud, Uwe or Veigo, depending on earlier quests.", "Name two miners from options such as Refir/Neral or Nivel/Miroh; Loafs can count as two miners on the Merchants’ Guild route.", "Wait a day or two after giving the names so Kessel can organize travel.", "Return to Vardhal and confirm the workers have arrived."),
            reward = "Complete Kessel's labor recruitment with two woodworkers and two miners (Loafs counts as two); exact stand-alone XP for this subquest has not been independently corroborated.",
            warnings = "Do not try to choose workers before exhausting Kessel's initial preparation dialogue and selecting 'As for the workers...' Recruited NPCs may require resting before they appear in Vardhal.",
            searchTags = listOf("CHAPTER 5 — VARDHAL EXPEDITION", "", "Guild/story route", "Canonical quest"),
        ),
        Quest(
            id = "AR-C5-018",
            chapter = 5,
            playOrder = 18,
            title = "A Job For Tough Guys",
            category = "MAIN STORY — Guild/story route",
            giver = "Kessel",
            location = "Archolos / whole island",
            prerequisites = "Route: Guild/story route",
            summary = "Recruit four strong fighters for the Vardhal expedition.",
            walkthroughSteps = listOf("Ask Kessel about combat manpower, then choose four available warriors. Candidates include Arwid/Berto for City Guard, Caramon for Araxos, Big Ben if spared, Candac, Gard, Grif, Havard, Ilse, Javad and Lutz depending on prior quests.", "If recruiting Fane for Eternal Rest, recruit him before the four main warriors or the option can disappear.", "For Ilse, defeat her but do not steal her hammer if you expect her to fight effectively later.", "Consider recruiting blunt-weapon users such as Big Ben or Ilse because Vardhal is full of undead.", "Return to Kessel after four warriors have agreed to go."),
            reward = "2,500 XP from Kessel after four warriors have agreed to join the expedition; recruitment can also unlock Grif's Nordmarian armor route.",
            warnings = "IMPORTANT: sending guild NPCs to Vardhal can permanently cancel unfinished quests that need them. Recruit Grif if pursuing Nordmarian Heavy Armor; for armor crafting his guild-leaving condition may also apply. Don't loot Ilse's hammer after knocking her down.",
            searchTags = listOf("CHAPTER 5 — VARDHAL EXPEDITION", "", "Guild/story route", "Canonical quest"),
        ),
        Quest(
            id = "AR-C5-019",
            chapter = 5,
            playOrder = 19,
            title = "Workforce",
            category = "MAIN STORY — Guild/story route",
            giver = "Kessel / Varin / Duster",
            location = "Archolos Harbour / southwest road",
            prerequisites = "Route: Guild/story route",
            summary = "Recruit Varin and Duster, then finish Duster’s bridge-demolition setup.",
            walkthroughSteps = listOf("Find Varin at the Harbour dockside and recruit him directly.", "Ask the nearby guard where Duster went, then travel southwest of Archolos toward Bermar’s Farm and find Duster with two guards.", "Pay Duster 400 gold and agree to help with the Orc roadblock.", "Take his two Powder Kegs, climb the ladder and place one on each side of the log bridge/root crossing.", "Report to Duster so he agrees to travel. Rest after recruiting him so his relocation triggers, then report both workers to Kessel."),
            reward = "2,500 XP from Kessel after Varin and Duster join. Duster requires 400 gold and the placement of two powder barrels at the log bridge.",
            warnings = "REST after persuading Duster, or he may fail to relocate to Vardhal. Duster's 400 gold is a fee you pay, not a reward.",
            searchTags = listOf("CHAPTER 5 — VARDHAL EXPEDITION", "", "Guild/story route", "Canonical quest"),
        ),
        Quest(
            id = "AR-C5-020",
            chapter = 5,
            playOrder = 20,
            title = "Preparations For The Expedition (Part II)",
            category = "MAIN STORY — Guild/story route",
            giver = "Kessel",
            location = "Vardhal",
            prerequisites = "Route: Guild/story route",
            summary = "Confirm every preparation category and begin the final move into Vardhal.",
            walkthroughSteps = listOf("Finish Part I, Trained People, A Job For Tough Guys and Workforce.", "Use this last open-world window to upgrade armour/weapons, buy healing, lockpicks and torches, cook permanent/stat food and clear unfinished quests.", "Speak with Kessel and report that every preparation is ready.", "Accept the final departure/entry dialogue."),
            reward = "7,500 XP from Kessel when all required expedition preparations are completed.",
            warnings = "MAJOR POINT OF NO RETURN AHEAD: before opening Vardhal's rebuilt gate, finish all outside quests except Where There Is Gold, There Is Trouble and Closing the Business, which the current guide lists as exceptions.",
            searchTags = listOf("CHAPTER 5 — VARDHAL EXPEDITION", "", "Guild/story route", "Canonical quest"),
        ),
        Quest(
            id = "AR-C5-021",
            chapter = 5,
            playOrder = 21,
            title = "The Vardhal Underground (Part I: The Great Hall)",
            category = "MAIN STORY — Guild/story route",
            giver = "Riordian / Kessel",
            location = "Vardhal interior",
            prerequisites = "Chapter 5; finish Preparations for the Expedition (Part II), then open Vardhal's rebuilt gate.",
            summary = "Open the fortress, establish the expedition camp and collect both Guard’s Greatswords needed for the Great Hall door.",
            walkthroughSteps = listOf("MAKE AN ARCHIVE SAVE before opening the rebuilt inner gate. Entering Vardhal fails most unfinished outside quests; only Where There Is Gold, There Is Trouble and Closing the Business are specifically excepted.", "Before entering, ask Viktor in Silbach to look after your dog if you have one; upgrade armor, cook permanent-stat meals, and stock healing, lockpicks and torches.", "Enter with the expedition and fight until Riordian and Kessel reach the camp. The damaged bridge collapses behind part of the party.", "Talk to Kessel at the camp and choose 'Teach me something' for +3 Strength, +3 Dexterity and +10 maximum HP.", "Use the two switches to open the gate to the Great Hall, clear the undead and ignite seven braziers with a torch.", "Search the side routes for the two Guard's Greatswords: one beyond the flooded crypt and another held by the training-room Tomb Guardian after Duster clears rubble.", "Place both Greatswords on pedestals near the great rear doors. Return to Riordian and camp whenever repairs or allied rest are needed."),
            reward = "Access to Vardhal's deeper temple. Kessel's optional camp training gives +3 Strength, +3 Dexterity and +10 HP. Completing the Great Hall mechanisms allows Part II.",
            warnings = "ACTUAL POINT OF NO RETURN: all unfinished quests other than the two explicitly exempted guild finales are FAILED on entering. Ask Viktor to look after your dog. The +3/+3/+10 Kessel training is easily missed.",
            searchTags = listOf("CHAPTER 5 — VARDHAL EXPEDITION", "", "Guild/story route", "Canonical quest"),
        ),
        Quest(
            id = "AR-C5-022",
            chapter = 5,
            playOrder = 22,
            title = "The Vardhal Underground (Part II: The Pedestal Maze, Catacombs & Vault)",
            category = "MAIN STORY — Guild/story route",
            giver = "Riordian / expedition",
            location = "Vardhal depths",
            prerequisites = "Route: Guild/story route",
            summary = "Solve the pedestal maze and throne puzzle, cross the catacombs, loot the vault under time pressure and escape with the Peacemaker.",
            walkthroughSteps = listOf("In the pedestal maze, operate the first two pedestals once each, turn left after the second, operate the third, turn left again and use the winch in the corner room.", "Enter the Throne Room and use the wall winch. Return to Riordian for help with the floor panels, then bring two warriors: place them on the inner upper-left and upper-right squares and stand on the panel nearest the throne.", "Kill the awakened Undead Lord, loot its unique weapon and descend into the catacombs.", "Kill the gargoyle, take the Burial Chamber key, return to camp when warned and kill the awakened gargoyles there; then continue alone after speaking with Kessel/Riordian.", "In the Burial Chamber route, find the additional Guard’s Greatsword from the Tomb Guardian sarcophagus and use it on the notched door. Make an archive save before entering the vault.", "In the vault, loot only priority treasure quickly before the gas/closing-door trap; follow Kessel to the Peacemaker chamber and take the Peacemaker from the altar.", "Escape through the kicked wall, follow the purple crystals, drop through the hole, reach Riordian and then test Varin’s repaired bridge.", "Resolve the warrior sacrifice/explosion choice and exit the fortress with Riordian."),
            reward = "Marvin escapes Vardhal with the Peacemaker and receives the large completion reward.",
            warnings = "This is a long one-way endgame gauntlet. Make a separate save at the notched-door/vault stage; the vault has a time-sensitive gas trap. Do not try to take every treasure before escaping.",
            searchTags = listOf("CHAPTER 5 — VARDHAL EXPEDITION", "", "Guild/story route", "Canonical quest"),
        ),
        Quest(
            id = "AR-C5-023",
            chapter = 5,
            playOrder = 23,
            title = "Rightful Heir",
            category = "MAIN STORY — Guild/story route",
            giver = "Ulryk",
            location = "Outside Vardhal → Monastery",
            prerequisites = "Route: Guild/story route",
            summary = "Survive Ulryk’s ambush by surrendering the Peacemaker, then report to the Monastery.",
            walkthroughSteps = listOf("After escaping Vardhal with the Peacemaker, speak to Riordian outside for approximately 7,500 XP, then SAVE before crossing the next open clearing.", "Ulryk and the Wolf Sons ambush the expedition and demand the Peacemaker. You may initially lie, but he knows you have the artifact.", "When Ulryk issues his last demand, surrender the Peacemaker. Refusal leads to Marvin's death rather than a normal victory.", "Riordian teleports you to the monastery for 1,000 XP; talk to Notger and Ingolf about what happened to the Peacemaker and the Old Scale.", "The chapter transition follows the final monastery debrief and begins Black Hour in Chapter 6."),
            reward = "About 7,500 XP for completing Vardhal and 1,000 XP after Riordian's monastery teleport; transitions into Chapter 6.",
            warnings = "Ulryk's final demand is NOT a fair optional duel: refusing it kills Marvin. Save before the outside Vardhal ambush.",
            searchTags = listOf("CHAPTER 5 — VARDHAL EXPEDITION", "", "Guild/story route", "Canonical quest"),
        ),
        Quest(
            id = "AR-C5-024",
            chapter = 5,
            playOrder = 24,
            title = "Small Gift",
            category = "SIDE QUEST — All routes",
            giver = "Southerner",
            location = "Archolos Old Town",
            prerequisites = "Route: All routes",
            summary = "Plant a decorated casket in the Corsair’s Hideout hotel.",
            walkthroughSteps = listOf("Meet the Southerner outside the City Guard compound in Chapter 5.", "Take the casket and rent a room at Corsair’s Hideout for 100 gold so Limak lets you upstairs.", "Plant the box in the top-floor corner indicated by the quest.", "Leave and return to the original meeting place.", "Open the pouch/note left on the ledge for your reimbursement and reward."),
            reward = "The delivery/assassination setup is complete.",
            warnings = "You can later revisit the hotel to see the consequences.",
            searchTags = listOf("LATE-GAME REGIONAL SIDE QUESTS", "ARCHOLOS — LATE GAME", "All routes", "Canonical side quest"),
        ),
        Quest(
            id = "AR-C5-025",
            chapter = 5,
            playOrder = 25,
            title = "The Biggest Will Be The Tiniest",
            category = "SIDE QUEST — All routes",
            giver = "Ingolf",
            location = "Monastery",
            prerequisites = "Route: All routes",
            summary = "Survive Ingolf’s humility lesson after being shrunk to rat size.",
            walkthroughSteps = listOf("Speak with Ingolf in Chapter 5 and admit that you may be acting recklessly.", "After he shrinks you, use the shelves, boxes and ramps to descend safely.", "Avoid enemies/hazards that are lethal at tiny size.", "Reach the floor and follow the route that restores your normal form.", "Speak with Ingolf again."),
            reward = "You return to normal size and complete the lesson.",
            warnings = "",
            searchTags = listOf("LATE-GAME REGIONAL SIDE QUESTS", "MONASTERY", "All routes", "Canonical side quest"),
        ),
        Quest(
            id = "AR-C5-026",
            chapter = 5,
            playOrder = 26,
            title = "Warrior Of Innos",
            category = "SIDE QUEST — All routes",
            giver = "Candac / Monastery novices",
            location = "Monastery graveyard",
            prerequisites = "Route: All routes",
            summary = "Investigate the graveyard and clear the undead with Candac.",
            walkthroughSteps = listOf("When The Coming Storm points toward Vardhal, return to Candac at the Monastery.", "Question the novices at the far side of the courtyard about the graveyard.", "Inspect the three recent animal burials and the suspicious Innos shrine.", "Report to Candac and arrange to meet at midnight.", "Follow him downhill and clear goblin skeletons, then skeleton warriors/archers.", "Finish the chapel/graveyard investigation and report to the novices."),
            reward = "Candac becomes available for later Vardhal recruitment; you receive magical rewards.",
            warnings = "Archive-save before the graveyard fight because Candac can pathfind badly.",
            searchTags = listOf("LATE-GAME REGIONAL SIDE QUESTS", "MONASTERY", "All routes", "Canonical side quest"),
        ),
        Quest(
            id = "AR-C5-027",
            chapter = 5,
            playOrder = 27,
            title = "Collector",
            category = "SIDE QUEST — All routes",
            giver = "Monastery gardener",
            location = "Monastery",
            prerequisites = "Route: All routes",
            summary = "Bring one seed/root of each requested plant.",
            walkthroughSteps = listOf("Speak with the Gardener in the courtyard.", "Collect one Fire Nettle, Fire Root, Healing Root and Blue Elder.", "Buy them from alchemists or gather them through advanced alchemy/harvesting.", "Return all four items."),
            reward = "You receive life/mana elixirs.",
            warnings = "",
            searchTags = listOf("LATE-GAME REGIONAL SIDE QUESTS", "MONASTERY", "All routes", "Canonical side quest"),
        ),
        Quest(
            id = "AR-C5-028",
            chapter = 5,
            playOrder = 28,
            title = "Hawkeye",
            category = "SIDE QUEST — All routes",
            giver = "Artur",
            location = "Water Mage Monastery",
            prerequisites = "Route: All routes",
            summary = "Recover Artur’s missing robe, pike and diary from the monastery rooftops, then choose whether to return them or obey Othekar.",
            walkthroughSteps = listOf("Speak with Artur and note the three missing items.", "Use the supplied/available Telekinesis scrolls and rooftop access to collect the robe, pike and diary.", "After all three are in hand, listen when Othekar asks you not to return them to Artur.", "Choose either to obey Othekar and cancel/close the return, or ignore him and give Artur all three items for the larger reward."),
            reward = "The Artur/Othekar dispute is resolved according to your choice.",
            warnings = "Returning the items to Artur gives the larger XP reward and a Pure Life Energy potion.",
            searchTags = listOf("LATE-GAME REGIONAL SIDE QUESTS", "MONASTERY", "All routes", "Canonical side quest"),
        ),
        Quest(
            id = "AR-C5-029",
            chapter = 5,
            playOrder = 29,
            title = "A Wing Or A Leg?",
            category = "SIDE QUEST — All routes",
            giver = "Rierol / Carden",
            location = "Monastery → Bodowin’s hut",
            prerequisites = "Route: All routes",
            summary = "Investigate the empowered scavengers near Bodowin, uncover his experiments and decide his fate.",
            walkthroughSteps = listOf("Speak with Rierol, then Carden, and travel to the area around Bodowin’s hut between Silbach and Valerio’s Vineyard.", "Kill the four groups of exhausted/empowered scavengers and pick a Scorching Fire Root from Bodowin’s garden.", "Search the corpse on the approach for the bellows, pick the hut lock, inspect the dead scavenger and read Research Journals I–IV.", "Save before leaving. Bodowin attacks after drinking a regeneration potion; kite him for roughly ten seconds until the regeneration wears off, then defeat him.", "Choose whether to spare/banish him or kill him; if killed, use his key for the nearby dungeon.", "Return to Rierol with the evidence."),
            reward = "Rierol rewards the investigation and Bodowin’s experiments are stopped.",
            warnings = "Buy anything you want from Bodowin before starting; this can be your last chance to trade with him.",
            searchTags = listOf("LATE-GAME REGIONAL SIDE QUESTS", "MONASTERY", "All routes", "Canonical side quest"),
        ),
    )
}
