package com.sliverzfx.gothicquest

internal object ArcholosGameplayTipsData {
    val entries: List<ToolReferenceEntry> = listOf(
        ToolReferenceEntry("arch_gameplay_patch_review", "VERSION NOTES", "Patch review through 1.2.11", "Official updates 1.2.3–1.2.11 were reviewed. They document trainer, trophy-sale, food-bonus and quest fixes, but do not announce numerical equipment-stat changes. Displayed stats remain attributed to the v1.2.2 export; this review does not certify every value against the latest game scripts.", source = "https://steamcommunity.com/games/1467450/announcements/detail/3891737145573175969"),
        ToolReferenceEntry("arch_gameplay_early_armor", "EARLY EQUIPMENT", "Armor options before joining a guild", "Veit in Silbach sells a light leather armor for 300 gold. Petra sells light chainmail for 500 gold, reduced to 250 after her Last Batch of Stuff quest. Both are chapter-one options in the acquisition index; check their separate protection cards before spending gold.", source = "https://docs.google.com/spreadsheets/d/1Z5O00oK-OYpmjtniR5t3s__TxNq8eMuwzn8ftJPeNpQ/edit#gid=1839435141"),
        ToolReferenceEntry("arch_gameplay_lumberjack", "EARLY EQUIPMENT", "Earn a lumberjack outfit", "The acquisition index lists Knut at the Lumberjack Camp as the source after cutting lumber. The relevant conversation requires 20 strength. This is an alternative early outfit rather than a guild armor.", source = "https://docs.google.com/spreadsheets/d/1Z5O00oK-OYpmjtniR5t3s__TxNq8eMuwzn8ftJPeNpQ/edit#gid=1839435141"),
        ToolReferenceEntry("arch_gameplay_faction_armor", "GUILD EQUIPMENT", "Guild armor follows promotion", "Joining the Guards or Araxos unlocks the corresponding basic outfit. Later swordsman, crossbowman and hunter armors depend on that guild route and promotion. A high stat by itself does not unlock a faction reward.", source = "https://docs.google.com/spreadsheets/d/1Z5O00oK-OYpmjtniR5t3s__TxNq8eMuwzn8ftJPeNpQ/edit#gid=1839435141"),
        ToolReferenceEntry("arch_gameplay_upgrade_route", "ARMOR", "Upgraded armor starts with the base piece", "Enhanced and superior cards identify separate upgraded IDs. Their acquisition text explicitly begins with the base armor. Obtain that armor first and use the armor upgrade service; inserting an upgraded version bypasses the normal process.", source = "https://docs.google.com/spreadsheets/d/1Z5O00oK-OYpmjtniR5t3s__TxNq8eMuwzn8ftJPeNpQ/edit#gid=1839435141"),
        ToolReferenceEntry("arch_gameplay_diagrams", "CRAFTING", "A diagram seller is not always a weapon seller", "Acquisition lines marked Diagram describe the recipe, not a ready-made weapon. Learn the indicated smithing or bowmaking level, obtain the diagram and required materials, then craft at the appropriate workshop.", source = "https://docs.google.com/spreadsheets/d/1Z5O00oK-OYpmjtniR5t3s__TxNq8eMuwzn8ftJPeNpQ/edit#gid=261322382"),
        ToolReferenceEntry("arch_gameplay_smith_trainer", "TRAINERS", "Odgar’s militia smithing limit changed", "Patch 1.2.3 made Odgar teach smithing through the skilled level for militia members. Do not use an older guide that treats his teaching limit as unchanged for that route.", source = "https://steamcommunity.com/games/1467450/announcements/detail/3218396987408269215"),
        ToolReferenceEntry("arch_gameplay_alchemy_trainer", "TRAINERS", "Yezegan can teach master alchemy", "Since patch 1.2.3, Yezegan teaches potion brewing through master level. Recipe possession and the required crafting skill are separate checks.", source = "https://steamcommunity.com/games/1467450/announcements/detail/3218396987408269215"),
        ToolReferenceEntry("arch_gameplay_bear_sale", "HUNTING & TRADING", "Sell the Gluttonous Bear skin to Frida", "Patch 1.2.4 added a sale option for this specific trophy with Frida. Keep the trophy if you intend to use that dialogue rather than selling it through ordinary trading.", source = "https://steamcommunity.com/games/1467450/announcements/detail/3294958655383840622"),
        ToolReferenceEntry("arch_gameplay_fang_sale", "HUNTING & TRADING", "Markus buys Seashark fangs", "Patch 1.2.4 added the specific fang sale dialogue with Markus. Patch 1.2.5 also added fang extraction to his teaching options.", source = "https://steamcommunity.com/games/1467450/announcements/detail/5241644120323512700"),
        ToolReferenceEntry("arch_gameplay_hunting_costs", "TRAINERS", "Old hunting prices may be wrong", "Patch 1.2.6 corrected hunting-skill learning costs in some conversations. Treat prices copied from older guides as historical rather than guaranteed current charges.", source = "https://steamcommunity.com/games/1467450/announcements/detail/3395173894695725565"),
        ToolReferenceEntry("arch_gameplay_apples", "FOOD", "Apple-based bonuses were corrected", "Patch 1.2.3 fixed strength-bonus counting for apples and dishes containing them. This is a gameplay calculation fix, not a new damage or armor stat; use the patched game when planning food bonuses.", source = "https://steamcommunity.com/games/1467450/announcements/detail/3218396987408269215"),
        ToolReferenceEntry("arch_gameplay_magic_books", "MAGIC", "Collect the complete circle book set", "The acquisition index lists two volumes for circle I, three for II, four for III and five for IV. Search Items for Magic Circle to find each volume’s sources. The official localization confirms that previous circles are prerequisites.", source = "https://docs.google.com/spreadsheets/d/1Z5O00oK-OYpmjtniR5t3s__TxNq8eMuwzn8ftJPeNpQ/edit#gid=126759505"),
        ToolReferenceEntry("arch_gameplay_miron", "MAGIC & TRADING", "Unlock Miron’s shop", "The acquisition index lists Miron’s shop after handing over 30 old coins. His available runes and books depend on the chapter; an unlock does not make every later item available immediately.", source = "https://docs.google.com/spreadsheets/d/1Z5O00oK-OYpmjtniR5t3s__TxNq8eMuwzn8ftJPeNpQ/edit#gid=2118690123"),
        ToolReferenceEntry("arch_gameplay_teleports", "TRAVEL", "Find both a teleport rune and its circle", "Search Items for Teleport to see the rune source and the destination circle separately. Some runes are tied to a quest or story access; the destination name alone does not mean you already have its rune.", source = "https://docs.google.com/spreadsheets/d/1Z5O00oK-OYpmjtniR5t3s__TxNq8eMuwzn8ftJPeNpQ/edit#gid=1721706426"),
        ToolReferenceEntry("arch_gameplay_save_compatibility", "VERSION NOTES", "These patches do not require a fresh playthrough", "The official 1.2.3 and 1.2.4 announcements explicitly state that players can load their existing saves after updating. That statement applies to those maintenance patches; it is not a promise for unrelated mods or future major releases.", source = "https://steamcommunity.com/games/1467450/announcements/detail/3294958655383840622"),
    )
}
