package com.sliverzfx.gothicquest

internal object Gothic3Part2Data {
    val quests = listOf(
        Quest(
            id = "G3-P2-001",
            chapter = 2,
            playOrder = 1,
            title = "Okara needs more people.",
            category = "SAFE",
            giver = "Manning",
            location = "Okara and surrounding wilderness",
            prerequisites = "Meet Manning, Okara's quartermaster and recruiter.",
            summary = "Recruit Randall, Owen, Rakus, Candela, Fraser and Kent from the countryside, and make sure Rufus from the Montera grain farm reaches Okara. Return to Manning after the recruitment chain is complete.",
            walkthroughSteps = listOf("Ask Manning for help populating Okara's rebel camp.", "Find RANDALL at a campfire beside the mine; help him clear the crawlers, then recruit him.", "Find OWEN in the wilderness, give him booze and offer him a home in Okara.", "Find RAKUS in the undead cave; remove his summoned undead and recruit him.", "Find hunters CANDELA and FRASER at the ruins, finish their shadowbeast/boar hunts, and recruit both.", "Find KENT hiding from ripperbeasts in a nearby cave, kill the beasts and ask him to join.", "Help RUFUS escape Montera's grain farm and escort him to Okara.", "Report the available recruits to Manning. After his requirements are met, he can also request five iron ore."),
            reward = "Individual recruits award experience and Okara reputation; each completed recruitment increases Okara manpower.",
            warnings = "Recruitment stages have prerequisites: clear Randall's mine, Rakus's undead, Kent's ripperbeasts and hunters' beasts before asking them to move.",
            searchTags = listOf("Okara needs more people.", "Manning", "Okara and surrounding wilderness", "SAFE")
        ),
        Quest(
            id = "G3-P2-002",
            chapter = 2,
            playOrder = 2,
            title = "Clean out the mine with Randall the fighter.",
            category = "SAFE",
            giver = "Randall",
            location = "West of Okara",
            prerequisites = "",
            summary = "Find Randall at his campfire west of Okara. Agree to help him and enter the nearby mine together. Kill the Minecrawlers in the first section without letting Randall die.",
            walkthroughSteps = listOf("Find Randall at the campfire west of Okara and agree to help with the nearby mine.", "Enter together and fight the Minecrawlers through roughly the first half of the mine. When that section is secured, Randall stops and the escort-style quest completes.", "Return to the quest giver or the named destination after the objective is complete. If no completion message appears, re-check the target area for a surviving enemy, missing quest item, or an unfinished dialogue step.", "Do not leave yet. Randall immediately leaves the remaining Minecrawlers to you, beginning “A rich mine.”"),
            reward = "Verified reward: 1000 XP and +4 Okara reputation.",
            warnings = "",
            searchTags = listOf("Clean out the mine with Randall the fighter.", "Randall", "West of Okara", "SAFE")
        ),
        Quest(
            id = "G3-P2-003",
            chapter = 2,
            playOrder = 3,
            title = "A rich mine.",
            category = "SAFE",
            giver = "Randall",
            location = "Mine west of Okara",
            prerequisites = "",
            summary = "After the first part of Randall's mine is cleared, continue through the remaining tunnels and kill the Minecrawlers so the mine can be worked safely.",
            walkthroughSteps = listOf("This begins after the first half of Randall's mine has been cleared with him.", "Continue deeper without Randall and kill the remaining nine Minecrawlers. Search and mine the tunnels while you are there; the iron ore is useful for Manning's later request.", "Return to the quest giver or the named destination after the objective is complete. If no completion message appears, re-check the target area for a surviving enemy, missing quest item, or an unfinished dialogue step.", "Keep at least five Iron Ore. After all Okara recruits are gathered, Manning asks specifically for five pieces."),
            reward = "Verified: 1500 XP, +4 Okara reputation, +1 Strength and a 500 XP follow-up from Randall.",
            warnings = "",
            searchTags = listOf("A rich mine.", "Randall", "Mine west of Okara", "SAFE")
        ),
        Quest(
            id = "G3-P2-004",
            chapter = 2,
            playOrder = 4,
            title = "Randall should go to Okara.",
            category = "SAFE",
            giver = "Randall",
            location = "Okara wilderness → Okara",
            prerequisites = "",
            summary = "After clearing Randall's mine, tell him Manning is looking for capable people. Randall travels to Okara; report his recruitment to Manning.",
            walkthroughSteps = listOf("Randall sits at a campfire west of Okara. He will not join simply because you ask him. First complete his two mine quests: clear the first section with him, then finish the remaining Minecrawlers yourself.", "After the mine is safe, ask Randall to support Okara. He requires 300 gold before agreeing. Pay him; he then heads for the Rebel camp. Report the successful recruitment to Manning.", "Return to the quest giver or the named destination after the objective is complete. If no completion message appears, re-check the target area for a surviving enemy, missing quest item, or an unfinished dialogue step.", "This is one of the easy-to-miss requirements of “Okara needs more people.”"),
            reward = "Verified: 1000 XP, +8 Okara reputation, +1 Rebel reputation; Manning adds 500 XP and 500 gold.",
            warnings = "",
            searchTags = listOf("Randall should go to Okara.", "Randall", "Okara wilderness → Okara", "SAFE")
        ),
        Quest(
            id = "G3-P2-005",
            chapter = 2,
            playOrder = 5,
            title = "Booze for the prospector.",
            category = "SAFE",
            giver = "Owen",
            location = "Hill south of Okara",
            prerequisites = "",
            summary = "Find Owen at his campfire on the prominent hill south of Okara and give him the booze he asks for.",
            walkthroughSteps = listOf("Find prospector Owen in the wilderness around Okara.", "Give him one bottle of booze to gain his trust.", "Ask Owen about his lack of a home and follow with A Homeless Prospector."),
            reward = "250 XP and +4 Okara reputation.",
            warnings = "",
            searchTags = listOf("Booze for the prospector.", "Owen", "Hill south of Okara", "SAFE")
        ),
        Quest(
            id = "G3-P2-006",
            chapter = 2,
            playOrder = 6,
            title = "A homeless prospector.",
            category = "SAFE",
            giver = "Owen",
            location = "South of Okara → Okara",
            prerequisites = "Give Owen a bottle of booze and ask where he can live.",
            summary = "After helping Owen with booze, tell him the rebels at Okara need people. Send him to the camp and report to Manning.",
            walkthroughSteps = listOf("Finish Booze for the Prospector so Owen will discuss his situation.", "Tell Owen to join Manning's rebel settlement at Okara.", "Visit Manning and mention Owen's arrival for any recruitment follow-up."),
            reward = "1,000 XP, +1 Rebel reputation and +8 Okara reputation.",
            warnings = "",
            searchTags = listOf("A homeless prospector.", "Owen", "South of Okara → Okara", "SAFE")
        ),
        Quest(
            id = "G3-P2-007",
            chapter = 2,
            playOrder = 7,
            title = "Rakus the Fire Mage should go to Okara.",
            category = "SAFE",
            giver = "Rakus",
            location = "Cave near Okara → Okara",
            prerequisites = "Rescue Rakus in the undead cave and clear his summoned undead.",
            summary = "After rescuing Rakus and destroying his undead, suggest that he join the rebels in Okara. Return to Manning after he leaves.",
            walkthroughSteps = listOf("Start by speaking with Rakus. This quest belongs to the Cave near Okara → Okara section. Exhaust the quest-related dialogue before leaving so every objective and follow-up is registered.", "After rescuing Rakus and destroying his undead, suggest that he join the rebels in Okara. Return to Manning after he leaves.", "Return to the quest giver or the named destination after the objective is complete. If no completion message appears, re-check the target area for a surviving enemy, missing quest item, or an unfinished dialogue step.", "Rakus carries a Fire Chalice; do not lose track of the Fire Chalice quest line."),
            reward = "1,000 XP, +1 Rebel reputation and +8 Okara reputation for recruiting Rakus.",
            warnings = "",
            searchTags = listOf("Rakus the Fire Mage should go to Okara.", "Rakus", "Cave near Okara → Okara", "SAFE")
        ),
        Quest(
            id = "G3-P2-008",
            chapter = 2,
            playOrder = 8,
            title = "Rescue Rakus the Fire Mage from the cave of the undead.",
            category = "SAFE",
            giver = "Rakus",
            location = "Cave near Okara",
            prerequisites = "",
            summary = "Locate Rakus in the cave where his necromantic experiment went wrong. Escort/fight your way out while killing the undead attacking him; keep Rakus alive.",
            walkthroughSteps = listOf("Start by speaking with Rakus. This quest belongs to the Cave near Okara section. Exhaust the quest-related dialogue before leaving so every objective and follow-up is registered.", "Locate Rakus in the cave where his necromantic experiment went wrong. Escort/fight your way out while killing the undead attacking him; keep Rakus alive.", "Return to the quest giver or the named destination after the objective is complete. If no completion message appears, re-check the target area for a surviving enemy, missing quest item, or an unfinished dialogue step.", "This unlocks his remaining quests."),
            reward = "",
            warnings = "",
            searchTags = listOf("Rescue Rakus the Fire Mage from the cave of the undead.", "Rakus", "Cave near Okara", "SAFE")
        ),
        Quest(
            id = "G3-P2-009",
            chapter = 2,
            playOrder = 9,
            title = "Kill the undead that Rakus summoned.",
            category = "SAFE",
            giver = "Rakus",
            location = "Cave near Okara",
            prerequisites = "",
            summary = "Clear the remaining skeletons and undead created by Rakus's failed experiment, then speak with him again.",
            walkthroughSteps = listOf("Start by speaking with Rakus. This quest belongs to the Cave near Okara section. Exhaust the quest-related dialogue before leaving so every objective and follow-up is registered.", "Clear the remaining skeletons and undead created by Rakus's failed experiment, then speak with him again.", "Return to the quest giver or the named destination after the objective is complete. If no completion message appears, re-check the target area for a surviving enemy, missing quest item, or an unfinished dialogue step.", "Do this before sending Rakus to Okara."),
            reward = "",
            warnings = "",
            searchTags = listOf("Kill the undead that Rakus summoned.", "Rakus", "Cave near Okara", "SAFE")
        ),
        Quest(
            id = "G3-P2-010",
            chapter = 2,
            playOrder = 10,
            title = "Hunt the nasty shadowbeasts.",
            category = "SAFE",
            giver = "Candela",
            location = "Ruined site northeast of Okara",
            prerequisites = "Meet Candela at the ruins outside Okara.",
            summary = "Meet Candela at the ruins and kill the two named nasty Shadowbeasts nearby. Loot their horns before leaving.",
            walkthroughSteps = listOf("Talk to hunter Candela at the ruined camp and ask about the beasts nearby.", "Find and defeat the TWO dangerous shadowbeasts near the ruins.", "Take their horns before heading back; Candela has a separate horn turn-in.", "Report the cleared hunting ground to Candela."),
            reward = "1,000 XP, +4 Okara reputation and +1 Hunting skill.",
            warnings = "",
            searchTags = listOf("Hunt the nasty shadowbeasts.", "Candela", "Ruined site northeast of Okara", "SAFE")
        ),
        Quest(
            id = "G3-P2-011",
            chapter = 2,
            playOrder = 11,
            title = "Two shadowbeast horns for Candela.",
            category = "SAFE",
            giver = "Candela",
            location = "Ruins near Okara",
            prerequisites = "Finish hunting Candela's two shadowbeasts and collect their horns.",
            summary = "Give Candela the two Shadowbeast horns from the beasts you just killed.",
            walkthroughSteps = listOf("Learn to take horns if necessary before hunting the two shadowbeasts near Candela.", "Loot a horn from each of the two shadowbeasts.", "Give both horns to Candela."),
            reward = "750 XP and +1 Hunting skill.",
            warnings = "",
            searchTags = listOf("Two shadowbeast horns for Candela.", "Candela", "Ruins near Okara", "SAFE")
        ),
        Quest(
            id = "G3-P2-012",
            chapter = 2,
            playOrder = 12,
            title = "Candela should go to Okara.",
            category = "SAFE",
            giver = "Candela",
            location = "Ruins → Okara",
            prerequisites = "Complete Hunt the Nasty Shadowbeasts and talk to Candela about Okara.",
            summary = "Once Candela's hunt is finished, tell him to join the rebels in Okara and report his recruitment to Manning.",
            walkthroughSteps = listOf("Candela is in the old ruins north of Okara with Fraser. He will only agree to relocate after you prove yourself by completing his Shadowbeast hunt.", "Kill the two Nasty Shadowbeasts, finish Candela's related horn dialogue if active, then tell him Okara needs people. Return to Manning afterward.", "Return to the quest giver or the named destination after the objective is complete. If no completion message appears, re-check the target area for a surviving enemy, missing quest item, or an unfinished dialogue step.", "Candela and Fraser are in the same ruins, so complete both hunters' quest chains in one trip."),
            reward = "1,000 XP and +8 Okara reputation.",
            warnings = "",
            searchTags = listOf("Candela should go to Okara.", "Candela", "Ruins → Okara", "SAFE")
        ),
        Quest(
            id = "G3-P2-013",
            chapter = 2,
            playOrder = 13,
            title = "Hunt the nasty wild boars.",
            category = "SAFE",
            giver = "Fraser",
            location = "Ruins near Okara",
            prerequisites = "Find Fraser with Candela at the ruins near Okara.",
            summary = "Kill the dangerous wild boars associated with Fraser's hunting area and make sure the whole target group is dead.",
            walkthroughSteps = listOf("Start by speaking with Fraser. This quest belongs to the Ruins near Okara section. Exhaust the quest-related dialogue before leaving so every objective and follow-up is registered.", "Kill the dangerous wild boars associated with Fraser's hunting area and make sure the whole target group is dead.", "Return to the quest giver or the named destination after the objective is complete. If no completion message appears, re-check the target area for a surviving enemy, missing quest item, or an unfinished dialogue step.", "Linked with Go boar hunting with Fraser."),
            reward = "750 XP and +1 Hunting skill from the boar hunt.",
            warnings = "",
            searchTags = listOf("Hunt the nasty wild boars.", "Fraser", "Ruins near Okara", "SAFE")
        ),
        Quest(
            id = "G3-P2-014",
            chapter = 2,
            playOrder = 14,
            title = "Go boar hunting with Fraser.",
            category = "SAFE",
            giver = "Fraser",
            location = "Ruins near Okara",
            prerequisites = "",
            summary = "Ask Fraser to hunt with you and accompany him to the boars. Help him kill them without letting him die.",
            walkthroughSteps = listOf("Start by speaking with Fraser. This quest belongs to the Ruins near Okara section. Exhaust the quest-related dialogue before leaving so every objective and follow-up is registered.", "Ask Fraser to hunt with you and accompany him to the boars. Help him kill them without letting him die.", "Return to the quest giver or the named destination after the objective is complete. If no completion message appears, re-check the target area for a surviving enemy, missing quest item, or an unfinished dialogue step.", "Afterward he can be recruited."),
            reward = "",
            warnings = "",
            searchTags = listOf("Go boar hunting with Fraser.", "Fraser", "Ruins near Okara", "SAFE")
        ),
        Quest(
            id = "G3-P2-015",
            chapter = 2,
            playOrder = 15,
            title = "Fraser should go to Okara.",
            category = "SAFE",
            giver = "Fraser",
            location = "Ruins → Okara",
            prerequisites = "Finish Fraser's boar hunting quest.",
            summary = "After the boar hunt, tell Fraser that Okara needs hunters and send him to the rebel camp.",
            walkthroughSteps = listOf("Start by speaking with Fraser. This quest belongs to the Ruins → Okara section. Exhaust the quest-related dialogue before leaving so every objective and follow-up is registered.", "After the boar hunt, tell Fraser that Okara needs hunters and send him to the rebel camp.", "Return to the quest giver or the named destination after the objective is complete. If no completion message appears, re-check the target area for a surviving enemy, missing quest item, or an unfinished dialogue step.", "Counts toward Manning's recruitment quest."),
            reward = "1,000 XP, +1 Rebel reputation and +8 Okara reputation for recruiting Fraser.",
            warnings = "",
            searchTags = listOf("Fraser should go to Okara.", "Fraser", "Ruins → Okara", "SAFE")
        ),
        Quest(
            id = "G3-P2-016",
            chapter = 2,
            playOrder = 16,
            title = "Malicious ripperbeasts.",
            category = "SAFE",
            giver = "Kent",
            location = "Cave east-northeast of Okara",
            prerequisites = "Find Kent hiding in a cave near Okara.",
            summary = "Find Kent hiding in a small cave near an abandoned hut. Kill the malicious Ripperbeasts outside so he can safely leave.",
            walkthroughSteps = listOf("Start by speaking with Kent. This quest belongs to the Cave east-northeast of Okara section. Exhaust the quest-related dialogue before leaving so every objective and follow-up is registered.", "Find Kent hiding in a small cave near an abandoned hut. Kill the malicious Ripperbeasts outside so he can safely leave.", "Return to the quest giver or the named destination after the objective is complete. If no completion message appears, re-check the target area for a surviving enemy, missing quest item, or an unfinished dialogue step.", "Speak to Kent after the area is safe."),
            reward = "1,000 XP, +4 Okara reputation and +1 Hunting skill for killing Kent's ripperbeasts.",
            warnings = "",
            searchTags = listOf("Malicious ripperbeasts.", "Kent", "Cave east-northeast of Okara", "SAFE")
        ),
        Quest(
            id = "G3-P2-017",
            chapter = 2,
            playOrder = 17,
            title = "Kent should go to Okara.",
            category = "SAFE",
            giver = "Kent",
            location = "Wilderness → Okara",
            prerequisites = "Finish Malicious Ripperbeasts for Kent.",
            summary = "After killing the Ripperbeasts, tell Kent to join Okara and later report his recruitment to Manning.",
            walkthroughSteps = listOf("Start by speaking with Kent. This quest belongs to the Wilderness → Okara section. Exhaust the quest-related dialogue before leaving so every objective and follow-up is registered.", "After killing the Ripperbeasts, tell Kent to join Okara and later report his recruitment to Manning.", "Return to the quest giver or the named destination after the objective is complete. If no completion message appears, re-check the target area for a surviving enemy, missing quest item, or an unfinished dialogue step.", "Kent is easy to miss and is a common reason Manning's quest remains unfinished."),
            reward = "1,000 XP, +1 Rebel reputation and +8 Okara reputation for recruiting Kent.",
            warnings = "",
            searchTags = listOf("Kent should go to Okara.", "Kent", "Wilderness → Okara", "SAFE")
        ),
        Quest(
            id = "G3-P2-018",
            chapter = 2,
            playOrder = 18,
            title = "Bring Manning some iron ore.",
            category = "SAFE",
            giver = "Manning",
            location = "Okara",
            prerequisites = "Complete Manning's six local recruitments before his smithing supplies request.",
            summary = "After progressing Manning's recruitment work, bring him five pieces of iron ore. Randall's newly cleared mine is a convenient source.",
            walkthroughSteps = listOf("Recruit Manning's workers from the surroundings of Okara, including Randall, Owen, Rakus, Candela, Fraser and Kent.", "Speak to Manning again; he asks for FIVE iron ore pieces.", "Mine the ore from Randall's now-safe mine or bring ore from another inventory source.", "Give Manning the five ore pieces."),
            reward = "1,500 XP and +8 Okara reputation; the existing guide also lists an extra 2,000 gold for this route.",
            warnings = "",
            searchTags = listOf("Bring Manning some iron ore.", "Manning", "Okara", "SAFE")
        ),
        Quest(
            id = "G3-P2-019",
            chapter = 2,
            playOrder = 19,
            title = "Take Okara apart!",
            category = "DEFER — ORC PATH",
            giver = "Orc leadership / faction route",
            location = "Okara",
            prerequisites = "",
            summary = "On a committed Orc route, attack Okara and kill enough rebels—including its leadership—for the camp to be destroyed, then report to the Orc quest giver.",
            walkthroughSteps = listOf("Varek in Montera gives this Orc-aligned destruction quest after you have enough access and have progressed the mercenary-loyalty line.", "Attack Okara and eliminate the Rebel population until the enclave is considered destroyed, then return to Varek.", "Return to the quest giver or the named destination after the objective is complete. If no completion message appears, re-check the target area for a surviving enemy, missing quest item, or an unfinished dialogue step.", "DEFER. Okara contains Roland, Manning and many recruited NPCs and is tied to numerous Rebel and main-story-adjacent quests."),
            reward = "Verified: 2500 XP, +7 Orc reputation, 2000 gold and 1500 follow-up XP from Varek.",
            warnings = "⚠ Choice warning: This quest can affect faction access, named NPCs, or later quest availability. Make a manual save before committing and finish the surrounding neutral quests first.",
            searchTags = listOf("Take Okara apart!", "Orc leadership / faction route", "Okara", "DEFER — ORC PATH")
        ),
        Quest(
            id = "G3-P2-020",
            chapter = 2,
            playOrder = 20,
            title = "Rescue Gorn from the orcs in Gotha.",
            category = "SAFE",
            giver = "Gorn / Potros",
            location = "Orc outpost below Gotha",
            prerequisites = "",
            summary = "Speak with imprisoned Gorn and Potros. The cleanest neutral solution is to pay Potros the demanded ransom; alternatively the Orc outpost can be fought. Speak with Gorn once he is free.",
            walkthroughSteps = listOf("Start by speaking with Gorn / Potros. This quest belongs to the Orc outpost below Gotha section. Exhaust the quest-related dialogue before leaving so every objective and follow-up is registered.", "Speak with imprisoned Gorn and Potros. The cleanest neutral solution is to pay Potros the demanded ransom; alternatively the Orc outpost can be fought. Speak with Gorn once he is free.", "Return to the quest giver or the named destination after the objective is complete. If no completion message appears, re-check the target area for a surviving enemy, missing quest item, or an unfinished dialogue step.", "Paying avoids unnecessary Orc hostility at this stage."),
            reward = "",
            warnings = "",
            searchTags = listOf("Rescue Gorn from the orcs in Gotha.", "Gorn / Potros", "Orc outpost below Gotha", "SAFE")
        ),
        Quest(
            id = "G3-P2-021",
            chapter = 2,
            playOrder = 21,
            title = "Defeat Potros.",
            category = "SAFE — DUEL",
            giver = "Potros",
            location = "Orc outpost below Gotha",
            prerequisites = "",
            summary = "Challenge the arrogant Potros and defeat him in the sanctioned fight. Do not turn the duel into a general attack on the camp unless that is your intention.",
            walkthroughSteps = listOf("Start by speaking with Potros. This quest belongs to the Orc outpost below Gotha section. Exhaust the quest-related dialogue before leaving so every objective and follow-up is registered.", "Challenge the arrogant Potros and defeat him in the sanctioned fight. Do not turn the duel into a general attack on the camp unless that is your intention.", "Return to the quest giver or the named destination after the objective is complete. If no completion message appears, re-check the target area for a surviving enemy, missing quest item, or an unfinished dialogue step.", "Complete before destroying the outpost if you want the duel reward."),
            reward = "",
            warnings = "",
            searchTags = listOf("Defeat Potros.", "Potros", "Orc outpost below Gotha", "SAFE — DUEL")
        ),
        Quest(
            id = "G3-P2-022",
            chapter = 2,
            playOrder = 22,
            title = "Hunting demons with Gorn.",
            category = "SAFE",
            giver = "Gorn",
            location = "Gotha ruins",
            prerequisites = "",
            summary = "After freeing Gorn, ask him to accompany you into Gotha. Fight through zombies, skeletons and other undead together until the fortress is secure.",
            walkthroughSteps = listOf("Start by speaking with Gorn. This quest belongs to the Gotha ruins section. Exhaust the quest-related dialogue before leaving so every objective and follow-up is registered.", "After freeing Gorn, ask him to accompany you into Gotha. Fight through zombies, skeletons and other undead together until the fortress is secure.", "Return to the quest giver or the named destination after the objective is complete. If no completion message appears, re-check the target area for a surviving enemy, missing quest item, or an unfinished dialogue step.", "Runs alongside Free Gotha from its curse."),
            reward = "",
            warnings = "",
            searchTags = listOf("Hunting demons with Gorn.", "Gorn", "Gotha ruins", "SAFE")
        ),
        Quest(
            id = "G3-P2-023",
            chapter = 2,
            playOrder = 23,
            title = "Free Gotha from its curse.",
            category = "SAFE",
            giver = "Gorn / Roland",
            location = "Gotha fortress",
            prerequisites = "",
            summary = "Fight through the ruined settlement and castle and kill the Demon of Gotha. Loot the demon carefully, then report the success through the Gotha/Okara quest line.",
            walkthroughSteps = listOf("Start by speaking with Gorn / Roland. This quest belongs to the Gotha fortress section. Exhaust the quest-related dialogue before leaving so every objective and follow-up is registered.", "Fight through the ruined settlement and castle and kill the Demon of Gotha. Loot the demon carefully, then report the success through the Gotha/Okara quest line.", "Return to the quest giver or the named destination after the objective is complete. If no completion message appears, re-check the target area for a surviving enemy, missing quest item, or an unfinished dialogue step.", "The demon is tied to an important divine artifact objective."),
            reward = "",
            warnings = "",
            searchTags = listOf("Free Gotha from its curse.", "Gorn / Roland", "Gotha fortress", "SAFE")
        ),
        Quest(
            id = "G3-P2-024",
            chapter = 2,
            playOrder = 24,
            title = "Rebuild Gotha.",
            category = "SAFE",
            giver = "Roland → Shawn",
            location = "Okara / Gotha",
            prerequisites = "Remove Gotha's undead demon curse and secure the fortress; then speak to Roland and Shawn.",
            summary = "After the curse is removed, speak with Roland in Okara, then Shawn. Give Shawn 1,000 gold so reconstruction of Gotha can begin.",
            walkthroughSteps = listOf("This becomes available after the Demon of Gotha is defeated. Return to Roland in Okara and discuss Gotha's future.", "Roland sends you to Shawn, who sleeps in the room next to Roland. Give Shawn 1000 gold to finance reconstruction.", "Return to the quest giver or the named destination after the objective is complete. If no completion message appears, re-check the target area for a surviving enemy, missing quest item, or an unfinished dialogue step.", "This is a post-cleansing quest; killing the demon alone does not rebuild the settlement."),
            reward = "Verified: 2500 XP and +2 Rebel reputation.",
            warnings = "Rebuilding Gotha comes after cleansing the undead. The Adanos Ring of Life is dropped by the Gotha DEMON; collect it before leaving.",
            searchTags = listOf("Rebuild Gotha.", "Roland → Shawn", "Okara / Gotha", "SAFE")
        ),
        Quest(
            id = "G3-P2-025",
            chapter = 2,
            playOrder = 25,
            title = "Hothead Ben needs to be taught a lesson.",
            category = "SAFE",
            giver = "Farm quest chain",
            location = "Farm near Trelis",
            prerequisites = "",
            summary = "Confront Ben at the farm and defeat him in the requested non-lethal lesson, then report back to the person who wanted him disciplined.",
            walkthroughSteps = listOf("Start by speaking with Farm quest chain. This quest belongs to the Farm near Trelis section. Exhaust the quest-related dialogue before leaving so every objective and follow-up is registered.", "Confront Ben at the farm and defeat him in the requested non-lethal lesson, then report back to the person who wanted him disciplined.", "Return to the quest giver or the named destination after the objective is complete. If no completion message appears, re-check the target area for a surviving enemy, missing quest item, or an unfinished dialogue step.", "Avoid killing ordinary farm NPCs."),
            reward = "",
            warnings = "",
            searchTags = listOf("Hothead Ben needs to be taught a lesson.", "Farm quest chain", "Farm near Trelis", "SAFE")
        ),
        Quest(
            id = "G3-P2-026",
            chapter = 2,
            playOrder = 26,
            title = "Ben the servant needs his shovel.",
            category = "SAFE",
            giver = "Ben",
            location = "Farm near Trelis",
            prerequisites = "",
            summary = "Locate Ben's missing shovel around the farm/work area and return it to him.",
            walkthroughSteps = listOf("Start by speaking with Ben. This quest belongs to the Farm near Trelis section. Exhaust the quest-related dialogue before leaving so every objective and follow-up is registered.", "Locate Ben's missing shovel around the farm/work area and return it to him.", "Return to the quest giver or the named destination after the objective is complete. If no completion message appears, re-check the target area for a surviving enemy, missing quest item, or an unfinished dialogue step.", "Do this while completing the farm's other errands."),
            reward = "",
            warnings = "",
            searchTags = listOf("Ben the servant needs his shovel.", "Ben", "Farm near Trelis", "SAFE")
        ),
        Quest(
            id = "G3-P2-027",
            chapter = 2,
            playOrder = 27,
            title = "Sneaky goblin raid on Derec's farm.",
            category = "SAFE",
            giver = "Derec",
            location = "Farm near Trelis",
            prerequisites = "",
            summary = "Speak with Derec about the goblin problem and investigate the nearby raiders.",
            walkthroughSteps = listOf("Start by speaking with Derec. This quest belongs to the Farm near Trelis section. Exhaust the quest-related dialogue before leaving so every objective and follow-up is registered.", "Speak with Derec about the goblin problem and investigate the nearby raiders.", "Return to the quest giver or the named destination after the objective is complete. If no completion message appears, re-check the target area for a surviving enemy, missing quest item, or an unfinished dialogue step.", "Leads directly to killing the thieving goblins."),
            reward = "",
            warnings = "",
            searchTags = listOf("Sneaky goblin raid on Derec's farm.", "Derec", "Farm near Trelis", "SAFE")
        ),
        Quest(
            id = "G3-P2-028",
            chapter = 2,
            playOrder = 28,
            title = "Kill the thieving goblins near Derec's farm.",
            category = "SAFE",
            giver = "Derec",
            location = "Near Derec's farm",
            prerequisites = "",
            summary = "Find the goblin group responsible for the raids, kill the entire target group and return to Derec.",
            walkthroughSteps = listOf("Start by speaking with Derec. This quest belongs to the Near Derec's farm section. Exhaust the quest-related dialogue before leaving so every objective and follow-up is registered.", "Find the goblin group responsible for the raids, kill the entire target group and return to Derec.", "Return to the quest giver or the named destination after the objective is complete. If no completion message appears, re-check the target area for a surviving enemy, missing quest item, or an unfinished dialogue step.", "Loot the camp before leaving."),
            reward = "",
            warnings = "",
            searchTags = listOf("Kill the thieving goblins near Derec's farm.", "Derec", "Near Derec's farm", "SAFE")
        ),
        Quest(
            id = "G3-P2-029",
            chapter = 2,
            playOrder = 29,
            title = "Clean out the undead caves.",
            category = "SAFE",
            giver = "Trelis-area quest giver",
            location = "Caves near Trelis",
            prerequisites = "",
            summary = "Enter the indicated cave system and destroy the undead occupying it. Search the chambers before reporting completion.",
            walkthroughSteps = listOf("Start by speaking with Trelis-area quest giver. This quest belongs to the Caves near Trelis section. Exhaust the quest-related dialogue before leaving so every objective and follow-up is registered.", "Enter the indicated cave system and destroy the undead occupying it. Search the chambers before reporting completion.", "Return to the quest giver or the named destination after the objective is complete. If no completion message appears, re-check the target area for a surviving enemy, missing quest item, or an unfinished dialogue step.", "Useful early combat/loot quest."),
            reward = "",
            warnings = "",
            searchTags = listOf("Clean out the undead caves.", "Trelis-area quest giver", "Caves near Trelis", "SAFE")
        ),
        Quest(
            id = "G3-P2-030",
            chapter = 2,
            playOrder = 30,
            title = "Destroy the orcs in and around the temple of Trelis.",
            category = "CHOICE — REBEL",
            giver = "Rebel/temple quest chain",
            location = "Eastern temple near Trelis",
            prerequisites = "",
            summary = "Attack and eliminate the Orc force occupying the temple and its immediate surroundings.",
            walkthroughSteps = listOf("Start by speaking with Rebel/temple quest chain. This quest belongs to the Eastern temple near Trelis section. Exhaust the quest-related dialogue before leaving so every objective and follow-up is registered.", "Attack and eliminate the Orc force occupying the temple and its immediate surroundings.", "Return to the quest giver or the named destination after the objective is complete. If no completion message appears, re-check the target area for a surviving enemy, missing quest item, or an unfinished dialogue step.", "Do not start this if you are preserving an Orc-friendly route."),
            reward = "",
            warnings = "⚠ Choice warning: This quest can affect faction access, named NPCs, or later quest availability. Make a manual save before committing and finish the surrounding neutral quests first.",
            searchTags = listOf("Destroy the orcs in and around the temple of Trelis.", "Rebel/temple quest chain", "Eastern temple near Trelis", "CHOICE — REBEL")
        ),
        Quest(
            id = "G3-P2-031",
            chapter = 2,
            playOrder = 31,
            title = "Kamak's artifact.",
            category = "SAFE / CHOICE",
            giver = "Kamak",
            location = "Temple of Trelis",
            prerequisites = "",
            summary = "Recover the artifact associated with shaman Kamak during the temple quest chain and resolve it through his dialogue.",
            walkthroughSteps = listOf("Start by speaking with Kamak. This quest belongs to the Temple of Trelis section. Exhaust the quest-related dialogue before leaving so every objective and follow-up is registered.", "Recover the artifact associated with shaman Kamak during the temple quest chain and resolve it through his dialogue.", "Return to the quest giver or the named destination after the objective is complete. If no completion message appears, re-check the target area for a surviving enemy, missing quest item, or an unfinished dialogue step.", "Complete before killing or abandoning Kamak."),
            reward = "",
            warnings = "⚠ Choice warning: This quest can affect faction access, named NPCs, or later quest availability. Make a manual save before committing and finish the surrounding neutral quests first.",
            searchTags = listOf("Kamak's artifact.", "Kamak", "Temple of Trelis", "SAFE / CHOICE")
        ),
        Quest(
            id = "G3-P2-032",
            chapter = 2,
            playOrder = 32,
            title = "Tell the leader of Nemora about the rebels' situation at the temple of Trelis.",
            category = "SAFE — REBEL",
            giver = "Rebels at temple",
            location = "Temple → Nemora",
            prerequisites = "",
            summary = "Carry the rebels' report from the Trelis temple to the leadership of Nemora.",
            walkthroughSteps = listOf("Charles leads the small Rebel camp west of the Trelis temple and asks you to report their situation to Nemora.", "Do not choose dialogue telling Charles that you do not know Nemora's leader; that can make him hostile. Instead build Nemora reputation to 75%, learn from Russel that he is the leader, then report Charles's situation to Russel.", "Return to the quest giver or the named destination after the objective is complete. If no completion message appears, re-check the target area for a surviving enemy, missing quest item, or an unfinished dialogue step.", "Russel cannot send reinforcements, but delivering the report completes the quest and opens the return-message follow-up."),
            reward = "Verified: 1000 XP and +1 Rebel reputation.",
            warnings = "",
            searchTags = listOf("Tell the leader of Nemora about the rebels' situation at the temple of Trelis.", "Rebels at temple", "Temple → Nemora", "SAFE — REBEL")
        ),
        Quest(
            id = "G3-P2-033",
            chapter = 2,
            playOrder = 33,
            title = "No deliveries arriving from the eastern temple.",
            category = "SAFE",
            giver = "Trelis Orcs",
            location = "Trelis → eastern temple",
            prerequisites = "",
            summary = "Investigate why the expected deliveries from the eastern temple have stopped. Travel to the temple and determine what happened.",
            walkthroughSteps = listOf("Start by speaking with Trelis Orcs. This quest belongs to the Trelis → eastern temple section. Exhaust the quest-related dialogue before leaving so every objective and follow-up is registered.", "Investigate why the expected deliveries from the eastern temple have stopped. Travel to the temple and determine what happened.", "Return to the quest giver or the named destination after the objective is complete. If no completion message appears, re-check the target area for a surviving enemy, missing quest item, or an unfinished dialogue step.", "Be careful: the temple has competing Rebel and Orc objectives."),
            reward = "",
            warnings = "",
            searchTags = listOf("No deliveries arriving from the eastern temple.", "Trelis Orcs", "Trelis → eastern temple", "SAFE")
        ),
        Quest(
            id = "G3-P2-034",
            chapter = 2,
            playOrder = 34,
            title = "Search for survivors in the temple of Trelis.",
            category = "SAFE",
            giver = "Temple quest chain",
            location = "Eastern temple",
            prerequisites = "",
            summary = "Search the temple area after the fighting and locate surviving named NPCs, including Kamak where applicable.",
            walkthroughSteps = listOf("Start by speaking with Temple quest chain. This quest belongs to the Eastern temple section. Exhaust the quest-related dialogue before leaving so every objective and follow-up is registered.", "Search the temple area after the fighting and locate surviving named NPCs, including Kamak where applicable.", "Return to the quest giver or the named destination after the objective is complete. If no completion message appears, re-check the target area for a surviving enemy, missing quest item, or an unfinished dialogue step.", "Speak to survivors before leaving."),
            reward = "",
            warnings = "",
            searchTags = listOf("Search for survivors in the temple of Trelis.", "Temple quest chain", "Eastern temple", "SAFE")
        ),
        Quest(
            id = "G3-P2-035",
            chapter = 2,
            playOrder = 35,
            title = "Help the shaman Kamak leave the temple.",
            category = "SAFE / ORC-FRIENDLY",
            giver = "Kamak",
            location = "Eastern temple → safety/Trelis",
            prerequisites = "",
            summary = "Escort or otherwise help Kamak leave the dangerous temple area alive.",
            walkthroughSteps = listOf("Start by speaking with Kamak. This quest belongs to the Eastern temple → safety/Trelis section. Exhaust the quest-related dialogue before leaving so every objective and follow-up is registered.", "Escort or otherwise help Kamak leave the dangerous temple area alive.", "Return to the quest giver or the named destination after the objective is complete. If no completion message appears, re-check the target area for a surviving enemy, missing quest item, or an unfinished dialogue step.", "Conflicts with simply wiping out everyone associated with the Orc side."),
            reward = "",
            warnings = "",
            searchTags = listOf("Help the shaman Kamak leave the temple.", "Kamak", "Eastern temple → safety/Trelis", "SAFE / ORC-FRIENDLY")
        ),
        Quest(
            id = "G3-P2-036",
            chapter = 2,
            playOrder = 36,
            title = "Kill the sneaky ogres in the woods.",
            category = "SAFE",
            giver = "Trelis-area NPC",
            location = "Woods near Trelis",
            prerequisites = "",
            summary = "Track down the ogres hiding in the nearby woods and kill the complete target group, then report back.",
            walkthroughSteps = listOf("Start by speaking with Trelis-area NPC. This quest belongs to the Woods near Trelis section. Exhaust the quest-related dialogue before leaving so every objective and follow-up is registered.", "Track down the ogres hiding in the nearby woods and kill the complete target group, then report back.", "Return to the quest giver or the named destination after the objective is complete. If no completion message appears, re-check the target area for a surviving enemy, missing quest item, or an unfinished dialogue step.", "Bring strong melee or ranged damage; ogres hit hard."),
            reward = "",
            warnings = "",
            searchTags = listOf("Kill the sneaky ogres in the woods.", "Trelis-area NPC", "Woods near Trelis", "SAFE")
        ),
        Quest(
            id = "G3-P2-037",
            chapter = 2,
            playOrder = 37,
            title = "Find out what is wrong with the western farm.",
            category = "SAFE",
            giver = "Trelis quest chain",
            location = "Western farm",
            prerequisites = "",
            summary = "Travel to the western farm and investigate why it has stopped functioning normally. Speak with survivors and inspect the area.",
            walkthroughSteps = listOf("Start by speaking with Trelis quest chain. This quest belongs to the Western farm section. Exhaust the quest-related dialogue before leaving so every objective and follow-up is registered.", "Travel to the western farm and investigate why it has stopped functioning normally. Speak with survivors and inspect the area.", "Return to the quest giver or the named destination after the objective is complete. If no completion message appears, re-check the target area for a surviving enemy, missing quest item, or an unfinished dialogue step.", "Leads into the suspicious cave/ranger questions."),
            reward = "",
            warnings = "",
            searchTags = listOf("Find out what is wrong with the western farm.", "Trelis quest chain", "Western farm", "SAFE")
        ),
        Quest(
            id = "G3-P2-038",
            chapter = 2,
            playOrder = 38,
            title = "The suspicious cave near the farm.",
            category = "SAFE",
            giver = "Western farm quest chain",
            location = "Cave near western farm",
            prerequisites = "",
            summary = "Explore the suspicious cave near the farm and deal with the creatures or evidence inside, then report what you found.",
            walkthroughSteps = listOf("Start by speaking with Western farm quest chain. This quest belongs to the Cave near western farm section. Exhaust the quest-related dialogue before leaving so every objective and follow-up is registered.", "Explore the suspicious cave near the farm and deal with the creatures or evidence inside, then report what you found.", "Return to the quest giver or the named destination after the objective is complete. If no completion message appears, re-check the target area for a surviving enemy, missing quest item, or an unfinished dialogue step.", "Search the cave fully before returning."),
            reward = "",
            warnings = "",
            searchTags = listOf("The suspicious cave near the farm.", "Western farm quest chain", "Cave near western farm", "SAFE")
        ),
        Quest(
            id = "G3-P2-039",
            chapter = 2,
            playOrder = 39,
            title = "Did the rangers devastate the farm?",
            category = "SAFE / INVESTIGATION",
            giver = "Western farm quest chain",
            location = "Western farm / ranger territory",
            prerequisites = "",
            summary = "Investigate whether the nearby Rangers were actually responsible for the farm's destruction and report the result through the quest dialogue.",
            walkthroughSteps = listOf("Start by speaking with Western farm quest chain. This quest belongs to the Western farm / ranger territory section. Exhaust the quest-related dialogue before leaving so every objective and follow-up is registered.", "Investigate whether the nearby Rangers were actually responsible for the farm's destruction and report the result through the quest dialogue.", "Return to the quest giver or the named destination after the objective is complete. If no completion message appears, re-check the target area for a surviving enemy, missing quest item, or an unfinished dialogue step.", "Do not attack Rangers merely because they are suspected."),
            reward = "",
            warnings = "",
            searchTags = listOf("Did the rangers devastate the farm?", "Western farm quest chain", "Western farm / ranger territory", "SAFE / INVESTIGATION")
        ),
        Quest(
            id = "G3-P2-040",
            chapter = 2,
            playOrder = 40,
            title = "Ransack the castle of Trelis.",
            category = "DEFER / THIEVERY",
            giver = "Faction/loot quest",
            location = "Trelis castle",
            prerequisites = "",
            summary = "Steal the required valuables from the castle without triggering a premature town-wide battle.",
            walkthroughSteps = listOf("Start by speaking with Faction/loot quest. This quest belongs to the Trelis castle section. Exhaust the quest-related dialogue before leaving so every objective and follow-up is registered.", "Steal the required valuables from the castle without triggering a premature town-wide battle.", "Return to the quest giver or the named destination after the objective is complete. If no completion message appears, re-check the target area for a surviving enemy, missing quest item, or an unfinished dialogue step.", "Save beforehand; this is much easier before either faction turns hostile."),
            reward = "",
            warnings = "⚠ Choice warning: This quest can affect faction access, named NPCs, or later quest availability. Make a manual save before committing and finish the surrounding neutral quests first.",
            searchTags = listOf("Ransack the castle of Trelis.", "Faction/loot quest", "Trelis castle", "DEFER / THIEVERY")
        ),
        Quest(
            id = "G3-P2-041",
            chapter = 2,
            playOrder = 41,
            title = "Ransack the farms!",
            category = "DEFER / THIEVERY",
            giver = "Faction/loot quest",
            location = "Farms around Trelis",
            prerequisites = "",
            summary = "Loot the specified farm valuables for the quest giver while keeping the broader Trelis quest network intact.",
            walkthroughSteps = listOf("Start by speaking with Faction/loot quest. This quest belongs to the Farms around Trelis section. Exhaust the quest-related dialogue before leaving so every objective and follow-up is registered.", "Loot the specified farm valuables for the quest giver while keeping the broader Trelis quest network intact.", "Return to the quest giver or the named destination after the objective is complete. If no completion message appears, re-check the target area for a surviving enemy, missing quest item, or an unfinished dialogue step.", "Finish peaceful farm quests first."),
            reward = "",
            warnings = "⚠ Choice warning: This quest can affect faction access, named NPCs, or later quest availability. Make a manual save before committing and finish the surrounding neutral quests first.",
            searchTags = listOf("Ransack the farms!", "Faction/loot quest", "Farms around Trelis", "DEFER / THIEVERY")
        ),
        Quest(
            id = "G3-P2-042",
            chapter = 2,
            playOrder = 42,
            title = "The paladin Konrad wants his magic back.",
            category = "SAFE — FIRE CHALICE",
            giver = "Konrad",
            location = "Trelis",
            prerequisites = "Obtain a blessed Fire Chalice from the Monastery sacred fire and return to Konrad.",
            summary = "Speak with Konrad about the loss of paladin magic and progress the global Fire Chalice quest so his power can eventually be restored.",
            walkthroughSteps = listOf("Speak with paladin Konrad at Trelis about his lost Innos magic.", "Collect all twelve Fire Chalices and bless them at the sacred fire in the Nordmar Monastery.", "Bring ONE Blessed Fire Chalice back to Konrad; an unblessed chalice cannot restore him."),
            reward = "2,500 XP, +1 Rebel reputation and 500 gold.",
            warnings = "You need a BLESSED chalice, not the basic chalice Konrad initially hands over.",
            searchTags = listOf("The paladin Konrad wants his magic back.", "Konrad", "Trelis", "SAFE — FIRE CHALICE")
        ),
        Quest(
            id = "G3-P2-043",
            chapter = 2,
            playOrder = 43,
            title = "The orc warrior Pranck needs healing potions.",
            category = "SAFE",
            giver = "Pranck",
            location = "Trelis",
            prerequisites = "",
            summary = "Give Pranck the initial healing potions he requests.",
            walkthroughSteps = listOf("Start by speaking with Pranck. This quest belongs to the Trelis section. Exhaust the quest-related dialogue before leaving so every objective and follow-up is registered.", "Give Pranck the initial healing potions he requests.", "Return to the quest giver or the named destination after the objective is complete. If no completion message appears, re-check the target area for a surviving enemy, missing quest item, or an unfinished dialogue step.", "This leads to a larger potion order."),
            reward = "",
            warnings = "",
            searchTags = listOf("The orc warrior Pranck needs healing potions.", "Pranck", "Trelis", "SAFE")
        ),
        Quest(
            id = "G3-P2-044",
            chapter = 2,
            playOrder = 44,
            title = "Find the runaway alchemist Avogadro.",
            category = "SAFE",
            giver = "Pranck / Avogadro",
            location = "Trelis countryside",
            prerequisites = "",
            summary = "Search the countryside for Avogadro, the missing alchemist, and speak with him about returning.",
            walkthroughSteps = listOf("Pranck in Trelis complains that his alchemist has run away. Avogadro is not hidden in a dungeon: he is at Josh's farm north of Trelis.", "Find Avogadro and speak with him. That report objective completes the search and leads into the choice of returning him or letting him escape.", "Return to the quest giver or the named destination after the objective is complete. If no completion message appears, re-check the target area for a surviving enemy, missing quest item, or an unfinished dialogue step.", "Save before resolving his fate because Pranck's follow-up changes depending on your decision."),
            reward = "Verified: 1000 XP, +4 Trelis reputation, plus 500 XP when reporting to Pranck.",
            warnings = "",
            searchTags = listOf("Find the runaway alchemist Avogadro.", "Pranck / Avogadro", "Trelis countryside", "SAFE")
        ),
        Quest(
            id = "G3-P2-045",
            chapter = 2,
            playOrder = 45,
            title = "Take Avogadro the alchemist to Trelis.",
            category = "SAFE",
            giver = "Avogadro",
            location = "Countryside → Trelis",
            prerequisites = "",
            summary = "Escort Avogadro safely back to Trelis and complete the handover to the Orcs.",
            walkthroughSteps = listOf("After finding Avogadro at Josh's farm, order/persuade him to return. He refuses to travel alone.", "Escort him from Josh's farm back into Trelis and deliver him safely to Pranck.", "Return to the quest giver or the named destination after the objective is complete. If no completion message appears, re-check the target area for a surviving enemy, missing quest item, or an unfinished dialogue step.", "This route avoids Pranck making you replace Avogadro as potion supplier."),
            reward = "Verified: 1000 XP, +8 Trelis reputation, +1 Alchemy, 500 gold and additional dialogue rewards.",
            warnings = "",
            searchTags = listOf("Take Avogadro the alchemist to Trelis.", "Avogadro", "Countryside → Trelis", "SAFE")
        ),
        Quest(
            id = "G3-P2-046",
            chapter = 2,
            playOrder = 46,
            title = "The orc warrior Pranck wants twenty healing potions.",
            category = "SAFE",
            giver = "Pranck",
            location = "Trelis",
            prerequisites = "",
            summary = "After the alchemist chain progresses, collect twenty Healing Potions and deliver them to Pranck.",
            walkthroughSteps = listOf("This is an alternative consequence, not a normal follow-up to returning Avogadro. It occurs if you accept Pranck's recapture task but allow Avogadro to escape.", "Pranck effectively appoints you as the replacement alchemist and gives you two days to supply twenty Healing Potions.", "Return to the quest giver or the named destination after the objective is complete. If no completion message appears, re-check the target area for a surviving enemy, missing quest item, or an unfinished dialogue step.", "If you intend to take this branch, have the potions ready before triggering it. Escorting Avogadro back to Trelis avoids this timed requirement."),
            reward = "Verified: 1500 XP, +4 Trelis reputation and 500 gold.",
            warnings = "",
            searchTags = listOf("The orc warrior Pranck wants twenty healing potions.", "Pranck", "Trelis", "SAFE")
        ),
        Quest(
            id = "G3-P2-047",
            chapter = 2,
            playOrder = 47,
            title = "Milok is looking for his old sword.",
            category = "SAFE",
            giver = "Milok",
            location = "Trelis",
            prerequisites = "",
            summary = "Find Milok's old sword in the location indicated by his clues/quest context and return it to him.",
            walkthroughSteps = listOf("Start by speaking with Milok. This quest belongs to the Trelis section. Exhaust the quest-related dialogue before leaving so every objective and follow-up is registered.", "Find Milok's old sword in the location indicated by his clues/quest context and return it to him.", "Return to the quest giver or the named destination after the objective is complete. If no completion message appears, re-check the target area for a surviving enemy, missing quest item, or an unfinished dialogue step.", "Do this before any liberation removes Trelis NPCs."),
            reward = "",
            warnings = "",
            searchTags = listOf("Milok is looking for his old sword.", "Milok", "Trelis", "SAFE")
        ),
        Quest(
            id = "G3-P2-048",
            chapter = 2,
            playOrder = 48,
            title = "Kill the grunting creatures below Josh's farm.",
            category = "SAFE",
            giver = "Josh",
            location = "Farm near Trelis",
            prerequisites = "",
            summary = "Go below/behind Josh's farm and kill the noisy creatures troubling the area, then return to Josh.",
            walkthroughSteps = listOf("Start by speaking with Josh. This quest belongs to the Farm near Trelis section. Exhaust the quest-related dialogue before leaving so every objective and follow-up is registered.", "Go below/behind Josh's farm and kill the noisy creatures troubling the area, then return to Josh.", "Return to the quest giver or the named destination after the objective is complete. If no completion message appears, re-check the target area for a surviving enemy, missing quest item, or an unfinished dialogue step.", "Simple local extermination quest."),
            reward = "",
            warnings = "",
            searchTags = listOf("Kill the grunting creatures below Josh's farm.", "Josh", "Farm near Trelis", "SAFE")
        ),
        Quest(
            id = "G3-P2-049",
            chapter = 2,
            playOrder = 49,
            title = "Vak needs fifty thousand gold coins for the Hashishin.",
            category = "CHOICE — MAJOR PAYMENT",
            giver = "Vak",
            location = "Trelis castle",
            prerequisites = "Gain access to Vak in Trelis; discuss the 50,000-gold Hashishin debt.",
            summary = "Vak needs 50,000 gold connected with the Hashishin arrangement. Accumulate the money and pay him only if you want to resolve the quest through his faction route.",
            walkthroughSteps = listOf("After earning access to Trelis castle, speak with Vak. He owes the Hashishin 50,000 gold and allows you to keep rent collected around Trelis if you agree to solve the debt.", "Raise the full 50,000 gold and pay Vak. The farm rents cover only a small fraction, so most of the sum normally comes from your own funds.", "Return to the quest giver or the named destination after the objective is complete. If no completion message appears, re-check the target area for a surviving enemy, missing quest item, or an unfinished dialogue step.", "This is a MAIN-STORY SIGNIFICANT quest: Vak gives you the Amulet of Adanos, one of the five divine artifacts. Do not treat the payment as a disposable side quest."),
            reward = "Verified: 5000 XP, +7 Orc reputation and the Amulet of Adanos; Khabir also has a related reward.",
            warnings = "50,000 GOLD IS A PAYMENT, not a reward. Vak holds the Amulet of Adanos; save before liberation as killing him changes the alternative acquisition route.",
            searchTags = listOf("Vak needs fifty thousand gold coins for the Hashishin.", "Vak", "Trelis castle", "CHOICE — MAJOR PAYMENT")
        ),
        Quest(
            id = "G3-P2-050",
            chapter = 2,
            playOrder = 50,
            title = "Conquer the castle of Trelis!",
            category = "DEFER — REBEL PATH",
            giver = "Rebel/Nemora route",
            location = "Trelis",
            prerequisites = "Finish all wanted Trelis quests, particularly Vak's divine artifact and Konrad's chalice dialogue.",
            summary = "When you have finished the peaceful Trelis content and deliberately choose the Rebel attack, assault the castle and defeat enough Orc forces for Trelis to fall.",
            walkthroughSteps = listOf("Konrad can help initiate the Rebel uprising in Trelis, especially after his paladin magic has been restored.", "Attack the Orc occupation and kill enough defenders for the remaining Orcs to flee. Keep important allies alive where possible.", "Return to the quest giver or the named destination after the objective is complete. If no completion message appears, re-check the target area for a surviving enemy, missing quest item, or an unfinished dialogue step.", "DEFER until every peaceful Trelis quest is complete, including Vak's artifact/payment route if you intend to obtain the Amulet of Adanos that way."),
            reward = "Verified: 7500 XP, +5 Rebel reputation and 1500 XP from Konrad.",
            warnings = "Trelis liberation is a counted strike in the Orc three-city hostility system. Finish quests and secure the Amulet of Adanos first.",
            searchTags = listOf("Conquer the castle of Trelis!", "Rebel/Nemora route", "Trelis", "DEFER — REBEL PATH")
        ),
        Quest(
            id = "G3-P2-051",
            chapter = 2,
            playOrder = 51,
            title = "Rebels stole the rent from Farmon's farm.",
            category = "SAFE / INVESTIGATION",
            giver = "Farmon / Nemora chain",
            location = "Farm near Nemora",
            prerequisites = "",
            summary = "Investigate the stolen rent and follow the trail to the rebels involved. Resolve the matter through the Nemora dialogue chain.",
            walkthroughSteps = listOf("Farmon, south of Trelis, says Rebels from Nemora stole the rent he owes.", "In Nemora, speak with Hengley. He admits responsibility and hands over the stolen rent. Return through the quest dialogue to close Farmon's problem.", "Return to the quest giver or the named destination after the objective is complete. If no completion message appears, re-check the target area for a surviving enemy, missing quest item, or an unfinished dialogue step.", "Do not confuse recovering the rent with judging Hengley; “Hengley the farm raider” is a separate follow-up resolved with Russel."),
            reward = "Verified: 1000 XP, 1000 gold recovered from Hengley and an additional 500 XP from Farmon.",
            warnings = "",
            searchTags = listOf("Rebels stole the rent from Farmon's farm.", "Farmon / Nemora chain", "Farm near Nemora", "SAFE / INVESTIGATION")
        ),
        Quest(
            id = "G3-P2-052",
            chapter = 2,
            playOrder = 52,
            title = "Cole the farmhand wants to go to Nemora.",
            category = "SAFE — REBEL",
            giver = "Cole",
            location = "Farm → Nemora",
            prerequisites = "",
            summary = "Agree to take Cole to Nemora and escort him safely to the rebel camp.",
            walkthroughSteps = listOf("Start by speaking with Cole. This quest belongs to the Farm → Nemora section. Exhaust the quest-related dialogue before leaving so every objective and follow-up is registered.", "Agree to take Cole to Nemora and escort him safely to the rebel camp.", "Return to the quest giver or the named destination after the objective is complete. If no completion message appears, re-check the target area for a surviving enemy, missing quest item, or an unfinished dialogue step.", "Counts toward strengthening Nemora."),
            reward = "",
            warnings = "",
            searchTags = listOf("Cole the farmhand wants to go to Nemora.", "Cole", "Farm → Nemora", "SAFE — REBEL")
        ),
        Quest(
            id = "G3-P2-053",
            chapter = 2,
            playOrder = 53,
            title = "A new man for Nemora.",
            category = "SAFE",
            giver = "Nemora recruitment chain",
            location = "Nemora region",
            prerequisites = "",
            summary = "Recruit the required useful newcomer for Nemora and report the successful addition to the camp.",
            walkthroughSteps = listOf("Start by speaking with Nemora recruitment chain. This quest belongs to the Nemora region section. Exhaust the quest-related dialogue before leaving so every objective and follow-up is registered.", "Recruit the required useful newcomer for Nemora and report the successful addition to the camp.", "Return to the quest giver or the named destination after the objective is complete. If no completion message appears, re-check the target area for a surviving enemy, missing quest item, or an unfinished dialogue step.", "Often overlaps naturally with escort/recruitment quests."),
            reward = "",
            warnings = "",
            searchTags = listOf("A new man for Nemora.", "Nemora recruitment chain", "Nemora region", "SAFE")
        ),
        Quest(
            id = "G3-P2-054",
            chapter = 2,
            playOrder = 54,
            title = "Karlen the paladin wants his magic back.",
            category = "SAFE — FIRE CHALICE",
            giver = "Karlen",
            location = "Nemora",
            prerequisites = "Collect 12 Fire Chalices and bless them at the sacred fire in the Nordmar Monastery.",
            summary = "Speak with Karlen about restoring his lost paladin magic and keep him in mind for the global blessed Fire Chalice objective.",
            walkthroughSteps = listOf("Karlen is found near Nemora and later may be inside the camp. Like Konrad, he needs a Blessed Fire Chalice, not an unblessed one.", "Complete the sacred-fire stage of the global Fire Chalice quest, then return one Blessed Fire Chalice to Karlen.", "Return to the quest giver or the named destination after the objective is complete. If no completion message appears, re-check the target area for a surviving enemy, missing quest item, or an unfinished dialogue step.", "Keep Karlen alive through his pass-to-Varant quests so you can finish this later."),
            reward = "Verified: 2500 XP, +1 Rebel reputation and ten Healing Potions.",
            warnings = "Keep Karlen alive during his Varant-pass quests. An UNBLESSED Fire Chalice does not complete his magic-restoration task.",
            searchTags = listOf("Karlen the paladin wants his magic back.", "Karlen", "Nemora", "SAFE — FIRE CHALICE")
        ),
        Quest(
            id = "G3-P2-055",
            chapter = 2,
            playOrder = 55,
            title = "The renegade paladin at the pass to Varant must die.",
            category = "SAFE / COMBAT",
            giver = "Karlen",
            location = "Pass toward Varant",
            prerequisites = "Meet paladin Karlen at Nemora and escort him toward the Varant pass.",
            summary = "Accompany or follow Karlen's instructions to find the renegade paladin at the desert pass and defeat him.",
            walkthroughSteps = listOf("Karlen sits at a campfire south of Nemora and wants to confront Kurt, a renegade paladin on the pass toward Varant.", "Travel with Karlen to the pass and kill Kurt. Search Kurt's body after the fight.", "Return to the quest giver or the named destination after the objective is complete. If no completion message appears, re-check the target area for a surviving enemy, missing quest item, or an unfinished dialogue step.", "Kurt carries one of the twelve Fire Chalices. Looting him is essential for the global Fire Chalice quest."),
            reward = "Verified: 1500 XP, +1 Rebel reputation, 1000 gold and 1000 follow-up XP from Karlen, plus Kurt's Fire Chalice.",
            warnings = "Renegade paladin Kurt's FIRE CHALICE is in his locked CHEST. Loot the chest using the key, not just Kurt's body.",
            searchTags = listOf("The renegade paladin at the pass to Varant must die.", "Karlen", "Pass toward Varant", "SAFE / COMBAT")
        ),
        Quest(
            id = "G3-P2-056",
            chapter = 2,
            playOrder = 56,
            title = "Cross the pass to Varant with Karlen.",
            category = "SAFE",
            giver = "Karlen",
            location = "Nemora → Varant pass",
            prerequisites = "Accept Karlen's escort near Nemora; travel together toward the Varant pass.",
            summary = "Travel with Karlen through the pass toward Varant, protecting him from enemies along the route.",
            walkthroughSteps = listOf("Start by speaking with Karlen. This quest belongs to the Nemora → Varant pass section. Exhaust the quest-related dialogue before leaving so every objective and follow-up is registered.", "Travel with Karlen through the pass toward Varant, protecting him from enemies along the route.", "Return to the quest giver or the named destination after the objective is complete. If no completion message appears, re-check the target area for a surviving enemy, missing quest item, or an unfinished dialogue step.", "This can be used as your first controlled introduction to the desert border."),
            reward = "",
            warnings = "Do not leave Kurt's encampment before looting the fire chalice from its chest. Karlen's escort and the renegade-paladin fight are linked.",
            searchTags = listOf("Cross the pass to Varant with Karlen.", "Karlen", "Nemora → Varant pass", "SAFE")
        ),
        Quest(
            id = "G3-P2-057",
            chapter = 2,
            playOrder = 57,
            title = "Karlen the paladin shows you the desert.",
            category = "SAFE",
            giver = "Karlen",
            location = "Varant border",
            prerequisites = "",
            summary = "Continue with Karlen after crossing the pass until he has shown you the desert route and the quest completes.",
            walkthroughSteps = listOf("Start by speaking with Karlen. This quest belongs to the Varant border section. Exhaust the quest-related dialogue before leaving so every objective and follow-up is registered.", "Continue with Karlen after crossing the pass until he has shown you the desert route and the quest completes.", "Return to the quest giver or the named destination after the objective is complete. If no completion message appears, re-check the target area for a surviving enemy, missing quest item, or an unfinished dialogue step.", "You do not need to begin the full Varant section yet."),
            reward = "",
            warnings = "",
            searchTags = listOf("Karlen the paladin shows you the desert.", "Karlen", "Varant border", "SAFE")
        ),
        Quest(
            id = "G3-P2-058",
            chapter = 2,
            playOrder = 58,
            title = "Bring Russel the goods from the desert.",
            category = "SAFE",
            giver = "Russel",
            location = "Nemora / Varant border",
            prerequisites = "",
            summary = "Recover or collect the requested shipment/goods from the desert side and deliver them to Russel in Nemora.",
            walkthroughSteps = listOf("Start by speaking with Russel. This quest belongs to the Nemora / Varant border section. Exhaust the quest-related dialogue before leaving so every objective and follow-up is registered.", "Recover or collect the requested shipment/goods from the desert side and deliver them to Russel in Nemora.", "Return to the quest giver or the named destination after the objective is complete. If no completion message appears, re-check the target area for a surviving enemy, missing quest item, or an unfinished dialogue step.", "Can be paired with Karlen's pass quests."),
            reward = "",
            warnings = "",
            searchTags = listOf("Bring Russel the goods from the desert.", "Russel", "Nemora / Varant border", "SAFE")
        ),
        Quest(
            id = "G3-P2-059",
            chapter = 2,
            playOrder = 59,
            title = "Who's boss in Nemora?",
            category = "SAFE",
            giver = "Nemora residents",
            location = "Nemora",
            prerequisites = "",
            summary = "Ask around and complete enough work for the camp to earn trust. The identity of Nemora's actual leader is revealed only after you have sufficiently proven yourself.",
            walkthroughSteps = listOf("Nemora intentionally hides its leader. Asking around at low reputation will not reveal him.", "Complete Nemora quests until you reach at least 75% reputation. Then speak with Russel again; he reveals that he is the camp's leader and the quest completes.", "Return to the quest giver or the named destination after the objective is complete. If no completion message appears, re-check the target area for a surviving enemy, missing quest item, or an unfinished dialogue step.", "This gates other quests. Charles's message about the Trelis temple cannot be properly delivered until you know Russel is the leader."),
            reward = "Verified: 2500 XP and +2 Rebel reputation.",
            warnings = "",
            searchTags = listOf("Who's boss in Nemora?", "Nemora residents", "Nemora", "SAFE")
        ),
        Quest(
            id = "G3-P2-060",
            chapter = 2,
            playOrder = 60,
            title = "Kill the three monsters north of Nemora.",
            category = "SAFE",
            giver = "Nemora quest giver",
            location = "North of Nemora",
            prerequisites = "",
            summary = "Find the three dangerous monsters north of the camp, kill all three and report back.",
            walkthroughSteps = listOf("Start by speaking with Nemora quest giver. This quest belongs to the North of Nemora section. Exhaust the quest-related dialogue before leaving so every objective and follow-up is registered.", "Find the three dangerous monsters north of the camp, kill all three and report back.", "Return to the quest giver or the named destination after the objective is complete. If no completion message appears, re-check the target area for a surviving enemy, missing quest item, or an unfinished dialogue step.", "Useful reputation quest before asking about the camp leader."),
            reward = "",
            warnings = "",
            searchTags = listOf("Kill the three monsters north of Nemora.", "Nemora quest giver", "North of Nemora", "SAFE")
        ),
        Quest(
            id = "G3-P2-061",
            chapter = 2,
            playOrder = 61,
            title = "Weapons for Nemora.",
            category = "SAFE",
            giver = "Nemora quartermaster/rebels",
            location = "Nemora",
            prerequisites = "",
            summary = "Collect the requested Bundles of Weapons and deliver them to Nemora.",
            walkthroughSteps = listOf("Start by speaking with Nemora quartermaster/rebels. This quest belongs to the Nemora section. Exhaust the quest-related dialogue before leaving so every objective and follow-up is registered.", "Collect the requested Bundles of Weapons and deliver them to Nemora.", "Return to the quest giver or the named destination after the objective is complete. If no completion message appears, re-check the target area for a surviving enemy, missing quest item, or an unfinished dialogue step.", "Continue saving weapon bundles; several Rebel camps use them."),
            reward = "",
            warnings = "",
            searchTags = listOf("Weapons for Nemora.", "Nemora quartermaster/rebels", "Nemora", "SAFE")
        ),
        Quest(
            id = "G3-P2-062",
            chapter = 2,
            playOrder = 62,
            title = "Clear the orcs out of the farm west of Trelis.",
            category = "SAFE — REBEL",
            giver = "Nemora rebels",
            location = "Farm west of Trelis",
            prerequisites = "",
            summary = "Attack the Orc group occupying the farm west of Trelis and eliminate them, then report back to Nemora.",
            walkthroughSteps = listOf("Start by speaking with Nemora rebels. This quest belongs to the Farm west of Trelis section. Exhaust the quest-related dialogue before leaving so every objective and follow-up is registered.", "Attack the Orc group occupying the farm west of Trelis and eliminate them, then report back to Nemora.", "Return to the quest giver or the named destination after the objective is complete. If no completion message appears, re-check the target area for a surviving enemy, missing quest item, or an unfinished dialogue step.", "This is a localized fight, not the full liberation of Trelis."),
            reward = "",
            warnings = "",
            searchTags = listOf("Clear the orcs out of the farm west of Trelis.", "Nemora rebels", "Farm west of Trelis", "SAFE — REBEL")
        ),
        Quest(
            id = "G3-P2-063",
            chapter = 2,
            playOrder = 63,
            title = "Bring Treslott the rare plant herbaceous lobelia.",
            category = "SAFE",
            giver = "Treslott",
            location = "Nemora region",
            prerequisites = "",
            summary = "Find the rare herbaceous lobelia requested by Treslott and bring it back to him.",
            walkthroughSteps = listOf("Start by speaking with Treslott. This quest belongs to the Nemora region section. Exhaust the quest-related dialogue before leaving so every objective and follow-up is registered.", "Find the rare herbaceous lobelia requested by Treslott and bring it back to him.", "Return to the quest giver or the named destination after the objective is complete. If no completion message appears, re-check the target area for a surviving enemy, missing quest item, or an unfinished dialogue step.", "Check the surrounding wilderness carefully; rare plants are easy to walk past."),
            reward = "",
            warnings = "",
            searchTags = listOf("Bring Treslott the rare plant herbaceous lobelia.", "Treslott", "Nemora region", "SAFE")
        ),
        Quest(
            id = "G3-P2-064",
            chapter = 2,
            playOrder = 64,
            title = "Hengley the farm raider.",
            category = "CHOICE / JUSTICE",
            giver = "Nemora / Farmon chain",
            location = "Nemora",
            prerequisites = "",
            summary = "Confront the issue of Hengley's raid on Farmon's farm and resolve it through the camp leadership once you have the evidence/dialogue required.",
            walkthroughSteps = listOf("After learning that Hengley raided Farmon's farm, you can eventually report his behavior to Nemora's true leader.", "First reach 75% Nemora reputation and discover that Russel is the boss. Then tell Russel about Hengley to resolve the disciplinary quest.", "Return to the quest giver or the named destination after the objective is complete. If no completion message appears, re-check the target area for a surviving enemy, missing quest item, or an unfinished dialogue step.", "This is directly tied to “Who's boss in Nemora?”; trying to finish it too early leaves you without the correct authority to report to."),
            reward = "Verified: 1000 XP and 200 gold from Russel.",
            warnings = "⚠ Choice warning: This quest can affect faction access, named NPCs, or later quest availability. Make a manual save before committing and finish the surrounding neutral quests first.",
            searchTags = listOf("Hengley the farm raider.", "Nemora / Farmon chain", "Nemora", "CHOICE / JUSTICE")
        ),
        Quest(
            id = "G3-P2-065",
            chapter = 2,
            playOrder = 65,
            title = "A message for the rebel Charles.",
            category = "SAFE — REBEL",
            giver = "Nemora quest chain",
            location = "Nemora → Charles",
            prerequisites = "",
            summary = "Carry the message from Nemora to the rebel Charles and deliver it.",
            walkthroughSteps = listOf("Start by speaking with Nemora quest chain. This quest belongs to the Nemora → Charles section. Exhaust the quest-related dialogue before leaving so every objective and follow-up is registered.", "Carry the message from Nemora to the rebel Charles and deliver it.", "Return to the quest giver or the named destination after the objective is complete. If no completion message appears, re-check the target area for a surviving enemy, missing quest item, or an unfinished dialogue step.", "A straightforward courier quest that expands the Rebel network."),
            reward = "",
            warnings = "",
            searchTags = listOf("A message for the rebel Charles.", "Nemora quest chain", "Nemora → Charles", "SAFE — REBEL")
        ),
        Quest(
            id = "G3-P2-066",
            chapter = 2,
            playOrder = 66,
            title = "Finley gets all set to attack Trelis.",
            category = "DEFER — REBEL PREP",
            giver = "Finley",
            location = "Nemora",
            prerequisites = "",
            summary = "After the required Nemora/Trelis conditions are met, tell Finley to prepare for the attack on Trelis.",
            walkthroughSteps = listOf("Start by speaking with Finley. This quest belongs to the Nemora section. Exhaust the quest-related dialogue before leaving so every objective and follow-up is registered.", "After the required Nemora/Trelis conditions are met, tell Finley to prepare for the attack on Trelis.", "Return to the quest giver or the named destination after the objective is complete. If no completion message appears, re-check the target area for a surviving enemy, missing quest item, or an unfinished dialogue step.", "Preparation is safer than launching the assault; finish Trelis quests first."),
            reward = "",
            warnings = "⚠ Choice warning: This quest can affect faction access, named NPCs, or later quest availability. Make a manual save before committing and finish the surrounding neutral quests first.",
            searchTags = listOf("Finley gets all set to attack Trelis.", "Finley", "Nemora", "DEFER — REBEL PREP")
        ),
        Quest(
            id = "G3-P2-067",
            chapter = 2,
            playOrder = 67,
            title = "Finley attacks Trelis.",
            category = "DEFER — REBEL PATH",
            giver = "Finley",
            location = "Nemora → Trelis",
            prerequisites = "",
            summary = "When you intentionally begin the liberation, take Finley with you and assault Trelis. Keep him alive if possible while defeating the Orc occupation.",
            walkthroughSteps = listOf("Start by speaking with Finley. This quest belongs to the Nemora → Trelis section. Exhaust the quest-related dialogue before leaving so every objective and follow-up is registered.", "When you intentionally begin the liberation, take Finley with you and assault Trelis. Keep him alive if possible while defeating the Orc occupation.", "Return to the quest giver or the named destination after the objective is complete. If no completion message appears, re-check the target area for a surviving enemy, missing quest item, or an unfinished dialogue step.", "This belongs at the very end of the Trelis/Nemora quest block."),
            reward = "",
            warnings = "⚠ Choice warning: This quest can affect faction access, named NPCs, or later quest availability. Make a manual save before committing and finish the surrounding neutral quests first.",
            searchTags = listOf("Finley attacks Trelis.", "Finley", "Nemora → Trelis", "DEFER — REBEL PATH")
        ),
        Quest(
            id = "G3-P2-068",
            chapter = 2,
            playOrder = 68,
            title = "Destroy the rebel camp Nemora.",
            category = "DEFER — ORC PATH",
            giver = "Orc leadership",
            location = "Nemora",
            prerequisites = "Orc-faction commitment; finish all rebel quests, recruitments and the Nemora Fire Mage's chalice before attacking.",
            summary = "On a committed Orc playthrough, attack Nemora and eliminate enough rebels and leadership for the camp to be destroyed, then report to the Orc quest giver.",
            walkthroughSteps = listOf("Start by speaking with Orc leadership. This quest belongs to the Nemora section. Exhaust the quest-related dialogue before leaving so every objective and follow-up is registered.", "On a committed Orc playthrough, attack Nemora and eliminate enough rebels and leadership for the camp to be destroyed, then report to the Orc quest giver.", "Return to the quest giver or the named destination after the objective is complete. If no completion message appears, re-check the target area for a surviving enemy, missing quest item, or an unfinished dialogue step.", "Mutually hostile to most Nemora content. Complete every desired Rebel quest first."),
            reward = "",
            warnings = "Destroying Nemora is irreversible and counts against rebel-camp hostility. Finish Treslott's chalice and Karlen's quests first.",
            searchTags = listOf("Destroy the rebel camp Nemora.", "Orc leadership", "Nemora", "DEFER — ORC PATH")
        ),
    )
}
