package com.sliverzfx.gothicquest

internal object Gothic3Part6Data {
    val quests = listOf(
        Quest(
            id = "G3-P6-001",
            chapter = 6,
            playOrder = 1,
            title = "Talk to Gonzales.",
            category = "SAFE / REPUTATION GATE",
            giver = "Gonzales",
            location = "Mora Sul",
            prerequisites = "Mora Sul access and sufficient local reputation to meet its ruler; speak to guards, merchants and arena contacts first.",
            summary = "Earn enough Mora Sul reputation to gain an audience with Gonzales, then exhaust his dialogue about the city, temple and political situation.",
            walkthroughSteps = listOf("Begin with Gonzales. This quest is centered on Mora Sul. Use city gates, oases, excavation camps and large ruin complexes as navigation anchors; southern Varant has long stretches where a wrong canyon can add a major detour.", "Earn enough Mora Sul reputation to gain an audience with Gonzales, then exhaust his dialogue about the city, temple and political situation.", "Return to the quest giver or named destination after the objective triggers and exhaust the follow-up dialogue. For multi-item quests, verify every required key/item is actually in your inventory before entering a temple or reporting completion.", "Do not expect immediate access when first arriving; build reputation through merchants, arena fights and local jobs."),
            reward = "",
            warnings = "Earn local Mora Sul reputation before asking for Gonzales; forcing the palace or killing the ruler forfeits his temple-key and trade quests.",
            searchTags = listOf("Talk to Gonzales.", "Gonzales", "Mora Sul", "SAFE / REPUTATION GATE")
        ),
        Quest(
            id = "G3-P6-002",
            chapter = 6,
            playOrder = 2,
            title = "A present for Gonzales.",
            category = "SAFE",
            giver = "Mora Sul merchants / quest chain",
            location = "Mora Sul",
            prerequisites = "",
            summary = "Obtain a suitable valuable gift requested for Gonzales and deliver it through the relevant dialogue.",
            walkthroughSteps = listOf("Begin with Mora Sul merchants / quest chain. This quest is centered on Mora Sul. Use city gates, oases, excavation camps and large ruin complexes as navigation anchors; southern Varant has long stretches where a wrong canyon can add a major detour.", "Obtain a suitable valuable gift requested for Gonzales and deliver it through the relevant dialogue.", "Return to the quest giver or named destination after the objective triggers and exhaust the follow-up dialogue. For multi-item quests, verify every required key/item is actually in your inventory before entering a temple or reporting completion.", "Use this as a peaceful reputation route rather than stealing or fighting."),
            reward = "",
            warnings = "",
            searchTags = listOf("A present for Gonzales.", "Mora Sul merchants / quest chain", "Mora Sul", "SAFE")
        ),
        Quest(
            id = "G3-P6-003",
            chapter = 6,
            playOrder = 3,
            title = "The arena of Mora Sul.",
            category = "SAFE — ARENA",
            giver = "Arena organizer",
            location = "Mora Sul arena",
            prerequisites = "",
            summary = "Register for Mora Sul's arena and defeat the available opponents one at a time. Stay within the arena and use non-lethal knockouts unless a quest explicitly says otherwise.",
            walkthroughSteps = listOf("Begin with Arena organizer. This quest is centered on Mora Sul arena. Use city gates, oases, excavation camps and large ruin complexes as navigation anchors; southern Varant has long stretches where a wrong canyon can add a major detour.", "Register for Mora Sul's arena and defeat the available opponents one at a time. Stay within the arena and use non-lethal knockouts unless a quest explicitly says otherwise.", "Return to the quest giver or named destination after the objective triggers and exhaust the follow-up dialogue. For multi-item quests, verify every required key/item is actually in your inventory before entering a temple or reporting completion.", "Complete every arena fight before any liberation; arena NPCs are easy to lose during city combat."),
            reward = "",
            warnings = "",
            searchTags = listOf("The arena of Mora Sul.", "Arena organizer", "Mora Sul arena", "SAFE — ARENA")
        ),
        Quest(
            id = "G3-P6-004",
            chapter = 6,
            playOrder = 4,
            title = "Defeat the first Mora Sul gladiator.",
            category = "SAFE — ARENA",
            giver = "Arena opponent",
            location = "Mora Sul arena",
            prerequisites = "",
            summary = "Challenge and defeat the first available gladiator, wait for him to recover and finish the post-fight dialogue.",
            walkthroughSteps = listOf("Begin with Arena opponent. This quest is centered on Mora Sul arena. Use city gates, oases, excavation camps and large ruin complexes as navigation anchors; southern Varant has long stretches where a wrong canyon can add a major detour.", "Challenge and defeat the first available gladiator, wait for him to recover and finish the post-fight dialogue.", "Return to the quest giver or named destination after the objective triggers and exhaust the follow-up dialogue. For multi-item quests, verify every required key/item is actually in your inventory before entering a temple or reporting completion.", "Arena victories build Mora Sul standing."),
            reward = "",
            warnings = "",
            searchTags = listOf("Defeat the first Mora Sul gladiator.", "Arena opponent", "Mora Sul arena", "SAFE — ARENA")
        ),
        Quest(
            id = "G3-P6-005",
            chapter = 6,
            playOrder = 5,
            title = "Defeat the veteran gladiator.",
            category = "SAFE — ARENA",
            giver = "Arena opponent",
            location = "Mora Sul arena",
            prerequisites = "",
            summary = "Beat the stronger veteran opponent under arena rules.",
            walkthroughSteps = listOf("Begin with Arena opponent. This quest is centered on Mora Sul arena. Use city gates, oases, excavation camps and large ruin complexes as navigation anchors; southern Varant has long stretches where a wrong canyon can add a major detour.", "Beat the stronger veteran opponent under arena rules.", "Return to the quest giver or named destination after the objective triggers and exhaust the follow-up dialogue. For multi-item quests, verify every required key/item is actually in your inventory before entering a temple or reporting completion.", "Prepare with good armor and healing because Varant arena fighters hit harder than early Myrtana opponents."),
            reward = "",
            warnings = "",
            searchTags = listOf("Defeat the veteran gladiator.", "Arena opponent", "Mora Sul arena", "SAFE — ARENA")
        ),
        Quest(
            id = "G3-P6-006",
            chapter = 6,
            playOrder = 6,
            title = "Defeat the Mora Sul champion.",
            category = "SAFE — ARENA",
            giver = "Arena champion",
            location = "Mora Sul arena",
            prerequisites = "",
            summary = "After qualifying through earlier fights, defeat the champion and collect the associated reward/reputation.",
            walkthroughSteps = listOf("Begin with Arena champion. This quest is centered on Mora Sul arena. Use city gates, oases, excavation camps and large ruin complexes as navigation anchors; southern Varant has long stretches where a wrong canyon can add a major detour.", "After qualifying through earlier fights, defeat the champion and collect the associated reward/reputation.", "Return to the quest giver or named destination after the objective triggers and exhaust the follow-up dialogue. For multi-item quests, verify every required key/item is actually in your inventory before entering a temple or reporting completion.", "Do this before provoking the city."),
            reward = "",
            warnings = "",
            searchTags = listOf("Defeat the Mora Sul champion.", "Arena champion", "Mora Sul arena", "SAFE — ARENA")
        ),
        Quest(
            id = "G3-P6-007",
            chapter = 6,
            playOrder = 7,
            title = "Debt collection in Mora Sul.",
            category = "SAFE / COLLECTION",
            giver = "Mora Sul merchant",
            location = "Mora Sul",
            prerequisites = "",
            summary = "Visit the named debtors, collect the outstanding money and return it to the quest giver.",
            walkthroughSteps = listOf("Begin with Mora Sul merchant. This quest is centered on Mora Sul. Use city gates, oases, excavation camps and large ruin complexes as navigation anchors; southern Varant has long stretches where a wrong canyon can add a major detour.", "Visit the named debtors, collect the outstanding money and return it to the quest giver.", "Return to the quest giver or named destination after the objective triggers and exhaust the follow-up dialogue. For multi-item quests, verify every required key/item is actually in your inventory before entering a temple or reporting completion.", "Speak through every dialogue option before threatening anyone; several collection quests allow peaceful resolutions."),
            reward = "",
            warnings = "",
            searchTags = listOf("Debt collection in Mora Sul.", "Mora Sul merchant", "Mora Sul", "SAFE / COLLECTION")
        ),
        Quest(
            id = "G3-P6-008",
            chapter = 6,
            playOrder = 8,
            title = "The missing merchant.",
            category = "SAFE / SEARCH",
            giver = "Mora Sul quest giver",
            location = "Desert near Mora Sul",
            prerequisites = "",
            summary = "Follow the road/desert clues to locate the missing merchant or caravan and determine what happened.",
            walkthroughSteps = listOf("Begin with Mora Sul quest giver. This quest is centered on Desert near Mora Sul. Use city gates, oases, excavation camps and large ruin complexes as navigation anchors; southern Varant has long stretches where a wrong canyon can add a major detour.", "Follow the road/desert clues to locate the missing merchant or caravan and determine what happened.", "Return to the quest giver or named destination after the objective triggers and exhaust the follow-up dialogue. For multi-item quests, verify every required key/item is actually in your inventory before entering a temple or reporting completion.", "Search bodies and caravan wreckage for quest items before returning."),
            reward = "",
            warnings = "",
            searchTags = listOf("The missing merchant.", "Mora Sul quest giver", "Desert near Mora Sul", "SAFE / SEARCH")
        ),
        Quest(
            id = "G3-P6-009",
            chapter = 6,
            playOrder = 9,
            title = "Escort the merchant to Mora Sul.",
            category = "SAFE / ESCORT",
            giver = "Desert merchant",
            location = "Desert → Mora Sul",
            prerequisites = "",
            summary = "Protect the merchant along the route to Mora Sul and keep him alive until he reaches the city.",
            walkthroughSteps = listOf("Begin with Desert merchant. This quest is centered on Desert → Mora Sul. Use city gates, oases, excavation camps and large ruin complexes as navigation anchors; southern Varant has long stretches where a wrong canyon can add a major detour.", "Protect the merchant along the route to Mora Sul and keep him alive until he reaches the city.", "Return to the quest giver or named destination after the objective triggers and exhaust the follow-up dialogue. For multi-item quests, verify every required key/item is actually in your inventory before entering a temple or reporting completion.", "Clear predators or bandits ahead if the route is dangerous."),
            reward = "",
            warnings = "",
            searchTags = listOf("Escort the merchant to Mora Sul.", "Desert merchant", "Desert → Mora Sul", "SAFE / ESCORT")
        ),
        Quest(
            id = "G3-P6-010",
            chapter = 6,
            playOrder = 10,
            title = "The five keys of the temple of Mora Sul.",
            category = "MAJOR / ARTIFACT",
            giver = "Kalesch (Orc supervisor at the temple)",
            location = "Mora Sul region",
            prerequisites = "Reach the excavated temple south of Mora Sul and speak to Kalesch.",
            summary = "Find the five unique temple keys possessed by Yussuf, Ilja, Kirk, Gonzales and Kalesch. Open the temple after collecting the set.",
            walkthroughSteps = listOf("Meet Orc supervisor Kalesch at the temple excavation south of Mora Sul. He claims to own a key and tells you about the four others.", "Find escaped slave Yussuf in the desert camp to the north and persuade him to surrender his key.", "Trade with Ilja in Mora Sul. He offers his key in return for recovering an ancient vase from the temple.", "Accept mercenary Kirk's supposed raid expedition, survive his ambush and loot the key from him.", "Earn access to Gonzales, then buy his temple key for 10,000 gold or take it through an explicitly hostile route.", "Return to Kalesch. When he demands the four keys without yielding his own, fight him and recover the final key.", "Confirm that you possess all five and open the sealed temple. Continue to the Crown of Adanos."),
            reward = "Five keys granting access to the Mora Sul temple and its Crown of Adanos; Gonzales's key costs 10,000 gold on the peaceful route.",
            warnings = "Kalesch's key is obtained at the end of the chain, usually in combat. Do not kill Ilja or Gonzales before doing their other quests unless deliberately committing to a hostile ending.",
            searchTags = listOf("The five keys of the temple of Mora Sul.", "Mora Sul / temple chain", "Mora Sul region", "MAJOR / ARTIFACT")
        ),
        Quest(
            id = "G3-P6-011",
            chapter = 6,
            playOrder = 11,
            title = "Temple key I.",
            category = "SAFE / TEMPLE KEY",
            giver = "Yussuf (escaped slave)",
            location = "Mora Sul region",
            prerequisites = "Temple-key collection begun; find Yussuf north of Mora Sul.",
            summary = "Obtain a Mora Sul temple key from escaped slave Yussuf.",
            walkthroughSteps = listOf("Travel into the desert north of Mora Sul and find the camp where escaped slave Yussuf is hiding.", "Ask Yussuf about the ancient temple keys; pressure him through the offered dialogue until he relinquishes his key.", "Keep the uniquely named key for the five-key collection and return to Kalesch only when prepared for his confrontation."),
            reward = "One of the five temple keys to Mora Sul's ancient temple.",
            warnings = "Yussuf is a person, not a random chest; follow his dialogue before attacking or returning him to slave owners.",
            searchTags = listOf("Temple key I.", "Mora Sul key holder", "Mora Sul region", "SAFE / TEMPLE KEY")
        ),
        Quest(
            id = "G3-P6-012",
            chapter = 6,
            playOrder = 12,
            title = "Temple key II.",
            category = "SAFE / TEMPLE KEY",
            giver = "Ilja (Mora Sul merchant)",
            location = "Mora Sul region",
            prerequisites = "Meet Ilja in Mora Sul; discuss his interest in relics.",
            summary = "Acquire the second key through its associated quest, trade, theft or combat route as appropriate.",
            walkthroughSteps = listOf("Speak with merchant Ilja and ask about the key to the old temple.", "Agree to recover the ancient vase from the temple once it is open (his return-favor arrangement).", "Accept his temple key, preserve it for the combined five-key puzzle, and return his vase afterward to fulfill the bargain."),
            reward = "One of the five Mora Sul temple keys; the promised ancient vase is a separate merchant favor.",
            warnings = "Ilja is a merchant with other valuable dialogue. Do not kill him simply to obtain a key.",
            searchTags = listOf("Temple key II.", "Mora Sul key holder", "Mora Sul region", "SAFE / TEMPLE KEY")
        ),
        Quest(
            id = "G3-P6-013",
            chapter = 6,
            playOrder = 13,
            title = "Temple key III.",
            category = "SAFE / TEMPLE KEY",
            giver = "Kirk (mercenary near Mora Sul's moneylender)",
            location = "Mora Sul region",
            prerequisites = "Find Kirk in Mora Sul and discuss raiders in the desert.",
            summary = "Acquire the third Mora Sul temple key and keep it for the temple entrance.",
            walkthroughSteps = listOf("Speak with mercenary Kirk in Mora Sul and agree to accompany him to the supposed desert-raider camp.", "Follow Kirk into the desert; he and two accomplices turn on you.", "Defeat the ambushers and loot Kirk for his Mora Sul temple key.", "Return to the temple later with the complete five-key set."),
            reward = "Kirk's Mora Sul temple key, one of five.",
            warnings = "Kirk's 'raid' is a trap. Prepare before leaving town and loot the key from his body.",
            searchTags = listOf("Temple key III.", "Mora Sul key holder", "Mora Sul region", "SAFE / TEMPLE KEY")
        ),
        Quest(
            id = "G3-P6-014",
            chapter = 6,
            playOrder = 14,
            title = "Temple key IV.",
            category = "SAFE / TEMPLE KEY",
            giver = "Gonzales (ruler of Mora Sul)",
            location = "Mora Sul region",
            prerequisites = "Gain Gonzales's audience through Mora Sul reputation and palace access.",
            summary = "Complete the fourth key's character quest and obtain the key.",
            walkthroughSteps = listOf("Earn entry to Gonzales's quarters by completing local Mora Sul reputation quests.", "Ask Gonzales about the temple key he holds. Pay the 10,000-gold price to preserve his quests and services.", "Alternatively attack and loot him only if intentionally abandoning the peaceful Hashishin route.", "Bring the key to the five-key temple collection."),
            reward = "Gonzales's Mora Sul temple key. Peaceful acquisition costs 10,000 gold.",
            warnings = "The 10,000 gold is a PURCHASE cost, not a reward. Killing Gonzales can close Mora Sul services and Hashishin faction quests.",
            searchTags = listOf("Temple key IV.", "Mora Sul key holder", "Mora Sul region", "SAFE / TEMPLE KEY")
        ),
        Quest(
            id = "G3-P6-015",
            chapter = 6,
            playOrder = 15,
            title = "Temple key V.",
            category = "SAFE / TEMPLE KEY",
            giver = "Kalesch (Orc supervisor at the ancient temple)",
            location = "Mora Sul region",
            prerequisites = "Collect the four other temple keys from Yussuf, Ilja, Kirk and Gonzales.",
            summary = "Obtain the final temple key needed to open the ancient temple.",
            walkthroughSteps = listOf("Return to Kalesch outside the sealed temple when you have four other keys.", "He demands your keys while still holding his own, leading to a confrontation.", "Defeat Kalesch and loot his key. Keep the full five-key set to open the temple."),
            reward = "Kalesch's temple key, completing the five-key set.",
            warnings = "Resolve Kalesch only after collecting the four other keys; you cannot open the temple with four.",
            searchTags = listOf("Temple key V.", "Mora Sul key holder", "Mora Sul region", "SAFE / TEMPLE KEY")
        ),
        Quest(
            id = "G3-P6-016",
            chapter = 6,
            playOrder = 16,
            title = "Open the temple of Mora Sul.",
            category = "MAJOR / DUNGEON",
            giver = "Temple entrance (five-key interaction)",
            location = "Ancient temple near Mora Sul",
            prerequisites = "Obtain all five Mora Sul keys from Yussuf, Ilja, Kirk, Gonzales and Kalesch.",
            summary = "Use the five keys at the temple entrance, enter the ruin and fight through the undead and guardians inside.",
            walkthroughSteps = listOf("Complete The Five Keys of the Temple of Mora Sul and check inventory for all five uniquely identified keys.", "Return to the great sealed temple south of the city, near Kalesch's excavation.", "Unlock the ancient entrance and prepare for undead guardians inside; save before exploring the chambers.", "Continue to the Crown of Adanos objective."),
            reward = "Access to the ancient temple and the Crown of Adanos.",
            warnings = "A complete five-key set is mandatory; partial keys do not unlock the door.",
            searchTags = listOf("Open the temple of Mora Sul.", "Mora Sul temple chain", "Ancient temple near Mora Sul", "MAJOR / DUNGEON")
        ),
        Quest(
            id = "G3-P6-017",
            chapter = 6,
            playOrder = 17,
            title = "Find the divine artifact in Mora Sul's temple.",
            category = "MAIN QUEST / ARTIFACT",
            giver = "Automatic on acquiring the Crown of Adanos",
            location = "Temple of Mora Sul",
            prerequisites = "Open the Mora Sul temple with all five keys.",
            summary = "Recover the Crown of Adanos from inside the Temple of Mora Sul.",
            walkthroughSteps = listOf("Use all five ancient keys to unlock the temple entrance near Kalesch.", "Defeat the guardians in the chambers, then search the deeper burial area for the chest with the Crown of Adanos.", "Keep the Crown for the five-artifact main quest; later choose Innos, Beliar or Xardas after you collect the rest."),
            reward = "Crown of Adanos, one of the five divine artifacts needed for every ending decision.",
            warnings = "The artifact is the CROWN. The ROBE is in Al Shedim, the Life ring in Gotha, and the Magic ring in Akascha's Nordmar tomb.",
            searchTags = listOf("Find the divine artifact in Mora Sul's temple.", "Main story", "Temple of Mora Sul", "MAIN QUEST / ARTIFACT")
        ),
        Quest(
            id = "G3-P6-018",
            chapter = 6,
            playOrder = 18,
            title = "The Moonblade.",
            category = "SAFE / UNIQUE ITEM",
            giver = "Mora Sul quest chain",
            location = "Mora Sul",
            prerequisites = "",
            summary = "Track the unique Moonblade through its associated arena/merchant quest and decide who receives it according to the desired reward path.",
            walkthroughSteps = listOf("Begin with Mora Sul quest chain. This quest is centered on Mora Sul. Use city gates, oases, excavation camps and large ruin complexes as navigation anchors; southern Varant has long stretches where a wrong canyon can add a major detour.", "Track the unique Moonblade through its associated arena/merchant quest and decide who receives it according to the desired reward path.", "Return to the quest giver or named destination after the objective triggers and exhaust the follow-up dialogue. For multi-item quests, verify every required key/item is actually in your inventory before entering a temple or reporting completion.", "Do not sell the Moonblade as ordinary loot."),
            reward = "",
            warnings = "",
            searchTags = listOf("The Moonblade.", "Mora Sul quest chain", "Mora Sul", "SAFE / UNIQUE ITEM")
        ),
        Quest(
            id = "G3-P6-019",
            chapter = 6,
            playOrder = 19,
            title = "A sword for Gonzales.",
            category = "SAFE",
            giver = "Mora Sul quest chain",
            location = "Mora Sul",
            prerequisites = "",
            summary = "Obtain the requested special sword and deliver it to Gonzales or the intermediary as directed.",
            walkthroughSteps = listOf("Begin with Mora Sul quest chain. This quest is centered on Mora Sul. Use city gates, oases, excavation camps and large ruin complexes as navigation anchors; southern Varant has long stretches where a wrong canyon can add a major detour.", "Obtain the requested special sword and deliver it to Gonzales or the intermediary as directed.", "Return to the quest giver or named destination after the objective triggers and exhaust the follow-up dialogue. For multi-item quests, verify every required key/item is actually in your inventory before entering a temple or reporting completion.", "Complete any competing item quest before handing over a unique weapon."),
            reward = "",
            warnings = "",
            searchTags = listOf("A sword for Gonzales.", "Mora Sul quest chain", "Mora Sul", "SAFE")
        ),
        Quest(
            id = "G3-P6-020",
            chapter = 6,
            playOrder = 20,
            title = "Find the escaped slaves.",
            category = "CHOICE",
            giver = "Mora Sul slave quest",
            location = "Mora Sul outskirts",
            prerequisites = "",
            summary = "Locate the escaped slaves and decide whether to return them to Hashishin control or support their escape.",
            walkthroughSteps = listOf("Begin with Mora Sul slave quest. This quest is centered on Mora Sul outskirts. Use city gates, oases, excavation camps and large ruin complexes as navigation anchors; southern Varant has long stretches where a wrong canyon can add a major detour.", "Locate the escaped slaves and decide whether to return them to Hashishin control or support their escape.", "Return to the quest giver or named destination after the objective triggers and exhaust the follow-up dialogue. For multi-item quests, verify every required key/item is actually in your inventory before entering a temple or reporting completion.", "Save before resolving; this is a faction-sensitive slave quest."),
            reward = "",
            warnings = "⚠ Faction / story warning: Make a permanent manual save before resolving this objective. It can remove major NPCs, close faction content, block trainers or commit the main story toward an ending.",
            searchTags = listOf("Find the escaped slaves.", "Mora Sul slave quest", "Mora Sul outskirts", "CHOICE")
        ),
        Quest(
            id = "G3-P6-021",
            chapter = 6,
            playOrder = 21,
            title = "The Nomads around Mora Sul.",
            category = "DEFER — HASHISHIN",
            giver = "Gonzales / Hashishin",
            location = "Mora Sul region",
            prerequisites = "",
            summary = "Locate the Nomad groups identified as enemies of Mora Sul and destroy them only if committing to the Hashishin path.",
            walkthroughSteps = listOf("Begin with Gonzales / Hashishin. This quest is centered on Mora Sul region. Use city gates, oases, excavation camps and large ruin complexes as navigation anchors; southern Varant has long stretches where a wrong canyon can add a major detour.", "Locate the Nomad groups identified as enemies of Mora Sul and destroy them only if committing to the Hashishin path.", "Return to the quest giver or named destination after the objective triggers and exhaust the follow-up dialogue. For multi-item quests, verify every required key/item is actually in your inventory before entering a temple or reporting completion.", "Talk to the Nomads and Water Mages first; they have extensive quest content."),
            reward = "",
            warnings = "⚠ Faction / story warning: Make a permanent manual save before resolving this objective. It can remove major NPCs, close faction content, block trainers or commit the main story toward an ending.",
            searchTags = listOf("The Nomads around Mora Sul.", "Gonzales / Hashishin", "Mora Sul region", "DEFER — HASHISHIN")
        ),
        Quest(
            id = "G3-P6-022",
            chapter = 6,
            playOrder = 22,
            title = "Liberate Mora Sul!",
            category = "DEFER — NOMAD",
            giver = "Nomad / player action",
            location = "Mora Sul",
            prerequisites = "",
            summary = "After finishing the arena, temple-key, merchant and city reputation quests, defeat enough Hashishin defenders for Mora Sul to fall.",
            walkthroughSteps = listOf("Begin with Nomad / player action. This quest is centered on Mora Sul. Use city gates, oases, excavation camps and large ruin complexes as navigation anchors; southern Varant has long stretches where a wrong canyon can add a major detour.", "After finishing the arena, temple-key, merchant and city reputation quests, defeat enough Hashishin defenders for Mora Sul to fall.", "Return to the quest giver or named destination after the objective triggers and exhaust the follow-up dialogue. For multi-item quests, verify every required key/item is actually in your inventory before entering a temple or reporting completion.", "Major city liberation; create a permanent save."),
            reward = "",
            warnings = "⚠ Faction / story warning: Make a permanent manual save before resolving this objective. It can remove major NPCs, close faction content, block trainers or commit the main story toward an ending.",
            searchTags = listOf("Liberate Mora Sul!", "Nomad / player action", "Mora Sul", "DEFER — NOMAD")
        ),
        Quest(
            id = "G3-P6-023",
            chapter = 6,
            playOrder = 23,
            title = "Find Saturas.",
            category = "SAFE / MAIN-STORY SUPPORT",
            giver = "Water Mage Saturas / Nomad contacts",
            location = "Al Shedim",
            prerequisites = "Visit the Water Mage and Nomad camp at Al Shedim.",
            summary = "Locate Saturas among the Water Mages at Al Shedim and exhaust his dialogue about the ruins, Nomads and ancient temple.",
            walkthroughSteps = listOf("Begin with Water Mage / Nomad chain. This quest is centered on Al Shedim. Use city gates, oases, excavation camps and large ruin complexes as navigation anchors; southern Varant has long stretches where a wrong canyon can add a major detour.", "Locate Saturas among the Water Mages at Al Shedim and exhaust his dialogue about the ruins, Nomads and ancient temple.", "Return to the quest giver or named destination after the objective triggers and exhaust the follow-up dialogue. For multi-item quests, verify every required key/item is actually in your inventory before entering a temple or reporting completion.", "Saturas is a major returning Gothic character; do not attack the Water Mages if you want their storyline."),
            reward = "",
            warnings = "Saturas holds a temple key and begins the Al Shedim research route. Preserve his quests before accepting Hashishin assassination orders.",
            searchTags = listOf("Find Saturas.", "Water Mage / Nomad chain", "Al Shedim", "SAFE / MAIN-STORY SUPPORT")
        ),
        Quest(
            id = "G3-P6-024",
            chapter = 6,
            playOrder = 24,
            title = "Talk to Myxir.",
            category = "SAFE",
            giver = "Myxir",
            location = "Al Shedim",
            prerequisites = "",
            summary = "Speak with Myxir and complete his dialogue/knowledge quests around the ruins.",
            walkthroughSteps = listOf("Begin with Myxir. This quest is centered on Al Shedim. Use city gates, oases, excavation camps and large ruin complexes as navigation anchors; southern Varant has long stretches where a wrong canyon can add a major detour.", "Speak with Myxir and complete his dialogue/knowledge quests around the ruins.", "Return to the quest giver or named destination after the objective triggers and exhaust the follow-up dialogue. For multi-item quests, verify every required key/item is actually in your inventory before entering a temple or reporting completion.", "He is part of the Water Mage network and may connect to ancient knowledge objectives."),
            reward = "",
            warnings = "",
            searchTags = listOf("Talk to Myxir.", "Myxir", "Al Shedim", "SAFE")
        ),
        Quest(
            id = "G3-P6-025",
            chapter = 6,
            playOrder = 25,
            title = "Talk to Riordian.",
            category = "SAFE",
            giver = "Riordian",
            location = "Al Shedim",
            prerequisites = "",
            summary = "Find Riordian and complete his Water Mage dialogue and any exploration tasks he provides.",
            walkthroughSteps = listOf("Begin with Riordian. This quest is centered on Al Shedim. Use city gates, oases, excavation camps and large ruin complexes as navigation anchors; southern Varant has long stretches where a wrong canyon can add a major detour.", "Find Riordian and complete his Water Mage dialogue and any exploration tasks he provides.", "Return to the quest giver or named destination after the objective triggers and exhaust the follow-up dialogue. For multi-item quests, verify every required key/item is actually in your inventory before entering a temple or reporting completion.", "Speak with every Water Mage before entering the temple."),
            reward = "",
            warnings = "",
            searchTags = listOf("Talk to Riordian.", "Riordian", "Al Shedim", "SAFE")
        ),
        Quest(
            id = "G3-P6-026",
            chapter = 6,
            playOrder = 26,
            title = "Explore the ruins of Al Shedim.",
            category = "SAFE / EXPLORATION",
            giver = "Saturas / Water Mages",
            location = "Al Shedim ruins",
            prerequisites = "",
            summary = "Search the ruined city, kill hostile creatures and undead, and collect the tablets/keys/items requested by the Water Mages.",
            walkthroughSteps = listOf("Begin with Saturas / Water Mages. This quest is centered on Al Shedim ruins. Use city gates, oases, excavation camps and large ruin complexes as navigation anchors; southern Varant has long stretches where a wrong canyon can add a major detour.", "Search the ruined city, kill hostile creatures and undead, and collect the tablets/keys/items requested by the Water Mages.", "Return to the quest giver or named destination after the objective triggers and exhaust the follow-up dialogue. For multi-item quests, verify every required key/item is actually in your inventory before entering a temple or reporting completion.", "Work sector by sector; the ruins are large and easy to search twice."),
            reward = "",
            warnings = "",
            searchTags = listOf("Explore the ruins of Al Shedim.", "Saturas / Water Mages", "Al Shedim ruins", "SAFE / EXPLORATION")
        ),
        Quest(
            id = "G3-P6-027",
            chapter = 6,
            playOrder = 27,
            title = "The temple keys of Al Shedim.",
            category = "MAJOR / TEMPLE KEYS",
            giver = "Saturas (Water Mage)",
            location = "Al Shedim",
            prerequisites = "Find Saturas in the Al Shedim ruins and ask about the temple.",
            summary = "Collect all keys required to open Al Shedim's temple. They are distributed through the surrounding ruins and quest chain.",
            walkthroughSteps = listOf("Meet Saturas at Al Shedim and obtain the first key through his dialogue.", "Meet Lester near the temple and help him deal with the Orcs occupying the nearby approach to receive his key.", "Search the ruined structures and treasure chests across Al Shedim for the remaining THREE temple keys.", "Once all five are in inventory, return to the temple door and unlock it. Avoid selling or dropping the keys."),
            reward = "Five Al Shedim keys permitting entry into the temple and recovery of the Robe of Adanos.",
            warnings = "Al Shedim's five keys have a DIFFERENT distribution from Mora Sul: Saturas one, Lester one, and three in scattered ruin chests.",
            searchTags = listOf("The temple keys of Al Shedim.", "Saturas / Nomads", "Al Shedim", "MAJOR / TEMPLE KEYS")
        ),
        Quest(
            id = "G3-P6-028",
            chapter = 6,
            playOrder = 28,
            title = "Find the ancient tablets.",
            category = "SAFE / COLLECTION",
            giver = "Water Mages",
            location = "Al Shedim ruins",
            prerequisites = "",
            summary = "Search ruins, chests and excavation areas for the requested ancient tablets and bring/report them to the Water Mages.",
            walkthroughSteps = listOf("Begin with Water Mages. This quest is centered on Al Shedim ruins. Use city gates, oases, excavation camps and large ruin complexes as navigation anchors; southern Varant has long stretches where a wrong canyon can add a major detour.", "Search ruins, chests and excavation areas for the requested ancient tablets and bring/report them to the Water Mages.", "Return to the quest giver or named destination after the objective triggers and exhaust the follow-up dialogue. For multi-item quests, verify every required key/item is actually in your inventory before entering a temple or reporting completion.", "Ancient tablets can also grant Ancient Knowledge, so distinguish quest-specific items from readable tablets."),
            reward = "",
            warnings = "",
            searchTags = listOf("Find the ancient tablets.", "Water Mages", "Al Shedim ruins", "SAFE / COLLECTION")
        ),
        Quest(
            id = "G3-P6-029",
            chapter = 6,
            playOrder = 29,
            title = "Kill the undead guardians in the ruins.",
            category = "SAFE",
            giver = "Water Mage / Nomad quest",
            location = "Al Shedim",
            prerequisites = "",
            summary = "Clear the specified undead groups guarding important ruin sectors.",
            walkthroughSteps = listOf("Begin with Water Mage / Nomad quest. This quest is centered on Al Shedim. Use city gates, oases, excavation camps and large ruin complexes as navigation anchors; southern Varant has long stretches where a wrong canyon can add a major detour.", "Clear the specified undead groups guarding important ruin sectors.", "Return to the quest giver or named destination after the objective triggers and exhaust the follow-up dialogue. For multi-item quests, verify every required key/item is actually in your inventory before entering a temple or reporting completion.", "Loot named undead and chests for keys."),
            reward = "",
            warnings = "",
            searchTags = listOf("Kill the undead guardians in the ruins.", "Water Mage / Nomad quest", "Al Shedim", "SAFE")
        ),
        Quest(
            id = "G3-P6-030",
            chapter = 6,
            playOrder = 30,
            title = "Open the temple of Al Shedim.",
            category = "MAJOR / DUNGEON",
            giver = "Ancient temple of Al Shedim (Saturas's questline)",
            location = "Al Shedim temple",
            prerequisites = "Acquire five Al Shedim keys: Saturas, Lester, and three ruin chests.",
            summary = "After gathering the required keys, open the ancient temple and fight through its guardians.",
            walkthroughSteps = listOf("Ask Saturas for a key and get Lester's key after addressing the Orc threat by the temple.", "Loot the other three keys from the chests scattered through Al Shedim's ruined compounds.", "Use the full five-key set to open the ancient temple entrance.", "Fight through the undead and locate the Robe of Adanos in the temple."),
            reward = "Access to the Al Shedim temple and Robe of Adanos.",
            warnings = "Do not confuse the Robe here with the Crown in Mora Sul. Both temples require their own five-key sets.",
            searchTags = listOf("Open the temple of Al Shedim.", "Saturas / temple chain", "Al Shedim temple", "MAJOR / DUNGEON")
        ),
        Quest(
            id = "G3-P6-031",
            chapter = 6,
            playOrder = 31,
            title = "Recover the Artifact of Adanos from Al Shedim.",
            category = "MAIN QUEST / ARTIFACT",
            giver = "Automatic on obtaining the Robe of Adanos",
            location = "Al Shedim temple",
            prerequisites = "Open Al Shedim's temple with its five distinct keys.",
            summary = "Recover the Robe of Adanos, one of the five divine artifacts, from the reopened Al Shedim temple.",
            walkthroughSteps = listOf("Meet Saturas and Lester at Al Shedim; gather their two keys plus the three from ruins chests.", "Unlock the temple, defeat undead guardians and search the inner sanctum for the Robe of Adanos.", "Preserve the Robe alongside the Crown, Amulet and two rings until the three-way endgame choice."),
            reward = "Robe of Adanos.",
            warnings = "The artifact here is specifically the Robe, not an unidentified relic or Adanos ring.",
            searchTags = listOf("Recover the Artifact of Adanos from Al Shedim.", "Main story", "Al Shedim temple", "MAIN QUEST / ARTIFACT")
        ),
        Quest(
            id = "G3-P6-032",
            chapter = 6,
            playOrder = 32,
            title = "Help the Nomads at Al Shedim.",
            category = "SAFE — NOMAD",
            giver = "Nomad leaders",
            location = "Al Shedim",
            prerequisites = "",
            summary = "Complete the local Nomad support quests, including clearing enemies and helping secure the ruins.",
            walkthroughSteps = listOf("Begin with Nomad leaders. This quest is centered on Al Shedim. Use city gates, oases, excavation camps and large ruin complexes as navigation anchors; southern Varant has long stretches where a wrong canyon can add a major detour.", "Complete the local Nomad support quests, including clearing enemies and helping secure the ruins.", "Return to the quest giver or named destination after the objective triggers and exhaust the follow-up dialogue. For multi-item quests, verify every required key/item is actually in your inventory before entering a temple or reporting completion.", "Do these before accepting Hashishin contracts against the Water Mages."),
            reward = "",
            warnings = "",
            searchTags = listOf("Help the Nomads at Al Shedim.", "Nomad leaders", "Al Shedim", "SAFE — NOMAD")
        ),
        Quest(
            id = "G3-P6-033",
            chapter = 6,
            playOrder = 33,
            title = "Kill the Water Mages.",
            category = "DEFER — HASHISHIN",
            giver = "Hashishin / Gonzales / Zuben route",
            location = "Varant",
            prerequisites = "",
            summary = "Only on a committed Hashishin/Beliar route, hunt the Water Mages named by the quest and report their deaths.",
            walkthroughSteps = listOf("Begin with Hashishin / Gonzales / Zuben route. This quest is centered on Varant. Use city gates, oases, excavation camps and large ruin complexes as navigation anchors; southern Varant has long stretches where a wrong canyon can add a major detour.", "Only on a committed Hashishin/Beliar route, hunt the Water Mages named by the quest and report their deaths.", "Return to the quest giver or named destination after the objective triggers and exhaust the follow-up dialogue. For multi-item quests, verify every required key/item is actually in your inventory before entering a temple or reporting completion.", "This permanently removes major story/lore NPCs. Complete every Water Mage quest first."),
            reward = "",
            warnings = "⚠ Faction / story warning: Make a permanent manual save before resolving this objective. It can remove major NPCs, close faction content, block trainers or commit the main story toward an ending.",
            searchTags = listOf("Kill the Water Mages.", "Hashishin / Gonzales / Zuben route", "Varant", "DEFER — HASHISHIN")
        ),
        Quest(
            id = "G3-P6-034",
            chapter = 6,
            playOrder = 34,
            title = "Defend Al Shedim from hostile forces.",
            category = "CHOICE — NOMAD",
            giver = "Nomad / Water Mage chain",
            location = "Al Shedim",
            prerequisites = "",
            summary = "Help the Nomads and Water Mages defeat the hostile group threatening the ruins.",
            walkthroughSteps = listOf("Begin with Nomad / Water Mage chain. This quest is centered on Al Shedim. Use city gates, oases, excavation camps and large ruin complexes as navigation anchors; southern Varant has long stretches where a wrong canyon can add a major detour.", "Help the Nomads and Water Mages defeat the hostile group threatening the ruins.", "Return to the quest giver or named destination after the objective triggers and exhaust the follow-up dialogue. For multi-item quests, verify every required key/item is actually in your inventory before entering a temple or reporting completion.", "Can conflict with Hashishin assassination objectives."),
            reward = "",
            warnings = "⚠ Faction / story warning: Make a permanent manual save before resolving this objective. It can remove major NPCs, close faction content, block trainers or commit the main story toward an ending.",
            searchTags = listOf("Defend Al Shedim from hostile forces.", "Nomad / Water Mage chain", "Al Shedim", "CHOICE — NOMAD")
        ),
        Quest(
            id = "G3-P6-035",
            chapter = 6,
            playOrder = 35,
            title = "Gain access to the temple of Beliar.",
            category = "SAFE / REPUTATION GATE",
            giver = "Bakaresh Hashishin",
            location = "Bakaresh",
            prerequisites = "Build Bakaresh local standing to gain access to Tizgar and the Temple of Beliar.",
            summary = "Complete enough Bakaresh city quests and reputation tasks to be admitted to the upper temple area.",
            walkthroughSteps = listOf("Begin with Bakaresh Hashishin. This quest is centered on Bakaresh. Use city gates, oases, excavation camps and large ruin complexes as navigation anchors; southern Varant has long stretches where a wrong canyon can add a major detour.", "Complete enough Bakaresh city quests and reputation tasks to be admitted to the upper temple area.", "Return to the quest giver or named destination after the objective triggers and exhaust the follow-up dialogue. For multi-item quests, verify every required key/item is actually in your inventory before entering a temple or reporting completion.", "Do neutral trader, arena and hunting work before faction violence."),
            reward = "",
            warnings = "Do not confuse entering the local Beliar temple with committing to the Beliar ending; the final ritual requires the five divine artifacts.",
            searchTags = listOf("Gain access to the temple of Beliar.", "Bakaresh Hashishin", "Bakaresh", "SAFE / REPUTATION GATE")
        ),
        Quest(
            id = "G3-P6-036",
            chapter = 6,
            playOrder = 36,
            title = "Talk to Tizgar.",
            category = "SAFE",
            giver = "Tizgar",
            location = "Bakaresh",
            prerequisites = "",
            summary = "Once admitted, speak with Tizgar and exhaust his dialogue about Beliar, the city and the Hashishin hierarchy.",
            walkthroughSteps = listOf("Begin with Tizgar. This quest is centered on Bakaresh. Use city gates, oases, excavation camps and large ruin complexes as navigation anchors; southern Varant has long stretches where a wrong canyon can add a major detour.", "Once admitted, speak with Tizgar and exhaust his dialogue about Beliar, the city and the Hashishin hierarchy.", "Return to the quest giver or named destination after the objective triggers and exhaust the follow-up dialogue. For multi-item quests, verify every required key/item is actually in your inventory before entering a temple or reporting completion.", "Important for understanding Bakaresh's religious/political role."),
            reward = "",
            warnings = "",
            searchTags = listOf("Talk to Tizgar.", "Tizgar", "Bakaresh", "SAFE")
        ),
        Quest(
            id = "G3-P6-037",
            chapter = 6,
            playOrder = 37,
            title = "The arena of Bakaresh.",
            category = "SAFE — ARENA",
            giver = "Arena organizer",
            location = "Bakaresh",
            prerequisites = "",
            summary = "Enter the arena and defeat each available opponent under normal non-lethal rules.",
            walkthroughSteps = listOf("Begin with Arena organizer. This quest is centered on Bakaresh. Use city gates, oases, excavation camps and large ruin complexes as navigation anchors; southern Varant has long stretches where a wrong canyon can add a major detour.", "Enter the arena and defeat each available opponent under normal non-lethal rules.", "Return to the quest giver or named destination after the objective triggers and exhaust the follow-up dialogue. For multi-item quests, verify every required key/item is actually in your inventory before entering a temple or reporting completion.", "Finish the entire arena before liberating Bakaresh."),
            reward = "",
            warnings = "",
            searchTags = listOf("The arena of Bakaresh.", "Arena organizer", "Bakaresh", "SAFE — ARENA")
        ),
        Quest(
            id = "G3-P6-038",
            chapter = 6,
            playOrder = 38,
            title = "Defeat Bakaresh's arena champion.",
            category = "SAFE — ARENA",
            giver = "Arena champion",
            location = "Bakaresh",
            prerequisites = "",
            summary = "Win the final local arena fight and collect the reward/reputation.",
            walkthroughSteps = listOf("Begin with Arena champion. This quest is centered on Bakaresh. Use city gates, oases, excavation camps and large ruin complexes as navigation anchors; southern Varant has long stretches where a wrong canyon can add a major detour.", "Win the final local arena fight and collect the reward/reputation.", "Return to the quest giver or named destination after the objective triggers and exhaust the follow-up dialogue. For multi-item quests, verify every required key/item is actually in your inventory before entering a temple or reporting completion.", "Good route to temple access."),
            reward = "",
            warnings = "",
            searchTags = listOf("Defeat Bakaresh's arena champion.", "Arena champion", "Bakaresh", "SAFE — ARENA")
        ),
        Quest(
            id = "G3-P6-039",
            chapter = 6,
            playOrder = 39,
            title = "Collect tribute in Bakaresh.",
            category = "SAFE / COLLECTION",
            giver = "Bakaresh quest giver",
            location = "Bakaresh",
            prerequisites = "",
            summary = "Collect the requested payments from the named merchants/citizens and return the total.",
            walkthroughSteps = listOf("Begin with Bakaresh quest giver. This quest is centered on Bakaresh. Use city gates, oases, excavation camps and large ruin complexes as navigation anchors; southern Varant has long stretches where a wrong canyon can add a major detour.", "Collect the requested payments from the named merchants/citizens and return the total.", "Return to the quest giver or named destination after the objective triggers and exhaust the follow-up dialogue. For multi-item quests, verify every required key/item is actually in your inventory before entering a temple or reporting completion.", "Do all debtor conversations before spending the gold."),
            reward = "",
            warnings = "",
            searchTags = listOf("Collect tribute in Bakaresh.", "Bakaresh quest giver", "Bakaresh", "SAFE / COLLECTION")
        ),
        Quest(
            id = "G3-P6-040",
            chapter = 6,
            playOrder = 40,
            title = "A merchant's missing goods.",
            category = "SAFE",
            giver = "Bakaresh merchant",
            location = "Bakaresh outskirts",
            prerequisites = "",
            summary = "Locate the stolen or missing shipment, recover the quest goods and return them.",
            walkthroughSteps = listOf("Begin with Bakaresh merchant. This quest is centered on Bakaresh outskirts. Use city gates, oases, excavation camps and large ruin complexes as navigation anchors; southern Varant has long stretches where a wrong canyon can add a major detour.", "Locate the stolen or missing shipment, recover the quest goods and return them.", "Return to the quest giver or named destination after the objective triggers and exhaust the follow-up dialogue. For multi-item quests, verify every required key/item is actually in your inventory before entering a temple or reporting completion.", "Search bandit bodies and crates carefully."),
            reward = "",
            warnings = "",
            searchTags = listOf("A merchant's missing goods.", "Bakaresh merchant", "Bakaresh outskirts", "SAFE")
        ),
        Quest(
            id = "G3-P6-041",
            chapter = 6,
            playOrder = 41,
            title = "Bandits outside Bakaresh.",
            category = "SAFE",
            giver = "Bakaresh guard/merchant",
            location = "Bakaresh region",
            prerequisites = "",
            summary = "Find and eliminate the bandit group threatening trade near Bakaresh.",
            walkthroughSteps = listOf("Begin with Bakaresh guard/merchant. This quest is centered on Bakaresh region. Use city gates, oases, excavation camps and large ruin complexes as navigation anchors; southern Varant has long stretches where a wrong canyon can add a major detour.", "Find and eliminate the bandit group threatening trade near Bakaresh.", "Return to the quest giver or named destination after the objective triggers and exhaust the follow-up dialogue. For multi-item quests, verify every required key/item is actually in your inventory before entering a temple or reporting completion.", "Complete alongside missing-goods quests."),
            reward = "",
            warnings = "",
            searchTags = listOf("Bandits outside Bakaresh.", "Bakaresh guard/merchant", "Bakaresh region", "SAFE")
        ),
        Quest(
            id = "G3-P6-042",
            chapter = 6,
            playOrder = 42,
            title = "Hunt the desert predators.",
            category = "SAFE",
            giver = "Bakaresh hunter",
            location = "Bakaresh wilderness",
            prerequisites = "",
            summary = "Kill the specified predators and return to the hunter.",
            walkthroughSteps = listOf("Begin with Bakaresh hunter. This quest is centered on Bakaresh wilderness. Use city gates, oases, excavation camps and large ruin complexes as navigation anchors; southern Varant has long stretches where a wrong canyon can add a major detour.", "Kill the specified predators and return to the hunter.", "Return to the quest giver or named destination after the objective triggers and exhaust the follow-up dialogue. For multi-item quests, verify every required key/item is actually in your inventory before entering a temple or reporting completion.", "Use these safe jobs for reputation."),
            reward = "",
            warnings = "",
            searchTags = listOf("Hunt the desert predators.", "Bakaresh hunter", "Bakaresh wilderness", "SAFE")
        ),
        Quest(
            id = "G3-P6-043",
            chapter = 6,
            playOrder = 43,
            title = "The slave problem in Bakaresh.",
            category = "CHOICE",
            giver = "Bakaresh quest chain",
            location = "Bakaresh",
            prerequisites = "",
            summary = "Investigate the slaves involved in the local quest and resolve their fate according to your faction preference.",
            walkthroughSteps = listOf("Begin with Bakaresh quest chain. This quest is centered on Bakaresh. Use city gates, oases, excavation camps and large ruin complexes as navigation anchors; southern Varant has long stretches where a wrong canyon can add a major detour.", "Investigate the slaves involved in the local quest and resolve their fate according to your faction preference.", "Return to the quest giver or named destination after the objective triggers and exhaust the follow-up dialogue. For multi-item quests, verify every required key/item is actually in your inventory before entering a temple or reporting completion.", "Save before choosing return/punishment/freedom outcomes."),
            reward = "",
            warnings = "⚠ Faction / story warning: Make a permanent manual save before resolving this objective. It can remove major NPCs, close faction content, block trainers or commit the main story toward an ending.",
            searchTags = listOf("The slave problem in Bakaresh.", "Bakaresh quest chain", "Bakaresh", "CHOICE")
        ),
        Quest(
            id = "G3-P6-044",
            chapter = 6,
            playOrder = 44,
            title = "A favor for the temple.",
            category = "SAFE",
            giver = "Bakaresh temple NPC",
            location = "Bakaresh",
            prerequisites = "",
            summary = "Complete the requested delivery or service for the temple faction to gain standing.",
            walkthroughSteps = listOf("Begin with Bakaresh temple NPC. This quest is centered on Bakaresh. Use city gates, oases, excavation camps and large ruin complexes as navigation anchors; southern Varant has long stretches where a wrong canyon can add a major detour.", "Complete the requested delivery or service for the temple faction to gain standing.", "Return to the quest giver or named destination after the objective triggers and exhaust the follow-up dialogue. For multi-item quests, verify every required key/item is actually in your inventory before entering a temple or reporting completion.", "Useful peaceful path toward upper-city access."),
            reward = "",
            warnings = "",
            searchTags = listOf("A favor for the temple.", "Bakaresh temple NPC", "Bakaresh", "SAFE")
        ),
        Quest(
            id = "G3-P6-045",
            chapter = 6,
            playOrder = 45,
            title = "Talk to the black mage.",
            category = "SAFE / LORE",
            giver = "Bakaresh temple",
            location = "Bakaresh",
            prerequisites = "",
            summary = "Meet the Black Mage in the temple and exhaust the dialogue about Beliar and the Hashishin.",
            walkthroughSteps = listOf("Begin with Bakaresh temple. This quest is centered on Bakaresh. Use city gates, oases, excavation camps and large ruin complexes as navigation anchors; southern Varant has long stretches where a wrong canyon can add a major detour.", "Meet the Black Mage in the temple and exhaust the dialogue about Beliar and the Hashishin.", "Return to the quest giver or named destination after the objective triggers and exhaust the follow-up dialogue. For multi-item quests, verify every required key/item is actually in your inventory before entering a temple or reporting completion.", "Do this before any Nomad liberation."),
            reward = "",
            warnings = "",
            searchTags = listOf("Talk to the black mage.", "Bakaresh temple", "Bakaresh", "SAFE / LORE")
        ),
        Quest(
            id = "G3-P6-046",
            chapter = 6,
            playOrder = 46,
            title = "The Nomads near Bakaresh.",
            category = "DEFER — HASHISHIN",
            giver = "Hashishin leadership",
            location = "Bakaresh region",
            prerequisites = "",
            summary = "Destroy the designated Nomad group only if committing to the Hashishin route.",
            walkthroughSteps = listOf("Begin with Hashishin leadership. This quest is centered on Bakaresh region. Use city gates, oases, excavation camps and large ruin complexes as navigation anchors; southern Varant has long stretches where a wrong canyon can add a major detour.", "Destroy the designated Nomad group only if committing to the Hashishin route.", "Return to the quest giver or named destination after the objective triggers and exhaust the follow-up dialogue. For multi-item quests, verify every required key/item is actually in your inventory before entering a temple or reporting completion.", "Visit the Nomads first for their quests."),
            reward = "",
            warnings = "⚠ Faction / story warning: Make a permanent manual save before resolving this objective. It can remove major NPCs, close faction content, block trainers or commit the main story toward an ending.",
            searchTags = listOf("The Nomads near Bakaresh.", "Hashishin leadership", "Bakaresh region", "DEFER — HASHISHIN")
        ),
        Quest(
            id = "G3-P6-047",
            chapter = 6,
            playOrder = 47,
            title = "Help the Nomads against Bakaresh.",
            category = "DEFER — NOMAD",
            giver = "Nomad leader",
            location = "Bakaresh region",
            prerequisites = "",
            summary = "Prepare the Nomad attack/support operation against Bakaresh after finishing city content.",
            walkthroughSteps = listOf("Begin with Nomad leader. This quest is centered on Bakaresh region. Use city gates, oases, excavation camps and large ruin complexes as navigation anchors; southern Varant has long stretches where a wrong canyon can add a major detour.", "Prepare the Nomad attack/support operation against Bakaresh after finishing city content.", "Return to the quest giver or named destination after the objective triggers and exhaust the follow-up dialogue. For multi-item quests, verify every required key/item is actually in your inventory before entering a temple or reporting completion.", "Faction commitment."),
            reward = "",
            warnings = "⚠ Faction / story warning: Make a permanent manual save before resolving this objective. It can remove major NPCs, close faction content, block trainers or commit the main story toward an ending.",
            searchTags = listOf("Help the Nomads against Bakaresh.", "Nomad leader", "Bakaresh region", "DEFER — NOMAD")
        ),
        Quest(
            id = "G3-P6-048",
            chapter = 6,
            playOrder = 48,
            title = "Liberate Bakaresh!",
            category = "DEFER — NOMAD",
            giver = "Nomad / player action",
            location = "Bakaresh",
            prerequisites = "",
            summary = "After completing arena, temple, merchant and reputation quests, attack the Hashishin occupation and defeat enough defenders to liberate the city.",
            walkthroughSteps = listOf("Begin with Nomad / player action. This quest is centered on Bakaresh. Use city gates, oases, excavation camps and large ruin complexes as navigation anchors; southern Varant has long stretches where a wrong canyon can add a major detour.", "After completing arena, temple, merchant and reputation quests, attack the Hashishin occupation and defeat enough defenders to liberate the city.", "Return to the quest giver or named destination after the objective triggers and exhaust the follow-up dialogue. For multi-item quests, verify every required key/item is actually in your inventory before entering a temple or reporting completion.", "Bakaresh is large and heavily defended; save before beginning."),
            reward = "",
            warnings = "⚠ Faction / story warning: Make a permanent manual save before resolving this objective. It can remove major NPCs, close faction content, block trainers or commit the main story toward an ending.",
            searchTags = listOf("Liberate Bakaresh!", "Nomad / player action", "Bakaresh", "DEFER — NOMAD")
        ),
        Quest(
            id = "G3-P6-049",
            chapter = 6,
            playOrder = 49,
            title = "Beliar's instructions.",
            category = "ENDGAME CHOICE",
            giver = "Beliar (through his shrine in Bakaresh)",
            location = "Bakaresh temple",
            prerequisites = "Collect the five Artifacts of Adanos and choose the Beliar ending at his shrine.",
            summary = "At the appropriate main-story stage, Beliar's path can direct you toward killing rival leaders and delivering the divine artifacts to his cause.",
            walkthroughSteps = listOf("Gather all five artifacts of Adanos and prepare a permanent save before entering the Beliar shrine ritual.", "Travel to the Temple of Beliar in Bakaresh and accept Beliar's endgame instructions.", "Follow the required assassination and faction war objectives against his opponents, including Rhobar, Xardas and Orc leaders as assigned; complete prior faction content first.", "Return to the god's shrine to close the final Beliar route."),
            reward = "Beliar-aligned endgame branch and the divine power ritual.",
            warnings = "IRREVERSIBLE ENDING: the Beliar shrine commits the five artifacts. Finish competing Rhobar, Xardas, Orc and Water Mage quests first.",
            searchTags = listOf("Beliar's instructions.", "Beliar shrine / main story", "Bakaresh temple", "ENDGAME CHOICE")
        ),
        Quest(
            id = "G3-P6-050",
            chapter = 6,
            playOrder = 50,
            title = "Gain access to Ishtar.",
            category = "MAJOR / REPUTATION GATE",
            giver = "Ishtar guards / Hashishin reputation",
            location = "Ishtar",
            prerequisites = "75 Hashishin faction reputation to enter Ishtar peacefully; this is GLOBAL reputation, not a local 75% in Mora Sul or Braga.",
            summary = "Raise Hashishin reputation sufficiently to pass Ishtar's gate and enter the capital. Complete Hashishin-friendly quests around Varant if this access matters to your playthrough.",
            walkthroughSteps = listOf("Check your global HASHISHIN faction reputation in the status menu. Ishtar's gate requires 75 to admit you peacefully.", "Do neutral and Hashishin-friendly work in Braga, Ben Erai, Lago, Mora Sul and Bakaresh before liberating their towns.", "Be careful with quests demanding Water Mage or Nomad deaths: killing important NPCs is permanent and can block artifact and ally content.", "At 75 Hashishin reputation, approach Ishtar's gate and gain access to Zuben's capital; complete the arena and trainer content you want before opposing him."),
            reward = "Peaceful access to Ishtar, Zuben and specialized Hashishin combat trainers.",
            warnings = "75 reputation means HASHISHIN FACTION reputation, not a single city's local reputation. Early town liberations may make peaceful access impossible in the base game.",
            searchTags = listOf("Gain access to Ishtar.", "Ishtar guards / Hashishin reputation", "Ishtar", "MAJOR / REPUTATION GATE")
        ),
        Quest(
            id = "G3-P6-051",
            chapter = 6,
            playOrder = 51,
            title = "Talk to Zuben.",
            category = "MAIN QUEST",
            giver = "Zuben",
            location = "Ishtar",
            prerequisites = "Enter Ishtar, usually at 75 Hashishin faction reputation, and reach Zuben's residence.",
            summary = "After gaining entry and access to the palace, speak with Zuben and exhaust his dialogue about the Hashishin, Beliar and the divine artifacts.",
            walkthroughSteps = listOf("Begin with Zuben. This quest is centered on Ishtar. Use city gates, oases, excavation camps and large ruin complexes as navigation anchors; southern Varant has long stretches where a wrong canyon can add a major detour.", "After gaining entry and access to the palace, speak with Zuben and exhaust his dialogue about the Hashishin, Beliar and the divine artifacts.", "Return to the quest giver or named destination after the objective triggers and exhaust the follow-up dialogue. For multi-item quests, verify every required key/item is actually in your inventory before entering a temple or reporting completion.", "Zuben is one of Gothic 3's major faction leaders."),
            reward = "",
            warnings = "Zuben possesses the Staff of the Eternal Wanderer needed for Xardas's portal ending. Preserve his dialogue and the staff until the final route is decided.",
            searchTags = listOf("Talk to Zuben.", "Zuben", "Ishtar", "MAIN QUEST")
        ),
        Quest(
            id = "G3-P6-052",
            chapter = 6,
            playOrder = 52,
            title = "Train with the Hashishin masters.",
            category = "SAFE",
            giver = "Ishtar trainers",
            location = "Ishtar",
            prerequisites = "",
            summary = "Use Ishtar's unique trainers after earning access and completing their prerequisite tasks.",
            walkthroughSteps = listOf("Begin with Ishtar trainers. This quest is centered on Ishtar. Use city gates, oases, excavation camps and large ruin complexes as navigation anchors; southern Varant has long stretches where a wrong canyon can add a major detour.", "Use Ishtar's unique trainers after earning access and completing their prerequisite tasks.", "Return to the quest giver or named destination after the objective triggers and exhaust the follow-up dialogue. For multi-item quests, verify every required key/item is actually in your inventory before entering a temple or reporting completion.", "Do this before making Ishtar hostile; some advanced skills are easiest to learn here."),
            reward = "",
            warnings = "",
            searchTags = listOf("Train with the Hashishin masters.", "Ishtar trainers", "Ishtar", "SAFE")
        ),
        Quest(
            id = "G3-P6-053",
            chapter = 6,
            playOrder = 53,
            title = "The arena of Ishtar.",
            category = "SAFE — ARENA",
            giver = "Ishtar arena organizer",
            location = "Ishtar",
            prerequisites = "",
            summary = "Enter Ishtar's elite arena and defeat the available opponents in sequence.",
            walkthroughSteps = listOf("Begin with Ishtar arena organizer. This quest is centered on Ishtar. Use city gates, oases, excavation camps and large ruin complexes as navigation anchors; southern Varant has long stretches where a wrong canyon can add a major detour.", "Enter Ishtar's elite arena and defeat the available opponents in sequence.", "Return to the quest giver or named destination after the objective triggers and exhaust the follow-up dialogue. For multi-item quests, verify every required key/item is actually in your inventory before entering a temple or reporting completion.", "These are late-game fighters; arrive well equipped."),
            reward = "",
            warnings = "",
            searchTags = listOf("The arena of Ishtar.", "Ishtar arena organizer", "Ishtar", "SAFE — ARENA")
        ),
        Quest(
            id = "G3-P6-054",
            chapter = 6,
            playOrder = 54,
            title = "Defeat the first Ishtar fighter.",
            category = "SAFE — ARENA",
            giver = "Ishtar arena",
            location = "Ishtar",
            prerequisites = "",
            summary = "Beat the first elite opponent without leaving the arena.",
            walkthroughSteps = listOf("Begin with Ishtar arena. This quest is centered on Ishtar. Use city gates, oases, excavation camps and large ruin complexes as navigation anchors; southern Varant has long stretches where a wrong canyon can add a major detour.", "Beat the first elite opponent without leaving the arena.", "Return to the quest giver or named destination after the objective triggers and exhaust the follow-up dialogue. For multi-item quests, verify every required key/item is actually in your inventory before entering a temple or reporting completion.", "Use potions/buffs before starting if needed."),
            reward = "",
            warnings = "",
            searchTags = listOf("Defeat the first Ishtar fighter.", "Ishtar arena", "Ishtar", "SAFE — ARENA")
        ),
        Quest(
            id = "G3-P6-055",
            chapter = 6,
            playOrder = 55,
            title = "Defeat the second Ishtar fighter.",
            category = "SAFE — ARENA",
            giver = "Ishtar arena",
            location = "Ishtar",
            prerequisites = "",
            summary = "Defeat the next arena opponent and finish the post-fight dialogue.",
            walkthroughSteps = listOf("Begin with Ishtar arena. This quest is centered on Ishtar. Use city gates, oases, excavation camps and large ruin complexes as navigation anchors; southern Varant has long stretches where a wrong canyon can add a major detour.", "Defeat the next arena opponent and finish the post-fight dialogue.", "Return to the quest giver or named destination after the objective triggers and exhaust the follow-up dialogue. For multi-item quests, verify every required key/item is actually in your inventory before entering a temple or reporting completion.", "Continue until the champion becomes available."),
            reward = "",
            warnings = "",
            searchTags = listOf("Defeat the second Ishtar fighter.", "Ishtar arena", "Ishtar", "SAFE — ARENA")
        ),
        Quest(
            id = "G3-P6-056",
            chapter = 6,
            playOrder = 56,
            title = "Defeat the champion of Ishtar.",
            category = "SAFE — ARENA",
            giver = "Ishtar champion",
            location = "Ishtar",
            prerequisites = "",
            summary = "Beat Ishtar's strongest arena fighter and collect the final arena reward.",
            walkthroughSteps = listOf("Begin with Ishtar champion. This quest is centered on Ishtar. Use city gates, oases, excavation camps and large ruin complexes as navigation anchors; southern Varant has long stretches where a wrong canyon can add a major detour.", "Beat Ishtar's strongest arena fighter and collect the final arena reward.", "Return to the quest giver or named destination after the objective triggers and exhaust the follow-up dialogue. For multi-item quests, verify every required key/item is actually in your inventory before entering a temple or reporting completion.", "Complete before attacking Zuben or liberating the city."),
            reward = "",
            warnings = "",
            searchTags = listOf("Defeat the champion of Ishtar.", "Ishtar champion", "Ishtar", "SAFE — ARENA")
        ),
        Quest(
            id = "G3-P6-057",
            chapter = 6,
            playOrder = 57,
            title = "A test for the assassins.",
            category = "SAFE / HASHISHIN",
            giver = "Ishtar master",
            location = "Ishtar",
            prerequisites = "",
            summary = "Complete the combat, hunting or assassination-style test assigned by the Hashishin master.",
            walkthroughSteps = listOf("Begin with Ishtar master. This quest is centered on Ishtar. Use city gates, oases, excavation camps and large ruin complexes as navigation anchors; southern Varant has long stretches where a wrong canyon can add a major detour.", "Complete the combat, hunting or assassination-style test assigned by the Hashishin master.", "Return to the quest giver or named destination after the objective triggers and exhaust the follow-up dialogue. For multi-item quests, verify every required key/item is actually in your inventory before entering a temple or reporting completion.", "Some tests involve targets outside Ishtar; read the target carefully before killing unrelated NPCs."),
            reward = "",
            warnings = "",
            searchTags = listOf("A test for the assassins.", "Ishtar master", "Ishtar", "SAFE / HASHISHIN")
        ),
        Quest(
            id = "G3-P6-058",
            chapter = 6,
            playOrder = 58,
            title = "A lesson in two-sword fighting.",
            category = "SAFE / TRAINING",
            giver = "Ishtar trainer",
            location = "Ishtar",
            prerequisites = "",
            summary = "Complete the trainer's prerequisite quest/reputation requirement and learn the advanced dual-wield skill if desired.",
            walkthroughSteps = listOf("Begin with Ishtar trainer. This quest is centered on Ishtar. Use city gates, oases, excavation camps and large ruin complexes as navigation anchors; southern Varant has long stretches where a wrong canyon can add a major detour.", "Complete the trainer's prerequisite quest/reputation requirement and learn the advanced dual-wield skill if desired.", "Return to the quest giver or named destination after the objective triggers and exhaust the follow-up dialogue. For multi-item quests, verify every required key/item is actually in your inventory before entering a temple or reporting completion.", "One of the strongest reasons to preserve Ishtar access on a completionist run."),
            reward = "",
            warnings = "",
            searchTags = listOf("A lesson in two-sword fighting.", "Ishtar trainer", "Ishtar", "SAFE / TRAINING")
        ),
        Quest(
            id = "G3-P6-059",
            chapter = 6,
            playOrder = 59,
            title = "The slave training in Ishtar.",
            category = "CHOICE",
            giver = "Ishtar quest giver",
            location = "Ishtar",
            prerequisites = "",
            summary = "Complete the slave-related training/control objective or choose the alternative consistent with your faction route.",
            walkthroughSteps = listOf("Begin with Ishtar quest giver. This quest is centered on Ishtar. Use city gates, oases, excavation camps and large ruin complexes as navigation anchors; southern Varant has long stretches where a wrong canyon can add a major detour.", "Complete the slave-related training/control objective or choose the alternative consistent with your faction route.", "Return to the quest giver or named destination after the objective triggers and exhaust the follow-up dialogue. For multi-item quests, verify every required key/item is actually in your inventory before entering a temple or reporting completion.", "Resolve all dialogue before violence."),
            reward = "",
            warnings = "⚠ Faction / story warning: Make a permanent manual save before resolving this objective. It can remove major NPCs, close faction content, block trainers or commit the main story toward an ending.",
            searchTags = listOf("The slave training in Ishtar.", "Ishtar quest giver", "Ishtar", "CHOICE")
        ),
        Quest(
            id = "G3-P6-060",
            chapter = 6,
            playOrder = 60,
            title = "Kill the Water Mages for Zuben.",
            category = "DEFER — HASHISHIN",
            giver = "Zuben / Hashishin",
            location = "Varant",
            prerequisites = "",
            summary = "Track down and kill the Water Mages named by the Hashishin leadership, then report the results.",
            walkthroughSteps = listOf("Begin with Zuben / Hashishin. This quest is centered on Varant. Use city gates, oases, excavation camps and large ruin complexes as navigation anchors; southern Varant has long stretches where a wrong canyon can add a major detour.", "Track down and kill the Water Mages named by the Hashishin leadership, then report the results.", "Return to the quest giver or named destination after the objective triggers and exhaust the follow-up dialogue. For multi-item quests, verify every required key/item is actually in your inventory before entering a temple or reporting completion.", "Do every Al Shedim and Water Mage quest first. This permanently removes major NPCs."),
            reward = "",
            warnings = "⚠ Faction / story warning: Make a permanent manual save before resolving this objective. It can remove major NPCs, close faction content, block trainers or commit the main story toward an ending.",
            searchTags = listOf("Kill the Water Mages for Zuben.", "Zuben / Hashishin", "Varant", "DEFER — HASHISHIN")
        ),
        Quest(
            id = "G3-P6-061",
            chapter = 6,
            playOrder = 61,
            title = "Kill the Nomad leaders.",
            category = "DEFER — HASHISHIN",
            giver = "Zuben / Hashishin",
            location = "Varant",
            prerequisites = "",
            summary = "Eliminate the designated Nomad leaders across Varant and report to Zuben.",
            walkthroughSteps = listOf("Begin with Zuben / Hashishin. This quest is centered on Varant. Use city gates, oases, excavation camps and large ruin complexes as navigation anchors; southern Varant has long stretches where a wrong canyon can add a major detour.", "Eliminate the designated Nomad leaders across Varant and report to Zuben.", "Return to the quest giver or named destination after the objective triggers and exhaust the follow-up dialogue. For multi-item quests, verify every required key/item is actually in your inventory before entering a temple or reporting completion.", "A region-wide faction purge; leave until late."),
            reward = "",
            warnings = "⚠ Faction / story warning: Make a permanent manual save before resolving this objective. It can remove major NPCs, close faction content, block trainers or commit the main story toward an ending.",
            searchTags = listOf("Kill the Nomad leaders.", "Zuben / Hashishin", "Varant", "DEFER — HASHISHIN")
        ),
        Quest(
            id = "G3-P6-062",
            chapter = 6,
            playOrder = 62,
            title = "Find the divine artifacts for Zuben.",
            category = "MAIN QUEST / CHOICE",
            giver = "Zuben",
            location = "World / Varant",
            prerequisites = "Gain access to Zuben and follow his artifact investigation.",
            summary = "Discuss the five Artifacts of Adanos with Zuben and follow the Beliar-aligned route only if that is your chosen ending.",
            walkthroughSteps = listOf("Begin with Zuben. This quest is centered on World / Varant. Use city gates, oases, excavation camps and large ruin complexes as navigation anchors; southern Varant has long stretches where a wrong canyon can add a major detour.", "Discuss the five Artifacts of Adanos with Zuben and follow the Beliar-aligned route only if that is your chosen ending.", "Return to the quest giver or named destination after the objective triggers and exhaust the follow-up dialogue. For multi-item quests, verify every required key/item is actually in your inventory before entering a temple or reporting completion.", "The same five artifacts are contested by the game's major ending paths."),
            reward = "",
            warnings = "Zuben's path is not the same as Xardas's destruction route. Do not destroy the artifacts if you intend to offer them to a god.",
            searchTags = listOf("Find the divine artifacts for Zuben.", "Zuben", "World / Varant", "MAIN QUEST / CHOICE")
        ),
        Quest(
            id = "G3-P6-063",
            chapter = 6,
            playOrder = 63,
            title = "Kill King Rhobar.",
            category = "ENDGAME CHOICE",
            giver = "Zuben / Beliar route",
            location = "Vengard",
            prerequisites = "Beliar/Xardas endgame route; complete any desired King Rhobar quests first.",
            summary = "On the relevant Beliar/Hashishin path, return to Vengard and kill King Rhobar as directed.",
            walkthroughSteps = listOf("Begin with Zuben / Beliar route. This quest is centered on Vengard. Use city gates, oases, excavation camps and large ruin complexes as navigation anchors; southern Varant has long stretches where a wrong canyon can add a major detour.", "On the relevant Beliar/Hashishin path, return to Vengard and kill King Rhobar as directed.", "Return to the quest giver or named destination after the objective triggers and exhaust the follow-up dialogue. For multi-item quests, verify every required key/item is actually in your inventory before entering a temple or reporting completion.", "Major irreversible story choice. Finish Rhobar/Vengard content first."),
            reward = "5,000 XP for killing Rhobar in the base guide; obtain Rhobar's Scepter of Varant for Xardas's route.",
            warnings = "Killing Rhobar closes his Vengard quests. LOOT THE SCEPTER before departing; Xardas needs both royal symbols.",
            searchTags = listOf("Kill King Rhobar.", "Zuben / Beliar route", "Vengard", "ENDGAME CHOICE")
        ),
        Quest(
            id = "G3-P6-064",
            chapter = 6,
            playOrder = 64,
            title = "Kill Xardas.",
            category = "ENDGAME CHOICE",
            giver = "Beliar (after committing at his shrine)",
            location = "Nordmar",
            prerequisites = "Beliar endgame branch; speak to Beliar at the Bakaresh shrine.",
            summary = "If the chosen ending explicitly requires it, confront Xardas at his tower.",
            walkthroughSteps = listOf("Begin with Zuben / Beliar route. This quest is centered on Nordmar. Use city gates, oases, excavation camps and large ruin complexes as navigation anchors; southern Varant has long stretches where a wrong canyon can add a major detour.", "If the chosen ending explicitly requires it, confront Xardas at his tower.", "Return to the quest giver or named destination after the objective triggers and exhaust the follow-up dialogue. For multi-item quests, verify every required key/item is actually in your inventory before entering a temple or reporting completion.", "Do not do this during ordinary exploration; Xardas is central to another complete ending route."),
            reward = "5,000 XP from the Xardas assassination in the base guide.",
            warnings = "Killing Xardas forfeits his Unknown Lands escort route. Do not choose this path before completing any conversation with him that you need.",
            searchTags = listOf("Kill Xardas.", "Zuben / Beliar route", "Nordmar", "ENDGAME CHOICE")
        ),
        Quest(
            id = "G3-P6-065",
            chapter = 6,
            playOrder = 65,
            title = "Kill Zuben.",
            category = "ENDGAME CHOICE",
            giver = "Xardas/Innos-related ending route",
            location = "Ishtar",
            prerequisites = "Innos or Xardas ending, once you deliberately choose to oppose Zuben.",
            summary = "On endings that require Zuben's death, fight through or confront him after finishing every Ishtar quest you want.",
            walkthroughSteps = listOf("Begin with Xardas/Innos-related ending route. This quest is centered on Ishtar. Use city gates, oases, excavation camps and large ruin complexes as navigation anchors; southern Varant has long stretches where a wrong canyon can add a major detour.", "On endings that require Zuben's death, fight through or confront him after finishing every Ishtar quest you want.", "Return to the quest giver or named destination after the objective triggers and exhaust the follow-up dialogue. For multi-item quests, verify every required key/item is actually in your inventory before entering a temple or reporting completion.", "Loot Zuben and complete the relevant main-story follow-up afterward."),
            reward = "5,000 XP in the base guide and Staff of the Eternal Wanderer from Zuben; the staff is required for the Unknown Lands portal.",
            warnings = "Do not kill Zuben before finishing Ishtar quests/training if desired. Loot his STAFF; do not leave without the royal portal item.",
            searchTags = listOf("Kill Zuben.", "Xardas/Innos-related ending route", "Ishtar", "ENDGAME CHOICE")
        ),
        Quest(
            id = "G3-P6-066",
            chapter = 6,
            playOrder = 66,
            title = "Liberate Ishtar!",
            category = "DEFER — NOMAD / ENDGAME",
            giver = "Nomad / player action",
            location = "Ishtar",
            prerequisites = "",
            summary = "After exhausting Ishtar's trainers, arena, palace and story content, attack the Hashishin capital and defeat its defenders.",
            walkthroughSteps = listOf("Begin with Nomad / player action. This quest is centered on Ishtar. Use city gates, oases, excavation camps and large ruin complexes as navigation anchors; southern Varant has long stretches where a wrong canyon can add a major detour.", "After exhausting Ishtar's trainers, arena, palace and story content, attack the Hashishin capital and defeat its defenders.", "Return to the quest giver or named destination after the objective triggers and exhaust the follow-up dialogue. For multi-item quests, verify every required key/item is actually in your inventory before entering a temple or reporting completion.", "One of Varant's hardest city battles and a major faction commitment."),
            reward = "",
            warnings = "⚠ Faction / story warning: Make a permanent manual save before resolving this objective. It can remove major NPCs, close faction content, block trainers or commit the main story toward an ending.",
            searchTags = listOf("Liberate Ishtar!", "Nomad / player action", "Ishtar", "DEFER — NOMAD / ENDGAME")
        ),
    )
}
