package com.sliverzfx.gothicquest

internal object Gothic3Part7Data {
    val quests = listOf(
        Quest(
            id = "G3-P7-001",
            chapter = 7,
            playOrder = 1,
            title = "THE 12 FIRE CHALICES — COMPLETE CHECKLIST",
            category = "MAIN STORY / COMPLETIONIST GUIDE",
            giver = "Global guide / main story",
            location = "Whole game",
            prerequisites = "",
            summary = "The Fire Chalice quest spans all three regions. The safest completionist method is to collect all twelve before deciding whether to hand them to Grok for the Orc outcome or take the Fire Mage route and bless them in the sacred fire.",
            walkthroughSteps = listOf("1. Cape Dun — Urkrass — Gamal explains that Wenzel once owned the chalice. Urkrass has it among the captured paladin's belongings; obtain it through that quest/trade route before destroying Cape Dun.", "2. Montera — Bengerd — During “Change of shift in the slave camp,” send Bengerd to the farmyard and he gives you his Fire Chalice. If Montera has already been liberated, the chalice can still be taken from him after knocking him down.", "3. Pass to Varant — Kurt — Travel with Karlen and kill the renegade paladin Kurt. Loot Kurt's body; he carries a Fire Chalice.", "4. Trelis — Konrad — Speak with paladin Konrad in Trelis castle. He hands over the unblessed Fire Chalice during his dialogue; later he wants a Blessed Fire Chalice back.", "5. Geldern — town mine — Explore the mine inside Geldern all the way to the dark, previously unexplored section. A Fire Chalice lies beside a skeleton.", "6. Mora Sul — Masil — Complete Masil's chain beginning with Orknarok the temple slave and “Debt and debility.” The promissory-note outcome still leads to Masil rewarding the Fire Chalice.", "7. Northeast of Mora Sul — Cruz — Find paladin Cruz and Yussuf. Cruz's chalice was swallowed by an injured sandcrawler. Complete the sandcrawler hunt and recover the chalice from the creature.", "8. Nordmar Monastery — Milten — Speak with Milten at the Innos shrine. He gives you his Fire Chalice through dialogue.", "9. Vengard — Markus — After teleporting into besieged Vengard, Markus gives you a Fire Chalice and asks you to take it to Karrypto, head of the Fire Mages.", "10. Silden — Zapotek's house — The chalice is inside slave keeper Zapotek's house. Sneak in when you can take it without being witnessed.", "11. Nemora — Treslott — Build trust with Fire Mage Treslott and complete his herbaceous lobelia quest. He then gives you his Fire Chalice.", "12. Near Okara — Rakus — Rescue Rakus from the cave of undead and destroy the undead he summoned. Rakus rewards you with his Fire Chalice.", "Fire Mage / Paladin route: Take all twelve to the sacred-fire stage of the Fire Mage quest, turn them into Blessed Fire Chalices, and distribute blessed chalices to the paladins who ask for their magic back. Konrad and Karlen are two verified examples.", "Orc route: Grok in Geldern wants all twelve unblessed Fire Chalices and rewards the Orc-aligned hand-in. Treat this as an alternative resolution; make a permanent save before giving him the complete set."),
            reward = "",
            warnings = "",
            searchTags = listOf("THE 12 FIRE CHALICES — COMPLETE CHECKLIST", "Gothic 3", "main story", "completionist")
        ),
        Quest(
            id = "G3-P7-002",
            chapter = 7,
            playOrder = 2,
            title = "THE FIVE ARTIFACTS OF ADANOS",
            category = "MAIN STORY / COMPLETIONIST GUIDE",
            giver = "Global guide / main story",
            location = "Whole game",
            prerequisites = "",
            summary = "Xardas asks you to find five divine artifacts: the Amulet of Adanos, Crown of Adanos, Robe of Adanos and two Rings of Adanos. All three major ending routes revolve around what happens to these five items.",
            walkthroughSteps = listOf("Amulet of Adanos — Trelis: Vak gives the amulet when his 50,000-gold Hashishin debt quest is completed. Khabir/Charles dialogue points toward the artifact.", "Crown of Adanos — Temple of Mora Sul: Collect all five Mora Sul temple keys, open the temple and search the far end of the catacombs for the chest containing the Crown.", "Artifact from Al Shedim — Temple of Al Shedim: Complete the Al Shedim key/ruin chain, open the temple and recover its divine artifact.", "Remaining Ring / Robe artifacts — Main-story temple/artifact chain: Follow Xardas's global artifact quest and the associated ancient-temple quests until all five named artifacts are present in your inventory.", "Full set — Global: Before choosing a god or destroying the artifacts, create a permanent save with all five collected."),
            reward = "",
            warnings = "",
            searchTags = listOf("THE FIVE ARTIFACTS OF ADANOS", "Gothic 3", "main story", "completionist")
        ),
        Quest(
            id = "G3-P7-003",
            chapter = 7,
            playOrder = 3,
            title = "FIND XARDAS & REPORT HIS PLAN",
            category = "MAIN STORY / COMPLETIONIST GUIDE",
            giver = "Global guide / main story",
            location = "Whole game",
            prerequisites = "",
            summary = "A clean route is to reach the Wolf Clan in Nordmar, feed Graypelt and follow him to Xardas's tower. Speak with Xardas about the war and the Artifacts of Adanos. If you have already met King Rhobar, return to Rhobar afterward to complete the report about what Xardas is planning.",
            walkthroughSteps = listOf("Do not confuse finding Xardas with choosing Xardas's ending. His tower and artifact dialogue are part of the shared main story; the irreversible branch comes later."),
            reward = "",
            warnings = "",
            searchTags = listOf("FIND XARDAS & REPORT HIS PLAN", "Gothic 3", "main story", "completionist")
        ),
        Quest(
            id = "G3-P7-004",
            chapter = 7,
            playOrder = 4,
            title = "THE THREE ENDING ROUTES",
            category = "MAIN STORY / COMPLETIONIST GUIDE",
            giver = "Global guide / main story",
            location = "Whole game",
            prerequisites = "",
            summary = "A. Innos / King Rhobar route",
            walkthroughSteps = listOf("Collect all five Artifacts of Adanos and work with Rhobar. Rhobar provides the Scepter of Varant and directs the hero toward the Innos shrine in the Nordmar Monastery. Activating the shrine commits the artifacts to Innos and produces the Innos-aligned endgame tasks, including killing Zuben and liberating Myrtana.", "POINT OF NO RETURN: create a permanent save before using the five artifacts at the Innos shrine.", "B. Beliar / Zuben route", "Preserve enough Hashishin standing to access Ishtar and speak with Zuben. The Beliar route ultimately uses the Staff of the Eternal Wanderer and Beliar's shrine in Bakaresh. It sends the player against rival leaders and factions. Finish Ishtar, Water Mage, Rhobar and Xardas content before performing endgame assassinations.", "POINT OF NO RETURN: save before committing the divine artifacts to Beliar's path and before killing any major leader solely for the ending.", "C. Xardas / Adanos-independent route", "After collecting all five Artifacts of Adanos, choose Xardas's plan and travel to the Hammer Clan's ore furnace. Use the furnace to destroy the Amulet, Crown, Robe and both Rings. This is separate from the earlier quest to liberate the furnace from Orcs.", "After the artifacts are destroyed, the route requires the two royal symbols: Rhobar's Scepter of Varant and Zuben's Staff of the Eternal Wanderer. The necessary confrontations with Rhobar and Zuben must then be resolved. Return to Xardas and accompany him on the long journey toward the rock portal near the Geldern region. Expect enemies and an ambush near the destination. Once Xardas reaches the portal, use the portal to enter the Unknown Lands and end the game.", "POINT OF NO RETURN: save before destroying the five artifacts in the Hammer Clan furnace."),
            reward = "",
            warnings = "POINT OF NO RETURN: create a permanent manual save before committing to irreversible ending or faction decisions.",
            searchTags = listOf("THE THREE ENDING ROUTES", "Gothic 3", "main story", "completionist")
        ),
        Quest(
            id = "G3-P7-005",
            chapter = 7,
            playOrder = 5,
            title = "DRUID STONES — IMPORTANT GLOBAL COLLECTION",
            category = "MAIN STORY / COMPLETIONIST GUIDE",
            giver = "Global guide / main story",
            location = "Whole game",
            prerequisites = "",
            summary = "Transformation",
            walkthroughSteps = listOf("Ripperbeast — Porgan: Recover/recharge Porgan's stone; his follow-up requires 20 Stoneroots growing in marshy areas. He lets you keep the recharged stone.", "Wolf — Bogir, Wolf Clan: Prove yourself by killing the White Ripper near Xardas's tower. Bogir gives the Wolf Druid Stone.", "Shadowbeast — Runak: Complete Runak's anti-Orc-search-party quest line; killing Gunock, leader of the southern search party, is tied to receiving Runak's Shadowbeast stone.", "Snapper — Torn / Geldern route: Torn's Druid Stone is tied to mobilizing the people around Geldern and the Rebel/Druid liberation route."),
            reward = "",
            warnings = "",
            searchTags = listOf("DRUID STONES — IMPORTANT GLOBAL COLLECTION", "Gothic 3", "main story", "completionist")
        ),
        Quest(
            id = "G3-P7-006",
            chapter = 7,
            playOrder = 6,
            title = "TELEPORT STONES — COMPLETIONIST RULE",
            category = "MAIN STORY / COMPLETIONIST GUIDE",
            giver = "Global guide / main story",
            location = "Whole game",
            prerequisites = "",
            summary = "Pick up each settlement's teleport stone as soon as you safely reach the hub. Gothic 3's world is large and many quest chains require repeated returns. The most story-critical teleport is Vengard's: Roland's quest sends you to Gotha, where the Vengard teleport stone is found in the undead cave/mine route on the hill. Using it gets you inside the magical barrier and eventually to King Rhobar.",
            walkthroughSteps = listOf("For the app, every settlement page should eventually include a small “Teleport Stone” field with exact location, acquisition condition and whether theft is involved. This is more useful than placing all stones only in one giant list."),
            reward = "",
            warnings = "",
            searchTags = listOf("TELEPORT STONES — COMPLETIONIST RULE", "Gothic 3", "main story", "completionist")
        ),
        Quest(
            id = "G3-P7-007",
            chapter = 7,
            playOrder = 7,
            title = "FACTION & REPUTATION SAFETY RULES",
            category = "MAIN STORY / COMPLETIONIST GUIDE",
            giver = "Global guide / main story",
            location = "Whole game",
            prerequisites = "",
            summary = "System",
            walkthroughSteps = listOf("Orc towns in Myrtana — Do not liberate several Orc settlements early. Finish local Orc, mercenary, Rebel-spy, arena, slave and merchant quests before beginning the liberation chain.", "Rebel camps — Do not destroy Reddock, Okara or Nemora until all recruitment, mage, paladin and message quests are complete.", "Hashishin / Ishtar — Preserve Hashishin reputation if you want Ishtar access, its elite arena and advanced trainers. City liberation and Nomad support can undermine that plan.", "Nomads & Water Mages — Speak with every Water Mage and complete Al Shedim/ruin content before accepting assassination contracts against them.", "Nordmar clans — Complete clan quests and the six ancestor tombs; clear the five Orc camps and Hammer Clan furnace as the regional capstone.", "Major leaders — Rhobar, Zuben and Xardas are endgame-critical. Never kill one simply because a faction offers the objective unless you have completed the competing routes you care about."),
            reward = "",
            warnings = "",
            searchTags = listOf("FACTION & REPUTATION SAFETY RULES", "Gothic 3", "main story", "completionist")
        ),
        Quest(
            id = "G3-P7-008",
            chapter = 7,
            playOrder = 8,
            title = "MASTER WHOLE-GAME ROUTE",
            category = "MAIN STORY / COMPLETIONIST GUIDE",
            giver = "Global guide / main story",
            location = "Whole game",
            prerequisites = "",
            summary = "PART I — Ardea → Reddock → Cape Dun → Montera. Learn the faction system; postpone city liberation.",
            walkthroughSteps = listOf("PART II — Okara → Gotha → Trelis → Nemora. Recruit Okara, cleanse Gotha, preserve Vak's Adanos artifact route and collect Karlen/Kurt Fire Chalice content.", "PART III — Geldern → Silden → Vengard → Faring. Collect Geldern/Silden Fire Chalices, meet Rhobar, unlock the route into Nordmar.", "PART IV — Nordmar. Wolf Clan → Xardas → Hammer Clan → Fire Clan → Monastery → six ancestor tombs → five Orc camps → furnace liberation.", "PART V — Northern Varant. Braga → Ben Erai → Lago → Ben Sala. Preserve both Nomad and Hashishin content until neutral quests are exhausted.", "PART VI — Southern Varant. Mora Sul → Al Shedim → Bakaresh → Ishtar. Collect temple artifacts, meet Water Mages and Zuben, use Ishtar's trainers.", "PART VII — Finish all 12 Fire Chalices and all 5 Artifacts of Adanos. Create a permanent save. Choose Innos, Beliar or Xardas and follow only that ending's irreversible objectives."),
            reward = "",
            warnings = "",
            searchTags = listOf("MASTER WHOLE-GAME ROUTE", "Gothic 3", "main story", "completionist")
        ),
        Quest(
            id = "G3-P7-009",
            chapter = 7,
            playOrder = 9,
            title = "POINT-OF-NO-RETURN CHECKLIST",
            category = "MAIN STORY / COMPLETIONIST GUIDE",
            giver = "Global guide / main story",
            location = "Whole game",
            prerequisites = "",
            summary = "All desired town and Rebel-camp quests completed before liberation/destruction.",
            walkthroughSteps = listOf("All 12 Fire Chalices collected before choosing Grok versus sacred-fire resolution.", "All Water Mage and Nomad quests completed before any Hashishin purge.", "Ishtar entered; desired arena fights and advanced training completed.", "All five Artifacts of Adanos collected.", "Rhobar, Zuben and Xardas still alive unless your chosen route now requires otherwise.", "Permanent manual save created before Innos/Beliar artifact commitment or Xardas's furnace destruction.", "Unique quest items, royal symbols and temple keys not sold or discarded."),
            reward = "",
            warnings = "POINT OF NO RETURN: create a permanent manual save before committing to irreversible ending or faction decisions.",
            searchTags = listOf("POINT-OF-NO-RETURN CHECKLIST", "Gothic 3", "main story", "completionist")
        ),
        Quest(
            id = "G3-P7-010",
            chapter = 7,
            playOrder = 10,
            title = "QUEST DEPENDENCY MAPS FOR THE APP",
            category = "MAIN STORY / COMPLETIONIST GUIDE",
            giver = "Global guide / main story",
            location = "Whole game",
            prerequisites = "",
            summary = "Quest group",
            walkthroughSteps = listOf("Fire Chalices — Collect 12 → choose Grok OR sacred fire → if sacred fire: Blessed Chalices → return to eligible paladins → paladin/rebel follow-ups.", "Artifacts of Adanos — Find Xardas → collect five artifacts → permanent save → Innos shrine OR Beliar route OR destroy all five in Hammer Clan furnace.", "Xardas ending — Five artifacts → destroy in furnace → Scepter of Varant + Staff of Eternal Wanderer → resolve Rhobar + Zuben → return to Xardas → escort to portal → Unknown Lands.", "Nordmar liberation — Clan preparation → ancestor tombs → five Orc camps + free Hammer Clan furnace → report regional liberation.", "Mora Sul temple — Identify five key holders → finish holder quests → collect five keys → open temple → recover Crown of Adanos / other temple objectives."),
            reward = "",
            warnings = "",
            searchTags = listOf("QUEST DEPENDENCY MAPS FOR THE APP", "Gothic 3", "main story", "completionist")
        ),
    )
}
