package com.sliverzfx.gothicquest

internal object Gothic3Part7Data {
    val quests = listOf(
        Quest(
            id = "G3-P7-001",
            chapter = 7,
            playOrder = 1,
            title = "THE 12 FIRE CHALICES — COMPLETE CHECKLIST",
            category = "MAIN STORY / COMPLETIONIST GUIDE",
            giver = "Guide entry (not a separate quest giver); Sebastian in Reddock starts the Fire Chalices storyline",
            location = "Whole game",
            prerequisites = "Meet Fire Mage Sebastian in Reddock; the twelve chalices are obtained throughout Myrtana, Nordmar and Varant.",
            summary = "The Fire Chalice quest spans all three regions. The safest completionist method is to collect all twelve before deciding whether to hand them to Grok for the Orc outcome or take the Fire Mage route and bless them in the sacred fire.",
            walkthroughSteps = listOf("1. Cape Dun — Urkrass has the captured chalice from Wenzel. Buy it before hostile liberation; his initial asking price is 100 gold in the base guide.", "2. Montera — Bengerd, enslaved at the excavation, offers the chalice through his work-transfer dialogue. Resolve his quest before attacking the occupation.", "3. Varant pass — renegade paladin Kurt has the key to a chest holding a Fire Chalice. Defeat him with Karlen and check the chest, not just Kurt's corpse.", "4. Trelis — paladin Konrad hands over an unblessed Fire Chalice; return a blessed one later if you choose the Fire Mage route.", "5. Geldern — explore the dark back tunnels of the town mine. Search near a skeleton for a chalice.", "6. Mora Sul — complete merchant Masil's errands, including the Orknarok-related work, to earn his chalice.", "7. Northeast of Mora Sul — paladin Cruz leads you toward the injured sandcrawler that swallowed the missing chalice. Defeat it and loot the item.", "8. Nordmar Monastery — ask Milten for his chalice. He also explains how to bless the complete set.", "9. Vengard — paladin Markus gives you a chalice after you teleport into Vengard; he asks you to bring it to Karrypto.", "10. Silden — steal the chalice lying inside overseer Zapotek's house when nobody can see you.", "11. Nemora — complete Fire Mage Treslott's herbaceous lobelia assignment, then ask him for his chalice.", "12. Near Okara — free Rakus from the undead in his cave. After the undead-summoning trouble is resolved he gives you his chalice.", "Rebel/paladin path: after collecting twelve, take them to the sacred fire next to the Innos altar in Nordmar's Monastery, bless the chalices, collect the twelve blessed versions from the fire and distribute them to eligible paladins.", "Orc path: give Grok in Geldern the twelve unblessed chalices instead. Save beforehand because this forfeits the sacred-fire paladin restoration route."),
            reward = "Complete set of twelve Fire Chalices; quest rewards depend on Grok versus Milten's sacred-fire resolution. Blessing the set awards 12,000 XP in the base guide.",
            warnings = "IMPORTANT: do not hand the entire set to Grok if you plan to bless the chalices for the paladins. The two outcomes are mutually exclusive. The Varant pass chalice is found in Kurt's locked chest; do not rely on his body alone.",
            searchTags = listOf("THE 12 FIRE CHALICES — COMPLETE CHECKLIST", "Gothic 3", "main story", "completionist")
        ),
        Quest(
            id = "G3-P7-002",
            chapter = 7,
            playOrder = 2,
            title = "THE FIVE ARTIFACTS OF ADANOS",
            category = "MAIN STORY / COMPLETIONIST GUIDE",
            giver = "Guide entry — Xardas and main-story contacts",
            location = "Whole game",
            prerequisites = "Explore the five artifact quest with Xardas, Rhobar or Grok; collect all five BEFORE choosing an ending.",
            summary = "Locate the amulet, crown, robe, ring of life and ring of magic; these five artifacts determine how the three main endings proceed.",
            walkthroughSteps = listOf("Amulet of Adanos — Trelis: Vak possesses it. Obtain the amulet by paying his 50,000-gold tribute debt or through a later hostile faction choice.", "Crown of Adanos — Temple of Mora Sul: gather five temple keys from Kalesch, Kirk, Gonzales, Yussuf and Ilja. Unlock the temple and take the Crown from within.", "Robe of Adanos — Temple of Al Shedim: collect Saturas's and Lester's keys, plus three chest keys hidden among the ruins, then open the temple and recover the Robe.", "Ring of Adanos (Life) — Gotha: defeat the demon responsible for the undead curse and loot its ring.", "Ring of Adanos (Magic) — Nordmar: explore the ancient tomb of Akascha and take the ring from his undead body.", "Before you choose Innos, Beliar or Xardas, account for all five distinct items and save. Xardas's path destroys them; god-aligned paths commit them through their divine ritual."),
            reward = "Five divine artifacts: Amulet (Vak), Crown (Mora Sul), Robe (Al Shedim), Ring of Life (Gotha demon) and Ring of Magic (Akascha).",
            warnings = "The two Adanos rings are NOT both in desert temples. The Gotha demon carries the Life ring and undead Akascha in Nordmar has the Magic ring; Al Shedim holds the Robe, not a mystery sixth artifact.",
            searchTags = listOf("THE FIVE ARTIFACTS OF ADANOS", "Gothic 3", "main story", "completionist")
        ),
        Quest(
            id = "G3-P7-003",
            chapter = 7,
            playOrder = 3,
            title = "FIND XARDAS & REPORT HIS PLAN",
            category = "MAIN STORY / COMPLETIONIST GUIDE",
            giver = "Guide entry — Xardas's search and Rhobar's reporting quest",
            location = "Whole game",
            prerequisites = "Travel to Nordmar; if reporting to Rhobar, first reach King Rhobar in Vengard.",
            summary = "A clean route is to reach the Wolf Clan in Nordmar, feed Graypelt and follow him to Xardas's tower. Speak with Xardas about the war and the Artifacts of Adanos. If you have already met King Rhobar, return to Rhobar afterward to complete the report about what Xardas is planning.",
            walkthroughSteps = listOf("Reach the Wolf Clan in Nordmar and ask local hunters about Xardas and the route to his tower.", "Seek the hunter Hanson and his wolf Graypelt. Give Graypelt the requested meat, then follow him toward Xardas's tower; alternatively travel up the mountains independently.", "Speak with Xardas inside his tower and learn what he is trying to accomplish with the artifacts of Adanos.", "If King Rhobar asked you to investigate Xardas, return to Vengard using its teleport rune and report the magician's plan. This is not yet a commitment to Xardas's ending."),
            reward = "Finding Xardas awards 1,250 XP in the base guide; reporting his plan to Rhobar awards 2,500 XP.",
            warnings = "Merely finding Xardas does not select his ending. Avoid destroying or committing artifacts until after completing any Rhobar/Zuben quests you care about.",
            searchTags = listOf("FIND XARDAS & REPORT HIS PLAN", "Gothic 3", "main story", "completionist")
        ),
        Quest(
            id = "G3-P7-004",
            chapter = 7,
            playOrder = 4,
            title = "THE THREE ENDING ROUTES",
            category = "MAIN STORY / COMPLETIONIST GUIDE",
            giver = "Guide entry — choice of Innos, Beliar or Xardas",
            location = "Whole game",
            prerequisites = "Collect all five Artifacts of Adanos and preserve relevant major leaders until you have chosen an ending.",
            summary = "A. Innos / King Rhobar route",
            walkthroughSteps = listOf("Collect all five Artifacts of Adanos and work with Rhobar. Rhobar provides the Scepter of Varant and directs the hero toward the Innos shrine in the Nordmar Monastery. Activating the shrine commits the artifacts to Innos and produces the Innos-aligned endgame tasks, including killing Zuben and liberating Myrtana.", "POINT OF NO RETURN: create a permanent save before using the five artifacts at the Innos shrine.", "B. Beliar / Zuben route", "Preserve enough Hashishin standing to access Ishtar and speak with Zuben. The Beliar route ultimately uses the Staff of the Eternal Wanderer and Beliar's shrine in Bakaresh. It sends the player against rival leaders and factions. Finish Ishtar, Water Mage, Rhobar and Xardas content before performing endgame assassinations.", "POINT OF NO RETURN: save before committing the divine artifacts to Beliar's path and before killing any major leader solely for the ending.", "C. Xardas / Adanos-independent route", "After collecting all five Artifacts of Adanos, choose Xardas's plan and travel to the Hammer Clan's ore furnace. Use the furnace to destroy the Amulet, Crown, Robe and both Rings. This is separate from the earlier quest to liberate the furnace from Orcs.", "After the artifacts are destroyed, the route requires the two royal symbols: Rhobar's Scepter of Varant and Zuben's Staff of the Eternal Wanderer. The necessary confrontations with Rhobar and Zuben must then be resolved. Return to Xardas and accompany him on the long journey toward the rock portal near the Geldern region. Expect enemies and an ambush near the destination. Once Xardas reaches the portal, use the portal to enter the Unknown Lands and end the game.", "POINT OF NO RETURN: save before destroying the five artifacts in the Hammer Clan furnace."),
            reward = "Three mutually exclusive main endings. The Innos and Beliar rituals keep the chosen god's storyline; Xardas's furnace ritual destroys the artifacts and leads to the Unknown Lands.",
            warnings = "ENDGAME COMMITMENT: Do not activate a god's artifact shrine or destroy all five items at the Hammer Clan furnace until you are ready. Rhobar's scepter and Zuben's staff are BOTH needed for Xardas's portal.",
            searchTags = listOf("THE THREE ENDING ROUTES", "Gothic 3", "main story", "completionist")
        ),
        Quest(
            id = "G3-P7-005",
            chapter = 7,
            playOrder = 5,
            title = "DRUID STONES — IMPORTANT GLOBAL COLLECTION",
            category = "MAIN STORY / COMPLETIONIST GUIDE",
            giver = "Guide entry — Porgan, Bogir, Runak and Torn",
            location = "Whole game",
            prerequisites = "Druid stones have separate owners and quest conditions; complete their personal requests before attacking Druids or their allies.",
            summary = "Collect unique transformation stones from Myrtana and Nordmar druids; each has its own NPC and quest chain.",
            walkthroughSteps = listOf("Ripperbeast — Porgan: Recover/recharge Porgan's stone; his follow-up requires 20 Stoneroots growing in marshy areas. He lets you keep the recharged stone.", "Wolf — Bogir, Wolf Clan: Prove yourself by killing the White Ripper near Xardas's tower. Bogir gives the Wolf Druid Stone.", "Shadowbeast — Runak: Complete Runak's anti-Orc-search-party quest line; killing Gunock, leader of the southern search party, is tied to receiving Runak's Shadowbeast stone.", "Snapper — Torn / Geldern route: Torn's Druid Stone is tied to mobilizing the people around Geldern and the Rebel/Druid liberation route."),
            reward = "Transformation abilities associated with Porgan's Ripperbeast, Bogir's Wolf, Runak's Shadowbeast and Torn's Snapper stones.",
            warnings = "Some stones require druid NPCs to survive. Complete their quests before accepting Orc bounty missions targeting the druids.",
            searchTags = listOf("DRUID STONES — IMPORTANT GLOBAL COLLECTION", "Gothic 3", "main story", "completionist")
        ),
        Quest(
            id = "G3-P7-006",
            chapter = 7,
            playOrder = 6,
            title = "TELEPORT STONES — COMPLETIONIST RULE",
            category = "MAIN STORY / COMPLETIONIST GUIDE",
            giver = "Guide entry — exploration reward, not a journal quest",
            location = "Whole game",
            prerequisites = "No main-story gate; collect teleport stones while exploring settlements.",
            summary = "Pick up each settlement's teleport stone as soon as you safely reach the hub. Gothic 3's world is large and many quest chains require repeated returns. The most story-critical teleport is Vengard's: Roland's quest sends you to Gotha, where the Vengard teleport stone is found in the undead cave/mine route on the hill. Using it gets you inside the magical barrier and eventually to King Rhobar.",
            walkthroughSteps = listOf("When arriving at a settlement, seek its teleport stone before finishing a major combat or liberation quest; many are in guarded houses, inventories, ruins or nearby camps.", "Gotha: Roland in Okara sends you to search for the Vengard teleport stone. It lies on a crate at the end of Gotha's underground cave/tunnel, after clearing its undead.", "Use the Vengard teleporter to pass the city's magic barrier and reach the besieged interior, then fight toward King Rhobar.", "Store stones rather than discarding them. Recording each exact acquisition location in a town-specific guide is a future data improvement, not a separate in-game objective."),
            reward = "Fast travel to settlements and otherwise inaccessible Vengard. Teleport stones are utility items, not a journal reward.",
            warnings = "In particular, Vengard cannot be reached by simply walking through the barrier; the rune in Gotha's underground tunnels is crucial.",
            searchTags = listOf("TELEPORT STONES — COMPLETIONIST RULE", "Gothic 3", "main story", "completionist")
        ),
        Quest(
            id = "G3-P7-007",
            chapter = 7,
            playOrder = 7,
            title = "FACTION & REPUTATION SAFETY RULES",
            category = "MAIN STORY / COMPLETIONIST GUIDE",
            giver = "Guide entry — faction planning advice",
            location = "Whole game",
            prerequisites = "Applies throughout the game; some faction outcomes exclude others.",
            summary = "System",
            walkthroughSteps = listOf("Orc towns in Myrtana — Do not liberate several Orc settlements early. Finish local Orc, mercenary, Rebel-spy, arena, slave and merchant quests before beginning the liberation chain.", "Rebel camps — Do not destroy Reddock, Okara or Nemora until all recruitment, mage, paladin and message quests are complete.", "Hashishin / Ishtar — Preserve Hashishin reputation if you want Ishtar access, its elite arena and advanced trainers. City liberation and Nomad support can undermine that plan.", "Nomads & Water Mages — Speak with every Water Mage and complete Al Shedim/ruin content before accepting assassination contracts against them.", "Nordmar clans — Complete clan quests and the six ancestor tombs; clear the five Orc camps and Hammer Clan furnace as the regional capstone.", "Major leaders — Rhobar, Zuben and Xardas are endgame-critical. Never kill one simply because a faction offers the objective unless you have completed the competing routes you care about."),
            reward = "Retains access to towns, trainers, merchants, quests and mutually exclusive ending routes.",
            warnings = "Liberating multiple Orc towns, killing Water Mages or attacking Ishtar can permanently close faction options. Make a manual save before beginning a town uprising or major assassination.",
            searchTags = listOf("FACTION & REPUTATION SAFETY RULES", "Gothic 3", "main story", "completionist")
        ),
        Quest(
            id = "G3-P7-008",
            chapter = 7,
            playOrder = 8,
            title = "MASTER WHOLE-GAME ROUTE",
            category = "MAIN STORY / COMPLETIONIST GUIDE",
            giver = "Guide entry — suggested play order",
            location = "Whole game",
            prerequisites = "Optional recommended route; this is NOT a quest and does not have a required in-game order.",
            summary = "PART I — Ardea → Reddock → Cape Dun → Montera. Learn the faction system; postpone city liberation.",
            walkthroughSteps = listOf("PART II — Okara → Gotha → Trelis → Nemora. Recruit Okara, cleanse Gotha, preserve Vak's Adanos artifact route and collect Karlen/Kurt Fire Chalice content.", "PART III — Geldern → Silden → Vengard → Faring. Collect Geldern/Silden Fire Chalices, meet Rhobar, unlock the route into Nordmar.", "PART IV — Nordmar. Wolf Clan → Xardas → Hammer Clan → Fire Clan → Monastery → six ancestor tombs → five Orc camps → furnace liberation.", "PART V — Northern Varant. Braga → Ben Erai → Lago → Ben Sala. Preserve both Nomad and Hashishin content until neutral quests are exhausted.", "PART VI — Southern Varant. Mora Sul → Al Shedim → Bakaresh → Ishtar. Collect temple artifacts, meet Water Mages and Zuben, use Ishtar's trainers.", "PART VII — Finish all 12 Fire Chalices and all 5 Artifacts of Adanos. Create a permanent save. Choose Innos, Beliar or Xardas and follow only that ending's irreversible objectives."),
            reward = "Suggested neutral-first completionist path, preserving optional quests and the possibility of each final faction choice.",
            warnings = "Seven app sections group the guide geographically. Gothic 3 itself has no seven-chapter story progression; players may visit Myrtana, Nordmar and Varant in different orders.",
            searchTags = listOf("MASTER WHOLE-GAME ROUTE", "Gothic 3", "main story", "completionist")
        ),
        Quest(
            id = "G3-P7-009",
            chapter = 7,
            playOrder = 9,
            title = "POINT-OF-NO-RETURN CHECKLIST",
            category = "MAIN STORY / COMPLETIONIST GUIDE",
            giver = "Guide entry — point-of-no-return checklist",
            location = "Whole game",
            prerequisites = "Before major liberation, assassination, sacred-fire chalice hand-in or artifact commitment.",
            summary = "All desired town and Rebel-camp quests completed before liberation/destruction.",
            walkthroughSteps = listOf("All 12 Fire Chalices collected before choosing Grok versus sacred-fire resolution.", "All Water Mage and Nomad quests completed before any Hashishin purge.", "Ishtar entered; desired arena fights and advanced training completed.", "All five Artifacts of Adanos collected.", "Rhobar, Zuben and Xardas still alive unless your chosen route now requires otherwise.", "Permanent manual save created before Innos/Beliar artifact commitment or Xardas's furnace destruction.", "Unique quest items, royal symbols and temple keys not sold or discarded."),
            reward = "Preserves the ability to compare the Innos, Beliar and Xardas outcomes on separate save files.",
            warnings = "Back up a permanent save before irreversible quest turn-ins, large-scale liberation, killing Rhobar/Zuben/Xardas or destroying the five artifacts.",
            searchTags = listOf("POINT-OF-NO-RETURN CHECKLIST", "Gothic 3", "main story", "completionist")
        ),
        Quest(
            id = "G3-P7-010",
            chapter = 7,
            playOrder = 10,
            title = "QUEST DEPENDENCY MAPS FOR THE APP",
            category = "MAIN STORY / COMPLETIONIST GUIDE",
            giver = "Guide entry — cross-quest dependency overview",
            location = "Whole game",
            prerequisites = "Consult before Fire Chalice turn-in, temple openings, faction war quests and ending rituals.",
            summary = "Quest group",
            walkthroughSteps = listOf("Fire Chalices — Collect 12 → choose Grok OR sacred fire → if sacred fire: Blessed Chalices → return to eligible paladins → paladin/rebel follow-ups.", "Artifacts of Adanos — Find Xardas → collect five artifacts → permanent save → Innos shrine OR Beliar route OR destroy all five in Hammer Clan furnace.", "Xardas ending — Five artifacts → destroy in furnace → Scepter of Varant + Staff of Eternal Wanderer → resolve Rhobar + Zuben → return to Xardas → escort to portal → Unknown Lands.", "Nordmar liberation — Clan preparation → ancestor tombs → five Orc camps + free Hammer Clan furnace → report regional liberation.", "Mora Sul temple — Identify five key holders → finish holder quests → collect five keys → open temple → recover Crown of Adanos / other temple objectives."),
            reward = "Dependency overview for 12 Fire Chalices, 5 divine artifacts, Nordmar liberation, the desert temple keys and three endgame branches.",
            warnings = "The Gothic 3 sections are geographic clusters, not chronological chapters. Finishing one part does not unlock the next part as a mandatory questline.",
            searchTags = listOf("QUEST DEPENDENCY MAPS FOR THE APP", "Gothic 3", "main story", "completionist")
        ),
    )
}
