package com.sliverzfx.gothicquest
object Gothic2Chapter1Part3 {
    val quests = listOf(
        g2q("G2G-C01-055",41,"Replacement for Lares","Side Quest","Khorinis Harbor","Ring of Water","Route stage 3 — Night of the Raven investigation and the Thieves’ Guild","Find someone to cover Lares so he can escort you.","Receive Lares’s Aquamarine Ring and wear it while talking to the marketplace merchants.§Identify Baltram as the Ring contact and arrange for him to cover Lares’s duties, then return to Lares.","Required for some Lares escort options and the Water Mage path."),
        g2q("G2G-C01-042",42,"Joining the Thieves' Guild","Side Quest","Khorinis Sewers","Thieves’ Guild","Route stage 3 — Night of the Raven investigation and the Thieves’ Guild","Gain entry to the secret Thieves’ Guild.","Complete the harbor theft chain involving Rengaru, Nagur and Halvor without betraying everyone, then speak to Kardif and meet Attila for the sewer key.§Enter the sewers and meet Cassia.§Alternatively, betray the thieves and fight Attila for the key.","The peaceful route preserves more guild members and content."),
        g2q("G2G-C01-016",43,"Bosper's Bow","Side Quest","Khorinis","General","Route stage 3 — Night of the Raven investigation and the Thieves’ Guild","Recover Bosper’s stolen bow.","Ask Bosper/Regis about the missing bow.§Investigate the harbor and thieves connected to the burglary, recover the bow from the thieves’ stash, and return it to Bosper.","This quest ties into the chain that exposes the Thieves’ Guild."),
        g2q("G2G-C01-025",44,"Coragon's Silver","Side Quest","Khorinis","Thieves’ Guild / General","Route stage 3 — Night of the Raven investigation and the Thieves’ Guild","Recover the silver stolen from Coragon’s tavern.","Speak to Coragon about the robbery.§Follow the thieves’ trail into the harbor/sewers, recover his silver from the thieves’ loot, and return it to him.","Returning the silver earns Coragon’s special beer and helps establish the guild burglary chain."),
        g2q("G2G-C01-024",45,"Constantino's Ring","Side Quest","Khorinis","Thieves’ Guild","Route stage 3 — Night of the Raven investigation and the Thieves’ Guild","Steal Constantino’s ring as Cassia’s initiation test.","After reaching the Thieves’ Guild, accept Cassia’s test.§Enter Constantino’s house/shop when you can do so safely, open the correct chest and steal the ring.§Bring it to Cassia.","Joining the guild peacefully or violently changes how you reach this point, but the test itself is the same."),
        g2q("G2G-C01-065",46,"The Blood Chalices","Side Quest","Khorinis","Thieves’ Guild","Route stage 3 — Night of the Raven investigation and the Thieves’ Guild","Steal six valuable blood chalices from wealthy citizens.","After Cassia’s initiation, accept the heist.§Burgle the specified houses in the Upper/Lower Quarter, using lockpicking and keys as needed, collect all six chalices, and return to Cassia.","Best done at night. Save before entering occupied houses because witnesses can trigger fines/hostility."),
        g2q("G2G-C01-039",47,"Joe","Side Quest","Khorinis","Thieves’ Guild / General","Route stage 3 — Night of the Raven investigation and the Thieves’ Guild","Find the missing thief Joe.","Ask Hakon and guild contacts about Joe.§Obtain access to the locked guard tower near the city wall/barracks, open it and speak to Joe inside.","Joe is missing because he got trapped; he was not abducted by Raven’s slavers."),
        g2q("G2G-C01-032",48,"Farmer in Distress","Side Quest","Akil’s Farm","General","Route stage 4 — The countryside, farms and Onar’s mercenaries","Free Akil’s farm from armed extortion.","Learn that mercenaries/bandits are threatening Akil.§Travel to the farm, confront the two extortionists, defeat them, and speak with Akil and the affected workers.","Can be discovered through several city conversations."),
        g2q("G2G-C01-048",49,"Merchant Ambush","Side Quest","Road to Dead Harpy / Akil","General","Route stage 4 — The countryside, farms and Onar’s mercenaries","Help Erol recover stolen stone tablets/goods from bandits.","Meet Erol on the road.§Locate the nearby bandits who robbed him, defeat them, retrieve his tablets/goods, and return them.","Erol later becomes a useful merchant/trainer after his situation is resolved."),
        g2q("G2G-C01-030",50,"Empty the Mug in One Go","Side Quest","Dead Harpy Tavern","General","Route stage 4 — The countryside, farms and Onar’s mercenaries","Win Rukhar’s drinking contest.","Speak to Rukhar and arrange the contest with Randolph.§Manipulate the drink by replacing the gin with water before the match, then watch Randolph compete and settle the bet.","If you want the clean win, make the substitution without being caught."),
        g2q("G2G-C01-027",51,"Dragomir's Crossbow","Side Quest","Tavern countryside","General","Route stage 4 — The countryside, farms and Onar’s mercenaries","Find Dragomir’s lost crossbow.","Speak to Dragomir at his hunter camp.§Search the old stone-circle/forest area he indicates, retrieve the crossbow, and return it.","Useful early hunter quest while exploring the road network."),
        g2q("G2G-C01-056",52,"Respect of the Mercenaries","Side Quest","Onar’s Farm","Mercenaries","Route stage 4 — The countryside, farms and Onar’s mercenaries","Earn enough support among the mercenaries to be accepted.","Speak to Torlof and the key mercenaries.§Complete Torlof’s chosen test and side tasks for men such as Cord, Jarvis, Cipher and Rod until you have enough support.§Report to Torlof/Lee.","Several votes are optional; the app should later expose each voter as a dependency link."),
        g2q("G2G-C01-058",53,"Rod's Sword","Side Quest","Onar’s Farm","Mercenaries","Route stage 4 — The countryside, farms and Onar’s mercenaries","Prove Rod wrong about whether you can wield his sword.","Talk to Rod and accept his wager.§Meet the strength requirement and equip his sword when prompted, then return it and settle the bet.","Can contribute to mercenary respect."),
        g2q("G2G-C01-034",54,"For a Few Stalks of Weed","Side Quest","Onar’s Farm","Mercenaries","Route stage 4 — The countryside, farms and Onar’s mercenaries","Bring Cipher ten swampweed stalks for his vote.","Ask Cipher for his support.§Collect or buy ten swampweed stalks, give them to him, and confirm his vote.","Pairs naturally with the weed-package quests."),
        g2q("G2G-C01-093",55,"The Weed Package","Side Quest","Khorinis Harbor / Onar’s Farm","Mercenaries","Route stage 4 — The countryside, farms and Onar’s mercenaries","Recover Cipher’s missing swampweed package.","Ask Cipher about the package.§Investigate Bodo and the harbor warehouse; the same package is targeted by Lord Andre’s militia quest.§Obtain it and give it to Cipher.","If you also have A Package Full of Weed, tell Andre you disposed of it rather than handing it over if you want to keep it for Cipher."),
        g2q("G2G-C01-046",56,"Martial Arts","Side Quest","Onar’s Farm","Mercenaries","Route stage 4 — The countryside, farms and Onar’s mercenaries","Prove your fighting ability to Cord.","Ask Cord for his vote/support.§Meet his combat-skill requirement or accept the associated task he offers, then return to him.","Cord can also provide information useful to the missing-people investigation."),
        g2q("G2G-C01-073",57,"The Hungry Hunter","Side Quest","Valley of Khorinis","General","Route stage 4 — The countryside, farms and Onar’s mercenaries","Bring Grom food before asking for training.","Find Grom near Onar’s farm.§Give him the requested ham, milk and bread, then continue the conversation.","Opens access to some hunting training."),
        g2q("G2G-C01-035",58,"Four Wolves for Pepe","Side Quest","Onar’s Farm","Mercenaries / General","Route stage 4 — The countryside, farms and Onar’s mercenaries","Kill the wolves attacking Pepe’s sheep.","Speak to Pepe on the pasture.§Find the four young wolves in the nearby woods, kill them, then report back.","Leads to Beat Up Bullco."),
        g2q("G2G-C01-015",59,"Beat Up Bullco","Side Quest","Onar’s Farm","Mercenaries","Route stage 4 — The countryside, farms and Onar’s mercenaries","Teach Bullco a lesson for Pepe.","After Four Wolves for Pepe, ask Pepe what else is wrong.§Confront Bullco in the mercenary camp, beat him in a duel/fight, and report back to Pepe.","Do not kill him; a normal knockout is enough."),
        g2q("G2G-C01-043",60,"Kind Regards","Side Quest","Onar’s Farm","Mercenaries","Route stage 4 — The countryside, farms and Onar’s mercenaries","Beat three of Sylvio’s men to earn Jarvis’s vote.","Ask Jarvis for his support.§Defeat three mercenaries loyal to Sylvio in fair fights, then return to Jarvis.","Normal knockouts are sufficient; killing is unnecessary.")
    )
}