package com.sliverzfx.gothicquest
object Gothic2Chapter1Part4 {
    val quests = listOf(
        g2q("G2G-C01-060",61,"Stew","Side Quest","Onar’s Farm","General","Route stage 4 — The countryside, farms and Onar’s mercenaries","Earn Thekla’s special stew rewards.","Speak with Thekla after helping around the farm/mercenary camp.§Complete the linked favors and return to her at the relevant milestones to receive stew.","The quest journal can update several times as you earn additional servings."),
        g2q("G2G-C01-088",62,"The Sun Aloe","Side Quest","Black Troll area / Sagitta","General","Route stage 4 — The countryside, farms and Onar’s mercenaries","Bring Sagitta the rare Sun Aloe.","Ask Sagitta for training.§Find the Sun Aloe growing near the black troll, pick it, and deliver it to her.","Can be combined with The Snorting Creature."),
        g2q("G2G-C01-022",63,"Collect Rent","Side Quest","Onar’s Farm / Sekob’s Farm","Mercenaries","Route stage 4 — The countryside, farms and Onar’s mercenaries","Collect Onar’s rent from Sekob as Torlof’s test.","Take Torlof’s job, travel to Sekob’s farm, pressure Sekob until he pays, then return the money/report to Torlof.","One of two alternative Torlof tests for mercenary acceptance."),
        g2q("G2G-C01-028",64,"Drive Off the Militia","Side Quest","Onar’s Farm / Bengar’s Farm","Mercenaries","Route stage 4 — The countryside, farms and Onar’s mercenaries","Drive the militia away from Bengar’s farm as Torlof’s test.","Choose this task from Torlof.§Travel to Bengar’s farm when the militia detachment is present, defeat or force them to leave, then report to Torlof.","Alternative to Collect Rent; generally more dangerous but gives more combat experience."),
        g2q("G2G-C01-074",65,"The Lazy Farmer","Side Quest","Sekob’s Farm","General","Route stage 4 — The countryside, farms and Onar’s mercenaries","Make Bronko stop loafing and return to work.","Speak with Till about Bronko.§Confront Bronko, refuse his toll and beat/intimidate him until he agrees to work.§Report back to Till.","A normal knockout is enough."),
        g2q("G2G-C01-072",66,"The Forbidden Pasture","Side Quest","Sekob’s Farm / Bengar’s Farm","General","Route stage 4 — The countryside, farms and Onar’s mercenaries","Help Balthasar regain access to his old pasture.","Speak to Balthasar.§Talk with Bengar/Sekob and resolve the ownership dispute, using persuasion or later leverage, then return to Balthasar.","Often easiest after you have helped Bengar with other problems."),
        g2q("G2G-C01-087",67,"The Snorting Creature","Side Quest","Pass to Valley of Mines","General","Route stage 4 — The countryside, farms and Onar’s mercenaries","Kill the dangerous black troll Gaan calls the snorting creature.","Speak to Gaan near the pass.§Follow his directions to the black troll area, defeat the creature, then return to Gaan.","The troll can be handled early with careful movement; the same kill supports Raoul’s Black Fur quest later."),
        g2q("G2G-C01-067",68,"The Easy Way to the Militia","Side Quest","Khorinis","Ring of Water","Route stage 5 — Choose your main faction","Use Lares’s contacts to simplify joining the Militia.","Ask Lares for help with the Militia.§Speak with Martin in the harbor and follow his instructions, then take the resulting recommendation to Lord Andre.","An add-on shortcut that still leaves normal city content available."),
        g2q("G2G-C01-041",69,"Joining the Militia","Side Quest","Khorinis","Faction entry","Route stage 5 — Choose your main faction","Join Lord Andre’s militia.","Become a citizen of Khorinis, or use the alternative route involving the Thieves’ Guild.§Speak to Lord Andre in the barracks and accept the oath/assignment.","Locks you onto the Militia → Paladin route."),
        g2q("G2G-C01-100",70,"Where Is Peck","Side Quest","Khorinis","Militia","Route stage 5 — Choose your main faction","Find the absent militia soldier Peck.","Take Lord Andre’s order.§Search the harbor entertainment district/Red Lantern, find Peck and tell him to return to duty.§Report to Andre.","How harshly you report Peck can change the reward."),
        g2q("G2G-C01-003",71,"A Package Full of Weed","Side Quest","Khorinis","Militia","Route stage 5 — Choose your main faction","Find the swampweed package Lord Andre wants confiscated.","After joining the Militia, ask Lord Andre for work.§Follow leads through Mortis and Kardif to the harbor warehouse near Garvell.§Defeat the warehouse guard, take his key, open the chest and recover the package.§Return to Andre.","You can claim you threw the package into the harbor and keep it for Cipher’s related quest, or surrender it to Andre."),
        g2q("G2G-C01-094",72,"The Weed Trade","Side Quest","Khorinis Harbor","Militia","Route stage 5 — Choose your main faction","Identify the people selling swampweed in the harbor.","Take Lord Andre’s assignment.§Question harbor residents and dealers, trace the supply through the Red Lantern/tavern contacts, gather proof, then report the operation to Andre.","Militia-only investigation."),
        g2q("G2G-C01-096",73,"Trouble at Lobart's Farm","Side Quest","Khorinis / Lobart’s Farm","Militia","Route stage 5 — Choose your main faction","Help Lobart with the problem Lord Andre assigns.","After joining the Militia, take Andre’s farm-support job.§Go to Lobart, deal with the immediate threat/problem around the farm, then report back to both Lobart and Andre.","Militia reputation task."),
        g2q("G2G-C01-066",74,"The Easy Way to the Mercenaries","Side Quest","Khorinis / Onar’s Farm","Ring of Water","Route stage 5 — Choose your main faction","Use Lares’s contacts to simplify joining the mercenaries.","Ask Lares for help choosing the mercenary path.§Follow his referral to Cord/Onar’s farm, complete the shortened entry task, and report as directed.","Designed as an alternate faction-entry route in Night of the Raven."),
        g2q("G2G-C01-040",75,"Joining the Mercenaries","Side Quest","Onar’s Farm","Faction entry","Route stage 5 — Choose your main faction","Become one of Lee’s mercenaries.","Reach Onar’s farm and speak with Lee/Torlof.§Complete Respect of the Mercenaries, earn enough votes or satisfy the required tests, then return to Lee and formally join.","Locks you onto the mercenary → Dragon Hunter route."),
        g2q("G2G-C01-083",76,"The Peace Offer","Side Quest","Onar’s Farm / Khorinis","Mercenaries","Route stage 5 — Choose your main faction","Deliver Lee’s peace proposal to the Paladins.","After joining the mercenaries, take Lee’s letter/proposal.§Gain access to Lord Hagen and deliver it, then report the response back to Lee.","Faction-specific political side quest."),
        g2q("G2G-C01-068",77,"The Easy Way to the Monastery","Side Quest","Khorinis / Monastery","Ring of Water","Route stage 5 — Choose your main faction","Use Vatras/Lares to enter the monastery without the normal full offering.","Ask Lares about the monastery route, then speak to Vatras and follow the special statue/tribute chain.§Bring the valuable Innos statue to Pedro/Gorax as instructed.","Night of the Raven alternative to paying 1,000 gold plus a sheep."),
        g2q("G2G-C01-008",78,"Access to the Innos Monastery","Side Quest","Monastery of Fire","Faction entry","Route stage 5 — Choose your main faction","Gain admission to the Monastery of Fire as a novice.","Speak to Pedro at the monastery gate.§Normally bring a sheep and 1,000 gold; the Night of the Raven shortcut can use the valuable Innos statue obtained through the Water Mage/Lares route.§Hand over the required offering and enter.","This choice commits you to the novice/mage progression once you formally join."),
        g2q("G2G-C01-101",79,"Work for the Community","Side Quest","Monastery of Fire","Novice / Mage","Route stage 6 — Monastery branch: novice and Fire Mage progression","Complete enough chores for the Fire Mages to earn library access.","Speak to Parlan and take monastery assignments.§Complete the required set of novice chores for the mages, then return to Parlan for the library key.","Gateway to the Trial of Fire."),
        g2q("G2G-C01-081",80,"The Novice Chambers","Side Quest","Monastery of Fire","Novice / Mage","Route stage 6 — Monastery branch: novice and Fire Mage progression","Organize novices to clean the sleeping quarters.","Take Parlan’s chore.§Recruit the required novices, resolve any excuses/favors they demand, then tell Parlan the work is arranged.","Part of Work for the Community.")
    )
}