package com.sliverzfx.gothicquest

internal object Gothic3Part4Data {
    val quests = listOf(
        Quest(
            id = "G3-P4-001",
            chapter = 4,
            playOrder = 1,
            title = "The fat bastard is dead!",
            category = "SAFE",
            giver = "Automatic on killing Ugluz Potbelly",
            location = "Nordmar",
            prerequisites = "Locate the named ogre Ugluz Potbelly in Nordmar.",
            summary = "Kill Ugluz Potbelly, the wandering named ogre found around the Hammer Clan mine/hunting region.",
            walkthroughSteps = listOf("Explore the lower Hammer Clan mine approaches and Jensgar's hunting areas for named ogre Ugluz Potbelly.", "The ogre can wander between separate locations; he is not a stationary generic target.", "Defeat Ugluz to complete the automatic kill quest; there is no quest giver to return to."),
            reward = "5,000 XP for Ugluz Potbelly.",
            warnings = "Automatic completion; the target is Ugluz Potbelly, not a generic ogre.",
            searchTags = listOf("The fat bastard is dead!", "Automatic / related kill", "Nordmar", "SAFE")
        ),
        Quest(
            id = "G3-P4-002",
            chapter = 4,
            playOrder = 2,
            title = "Meat for Graypelt.",
            category = "SAFE",
            giver = "Hanson's wolf Graypelt",
            location = "Wolf Clan / wilderness",
            prerequisites = "Find Hanson near Wolf Clan and speak with him about Xardas.",
            summary = "Give Graypelt the meat he requests so the wolf will cooperate with you.",
            walkthroughSteps = listOf("Speak to hunter Hanson near his cabin and ask about Graypelt and Xardas.", "Give his wolf Graypelt ONE RAW MEAT.", "Talk to Graypelt or wait until his escort behavior begins; then follow him to Xardas's tower."),
            reward = "1,000 XP; unlocks Graypelt's guided route to Xardas.",
            warnings = "Use raw meat, not cooked meat. Feeding Graypelt triggers the separate escort objective.",
            searchTags = listOf("Meat for Graypelt.", "Graypelt", "Wolf Clan / wilderness", "SAFE")
        ),
        Quest(
            id = "G3-P4-003",
            chapter = 4,
            playOrder = 3,
            title = "Follow Graypelt to Xardas' tower.",
            category = "SAFE / MAIN-STORY SUPPORT",
            giver = "Graypelt, Hanson's wolf",
            location = "Wolf Clan Xardas' → tower",
            prerequisites = "Give Hanson's wolf Graypelt a piece of raw meat.",
            summary = "After feeding Graypelt, follow the wolf through Nordmar's wilderness. Stay close and protect him from hostile creatures until he reaches Xardas's tower.",
            walkthroughSteps = listOf("Meet hunter Hanson and his wolf Graypelt in Nordmar.", "Give the wolf raw meat and follow him along the mountain paths to Xardas's tower.", "Enter the tower to meet Xardas and continue the main artifact quest."),
            reward = "1,000 XP, +3 Wolf Clan reputation and +1 Hunting skill.",
            warnings = "",
            searchTags = listOf("Follow Graypelt to Xardas' tower.", "Graypelt", "Wolf Clan Xardas' → tower", "SAFE / MAIN-STORY SUPPORT")
        ),
        Quest(
            id = "G3-P4-004",
            chapter = 4,
            playOrder = 4,
            title = "Goblin attack!",
            category = "SAFE",
            giver = "Automatic goblin kill objective",
            location = "Wolf Clan outskirts",
            prerequisites = "Explore around the Wolf Clan and encounter goblin groups.",
            summary = "Kill the goblins attacking or threatening the clan and return after the complete target group is dead.",
            walkthroughSteps = listOf("Search the Wolf Clan's surrounding trails and caves for hostile goblins.", "Defeat fifteen goblins in total to trigger completion.", "No named NPC turn-in is necessary for the automatic objective."),
            reward = "1,500 XP, +2 Nordmar reputation and +3 Wolf Clan reputation.",
            warnings = "",
            searchTags = listOf("Goblin attack!", "Wolf Clan quest giver", "Wolf Clan outskirts", "SAFE")
        ),
        Quest(
            id = "G3-P4-005",
            chapter = 4,
            playOrder = 5,
            title = "Bag the deer on the plateau!",
            category = "SAFE",
            giver = "Hanson",
            location = "Plateau near Wolf Clan",
            prerequisites = "Speak with Hanson at his hunting cabin.",
            summary = "Travel to the plateau indicated by the hunter and kill the designated deer. Collect useful trophies and report back.",
            walkthroughSteps = listOf("Ask Hanson about the deer on the plateau above his hut.", "Hunt ELEVEN deer on the nearby plateau, using ranged attacks to avoid scattering them.", "Return to Hanson after the last deer is dead."),
            reward = "",
            warnings = "Eleven deer; they can flee and scatter.",
            searchTags = listOf("Bag the deer on the plateau!", "Wolf Clan hunter", "Plateau near Wolf Clan", "SAFE")
        ),
        Quest(
            id = "G3-P4-006",
            chapter = 4,
            playOrder = 6,
            title = "Take the ice wolf skins to the Wolf Clan.",
            category = "SAFE",
            giver = "Hanson",
            location = "Nordmar wilderness → Wolf Clan",
            prerequisites = "Meet Hanson near Wolf Clan and accept his ice-wolf skin delivery.",
            summary = "Collect the required Ice Wolf skins and deliver them to the clan.",
            walkthroughSteps = listOf("Talk to Hanson at his hunting cabin.", "He hands you TWENTY ICE WOLF SKINS for quartermaster Rune.", "Carry the twenty skins to Rune at Wolf Clan, then report completion."),
            reward = "1,500 XP, +2 Nordmar reputation and +5 Wolf Clan reputation.",
            warnings = "You are DELIVERING 20 skins provided by Hanson; you do not need to kill twenty ice wolves for this task.",
            searchTags = listOf("Take the ice wolf skins to the Wolf Clan.", "Wolf Clan hunter", "Nordmar wilderness → Wolf Clan", "SAFE")
        ),
        Quest(
            id = "G3-P4-007",
            chapter = 4,
            playOrder = 7,
            title = "Garik needs booze.",
            category = "SAFE",
            giver = "Garik (Wolf Clan guard)",
            location = "Wolf Clan",
            prerequisites = "Talk to Garik at Wolf Clan.",
            summary = "Bring Garik the requested booze and speak with him again.",
            walkthroughSteps = listOf("Ask Wolf Clan guard Garik whether he needs supplies.", "Give him a single bottle of BOOZE from inventory.", "Finish his dialogue."),
            reward = "1,000 XP and +2 Wolf Clan reputation.",
            warnings = "",
            searchTags = listOf("Garik needs booze.", "Garik", "Wolf Clan", "SAFE")
        ),
        Quest(
            id = "G3-P4-008",
            chapter = 4,
            playOrder = 8,
            title = "Take Ronar to his hunting cabin.",
            category = "SAFE / ESCORT",
            giver = "Ronar",
            location = "Wolf Clan hunting → cabin",
            prerequisites = "Speak to Ronar in the center of Wolf Clan.",
            summary = "Escort Ronar from the clan to his hunting cabin. Stay close and kill wildlife before it overwhelms him.",
            walkthroughSteps = listOf("Find Ronar near the center of the Wolf Clan settlement and offer to guide him to his hunting cabin.", "Follow him across the snowbound tracks, killing creatures that threaten him.", "Stay close until he reaches the hunting hut and the escort completes."),
            reward = "1,500 XP and +5 Wolf Clan reputation.",
            warnings = "KNOWN PATHFINDING FAILURE: Ronar can vanish into the brush mid-escort and later reappear in Wolf Clan without a completion dialogue. Make a separate save first.",
            searchTags = listOf("Take Ronar to his hunting cabin.", "Ronar", "Wolf Clan hunting → cabin", "SAFE / ESCORT")
        ),
        Quest(
            id = "G3-P4-009",
            chapter = 4,
            playOrder = 9,
            title = "Ham for the woodcutters.",
            category = "SAFE",
            giver = "Corwin (woodcutters)",
            location = "Woodcutters' camp",
            prerequisites = "Meet Corwin at Wolf Clan's woodcutter camp.",
            summary = "Bring the requested ham/food supply to the woodcutters and complete the delivery dialogue.",
            walkthroughSteps = listOf("Talk to Corwin about the woodcutters' hunger.", "Visit quartermaster Rune in Wolf Clan and obtain ham from his stores.", "Bring five hams back, one for each woodcutter, and finish Corwin's dialogue."),
            reward = "1,500 XP, +1 Nordmar reputation and +5 Wolf Clan reputation.",
            warnings = "",
            searchTags = listOf("Ham for the woodcutters.", "Wolf Clan / woodcutters", "Woodcutters' camp", "SAFE")
        ),
        Quest(
            id = "G3-P4-010",
            chapter = 4,
            playOrder = 10,
            title = "Kill the sabertooths outside the woodcutters' camp!",
            category = "SAFE",
            giver = "Corwin (woodcutters)",
            location = "Woodcutters' camp",
            prerequisites = "Speak to Corwin near Wolf Clan.",
            summary = "Kill all sabertooths threatening the woodcutters outside their camp and report back.",
            walkthroughSteps = listOf("Ask Corwin about the sabertooth predators near the woodcutters.", "Find and kill the TWO sabertooths near the encampment.", "Report to Corwin."),
            reward = "1,500 XP and +5 Wolf Clan reputation.",
            warnings = "",
            searchTags = listOf("Kill the sabertooths outside the woodcutters' camp!", "Woodcutters", "Woodcutters' camp", "SAFE")
        ),
        Quest(
            id = "G3-P4-011",
            chapter = 4,
            playOrder = 11,
            title = "Duel with Hogar.",
            category = "SAFE — DUEL",
            giver = "Hogar (Wolf Clan warrior)",
            location = "Wolf Clan",
            prerequisites = "Speak to Hogar in Wolf Clan.",
            summary = "Challenge Hogar and defeat him under normal non-lethal duel rules. Wait for him to stand and speak again.",
            walkthroughSteps = listOf("Ask Hogar to challenge you to a friendly duel.", "Defeat him without killing him or drawing the town into combat.", "Talk afterward and ask if he will help clear the Orc-held bridge."),
            reward = "1,500 XP, +3 Nordmar reputation, +5 Wolf Clan reputation and +1 Strength.",
            warnings = "NONLETHAL: Hogar must remain alive for the bridge escort.",
            searchTags = listOf("Duel with Hogar.", "Hogar", "Wolf Clan", "SAFE — DUEL")
        ),
        Quest(
            id = "G3-P4-012",
            chapter = 4,
            playOrder = 12,
            title = "Free the bridge in the south.",
            category = "SAFE",
            giver = "Grim (Wolf Clan leader)",
            location = "Southern bridge",
            prerequisites = "Ask Grim about Orcs at the bridge; recruit Hogar.",
            summary = "Travel to the southern bridge and eliminate the Orc force blocking it.",
            walkthroughSteps = listOf("Grim wants the Orcs removed from the bridge.", "Take Hogar with you and follow his route to the Orc camp.", "Defeat the Orcs, particularly the shaman, then return to Grim."),
            reward = "2,000 XP, +3 Nordmar reputation and +10 Wolf Clan reputation.",
            warnings = "Take Hogar to the bridge, rather than heading to a different Orc camp.",
            searchTags = listOf("Free the bridge in the south.", "Hogar / Wolf Clan", "Southern bridge", "SAFE")
        ),
        Quest(
            id = "G3-P4-013",
            chapter = 4,
            playOrder = 13,
            title = "Go to the southern bridge with Hogar.",
            category = "SAFE / ESCORT",
            giver = "Grim / Hogar",
            location = "Wolf Clan southern → bridge",
            prerequisites = "Ask Wolf Clan leader Grim about freeing the bridge and recruit Hogar.",
            summary = "Ask Hogar to accompany you and follow him to the southern bridge. Protect him on the route and during the Orc fight.",
            walkthroughSteps = listOf("After accepting Grim's Orc-bridge task, find Hogar at Wolf Clan.", "Ask Hogar to show you the occupied bridge and follow his route.", "When he reaches the Orc camp, help him defeat the defenders, especially the shaman.", "Report the completed escort and bridge victory through Grim's quest."),
            reward = "1,000 XP for Hogar's escort; clearing the bridge is a separate reward.",
            warnings = "Follow Hogar; different guides describe the relevant Wolf Clan bridge as northern/southern.",
            searchTags = listOf("Go to the southern bridge with Hogar.", "Hogar", "Wolf Clan southern → bridge", "SAFE / ESCORT")
        ),
        Quest(
            id = "G3-P4-014",
            chapter = 4,
            playOrder = 14,
            title = "The druid stone of the wolf.",
            category = "SAFE / DRUID",
            giver = "Bogir",
            location = "Wolf Clan",
            prerequisites = "Talk to Bogir at the Wolf Clan and accept the legendary wolf hunt.",
            summary = "Speak with Bogir and follow his quest chain involving the Wolf Druid Stone.",
            walkthroughSteps = listOf("Speak with Bogir about inheriting his Wolf Druid Stone.", "Travel toward the Hammer Clan hunting area and find the legendary White Ripper.", "Kill White Ripper, then return to Bogir; no trophy turn-in is needed."),
            reward = "Wolf Druid Stone, 2,500 XP, +15 Rangers and +15 Wolf Clan reputation.",
            warnings = "Killing normal ice wolves does not count; keep Bogir alive for the reward.",
            searchTags = listOf("The druid stone of the wolf.", "Bogir", "Wolf Clan", "SAFE / DRUID")
        ),
        Quest(
            id = "G3-P4-015",
            chapter = 4,
            playOrder = 15,
            title = "Kill the White Ripper!",
            category = "SAFE",
            giver = "Bogir (Wolf Clan)",
            location = "Nordmar wilderness",
            prerequisites = "Accept Bogir's White Ripper hunt at Wolf Clan.",
            summary = "Track down the unique White Ripper requested by Bogir and kill it. Return to Bogir after the hunt.",
            walkthroughSteps = listOf("Ask Bogir about the legendary White Ripper wolf.", "Travel toward the Hammer Clan hunting territory and look for the uniquely named White Ripper.", "Kill White Ripper, then return to Bogir; no fur or tooth is required."),
            reward = "2,500 XP and +10 Wolf Clan reputation; advances the Wolf Druid Stone quest.",
            warnings = "",
            searchTags = listOf("Kill the White Ripper!", "Bogir", "Nordmar wilderness", "SAFE")
        ),
        Quest(
            id = "G3-P4-016",
            chapter = 4,
            playOrder = 16,
            title = "Hunt the white shadowbeast!",
            category = "SAFE",
            giver = "Automatic or unconfirmed regional kill trigger",
            location = "Nordmar wilderness",
            prerequisites = "Possible world encounter with a unique white shadowbeast; existence in some base-game versions is not corroborated.",
            summary = "An uncertain ghost quest concerning a unique white shadowbeast. The cited classic guide could not confirm encountering this creature.",
            walkthroughSteps = listOf("This entry appears in older Gothic 3 quest lists, but the classic guide explicitly reports uncertainty whether the white shadowbeast even appears.", "Do not assume the creature exists in your version; only investigate if your journal records a white-shadowbeast kill or a named encounter.", "If the enemy appears, defeat it and confirm the completion notification; otherwise leave the guide entry uncompleted rather than hunting ordinary white wolves."),
            reward = "A historical quest list attributes 3,750 XP and +1 Hunting, but this is NOT verified as attainable in current builds.",
            warnings = "UNVERIFIED GHOST QUEST: do not spend hours hunting a possibly absent spawn. The base guide itself says it never found the target; version or patch differences may apply.",
            searchTags = listOf("Hunt the white shadowbeast!", "Wolf Clan hunter", "Nordmar wilderness", "SAFE")
        ),
        Quest(
            id = "G3-P4-017",
            chapter = 4,
            playOrder = 17,
            title = "Eliminate the war drummer of the orcs!",
            category = "SAFE — NORDMAR LIBERATION",
            giver = "Jensgar and Lisk (Wolf Clan hunters)",
            location = "Pass / Orc camp",
            prerequisites = "Meet Jensgar and Lisk at their hunting camp near Wolf Clan.",
            summary = "Find the Orc unit with the war drummer on the pass and destroy the group, including the drummer.",
            walkthroughSteps = listOf("Ask Jensgar or Lisk about an Orc war party near the hunters' camp.", "Find the Orc battle camp in the surrounding snowy woodland.", "Kill its defenders and especially the ORC WAR DRUMMER; his death completes the quest's kill target.", "Return to the hunting camp to report."),
            reward = "2,000 XP and +7 Wolf Clan reputation.",
            warnings = "The war drummer is a key completion target; this fight is distinct from Kerth's five Orc camps.",
            searchTags = listOf("Eliminate the war drummer of the orcs!", "Jensgar", "Pass / Orc camp", "SAFE — NORDMAR LIBERATION")
        ),
        Quest(
            id = "G3-P4-018",
            chapter = 4,
            playOrder = 18,
            title = "Pelts for Jensgar.",
            category = "SAFE",
            giver = "Jensgar",
            location = "Wolf Clan",
            prerequisites = "Meet hunter Jensgar in Nordmar.",
            summary = "Collect the animal pelts Jensgar requests and bring the full amount to him.",
            walkthroughSteps = listOf("Ask Jensgar for his pelt requisition.", "Hunt ice wolves and bison, obtaining 30 ice-wolf pelts and 10 bison skins.", "Return all requested skins to Jensgar."),
            reward = "1,500 XP, +5 Wolf Clan reputation and +1 Hunting skill.",
            warnings = "",
            searchTags = listOf("Pelts for Jensgar.", "Jensgar", "Wolf Clan", "SAFE")
        ),
        Quest(
            id = "G3-P4-019",
            chapter = 4,
            playOrder = 19,
            title = "Jorn needs exploding arrows.",
            category = "SAFE",
            giver = "Jorn",
            location = "Wolf Clan",
            prerequisites = "Speak with Jorn near Jensgar's hunting camp.",
            summary = "Bring Jorn twelve exploding arrows. They can be obtained from merchants including Vibald near the Hammer Clan region.",
            walkthroughSteps = listOf("Jorn asks for special ammunition.", "Collect 15 exploding arrows; alchemist Vibald near Wolf Clan can help acquire them.", "Deliver all 15 to Jorn."),
            reward = "1,500 XP and +5 Wolf Clan reputation.",
            warnings = "",
            searchTags = listOf("Jorn needs exploding arrows.", "Jorn", "Wolf Clan", "SAFE")
        ),
        Quest(
            id = "G3-P4-020",
            chapter = 4,
            playOrder = 20,
            title = "Looking for ore with Larson.",
            category = "SAFE / ESCORT",
            giver = "Larson",
            location = "Wolf Clan / wilderness",
            prerequisites = "Meet ore prospector Larson near Wolf Clan.",
            summary = "Accompany Larson on his prospecting trip and help him reach the ore location safely.",
            walkthroughSteps = listOf("Speak to Larson about searching the mountains for an ore vein.", "Agree to accompany him and stay close through winding cliffs and snow trails.", "Protect Larson from wildlife until he locates a suitable deposit.", "Speak with Larson to register the successful search."),
            reward = "2,000 XP, +3 Nordmar reputation, +10 Wolf Clan reputation and +1 Smithing.",
            warnings = "",
            searchTags = listOf("Looking for ore with Larson.", "Larson", "Wolf Clan / wilderness", "SAFE / ESCORT")
        ),
        Quest(
            id = "G3-P4-021",
            chapter = 4,
            playOrder = 21,
            title = "Supplies for Pedar.",
            category = "SAFE",
            giver = "Pedar (isolated former smith)",
            location = "Hammer Clan region",
            prerequisites = "Find Pedar on his hill in Nordmar; Rathgar can lead you there.",
            summary = "Bring Pedar the supplies he requests and finish his delivery dialogue.",
            walkthroughSteps = listOf("Find Pedar's isolated hilltop workshop; Rathgar can help you locate it.", "Pedar asks for 20 ice-wolf skins and 10 pieces of ore.", "Gather the materials from local hunting and mines, then deliver the full amounts."),
            reward = "1,500 XP and +3 Hammer Clan reputation.",
            warnings = "This is Pedar's FIRST task; complete it to unlock his later shadowbeast-horn request.",
            searchTags = listOf("Supplies for Pedar.", "Pedar", "Hammer Clan region", "SAFE")
        ),
        Quest(
            id = "G3-P4-022",
            chapter = 4,
            playOrder = 22,
            title = "Hauke needs ore.",
            category = "SAFE",
            giver = "Hauke (Hammer Clan prospector)",
            location = "Hammer Clan",
            prerequisites = "Ask Hauke how much ore he needs in Hammer Clan.",
            summary = "Bring Hauke ten ore nuggets/pieces as requested.",
            walkthroughSteps = listOf("Talk to prospector Hauke about his ore requirements.", "Bring him TEN ore pieces from nearby Nordmar deposits or your inventory.", "Deliver all ten pieces to Hauke."),
            reward = "2,000 XP, +5 Hammer Clan reputation and +1 Smithing.",
            warnings = "",
            searchTags = listOf("Hauke needs ore.", "Hauke", "Hammer Clan", "SAFE")
        ),
        Quest(
            id = "G3-P4-023",
            chapter = 4,
            playOrder = 23,
            title = "Go to the prospectors' camp with Hauke.",
            category = "SAFE / ESCORT",
            giver = "Hauke",
            location = "Hammer Clan → prospectors' camp",
            prerequisites = "Ask Hauke about his missing friends at the Hammer Clan prospectors' cave.",
            summary = "Follow Hauke to the prospectors' camp and keep him alive along the route.",
            walkthroughSteps = listOf("Hauke wants to check on miners working at a nearby prospector camp.", "Ask him to lead you and follow the route to their cave.", "Protect Hauke from beasts during the journey and speak again when the camp is reached."),
            reward = "1,500 XP and +5 Hammer Clan reputation.",
            warnings = "",
            searchTags = listOf("Go to the prospectors' camp with Hauke.", "Hauke", "Hammer Clan → prospectors' camp", "SAFE / ESCORT")
        ),
        Quest(
            id = "G3-P4-024",
            chapter = 4,
            playOrder = 24,
            title = "Kill the minecrawler in the prospectors' camp.",
            category = "SAFE",
            giver = "Hauke",
            location = "Prospectors' camp",
            prerequisites = "Reach the prospectors' camp with Hauke and investigate the minecrawlers.",
            summary = "When you arrive, quickly kill the Minecrawler(s) attacking the prospectors before the workers are killed.",
            walkthroughSteps = listOf("Enter the mine/cave at the prospectors' camp.", "Kill the minecrawlers attacking or threatening the miners.", "Search the final passages before reporting to Hauke."),
            reward = "Completes Hauke's minecrawler cleanup; the older guide does not establish a separate exact payout.",
            warnings = "",
            searchTags = listOf("Kill the minecrawler in the prospectors' camp.", "Hauke", "Prospectors' camp", "SAFE")
        ),
        Quest(
            id = "G3-P4-025",
            chapter = 4,
            playOrder = 25,
            title = "Hjalte is thirsty.",
            category = "SAFE",
            giver = "Hjalte (Hammer Clan sentry)",
            location = "Hammer Clan",
            prerequisites = "Find Hjalte in the watchtower hidden beside the rock wall in Hammer Clan.",
            summary = "Give Hjalte the drink he asks for.",
            walkthroughSteps = listOf("Find guard Hjalte in the elevated side watchtower.", "Ask what he wants to drink.", "Give Hjalte ONE BOOZE.", "Continue his conversation to learn he is also hungry."),
            reward = "1,000 XP and +3 Hammer Clan reputation.",
            warnings = "",
            searchTags = listOf("Hjalte is thirsty.", "Hjalte", "Hammer Clan", "SAFE")
        ),
        Quest(
            id = "G3-P4-026",
            chapter = 4,
            playOrder = 26,
            title = "Hjalte is hungry.",
            category = "SAFE",
            giver = "Hjalte (Hammer Clan sentry)",
            location = "Hammer Clan",
            prerequisites = "Give Hjalte booze and ask about food.",
            summary = "Give Hjalte the requested meat/food.",
            walkthroughSteps = listOf("Return to Hjalte in the hidden side watchtower.", "He demands a piece of ROASTED MEAT to eat.", "Give him one roasted meat and finish the dialogue."),
            reward = "1,000 XP and +3 Hammer Clan reputation.",
            warnings = "",
            searchTags = listOf("Hjalte is hungry.", "Hjalte", "Hammer Clan", "SAFE")
        ),
        Quest(
            id = "G3-P4-027",
            chapter = 4,
            playOrder = 27,
            title = "Bridge orcs.",
            category = "SAFE",
            giver = "Hjalte or Ugolf (Hammer Clan)",
            location = "Hammer Clan bridge",
            prerequisites = "Give Hjalte the requested booze and meat, or talk to Ugolf about the Orcs at the bridge.",
            summary = "After asking about places worth visiting and the Orcs, kill the five Orc warriors that appear beneath the bridge at the Hammer Clan entrance.",
            walkthroughSteps = listOf("Ask sentry Hjalte about the Orcs near the bridge; he needs booze and cooked meat before speaking freely.", "Alternatively find Ugolf in Hammer Clan and ask about the camp.", "Travel to the bridge and defeat the Orc group occupying it.", "Finish the regional objective once the Orcs have been killed."),
            reward = "2,000 XP.",
            warnings = "",
            searchTags = listOf("Bridge orcs.", "Hjalte / Ugolf", "Hammer Clan bridge", "SAFE")
        ),
        Quest(
            id = "G3-P4-028",
            chapter = 4,
            playOrder = 28,
            title = "Hidden ore.",
            category = "SAFE",
            giver = "Hjalte / Ugolf",
            location = "Hammer Clan region",
            prerequisites = "Speak with Hjalte or Ugolf about a concealed ore deposit.",
            summary = "Follow the clues to the hidden ore deposit/cache and collect or report it as required.",
            walkthroughSteps = listOf("Get Hjalte or Ugolf's lead about a hidden ore vein.", "Follow one of the mountain canyons toward a goblin camp near a stone circle.", "Find the FALLEN TREE leaning against the canyon wall; it forms a natural bridge upward.", "Cross the tree to the hidden ledge and find the ore deposit."),
            reward = "2,000 XP, +3 Hammer Clan reputation and +1 Smithing.",
            warnings = "The key landmark is a fallen tree bridging upward near a goblin camp and stone circle.",
            searchTags = listOf("Hidden ore.", "Hammer Clan quest chain", "Hammer Clan region", "SAFE")
        ),
        Quest(
            id = "G3-P4-029",
            chapter = 4,
            playOrder = 29,
            title = "Tjalf's chest.",
            category = "SAFE / REWARD",
            giver = "Tjalf",
            location = "Hammer Clan",
            prerequisites = "Liberate the Hammer Clan furnace first.",
            summary = "Earn access to Tjalf's chest through the Hammer Clan quest chain and loot it when authorized.",
            walkthroughSteps = listOf("Speak to clan chief Tjalf about his valuable chest.", "Free the furnace and return to Tjalf.", "Take the key he offers and open his chest; stealing early is not required."),
            reward = "2,000 XP, +1 Thieving and Tjalf's chest loot.",
            warnings = "",
            searchTags = listOf("Tjalf's chest.", "Tjalf", "Hammer Clan", "SAFE / REWARD")
        ),
        Quest(
            id = "G3-P4-030",
            chapter = 4,
            playOrder = 30,
            title = "Tunnelrumbler.",
            category = "SAFE",
            giver = "Ugolf",
            location = "Hammer Clan",
            prerequisites = "Ask Ugolf in Hammer Clan about earning his confidence.",
            summary = "Investigate the rumbling/tunnel problem Ugolf mentions and resolve the creature threat connected with it.",
            walkthroughSteps = listOf("Speak to Ugolf and accept his drinking-strength test.", "Take Ugolf's TUNNELRUMBLER recipe and obtain the required ingredients.", "Prepare Tunnelrumbler at an alchemy table and DRINK it.", "Return to Ugolf to open his other ore and brewing jobs."),
            reward = "2,000 XP, +3 Hammer Clan reputation and +3 Nordmar reputation.",
            warnings = "Must brew AND drink Tunnelrumbler. Some builds have temperamental Ugolf dialogue; save before the test.",
            searchTags = listOf("Tunnelrumbler.", "Ugolf", "Hammer Clan", "SAFE")
        ),
        Quest(
            id = "G3-P4-031",
            chapter = 4,
            playOrder = 31,
            title = "Making booze with Ugolf.",
            category = "SAFE",
            giver = "Ugolf",
            location = "Hammer Clan",
            prerequisites = "Complete Ugolf's Tunnelrumbler test.",
            summary = "Bring Ugolf the ingredients required to brew his Nordmar alcohol and complete the brewing dialogue.",
            walkthroughSteps = listOf("Ask Ugolf about more alcohol supplies.", "Collect 20 BOOZEBERRIES, 2 ORE pieces and 2 MINECRAWLER MANDIBLES.", "Bring all ingredients to Ugolf to make the specialty drink."),
            reward = "2,000 XP, +3 Hammer Clan reputation and +1 Alchemy.",
            warnings = "",
            searchTags = listOf("Making booze with Ugolf.", "Ugolf", "Hammer Clan", "SAFE")
        ),
        Quest(
            id = "G3-P4-032",
            chapter = 4,
            playOrder = 32,
            title = "Ore for Ugolf.",
            category = "SAFE",
            giver = "Ugolf",
            location = "Hammer Clan",
            prerequisites = "Earn Ugolf's confidence with the Tunnelrumbler test.",
            summary = "Bring Ugolf the ore he requests.",
            walkthroughSteps = listOf("Ask Ugolf how you can help his smithing stockpile.", "Mine or collect FIFTY ore pieces.", "Hand all fifty to Ugolf."),
            reward = "1,500 XP and +1 Hammer Clan reputation.",
            warnings = "",
            searchTags = listOf("Ore for Ugolf.", "Ugolf", "Hammer Clan", "SAFE")
        ),
        Quest(
            id = "G3-P4-033",
            chapter = 4,
            playOrder = 33,
            title = "Ketil needs 12 buffalo skins.",
            category = "SAFE",
            giver = "Ketil",
            location = "Hammer Clan",
            prerequisites = "Speak to Ketil in Hammer Clan.",
            summary = "Collect twelve bison/buffalo skins and deliver them to Ketil.",
            walkthroughSteps = listOf("Ketil wants 12 bison skins for his forge.", "Collect twelve hides using hunting/skin extraction as needed.", "Give the skins to Ketil to receive his offer."),
            reward = "2,000 XP and +5 Hammer Clan reputation; hides may be exchanged for ore.",
            warnings = "",
            searchTags = listOf("Ketil needs 12 buffalo skins.", "Ketil", "Hammer Clan", "SAFE")
        ),
        Quest(
            id = "G3-P4-034",
            chapter = 4,
            playOrder = 34,
            title = "Stejnar's armor.",
            category = "SAFE",
            giver = "Stejnar (Hammer Clan armorer)",
            location = "Hammer Clan",
            prerequisites = "Ask armorer Stejnar about special armor crafting.",
            summary = "Complete Stejnar's trade/request to obtain the light Nordmar armor associated with his quest.",
            walkthroughSteps = listOf("Find Stejnar at Hammer Clan and ask about his armor.", "He offers to forge special armor if you supply TEN ore pieces.", "Bring ten ore to Stejnar and complete the forging commission."),
            reward = "2,000 XP and +3 Hammer Clan reputation.",
            warnings = "The quest requires 10 ORE pieces. Thorald's separate armor order costs gold and is not the same request.",
            searchTags = listOf("Stejnar's armor.", "Stejnar", "Hammer Clan", "SAFE")
        ),
        Quest(
            id = "G3-P4-035",
            chapter = 4,
            playOrder = 35,
            title = "Follow Mort to the Wolf Clan.",
            category = "SAFE / ESCORT",
            giver = "Mort (Hammer Clan guide)",
            location = "Hammer Clan Wolf → Clan",
            prerequisites = "Talk to Mort about gathering Wolf Clan allies for the furnace attack.",
            summary = "After discussing help for the furnace liberation, ask Mort to guide you to the Wolf Clan. Follow and protect him.",
            walkthroughSteps = listOf("Ask Mort at Hammer Clan to lead you to the Wolf Clan.", "Follow him through Nordmar, fighting hostile wildlife and Orc patrols.", "At Wolf Clan speak with Grim and available hunters Jensgar and Lisk about supporting the furnace battle."),
            reward = "1,000 XP and +2 Nordmar reputation.",
            warnings = "",
            searchTags = listOf("Follow Mort to the Wolf Clan.", "Mort", "Hammer Clan Wolf → Clan", "SAFE / ESCORT")
        ),
        Quest(
            id = "G3-P4-036",
            chapter = 4,
            playOrder = 36,
            title = "Follow Mort to the Fire Clan.",
            category = "SAFE / ESCORT",
            giver = "Mort",
            location = "Hammer Clan Fire → Clan",
            prerequisites = "Enlist Mort as a guide while preparing the Hammer Clan furnace assault.",
            summary = "Ask Mort to lead you to the Fire Clan to recruit additional fighters for the furnace assault. Protect him during the long journey.",
            walkthroughSteps = listOf("Ask Mort to guide you from Hammer Clan to Fire Clan.", "Stay with him through the snow trails; avoid getting trapped by enemies on cliffs.", "At Fire Clan locate Thorald and other fighters who may join the furnace expedition."),
            reward = "1,000 XP and +2 Nordmar reputation.",
            warnings = "",
            searchTags = listOf("Follow Mort to the Fire Clan.", "Mort", "Hammer Clan Fire → Clan", "SAFE / ESCORT")
        ),
        Quest(
            id = "G3-P4-037",
            chapter = 4,
            playOrder = 37,
            title = "Follow Mort to the lower mine entrance.",
            category = "SAFE / ESCORT",
            giver = "Mort",
            location = "Hammer Clan mine",
            prerequisites = "Prepare to attack the Orc-occupied Hammer Clan furnace.",
            summary = "Have Mort show you the lower/back entrance to the mine containing the ore furnace.",
            walkthroughSteps = listOf("Ask Mort to lead you to the LOWER mine entrance.", "Follow Mort on the mountain route to the occupied ore-mine galleries.", "Meet the allied warriors there, then begin Free the Furnace as a separate battle."),
            reward = "1,000 XP for reaching the lower mine entrance.",
            warnings = "",
            searchTags = listOf("Follow Mort to the lower mine entrance.", "Mort", "Hammer Clan mine", "SAFE / ESCORT")
        ),
        Quest(
            id = "G3-P4-038",
            chapter = 4,
            playOrder = 38,
            title = "Kill the boss of the valley.",
            category = "SAFE",
            giver = "Automatic kill objective (valley boss)",
            location = "Valley near Hammer Clan",
            prerequisites = "Travel to the lower approach to the Hammer Clan ore mine.",
            summary = "Find and kill the named/elite Orc leader controlling the valley and report the result.",
            walkthroughSteps = listOf("During the Hammer Clan furnace assault, search the area near the LOWER MINE ENTRANCE.", "Find the special Orc leader called the BOSS OF THE VALLEY.", "Kill him to trigger the automatic regional completion."),
            reward = "2,500 XP.",
            warnings = "Automatic kill quest; there is no NPC to speak to afterward.",
            searchTags = listOf("Kill the boss of the valley.", "Hammer Clan quest chain", "Valley near Hammer Clan", "SAFE")
        ),
        Quest(
            id = "G3-P4-039",
            chapter = 4,
            playOrder = 39,
            title = "Free the furnace.",
            category = "MAJOR — NORDMAR LIBERATION",
            giver = "Tjalf or Reto",
            location = "Hammer Clan mine",
            prerequisites = "Speak with Tjalf or Reto at Hammer Clan about the Orc-held mine.",
            summary = "Recruit available helpers—Mort plus fighters from the other clans—then attack the Orcs occupying the enormous mine. Fight from the lower entrance through the mine until enough Orcs are dead and the survivors flee.",
            walkthroughSteps = listOf("Accept the mine liberation assignment from Tjalf or Reto; recruit Mort as mountain guide.", "Have Mort show you the lower mine entrance and visit Wolf and Fire Clans to enlist more fighters.", "Organize the attack through the LOWER entrance; the Orc garrison is too numerous to rush alone.", "Advance through the galleries and kill shamans first until the surviving Orcs flee.", "Report to Tjalf; note that destroying Adanos artifacts in the furnace later is a DIFFERENT Xardas ending quest."),
            reward = "5,000 XP, +5 Nordmar reputation and +15 Hammer Clan reputation for freeing the furnace.",
            warnings = "Bring Jensgar, Lisk and Thorald if available, guided by Mort. Attack from the LOWER mine entrance; this liberation is NOT Xardas's later artifact-destruction ritual.",
            searchTags = listOf("Free the furnace.", "Mort / Hammer Clan", "Hammer Clan mine", "MAJOR — NORDMAR LIBERATION")
        ),
        Quest(
            id = "G3-P4-040",
            chapter = 4,
            playOrder = 40,
            title = "Ingvar wants a sword.",
            category = "SAFE / SMITHING",
            giver = "Ingvar",
            location = "Hammer Clan",
            prerequisites = "Free the Hammer Clan furnace and speak to master smith Ingvar.",
            summary = "Obtain or forge the Nordmar sword Ingvar requests and bring it to him.",
            walkthroughSteps = listOf("After clearing the furnace, ask Ingvar about the advanced sword he wants.", "Learn forging and use Ingvar's recipe to craft it yourself.", "Return the forged sword to Ingvar."),
            reward = "2,000 XP and +10 Hammer Clan reputation.",
            warnings = "",
            searchTags = listOf("Ingvar wants a sword.", "Ingvar", "Hammer Clan", "SAFE / SMITHING")
        ),
        Quest(
            id = "G3-P4-041",
            chapter = 4,
            playOrder = 41,
            title = "Approval from the ore smelters.",
            category = "SAFE / SMITHING",
            giver = "Ingvar (Hammer Clan master smith)",
            location = "Nordmar clans",
            prerequisites = "Liberate Hammer Clan's furnace, forge Ingvar's sword, then request advanced ore-smelting training.",
            summary = "Earn the approval of the required master smiths/smelters by completing their individual requests, then return to Ingvar.",
            walkthroughSteps = listOf("Complete Ingvar Wants a Sword and ask Ingvar for advanced ore smelting.", "Seek approval from FOUR smiths or ore workers: KALAN at Fire Clan, PEDAR at his remote hill workshop, and LARSON and RUNE associated with Wolf Clan.", "Finish their necessary personal assignments before requesting endorsement.", "Return to Ingvar once all four approve."),
            reward = "2,500 XP, +8 Nordmar reputation, +15 Hammer Clan reputation and +5 Smithing.",
            warnings = "Some smiths wander between locations after their earlier quests; do not assume their original positions are permanent.",
            searchTags = listOf("Approval from the ore smelters.", "Ingvar / ore smelters", "Nordmar clans", "SAFE / SMITHING")
        ),
        Quest(
            id = "G3-P4-042",
            chapter = 4,
            playOrder = 42,
            title = "A shadowbeast horn for Pedar.",
            category = "SAFE",
            giver = "Pedar (Nordmar smith)",
            location = "Hammer Clan region",
            prerequisites = "Finish Pedar's supply request for 20 ice-wolf skins and 10 ore.",
            summary = "Bring Pedar one Shadowbeast horn.",
            walkthroughSteps = listOf("After supplying Pedar, ask whether he needs another smithing material.", "Hunt shadowbeasts in Nordmar and harvest ONE shadowbeast horn.", "Bring the horn to Pedar to complete the request."),
            reward = "2,000 XP, +3 Hammer Clan reputation and +1 Smithing.",
            warnings = "",
            searchTags = listOf("A shadowbeast horn for Pedar.", "Pedar", "Hammer Clan region", "SAFE")
        ),
        Quest(
            id = "G3-P4-043",
            chapter = 4,
            playOrder = 43,
            title = "An ancestor stone for Rathgar.",
            category = "SAFE / ANCESTOR",
            giver = "Rathgar",
            location = "Fire Clan / ancestor tomb route",
            prerequisites = "Meet Rathgar after entering Nordmar from Faring and hear about thief Ali.",
            summary = "Speak with Rathgar about the ancestor stone and Kerth's mission. Obtain the correct stone for his assigned tomb.",
            walkthroughSteps = listOf("Rathgar explains that Hashishin ALI stole his ancestor stone.", "Go to Faring and find Ali, who has the stolen stone.", "Recover the ancestor stone through theft or confrontation and return it to Rathgar.", "Offer to accompany Rathgar to the nearby ancestor tomb; he can eventually give you the stone to place."),
            reward = "2,000 XP and +3 Fire Clan reputation.",
            warnings = "",
            searchTags = listOf("An ancestor stone for Rathgar.", "Rathgar", "Fire Clan / ancestor tomb route", "SAFE / ANCESTOR")
        ),
        Quest(
            id = "G3-P4-044",
            chapter = 4,
            playOrder = 44,
            title = "Accompany Rathgar to the cave tombs.",
            category = "SAFE / ESCORT",
            giver = "Rathgar",
            location = "Fire Clan tomb →",
            prerequisites = "Recover Rathgar's stone from Ali and return to him.",
            summary = "Follow Rathgar to the tomb area and protect him from wildlife and Orcs.",
            walkthroughSteps = listOf("After returning the ancestor stone, offer to accompany Rathgar to the tomb.", "Clear the route of wolves, ripperbeasts and rhinos when possible.", "Escort Rathgar to Ejnar's tomb without letting him die.", "Talk to Rathgar on arrival and continue the stone/helmet quests."),
            reward = "1,000 XP.",
            warnings = "The path is dangerous and Rathgar can be killed; clear predators before the escort if possible.",
            searchTags = listOf("Accompany Rathgar to the cave tombs.", "Rathgar", "Fire Clan tomb →", "SAFE / ESCORT")
        ),
        Quest(
            id = "G3-P4-045",
            chapter = 4,
            playOrder = 45,
            title = "Ejnar's helmet.",
            category = "SAFE / ANCESTOR",
            giver = "Rathgar",
            location = "Ejnar's tomb",
            prerequisites = "Enter Ejnar's tomb after accompanying Rathgar.",
            summary = "Search Ejnar's tomb and recover the unique helmet associated with the ancestor.",
            walkthroughSteps = listOf("Ask Rathgar about the legendary helmet of ancestor Ejnar.", "Enter Ejnar's tomb with the ancestor stone chain active.", "Defeat Ejnar's undead body and loot his helmet.", "Take Ejnar's helmet to Rathgar; he allows you to keep it afterward."),
            reward = "2,000 XP, +5 Fire Clan reputation and Ejnar's Helmet.",
            warnings = "Loot the actual named ancestor's body, not an ordinary skeleton in the tomb.",
            searchTags = listOf("Ejnar's helmet.", "Fire Clan / tomb quest", "Ejnar's tomb", "SAFE / ANCESTOR")
        ),
        Quest(
            id = "G3-P4-046",
            chapter = 4,
            playOrder = 46,
            title = "Duel with Sivert.",
            category = "SAFE — DUEL",
            giver = "Sivert (Fire Clan gate guard)",
            location = "Fire Clan",
            prerequisites = "Meet Sivert at the entrance to Fire Clan.",
            summary = "Challenge Sivert and knock him down under non-lethal duel rules.",
            walkthroughSteps = listOf("Speak to Sivert at the Fire Clan gate.", "When he challenges your allegiance, answer that you are an enemy to trigger the duel.", "Defeat Sivert NONLETHALLY without attacking other clan members.", "Finish his post-duel dialogue."),
            reward = "2,000 XP, +3 Nordmar reputation and +5 Fire Clan reputation.",
            warnings = "",
            searchTags = listOf("Duel with Sivert.", "Sivert", "Fire Clan", "SAFE — DUEL")
        ),
        Quest(
            id = "G3-P4-047",
            chapter = 4,
            playOrder = 47,
            title = "Hunting orcs with Kaelin.",
            category = "SAFE — NORDMAR LIBERATION",
            giver = "Kaelin",
            location = "Fire Clan Orc camp →",
            prerequisites = "Find Kaelin near Fire Clan and ask about the Orc camp.",
            summary = "Follow Kaelin to the Orc camp west of the Fire Clan and fight alongside him.",
            walkthroughSteps = listOf("Speak to Kaelin and accept his raid on the Orc encampment.", "Clear the road of wolves, goblins and sabertooths before escorting him if possible.", "Follow Kaelin to the Orc camp west of Fire Clan and keep him alive.", "Continue with his separate Kill the Orcs task."),
            reward = "1,250 XP.",
            warnings = "Escort safety: Kaelin may die to predators en route. He is needed for the related camp-clearance quest.",
            searchTags = listOf("Hunting orcs with Kaelin.", "Kaelin", "Fire Clan Orc camp →", "SAFE — NORDMAR LIBERATION")
        ),
        Quest(
            id = "G3-P4-048",
            chapter = 4,
            playOrder = 48,
            title = "Killing orcs!",
            category = "SAFE — NORDMAR LIBERATION",
            giver = "Kaelin",
            location = "Orc camp west of Fire Clan",
            prerequisites = "Complete Hunting Orcs with Kaelin by reaching the war camp.",
            summary = "Kill the entire designated Orc camp: warriors, scouts, shamans and elites until the quest completes.",
            walkthroughSteps = listOf("Go with Kaelin to the nearby Orc battle camp.", "Clear its Orc fighters, shamans and bowmen, prioritizing ranged enemies.", "Protect Kaelin during the fight and talk after the last Orc has fallen."),
            reward = "2,500 XP, +3 Nordmar reputation and +10 Fire Clan reputation.",
            warnings = "",
            searchTags = listOf("Killing orcs!", "Kaelin", "Orc camp west of Fire Clan", "SAFE — NORDMAR LIBERATION")
        ),
        Quest(
            id = "G3-P4-049",
            chapter = 4,
            playOrder = 49,
            title = "Hunting with Leif.",
            category = "SAFE",
            giver = "Leif",
            location = "Fire Clan wilderness",
            prerequisites = "Meet hunter Leif in the Fire Clan.",
            summary = "Join Leif on his hunting trip and help kill the target animals.",
            walkthroughSteps = listOf("Ask Leif to take you wolf hunting.", "Follow his hunting route and fight the wolves you encounter.", "Keep Leif alive and speak after the hunt ends."),
            reward = "1,500 XP, +5 Fire Clan reputation and +1 Hunting.",
            warnings = "",
            searchTags = listOf("Hunting with Leif.", "Leif", "Fire Clan wilderness", "SAFE")
        ),
        Quest(
            id = "G3-P4-050",
            chapter = 4,
            playOrder = 50,
            title = "Ten sabertooth teeth for Leif.",
            category = "SAFE",
            giver = "Leif",
            location = "Fire Clan",
            prerequisites = "Speak to Leif at Fire Clan after his hunting introduction.",
            summary = "Collect ten sabertooth teeth and give them to Leif.",
            walkthroughSteps = listOf("Leif asks for TEN SABERTOOTH TEETH.", "Hunt sabertooth tigers in Nordmar and take their teeth using the proper trophy skill.", "Return all ten teeth to Leif."),
            reward = "2,000 XP and +5 Fire Clan reputation.",
            warnings = "",
            searchTags = listOf("Ten sabertooth teeth for Leif.", "Leif", "Fire Clan", "SAFE")
        ),
        Quest(
            id = "G3-P4-051",
            chapter = 4,
            playOrder = 51,
            title = "Armor for Thorald.",
            category = "SAFE",
            giver = "Thorald",
            location = "Fire Clan",
            prerequisites = "Ask Thorald at Fire Clan about participating in battle.",
            summary = "Obtain the armor Thorald requests so he is properly equipped for later fighting.",
            walkthroughSteps = listOf("Thorald needs armor before he can join the fight.", "Visit armor maker Stejnar at Hammer Clan and commission the armor for 1,000 gold.", "Take the finished armor to Thorald."),
            reward = "2,000 XP and +5 Fire Clan reputation; the armor costs 1,000 gold.",
            warnings = "",
            searchTags = listOf("Armor for Thorald.", "Thorald", "Fire Clan", "SAFE")
        ),
        Quest(
            id = "G3-P4-052",
            chapter = 4,
            playOrder = 52,
            title = "A teleporter stone for Lee.",
            category = "SAFE / STORY CHARACTER",
            giver = "Lee (Fire Clan)",
            location = "Fire Clan",
            prerequisites = "Meet Lee at the Fire Clan; discover at least one Vengard teleport rune.",
            summary = "Find the Vengard teleport stone Lee requests and bring it to him.",
            walkthroughSteps = listOf("Lee wants to reach Vengard to confront King Rhobar.", "Find the first Vengard teleport rune in Gotha's underground cave.", "Teleport to Vengard, find the second relevant rune through the castle mage, and preserve one rune for yourself.", "Give Lee a spare Vengard rune and finish his dialogue."),
            reward = "2,000 XP.",
            warnings = "Lee's Rhobar objective may conflict with the Innos route. Keep your own way into Vengard before giving away a rune.",
            searchTags = listOf("A teleporter stone for Lee.", "Lee", "Fire Clan", "SAFE / STORY CHARACTER")
        ),
        Quest(
            id = "G3-P4-053",
            chapter = 4,
            playOrder = 53,
            title = "Raw materials for Kalan.",
            category = "SAFE / SMITHING",
            giver = "Kalan",
            location = "Fire Clan",
            prerequisites = "Speak with smith Kalan at Fire Clan.",
            summary = "Bring Kalan 30 pieces of raw steel and the required hammer so he will give his approval and offer smithing training.",
            walkthroughSteps = listOf("Ask Kalan about smithing training.", "Collect thirty pieces of RAW STEEL from traders, mines or your inventory.", "Give the 30 pieces to Kalan."),
            reward = "2,000 XP and +5 Fire Clan reputation.",
            warnings = "",
            searchTags = listOf("Raw materials for Kalan.", "Kalan", "Fire Clan", "SAFE / SMITHING")
        ),
        Quest(
            id = "G3-P4-054",
            chapter = 4,
            playOrder = 54,
            title = "The power of the ancestors.",
            category = "MAJOR / ANCESTOR",
            giver = "Kerth",
            location = "Fire Clan / all Nordmar",
            prerequisites = "Meet Kerth in Fire Clan and take his map of the six ancestor tombs.",
            summary = "Kerth gives you the ancestor-tomb mission and a map. Recover the lost ancestor stones and place each one on the altar in its corresponding tomb. There are six tombs in total.",
            walkthroughSteps = listOf("Accept Kerth's ancestor quest and map marking six Nordmar tombs.", "Find the stones of Ejnar, Angir, Snorre, Berek, Baldar and Akascha through their related quests.", "Explore around the map crosses for entrances hidden behind cliffs, then fight into each tomb.", "Place each corresponding ancestor stone on its tomb's pedestal.", "Return to Kerth after all six are activated."),
            reward = "5,000 XP, +5 Nordmar reputation and +10 Fire Clan reputation.",
            warnings = "Akascha also carries the Ring of Adanos (Magic), needed for the main ending.",
            searchTags = listOf("The power of the ancestors.", "Kerth", "Fire Clan / all Nordmar", "MAJOR / ANCESTOR")
        ),
        Quest(
            id = "G3-P4-055",
            chapter = 4,
            playOrder = 55,
            title = "Ejnar's tomb.",
            category = "SAFE / ANCESTOR",
            giver = "Kerth (Fire Clan leader)",
            location = "Nordmar",
            prerequisites = "Receive Kerth's six-tomb map and recover Ejnar's stone from Ali through Rathgar.",
            summary = "Find Ejnar's tomb, clear the undead/hostile occupants, obtain the matching ancestor stone if needed and use it on the altar.",
            walkthroughSteps = listOf("Ask Rathgar about the ancestor stone stolen by Ali in Faring, recover it and escort Rathgar to the tomb.", "Take Ejnar's stone into Ejnar's burial chamber.", "Defeat undead Ejnar and clear other skeletons.", "Put the ancestor stone on the tomb's pedestal and claim the blessing."),
            reward = "2,500 XP, +5 Nordmar reputation, +5 Fire Clan reputation and +3 Hunting.",
            warnings = "",
            searchTags = listOf("Ejnar's tomb.", "Kerth / ancestor quest", "Nordmar", "SAFE / ANCESTOR")
        ),
        Quest(
            id = "G3-P4-056",
            chapter = 4,
            playOrder = 56,
            title = "Angir's tomb.",
            category = "SAFE / ANCESTOR",
            giver = "Kerth / Osmund (Angir tomb escort)",
            location = "Nordmar",
            prerequisites = "Receive Kerth's ancestor quest; meet Osmund near Angir's tomb.",
            summary = "Locate Angir's tomb and speak with Osmund. Follow his Orc-related quest to recover the ancestor stone, clear the tomb and place the stone on the altar.",
            walkthroughSteps = listOf("Find Osmund on the way to Angir's tomb and ask about his stolen ancestor stone.", "Help Osmund kill the Orc group and its shaman holding the stone.", "Recover Angir's stone and persuade Osmund to hand it over.", "Enter Angir's tomb, kill undead Angir and place his stone on the pedestal."),
            reward = "2,500 XP, +5 Nordmar reputation, +5 Fire Clan reputation and +8 Smithing.",
            warnings = "Osmund can die in the shaman fight; make a save before escorting him.",
            searchTags = listOf("Angir's tomb.", "Kerth / Osmund", "Nordmar", "SAFE / ANCESTOR")
        ),
        Quest(
            id = "G3-P4-057",
            chapter = 4,
            playOrder = 57,
            title = "Find the orc shamans.",
            category = "SAFE",
            giver = "Osmund",
            location = "Near Angir's tomb",
            prerequisites = "Meet Osmund near Angir's tomb while collecting the six ancestor stones.",
            summary = "Follow Osmund or his directions to locate the Orc shamans who took the ancestor stone.",
            walkthroughSteps = listOf("Ask Osmund who stole his ancestor stone.", "He explains Orc shamans took it and asks for help locating them.", "Follow Osmund to the Orc encampment, staying close and clearing wildlife.", "Identify the shaman carrying Angir's stone; the assassination follows as a separate quest."),
            reward = "1,500 XP.",
            warnings = "This is the tracking stage; recover the stone during Kill the Orc Shamans.",
            searchTags = listOf("Find the orc shamans.", "Osmund / ancestor chain", "Near Angir's tomb", "SAFE")
        ),
        Quest(
            id = "G3-P4-058",
            chapter = 4,
            playOrder = 58,
            title = "Kill the orc shamans!",
            category = "SAFE",
            giver = "Osmund",
            location = "Near Angir's tomb",
            prerequisites = "Find the Orc shamans with Osmund.",
            summary = "Kill the target Orc shamans and loot the ancestor stone from the relevant body.",
            walkthroughSteps = listOf("Follow Osmund to the Orc shaman group that stole Angir's stone.", "Defeat the Orc shaman and his defenders, protecting Osmund.", "Loot the ancestor stone and speak to Osmund.", "Ask for the stone so you can restore Angir's tomb."),
            reward = "2,500 XP and +7 Fire Clan reputation.",
            warnings = "At least one shaman has the necessary Angir Ancestor Stone; loot him before leaving.",
            searchTags = listOf("Kill the orc shamans!", "Osmund", "Near Angir's tomb", "SAFE")
        ),
        Quest(
            id = "G3-P4-059",
            chapter = 4,
            playOrder = 59,
            title = "Snorre's tomb.",
            category = "SAFE / ANCESTOR",
            giver = "Kerth (ancestor quest)",
            location = "Nordmar",
            prerequisites = "Receive Kerth's tomb map; travel to Snorre's tomb.",
            summary = "Find Snorre's tomb, secure the matching ancestor stone and place it on the tomb altar after clearing enemies.",
            walkthroughSteps = listOf("Find Snorre's burial site using Kerth's map.", "Orcs and undead may already be fighting inside; defeat the ORC SHAMAN carrying Snorre's stone.", "Recover the stone, defeat undead Snorre and remaining monsters.", "Set the ancestor stone in the pedestal."),
            reward = "2,500 XP, +5 Nordmar reputation, +5 Fire Clan reputation and +3 Strength.",
            warnings = "",
            searchTags = listOf("Snorre's tomb.", "Kerth", "Nordmar", "SAFE / ANCESTOR")
        ),
        Quest(
            id = "G3-P4-060",
            chapter = 4,
            playOrder = 60,
            title = "Berek's tomb.",
            category = "SAFE / ANCESTOR",
            giver = "Kerth (ancestor quest)",
            location = "Nordmar",
            prerequisites = "Receive Kerth's tomb map and locate Berek's burial site.",
            summary = "Find Berek's tomb, clear it and place Berek's ancestor stone on the altar.",
            walkthroughSteps = listOf("Find Berek's tomb and the nearby sacrificial altar.", "Orcs killed a Nordmarian here; loot the corpse ON THE ALTAR for Berek's stone.", "Defeat the Orc shaman and the DEMON he has summoned.", "Enter Berek's tomb, kill undead Berek and activate its pedestal with the stone."),
            reward = "2,500 XP, +5 Nordmar reputation, +5 Fire Clan reputation and +3 Hunting.",
            warnings = "",
            searchTags = listOf("Berek's tomb.", "Kerth", "Nordmar", "SAFE / ANCESTOR")
        ),
        Quest(
            id = "G3-P4-061",
            chapter = 4,
            playOrder = 61,
            title = "Akascha's ancestor stone.",
            category = "SAFE / ANCESTOR",
            giver = "Kerth / monastery Akascha investigation",
            location = "Nordmar",
            prerequisites = "Learn about Akascha's tomb and receive Kerth's ancestor mission.",
            summary = "Recover Akascha's ancestor stone from the location/NPC associated with his tomb and keep it until the tomb is found.",
            walkthroughSteps = listOf("Travel to Akascha's tomb in Nordmar and identify the Orc force guarding its entrance.", "Defeat the Orc SHAMAN commanding the guardians.", "Loot Akascha's ancestor stone from the shaman's body.", "Enter the tomb, clear undead defenders, activate the altar and search undead Akascha for the Ring of Adanos (Magic)."),
            reward = "2,500 XP, +5 Nordmar reputation, +5 Fire Clan reputation and +1 Ancient Knowledge.",
            warnings = "Akascha has BOTH an ancestor stone and an Adanos ARTIFACT. The shaman guards the stone; Akascha carries the ring.",
            searchTags = listOf("Akascha's ancestor stone.", "Monastery / ancestor chain", "Nordmar", "SAFE / ANCESTOR")
        ),
        Quest(
            id = "G3-P4-062",
            chapter = 4,
            playOrder = 62,
            title = "Baldar's tomb.",
            category = "SAFE / ANCESTOR",
            giver = "Kerth (ancestor quest)",
            location = "Nordmar",
            prerequisites = "Receive Kerth's tomb map and locate Baldar's burial site.",
            summary = "Locate Baldar's tomb, clear the interior and place the correct ancestor stone on its altar.",
            walkthroughSteps = listOf("Search around Baldar's tomb entrance for a trail of BLOOD.", "Follow the blood to a nearby cave where a shadowbeast is hiding.", "Kill the shadowbeast and take Baldar's ancestor stone from its body.", "Enter the tomb, defeat Baldar's undead and use the stone on the pedestal."),
            reward = "2,500 XP, +5 Nordmar reputation, +5 Fire Clan reputation and +3 Strength.",
            warnings = "Baldar's stone is on the SHADOWBEAST in the cave, not on the ancestor inside the tomb.",
            searchTags = listOf("Baldar's tomb.", "Kerth", "Nordmar", "SAFE / ANCESTOR")
        ),
        Quest(
            id = "G3-P4-063",
            chapter = 4,
            playOrder = 63,
            title = "Liberate Nordmar!",
            category = "MAJOR",
            giver = "Kerth",
            location = "All Nordmar",
            prerequisites = "Finish the six ancestor altars and receive Kerth's Nordmar liberation quest.",
            summary = "After completing the ancestor-related progression, destroy all five major Orc camps and free the Hammer Clan ore furnace. Return to Kerth when the Orc military presence has been broken.",
            walkthroughSteps = listOf("Complete The Power of the Ancestors to earn Kerth's support.", "Destroy five separate Orc military camps in Nordmar, dealing with shamans and archers.", "Free Hammer Clan's furnace if still held by Orcs.", "Report the liberation to Kerth at Fire Clan."),
            reward = "5,000 XP, +5 Nordmar reputation and +10 Fire Clan reputation; each of five camp clearances gives 2,500 XP and +2 Nordmar.",
            warnings = "All five camps count separately. Freeing the furnace alone is insufficient.",
            searchTags = listOf("Liberate Nordmar!", "Kerth", "All Nordmar", "MAJOR")
        ),
        Quest(
            id = "G3-P4-064",
            chapter = 4,
            playOrder = 64,
            title = "Orc camp wiped out!!! — Camp 1",
            category = "SAFE — LIBERATION",
            giver = "Automatic on clearing a Nordmar Orc camp",
            location = "Nordmar",
            prerequisites = "Locate one of Kerth's five counted Nordmar Orc military camps.",
            summary = "Find one of the five major Orc camps marked by the Nordmar liberation route and kill enough Orcs for the camp-wiped-out message.",
            walkthroughSteps = listOf("Locate the Orc camp among Nordmar's five military garrisons.", "Defeat the camp's Orcs, prioritizing the shamans and pulling smaller groups out of the fortifications.", "The local objective completes when the garrison is routed; repeat for all five and report to Kerth."),
            reward = "2,500 XP and +2 Nordmar reputation for this camp.",
            warnings = "Each of the FIVE camps counts separately. Killing wandering Orc patrols does not replace a camp.",
            searchTags = listOf("Orc camp wiped out!!! — Camp 1", "Regional objective", "Nordmar", "SAFE — LIBERATION")
        ),
        Quest(
            id = "G3-P4-065",
            chapter = 4,
            playOrder = 65,
            title = "Orc camp wiped out!!! — Camp 2",
            category = "SAFE — LIBERATION",
            giver = "Automatic on clearing a Nordmar Orc camp",
            location = "Nordmar",
            prerequisites = "Locate one of Kerth's five counted Nordmar Orc military camps.",
            summary = "Clear the second major Orc camp completely enough to trigger its objective.",
            walkthroughSteps = listOf("Locate the Orc camp among Nordmar's five military garrisons.", "Defeat the camp's Orcs, prioritizing the shamans and pulling smaller groups out of the fortifications.", "The local objective completes when the garrison is routed; repeat for all five and report to Kerth."),
            reward = "2,500 XP and +2 Nordmar reputation for this camp.",
            warnings = "Each of the FIVE camps counts separately. Killing wandering Orc patrols does not replace a camp.",
            searchTags = listOf("Orc camp wiped out!!! — Camp 2", "Regional objective", "Nordmar", "SAFE — LIBERATION")
        ),
        Quest(
            id = "G3-P4-066",
            chapter = 4,
            playOrder = 66,
            title = "Orc camp wiped out!!! — Camp 3",
            category = "SAFE — LIBERATION",
            giver = "Automatic on clearing a Nordmar Orc camp",
            location = "Nordmar",
            prerequisites = "Locate one of Kerth's five counted Nordmar Orc military camps.",
            summary = "Destroy the third major Orc encampment.",
            walkthroughSteps = listOf("Locate the Orc camp among Nordmar's five military garrisons.", "Defeat the camp's Orcs, prioritizing the shamans and pulling smaller groups out of the fortifications.", "The local objective completes when the garrison is routed; repeat for all five and report to Kerth."),
            reward = "2,500 XP and +2 Nordmar reputation for this camp.",
            warnings = "Each of the FIVE camps counts separately. Killing wandering Orc patrols does not replace a camp.",
            searchTags = listOf("Orc camp wiped out!!! — Camp 3", "Regional objective", "Nordmar", "SAFE — LIBERATION")
        ),
        Quest(
            id = "G3-P4-067",
            chapter = 4,
            playOrder = 67,
            title = "Orc camp wiped out!!! — Camp 4",
            category = "SAFE — LIBERATION",
            giver = "Automatic on clearing a Nordmar Orc camp",
            location = "Nordmar",
            prerequisites = "Locate one of Kerth's five counted Nordmar Orc military camps.",
            summary = "Destroy the fourth major Orc encampment.",
            walkthroughSteps = listOf("Locate the Orc camp among Nordmar's five military garrisons.", "Defeat the camp's Orcs, prioritizing the shamans and pulling smaller groups out of the fortifications.", "The local objective completes when the garrison is routed; repeat for all five and report to Kerth."),
            reward = "2,500 XP and +2 Nordmar reputation for this camp.",
            warnings = "Each of the FIVE camps counts separately. Killing wandering Orc patrols does not replace a camp.",
            searchTags = listOf("Orc camp wiped out!!! — Camp 4", "Regional objective", "Nordmar", "SAFE — LIBERATION")
        ),
        Quest(
            id = "G3-P4-068",
            chapter = 4,
            playOrder = 68,
            title = "Orc camp wiped out!!! — Camp 5",
            category = "SAFE — LIBERATION",
            giver = "Automatic on clearing a Nordmar Orc camp",
            location = "Nordmar",
            prerequisites = "Locate one of Kerth's five counted Nordmar Orc military camps.",
            summary = "Destroy the fifth and final major Orc camp.",
            walkthroughSteps = listOf("Locate the Orc camp among Nordmar's five military garrisons.", "Defeat the camp's Orcs, prioritizing the shamans and pulling smaller groups out of the fortifications.", "The local objective completes when the garrison is routed; repeat for all five and report to Kerth."),
            reward = "2,500 XP and +2 Nordmar reputation for this camp.",
            warnings = "Each of the FIVE camps counts separately. Killing wandering Orc patrols does not replace a camp.",
            searchTags = listOf("Orc camp wiped out!!! — Camp 5", "Regional objective", "Nordmar", "SAFE — LIBERATION")
        ),
        Quest(
            id = "G3-P4-069",
            chapter = 4,
            playOrder = 69,
            title = "Find Akascha's tomb!",
            category = "SAFE / ANCESTOR",
            giver = "Dargoth (monastery librarian)",
            location = "Monastery Nordmar →",
            prerequisites = "Ask Dargoth about Akascha when seeking Adanos artifacts.",
            summary = "Use the Monastery's information to locate Akascha's tomb and continue the ancestor￾stone objective there.",
            walkthroughSteps = listOf("Ask Dargoth in Nordmar's Monastery about Akascha and the fifth temple.", "Read the relevant chronicles in the LOWER monastery library.", "Fight the demon and skeletons summoned after reading.", "Travel to Akascha's tomb and loot his Ring of Adanos (Magic)."),
            reward = "2,500 XP for the tomb lead; Akascha's ring is a divine artifact.",
            warnings = "The monastery chronicle spawns enemies; be ready before reading.",
            searchTags = listOf("Find Akascha's tomb!", "Monastery quest giver", "Monastery Nordmar →", "SAFE / ANCESTOR")
        ),
        Quest(
            id = "G3-P4-070",
            chapter = 4,
            playOrder = 70,
            title = "Mana potions for Pyran.",
            category = "SAFE",
            giver = "Pyran",
            location = "Monastery",
            prerequisites = "Ask Pyran in the Nordmar monastery courtyard.",
            summary = "Bring Pyran the requested mana potions.",
            walkthroughSteps = listOf("Begin with Pyran. The quest belongs to Monastery. In Nordmar, follow roads, bridges, clan paths and campfires whenever possible; direct cross-country travel is often slower because cliffs force long detours.", "Bring Pyran the requested mana potions.", "After the objective triggers, return to the named quest giver where applicable and exhaust the follow-up dialogue. For kill quests, if completion does not trigger, search the entire camp/perimeter for a surviving target.", "Easy Monastery quest; complete before using/selling excess mana potions."),
            reward = "1,500 XP for delivering five mana potions.",
            warnings = "",
            searchTags = listOf("Mana potions for Pyran.", "Pyran", "Monastery", "SAFE")
        ),
        Quest(
            id = "G3-P4-071",
            chapter = 4,
            playOrder = 71,
            title = "Mana plants for the monastery.",
            category = "SAFE",
            giver = "Innostian (monastery alchemist)",
            location = "Monastery",
            prerequisites = "Ask Innostian about his alchemy training and herb supply.",
            summary = "Collect the requested mana plants and deliver them to the Monastery.",
            walkthroughSteps = listOf("Begin with Monastery mage. The quest belongs to Monastery. In Nordmar, follow roads, bridges, clan paths and campfires whenever possible; direct cross-country travel is often slower because cliffs force long detours.", "Collect the requested mana plants and deliver them to the Monastery.", "After the objective triggers, return to the named quest giver where applicable and exhaust the follow-up dialogue. For kill quests, if completion does not trigger, search the entire camp/perimeter for a surviving target.", "Search around snowy slopes and paths while doing the tomb circuit."),
            reward = "1,500 XP for 50 Mana Plants.",
            warnings = "You need fifty plants, not five.",
            searchTags = listOf("Mana plants for the monastery.", "Monastery mage", "Monastery", "SAFE")
        ),
        Quest(
            id = "G3-P4-072",
            chapter = 4,
            playOrder = 72,
            title = "Bring Aidan the secret of the druids.",
            category = "SAFE / LORE",
            giver = "Aidan",
            location = "Monastery",
            prerequisites = "Ask Aidan in the Nordmar monastery about druid shapeshifting.",
            summary = "Obtain the Druid knowledge/secret required by Aidan through the relevant Druid quest line and report it to him.",
            walkthroughSteps = listOf("Speak to Aidan about the druid secret he wants to research.", "Complete Bogir's White Ripper hunt at Wolf Clan to obtain his WOLF Druid Stone.", "Bring Bogir's Wolf Druid Stone to Aidan."),
            reward = "2,000 XP.",
            warnings = "Requires Bogir's wolf stone rather than any other transformation stone.",
            searchTags = listOf("Bring Aidan the secret of the druids.", "Aidan", "Monastery", "SAFE / LORE")
        ),
    )
}
