package com.sliverzfx.gothicquest

internal object Gothic3Part4Data {
    val quests = listOf(
        Quest(
            id = "G3-P4-001",
            chapter = 4,
            playOrder = 1,
            title = "The fat bastard is dead!",
            category = "SAFE",
            giver = "Automatic / related kill",
            location = "Nordmar",
            prerequisites = "",
            summary = "This global Nordmar quest completes when the associated unique target is killed during exploration.",
            walkthroughSteps = listOf("Begin with Automatic / related kill. The quest belongs to Nordmar. In Nordmar, follow roads, bridges, clan paths and campfires whenever possible; direct cross-country travel is often slower because cliffs force long detours.", "This global Nordmar quest completes when the associated unique target is killed during exploration.", "After the objective triggers, return to the named quest giver where applicable and exhaust the follow-up dialogue. For kill quests, if completion does not trigger, search the entire camp/perimeter for a surviving target.", "Treat it as a global action quest rather than a clan-specific assignment. 1. WOLF CLAN The Wolf Clan is an excellent first anchor because its hunters teach the terrain and Graypelt can lead you directly to Xardas. Finish its hunting and bridge work before moving deeper north."),
            reward = "",
            warnings = "",
            searchTags = listOf("The fat bastard is dead!", "Automatic / related kill", "Nordmar", "SAFE")
        ),
        Quest(
            id = "G3-P4-002",
            chapter = 4,
            playOrder = 2,
            title = "Meat for Graypelt.",
            category = "SAFE",
            giver = "Graypelt",
            location = "Wolf Clan / wilderness",
            prerequisites = "",
            summary = "Give Graypelt the meat he requests so the wolf will cooperate with you.",
            walkthroughSteps = listOf("Begin with Graypelt. The quest belongs to Wolf Clan / wilderness. In Nordmar, follow roads, bridges, clan paths and campfires whenever possible; direct cross-country travel is often slower because cliffs force long detours.", "Give Graypelt the meat he requests so the wolf will cooperate with you.", "After the objective triggers, return to the named quest giver where applicable and exhaust the follow-up dialogue. For kill quests, if completion does not trigger, search the entire camp/perimeter for a surviving target.", "This immediately links into the route to Xardas; keep Graypelt alive."),
            reward = "",
            warnings = "",
            searchTags = listOf("Meat for Graypelt.", "Graypelt", "Wolf Clan / wilderness", "SAFE")
        ),
        Quest(
            id = "G3-P4-003",
            chapter = 4,
            playOrder = 3,
            title = "Follow Graypelt to Xardas' tower.",
            category = "SAFE / MAIN-STORY SUPPORT",
            giver = "Graypelt",
            location = "Wolf Clan Xardas' → tower",
            prerequisites = "",
            summary = "After feeding Graypelt, follow the wolf through Nordmar's wilderness. Stay close and protect him from hostile creatures until he reaches Xardas's tower.",
            walkthroughSteps = listOf("Begin with Graypelt. The quest belongs to Wolf Clan Xardas' tower. In Nordmar, follow → roads, bridges, clan paths and campfires whenever possible; direct cross-country travel is often slower because cliffs force long detours.", "After feeding Graypelt, follow the wolf through Nordmar's wilderness. Stay close and protect him from hostile creatures until he reaches Xardas's tower.", "After the objective triggers, return to the named quest giver where applicable and exhaust the follow-up dialogue. For kill quests, if completion does not trigger, search the entire camp/perimeter for a surviving target.", "This is one of the safest ways to find Xardas without wandering blindly through Nordmar."),
            reward = "",
            warnings = "",
            searchTags = listOf("Follow Graypelt to Xardas' tower.", "Graypelt", "Wolf Clan Xardas' → tower", "SAFE / MAIN-STORY SUPPORT")
        ),
        Quest(
            id = "G3-P4-004",
            chapter = 4,
            playOrder = 4,
            title = "Goblin attack!",
            category = "SAFE",
            giver = "Wolf Clan quest giver",
            location = "Wolf Clan outskirts",
            prerequisites = "",
            summary = "Kill the goblins attacking or threatening the clan and return after the complete target group is dead.",
            walkthroughSteps = listOf("Begin with Wolf Clan quest giver. The quest belongs to Wolf Clan outskirts. In Nordmar, follow roads, bridges, clan paths and campfires whenever possible; direct cross-country travel is often slower because cliffs force long detours.", "Kill the goblins attacking or threatening the clan and return after the complete target group is dead.", "After the objective triggers, return to the named quest giver where applicable and exhaust the follow-up dialogue. For kill quests, if completion does not trigger, search the entire camp/perimeter for a surviving target.", "Search the slopes around the settlement if the quest does not complete."),
            reward = "",
            warnings = "",
            searchTags = listOf("Goblin attack!", "Wolf Clan quest giver", "Wolf Clan outskirts", "SAFE")
        ),
        Quest(
            id = "G3-P4-005",
            chapter = 4,
            playOrder = 5,
            title = "Bag the deer on the plateau!",
            category = "SAFE",
            giver = "Wolf Clan hunter",
            location = "Plateau near Wolf Clan",
            prerequisites = "",
            summary = "Travel to the plateau indicated by the hunter and kill the designated deer. Collect useful trophies and report back.",
            walkthroughSteps = listOf("Begin with Wolf Clan hunter. The quest belongs to Plateau near Wolf Clan. In Nordmar, follow roads, bridges, clan paths and campfires whenever possible; direct cross-country travel is often slower because cliffs force long detours.", "Travel to the plateau indicated by the hunter and kill the designated deer. Collect useful trophies and report back.", "After the objective triggers, return to the named quest giver where applicable and exhaust the follow-up dialogue. For kill quests, if completion does not trigger, search the entire camp/perimeter for a surviving target.", "Ranged weapons help because deer flee quickly."),
            reward = "",
            warnings = "",
            searchTags = listOf("Bag the deer on the plateau!", "Wolf Clan hunter", "Plateau near Wolf Clan", "SAFE")
        ),
        Quest(
            id = "G3-P4-006",
            chapter = 4,
            playOrder = 6,
            title = "Take the ice wolf skins to the Wolf Clan.",
            category = "SAFE",
            giver = "Wolf Clan hunter",
            location = "Nordmar wilderness → Wolf Clan",
            prerequisites = "",
            summary = "Collect the required Ice Wolf skins and deliver them to the clan.",
            walkthroughSteps = listOf("Begin with Wolf Clan hunter. The quest belongs to Nordmar wilderness Wolf Clan. In → Nordmar, follow roads, bridges, clan paths and campfires whenever possible; direct cross-country travel is often slower because cliffs force long detours.", "Collect the required Ice Wolf skins and deliver them to the clan.", "After the objective triggers, return to the named quest giver where applicable and exhaust the follow-up dialogue. For kill quests, if completion does not trigger, search the entire camp/perimeter for a surviving target.", "Learn Skin Animals before extensive Nordmar hunting; many quests require trophies."),
            reward = "",
            warnings = "",
            searchTags = listOf("Take the ice wolf skins to the Wolf Clan.", "Wolf Clan hunter", "Nordmar wilderness → Wolf Clan", "SAFE")
        ),
        Quest(
            id = "G3-P4-007",
            chapter = 4,
            playOrder = 7,
            title = "Garik needs booze.",
            category = "SAFE",
            giver = "Garik",
            location = "Wolf Clan",
            prerequisites = "",
            summary = "Bring Garik the requested booze and speak with him again.",
            walkthroughSteps = listOf("Begin with Garik. The quest belongs to Wolf Clan. In Nordmar, follow roads, bridges, clan paths and campfires whenever possible; direct cross-country travel is often slower because cliffs force long detours.", "Bring Garik the requested booze and speak with him again.", "After the objective triggers, return to the named quest giver where applicable and exhaust the follow-up dialogue. For kill quests, if completion does not trigger, search the entire camp/perimeter for a surviving target.", "Easy reputation quest; keep Nordmar booze instead of selling every bottle."),
            reward = "",
            warnings = "",
            searchTags = listOf("Garik needs booze.", "Garik", "Wolf Clan", "SAFE")
        ),
        Quest(
            id = "G3-P4-008",
            chapter = 4,
            playOrder = 8,
            title = "Take Ronar to his hunting cabin.",
            category = "SAFE / ESCORT",
            giver = "Ronar",
            location = "Wolf Clan hunting → cabin",
            prerequisites = "",
            summary = "Escort Ronar from the clan to his hunting cabin. Stay close and kill wildlife before it overwhelms him.",
            walkthroughSteps = listOf("Begin with Ronar. The quest belongs to Wolf Clan hunting cabin. In Nordmar, follow → roads, bridges, clan paths and campfires whenever possible; direct cross-country travel is often slower because cliffs force long detours.", "Escort Ronar from the clan to his hunting cabin. Stay close and kill wildlife before it overwhelms him.", "After the objective triggers, return to the named quest giver where applicable and exhaust the follow-up dialogue. For kill quests, if completion does not trigger, search the entire camp/perimeter for a surviving target.", "Clear nearby predators first if you know the route."),
            reward = "",
            warnings = "",
            searchTags = listOf("Take Ronar to his hunting cabin.", "Ronar", "Wolf Clan hunting → cabin", "SAFE / ESCORT")
        ),
        Quest(
            id = "G3-P4-009",
            chapter = 4,
            playOrder = 9,
            title = "Ham for the woodcutters.",
            category = "SAFE",
            giver = "Wolf Clan / woodcutters",
            location = "Woodcutters' camp",
            prerequisites = "",
            summary = "Bring the requested ham/food supply to the woodcutters and complete the delivery dialogue.",
            walkthroughSteps = listOf("Begin with Wolf Clan / woodcutters. The quest belongs to Woodcutters' camp. In Nordmar, follow roads, bridges, clan paths and campfires whenever possible; direct cross-country travel is often slower because cliffs force long detours.", "Bring the requested ham/food supply to the woodcutters and complete the delivery dialogue.", "After the objective triggers, return to the named quest giver where applicable and exhaust the follow-up dialogue. For kill quests, if completion does not trigger, search the entire camp/perimeter for a surviving target.", "Pair this with the sabertooth quest at the same camp."),
            reward = "",
            warnings = "",
            searchTags = listOf("Ham for the woodcutters.", "Wolf Clan / woodcutters", "Woodcutters' camp", "SAFE")
        ),
        Quest(
            id = "G3-P4-010",
            chapter = 4,
            playOrder = 10,
            title = "Kill the sabertooths outside the woodcutters' camp!",
            category = "SAFE",
            giver = "Woodcutters",
            location = "Woodcutters' camp",
            prerequisites = "",
            summary = "Kill all sabertooths threatening the woodcutters outside their camp and report back.",
            walkthroughSteps = listOf("Begin with Woodcutters. The quest belongs to Woodcutters' camp. In Nordmar, follow roads, bridges, clan paths and campfires whenever possible; direct cross-country travel is often slower because cliffs force long detours.", "Kill all sabertooths threatening the woodcutters outside their camp and report back.", "After the objective triggers, return to the named quest giver where applicable and exhaust the follow-up dialogue. For kill quests, if completion does not trigger, search the entire camp/perimeter for a surviving target.", "Do not leave after killing only the first animal; check the whole perimeter."),
            reward = "",
            warnings = "",
            searchTags = listOf("Kill the sabertooths outside the woodcutters' camp!", "Woodcutters", "Woodcutters' camp", "SAFE")
        ),
        Quest(
            id = "G3-P4-011",
            chapter = 4,
            playOrder = 11,
            title = "Duel with Hogar.",
            category = "SAFE — DUEL",
            giver = "Hogar",
            location = "Wolf Clan",
            prerequisites = "",
            summary = "Challenge Hogar and defeat him under normal non-lethal duel rules. Wait for him to stand and speak again.",
            walkthroughSteps = listOf("Begin with Hogar. The quest belongs to Wolf Clan. In Nordmar, follow roads, bridges, clan paths and campfires whenever possible; direct cross-country travel is often slower because cliffs force long detours.", "Challenge Hogar and defeat him under normal non-lethal duel rules. Wait for him to stand and speak again.", "After the objective triggers, return to the named quest giver where applicable and exhaust the follow-up dialogue. For kill quests, if completion does not trigger, search the entire camp/perimeter for a surviving target.", "Do this before taking Hogar on his bridge combat quest."),
            reward = "",
            warnings = "",
            searchTags = listOf("Duel with Hogar.", "Hogar", "Wolf Clan", "SAFE — DUEL")
        ),
        Quest(
            id = "G3-P4-012",
            chapter = 4,
            playOrder = 12,
            title = "Free the bridge in the south.",
            category = "SAFE",
            giver = "Hogar / Wolf Clan",
            location = "Southern bridge",
            prerequisites = "",
            summary = "Travel to the southern bridge and eliminate the Orc force blocking it.",
            walkthroughSteps = listOf("Begin with Hogar / Wolf Clan. The quest belongs to Southern bridge. In Nordmar, follow roads, bridges, clan paths and campfires whenever possible; direct cross-country travel is often slower because cliffs force long detours.", "Travel to the southern bridge and eliminate the Orc force blocking it.", "After the objective triggers, return to the named quest giver where applicable and exhaust the follow-up dialogue. For kill quests, if completion does not trigger, search the entire camp/perimeter for a surviving target.", "Linked with going to the bridge with Hogar."),
            reward = "",
            warnings = "",
            searchTags = listOf("Free the bridge in the south.", "Hogar / Wolf Clan", "Southern bridge", "SAFE")
        ),
        Quest(
            id = "G3-P4-013",
            chapter = 4,
            playOrder = 13,
            title = "Go to the southern bridge with Hogar.",
            category = "SAFE / ESCORT",
            giver = "Hogar",
            location = "Wolf Clan southern → bridge",
            prerequisites = "",
            summary = "Ask Hogar to accompany you and follow him to the southern bridge. Protect him on the route and during the Orc fight.",
            walkthroughSteps = listOf("Begin with Hogar. The quest belongs to Wolf Clan southern bridge. In Nordmar, follow → roads, bridges, clan paths and campfires whenever possible; direct cross-country travel is often slower because cliffs force long detours.", "Ask Hogar to accompany you and follow him to the southern bridge. Protect him on the route and during the Orc fight.", "After the objective triggers, return to the named quest giver where applicable and exhaust the follow-up dialogue. For kill quests, if completion does not trigger, search the entire camp/perimeter for a surviving target.", "Completing both bridge quests together is the efficient route."),
            reward = "",
            warnings = "",
            searchTags = listOf("Go to the southern bridge with Hogar.", "Hogar", "Wolf Clan southern → bridge", "SAFE / ESCORT")
        ),
        Quest(
            id = "G3-P4-014",
            chapter = 4,
            playOrder = 14,
            title = "The druid stone of the wolf.",
            category = "SAFE / DRUID",
            giver = "Bogir",
            location = "Wolf Clan",
            prerequisites = "",
            summary = "Speak with Bogir and follow his quest chain involving the Wolf Druid Stone.",
            walkthroughSteps = listOf("Begin with Bogir. The quest belongs to Wolf Clan. In Nordmar, follow roads, bridges, clan paths and campfires whenever possible; direct cross-country travel is often slower because cliffs force long detours.", "Speak with Bogir and follow his quest chain involving the Wolf Druid Stone.", "After the objective triggers, return to the named quest giver where applicable and exhaust the follow-up dialogue. For kill quests, if completion does not trigger, search the entire camp/perimeter for a surviving target.", "Do not kill or alienate Bogir before completing his hunt and Druid Stone content."),
            reward = "",
            warnings = "",
            searchTags = listOf("The druid stone of the wolf.", "Bogir", "Wolf Clan", "SAFE / DRUID")
        ),
        Quest(
            id = "G3-P4-015",
            chapter = 4,
            playOrder = 15,
            title = "Kill the White Ripper!",
            category = "SAFE",
            giver = "Bogir",
            location = "Nordmar wilderness",
            prerequisites = "",
            summary = "Track down the unique White Ripper requested by Bogir and kill it. Return to Bogir after the hunt.",
            walkthroughSteps = listOf("Begin with Bogir. The quest belongs to Nordmar wilderness. In Nordmar, follow roads, bridges, clan paths and campfires whenever possible; direct cross-country travel is often slower because cliffs force long detours.", "Track down the unique White Ripper requested by Bogir and kill it. Return to Bogir after the hunt.", "After the objective triggers, return to the named quest giver where applicable and exhaust the follow-up dialogue. For kill quests, if completion does not trigger, search the entire camp/perimeter for a surviving target.", "The hunt is connected to Bogir's personal story and Druid Stone."),
            reward = "",
            warnings = "",
            searchTags = listOf("Kill the White Ripper!", "Bogir", "Nordmar wilderness", "SAFE")
        ),
        Quest(
            id = "G3-P4-016",
            chapter = 4,
            playOrder = 16,
            title = "Hunt the white shadowbeast!",
            category = "SAFE",
            giver = "Wolf Clan hunter",
            location = "Nordmar wilderness",
            prerequisites = "",
            summary = "Locate and kill the unique white Shadowbeast, then report back to the appropriate hunter.",
            walkthroughSteps = listOf("Begin with Wolf Clan hunter. The quest belongs to Nordmar wilderness. In Nordmar, follow roads, bridges, clan paths and campfires whenever possible; direct cross-country travel is often slower because cliffs force long detours.", "Locate and kill the unique white Shadowbeast, then report back to the appropriate hunter.", "After the objective triggers, return to the named quest giver where applicable and exhaust the follow-up dialogue. For kill quests, if completion does not trigger, search the entire camp/perimeter for a surviving target.", "Treat unique white beasts as quest targets; do not assume they are ordinary wildlife."),
            reward = "",
            warnings = "",
            searchTags = listOf("Hunt the white shadowbeast!", "Wolf Clan hunter", "Nordmar wilderness", "SAFE")
        ),
        Quest(
            id = "G3-P4-017",
            chapter = 4,
            playOrder = 17,
            title = "Eliminate the war drummer of the orcs!",
            category = "SAFE — NORDMAR LIBERATION",
            giver = "Jensgar",
            location = "Pass / Orc camp",
            prerequisites = "",
            summary = "Find the Orc unit with the war drummer on the pass and destroy the group, including the drummer.",
            walkthroughSteps = listOf("Begin with Jensgar. The quest belongs to Pass / Orc camp. In Nordmar, follow roads, bridges, clan paths and campfires whenever possible; direct cross-country travel is often slower because cliffs force long detours.", "Find the Orc unit with the war drummer on the pass and destroy the group, including the drummer.", "After the objective triggers, return to the named quest giver where applicable and exhaust the follow-up dialogue. For kill quests, if completion does not trigger, search the entire camp/perimeter for a surviving target.", "This contributes to weakening the Orc presence in Nordmar."),
            reward = "",
            warnings = "",
            searchTags = listOf("Eliminate the war drummer of the orcs!", "Jensgar", "Pass / Orc camp", "SAFE — NORDMAR LIBERATION")
        ),
        Quest(
            id = "G3-P4-018",
            chapter = 4,
            playOrder = 18,
            title = "Pelts for Jensgar.",
            category = "SAFE",
            giver = "Jensgar",
            location = "Wolf Clan",
            prerequisites = "",
            summary = "Collect the animal pelts Jensgar requests and bring the full amount to him.",
            walkthroughSteps = listOf("Begin with Jensgar. The quest belongs to Wolf Clan. In Nordmar, follow roads, bridges, clan paths and campfires whenever possible; direct cross-country travel is often slower because cliffs force long detours.", "Collect the animal pelts Jensgar requests and bring the full amount to him.", "After the objective triggers, return to the named quest giver where applicable and exhaust the follow-up dialogue. For kill quests, if completion does not trigger, search the entire camp/perimeter for a surviving target.", "Combine with Ice Wolf, sabertooth and other hunting objectives."),
            reward = "",
            warnings = "",
            searchTags = listOf("Pelts for Jensgar.", "Jensgar", "Wolf Clan", "SAFE")
        ),
        Quest(
            id = "G3-P4-019",
            chapter = 4,
            playOrder = 19,
            title = "Jorn needs exploding arrows.",
            category = "SAFE",
            giver = "Jorn",
            location = "Wolf Clan",
            prerequisites = "",
            summary = "Bring Jorn twelve exploding arrows. They can be obtained from merchants including Vibald near the Hammer Clan region.",
            walkthroughSteps = listOf("Begin with Jorn. The quest belongs to Wolf Clan. In Nordmar, follow roads, bridges, clan paths and campfires whenever possible; direct cross-country travel is often slower because cliffs force long detours.", "Bring Jorn twelve exploding arrows. They can be obtained from merchants including Vibald near the Hammer Clan region.", "After the objective triggers, return to the named quest giver where applicable and exhaust the follow-up dialogue. For kill quests, if completion does not trigger, search the entire camp/perimeter for a surviving target.", "Do not waste the arrows if you already know you need twelve for this quest."),
            reward = "",
            warnings = "",
            searchTags = listOf("Jorn needs exploding arrows.", "Jorn", "Wolf Clan", "SAFE")
        ),
        Quest(
            id = "G3-P4-020",
            chapter = 4,
            playOrder = 20,
            title = "Looking for ore with Larson.",
            category = "SAFE / ESCORT",
            giver = "Larson",
            location = "Wolf Clan / wilderness",
            prerequisites = "",
            summary = "Accompany Larson on his prospecting trip and help him reach the ore location safely.",
            walkthroughSteps = listOf("Begin with Larson. The quest belongs to Wolf Clan / wilderness. In Nordmar, follow roads, bridges, clan paths and campfires whenever possible; direct cross-country travel is often slower because cliffs force long detours.", "Accompany Larson on his prospecting trip and help him reach the ore location safely.", "After the objective triggers, return to the named quest giver where applicable and exhaust the follow-up dialogue. For kill quests, if completion does not trigger, search the entire camp/perimeter for a surviving target.", "Stay close; Nordmar escort NPCs can easily engage predators off-route. 2. HAMMER CLAN The Hammer Clan revolves around mining, smithing and the giant ore furnace. Do its smaller supply/prospector quests first, recruit help from the other clans, then liberate the furnace."),
            reward = "",
            warnings = "",
            searchTags = listOf("Looking for ore with Larson.", "Larson", "Wolf Clan / wilderness", "SAFE / ESCORT")
        ),
        Quest(
            id = "G3-P4-021",
            chapter = 4,
            playOrder = 21,
            title = "Supplies for Pedar.",
            category = "SAFE",
            giver = "Pedar",
            location = "Hammer Clan region",
            prerequisites = "",
            summary = "Bring Pedar the supplies he requests and finish his delivery dialogue.",
            walkthroughSteps = listOf("Begin with Pedar. The quest belongs to Hammer Clan region. In Nordmar, follow roads, bridges, clan paths and campfires whenever possible; direct cross-country travel is often slower because cliffs force long detours.", "Bring Pedar the supplies he requests and finish his delivery dialogue.", "After the objective triggers, return to the named quest giver where applicable and exhaust the follow-up dialogue. For kill quests, if completion does not trigger, search the entire camp/perimeter for a surviving target.", "Pedar is also tied to the ore-smelter approval chain."),
            reward = "",
            warnings = "",
            searchTags = listOf("Supplies for Pedar.", "Pedar", "Hammer Clan region", "SAFE")
        ),
        Quest(
            id = "G3-P4-022",
            chapter = 4,
            playOrder = 22,
            title = "Hauke needs ore.",
            category = "SAFE",
            giver = "Hauke",
            location = "Hammer Clan",
            prerequisites = "",
            summary = "Bring Hauke ten ore nuggets/pieces as requested.",
            walkthroughSteps = listOf("Begin with Hauke. The quest belongs to Hammer Clan. In Nordmar, follow roads, bridges, clan paths and campfires whenever possible; direct cross-country travel is often slower because cliffs force long detours.", "Bring Hauke ten ore nuggets/pieces as requested.", "After the objective triggers, return to the named quest giver where applicable and exhaust the follow-up dialogue. For kill quests, if completion does not trigger, search the entire camp/perimeter for a surviving target.", "Keep spare ore; Hammer Clan has several ore and smithing quests."),
            reward = "",
            warnings = "",
            searchTags = listOf("Hauke needs ore.", "Hauke", "Hammer Clan", "SAFE")
        ),
        Quest(
            id = "G3-P4-023",
            chapter = 4,
            playOrder = 23,
            title = "Go to the prospectors' camp with Hauke.",
            category = "SAFE / ESCORT",
            giver = "Hauke",
            location = "Hammer Clan → prospectors' camp",
            prerequisites = "",
            summary = "Follow Hauke to the prospectors' camp and keep him alive along the route.",
            walkthroughSteps = listOf("Begin with Hauke. The quest belongs to Hammer Clan prospectors' camp. In Nordmar, → follow roads, bridges, clan paths and campfires whenever possible; direct cross-country travel is often slower because cliffs force long detours.", "Follow Hauke to the prospectors' camp and keep him alive along the route.", "After the objective triggers, return to the named quest giver where applicable and exhaust the follow-up dialogue. For kill quests, if completion does not trigger, search the entire camp/perimeter for a surviving target.", "The next Minecrawler quest begins at the camp."),
            reward = "",
            warnings = "",
            searchTags = listOf("Go to the prospectors' camp with Hauke.", "Hauke", "Hammer Clan → prospectors' camp", "SAFE / ESCORT")
        ),
        Quest(
            id = "G3-P4-024",
            chapter = 4,
            playOrder = 24,
            title = "Kill the minecrawler in the prospectors' camp.",
            category = "SAFE",
            giver = "Hauke",
            location = "Prospectors' camp",
            prerequisites = "",
            summary = "When you arrive, quickly kill the Minecrawler(s) attacking the prospectors before the workers are killed.",
            walkthroughSteps = listOf("Begin with Hauke. The quest belongs to Prospectors' camp. In Nordmar, follow roads, bridges, clan paths and campfires whenever possible; direct cross-country travel is often slower because cliffs force long detours.", "When you arrive, quickly kill the Minecrawler(s) attacking the prospectors before the workers are killed.", "After the objective triggers, return to the named quest giver where applicable and exhaust the follow-up dialogue. For kill quests, if completion does not trigger, search the entire camp/perimeter for a surviving target.", "Act immediately on arrival; friendly NPCs can die during the attack."),
            reward = "",
            warnings = "",
            searchTags = listOf("Kill the minecrawler in the prospectors' camp.", "Hauke", "Prospectors' camp", "SAFE")
        ),
        Quest(
            id = "G3-P4-025",
            chapter = 4,
            playOrder = 25,
            title = "Hjalte is thirsty.",
            category = "SAFE",
            giver = "Hjalte",
            location = "Hammer Clan",
            prerequisites = "",
            summary = "Give Hjalte the drink he asks for.",
            walkthroughSteps = listOf("Begin with Hjalte. The quest belongs to Hammer Clan. In Nordmar, follow roads, bridges, clan paths and campfires whenever possible; direct cross-country travel is often slower because cliffs force long detours.", "Give Hjalte the drink he asks for.", "After the objective triggers, return to the named quest giver where applicable and exhaust the follow-up dialogue. For kill quests, if completion does not trigger, search the entire camp/perimeter for a surviving target.", "His dialogue also leads to local information and other small quests."),
            reward = "",
            warnings = "",
            searchTags = listOf("Hjalte is thirsty.", "Hjalte", "Hammer Clan", "SAFE")
        ),
        Quest(
            id = "G3-P4-026",
            chapter = 4,
            playOrder = 26,
            title = "Hjalte is hungry.",
            category = "SAFE",
            giver = "Hjalte",
            location = "Hammer Clan",
            prerequisites = "",
            summary = "Give Hjalte the requested meat/food.",
            walkthroughSteps = listOf("Begin with Hjalte. The quest belongs to Hammer Clan. In Nordmar, follow roads, bridges, clan paths and campfires whenever possible; direct cross-country travel is often slower because cliffs force long detours.", "Give Hjalte the requested meat/food.", "After the objective triggers, return to the named quest giver where applicable and exhaust the follow-up dialogue. For kill quests, if completion does not trigger, search the entire camp/perimeter for a surviving target.", "Do together with his thirst quest."),
            reward = "",
            warnings = "",
            searchTags = listOf("Hjalte is hungry.", "Hjalte", "Hammer Clan", "SAFE")
        ),
        Quest(
            id = "G3-P4-027",
            chapter = 4,
            playOrder = 27,
            title = "Bridge orcs.",
            category = "SAFE",
            giver = "Hjalte / Ugolf",
            location = "Hammer Clan bridge",
            prerequisites = "",
            summary = "After asking about places worth visiting and the Orcs, kill the five Orc warriors that appear beneath the bridge at the Hammer Clan entrance.",
            walkthroughSteps = listOf("Begin with Hjalte / Ugolf. The quest belongs to Hammer Clan bridge. In Nordmar, follow roads, bridges, clan paths and campfires whenever possible; direct cross-country travel is often slower because cliffs force long detours.", "After asking about places worth visiting and the Orcs, kill the five Orc warriors that appear beneath the bridge at the Hammer Clan entrance.", "After the objective triggers, return to the named quest giver where applicable and exhaust the follow-up dialogue. For kill quests, if completion does not trigger, search the entire camp/perimeter for a surviving target.", "Verified target is five Orc warriors; visit Ugolf afterward for the extra reward."),
            reward = "",
            warnings = "",
            searchTags = listOf("Bridge orcs.", "Hjalte / Ugolf", "Hammer Clan bridge", "SAFE")
        ),
        Quest(
            id = "G3-P4-028",
            chapter = 4,
            playOrder = 28,
            title = "Hidden ore.",
            category = "SAFE",
            giver = "Hammer Clan quest chain",
            location = "Hammer Clan region",
            prerequisites = "",
            summary = "Follow the clues to the hidden ore deposit/cache and collect or report it as required.",
            walkthroughSteps = listOf("Begin with Hammer Clan quest chain. The quest belongs to Hammer Clan region. In Nordmar, follow roads, bridges, clan paths and campfires whenever possible; direct cross-country travel is often slower because cliffs force long detours.", "Follow the clues to the hidden ore deposit/cache and collect or report it as required.", "After the objective triggers, return to the named quest giver where applicable and exhaust the follow-up dialogue. For kill quests, if completion does not trigger, search the entire camp/perimeter for a surviving target.", "Search rock ledges and mine approaches carefully."),
            reward = "",
            warnings = "",
            searchTags = listOf("Hidden ore.", "Hammer Clan quest chain", "Hammer Clan region", "SAFE")
        ),
        Quest(
            id = "G3-P4-029",
            chapter = 4,
            playOrder = 29,
            title = "Tjalf's chest.",
            category = "SAFE / REWARD",
            giver = "Tjalf",
            location = "Hammer Clan",
            prerequisites = "",
            summary = "Earn access to Tjalf's chest through the Hammer Clan quest chain and loot it when authorized.",
            walkthroughSteps = listOf("Begin with Tjalf. The quest belongs to Hammer Clan. In Nordmar, follow roads, bridges, clan paths and campfires whenever possible; direct cross-country travel is often slower because cliffs force long detours.", "Earn access to Tjalf's chest through the Hammer Clan quest chain and loot it when authorized.", "After the objective triggers, return to the named quest giver where applicable and exhaust the follow-up dialogue. For kill quests, if completion does not trigger, search the entire camp/perimeter for a surviving target.", "Do not simply steal from the clan leader before earning the key/right."),
            reward = "",
            warnings = "",
            searchTags = listOf("Tjalf's chest.", "Tjalf", "Hammer Clan", "SAFE / REWARD")
        ),
        Quest(
            id = "G3-P4-030",
            chapter = 4,
            playOrder = 30,
            title = "Tunnelrumbler.",
            category = "SAFE",
            giver = "Ugolf",
            location = "Hammer Clan",
            prerequisites = "",
            summary = "Investigate the rumbling/tunnel problem Ugolf mentions and resolve the creature threat connected with it.",
            walkthroughSteps = listOf("Begin with Ugolf. The quest belongs to Hammer Clan. In Nordmar, follow roads, bridges, clan paths and campfires whenever possible; direct cross-country travel is often slower because cliffs force long detours.", "Investigate the rumbling/tunnel problem Ugolf mentions and resolve the creature threat connected with it.", "After the objective triggers, return to the named quest giver where applicable and exhaust the follow-up dialogue. For kill quests, if completion does not trigger, search the entire camp/perimeter for a surviving target.", "This helps earn Ugolf's approval in the smith/smelter chain."),
            reward = "",
            warnings = "",
            searchTags = listOf("Tunnelrumbler.", "Ugolf", "Hammer Clan", "SAFE")
        ),
        Quest(
            id = "G3-P4-031",
            chapter = 4,
            playOrder = 31,
            title = "Making booze with Ugolf.",
            category = "SAFE",
            giver = "Ugolf",
            location = "Hammer Clan",
            prerequisites = "",
            summary = "Bring Ugolf the ingredients required to brew his Nordmar alcohol and complete the brewing dialogue.",
            walkthroughSteps = listOf("Begin with Ugolf. The quest belongs to Hammer Clan. In Nordmar, follow roads, bridges, clan paths and campfires whenever possible; direct cross-country travel is often slower because cliffs force long detours.", "Bring Ugolf the ingredients required to brew his Nordmar alcohol and complete the brewing dialogue.", "After the objective triggers, return to the named quest giver where applicable and exhaust the follow-up dialogue. For kill quests, if completion does not trigger, search the entire camp/perimeter for a surviving target.", "Keep local brewing ingredients until this quest is finished."),
            reward = "",
            warnings = "",
            searchTags = listOf("Making booze with Ugolf.", "Ugolf", "Hammer Clan", "SAFE")
        ),
        Quest(
            id = "G3-P4-032",
            chapter = 4,
            playOrder = 32,
            title = "Ore for Ugolf.",
            category = "SAFE",
            giver = "Ugolf",
            location = "Hammer Clan",
            prerequisites = "",
            summary = "Bring Ugolf the ore he requests.",
            walkthroughSteps = listOf("Begin with Ugolf. The quest belongs to Hammer Clan. In Nordmar, follow roads, bridges, clan paths and campfires whenever possible; direct cross-country travel is often slower because cliffs force long detours.", "Bring Ugolf the ore he requests.", "After the objective triggers, return to the named quest giver where applicable and exhaust the follow-up dialogue. For kill quests, if completion does not trigger, search the entire camp/perimeter for a surviving target.", "Can overlap with Hauke and mining objectives."),
            reward = "",
            warnings = "",
            searchTags = listOf("Ore for Ugolf.", "Ugolf", "Hammer Clan", "SAFE")
        ),
        Quest(
            id = "G3-P4-033",
            chapter = 4,
            playOrder = 33,
            title = "Ketil needs 12 buffalo skins.",
            category = "SAFE",
            giver = "Ketil",
            location = "Hammer Clan",
            prerequisites = "",
            summary = "Collect twelve bison/buffalo skins and deliver them to Ketil.",
            walkthroughSteps = listOf("Begin with Ketil. The quest belongs to Hammer Clan. In Nordmar, follow roads, bridges, clan paths and campfires whenever possible; direct cross-country travel is often slower because cliffs force long detours.", "Collect twelve bison/buffalo skins and deliver them to Ketil.", "After the objective triggers, return to the named quest giver where applicable and exhaust the follow-up dialogue. For kill quests, if completion does not trigger, search the entire camp/perimeter for a surviving target.", "Rune in the Wolf Clan may sell some skins; otherwise hunt bison after learning Skin Animals."),
            reward = "",
            warnings = "",
            searchTags = listOf("Ketil needs 12 buffalo skins.", "Ketil", "Hammer Clan", "SAFE")
        ),
        Quest(
            id = "G3-P4-034",
            chapter = 4,
            playOrder = 34,
            title = "Stejnar's armor.",
            category = "SAFE",
            giver = "Stejnar",
            location = "Hammer Clan",
            prerequisites = "",
            summary = "Complete Stejnar's trade/request to obtain the light Nordmar armor associated with his quest.",
            walkthroughSteps = listOf("Begin with Stejnar. The quest belongs to Hammer Clan. In Nordmar, follow roads, bridges, clan paths and campfires whenever possible; direct cross-country travel is often slower because cliffs force long detours.", "Complete Stejnar's trade/request to obtain the light Nordmar armor associated with his quest.", "After the objective triggers, return to the named quest giver where applicable and exhaust the follow-up dialogue. For kill quests, if completion does not trigger, search the entire camp/perimeter for a surviving target.", "Useful equipment before the harder Orc camps and tombs."),
            reward = "",
            warnings = "",
            searchTags = listOf("Stejnar's armor.", "Stejnar", "Hammer Clan", "SAFE")
        ),
        Quest(
            id = "G3-P4-035",
            chapter = 4,
            playOrder = 35,
            title = "Follow Mort to the Wolf Clan.",
            category = "SAFE / ESCORT",
            giver = "Mort",
            location = "Hammer Clan Wolf → Clan",
            prerequisites = "",
            summary = "After discussing help for the furnace liberation, ask Mort to guide you to the Wolf Clan. Follow and protect him.",
            walkthroughSteps = listOf("Begin with Mort. The quest belongs to Hammer Clan Wolf Clan. In Nordmar, follow → roads, bridges, clan paths and campfires whenever possible; direct cross-country travel is often slower because cliffs force long detours.", "After discussing help for the furnace liberation, ask Mort to guide you to the Wolf Clan. Follow and protect him.", "After the objective triggers, return to the named quest giver where applicable and exhaust the follow-up dialogue. For kill quests, if completion does not trigger, search the entire camp/perimeter for a surviving target.", "Mort changes routes depending on starting position; stay close."),
            reward = "",
            warnings = "",
            searchTags = listOf("Follow Mort to the Wolf Clan.", "Mort", "Hammer Clan Wolf → Clan", "SAFE / ESCORT")
        ),
        Quest(
            id = "G3-P4-036",
            chapter = 4,
            playOrder = 36,
            title = "Follow Mort to the Fire Clan.",
            category = "SAFE / ESCORT",
            giver = "Mort",
            location = "Hammer Clan Fire → Clan",
            prerequisites = "",
            summary = "Ask Mort to lead you to the Fire Clan to recruit additional fighters for the furnace assault. Protect him during the long journey.",
            walkthroughSteps = listOf("Begin with Mort. The quest belongs to Hammer Clan Fire Clan. In Nordmar, follow → roads, bridges, clan paths and campfires whenever possible; direct cross-country travel is often slower because cliffs force long detours.", "Ask Mort to lead you to the Fire Clan to recruit additional fighters for the furnace assault. Protect him during the long journey.", "After the objective triggers, return to the named quest giver where applicable and exhaust the follow-up dialogue. For kill quests, if completion does not trigger, search the entire camp/perimeter for a surviving target.", "Verified to involve a long route with Orcs and wildlife."),
            reward = "",
            warnings = "",
            searchTags = listOf("Follow Mort to the Fire Clan.", "Mort", "Hammer Clan Fire → Clan", "SAFE / ESCORT")
        ),
        Quest(
            id = "G3-P4-037",
            chapter = 4,
            playOrder = 37,
            title = "Follow Mort to the lower mine entrance.",
            category = "SAFE / ESCORT",
            giver = "Mort",
            location = "Hammer Clan mine",
            prerequisites = "",
            summary = "Have Mort show you the lower/back entrance to the mine containing the ore furnace.",
            walkthroughSteps = listOf("Begin with Mort. The quest belongs to Hammer Clan mine. In Nordmar, follow roads, bridges, clan paths and campfires whenever possible; direct cross-country travel is often slower because cliffs force long detours.", "Have Mort show you the lower/back entrance to the mine containing the ore furnace.", "After the objective triggers, return to the named quest giver where applicable and exhaust the follow-up dialogue. For kill quests, if completion does not trigger, search the entire camp/perimeter for a surviving target.", "This entrance is useful for gathering allies before the liberation."),
            reward = "",
            warnings = "",
            searchTags = listOf("Follow Mort to the lower mine entrance.", "Mort", "Hammer Clan mine", "SAFE / ESCORT")
        ),
        Quest(
            id = "G3-P4-038",
            chapter = 4,
            playOrder = 38,
            title = "Kill the boss of the valley.",
            category = "SAFE",
            giver = "Hammer Clan quest chain",
            location = "Valley near Hammer Clan",
            prerequisites = "",
            summary = "Find and kill the named/elite Orc leader controlling the valley and report the result.",
            walkthroughSteps = listOf("Begin with Hammer Clan quest chain. The quest belongs to Valley near Hammer Clan. In Nordmar, follow roads, bridges, clan paths and campfires whenever possible; direct cross-country travel is often slower because cliffs force long detours.", "Find and kill the named/elite Orc leader controlling the valley and report the result.", "After the objective triggers, return to the named quest giver where applicable and exhaust the follow-up dialogue. For kill quests, if completion does not trigger, search the entire camp/perimeter for a surviving target.", "Useful preparation before the furnace assault."),
            reward = "",
            warnings = "",
            searchTags = listOf("Kill the boss of the valley.", "Hammer Clan quest chain", "Valley near Hammer Clan", "SAFE")
        ),
        Quest(
            id = "G3-P4-039",
            chapter = 4,
            playOrder = 39,
            title = "Free the furnace.",
            category = "MAJOR — NORDMAR LIBERATION",
            giver = "Mort / Hammer Clan",
            location = "Hammer Clan mine",
            prerequisites = "",
            summary = "Recruit available helpers—Mort plus fighters from the other clans—then attack the Orcs occupying the enormous mine. Fight from the lower entrance through the mine until enough Orcs are dead and the survivors flee.",
            walkthroughSteps = listOf("Begin with Mort / Hammer Clan. The quest belongs to Hammer Clan mine. In Nordmar, follow roads, bridges, clan paths and campfires whenever possible; direct cross-country travel is often slower because cliffs force long detours.", "Recruit available helpers—Mort plus fighters from the other clans—then attack the Orcs occupying the enormous mine. Fight from the lower entrance through the mine until enough Orcs are dead and the survivors flee.", "After the objective triggers, return to the named quest giver where applicable and exhaust the follow-up dialogue. For kill quests, if completion does not trigger, search the entire camp/perimeter for a surviving target.", "This is one of Nordmar's biggest battles. It is NOT the same as using the furnace later for Xardas's ending. ⚠ Progression warning: Make a manual save before committing. This quest can affect major regional or ending-related progression."),
            reward = "",
            warnings = "",
            searchTags = listOf("Free the furnace.", "Mort / Hammer Clan", "Hammer Clan mine", "MAJOR — NORDMAR LIBERATION")
        ),
        Quest(
            id = "G3-P4-040",
            chapter = 4,
            playOrder = 40,
            title = "Ingvar wants a sword.",
            category = "SAFE / SMITHING",
            giver = "Ingvar",
            location = "Hammer Clan",
            prerequisites = "",
            summary = "Obtain or forge the Nordmar sword Ingvar requests and bring it to him.",
            walkthroughSteps = listOf("Begin with Ingvar. The quest belongs to Hammer Clan. In Nordmar, follow roads, bridges, clan paths and campfires whenever possible; direct cross-country travel is often slower because cliffs force long detours.", "Obtain or forge the Nordmar sword Ingvar requests and bring it to him.", "After the objective triggers, return to the named quest giver where applicable and exhaust the follow-up dialogue. For kill quests, if completion does not trigger, search the entire camp/perimeter for a surviving target.", "This ties into becoming accepted by the ore smelters."),
            reward = "",
            warnings = "",
            searchTags = listOf("Ingvar wants a sword.", "Ingvar", "Hammer Clan", "SAFE / SMITHING")
        ),
        Quest(
            id = "G3-P4-041",
            chapter = 4,
            playOrder = 41,
            title = "Approval from the ore smelters.",
            category = "SAFE / SMITHING",
            giver = "Ingvar / ore smelters",
            location = "Nordmar clans",
            prerequisites = "",
            summary = "Earn the approval of the required master smiths/smelters by completing their individual requests, then return to Ingvar.",
            walkthroughSteps = listOf("Begin with Ingvar / ore smelters. The quest belongs to Nordmar clans. In Nordmar, follow roads, bridges, clan paths and campfires whenever possible; direct cross-country travel is often slower because cliffs force long detours.", "Earn the approval of the required master smiths/smelters by completing their individual requests, then return to Ingvar.", "After the objective triggers, return to the named quest giver where applicable and exhaust the follow-up dialogue. For kill quests, if completion does not trigger, search the entire camp/perimeter for a surviving target.", "Do the component smith quests before expecting Ingvar to teach advanced forging."),
            reward = "",
            warnings = "",
            searchTags = listOf("Approval from the ore smelters.", "Ingvar / ore smelters", "Nordmar clans", "SAFE / SMITHING")
        ),
        Quest(
            id = "G3-P4-042",
            chapter = 4,
            playOrder = 42,
            title = "A shadowbeast horn for Pedar.",
            category = "SAFE",
            giver = "Pedar",
            location = "Hammer Clan region",
            prerequisites = "",
            summary = "Bring Pedar one Shadowbeast horn.",
            walkthroughSteps = listOf("Begin with Pedar. The quest belongs to Hammer Clan region. In Nordmar, follow roads, bridges, clan paths and campfires whenever possible; direct cross-country travel is often slower because cliffs force long detours.", "Bring Pedar one Shadowbeast horn.", "After the objective triggers, return to the named quest giver where applicable and exhaust the follow-up dialogue. For kill quests, if completion does not trigger, search the entire camp/perimeter for a surviving target.", "If you already hunted Shadowbeasts in Myrtana, keep a horn in reserve. 3. FIRE CLAN & ANCESTOR TOMBS Kerth's clan drives Nordmar's regional liberation and the six ancestor tombs. This section is best tackled after you know the clan routes and have strong cold-region combat gear."),
            reward = "",
            warnings = "",
            searchTags = listOf("A shadowbeast horn for Pedar.", "Pedar", "Hammer Clan region", "SAFE")
        ),
        Quest(
            id = "G3-P4-043",
            chapter = 4,
            playOrder = 43,
            title = "An ancestor stone for Rathgar.",
            category = "SAFE / ANCESTOR",
            giver = "Rathgar",
            location = "Fire Clan / ancestor tomb route",
            prerequisites = "",
            summary = "Speak with Rathgar about the ancestor stone and Kerth's mission. Obtain the correct stone for his assigned tomb.",
            walkthroughSteps = listOf("Begin with Rathgar. The quest belongs to Fire Clan / ancestor tomb route. In Nordmar, follow roads, bridges, clan paths and campfires whenever possible; direct cross-country travel is often slower because cliffs force long detours.", "Speak with Rathgar about the ancestor stone and Kerth's mission. Obtain the correct stone for his assigned tomb.", "After the objective triggers, return to the named quest giver where applicable and exhaust the follow-up dialogue. For kill quests, if completion does not trigger, search the entire camp/perimeter for a surviving target.", "Ancestor stones must be placed on the altar inside their matching tomb."),
            reward = "",
            warnings = "",
            searchTags = listOf("An ancestor stone for Rathgar.", "Rathgar", "Fire Clan / ancestor tomb route", "SAFE / ANCESTOR")
        ),
        Quest(
            id = "G3-P4-044",
            chapter = 4,
            playOrder = 44,
            title = "Accompany Rathgar to the cave tombs.",
            category = "SAFE / ESCORT",
            giver = "Rathgar",
            location = "Fire Clan tomb →",
            prerequisites = "",
            summary = "Follow Rathgar to the tomb area and protect him from wildlife and Orcs.",
            walkthroughSteps = listOf("Begin with Rathgar. The quest belongs to Fire Clan tomb. In Nordmar, follow roads, → bridges, clan paths and campfires whenever possible; direct cross-country travel is often slower because cliffs force long detours.", "Follow Rathgar to the tomb area and protect him from wildlife and Orcs.", "After the objective triggers, return to the named quest giver where applicable and exhaust the follow-up dialogue. For kill quests, if completion does not trigger, search the entire camp/perimeter for a surviving target.", "Use this as an introduction to the ancestor-tomb system."),
            reward = "",
            warnings = "",
            searchTags = listOf("Accompany Rathgar to the cave tombs.", "Rathgar", "Fire Clan tomb →", "SAFE / ESCORT")
        ),
        Quest(
            id = "G3-P4-045",
            chapter = 4,
            playOrder = 45,
            title = "Ejnar's helmet.",
            category = "SAFE / ANCESTOR",
            giver = "Fire Clan / tomb quest",
            location = "Ejnar's tomb",
            prerequisites = "",
            summary = "Search Ejnar's tomb and recover the unique helmet associated with the ancestor.",
            walkthroughSteps = listOf("Begin with Fire Clan / tomb quest. The quest belongs to Ejnar's tomb. In Nordmar, follow roads, bridges, clan paths and campfires whenever possible; direct cross-country travel is often slower because cliffs force long detours.", "Search Ejnar's tomb and recover the unique helmet associated with the ancestor.", "After the objective triggers, return to the named quest giver where applicable and exhaust the follow-up dialogue. For kill quests, if completion does not trigger, search the entire camp/perimeter for a surviving target.", "Do not leave the tomb after placing the stone; loot the unique equipment as well."),
            reward = "",
            warnings = "",
            searchTags = listOf("Ejnar's helmet.", "Fire Clan / tomb quest", "Ejnar's tomb", "SAFE / ANCESTOR")
        ),
        Quest(
            id = "G3-P4-046",
            chapter = 4,
            playOrder = 46,
            title = "Duel with Sivert.",
            category = "SAFE — DUEL",
            giver = "Sivert",
            location = "Fire Clan",
            prerequisites = "",
            summary = "Challenge Sivert and knock him down under non-lethal duel rules.",
            walkthroughSteps = listOf("Begin with Sivert. The quest belongs to Fire Clan. In Nordmar, follow roads, bridges, clan paths and campfires whenever possible; direct cross-country travel is often slower because cliffs force long detours.", "Challenge Sivert and knock him down under non-lethal duel rules.", "After the objective triggers, return to the named quest giver where applicable and exhaust the follow-up dialogue. For kill quests, if completion does not trigger, search the entire camp/perimeter for a surviving target.", "Safe clan reputation before the harder quests."),
            reward = "",
            warnings = "",
            searchTags = listOf("Duel with Sivert.", "Sivert", "Fire Clan", "SAFE — DUEL")
        ),
        Quest(
            id = "G3-P4-047",
            chapter = 4,
            playOrder = 47,
            title = "Hunting orcs with Kaelin.",
            category = "SAFE — NORDMAR LIBERATION",
            giver = "Kaelin",
            location = "Fire Clan Orc camp →",
            prerequisites = "",
            summary = "Follow Kaelin to the Orc camp west of the Fire Clan and fight alongside him.",
            walkthroughSteps = listOf("Begin with Kaelin. The quest belongs to Fire Clan Orc camp. In Nordmar, follow roads, → bridges, clan paths and campfires whenever possible; direct cross-country travel is often slower because cliffs force long detours.", "Follow Kaelin to the Orc camp west of the Fire Clan and fight alongside him.", "After the objective triggers, return to the named quest giver where applicable and exhaust the follow-up dialogue. For kill quests, if completion does not trigger, search the entire camp/perimeter for a surviving target.", "Keep Kaelin alive if possible."),
            reward = "",
            warnings = "",
            searchTags = listOf("Hunting orcs with Kaelin.", "Kaelin", "Fire Clan Orc camp →", "SAFE — NORDMAR LIBERATION")
        ),
        Quest(
            id = "G3-P4-048",
            chapter = 4,
            playOrder = 48,
            title = "Killing orcs!",
            category = "SAFE — NORDMAR LIBERATION",
            giver = "Kaelin",
            location = "Orc camp west of Fire Clan",
            prerequisites = "",
            summary = "Kill the entire designated Orc camp: warriors, scouts, shamans and elites until the quest completes.",
            walkthroughSteps = listOf("Begin with Kaelin. The quest belongs to Orc camp west of Fire Clan. In Nordmar, follow roads, bridges, clan paths and campfires whenever possible; direct cross-country travel is often slower because cliffs force long detours.", "Kill the entire designated Orc camp: warriors, scouts, shamans and elites until the quest completes.", "After the objective triggers, return to the named quest giver where applicable and exhaust the follow-up dialogue. For kill quests, if completion does not trigger, search the entire camp/perimeter for a surviving target.", "This camp contributes to freeing Nordmar."),
            reward = "",
            warnings = "",
            searchTags = listOf("Killing orcs!", "Kaelin", "Orc camp west of Fire Clan", "SAFE — NORDMAR LIBERATION")
        ),
        Quest(
            id = "G3-P4-049",
            chapter = 4,
            playOrder = 49,
            title = "Hunting with Leif.",
            category = "SAFE",
            giver = "Leif",
            location = "Fire Clan wilderness",
            prerequisites = "",
            summary = "Join Leif on his hunting trip and help kill the target animals.",
            walkthroughSteps = listOf("Begin with Leif. The quest belongs to Fire Clan wilderness. In Nordmar, follow roads, bridges, clan paths and campfires whenever possible; direct cross-country travel is often slower because cliffs force long detours.", "Join Leif on his hunting trip and help kill the target animals.", "After the objective triggers, return to the named quest giver where applicable and exhaust the follow-up dialogue. For kill quests, if completion does not trigger, search the entire camp/perimeter for a surviving target.", "His follow-up asks for sabertooth teeth."),
            reward = "",
            warnings = "",
            searchTags = listOf("Hunting with Leif.", "Leif", "Fire Clan wilderness", "SAFE")
        ),
        Quest(
            id = "G3-P4-050",
            chapter = 4,
            playOrder = 50,
            title = "Ten sabertooth teeth for Leif.",
            category = "SAFE",
            giver = "Leif",
            location = "Fire Clan",
            prerequisites = "",
            summary = "Collect ten sabertooth teeth and give them to Leif.",
            walkthroughSteps = listOf("Begin with Leif. The quest belongs to Fire Clan. In Nordmar, follow roads, bridges, clan paths and campfires whenever possible; direct cross-country travel is often slower because cliffs force long detours.", "Collect ten sabertooth teeth and give them to Leif.", "After the objective triggers, return to the named quest giver where applicable and exhaust the follow-up dialogue. For kill quests, if completion does not trigger, search the entire camp/perimeter for a surviving target.", "Learn the appropriate trophy skill before hunting if necessary."),
            reward = "",
            warnings = "",
            searchTags = listOf("Ten sabertooth teeth for Leif.", "Leif", "Fire Clan", "SAFE")
        ),
        Quest(
            id = "G3-P4-051",
            chapter = 4,
            playOrder = 51,
            title = "Armor for Thorald.",
            category = "SAFE",
            giver = "Thorald",
            location = "Fire Clan",
            prerequisites = "",
            summary = "Obtain the armor Thorald requests so he is properly equipped for later fighting.",
            walkthroughSteps = listOf("Begin with Thorald. The quest belongs to Fire Clan. In Nordmar, follow roads, bridges, clan paths and campfires whenever possible; direct cross-country travel is often slower because cliffs force long detours.", "Obtain the armor Thorald requests so he is properly equipped for later fighting.", "After the objective triggers, return to the named quest giver where applicable and exhaust the follow-up dialogue. For kill quests, if completion does not trigger, search the entire camp/perimeter for a surviving target.", "Thorald can assist with the Hammer Clan furnace liberation."),
            reward = "",
            warnings = "",
            searchTags = listOf("Armor for Thorald.", "Thorald", "Fire Clan", "SAFE")
        ),
        Quest(
            id = "G3-P4-052",
            chapter = 4,
            playOrder = 52,
            title = "A teleporter stone for Lee.",
            category = "SAFE / STORY CHARACTER",
            giver = "Lee",
            location = "Fire Clan",
            prerequisites = "",
            summary = "Find the Vengard teleport stone Lee requests and bring it to him.",
            walkthroughSteps = listOf("Begin with Lee. The quest belongs to Fire Clan. In Nordmar, follow roads, bridges, clan paths and campfires whenever possible; direct cross-country travel is often slower because cliffs force long detours.", "Find the Vengard teleport stone Lee requests and bring it to him.", "After the objective triggers, return to the named quest giver where applicable and exhaust the follow-up dialogue. For kill quests, if completion does not trigger, search the entire camp/perimeter for a surviving target.", "The stone is found in Fire Mage Karrypto's room above King Rhobar's throne room in Vengard."),
            reward = "",
            warnings = "",
            searchTags = listOf("A teleporter stone for Lee.", "Lee", "Fire Clan", "SAFE / STORY CHARACTER")
        ),
        Quest(
            id = "G3-P4-053",
            chapter = 4,
            playOrder = 53,
            title = "Raw materials for Kalan.",
            category = "SAFE / SMITHING",
            giver = "Kalan",
            location = "Fire Clan",
            prerequisites = "",
            summary = "Bring Kalan 30 pieces of raw steel and the required hammer so he will give his approval and offer smithing training.",
            walkthroughSteps = listOf("Begin with Kalan. The quest belongs to Fire Clan. In Nordmar, follow roads, bridges, clan paths and campfires whenever possible; direct cross-country travel is often slower because cliffs force long detours.", "Bring Kalan 30 pieces of raw steel and the required hammer so he will give his approval and offer smithing training.", "After the objective triggers, return to the named quest giver where applicable and exhaust the follow-up dialogue. For kill quests, if completion does not trigger, search the entire camp/perimeter for a surviving target.", "Part of the ore-smelter approval chain."),
            reward = "",
            warnings = "",
            searchTags = listOf("Raw materials for Kalan.", "Kalan", "Fire Clan", "SAFE / SMITHING")
        ),
        Quest(
            id = "G3-P4-054",
            chapter = 4,
            playOrder = 54,
            title = "The power of the ancestors.",
            category = "MAJOR / ANCESTOR",
            giver = "Kerth",
            location = "Fire Clan / all Nordmar",
            prerequisites = "",
            summary = "Kerth gives you the ancestor-tomb mission and a map. Recover the lost ancestor stones and place each one on the altar in its corresponding tomb. There are six tombs in total.",
            walkthroughSteps = listOf("Begin with Kerth. The quest belongs to Fire Clan / all Nordmar. In Nordmar, follow roads, bridges, clan paths and campfires whenever possible; direct cross-country travel is often slower because cliffs force long detours.", "Kerth gives you the ancestor-tomb mission and a map. Recover the lost ancestor stones and place each one on the altar in its corresponding tomb. There are six tombs in total.", "After the objective triggers, return to the named quest giver where applicable and exhaust the follow-up dialogue. For kill quests, if completion does not trigger, search the entire camp/perimeter for a surviving target.", "Mark completed tombs mentally/on your map; entrances are sometimes offset from the red cross on Kerth's map. ⚠ Progression warning: Make a manual save before committing. This quest can affect major regional or ending-related progression."),
            reward = "",
            warnings = "",
            searchTags = listOf("The power of the ancestors.", "Kerth", "Fire Clan / all Nordmar", "MAJOR / ANCESTOR")
        ),
        Quest(
            id = "G3-P4-055",
            chapter = 4,
            playOrder = 55,
            title = "Ejnar's tomb.",
            category = "SAFE / ANCESTOR",
            giver = "Kerth / ancestor quest",
            location = "Nordmar",
            prerequisites = "",
            summary = "Find Ejnar's tomb, clear the undead/hostile occupants, obtain the matching ancestor stone if needed and use it on the altar.",
            walkthroughSteps = listOf("Begin with Kerth / ancestor quest. The quest belongs to Nordmar. In Nordmar, follow roads, bridges, clan paths and campfires whenever possible; direct cross-country travel is often slower because cliffs force long detours.", "Find Ejnar's tomb, clear the undead/hostile occupants, obtain the matching ancestor stone if needed and use it on the altar.", "After the objective triggers, return to the named quest giver where applicable and exhaust the follow-up dialogue. For kill quests, if completion does not trigger, search the entire camp/perimeter for a surviving target.", "Search for Ejnar's unique helmet before leaving."),
            reward = "",
            warnings = "",
            searchTags = listOf("Ejnar's tomb.", "Kerth / ancestor quest", "Nordmar", "SAFE / ANCESTOR")
        ),
        Quest(
            id = "G3-P4-056",
            chapter = 4,
            playOrder = 56,
            title = "Angir's tomb.",
            category = "SAFE / ANCESTOR",
            giver = "Kerth / Osmund",
            location = "Nordmar",
            prerequisites = "",
            summary = "Locate Angir's tomb and speak with Osmund. Follow his Orc-related quest to recover the ancestor stone, clear the tomb and place the stone on the altar.",
            walkthroughSteps = listOf("Begin with Kerth / Osmund. The quest belongs to Nordmar. In Nordmar, follow roads, bridges, clan paths and campfires whenever possible; direct cross-country travel is often slower because cliffs force long detours.", "Locate Angir's tomb and speak with Osmund. Follow his Orc-related quest to recover the ancestor stone, clear the tomb and place the stone on the altar.", "After the objective triggers, return to the named quest giver where applicable and exhaust the follow-up dialogue. For kill quests, if completion does not trigger, search the entire camp/perimeter for a surviving target.", "The nearby Orc shaman carries the stone; kill and loot him."),
            reward = "",
            warnings = "",
            searchTags = listOf("Angir's tomb.", "Kerth / Osmund", "Nordmar", "SAFE / ANCESTOR")
        ),
        Quest(
            id = "G3-P4-057",
            chapter = 4,
            playOrder = 57,
            title = "Find the orc shamans.",
            category = "SAFE",
            giver = "Osmund / ancestor chain",
            location = "Near Angir's tomb",
            prerequisites = "",
            summary = "Follow Osmund or his directions to locate the Orc shamans who took the ancestor stone.",
            walkthroughSteps = listOf("Begin with Osmund / ancestor chain. The quest belongs to Near Angir's tomb. In Nordmar, follow roads, bridges, clan paths and campfires whenever possible; direct cross-country travel is often slower because cliffs force long detours.", "Follow Osmund or his directions to locate the Orc shamans who took the ancestor stone.", "After the objective triggers, return to the named quest giver where applicable and exhaust the follow-up dialogue. For kill quests, if completion does not trigger, search the entire camp/perimeter for a surviving target.", "Do not return to the tomb without looting the stone."),
            reward = "",
            warnings = "",
            searchTags = listOf("Find the orc shamans.", "Osmund / ancestor chain", "Near Angir's tomb", "SAFE")
        ),
        Quest(
            id = "G3-P4-058",
            chapter = 4,
            playOrder = 58,
            title = "Kill the orc shamans!",
            category = "SAFE",
            giver = "Osmund",
            location = "Near Angir's tomb",
            prerequisites = "",
            summary = "Kill the target Orc shamans and loot the ancestor stone from the relevant body.",
            walkthroughSteps = listOf("Begin with Osmund. The quest belongs to Near Angir's tomb. In Nordmar, follow roads, bridges, clan paths and campfires whenever possible; direct cross-country travel is often slower because cliffs force long detours.", "Kill the target Orc shamans and loot the ancestor stone from the relevant body.", "After the objective triggers, return to the named quest giver where applicable and exhaust the follow-up dialogue. For kill quests, if completion does not trigger, search the entire camp/perimeter for a surviving target.", "This directly enables Angir's tomb completion."),
            reward = "",
            warnings = "",
            searchTags = listOf("Kill the orc shamans!", "Osmund", "Near Angir's tomb", "SAFE")
        ),
        Quest(
            id = "G3-P4-059",
            chapter = 4,
            playOrder = 59,
            title = "Snorre's tomb.",
            category = "SAFE / ANCESTOR",
            giver = "Kerth",
            location = "Nordmar",
            prerequisites = "",
            summary = "Find Snorre's tomb, secure the matching ancestor stone and place it on the tomb altar after clearing enemies.",
            walkthroughSteps = listOf("Begin with Kerth. The quest belongs to Nordmar. In Nordmar, follow roads, bridges, clan paths and campfires whenever possible; direct cross-country travel is often slower because cliffs force long detours.", "Find Snorre's tomb, secure the matching ancestor stone and place it on the tomb altar after clearing enemies.", "After the objective triggers, return to the named quest giver where applicable and exhaust the follow-up dialogue. For kill quests, if completion does not trigger, search the entire camp/perimeter for a surviving target.", "Use Kerth's map but search around the marked mountain face for the actual entrance."),
            reward = "",
            warnings = "",
            searchTags = listOf("Snorre's tomb.", "Kerth", "Nordmar", "SAFE / ANCESTOR")
        ),
        Quest(
            id = "G3-P4-060",
            chapter = 4,
            playOrder = 60,
            title = "Berek's tomb.",
            category = "SAFE / ANCESTOR",
            giver = "Kerth",
            location = "Nordmar",
            prerequisites = "",
            summary = "Find Berek's tomb, clear it and place Berek's ancestor stone on the altar.",
            walkthroughSteps = listOf("Begin with Kerth. The quest belongs to Nordmar. In Nordmar, follow roads, bridges, clan paths and campfires whenever possible; direct cross-country travel is often slower because cliffs force long detours.", "Find Berek's tomb, clear it and place Berek's ancestor stone on the altar.", "After the objective triggers, return to the named quest giver where applicable and exhaust the follow-up dialogue. For kill quests, if completion does not trigger, search the entire camp/perimeter for a surviving target.", "Loot the tomb before leaving; ancestor tombs often contain valuable equipment."),
            reward = "",
            warnings = "",
            searchTags = listOf("Berek's tomb.", "Kerth", "Nordmar", "SAFE / ANCESTOR")
        ),
        Quest(
            id = "G3-P4-061",
            chapter = 4,
            playOrder = 61,
            title = "Akascha's ancestor stone.",
            category = "SAFE / ANCESTOR",
            giver = "Monastery / ancestor chain",
            location = "Nordmar",
            prerequisites = "",
            summary = "Recover Akascha's ancestor stone from the location/NPC associated with his tomb and keep it until the tomb is found.",
            walkthroughSteps = listOf("Begin with Monastery / ancestor chain. The quest belongs to Nordmar. In Nordmar, follow roads, bridges, clan paths and campfires whenever possible; direct cross-country travel is often slower because cliffs force long detours.", "Recover Akascha's ancestor stone from the location/NPC associated with his tomb and keep it until the tomb is found.", "After the objective triggers, return to the named quest giver where applicable and exhaust the follow-up dialogue. For kill quests, if completion does not trigger, search the entire camp/perimeter for a surviving target.", "The Monastery has a separate quest specifically helping locate Akascha's tomb."),
            reward = "",
            warnings = "",
            searchTags = listOf("Akascha's ancestor stone.", "Monastery / ancestor chain", "Nordmar", "SAFE / ANCESTOR")
        ),
        Quest(
            id = "G3-P4-062",
            chapter = 4,
            playOrder = 62,
            title = "Baldar's tomb.",
            category = "SAFE / ANCESTOR",
            giver = "Kerth",
            location = "Nordmar",
            prerequisites = "",
            summary = "Locate Baldar's tomb, clear the interior and place the correct ancestor stone on its altar.",
            walkthroughSteps = listOf("Begin with Kerth. The quest belongs to Nordmar. In Nordmar, follow roads, bridges, clan paths and campfires whenever possible; direct cross-country travel is often slower because cliffs force long detours.", "Locate Baldar's tomb, clear the interior and place the correct ancestor stone on its altar.", "After the objective triggers, return to the named quest giver where applicable and exhaust the follow-up dialogue. For kill quests, if completion does not trigger, search the entire camp/perimeter for a surviving target.", "One of the six tombs required for Kerth's Power of the Ancestors."),
            reward = "",
            warnings = "",
            searchTags = listOf("Baldar's tomb.", "Kerth", "Nordmar", "SAFE / ANCESTOR")
        ),
        Quest(
            id = "G3-P4-063",
            chapter = 4,
            playOrder = 63,
            title = "Liberate Nordmar!",
            category = "MAJOR",
            giver = "Kerth",
            location = "All Nordmar",
            prerequisites = "",
            summary = "After completing the ancestor-related progression, destroy all five major Orc camps and free the Hammer Clan ore furnace. Return to Kerth when the Orc military presence has been broken.",
            walkthroughSteps = listOf("Begin with Kerth. The quest belongs to All Nordmar. In Nordmar, follow roads, bridges, clan paths and campfires whenever possible; direct cross-country travel is often slower because cliffs force long detours.", "After completing the ancestor-related progression, destroy all five major Orc camps and free the Hammer Clan ore furnace. Return to Kerth when the Orc military presence has been broken.", "After the objective triggers, return to the named quest giver where applicable and exhaust the follow-up dialogue. For kill quests, if completion does not trigger, search the entire camp/perimeter for a surviving target.", "This is the regional capstone. Do not assume clearing only the furnace is enough. ⚠ Progression warning: Make a manual save before committing. This quest can affect major regional or ending-related progression."),
            reward = "",
            warnings = "",
            searchTags = listOf("Liberate Nordmar!", "Kerth", "All Nordmar", "MAJOR")
        ),
        Quest(
            id = "G3-P4-064",
            chapter = 4,
            playOrder = 64,
            title = "Orc camp wiped out!!! — Camp 1",
            category = "SAFE — LIBERATION",
            giver = "Regional objective",
            location = "Nordmar",
            prerequisites = "",
            summary = "Find one of the five major Orc camps marked by the Nordmar liberation route and kill enough Orcs for the camp-wiped-out message.",
            walkthroughSteps = listOf("Begin with Regional objective. The quest belongs to Nordmar. In Nordmar, follow roads, bridges, clan paths and campfires whenever possible; direct cross-country travel is often slower because cliffs force long detours.", "Find one of the five major Orc camps marked by the Nordmar liberation route and kill enough Orcs for the camp-wiped-out message.", "After the objective triggers, return to the named quest giver where applicable and exhaust the follow-up dialogue. For kill quests, if completion does not trigger, search the entire camp/perimeter for a surviving target.", "There are five separate objectives; keep track of which camps you have cleared."),
            reward = "",
            warnings = "",
            searchTags = listOf("Orc camp wiped out!!! — Camp 1", "Regional objective", "Nordmar", "SAFE — LIBERATION")
        ),
        Quest(
            id = "G3-P4-065",
            chapter = 4,
            playOrder = 65,
            title = "Orc camp wiped out!!! — Camp 2",
            category = "SAFE — LIBERATION",
            giver = "Regional objective",
            location = "Nordmar",
            prerequisites = "",
            summary = "Clear the second major Orc camp completely enough to trigger its objective.",
            walkthroughSteps = listOf("Begin with Regional objective. The quest belongs to Nordmar. In Nordmar, follow roads, bridges, clan paths and campfires whenever possible; direct cross-country travel is often slower because cliffs force long detours.", "Clear the second major Orc camp completely enough to trigger its objective.", "After the objective triggers, return to the named quest giver where applicable and exhaust the follow-up dialogue. For kill quests, if completion does not trigger, search the entire camp/perimeter for a surviving target.", "Loot shamans and leaders before leaving."),
            reward = "",
            warnings = "",
            searchTags = listOf("Orc camp wiped out!!! — Camp 2", "Regional objective", "Nordmar", "SAFE — LIBERATION")
        ),
        Quest(
            id = "G3-P4-066",
            chapter = 4,
            playOrder = 66,
            title = "Orc camp wiped out!!! — Camp 3",
            category = "SAFE — LIBERATION",
            giver = "Regional objective",
            location = "Nordmar",
            prerequisites = "",
            summary = "Destroy the third major Orc encampment.",
            walkthroughSteps = listOf("Begin with Regional objective. The quest belongs to Nordmar. In Nordmar, follow roads, bridges, clan paths and campfires whenever possible; direct cross-country travel is often slower because cliffs force long detours.", "Destroy the third major Orc encampment.", "After the objective triggers, return to the named quest giver where applicable and exhaust the follow-up dialogue. For kill quests, if completion does not trigger, search the entire camp/perimeter for a surviving target.", "Use clan warriors where a quest provides them rather than fighting every camp alone."),
            reward = "",
            warnings = "",
            searchTags = listOf("Orc camp wiped out!!! — Camp 3", "Regional objective", "Nordmar", "SAFE — LIBERATION")
        ),
        Quest(
            id = "G3-P4-067",
            chapter = 4,
            playOrder = 67,
            title = "Orc camp wiped out!!! — Camp 4",
            category = "SAFE — LIBERATION",
            giver = "Regional objective",
            location = "Nordmar",
            prerequisites = "",
            summary = "Destroy the fourth major Orc encampment.",
            walkthroughSteps = listOf("Begin with Regional objective. The quest belongs to Nordmar. In Nordmar, follow roads, bridges, clan paths and campfires whenever possible; direct cross-country travel is often slower because cliffs force long detours.", "Destroy the fourth major Orc encampment.", "After the objective triggers, return to the named quest giver where applicable and exhaust the follow-up dialogue. For kill quests, if completion does not trigger, search the entire camp/perimeter for a surviving target.", "Save before large camp assaults; multiple shamans can be dangerous."),
            reward = "",
            warnings = "",
            searchTags = listOf("Orc camp wiped out!!! — Camp 4", "Regional objective", "Nordmar", "SAFE — LIBERATION")
        ),
        Quest(
            id = "G3-P4-068",
            chapter = 4,
            playOrder = 68,
            title = "Orc camp wiped out!!! — Camp 5",
            category = "SAFE — LIBERATION",
            giver = "Regional objective",
            location = "Nordmar",
            prerequisites = "",
            summary = "Destroy the fifth and final major Orc camp.",
            walkthroughSteps = listOf("Begin with Regional objective. The quest belongs to Nordmar. In Nordmar, follow roads, bridges, clan paths and campfires whenever possible; direct cross-country travel is often slower because cliffs force long detours.", "Destroy the fifth and final major Orc camp.", "After the objective triggers, return to the named quest giver where applicable and exhaust the follow-up dialogue. For kill quests, if completion does not trigger, search the entire camp/perimeter for a surviving target.", "Together with freeing the furnace, this satisfies the military side of Liberate Nordmar. 4. MONASTERY The Monastery is a small but story-important hub. It connects the Fire Chalice storyline, Akascha's tomb and Fire Mage lore."),
            reward = "",
            warnings = "",
            searchTags = listOf("Orc camp wiped out!!! — Camp 5", "Regional objective", "Nordmar", "SAFE — LIBERATION")
        ),
        Quest(
            id = "G3-P4-069",
            chapter = 4,
            playOrder = 69,
            title = "Find Akascha's tomb!",
            category = "SAFE / ANCESTOR",
            giver = "Monastery quest giver",
            location = "Monastery Nordmar →",
            prerequisites = "",
            summary = "Use the Monastery's information to locate Akascha's tomb and continue the ancestor￾stone objective there.",
            walkthroughSteps = listOf("Begin with Monastery quest giver. The quest belongs to Monastery Nordmar. In → Nordmar, follow roads, bridges, clan paths and campfires whenever possible; direct cross-country travel is often slower because cliffs force long detours.", "Use the Monastery's information to locate Akascha's tomb and continue the ancestor-stone objective there.", "After the objective triggers, return to the named quest giver where applicable and exhaust the follow-up dialogue. For kill quests, if completion does not trigger, search the entire camp/perimeter for a surviving target.", "This is part of the six-tomb circuit."),
            reward = "",
            warnings = "",
            searchTags = listOf("Find Akascha's tomb!", "Monastery quest giver", "Monastery Nordmar →", "SAFE / ANCESTOR")
        ),
        Quest(
            id = "G3-P4-070",
            chapter = 4,
            playOrder = 70,
            title = "Mana potions for Pyran.",
            category = "SAFE",
            giver = "Pyran",
            location = "Monastery",
            prerequisites = "",
            summary = "Bring Pyran the requested mana potions.",
            walkthroughSteps = listOf("Begin with Pyran. The quest belongs to Monastery. In Nordmar, follow roads, bridges, clan paths and campfires whenever possible; direct cross-country travel is often slower because cliffs force long detours.", "Bring Pyran the requested mana potions.", "After the objective triggers, return to the named quest giver where applicable and exhaust the follow-up dialogue. For kill quests, if completion does not trigger, search the entire camp/perimeter for a surviving target.", "Easy Monastery quest; complete before using/selling excess mana potions."),
            reward = "",
            warnings = "",
            searchTags = listOf("Mana potions for Pyran.", "Pyran", "Monastery", "SAFE")
        ),
        Quest(
            id = "G3-P4-071",
            chapter = 4,
            playOrder = 71,
            title = "Mana plants for the monastery.",
            category = "SAFE",
            giver = "Monastery mage",
            location = "Monastery",
            prerequisites = "",
            summary = "Collect the requested mana plants and deliver them to the Monastery.",
            walkthroughSteps = listOf("Begin with Monastery mage. The quest belongs to Monastery. In Nordmar, follow roads, bridges, clan paths and campfires whenever possible; direct cross-country travel is often slower because cliffs force long detours.", "Collect the requested mana plants and deliver them to the Monastery.", "After the objective triggers, return to the named quest giver where applicable and exhaust the follow-up dialogue. For kill quests, if completion does not trigger, search the entire camp/perimeter for a surviving target.", "Search around snowy slopes and paths while doing the tomb circuit."),
            reward = "",
            warnings = "",
            searchTags = listOf("Mana plants for the monastery.", "Monastery mage", "Monastery", "SAFE")
        ),
        Quest(
            id = "G3-P4-072",
            chapter = 4,
            playOrder = 72,
            title = "Bring Aidan the secret of the druids.",
            category = "SAFE / LORE",
            giver = "Aidan",
            location = "Monastery",
            prerequisites = "",
            summary = "Obtain the Druid knowledge/secret required by Aidan through the relevant Druid quest line and report it to him.",
            walkthroughSteps = listOf("Begin with Aidan. The quest belongs to Monastery. In Nordmar, follow roads, bridges, clan paths and campfires whenever possible; direct cross-country travel is often slower because cliffs force long detours.", "Obtain the Druid knowledge/secret required by Aidan through the relevant Druid quest line and report it to him.", "After the objective triggers, return to the named quest giver where applicable and exhaust the follow-up dialogue. For kill quests, if completion does not trigger, search the entire camp/perimeter for a surviving target.", "This connects Nordmar's Fire Mages with the Druid storyline from Myrtana. 5. XARDAS & THE ORE FURNACE — STORY CONNECTION Finding Xardas is not the same as choosing his ending. Graypelt can guide you to Xardas's tower, where the main story surrounding the five Artifacts of Adanos develops. If you later choose Xardas's path, he orders you to destroy all five artifacts in the Hammer Clan's ore furnace. Return to the already￾liberated mine, reach the furnace and use it with all five artifacts in your possession. This is an endgame commitment and should be preceded by a dedicated save. The five artifacts are the Amulet of Adanos, the Crown of Adanos, two Rings of Adanos and the Robe of Adanos. The furnace objective is separate from “Free the furnace”; liberation only makes the site usable/safe for the later story decision. PART IV — COMPLETION CHECKLIST  Finish all 19 Wolf Clan quests.  Finish all 22 Hammer Clan quests and liberate the ore furnace.  Finish the Fire Clan's local quests and Kerth's six-tomb ancestor quest.  Clear all five major Orc camps.  Finish the four Monastery quests.  Return to Kerth to complete the regional liberation when its requirements are satisfied.  Keep the Xardas artifact-destruction decision for the endgame; do not trigger it merely because you have access to the furnace. Quest catalogue coverage in this document: 72 Nordmar entries (1 global + 19 Wolf Clan + 22 Hammer Clan + 26 Fire Clan + 4 Monastery). APP DATA NOTES For the Android app, ancestor tombs should receive a dedicated quest-group ID so the six tomb entries can show shared progress beneath “The power of the ancestors.” Likewise, the five Orc-camp objectives should display as five checkboxes beneath “Liberate Nordmar!” while remaining searchable as individual quests. SOURCE & VERIFICATION NOTES Quest coverage and English titles were cross-checked against the current Steam Gothic 3 quest catalogue. Specific mechanics—including the six ancestor tombs, Hammer Clan furnace liberation, Mort's Fire Clan escort, the bridge Orc count and Xardas's use of the ore furnace—were cross-checked against World of Gothic, Gamepressure and established GameFAQs walkthrough material.  Steam Community — Gothic 3 - Quests, Nordmar quest index.  World of Gothic — individual Gothic 3 quest database entries.  Gamepressure — Gothic 3 Nordmar / Fire Clan walkthrough.  GameFAQs — Gothic 3 walkthroughs by GeorgeKI and N3Burgener."),
            reward = "",
            warnings = "",
            searchTags = listOf("Bring Aidan the secret of the druids.", "Aidan", "Monastery", "SAFE / LORE")
        ),
    )
}
