package com.sliverzfx.gothicquest

internal object Gothic3Part5Data {
    val quests = listOf(
        Quest(
            id = "G3-P5-001",
            chapter = 5,
            playOrder = 1,
            title = "Talk to Nafalem.",
            category = "SAFE",
            giver = "Nafalem",
            location = "Braga",
            prerequisites = "Reach Braga and speak with Hashishin leader Nafalem.",
            summary = "Find Nafalem, Braga's Hashishin leader, and exhaust his dialogue about the town, tribute and Nomad threat.",
            walkthroughSteps = listOf("Enter Braga and speak to Hashishin leader Nafalem near his residence.", "Ask about the tribute collection and the Nomad problem.", "Begin Tribute from Braga, then talk with Tufail and the debtors he identifies.", "Resolve the town's neutral tasks before choosing Asaru's Nomads or Nafalem's Hashishin."),
            reward = "Unlocks the tribute and nomad bounty questlines centered on Braga.",
            warnings = "Nafalem's conversation is the setup for several quests, not a stand-alone 1,000-XP journal mission.",
            searchTags = listOf("Talk to Nafalem.", "Nafalem", "Braga", "SAFE")
        ),
        Quest(
            id = "G3-P5-002",
            chapter = 5,
            playOrder = 2,
            title = "The tribute from Braga.",
            category = "SAFE / COLLECTION",
            giver = "Nafalem",
            location = "Braga",
            prerequisites = "Speak with Nafalem about collecting Braga's unpaid tribute.",
            summary = "Collect the outstanding tribute payments and goods from the people Nafalem names, then return to him with the required total.",
            walkthroughSteps = listOf("Speak to Nafalem and learn which Braga debtors owe tribute.", "Ask Tufail for leads on the missing tribute, then approach Bernado, Jose, Luca and Abbas.", "Do each debtor's related task before returning to Nafalem with the proceeds.", "Finish the full report to receive Hashishin and local Braga reputation."),
            reward = "1,500 XP, +10 Hashishin reputation and +15 Braga reputation.",
            warnings = "Bernado must be DEFEATED rather than killed; Luca needs the dark snapper skin first. Nomad/Hashishin choices affect which tasks remain.",
            searchTags = listOf("The tribute from Braga.", "Nafalem", "Braga", "SAFE / COLLECTION")
        ),
        Quest(
            id = "G3-P5-003",
            chapter = 5,
            playOrder = 3,
            title = "Bernado's tribute.",
            category = "SAFE",
            giver = "Bernado (tribute debtor); Nafalem commissions collection",
            location = "Braga",
            prerequisites = "Start Nafalem's tribute collection and ask Bernado to pay.",
            summary = "Speak with Bernado about the tribute he owes and obtain the required payment for Nafalem.",
            walkthroughSteps = listOf("Find Bernado in Braga after accepting Nafalem's collection task.", "Demand the outstanding tribute. Bernado refuses to pay a second time.", "Beat Bernado nonlethally, then take the payment and report the outcome."),
            reward = "1,000 XP and +5 Braga reputation.",
            warnings = "Do NOT kill Bernado; you need him alive to complete the tribute safely.",
            searchTags = listOf("Bernado's tribute.", "Bernado / Nafalem", "Braga", "SAFE")
        ),
        Quest(
            id = "G3-P5-004",
            chapter = 5,
            playOrder = 4,
            title = "Jose's tribute.",
            category = "SAFE",
            giver = "Jose",
            location = "Braga",
            prerequisites = "Start Nafalem's Braga tribute quest and talk to Jose.",
            summary = "Collect Jose's share of Braga's tribute and keep it for the final hand-in to Nafalem.",
            walkthroughSteps = listOf("Ask bounty hunter Jose about his unpaid Braga tribute after starting Nafalem's collection.", "Jose hands over his share without demanding another service.", "Ask him about the bounty contract for Asaru, Malir and Taklar, then return to Nafalem."),
            reward = "500 XP and +5 Braga reputation; opens Jose's bounty-hunting lead.",
            warnings = "",
            searchTags = listOf("Jose's tribute.", "Jose / Nafalem", "Braga", "SAFE")
        ),
        Quest(
            id = "G3-P5-005",
            chapter = 5,
            playOrder = 5,
            title = "Luca's tribute.",
            category = "SAFE",
            giver = "Luca (tribute debtor); Nafalem commissions collection",
            location = "Braga",
            prerequisites = "Accept Nafalem's tribute task and speak with Luca about his missing goods.",
            summary = "Obtain Luca's contribution to the tribute and return it as part of Nafalem's collection.",
            walkthroughSteps = listOf("Ask Luca to pay his tribute in Braga.", "Luca will pay after you bring the dark snapper skin he wants.", "Hunt a dark snapper and obtain its skin, then return to Luca.", "Collect the tribute and report to Nafalem."),
            reward = "500 XP and +5 Braga reputation for Luca's tribute; separate hunting rewards may apply.",
            warnings = "",
            searchTags = listOf("Luca's tribute.", "Luca / Nafalem", "Braga", "SAFE")
        ),
        Quest(
            id = "G3-P5-006",
            chapter = 5,
            playOrder = 6,
            title = "Abbas's tribute.",
            category = "SAFE",
            giver = "Abbas (water trader in Braga)",
            location = "Braga",
            prerequisites = "Investigate Nafalem's tribute and Abbas's lost water-vendor chalice.",
            summary = "Collect the tribute demanded from Abbas and include it in Nafalem's total.",
            walkthroughSteps = listOf("Find Abbas and ask why his tribute has not been delivered.", "Follow Tufail to the bandits who stole the water vendors' chalice.", "Clear the bandit cave and open their chest to recover the chalice.", "Bring the chalice back to Abbas, then finish Nafalem's tribute report."),
            reward = "1,500 XP and +5 Braga reputation for recovering Abbas's water-vendor chalice.",
            warnings = "The WATER VENDORS' CHALICE is not one of the twelve magical Fire Chalices. Do not confuse the two items.",
            searchTags = listOf("Abbas's tribute.", "Abbas / Nafalem", "Braga", "SAFE")
        ),
        Quest(
            id = "G3-P5-007",
            chapter = 5,
            playOrder = 7,
            title = "The dark snapper hunt.",
            category = "SAFE / HUNT",
            giver = "Luca (Braga leather merchant)",
            location = "Desert around Braga",
            prerequisites = "Speak with Luca when collecting Braga's tribute.",
            summary = "Track the designated dark snappers outside Braga and kill the full group. Return to the hunter when the objective message appears.",
            walkthroughSteps = listOf("Ask Luca about his tribute; he asks for dark snapper hides for an armor.", "Go north of Braga toward the ruins, where dark snappers roam; Diego can help with the hunt.", "Learn skinning if needed and collect FIVE dark snapper hides.", "Bring five hides to Luca, then collect his tribute for Nafalem."),
            reward = "1,000 XP for Dark Snapper Leather; Luca's tribute is a separate 500 XP and +5 Braga reputation.",
            warnings = "FIVE DARK SNAPPER skins, not merely killing a pack.",
            searchTags = listOf("The dark snapper hunt.", "Braga hunter", "Desert around Braga", "SAFE / HUNT")
        ),
        Quest(
            id = "G3-P5-008",
            chapter = 5,
            playOrder = 8,
            title = "Hunt with Diego near Braga",
            category = "SAFE / HUNT",
            giver = "Diego",
            location = "Braga wilderness",
            prerequisites = "",
            summary = "Join or assist the hunter with the dangerous beasts around Braga and kill the designated targets.",
            walkthroughSteps = listOf("Find Diego near Braga and ask him to help hunt dark snappers.", "Follow Diego into the ruins north of Braga.", "Defeat the dark snappers and extract their hides if you are completing Luca's tribute quest.", "Finish Diego's hunting dialogue and return five hides to Luca if required."),
            reward = "",
            warnings = "Tied to Diego's outdoor hunt and Luca's five-skin requirement; the old generic 'desert beasts' title was imprecise.",
            searchTags = listOf("Hunt the dangerous desert beasts.", "Diego / Braga hunter chain", "Braga wilderness", "SAFE / HUNT")
        ),
        Quest(
            id = "G3-P5-009",
            chapter = 5,
            playOrder = 9,
            title = "Follow Diego into the desert.",
            category = "SAFE / ESCORT",
            giver = "Diego",
            location = "Braga → desert",
            prerequisites = "",
            summary = "Accompany Diego on his route outside Braga and stay close while he leads you to the hunting/objective area.",
            walkthroughSteps = listOf("Talk to Diego near the Braga approach and ask him to guide you into the desert.", "Follow his route without sprinting out of escort distance.", "Deal with dark snappers or other enemies on the way.", "Speak to Diego at his stopping point to complete the guidance."),
            reward = "",
            warnings = "Do not confuse Diego's introductory escort with Luca's separate five-dark-snapper-hide delivery.",
            searchTags = listOf("Follow Diego into the desert.", "Diego", "Braga → desert", "SAFE / ESCORT")
        ),
        Quest(
            id = "G3-P5-010",
            chapter = 5,
            playOrder = 10,
            title = "Aila.",
            category = "CHOICE",
            giver = "Nafalem / Jose (Aila's fate)",
            location = "Braga / Nomad area",
            prerequisites = "Travel from Braga to Asaru's Nomad cave and find Aila.",
            summary = "Investigate Aila's disappearance/capture and locate her through the Nomad-related quest chain.",
            walkthroughSteps = listOf("Ask Nafalem or Jose about missing Aila.", "Find Aila at Asaru's hidden Nomad camp near Braga.", "Choose to escort her to Braga after helping Asaru's deception, or fight the Nomads for a hostile recovery route.", "Take Aila to the agreed destination and report to the faction contact."),
            reward = "1,500 XP and +15 Braga reputation for the completed Aila return route.",
            warnings = "Two routes exist, Nomad DECEPTION and Hashishin VIOLENCE. Killing Asaru blocks his peaceful Nomad quests.",
            searchTags = listOf("Aila.", "Nafalem / Braga quest chain", "Braga / Nomad area", "CHOICE")
        ),
        Quest(
            id = "G3-P5-011",
            chapter = 5,
            playOrder = 11,
            title = "Bring Aila back to Braga.",
            category = "CHOICE — HASHISHIN",
            giver = "Aila",
            location = "Nomad camp → Braga",
            prerequisites = "Find Aila in Asaru's camp and choose the Hashishin return or Nomad trick route.",
            summary = "If choosing the Braga/Hashishin resolution, escort Aila safely back to Braga and deliver her to the appropriate NPC.",
            walkthroughSteps = listOf("Find Asaru's Nomad hideout in the caves around Braga; Aila is staying with his people.", "Speak with Asaru before deciding how to resolve the dispute.", "For the peaceful Nomad trick, agree to return Aila as part of Asaru's plan; alternatively defeat the Nomads to take her by force.", "Escort Aila back to Braga, protect her from wildlife and report to Nafalem or Jose."),
            reward = "1,500 XP and +15 Braga reputation on completing Aila's return.",
            warnings = "The nonviolent deception route preserves Asaru and his Nomad quests; killing Asaru forfeits them.",
            searchTags = listOf("Bring Aila back to Braga.", "Aila / Nafalem", "Nomad camp → Braga", "CHOICE — HASHISHIN")
        ),
        Quest(
            id = "G3-P5-012",
            chapter = 5,
            playOrder = 12,
            title = "Bounty Hunting: Braga",
            category = "DEFER — HASHISHIN PATH",
            giver = "Jose",
            location = "Braga region",
            prerequisites = "Accept Jose/Nafalem's anti-Nomad contracts around Braga.",
            summary = "Locate the Nomad group threatening Braga and eliminate its members, then report to Nafalem.",
            walkthroughSteps = listOf("Ask bounty hunter Jose in Braga for the wanted Nomad leaders.", "The three named targets are Asaru, Malir and Taklar.", "Locate Asaru in his hidden Nomad cave, Malir in another nearby cave and Taklar among the ruins north of Braga.", "On the Hashishin route, defeat all three groups and report the bounty to Jose."),
            reward = "1,500 XP and +5 Braga reputation for the complete bounty; separate target rewards also apply.",
            warnings = "Killing Asaru prevents his Nomad-friendly Aila return and the preparations to liberate Braga.",
            searchTags = listOf("Eliminate the nomads near Braga.", "Nafalem", "Braga region", "DEFER — HASHISHIN PATH")
        ),
        Quest(
            id = "G3-P5-013",
            chapter = 5,
            playOrder = 13,
            title = "Preparations for the Liberation of Braga",
            category = "DEFER — NOMAD PATH",
            giver = "Marus (Asaru's Nomad companion)",
            location = "Braga region",
            prerequisites = "Find Asaru's hidden camp and complete Nomad-friendly work before attacking Braga.",
            summary = "If supporting the Nomads, complete their preparation and attack/undermine the Hashishin position at Braga as directed.",
            walkthroughSteps = listOf("Find Asaru's Nomad group near Braga and choose to support their campaign.", "Speak with his ally Marus about what the Nomads need to raid the town.", "Bring THREE Weapon Bundles; Bernado's stock in Braga can supply them.", "Hand the bundles to Marus and proceed with the Nomad plan."),
            reward = "1,500 XP and +5 Nomads reputation.",
            warnings = "This contradicts Jose and Nafalem's bounty missions; do not kill Asaru or Marus before preparing the liberation.",
            searchTags = listOf("Help the nomads against Braga.", "Nomad leader", "Braga region", "DEFER — NOMAD PATH")
        ),
        Quest(
            id = "G3-P5-014",
            chapter = 5,
            playOrder = 14,
            title = "The Ruin Fields of Braga",
            category = "SAFE",
            giver = "Ayitos (Asaru's Nomads)",
            location = "Braga",
            prerequisites = "Find Asaru's Nomad camp and talk to Ayitos about securing the ruins.",
            summary = "Clear the jackal- and bandit-infested ruins north of Braga for Ayitos and Asaru's Nomads.",
            walkthroughSteps = listOf("Find Ayitos among Asaru's Nomads.", "He asks you to clear the ruins outside Braga for the Nomad gathering.", "Travel to the ruins north of Braga, kill the jackals and Taklar's bandits.", "Tell Ayitos when the area is safe."),
            reward = "1,500 XP and +5 Nomads reputation.",
            warnings = "This is the ruin-clearance quest, not the unrelated Bakaresh quest titled A Lesson in Hospitality.",
            searchTags = listOf("A lesson in hospitality.", "Braga quest chain", "Braga", "SAFE")
        ),
        Quest(
            id = "G3-P5-015",
            chapter = 5,
            playOrder = 15,
            title = "A Job for Sancho",
            category = "SAFE",
            giver = "Navaras (Ben Erai mine entrance guard)",
            location = "Ben Erai",
            prerequisites = "Enter Ben Erai and speak to Navaras at the mine entrance.",
            summary = "Report to Sancho within Navaras's two-day deadline to begin work in the Ben Erai mine.",
            walkthroughSteps = listOf("At Ben Erai, talk to Navaras guarding the mine entrance.", "He orders you to report to overseer Sancho and obtain an assignment.", "Find Sancho inside the settlement and speak with him within TWO in-game days."),
            reward = "500 XP.",
            warnings = "Two-day deadline according to the classic guide; the old 'Talk to Sancho' record omitted Navaras and the timed requirement.",
            searchTags = listOf("Talk to Sancho.", "Sancho", "Ben Erai", "SAFE")
        ),
        Quest(
            id = "G3-P5-016",
            chapter = 5,
            playOrder = 16,
            title = "The Tunnel of Lago",
            category = "SAFE",
            giver = "Sancho",
            location = "Ben Erai mines",
            prerequisites = "Complete the initial Ben Erai job interview with Sancho.",
            summary = "Investigate why Lago's gold mine has stopped sending shipments, then report Fabio's explanation to Sancho.",
            walkthroughSteps = listOf("Speak with Sancho about the lack of gold shipments from Lago.", "Travel to Lago and find its ruler Fabio.", "Question Fabio about the closed mine/tunnel and missing transports.", "Return to Sancho with the report; this leads to Slaves for Lago."),
            reward = "1,000 XP and +5 Ben Erai reputation.",
            warnings = "The genuine task is checking Lago's tunnel with Fabio, not collecting arbitrary mine status updates.",
            searchTags = listOf("Report from the mines.", "Sancho / mine overseers", "Ben Erai mines", "SAFE")
        ),
        Quest(
            id = "G3-P5-017",
            chapter = 5,
            playOrder = 17,
            title = "Lukar Had Better Get Out!",
            category = "SAFE",
            giver = "Sancho",
            location = "Ben Erai",
            prerequisites = "Learn about Lukar's plans in Ben Erai and speak to Sancho.",
            summary = "Expose trader Lukar's plans to Sancho, then decide whether to kill him for the Hashishin.",
            walkthroughSteps = listOf("Speak to shady trader Lukar about his plans for Ben Erai.", "Report Lukar's plans to Sancho.", "Sancho orders Lukar removed; choosing this outcome requires killing him.", "Confirm the result with Sancho."),
            reward = "1,000 XP and +10 Ben Erai reputation.",
            warnings = "The earlier 'Lukar needs ore' task is not corroborated in the base-game quest guide. Killing Lukar forfeits his possible support during Ben Erai's liberation.",
            searchTags = listOf("Lukar needs ore.", "Lukar", "Ben Erai", "SAFE")
        ),
        Quest(
            id = "G3-P5-018",
            chapter = 5,
            playOrder = 18,
            title = "Ten Cactus Flowers",
            category = "SAFE / DELIVERY",
            giver = "Eusebio (Ben Erai alchemist)",
            location = "Ben Erai mine",
            prerequisites = "Speak to Eusebio the alchemist in Ben Erai.",
            summary = "Collect ten cactus flowers for alchemist Eusebio in Ben Erai.",
            walkthroughSteps = listOf("Find alchemist Eusebio in Ben Erai and ask for a simple gathering job.", "Collect TEN cactus flowers from the shrubs in and around Ben Erai.", "Bring all ten to Eusebio and ask about further alchemy work."),
            reward = "1,000 XP, +5 Ben Erai reputation and +1 Alchemy.",
            warnings = "The old 'Mine Workers Need Food' record had no matching documented quest; this is the real herb delivery from Eusebio.",
            searchTags = listOf("The mine workers need food.", "Mine overseer", "Ben Erai mine", "SAFE / DELIVERY")
        ),
        Quest(
            id = "G3-P5-019",
            chapter = 5,
            playOrder = 19,
            title = "Talk to Vasco",
            category = "SAFE / DELIVERY",
            giver = "Sancho",
            location = "Ben Erai mine",
            prerequisites = "Speak with Sancho and ask who needs to receive his message.",
            summary = "Deliver Sancho's message to Vasco inside Ben Erai.",
            walkthroughSteps = listOf("Speak with Sancho about contacts in Ben Erai.", "He asks you to take a message or report to Vasco.", "Find Vasco in Ben Erai and speak to him.", "Return to Sancho if his follow-up dialogue becomes available."),
            reward = "250 XP.",
            warnings = "This is a messenger quest; the old 'Bring Water to the Mine' objective is not corroborated.",
            searchTags = listOf("Bring water to the mine.", "Ben Erai mine quest giver", "Ben Erai mine", "SAFE / DELIVERY")
        ),
        Quest(
            id = "G3-P5-020",
            chapter = 5,
            playOrder = 20,
            title = "The Way to Gold",
            category = "CHOICE",
            giver = "Eusebio (Ben Erai alchemist)",
            location = "Ben Erai",
            prerequisites = "Ask Eusebio in Ben Erai about the gold trade.",
            summary = "Expose Eusebio's proposal to rob Sancho's gold chests.",
            walkthroughSteps = listOf("Ask Eusebio about Sancho's valuable gold chests.", "Eusebio proposes robbing the chests.", "Instead of attempting a generic mine-worker task, report Eusebio's proposal to Sancho.", "Resolve Sancho's dialogue on the attempted theft."),
            reward = "1,500 XP.",
            warnings = "Faction-sensitive thief-or-report dialogue. No separate 'Exhausted Slaves' quest was found in the classic Ben Erai index.",
            searchTags = listOf("The exhausted slaves.", "Ben Erai overseer", "Ben Erai", "CHOICE")
        ),
        Quest(
            id = "G3-P5-021",
            chapter = 5,
            playOrder = 21,
            title = "Slaves for Lago",
            category = "CHOICE — HASHISHIN",
            giver = "Sancho",
            location = "Ben Erai",
            prerequisites = "Complete Sancho's The Tunnel of Lago investigation.",
            summary = "Escort an emaciated slave and other captive workers from Ben Erai to reopen Lago's mine.",
            walkthroughSteps = listOf("Complete The Tunnel of Lago by investigating Fabio's gold mine.", "Ask Sancho how to restart the mining operation in Lago.", "Find the emaciated slave in Ben Erai and order him to bring his group to Lago.", "Escort the group all the way to Lago; protect the enslaved workers so they survive.", "At the mine, tell the workers to begin work and report success."),
            reward = "1,500 XP and +20 Ben Erai reputation.",
            warnings = "The captive escort is a faction-specific slavery quest. The old generic new-slave objective omitted the required earlier Tunnel of Lago task.",
            searchTags = listOf("A new slave for the mine.", "Ben Erai quest chain", "Ben Erai", "CHOICE — HASHISHIN")
        ),
        Quest(
            id = "G3-P5-022",
            chapter = 5,
            playOrder = 22,
            title = "Crawler Hunt",
            category = "SAFE",
            giver = "Vasco",
            location = "Ben Erai mine",
            prerequisites = "Ask Vasco about the dangerous crawlers near Ben Erai.",
            summary = "Clear Vasco's cave of twelve tough sandcrawlers outside Ben Erai.",
            walkthroughSteps = listOf("Find Vasco in Ben Erai and ask about dangerous crawlers.", "Travel to the nearby cave where the colony lives.", "Kill TWELVE TOUGH SANDCRAWLERS; additional ordinary crawlers may also inhabit the cave.", "Return to Vasco after the colony is cleared."),
            reward = "1,000 XP and +15 Ben Erai reputation.",
            warnings = "The completion condition is 12 tough sandcrawlers, not an unspecified enemy somewhere in the mine.",
            searchTags = listOf("The tunnel is blocked.", "Mine overseer", "Ben Erai mine", "SAFE")
        ),
        Quest(
            id = "G3-P5-023",
            chapter = 5,
            playOrder = 23,
            title = "Ten Gold Nuggets (Unverified Ghost Quest)",
            category = "GUIDE — UNVERIFIED",
            giver = "Unverified automatic/mining trigger",
            location = "Ben Erai mine",
            prerequisites = "Ben Erai gold mine access. Journal trigger is not verified.",
            summary = "Unverified historical mining quest; the classic guide could not locate a quest giver.",
            walkthroughSteps = listOf("The classic Gothic 3 guide describes an apparent ghost quest for ten gold nuggets, with no known character offering it.", "After gaining access to the Ben Erai mine, gather ten gold nuggets if your installed version allows it.", "Check your quest log for an actual triggered task. If no entry appears, do not assume mining ten nuggets will create a mission."),
            reward = "Historical guide suggests 2,500 XP but could not verify the quest's trigger.",
            warnings = "GHOST QUEST: this entry was previously a duplicate generic 'crawlers' hunt. The classic guide itself could not find the gold-nugget quest giver.",
            searchTags = listOf("Crawlers in the mine.", "Ben Erai miner", "Ben Erai mine", "SAFE")
        ),
        Quest(
            id = "G3-P5-024",
            chapter = 5,
            playOrder = 24,
            title = "Bounty Hunting: Hurit",
            category = "SAFE",
            giver = "Campa (Ben Erai bounty hunter)",
            location = "Oasis/river area",
            prerequisites = "Accept Campa's Ben Erai bounty list.",
            summary = "Fulfill Campa's bounty against Nomad leader Hurit after resolving any desired Sugut cooperation.",
            walkthroughSteps = listOf("Accept Campa's Ben Erai bounty list.", "Find Nomad leader Hurit in the desert to the north.", "If you want Hurit's help against Sugut, resolve that separate quest before attacking him.", "On the Hashishin route, defeat Hurit and his companions and confirm the bounty."),
            reward = "1,000 XP and +15 Ben Erai reputation.",
            warnings = "Hurit can help against Sugut; the old generic 'Lurkers' quest did not match a documented Ben Erai mission.",
            searchTags = listOf("Hunt the lurkers near Ben Erai.", "Ben Erai hunter", "Oasis/river area", "SAFE")
        ),
        Quest(
            id = "G3-P5-025",
            chapter = 5,
            playOrder = 25,
            title = "Dirty Doings",
            category = "SAFE / INVESTIGATION",
            giver = "Vasco",
            location = "Ben Erai region",
            prerequisites = "Speak with Vasco about Sancho's gold in Ben Erai.",
            summary = "Choose whether to participate in Vasco's scheme to trick Sancho out of his gold.",
            walkthroughSteps = listOf("Talk to Vasco in Ben Erai about Sancho's gold.", "Vasco suggests pretending your money was stolen so you can keep the gold.", "Agree with Vasco's trick and tell Sancho you were robbed, OR expose Vasco's plan to Sancho.", "Collect the appropriate choice-specific dialogue result."),
            reward = "1,000 XP for the documented Dirty Doings resolution; the connected gold deception may award more XP.",
            warnings = "You are deciding whether to cheat Sancho, not recovering an unspecified stolen ore shipment.",
            searchTags = listOf("The stolen ore.", "Sancho / Ben Erai quest chain", "Ben Erai region", "SAFE / INVESTIGATION")
        ),
        Quest(
            id = "G3-P5-026",
            chapter = 5,
            playOrder = 26,
            title = "An Unexpected Message for Sigmor in Bakaresh",
            category = "CROSS-REGION",
            giver = "Sancho",
            location = "Ben Erai → Mora Sul",
            prerequisites = "Complete Sancho's connected Ben Erai assignments.",
            summary = "Carry Sancho's letter from Ben Erai to priest Sigmor at the Bakaresh temple.",
            walkthroughSteps = listOf("Finish Sancho's Ben Erai jobs and report back to him.", "He hands you a written message for Sigmor, the priest in Bakaresh.", "Travel east to Bakaresh and gain entry to the temple area where Sigmor resides.", "Deliver the letter to Sigmor."),
            reward = "500 XP and +15 Hashishin reputation.",
            warnings = "The documented destination is SIGMOR in BAKARESH, not Gonzales in Mora Sul.",
            searchTags = listOf("Report to Gonzales / Mora Sul.", "Sancho", "Ben Erai → Mora Sul", "CROSS-REGION")
        ),
        Quest(
            id = "G3-P5-027",
            chapter = 5,
            playOrder = 27,
            title = "Bounty Hunting: Ben Erai",
            category = "DEFER — HASHISHIN PATH",
            giver = "Campa",
            location = "Ben Erai region",
            prerequisites = "Speak to Campa at Ben Erai's outskirts.",
            summary = "Find and defeat Campa's three Nomad bounty targets: Yespas, Hurit and Shakyor.",
            walkthroughSteps = listOf("Find bounty hunter Campa by Ben Erai's town entrance.", "Accept his contracts against three Nomad leaders: YESPAS, HURIT and SHAKYOR.", "Find Yespas west of Ben Erai by the road, Hurit north in the desert and Shakyor through the Lago Nomad line.", "For the Hashishin route, defeat the three and report each bounty."),
            reward = "1,500 XP and +20 Ben Erai reputation for the complete bounty chain.",
            warnings = "Killing Hurit, Yespas and Shakyor closes their Nomad quests and can affect the liberation of nearby towns.",
            searchTags = listOf("Eliminate the nomads around Ben Erai.", "Sancho / Hashishin", "Ben Erai region", "DEFER — HASHISHIN PATH")
        ),
        Quest(
            id = "G3-P5-028",
            chapter = 5,
            playOrder = 28,
            title = "Liberate Ben Erai",
            category = "DEFER — NOMAD PATH",
            giver = "Lukar (Nomad-aligned instigator)",
            location = "Ben Erai region",
            prerequisites = "Talk to Lukar about liberating Ben Erai; complete neutral work first.",
            summary = "Take the Nomad side and overthrow Ben Erai's Hashishin occupation.",
            walkthroughSteps = listOf("Talk to trader Lukar about overthrowing the Hashishin holding Ben Erai.", "Complete all peaceful work for Sancho, Eusebio, Vasco and Campa first if you want their rewards.", "Side with the Nomads and attack the Hashishin guards in Ben Erai.", "Defeat enough defenders for the town to fall."),
            reward = "2,500 XP and +5 Nomads reputation.",
            warnings = "Lukar offers little practical help in the battle. His death in Sancho's opposing quest prevents his dialogue; liberation contributes to Hashishin faction hostility.",
            searchTags = listOf("Support the nomads near Ben Erai.", "Nomad contact", "Ben Erai region", "DEFER — NOMAD PATH")
        ),
        Quest(
            id = "G3-P5-029",
            chapter = 5,
            playOrder = 29,
            title = "Talk to Fabio.",
            category = "SAFE",
            giver = "Fabio (Lago's Hashishin leader)",
            location = "Lago",
            prerequisites = "Reach Lago; consider Sancho's The Tunnel of Lago investigation.",
            summary = "Talk to Fabio, ruler of Lago, about its inactive mine and imprisoned Water Mage.",
            walkthroughSteps = listOf("Enter Lago and find Fabio, the local Hashishin ruler.", "Ask about the mine and why it is producing no gold; this answers Sancho's Tunnel of Lago report.", "Learn about the locked house/prison where Water Mage Vatras is held.", "Finish Lago's neutral fights and errands before liberating the settlement."),
            reward = "",
            warnings = "Fabio's dialogue is a hub for other missions; the classic guide does not list a separate 'Talk to Fabio' journal reward.",
            searchTags = listOf("Talk to Fabio.", "Fabio", "Lago", "SAFE")
        ),
        Quest(
            id = "G3-P5-030",
            chapter = 5,
            playOrder = 30,
            title = "Sibur's Fuzzy Dreams",
            category = "SAFE / COLLECTION",
            giver = "Sibur (Lago)",
            location = "Lago",
            prerequisites = "Meet Sibur in Lago.",
            summary = "Supply Sibur with five ice-wolf pelts to obtain his shipbuilding plans for Hatlod.",
            walkthroughSteps = listOf("Find Sibur in Lago and ask him about his strange ideas and plans.", "Sibur wants FIVE ICE WOLF PELTS from Nordmar.", "Collect the five pelts, then hand them to Sibur.", "He gives you his shipbuilding plans, useful for Hatlod the Silden shipwright."),
            reward = "1,500 XP, +15 Lago reputation and +1 Alchemy; Sibur's blueprints for Hatlod.",
            warnings = "The older 'Swampweed for Lago' entry did not match a distinct quest in the classic Lago index.",
            searchTags = listOf("Swampweed for Lago.", "Lago quest giver", "Lago", "SAFE / COLLECTION")
        ),
        Quest(
            id = "G3-P5-031",
            chapter = 5,
            playOrder = 31,
            title = "The Stone of the Lion",
            category = "SAFE",
            giver = "Shakyor (Nomad/druid ally near Lago)",
            location = "Lago fields",
            prerequisites = "Meet Shakyor and his lion near Lago.",
            summary = "Earn Shakyor's Lion Druid Stone through his Nomad diplomacy, or take it by hostile force.",
            walkthroughSteps = listOf("Find Shakyor in the desert near Lago with his lion companion.", "Ask how to obtain his Lion Druid Stone.", "He requires that you speak to the Nomad leaders he identifies around Varant.", "Meet those leaders and return to Shakyor, OR kill Shakyor if deliberately pursuing Campa's opposing bounty."),
            reward = "1,500 XP and Shakyor's Lion Druid Stone through the appropriate resolution.",
            warnings = "Shakyor is a named Nomad leader. Killing him conflicts with Nomad routes and Ranger-style druid-stone cooperation.",
            searchTags = listOf("The swampweed harvest.", "Lago worker", "Lago fields", "SAFE")
        ),
        Quest(
            id = "G3-P5-032",
            chapter = 5,
            playOrder = 32,
            title = "Bloody Bloodflies",
            category = "SAFE / HUNT",
            giver = "Rasul (Lago swampweed farmer)",
            location = "Oasis near Lago",
            prerequisites = "Ask Rasul about bloodflies at his swampweed fields.",
            summary = "Kill the bloodflies threatening Rasul's swampweed plantation near Lago.",
            walkthroughSteps = listOf("Talk to Rasul at Lago's swampweed plantation and ask about the insects.", "Climb the slope near the palm trees by the coast.", "Kill at least TEN bloodflies attacking the fields.", "Return to Rasul to close the objective."),
            reward = "1,500 XP and +15 Lago reputation.",
            warnings = "Ten bloodflies by the coastal trees are enough; do not roam the desert looking for unrelated insects.",
            searchTags = listOf("Hunt the bloodflies near Lago.", "Lago hunter", "Oasis near Lago", "SAFE / HUNT")
        ),
        Quest(
            id = "G3-P5-033",
            chapter = 5,
            playOrder = 33,
            title = "Fight Against Mamuk",
            category = "SAFE — ARENA",
            giver = "Fabio (Lago arena organizer) / Mamuk (opponent)",
            location = "Lago",
            prerequisites = "Ask Fabio about arena fights in Lago.",
            summary = "Defeat Mamuk nonlethally in Lago's first arena match.",
            walkthroughSteps = listOf("Ask Fabio in Lago to enter the local arena.", "Find Mamuk, the intoxicated Hashishin fighter.", "If he refuses, tell him you will beat him anyway; he agrees to the duel.", "Defeat him within the arena without killing him and finish the post-fight dialogue."),
            reward = "1,000 XP, +10 Lago reputation and +1 Strength.",
            warnings = "Mamuk is the FIRST Lago arena opponent; his dialogue takes extra persuasion.",
            searchTags = listOf("Fight in Lago's arena.", "Lago arena", "Lago", "SAFE — ARENA")
        ),
        Quest(
            id = "G3-P5-034",
            chapter = 5,
            playOrder = 34,
            title = "Fight Against Grubuz",
            category = "SAFE — ARENA",
            giver = "Fabio (Lago arena organizer) / Grubuz (opponent)",
            location = "Lago",
            prerequisites = "Defeat Mamuk in Lago's arena and ask Fabio for the next duel.",
            summary = "Beat Orc fighter Grubuz in Lago's second arena match.",
            walkthroughSteps = listOf("After the Mamuk arena victory, ask Fabio about the second fight.", "Challenge Orc warrior Grubuz in Lago.", "Defeat him nonlethally inside the arena and report the outcome to Fabio."),
            reward = "1,500 XP, +20 Lago reputation and +1 Strength.",
            warnings = "Grubuz is the second arena opponent, not an unidentified champion.",
            searchTags = listOf("Defeat Lago's strongest fighter.", "Arena champion", "Lago", "SAFE — ARENA")
        ),
        Quest(
            id = "G3-P5-035",
            chapter = 5,
            playOrder = 35,
            title = "Find Vatras.",
            category = "MAIN-STORY SUPPORT",
            giver = "Automatic search objective — Vatras is imprisoned in Lago",
            location = "Lago",
            prerequisites = "Travel to Lago and search its prison for Vatras.",
            summary = "Discover that Vatras, the Water Mage from Khorinis, is being held prisoner in Lago. Reach his cell and speak with him before deciding how to handle the town.",
            walkthroughSteps = listOf("Enter Lago and ask residents about the captive Water Mage.", "Find Vatras imprisoned in one of the town cells and speak to him.", "Decide whether to help the Nomads free him or remain on the Hashishin side, then follow the appropriate town quest."),
            reward = "Locates Vatras and enables his liberation/escort chain.",
            warnings = "Vatras must remain alive if you want Water Mage/Nomad quests. Do not rush town liberation before speaking to him.",
            searchTags = listOf("Find Vatras.", "Main story / Water Mage chain", "Lago", "MAIN-STORY SUPPORT")
        ),
        Quest(
            id = "G3-P5-036",
            chapter = 5,
            playOrder = 36,
            title = "Free Vatras from Lago.",
            category = "MAJOR — NOMAD",
            giver = "Vatras / Nomad route",
            location = "Lago",
            prerequisites = "Find Vatras in Lago's cell and choose the Nomad liberation route.",
            summary = "To free Vatras, you must remove the Hashishin control of Lago or otherwise reach the liberation outcome that opens his imprisonment. Speak with Vatras afterward and follow his relocation/dialogue.",
            walkthroughSteps = listOf("Speak to Vatras behind bars in Lago and learn that the Hashishin hold him.", "Complete the town's neutral traders and arena tasks before turning its guards hostile.", "Join the Nomad side or otherwise bring about Lago's liberation to open the prison.", "Free Vatras, speak to him and escort him to safety as directed."),
            reward = "Vatras is freed and his Water Mage/Nomad quests become available.",
            warnings = "This is a Hashishin-versus-Nomad choice. Early liberation closes Lago's peaceful quests and can worsen faction standing.",
            searchTags = listOf("Free Vatras from Lago.", "Vatras / Nomad route", "Lago", "MAJOR — NOMAD")
        ),
        Quest(
            id = "G3-P5-037",
            chapter = 5,
            playOrder = 37,
            title = "Escort Vatras Safely to Hurit",
            category = "SAFE / ESCORT",
            giver = "Vatras",
            location = "Lago → Nomad/Water Mage destination",
            prerequisites = "Free Vatras during the liberation of Lago.",
            summary = "Escort the freed Water Mage Vatras from Lago safely to Nomad leader Hurit.",
            walkthroughSteps = listOf("Liberate Lago and free Water Mage Vatras from imprisonment.", "Ask Vatras to follow you toward Nomad leader Hurit's desert camp.", "Escort him carefully through the sand and hostile wildlife.", "Deliver Vatras alive to Hurit and finish the escort dialogue."),
            reward = "1,000 XP and +3 Nomads reputation.",
            warnings = "Destination is HURIT's Nomad camp, not an unspecified nearby safe location.",
            searchTags = listOf("Escort Vatras to safety.", "Vatras", "Lago → Nomad/Water Mage destination", "SAFE / ESCORT")
        ),
        Quest(
            id = "G3-P5-038",
            chapter = 5,
            playOrder = 38,
            title = "Liberate Lago!",
            category = "DEFER — NOMAD PATH",
            giver = "Shakyor / Nomad liberation",
            location = "Lago",
            prerequisites = "Finish Lago's peaceful quests and choose the Nomad uprising.",
            summary = "Liberate Lago with the Nomad allies, then release Vatras.",
            walkthroughSteps = listOf("Resolve Lago's neutral quests, including Rasul, Sibur, Vatras's identity and the Mamuk/Grubuz arena matches.", "Speak with Shakyor, Rasul and Vatras to confirm the local pro-Nomad line.", "Attack Fabio and the Hashishin garrison and defeat enough defenders to liberate the settlement.", "Free Vatras and escort him to Hurit."),
            reward = "2,500 XP and +5 Nomads reputation.",
            warnings = "Completing the liberation makes Fabio and other Hashishin NPCs hostile and may affect faction-wide access.",
            searchTags = listOf("Liberate Lago!", "Nomad / player action", "Lago", "DEFER — NOMAD PATH")
        ),
        Quest(
            id = "G3-P5-039",
            chapter = 5,
            playOrder = 39,
            title = "Bounty Hunting: Shakyor, the Desert Lion",
            category = "DEFER — HASHISHIN PATH",
            giver = "Campa (Ben Erai bounty hunter)",
            location = "Lago region",
            prerequisites = "Accept Campa's bounty list in Ben Erai.",
            summary = "Fulfill Campa's Hashishin bounty against Shakyor and his lion near Lago.",
            walkthroughSteps = listOf("Accept Campa's bounty against Nomad leader Shakyor.", "Find Shakyor with his lion in the wilderness near Lago.", "If pursuing the Hashishin route, defeat both Shakyor and his lion.", "Return to Campa and report the bounty."),
            reward = "2,000 XP, +4 Hashishin reputation and +25 Lago reputation.",
            warnings = "Kills the owner of the Lion Druid Stone and blocks his Nomad quests.",
            searchTags = listOf("Destroy the nomads connected to Lago.", "Hashishin quest giver", "Lago region", "DEFER — HASHISHIN PATH")
        ),
        Quest(
            id = "G3-P5-040",
            chapter = 5,
            playOrder = 40,
            title = "Talk to Julio.",
            category = "SAFE",
            giver = "Julio (Ben Sala governor)",
            location = "Ben Sala",
            prerequisites = "Reach Ben Sala and speak with governor Julio.",
            summary = "Learn from Julio which mines and ruins must be cleared to save Ben Sala.",
            walkthroughSteps = listOf("Reach Ben Sala and ask Julio about the undead disaster.", "He describes the trouble in the mines and ruins and suspects Basir.", "Speak with Daro about the tunnels, Dolok about the temple path and Enzo about missing smithing supplies.", "Complete the real Ben Sala missions before returning to Julio for Saving Ben Sala."),
            reward = "",
            warnings = "Town briefing/hub entry; no standalone 'Talk to Julio' journal quest was confirmed in the classic guide.",
            searchTags = listOf("Talk to Julio.", "Julio", "Ben Sala", "SAFE")
        ),
        Quest(
            id = "G3-P5-041",
            chapter = 5,
            playOrder = 41,
            title = "The Ruins",
            category = "SAFE",
            giver = "Daro (Ben Sala guard)",
            location = "Ben Sala outskirts",
            prerequisites = "Ask Daro about the missing scouts in Ben Sala.",
            summary = "Destroy Daro's missing scouts, now undead, among the ruins near Ben Sala.",
            walkthroughSteps = listOf("Ask Daro about his scouts who vanished near the ruins.", "Travel into the ruined area outside Ben Sala.", "The missing scouts have turned undead; defeat all hostile former scouts.", "Return to Daro and report what happened."),
            reward = "1,500 XP and +10 Ben Sala reputation.",
            warnings = "The undead epidemic is a connected mine/temple questline; complete local survival quests before launching a faction purge.",
            searchTags = listOf("The undead around Ben Sala.", "Julio / town defenders", "Ben Sala outskirts", "SAFE")
        ),
        Quest(
            id = "G3-P5-042",
            chapter = 5,
            playOrder = 42,
            title = "Looted Goods",
            category = "SAFE",
            giver = "Giores (Ben Sala merchant)",
            location = "Cave near Ben Sala",
            prerequisites = "Speak to merchant Giores in Ben Sala.",
            summary = "Retrieve eight stolen cargo chests from bandits for Giores.",
            walkthroughSteps = listOf("Speak to merchant Giores about goods stolen by bandits.", "Find the nearby bandit cave and defeat its occupants.", "Collect EIGHT chests of stolen goods lying around the hideout.", "Bring all eight chests back to Giores."),
            reward = "1,500 XP and +5 Ben Sala reputation.",
            warnings = "Eight chests of Giores's goods; do not mix them up with Enzo's six steel crates.",
            searchTags = listOf("Clean out the cave near Ben Sala.", "Ben Sala quest giver", "Cave near Ben Sala", "SAFE")
        ),
        Quest(
            id = "G3-P5-043",
            chapter = 5,
            playOrder = 43,
            title = "The Tunnels",
            category = "SAFE",
            giver = "Daro (Ben Sala guard)",
            location = "Ben Sala",
            prerequisites = "Ask Daro about the undead-infested mine passages.",
            summary = "Clear undead from both tunnels at Ben Sala for Daro.",
            walkthroughSteps = listOf("Talk to Daro about the undead occupying Ben Sala's two tunnels.", "Enter BOTH mine tunnels, killing skeletons and zombies in each.", "Check the side alcoves for Enzo's heavy steel crates and Miguel.", "Report to Daro when both tunnels are clear."),
            reward = "1,500 XP and +10 Ben Sala reputation.",
            warnings = "Two different tunnels need cleaning, not just one mine shaft.",
            searchTags = listOf("The tunnel of the undead.", "Ben Sala mine/tunnel quest giver", "Ben Sala", "SAFE")
        ),
        Quest(
            id = "G3-P5-044",
            chapter = 5,
            playOrder = 44,
            title = "Ben Sala's Ruined Mine — Guide Entry",
            category = "GUIDE — REFERENCE",
            giver = "Guide entry (related to Daro's The Tunnels)",
            location = "Ben Sala region",
            prerequisites = "The Tunnels is the verified nearby quest; no separate trigger established.",
            summary = "Reference note linking Ben Sala's ruined mines to Daro's real The Tunnels quest.",
            walkthroughSteps = listOf("The classic base-game quest index does not list a separate journal mission called The Ruined Mine.", "For the actual task, accept Daro's The Tunnels and clear the undead from both mine passages.", "Look for Miguel, who is endangered by attacks, and collect steel crates for Enzo.", "Finish Daro's named quest and the separately documented escort of Miguel."),
            reward = "No independent reward confirmed for the former Ruined Mine placeholder; Daro's The Tunnels awards 1,500 XP.",
            warnings = "GUIDE ENTRY, not verified as its own journal quest. See The Tunnels and Escort Miguel Safely to the Village.",
            searchTags = listOf("The ruined mine.", "Ben Sala miner", "Ben Sala region", "SAFE")
        ),
        Quest(
            id = "G3-P5-045",
            chapter = 5,
            playOrder = 45,
            title = "Six Crates of Steel",
            category = "SAFE / COLLECTION",
            giver = "Enzo (Ben Sala smith)",
            location = "Ben Sala",
            prerequisites = "Ask blacksmith Enzo in Ben Sala about missing steel cargo.",
            summary = "Recover six crates of steel for Enzo: five from the tunnels and one from Miguel.",
            walkthroughSteps = listOf("Ask blacksmith Enzo about his supplies lost during the undead attack.", "Search both mine tunnels; FIVE crates, identified as heavy chests, are scattered inside.", "Find the sixth crate with miner Miguel in the tunnel. If he survives, speak to him; otherwise search the body.", "Deliver all SIX crates to Enzo."),
            reward = "1,500 XP, +5 Ben Sala reputation and +1 Smithing.",
            warnings = "Five crates in tunnels plus ONE with Miguel. Protect Miguel for his escort quest if possible.",
            searchTags = listOf("Weapons for Ben Sala.", "Ben Sala guard/merchant", "Ben Sala", "SAFE / COLLECTION")
        ),
        Quest(
            id = "G3-P5-046",
            chapter = 5,
            playOrder = 46,
            title = "A Banquet for the Vultures",
            category = "SAFE / COLLECTION",
            giver = "Julio",
            location = "Ben Sala",
            prerequisites = "Speak to Julio about the thief who fled Ben Sala.",
            summary = "Find thief Sugut in the oasis north of Ben Sala on Julio's request.",
            walkthroughSteps = listOf("Julio tells you a thief stole from Ben Sala.", "Track Sugut to an oasis NORTH of the town.", "Near the oasis are Hurit and his Nomads; you can enlist their aid against Sugut if desired.", "Confront Sugut and report the outcome to Julio."),
            reward = "1,500 XP and +10 Ben Sala reputation.",
            warnings = "Sugut and Hurit oppose each other. Their bounties and Nomad support may be mutually exclusive.",
            searchTags = listOf("Ore for the smith.", "Ben Sala smith", "Ben Sala", "SAFE / COLLECTION")
        ),
        Quest(
            id = "G3-P5-047",
            chapter = 5,
            playOrder = 47,
            title = "The Deal with Basir",
            category = "SAFE / DELIVERY",
            giver = "Julio",
            location = "Ben Sala",
            prerequisites = "Ask Julio about Basir's role in the Ben Sala undead disaster.",
            summary = "Locate Basir in Montera and decide whether to punish him for Julio.",
            walkthroughSteps = listOf("Talk to Julio about Basir's involvement in the curse on Ben Sala.", "Julio wants Basir punished; he is not in Ben Sala anymore.", "Travel to MONTERA, where Basir has settled in the occupied city.", "Decide whether to kill Basir for Julio, potentially after a Rebel liberation makes the town safer.", "Return and report to Julio."),
            reward = "1,500 XP and +15 Ben Sala reputation.",
            warnings = "Basir is in MONTERA. Killing him is irreversible and can trigger nearby guards if the town is still peaceful.",
            searchTags = listOf("Healing potions for the defenders.", "Ben Sala quest giver", "Ben Sala", "SAFE / DELIVERY")
        ),
        Quest(
            id = "G3-P5-048",
            chapter = 5,
            playOrder = 48,
            title = "The Cursed One",
            category = "SAFE / DUNGEON",
            giver = "Julio / Daro / Dolok",
            location = "Ben Sala ruins",
            prerequisites = "Gain Dolok's help locating the temple after doing local quests.",
            summary = "Clear the Ben Sala temple of undead and defeat Yugul the Cursed One.",
            walkthroughSteps = listOf("Finish enough Ben Sala work to earn Dolok's help locating the temple.", "Follow Dolok to the undead-filled ancient temple; clear the guardians outside.", "Fight through the undead INSIDE the temple.", "Defeat YUGUL THE CURSED ONE at the final chamber.", "Return to Julio and report that the source of the curse has been defeated."),
            reward = "2,500 XP and +20 Ben Sala reputation; enables Saving Ben Sala.",
            warnings = "The named final boss is YUGUL, not an anonymous undead general.",
            searchTags = listOf("The cursed temple near Ben Sala.", "Ben Sala / temple quest chain", "Ben Sala ruins", "SAFE / DUNGEON")
        ),
        Quest(
            id = "G3-P5-049",
            chapter = 5,
            playOrder = 49,
            title = "The Way to the Temple",
            category = "SAFE / INVESTIGATION",
            giver = "Dolok",
            location = "Ben Sala region",
            prerequisites = "Increase Ben Sala standing through tasks for Daro and speak to Dolok.",
            summary = "Follow Dolok to the cursed temple after gaining his trust.",
            walkthroughSteps = listOf("Complete some of Daro's Ben Sala tasks to earn local trust.", "Ask Dolok to reveal the way to the old temple.", "Follow Dolok's route; prepare for strong undead enemies along the way.", "Arrive at the temple and begin the separate The Cursed One fight."),
            reward = "2,500 XP.",
            warnings = "May require sufficiently high Ben Sala standing. Dolok's escort precedes the boss Yugul.",
            searchTags = listOf("Find the source of the undead.", "Julio / temple chain", "Ben Sala region", "SAFE / INVESTIGATION")
        ),
        Quest(
            id = "G3-P5-050",
            chapter = 5,
            playOrder = 50,
            title = "Yugul's Temple — Boss Encounter Guide",
            category = "GUIDE — REFERENCE",
            giver = "Guide entry (The Cursed One)",
            location = "Ben Sala ruins",
            prerequisites = "Complete Dolok's The Way to the Temple; not a separately confirmed quest.",
            summary = "Reference walkthrough for Yugul, the final encounter in The Cursed One.",
            walkthroughSteps = listOf("This is the final battle portion of The Cursed One, not a separately confirmed journal mission.", "Enter the temple after Dolok's escort and defeat its outside defenders.", "Inside, kill undead and fight Yugul the Cursed One.", "Return to Julio through the documented The Cursed One and Saving Ben Sala conversations."),
            reward = "The Cursed One quest awards 2,500 XP; no additional separate boss-quest reward confirmed.",
            warnings = "GUIDE ENCOUNTER, not a proven distinct journal quest. Do not expect an extra reward or new diary objective.",
            searchTags = listOf("Kill the undead leaders.", "Ben Sala quest chain", "Ben Sala ruins", "SAFE")
        ),
        Quest(
            id = "G3-P5-051",
            chapter = 5,
            playOrder = 51,
            title = "Basir Investigation — Quest Link",
            category = "GUIDE — UNVERIFIED",
            giver = "Guide entry (Julio's The Deal with Basir)",
            location = "Ben Sala ruins",
            prerequisites = "Speak to Julio about Basir. A stand-alone Basir-chest journal trigger is not established.",
            summary = "Reference guide to Julio's documented The Deal with Basir; a separate chest quest is unverified.",
            walkthroughSteps = listOf("This formerly generic treasure-chest entry has no independently identified match in the base-game Ben Sala quest list.", "The documented Basir quest is The Deal with Basir, offered by Julio.", "Find Basir in Montera, resolve Julio's demand and report back to Ben Sala.", "For lost cargo in the Ben Sala area, do Giores's Looted Goods separately."),
            reward = "No standalone reward established for the former Basir's Chest entry; see Julio's 1,500 XP quest.",
            warnings = "UNVERIFIED AS A SEPARATE QUEST; do not hunt for an unspecified Basir chest that the guide never locates.",
            searchTags = listOf("Basir's old chest / treasure.", "Basir-related quest chain", "Ben Sala ruins", "SAFE")
        ),
        Quest(
            id = "G3-P5-052",
            chapter = 5,
            playOrder = 52,
            title = "Escort Miguel Safely to the Village",
            category = "SAFE / ESCORT",
            giver = "Miguel (miner in Ben Sala tunnels)",
            location = "Ben Sala road",
            prerequisites = "Enter Ben Sala's undead tunnels for Daro; Miguel must still be alive.",
            summary = "Rescue miner Miguel from Ben Sala's tunnels and escort him to Enzo.",
            walkthroughSteps = listOf("During Daro's The Tunnels, find Miguel in one of the undead-filled mine shafts.", "Reach him quickly: zombies can kill Miguel before you arrive.", "Talk to Miguel and escort him to Enzo the smith inside Ben Sala.", "Keep him alive and check whether he still holds Enzo's missing sixth steel crate."),
            reward = "1,000 XP and +10 Ben Sala reputation.",
            warnings = "Miguel is a miner under undead attack, not an arbitrary merchant on the road. His survival matters for Enzo's supplies.",
            searchTags = listOf("Escort the merchant through the dangerous area.", "Ben Sala merchant", "Ben Sala road", "SAFE / ESCORT")
        ),
        Quest(
            id = "G3-P5-053",
            chapter = 5,
            playOrder = 53,
            title = "The Road to Bakaresh — Guide Entry",
            category = "GUIDE — REFERENCE",
            giver = "Guide entry (travel advice)",
            location = "Ben Sala → Bakaresh road",
            prerequisites = "Optional exploration of the Ben Sala–Bakaresh road.",
            summary = "Regional travel advice for the road from Ben Sala to Bakaresh; no distinct journal quest found.",
            walkthroughSteps = listOf("The old guide entry describing a separate Ben Sala road-clearing quest is not corroborated by the classic quest list.", "If travelling east to Bakaresh, clear only the undead or bandits actually attacking you.", "The genuine named Ben Sala assignments are Daro's The Tunnels and The Ruins, Giores's Looted Goods, and Dolok's temple escort.", "Do not search for a nonexistent named quest giver along the road."),
            reward = "No verified standalone quest reward.",
            warnings = "GUIDE ENTRY ONLY until an actual in-game journal mission is shown.",
            searchTags = listOf("Clear the road to Bakaresh.", "Ben Sala quest giver", "Ben Sala → Bakaresh road", "SAFE")
        ),
        Quest(
            id = "G3-P5-054",
            chapter = 5,
            playOrder = 54,
            title = "Saving Ben Sala",
            category = "SAFE",
            giver = "Julio (on report after The Cursed One)",
            location = "Ben Sala",
            prerequisites = "Complete The Cursed One at Ben Sala's ancient temple.",
            summary = "Report Yugul's defeat and the end of Ben Sala's undead curse to Julio.",
            walkthroughSteps = listOf("Finish Dolok's The Way to the Temple and clear Yugul's undead temple.", "Return to Ben Sala and speak with Julio.", "Report that the curse source has been removed and the town can recover."),
            reward = "2,500 XP and +15 Ben Sala reputation.",
            warnings = "This quest resolves the undead crisis, not the optional Nomad rebellion against Ben Sala.",
            searchTags = listOf("Report the end of the undead threat.", "Julio", "Ben Sala", "SAFE")
        ),
        Quest(
            id = "G3-P5-055",
            chapter = 5,
            playOrder = 55,
            title = "Liberate Ben Sala.",
            category = "DEFER — NOMAD PATH",
            giver = "Nomad-aligned liberation objective",
            location = "Ben Sala",
            prerequisites = "Choose the Nomad campaign against Ben Sala.",
            summary = "Liberate Ben Sala from the Hashishin after completing neutral settlement quests.",
            walkthroughSteps = listOf("Finish Ben Sala's neutral smithing, missing-goods, tunnel and Yugul tasks first.", "When siding with Nomads, attack the Hashishin occupying Ben Sala.", "Defeat enough defenders to trigger liberation.", "Remember that this affects wider Hashishin faction hostility."),
            reward = "2,500 XP and +5 Nomads reputation.",
            warnings = "The liberation is independent from Saving Ben Sala's undead-curse resolution.",
            searchTags = listOf("Liberate Ben Sala.", "Nomad / player action", "Ben Sala", "DEFER — NOMAD PATH")
        ),
        Quest(
            id = "G3-P5-056",
            chapter = 5,
            playOrder = 56,
            title = "Ben Sala Nomad Bounty — Unverified",
            category = "GUIDE — UNVERIFIED",
            giver = "Unverified Hashishin bounty giver",
            location = "Ben Sala region",
            prerequisites = "No reliable journal trigger or target has been established.",
            summary = "Unverified regional Nomad bounty entry, without a named giver or target in the classic quest list.",
            walkthroughSteps = listOf("The classic base-game Ben Sala quest list does not confirm a named mission to destroy a local Nomad camp.", "Do not attack Hurit or nearby Nomads based solely on this placeholder; their named bounties belong to Campa and other Hashishin contracts.", "Check for a real journal entry identifying a target before acting.", "Complete Ben Sala's documented neutral quests first."),
            reward = "No independently verified standalone reward.",
            warnings = "UNVERIFIED: the older catalog inferred a generic Nomad extermination quest without a named giver or target.",
            searchTags = listOf("Destroy the nomads near Ben Sala.", "Hashishin leadership", "Ben Sala region", "DEFER — HASHISHIN PATH")
        ),
    )
}
