package com.sliverzfx.gothicquest

internal object Gothic3Part2Data {
    val quests = listOf(
        Quest(
            id = "G3-P2-001",
            chapter = 2,
            playOrder = 1,
            title = "Okara needs more people.",
            category = "SAFE",
            giver = "Manning",
            location = "Okara and surrounding wilderness",
            prerequisites = "Meet Manning, Okara's quartermaster and recruiter.",
            summary = "Recruit Randall, Owen, Rakus, Candela, Fraser and Kent from the countryside, and make sure Rufus from the Montera grain farm reaches Okara. Return to Manning after the recruitment chain is complete.",
            walkthroughSteps = listOf("Ask Manning for help populating Okara's rebel camp.", "Find RANDALL at a campfire beside the mine; help him clear the crawlers, then recruit him.", "Find OWEN in the wilderness, give him booze and offer him a home in Okara.", "Find RAKUS in the undead cave; remove his summoned undead and recruit him.", "Find hunters CANDELA and FRASER at the ruins, finish their shadowbeast/boar hunts, and recruit both.", "Find KENT hiding from ripperbeasts in a nearby cave, kill the beasts and ask him to join.", "Help RUFUS escape Montera's grain farm and escort him to Okara.", "Report the available recruits to Manning. After his requirements are met, he can also request five iron ore."),
            reward = "Individual recruits award experience and Okara reputation; each completed recruitment increases Okara manpower.",
            warnings = "Recruitment stages have prerequisites: clear Randall's mine, Rakus's undead, Kent's ripperbeasts and hunters' beasts before asking them to move.",
            searchTags = listOf("Okara needs more people.", "Manning", "Okara and surrounding wilderness", "SAFE")
        ),
        Quest(
            id = "G3-P2-002",
            chapter = 2,
            playOrder = 2,
            title = "Clean out the mine with Randall the fighter.",
            category = "SAFE",
            giver = "Randall",
            location = "West of Okara",
            prerequisites = "",
            summary = "Find Randall at his campfire west of Okara. Agree to help him and enter the nearby mine together. Kill the Minecrawlers in the first section without letting Randall die.",
            walkthroughSteps = listOf("Find Randall at the campfire west of Okara and agree to help with the nearby mine.", "Enter together and fight the Minecrawlers through roughly the first half of the mine. When that section is secured, Randall stops and the escort-style quest completes.", "Return to the quest giver or the named destination after the objective is complete. If no completion message appears, re-check the target area for a surviving enemy, missing quest item, or an unfinished dialogue step.", "Do not leave yet. Randall immediately leaves the remaining Minecrawlers to you, beginning “A rich mine.”"),
            reward = "Verified reward: 1000 XP and +4 Okara reputation.",
            warnings = "",
            searchTags = listOf("Clean out the mine with Randall the fighter.", "Randall", "West of Okara", "SAFE")
        ),
        Quest(
            id = "G3-P2-003",
            chapter = 2,
            playOrder = 3,
            title = "A rich mine.",
            category = "SAFE",
            giver = "Randall",
            location = "Mine west of Okara",
            prerequisites = "",
            summary = "After the first part of Randall's mine is cleared, continue through the remaining tunnels and kill the Minecrawlers so the mine can be worked safely.",
            walkthroughSteps = listOf("This begins after the first half of Randall's mine has been cleared with him.", "Continue deeper without Randall and kill the remaining nine Minecrawlers. Search and mine the tunnels while you are there; the iron ore is useful for Manning's later request.", "Return to the quest giver or the named destination after the objective is complete. If no completion message appears, re-check the target area for a surviving enemy, missing quest item, or an unfinished dialogue step.", "Keep at least five Iron Ore. After all Okara recruits are gathered, Manning asks specifically for five pieces."),
            reward = "Verified: 1500 XP, +4 Okara reputation, +1 Strength and a 500 XP follow-up from Randall.",
            warnings = "",
            searchTags = listOf("A rich mine.", "Randall", "Mine west of Okara", "SAFE")
        ),
        Quest(
            id = "G3-P2-004",
            chapter = 2,
            playOrder = 4,
            title = "Randall should go to Okara.",
            category = "SAFE",
            giver = "Randall",
            location = "Okara wilderness → Okara",
            prerequisites = "",
            summary = "After clearing Randall's mine, tell him Manning is looking for capable people. Randall travels to Okara; report his recruitment to Manning.",
            walkthroughSteps = listOf("Randall sits at a campfire west of Okara. He will not join simply because you ask him. First complete his two mine quests: clear the first section with him, then finish the remaining Minecrawlers yourself.", "After the mine is safe, ask Randall to support Okara. He requires 300 gold before agreeing. Pay him; he then heads for the Rebel camp. Report the successful recruitment to Manning.", "Return to the quest giver or the named destination after the objective is complete. If no completion message appears, re-check the target area for a surviving enemy, missing quest item, or an unfinished dialogue step.", "This is one of the easy-to-miss requirements of “Okara needs more people.”"),
            reward = "Verified: 1000 XP, +8 Okara reputation, +1 Rebel reputation; Manning adds 500 XP and 500 gold.",
            warnings = "",
            searchTags = listOf("Randall should go to Okara.", "Randall", "Okara wilderness → Okara", "SAFE")
        ),
        Quest(
            id = "G3-P2-005",
            chapter = 2,
            playOrder = 5,
            title = "Booze for the prospector.",
            category = "SAFE",
            giver = "Owen",
            location = "Hill south of Okara",
            prerequisites = "",
            summary = "Find Owen at his campfire on the prominent hill south of Okara and give him the booze he asks for.",
            walkthroughSteps = listOf("Find prospector Owen in the wilderness around Okara.", "Give him one bottle of booze to gain his trust.", "Ask Owen about his lack of a home and follow with A Homeless Prospector."),
            reward = "250 XP and +4 Okara reputation.",
            warnings = "",
            searchTags = listOf("Booze for the prospector.", "Owen", "Hill south of Okara", "SAFE")
        ),
        Quest(
            id = "G3-P2-006",
            chapter = 2,
            playOrder = 6,
            title = "A homeless prospector.",
            category = "SAFE",
            giver = "Owen",
            location = "South of Okara → Okara",
            prerequisites = "Give Owen a bottle of booze and ask where he can live.",
            summary = "After helping Owen with booze, tell him the rebels at Okara need people. Send him to the camp and report to Manning.",
            walkthroughSteps = listOf("Finish Booze for the Prospector so Owen will discuss his situation.", "Tell Owen to join Manning's rebel settlement at Okara.", "Visit Manning and mention Owen's arrival for any recruitment follow-up."),
            reward = "1,000 XP, +1 Rebel reputation and +8 Okara reputation.",
            warnings = "",
            searchTags = listOf("A homeless prospector.", "Owen", "South of Okara → Okara", "SAFE")
        ),
        Quest(
            id = "G3-P2-007",
            chapter = 2,
            playOrder = 7,
            title = "Rakus the Fire Mage should go to Okara.",
            category = "SAFE",
            giver = "Rakus (Fire Mage)",
            location = "Cave near Okara → Okara",
            prerequisites = "Rescue Rakus from undead and defeat the remaining undead in his cave.",
            summary = "After rescuing Rakus and destroying his undead, suggest that he join the rebels in Okara. Return to Manning after he leaves.",
            walkthroughSteps = listOf("Find Rakus in the undead-filled cave in the woods near Okara.", "Protect him while fighting out, then clear the rest of the undead in his cave.", "Ask Rakus to join the rebels at Okara.", "Report another recruit to Manning at Okara."),
            reward = "1,000 XP, +1 Rebel reputation and +8 Okara reputation.",
            warnings = "",
            searchTags = listOf("Rakus the Fire Mage should go to Okara.", "Rakus", "Cave near Okara → Okara", "SAFE")
        ),
        Quest(
            id = "G3-P2-008",
            chapter = 2,
            playOrder = 8,
            title = "Rescue Rakus the Fire Mage from the cave of the undead.",
            category = "SAFE",
            giver = "Rakus",
            location = "Cave near Okara",
            prerequisites = "Find Rakus trapped inside the cave of his failed necromancy experiment.",
            summary = "Locate Rakus in the cave where his necromantic experiment went wrong. Escort/fight your way out while killing the undead attacking him; keep Rakus alive.",
            walkthroughSteps = listOf("Search the woods around Okara for a cave occupied by undead and containing Fire Mage Rakus.", "Talk to Rakus about his failed experiment and escort him toward the exit.", "Defeat the undead attackers without letting Rakus die.", "Talk to Rakus afterward; he asks you to destroy any remaining skeletons."),
            reward = "1,000 XP, +4 Okara reputation and +1 Ancient Knowledge.",
            warnings = "Keep Rakus alive during the rescue; he is both an Okara recruit and a FIRE CHALICE holder.",
            searchTags = listOf("Rescue Rakus the Fire Mage from the cave of the undead.", "Rakus", "Cave near Okara", "SAFE")
        ),
        Quest(
            id = "G3-P2-009",
            chapter = 2,
            playOrder = 9,
            title = "Kill the undead that Rakus summoned.",
            category = "SAFE",
            giver = "Rakus",
            location = "Cave near Okara",
            prerequisites = "First rescue Rakus from the undead-filled cave.",
            summary = "Clear the remaining skeletons and undead created by Rakus's failed experiment, then speak with him again.",
            walkthroughSteps = listOf("Return to the cave where Rakus summoned undead in his experiments.", "Destroy the remaining skeletons and zombies after Rakus reaches safety.", "Report the cave cleared to Rakus and ask for his Fire Chalice."),
            reward = "1,000 XP, +4 Okara reputation and +1 Ancient Knowledge; unlocks Rakus's Fire Chalice dialogue.",
            warnings = "",
            searchTags = listOf("Kill the undead that Rakus summoned.", "Rakus", "Cave near Okara", "SAFE")
        ),
        Quest(
            id = "G3-P2-010",
            chapter = 2,
            playOrder = 10,
            title = "Hunt the nasty shadowbeasts.",
            category = "SAFE",
            giver = "Candela",
            location = "Ruined site northeast of Okara",
            prerequisites = "Meet Candela at the ruins outside Okara.",
            summary = "Meet Candela at the ruins and kill the two named nasty Shadowbeasts nearby. Loot their horns before leaving.",
            walkthroughSteps = listOf("Talk to hunter Candela at the ruined camp and ask about the beasts nearby.", "Find and defeat the TWO dangerous shadowbeasts near the ruins.", "Take their horns before heading back; Candela has a separate horn turn-in.", "Report the cleared hunting ground to Candela."),
            reward = "1,000 XP, +4 Okara reputation and +1 Hunting skill.",
            warnings = "",
            searchTags = listOf("Hunt the nasty shadowbeasts.", "Candela", "Ruined site northeast of Okara", "SAFE")
        ),
        Quest(
            id = "G3-P2-011",
            chapter = 2,
            playOrder = 11,
            title = "Two shadowbeast horns for Candela.",
            category = "SAFE",
            giver = "Candela",
            location = "Ruins near Okara",
            prerequisites = "Finish hunting Candela's two shadowbeasts and collect their horns.",
            summary = "Give Candela the two Shadowbeast horns from the beasts you just killed.",
            walkthroughSteps = listOf("Learn to take horns if necessary before hunting the two shadowbeasts near Candela.", "Loot a horn from each of the two shadowbeasts.", "Give both horns to Candela."),
            reward = "750 XP and +1 Hunting skill.",
            warnings = "",
            searchTags = listOf("Two shadowbeast horns for Candela.", "Candela", "Ruins near Okara", "SAFE")
        ),
        Quest(
            id = "G3-P2-012",
            chapter = 2,
            playOrder = 12,
            title = "Candela should go to Okara.",
            category = "SAFE",
            giver = "Candela",
            location = "Ruins → Okara",
            prerequisites = "Complete Hunt the Nasty Shadowbeasts and talk to Candela about Okara.",
            summary = "Once Candela's hunt is finished, tell him to join the rebels in Okara and report his recruitment to Manning.",
            walkthroughSteps = listOf("Candela is in the old ruins north of Okara with Fraser. He will only agree to relocate after you prove yourself by completing his Shadowbeast hunt.", "Kill the two Nasty Shadowbeasts, finish Candela's related horn dialogue if active, then tell him Okara needs people. Return to Manning afterward.", "Return to the quest giver or the named destination after the objective is complete. If no completion message appears, re-check the target area for a surviving enemy, missing quest item, or an unfinished dialogue step.", "Candela and Fraser are in the same ruins, so complete both hunters' quest chains in one trip."),
            reward = "1,000 XP and +8 Okara reputation.",
            warnings = "",
            searchTags = listOf("Candela should go to Okara.", "Candela", "Ruins → Okara", "SAFE")
        ),
        Quest(
            id = "G3-P2-013",
            chapter = 2,
            playOrder = 13,
            title = "Hunt the nasty wild boars.",
            category = "SAFE",
            giver = "Fraser",
            location = "Ruins near Okara",
            prerequisites = "Find Fraser camping with Candela among the ruins near Okara.",
            summary = "Kill the dangerous wild boars associated with Fraser's hunting area and make sure the whole target group is dead.",
            walkthroughSteps = listOf("Ask hunter Fraser about the wild boars roaming below the ruins.", "Find the group of aggressive boars in the nearby valley.", "Kill them using a bow from a rocky position if needed.", "Return to Fraser to report the hunt."),
            reward = "750 XP and +1 Hunting skill.",
            warnings = "",
            searchTags = listOf("Hunt the nasty wild boars.", "Fraser", "Ruins near Okara", "SAFE")
        ),
        Quest(
            id = "G3-P2-014",
            chapter = 2,
            playOrder = 14,
            title = "Go boar hunting with Fraser.",
            category = "SAFE",
            giver = "Fraser",
            location = "Ruins near Okara",
            prerequisites = "Talk to Fraser about joining him on a boar hunt near the ruins.",
            summary = "Ask Fraser to hunt with you and accompany him to the boars. Help him kill them without letting him die.",
            walkthroughSteps = listOf("Ask Fraser to go hunting with you.", "Follow his route from the ruined camp toward the boars in the valley.", "Help him defeat the boars without letting him get surrounded.", "Talk to Fraser again and ask whether he would join Okara."),
            reward = "Hunting companion and progress toward Fraser's Okara recruitment; exact separate XP award not independently verified.",
            warnings = "",
            searchTags = listOf("Go boar hunting with Fraser.", "Fraser", "Ruins near Okara", "SAFE")
        ),
        Quest(
            id = "G3-P2-015",
            chapter = 2,
            playOrder = 15,
            title = "Fraser should go to Okara.",
            category = "SAFE",
            giver = "Fraser",
            location = "Ruins → Okara",
            prerequisites = "Complete Fraser's boar hunt near the ruins outside Okara.",
            summary = "After the boar hunt, tell Fraser that Okara needs hunters and send him to the rebel camp.",
            walkthroughSteps = listOf("Speak to Fraser after dealing with his dangerous boars.", "Tell him Manning needs fighters and hunters in the rebel camp of Okara.", "Ask Fraser to relocate to Okara and report his agreement to Manning."),
            reward = "1,000 XP, +1 Rebel reputation and +8 Okara reputation.",
            warnings = "",
            searchTags = listOf("Fraser should go to Okara.", "Fraser", "Ruins → Okara", "SAFE")
        ),
        Quest(
            id = "G3-P2-016",
            chapter = 2,
            playOrder = 16,
            title = "Malicious ripperbeasts.",
            category = "SAFE",
            giver = "Kent",
            location = "Cave east-northeast of Okara",
            prerequisites = "Find Kent hiding in a small cave near the Okara hunting grounds.",
            summary = "Find Kent hiding in a small cave near an abandoned hut. Kill the malicious Ripperbeasts outside so he can safely leave.",
            walkthroughSteps = listOf("Find Kent in his small cave, where he is afraid of ripperbeasts outside.", "Ask about the monsters preventing his departure.", "Kill all of the ripperbeasts outside the cave.", "Return to Kent to report the danger is gone."),
            reward = "1,000 XP, +4 Okara reputation and +1 Hunting skill.",
            warnings = "",
            searchTags = listOf("Malicious ripperbeasts.", "Kent", "Cave east-northeast of Okara", "SAFE")
        ),
        Quest(
            id = "G3-P2-017",
            chapter = 2,
            playOrder = 17,
            title = "Kent should go to Okara.",
            category = "SAFE",
            giver = "Kent",
            location = "Wilderness → Okara",
            prerequisites = "Complete Malicious Ripperbeasts and speak with Kent in his cave.",
            summary = "After killing the Ripperbeasts, tell Kent to join Okara and later report his recruitment to Manning.",
            walkthroughSteps = listOf("After clearing the beasts, tell Kent there is a rebel camp at Okara.", "Persuade him to join Manning there.", "Talk to Manning to record the recruitment."),
            reward = "1,000 XP, +1 Rebel reputation and +8 Okara reputation.",
            warnings = "",
            searchTags = listOf("Kent should go to Okara.", "Kent", "Wilderness → Okara", "SAFE")
        ),
        Quest(
            id = "G3-P2-018",
            chapter = 2,
            playOrder = 18,
            title = "Bring Manning some iron ore.",
            category = "SAFE",
            giver = "Manning",
            location = "Okara",
            prerequisites = "Complete Manning's six local recruitments before his smithing supplies request.",
            summary = "After progressing Manning's recruitment work, bring him five pieces of iron ore. Randall's newly cleared mine is a convenient source.",
            walkthroughSteps = listOf("Recruit Manning's workers from the surroundings of Okara, including Randall, Owen, Rakus, Candela, Fraser and Kent.", "Speak to Manning again; he asks for FIVE iron ore pieces.", "Mine the ore from Randall's now-safe mine or bring ore from another inventory source.", "Give Manning the five ore pieces."),
            reward = "1,500 XP and +8 Okara reputation; the existing guide also lists an extra 2,000 gold for this route.",
            warnings = "",
            searchTags = listOf("Bring Manning some iron ore.", "Manning", "Okara", "SAFE")
        ),
        Quest(
            id = "G3-P2-019",
            chapter = 2,
            playOrder = 19,
            title = "Take Okara apart!",
            category = "DEFER — ORC PATH",
            giver = "Orc leadership / faction route",
            location = "Okara",
            prerequisites = "",
            summary = "On a committed Orc route, attack Okara and kill enough rebels—including its leadership—for the camp to be destroyed, then report to the Orc quest giver.",
            walkthroughSteps = listOf("Varek in Montera gives this Orc-aligned destruction quest after you have enough access and have progressed the mercenary-loyalty line.", "Attack Okara and eliminate the Rebel population until the enclave is considered destroyed, then return to Varek.", "Return to the quest giver or the named destination after the objective is complete. If no completion message appears, re-check the target area for a surviving enemy, missing quest item, or an unfinished dialogue step.", "DEFER. Okara contains Roland, Manning and many recruited NPCs and is tied to numerous Rebel and main-story-adjacent quests."),
            reward = "Verified: 2500 XP, +7 Orc reputation, 2000 gold and 1500 follow-up XP from Varek.",
            warnings = "⚠ Choice warning: This quest can affect faction access, named NPCs, or later quest availability. Make a manual save before committing and finish the surrounding neutral quests first.",
            searchTags = listOf("Take Okara apart!", "Orc leadership / faction route", "Okara", "DEFER — ORC PATH")
        ),
        Quest(
            id = "G3-P2-020",
            chapter = 2,
            playOrder = 20,
            title = "Rescue Gorn from the orcs in Gotha.",
            category = "SAFE",
            giver = "Gorn and Potros (Orc overseer)",
            location = "Orc outpost below Gotha",
            prerequisites = "Reach the Orc outpost below cursed Gotha; find Gorn imprisoned there.",
            summary = "Speak with imprisoned Gorn and Potros. The cleanest neutral solution is to pay Potros the demanded ransom; alternatively the Orc outpost can be fought. Speak with Gorn once he is free.",
            walkthroughSteps = listOf("Find Orc leader Potros and imprisoned Gorn in the tower by Gotha's approach.", "Free Gorn by paying Potros's demanded ransom or defeating the Orc outpost.", "Speak with Gorn once he is free; he can help fight Gotha's demon.", "Do not kill Gorn or leave without asking for the follow-up."),
            reward = "1,500 XP and +1 Rebel reputation.",
            warnings = "Potros's ransom is a peaceful alternative. Gorn must be freed before his demon-hunting escort.",
            searchTags = listOf("Rescue Gorn from the orcs in Gotha.", "Gorn / Potros", "Orc outpost below Gotha", "SAFE")
        ),
        Quest(
            id = "G3-P2-021",
            chapter = 2,
            playOrder = 21,
            title = "Defeat Potros.",
            category = "SAFE — DUEL",
            giver = "Potros",
            location = "Orc outpost below Gotha",
            prerequisites = "Speak with Orc leader Potros at Gotha's approach tower.",
            summary = "Challenge the arrogant Potros and defeat him in the sanctioned fight. Do not turn the duel into a general attack on the camp unless that is your intention.",
            walkthroughSteps = listOf("Potros boasts about his strength and talks about captive Gorn.", "Challenge Potros to a duel INSIDE the building.", "Knock him out nonlethally; nearby Orcs normally do not join a sanctioned duel.", "After winning, discuss freeing Gorn or choose a different resolution."),
            reward = "1,500 XP and +1 Strength.",
            warnings = "A duel with Potros is not automatically a full attack on the Gotha Orc camp.",
            searchTags = listOf("Defeat Potros.", "Potros", "Orc outpost below Gotha", "SAFE — DUEL")
        ),
        Quest(
            id = "G3-P2-022",
            chapter = 2,
            playOrder = 22,
            title = "Hunting demons with Gorn.",
            category = "SAFE",
            giver = "Gorn",
            location = "Gotha ruins",
            prerequisites = "Free Gorn from Potros before entering Gotha's ruined fortress.",
            summary = "After freeing Gorn, ask him to accompany you into Gotha. Fight through zombies, skeletons and other undead together until the fortress is secure.",
            walkthroughSteps = listOf("Speak with rescued Gorn about the demon and the undead curse occupying Gotha.", "Ask Gorn to follow you into the former paladin fortress.", "Fight through skeletons and zombies until you reach the great demon in the castle courtyard.", "Defeat the demon with Gorn's help and LOOT its body: it carries the Ring of Adanos (Life)."),
            reward = "1,000 XP from the hunt, plus the Ring of Adanos (Life) from the demon.",
            warnings = "The demon's ring is one of the five ENDGAME ARTIFACTS. Loot it before you leave Gotha.",
            searchTags = listOf("Hunting demons with Gorn.", "Gorn", "Gotha ruins", "SAFE")
        ),
        Quest(
            id = "G3-P2-023",
            chapter = 2,
            playOrder = 23,
            title = "Free Gotha from its curse.",
            category = "SAFE",
            giver = "Roland (Okara Rebel leader)",
            location = "Gotha fortress",
            prerequisites = "Speak with Roland in Okara and travel to cursed Gotha.",
            summary = "Fight through the ruined settlement and castle and kill the Demon of Gotha. Loot the demon carefully, then report the success through the Gotha/Okara quest line.",
            walkthroughSteps = listOf("Accept Roland's mission to free Gotha from its undead curse.", "Rescue Gorn from Potros if desired, then fight toward Gotha castle.", "Kill the undead and the DEMON in the castle's central courtyard.", "Take the Ring of Adanos (Life) from the demon's body.", "Return to Roland and arrange Gotha's rebuilding with Shawn."),
            reward = "5,000 XP and +2 Rebel reputation; Ring of Adanos (Life) from the demon.",
            warnings = "The demon has a unique divine artifact; do not confuse Gotha's ring with the desert temple artifacts.",
            searchTags = listOf("Free Gotha from its curse.", "Gorn / Roland", "Gotha fortress", "SAFE")
        ),
        Quest(
            id = "G3-P2-024",
            chapter = 2,
            playOrder = 24,
            title = "Rebuild Gotha.",
            category = "SAFE",
            giver = "Roland → Shawn",
            location = "Okara / Gotha",
            prerequisites = "Remove Gotha's undead demon curse and secure the fortress; then speak to Roland and Shawn.",
            summary = "After the curse is removed, speak with Roland in Okara, then Shawn. Give Shawn 1,000 gold so reconstruction of Gotha can begin.",
            walkthroughSteps = listOf("This becomes available after the Demon of Gotha is defeated. Return to Roland in Okara and discuss Gotha's future.", "Roland sends you to Shawn, who sleeps in the room next to Roland. Give Shawn 1000 gold to finance reconstruction.", "Return to the quest giver or the named destination after the objective is complete. If no completion message appears, re-check the target area for a surviving enemy, missing quest item, or an unfinished dialogue step.", "This is a post-cleansing quest; killing the demon alone does not rebuild the settlement."),
            reward = "Verified: 2500 XP and +2 Rebel reputation.",
            warnings = "Rebuilding Gotha comes after cleansing the undead. The Adanos Ring of Life is dropped by the Gotha DEMON; collect it before leaving.",
            searchTags = listOf("Rebuild Gotha.", "Roland → Shawn", "Okara / Gotha", "SAFE")
        ),
        Quest(
            id = "G3-P2-025",
            chapter = 2,
            playOrder = 25,
            title = "Hothead Ben needs to be taught a lesson.",
            category = "SAFE",
            giver = "Ben (farmhand on Derec's farm)",
            location = "Farm near Trelis",
            prerequisites = "Talk to Ben at Derec's farm near Trelis.",
            summary = "Confront Ben at the farm and defeat him in the requested non-lethal lesson, then report back to the person who wanted him disciplined.",
            walkthroughSteps = listOf("Find Ben at Derec's farm and listen to him brag.", "Keep challenging his arrogance until he attacks.", "Knock him down NONLETHALLY and talk afterward."),
            reward = "500 XP and +1 Strength.",
            warnings = "Do not kill Ben; he also has the missing-shovel quest.",
            searchTags = listOf("Hothead Ben needs to be taught a lesson.", "Farm quest chain", "Farm near Trelis", "SAFE")
        ),
        Quest(
            id = "G3-P2-026",
            chapter = 2,
            playOrder = 26,
            title = "Ben the servant needs his shovel.",
            category = "SAFE",
            giver = "Ben",
            location = "Farm near Trelis",
            prerequisites = "Defeat boastful Ben at Derec's farm, then ask about his shovel.",
            summary = "Locate Ben's missing shovel around the farm/work area and return it to him.",
            walkthroughSteps = listOf("Talk to Ben after his lesson and learn he misplaced his shovel.", "Go to the temple excavation outside Trelis.", "Find his shovel stuck in a rubbish heap near the temple's entrance.", "Take the shovel back to Ben."),
            reward = "1,000 XP and +1 Thieving.",
            warnings = "",
            searchTags = listOf("Ben the servant needs his shovel.", "Ben", "Farm near Trelis", "SAFE")
        ),
        Quest(
            id = "G3-P2-027",
            chapter = 2,
            playOrder = 27,
            title = "Sneaky goblin raid on Derec's farm.",
            category = "SAFE",
            giver = "Derec (farm owner)",
            location = "Farm near Trelis",
            prerequisites = "Speak with Derec at his farm near Trelis.",
            summary = "Speak with Derec about the goblin problem and investigate the nearby raiders.",
            walkthroughSteps = listOf("Visit Derec's farm and ask about the goblins stealing from his workers.", "A goblin raid begins during his dialogue; leave the hut and fight the attackers.", "Defeat every attacking goblin and report back to Derec.", "Ask about their hiding place to start the separate goblin-cave hunt."),
            reward = "750 XP and +4 Trelis reputation.",
            warnings = "",
            searchTags = listOf("Sneaky goblin raid on Derec's farm.", "Derec", "Farm near Trelis", "SAFE")
        ),
        Quest(
            id = "G3-P2-028",
            chapter = 2,
            playOrder = 28,
            title = "Kill the thieving goblins near Derec's farm.",
            category = "SAFE",
            giver = "Derec",
            location = "Near Derec's farm",
            prerequisites = "Complete Sneaky Goblin Raid on Derec's Farm.",
            summary = "Find the goblin group responsible for the raids, kill the entire target group and return to Derec.",
            walkthroughSteps = listOf("After repelling Derec's farm raid, ask where the attackers have been hiding.", "Follow the mountain wall near Derec's farm to their cave.", "Clear all goblins inside and return to Derec."),
            reward = "1,000 XP and +8 Trelis reputation.",
            warnings = "",
            searchTags = listOf("Kill the thieving goblins near Derec's farm.", "Derec", "Near Derec's farm", "SAFE")
        ),
        Quest(
            id = "G3-P2-029",
            chapter = 2,
            playOrder = 29,
            title = "Clean out the undead caves.",
            category = "SAFE",
            giver = "Steve (Rebel hiding near Trelis)",
            location = "Caves near Trelis",
            prerequisites = "Speak with rebel Steve at the cave near Trelis.",
            summary = "Enter the indicated cave system and destroy the undead occupying it. Search the chambers before reporting completion.",
            walkthroughSteps = listOf("Find Steve among the Rebels sheltered in a cave near Trelis.", "Ask about the undead that have infested the neighboring cavern.", "Clear every skeleton and other undead in the cave.", "Report the cleared cave to Steve."),
            reward = "1,500 XP and +1 Rebel reputation.",
            warnings = "",
            searchTags = listOf("Clean out the undead caves.", "Trelis-area quest giver", "Caves near Trelis", "SAFE")
        ),
        Quest(
            id = "G3-P2-030",
            chapter = 2,
            playOrder = 30,
            title = "Destroy the orcs in and around the temple of Trelis.",
            category = "CHOICE — REBEL",
            giver = "Charles (Rebel leader near Trelis)",
            location = "Eastern temple near Trelis",
            prerequisites = "Meet Charles's Rebels at the cave by the Trelis eastern temple.",
            summary = "Attack and eliminate the Orc force occupying the temple and its immediate surroundings.",
            walkthroughSteps = listOf("Meet Rebel leader Charles and investigate the Orc occupation of Trelis's eastern temple.", "Finish Tempeck's and Kamak's peaceful temple quests if you want their XP first.", "Return with Charles's rebellion plan and attack the Orc guards at the excavation.", "Kill the Orc officers Tempeck and Kamak along with the occupation, then report to Charles."),
            reward = "1,500 XP and +2 Rebel reputation.",
            warnings = "Kills KAMAK and TEMPECK. Complete their temple-survivor and escort quests before choosing the attack.",
            searchTags = listOf("Destroy the orcs in and around the temple of Trelis.", "Rebel/temple quest chain", "Eastern temple near Trelis", "CHOICE — REBEL")
        ),
        Quest(
            id = "G3-P2-031",
            chapter = 2,
            playOrder = 31,
            title = "Kamak's artifact.",
            category = "SAFE / CHOICE",
            giver = "Peer / Dudley (Kamak artifact lead)",
            location = "Temple of Trelis",
            prerequisites = "Talk to Peer at the Trelis farm or Dudley at Nemora about Kamak.",
            summary = "Recover the artifact associated with shaman Kamak during the temple quest chain and resolve it through his dialogue.",
            walkthroughSteps = listOf("Ask Peer or Dudley about the valuable artifact carried by Orc shaman Kamak.", "Find Kamak deep in the Trelis temple excavation.", "He carries the artifact on his person, so sneaking into a chest will not recover it.", "Knock Kamak unconscious after protecting yourself from guard intervention, or choose the Rebel attack that kills the temple Orcs.", "Loot his artifact and complete the relevant dialogue."),
            reward = "500 XP and +1 Thieving.",
            warnings = "Kamak is a named shaman, not a chest location. Violence may turn nearby Orcs hostile; save first.",
            searchTags = listOf("Kamak's artifact.", "Kamak", "Temple of Trelis", "SAFE / CHOICE")
        ),
        Quest(
            id = "G3-P2-032",
            chapter = 2,
            playOrder = 32,
            title = "Tell the leader of Nemora about the rebels' situation at the temple of Trelis.",
            category = "SAFE — REBEL",
            giver = "Charles (Rebel leader near Trelis)",
            location = "Temple → Nemora",
            prerequisites = "Find Charles in the rebels' cave by the eastern temple.",
            summary = "Carry the rebels' report from the Trelis temple to the leadership of Nemora.",
            walkthroughSteps = listOf("Speak to Charles about his fighters' situation.", "Travel to Nemora and learn which resident actually leads the Rebels there.", "Report the plea for help to the Nemora leader.", "Return to Charles or carry the leader's message as the journal requests."),
            reward = "1,000 XP and +1 Rebel reputation.",
            warnings = "Finding Nemora's leader requires completing its local introduction quests first.",
            searchTags = listOf("Tell the leader of Nemora about the rebels' situation at the temple of Trelis.", "Rebels at temple", "Temple → Nemora", "SAFE — REBEL")
        ),
        Quest(
            id = "G3-P2-033",
            chapter = 2,
            playOrder = 33,
            title = "No deliveries arriving from the eastern temple.",
            category = "SAFE",
            giver = "Thorus (Trelis front gate)",
            location = "Trelis → eastern temple",
            prerequisites = "Ask Thorus at Trelis why supplies from the eastern temple have stopped.",
            summary = "Investigate why the expected deliveries from the eastern temple have stopped. Travel to the temple and determine what happened.",
            walkthroughSteps = listOf("Speak with Thorus at the main gate of Trelis about the overdue temple deliveries.", "Go to the eastern excavation and locate Orc supervisor Tempeck.", "Ask Tempeck why no supplies are arriving; he explains the undead infestation.", "Return to Thorus with his report."),
            reward = "1,500 XP and +8 Trelis reputation.",
            warnings = "",
            searchTags = listOf("No deliveries arriving from the eastern temple.", "Trelis Orcs", "Trelis → eastern temple", "SAFE")
        ),
        Quest(
            id = "G3-P2-034",
            chapter = 2,
            playOrder = 34,
            title = "Search for survivors in the temple of Trelis.",
            category = "SAFE",
            giver = "Tempeck (Orc guard captain)",
            location = "Eastern temple",
            prerequisites = "Reach the eastern Trelis temple and speak with Tempeck.",
            summary = "Search the temple area after the fighting and locate surviving named NPCs, including Kamak where applicable.",
            walkthroughSteps = listOf("Find Tempeck guarding the excavation by the temple.", "Enter the temple depths to check for survivors; prepare for skeletons, zombies and a fast poisonous scorpionlike mutant.", "Find shaman Kamak on the lowest temple level.", "Report Kamak's survival to Tempeck."),
            reward = "1,000 XP and +8 Trelis reputation.",
            warnings = "Kamak is found on the lowest level and is required alive for his subsequent escort quest.",
            searchTags = listOf("Search for survivors in the temple of Trelis.", "Temple quest chain", "Eastern temple", "SAFE")
        ),
        Quest(
            id = "G3-P2-035",
            chapter = 2,
            playOrder = 35,
            title = "Help the shaman Kamak leave the temple.",
            category = "SAFE / ORC-FRIENDLY",
            giver = "Kamak (Orc shaman)",
            location = "Eastern temple → safety/Trelis",
            prerequisites = "Find Kamak alive during Search for Survivors in the Temple of Trelis.",
            summary = "Escort or otherwise help Kamak leave the dangerous temple area alive.",
            walkthroughSteps = listOf("Fight down into the Trelis temple and reach shaman Kamak at the lowest level.", "Ask him to follow you back to the surface.", "Escort him through remaining undead and back to the guarded entrance.", "Finish his dialogue outside the temple."),
            reward = "1,000 XP and +8 Trelis reputation.",
            warnings = "Finish this rescue BEFORE taking Charles's rival mission to exterminate the temple Orcs.",
            searchTags = listOf("Help the shaman Kamak leave the temple.", "Kamak", "Eastern temple → safety/Trelis", "SAFE / ORC-FRIENDLY")
        ),
        Quest(
            id = "G3-P2-036",
            chapter = 2,
            playOrder = 36,
            title = "Kill the sneaky ogres in the woods.",
            category = "SAFE",
            giver = "Thorus (Trelis gate guard)",
            location = "Woods near Trelis",
            prerequisites = "Talk to Thorus about ogres in the woods by Trelis.",
            summary = "Track down the ogres hiding in the nearby woods and kill the complete target group, then report back.",
            walkthroughSteps = listOf("Ask Thorus about the dangerous ogres lurking outside Trelis.", "Enter the wooded cave he identifies near the town.", "There are FIVE ogres; pull them out one at a time and retreat to heal.", "Kill all five and report to Thorus."),
            reward = "1,250 XP and +8 Trelis reputation.",
            warnings = "Five ogres can overpower melee players if attacked together.",
            searchTags = listOf("Kill the sneaky ogres in the woods.", "Trelis-area NPC", "Woods near Trelis", "SAFE")
        ),
        Quest(
            id = "G3-P2-037",
            chapter = 2,
            playOrder = 37,
            title = "Find out what is wrong with the western farm.",
            category = "SAFE",
            giver = "Kapotth (Orc farm commander)",
            location = "Western farm",
            prerequisites = "Meet Kapotth at the western farm near Trelis.",
            summary = "Travel to the western farm and investigate why it has stopped functioning normally. Speak with survivors and inspect the area.",
            walkthroughSteps = listOf("Ask Kapotth why his workers cannot use the nearby area.", "Locate the cave near the western farm.", "Kill the sabertooth cats infesting the cave.", "Return to Kapotth."),
            reward = "1,250 XP and +8 Trelis reputation.",
            warnings = "",
            searchTags = listOf("Find out what is wrong with the western farm.", "Trelis quest chain", "Western farm", "SAFE")
        ),
        Quest(
            id = "G3-P2-038",
            chapter = 2,
            playOrder = 38,
            title = "The suspicious cave near the farm.",
            category = "SAFE",
            giver = "Thorus",
            location = "Cave near western farm",
            prerequisites = "Speak to Thorus about the suspicious cave near the farm.",
            summary = "Explore the suspicious cave near the farm and deal with the creatures or evidence inside, then report what you found.",
            walkthroughSteps = listOf("Thorus asks you to investigate suspicious activity near the western Trelis farm.", "Travel to the farm and question Orc commander Kapotth.", "Follow the related farm threat report and return to Thorus."),
            reward = "1,500 XP and +8 Trelis reputation.",
            warnings = "",
            searchTags = listOf("The suspicious cave near the farm.", "Western farm quest chain", "Cave near western farm", "SAFE")
        ),
        Quest(
            id = "G3-P2-039",
            chapter = 2,
            playOrder = 39,
            title = "Did the rangers devastate the farm?",
            category = "SAFE / INVESTIGATION",
            giver = "Kapotth",
            location = "Western farm / ranger territory",
            prerequisites = "Ask Kapotth about who damaged the western Trelis farm.",
            summary = "Investigate whether the nearby Rangers were actually responsible for the farm's destruction and report the result through the quest dialogue.",
            walkthroughSteps = listOf("Kapotth blames the Rangers for the damage at the farm.", "Travel north toward the road to Geldern to find the Rangers' cave on a cliff.", "Speak to the Druid leading their camp about the accusation.", "Report the actual account back to Kapotth."),
            reward = "1,000 XP and +8 Trelis reputation.",
            warnings = "Question the Ranger leader before attacking. Kapotth's accusation does not prove the Rangers are guilty.",
            searchTags = listOf("Did the rangers devastate the farm?", "Western farm quest chain", "Western farm / ranger territory", "SAFE / INVESTIGATION")
        ),
        Quest(
            id = "G3-P2-040",
            chapter = 2,
            playOrder = 40,
            title = "Ransack the castle of Trelis.",
            category = "DEFER / THIEVERY",
            giver = "Peer (farm near Trelis)",
            location = "Trelis castle",
            prerequisites = "Talk to Peer about robbing the castle of Trelis.",
            summary = "Steal the required valuables from the castle without triggering a premature town-wide battle.",
            walkthroughSteps = listOf("Ask Peer about his plans for a profitable raid.", "Enter Trelis castle discreetly and find the cellar beneath Vak's quarters.", "Loot the designated chests, avoiding Orc witnesses.", "Report the completed raid to Peer."),
            reward = "2,500 XP and +1 Thieving.",
            warnings = "Complete before a hostile uprising if you want the stealth approach.",
            searchTags = listOf("Ransack the castle of Trelis.", "Faction/loot quest", "Trelis castle", "DEFER / THIEVERY")
        ),
        Quest(
            id = "G3-P2-041",
            chapter = 2,
            playOrder = 41,
            title = "Ransack the farms!",
            category = "DEFER / THIEVERY",
            giver = "Peer (farmer and thief)",
            location = "Farms around Trelis",
            prerequisites = "Speak to Peer at Josh's farm about raiding other farms.",
            summary = "Loot the specified farm valuables for the quest giver while keeping the broader Trelis quest network intact.",
            walkthroughSteps = listOf("Peer asks you to steal valuable supplies from the nearby farm.", "Travel to the second farm and find the chest in Dudley's hut.", "Open and loot the chest, then return to Peer."),
            reward = "1,250 XP and +1 Thieving.",
            warnings = "⚠ Choice warning: This quest can affect faction access, named NPCs, or later quest availability. Make a manual save before committing and finish the surrounding neutral quests first.",
            searchTags = listOf("Ransack the farms!", "Faction/loot quest", "Farms around Trelis", "DEFER / THIEVERY")
        ),
        Quest(
            id = "G3-P2-042",
            chapter = 2,
            playOrder = 42,
            title = "The paladin Konrad wants his magic back.",
            category = "SAFE — FIRE CHALICE",
            giver = "Konrad",
            location = "Trelis",
            prerequisites = "Obtain a blessed Fire Chalice from the Monastery sacred fire and return to Konrad.",
            summary = "Speak with Konrad about the loss of paladin magic and progress the global Fire Chalice quest so his power can eventually be restored.",
            walkthroughSteps = listOf("Speak with paladin Konrad at Trelis about his lost Innos magic.", "Collect all twelve Fire Chalices and bless them at the sacred fire in the Nordmar Monastery.", "Bring ONE Blessed Fire Chalice back to Konrad; an unblessed chalice cannot restore him."),
            reward = "2,500 XP, +1 Rebel reputation and 500 gold.",
            warnings = "You need a BLESSED chalice, not the basic chalice Konrad initially hands over.",
            searchTags = listOf("The paladin Konrad wants his magic back.", "Konrad", "Trelis", "SAFE — FIRE CHALICE")
        ),
        Quest(
            id = "G3-P2-043",
            chapter = 2,
            playOrder = 43,
            title = "The orc warrior Pranck needs healing potions.",
            category = "SAFE",
            giver = "Pranck (Orc warrior)",
            location = "Trelis",
            prerequisites = "Speak to Pranck inside Trelis castle and offer a modest healing potion supply.",
            summary = "Give Pranck the initial healing potions he requests.",
            walkthroughSteps = listOf("Find Orc warrior Pranck at Trelis castle.", "When he asks for healing potions, confidently offer only ONE.", "Give the potion to Pranck; this opens his missing-alchemist investigation."),
            reward = "500 XP and +4 Trelis reputation.",
            warnings = "Do not timidly ask how many he wants; that dialogue can trigger a timed TWENTY-potion demand instead.",
            searchTags = listOf("The orc warrior Pranck needs healing potions.", "Pranck", "Trelis", "SAFE")
        ),
        Quest(
            id = "G3-P2-044",
            chapter = 2,
            playOrder = 44,
            title = "Find the runaway alchemist Avogadro.",
            category = "SAFE",
            giver = "Pranck",
            location = "Trelis countryside",
            prerequisites = "Complete Pranck's initial potion discussion and accept his search for Avogadro.",
            summary = "Search the countryside for Avogadro, the missing alchemist, and speak with him about returning.",
            walkthroughSteps = listOf("Ask Pranck what happened to alchemist Avogadro.", "Search Josh's farm outside Trelis; Avogadro is hiding there.", "Speak with Avogadro and instruct him to return to Trelis.", "Report the location to Pranck; escort him for the separate follow-up."),
            reward = "1,000 XP and +4 Trelis reputation.",
            warnings = "",
            searchTags = listOf("Find the runaway alchemist Avogadro.", "Pranck / Avogadro", "Trelis countryside", "SAFE")
        ),
        Quest(
            id = "G3-P2-045",
            chapter = 2,
            playOrder = 45,
            title = "Take Avogadro the alchemist to Trelis.",
            category = "SAFE",
            giver = "Avogadro",
            location = "Countryside → Trelis",
            prerequisites = "Locate Avogadro at Josh's farm for Pranck.",
            summary = "Escort Avogadro safely back to Trelis and complete the handover to the Orcs.",
            walkthroughSteps = listOf("After finding Avogadro at Josh's farm, ask him to return to Trelis.", "Escort Avogadro safely along the road back to the castle.", "Talk to him and Pranck when he reaches the town."),
            reward = "1,000 XP, +8 Trelis reputation and +1 Alchemy.",
            warnings = "",
            searchTags = listOf("Take Avogadro the alchemist to Trelis.", "Avogadro", "Countryside → Trelis", "SAFE")
        ),
        Quest(
            id = "G3-P2-046",
            chapter = 2,
            playOrder = 46,
            title = "The orc warrior Pranck wants twenty healing potions.",
            category = "SAFE",
            giver = "Pranck",
            location = "Trelis",
            prerequisites = "Take the demanding response in Pranck's potion conversation at Trelis.",
            summary = "After the alchemist chain progresses, collect twenty Healing Potions and deliver them to Pranck.",
            walkthroughSteps = listOf("Ask Pranck how many healing potions he wants rather than offering only one.", "He demands TWENTY Healing Potions and gives you TWO days.", "Buy or brew the full twenty and give them to Pranck before his deadline."),
            reward = "1,500 XP and +4 Trelis reputation.",
            warnings = "TWO-DAY deadline. Can be avoided by offering a single potion in Pranck's other quest.",
            searchTags = listOf("The orc warrior Pranck wants twenty healing potions.", "Pranck", "Trelis", "SAFE")
        ),
        Quest(
            id = "G3-P2-047",
            chapter = 2,
            playOrder = 47,
            title = "Milok is looking for his old sword.",
            category = "SAFE",
            giver = "Milok (Trelis blacksmith)",
            location = "Trelis",
            prerequisites = "Speak to Milok about his missing sword.",
            summary = "Find Milok's old sword in the location indicated by his clues/quest context and return it to him.",
            walkthroughSteps = listOf("Ask smith Milok where his old sword went.", "Travel to the eastern temple excavation controlled by Tempeck.", "Search the CART near Tempeck's position; Milok's old sword lies there.", "Take the sword back to Milok."),
            reward = "1,000 XP and +4 Trelis reputation.",
            warnings = "The old sword is on a cart at the temple excavation, not an enemy's body.",
            searchTags = listOf("Milok is looking for his old sword.", "Milok", "Trelis", "SAFE")
        ),
        Quest(
            id = "G3-P2-048",
            chapter = 2,
            playOrder = 48,
            title = "Kill the grunting creatures below Josh's farm.",
            category = "SAFE",
            giver = "Josh (farmer)",
            location = "Farm near Trelis",
            prerequisites = "Talk to Josh at his hilltop farm near Trelis.",
            summary = "Go below/behind Josh's farm and kill the noisy creatures troubling the area, then return to Josh.",
            walkthroughSteps = listOf("Josh reports creatures growling below his farm.", "Find one of two entrances to the cave beneath the hill.", "Kill the Ripperbeasts. The upper entrance lets you shoot from elevation rather than fight at close quarters.", "Return to Josh when the cave is clear."),
            reward = "1,000 XP and +8 Trelis reputation.",
            warnings = "",
            searchTags = listOf("Kill the grunting creatures below Josh's farm.", "Josh", "Farm near Trelis", "SAFE")
        ),
        Quest(
            id = "G3-P2-049",
            chapter = 2,
            playOrder = 49,
            title = "Vak needs fifty thousand gold coins for the Hashishin.",
            category = "CHOICE — MAJOR PAYMENT",
            giver = "Vak",
            location = "Trelis castle",
            prerequisites = "Gain access to Vak in Trelis; discuss the 50,000-gold Hashishin debt.",
            summary = "Vak needs 50,000 gold connected with the Hashishin arrangement. Accumulate the money and pay him only if you want to resolve the quest through his faction route.",
            walkthroughSteps = listOf("After earning access to Trelis castle, speak with Vak. He owes the Hashishin 50,000 gold and allows you to keep rent collected around Trelis if you agree to solve the debt.", "Raise the full 50,000 gold and pay Vak. The farm rents cover only a small fraction, so most of the sum normally comes from your own funds.", "Return to the quest giver or the named destination after the objective is complete. If no completion message appears, re-check the target area for a surviving enemy, missing quest item, or an unfinished dialogue step.", "This is a MAIN-STORY SIGNIFICANT quest: Vak gives you the Amulet of Adanos, one of the five divine artifacts. Do not treat the payment as a disposable side quest."),
            reward = "Verified: 5000 XP, +7 Orc reputation and the Amulet of Adanos; Khabir also has a related reward.",
            warnings = "50,000 GOLD IS A PAYMENT, not a reward. Vak holds the Amulet of Adanos; save before liberation as killing him changes the alternative acquisition route.",
            searchTags = listOf("Vak needs fifty thousand gold coins for the Hashishin.", "Vak", "Trelis castle", "CHOICE — MAJOR PAYMENT")
        ),
        Quest(
            id = "G3-P2-050",
            chapter = 2,
            playOrder = 50,
            title = "Conquer the castle of Trelis!",
            category = "DEFER — REBEL PATH",
            giver = "Rebel/Nemora route",
            location = "Trelis",
            prerequisites = "Finish all wanted Trelis quests, particularly Vak's divine artifact and Konrad's chalice dialogue.",
            summary = "When you have finished the peaceful Trelis content and deliberately choose the Rebel attack, assault the castle and defeat enough Orc forces for Trelis to fall.",
            walkthroughSteps = listOf("Konrad can help initiate the Rebel uprising in Trelis, especially after his paladin magic has been restored.", "Attack the Orc occupation and kill enough defenders for the remaining Orcs to flee. Keep important allies alive where possible.", "Return to the quest giver or the named destination after the objective is complete. If no completion message appears, re-check the target area for a surviving enemy, missing quest item, or an unfinished dialogue step.", "DEFER until every peaceful Trelis quest is complete, including Vak's artifact/payment route if you intend to obtain the Amulet of Adanos that way."),
            reward = "Verified: 7500 XP, +5 Rebel reputation and 1500 XP from Konrad.",
            warnings = "Trelis liberation is a counted strike in the Orc three-city hostility system. Finish quests and secure the Amulet of Adanos first.",
            searchTags = listOf("Conquer the castle of Trelis!", "Rebel/Nemora route", "Trelis", "DEFER — REBEL PATH")
        ),
        Quest(
            id = "G3-P2-051",
            chapter = 2,
            playOrder = 51,
            title = "Rebels stole the rent from Farmon's farm.",
            category = "SAFE / INVESTIGATION",
            giver = "Farmon / Nemora chain",
            location = "Farm near Nemora",
            prerequisites = "",
            summary = "Investigate the stolen rent and follow the trail to the rebels involved. Resolve the matter through the Nemora dialogue chain.",
            walkthroughSteps = listOf("Farmon, south of Trelis, says Rebels from Nemora stole the rent he owes.", "In Nemora, speak with Hengley. He admits responsibility and hands over the stolen rent. Return through the quest dialogue to close Farmon's problem.", "Return to the quest giver or the named destination after the objective is complete. If no completion message appears, re-check the target area for a surviving enemy, missing quest item, or an unfinished dialogue step.", "Do not confuse recovering the rent with judging Hengley; “Hengley the farm raider” is a separate follow-up resolved with Russel."),
            reward = "Verified: 1000 XP, 1000 gold recovered from Hengley and an additional 500 XP from Farmon.",
            warnings = "",
            searchTags = listOf("Rebels stole the rent from Farmon's farm.", "Farmon / Nemora chain", "Farm near Nemora", "SAFE / INVESTIGATION")
        ),
        Quest(
            id = "G3-P2-052",
            chapter = 2,
            playOrder = 52,
            title = "Cole the farmhand wants to go to Nemora.",
            category = "SAFE — REBEL",
            giver = "Cole",
            location = "Farm → Nemora",
            prerequisites = "Find Cole on a farm near Trelis and agree to help him reach Nemora.",
            summary = "Agree to take Cole to Nemora and escort him safely to the rebel camp.",
            walkthroughSteps = listOf("Meet Cole at the farm near Trelis.", "Tell him he can join the rebel camp in Nemora.", "Escort him safely through the wilderness, clearing enemies ahead.", "Talk to Cole when you reach Nemora."),
            reward = "500 XP and +1 Rebel reputation.",
            warnings = "Cole is vulnerable while following; do not sprint into dangerous beasts.",
            searchTags = listOf("Cole the farmhand wants to go to Nemora.", "Cole", "Farm → Nemora", "SAFE — REBEL")
        ),
        Quest(
            id = "G3-P2-053",
            chapter = 2,
            playOrder = 53,
            title = "A new man for Nemora.",
            category = "SAFE",
            giver = "Russel (leader of Nemora)",
            location = "Nemora region",
            prerequisites = "Speak with Russel about recruiting useful people to Nemora.",
            summary = "Recruit the required useful newcomer for Nemora and report the successful addition to the camp.",
            walkthroughSteps = listOf("Talk to Russel in Nemora about finding a new fighter.", "Find paladin Karlen camping near the Varant pass.", "Complete Karlen's tasks against renegade paladin Kurt and his bandits.", "Ask Karlen to join Nemora after he trusts you.", "Return to Russel to confirm the new recruit."),
            reward = "1,500 XP and +10 Nemora reputation.",
            warnings = "The intended new recruit is PALADIN KARLEN, not a random unnamed farmhand.",
            searchTags = listOf("A new man for Nemora.", "Nemora recruitment chain", "Nemora region", "SAFE")
        ),
        Quest(
            id = "G3-P2-054",
            chapter = 2,
            playOrder = 54,
            title = "Karlen the paladin wants his magic back.",
            category = "SAFE — FIRE CHALICE",
            giver = "Karlen",
            location = "Nemora",
            prerequisites = "Collect 12 Fire Chalices and bless them at the sacred fire in the Nordmar Monastery.",
            summary = "Speak with Karlen about restoring his lost paladin magic and keep him in mind for the global blessed Fire Chalice objective.",
            walkthroughSteps = listOf("Karlen is found near Nemora and later may be inside the camp. Like Konrad, he needs a Blessed Fire Chalice, not an unblessed one.", "Complete the sacred-fire stage of the global Fire Chalice quest, then return one Blessed Fire Chalice to Karlen.", "Return to the quest giver or the named destination after the objective is complete. If no completion message appears, re-check the target area for a surviving enemy, missing quest item, or an unfinished dialogue step.", "Keep Karlen alive through his pass-to-Varant quests so you can finish this later."),
            reward = "Verified: 2500 XP, +1 Rebel reputation and ten Healing Potions.",
            warnings = "Keep Karlen alive during his Varant-pass quests. An UNBLESSED Fire Chalice does not complete his magic-restoration task.",
            searchTags = listOf("Karlen the paladin wants his magic back.", "Karlen", "Nemora", "SAFE — FIRE CHALICE")
        ),
        Quest(
            id = "G3-P2-055",
            chapter = 2,
            playOrder = 55,
            title = "The renegade paladin at the pass to Varant must die.",
            category = "SAFE / COMBAT",
            giver = "Karlen",
            location = "Pass toward Varant",
            prerequisites = "Meet paladin Karlen at Nemora and escort him toward the Varant pass.",
            summary = "Accompany or follow Karlen's instructions to find the renegade paladin at the desert pass and defeat him.",
            walkthroughSteps = listOf("Karlen sits at a campfire south of Nemora and wants to confront Kurt, a renegade paladin on the pass toward Varant.", "Travel with Karlen to the pass and kill Kurt. Search Kurt's body after the fight.", "Return to the quest giver or the named destination after the objective is complete. If no completion message appears, re-check the target area for a surviving enemy, missing quest item, or an unfinished dialogue step.", "Kurt carries one of the twelve Fire Chalices. Looting him is essential for the global Fire Chalice quest."),
            reward = "Verified: 1500 XP, +1 Rebel reputation, 1000 gold and 1000 follow-up XP from Karlen, plus Kurt's Fire Chalice.",
            warnings = "Renegade paladin Kurt's FIRE CHALICE is in his locked CHEST. Loot the chest using the key, not just Kurt's body.",
            searchTags = listOf("The renegade paladin at the pass to Varant must die.", "Karlen", "Pass toward Varant", "SAFE / COMBAT")
        ),
        Quest(
            id = "G3-P2-056",
            chapter = 2,
            playOrder = 56,
            title = "Cross the pass to Varant with Karlen.",
            category = "SAFE",
            giver = "Karlen",
            location = "Nemora → Varant pass",
            prerequisites = "Join Karlen in his mission to the pass toward Varant.",
            summary = "Travel with Karlen through the pass toward Varant, protecting him from enemies along the route.",
            walkthroughSteps = listOf("Meet paladin Karlen near Nemora and ask to accompany his journey.", "Follow him through the pass toward Varant and fight any bandits on the route.", "Avoid losing Karlen in the hills, and finish the crossing dialogue."),
            reward = "1,500 XP and +1 Rebel reputation.",
            warnings = "Do not leave Kurt's encampment before looting the fire chalice from its chest. Karlen's escort and the renegade-paladin fight are linked.",
            searchTags = listOf("Cross the pass to Varant with Karlen.", "Karlen", "Nemora → Varant pass", "SAFE")
        ),
        Quest(
            id = "G3-P2-057",
            chapter = 2,
            playOrder = 57,
            title = "Karlen the paladin shows you the desert.",
            category = "SAFE",
            giver = "Karlen",
            location = "Varant border",
            prerequisites = "Finish the fight against renegade paladin Kurt and cross the Varant pass with Karlen.",
            summary = "Continue with Karlen after crossing the pass until he has shown you the desert route and the quest completes.",
            walkthroughSteps = listOf("After killing renegade Kurt, tell Karlen to guide you to the desert.", "Follow Karlen down the passage and into Varant.", "Talk to him at his destination to finish the introduction."),
            reward = "500 XP.",
            warnings = "",
            searchTags = listOf("Karlen the paladin shows you the desert.", "Karlen", "Varant border", "SAFE")
        ),
        Quest(
            id = "G3-P2-058",
            chapter = 2,
            playOrder = 58,
            title = "Bring Russel the goods from the desert.",
            category = "SAFE",
            giver = "Russel (Nemora leader)",
            location = "Nemora / Varant border",
            prerequisites = "Meet Russel and ask about missing supplies from the Varant border.",
            summary = "Recover or collect the requested shipment/goods from the desert side and deliver them to Russel in Nemora.",
            walkthroughSteps = listOf("Speak to Russel about goods left near the desert.", "Travel to the BORDER TENT at the entrance to Varant.", "Defeat the snappers around the tent; watch for strong nearby trolls.", "Take the marked supply goods from the tent and return them to Russel."),
            reward = "1,000 XP and +15 Nemora reputation.",
            warnings = "Goods are at a TENT on the Varant border, guarded by snappers, not in a town or on a merchant.",
            searchTags = listOf("Bring Russel the goods from the desert.", "Russel", "Nemora / Varant border", "SAFE")
        ),
        Quest(
            id = "G3-P2-059",
            chapter = 2,
            playOrder = 59,
            title = "Who's boss in Nemora?",
            category = "SAFE",
            giver = "Nemora residents",
            location = "Nemora",
            prerequisites = "",
            summary = "Ask around and complete enough work for the camp to earn trust. The identity of Nemora's actual leader is revealed only after you have sufficiently proven yourself.",
            walkthroughSteps = listOf("Nemora intentionally hides its leader. Asking around at low reputation will not reveal him.", "Complete Nemora quests until you reach at least 75% reputation. Then speak with Russel again; he reveals that he is the camp's leader and the quest completes.", "Return to the quest giver or the named destination after the objective is complete. If no completion message appears, re-check the target area for a surviving enemy, missing quest item, or an unfinished dialogue step.", "This gates other quests. Charles's message about the Trelis temple cannot be properly delivered until you know Russel is the leader."),
            reward = "Verified: 2500 XP and +2 Rebel reputation.",
            warnings = "",
            searchTags = listOf("Who's boss in Nemora?", "Nemora residents", "Nemora", "SAFE")
        ),
        Quest(
            id = "G3-P2-060",
            chapter = 2,
            playOrder = 60,
            title = "Kill the three monsters north of Nemora.",
            category = "SAFE",
            giver = "Rendell (north entrance guard)",
            location = "North of Nemora",
            prerequisites = "Find Rendell guarding Nemora's northern approach.",
            summary = "Find the three dangerous monsters north of the camp, kill all three and report back.",
            walkthroughSteps = listOf("Ask Rendell about the dangerous creatures prowling north of Nemora.", "Go north along the trail and kill THREE snorting beasts.", "Return to Rendell; harvest nearby herbs while there for Treslott's assignment."),
            reward = "1,500 XP and +20 Nemora reputation.",
            warnings = "",
            searchTags = listOf("Kill the three monsters north of Nemora.", "Nemora quest giver", "North of Nemora", "SAFE")
        ),
        Quest(
            id = "G3-P2-061",
            chapter = 2,
            playOrder = 61,
            title = "Weapons for Nemora.",
            category = "SAFE",
            giver = "Dudley (Nemora quartermaster)",
            location = "Nemora",
            prerequisites = "Talk to Dudley about weapon supplies in Nemora.",
            summary = "Collect the requested Bundles of Weapons and deliver them to Nemora.",
            walkthroughSteps = listOf("Find quartermaster Dudley in Nemora's rebel caves.", "He needs TEN Weapon Bundles.", "Loot bundles from Orc posts, Trelis farms, or the eastern temple; ordinary swords do not count.", "Deliver all ten bundles to Dudley."),
            reward = "1,000 XP, +15 Nemora reputation and +1 Thieving.",
            warnings = "",
            searchTags = listOf("Weapons for Nemora.", "Nemora quartermaster/rebels", "Nemora", "SAFE")
        ),
        Quest(
            id = "G3-P2-062",
            chapter = 2,
            playOrder = 62,
            title = "Clear the orcs out of the farm west of Trelis.",
            category = "SAFE — REBEL",
            giver = "Kippler (Nemora Rebel)",
            location = "Farm west of Trelis",
            prerequisites = "Meet Kippler at Nemora and ask how to weaken Trelis's Orcs.",
            summary = "Attack the Orc group occupying the farm west of Trelis and eliminate them, then report back to Nemora.",
            walkthroughSteps = listOf("Ask Kippler about the Orc garrison at the western farm.", "Travel to the farm occupied by Kapotth's warriors near Trelis.", "Kill the Orc guards and return to Kippler."),
            reward = "1,500 XP, +1 Rebel reputation and +20 Nemora reputation.",
            warnings = "Clear Kapotth's peaceful farm quests first if you want those rewards.",
            searchTags = listOf("Clear the orcs out of the farm west of Trelis.", "Nemora rebels", "Farm west of Trelis", "SAFE — REBEL")
        ),
        Quest(
            id = "G3-P2-063",
            chapter = 2,
            playOrder = 63,
            title = "Bring Treslott the rare plant herbaceous lobelia.",
            category = "SAFE",
            giver = "Treslott (Fire Mage in Nemora)",
            location = "Nemora region",
            prerequisites = "Speak with Treslott about a rare medicinal herb and his Fire Chalice.",
            summary = "Find the rare herbaceous lobelia requested by Treslott and bring it back to him.",
            walkthroughSteps = listOf("Ask Treslott in Nemora which herb he needs.", "Find FIVE Herbaceous Lobelia plants in the northern Nemora hills; the same area has Rendell's three monsters.", "Collect and hand him all five Lobelia plants.", "Speak to Treslott again for his FIRE CHALICE, then preserve it for the global twelve-chalice set."),
            reward = "1,000 XP, +15 Nemora reputation and +1 Alchemy; Treslott's Fire Chalice becomes available.",
            warnings = "FIVE Herbaceous Lobelia plants are required, not one. Treslott holds one of the 12 Fire Chalices.",
            searchTags = listOf("Bring Treslott the rare plant herbaceous lobelia.", "Treslott", "Nemora region", "SAFE")
        ),
        Quest(
            id = "G3-P2-064",
            chapter = 2,
            playOrder = 64,
            title = "Hengley the farm raider.",
            category = "CHOICE / JUSTICE",
            giver = "Nemora / Farmon chain",
            location = "Nemora",
            prerequisites = "",
            summary = "Confront the issue of Hengley's raid on Farmon's farm and resolve it through the camp leadership once you have the evidence/dialogue required.",
            walkthroughSteps = listOf("After learning that Hengley raided Farmon's farm, you can eventually report his behavior to Nemora's true leader.", "First reach 75% Nemora reputation and discover that Russel is the boss. Then tell Russel about Hengley to resolve the disciplinary quest.", "Return to the quest giver or the named destination after the objective is complete. If no completion message appears, re-check the target area for a surviving enemy, missing quest item, or an unfinished dialogue step.", "This is directly tied to “Who's boss in Nemora?”; trying to finish it too early leaves you without the correct authority to report to."),
            reward = "Verified: 1000 XP and 200 gold from Russel.",
            warnings = "⚠ Choice warning: This quest can affect faction access, named NPCs, or later quest availability. Make a manual save before committing and finish the surrounding neutral quests first.",
            searchTags = listOf("Hengley the farm raider.", "Nemora / Farmon chain", "Nemora", "CHOICE / JUSTICE")
        ),
        Quest(
            id = "G3-P2-065",
            chapter = 2,
            playOrder = 65,
            title = "A message for the rebel Charles.",
            category = "SAFE — REBEL",
            giver = "Russel (Nemora's Rebel leader)",
            location = "Nemora → Charles",
            prerequisites = "Meet rebel Charles and carry his request for more men to Nemora's leader.",
            summary = "Carry the message from Nemora to the rebel Charles and deliver it.",
            walkthroughSteps = listOf("Talk to Charles in his cave near the Trelis eastern temple.", "Travel to Nemora and complete its tasks to learn Russel's leadership identity.", "Tell Russel about Charles's shortage of reinforcements.", "Take Russel's message back to Charles."),
            reward = "1,000 XP.",
            warnings = "",
            searchTags = listOf("A message for the rebel Charles.", "Nemora quest chain", "Nemora → Charles", "SAFE — REBEL")
        ),
        Quest(
            id = "G3-P2-066",
            chapter = 2,
            playOrder = 66,
            title = "Finley gets all set to attack Trelis.",
            category = "DEFER — REBEL PREP",
            giver = "Finley",
            location = "Nemora",
            prerequisites = "Prepare for the Rebel assault on Trelis and recruit Finley in Nemora.",
            summary = "After the required Nemora/Trelis conditions are met, tell Finley to prepare for the attack on Trelis.",
            walkthroughSteps = listOf("Talk to Finley in Nemora when ready to attack Trelis.", "Allow Finley to follow you toward Trelis, watching for rhinos on the route.", "Leave him at a safe position outside the castle until you call for the assault."),
            reward = "1,000 XP.",
            warnings = "Finley can charge into rhinos and die en route; lead him carefully.",
            searchTags = listOf("Finley gets all set to attack Trelis.", "Finley", "Nemora", "DEFER — REBEL PREP")
        ),
        Quest(
            id = "G3-P2-067",
            chapter = 2,
            playOrder = 67,
            title = "Finley attacks Trelis.",
            category = "DEFER — REBEL PATH",
            giver = "Finley",
            location = "Nemora → Trelis",
            prerequisites = "Escort Finley to Trelis and start the planned Rebel assault.",
            summary = "When you intentionally begin the liberation, take Finley with you and assault Trelis. Keep him alive if possible while defeating the Orc occupation.",
            walkthroughSteps = listOf("When positioned for the Trelis uprising, tell Finley to begin attacking.", "Join his assault and help defeat the Orc defenders.", "Keep Finley alive and finish the liberation with his support."),
            reward = "1,250 XP and +2 Rebel reputation.",
            warnings = "⚠ Choice warning: This quest can affect faction access, named NPCs, or later quest availability. Make a manual save before committing and finish the surrounding neutral quests first.",
            searchTags = listOf("Finley attacks Trelis.", "Finley", "Nemora → Trelis", "DEFER — REBEL PATH")
        ),
        Quest(
            id = "G3-P2-068",
            chapter = 2,
            playOrder = 68,
            title = "Destroy the rebel camp Nemora.",
            category = "DEFER — ORC PATH",
            giver = "Varek (Orc leader in Montera) / Orc-faction contract",
            location = "Nemora",
            prerequisites = "Choose the Orc campaign against Nemora after collecting Treslott's chalice and Karlen's quests.",
            summary = "On a committed Orc playthrough, attack Nemora and eliminate enough rebels and leadership for the camp to be destroyed, then report to the Orc quest giver.",
            walkthroughSteps = listOf("First finish Nemora's Rebel recruitment, merchants, Treslott's Fire Chalice and Karlen tasks if you want them.", "Take the Orc-aligned assignment to destroy the rebel hideout.", "Approach the cave from its entrance and lure Rebels outside rather than fighting the full settlement underground.", "Fight leaders and remaining defenders until Nemora falls; report to the Orc contract giver."),
            reward = "2,500 XP and +7 Orc reputation.",
            warnings = "Irreversibly destroys Nemora and its Rebel quest lines. Treslott's FIRE CHALICE is a missable endgame item.",
            searchTags = listOf("Destroy the rebel camp Nemora.", "Orc leadership", "Nemora", "DEFER — ORC PATH")
        ),
    )
}
