package com.sliverzfx.gothicquest

internal object Gothic3Part5Data {
    val quests = listOf(
        Quest(
            id = "G3-P5-001",
            chapter = 5,
            playOrder = 1,
            title = "Talk to Nafalem.",
            category = "SAFE",
            giver = "Nafalem",
            location = "Braga",
            prerequisites = "",
            summary = "Find Nafalem, Braga's Hashishin leader, and exhaust his dialogue about the town, tribute and Nomad threat.",
            walkthroughSteps = listOf("Begin with Nafalem. This objective is centered on Braga. In Varant, use settlements, oases, roads and ruin silhouettes as navigation anchors; open desert shortcuts can easily lead into predator packs or the wrong canyon.", "Find Nafalem, Braga's Hashishin leader, and exhaust his dialogue about the town, tribute and Nomad threat.", "After the objective is complete, return to the named quest giver or destination and exhaust the new dialogue. For kill quests, search the whole marked area if the completion message has not appeared; isolated enemies can wander away from their group.", "His dialogue opens much of Braga's local quest network; do this before wandering into the desert."),
            reward = "",
            warnings = "",
            searchTags = listOf("Talk to Nafalem.", "Nafalem", "Braga", "SAFE")
        ),
        Quest(
            id = "G3-P5-002",
            chapter = 5,
            playOrder = 2,
            title = "The tribute from Braga.",
            category = "SAFE / COLLECTION",
            giver = "Nafalem",
            location = "Braga",
            prerequisites = "",
            summary = "Collect the outstanding tribute payments and goods from the people Nafalem names, then return to him with the required total.",
            walkthroughSteps = listOf("Begin with Nafalem. This objective is centered on Braga. In Varant, use settlements, oases, roads and ruin silhouettes as navigation anchors; open desert shortcuts can easily lead into predator packs or the wrong canyon.", "Collect the outstanding tribute payments and goods from the people Nafalem names, then return to him with the required total.", "After the objective is complete, return to the named quest giver or destination and exhaust the new dialogue. For kill quests, search the whole marked area if the completion message has not appeared; isolated enemies can wander away from their group.", "Speak to every named debtor before spending any collected quest gold."),
            reward = "",
            warnings = "",
            searchTags = listOf("The tribute from Braga.", "Nafalem", "Braga", "SAFE / COLLECTION")
        ),
        Quest(
            id = "G3-P5-003",
            chapter = 5,
            playOrder = 3,
            title = "Bernado's tribute.",
            category = "SAFE",
            giver = "Bernado / Nafalem",
            location = "Braga",
            prerequisites = "",
            summary = "Speak with Bernado about the tribute he owes and obtain the required payment for Nafalem.",
            walkthroughSteps = listOf("Begin with Bernado / Nafalem. This objective is centered on Braga. In Varant, use settlements, oases, roads and ruin silhouettes as navigation anchors; open desert shortcuts can easily lead into predator packs or the wrong canyon.", "Speak with Bernado about the tribute he owes and obtain the required payment for Nafalem.", "After the objective is complete, return to the named quest giver or destination and exhaust the new dialogue. For kill quests, search the whole marked area if the completion message has not appeared; isolated enemies can wander away from their group.", "Part of the larger tribute collection; resolve his personal dialogue before reporting."),
            reward = "",
            warnings = "",
            searchTags = listOf("Bernado's tribute.", "Bernado / Nafalem", "Braga", "SAFE")
        ),
        Quest(
            id = "G3-P5-004",
            chapter = 5,
            playOrder = 4,
            title = "Jose's tribute.",
            category = "SAFE",
            giver = "Jose / Nafalem",
            location = "Braga",
            prerequisites = "",
            summary = "Collect Jose's share of Braga's tribute and keep it for the final hand-in to Nafalem.",
            walkthroughSteps = listOf("Begin with Jose / Nafalem. This objective is centered on Braga. In Varant, use settlements, oases, roads and ruin silhouettes as navigation anchors; open desert shortcuts can easily lead into predator packs or the wrong canyon.", "Collect Jose's share of Braga's tribute and keep it for the final hand-in to Nafalem.", "After the objective is complete, return to the named quest giver or destination and exhaust the new dialogue. For kill quests, search the whole marked area if the completion message has not appeared; isolated enemies can wander away from their group.", "Do all tribute conversations in one circuit of Braga."),
            reward = "",
            warnings = "",
            searchTags = listOf("Jose's tribute.", "Jose / Nafalem", "Braga", "SAFE")
        ),
        Quest(
            id = "G3-P5-005",
            chapter = 5,
            playOrder = 5,
            title = "Luca's tribute.",
            category = "SAFE",
            giver = "Luca / Nafalem",
            location = "Braga",
            prerequisites = "",
            summary = "Obtain Luca's contribution to the tribute and return it as part of Nafalem's collection.",
            walkthroughSteps = listOf("Begin with Luca / Nafalem. This objective is centered on Braga. In Varant, use settlements, oases, roads and ruin silhouettes as navigation anchors; open desert shortcuts can easily lead into predator packs or the wrong canyon.", "Obtain Luca's contribution to the tribute and return it as part of Nafalem's collection.", "After the objective is complete, return to the named quest giver or destination and exhaust the new dialogue. For kill quests, search the whole marked area if the completion message has not appeared; isolated enemies can wander away from their group.", "Luca also has useful trader/armor dialogue; do not rush past him."),
            reward = "",
            warnings = "",
            searchTags = listOf("Luca's tribute.", "Luca / Nafalem", "Braga", "SAFE")
        ),
        Quest(
            id = "G3-P5-006",
            chapter = 5,
            playOrder = 6,
            title = "Abbas's tribute.",
            category = "SAFE",
            giver = "Abbas / Nafalem",
            location = "Braga",
            prerequisites = "",
            summary = "Collect the tribute demanded from Abbas and include it in Nafalem's total.",
            walkthroughSteps = listOf("Begin with Abbas / Nafalem. This objective is centered on Braga. In Varant, use settlements, oases, roads and ruin silhouettes as navigation anchors; open desert shortcuts can easily lead into predator packs or the wrong canyon.", "Collect the tribute demanded from Abbas and include it in Nafalem's total.", "After the objective is complete, return to the named quest giver or destination and exhaust the new dialogue. For kill quests, search the whole marked area if the completion message has not appeared; isolated enemies can wander away from their group.", "If an NPC offers a favor or alternative before paying, complete that dialogue first."),
            reward = "",
            warnings = "",
            searchTags = listOf("Abbas's tribute.", "Abbas / Nafalem", "Braga", "SAFE")
        ),
        Quest(
            id = "G3-P5-007",
            chapter = 5,
            playOrder = 7,
            title = "The dark snapper hunt.",
            category = "SAFE / HUNT",
            giver = "Braga hunter",
            location = "Desert around Braga",
            prerequisites = "",
            summary = "Track the designated dark snappers outside Braga and kill the full group. Return to the hunter when the objective message appears.",
            walkthroughSteps = listOf("Begin with Braga hunter. This objective is centered on Desert around Braga. In Varant, use settlements, oases, roads and ruin silhouettes as navigation anchors; open desert shortcuts can easily lead into predator packs or the wrong canyon.", "Track the designated dark snappers outside Braga and kill the full group. Return to the hunter when the objective message appears.", "After the objective is complete, return to the named quest giver or destination and exhaust the new dialogue. For kill quests, search the whole marked area if the completion message has not appeared; isolated enemies can wander away from their group.", "Desert predators blend into the terrain; circle the quest area if one target is missing."),
            reward = "",
            warnings = "",
            searchTags = listOf("The dark snapper hunt.", "Braga hunter", "Desert around Braga", "SAFE / HUNT")
        ),
        Quest(
            id = "G3-P5-008",
            chapter = 5,
            playOrder = 8,
            title = "Hunt the dangerous desert beasts.",
            category = "SAFE / HUNT",
            giver = "Diego / Braga hunter chain",
            location = "Braga wilderness",
            prerequisites = "",
            summary = "Join or assist the hunter with the dangerous beasts around Braga and kill the designated targets.",
            walkthroughSteps = listOf("Begin with Diego / Braga hunter chain. This objective is centered on Braga wilderness. In Varant, use settlements, oases, roads and ruin silhouettes as navigation anchors; open desert shortcuts can easily lead into predator packs or the wrong canyon.", "Join or assist the hunter with the dangerous beasts around Braga and kill the designated targets.", "After the objective is complete, return to the named quest giver or destination and exhaust the new dialogue. For kill quests, search the whole marked area if the completion message has not appeared; isolated enemies can wander away from their group.", "Use this to learn the nearby desert without provoking Nomad camps."),
            reward = "",
            warnings = "",
            searchTags = listOf("Hunt the dangerous desert beasts.", "Diego / Braga hunter chain", "Braga wilderness", "SAFE / HUNT")
        ),
        Quest(
            id = "G3-P5-009",
            chapter = 5,
            playOrder = 9,
            title = "Follow Diego into the desert.",
            category = "SAFE / ESCORT",
            giver = "Diego",
            location = "Braga → desert",
            prerequisites = "",
            summary = "Accompany Diego on his route outside Braga and stay close while he leads you to the hunting/objective area.",
            walkthroughSteps = listOf("Begin with Diego. This objective is centered on Braga → desert. In Varant, use settlements, oases, roads and ruin silhouettes as navigation anchors; open desert shortcuts can easily lead into predator packs or the wrong canyon.", "Accompany Diego on his route outside Braga and stay close while he leads you to the hunting/objective area.", "After the objective is complete, return to the named quest giver or destination and exhaust the new dialogue. For kill quests, search the whole marked area if the completion message has not appeared; isolated enemies can wander away from their group.", "Diego is a major recurring character; protect him and exhaust his dialogue afterward."),
            reward = "",
            warnings = "",
            searchTags = listOf("Follow Diego into the desert.", "Diego", "Braga → desert", "SAFE / ESCORT")
        ),
        Quest(
            id = "G3-P5-010",
            chapter = 5,
            playOrder = 10,
            title = "Aila.",
            category = "CHOICE",
            giver = "Nafalem / Braga quest chain",
            location = "Braga / Nomad area",
            prerequisites = "",
            summary = "Investigate Aila's disappearance/capture and locate her through the Nomad-related quest chain.",
            walkthroughSteps = listOf("Begin with Nafalem / Braga quest chain. This objective is centered on Braga / Nomad area. In Varant, use settlements, oases, roads and ruin silhouettes as navigation anchors; open desert shortcuts can easily lead into predator packs or the wrong canyon.", "Investigate Aila's disappearance/capture and locate her through the Nomad-related quest chain.", "After the objective is complete, return to the named quest giver or destination and exhaust the new dialogue. For kill quests, search the whole marked area if the completion message has not appeared; isolated enemies can wander away from their group.", "Do not attack every Nomad on sight; Aila's quest overlaps the faction conflict."),
            reward = "",
            warnings = "⚠ Faction / progression warning: Create a manual save before resolving this objective. It can remove NPCs, alter Hashishin/Nomad access or close later quests.",
            searchTags = listOf("Aila.", "Nafalem / Braga quest chain", "Braga / Nomad area", "CHOICE")
        ),
        Quest(
            id = "G3-P5-011",
            chapter = 5,
            playOrder = 11,
            title = "Bring Aila back to Braga.",
            category = "CHOICE — HASHISHIN",
            giver = "Aila / Nafalem",
            location = "Nomad camp → Braga",
            prerequisites = "",
            summary = "If choosing the Braga/Hashishin resolution, escort Aila safely back to Braga and deliver her to the appropriate NPC.",
            walkthroughSteps = listOf("Begin with Aila / Nafalem. This objective is centered on Nomad camp → Braga. In Varant, use settlements, oases, roads and ruin silhouettes as navigation anchors; open desert shortcuts can easily lead into predator packs or the wrong canyon.", "If choosing the Braga/Hashishin resolution, escort Aila safely back to Braga and deliver her to the appropriate NPC.", "After the objective is complete, return to the named quest giver or destination and exhaust the new dialogue. For kill quests, search the whole marked area if the completion message has not appeared; isolated enemies can wander away from their group.", "Clear predators on the route first; this outcome affects how the local Nomad conflict resolves."),
            reward = "",
            warnings = "⚠ Faction / progression warning: Create a manual save before resolving this objective. It can remove NPCs, alter Hashishin/Nomad access or close later quests.",
            searchTags = listOf("Bring Aila back to Braga.", "Aila / Nafalem", "Nomad camp → Braga", "CHOICE — HASHISHIN")
        ),
        Quest(
            id = "G3-P5-012",
            chapter = 5,
            playOrder = 12,
            title = "Eliminate the nomads near Braga.",
            category = "DEFER — HASHISHIN PATH",
            giver = "Nafalem",
            location = "Braga region",
            prerequisites = "",
            summary = "Locate the Nomad group threatening Braga and eliminate its members, then report to Nafalem.",
            walkthroughSteps = listOf("Begin with Nafalem. This objective is centered on Braga region. In Varant, use settlements, oases, roads and ruin silhouettes as navigation anchors; open desert shortcuts can easily lead into predator packs or the wrong canyon.", "Locate the Nomad group threatening Braga and eliminate its members, then report to Nafalem.", "After the objective is complete, return to the named quest giver or destination and exhaust the new dialogue. For kill quests, search the whole marked area if the completion message has not appeared; isolated enemies can wander away from their group.", "Finish all dialogue, Aila-related content and any Nomad quests first."),
            reward = "",
            warnings = "⚠ Faction / progression warning: Create a manual save before resolving this objective. It can remove NPCs, alter Hashishin/Nomad access or close later quests.",
            searchTags = listOf("Eliminate the nomads near Braga.", "Nafalem", "Braga region", "DEFER — HASHISHIN PATH")
        ),
        Quest(
            id = "G3-P5-013",
            chapter = 5,
            playOrder = 13,
            title = "Help the nomads against Braga.",
            category = "DEFER — NOMAD PATH",
            giver = "Nomad leader",
            location = "Braga region",
            prerequisites = "",
            summary = "If supporting the Nomads, complete their preparation and attack/undermine the Hashishin position at Braga as directed.",
            walkthroughSteps = listOf("Begin with Nomad leader. This objective is centered on Braga region. In Varant, use settlements, oases, roads and ruin silhouettes as navigation anchors; open desert shortcuts can easily lead into predator packs or the wrong canyon.", "If supporting the Nomads, complete their preparation and attack/undermine the Hashishin position at Braga as directed.", "After the objective is complete, return to the named quest giver or destination and exhaust the new dialogue. For kill quests, search the whole marked area if the completion message has not appeared; isolated enemies can wander away from their group.", "Mutually hostile with the Hashishin purge objective; make a permanent save."),
            reward = "",
            warnings = "⚠ Faction / progression warning: Create a manual save before resolving this objective. It can remove NPCs, alter Hashishin/Nomad access or close later quests.",
            searchTags = listOf("Help the nomads against Braga.", "Nomad leader", "Braga region", "DEFER — NOMAD PATH")
        ),
        Quest(
            id = "G3-P5-014",
            chapter = 5,
            playOrder = 14,
            title = "A lesson in hospitality.",
            category = "SAFE",
            giver = "Braga quest chain",
            location = "Braga",
            prerequisites = "",
            summary = "Complete the local conversation/delivery task involving Braga's customs and hospitality, then report to the quest giver.",
            walkthroughSteps = listOf("Begin with Braga quest chain. This objective is centered on Braga. In Varant, use settlements, oases, roads and ruin silhouettes as navigation anchors; open desert shortcuts can easily lead into predator packs or the wrong canyon.", "Complete the local conversation/delivery task involving Braga's customs and hospitality, then report to the quest giver.", "After the objective is complete, return to the named quest giver or destination and exhaust the new dialogue. For kill quests, search the whole marked area if the completion message has not appeared; isolated enemies can wander away from their group.", "Use these harmless local quests to build reputation before faction choices."),
            reward = "",
            warnings = "",
            searchTags = listOf("A lesson in hospitality.", "Braga quest chain", "Braga", "SAFE")
        ),
        Quest(
            id = "G3-P5-015",
            chapter = 5,
            playOrder = 15,
            title = "Talk to Sancho.",
            category = "SAFE",
            giver = "Sancho",
            location = "Ben Erai",
            prerequisites = "",
            summary = "Find Sancho, the authority in Ben Erai, and exhaust his dialogue about the mines, slaves and local problems.",
            walkthroughSteps = listOf("Begin with Sancho. This objective is centered on Ben Erai. In Varant, use settlements, oases, roads and ruin silhouettes as navigation anchors; open desert shortcuts can easily lead into predator packs or the wrong canyon.", "Find Sancho, the authority in Ben Erai, and exhaust his dialogue about the mines, slaves and local problems.", "After the objective is complete, return to the named quest giver or destination and exhaust the new dialogue. For kill quests, search the whole marked area if the completion message has not appeared; isolated enemies can wander away from their group.", "This opens the settlement's main work/reputation chain."),
            reward = "",
            warnings = "",
            searchTags = listOf("Talk to Sancho.", "Sancho", "Ben Erai", "SAFE")
        ),
        Quest(
            id = "G3-P5-016",
            chapter = 5,
            playOrder = 16,
            title = "Report from the mines.",
            category = "SAFE",
            giver = "Sancho / mine overseers",
            location = "Ben Erai mines",
            prerequisites = "",
            summary = "Visit the relevant mines, speak with the overseers and bring Sancho the requested status report.",
            walkthroughSteps = listOf("Begin with Sancho / mine overseers. This objective is centered on Ben Erai mines. In Varant, use settlements, oases, roads and ruin silhouettes as navigation anchors; open desert shortcuts can easily lead into predator packs or the wrong canyon.", "Visit the relevant mines, speak with the overseers and bring Sancho the requested status report.", "After the objective is complete, return to the named quest giver or destination and exhaust the new dialogue. For kill quests, search the whole marked area if the completion message has not appeared; isolated enemies can wander away from their group.", "Do the mining quests while making the reporting circuit."),
            reward = "",
            warnings = "",
            searchTags = listOf("Report from the mines.", "Sancho / mine overseers", "Ben Erai mines", "SAFE")
        ),
        Quest(
            id = "G3-P5-017",
            chapter = 5,
            playOrder = 17,
            title = "Lukar needs ore.",
            category = "SAFE",
            giver = "Lukar",
            location = "Ben Erai",
            prerequisites = "",
            summary = "Collect the ore Lukar requests and deliver the full amount.",
            walkthroughSteps = listOf("Begin with Lukar. This objective is centered on Ben Erai. In Varant, use settlements, oases, roads and ruin silhouettes as navigation anchors; open desert shortcuts can easily lead into predator packs or the wrong canyon.", "Collect the ore Lukar requests and deliver the full amount.", "After the objective is complete, return to the named quest giver or destination and exhaust the new dialogue. For kill quests, search the whole marked area if the completion message has not appeared; isolated enemies can wander away from their group.", "Keep quest ore until Ben Erai's mine chain is finished."),
            reward = "",
            warnings = "",
            searchTags = listOf("Lukar needs ore.", "Lukar", "Ben Erai", "SAFE")
        ),
        Quest(
            id = "G3-P5-018",
            chapter = 5,
            playOrder = 18,
            title = "The mine workers need food.",
            category = "SAFE / DELIVERY",
            giver = "Mine overseer",
            location = "Ben Erai mine",
            prerequisites = "",
            summary = "Bring the workers the requested food supplies and report the delivery.",
            walkthroughSteps = listOf("Begin with Mine overseer. This objective is centered on Ben Erai mine. In Varant, use settlements, oases, roads and ruin silhouettes as navigation anchors; open desert shortcuts can easily lead into predator packs or the wrong canyon.", "Bring the workers the requested food supplies and report the delivery.", "After the objective is complete, return to the named quest giver or destination and exhaust the new dialogue. For kill quests, search the whole marked area if the completion message has not appeared; isolated enemies can wander away from their group.", "Carry extra desert food before visiting the remote mine."),
            reward = "",
            warnings = "",
            searchTags = listOf("The mine workers need food.", "Mine overseer", "Ben Erai mine", "SAFE / DELIVERY")
        ),
        Quest(
            id = "G3-P5-019",
            chapter = 5,
            playOrder = 19,
            title = "Bring water to the mine.",
            category = "SAFE / DELIVERY",
            giver = "Ben Erai mine quest giver",
            location = "Ben Erai mine",
            prerequisites = "",
            summary = "Deliver the requested water to the miners/slaves working outside the settlement.",
            walkthroughSteps = listOf("Begin with Ben Erai mine quest giver. This objective is centered on Ben Erai mine. In Varant, use settlements, oases, roads and ruin silhouettes as navigation anchors; open desert shortcuts can easily lead into predator packs or the wrong canyon.", "Deliver the requested water to the miners/slaves working outside the settlement.", "After the objective is complete, return to the named quest giver or destination and exhaust the new dialogue. For kill quests, search the whole marked area if the completion message has not appeared; isolated enemies can wander away from their group.", "Water is common in Varant quests; avoid selling every bottle."),
            reward = "",
            warnings = "",
            searchTags = listOf("Bring water to the mine.", "Ben Erai mine quest giver", "Ben Erai mine", "SAFE / DELIVERY")
        ),
        Quest(
            id = "G3-P5-020",
            chapter = 5,
            playOrder = 20,
            title = "The exhausted slaves.",
            category = "CHOICE",
            giver = "Ben Erai overseer",
            location = "Ben Erai",
            prerequisites = "",
            summary = "Speak with the exhausted slaves and the overseer to determine what is required to keep the mine functioning or help the slaves.",
            walkthroughSteps = listOf("Begin with Ben Erai overseer. This objective is centered on Ben Erai. In Varant, use settlements, oases, roads and ruin silhouettes as navigation anchors; open desert shortcuts can easily lead into predator packs or the wrong canyon.", "Speak with the exhausted slaves and the overseer to determine what is required to keep the mine functioning or help the slaves.", "After the objective is complete, return to the named quest giver or destination and exhaust the new dialogue. For kill quests, search the whole marked area if the completion message has not appeared; isolated enemies can wander away from their group.", "Slave objectives often have faction-sensitive alternatives; save before coercive outcomes."),
            reward = "",
            warnings = "⚠ Faction / progression warning: Create a manual save before resolving this objective. It can remove NPCs, alter Hashishin/Nomad access or close later quests.",
            searchTags = listOf("The exhausted slaves.", "Ben Erai overseer", "Ben Erai", "CHOICE")
        ),
        Quest(
            id = "G3-P5-021",
            chapter = 5,
            playOrder = 21,
            title = "A new slave for the mine.",
            category = "CHOICE — HASHISHIN",
            giver = "Ben Erai quest chain",
            location = "Ben Erai",
            prerequisites = "",
            summary = "Deliver/recruit the requested slave to the mine if following the Hashishin outcome.",
            walkthroughSteps = listOf("Begin with Ben Erai quest chain. This objective is centered on Ben Erai. In Varant, use settlements, oases, roads and ruin silhouettes as navigation anchors; open desert shortcuts can easily lead into predator packs or the wrong canyon.", "Deliver/recruit the requested slave to the mine if following the Hashishin outcome.", "After the objective is complete, return to the named quest giver or destination and exhaust the new dialogue. For kill quests, search the whole marked area if the completion message has not appeared; isolated enemies can wander away from their group.", "Do not complete this automatically if you intend to support the Nomads."),
            reward = "",
            warnings = "⚠ Faction / progression warning: Create a manual save before resolving this objective. It can remove NPCs, alter Hashishin/Nomad access or close later quests.",
            searchTags = listOf("A new slave for the mine.", "Ben Erai quest chain", "Ben Erai", "CHOICE — HASHISHIN")
        ),
        Quest(
            id = "G3-P5-022",
            chapter = 5,
            playOrder = 22,
            title = "The tunnel is blocked.",
            category = "SAFE",
            giver = "Mine overseer",
            location = "Ben Erai mine",
            prerequisites = "",
            summary = "Enter the affected tunnel and remove the creature/enemy problem preventing mining. Explore the entire branch before returning.",
            walkthroughSteps = listOf("Begin with Mine overseer. This objective is centered on Ben Erai mine. In Varant, use settlements, oases, roads and ruin silhouettes as navigation anchors; open desert shortcuts can easily lead into predator packs or the wrong canyon.", "Enter the affected tunnel and remove the creature/enemy problem preventing mining. Explore the entire branch before returning.", "After the objective is complete, return to the named quest giver or destination and exhaust the new dialogue. For kill quests, search the whole marked area if the completion message has not appeared; isolated enemies can wander away from their group.", "Mine quests are efficient places to collect ore for other Ben Erai objectives."),
            reward = "",
            warnings = "",
            searchTags = listOf("The tunnel is blocked.", "Mine overseer", "Ben Erai mine", "SAFE")
        ),
        Quest(
            id = "G3-P5-023",
            chapter = 5,
            playOrder = 23,
            title = "Crawlers in the mine.",
            category = "SAFE",
            giver = "Ben Erai miner",
            location = "Ben Erai mine",
            prerequisites = "",
            summary = "Kill all Minecrawlers in the designated mine section and return once the tunnel is safe.",
            walkthroughSteps = listOf("Begin with Ben Erai miner. This objective is centered on Ben Erai mine. In Varant, use settlements, oases, roads and ruin silhouettes as navigation anchors; open desert shortcuts can easily lead into predator packs or the wrong canyon.", "Kill all Minecrawlers in the designated mine section and return once the tunnel is safe.", "After the objective is complete, return to the named quest giver or destination and exhaust the new dialogue. For kill quests, search the whole marked area if the completion message has not appeared; isolated enemies can wander away from their group.", "Search side chambers if the kill counter does not finish."),
            reward = "",
            warnings = "",
            searchTags = listOf("Crawlers in the mine.", "Ben Erai miner", "Ben Erai mine", "SAFE")
        ),
        Quest(
            id = "G3-P5-024",
            chapter = 5,
            playOrder = 24,
            title = "Hunt the lurkers near Ben Erai.",
            category = "SAFE",
            giver = "Ben Erai hunter",
            location = "Oasis/river area",
            prerequisites = "",
            summary = "Kill the designated Lurkers around the local water source and report back.",
            walkthroughSteps = listOf("Begin with Ben Erai hunter. This objective is centered on Oasis/river area. In Varant, use settlements, oases, roads and ruin silhouettes as navigation anchors; open desert shortcuts can easily lead into predator packs or the wrong canyon.", "Kill the designated Lurkers around the local water source and report back.", "After the objective is complete, return to the named quest giver or destination and exhaust the new dialogue. For kill quests, search the whole marked area if the completion message has not appeared; isolated enemies can wander away from their group.", "Useful source of trophies and early desert XP."),
            reward = "",
            warnings = "",
            searchTags = listOf("Hunt the lurkers near Ben Erai.", "Ben Erai hunter", "Oasis/river area", "SAFE")
        ),
        Quest(
            id = "G3-P5-025",
            chapter = 5,
            playOrder = 25,
            title = "The stolen ore.",
            category = "SAFE / INVESTIGATION",
            giver = "Sancho / Ben Erai quest chain",
            location = "Ben Erai region",
            prerequisites = "",
            summary = "Investigate the missing ore shipment, follow the clues to the thieves or responsible group and recover/report the goods.",
            walkthroughSteps = listOf("Begin with Sancho / Ben Erai quest chain. This objective is centered on Ben Erai region. In Varant, use settlements, oases, roads and ruin silhouettes as navigation anchors; open desert shortcuts can easily lead into predator packs or the wrong canyon.", "Investigate the missing ore shipment, follow the clues to the thieves or responsible group and recover/report the goods.", "After the objective is complete, return to the named quest giver or destination and exhaust the new dialogue. For kill quests, search the whole marked area if the completion message has not appeared; isolated enemies can wander away from their group.", "Do not sell ore crates or uniquely named shipment items."),
            reward = "",
            warnings = "",
            searchTags = listOf("The stolen ore.", "Sancho / Ben Erai quest chain", "Ben Erai region", "SAFE / INVESTIGATION")
        ),
        Quest(
            id = "G3-P5-026",
            chapter = 5,
            playOrder = 26,
            title = "Report to Gonzales / Mora Sul.",
            category = "CROSS-REGION",
            giver = "Sancho",
            location = "Ben Erai → Mora Sul",
            prerequisites = "",
            summary = "Carry Sancho's report or information onward to the appropriate Hashishin authority when the quest directs you south.",
            walkthroughSteps = listOf("Begin with Sancho. This objective is centered on Ben Erai → Mora Sul. In Varant, use settlements, oases, roads and ruin silhouettes as navigation anchors; open desert shortcuts can easily lead into predator packs or the wrong canyon.", "Carry Sancho's report or information onward to the appropriate Hashishin authority when the quest directs you south.", "After the objective is complete, return to the named quest giver or destination and exhaust the new dialogue. For kill quests, search the whole marked area if the completion message has not appeared; isolated enemies can wander away from their group.", "Keep this active for Part VI rather than rushing past unfinished Ben Erai content."),
            reward = "",
            warnings = "",
            searchTags = listOf("Report to Gonzales / Mora Sul.", "Sancho", "Ben Erai → Mora Sul", "CROSS-REGION")
        ),
        Quest(
            id = "G3-P5-027",
            chapter = 5,
            playOrder = 27,
            title = "Eliminate the nomads around Ben Erai.",
            category = "DEFER — HASHISHIN PATH",
            giver = "Sancho / Hashishin",
            location = "Ben Erai region",
            prerequisites = "",
            summary = "Find and destroy the designated Nomad group threatening Ben Erai, then report back.",
            walkthroughSteps = listOf("Begin with Sancho / Hashishin. This objective is centered on Ben Erai region. In Varant, use settlements, oases, roads and ruin silhouettes as navigation anchors; open desert shortcuts can easily lead into predator packs or the wrong canyon.", "Find and destroy the designated Nomad group threatening Ben Erai, then report back.", "After the objective is complete, return to the named quest giver or destination and exhaust the new dialogue. For kill quests, search the whole marked area if the completion message has not appeared; isolated enemies can wander away from their group.", "Finish any quests available from that Nomad camp first."),
            reward = "",
            warnings = "⚠ Faction / progression warning: Create a manual save before resolving this objective. It can remove NPCs, alter Hashishin/Nomad access or close later quests.",
            searchTags = listOf("Eliminate the nomads around Ben Erai.", "Sancho / Hashishin", "Ben Erai region", "DEFER — HASHISHIN PATH")
        ),
        Quest(
            id = "G3-P5-028",
            chapter = 5,
            playOrder = 28,
            title = "Support the nomads near Ben Erai.",
            category = "DEFER — NOMAD PATH",
            giver = "Nomad contact",
            location = "Ben Erai region",
            prerequisites = "",
            summary = "Help the local Nomads against Hashishin interests according to their quest line.",
            walkthroughSteps = listOf("Begin with Nomad contact. This objective is centered on Ben Erai region. In Varant, use settlements, oases, roads and ruin silhouettes as navigation anchors; open desert shortcuts can easily lead into predator packs or the wrong canyon.", "Help the local Nomads against Hashishin interests according to their quest line.", "After the objective is complete, return to the named quest giver or destination and exhaust the new dialogue. For kill quests, search the whole marked area if the completion message has not appeared; isolated enemies can wander away from their group.", "This can close Hashishin content in the settlement; do neutral quests first."),
            reward = "",
            warnings = "⚠ Faction / progression warning: Create a manual save before resolving this objective. It can remove NPCs, alter Hashishin/Nomad access or close later quests.",
            searchTags = listOf("Support the nomads near Ben Erai.", "Nomad contact", "Ben Erai region", "DEFER — NOMAD PATH")
        ),
        Quest(
            id = "G3-P5-029",
            chapter = 5,
            playOrder = 29,
            title = "Talk to Fabio.",
            category = "SAFE",
            giver = "Fabio",
            location = "Lago",
            prerequisites = "",
            summary = "Speak with Fabio, Lago's leader, and exhaust his dialogue about the town, prisoners and local work.",
            walkthroughSteps = listOf("Begin with Fabio. This objective is centered on Lago. In Varant, use settlements, oases, roads and ruin silhouettes as navigation anchors; open desert shortcuts can easily lead into predator packs or the wrong canyon.", "Speak with Fabio, Lago's leader, and exhaust his dialogue about the town, prisoners and local work.", "After the objective is complete, return to the named quest giver or destination and exhaust the new dialogue. For kill quests, search the whole marked area if the completion message has not appeared; isolated enemies can wander away from their group.", "Do this before resolving Vatras's fate."),
            reward = "",
            warnings = "",
            searchTags = listOf("Talk to Fabio.", "Fabio", "Lago", "SAFE")
        ),
        Quest(
            id = "G3-P5-030",
            chapter = 5,
            playOrder = 30,
            title = "Swampweed for Lago.",
            category = "SAFE / COLLECTION",
            giver = "Lago quest giver",
            location = "Lago",
            prerequisites = "",
            summary = "Collect the requested swampweed bundles/plants and deliver them to the quest giver.",
            walkthroughSteps = listOf("Begin with Lago quest giver. This objective is centered on Lago. In Varant, use settlements, oases, roads and ruin silhouettes as navigation anchors; open desert shortcuts can easily lead into predator packs or the wrong canyon.", "Collect the requested swampweed bundles/plants and deliver them to the quest giver.", "After the objective is complete, return to the named quest giver or destination and exhaust the new dialogue. For kill quests, search the whole marked area if the completion message has not appeared; isolated enemies can wander away from their group.", "Lago is heavily associated with swampweed; search gardens, traders and nearby areas."),
            reward = "",
            warnings = "",
            searchTags = listOf("Swampweed for Lago.", "Lago quest giver", "Lago", "SAFE / COLLECTION")
        ),
        Quest(
            id = "G3-P5-031",
            chapter = 5,
            playOrder = 31,
            title = "The swampweed harvest.",
            category = "SAFE",
            giver = "Lago worker",
            location = "Lago fields",
            prerequisites = "",
            summary = "Help collect or deliver the swampweed harvest as requested.",
            walkthroughSteps = listOf("Begin with Lago worker. This objective is centered on Lago fields. In Varant, use settlements, oases, roads and ruin silhouettes as navigation anchors; open desert shortcuts can easily lead into predator packs or the wrong canyon.", "Help collect or deliver the swampweed harvest as requested.", "After the objective is complete, return to the named quest giver or destination and exhaust the new dialogue. For kill quests, search the whole marked area if the completion message has not appeared; isolated enemies can wander away from their group.", "Complete alongside the other swampweed quest."),
            reward = "",
            warnings = "",
            searchTags = listOf("The swampweed harvest.", "Lago worker", "Lago fields", "SAFE")
        ),
        Quest(
            id = "G3-P5-032",
            chapter = 5,
            playOrder = 32,
            title = "Hunt the bloodflies near Lago.",
            category = "SAFE / HUNT",
            giver = "Lago hunter",
            location = "Oasis near Lago",
            prerequisites = "",
            summary = "Kill the bloodflies threatening the oasis/fields and return after the whole target group is dead.",
            walkthroughSteps = listOf("Begin with Lago hunter. This objective is centered on Oasis near Lago. In Varant, use settlements, oases, roads and ruin silhouettes as navigation anchors; open desert shortcuts can easily lead into predator packs or the wrong canyon.", "Kill the bloodflies threatening the oasis/fields and return after the whole target group is dead.", "After the objective is complete, return to the named quest giver or destination and exhaust the new dialogue. For kill quests, search the whole marked area if the completion message has not appeared; isolated enemies can wander away from their group.", "Ranged attacks help prevent several insects engaging at once."),
            reward = "",
            warnings = "",
            searchTags = listOf("Hunt the bloodflies near Lago.", "Lago hunter", "Oasis near Lago", "SAFE / HUNT")
        ),
        Quest(
            id = "G3-P5-033",
            chapter = 5,
            playOrder = 33,
            title = "Fight in Lago's arena.",
            category = "SAFE — ARENA",
            giver = "Lago arena",
            location = "Lago",
            prerequisites = "",
            summary = "Challenge the available fighter(s), remain inside the arena and win by knockout rather than killing.",
            walkthroughSteps = listOf("Begin with Lago arena. This objective is centered on Lago. In Varant, use settlements, oases, roads and ruin silhouettes as navigation anchors; open desert shortcuts can easily lead into predator packs or the wrong canyon.", "Challenge the available fighter(s), remain inside the arena and win by knockout rather than killing.", "After the objective is complete, return to the named quest giver or destination and exhaust the new dialogue. For kill quests, search the whole marked area if the completion message has not appeared; isolated enemies can wander away from their group.", "Finish arena content before any town liberation."),
            reward = "",
            warnings = "",
            searchTags = listOf("Fight in Lago's arena.", "Lago arena", "Lago", "SAFE — ARENA")
        ),
        Quest(
            id = "G3-P5-034",
            chapter = 5,
            playOrder = 34,
            title = "Defeat Lago's strongest fighter.",
            category = "SAFE — ARENA",
            giver = "Arena champion",
            location = "Lago",
            prerequisites = "",
            summary = "Beat the final/strongest local arena opponent and complete the post-fight dialogue.",
            walkthroughSteps = listOf("Begin with Arena champion. This objective is centered on Lago. In Varant, use settlements, oases, roads and ruin silhouettes as navigation anchors; open desert shortcuts can easily lead into predator packs or the wrong canyon.", "Beat the final/strongest local arena opponent and complete the post-fight dialogue.", "After the objective is complete, return to the named quest giver or destination and exhaust the new dialogue. For kill quests, search the whole marked area if the completion message has not appeared; isolated enemies can wander away from their group.", "A safe source of town reputation."),
            reward = "",
            warnings = "",
            searchTags = listOf("Defeat Lago's strongest fighter.", "Arena champion", "Lago", "SAFE — ARENA")
        ),
        Quest(
            id = "G3-P5-035",
            chapter = 5,
            playOrder = 35,
            title = "Find Vatras.",
            category = "MAIN-STORY SUPPORT",
            giver = "Trigger quest",
            location = "Lago",
            prerequisites = "",
            summary = "Discover that Vatras, the Water Mage from Khorinis, is being held prisoner in Lago. Reach his cell and speak with him before deciding how to handle the town.",
            walkthroughSteps = listOf("Begin with Main story / Water Mage chain. This objective is centered on Lago. In Varant, use settlements, oases, roads and ruin silhouettes as navigation anchors; open desert shortcuts can easily lead into predator packs or the wrong canyon.", "Discover that Vatras, the Water Mage from Khorinis, is being held prisoner in Lago. Reach his cell and speak with him before deciding how to handle the town.", "After the objective is complete, return to the named quest giver or destination and exhaust the new dialogue. For kill quests, search the whole marked area if the completion message has not appeared; isolated enemies can wander away from their group.", "Vatras is a major returning NPC and part of the Water Mage/Nomad network."),
            reward = "",
            warnings = "",
            searchTags = listOf("Find Vatras.", "Main story / Water Mage chain", "Lago", "MAIN-STORY SUPPORT")
        ),
        Quest(
            id = "G3-P5-036",
            chapter = 5,
            playOrder = 36,
            title = "Free Vatras from Lago.",
            category = "MAJOR — NOMAD",
            giver = "Vatras / Nomad route",
            location = "Lago",
            prerequisites = "",
            summary = "To free Vatras, you must remove the Hashishin control of Lago or otherwise reach the liberation outcome that opens his imprisonment. Speak with Vatras afterward and follow his relocation/dialogue.",
            walkthroughSteps = listOf("Begin with Vatras / Nomad route. This objective is centered on Lago. In Varant, use settlements, oases, roads and ruin silhouettes as navigation anchors; open desert shortcuts can easily lead into predator packs or the wrong canyon.", "To free Vatras, you must remove the Hashishin control of Lago or otherwise reach the liberation outcome that opens his imprisonment. Speak with Vatras afterward and follow his relocation/dialogue.", "After the objective is complete, return to the named quest giver or destination and exhaust the new dialogue. For kill quests, search the whole marked area if the completion message has not appeared; isolated enemies can wander away from their group.", "Complete Lago's neutral quests and arena first because liberation makes the town hostile."),
            reward = "",
            warnings = "⚠ Faction / progression warning: Create a manual save before resolving this objective. It can remove NPCs, alter Hashishin/Nomad access or close later quests.",
            searchTags = listOf("Free Vatras from Lago.", "Vatras / Nomad route", "Lago", "MAJOR — NOMAD")
        ),
        Quest(
            id = "G3-P5-037",
            chapter = 5,
            playOrder = 37,
            title = "Escort Vatras to safety.",
            category = "SAFE / ESCORT",
            giver = "Vatras",
            location = "Lago → Nomad/Water Mage destination",
            prerequisites = "",
            summary = "After freeing Vatras, accompany him as required by his follow-up route and protect him from desert wildlife.",
            walkthroughSteps = listOf("Begin with Vatras. This objective is centered on Lago → Nomad/Water Mage destination. In Varant, use settlements, oases, roads and ruin silhouettes as navigation anchors; open desert shortcuts can easily lead into predator packs or the wrong canyon.", "After freeing Vatras, accompany him as required by his follow-up route and protect him from desert wildlife.", "After the objective is complete, return to the named quest giver or destination and exhaust the new dialogue. For kill quests, search the whole marked area if the completion message has not appeared; isolated enemies can wander away from their group.", "Clear nearby predators before starting if possible."),
            reward = "",
            warnings = "",
            searchTags = listOf("Escort Vatras to safety.", "Vatras", "Lago → Nomad/Water Mage destination", "SAFE / ESCORT")
        ),
        Quest(
            id = "G3-P5-038",
            chapter = 5,
            playOrder = 38,
            title = "Liberate Lago!",
            category = "DEFER — NOMAD PATH",
            giver = "Nomad / player action",
            location = "Lago",
            prerequisites = "",
            summary = "After finishing all peaceful Lago quests, attack the Hashishin defenders and defeat enough of them for the settlement to be liberated.",
            walkthroughSteps = listOf("Begin with Nomad / player action. This objective is centered on Lago. In Varant, use settlements, oases, roads and ruin silhouettes as navigation anchors; open desert shortcuts can easily lead into predator packs or the wrong canyon.", "After finishing all peaceful Lago quests, attack the Hashishin defenders and defeat enough of them for the settlement to be liberated.", "After the objective is complete, return to the named quest giver or destination and exhaust the new dialogue. For kill quests, search the whole marked area if the completion message has not appeared; isolated enemies can wander away from their group.", "This is the practical trigger for freeing Vatras on the Nomad route."),
            reward = "",
            warnings = "⚠ Faction / progression warning: Create a manual save before resolving this objective. It can remove NPCs, alter Hashishin/Nomad access or close later quests.",
            searchTags = listOf("Liberate Lago!", "Nomad / player action", "Lago", "DEFER — NOMAD PATH")
        ),
        Quest(
            id = "G3-P5-039",
            chapter = 5,
            playOrder = 39,
            title = "Destroy the nomads connected to Lago.",
            category = "DEFER — HASHISHIN PATH",
            giver = "Hashishin quest giver",
            location = "Lago region",
            prerequisites = "",
            summary = "If following the Hashishin route, eliminate the relevant Nomad group and report the result.",
            walkthroughSteps = listOf("Begin with Hashishin quest giver. This objective is centered on Lago region. In Varant, use settlements, oases, roads and ruin silhouettes as navigation anchors; open desert shortcuts can easily lead into predator packs or the wrong canyon.", "If following the Hashishin route, eliminate the relevant Nomad group and report the result.", "After the objective is complete, return to the named quest giver or destination and exhaust the new dialogue. For kill quests, search the whole marked area if the completion message has not appeared; isolated enemies can wander away from their group.", "Conflicts with Vatras/Nomad progression; save before committing."),
            reward = "",
            warnings = "⚠ Faction / progression warning: Create a manual save before resolving this objective. It can remove NPCs, alter Hashishin/Nomad access or close later quests.",
            searchTags = listOf("Destroy the nomads connected to Lago.", "Hashishin quest giver", "Lago region", "DEFER — HASHISHIN PATH")
        ),
        Quest(
            id = "G3-P5-040",
            chapter = 5,
            playOrder = 40,
            title = "Talk to Julio.",
            category = "SAFE",
            giver = "Julio",
            location = "Ben Sala",
            prerequisites = "",
            summary = "Speak with Julio, the town's leader, about the disaster around Ben Sala and the undead threat.",
            walkthroughSteps = listOf("Begin with Julio. This objective is centered on Ben Sala. In Varant, use settlements, oases, roads and ruin silhouettes as navigation anchors; open desert shortcuts can easily lead into predator packs or the wrong canyon.", "Speak with Julio, the town's leader, about the disaster around Ben Sala and the undead threat.", "After the objective is complete, return to the named quest giver or destination and exhaust the new dialogue. For kill quests, search the whole marked area if the completion message has not appeared; isolated enemies can wander away from their group.", "His dialogue frames the entire Ben Sala quest chain."),
            reward = "",
            warnings = "",
            searchTags = listOf("Talk to Julio.", "Julio", "Ben Sala", "SAFE")
        ),
        Quest(
            id = "G3-P5-041",
            chapter = 5,
            playOrder = 41,
            title = "The undead around Ben Sala.",
            category = "SAFE",
            giver = "Julio / town defenders",
            location = "Ben Sala outskirts",
            prerequisites = "",
            summary = "Systematically clear the undead groups surrounding the settlement so travel and trade become safer.",
            walkthroughSteps = listOf("Begin with Julio / town defenders. This objective is centered on Ben Sala outskirts. In Varant, use settlements, oases, roads and ruin silhouettes as navigation anchors; open desert shortcuts can easily lead into predator packs or the wrong canyon.", "Systematically clear the undead groups surrounding the settlement so travel and trade become safer.", "After the objective is complete, return to the named quest giver or destination and exhaust the new dialogue. For kill quests, search the whole marked area if the completion message has not appeared; isolated enemies can wander away from their group.", "Work outward from town rather than pulling several undead groups together."),
            reward = "",
            warnings = "",
            searchTags = listOf("The undead around Ben Sala.", "Julio / town defenders", "Ben Sala outskirts", "SAFE")
        ),
        Quest(
            id = "G3-P5-042",
            chapter = 5,
            playOrder = 42,
            title = "Clean out the cave near Ben Sala.",
            category = "SAFE",
            giver = "Ben Sala quest giver",
            location = "Cave near Ben Sala",
            prerequisites = "",
            summary = "Enter the specified cave, destroy all undead/creatures inside and search it thoroughly before reporting back.",
            walkthroughSteps = listOf("Begin with Ben Sala quest giver. This objective is centered on Cave near Ben Sala. In Varant, use settlements, oases, roads and ruin silhouettes as navigation anchors; open desert shortcuts can easily lead into predator packs or the wrong canyon.", "Enter the specified cave, destroy all undead/creatures inside and search it thoroughly before reporting back.", "After the objective is complete, return to the named quest giver or destination and exhaust the new dialogue. For kill quests, search the whole marked area if the completion message has not appeared; isolated enemies can wander away from their group.", "Check side passages for quest items and chests."),
            reward = "",
            warnings = "",
            searchTags = listOf("Clean out the cave near Ben Sala.", "Ben Sala quest giver", "Cave near Ben Sala", "SAFE")
        ),
        Quest(
            id = "G3-P5-043",
            chapter = 5,
            playOrder = 43,
            title = "The tunnel of the undead.",
            category = "SAFE",
            giver = "Ben Sala mine/tunnel quest giver",
            location = "Ben Sala",
            prerequisites = "",
            summary = "Explore the affected tunnel and destroy the undead occupying it.",
            walkthroughSteps = listOf("Begin with Ben Sala mine/tunnel quest giver. This objective is centered on Ben Sala. In Varant, use settlements, oases, roads and ruin silhouettes as navigation anchors; open desert shortcuts can easily lead into predator packs or the wrong canyon.", "Explore the affected tunnel and destroy the undead occupying it.", "After the objective is complete, return to the named quest giver or destination and exhaust the new dialogue. For kill quests, search the whole marked area if the completion message has not appeared; isolated enemies can wander away from their group.", "Use blunt or strong melee/ranged attacks appropriate to skeletons and zombies."),
            reward = "",
            warnings = "",
            searchTags = listOf("The tunnel of the undead.", "Ben Sala mine/tunnel quest giver", "Ben Sala", "SAFE")
        ),
        Quest(
            id = "G3-P5-044",
            chapter = 5,
            playOrder = 44,
            title = "The ruined mine.",
            category = "SAFE",
            giver = "Ben Sala miner",
            location = "Ben Sala region",
            prerequisites = "",
            summary = "Investigate the mine ruined by the undead outbreak, clear hostile occupants and report what you find.",
            walkthroughSteps = listOf("Begin with Ben Sala miner. This objective is centered on Ben Sala region. In Varant, use settlements, oases, roads and ruin silhouettes as navigation anchors; open desert shortcuts can easily lead into predator packs or the wrong canyon.", "Investigate the mine ruined by the undead outbreak, clear hostile occupants and report what you find.", "After the objective is complete, return to the named quest giver or destination and exhaust the new dialogue. For kill quests, search the whole marked area if the completion message has not appeared; isolated enemies can wander away from their group.", "Combine with ore/weapon searches in the same area."),
            reward = "",
            warnings = "",
            searchTags = listOf("The ruined mine.", "Ben Sala miner", "Ben Sala region", "SAFE")
        ),
        Quest(
            id = "G3-P5-045",
            chapter = 5,
            playOrder = 45,
            title = "Weapons for Ben Sala.",
            category = "SAFE / COLLECTION",
            giver = "Ben Sala guard/merchant",
            location = "Ben Sala",
            prerequisites = "",
            summary = "Collect the requested weapon bundles or weapons and deliver them to the defenders.",
            walkthroughSteps = listOf("Begin with Ben Sala guard/merchant. This objective is centered on Ben Sala. In Varant, use settlements, oases, roads and ruin silhouettes as navigation anchors; open desert shortcuts can easily lead into predator packs or the wrong canyon.", "Collect the requested weapon bundles or weapons and deliver them to the defenders.", "After the objective is complete, return to the named quest giver or destination and exhaust the new dialogue. For kill quests, search the whole marked area if the completion message has not appeared; isolated enemies can wander away from their group.", "Keep Bundles of Weapons from Myrtana if you still have them."),
            reward = "",
            warnings = "",
            searchTags = listOf("Weapons for Ben Sala.", "Ben Sala guard/merchant", "Ben Sala", "SAFE / COLLECTION")
        ),
        Quest(
            id = "G3-P5-046",
            chapter = 5,
            playOrder = 46,
            title = "Ore for the smith.",
            category = "SAFE / COLLECTION",
            giver = "Ben Sala smith",
            location = "Ben Sala",
            prerequisites = "",
            summary = "Bring the smith the ore/raw materials he requests.",
            walkthroughSteps = listOf("Begin with Ben Sala smith. This objective is centered on Ben Sala. In Varant, use settlements, oases, roads and ruin silhouettes as navigation anchors; open desert shortcuts can easily lead into predator packs or the wrong canyon.", "Bring the smith the ore/raw materials he requests.", "After the objective is complete, return to the named quest giver or destination and exhaust the new dialogue. For kill quests, search the whole marked area if the completion message has not appeared; isolated enemies can wander away from their group.", "Do before selling mine loot."),
            reward = "",
            warnings = "",
            searchTags = listOf("Ore for the smith.", "Ben Sala smith", "Ben Sala", "SAFE / COLLECTION")
        ),
        Quest(
            id = "G3-P5-047",
            chapter = 5,
            playOrder = 47,
            title = "Healing potions for the defenders.",
            category = "SAFE / DELIVERY",
            giver = "Ben Sala quest giver",
            location = "Ben Sala",
            prerequisites = "",
            summary = "Deliver the requested healing potions to support the town against the undead.",
            walkthroughSteps = listOf("Begin with Ben Sala quest giver. This objective is centered on Ben Sala. In Varant, use settlements, oases, roads and ruin silhouettes as navigation anchors; open desert shortcuts can easily lead into predator packs or the wrong canyon.", "Deliver the requested healing potions to support the town against the undead.", "After the objective is complete, return to the named quest giver or destination and exhaust the new dialogue. For kill quests, search the whole marked area if the completion message has not appeared; isolated enemies can wander away from their group.", "Arrive stocked; the local battles can consume many potions."),
            reward = "",
            warnings = "",
            searchTags = listOf("Healing potions for the defenders.", "Ben Sala quest giver", "Ben Sala", "SAFE / DELIVERY")
        ),
        Quest(
            id = "G3-P5-048",
            chapter = 5,
            playOrder = 48,
            title = "The cursed temple near Ben Sala.",
            category = "SAFE / DUNGEON",
            giver = "Ben Sala / temple quest chain",
            location = "Ben Sala ruins",
            prerequisites = "",
            summary = "Travel to the nearby ancient temple/ruins, fight through the undead and investigate the source of the outbreak.",
            walkthroughSteps = listOf("Begin with Ben Sala / temple quest chain. This objective is centered on Ben Sala ruins. In Varant, use settlements, oases, roads and ruin silhouettes as navigation anchors; open desert shortcuts can easily lead into predator packs or the wrong canyon.", "Travel to the nearby ancient temple/ruins, fight through the undead and investigate the source of the outbreak.", "After the objective is complete, return to the named quest giver or destination and exhaust the new dialogue. For kill quests, search the whole marked area if the completion message has not appeared; isolated enemies can wander away from their group.", "This area is more dangerous than the ordinary town quests; prepare before entering."),
            reward = "",
            warnings = "",
            searchTags = listOf("The cursed temple near Ben Sala.", "Ben Sala / temple quest chain", "Ben Sala ruins", "SAFE / DUNGEON")
        ),
        Quest(
            id = "G3-P5-049",
            chapter = 5,
            playOrder = 49,
            title = "Find the source of the undead.",
            category = "SAFE / INVESTIGATION",
            giver = "Julio / temple chain",
            location = "Ben Sala region",
            prerequisites = "",
            summary = "Follow the clues from the mines, caves and ruins to identify the cause or central threat behind the undead plague.",
            walkthroughSteps = listOf("Begin with Julio / temple chain. This objective is centered on Ben Sala region. In Varant, use settlements, oases, roads and ruin silhouettes as navigation anchors; open desert shortcuts can easily lead into predator packs or the wrong canyon.", "Follow the clues from the mines, caves and ruins to identify the cause or central threat behind the undead plague.", "After the objective is complete, return to the named quest giver or destination and exhaust the new dialogue. For kill quests, search the whole marked area if the completion message has not appeared; isolated enemies can wander away from their group.", "Do the smaller undead-clearing quests first; they naturally lead toward the source."),
            reward = "",
            warnings = "",
            searchTags = listOf("Find the source of the undead.", "Julio / temple chain", "Ben Sala region", "SAFE / INVESTIGATION")
        ),
        Quest(
            id = "G3-P5-050",
            chapter = 5,
            playOrder = 50,
            title = "Kill the undead leaders.",
            category = "SAFE",
            giver = "Ben Sala quest chain",
            location = "Ben Sala ruins",
            prerequisites = "",
            summary = "Destroy the named/elite undead controlling groups around the settlement and temple.",
            walkthroughSteps = listOf("Begin with Ben Sala quest chain. This objective is centered on Ben Sala ruins. In Varant, use settlements, oases, roads and ruin silhouettes as navigation anchors; open desert shortcuts can easily lead into predator packs or the wrong canyon.", "Destroy the named/elite undead controlling groups around the settlement and temple.", "After the objective is complete, return to the named quest giver or destination and exhaust the new dialogue. For kill quests, search the whole marked area if the completion message has not appeared; isolated enemies can wander away from their group.", "Loot every named enemy for keys and quest items."),
            reward = "",
            warnings = "",
            searchTags = listOf("Kill the undead leaders.", "Ben Sala quest chain", "Ben Sala ruins", "SAFE")
        ),
        Quest(
            id = "G3-P5-051",
            chapter = 5,
            playOrder = 51,
            title = "Basir's old chest / treasure.",
            category = "SAFE",
            giver = "Basir-related quest chain",
            location = "Ben Sala ruins",
            prerequisites = "",
            summary = "Locate the treasure/chest connected to Basir's past in the ruined area and recover the requested item or information.",
            walkthroughSteps = listOf("Begin with Basir-related quest chain. This objective is centered on Ben Sala ruins. In Varant, use settlements, oases, roads and ruin silhouettes as navigation anchors; open desert shortcuts can easily lead into predator packs or the wrong canyon.", "Locate the treasure/chest connected to Basir's past in the ruined area and recover the requested item or information.", "After the objective is complete, return to the named quest giver or destination and exhaust the new dialogue. For kill quests, search the whole marked area if the completion message has not appeared; isolated enemies can wander away from their group.", "This connects back to characters encountered earlier in Myrtana."),
            reward = "",
            warnings = "",
            searchTags = listOf("Basir's old chest / treasure.", "Basir-related quest chain", "Ben Sala ruins", "SAFE")
        ),
        Quest(
            id = "G3-P5-052",
            chapter = 5,
            playOrder = 52,
            title = "Escort the merchant through the dangerous area.",
            category = "SAFE / ESCORT",
            giver = "Ben Sala merchant",
            location = "Ben Sala road",
            prerequisites = "",
            summary = "Protect the merchant while traveling through the undead-infested route and keep him alive until the destination is reached.",
            walkthroughSteps = listOf("Begin with Ben Sala merchant. This objective is centered on Ben Sala road. In Varant, use settlements, oases, roads and ruin silhouettes as navigation anchors; open desert shortcuts can easily lead into predator packs or the wrong canyon.", "Protect the merchant while traveling through the undead-infested route and keep him alive until the destination is reached.", "After the objective is complete, return to the named quest giver or destination and exhaust the new dialogue. For kill quests, search the whole marked area if the completion message has not appeared; isolated enemies can wander away from their group.", "Clear the road first if you want the safest escort."),
            reward = "",
            warnings = "",
            searchTags = listOf("Escort the merchant through the dangerous area.", "Ben Sala merchant", "Ben Sala road", "SAFE / ESCORT")
        ),
        Quest(
            id = "G3-P5-053",
            chapter = 5,
            playOrder = 53,
            title = "Clear the road to Bakaresh.",
            category = "SAFE",
            giver = "Ben Sala quest giver",
            location = "Ben Sala → Bakaresh road",
            prerequisites = "",
            summary = "Kill undead and other hostile creatures blocking the eastern/southern road so caravans can move again.",
            walkthroughSteps = listOf("Begin with Ben Sala quest giver. This objective is centered on Ben Sala → Bakaresh road. In Varant, use settlements, oases, roads and ruin silhouettes as navigation anchors; open desert shortcuts can easily lead into predator packs or the wrong canyon.", "Kill undead and other hostile creatures blocking the eastern/southern road so caravans can move again.", "After the objective is complete, return to the named quest giver or destination and exhaust the new dialogue. For kill quests, search the whole marked area if the completion message has not appeared; isolated enemies can wander away from their group.", "This prepares the transition into Part VI."),
            reward = "",
            warnings = "",
            searchTags = listOf("Clear the road to Bakaresh.", "Ben Sala quest giver", "Ben Sala → Bakaresh road", "SAFE")
        ),
        Quest(
            id = "G3-P5-054",
            chapter = 5,
            playOrder = 54,
            title = "Report the end of the undead threat.",
            category = "SAFE",
            giver = "Julio",
            location = "Ben Sala",
            prerequisites = "",
            summary = "After completing the major undead-clearing objectives, return to Julio and report that the settlement is secure.",
            walkthroughSteps = listOf("Begin with Julio. This objective is centered on Ben Sala. In Varant, use settlements, oases, roads and ruin silhouettes as navigation anchors; open desert shortcuts can easily lead into predator packs or the wrong canyon.", "After completing the major undead-clearing objectives, return to Julio and report that the settlement is secure.", "After the objective is complete, return to the named quest giver or destination and exhaust the new dialogue. For kill quests, search the whole marked area if the completion message has not appeared; isolated enemies can wander away from their group.", "Do not forget the final report; several Gothic 3 quest chains pay only after the closing dialogue."),
            reward = "",
            warnings = "",
            searchTags = listOf("Report the end of the undead threat.", "Julio", "Ben Sala", "SAFE")
        ),
        Quest(
            id = "G3-P5-055",
            chapter = 5,
            playOrder = 55,
            title = "Liberate Ben Sala.",
            category = "DEFER — NOMAD PATH",
            giver = "Nomad / player action",
            location = "Ben Sala",
            prerequisites = "",
            summary = "If choosing to remove Hashishin control, finish every neutral undead, trade and smith quest first, then defeat the town's Hashishin defenders.",
            walkthroughSteps = listOf("Begin with Nomad / player action. This objective is centered on Ben Sala. In Varant, use settlements, oases, roads and ruin silhouettes as navigation anchors; open desert shortcuts can easily lead into predator packs or the wrong canyon.", "If choosing to remove Hashishin control, finish every neutral undead, trade and smith quest first, then defeat the town's Hashishin defenders.", "After the objective is complete, return to the named quest giver or destination and exhaust the new dialogue. For kill quests, search the whole marked area if the completion message has not appeared; isolated enemies can wander away from their group.", "The undead quests are largely useful regardless of faction, so there is no reason to liberate early."),
            reward = "",
            warnings = "⚠ Faction / progression warning: Create a manual save before resolving this objective. It can remove NPCs, alter Hashishin/Nomad access or close later quests.",
            searchTags = listOf("Liberate Ben Sala.", "Nomad / player action", "Ben Sala", "DEFER — NOMAD PATH")
        ),
        Quest(
            id = "G3-P5-056",
            chapter = 5,
            playOrder = 56,
            title = "Destroy the nomads near Ben Sala.",
            category = "DEFER — HASHISHIN PATH",
            giver = "Hashishin leadership",
            location = "Ben Sala region",
            prerequisites = "",
            summary = "On the Hashishin route, locate and destroy the designated Nomad group before reporting back.",
            walkthroughSteps = listOf("Begin with Hashishin leadership. This objective is centered on Ben Sala region. In Varant, use settlements, oases, roads and ruin silhouettes as navigation anchors; open desert shortcuts can easily lead into predator packs or the wrong canyon.", "On the Hashishin route, locate and destroy the designated Nomad group before reporting back.", "After the objective is complete, return to the named quest giver or destination and exhaust the new dialogue. For kill quests, search the whole marked area if the completion message has not appeared; isolated enemies can wander away from their group.", "Finish their available quests first if pursuing completionist coverage."),
            reward = "",
            warnings = "⚠ Faction / progression warning: Create a manual save before resolving this objective. It can remove NPCs, alter Hashishin/Nomad access or close later quests.",
            searchTags = listOf("Destroy the nomads near Ben Sala.", "Hashishin leadership", "Ben Sala region", "DEFER — HASHISHIN PATH")
        ),
    )
}
