package com.sliverzfx.gothicquest

private val gothic2QuestGivers = mapOf(

)

internal fun g2q(id:String, order:Int, title:String, type:String, region:String, path:String, stage:String, objective:String, walkthrough:String, notes:String) = Quest(id,1,order,title,category="$type / $path",giver=gothic2QuestGivers[id] ?: "Trigger quest",location=region,prerequisites=stage,summary=objective,walkthroughSteps=walkthrough.split("§"),reward="Not specified in the master guide",warnings=notes,searchTags=listOf(title.lowercase(),region.lowercase(),path.lowercase()))
object Gothic2Chapter1Part1 {
    val quests = listOf(
        g2q("G2G-C01-070",1,"The Eye of Innos","Main Quest","Khorinis / Monastery / Sun Circle","Main quest","Route stage 1 — Xardas, Cavalorn and the road to Khorinis","Obtain, recover and restore the Eye of Innos so you can confront the dragons.","Tell Lord Hagen why you need the Eye.§Progress through Evidence and Chapter 2.§In Chapter 3 discover the Eye has been stolen and broken, recover it at the Sun Circle, have Bennet repair the setting, obtain three swampweed plants for the ritual, and bring Xardas, Vatras and Pyrokar together to recharge it.","This is the central multi-chapter quest; Night of the Raven requires resolving the Jharkendar/Raven arc so Vatras can leave Khorinis."),
        g2q("G2G-C01-036",2,"Herbs for Constantino","Side Quest","Xardas’ Tower / Khorinis","Night of the Raven","Route stage 1 — Xardas, Cavalorn and the road to Khorinis","Use Lester’s herb-collector story to get into Khorinis.","Ask Lester how to enter the city.§Tell the guards you collect herbs for Constantino, enter Khorinis, speak with Constantino about herbs, then return to Lester to confirm the trick worked.","One of the best free entry methods."),
        g2q("G2G-C01-098",3,"Wanted Posters and Bandits","Side Quest","Xardas road / Onar countryside","Night of the Raven","Route stage 1 — Xardas, Cavalorn and the road to Khorinis","Learn who ordered the attacks on you and follow the bandit lead.","Question the friendly bandit near Cavalorn’s hideout and learn Dexter’s name.§Later travel to Dexter’s camp near Onar’s farm, use his name to get past the guard and confront him.","The journal entry may linger until later even after you have the crucial information."),
        g2q("G2G-C01-020",4,"Cavalorn's Bandits","Side Quest","Xardas’ Tower road","Night of the Raven","Route stage 1 — Xardas, Cavalorn and the road to Khorinis","Help Cavalorn recover his stolen belongings from nearby bandits.","Meet Cavalorn on the road.§Talk to the lone bandit first if you want all dialogue XP, then tell Cavalorn you are ready.§Follow him into the hideout, defeat the bandits, loot Brago and take the important letter.","The stolen letter starts the Water Mage/Ring of Water investigation."),
        g2q("G2G-C01-085",5,"The Ring of Water","Main Quest","Khorinis / Dead Harpy Tavern","Night of the Raven","Route stage 1 — Xardas, Cavalorn and the road to Khorinis","Prove yourself and become a member of the Ring of Water.","Ask Vatras about the Ring.§Complete the missing-people investigation and deliver your dragon warning to Lord Hagen.§Attend the meeting at the Dead Harpy Tavern, speak to Lares and the members, receive the armor/sign, then return to Vatras for your first mission to Saturas.","Core prerequisite for entering Jharkendar."),
        g2q("G2G-C01-091",6,"The Water Mages","Side Quest","Xardas road / Ancient Ruins","Night of the Raven","Route stage 1 — Xardas, Cavalorn and the road to Khorinis","Deliver the stolen message and make contact with Saturas’s expedition.","Take the letter from Brago after Cavalorn’s Bandits and deliver it to Vatras.§Follow Lares toward the ancient ruins when ready, meet Saturas and the Water Mages, and continue the portal investigation.","Early backbone of the Night of the Raven storyline."),
        g2q("G2G-C01-063",7,"The Bandits at Lobart's Farm","Side Quest","Lobart’s Farm","General","Route stage 1 — Xardas, Cavalorn and the road to Khorinis","Remove the bandits troubling Lobart’s workers.","Speak to Maleth about the bandits near Xardas’s road.§Coordinate with Cavalorn if desired, kill the bandits in their cave, and report back to Maleth.","Overlaps directly with Cavalorn’s Bandits."),
        g2q("G2G-C01-054",8,"Pulling Turnips","Side Quest","Lobart’s Farm","General","Route stage 1 — Xardas, Cavalorn and the road to Khorinis","Harvest Lobart’s turnip field.","Agree to work for Lobart.§Pick all turnips from the marked field and report back to him.","First step in Lobart’s work-clothes chain."),
        g2q("G2G-C01-017",9,"Bring the Turnips to Hilda","Side Quest","Lobart’s Farm","General","Route stage 1 — Xardas, Cavalorn and the road to Khorinis","Deliver the harvested turnips to Hilda.","Finish Pulling Turnips, take the crop from Lobart, carry it into the farmhouse and give it to Hilda.","Leads into A Pan for Hilda."),
        g2q("G2G-C01-004",10,"A Pan for Hilda","Side Quest","Lobart’s Farm","General","Route stage 1 — Xardas, Cavalorn and the road to Khorinis","Buy a cooking pan for Hilda.","Complete Bring the Turnips to Hilda.§Take Hilda’s money, buy the pan from Canthar on the road, and return it to Hilda as soon as possible.","The reward decreases if you delay; keeping her money can permanently sour her attitude."),
        g2q("G2G-C01-033",11,"For a Bottle of Wine","Side Quest","Lobart’s Farm","General","Route stage 1 — Xardas, Cavalorn and the road to Khorinis","Bring Vino a bottle of wine.","Talk to Vino in the fields, give him a bottle of wine, and finish the dialogue.","Very small early quest."),
        g2q("G2G-C01-044",12,"Lobart's Worker Outfit","Side Quest","Lobart’s Farm","General","Route stage 1 — Xardas, Cavalorn and the road to Khorinis","Earn or buy peasant clothes from Lobart.","Ask Lobart for work and complete farm chores such as turnips and errands.§Each completed task lowers the price of the outfit.§Buy the clothes when affordable.","Wearing the outfit helps with the “farmer” entry story at Khorinis."),
        g2q("G2G-C01-078",13,"The Man with the Eyepatch","Side Quest","Khorinis / countryside","Night of the Raven","Route stage 1 — Xardas, Cavalorn and the road to Khorinis","Help Greg with his buried treasure and entry into Khorinis.","Meet Greg near Lobart’s farm/city road.§Help with the early treasure spot, later meet him outside the city and assist with his disguise/entry.§Follow his treasure-map clues as they become available.","Greg is central to the pirate/Jharkendar story and reappears repeatedly."),
        g2q("G2G-C01-007",14,"Access to the City of Khorinis","Main Quest","Lobart’s Farm / Khorinis","Main progression","Route stage 1 — Xardas, Cavalorn and the road to Khorinis","Get past the city gate without being rejected as an unknown drifter.","Use one of several routes: work for Lobart and wear peasant clothes; use Lester’s herb-collector story for Constantino; present Canthar’s pass; or pay/bribe your way in.§Speak to the gate guards and enter Khorinis.","The herb-collector and Lobart routes preserve early gold and open extra dialogue."),
        g2q("G2G-C01-092",15,"The Way to the Upper Quarter","Main Quest","Khorinis","Main progression","Route stage 2 — First day in Khorinis: citizenship and city errands","Gain legal access to the Upper Quarter.","Learn from Rupert/guards that ordinary outsiders are barred.§Become a citizen through an apprenticeship or join a recognized faction, then show your status to the Upper Quarter guards.","Required to meet Lord Hagen normally."),
        g2q("G2G-C01-010",16,"Apprentice in Khorinis","Side Quest","Khorinis","Citizenship","Route stage 2 — First day in Khorinis: citizenship and city errands","Become a citizen by earning the approval of the city masters.","Speak with Matteo, Bosper, Constantino, Harad and Thorben and complete enough of their approval tasks.§Choose a master for your apprenticeship and report the decision.","Your chosen apprenticeship affects income/training opportunities; you do not need to apprentice under every master."),
        g2q("G2G-C01-047",17,"Matteo and Gritta","Side Quest","Khorinis","Citizenship","Route stage 2 — First day in Khorinis: citizenship and city errands","Collect the money Gritta owes Matteo.","Speak to Matteo.§Visit Gritta in Thorben’s house and persuade her to pay, cover the debt yourself, or use another dialogue solution.§Return the 100 gold to Matteo.","One of the master-approval quests for citizenship."),
        g2q("G2G-C01-051",18,"Pelts for Bosper","Side Quest","Khorinis","Citizenship","Route stage 2 — First day in Khorinis: citizenship and city errands","Bring Bosper six wolf pelts.","Learn skinning from Bosper if needed.§Hunt wolves or obtain pelts elsewhere, then give Bosper six pelts.","Completes Bosper’s approval for apprenticeship/citizenship."),
        g2q("G2G-C01-064",19,"The Blessing of the Gods","Side Quest","Khorinis","Citizenship","Route stage 2 — First day in Khorinis: citizenship and city errands","Receive divine blessings so Thorben will approve you.","Ask Thorben what he requires.§Obtain a blessing from Vatras and another from a priest of Innos, usually Daron, then return to Thorben.","Daron may require a donation; this approval also opens lockpicking training from Thorben."),
        g2q("G2G-C01-002",20,"A Great Challenge","Side Quest","Khorinis","Citizenship","Route stage 2 — First day in Khorinis: citizenship and city errands","Earn Harad’s approval for an apprenticeship by proving you can handle an orc weapon.","Ask Harad what he requires.§Obtain a Light Orc Axe; the safest early option is the cave in the eastern valley, though hunting with Bartok is another route.§Bring the axe to Harad.","If you tell Harad the challenge is too hard, he can redirect you to the Bandit Raids task.")
    )
}