package com.sliverzfx.gothicquest

internal object Gothic3Part5Data {
    val quests = listOf(
        Quest(
            id = "G3-P5-001",
            chapter = 5,
            playOrder = 1,
            title = "Talk to Nafalem.",
            category = "SAFE",
            giver = "Nafalem",
            location = "Braga",
            prerequisites = "Reach Braga and speak with Hashishin leader Nafalem.",
            summary = "Find Nafalem, Braga's Hashishin leader, and exhaust his dialogue about the town, tribute and Nomad threat.",
            walkthroughSteps = listOf("Enter Braga and speak to Hashishin leader Nafalem near his residence.", "Ask about the tribute collection and the Nomad problem.", "Begin Tribute from Braga, then talk with Tufail and the debtors he identifies.", "Resolve the town's neutral tasks before choosing Asaru's Nomads or Nafalem's Hashishin."),
            reward = "Unlocks the tribute and nomad bounty questlines centered on Braga.",
            warnings = "Nafalem's conversation is the setup for several quests, not a stand-alone 1,000-XP journal mission.",
            searchTags = listOf("Talk to Nafalem.", "Nafalem", "Braga", "SAFE")
        ),
        Quest(
            id = "G3-P5-002",
            chapter = 5,
            playOrder = 2,
            title = "The tribute from Braga.",
            category = "SAFE / COLLECTION",
            giver = "Nafalem",
            location = "Braga",
            prerequisites = "Speak with Nafalem about collecting Braga's unpaid tribute.",
            summary = "Collect the outstanding tribute payments and goods from the people Nafalem names, then return to him with the required total.",
            walkthroughSteps = listOf("Speak to Nafalem and learn which Braga debtors owe tribute.", "Ask Tufail for leads on the missing tribute, then approach Bernado, Jose, Luca and Abbas.", "Do each debtor's related task before returning to Nafalem with the proceeds.", "Finish the full report to receive Hashishin and local Braga reputation."),
            reward = "1,500 XP, +10 Hashishin reputation and +15 Braga reputation.",
            warnings = "Bernado must be DEFEATED rather than killed; Luca needs the dark snapper skin first. Nomad/Hashishin choices affect which tasks remain.",
            searchTags = listOf("The tribute from Braga.", "Nafalem", "Braga", "SAFE / COLLECTION")
        ),
        Quest(
            id = "G3-P5-003",
            chapter = 5,
            playOrder = 3,
            title = "Bernado's tribute.",
            category = "SAFE",
            giver = "Bernado (tribute debtor); Nafalem commissions collection",
            location = "Braga",
            prerequisites = "Start Nafalem's tribute collection and ask Bernado to pay.",
            summary = "Speak with Bernado about the tribute he owes and obtain the required payment for Nafalem.",
            walkthroughSteps = listOf("Find Bernado in Braga after accepting Nafalem's collection task.", "Demand the outstanding tribute. Bernado refuses to pay a second time.", "Beat Bernado nonlethally, then take the payment and report the outcome."),
            reward = "1,000 XP and +5 Braga reputation.",
            warnings = "Do NOT kill Bernado; you need him alive to complete the tribute safely.",
            searchTags = listOf("Bernado's tribute.", "Bernado / Nafalem", "Braga", "SAFE")
        ),
        Quest(
            id = "G3-P5-004",
            chapter = 5,
            playOrder = 4,
            title = "Jose's tribute.",
            category = "SAFE",
            giver = "Jose",
            location = "Braga",
            prerequisites = "Start Nafalem's Braga tribute quest and talk to Jose.",
            summary = "Collect Jose's share of Braga's tribute and keep it for the final hand-in to Nafalem.",
            walkthroughSteps = listOf("Ask bounty hunter Jose about his unpaid Braga tribute after starting Nafalem's collection.", "Jose hands over his share without demanding another service.", "Ask him about the bounty contract for Asaru, Malir and Taklar, then return to Nafalem."),
            reward = "500 XP and +5 Braga reputation; opens Jose's bounty-hunting lead.",
            warnings = "",
            searchTags = listOf("Jose's tribute.", "Jose / Nafalem", "Braga", "SAFE")
        ),
        Quest(
            id = "G3-P5-005",
            chapter = 5,
            playOrder = 5,
            title = "Luca's tribute.",
            category = "SAFE",
            giver = "Luca (tribute debtor); Nafalem commissions collection",
            location = "Braga",
            prerequisites = "Accept Nafalem's tribute task and speak with Luca about his missing goods.",
            summary = "Obtain Luca's contribution to the tribute and return it as part of Nafalem's collection.",
            walkthroughSteps = listOf("Ask Luca to pay his tribute in Braga.", "Luca will pay after you bring the dark snapper skin he wants.", "Hunt a dark snapper and obtain its skin, then return to Luca.", "Collect the tribute and report to Nafalem."),
            reward = "500 XP and +5 Braga reputation for Luca's tribute; separate hunting rewards may apply.",
            warnings = "",
            searchTags = listOf("Luca's tribute.", "Luca / Nafalem", "Braga", "SAFE")
        ),
        Quest(
            id = "G3-P5-006",
            chapter = 5,
            playOrder = 6,
            title = "Abbas's tribute.",
            category = "SAFE",
            giver = "Abbas (water trader in Braga)",
            location = "Braga",
            prerequisites = "Investigate Nafalem's tribute and Abbas's lost water-vendor chalice.",
            summary = "Collect the tribute demanded from Abbas and include it in Nafalem's total.",
            walkthroughSteps = listOf("Find Abbas and ask why his tribute has not been delivered.", "Follow Tufail to the bandits who stole the water vendors' chalice.", "Clear the bandit cave and open their chest to recover the chalice.", "Bring the chalice back to Abbas, then finish Nafalem's tribute report."),
            reward = "1,500 XP and +5 Braga reputation for recovering Abbas's water-vendor chalice.",
            warnings = "The WATER VENDORS' CHALICE is not one of the twelve magical Fire Chalices. Do not confuse the two items.",
            searchTags = listOf("Abbas's tribute.", "Abbas / Nafalem", "Braga", "SAFE")
        ),
        Quest(
            id = "G3-P5-007",
            chapter = 5,
            playOrder = 7,
            title = "The dark snapper hunt.",
            category = "SAFE / HUNT",
            giver = "Luca (Braga leather merchant)",
            location = "Desert around Braga",
            prerequisites = "Speak with Luca when collecting Braga's tribute.",
            summary = "Track the designated dark snappers outside Braga and kill the full group. Return to the hunter when the objective message appears.",
            walkthroughSteps = listOf("Ask Luca about his tribute; he asks for dark snapper hides for an armor.", "Go north of Braga toward the ruins, where dark snappers roam; Diego can help with the hunt.", "Learn skinning if needed and collect FIVE dark snapper hides.", "Bring five hides to Luca, then collect his tribute for Nafalem."),
            reward = "1,000 XP for Dark Snapper Leather; Luca's tribute is a separate 500 XP and +5 Braga reputation.",
            warnings = "FIVE DARK SNAPPER skins, not merely killing a pack.",
            searchTags = listOf("The dark snapper hunt.", "Braga hunter", "Desert around Braga", "SAFE / HUNT")
        ),
        Quest(
            id = "G3-P5-008",
            chapter = 5,
            playOrder = 8,
            title = "Hunt with Diego near Braga",
            category = "SAFE / HUNT",
            giver = "Diego",
            location = "Braga wilderness",
            prerequisites = "",
            summary = "Join or assist the hunter with the dangerous beasts around Braga and kill the designated targets.",
            walkthroughSteps = listOf("Find Diego near Braga and ask him to help hunt dark snappers.", "Follow Diego into the ruins north of Braga.", "Defeat the dark snappers and extract their hides if you are completing Luca's tribute quest.", "Finish Diego's hunting dialogue and return five hides to Luca if required."),
            reward = "",
            warnings = "Tied to Diego's outdoor hunt and Luca's five-skin requirement; the old generic 'desert beasts' title was imprecise.",
            searchTags = listOf("Hunt the dangerous desert beasts.", "Diego / Braga hunter chain", "Braga wilderness", "SAFE / HUNT")
        ),
        Quest(
            id = "G3-P5-009",
            chapter = 5,
            playOrder = 9,
            title = "Follow Diego into the desert.",
            category = "SAFE / ESCORT",
            giver = "Diego",
            location = "Braga → desert",
            prerequisites = "",
            summary = "Accompany Diego on his route outside Braga and stay close while he leads you to the hunting/objective area.",
            walkthroughSteps = listOf("Talk to Diego near the Braga approach and ask him to guide you into the desert.", "Follow his route without sprinting out of escort distance.", "Deal with dark snappers or other enemies on the way.", "Speak to Diego at his stopping point to complete the guidance."),
            reward = "",
            warnings = "Do not confuse Diego's introductory escort with Luca's separate five-dark-snapper-hide delivery.",
            searchTags = listOf("Follow Diego into the desert.", "Diego", "Braga → desert", "SAFE / ESCORT")
        ),
        Quest(
            id = "G3-P5-010",
            chapter = 5,
            playOrder = 10,
            title = "Aila.",
            category = "CHOICE",
            giver = "Nafalem / Jose (Aila's fate)",
            location = "Braga / Nomad area",
            prerequisites = "Travel from Braga to Asaru's Nomad cave and find Aila.",
            summary = "Investigate Aila's disappearance/capture and locate her through the Nomad-related quest chain.",
            walkthroughSteps = listOf("Ask Nafalem or Jose about missing Aila.", "Find Aila at Asaru's hidden Nomad camp near Braga.", "Choose to escort her to Braga after helping Asaru's deception, or fight the Nomads for a hostile recovery route.", "Take Aila to the agreed destination and report to the faction contact."),
            reward = "1,500 XP and +15 Braga reputation for the completed Aila return route.",
            warnings = "Two routes exist, Nomad DECEPTION and Hashishin VIOLENCE. Killing Asaru blocks his peaceful Nomad quests.",
            searchTags = listOf("Aila.", "Nafalem / Braga quest chain", "Braga / Nomad area", "CHOICE")
        ),
        Quest(
            id = "G3-P5-011",
            chapter = 5,
            playOrder = 11,
            title = "Bring Aila back to Braga.",
            category = "CHOICE — HASHISHIN",
            giver = "Aila",
            location = "Nomad camp → Braga",
            prerequisites = "Find Aila in Asaru's camp and choose the Hashishin return or Nomad trick route.",
            summary = "If choosing the Braga/Hashishin resolution, escort Aila safely back to Braga and deliver her to the appropriate NPC.",
            walkthroughSteps = listOf("Find Asaru's Nomad hideout in the caves around Braga; Aila is staying with his people.", "Speak with Asaru before deciding how to resolve the dispute.", "For the peaceful Nomad trick, agree to return Aila as part of Asaru's plan; alternatively defeat the Nomads to take her by force.", "Escort Aila back to Braga, protect her from wildlife and report to Nafalem or Jose."),
            reward = "1,500 XP and +15 Braga reputation on completing Aila's return.",
            warnings = "The nonviolent deception route preserves Asaru and his Nomad quests; killing Asaru forfeits them.",
            searchTags = listOf("Bring Aila back to Braga.", "Aila / Nafalem", "Nomad camp → Braga", "CHOICE — HASHISHIN")
        ),
        Quest(
            id = "G3-P5-012",
            chapter = 5,
            playOrder = 12,
            title = "Bounty Hunting: Braga",
            category = "DEFER — HASHISHIN PATH",
            giver = "Jose",
            location = "Braga region",
            prerequisites = "Accept Jose/Nafalem's anti-Nomad contracts around Braga.",
            summary = "Locate the Nomad group threatening Braga and eliminate its members, then report to Nafalem.",
            walkthroughSteps = listOf("Ask bounty hunter Jose in Braga for the wanted Nomad leaders.", "The three named targets are Asaru, Malir and Taklar.", "Locate Asaru in his hidden Nomad cave, Malir in another nearby cave and Taklar among the ruins north of Braga.", "On the Hashishin route, defeat all three groups and report the bounty to Jose."),
            reward = "1,500 XP and +5 Braga reputation for the complete bounty; separate target rewards also apply.",
            warnings = "Killing Asaru prevents his Nomad-friendly Aila return and the preparations to liberate Braga.",
            searchTags = listOf("Eliminate the nomads near Braga.", "Nafalem", "Braga region", "DEFER — HASHISHIN PATH")
        ),
        Quest(
            id = "G3-P5-013",
            chapter = 5,
            playOrder = 13,
            title = "Preparations for the Liberation of Braga",
            category = "DEFER — NOMAD PATH",
            giver = "Marus (Asaru's Nomad companion)",
            location = "Braga region",
            prerequisites = "Find Asaru's hidden camp and complete Nomad-friendly work before attacking Braga.",
            summary = "If supporting the Nomads, complete their preparation and attack/undermine the Hashishin position at Braga as directed.",
            walkthroughSteps = listOf("Find Asaru's Nomad group near Braga and choose to support their campaign.", "Speak with his ally Marus about what the Nomads need to raid the town.", "Bring THREE Weapon Bundles; Bernado's stock in Braga can supply them.", "Hand the bundles to Marus and proceed with the Nomad plan."),
            reward = "1,500 XP and +5 Nomads reputation.",
            warnings = "This contradicts Jose and Nafalem's bounty missions; do not kill Asaru or Marus before preparing the liberation.",
            searchTags = listOf("Help the nomads against Braga.", "Nomad leader", "Braga region", "DEFER — NOMAD PATH")
        ),
        Quest(
            id = "G3-P5-014",
            chapter = 5,
            playOrder = 14,
            title = "The Ruin Fields of Braga",
            category = "SAFE",
            giver = "Ayitos (Asaru's Nomads)",
            location = "Braga",
            prerequisites = "",
            summary = "Complete the local conversation/delivery task involving Braga's customs and hospitality, then report to the quest giver.",
            walkthroughSteps = listOf("Find Ayitos among Asaru's Nomads.", "He asks you to clear the ruins outside Braga for the Nomad gathering.", "Travel to the ruins north of Braga, kill the jackals and Taklar's bandits.", "Tell Ayitos when the area is safe."),
            reward = "1,500 XP and +5 Nomads reputation.",
            warnings = "This is the ruin-clearance quest, not the unrelated Bakaresh quest titled A Lesson in Hospitality.",
            searchTags = listOf("A lesson in hospitality.", "Braga quest chain", "Braga", "SAFE")
        ),
        Quest(
            id = "G3-P5-015",
            chapter = 5,
            playOrder = 15,
            title = "A Job for Sancho",
            category = "SAFE",
            giver = "Navaras (Ben Erai mine entrance guard)",
            location = "Ben Erai",
            prerequisites = "Arrive at Ben Erai and ask Sancho about the mines.",
            summary = "Find Sancho, the authority in Ben Erai, and exhaust his dialogue about the mines, slaves and local problems.",
            walkthroughSteps = listOf("At Ben Erai, talk to Navaras guarding the mine entrance.", "He orders you to report to overseer Sancho and obtain an assignment.", "Find Sancho inside the settlement and speak with him within TWO in-game days."),
            reward = "500 XP.",
            warnings = "Two-day deadline according to the classic guide; the old 'Talk to Sancho' record omitted Navaras and the timed requirement.",
            searchTags = listOf("Talk to Sancho.", "Sancho", "Ben Erai", "SAFE")
        ),
        Quest(
            id = "G3-P5-016",
            chapter = 5,
            playOrder = 16,
            title = "The Tunnel of Lago",
            category = "SAFE",
            giver = "Sancho",
            location = "Ben Erai mines",
            prerequisites = "",
            summary = "Visit the relevant mines, speak with the overseers and bring Sancho the requested status report.",
            walkthroughSteps = listOf("Speak with Sancho about the lack of gold shipments from Lago.", "Travel to Lago and find its ruler Fabio.", "Question Fabio about the closed mine/tunnel and missing transports.", "Return to Sancho with the report; this leads to Slaves for Lago."),
            reward = "1,000 XP and +5 Ben Erai reputation.",
            warnings = "The genuine task is checking Lago's tunnel with Fabio, not collecting arbitrary mine status updates.",
            searchTags = listOf("Report from the mines.", "Sancho / mine overseers", "Ben Erai mines", "SAFE")
        ),
        Quest(
            id = "G3-P5-017",
            chapter = 5,
            playOrder = 17,
            title = "Lukar Had Better Get Out!",
            category = "SAFE",
            giver = "Sancho",
            location = "Ben Erai",
            prerequisites = "",
            summary = "Collect the ore Lukar requests and deliver the full amount.",
            walkthroughSteps = listOf("Speak to shady trader Lukar about his plans for Ben Erai.", "Report Lukar's plans to Sancho.", "Sancho orders Lukar removed; choosing this outcome requires killing him.", "Confirm the result with Sancho."),
            reward = "1,000 XP and +10 Ben Erai reputation.",
            warnings = "The earlier 'Lukar needs ore' task is not corroborated in the base-game quest guide. Killing Lukar forfeits his possible support during Ben Erai's liberation.",
            searchTags = listOf("Lukar needs ore.", "Lukar", "Ben Erai", "SAFE")
        ),
        Quest(
            id = "G3-P5-018",
            chapter = 5,
            playOrder = 18,
            title = "Ten Cactus Flowers",
            category = "SAFE / DELIVERY",
            giver = "Eusebio (Ben Erai alchemist)",
            location = "Ben Erai mine",
            prerequisites = "",
            summary = "Bring the workers the requested food supplies and report the delivery.",
            walkthroughSteps = listOf("Find alchemist Eusebio in Ben Erai and ask for a simple gathering job.", "Collect TEN cactus flowers from the shrubs in and around Ben Erai.", "Bring all ten to Eusebio and ask about further alchemy work."),
            reward = "1,000 XP, +5 Ben Erai reputation and +1 Alchemy.",
            warnings = "The old 'Mine Workers Need Food' record had no matching documented quest; this is the real herb delivery from Eusebio.",
            searchTags = listOf("The mine workers need food.", "Mine overseer", "Ben Erai mine", "SAFE / DELIVERY")
        ),
        Quest(
            id = "G3-P5-019",
            chapter = 5,
            playOrder = 19,
            title = "Talk to Vasco",
            category = "SAFE / DELIVERY",
            giver = "Sancho",
            location = "Ben Erai mine",
            prerequisites = "",
            summary = "Deliver the requested water to the miners/slaves working outside the settlement.",
            walkthroughSteps = listOf("Speak with Sancho about contacts in Ben Erai.", "He asks you to take a message or report to Vasco.", "Find Vasco in Ben Erai and speak to him.", "Return to Sancho if his follow-up dialogue becomes available."),
            reward = "250 XP.",
            warnings = "This is a messenger quest; the old 'Bring Water to the Mine' objective is not corroborated.",
            searchTags = listOf("Bring water to the mine.", "Ben Erai mine quest giver", "Ben Erai mine", "SAFE / DELIVERY")
        ),
        Quest(
            id = "G3-P5-020",
            chapter = 5,
            playOrder = 20,
            title = "The Way to Gold",
            category = "CHOICE",
            giver = "Eusebio (Ben Erai alchemist)",
            location = "Ben Erai",
            prerequisites = "",
            summary = "Speak with the exhausted slaves and the overseer to determine what is required to keep the mine functioning or help the slaves.",
            walkthroughSteps = listOf("Ask Eusebio about Sancho's valuable gold chests.", "Eusebio proposes robbing the chests.", "Instead of attempting a generic mine-worker task, report Eusebio's proposal to Sancho.", "Resolve Sancho's dialogue on the attempted theft."),
            reward = "1,500 XP.",
            warnings = "Faction-sensitive thief-or-report dialogue. No separate 'Exhausted Slaves' quest was found in the classic Ben Erai index.",
            searchTags = listOf("The exhausted slaves.", "Ben Erai overseer", "Ben Erai", "CHOICE")
        ),
        Quest(
            id = "G3-P5-021",
            chapter = 5,
            playOrder = 21,
            title = "Slaves for Lago",
            category = "CHOICE — HASHISHIN",
            giver = "Sancho",
            location = "Ben Erai",
            prerequisites = "",
            summary = "Deliver/recruit the requested slave to the mine if following the Hashishin outcome.",
            walkthroughSteps = listOf("Complete The Tunnel of Lago by investigating Fabio's gold mine.", "Ask Sancho how to restart the mining operation in Lago.", "Find the emaciated slave in Ben Erai and order him to bring his group to Lago.", "Escort the group all the way to Lago; protect the enslaved workers so they survive.", "At the mine, tell the workers to begin work and report success."),
            reward = "1,500 XP and +20 Ben Erai reputation.",
            warnings = "The captive escort is a faction-specific slavery quest. The old generic new-slave objective omitted the required earlier Tunnel of Lago task.",
            searchTags = listOf("A new slave for the mine.", "Ben Erai quest chain", "Ben Erai", "CHOICE — HASHISHIN")
        ),
        Quest(
            id = "G3-P5-022",
            chapter = 5,
            playOrder = 22,
            title = "Crawler Hunt",
            category = "SAFE",
            giver = "Vasco",
            location = "Ben Erai mine",
            prerequisites = "",
            summary = "Enter the affected tunnel and remove the creature/enemy problem preventing mining. Explore the entire branch before returning.",
            walkthroughSteps = listOf("Find Vasco in Ben Erai and ask about dangerous crawlers.", "Travel to the nearby cave where the colony lives.", "Kill TWELVE TOUGH SANDCRAWLERS; additional ordinary crawlers may also inhabit the cave.", "Return to Vasco after the colony is cleared."),
            reward = "1,000 XP and +15 Ben Erai reputation.",
            warnings = "The completion condition is 12 tough sandcrawlers, not an unspecified enemy somewhere in the mine.",
            searchTags = listOf("The tunnel is blocked.", "Mine overseer", "Ben Erai mine", "SAFE")
        ),
        Quest(
            id = "G3-P5-023",
            chapter = 5,
            playOrder = 23,
            title = "Ten Gold Nuggets (Unverified Ghost Quest)",
            category = "SAFE",
            giver = "Unverified automatic/mining trigger",
            location = "Ben Erai mine",
            prerequisites = "",
            summary = "Kill all Minecrawlers in the designated mine section and return once the tunnel is safe.",
            walkthroughSteps = listOf("The classic Gothic 3 guide describes an apparent ghost quest for ten gold nuggets, with no known character offering it.", "After gaining access to the Ben Erai mine, gather ten gold nuggets if your installed version allows it.", "Check your quest log for an actual triggered task. If no entry appears, do not assume mining ten nuggets will create a mission."),
            reward = "Historical guide suggests 2,500 XP but could not verify the quest's trigger.",
            warnings = "GHOST QUEST: this entry was previously a duplicate generic 'crawlers' hunt. The classic guide itself could not find the gold-nugget quest giver.",
            searchTags = listOf("Crawlers in the mine.", "Ben Erai miner", "Ben Erai mine", "SAFE")
        ),
        Quest(
            id = "G3-P5-024",
            chapter = 5,
            playOrder = 24,
            title = "Bounty Hunting: Hurit",
            category = "SAFE",
            giver = "Campa (Ben Erai bounty hunter)",
            location = "Oasis/river area",
            prerequisites = "",
            summary = "Kill the designated Lurkers around the local water source and report back.",
            walkthroughSteps = listOf("Accept Campa's Ben Erai bounty list.", "Find Nomad leader Hurit in the desert to the north.", "If you want Hurit's help against Sugut, resolve that separate quest before attacking him.", "On the Hashishin route, defeat Hurit and his companions and confirm the bounty."),
            reward = "1,000 XP and +15 Ben Erai reputation.",
            warnings = "Hurit can help against Sugut; the old generic 'Lurkers' quest did not match a documented Ben Erai mission.",
            searchTags = listOf("Hunt the lurkers near Ben Erai.", "Ben Erai hunter", "Oasis/river area", "SAFE")
        ),
        Quest(
            id = "G3-P5-025",
            chapter = 5,
            playOrder = 25,
            title = "Dirty Doings",
            category = "SAFE / INVESTIGATION",
            giver = "Vasco",
            location = "Ben Erai region",
            prerequisites = "",
            summary = "Investigate the missing ore shipment, follow the clues to the thieves or responsible group and recover/report the goods.",
            walkthroughSteps = listOf("Talk to Vasco in Ben Erai about Sancho's gold.", "Vasco suggests pretending your money was stolen so you can keep the gold.", "Agree with Vasco's trick and tell Sancho you were robbed, OR expose Vasco's plan to Sancho.", "Collect the appropriate choice-specific dialogue result."),
            reward = "1,000 XP for the documented Dirty Doings resolution; the connected gold deception may award more XP.",
            warnings = "You are deciding whether to cheat Sancho, not recovering an unspecified stolen ore shipment.",
            searchTags = listOf("The stolen ore.", "Sancho / Ben Erai quest chain", "Ben Erai region", "SAFE / INVESTIGATION")
        ),
        Quest(
            id = "G3-P5-026",
            chapter = 5,
            playOrder = 26,
            title = "An Unexpected Message for Sigmor in Bakaresh",
            category = "CROSS-REGION",
            giver = "Sancho",
            location = "Ben Erai → Mora Sul",
            prerequisites = "",
            summary = "Carry Sancho's report or information onward to the appropriate Hashishin authority when the quest directs you south.",
            walkthroughSteps = listOf("Finish Sancho's Ben Erai jobs and report back to him.", "He hands you a written message for Sigmor, the priest in Bakaresh.", "Travel east to Bakaresh and gain entry to the temple area where Sigmor resides.", "Deliver the letter to Sigmor."),
            reward = "500 XP and +15 Hashishin reputation.",
            warnings = "The documented destination is SIGMOR in BAKARESH, not Gonzales in Mora Sul.",
            searchTags = listOf("Report to Gonzales / Mora Sul.", "Sancho", "Ben Erai → Mora Sul", "CROSS-REGION")
        ),
        Quest(
            id = "G3-P5-027",
            chapter = 5,
            playOrder = 27,
            title = "Bounty Hunting: Ben Erai",
            category = "DEFER — HASHISHIN PATH",
            giver = "Campa",
            location = "Ben Erai region",
            prerequisites = "",
            summary = "Find and destroy the designated Nomad group threatening Ben Erai, then report back.",
            walkthroughSteps = listOf("Find bounty hunter Campa by Ben Erai's town entrance.", "Accept his contracts against three Nomad leaders: YESPAS, HURIT and SHAKYOR.", "Find Yespas west of Ben Erai by the road, Hurit north in the desert and Shakyor through the Lago Nomad line.", "For the Hashishin route, defeat the three and report each bounty."),
            reward = "1,500 XP and +20 Ben Erai reputation for the complete bounty chain.",
            warnings = "Killing Hurit, Yespas and Shakyor closes their Nomad quests and can affect the liberation of nearby towns.",
            searchTags = listOf("Eliminate the nomads around Ben Erai.", "Sancho / Hashishin", "Ben Erai region", "DEFER — HASHISHIN PATH")
        ),
        Quest(
            id = "G3-P5-028",
            chapter = 5,
            playOrder = 28,
            title = "Liberate Ben Erai",
            category = "DEFER — NOMAD PATH",
            giver = "Lukar (Nomad-aligned instigator)",
            location = "Ben Erai region",
            prerequisites = "",
            summary = "Help the local Nomads against Hashishin interests according to their quest line.",
            walkthroughSteps = listOf("Talk to trader Lukar about overthrowing the Hashishin holding Ben Erai.", "Complete all peaceful work for Sancho, Eusebio, Vasco and Campa first if you want their rewards.", "Side with the Nomads and attack the Hashishin guards in Ben Erai.", "Defeat enough defenders for the town to fall."),
            reward = "2,500 XP and +5 Nomads reputation.",
            warnings = "Lukar offers little practical help in the battle. His death in Sancho's opposing quest prevents his dialogue; liberation contributes to Hashishin faction hostility.",
            searchTags = listOf("Support the nomads near Ben Erai.", "Nomad contact", "Ben Erai region", "DEFER — NOMAD PATH")
        ),
        Quest(
            id = "G3-P5-029",
            chapter = 5,
            playOrder = 29,
            title = "Talk to Fabio.",
            category = "SAFE",
            giver = "Fabio",
            location = "Lago",
            prerequisites = "Meet Fabio in Lago; explore its neutral arena and trade quests before choosing a faction.",
            summary = "Speak with Fabio, Lago's leader, and exhaust his dialogue about the town, prisoners and local work.",
            walkthroughSteps = listOf("Begin with Fabio. This objective is centered on Lago. In Varant, use settlements, oases, roads and ruin silhouettes as navigation anchors; open desert shortcuts can easily lead into predator packs or the wrong canyon.", "Speak with Fabio, Lago's leader, and exhaust his dialogue about the town, prisoners and local work.", "After the objective is complete, return to the named quest giver or destination and exhaust the new dialogue. For kill quests, search the whole marked area if the completion message has not appeared; isolated enemies can wander away from their group.", "Do this before resolving Vatras's fate."),
            reward = "",
            warnings = "Lago holds Vatras in prison. Do not kill hostages or destroy the town before learning his cell location.",
            searchTags = listOf("Talk to Fabio.", "Fabio", "Lago", "SAFE")
        ),
        Quest(
            id = "G3-P5-030",
            chapter = 5,
            playOrder = 30,
            title = "Swampweed for Lago.",
            category = "SAFE / COLLECTION",
            giver = "Lago quest giver",
            location = "Lago",
            prerequisites = "",
            summary = "Collect the requested swampweed bundles/plants and deliver them to the quest giver.",
            walkthroughSteps = listOf("Begin with Lago quest giver. This objective is centered on Lago. In Varant, use settlements, oases, roads and ruin silhouettes as navigation anchors; open desert shortcuts can easily lead into predator packs or the wrong canyon.", "Collect the requested swampweed bundles/plants and deliver them to the quest giver.", "After the objective is complete, return to the named quest giver or destination and exhaust the new dialogue. For kill quests, search the whole marked area if the completion message has not appeared; isolated enemies can wander away from their group.", "Lago is heavily associated with swampweed; search gardens, traders and nearby areas."),
            reward = "",
            warnings = "",
            searchTags = listOf("Swampweed for Lago.", "Lago quest giver", "Lago", "SAFE / COLLECTION")
        ),
        Quest(
            id = "G3-P5-031",
            chapter = 5,
            playOrder = 31,
            title = "The swampweed harvest.",
            category = "SAFE",
            giver = "Lago worker",
            location = "Lago fields",
            prerequisites = "",
            summary = "Help collect or deliver the swampweed harvest as requested.",
            walkthroughSteps = listOf("Begin with Lago worker. This objective is centered on Lago fields. In Varant, use settlements, oases, roads and ruin silhouettes as navigation anchors; open desert shortcuts can easily lead into predator packs or the wrong canyon.", "Help collect or deliver the swampweed harvest as requested.", "After the objective is complete, return to the named quest giver or destination and exhaust the new dialogue. For kill quests, search the whole marked area if the completion message has not appeared; isolated enemies can wander away from their group.", "Complete alongside the other swampweed quest."),
            reward = "",
            warnings = "",
            searchTags = listOf("The swampweed harvest.", "Lago worker", "Lago fields", "SAFE")
        ),
        Quest(
            id = "G3-P5-032",
            chapter = 5,
            playOrder = 32,
            title = "Hunt the bloodflies near Lago.",
            category = "SAFE / HUNT",
            giver = "Lago hunter",
            location = "Oasis near Lago",
            prerequisites = "",
            summary = "Kill the bloodflies threatening the oasis/fields and return after the whole target group is dead.",
            walkthroughSteps = listOf("Begin with Lago hunter. This objective is centered on Oasis near Lago. In Varant, use settlements, oases, roads and ruin silhouettes as navigation anchors; open desert shortcuts can easily lead into predator packs or the wrong canyon.", "Kill the bloodflies threatening the oasis/fields and return after the whole target group is dead.", "After the objective is complete, return to the named quest giver or destination and exhaust the new dialogue. For kill quests, search the whole marked area if the completion message has not appeared; isolated enemies can wander away from their group.", "Ranged attacks help prevent several insects engaging at once."),
            reward = "",
            warnings = "",
            searchTags = listOf("Hunt the bloodflies near Lago.", "Lago hunter", "Oasis near Lago", "SAFE / HUNT")
        ),
        Quest(
            id = "G3-P5-033",
            chapter = 5,
            playOrder = 33,
            title = "Fight in Lago's arena.",
            category = "SAFE — ARENA",
            giver = "Lago arena",
            location = "Lago",
            prerequisites = "",
            summary = "Challenge the available fighter(s), remain inside the arena and win by knockout rather than killing.",
            walkthroughSteps = listOf("Begin with Lago arena. This objective is centered on Lago. In Varant, use settlements, oases, roads and ruin silhouettes as navigation anchors; open desert shortcuts can easily lead into predator packs or the wrong canyon.", "Challenge the available fighter(s), remain inside the arena and win by knockout rather than killing.", "After the objective is complete, return to the named quest giver or destination and exhaust the new dialogue. For kill quests, search the whole marked area if the completion message has not appeared; isolated enemies can wander away from their group.", "Finish arena content before any town liberation."),
            reward = "",
            warnings = "",
            searchTags = listOf("Fight in Lago's arena.", "Lago arena", "Lago", "SAFE — ARENA")
        ),
        Quest(
            id = "G3-P5-034",
            chapter = 5,
            playOrder = 34,
            title = "Defeat Lago's strongest fighter.",
            category = "SAFE — ARENA",
            giver = "Arena champion",
            location = "Lago",
            prerequisites = "",
            summary = "Beat the final/strongest local arena opponent and complete the post-fight dialogue.",
            walkthroughSteps = listOf("Begin with Arena champion. This objective is centered on Lago. In Varant, use settlements, oases, roads and ruin silhouettes as navigation anchors; open desert shortcuts can easily lead into predator packs or the wrong canyon.", "Beat the final/strongest local arena opponent and complete the post-fight dialogue.", "After the objective is complete, return to the named quest giver or destination and exhaust the new dialogue. For kill quests, search the whole marked area if the completion message has not appeared; isolated enemies can wander away from their group.", "A safe source of town reputation."),
            reward = "",
            warnings = "",
            searchTags = listOf("Defeat Lago's strongest fighter.", "Arena champion", "Lago", "SAFE — ARENA")
        ),
        Quest(
            id = "G3-P5-035",
            chapter = 5,
            playOrder = 35,
            title = "Find Vatras.",
            category = "MAIN-STORY SUPPORT",
            giver = "Automatic search objective — Vatras is imprisoned in Lago",
            location = "Lago",
            prerequisites = "Travel to Lago and search its prison for Vatras.",
            summary = "Discover that Vatras, the Water Mage from Khorinis, is being held prisoner in Lago. Reach his cell and speak with him before deciding how to handle the town.",
            walkthroughSteps = listOf("Enter Lago and ask residents about the captive Water Mage.", "Find Vatras imprisoned in one of the town cells and speak to him.", "Decide whether to help the Nomads free him or remain on the Hashishin side, then follow the appropriate town quest."),
            reward = "Locates Vatras and enables his liberation/escort chain.",
            warnings = "Vatras must remain alive if you want Water Mage/Nomad quests. Do not rush town liberation before speaking to him.",
            searchTags = listOf("Find Vatras.", "Main story / Water Mage chain", "Lago", "MAIN-STORY SUPPORT")
        ),
        Quest(
            id = "G3-P5-036",
            chapter = 5,
            playOrder = 36,
            title = "Free Vatras from Lago.",
            category = "MAJOR — NOMAD",
            giver = "Vatras / Nomad route",
            location = "Lago",
            prerequisites = "Find Vatras in Lago's cell and choose the Nomad liberation route.",
            summary = "To free Vatras, you must remove the Hashishin control of Lago or otherwise reach the liberation outcome that opens his imprisonment. Speak with Vatras afterward and follow his relocation/dialogue.",
            walkthroughSteps = listOf("Speak to Vatras behind bars in Lago and learn that the Hashishin hold him.", "Complete the town's neutral traders and arena tasks before turning its guards hostile.", "Join the Nomad side or otherwise bring about Lago's liberation to open the prison.", "Free Vatras, speak to him and escort him to safety as directed."),
            reward = "Vatras is freed and his Water Mage/Nomad quests become available.",
            warnings = "This is a Hashishin-versus-Nomad choice. Early liberation closes Lago's peaceful quests and can worsen faction standing.",
            searchTags = listOf("Free Vatras from Lago.", "Vatras / Nomad route", "Lago", "MAJOR — NOMAD")
        ),
        Quest(
            id = "G3-P5-037",
            chapter = 5,
            playOrder = 37,
            title = "Escort Vatras to safety.",
            category = "SAFE / ESCORT",
            giver = "Vatras",
            location = "Lago → Nomad/Water Mage destination",
            prerequisites = "Free Vatras from Lago and ask him to leave the prison.",
            summary = "After freeing Vatras, accompany him as required by his follow-up route and protect him from desert wildlife.",
            walkthroughSteps = listOf("Begin with Vatras. This objective is centered on Lago → Nomad/Water Mage destination. In Varant, use settlements, oases, roads and ruin silhouettes as navigation anchors; open desert shortcuts can easily lead into predator packs or the wrong canyon.", "After freeing Vatras, accompany him as required by his follow-up route and protect him from desert wildlife.", "After the objective is complete, return to the named quest giver or destination and exhaust the new dialogue. For kill quests, search the whole marked area if the completion message has not appeared; isolated enemies can wander away from their group.", "Clear nearby predators before starting if possible."),
            reward = "",
            warnings = "Protect Vatras during the escort; his death removes an important Water Mage and the Nomad storyline.",
            searchTags = listOf("Escort Vatras to safety.", "Vatras", "Lago → Nomad/Water Mage destination", "SAFE / ESCORT")
        ),
        Quest(
            id = "G3-P5-038",
            chapter = 5,
            playOrder = 38,
            title = "Liberate Lago!",
            category = "DEFER — NOMAD PATH",
            giver = "Nomad / player action",
            location = "Lago",
            prerequisites = "Help the Nomads and complete Lago's peaceful quests before the liberation.",
            summary = "After finishing all peaceful Lago quests, attack the Hashishin defenders and defeat enough of them for the settlement to be liberated.",
            walkthroughSteps = listOf("Begin with Nomad / player action. This objective is centered on Lago. In Varant, use settlements, oases, roads and ruin silhouettes as navigation anchors; open desert shortcuts can easily lead into predator packs or the wrong canyon.", "After finishing all peaceful Lago quests, attack the Hashishin defenders and defeat enough of them for the settlement to be liberated.", "After the objective is complete, return to the named quest giver or destination and exhaust the new dialogue. For kill quests, search the whole marked area if the completion message has not appeared; isolated enemies can wander away from their group.", "This is the practical trigger for freeing Vatras on the Nomad route."),
            reward = "",
            warnings = "Lago liberation counts toward global Hashishin hostility. Do the arena, swampweed and prisoner conversations first.",
            searchTags = listOf("Liberate Lago!", "Nomad / player action", "Lago", "DEFER — NOMAD PATH")
        ),
        Quest(
            id = "G3-P5-039",
            chapter = 5,
            playOrder = 39,
            title = "Destroy the nomads connected to Lago.",
            category = "DEFER — HASHISHIN PATH",
            giver = "Hashishin quest giver",
            location = "Lago region",
            prerequisites = "",
            summary = "If following the Hashishin route, eliminate the relevant Nomad group and report the result.",
            walkthroughSteps = listOf("Begin with Hashishin quest giver. This objective is centered on Lago region. In Varant, use settlements, oases, roads and ruin silhouettes as navigation anchors; open desert shortcuts can easily lead into predator packs or the wrong canyon.", "If following the Hashishin route, eliminate the relevant Nomad group and report the result.", "After the objective is complete, return to the named quest giver or destination and exhaust the new dialogue. For kill quests, search the whole marked area if the completion message has not appeared; isolated enemies can wander away from their group.", "Conflicts with Vatras/Nomad progression; save before committing."),
            reward = "",
            warnings = "⚠ Faction / progression warning: Create a manual save before resolving this objective. It can remove NPCs, alter Hashishin/Nomad access or close later quests.",
            searchTags = listOf("Destroy the nomads connected to Lago.", "Hashishin quest giver", "Lago region", "DEFER — HASHISHIN PATH")
        ),
        Quest(
            id = "G3-P5-040",
            chapter = 5,
            playOrder = 40,
            title = "Talk to Julio.",
            category = "SAFE",
            giver = "Julio",
            location = "Ben Sala",
            prerequisites = "",
            summary = "Speak with Julio, the town's leader, about the disaster around Ben Sala and the undead threat.",
            walkthroughSteps = listOf("Begin with Julio. This objective is centered on Ben Sala. In Varant, use settlements, oases, roads and ruin silhouettes as navigation anchors; open desert shortcuts can easily lead into predator packs or the wrong canyon.", "Speak with Julio, the town's leader, about the disaster around Ben Sala and the undead threat.", "After the objective is complete, return to the named quest giver or destination and exhaust the new dialogue. For kill quests, search the whole marked area if the completion message has not appeared; isolated enemies can wander away from their group.", "His dialogue frames the entire Ben Sala quest chain."),
            reward = "",
            warnings = "",
            searchTags = listOf("Talk to Julio.", "Julio", "Ben Sala", "SAFE")
        ),
        Quest(
            id = "G3-P5-041",
            chapter = 5,
            playOrder = 41,
            title = "The undead around Ben Sala.",
            category = "SAFE",
            giver = "Julio / Ben Sala defenders",
            location = "Ben Sala outskirts",
            prerequisites = "Reach Ben Sala and speak with Julio about the undead plague.",
            summary = "Systematically clear the undead groups surrounding the settlement so travel and trade become safer.",
            walkthroughSteps = listOf("Begin with Julio / town defenders. This objective is centered on Ben Sala outskirts. In Varant, use settlements, oases, roads and ruin silhouettes as navigation anchors; open desert shortcuts can easily lead into predator packs or the wrong canyon.", "Systematically clear the undead groups surrounding the settlement so travel and trade become safer.", "After the objective is complete, return to the named quest giver or destination and exhaust the new dialogue. For kill quests, search the whole marked area if the completion message has not appeared; isolated enemies can wander away from their group.", "Work outward from town rather than pulling several undead groups together."),
            reward = "",
            warnings = "The undead epidemic is a connected mine/temple questline; complete local survival quests before launching a faction purge.",
            searchTags = listOf("The undead around Ben Sala.", "Julio / town defenders", "Ben Sala outskirts", "SAFE")
        ),
        Quest(
            id = "G3-P5-042",
            chapter = 5,
            playOrder = 42,
            title = "Clean out the cave near Ben Sala.",
            category = "SAFE",
            giver = "Ben Sala quest giver",
            location = "Cave near Ben Sala",
            prerequisites = "",
            summary = "Enter the specified cave, destroy all undead/creatures inside and search it thoroughly before reporting back.",
            walkthroughSteps = listOf("Begin with Ben Sala quest giver. This objective is centered on Cave near Ben Sala. In Varant, use settlements, oases, roads and ruin silhouettes as navigation anchors; open desert shortcuts can easily lead into predator packs or the wrong canyon.", "Enter the specified cave, destroy all undead/creatures inside and search it thoroughly before reporting back.", "After the objective is complete, return to the named quest giver or destination and exhaust the new dialogue. For kill quests, search the whole marked area if the completion message has not appeared; isolated enemies can wander away from their group.", "Check side passages for quest items and chests."),
            reward = "",
            warnings = "",
            searchTags = listOf("Clean out the cave near Ben Sala.", "Ben Sala quest giver", "Cave near Ben Sala", "SAFE")
        ),
        Quest(
            id = "G3-P5-043",
            chapter = 5,
            playOrder = 43,
            title = "The tunnel of the undead.",
            category = "SAFE",
            giver = "Ben Sala mine/tunnel quest giver",
            location = "Ben Sala",
            prerequisites = "",
            summary = "Explore the affected tunnel and destroy the undead occupying it.",
            walkthroughSteps = listOf("Begin with Ben Sala mine/tunnel quest giver. This objective is centered on Ben Sala. In Varant, use settlements, oases, roads and ruin silhouettes as navigation anchors; open desert shortcuts can easily lead into predator packs or the wrong canyon.", "Explore the affected tunnel and destroy the undead occupying it.", "After the objective is complete, return to the named quest giver or destination and exhaust the new dialogue. For kill quests, search the whole marked area if the completion message has not appeared; isolated enemies can wander away from their group.", "Use blunt or strong melee/ranged attacks appropriate to skeletons and zombies."),
            reward = "",
            warnings = "",
            searchTags = listOf("The tunnel of the undead.", "Ben Sala mine/tunnel quest giver", "Ben Sala", "SAFE")
        ),
        Quest(
            id = "G3-P5-044",
            chapter = 5,
            playOrder = 44,
            title = "The ruined mine.",
            category = "SAFE",
            giver = "Ben Sala miner",
            location = "Ben Sala region",
            prerequisites = "",
            summary = "Investigate the mine ruined by the undead outbreak, clear hostile occupants and report what you find.",
            walkthroughSteps = listOf("Begin with Ben Sala miner. This objective is centered on Ben Sala region. In Varant, use settlements, oases, roads and ruin silhouettes as navigation anchors; open desert shortcuts can easily lead into predator packs or the wrong canyon.", "Investigate the mine ruined by the undead outbreak, clear hostile occupants and report what you find.", "After the objective is complete, return to the named quest giver or destination and exhaust the new dialogue. For kill quests, search the whole marked area if the completion message has not appeared; isolated enemies can wander away from their group.", "Combine with ore/weapon searches in the same area."),
            reward = "",
            warnings = "",
            searchTags = listOf("The ruined mine.", "Ben Sala miner", "Ben Sala region", "SAFE")
        ),
        Quest(
            id = "G3-P5-045",
            chapter = 5,
            playOrder = 45,
            title = "Weapons for Ben Sala.",
            category = "SAFE / COLLECTION",
            giver = "Ben Sala guard/merchant",
            location = "Ben Sala",
            prerequisites = "",
            summary = "Collect the requested weapon bundles or weapons and deliver them to the defenders.",
            walkthroughSteps = listOf("Begin with Ben Sala guard/merchant. This objective is centered on Ben Sala. In Varant, use settlements, oases, roads and ruin silhouettes as navigation anchors; open desert shortcuts can easily lead into predator packs or the wrong canyon.", "Collect the requested weapon bundles or weapons and deliver them to the defenders.", "After the objective is complete, return to the named quest giver or destination and exhaust the new dialogue. For kill quests, search the whole marked area if the completion message has not appeared; isolated enemies can wander away from their group.", "Keep Bundles of Weapons from Myrtana if you still have them."),
            reward = "",
            warnings = "",
            searchTags = listOf("Weapons for Ben Sala.", "Ben Sala guard/merchant", "Ben Sala", "SAFE / COLLECTION")
        ),
        Quest(
            id = "G3-P5-046",
            chapter = 5,
            playOrder = 46,
            title = "Ore for the smith.",
            category = "SAFE / COLLECTION",
            giver = "Ben Sala smith",
            location = "Ben Sala",
            prerequisites = "",
            summary = "Bring the smith the ore/raw materials he requests.",
            walkthroughSteps = listOf("Begin with Ben Sala smith. This objective is centered on Ben Sala. In Varant, use settlements, oases, roads and ruin silhouettes as navigation anchors; open desert shortcuts can easily lead into predator packs or the wrong canyon.", "Bring the smith the ore/raw materials he requests.", "After the objective is complete, return to the named quest giver or destination and exhaust the new dialogue. For kill quests, search the whole marked area if the completion message has not appeared; isolated enemies can wander away from their group.", "Do before selling mine loot."),
            reward = "",
            warnings = "",
            searchTags = listOf("Ore for the smith.", "Ben Sala smith", "Ben Sala", "SAFE / COLLECTION")
        ),
        Quest(
            id = "G3-P5-047",
            chapter = 5,
            playOrder = 47,
            title = "Healing potions for the defenders.",
            category = "SAFE / DELIVERY",
            giver = "Ben Sala quest giver",
            location = "Ben Sala",
            prerequisites = "",
            summary = "Deliver the requested healing potions to support the town against the undead.",
            walkthroughSteps = listOf("Begin with Ben Sala quest giver. This objective is centered on Ben Sala. In Varant, use settlements, oases, roads and ruin silhouettes as navigation anchors; open desert shortcuts can easily lead into predator packs or the wrong canyon.", "Deliver the requested healing potions to support the town against the undead.", "After the objective is complete, return to the named quest giver or destination and exhaust the new dialogue. For kill quests, search the whole marked area if the completion message has not appeared; isolated enemies can wander away from their group.", "Arrive stocked; the local battles can consume many potions."),
            reward = "",
            warnings = "",
            searchTags = listOf("Healing potions for the defenders.", "Ben Sala quest giver", "Ben Sala", "SAFE / DELIVERY")
        ),
        Quest(
            id = "G3-P5-048",
            chapter = 5,
            playOrder = 48,
            title = "The cursed temple near Ben Sala.",
            category = "SAFE / DUNGEON",
            giver = "Ben Sala / temple quest chain",
            location = "Ben Sala ruins",
            prerequisites = "Learn from Ben Sala's defenders about the undead curse at the nearby temple.",
            summary = "Travel to the nearby ancient temple/ruins, fight through the undead and investigate the source of the outbreak.",
            walkthroughSteps = listOf("Begin with Ben Sala / temple quest chain. This objective is centered on Ben Sala ruins. In Varant, use settlements, oases, roads and ruin silhouettes as navigation anchors; open desert shortcuts can easily lead into predator packs or the wrong canyon.", "Travel to the nearby ancient temple/ruins, fight through the undead and investigate the source of the outbreak.", "After the objective is complete, return to the named quest giver or destination and exhaust the new dialogue. For kill quests, search the whole marked area if the completion message has not appeared; isolated enemies can wander away from their group.", "This area is more dangerous than the ordinary town quests; prepare before entering."),
            reward = "",
            warnings = "The undead leader and temple quest should be completed for the town's survival; do not mistake this for a normal Nomad liberation.",
            searchTags = listOf("The cursed temple near Ben Sala.", "Ben Sala / temple quest chain", "Ben Sala ruins", "SAFE / DUNGEON")
        ),
        Quest(
            id = "G3-P5-049",
            chapter = 5,
            playOrder = 49,
            title = "Find the source of the undead.",
            category = "SAFE / INVESTIGATION",
            giver = "Julio / temple chain",
            location = "Ben Sala region",
            prerequisites = "",
            summary = "Follow the clues from the mines, caves and ruins to identify the cause or central threat behind the undead plague.",
            walkthroughSteps = listOf("Begin with Julio / temple chain. This objective is centered on Ben Sala region. In Varant, use settlements, oases, roads and ruin silhouettes as navigation anchors; open desert shortcuts can easily lead into predator packs or the wrong canyon.", "Follow the clues from the mines, caves and ruins to identify the cause or central threat behind the undead plague.", "After the objective is complete, return to the named quest giver or destination and exhaust the new dialogue. For kill quests, search the whole marked area if the completion message has not appeared; isolated enemies can wander away from their group.", "Do the smaller undead-clearing quests first; they naturally lead toward the source."),
            reward = "",
            warnings = "",
            searchTags = listOf("Find the source of the undead.", "Julio / temple chain", "Ben Sala region", "SAFE / INVESTIGATION")
        ),
        Quest(
            id = "G3-P5-050",
            chapter = 5,
            playOrder = 50,
            title = "Kill the undead leaders.",
            category = "SAFE",
            giver = "Ben Sala quest chain",
            location = "Ben Sala ruins",
            prerequisites = "",
            summary = "Destroy the named/elite undead controlling groups around the settlement and temple.",
            walkthroughSteps = listOf("Begin with Ben Sala quest chain. This objective is centered on Ben Sala ruins. In Varant, use settlements, oases, roads and ruin silhouettes as navigation anchors; open desert shortcuts can easily lead into predator packs or the wrong canyon.", "Destroy the named/elite undead controlling groups around the settlement and temple.", "After the objective is complete, return to the named quest giver or destination and exhaust the new dialogue. For kill quests, search the whole marked area if the completion message has not appeared; isolated enemies can wander away from their group.", "Loot every named enemy for keys and quest items."),
            reward = "",
            warnings = "",
            searchTags = listOf("Kill the undead leaders.", "Ben Sala quest chain", "Ben Sala ruins", "SAFE")
        ),
        Quest(
            id = "G3-P5-051",
            chapter = 5,
            playOrder = 51,
            title = "Basir's old chest / treasure.",
            category = "SAFE",
            giver = "Basir-related quest chain",
            location = "Ben Sala ruins",
            prerequisites = "",
            summary = "Locate the treasure/chest connected to Basir's past in the ruined area and recover the requested item or information.",
            walkthroughSteps = listOf("Begin with Basir-related quest chain. This objective is centered on Ben Sala ruins. In Varant, use settlements, oases, roads and ruin silhouettes as navigation anchors; open desert shortcuts can easily lead into predator packs or the wrong canyon.", "Locate the treasure/chest connected to Basir's past in the ruined area and recover the requested item or information.", "After the objective is complete, return to the named quest giver or destination and exhaust the new dialogue. For kill quests, search the whole marked area if the completion message has not appeared; isolated enemies can wander away from their group.", "This connects back to characters encountered earlier in Myrtana."),
            reward = "",
            warnings = "",
            searchTags = listOf("Basir's old chest / treasure.", "Basir-related quest chain", "Ben Sala ruins", "SAFE")
        ),
        Quest(
            id = "G3-P5-052",
            chapter = 5,
            playOrder = 52,
            title = "Escort the merchant through the dangerous area.",
            category = "SAFE / ESCORT",
            giver = "Ben Sala merchant",
            location = "Ben Sala road",
            prerequisites = "",
            summary = "Protect the merchant while traveling through the undead-infested route and keep him alive until the destination is reached.",
            walkthroughSteps = listOf("Begin with Ben Sala merchant. This objective is centered on Ben Sala road. In Varant, use settlements, oases, roads and ruin silhouettes as navigation anchors; open desert shortcuts can easily lead into predator packs or the wrong canyon.", "Protect the merchant while traveling through the undead-infested route and keep him alive until the destination is reached.", "After the objective is complete, return to the named quest giver or destination and exhaust the new dialogue. For kill quests, search the whole marked area if the completion message has not appeared; isolated enemies can wander away from their group.", "Clear the road first if you want the safest escort."),
            reward = "",
            warnings = "",
            searchTags = listOf("Escort the merchant through the dangerous area.", "Ben Sala merchant", "Ben Sala road", "SAFE / ESCORT")
        ),
        Quest(
            id = "G3-P5-053",
            chapter = 5,
            playOrder = 53,
            title = "Clear the road to Bakaresh.",
            category = "SAFE",
            giver = "Ben Sala quest giver",
            location = "Ben Sala → Bakaresh road",
            prerequisites = "",
            summary = "Kill undead and other hostile creatures blocking the eastern/southern road so caravans can move again.",
            walkthroughSteps = listOf("Begin with Ben Sala quest giver. This objective is centered on Ben Sala → Bakaresh road. In Varant, use settlements, oases, roads and ruin silhouettes as navigation anchors; open desert shortcuts can easily lead into predator packs or the wrong canyon.", "Kill undead and other hostile creatures blocking the eastern/southern road so caravans can move again.", "After the objective is complete, return to the named quest giver or destination and exhaust the new dialogue. For kill quests, search the whole marked area if the completion message has not appeared; isolated enemies can wander away from their group.", "This prepares the transition into Part VI."),
            reward = "",
            warnings = "",
            searchTags = listOf("Clear the road to Bakaresh.", "Ben Sala quest giver", "Ben Sala → Bakaresh road", "SAFE")
        ),
        Quest(
            id = "G3-P5-054",
            chapter = 5,
            playOrder = 54,
            title = "Report the end of the undead threat.",
            category = "SAFE",
            giver = "Julio",
            location = "Ben Sala",
            prerequisites = "",
            summary = "After completing the major undead-clearing objectives, return to Julio and report that the settlement is secure.",
            walkthroughSteps = listOf("Begin with Julio. This objective is centered on Ben Sala. In Varant, use settlements, oases, roads and ruin silhouettes as navigation anchors; open desert shortcuts can easily lead into predator packs or the wrong canyon.", "After completing the major undead-clearing objectives, return to Julio and report that the settlement is secure.", "After the objective is complete, return to the named quest giver or destination and exhaust the new dialogue. For kill quests, search the whole marked area if the completion message has not appeared; isolated enemies can wander away from their group.", "Do not forget the final report; several Gothic 3 quest chains pay only after the closing dialogue."),
            reward = "",
            warnings = "",
            searchTags = listOf("Report the end of the undead threat.", "Julio", "Ben Sala", "SAFE")
        ),
        Quest(
            id = "G3-P5-055",
            chapter = 5,
            playOrder = 55,
            title = "Liberate Ben Sala.",
            category = "DEFER — NOMAD PATH",
            giver = "Nomad / player action",
            location = "Ben Sala",
            prerequisites = "Nomad liberation route after completing Ben Sala's peaceful undead and supply quests.",
            summary = "If choosing to remove Hashishin control, finish every neutral undead, trade and smith quest first, then defeat the town's Hashishin defenders.",
            walkthroughSteps = listOf("Begin with Nomad / player action. This objective is centered on Ben Sala. In Varant, use settlements, oases, roads and ruin silhouettes as navigation anchors; open desert shortcuts can easily lead into predator packs or the wrong canyon.", "If choosing to remove Hashishin control, finish every neutral undead, trade and smith quest first, then defeat the town's Hashishin defenders.", "After the objective is complete, return to the named quest giver or destination and exhaust the new dialogue. For kill quests, search the whole marked area if the completion message has not appeared; isolated enemies can wander away from their group.", "The undead quests are largely useful regardless of faction, so there is no reason to liberate early."),
            reward = "",
            warnings = "Attacking Ben Sala's Hashishin closes all resident/trader quests and contributes to faction hostility.",
            searchTags = listOf("Liberate Ben Sala.", "Nomad / player action", "Ben Sala", "DEFER — NOMAD PATH")
        ),
        Quest(
            id = "G3-P5-056",
            chapter = 5,
            playOrder = 56,
            title = "Destroy the nomads near Ben Sala.",
            category = "DEFER — HASHISHIN PATH",
            giver = "Hashishin leadership",
            location = "Ben Sala region",
            prerequisites = "",
            summary = "On the Hashishin route, locate and destroy the designated Nomad group before reporting back.",
            walkthroughSteps = listOf("Begin with Hashishin leadership. This objective is centered on Ben Sala region. In Varant, use settlements, oases, roads and ruin silhouettes as navigation anchors; open desert shortcuts can easily lead into predator packs or the wrong canyon.", "On the Hashishin route, locate and destroy the designated Nomad group before reporting back.", "After the objective is complete, return to the named quest giver or destination and exhaust the new dialogue. For kill quests, search the whole marked area if the completion message has not appeared; isolated enemies can wander away from their group.", "Finish their available quests first if pursuing completionist coverage."),
            reward = "",
            warnings = "⚠ Faction / progression warning: Create a manual save before resolving this objective. It can remove NPCs, alter Hashishin/Nomad access or close later quests.",
            searchTags = listOf("Destroy the nomads near Ben Sala.", "Hashishin leadership", "Ben Sala region", "DEFER — HASHISHIN PATH")
        ),
    )
}
