package com.sliverzfx.gothicquest

internal object Gothic3Part3Data {
    val quests = listOf(
        Quest(
            id = "G3-P3-001",
            chapter = 3,
            playOrder = 1,
            title = "Bring the shaman Grimboll sulfur.",
            category = "SAFE",
            giver = "Grimboll",
            location = "Geldern",
            prerequisites = "",
            summary = "Speak with Grimboll in Geldern and accept his request for sulfur. Collect the required sulfur pieces from mines, merchants or loot and bring the complete amount back to him.",
            walkthroughSteps = listOf("Speak with Grimboll and make sure all quest-related dialogue is exhausted. The objective is associated with Geldern. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "Speak with Grimboll in Geldern and accept his request for sulfur. Collect the required sulfur pieces from mines, merchants or loot and bring the complete amount back to him.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "Keep sulfur you find while exploring the nearby mines instead of selling it."),
            reward = "",
            warnings = "",
            searchTags = listOf("Bring the shaman Grimboll sulfur.", "Grimboll", "Geldern", "SAFE")
        ),
        Quest(
            id = "G3-P3-002",
            chapter = 3,
            playOrder = 2,
            title = "Bring the shaman Nemrok the artifact from the ruin in the north.",
            category = "SAFE",
            giver = "Nemrok",
            location = "Geldern → northern ruins",
            prerequisites = "",
            summary = "Nemrok sends you to the ruins north of Geldern to recover an ancient artifact. Travel north, clear any creatures around the ruin, search the site thoroughly and take the quest artifact back to Nemrok.",
            walkthroughSteps = listOf("Speak with Nemrok and make sure all quest-related dialogue is exhausted. The objective is associated with Geldern → northern ruins. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "Nemrok sends you to the ruins north of Geldern to recover an ancient artifact. Travel north, clear any creatures around the ruin, search the site thoroughly and take the quest artifact back to Nemrok.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "This is one of Geldern's archaeology/artifact quests; loot the ruin fully while you are there."),
            reward = "",
            warnings = "",
            searchTags = listOf("Bring the shaman Nemrok the artifact from the ruin in the north.", "Nemrok", "Geldern → northern ruins", "SAFE")
        ),
        Quest(
            id = "G3-P3-003",
            chapter = 3,
            playOrder = 3,
            title = "Bring Nemrok the scepter from the ruins.",
            category = "SAFE",
            giver = "Nemrok",
            location = "Geldern region",
            prerequisites = "",
            summary = "Follow Nemrok's directions to the specified ruins, locate the requested scepter among the ancient remains and return it to him.",
            walkthroughSteps = listOf("Speak with Nemrok and make sure all quest-related dialogue is exhausted. The objective is associated with Geldern region. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "Follow Nemrok's directions to the specified ruins, locate the requested scepter among the ancient remains and return it to him.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "Do this alongside the other ruin searches to minimize travel."),
            reward = "",
            warnings = "",
            searchTags = listOf("Bring Nemrok the scepter from the ruins.", "Nemrok", "Geldern region", "SAFE")
        ),
        Quest(
            id = "G3-P3-004",
            chapter = 3,
            playOrder = 4,
            title = "Bring Renwik the rare plant King's Sorrel.",
            category = "SAFE",
            giver = "Renwik",
            location = "Geldern",
            prerequisites = "",
            summary = "Renwik, Geldern's absent-minded alchemist, asks for a King's Sorrel. Give him one from your inventory or search the countryside for the distinctive rare plant.",
            walkthroughSteps = listOf("Speak with Renwik and make sure all quest-related dialogue is exhausted. The objective is associated with Geldern. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "Renwik, Geldern's absent-minded alchemist, asks for a King's Sorrel. Give him one from your inventory or search the countryside for the distinctive rare plant.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "King's Sorrel permanently increases attributes through potions later, so decide whether the quest reward is worth giving one away."),
            reward = "",
            warnings = "",
            searchTags = listOf("Bring Renwik the rare plant King's Sorrel.", "Renwik", "Geldern", "SAFE")
        ),
        Quest(
            id = "G3-P3-005",
            chapter = 3,
            playOrder = 5,
            title = "Find all the fire chalices for Grok.",
            category = "MAIN QUEST / CHOICE",
            giver = "Grok",
            location = "Geldern",
            prerequisites = "",
            summary = "Grok is interested in the Fire Chalices and can become involved in the global chalice quest. Speak with him only after understanding which faction outcome you want; the chalices are central to restoring the paladins' magic.",
            walkthroughSteps = listOf("Speak with Grok and make sure all quest-related dialogue is exhausted. The objective is associated with Geldern. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "Grok is interested in the Fire Chalices and can become involved in the global chalice quest. Speak with him only after understanding which faction outcome you want; the chalices are central to restoring the paladins' magic.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "Do not casually hand over globally important quest items without saving first."),
            reward = "",
            warnings = "⚠ Choice warning: Make a manual save before committing. This objective can affect faction access, named NPCs or later quests.",
            searchTags = listOf("Find all the fire chalices for Grok.", "Grok", "Geldern", "MAIN QUEST / CHOICE")
        ),
        Quest(
            id = "G3-P3-006",
            chapter = 3,
            playOrder = 6,
            title = "Find the first paladin's helmet.",
            category = "SAFE",
            giver = "Geldern quest chain",
            location = "Geldern / ruins",
            prerequisites = "",
            summary = "Search the indicated ruins/old battlefield area for the missing paladin helmet and recover it for the relevant Geldern quest giver.",
            walkthroughSteps = listOf("Speak with Geldern quest chain and make sure all quest-related dialogue is exhausted. The objective is associated with Geldern / ruins. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "Search the indicated ruins/old battlefield area for the missing paladin helmet and recover it for the relevant Geldern quest giver.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "Ancient equipment can be visually small; inspect bodies, chests and ground loot carefully."),
            reward = "",
            warnings = "",
            searchTags = listOf("Find the first paladin's helmet.", "Geldern quest chain", "Geldern / ruins", "SAFE")
        ),
        Quest(
            id = "G3-P3-007",
            chapter = 3,
            playOrder = 7,
            title = "Find the druid Runak.",
            category = "CHOICE",
            giver = "Geldern / Orc quest chain",
            location = "Forest northwest of Geldern",
            prerequisites = "",
            summary = "Travel into the forest northwest of Geldern and locate Runak's Ranger camp. Speak with Runak before taking any hostile action so you can access his dialogue and associated quests.",
            walkthroughSteps = listOf("Speak with Geldern / Orc quest chain and make sure all quest-related dialogue is exhausted. The objective is associated with Forest northwest of Geldern. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "Travel into the forest northwest of Geldern and locate Runak's Ranger camp. Speak with Runak before taking any hostile action so you can access his dialogue and associated quests.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "Runak is a Druid and is connected to the Orc-vs-Druid conflict. Do not kill him merely because an Orc asks you to."),
            reward = "",
            warnings = "⚠ Choice warning: Make a manual save before committing. This objective can affect faction access, named NPCs or later quests.",
            searchTags = listOf("Find the druid Runak.", "Geldern / Orc quest chain", "Forest northwest of Geldern", "CHOICE")
        ),
        Quest(
            id = "G3-P3-008",
            chapter = 3,
            playOrder = 8,
            title = "Kill the druid Runak.",
            category = "DEFER — ORC PATH",
            giver = "Orc leadership in Geldern",
            location = "Runak's camp",
            prerequisites = "",
            summary = "If committing to the Orc route, return to Runak's camp and kill the druid, then report the result to the Orc quest giver in Geldern.",
            walkthroughSteps = listOf("Speak with Orc leadership in Geldern and make sure all quest-related dialogue is exhausted. The objective is associated with Runak's camp. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "If committing to the Orc route, return to Runak's camp and kill the druid, then report the result to the Orc quest giver in Geldern.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "Finish Runak's quests and any Druid Stone objectives first."),
            reward = "",
            warnings = "⚠ Choice warning: Make a manual save before committing. This objective can affect faction access, named NPCs or later quests.",
            searchTags = listOf("Kill the druid Runak.", "Orc leadership in Geldern", "Runak's camp", "DEFER — ORC PATH")
        ),
        Quest(
            id = "G3-P3-009",
            chapter = 3,
            playOrder = 9,
            title = "Kill the wandering shadowbeasts.",
            category = "SAFE",
            giver = "Geldern hunter",
            location = "Geldern wilderness",
            prerequisites = "",
            summary = "Track the designated Shadowbeasts roaming outside Geldern, kill the complete target group and return to the hunter.",
            walkthroughSteps = listOf("Speak with Geldern hunter and make sure all quest-related dialogue is exhausted. The objective is associated with Geldern wilderness. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "Track the designated Shadowbeasts roaming outside Geldern, kill the complete target group and return to the hunter.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "Shadowbeasts are dangerous at low level; fight one at a time where possible."),
            reward = "",
            warnings = "",
            searchTags = listOf("Kill the wandering shadowbeasts.", "Geldern hunter", "Geldern wilderness", "SAFE")
        ),
        Quest(
            id = "G3-P3-010",
            chapter = 3,
            playOrder = 10,
            title = "Minecrawler plates for the shaman.",
            category = "SAFE",
            giver = "Geldern shaman",
            location = "Geldern mines",
            prerequisites = "",
            summary = "Hunt Minecrawlers in the mines around Geldern and collect the requested plates. Return when you have the full quantity.",
            walkthroughSteps = listOf("Speak with Geldern shaman and make sure all quest-related dialogue is exhausted. The objective is associated with Geldern mines. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "Hunt Minecrawlers in the mines around Geldern and collect the requested plates. Return when you have the full quantity.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "If you lack the appropriate trophy skill, check whether the quest version provides lootable plates or learn the skill before hunting."),
            reward = "",
            warnings = "",
            searchTags = listOf("Minecrawler plates for the shaman.", "Geldern shaman", "Geldern mines", "SAFE")
        ),
        Quest(
            id = "G3-P3-011",
            chapter = 3,
            playOrder = 11,
            title = "The secret of Mazin's mine.",
            category = "SAFE",
            giver = "Mazin",
            location = "Mine near Geldern",
            prerequisites = "",
            summary = "Speak with Mazin and investigate the mine he is concerned about. Explore it completely, deal with the creatures inside and inspect the deeper chambers for the reason the mine is unusual.",
            walkthroughSteps = listOf("Speak with Mazin and make sure all quest-related dialogue is exhausted. The objective is associated with Mine near Geldern. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "Speak with Mazin and investigate the mine he is concerned about. Explore it completely, deal with the creatures inside and inspect the deeper chambers for the reason the mine is unusual.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "Combine this with Geldern's ore and Minecrawler objectives."),
            reward = "",
            warnings = "",
            searchTags = listOf("The secret of Mazin's mine.", "Mazin", "Mine near Geldern", "SAFE")
        ),
        Quest(
            id = "G3-P3-012",
            chapter = 3,
            playOrder = 12,
            title = "Gold plates for Lares.",
            category = "SAFE / THIEVERY",
            giver = "Lares",
            location = "Geldern",
            prerequisites = "",
            summary = "Lares wants valuable golden plates from Geldern. Acquire the required plates without causing the entire city to become hostile and bring them to him.",
            walkthroughSteps = listOf("Speak with Lares and make sure all quest-related dialogue is exhausted. The objective is associated with Geldern. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "Lares wants valuable golden plates from Geldern. Acquire the required plates without causing the entire city to become hostile and bring them to him.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "Use nighttime and save before theft. Lares's quests are much easier before a city liberation."),
            reward = "",
            warnings = "",
            searchTags = listOf("Gold plates for Lares.", "Lares", "Geldern", "SAFE / THIEVERY")
        ),
        Quest(
            id = "G3-P3-013",
            chapter = 3,
            playOrder = 13,
            title = "Steal the shamans' artifact.",
            category = "SAFE / THIEVERY",
            giver = "Lares / Rebel-thief chain",
            location = "Geldern",
            prerequisites = "",
            summary = "Infiltrate the shamans' area and steal the requested artifact. Avoid witnesses and return it to the quest giver.",
            walkthroughSteps = listOf("Speak with Lares / Rebel-thief chain and make sure all quest-related dialogue is exhausted. The objective is associated with Geldern. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "Infiltrate the shamans' area and steal the requested artifact. Avoid witnesses and return it to the quest giver.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "Do not begin a general fight; this is intended as theft, not liberation."),
            reward = "",
            warnings = "",
            searchTags = listOf("Steal the shamans' artifact.", "Lares / Rebel-thief chain", "Geldern", "SAFE / THIEVERY")
        ),
        Quest(
            id = "G3-P3-014",
            chapter = 3,
            playOrder = 14,
            title = "Bring Jared Lares' message.",
            category = "SAFE",
            giver = "Jared / Lares",
            location = "Geldern",
            prerequisites = "",
            summary = "Carry the message between Jared and Lares and exhaust the follow-up dialogue on both ends.",
            walkthroughSteps = listOf("Speak with Jared / Lares and make sure all quest-related dialogue is exhausted. The objective is associated with Geldern. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "Carry the message between Jared and Lares and exhaust the follow-up dialogue on both ends.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "A simple courier quest that helps connect Geldern's underground characters."),
            reward = "",
            warnings = "",
            searchTags = listOf("Bring Jared Lares' message.", "Jared / Lares", "Geldern", "SAFE")
        ),
        Quest(
            id = "G3-P3-015",
            chapter = 3,
            playOrder = 15,
            title = "Seven ancient rings for the alchemist.",
            category = "SAFE",
            giver = "Geldern alchemist",
            location = "Geldern / ruins",
            prerequisites = "",
            summary = "Collect the seven ancient rings requested by the alchemist. Search ruins, chests and quest locations around Geldern, then deliver the complete set.",
            walkthroughSteps = listOf("Speak with Geldern alchemist and make sure all quest-related dialogue is exhausted. The objective is associated with Geldern / ruins. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "Collect the seven ancient rings requested by the alchemist. Search ruins, chests and quest locations around Geldern, then deliver the complete set.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "Do not sell uniquely named ancient jewelry until Geldern's collector quests are finished."),
            reward = "",
            warnings = "",
            searchTags = listOf("Seven ancient rings for the alchemist.", "Geldern alchemist", "Geldern / ruins", "SAFE")
        ),
        Quest(
            id = "G3-P3-016",
            chapter = 3,
            playOrder = 16,
            title = "A delivery from the southern mine.",
            category = "SAFE",
            giver = "Geldern mine quest chain",
            location = "Southern mine → Geldern",
            prerequisites = "",
            summary = "Visit the southern mine, obtain the shipment requested for Geldern and deliver it to the named recipient in town.",
            walkthroughSteps = listOf("Speak with Geldern mine quest chain and make sure all quest-related dialogue is exhausted. The objective is associated with Southern mine → Geldern. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "Visit the southern mine, obtain the shipment requested for Geldern and deliver it to the named recipient in town.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "Use the trip to clear nearby wildlife and mine ore."),
            reward = "",
            warnings = "",
            searchTags = listOf("A delivery from the southern mine.", "Geldern mine quest chain", "Southern mine → Geldern", "SAFE")
        ),
        Quest(
            id = "G3-P3-017",
            chapter = 3,
            playOrder = 17,
            title = "The northern mine needs help.",
            category = "SAFE",
            giver = "Geldern mine quest chain",
            location = "Northern mine",
            prerequisites = "",
            summary = "Travel to the northern mine and resolve the problem preventing normal work—speak to the workers, clear hostile creatures as required and report back.",
            walkthroughSteps = listOf("Speak with Geldern mine quest chain and make sure all quest-related dialogue is exhausted. The objective is associated with Northern mine. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "Travel to the northern mine and resolve the problem preventing normal work—speak to the workers, clear hostile creatures as required and report back.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "Search the mine thoroughly for quest ore and artifacts."),
            reward = "",
            warnings = "",
            searchTags = listOf("The northern mine needs help.", "Geldern mine quest chain", "Northern mine", "SAFE")
        ),
        Quest(
            id = "G3-P3-018",
            chapter = 3,
            playOrder = 18,
            title = "Hamil the audacious artifact trader among the slaves.",
            category = "SAFE / INVESTIGATION",
            giver = "Hamil",
            location = "Geldern",
            prerequisites = "",
            summary = "Find Hamil among Geldern's slaves and speak with him about his artifact dealings. Follow the dialogue carefully before deciding whether to expose or assist him.",
            walkthroughSteps = listOf("Speak with Hamil and make sure all quest-related dialogue is exhausted. The objective is associated with Geldern. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "Find Hamil among Geldern's slaves and speak with him about his artifact dealings. Follow the dialogue carefully before deciding whether to expose or assist him.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "His information overlaps Geldern's artifact economy; do not kill or expose him prematurely."),
            reward = "",
            warnings = "",
            searchTags = listOf("Hamil the audacious artifact trader among the slaves.", "Hamil", "Geldern", "SAFE / INVESTIGATION")
        ),
        Quest(
            id = "G3-P3-019",
            chapter = 3,
            playOrder = 19,
            title = "Mobilize the people of Geldern for Torn's druid stone.",
            category = "CHOICE — REBEL/DRUID",
            giver = "Torn / Rebel-Druid route",
            location = "Geldern region",
            prerequisites = "",
            summary = "Complete the preparation required by Torn and the local resistance for the Druid-related objective around Geldern.",
            walkthroughSteps = listOf("Speak with Torn / Rebel-Druid route and make sure all quest-related dialogue is exhausted. The objective is associated with Geldern region. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "Complete the preparation required by Torn and the local resistance for the Druid-related objective around Geldern.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "Preserve the Rangers and Druids if following this branch."),
            reward = "",
            warnings = "⚠ Choice warning: Make a manual save before committing. This objective can affect faction access, named NPCs or later quests.",
            searchTags = listOf("Mobilize the people of Geldern for Torn's druid stone.", "Torn / Rebel-Druid route", "Geldern region", "CHOICE — REBEL/DRUID")
        ),
        Quest(
            id = "G3-P3-020",
            chapter = 3,
            playOrder = 20,
            title = "Liberate Geldern from the orcs!",
            category = "DEFER — REBEL PATH",
            giver = "Rebel/Druid route",
            location = "Geldern",
            prerequisites = "",
            summary = "Only after completing Geldern's normal quests, attack the Orc leadership and defenders until the surviving occupation flees. Protect useful allies and loot important named enemies.",
            walkthroughSteps = listOf("Speak with Rebel/Druid route and make sure all quest-related dialogue is exhausted. The objective is associated with Geldern. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "Only after completing Geldern's normal quests, attack the Orc leadership and defenders until the surviving occupation flees. Protect useful allies and loot important named enemies.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "A major city liberation; save beforehand and expect consequences with the Orc faction."),
            reward = "",
            warnings = "⚠ Choice warning: Make a manual save before committing. This objective can affect faction access, named NPCs or later quests.",
            searchTags = listOf("Liberate Geldern from the orcs!", "Rebel/Druid route", "Geldern", "DEFER — REBEL PATH")
        ),
        Quest(
            id = "G3-P3-021",
            chapter = 3,
            playOrder = 21,
            title = "Destroy the rebel resistance around Geldern.",
            category = "DEFER — ORC PATH",
            giver = "Orc leadership",
            location = "Geldern region",
            prerequisites = "",
            summary = "On the Orc route, eliminate the Ranger/Rebel positions around Geldern and report the destruction.",
            walkthroughSteps = listOf("Speak with Orc leadership and make sure all quest-related dialogue is exhausted. The objective is associated with Geldern region. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "On the Orc route, eliminate the Ranger/Rebel positions around Geldern and report the destruction.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "Mutually destructive with the Rebel/Druid quest line. Finish neutral quests first."),
            reward = "",
            warnings = "⚠ Choice warning: Make a manual save before committing. This objective can affect faction access, named NPCs or later quests.",
            searchTags = listOf("Destroy the rebel resistance around Geldern.", "Orc leadership", "Geldern region", "DEFER — ORC PATH")
        ),
        Quest(
            id = "G3-P3-022",
            chapter = 3,
            playOrder = 22,
            title = "Take the delivery from Nordmar to Anog.",
            category = "SAFE — REBEL",
            giver = "Anog",
            location = "Road/Nordmar border → Silden",
            prerequisites = "",
            summary = "Recover the delivery intended for Anog and bring it safely to the Rebel leader outside Silden.",
            walkthroughSteps = listOf("Speak with Anog and make sure all quest-related dialogue is exhausted. The objective is associated with Road/Nordmar border → Silden. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "Recover the delivery intended for Anog and bring it safely to the Rebel leader outside Silden.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "This helps establish the Rebel network around Silden."),
            reward = "",
            warnings = "",
            searchTags = listOf("Take the delivery from Nordmar to Anog.", "Anog", "Road/Nordmar border → Silden", "SAFE — REBEL")
        ),
        Quest(
            id = "G3-P3-023",
            chapter = 3,
            playOrder = 23,
            title = "Talk to Anog about the rebel situation.",
            category = "SAFE",
            giver = "Anog",
            location = "Rebel camp near Silden",
            prerequisites = "",
            summary = "Speak with Anog and exhaust his dialogue about Silden, the surrounding patrols and his brother Inog inside town.",
            walkthroughSteps = listOf("Speak with Anog and make sure all quest-related dialogue is exhausted. The objective is associated with Rebel camp near Silden. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "Speak with Anog and exhaust his dialogue about Silden, the surrounding patrols and his brother Inog inside town.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "Do this before entering deeper into the Silden faction chain."),
            reward = "",
            warnings = "",
            searchTags = listOf("Talk to Anog about the rebel situation.", "Anog", "Rebel camp near Silden", "SAFE")
        ),
        Quest(
            id = "G3-P3-024",
            chapter = 3,
            playOrder = 24,
            title = "Inog needs help.",
            category = "SAFE — REBEL",
            giver = "Inog",
            location = "Silden",
            prerequisites = "",
            summary = "Find Inog inside Silden and speak with him privately. Complete his requested support tasks without exposing him to the Orcs.",
            walkthroughSteps = listOf("Speak with Inog and make sure all quest-related dialogue is exhausted. The objective is associated with Silden. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "Find Inog inside Silden and speak with him privately. Complete his requested support tasks without exposing him to the Orcs.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "Inog is an undercover Rebel contact; preserve his identity."),
            reward = "",
            warnings = "",
            searchTags = listOf("Inog needs help.", "Inog", "Silden", "SAFE — REBEL")
        ),
        Quest(
            id = "G3-P3-025",
            chapter = 3,
            playOrder = 25,
            title = "Bring Inog five bundles of weapons.",
            category = "SAFE — REBEL",
            giver = "Inog",
            location = "Silden",
            prerequisites = "",
            summary = "Collect five Bundles of Weapons and secretly deliver them to Inog.",
            walkthroughSteps = listOf("Speak with Inog and make sure all quest-related dialogue is exhausted. The objective is associated with Silden. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "Collect five Bundles of Weapons and secretly deliver them to Inog.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "Continue hoarding weapon bundles; they are used by multiple Rebel quests."),
            reward = "",
            warnings = "",
            searchTags = listOf("Bring Inog five bundles of weapons.", "Inog", "Silden", "SAFE — REBEL")
        ),
        Quest(
            id = "G3-P3-026",
            chapter = 3,
            playOrder = 26,
            title = "Kill the orc patrol near Silden.",
            category = "SAFE — REBEL",
            giver = "Anog / Rebel chain",
            location = "Silden outskirts",
            prerequisites = "",
            summary = "Locate the designated Orc patrol outside Silden, eliminate it away from the town and report to the Rebels.",
            walkthroughSteps = listOf("Speak with Anog / Rebel chain and make sure all quest-related dialogue is exhausted. The objective is associated with Silden outskirts. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "Locate the designated Orc patrol outside Silden, eliminate it away from the town and report to the Rebels.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "Avoid dragging the fight into Silden."),
            reward = "",
            warnings = "",
            searchTags = listOf("Kill the orc patrol near Silden.", "Anog / Rebel chain", "Silden outskirts", "SAFE — REBEL")
        ),
        Quest(
            id = "G3-P3-027",
            chapter = 3,
            playOrder = 27,
            title = "Kill the strange lurkers at the river.",
            category = "SAFE",
            giver = "Silden hunter/fisher",
            location = "River near Silden",
            prerequisites = "",
            summary = "Follow the river and kill the designated Lurkers threatening the local workers or fishermen. Return after the full target group is dead.",
            walkthroughSteps = listOf("Speak with Silden hunter/fisher and make sure all quest-related dialogue is exhausted. The objective is associated with River near Silden. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "Follow the river and kill the designated Lurkers threatening the local workers or fishermen. Return after the full target group is dead.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "Search both banks if the quest does not complete."),
            reward = "",
            warnings = "",
            searchTags = listOf("Kill the strange lurkers at the river.", "Silden hunter/fisher", "River near Silden", "SAFE")
        ),
        Quest(
            id = "G3-P3-028",
            chapter = 3,
            playOrder = 28,
            title = "The fishermen's catch.",
            category = "SAFE",
            giver = "Silden fishing camp",
            location = "Silden",
            prerequisites = "",
            summary = "Help the fishermen with the requested catch/delivery objective and bring the required fish or goods to the quest giver.",
            walkthroughSteps = listOf("Speak with Silden fishing camp and make sure all quest-related dialogue is exhausted. The objective is associated with Silden. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "Help the fishermen with the requested catch/delivery objective and bring the required fish or goods to the quest giver.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "Complete while doing the river Lurker quest."),
            reward = "",
            warnings = "",
            searchTags = listOf("The fishermen's catch.", "Silden fishing camp", "Silden", "SAFE")
        ),
        Quest(
            id = "G3-P3-029",
            chapter = 3,
            playOrder = 29,
            title = "Bring the woodcutters back to work.",
            category = "SAFE",
            giver = "Silden lumber camp",
            location = "Silden outskirts",
            prerequisites = "",
            summary = "Visit the woodcutters, resolve the reason they have stopped working and report that production can resume.",
            walkthroughSteps = listOf("Speak with Silden lumber camp and make sure all quest-related dialogue is exhausted. The objective is associated with Silden outskirts. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "Visit the woodcutters, resolve the reason they have stopped working and report that production can resume.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "Speak with every named worker before leaving the camp."),
            reward = "",
            warnings = "",
            searchTags = listOf("Bring the woodcutters back to work.", "Silden lumber camp", "Silden outskirts", "SAFE")
        ),
        Quest(
            id = "G3-P3-030",
            chapter = 3,
            playOrder = 30,
            title = "Hunt the wolves around Silden.",
            category = "SAFE",
            giver = "Silden hunter",
            location = "Silden wilderness",
            prerequisites = "",
            summary = "Kill the specified wolf packs around Silden and report back.",
            walkthroughSteps = listOf("Speak with Silden hunter and make sure all quest-related dialogue is exhausted. The objective is associated with Silden wilderness. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "Kill the specified wolf packs around Silden and report back.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "Good early reputation quest and useful source of pelts."),
            reward = "",
            warnings = "",
            searchTags = listOf("Hunt the wolves around Silden.", "Silden hunter", "Silden wilderness", "SAFE")
        ),
        Quest(
            id = "G3-P3-031",
            chapter = 3,
            playOrder = 31,
            title = "Pelts for the hunter in Silden.",
            category = "SAFE",
            giver = "Silden hunter",
            location = "Silden",
            prerequisites = "",
            summary = "Collect the requested animal pelts and deliver them to the hunter.",
            walkthroughSteps = listOf("Speak with Silden hunter and make sure all quest-related dialogue is exhausted. The objective is associated with Silden. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "Collect the requested animal pelts and deliver them to the hunter.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "Learn Skin Animals early if you intend to complete hunting quests efficiently."),
            reward = "",
            warnings = "",
            searchTags = listOf("Pelts for the hunter in Silden.", "Silden hunter", "Silden", "SAFE")
        ),
        Quest(
            id = "G3-P3-032",
            chapter = 3,
            playOrder = 32,
            title = "Take the slaves to the lumber camp.",
            category = "CHOICE",
            giver = "Silden overseer",
            location = "Silden → lumber camp",
            prerequisites = "",
            summary = "Escort the assigned slaves from Silden to the lumber camp and keep the group alive.",
            walkthroughSteps = listOf("Speak with Silden overseer and make sure all quest-related dialogue is exhausted. The objective is associated with Silden → lumber camp. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "Escort the assigned slaves from Silden to the lumber camp and keep the group alive.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "Slave quests can conflict with Rebel rescue objectives; check active alternatives first."),
            reward = "",
            warnings = "⚠ Choice warning: Make a manual save before committing. This objective can affect faction access, named NPCs or later quests.",
            searchTags = listOf("Take the slaves to the lumber camp.", "Silden overseer", "Silden → lumber camp", "CHOICE")
        ),
        Quest(
            id = "G3-P3-033",
            chapter = 3,
            playOrder = 33,
            title = "Free the slaves from Silden.",
            category = "CHOICE — REBEL",
            giver = "Rebel route",
            location = "Silden",
            prerequisites = "",
            summary = "Help the relevant slaves escape Orc control and reach safety according to the Rebel plan.",
            walkthroughSteps = listOf("Speak with Rebel route and make sure all quest-related dialogue is exhausted. The objective is associated with Silden. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "Help the relevant slaves escape Orc control and reach safety according to the Rebel plan.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "Do not attempt this while simultaneously trying to complete an Orc slave-delivery outcome."),
            reward = "",
            warnings = "⚠ Choice warning: Make a manual save before committing. This objective can affect faction access, named NPCs or later quests.",
            searchTags = listOf("Free the slaves from Silden.", "Rebel route", "Silden", "CHOICE — REBEL")
        ),
        Quest(
            id = "G3-P3-034",
            chapter = 3,
            playOrder = 34,
            title = "Win the arena fights in Silden.",
            category = "SAFE",
            giver = "Silden arena fighters",
            location = "Silden arena",
            prerequisites = "",
            summary = "Challenge the available arena opponents one by one. Stay inside the arena boundaries, knock each opponent unconscious rather than killing them, and speak to them or the arena organizer after each victory.",
            walkthroughSteps = listOf("Speak with Silden arena fighters and make sure all quest-related dialogue is exhausted. The objective is associated with Silden arena. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "Challenge the available arena opponents one by one. Stay inside the arena boundaries, knock each opponent unconscious rather than killing them, and speak to them or the arena organizer after each victory.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "Finish all arena fights before liberating Silden."),
            reward = "",
            warnings = "",
            searchTags = listOf("Win the arena fights in Silden.", "Silden arena fighters", "Silden arena", "SAFE")
        ),
        Quest(
            id = "G3-P3-035",
            chapter = 3,
            playOrder = 35,
            title = "Defeat the strongest fighter in Silden.",
            category = "SAFE",
            giver = "Arena champion",
            location = "Silden arena",
            prerequisites = "",
            summary = "After beating the preliminary opponents, challenge the champion and win under normal arena rules.",
            walkthroughSteps = listOf("Speak with Arena champion and make sure all quest-related dialogue is exhausted. The objective is associated with Silden arena. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "After beating the preliminary opponents, challenge the champion and win under normal arena rules.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "Arena victories are a safe way to build town reputation."),
            reward = "",
            warnings = "",
            searchTags = listOf("Defeat the strongest fighter in Silden.", "Arena champion", "Silden arena", "SAFE")
        ),
        Quest(
            id = "G3-P3-036",
            chapter = 3,
            playOrder = 36,
            title = "Bring the Orcs their requested firewood.",
            category = "SAFE",
            giver = "Silden quartermaster",
            location = "Silden / lumber camp",
            prerequisites = "",
            summary = "Collect the required wood/firewood shipment and deliver it to the Orc recipient.",
            walkthroughSteps = listOf("Speak with Silden quartermaster and make sure all quest-related dialogue is exhausted. The objective is associated with Silden / lumber camp. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "Collect the required wood/firewood shipment and deliver it to the Orc recipient.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "Combine with lumber-camp quests."),
            reward = "",
            warnings = "",
            searchTags = listOf("Bring the Orcs their requested firewood.", "Silden quartermaster", "Silden / lumber camp", "SAFE")
        ),
        Quest(
            id = "G3-P3-037",
            chapter = 3,
            playOrder = 37,
            title = "Bring the Orcs their fish.",
            category = "SAFE",
            giver = "Silden quartermaster",
            location = "Silden fishing camp",
            prerequisites = "",
            summary = "Collect the required fish shipment and deliver it to the Orcs.",
            walkthroughSteps = listOf("Speak with Silden quartermaster and make sure all quest-related dialogue is exhausted. The objective is associated with Silden fishing camp. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "Collect the required fish shipment and deliver it to the Orcs.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "Can usually be paired with fishermen's quests."),
            reward = "",
            warnings = "",
            searchTags = listOf("Bring the Orcs their fish.", "Silden quartermaster", "Silden fishing camp", "SAFE")
        ),
        Quest(
            id = "G3-P3-038",
            chapter = 3,
            playOrder = 38,
            title = "Find the missing hunter.",
            category = "SAFE",
            giver = "Silden quest chain",
            location = "Wilderness near Silden",
            prerequisites = "",
            summary = "Search the wilderness for the missing hunter, deal with nearby predators and speak with him if alive.",
            walkthroughSteps = listOf("Speak with Silden quest chain and make sure all quest-related dialogue is exhausted. The objective is associated with Wilderness near Silden. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "Search the wilderness for the missing hunter, deal with nearby predators and speak with him if alive.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "Follow roads, riverbanks and campfire clues rather than searching the entire forest randomly."),
            reward = "",
            warnings = "",
            searchTags = listOf("Find the missing hunter.", "Silden quest chain", "Wilderness near Silden", "SAFE")
        ),
        Quest(
            id = "G3-P3-039",
            chapter = 3,
            playOrder = 39,
            title = "The escaped slaves.",
            category = "CHOICE",
            giver = "Silden quest chain",
            location = "Silden outskirts",
            prerequisites = "",
            summary = "Locate the escaped slaves and decide whether to help them or return/report them according to your chosen faction path.",
            walkthroughSteps = listOf("Speak with Silden quest chain and make sure all quest-related dialogue is exhausted. The objective is associated with Silden outskirts. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "Locate the escaped slaves and decide whether to help them or return/report them according to your chosen faction path.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "Save before resolving their fate."),
            reward = "",
            warnings = "⚠ Choice warning: Make a manual save before committing. This objective can affect faction access, named NPCs or later quests.",
            searchTags = listOf("The escaped slaves.", "Silden quest chain", "Silden outskirts", "CHOICE")
        ),
        Quest(
            id = "G3-P3-040",
            chapter = 3,
            playOrder = 40,
            title = "A package for Nordmar.",
            category = "SAFE / CROSS-REGION",
            giver = "Silden/Nordmar quest chain",
            location = "Silden → Nordmar",
            prerequisites = "",
            summary = "Obtain the package destined for Nordmar and keep it until you travel through Faring into the northern region.",
            walkthroughSteps = listOf("Speak with Silden/Nordmar quest chain and make sure all quest-related dialogue is exhausted. The objective is associated with Silden → Nordmar. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "Obtain the package destined for Nordmar and keep it until you travel through Faring into the northern region.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "Do not discard or sell uniquely named packages."),
            reward = "",
            warnings = "",
            searchTags = listOf("A package for Nordmar.", "Silden/Nordmar quest chain", "Silden → Nordmar", "SAFE / CROSS-REGION")
        ),
        Quest(
            id = "G3-P3-041",
            chapter = 3,
            playOrder = 41,
            title = "Liberate Silden from the orcs!",
            category = "DEFER — REBEL PATH",
            giver = "Inog / Anog / Rebel route",
            location = "Silden",
            prerequisites = "",
            summary = "Finish Silden's arena, hunting, slave, fishing, lumber and undercover quests first. Then coordinate with the Rebel side and defeat enough Orc defenders for the town to fall.",
            walkthroughSteps = listOf("Speak with Inog / Anog / Rebel route and make sure all quest-related dialogue is exhausted. The objective is associated with Silden. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "Finish Silden's arena, hunting, slave, fishing, lumber and undercover quests first. Then coordinate with the Rebel side and defeat enough Orc defenders for the town to fall.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "Major liberation. Make a permanent save before starting."),
            reward = "",
            warnings = "⚠ Choice warning: Make a manual save before committing. This objective can affect faction access, named NPCs or later quests.",
            searchTags = listOf("Liberate Silden from the orcs!", "Inog / Anog / Rebel route", "Silden", "DEFER — REBEL PATH")
        ),
        Quest(
            id = "G3-P3-042",
            chapter = 3,
            playOrder = 42,
            title = "Destroy the rebels around Silden.",
            category = "DEFER — ORC PATH",
            giver = "Orc leadership",
            location = "Silden region",
            prerequisites = "",
            summary = "On an Orc-aligned playthrough, eliminate Anog's Rebel force and other designated resistance positions around Silden.",
            walkthroughSteps = listOf("Speak with Orc leadership and make sure all quest-related dialogue is exhausted. The objective is associated with Silden region. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "On an Orc-aligned playthrough, eliminate Anog's Rebel force and other designated resistance positions around Silden.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "This removes major Rebel quest givers and conflicts with liberation."),
            reward = "",
            warnings = "⚠ Choice warning: Make a manual save before committing. This objective can affect faction access, named NPCs or later quests.",
            searchTags = listOf("Destroy the rebels around Silden.", "Orc leadership", "Silden region", "DEFER — ORC PATH")
        ),
        Quest(
            id = "G3-P3-043",
            chapter = 3,
            playOrder = 43,
            title = "Find the king.",
            category = "MAIN QUEST",
            giver = "Main story",
            location = "Vengard",
            prerequisites = "",
            summary = "Use the Vengard teleport route/stone when the story sends you to the capital. Fight or evade Orcs inside the magical barrier and reach the castle. Speak with King Rhobar.",
            walkthroughSteps = listOf("Speak with Main story and make sure all quest-related dialogue is exhausted. The objective is associated with Vengard. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "Use the Vengard teleport route/stone when the story sends you to the capital. Fight or evade Orcs inside the magical barrier and reach the castle. Speak with King Rhobar.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "Vengard is a war zone; carry healing supplies and save frequently."),
            reward = "",
            warnings = "",
            searchTags = listOf("Find the king.", "Main story", "Vengard", "MAIN QUEST")
        ),
        Quest(
            id = "G3-P3-044",
            chapter = 3,
            playOrder = 44,
            title = "Talk to King Rhobar.",
            category = "MAIN QUEST",
            giver = "King Rhobar",
            location = "Vengard castle",
            prerequisites = "",
            summary = "Once inside the castle, speak with Rhobar and exhaust the main-story dialogue about the war, Xardas, the divine artifacts and your next objectives.",
            walkthroughSteps = listOf("Speak with King Rhobar and make sure all quest-related dialogue is exhausted. The objective is associated with Vengard castle. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "Once inside the castle, speak with Rhobar and exhaust the main-story dialogue about the war, Xardas, the divine artifacts and your next objectives.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "Do not rush away; several castle NPCs open quests after you meet the king."),
            reward = "",
            warnings = "",
            searchTags = listOf("Talk to King Rhobar.", "King Rhobar", "Vengard castle", "MAIN QUEST")
        ),
        Quest(
            id = "G3-P3-045",
            chapter = 3,
            playOrder = 45,
            title = "Bring the Fire Mage Karrypto information.",
            category = "SAFE / MAIN-STORY SUPPORT",
            giver = "Karrypto",
            location = "Vengard castle",
            prerequisites = "",
            summary = "Speak with Karrypto in the castle and complete his information/request chain regarding the siege and magical situation.",
            walkthroughSteps = listOf("Speak with Karrypto and make sure all quest-related dialogue is exhausted. The objective is associated with Vengard castle. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "Speak with Karrypto in the castle and complete his information/request chain regarding the siege and magical situation.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "Karrypto is an important mage/trainer and is worth speaking to repeatedly as the story advances."),
            reward = "",
            warnings = "",
            searchTags = listOf("Bring the Fire Mage Karrypto information.", "Karrypto", "Vengard castle", "SAFE / MAIN-STORY SUPPORT")
        ),
        Quest(
            id = "G3-P3-046",
            chapter = 3,
            playOrder = 46,
            title = "Help the paladins defend Vengard.",
            category = "SAFE — REBEL",
            giver = "Vengard paladins",
            location = "Vengard",
            prerequisites = "",
            summary = "Join the defenders against Orc groups occupying sections of the city. Clear the specified positions rather than wandering into every enemy at once.",
            walkthroughSteps = listOf("Speak with Vengard paladins and make sure all quest-related dialogue is exhausted. The objective is associated with Vengard. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "Join the defenders against Orc groups occupying sections of the city. Clear the specified positions rather than wandering into every enemy at once.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "Use paladins as allies; pull smaller groups toward friendly fighters."),
            reward = "",
            warnings = "",
            searchTags = listOf("Help the paladins defend Vengard.", "Vengard paladins", "Vengard", "SAFE — REBEL")
        ),
        Quest(
            id = "G3-P3-047",
            chapter = 3,
            playOrder = 47,
            title = "Destroy the orcs inside the barrier.",
            category = "SAFE — REBEL / LARGE BATTLE",
            giver = "Vengard defenders",
            location = "Vengard city",
            prerequisites = "",
            summary = "Systematically clear the Orc forces trapped within Vengard's magical barrier. Work district by district and use surviving paladins to reduce the risk of being surrounded.",
            walkthroughSteps = listOf("Speak with Vengard defenders and make sure all quest-related dialogue is exhausted. The objective is associated with Vengard city. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "Systematically clear the Orc forces trapped within Vengard's magical barrier. Work district by district and use surviving paladins to reduce the risk of being surrounded.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "This is effectively a prolonged battle rather than a single encounter."),
            reward = "",
            warnings = "",
            searchTags = listOf("Destroy the orcs inside the barrier.", "Vengard defenders", "Vengard city", "SAFE — REBEL / LARGE BATTLE")
        ),
        Quest(
            id = "G3-P3-048",
            chapter = 3,
            playOrder = 48,
            title = "Find the missing paladin patrol.",
            category = "SAFE",
            giver = "Vengard quest chain",
            location = "Vengard ruins",
            prerequisites = "",
            summary = "Search the ruined streets and buildings for the missing paladins and resolve their situation.",
            walkthroughSteps = listOf("Speak with Vengard quest chain and make sure all quest-related dialogue is exhausted. The objective is associated with Vengard ruins. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "Search the ruined streets and buildings for the missing paladins and resolve their situation.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "Explore rooftops and side streets carefully; Vengard's ruined geometry can hide routes."),
            reward = "",
            warnings = "",
            searchTags = listOf("Find the missing paladin patrol.", "Vengard quest chain", "Vengard ruins", "SAFE")
        ),
        Quest(
            id = "G3-P3-049",
            chapter = 3,
            playOrder = 49,
            title = "Supplies for Vengard.",
            category = "SAFE",
            giver = "Vengard quartermaster",
            location = "Vengard castle",
            prerequisites = "",
            summary = "Collect and deliver the requested supplies to the castle defenders.",
            walkthroughSteps = listOf("Speak with Vengard quartermaster and make sure all quest-related dialogue is exhausted. The objective is associated with Vengard castle. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "Collect and deliver the requested supplies to the castle defenders.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "Complete supply quests before selling bulk food, potions or weapon bundles."),
            reward = "",
            warnings = "",
            searchTags = listOf("Supplies for Vengard.", "Vengard quartermaster", "Vengard castle", "SAFE")
        ),
        Quest(
            id = "G3-P3-050",
            chapter = 3,
            playOrder = 50,
            title = "Healing for the defenders.",
            category = "SAFE",
            giver = "Vengard healer",
            location = "Vengard castle",
            prerequisites = "",
            summary = "Bring the requested healing items or plants to the healer supporting Vengard's troops.",
            walkthroughSteps = listOf("Speak with Vengard healer and make sure all quest-related dialogue is exhausted. The objective is associated with Vengard castle. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "Bring the requested healing items or plants to the healer supporting Vengard's troops.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "A simple support quest that is easiest if you arrive stocked."),
            reward = "",
            warnings = "",
            searchTags = listOf("Healing for the defenders.", "Vengard healer", "Vengard castle", "SAFE")
        ),
        Quest(
            id = "G3-P3-051",
            chapter = 3,
            playOrder = 51,
            title = "Find the teleport stone to Vengard.",
            category = "MAIN QUEST",
            giver = "Main-story exploration",
            location = "Myrtana",
            prerequisites = "",
            summary = "Obtain the teleport stone that allows entry past Vengard's magical barrier. Once used, be prepared to fight because the city outside the castle is occupied by Orcs.",
            walkthroughSteps = listOf("Speak with Main-story exploration and make sure all quest-related dialogue is exhausted. The objective is associated with Myrtana. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "Obtain the teleport stone that allows entry past Vengard's magical barrier. Once used, be prepared to fight because the city outside the castle is occupied by Orcs.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "Keep a separate save before teleporting if you are under-equipped."),
            reward = "",
            warnings = "",
            searchTags = listOf("Find the teleport stone to Vengard.", "Main-story exploration", "Myrtana", "MAIN QUEST")
        ),
        Quest(
            id = "G3-P3-052",
            chapter = 3,
            playOrder = 52,
            title = "The sacred fire and the Fire Chalices.",
            category = "MAIN QUEST / GLOBAL",
            giver = "Milten / Fire Mages",
            location = "Vengard monastery-related global chain",
            prerequisites = "",
            summary = "The Fire Chalice storyline ultimately requires all chalices to be blessed in the sacred fire before they can restore individual paladins' magic. Track every chalice and do not lose or hand them away carelessly.",
            walkthroughSteps = listOf("Speak with Milten / Fire Mages and make sure all quest-related dialogue is exhausted. The objective is associated with Vengard monastery-related global chain. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "The Fire Chalice storyline ultimately requires all chalices to be blessed in the sacred fire before they can restore individual paladins' magic. Track every chalice and do not lose or hand them away carelessly.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "This global objective connects Konrad, Karlen and other paladins from earlier Parts."),
            reward = "",
            warnings = "",
            searchTags = listOf("The sacred fire and the Fire Chalices.", "Milten / Fire Mages", "Vengard monastery-related global chain", "MAIN QUEST / GLOBAL")
        ),
        Quest(
            id = "G3-P3-053",
            chapter = 3,
            playOrder = 53,
            title = "Report the situation to the king.",
            category = "SAFE",
            giver = "Vengard quest chain",
            location = "Vengard castle",
            prerequisites = "",
            summary = "After completing the requested military or story objective, return to Rhobar and report the outcome.",
            walkthroughSteps = listOf("Speak with Vengard quest chain and make sure all quest-related dialogue is exhausted. The objective is associated with Vengard castle. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "After completing the requested military or story objective, return to Rhobar and report the outcome.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "Always revisit Rhobar after major artifact or war milestones for new dialogue."),
            reward = "",
            warnings = "",
            searchTags = listOf("Report the situation to the king.", "Vengard quest chain", "Vengard castle", "SAFE")
        ),
        Quest(
            id = "G3-P3-054",
            chapter = 3,
            playOrder = 54,
            title = "Clear the approaches to the castle.",
            category = "SAFE",
            giver = "Vengard defenders",
            location = "Vengard",
            prerequisites = "",
            summary = "Eliminate the Orc groups blocking safe movement between the ruined city and the castle approaches.",
            walkthroughSteps = listOf("Speak with Vengard defenders and make sure all quest-related dialogue is exhausted. The objective is associated with Vengard. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "Eliminate the Orc groups blocking safe movement between the ruined city and the castle approaches.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "Fight in controlled groups; Vengard contains many tightly packed enemies."),
            reward = "",
            warnings = "",
            searchTags = listOf("Clear the approaches to the castle.", "Vengard defenders", "Vengard", "SAFE")
        ),
        Quest(
            id = "G3-P3-055",
            chapter = 3,
            playOrder = 55,
            title = "Gain access to Faring.",
            category = "SAFE",
            giver = "Faring guards",
            location = "Faring",
            prerequisites = "",
            summary = "Arrive at Faring and complete enough local mercenary/Orc tasks to earn permission to move beyond the lower settlement.",
            walkthroughSteps = listOf("Speak with Faring guards and make sure all quest-related dialogue is exhausted. The objective is associated with Faring. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "Arrive at Faring and complete enough local mercenary/Orc tasks to earn permission to move beyond the lower settlement.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "Faring uses layered access: lower village, castle and eventually the Nordmar pass."),
            reward = "",
            warnings = "",
            searchTags = listOf("Gain access to Faring.", "Faring guards", "Faring", "SAFE")
        ),
        Quest(
            id = "G3-P3-056",
            chapter = 3,
            playOrder = 56,
            title = "Earn the right to enter Faring castle.",
            category = "SAFE",
            giver = "Faring Orcs / mercenaries",
            location = "Faring",
            prerequisites = "",
            summary = "Build reputation by completing hunting, arena and mercenary quests until the guards allow you into the castle area.",
            walkthroughSteps = listOf("Speak with Faring Orcs / mercenaries and make sure all quest-related dialogue is exhausted. The objective is associated with Faring. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "Build reputation by completing hunting, arena and mercenary quests until the guards allow you into the castle area.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "Do every harmless reputation quest before choosing faction-hostile objectives."),
            reward = "",
            warnings = "",
            searchTags = listOf("Earn the right to enter Faring castle.", "Faring Orcs / mercenaries", "Faring", "SAFE")
        ),
        Quest(
            id = "G3-P3-057",
            chapter = 3,
            playOrder = 57,
            title = "Win the arena fights in Faring.",
            category = "SAFE",
            giver = "Faring arena fighters",
            location = "Faring arena",
            prerequisites = "",
            summary = "Challenge each available fighter and win without leaving the arena or killing your opponent. Complete the dialogue after each fight.",
            walkthroughSteps = listOf("Speak with Faring arena fighters and make sure all quest-related dialogue is exhausted. The objective is associated with Faring arena. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "Challenge each available fighter and win without leaving the arena or killing your opponent. Complete the dialogue after each fight.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "Arena wins are among the safest sources of Faring reputation."),
            reward = "",
            warnings = "",
            searchTags = listOf("Win the arena fights in Faring.", "Faring arena fighters", "Faring arena", "SAFE")
        ),
        Quest(
            id = "G3-P3-058",
            chapter = 3,
            playOrder = 58,
            title = "Defeat the arena champion.",
            category = "SAFE",
            giver = "Faring champion",
            location = "Faring arena",
            prerequisites = "",
            summary = "After the preliminary victories, challenge and defeat Faring's strongest arena opponent.",
            walkthroughSteps = listOf("Speak with Faring champion and make sure all quest-related dialogue is exhausted. The objective is associated with Faring arena. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "After the preliminary victories, challenge and defeat Faring's strongest arena opponent.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "Complete before any action that makes Faring hostile."),
            reward = "",
            warnings = "",
            searchTags = listOf("Defeat the arena champion.", "Faring champion", "Faring arena", "SAFE")
        ),
        Quest(
            id = "G3-P3-059",
            chapter = 3,
            playOrder = 59,
            title = "Hunt with Wilson.",
            category = "SAFE",
            giver = "Wilson",
            location = "Faring wilderness",
            prerequisites = "",
            summary = "Meet hunter Wilson and accompany him on his hunting objective. Stay close enough that his AI continues along the route and help kill the target animals.",
            walkthroughSteps = listOf("Speak with Wilson and make sure all quest-related dialogue is exhausted. The objective is associated with Faring wilderness. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "Meet hunter Wilson and accompany him on his hunting objective. Stay close enough that his AI continues along the route and help kill the target animals.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "Hunting quests are useful for both reputation and learning the route toward Nordmar."),
            reward = "",
            warnings = "",
            searchTags = listOf("Hunt with Wilson.", "Wilson", "Faring wilderness", "SAFE")
        ),
        Quest(
            id = "G3-P3-060",
            chapter = 3,
            playOrder = 60,
            title = "Bring Wilson the required pelts.",
            category = "SAFE",
            giver = "Wilson",
            location = "Faring",
            prerequisites = "",
            summary = "Collect the pelts Wilson requests and return them to him.",
            walkthroughSteps = listOf("Speak with Wilson and make sure all quest-related dialogue is exhausted. The objective is associated with Faring. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "Collect the pelts Wilson requests and return them to him.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "Skin Animals is highly useful here."),
            reward = "",
            warnings = "",
            searchTags = listOf("Bring Wilson the required pelts.", "Wilson", "Faring", "SAFE")
        ),
        Quest(
            id = "G3-P3-061",
            chapter = 3,
            playOrder = 61,
            title = "Hunt the dangerous trolls near Faring.",
            category = "SAFE",
            giver = "Faring hunter",
            location = "Faring/Nordmar approach",
            prerequisites = "",
            summary = "Locate the trolls in the mountains near Faring and kill the designated group. Use terrain and ranged attacks if melee is too dangerous.",
            walkthroughSteps = listOf("Speak with Faring hunter and make sure all quest-related dialogue is exhausted. The objective is associated with Faring/Nordmar approach. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "Locate the trolls in the mountains near Faring and kill the designated group. Use terrain and ranged attacks if melee is too dangerous.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "Trolls have high health; avoid pulling several simultaneously."),
            reward = "",
            warnings = "",
            searchTags = listOf("Hunt the dangerous trolls near Faring.", "Faring hunter", "Faring/Nordmar approach", "SAFE")
        ),
        Quest(
            id = "G3-P3-062",
            chapter = 3,
            playOrder = 62,
            title = "Kill the goblins in the caves near Faring.",
            category = "SAFE",
            giver = "Faring quest giver",
            location = "Caves near Faring",
            prerequisites = "",
            summary = "Explore the nearby caves and kill the goblins occupying them. Search every branch before reporting back.",
            walkthroughSteps = listOf("Speak with Faring quest giver and make sure all quest-related dialogue is exhausted. The objective is associated with Caves near Faring. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "Explore the nearby caves and kill the goblins occupying them. Search every branch before reporting back.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "Caves around Faring often contain useful ore and weapons."),
            reward = "",
            warnings = "",
            searchTags = listOf("Kill the goblins in the caves near Faring.", "Faring quest giver", "Caves near Faring", "SAFE")
        ),
        Quest(
            id = "G3-P3-063",
            chapter = 3,
            playOrder = 63,
            title = "Bring booze to the mercenaries.",
            category = "SAFE",
            giver = "Faring mercenary",
            location = "Faring",
            prerequisites = "",
            summary = "Acquire the requested booze and deliver it to the mercenary quest giver.",
            walkthroughSteps = listOf("Speak with Faring mercenary and make sure all quest-related dialogue is exhausted. The objective is associated with Faring. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "Acquire the requested booze and deliver it to the mercenary quest giver.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "Easy reputation; do it before spending or selling alcohol."),
            reward = "",
            warnings = "",
            searchTags = listOf("Bring booze to the mercenaries.", "Faring mercenary", "Faring", "SAFE")
        ),
        Quest(
            id = "G3-P3-064",
            chapter = 3,
            playOrder = 64,
            title = "The hunters of Faring.",
            category = "SAFE",
            giver = "Faring hunting camp",
            location = "Faring",
            prerequisites = "",
            summary = "Meet the hunters and complete their introductory dialogue/tasks to establish yourself with the hunting group.",
            walkthroughSteps = listOf("Speak with Faring hunting camp and make sure all quest-related dialogue is exhausted. The objective is associated with Faring. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "Meet the hunters and complete their introductory dialogue/tasks to establish yourself with the hunting group.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "This chain helps prepare the route into Nordmar."),
            reward = "",
            warnings = "",
            searchTags = listOf("The hunters of Faring.", "Faring hunting camp", "Faring", "SAFE")
        ),
        Quest(
            id = "G3-P3-065",
            chapter = 3,
            playOrder = 65,
            title = "Take the pass to Nordmar.",
            category = "SAFE / CROSS-REGION",
            giver = "Faring guards",
            location = "Faring → Nordmar",
            prerequisites = "",
            summary = "After earning sufficient standing/access, pass through the guarded northern route beyond Faring and enter Nordmar.",
            walkthroughSteps = listOf("Speak with Faring guards and make sure all quest-related dialogue is exhausted. The objective is associated with Faring → Nordmar. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "After earning sufficient standing/access, pass through the guarded northern route beyond Faring and enter Nordmar.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "This is the natural transition into the next major guide Part."),
            reward = "",
            warnings = "",
            searchTags = listOf("Take the pass to Nordmar.", "Faring guards", "Faring → Nordmar", "SAFE / CROSS-REGION")
        ),
        Quest(
            id = "G3-P3-066",
            chapter = 3,
            playOrder = 66,
            title = "A message for the Orcs in Nordmar.",
            category = "SAFE / CROSS-REGION",
            giver = "Faring Orc quest chain",
            location = "Faring → Nordmar",
            prerequisites = "",
            summary = "Carry the designated message or package through the pass and keep it until you reach the correct Orc contact in Nordmar.",
            walkthroughSteps = listOf("Speak with Faring Orc quest chain and make sure all quest-related dialogue is exhausted. The objective is associated with Faring → Nordmar. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "Carry the designated message or package through the pass and keep it until you reach the correct Orc contact in Nordmar.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "Leave this active when Part III ends; it belongs to the transition north."),
            reward = "",
            warnings = "",
            searchTags = listOf("A message for the Orcs in Nordmar.", "Faring Orc quest chain", "Faring → Nordmar", "SAFE / CROSS-REGION")
        ),
        Quest(
            id = "G3-P3-067",
            chapter = 3,
            playOrder = 67,
            title = "The ancestor tomb information.",
            category = "SAFE / CROSS-REGION",
            giver = "Faring/Nordmar quest chain",
            location = "Faring",
            prerequisites = "",
            summary = "Speak with the relevant Orcs/hunters about Nordmar's ancestor tombs and retain the information for the northern quest line.",
            walkthroughSteps = listOf("Speak with Faring/Nordmar quest chain and make sure all quest-related dialogue is exhausted. The objective is associated with Faring. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "Speak with the relevant Orcs/hunters about Nordmar's ancestor tombs and retain the information for the northern quest line.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "Do not attempt to solve the tomb network from Faring; it belongs in the Nordmar Part."),
            reward = "",
            warnings = "",
            searchTags = listOf("The ancestor tomb information.", "Faring/Nordmar quest chain", "Faring", "SAFE / CROSS-REGION")
        ),
        Quest(
            id = "G3-P3-068",
            chapter = 3,
            playOrder = 68,
            title = "Gain the Orc leaders' trust.",
            category = "CHOICE — ORC",
            giver = "Faring leadership",
            location = "Faring",
            prerequisites = "",
            summary = "Complete the reputation and service objectives needed to speak with higher-ranking Orcs in Faring.",
            walkthroughSteps = listOf("Speak with Faring leadership and make sure all quest-related dialogue is exhausted. The objective is associated with Faring. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "Complete the reputation and service objectives needed to speak with higher-ranking Orcs in Faring.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "You can gain access without immediately destroying Rebel settlements; postpone destructive proof-of-loyalty quests."),
            reward = "",
            warnings = "⚠ Choice warning: Make a manual save before committing. This objective can affect faction access, named NPCs or later quests.",
            searchTags = listOf("Gain the Orc leaders' trust.", "Faring leadership", "Faring", "CHOICE — ORC")
        ),
        Quest(
            id = "G3-P3-069",
            chapter = 3,
            playOrder = 69,
            title = "Destroy the rebels connected to Faring.",
            category = "DEFER — ORC PATH",
            giver = "Orc leadership",
            location = "Faring region",
            prerequisites = "",
            summary = "If following the Orc route, eliminate the designated Rebel forces and report back to Faring's leadership.",
            walkthroughSteps = listOf("Speak with Orc leadership and make sure all quest-related dialogue is exhausted. The objective is associated with Faring region. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "If following the Orc route, eliminate the designated Rebel forces and report back to Faring's leadership.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "Finish all neutral and Rebel-dependent content first."),
            reward = "",
            warnings = "⚠ Choice warning: Make a manual save before committing. This objective can affect faction access, named NPCs or later quests.",
            searchTags = listOf("Destroy the rebels connected to Faring.", "Orc leadership", "Faring region", "DEFER — ORC PATH")
        ),
        Quest(
            id = "G3-P3-070",
            chapter = 3,
            playOrder = 70,
            title = "Liberate Faring from the orcs!",
            category = "DEFER — REBEL PATH",
            giver = "Rebel route / player action",
            location = "Faring",
            prerequisites = "",
            summary = "After completing every desired Faring quest and using the pass as needed, attack the Orc occupation and defeat enough defenders for the settlement to fall.",
            walkthroughSteps = listOf("Speak with Rebel route / player action and make sure all quest-related dialogue is exhausted. The objective is associated with Faring. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "After completing every desired Faring quest and using the pass as needed, attack the Orc occupation and defeat enough defenders for the settlement to fall.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "Faring is heavily defended. Treat this as a late-game liberation, not an arrival quest."),
            reward = "",
            warnings = "⚠ Choice warning: Make a manual save before committing. This objective can affect faction access, named NPCs or later quests.",
            searchTags = listOf("Liberate Faring from the orcs!", "Rebel route / player action", "Faring", "DEFER — REBEL PATH")
        ),
    )
}
