package com.sliverzfx.gothicquest

internal object Gothic3Part3Data {
    val quests = listOf(
        Quest(
            id = "G3-P3-001",
            chapter = 3,
            playOrder = 1,
            title = "Bring the shaman Grimboll sulfur.",
            category = "SAFE",
            giver = "Grimboll",
            location = "Geldern",
            prerequisites = "Talk to Orc shaman Grimboll in Geldern.",
            summary = "Speak with Grimboll in Geldern and accept his request for sulfur. Collect the required sulfur pieces from mines, merchants or loot and bring the complete amount back to him.",
            walkthroughSteps = listOf("Ask Grimboll in Geldern what he needs from the sulfur mines.", "Collect FIVE pieces of sulfur from nearby mine deposits or your inventory.", "Hand all five to Grimboll."),
            reward = "1,000 XP and +2 Geldern reputation.",
            warnings = "",
            searchTags = listOf("Bring the shaman Grimboll sulfur.", "Grimboll", "Geldern", "SAFE")
        ),
        Quest(
            id = "G3-P3-002",
            chapter = 3,
            playOrder = 2,
            title = "Bring the shaman Nemrok the artifact from the ruin in the north.",
            category = "SAFE",
            giver = "Nemrok",
            location = "Geldern → northern ruins",
            prerequisites = "Talk to Nemrok in Geldern about artifacts to the northwest.",
            summary = "Nemrok sends you to the ruins north of Geldern to recover an ancient artifact. Travel north, clear any creatures around the ruin, search the site thoroughly and take the quest artifact back to Nemrok.",
            walkthroughSteps = listOf("Ask Nemrok about the ancient artifact among the ruins NORTHWEST of Geldern.", "Follow the river toward the ruined hill, watching for trolls, ripperbeasts and shadowbeasts.", "Find the SHADOW SCEPTER among the ruins and return it to Nemrok."),
            reward = "2,000 XP and +6 Geldern reputation.",
            warnings = "The ruins are NORTHWEST by the river on a hill, not due north; the item is the Shadow Scepter.",
            searchTags = listOf("Bring the shaman Nemrok the artifact from the ruin in the north.", "Nemrok", "Geldern → northern ruins", "SAFE")
        ),
        Quest(
            id = "G3-P3-003",
            chapter = 3,
            playOrder = 3,
            title = "Bring Nemrok the scepter from the ruins.",
            category = "SAFE",
            giver = "Nemrok",
            location = "Geldern region",
            prerequisites = "Speak with Nemrok about the ruin artifact commission.",
            summary = "Follow Nemrok's directions to the specified ruins, locate the requested scepter among the ancient remains and return it to him.",
            walkthroughSteps = listOf("Speak with Nemrok and make sure all quest-related dialogue is exhausted. The objective is associated with Geldern region. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "Follow Nemrok's directions to the specified ruins, locate the requested scepter among the ancient remains and return it to him.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "Do this alongside the other ruin searches to minimize travel."),
            reward = "",
            warnings = "Cross-check against Nemrok's Shadow Scepter quest before looking for a SECOND unidentified scepter; entries may describe the same objective in some versions.",
            searchTags = listOf("Bring Nemrok the scepter from the ruins.", "Nemrok", "Geldern region", "SAFE")
        ),
        Quest(
            id = "G3-P3-004",
            chapter = 3,
            playOrder = 4,
            title = "Bring Renwik the rare plant King's Sorrel.",
            category = "SAFE",
            giver = "Renwik",
            location = "Geldern",
            prerequisites = "Speak to alchemist Renwik in Geldern.",
            summary = "Renwik, Geldern's absent-minded alchemist, asks for a King's Sorrel. Give him one from your inventory or search the countryside for the distinctive rare plant.",
            walkthroughSteps = listOf("Speak with Renwik and make sure all quest-related dialogue is exhausted. The objective is associated with Geldern. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "Renwik, Geldern's absent-minded alchemist, asks for a King's Sorrel. Give him one from your inventory or search the countryside for the distinctive rare plant.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "King's Sorrel permanently increases attributes through potions later, so decide whether the quest reward is worth giving one away."),
            reward = "1,000 XP and +2 Geldern reputation for King's Sorrel.",
            warnings = "",
            searchTags = listOf("Bring Renwik the rare plant King's Sorrel.", "Renwik", "Geldern", "SAFE")
        ),
        Quest(
            id = "G3-P3-005",
            chapter = 3,
            playOrder = 5,
            title = "Find all the fire chalices for Grok.",
            category = "MAIN QUEST / CHOICE",
            giver = "Sebastian (Reddock) / Grok offers the Orc-aligned hand-in",
            location = "Geldern",
            prerequisites = "Speak with Sebastian in Reddock and begin collecting the 12 Fire Chalices.",
            summary = "Grok is interested in the Fire Chalices and can become involved in the global chalice quest. Speak with him only after understanding which faction outcome you want; the chalices are central to restoring the paladins' magic.",
            walkthroughSteps = listOf("Start the global Fire Chalice quest with Sebastian in Reddock.", "Find twelve chalices scattered across Myrtana, Nordmar and Varant; consult the global checklist in Part 7 for the exact holders.", "If siding with the Orcs, deliver all twelve UNBLESSED chalices to Grok in Geldern.", "If restoring paladins, keep the set, travel to Milten at Nordmar Monastery, and bless the chalices in the sacred fire instead."),
            reward = "10,000 XP and +7 Orc reputation for delivering all twelve unblessed Fire Chalices to Grok, an alternative to Milten's sacred-fire route.",
            warnings = "Grok's delivery competes with the Fire Mage sacred-fire objective. Save BEFORE handing over all twelve chalices.",
            searchTags = listOf("Find all the fire chalices for Grok.", "Grok", "Geldern", "MAIN QUEST / CHOICE")
        ),
        Quest(
            id = "G3-P3-006",
            chapter = 3,
            playOrder = 6,
            title = "Find the first paladin's helmet.",
            category = "SAFE",
            giver = "Shawn (Gotha reconstruction) / helmet found in Geldern",
            location = "Geldern / ruins",
            prerequisites = "Help Shawn with rebuilding Gotha and ask about the missing legendary paladin helmet.",
            summary = "Search the indicated ruins/old battlefield area for the missing paladin helmet and recover it for the relevant Geldern quest giver.",
            walkthroughSteps = listOf("After working with Shawn to rebuild Gotha, ask about his search for the old paladin's helmet.", "Travel to Geldern and examine the shaman's quarters; the helmet is on a shelf.", "Take the helmet and return through the related quest dialogue, or sell to Jared only if willing to lose its other uses."),
            reward = "500 XP and +1 Thieving skill.",
            warnings = "The helmet is in GELDERN's shaman quarters, on a shelf. Avoid selling it before the original quest is resolved.",
            searchTags = listOf("Find the first paladin's helmet.", "Geldern quest chain", "Geldern / ruins", "SAFE")
        ),
        Quest(
            id = "G3-P3-007",
            chapter = 3,
            playOrder = 7,
            title = "Find the druid Runak.",
            category = "CHOICE",
            giver = "Grok (Orc shaman) for investigation; Runak for Ranger path",
            location = "Forest northwest of Geldern",
            prerequisites = "Ask Grok about the druids near Geldern, then find Runak's forest camp.",
            summary = "Travel into the forest northwest of Geldern and locate Runak's Ranger camp. Speak with Runak before taking any hostile action so you can access his dialogue and associated quests.",
            walkthroughSteps = listOf("Speak with Geldern / Orc quest chain and make sure all quest-related dialogue is exhausted. The objective is associated with Forest northwest of Geldern. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "Travel into the forest northwest of Geldern and locate Runak's Ranger camp. Speak with Runak before taking any hostile action so you can access his dialogue and associated quests.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "Runak is a Druid and is connected to the Orc-vs-Druid conflict. Do not kill him merely because an Orc asks you to."),
            reward = "",
            warnings = "Finding Runak does not require killing him. Runak and Grok/Bollock offer rival outcomes; speak with the Druid before choosing.",
            searchTags = listOf("Find the druid Runak.", "Geldern / Orc quest chain", "Forest northwest of Geldern", "CHOICE")
        ),
        Quest(
            id = "G3-P3-008",
            chapter = 3,
            playOrder = 8,
            title = "Kill the druid Runak.",
            category = "DEFER — ORC PATH",
            giver = "Grok or Bollock",
            location = "Runak's camp",
            prerequisites = "Orc-aligned hunt for Runak; speak with Grok or Bollock first.",
            summary = "If committing to the Orc route, return to Runak's camp and kill the druid, then report the result to the Orc quest giver in Geldern.",
            walkthroughSteps = listOf("Speak with Orc leadership in Geldern and make sure all quest-related dialogue is exhausted. The objective is associated with Runak's camp. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "If committing to the Orc route, return to Runak's camp and kill the druid, then report the result to the Orc quest giver in Geldern.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "Finish Runak's quests and any Druid Stone objectives first."),
            reward = "2,500 XP, +4 Orc reputation and +4 Geldern reputation for killing Runak.",
            warnings = "Killing Runak permanently loses his druid/Ranger quests and Shadowbeast stone. Finish them before this Orc assassination.",
            searchTags = listOf("Kill the druid Runak.", "Orc leadership in Geldern", "Runak's camp", "DEFER — ORC PATH")
        ),
        Quest(
            id = "G3-P3-009",
            chapter = 3,
            playOrder = 9,
            title = "Kill the wandering shadowbeasts.",
            category = "SAFE",
            giver = "Geldern hunter",
            location = "Geldern wilderness",
            prerequisites = "",
            summary = "Track the designated Shadowbeasts roaming outside Geldern, kill the complete target group and return to the hunter.",
            walkthroughSteps = listOf("Speak with Geldern hunter and make sure all quest-related dialogue is exhausted. The objective is associated with Geldern wilderness. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "Track the designated Shadowbeasts roaming outside Geldern, kill the complete target group and return to the hunter.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "Shadowbeasts are dangerous at low level; fight one at a time where possible."),
            reward = "",
            warnings = "",
            searchTags = listOf("Kill the wandering shadowbeasts.", "Geldern hunter", "Geldern wilderness", "SAFE")
        ),
        Quest(
            id = "G3-P3-010",
            chapter = 3,
            playOrder = 10,
            title = "Minecrawler plates for the shaman.",
            category = "SAFE",
            giver = "Geldern shaman",
            location = "Geldern mines",
            prerequisites = "",
            summary = "Hunt Minecrawlers in the mines around Geldern and collect the requested plates. Return when you have the full quantity.",
            walkthroughSteps = listOf("Speak with Geldern shaman and make sure all quest-related dialogue is exhausted. The objective is associated with Geldern mines. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "Hunt Minecrawlers in the mines around Geldern and collect the requested plates. Return when you have the full quantity.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "If you lack the appropriate trophy skill, check whether the quest version provides lootable plates or learn the skill before hunting."),
            reward = "",
            warnings = "",
            searchTags = listOf("Minecrawler plates for the shaman.", "Geldern shaman", "Geldern mines", "SAFE")
        ),
        Quest(
            id = "G3-P3-011",
            chapter = 3,
            playOrder = 11,
            title = "The secret of Mazin's mine.",
            category = "SAFE",
            giver = "Mazin and Mirzo (brothers)",
            location = "Mine near Geldern",
            prerequisites = "Speak with Mazin and Mirzo about artifacts extracted from the Geldern mines.",
            summary = "Speak with Mazin and investigate the mine he is concerned about. Explore it completely, deal with the creatures inside and inspect the deeper chambers for the reason the mine is unusual.",
            walkthroughSteps = listOf("Find Hashishin merchant Mazin and ask why he sells rare artifacts.", "Locate his brother Mirzo working in a Geldern mine and question him about the source of the relics.", "Return the discovered mine information to the relevant Geldern overseer if pursuing the Orc investigation."),
            reward = "2,000 XP and +4 Geldern reputation.",
            warnings = "",
            searchTags = listOf("The secret of Mazin's mine.", "Mazin", "Mine near Geldern", "SAFE")
        ),
        Quest(
            id = "G3-P3-012",
            chapter = 3,
            playOrder = 12,
            title = "Gold plates for Lares.",
            category = "SAFE / THIEVERY",
            giver = "Lares",
            location = "Geldern",
            prerequisites = "",
            summary = "Lares wants valuable golden plates from Geldern. Acquire the required plates without causing the entire city to become hostile and bring them to him.",
            walkthroughSteps = listOf("Speak with Lares and make sure all quest-related dialogue is exhausted. The objective is associated with Geldern. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "Lares wants valuable golden plates from Geldern. Acquire the required plates without causing the entire city to become hostile and bring them to him.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "Use nighttime and save before theft. Lares's quests are much easier before a city liberation."),
            reward = "",
            warnings = "",
            searchTags = listOf("Gold plates for Lares.", "Lares", "Geldern", "SAFE / THIEVERY")
        ),
        Quest(
            id = "G3-P3-013",
            chapter = 3,
            playOrder = 13,
            title = "Steal the shamans' artifact.",
            category = "SAFE / THIEVERY",
            giver = "Lares / Rebel-thief chain",
            location = "Geldern",
            prerequisites = "",
            summary = "Infiltrate the shamans' area and steal the requested artifact. Avoid witnesses and return it to the quest giver.",
            walkthroughSteps = listOf("Speak with Lares / Rebel-thief chain and make sure all quest-related dialogue is exhausted. The objective is associated with Geldern. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "Infiltrate the shamans' area and steal the requested artifact. Avoid witnesses and return it to the quest giver.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "Do not begin a general fight; this is intended as theft, not liberation."),
            reward = "",
            warnings = "",
            searchTags = listOf("Steal the shamans' artifact.", "Lares / Rebel-thief chain", "Geldern", "SAFE / THIEVERY")
        ),
        Quest(
            id = "G3-P3-014",
            chapter = 3,
            playOrder = 14,
            title = "Bring Jared Lares' message.",
            category = "SAFE",
            giver = "Jared",
            location = "Geldern",
            prerequisites = "Speak with Jared in Geldern; Lares is also staying nearby.",
            summary = "Carry the message between Jared and Lares and exhaust the follow-up dialogue on both ends.",
            walkthroughSteps = listOf("Talk with artifact trader Jared; he wants to meet the famous thief Lares.", "Find Lares in Geldern and pass along Jared's request.", "Return to Jared and confirm the meeting or completed introduction."),
            reward = "1,000 XP, +2 Geldern reputation and +1 Thieving.",
            warnings = "",
            searchTags = listOf("Bring Jared Lares' message.", "Jared / Lares", "Geldern", "SAFE")
        ),
        Quest(
            id = "G3-P3-015",
            chapter = 3,
            playOrder = 15,
            title = "Seven ancient rings for the alchemist.",
            category = "SAFE",
            giver = "Jared (artifact merchant)",
            location = "Geldern / ruins",
            prerequisites = "Speak with Jared about the seven ancient alchemists' rings; stealth access needed to the shaman quarters.",
            summary = "Collect the seven ancient rings requested by the alchemist. Search ruins, chests and quest locations around Geldern, then deliver the complete set.",
            walkthroughSteps = listOf("Accept Jared's request for SEVEN ancient alchemist rings.", "Search shelves, tables and locked rooms around Geldern's shaman quarters for the rings.", "Take rings carefully without triggering guards; a high local reputation may be necessary to reach restricted rooms.", "Deliver all seven rings to Jared."),
            reward = "1,500 XP and +1 Thieving.",
            warnings = "The rings are primarily in Geldern itself, not scattered around unrelated world ruins. Save before each risky theft.",
            searchTags = listOf("Seven ancient rings for the alchemist.", "Geldern alchemist", "Geldern / ruins", "SAFE")
        ),
        Quest(
            id = "G3-P3-016",
            chapter = 3,
            playOrder = 16,
            title = "A delivery from the southern mine.",
            category = "SAFE",
            giver = "Geldern mine quest chain",
            location = "Southern mine → Geldern",
            prerequisites = "",
            summary = "Visit the southern mine, obtain the shipment requested for Geldern and deliver it to the named recipient in town.",
            walkthroughSteps = listOf("Speak with Geldern mine quest chain and make sure all quest-related dialogue is exhausted. The objective is associated with Southern mine → Geldern. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "Visit the southern mine, obtain the shipment requested for Geldern and deliver it to the named recipient in town.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "Use the trip to clear nearby wildlife and mine ore."),
            reward = "",
            warnings = "",
            searchTags = listOf("A delivery from the southern mine.", "Geldern mine quest chain", "Southern mine → Geldern", "SAFE")
        ),
        Quest(
            id = "G3-P3-017",
            chapter = 3,
            playOrder = 17,
            title = "The northern mine needs help.",
            category = "SAFE",
            giver = "Geldern mine quest chain",
            location = "Northern mine",
            prerequisites = "",
            summary = "Travel to the northern mine and resolve the problem preventing normal work—speak to the workers, clear hostile creatures as required and report back.",
            walkthroughSteps = listOf("Speak with Geldern mine quest chain and make sure all quest-related dialogue is exhausted. The objective is associated with Northern mine. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "Travel to the northern mine and resolve the problem preventing normal work—speak to the workers, clear hostile creatures as required and report back.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "Search the mine thoroughly for quest ore and artifacts."),
            reward = "",
            warnings = "",
            searchTags = listOf("The northern mine needs help.", "Geldern mine quest chain", "Northern mine", "SAFE")
        ),
        Quest(
            id = "G3-P3-018",
            chapter = 3,
            playOrder = 18,
            title = "Hamil the audacious artifact trader among the slaves.",
            category = "SAFE / INVESTIGATION",
            giver = "Hamil",
            location = "Geldern",
            prerequisites = "Meet slave Hamil near Geldern's mine and uncover his artifact trade.",
            summary = "Find Hamil among Geldern's slaves and speak with him about his artifact dealings. Follow the dialogue carefully before deciding whether to expose or assist him.",
            walkthroughSteps = listOf("Question Hamil about how he obtained rare artifacts from the Geldern mine.", "Report his black-market trade to Orc overseer Nemrok.", "Locate alchemist Peratur, who is involved in supplying or handling the finds, and finish the dialogue."),
            reward = "1,500 XP and +4 Geldern reputation.",
            warnings = "",
            searchTags = listOf("Hamil the audacious artifact trader among the slaves.", "Hamil", "Geldern", "SAFE / INVESTIGATION")
        ),
        Quest(
            id = "G3-P3-019",
            chapter = 3,
            playOrder = 19,
            title = "Mobilize the people of Geldern for Torn's druid stone.",
            category = "CHOICE — REBEL/DRUID",
            giver = "Torn (Druid)",
            location = "Geldern region",
            prerequisites = "Meet Torn in the Ranger camp and agree to mobilize Geldern for the druid cause.",
            summary = "Complete the preparation required by Torn and the local resistance for the Druid-related objective around Geldern.",
            walkthroughSteps = listOf("Ask druid Torn how to mobilize resistance against Geldern's Orcs.", "Talk to cook/former Fire Mage Marius in Geldern and ask about sympathetic allies.", "Investigate the golden chalice in Geldern's temple through the appropriate reputation gate.", "Report to Torn when Marius's leads have been investigated."),
            reward = "1,500 XP and +15 Rangers reputation.",
            warnings = "This follows the Ranger/Druid route, which conflicts with Grok's druid assassination quests.",
            searchTags = listOf("Mobilize the people of Geldern for Torn's druid stone.", "Torn / Rebel-Druid route", "Geldern region", "CHOICE — REBEL/DRUID")
        ),
        Quest(
            id = "G3-P3-020",
            chapter = 3,
            playOrder = 20,
            title = "Liberate Geldern from the orcs!",
            category = "DEFER — REBEL PATH",
            giver = "Rebel/Druid route",
            location = "Geldern",
            prerequisites = "Choose the Rebel/Druid path and complete wanted Geldern merchant, arena and shaman investigations.",
            summary = "Only after completing Geldern's normal quests, attack the Orc leadership and defenders until the surviving occupation flees. Protect useful allies and loot important named enemies.",
            walkthroughSteps = listOf("Speak with Rebel/Druid route and make sure all quest-related dialogue is exhausted. The objective is associated with Geldern. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "Only after completing Geldern's normal quests, attack the Orc leadership and defenders until the surviving occupation flees. Protect useful allies and loot important named enemies.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "A major city liberation; save beforehand and expect consequences with the Orc faction."),
            reward = "7,500 XP and +5 Rebel reputation for liberating Geldern.",
            warnings = "Geldern is a COUNTED Orc-town liberation. Finish Grok's peaceful Fire Chalice and other merchants' quests first.",
            searchTags = listOf("Liberate Geldern from the orcs!", "Rebel/Druid route", "Geldern", "DEFER — REBEL PATH")
        ),
        Quest(
            id = "G3-P3-021",
            chapter = 3,
            playOrder = 21,
            title = "Destroy the rebel resistance around Geldern.",
            category = "DEFER — ORC PATH",
            giver = "Orc leadership",
            location = "Geldern region",
            prerequisites = "Accept Orc leadership's mission against Ranger camps around Geldern.",
            summary = "On the Orc route, eliminate the Ranger/Rebel positions around Geldern and report the destruction.",
            walkthroughSteps = listOf("Speak with Orc leadership and make sure all quest-related dialogue is exhausted. The objective is associated with Geldern region. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "On the Orc route, eliminate the Ranger/Rebel positions around Geldern and report the destruction.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "Mutually destructive with the Rebel/Druid quest line. Finish neutral quests first."),
            reward = "",
            warnings = "Destroying Runak and Torn's people permanently blocks Ranger Druid Stones and related quests; make a save.",
            searchTags = listOf("Destroy the rebel resistance around Geldern.", "Orc leadership", "Geldern region", "DEFER — ORC PATH")
        ),
        Quest(
            id = "G3-P3-022",
            chapter = 3,
            playOrder = 22,
            title = "Take the delivery from Nordmar to Anog.",
            category = "SAFE — REBEL",
            giver = "Anog (Rebel leader outside Silden)",
            location = "Road/Nordmar border → Silden",
            prerequisites = "Speak with Anog's Rebels and locate Orc supply courier Tragak.",
            summary = "Recover the delivery intended for Anog and bring it safely to the Rebel leader outside Silden.",
            walkthroughSteps = listOf("Find Anog in the forest rebel camp near Silden and ask about the Nordmar supplies.", "Tragak is bringing an Orc shipment toward shaman Grompel in Silden.", "For Anog's Rebel route, intercept and kill Tragak before he reaches Grompel.", "Take the shipment and deliver it to Anog."),
            reward = "1,500 XP and +1 Rebel reputation.",
            warnings = "Tragak's delivery to Grompel is the opposing Orc route. Do not escort him to Silden if you plan to steal his shipment for Anog.",
            searchTags = listOf("Take the delivery from Nordmar to Anog.", "Anog", "Road/Nordmar border → Silden", "SAFE — REBEL")
        ),
        Quest(
            id = "G3-P3-023",
            chapter = 3,
            playOrder = 23,
            title = "Talk to Anog about the rebel situation.",
            category = "SAFE",
            giver = "Anog",
            location = "Rebel camp near Silden",
            prerequisites = "",
            summary = "Speak with Anog and exhaust his dialogue about Silden, the surrounding patrols and his brother Inog inside town.",
            walkthroughSteps = listOf("Speak with Anog and make sure all quest-related dialogue is exhausted. The objective is associated with Rebel camp near Silden. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "Speak with Anog and exhaust his dialogue about Silden, the surrounding patrols and his brother Inog inside town.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "Do this before entering deeper into the Silden faction chain."),
            reward = "",
            warnings = "",
            searchTags = listOf("Talk to Anog about the rebel situation.", "Anog", "Rebel camp near Silden", "SAFE")
        ),
        Quest(
            id = "G3-P3-024",
            chapter = 3,
            playOrder = 24,
            title = "Let Anog Know That Inog Needs Help",
            category = "SAFE — REBEL",
            giver = "Inog",
            location = "Silden",
            prerequisites = "Ask Inog at his house in Silden about organizing resistance.",
            summary = "Find Inog inside Silden and speak with him privately. Complete his requested support tasks without exposing him to the Orcs.",
            walkthroughSteps = listOf("Find Inog in Silden and ask about the rebellion he is secretly planning.", "He needs help from his brother ANOG, whose Rebels are hidden in nearby woods.", "Travel to Anog's rebel camp and pass on Inog's message.", "Anog's reply opens the follow-up return message."),
            reward = "1,000 XP and +1 Rebel reputation.",
            warnings = "",
            searchTags = listOf("Inog needs help.", "Inog", "Silden", "SAFE — REBEL")
        ),
        Quest(
            id = "G3-P3-025",
            chapter = 3,
            playOrder = 25,
            title = "Bring Inog five bundles of weapons.",
            category = "SAFE — REBEL",
            giver = "Inog",
            location = "Silden",
            prerequisites = "Find Inog in Silden and offer to help the resistance.",
            summary = "Collect five Bundles of Weapons and secretly deliver them to Inog.",
            walkthroughSteps = listOf("Inog requests five Weapon Bundles for his underground rebels.", "Collect five bundles from the old mill or Orc quarters; ordinary swords are not equivalent.", "Bring all FIVE Weapon Bundles to Inog discreetly."),
            reward = "1,500 XP and +1 Rebel reputation.",
            warnings = "",
            searchTags = listOf("Bring Inog five bundles of weapons.", "Inog", "Silden", "SAFE — REBEL")
        ),
        Quest(
            id = "G3-P3-026",
            chapter = 3,
            playOrder = 26,
            title = "Kill the orc patrol near Silden.",
            category = "SAFE — REBEL",
            giver = "Anog / Rebel chain",
            location = "Silden outskirts",
            prerequisites = "",
            summary = "Locate the designated Orc patrol outside Silden, eliminate it away from the town and report to the Rebels.",
            walkthroughSteps = listOf("Speak with Anog / Rebel chain and make sure all quest-related dialogue is exhausted. The objective is associated with Silden outskirts. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "Locate the designated Orc patrol outside Silden, eliminate it away from the town and report to the Rebels.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "Avoid dragging the fight into Silden."),
            reward = "",
            warnings = "",
            searchTags = listOf("Kill the orc patrol near Silden.", "Anog / Rebel chain", "Silden outskirts", "SAFE — REBEL")
        ),
        Quest(
            id = "G3-P3-027",
            chapter = 3,
            playOrder = 27,
            title = "Kill the strange lurkers at the river.",
            category = "SAFE",
            giver = "Brontobb (Silden town guard)",
            location = "River near Silden",
            prerequisites = "Speak to Brontobb about the strange lurkers near Silden's river.",
            summary = "Follow the river and kill the designated Lurkers threatening the local workers or fishermen. Return after the full target group is dead.",
            walkthroughSteps = listOf("Brontobb reports unusual lurkers attacking near the river.", "Find the riverbank outside Silden and kill EIGHT strange lurkers.", "Report back to Brontobb; he can now be recruited as a city guard for Denpok."),
            reward = "1,000 XP and +6 Silden reputation.",
            warnings = "Eight STRANGE lurkers, not ordinary lurkers elsewhere.",
            searchTags = listOf("Kill the strange lurkers at the river.", "Silden hunter/fisher", "River near Silden", "SAFE")
        ),
        Quest(
            id = "G3-P3-028",
            chapter = 3,
            playOrder = 28,
            title = "Take the Fish Barrels to the Mill",
            category = "SAFE",
            giver = "Temmy (Silden fisherman)",
            location = "Silden",
            prerequisites = "Ask Temmy at Silden's fishing huts about his catch.",
            summary = "Help the fishermen with the requested catch/delivery objective and bring the required fish or goods to the quest giver.",
            walkthroughSteps = listOf("Find fisherman Temmy near Silden's riverside fishery.", "Collect EIGHT barrels of fish from the fishermen's huts and surrounding area.", "Carry them to GIVESS at the old mill.", "Report the completed delivery to Temmy if his dialogue is offered."),
            reward = "1,000 XP and +4 Silden reputation.",
            warnings = "",
            searchTags = listOf("The fishermen's catch.", "Silden fishing camp", "Silden", "SAFE")
        ),
        Quest(
            id = "G3-P3-029",
            chapter = 3,
            playOrder = 29,
            title = "The Wood from the Prison Camp for Givess",
            category = "SAFE",
            giver = "Gancka (Silden guard)",
            location = "Silden outskirts",
            prerequisites = "Ask Gancka at the Silden lumber/prison camp about supplies.",
            summary = "Visit the woodcutters, resolve the reason they have stopped working and report that production can resume.",
            walkthroughSteps = listOf("Talk to Gancka at the prison-camp sawmill.", "Collect TEN packages of firewood scattered around the camp.", "Bring the full set to Givess in the old mill.", "Report the supply delivery."),
            reward = "1,000 XP and +4 Silden reputation.",
            warnings = "",
            searchTags = listOf("Bring the woodcutters back to work.", "Silden lumber camp", "Silden outskirts", "SAFE")
        ),
        Quest(
            id = "G3-P3-030",
            chapter = 3,
            playOrder = 30,
            title = "Hunt the wolves around Silden.",
            category = "SAFE",
            giver = "Bram (hunter near Silden)",
            location = "Silden wilderness",
            prerequisites = "Meet Bram at his hut outside Silden.",
            summary = "Kill the specified wolf packs around Silden and report back.",
            walkthroughSteps = listOf("Speak to hunter Bram about the wolves near his home.", "Find and kill the group of wolves in the surrounding woods.", "Return to Bram, who can also offer a silver-wolf hunting excursion."),
            reward = "1,000 XP, +2 Silden reputation and +1 Hunting.",
            warnings = "",
            searchTags = listOf("Hunt the wolves around Silden.", "Silden hunter", "Silden wilderness", "SAFE")
        ),
        Quest(
            id = "G3-P3-031",
            chapter = 3,
            playOrder = 31,
            title = "Pelts for the hunter in Silden.",
            category = "SAFE",
            giver = "Lukjan (Silden hunter)",
            location = "Silden",
            prerequisites = "Find Lukjan and his fellow hunter near Silden.",
            summary = "Collect the requested animal pelts and deliver them to the hunter.",
            walkthroughSteps = listOf("Ask hunter Lukjan about the hides from his latest hunt.", "Discuss the money owed for the pelts.", "Deliver Lukjan's collected payment and speak with him to complete the exchange."),
            reward = "Reward varies by the hunter payment route; exact standalone XP not confirmed.",
            warnings = "Do not confuse Lukjan's pelts with Bram's wolves or Falk's snappers.",
            searchTags = listOf("Pelts for the hunter in Silden.", "Silden hunter", "Silden", "SAFE")
        ),
        Quest(
            id = "G3-P3-032",
            chapter = 3,
            playOrder = 32,
            title = "Take the slaves to the lumber camp.",
            category = "CHOICE",
            giver = "Silden overseer",
            location = "Silden → lumber camp",
            prerequisites = "",
            summary = "Escort the assigned slaves from Silden to the lumber camp and keep the group alive.",
            walkthroughSteps = listOf("Speak with Silden overseer and make sure all quest-related dialogue is exhausted. The objective is associated with Silden → lumber camp. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "Escort the assigned slaves from Silden to the lumber camp and keep the group alive.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "Slave quests can conflict with Rebel rescue objectives; check active alternatives first."),
            reward = "",
            warnings = "⚠ Choice warning: Make a manual save before committing. This objective can affect faction access, named NPCs or later quests.",
            searchTags = listOf("Take the slaves to the lumber camp.", "Silden overseer", "Silden → lumber camp", "CHOICE")
        ),
        Quest(
            id = "G3-P3-033",
            chapter = 3,
            playOrder = 33,
            title = "Rescue a Silden Slave from the Wilderness",
            category = "CHOICE — REBEL",
            giver = "Freman (Rebel camp near Silden)",
            location = "Silden",
            prerequisites = "Find Freman's Rebels in the woods near Silden.",
            summary = "Help the relevant slaves escape Orc control and reach safety according to the Rebel plan.",
            walkthroughSteps = listOf("Ask Freman about escaped slaves hiding near the city.", "Search the woods on the opposite side of Silden, near three separate campfires.", "Find a survivor, ask them to follow, and escort them through wildlife to Freman's rebel camp.", "Report the rescue."),
            reward = "500 XP and +1 Rebel reputation.",
            warnings = "Keep the escaped slave alive; their camp lies away from Freman on the far side of Silden.",
            searchTags = listOf("Free the slaves from Silden.", "Rebel route", "Silden", "CHOICE — REBEL")
        ),
        Quest(
            id = "G3-P3-034",
            chapter = 3,
            playOrder = 34,
            title = "Win the arena fights in Silden.",
            category = "SAFE",
            giver = "Silden arena fighters",
            location = "Silden arena",
            prerequisites = "",
            summary = "Challenge the available arena opponents one by one. Stay inside the arena boundaries, knock each opponent unconscious rather than killing them, and speak to them or the arena organizer after each victory.",
            walkthroughSteps = listOf("Speak with Silden arena fighters and make sure all quest-related dialogue is exhausted. The objective is associated with Silden arena. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "Challenge the available arena opponents one by one. Stay inside the arena boundaries, knock each opponent unconscious rather than killing them, and speak to them or the arena organizer after each victory.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "Finish all arena fights before liberating Silden."),
            reward = "",
            warnings = "",
            searchTags = listOf("Win the arena fights in Silden.", "Silden arena fighters", "Silden arena", "SAFE")
        ),
        Quest(
            id = "G3-P3-035",
            chapter = 3,
            playOrder = 35,
            title = "Defeat the strongest fighter in Silden.",
            category = "SAFE",
            giver = "Arena champion",
            location = "Silden arena",
            prerequisites = "",
            summary = "After beating the preliminary opponents, challenge the champion and win under normal arena rules.",
            walkthroughSteps = listOf("Speak with Arena champion and make sure all quest-related dialogue is exhausted. The objective is associated with Silden arena. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "After beating the preliminary opponents, challenge the champion and win under normal arena rules.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "Arena victories are a safe way to build town reputation."),
            reward = "",
            warnings = "",
            searchTags = listOf("Defeat the strongest fighter in Silden.", "Arena champion", "Silden arena", "SAFE")
        ),
        Quest(
            id = "G3-P3-036",
            chapter = 3,
            playOrder = 36,
            title = "The Wood from the Prison Camp for Givess — Link",
            category = "SAFE",
            giver = "Gancka / Givess",
            location = "Silden / lumber camp",
            prerequisites = "Ask Gancka at the sawmill to deliver supplies to Givess.",
            summary = "Collect the required wood/firewood shipment and deliver it to the Orc recipient.",
            walkthroughSteps = listOf("Collect the ten wood bundles scattered around Silden's prison-camp sawmill.", "Take the bundles to Givess at the old mill.", "Finish Gancka's supply quest, also represented by the woodcutters' entry earlier in this section."),
            reward = "1,000 XP and +4 Silden reputation from the single documented delivery.",
            warnings = "Guide cross-reference; overlapping G3-P3-029 and G3-P3-036 describe the same ten-package hand-in, not two rewards.",
            searchTags = listOf("Bring the Orcs their requested firewood.", "Silden quartermaster", "Silden / lumber camp", "SAFE")
        ),
        Quest(
            id = "G3-P3-037",
            chapter = 3,
            playOrder = 37,
            title = "Take the Fish Barrels to the Mill — Link",
            category = "SAFE",
            giver = "Temmy / Givess",
            location = "Silden fishing camp",
            prerequisites = "Ask fisherman Temmy about sending the day's catch to Givess.",
            summary = "Collect the required fish shipment and deliver it to the Orcs.",
            walkthroughSteps = listOf("Collect eight fish barrels from Silden's fishermen's quarters.", "Deliver them to Givess at the old mill.", "Return to Temmy if a follow-up dialogue appears."),
            reward = "1,000 XP and +4 Silden reputation from the one documented delivery.",
            warnings = "Guide cross-reference to G3-P3-028, not a separate guaranteed fish quest.",
            searchTags = listOf("Bring the Orcs their fish.", "Silden quartermaster", "Silden fishing camp", "SAFE")
        ),
        Quest(
            id = "G3-P3-038",
            chapter = 3,
            playOrder = 38,
            title = "Find the missing hunter.",
            category = "SAFE",
            giver = "Silden quest chain",
            location = "Wilderness near Silden",
            prerequisites = "",
            summary = "Search the wilderness for the missing hunter, deal with nearby predators and speak with him if alive.",
            walkthroughSteps = listOf("Speak with Silden quest chain and make sure all quest-related dialogue is exhausted. The objective is associated with Wilderness near Silden. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "Search the wilderness for the missing hunter, deal with nearby predators and speak with him if alive.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "Follow roads, riverbanks and campfire clues rather than searching the entire forest randomly."),
            reward = "",
            warnings = "",
            searchTags = listOf("Find the missing hunter.", "Silden quest chain", "Wilderness near Silden", "SAFE")
        ),
        Quest(
            id = "G3-P3-039",
            chapter = 3,
            playOrder = 39,
            title = "The escaped slaves.",
            category = "CHOICE",
            giver = "Zapotek (Orc overseer) or Freman (Rebel alternative)",
            location = "Silden outskirts",
            prerequisites = "Find Silden's escaped slaves in the woods; faction branch.",
            summary = "Locate the escaped slaves and decide whether to help them or return/report them according to your chosen faction path.",
            walkthroughSteps = listOf("Ask Freman about escaped slaves hiding by three campfires across Silden's forest.", "On the Rebel route, escort an escaped slave back to Freman.", "On the Orc route, Zapotek orders you to kill the escaped slaves.", "Choose one objective; returning or killing the same slaves is mutually exclusive."),
            reward = "Rebel rescue: 500 XP and +1 Rebel reputation. Orc hunt: 1,500 XP and +1 Orc reputation.",
            warnings = "Rebel and Orc outcomes conflict. Do not kill the refugees if planning Freman's rescue.",
            searchTags = listOf("The escaped slaves.", "Silden quest chain", "Silden outskirts", "CHOICE")
        ),
        Quest(
            id = "G3-P3-040",
            chapter = 3,
            playOrder = 40,
            title = "Follow Lars to the Pass to Nordmar",
            category = "SAFE / CROSS-REGION",
            giver = "Lars (captured Nordmarian)",
            location = "Silden → Nordmar",
            prerequisites = "Buy Lars's freedom from Zapotek in Silden; historical price 300 gold.",
            summary = "Obtain the package destined for Nordmar and keep it until you travel through Faring into the northern region.",
            walkthroughSteps = listOf("Buy the Nordmarian Lars from Zapotek for about 300 gold.", "Speak to Lars after freeing him and agree to follow him to the northern pass.", "Escort him out of Silden and along the trails toward Nordmar.", "Keep him alive and finish his arrival dialogue."),
            reward = "1,500 XP and +2 Nordmar reputation for escorting Lars; freedom purchase costs about 300 gold.",
            warnings = "The earlier 'Package for Nordmar' generic task did not identify a separate documented delivery.",
            searchTags = listOf("A package for Nordmar.", "Silden/Nordmar quest chain", "Silden → Nordmar", "SAFE / CROSS-REGION")
        ),
        Quest(
            id = "G3-P3-041",
            chapter = 3,
            playOrder = 41,
            title = "Liberate Silden from the orcs!",
            category = "DEFER — REBEL PATH",
            giver = "Inog / Anog (Rebel liberation)",
            location = "Silden",
            prerequisites = "Prepare with Inog and Anog; finish neutral Silden jobs before attacking.",
            summary = "Finish Silden's arena, hunting, slave, fishing, lumber and undercover quests first. Then coordinate with the Rebel side and defeat enough Orc defenders for the town to fall.",
            walkthroughSteps = listOf("Complete wanted Silden quests and the messages between rebel brothers Inog and Anog.", "Coordinate the planned uprising and target isolated Orc groups first.", "Attack the city garrison, prioritizing the dangerous shaman.", "Lure defenders outside the town if outnumbered, then clear enough Orcs to liberate Silden."),
            reward = "7,500 XP and +5 Rebel reputation.",
            warnings = "Counted Orc town liberation; doing enough other liberations can make remaining Orc settlements hostile.",
            searchTags = listOf("Liberate Silden from the orcs!", "Inog / Anog / Rebel route", "Silden", "DEFER — REBEL PATH")
        ),
        Quest(
            id = "G3-P3-042",
            chapter = 3,
            playOrder = 42,
            title = "The Warlord Umbrak Wants Anog Dead",
            category = "DEFER — ORC PATH",
            giver = "Umbrak (Orc ruler of Silden)",
            location = "Silden region",
            prerequisites = "Gain Umbrak's trust in occupied Silden.",
            summary = "On an Orc-aligned playthrough, eliminate Anog's Rebel force and other designated resistance positions around Silden.",
            walkthroughSteps = listOf("Ask warlord Umbrak about the rebel leader Anog.", "Locate Anog at his forest camp near Silden.", "If siding with the Orcs, attack and kill Anog and his rebel followers.", "Report the assassination to Umbrak."),
            reward = "5,000 XP and +7 Orc reputation.",
            warnings = "Killing Anog eliminates his supplies quest and his brother Inog's underground story.",
            searchTags = listOf("Destroy the rebels around Silden.", "Orc leadership", "Silden region", "DEFER — ORC PATH")
        ),
        Quest(
            id = "G3-P3-043",
            chapter = 3,
            playOrder = 43,
            title = "Find the king.",
            category = "MAIN QUEST",
            giver = "Automatic when reaching King Rhobar",
            location = "Vengard",
            prerequisites = "Find the Vengard teleport rune in Gotha's undead cave to enter the royal city.",
            summary = "Use the Vengard teleport route/stone when the story sends you to the capital. Fight or evade Orcs inside the magical barrier and reach the castle. Speak with King Rhobar.",
            walkthroughSteps = listOf("Go to Gotha and clear or avoid the undead in the cave below the castle.", "Find the Vengard TELEPORT RUNE resting on a crate near the end of the mine shaft.", "Teleport inside the magical barrier, speak to Markus and fight toward the royal castle.", "Reach King Rhobar and talk to him to complete the find-the-king milestone."),
            reward = "2,500 XP for finding King Rhobar.",
            warnings = "Vengard's magical barrier cannot be entered by walking through it. Use the rune discovered in Gotha.",
            searchTags = listOf("Find the king.", "Main story", "Vengard", "MAIN QUEST")
        ),
        Quest(
            id = "G3-P3-044",
            chapter = 3,
            playOrder = 44,
            title = "Talk to King Rhobar.",
            category = "MAIN QUEST",
            giver = "King Rhobar",
            location = "Vengard castle",
            prerequisites = "Use Gotha's teleport rune to enter Vengard and fight to Rhobar's throne.",
            summary = "Once inside the castle, speak with Rhobar and exhaust the main-story dialogue about the war, Xardas, the divine artifacts and your next objectives.",
            walkthroughSteps = listOf("Speak with King Rhobar and make sure all quest-related dialogue is exhausted. The objective is associated with Vengard castle. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "Once inside the castle, speak with Rhobar and exhaust the main-story dialogue about the war, Xardas, the divine artifacts and your next objectives.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "Do not rush away; several castle NPCs open quests after you meet the king."),
            reward = "Meeting Rhobar advances the quest to discover Xardas's plan; 2,500 XP for finding the king in the base guide.",
            warnings = "Do not kill Rhobar before completing his investigation of Xardas or other Vengard dialogue.",
            searchTags = listOf("Talk to King Rhobar.", "King Rhobar", "Vengard castle", "MAIN QUEST")
        ),
        Quest(
            id = "G3-P3-045",
            chapter = 3,
            playOrder = 45,
            title = "Bring the Fire Mage Karrypto information.",
            category = "SAFE / MAIN-STORY SUPPORT",
            giver = "Karrypto (head of Fire Mages)",
            location = "Vengard castle",
            prerequisites = "Reach the Vengard castle and speak with Karrypto.",
            summary = "Speak with Karrypto in the castle and complete his information/request chain regarding the siege and magical situation.",
            walkthroughSteps = listOf("After teleporting into Vengard, talk to paladin Markus, who gives you his unblessed Fire Chalice.", "Fight to Rhobar's castle and find Karrypto, leader of the Fire Mages, near the king's throne.", "Give him Markus's chalice and ask about the defense of Vengard."),
            reward = "2,000 XP, +1 Rebel reputation and +5 Vengard reputation for Markus's chalice delivery.",
            warnings = "Markus is the chalice holder; Karrypto is the recipient. Preserve the chalice for his delivery dialogue.",
            searchTags = listOf("Bring the Fire Mage Karrypto information.", "Karrypto", "Vengard castle", "SAFE / MAIN-STORY SUPPORT")
        ),
        Quest(
            id = "G3-P3-046",
            chapter = 3,
            playOrder = 46,
            title = "Help the paladins defend Vengard.",
            category = "SAFE — REBEL",
            giver = "Vengard paladins",
            location = "Vengard",
            prerequisites = "",
            summary = "Join the defenders against Orc groups occupying sections of the city. Clear the specified positions rather than wandering into every enemy at once.",
            walkthroughSteps = listOf("Speak with Vengard paladins and make sure all quest-related dialogue is exhausted. The objective is associated with Vengard. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "Join the defenders against Orc groups occupying sections of the city. Clear the specified positions rather than wandering into every enemy at once.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "Use paladins as allies; pull smaller groups toward friendly fighters."),
            reward = "",
            warnings = "",
            searchTags = listOf("Help the paladins defend Vengard.", "Vengard paladins", "Vengard", "SAFE — REBEL")
        ),
        Quest(
            id = "G3-P3-047",
            chapter = 3,
            playOrder = 47,
            title = "Destroy the orcs inside the barrier.",
            category = "SAFE — REBEL / LARGE BATTLE",
            giver = "Markus (paladin at Vengard teleport entry)",
            location = "Vengard city",
            prerequisites = "Teleport inside Vengard and meet Markus.",
            summary = "Systematically clear the Orc forces trapped within Vengard's magical barrier. Work district by district and use surviving paladins to reduce the risk of being surrounded.",
            walkthroughSteps = listOf("Speak with Markus after the Vengard teleport and ask about the siege.", "Defeat FIVE distinct Orc siege leaders inside the city's barrier, using the temple defenders and Georg as allies when possible.", "Search all occupied quarters for remaining chiefs, and report to Cobryn after all five are dead."),
            reward = "5,000 XP, +2 Rebel reputation and +15 Vengard reputation.",
            warnings = "Requires five siege LEADERS, not just ordinary Orc soldiers. The siege battle inside Vengard does not count as a normal Orc-town liberation.",
            searchTags = listOf("Destroy the orcs inside the barrier.", "Vengard defenders", "Vengard city", "SAFE — REBEL / LARGE BATTLE")
        ),
        Quest(
            id = "G3-P3-048",
            chapter = 3,
            playOrder = 48,
            title = "Find the missing paladin patrol.",
            category = "SAFE",
            giver = "Cobryn (Vengard paladin commander)",
            location = "Vengard ruins",
            prerequisites = "Enter Vengard and reach Cobryn in the castle.",
            summary = "Search the ruined streets and buildings for the missing paladins and resolve their situation.",
            walkthroughSteps = listOf("Ask Cobryn about missing paladin Thordir.", "Return toward the castle entrance and enter the damaged wall tower in the ruined city.", "Jump the fallen obstacle on the stairs and reach Thordir beside the campfire at the top.", "Speak to Thordir; escort him to Cobryn if his follow-up appears."),
            reward = "1,500 XP and +15 Vengard reputation for locating Thordir; his escort adds another 2,000 XP and +15 Vengard.",
            warnings = "Thordir is on TOP of a wall turret near the castle approach, not in a random cave.",
            searchTags = listOf("Find the missing paladin patrol.", "Vengard quest chain", "Vengard ruins", "SAFE")
        ),
        Quest(
            id = "G3-P3-049",
            chapter = 3,
            playOrder = 49,
            title = "Supplies for Vengard.",
            category = "SAFE",
            giver = "Vengard quartermaster",
            location = "Vengard castle",
            prerequisites = "",
            summary = "Collect and deliver the requested supplies to the castle defenders.",
            walkthroughSteps = listOf("Speak with Vengard quartermaster and make sure all quest-related dialogue is exhausted. The objective is associated with Vengard castle. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "Collect and deliver the requested supplies to the castle defenders.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "Complete supply quests before selling bulk food, potions or weapon bundles."),
            reward = "",
            warnings = "",
            searchTags = listOf("Supplies for Vengard.", "Vengard quartermaster", "Vengard castle", "SAFE")
        ),
        Quest(
            id = "G3-P3-050",
            chapter = 3,
            playOrder = 50,
            title = "Healing for the defenders.",
            category = "SAFE",
            giver = "Vengard healer",
            location = "Vengard castle",
            prerequisites = "",
            summary = "Bring the requested healing items or plants to the healer supporting Vengard's troops.",
            walkthroughSteps = listOf("Speak with Vengard healer and make sure all quest-related dialogue is exhausted. The objective is associated with Vengard castle. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "Bring the requested healing items or plants to the healer supporting Vengard's troops.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "A simple support quest that is easiest if you arrive stocked."),
            reward = "",
            warnings = "",
            searchTags = listOf("Healing for the defenders.", "Vengard healer", "Vengard castle", "SAFE")
        ),
        Quest(
            id = "G3-P3-051",
            chapter = 3,
            playOrder = 51,
            title = "Find the teleport stone to Vengard.",
            category = "MAIN QUEST",
            giver = "Roland (Okara rebel leader)",
            location = "Myrtana",
            prerequisites = "Meet Roland at Okara and ask about reaching King Rhobar.",
            summary = "Obtain the teleport stone that allows entry past Vengard's magical barrier. Once used, be prepared to fight because the city outside the castle is occupied by Orcs.",
            walkthroughSteps = listOf("Speak with Roland in Okara to learn about Gotha's special Vengard teleporter.", "Travel to Gotha. Search the undead-filled UNDERGROUND tunnel below the old fortress.", "The Vengard rune lies on a crate near the end of the mine shaft.", "Return to Roland with news; then use the rune to teleport inside Vengard and meet the king."),
            reward = "2,500 XP for finding the Vengard rune, plus 1,000 XP follow-up from Roland in the base guide.",
            warnings = "The rune is in Gotha's subterranean mine/cave, not freely accessible inside Vengard.",
            searchTags = listOf("Find the teleport stone to Vengard.", "Main-story exploration", "Myrtana", "MAIN QUEST")
        ),
        Quest(
            id = "G3-P3-052",
            chapter = 3,
            playOrder = 52,
            title = "The sacred fire and the Fire Chalices.",
            category = "MAIN QUEST / GLOBAL",
            giver = "Milten (Nordmar Monastery)",
            location = "Vengard monastery-related global chain",
            prerequisites = "Collect twelve UNBLESSED Fire Chalices and keep them instead of handing them to Grok.",
            summary = "The Fire Chalice storyline ultimately requires all chalices to be blessed in the sacred fire before they can restore individual paladins' magic. Track every chalice and do not lose or hand them away carelessly.",
            walkthroughSteps = listOf("Visit Milten at the Nordmar Monastery and discuss the Fire Chalices.", "Collect the complete set of twelve from holders across the world.", "Place the twelve chalices into the SACRED FIRE next to the Innos altar.", "Take all twelve Blessed Fire Chalices from the pedestals, then visit paladins such as Konrad and Karlen to restore their magic."),
            reward = "12,000 XP for blessing the chalices, plus separate paladin restoration quest rewards.",
            warnings = "Giving all twelve to Grok closes this route. Remember to TAKE the blessed chalices back out of the fire before leaving.",
            searchTags = listOf("The sacred fire and the Fire Chalices.", "Milten / Fire Mages", "Vengard monastery-related global chain", "MAIN QUEST / GLOBAL")
        ),
        Quest(
            id = "G3-P3-053",
            chapter = 3,
            playOrder = 53,
            title = "Report the situation to the king.",
            category = "SAFE",
            giver = "Vengard quest chain",
            location = "Vengard castle",
            prerequisites = "",
            summary = "After completing the requested military or story objective, return to Rhobar and report the outcome.",
            walkthroughSteps = listOf("Speak with Vengard quest chain and make sure all quest-related dialogue is exhausted. The objective is associated with Vengard castle. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "After completing the requested military or story objective, return to Rhobar and report the outcome.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "Always revisit Rhobar after major artifact or war milestones for new dialogue."),
            reward = "",
            warnings = "",
            searchTags = listOf("Report the situation to the king.", "Vengard quest chain", "Vengard castle", "SAFE")
        ),
        Quest(
            id = "G3-P3-054",
            chapter = 3,
            playOrder = 54,
            title = "Clear the approaches to the castle.",
            category = "SAFE",
            giver = "Vengard defenders",
            location = "Vengard",
            prerequisites = "",
            summary = "Eliminate the Orc groups blocking safe movement between the ruined city and the castle approaches.",
            walkthroughSteps = listOf("Speak with Vengard defenders and make sure all quest-related dialogue is exhausted. The objective is associated with Vengard. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "Eliminate the Orc groups blocking safe movement between the ruined city and the castle approaches.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "Fight in controlled groups; Vengard contains many tightly packed enemies."),
            reward = "",
            warnings = "",
            searchTags = listOf("Clear the approaches to the castle.", "Vengard defenders", "Vengard", "SAFE")
        ),
        Quest(
            id = "G3-P3-055",
            chapter = 3,
            playOrder = 55,
            title = "Gain access to Faring.",
            category = "SAFE",
            giver = "Faring guards",
            location = "Faring",
            prerequisites = "Enter Faring and speak with the guards about access.",
            summary = "Arrive at Faring and complete enough local mercenary/Orc tasks to earn permission to move beyond the lower settlement.",
            walkthroughSteps = listOf("Speak with Faring guards and make sure all quest-related dialogue is exhausted. The objective is associated with Faring. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "Arrive at Faring and complete enough local mercenary/Orc tasks to earn permission to move beyond the lower settlement.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "Faring uses layered access: lower village, castle and eventually the Nordmar pass."),
            reward = "",
            warnings = "Local Faring access and entry to the Orc leader Kan's inner fortress are separate gates; Kan normally requires 75 ORC faction reputation.",
            searchTags = listOf("Gain access to Faring.", "Faring guards", "Faring", "SAFE")
        ),
        Quest(
            id = "G3-P3-056",
            chapter = 3,
            playOrder = 56,
            title = "Earn the right to enter Faring castle.",
            category = "SAFE",
            giver = "Faring Orcs / mercenaries",
            location = "Faring",
            prerequisites = "Earn 75 global Orc faction reputation to gain Kan's inner Faring fortress access.",
            summary = "Build reputation by completing hunting, arena and mercenary quests until the guards allow you into the castle area.",
            walkthroughSteps = listOf("Speak with Faring Orcs / mercenaries and make sure all quest-related dialogue is exhausted. The objective is associated with Faring. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "Build reputation by completing hunting, arena and mercenary quests until the guards allow you into the castle area.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "Do every harmless reputation quest before choosing faction-hostile objectives."),
            reward = "",
            warnings = "The 75 requirement is ORC FACTION reputation, not simply Faring's city reputation. Finish neutral quests before triggering global faction hostilities.",
            searchTags = listOf("Earn the right to enter Faring castle.", "Faring Orcs / mercenaries", "Faring", "SAFE")
        ),
        Quest(
            id = "G3-P3-057",
            chapter = 3,
            playOrder = 57,
            title = "Win the arena fights in Faring.",
            category = "SAFE",
            giver = "Faring arena fighters",
            location = "Faring arena",
            prerequisites = "",
            summary = "Challenge each available fighter and win without leaving the arena or killing your opponent. Complete the dialogue after each fight.",
            walkthroughSteps = listOf("Speak with Faring arena fighters and make sure all quest-related dialogue is exhausted. The objective is associated with Faring arena. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "Challenge each available fighter and win without leaving the arena or killing your opponent. Complete the dialogue after each fight.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "Arena wins are among the safest sources of Faring reputation."),
            reward = "",
            warnings = "",
            searchTags = listOf("Win the arena fights in Faring.", "Faring arena fighters", "Faring arena", "SAFE")
        ),
        Quest(
            id = "G3-P3-058",
            chapter = 3,
            playOrder = 58,
            title = "Defeat the arena champion.",
            category = "SAFE",
            giver = "Faring champion",
            location = "Faring arena",
            prerequisites = "",
            summary = "After the preliminary victories, challenge and defeat Faring's strongest arena opponent.",
            walkthroughSteps = listOf("Speak with Faring champion and make sure all quest-related dialogue is exhausted. The objective is associated with Faring arena. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "After the preliminary victories, challenge and defeat Faring's strongest arena opponent.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "Complete before any action that makes Faring hostile."),
            reward = "",
            warnings = "",
            searchTags = listOf("Defeat the arena champion.", "Faring champion", "Faring arena", "SAFE")
        ),
        Quest(
            id = "G3-P3-059",
            chapter = 3,
            playOrder = 59,
            title = "Hunt with Wilson.",
            category = "SAFE",
            giver = "Wilson",
            location = "Faring wilderness",
            prerequisites = "",
            summary = "Meet hunter Wilson and accompany him on his hunting objective. Stay close enough that his AI continues along the route and help kill the target animals.",
            walkthroughSteps = listOf("Speak with Wilson and make sure all quest-related dialogue is exhausted. The objective is associated with Faring wilderness. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "Meet hunter Wilson and accompany him on his hunting objective. Stay close enough that his AI continues along the route and help kill the target animals.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "Hunting quests are useful for both reputation and learning the route toward Nordmar."),
            reward = "",
            warnings = "",
            searchTags = listOf("Hunt with Wilson.", "Wilson", "Faring wilderness", "SAFE")
        ),
        Quest(
            id = "G3-P3-060",
            chapter = 3,
            playOrder = 60,
            title = "Bring Wilson the required pelts.",
            category = "SAFE",
            giver = "Wilson",
            location = "Faring",
            prerequisites = "",
            summary = "Collect the pelts Wilson requests and return them to him.",
            walkthroughSteps = listOf("Speak with Wilson and make sure all quest-related dialogue is exhausted. The objective is associated with Faring. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "Collect the pelts Wilson requests and return them to him.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "Skin Animals is highly useful here."),
            reward = "",
            warnings = "",
            searchTags = listOf("Bring Wilson the required pelts.", "Wilson", "Faring", "SAFE")
        ),
        Quest(
            id = "G3-P3-061",
            chapter = 3,
            playOrder = 61,
            title = "Kill the Three Trolls near Faring",
            category = "SAFE",
            giver = "Zakosh (Faring smith)",
            location = "Faring/Nordmar approach",
            prerequisites = "Speak to Zakosh about trolls near Tippler's hut.",
            summary = "Locate the trolls in the mountains near Faring and kill the designated group. Use terrain and ranged attacks if melee is too dangerous.",
            walkthroughSteps = listOf("Talk to smith Zakosh in Faring and take the three-troll contract.", "Find Mitch, a mercenary trying to do the same hunt, and offer to cooperate.", "Go to the hill near Tippler's hut and kill THREE trolls, protecting Mitch.", "Report to Zakosh; finish Mitch's separate helper escort if offered."),
            reward = "2,500 XP and +12 Faring reputation for the troll contract; Mitch's assistance adds 500 XP and +4 Faring.",
            warnings = "These are the three trolls by TIPPLER's hut; do not attack random trolls elsewhere.",
            searchTags = listOf("Hunt the dangerous trolls near Faring.", "Faring hunter", "Faring/Nordmar approach", "SAFE")
        ),
        Quest(
            id = "G3-P3-062",
            chapter = 3,
            playOrder = 62,
            title = "Kill the goblins in the caves near Faring.",
            category = "SAFE",
            giver = "Tippler (Faring brewer)",
            location = "Caves near Faring",
            prerequisites = "Find Tippler's house on the outskirts of Faring and ask about ancient ruins.",
            summary = "Explore the nearby caves and kill the goblins occupying them. Search every branch before reporting back.",
            walkthroughSteps = listOf("Ask Tippler about the goblins in the nearby ancient ruins.", "Travel to the hillside toward Vengard near Tippler's house.", "Kill the goblins in the ruins, avoiding stronger monsters nearby.", "Return to Tippler."),
            reward = "1,000 XP, +4 Faring reputation and +1 Hunting.",
            warnings = "The classic guide notes Tippler sometimes fails to offer this quest at all in some builds.",
            searchTags = listOf("Kill the goblins in the caves near Faring.", "Faring quest giver", "Caves near Faring", "SAFE")
        ),
        Quest(
            id = "G3-P3-063",
            chapter = 3,
            playOrder = 63,
            title = "Distribute Booze to the Orcs",
            category = "SAFE",
            giver = "Flint (Faring innkeeper)",
            location = "Faring",
            prerequisites = "Ask Flint in Faring how to impress its Orc guards.",
            summary = "Acquire the requested booze and deliver it to the mercenary quest giver.",
            walkthroughSteps = listOf("Speak with Flint at Faring's inn; he suggests supplying important Orcs with drinks.", "Bring the booze to GOROK, MOJOK and GNAR.", "Talk to each guard to register his delivery, then return to Flint."),
            reward = "1,500 XP and +12 Faring reputation.",
            warnings = "Three named recipients: Gorok, Mojok and Gnar; Mojok may also demand two Nordmar Nogginfog bottles separately.",
            searchTags = listOf("Bring booze to the mercenaries.", "Faring mercenary", "Faring", "SAFE")
        ),
        Quest(
            id = "G3-P3-064",
            chapter = 3,
            playOrder = 64,
            title = "The Hunters of Faring",
            category = "SAFE",
            giver = "Wilson and Tom (Faring hunters)",
            location = "Faring",
            prerequisites = "Ask Wilson or Tom how to be accepted by Faring hunters.",
            summary = "Meet the hunters and complete their introductory dialogue/tasks to establish yourself with the hunting group.",
            walkthroughSteps = listOf("Meet hunters Wilson and Tom in Faring.", "Go lurker hunting with Wilson and finish his nine-lurker objective.", "Sell Wilson's provided shadowbeast skin to Gnar, then honestly report the price you received.", "Complete their follow-up conversations until the hunters recognize you as one of them; this enables the Nordmar pass."),
            reward = "2,500 XP and +4 Faring reputation for hunter recognition.",
            warnings = "Do not lie to Wilson about the 400-gold payment from Gnar; lying can block hunter recognition.",
            searchTags = listOf("The hunters of Faring.", "Faring hunting camp", "Faring", "SAFE")
        ),
        Quest(
            id = "G3-P3-065",
            chapter = 3,
            playOrder = 65,
            title = "Follow Lars to the Nordmar Pass",
            category = "SAFE / CROSS-REGION",
            giver = "Lars (freed Nordmarian from Silden)",
            location = "Faring → Nordmar",
            prerequisites = "Free Lars in Silden and agree to follow him to the pass.",
            summary = "After earning sufficient standing/access, pass through the guarded northern route beyond Faring and enter Nordmar.",
            walkthroughSteps = listOf("Buy Lars out of slavery in Silden from Zapotek.", "Ask him to guide you to the Nordmar pass.", "Follow him up the road from Silden until he reaches the snowbound crossing.", "Protect Lars and complete his arrival dialogue."),
            reward = "1,500 XP and +2 Nordmar reputation.",
            warnings = "Same escorted Nordmarian quest referenced in G3-P3-040; not a separate Faring mission. Faring hunters provide an alternative pass-access path.",
            searchTags = listOf("Take the pass to Nordmar.", "Faring guards", "Faring → Nordmar", "SAFE / CROSS-REGION")
        ),
        Quest(
            id = "G3-P3-066",
            chapter = 3,
            playOrder = 66,
            title = "A message for the Orcs in Nordmar.",
            category = "SAFE / CROSS-REGION",
            giver = "Faring Orc quest chain",
            location = "Faring → Nordmar",
            prerequisites = "",
            summary = "Carry the designated message or package through the pass and keep it until you reach the correct Orc contact in Nordmar.",
            walkthroughSteps = listOf("Speak with Faring Orc quest chain and make sure all quest-related dialogue is exhausted. The objective is associated with Faring → Nordmar. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "Carry the designated message or package through the pass and keep it until you reach the correct Orc contact in Nordmar.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "Leave this active when Part III ends; it belongs to the transition north."),
            reward = "",
            warnings = "",
            searchTags = listOf("A message for the Orcs in Nordmar.", "Faring Orc quest chain", "Faring → Nordmar", "SAFE / CROSS-REGION")
        ),
        Quest(
            id = "G3-P3-067",
            chapter = 3,
            playOrder = 67,
            title = "The ancestor tomb information.",
            category = "SAFE / CROSS-REGION",
            giver = "Faring/Nordmar quest chain",
            location = "Faring",
            prerequisites = "",
            summary = "Speak with the relevant Orcs/hunters about Nordmar's ancestor tombs and retain the information for the northern quest line.",
            walkthroughSteps = listOf("Speak with Faring/Nordmar quest chain and make sure all quest-related dialogue is exhausted. The objective is associated with Faring. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "Speak with the relevant Orcs/hunters about Nordmar's ancestor tombs and retain the information for the northern quest line.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "Do not attempt to solve the tomb network from Faring; it belongs in the Nordmar Part."),
            reward = "",
            warnings = "",
            searchTags = listOf("The ancestor tomb information.", "Faring/Nordmar quest chain", "Faring", "SAFE / CROSS-REGION")
        ),
        Quest(
            id = "G3-P3-068",
            chapter = 3,
            playOrder = 68,
            title = "Gain the Orc leaders' trust.",
            category = "CHOICE — ORC",
            giver = "Faring leadership",
            location = "Faring",
            prerequisites = "Help Faring's Orcs and reach the reputation gate to Kan's castle.",
            summary = "Complete the reputation and service objectives needed to speak with higher-ranking Orcs in Faring.",
            walkthroughSteps = listOf("Speak with Faring leadership and make sure all quest-related dialogue is exhausted. The objective is associated with Faring. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "Complete the reputation and service objectives needed to speak with higher-ranking Orcs in Faring.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "You can gain access without immediately destroying Rebel settlements; postpone destructive proof-of-loyalty quests."),
            reward = "",
            warnings = "Meeting Kan and completing his Orc-faction demands is optional and may conflict with Rebel story goals.",
            searchTags = listOf("Gain the Orc leaders' trust.", "Faring leadership", "Faring", "CHOICE — ORC")
        ),
        Quest(
            id = "G3-P3-069",
            chapter = 3,
            playOrder = 69,
            title = "Destroy the rebels connected to Faring.",
            category = "DEFER — ORC PATH",
            giver = "Orc leadership",
            location = "Faring region",
            prerequisites = "Orc-aligned route; receive a contract against the Rebel camps associated with Faring.",
            summary = "If following the Orc route, eliminate the designated Rebel forces and report back to Faring's leadership.",
            walkthroughSteps = listOf("Speak with Orc leadership and make sure all quest-related dialogue is exhausted. The objective is associated with Faring region. Use the surrounding roads, named camps and landmarks rather than cutting blindly across hostile terrain.", "If following the Orc route, eliminate the designated Rebel forces and report back to Faring's leadership.", "Once the stated objective is complete, return to the quest giver or named destination and exhaust the new dialogue. If the quest does not complete, check for a missing target, uncollected quest item, surviving enemy or unfinished conversation.", "Finish all neutral and Rebel-dependent content first."),
            reward = "",
            warnings = "Destroying Rebel hubs closes their recruitments and merchants. Save before attacking any camp and finish paladin/Fire Chalice rewards.",
            searchTags = listOf("Destroy the rebels connected to Faring.", "Orc leadership", "Faring region", "DEFER — ORC PATH")
        ),
        Quest(
            id = "G3-P3-070",
            chapter = 3,
            playOrder = 70,
            title = "Liberate Faring from the orcs!",
            category = "DEFER — REBEL PATH",
            giver = "Rebel liberation / Innos endgame",
            location = "Faring",
            prerequisites = "Complete desired Faring training and Orc quests; choose Innos/Rebel liberation route.",
            summary = "After completing every desired Faring quest and using the pass as needed, attack the Orc occupation and defeat enough defenders for the settlement to fall.",
            walkthroughSteps = listOf("Finish Faring's peaceful hunter, arena, smithing and Orc guard content.", "If following the late-game Innos route, return to Faring to expel its Orc rulers.", "Fight through the heavily defended streets and castle, facing powerful arena warriors as well.", "Defeat enough defenders to complete the liberation."),
            reward = "10,000 XP and +5 Rebel reputation.",
            warnings = "Faring liberation is difficult and hostile to Orc factions; unlike Silden, no prepared Rebel uprising army is available.",
            searchTags = listOf("Liberate Faring from the orcs!", "Rebel route / player action", "Faring", "DEFER — REBEL PATH")
        ),
    )
}
