package com.sliverzfx.gothicquest

object NewBalanceChapter3Part2 {
    val quests = listOf(
        Quest(
            id = "CH3-043",
            chapter = 3,
            playOrder = 43,
            title = "A Huge Ruby for Cassia",
            category = "Thieves' Guild",
            giver = "Local quest giver in Thieves' Guild",
            location = "Thieves' Guild",
            prerequisites = "Chapter 3; complete earlier quests in the same area/faction if the dialogue is not yet available.",
            summary = "Core objective: secure a huge ruby and get it to Cassia.",
            walkthroughSteps = listOf("Core objective: secure a huge ruby and get it to Cassia. Start this quest in Thieves' Guild and exhaust the new dialogue connected with \"A Huge Ruby for Cassia\". Speak with the relevant contact in Thieves' Guild to confirm the requested amount or exact variant. Obtain \"A Huge Ruby\" by gathering, buying, crafting, looting or completing the linked prerequisite task, then bring it to Cassia. If the quest does not close immediately, return to the NPC who originally sent you."),
            reward = "Reward varies by quest/build; exact values should be taken from the current in-game dialogue or source page.",
            warnings = "Do not sell unique named items, special ingredients, quest letters or unusual trophies until the related quest chain is finished.",
            searchTags = listOf("a huge ruby for cassia", "thieves' guild", "local quest giver in thieves' guild")
        ),
        Quest(
            id = "CH3-044",
            chapter = 3,
            playOrder = 44,
            title = "Antiques",
            category = "Merchants' Guild",
            giver = "Local quest giver in Merchants' Guild",
            location = "Merchants' Guild",
            prerequisites = "Chapter 3; complete earlier quests in the same area/faction if the dialogue is not yet available.",
            summary = "Start this quest in Merchants' Guild and exhaust the new dialogue connected with \"Antiques\".",
            walkthroughSteps = listOf("Start this quest in Merchants' Guild and exhaust the new dialogue connected with \"Antiques\". Follow the dialogue chain for \"Antiques\" in Merchants' Guild. Speak to the quest giver and every newly mentioned NPC, inspect the locations or objects added to the journal, and complete the objective that causes the journal to update. Return to the relevant giver/contact after each major update; if no new dialogue appears, complete earlier quests in the same area or faction and check again."),
            reward = "Reward varies by quest/build; exact values should be taken from the current in-game dialogue or source page.",
            warnings = "This is an index-guided quick solution. Exact item counts, coordinates and reward values can differ with New Balance updates; use the linked source record when a build-specific detail matters.",
            searchTags = listOf("antiques", "merchants' guild", "local quest giver in merchants' guild")
        ),
        Quest(
            id = "CH3-045",
            chapter = 3,
            playOrder = 45,
            title = "Gomez's Curse",
            category = "Merchants' Guild",
            giver = "Local quest giver in Merchants' Guild",
            location = "Merchants' Guild",
            prerequisites = "Chapter 3; complete earlier quests in the same area/faction if the dialogue is not yet available.",
            summary = "Start this quest in Merchants' Guild and exhaust the new dialogue connected with \"Gomez's Curse\".",
            walkthroughSteps = listOf("Start this quest in Merchants' Guild and exhaust the new dialogue connected with \"Gomez's Curse\". Follow the dialogue chain for \"Gomez's Curse\" in Merchants' Guild. Speak to the quest giver and every newly mentioned NPC, inspect the locations or objects added to the journal, and complete the objective that causes the journal to update. Return to the relevant giver/contact after each major update; if no new dialogue appears, complete earlier quests in the same area or faction and check again."),
            reward = "Reward varies by quest/build; exact values should be taken from the current in-game dialogue or source page.",
            warnings = "This is an index-guided quick solution. Exact item counts, coordinates and reward values can differ with New Balance updates; use the linked source record when a build-specific detail matters.",
            searchTags = listOf("gomez's curse", "merchants' guild", "local quest giver in merchants' guild")
        ),
        Quest(
            id = "CH3-046",
            chapter = 3,
            playOrder = 46,
            title = "Black Brandy",
            category = "Merchants' Guild",
            giver = "Local quest giver in Merchants' Guild",
            location = "Merchants' Guild",
            prerequisites = "Chapter 3; complete earlier quests in the same area/faction if the dialogue is not yet available.",
            summary = "Start this quest in Merchants' Guild and exhaust the new dialogue connected with \"Black Brandy\".",
            walkthroughSteps = listOf("Start this quest in Merchants' Guild and exhaust the new dialogue connected with \"Black Brandy\". Follow the dialogue chain for \"Black Brandy\" in Merchants' Guild. Speak to the quest giver and every newly mentioned NPC, inspect the locations or objects added to the journal, and complete the objective that causes the journal to update. Return to the relevant giver/contact after each major update; if no new dialogue appears, complete earlier quests in the same area or faction and check again."),
            reward = "Reward varies by quest/build; exact values should be taken from the current in-game dialogue or source page.",
            warnings = "This is an index-guided quick solution. Exact item counts, coordinates and reward values can differ with New Balance updates; use the linked source record when a build-specific detail matters.",
            searchTags = listOf("black brandy", "merchants' guild", "local quest giver in merchants' guild")
        ),
        Quest(
            id = "CH3-047",
            chapter = 3,
            playOrder = 47,
            title = "The Assistant",
            category = "Merchants' Guild",
            giver = "Local quest giver in Merchants' Guild",
            location = "Merchants' Guild",
            prerequisites = "Chapter 3; complete earlier quests in the same area/faction if the dialogue is not yet available.",
            summary = "Start this quest in Merchants' Guild and exhaust the new dialogue connected with \"The Assistant\".",
            walkthroughSteps = listOf("Start this quest in Merchants' Guild and exhaust the new dialogue connected with \"The Assistant\". Follow the dialogue chain for \"The Assistant\" in Merchants' Guild. Speak to the quest giver and every newly mentioned NPC, inspect the locations or objects added to the journal, and complete the objective that causes the journal to update. Return to the relevant giver/contact after each major update; if no new dialogue appears, complete earlier quests in the same area or faction and check again."),
            reward = "Reward varies by quest/build; exact values should be taken from the current in-game dialogue or source page.",
            warnings = "This is an index-guided quick solution. Exact item counts, coordinates and reward values can differ with New Balance updates; use the linked source record when a build-specific detail matters.",
            searchTags = listOf("the assistant", "merchants' guild", "local quest giver in merchants' guild")
        ),
        Quest(
            id = "CH3-048",
            chapter = 3,
            playOrder = 48,
            title = "Helping Sarah",
            category = "Merchants' Guild",
            giver = "Local quest giver in Merchants' Guild",
            location = "Merchants' Guild",
            prerequisites = "Chapter 3; complete earlier quests in the same area/faction if the dialogue is not yet available.",
            summary = "Start this quest in Merchants' Guild and exhaust the new dialogue connected with \"Helping Sarah\".",
            walkthroughSteps = listOf("Start this quest in Merchants' Guild and exhaust the new dialogue connected with \"Helping Sarah\". Follow the dialogue chain for \"Helping Sarah\" in Merchants' Guild. Speak to the quest giver and every newly mentioned NPC, inspect the locations or objects added to the journal, and complete the objective that causes the journal to update. Return to the relevant giver/contact after each major update; if no new dialogue appears, complete earlier quests in the same area or faction and check again."),
            reward = "Reward varies by quest/build; exact values should be taken from the current in-game dialogue or source page.",
            warnings = "This is an index-guided quick solution. Exact item counts, coordinates and reward values can differ with New Balance updates; use the linked source record when a build-specific detail matters.",
            searchTags = listOf("helping sarah", "merchants' guild", "local quest giver in merchants' guild")
        ),
        Quest(
            id = "CH3-049",
            chapter = 3,
            playOrder = 49,
            title = "Food for Sarah",
            category = "Merchants' Guild",
            giver = "Local quest giver in Merchants' Guild",
            location = "Merchants' Guild",
            prerequisites = "Chapter 3; complete earlier quests in the same area/faction if the dialogue is not yet available.",
            summary = "Core objective: secure food and get it to Sarah.",
            walkthroughSteps = listOf("Core objective: secure food and get it to Sarah. Start this quest in Merchants' Guild and exhaust the new dialogue connected with \"Food for Sarah\". Speak with the relevant contact in Merchants' Guild to confirm the requested amount or exact variant. Obtain \"Food\" by gathering, buying, crafting, looting or completing the linked prerequisite task, then bring it to Sarah. If the quest does not close immediately, return to the NPC who originally sent you."),
            reward = "Reward varies by quest/build; exact values should be taken from the current in-game dialogue or source page.",
            warnings = "Do not sell unique named items, special ingredients, quest letters or unusual trophies until the related quest chain is finished.",
            searchTags = listOf("food for sarah", "merchants' guild", "local quest giver in merchants' guild")
        ),
        Quest(
            id = "CH3-050",
            chapter = 3,
            playOrder = 50,
            title = "Family Ring",
            category = "Merchants' Guild",
            giver = "Local quest giver in Merchants' Guild",
            location = "Merchants' Guild",
            prerequisites = "Chapter 3; complete earlier quests in the same area/faction if the dialogue is not yet available.",
            summary = "Start this quest in Merchants' Guild and exhaust the new dialogue connected with \"Family Ring\".",
            walkthroughSteps = listOf("Start this quest in Merchants' Guild and exhaust the new dialogue connected with \"Family Ring\". Ask the quest giver for all available clues, then search Merchants' Guild and the locations mentioned in the journal for the named object connected with \"Family Ring\". Check corpses, locked chests, shelves, caves and camp interiors, and read any notes you find because they often advance the objective. Take the item to the intended owner/quest giver and continue the dialogue until the journal closes."),
            reward = "Reward varies by quest/build; exact values should be taken from the current in-game dialogue or source page.",
            warnings = "Unique equipment can be tied to several quests. Do not sell, forge away or discard it before checking all related dialogue.",
            searchTags = listOf("family ring", "merchants' guild", "local quest giver in merchants' guild")
        ),
        Quest(
            id = "CH3-051",
            chapter = 3,
            playOrder = 51,
            title = "Sarah's Debts",
            category = "Merchants' Guild",
            giver = "Local quest giver in Merchants' Guild",
            location = "Merchants' Guild",
            prerequisites = "Chapter 3; complete earlier quests in the same area/faction if the dialogue is not yet available.",
            summary = "Start this quest in Merchants' Guild and exhaust the new dialogue connected with \"Sarah's Debts\".",
            walkthroughSteps = listOf("Start this quest in Merchants' Guild and exhaust the new dialogue connected with \"Sarah's Debts\". Speak with all merchants/debtors named by the quest and use the available dialogue, payment or persuasion options. Collect the money, goods or signed agreement required by \"Sarah's Debts\", then return it to the quest giver in Merchants' Guild. If you are offered several settlement choices, resolve the related side quests first so you do not lose a better outcome."),
            reward = "Reward varies by quest/build; exact values should be taken from the current in-game dialogue or source page.",
            warnings = "Commercial quests often branch according to who you support. Save before handing over unique ledgers, contracts or large payments.",
            searchTags = listOf("sarah's debts", "merchants' guild", "local quest giver in merchants' guild")
        ),
        Quest(
            id = "CH3-052",
            chapter = 3,
            playOrder = 52,
            title = "Missing Novices",
            category = "Masyaf Brotherhood - Main",
            giver = "Local quest giver in Masyaf Brotherhood - Main",
            location = "Masyaf Brotherhood - Main",
            prerequisites = "Chapter 3; complete earlier quests in the same area/faction if the dialogue is not yet available.",
            summary = "Treat Masyaf as a chained storyline: exhaust dialogue with the local leaders and slaves before killing or freeing anyone, because later quests depend on earlier outcomes.",
            walkthroughSteps = listOf("Treat Masyaf as a chained storyline: exhaust dialogue with the local leaders and slaves before killing or freeing anyone, because later quests depend on earlier outcomes. Start this quest in Masyaf Brotherhood - Main and exhaust the new dialogue connected with \"Missing Novices\". Begin by questioning the NPCs tied to Masyaf Brotherhood - Main and follow every new name or location added to the journal. Search the relevant nearby camps, caves, roads and interiors for the missing person, item or clue named by \"Missing Novices\". Read notes and letters you find, then return to the original contact after the journal updates; some investigations require reporting to more than one NPC."),
            reward = "Reward varies by quest/build; exact values should be taken from the current in-game dialogue or source page.",
            warnings = "Do not kill neutral or named NPCs involved in the investigation until you have exhausted their dialogue; New Balance often uses them in follow-up quests.",
            searchTags = listOf("missing novices", "masyaf brotherhood - main", "local quest giver in masyaf brotherhood - main")
        ),
        Quest(
            id = "CH3-053",
            chapter = 3,
            playOrder = 53,
            title = "Mentor for the Guards",
            category = "Masyaf Brotherhood - Main",
            giver = "Local quest giver in Masyaf Brotherhood - Main",
            location = "Masyaf Brotherhood - Main",
            prerequisites = "Chapter 3; complete earlier quests in the same area/faction if the dialogue is not yet available.",
            summary = "Core objective: secure mentor and get it to the Guards.",
            walkthroughSteps = listOf("Core objective: secure mentor and get it to the Guards. Treat Masyaf as a chained storyline: exhaust dialogue with the local leaders and slaves before killing or freeing anyone, because later quests depend on earlier outcomes. Start this quest in Masyaf Brotherhood - Main and exhaust the new dialogue connected with \"Mentor for the Guards\". Speak with the relevant contact in Masyaf Brotherhood - Main to confirm the requested amount or exact variant. Obtain \"Mentor\" by gathering, buying, crafting, looting or completing the linked prerequisite task, then bring it to the Guards. If the quest does not close immediately, return to the NPC who originally sent you."),
            reward = "Reward varies by quest/build; exact values should be taken from the current in-game dialogue or source page.",
            warnings = "Do not sell unique named items, special ingredients, quest letters or unusual trophies until the related quest chain is finished.",
            searchTags = listOf("mentor for the guards", "masyaf brotherhood - main", "local quest giver in masyaf brotherhood - main")
        ),
        Quest(
            id = "CH3-054",
            chapter = 3,
            playOrder = 54,
            title = "Tirax's Nerves",
            category = "Masyaf Brotherhood - Main",
            giver = "Local quest giver in Masyaf Brotherhood - Main",
            location = "Masyaf Brotherhood - Main",
            prerequisites = "Chapter 3; complete earlier quests in the same area/faction if the dialogue is not yet available.",
            summary = "Treat Masyaf as a chained storyline: exhaust dialogue with the local leaders and slaves before killing or freeing anyone, because later quests depend on earlier outcomes.",
            walkthroughSteps = listOf("Treat Masyaf as a chained storyline: exhaust dialogue with the local leaders and slaves before killing or freeing anyone, because later quests depend on earlier outcomes. Start this quest in Masyaf Brotherhood - Main and exhaust the new dialogue connected with \"Tirax's Nerves\". Follow the dialogue chain for \"Tirax's Nerves\" in Masyaf Brotherhood - Main. Speak to the quest giver and every newly mentioned NPC, inspect the locations or objects added to the journal, and complete the objective that causes the journal to update. Return to the relevant giver/contact after each major update; if no new dialogue appears, complete earlier quests in the same area or faction and check again."),
            reward = "Reward varies by quest/build; exact values should be taken from the current in-game dialogue or source page.",
            warnings = "This is an index-guided quick solution. Exact item counts, coordinates and reward values can differ with New Balance updates; use the linked source record when a build-specific detail matters.",
            searchTags = listOf("tirax's nerves", "masyaf brotherhood - main", "local quest giver in masyaf brotherhood - main")
        ),
        Quest(
            id = "CH3-055",
            chapter = 3,
            playOrder = 55,
            title = "Swampweed for Balam",
            category = "Masyaf Brotherhood - Gatherers",
            giver = "Local quest giver in Masyaf Brotherhood - Gatherers",
            location = "Masyaf Brotherhood - Gatherers",
            prerequisites = "Chapter 3; complete earlier quests in the same area/faction if the dialogue is not yet available.",
            summary = "Core objective: secure swampweed and get it to Balam.",
            walkthroughSteps = listOf("Core objective: secure swampweed and get it to Balam. Treat Masyaf as a chained storyline: exhaust dialogue with the local leaders and slaves before killing or freeing anyone, because later quests depend on earlier outcomes. Start this quest in Masyaf Brotherhood - Gatherers and exhaust the new dialogue connected with \"Swampweed for Balam\". Speak with the relevant contact in Masyaf Brotherhood - Gatherers to confirm the requested amount or exact variant. Obtain \"Swampweed\" by gathering, buying, crafting, looting or completing the linked prerequisite task, then bring it to Balam. If the quest does not close immediately, return to the NPC who originally sent you."),
            reward = "Reward varies by quest/build; exact values should be taken from the current in-game dialogue or source page.",
            warnings = "Do not sell unique named items, special ingredients, quest letters or unusual trophies until the related quest chain is finished.",
            searchTags = listOf("swampweed for balam", "masyaf brotherhood - gatherers", "local quest giver in masyaf brotherhood - gatherers")
        ),
        Quest(
            id = "CH3-056",
            chapter = 3,
            playOrder = 56,
            title = "Noises in the Night",
            category = "Masyaf Brotherhood - Gatherers",
            giver = "Local quest giver in Masyaf Brotherhood - Gatherers",
            location = "Masyaf Brotherhood - Gatherers",
            prerequisites = "Chapter 3; complete earlier quests in the same area/faction if the dialogue is not yet available.",
            summary = "Treat Masyaf as a chained storyline: exhaust dialogue with the local leaders and slaves before killing or freeing anyone, because later quests depend on earlier outcomes.",
            walkthroughSteps = listOf("Treat Masyaf as a chained storyline: exhaust dialogue with the local leaders and slaves before killing or freeing anyone, because later quests depend on earlier outcomes. Start this quest in Masyaf Brotherhood - Gatherers and exhaust the new dialogue connected with \"Noises in the Night\". Follow the dialogue chain for \"Noises in the Night\" in Masyaf Brotherhood - Gatherers. Speak to the quest giver and every newly mentioned NPC, inspect the locations or objects added to the journal, and complete the objective that causes the journal to update. Return to the relevant giver/contact after each major update; if no new dialogue appears, complete earlier quests in the same area or faction and check again."),
            reward = "Reward varies by quest/build; exact values should be taken from the current in-game dialogue or source page.",
            warnings = "This is an index-guided quick solution. Exact item counts, coordinates and reward values can differ with New Balance updates; use the linked source record when a build-specific detail matters.",
            searchTags = listOf("noises in the night", "masyaf brotherhood - gatherers", "local quest giver in masyaf brotherhood - gatherers")
        ),
        Quest(
            id = "CH3-057",
            chapter = 3,
            playOrder = 57,
            title = "Food for the Gatherers",
            category = "Masyaf Brotherhood - Gatherers",
            giver = "Local quest giver in Masyaf Brotherhood - Gatherers",
            location = "Masyaf Brotherhood - Gatherers",
            prerequisites = "Chapter 3; complete earlier quests in the same area/faction if the dialogue is not yet available.",
            summary = "Core objective: secure food and get it to the Gatherers.",
            walkthroughSteps = listOf("Core objective: secure food and get it to the Gatherers. Treat Masyaf as a chained storyline: exhaust dialogue with the local leaders and slaves before killing or freeing anyone, because later quests depend on earlier outcomes. Start this quest in Masyaf Brotherhood - Gatherers and exhaust the new dialogue connected with \"Food for the Gatherers\". Speak with the relevant contact in Masyaf Brotherhood - Gatherers to confirm the requested amount or exact variant. Obtain \"Food\" by gathering, buying, crafting, looting or completing the linked prerequisite task, then bring it to the Gatherers. If the quest does not close immediately, return to the NPC who originally sent you."),
            reward = "Reward varies by quest/build; exact values should be taken from the current in-game dialogue or source page.",
            warnings = "Do not sell unique named items, special ingredients, quest letters or unusual trophies until the related quest chain is finished.",
            searchTags = listOf("food for the gatherers", "masyaf brotherhood - gatherers", "local quest giver in masyaf brotherhood - gatherers")
        ),
        Quest(
            id = "CH3-058",
            chapter = 3,
            playOrder = 58,
            title = "Sheepskins for the Guards",
            category = "Masyaf Brotherhood - Gatherers",
            giver = "Local quest giver in Masyaf Brotherhood - Gatherers",
            location = "Masyaf Brotherhood - Gatherers",
            prerequisites = "Chapter 3; complete earlier quests in the same area/faction if the dialogue is not yet available.",
            summary = "Core objective: secure sheepskins and get it to the Guards.",
            walkthroughSteps = listOf("Core objective: secure sheepskins and get it to the Guards. Treat Masyaf as a chained storyline: exhaust dialogue with the local leaders and slaves before killing or freeing anyone, because later quests depend on earlier outcomes. Start this quest in Masyaf Brotherhood - Gatherers and exhaust the new dialogue connected with \"Sheepskins for the Guards\". Speak with the relevant contact in Masyaf Brotherhood - Gatherers to confirm the requested amount or exact variant. Obtain \"Sheepskins\" by gathering, buying, crafting, looting or completing the linked prerequisite task, then bring it to the Guards. If the quest does not close immediately, return to the NPC who originally sent you."),
            reward = "Reward varies by quest/build; exact values should be taken from the current in-game dialogue or source page.",
            warnings = "Do not sell unique named items, special ingredients, quest letters or unusual trophies until the related quest chain is finished.",
            searchTags = listOf("sheepskins for the guards", "masyaf brotherhood - gatherers", "local quest giver in masyaf brotherhood - gatherers")
        ),
        Quest(
            id = "CH3-059",
            chapter = 3,
            playOrder = 59,
            title = "Escort Gonzales to the Pass",
            category = "Masyaf Brotherhood - Gatherers",
            giver = "Local quest giver in Masyaf Brotherhood - Gatherers",
            location = "Masyaf Brotherhood - Gatherers",
            prerequisites = "Chapter 3; complete earlier quests in the same area/faction if the dialogue is not yet available.",
            summary = "Core objective: get the relevant NPC safely to the destination and trigger the arrival dialogue.",
            walkthroughSteps = listOf("Core objective: get the relevant NPC safely to the destination and trigger the arrival dialogue. Treat Masyaf as a chained storyline: exhaust dialogue with the local leaders and slaves before killing or freeing anyone, because later quests depend on earlier outcomes. Start this quest in Masyaf Brotherhood - Gatherers and exhaust the new dialogue connected with \"Escort Gonzales to the Pass\". Speak to the person who needs to travel, clear the route before starting the escort if possible, then accompany them through Masyaf Brotherhood - Gatherers to the destination named by the quest. Stay close enough for escort dialogue/triggers to fire and deal with enemies that block the route. At the destination, speak with the escorted NPC and then report back if the journal remains open."),
            reward = "Reward varies by quest/build; exact values should be taken from the current in-game dialogue or source page.",
            warnings = "Save before starting long escorts. If the NPC stops, clear nearby enemies, move back toward them, and trigger any pending dialogue before continuing.",
            searchTags = listOf("escort gonzales to the pass", "masyaf brotherhood - gatherers", "local quest giver in masyaf brotherhood - gatherers")
        ),
        Quest(
            id = "CH3-060",
            chapter = 3,
            playOrder = 60,
            title = "One of Them",
            category = "Masyaf Brotherhood - Gatherers",
            giver = "Local quest giver in Masyaf Brotherhood - Gatherers",
            location = "Masyaf Brotherhood - Gatherers",
            prerequisites = "Chapter 3; complete earlier quests in the same area/faction if the dialogue is not yet available.",
            summary = "Treat Masyaf as a chained storyline: exhaust dialogue with the local leaders and slaves before killing or freeing anyone, because later quests depend on earlier outcomes.",
            walkthroughSteps = listOf("Treat Masyaf as a chained storyline: exhaust dialogue with the local leaders and slaves before killing or freeing anyone, because later quests depend on earlier outcomes. Start this quest in Masyaf Brotherhood - Gatherers and exhaust the new dialogue connected with \"One of Them\". Question the quest giver and every NPC they mention, then investigate the nearby location in Masyaf Brotherhood - Gatherers. Resolve the concrete cause behind \"One of Them\" - usually a person, creature, stolen item or dispute - and return once the journal records the result. If several dialogue solutions are offered, finish optional conversations before choosing the final resolution."),
            reward = "Reward varies by quest/build; exact values should be taken from the current in-game dialogue or source page.",
            warnings = "Many New Balance side quests chain into later content, so favor dialogue/investigation over immediately killing a named NPC.",
            searchTags = listOf("one of them", "masyaf brotherhood - gatherers", "local quest giver in masyaf brotherhood - gatherers")
        ),
        Quest(
            id = "CH3-061",
            chapter = 3,
            playOrder = 61,
            title = "Herb Gatherer",
            category = "Masyaf Brotherhood - Nrozas",
            giver = "Local quest giver in Masyaf Brotherhood - Nrozas",
            location = "Masyaf Brotherhood - Nrozas",
            prerequisites = "Chapter 3; complete earlier quests in the same area/faction if the dialogue is not yet available.",
            summary = "Treat Masyaf as a chained storyline: exhaust dialogue with the local leaders and slaves before killing or freeing anyone, because later quests depend on earlier outcomes.",
            walkthroughSteps = listOf("Treat Masyaf as a chained storyline: exhaust dialogue with the local leaders and slaves before killing or freeing anyone, because later quests depend on earlier outcomes. Start this quest in Masyaf Brotherhood - Nrozas and exhaust the new dialogue connected with \"Herb Gatherer\". Follow the dialogue chain for \"Herb Gatherer\" in Masyaf Brotherhood - Nrozas. Speak to the quest giver and every newly mentioned NPC, inspect the locations or objects added to the journal, and complete the objective that causes the journal to update. Return to the relevant giver/contact after each major update; if no new dialogue appears, complete earlier quests in the same area or faction and check again."),
            reward = "Reward varies by quest/build; exact values should be taken from the current in-game dialogue or source page.",
            warnings = "This is an index-guided quick solution. Exact item counts, coordinates and reward values can differ with New Balance updates; use the linked source record when a build-specific detail matters.",
            searchTags = listOf("herb gatherer", "masyaf brotherhood - nrozas", "local quest giver in masyaf brotherhood - nrozas")
        ),
        Quest(
            id = "CH3-062",
            chapter = 3,
            playOrder = 62,
            title = "Message to Osair",
            category = "Masyaf Brotherhood - Nrozas",
            giver = "Local quest giver in Masyaf Brotherhood - Nrozas",
            location = "Masyaf Brotherhood - Nrozas",
            prerequisites = "Chapter 3; complete earlier quests in the same area/faction if the dialogue is not yet available.",
            summary = "Treat Masyaf as a chained storyline: exhaust dialogue with the local leaders and slaves before killing or freeing anyone, because later quests depend on earlier outcomes.",
            walkthroughSteps = listOf("Treat Masyaf as a chained storyline: exhaust dialogue with the local leaders and slaves before killing or freeing anyone, because later quests depend on earlier outcomes. Start this quest in Masyaf Brotherhood - Nrozas and exhaust the new dialogue connected with \"Message to Osair\". Take the message, item or instructions from the quest giver in Masyaf Brotherhood - Nrozas. Find the named recipient or information source, exhaust the relevant dialogue and hand over any quest item when prompted. Then return to the original giver for the report-back stage; if a new name is added to the journal, follow that lead before returning."),
            reward = "Reward varies by quest/build; exact values should be taken from the current in-game dialogue or source page.",
            warnings = "Carry letters and packages until the journal explicitly confirms delivery; some chains use the same NPC again later.",
            searchTags = listOf("message to osair", "masyaf brotherhood - nrozas", "local quest giver in masyaf brotherhood - nrozas")
        ),
        Quest(
            id = "CH3-063",
            chapter = 3,
            playOrder = 63,
            title = "Unspoken Concession",
            category = "Masyaf Brotherhood - Nrozas",
            giver = "Local quest giver in Masyaf Brotherhood - Nrozas",
            location = "Masyaf Brotherhood - Nrozas",
            prerequisites = "Chapter 3; complete earlier quests in the same area/faction if the dialogue is not yet available.",
            summary = "Treat Masyaf as a chained storyline: exhaust dialogue with the local leaders and slaves before killing or freeing anyone, because later quests depend on earlier outcomes.",
            walkthroughSteps = listOf("Treat Masyaf as a chained storyline: exhaust dialogue with the local leaders and slaves before killing or freeing anyone, because later quests depend on earlier outcomes. Start this quest in Masyaf Brotherhood - Nrozas and exhaust the new dialogue connected with \"Unspoken Concession\". Follow the dialogue chain for \"Unspoken Concession\" in Masyaf Brotherhood - Nrozas. Speak to the quest giver and every newly mentioned NPC, inspect the locations or objects added to the journal, and complete the objective that causes the journal to update. Return to the relevant giver/contact after each major update; if no new dialogue appears, complete earlier quests in the same area or faction and check again."),
            reward = "Reward varies by quest/build; exact values should be taken from the current in-game dialogue or source page.",
            warnings = "This is an index-guided quick solution. Exact item counts, coordinates and reward values can differ with New Balance updates; use the linked source record when a build-specific detail matters.",
            searchTags = listOf("unspoken concession", "masyaf brotherhood - nrozas", "local quest giver in masyaf brotherhood - nrozas")
        ),
        Quest(
            id = "CH3-064",
            chapter = 3,
            playOrder = 64,
            title = "Ingredients for Nrozas",
            category = "Masyaf Brotherhood - Nrozas",
            giver = "Local quest giver in Masyaf Brotherhood - Nrozas",
            location = "Masyaf Brotherhood - Nrozas",
            prerequisites = "Chapter 3; complete earlier quests in the same area/faction if the dialogue is not yet available.",
            summary = "Core objective: secure ingredients and get it to Nrozas.",
            walkthroughSteps = listOf("Core objective: secure ingredients and get it to Nrozas. Treat Masyaf as a chained storyline: exhaust dialogue with the local leaders and slaves before killing or freeing anyone, because later quests depend on earlier outcomes. Start this quest in Masyaf Brotherhood - Nrozas and exhaust the new dialogue connected with \"Ingredients for Nrozas\". Speak with the relevant contact in Masyaf Brotherhood - Nrozas to confirm the requested amount or exact variant. Obtain \"Ingredients\" by gathering, buying, crafting, looting or completing the linked prerequisite task, then bring it to Nrozas. If the quest does not close immediately, return to the NPC who originally sent you."),
            reward = "Reward varies by quest/build; exact values should be taken from the current in-game dialogue or source page.",
            warnings = "Do not sell unique named items, special ingredients, quest letters or unusual trophies until the related quest chain is finished.",
            searchTags = listOf("ingredients for nrozas", "masyaf brotherhood - nrozas", "local quest giver in masyaf brotherhood - nrozas")
        ),
        Quest(
            id = "CH3-065",
            chapter = 3,
            playOrder = 65,
            title = "Pack of Black Glorks",
            category = "Masyaf Brotherhood - Osair",
            giver = "Local quest giver in Masyaf Brotherhood - Osair",
            location = "Masyaf Brotherhood - Osair",
            prerequisites = "Chapter 3; complete earlier quests in the same area/faction if the dialogue is not yet available.",
            summary = "Treat Masyaf as a chained storyline: exhaust dialogue with the local leaders and slaves before killing or freeing anyone, because later quests depend on earlier outcomes.",
            walkthroughSteps = listOf("Treat Masyaf as a chained storyline: exhaust dialogue with the local leaders and slaves before killing or freeing anyone, because later quests depend on earlier outcomes. Start this quest in Masyaf Brotherhood - Osair and exhaust the new dialogue connected with \"Pack of Black Glorks\". Get the target description from the quest giver, then travel through Masyaf Brotherhood - Osair to the marked or described hunting area. Defeat the enemies or named target associated with \"Pack of Black Glorks\", loot all bodies for proof/items, and search the immediate area for a journal-triggering object. Return to the quest giver and report the kill/clearing only after the objective counter or journal text has updated."),
            reward = "Reward varies by quest/build; exact values should be taken from the current in-game dialogue or source page.",
            warnings = "Named enemies frequently carry keys, notes or trophies used by another quest. Loot them before leaving the area.",
            searchTags = listOf("pack of black glorks", "masyaf brotherhood - osair", "local quest giver in masyaf brotherhood - osair")
        ),
        Quest(
            id = "CH3-066",
            chapter = 3,
            playOrder = 66,
            title = "The Conspiring Slave",
            category = "Masyaf Brotherhood - Osair",
            giver = "Local quest giver in Masyaf Brotherhood - Osair",
            location = "Masyaf Brotherhood - Osair",
            prerequisites = "Chapter 3; complete earlier quests in the same area/faction if the dialogue is not yet available.",
            summary = "Core objective: locate the named quest item (The Conspiring Slave) and return it to the NPC whose dialogue identifies it.",
            walkthroughSteps = listOf("Core objective: locate the named quest item (The Conspiring Slave) and return it to the NPC whose dialogue identifies it. Treat Masyaf as a chained storyline: exhaust dialogue with the local leaders and slaves before killing or freeing anyone, because later quests depend on earlier outcomes. Start this quest in Masyaf Brotherhood - Osair and exhaust the new dialogue connected with \"The Conspiring Slave\". Ask the quest giver for all available clues, then search Masyaf Brotherhood - Osair and the locations mentioned in the journal for the named object connected with \"The Conspiring Slave\". Check corpses, locked chests, shelves, caves and camp interiors, and read any notes you find because they often advance the objective. Take the item to the intended owner/quest giver and continue the dialogue until the journal closes."),
            reward = "Reward varies by quest/build; exact values should be taken from the current in-game dialogue or source page.",
            warnings = "Unique equipment can be tied to several quests. Do not sell, forge away or discard it before checking all related dialogue.",
            searchTags = listOf("the conspiring slave", "masyaf brotherhood - osair", "local quest giver in masyaf brotherhood - osair")
        ),
        Quest(
            id = "CH3-067",
            chapter = 3,
            playOrder = 67,
            title = "Weapon Bundles for Marius",
            category = "Masyaf Brotherhood - Osair",
            giver = "Local quest giver in Masyaf Brotherhood - Osair",
            location = "Masyaf Brotherhood - Osair",
            prerequisites = "Chapter 3; complete earlier quests in the same area/faction if the dialogue is not yet available.",
            summary = "Core objective: secure weapon bundles and get it to Marius.",
            walkthroughSteps = listOf("Core objective: secure weapon bundles and get it to Marius. Treat Masyaf as a chained storyline: exhaust dialogue with the local leaders and slaves before killing or freeing anyone, because later quests depend on earlier outcomes. Start this quest in Masyaf Brotherhood - Osair and exhaust the new dialogue connected with \"Weapon Bundles for Marius\". Speak with the relevant contact in Masyaf Brotherhood - Osair to confirm the requested amount or exact variant. Obtain \"Weapon Bundles\" by gathering, buying, crafting, looting or completing the linked prerequisite task, then bring it to Marius. If the quest does not close immediately, return to the NPC who originally sent you."),
            reward = "Reward varies by quest/build; exact values should be taken from the current in-game dialogue or source page.",
            warnings = "Do not sell unique named items, special ingredients, quest letters or unusual trophies until the related quest chain is finished.",
            searchTags = listOf("weapon bundles for marius", "masyaf brotherhood - osair", "local quest giver in masyaf brotherhood - osair")
        ),
        Quest(
            id = "CH3-068",
            chapter = 3,
            playOrder = 68,
            title = "Payment for the Slaves",
            category = "Masyaf Brotherhood - Osair",
            giver = "Local quest giver in Masyaf Brotherhood - Osair",
            location = "Masyaf Brotherhood - Osair",
            prerequisites = "Chapter 3; complete earlier quests in the same area/faction if the dialogue is not yet available.",
            summary = "Core objective: secure payment and get it to the Slaves.",
            walkthroughSteps = listOf("Core objective: secure payment and get it to the Slaves. Treat Masyaf as a chained storyline: exhaust dialogue with the local leaders and slaves before killing or freeing anyone, because later quests depend on earlier outcomes. Start this quest in Masyaf Brotherhood - Osair and exhaust the new dialogue connected with \"Payment for the Slaves\". Speak with the relevant contact in Masyaf Brotherhood - Osair to confirm the requested amount or exact variant. Obtain \"Payment\" by gathering, buying, crafting, looting or completing the linked prerequisite task, then bring it to the Slaves. If the quest does not close immediately, return to the NPC who originally sent you."),
            reward = "Reward varies by quest/build; exact values should be taken from the current in-game dialogue or source page.",
            warnings = "Do not sell unique named items, special ingredients, quest letters or unusual trophies until the related quest chain is finished.",
            searchTags = listOf("payment for the slaves", "masyaf brotherhood - osair", "local quest giver in masyaf brotherhood - osair")
        ),
        Quest(
            id = "CH3-069",
            chapter = 3,
            playOrder = 69,
            title = "Moon Blades",
            category = "Masyaf Brotherhood - Osair",
            giver = "Local quest giver in Masyaf Brotherhood - Osair",
            location = "Masyaf Brotherhood - Osair",
            prerequisites = "Chapter 3; complete earlier quests in the same area/faction if the dialogue is not yet available.",
            summary = "Treat Masyaf as a chained storyline: exhaust dialogue with the local leaders and slaves before killing or freeing anyone, because later quests depend on earlier outcomes.",
            walkthroughSteps = listOf("Treat Masyaf as a chained storyline: exhaust dialogue with the local leaders and slaves before killing or freeing anyone, because later quests depend on earlier outcomes. Start this quest in Masyaf Brotherhood - Osair and exhaust the new dialogue connected with \"Moon Blades\". Follow the dialogue chain for \"Moon Blades\" in Masyaf Brotherhood - Osair. Speak to the quest giver and every newly mentioned NPC, inspect the locations or objects added to the journal, and complete the objective that causes the journal to update. Return to the relevant giver/contact after each major update; if no new dialogue appears, complete earlier quests in the same area or faction and check again."),
            reward = "Reward varies by quest/build; exact values should be taken from the current in-game dialogue or source page.",
            warnings = "This is an index-guided quick solution. Exact item counts, coordinates and reward values can differ with New Balance updates; use the linked source record when a build-specific detail matters.",
            searchTags = listOf("moon blades", "masyaf brotherhood - osair", "local quest giver in masyaf brotherhood - osair")
        ),
        Quest(
            id = "CH3-070",
            chapter = 3,
            playOrder = 70,
            title = "Loyal People",
            category = "Masyaf Brotherhood - Osair",
            giver = "Local quest giver in Masyaf Brotherhood - Osair",
            location = "Masyaf Brotherhood - Osair",
            prerequisites = "Chapter 3; complete earlier quests in the same area/faction if the dialogue is not yet available.",
            summary = "Treat Masyaf as a chained storyline: exhaust dialogue with the local leaders and slaves before killing or freeing anyone, because later quests depend on earlier outcomes.",
            walkthroughSteps = listOf("Treat Masyaf as a chained storyline: exhaust dialogue with the local leaders and slaves before killing or freeing anyone, because later quests depend on earlier outcomes. Start this quest in Masyaf Brotherhood - Osair and exhaust the new dialogue connected with \"Loyal People\". Follow the dialogue chain for \"Loyal People\" in Masyaf Brotherhood - Osair. Speak to the quest giver and every newly mentioned NPC, inspect the locations or objects added to the journal, and complete the objective that causes the journal to update. Return to the relevant giver/contact after each major update; if no new dialogue appears, complete earlier quests in the same area or faction and check again."),
            reward = "Reward varies by quest/build; exact values should be taken from the current in-game dialogue or source page.",
            warnings = "This is an index-guided quick solution. Exact item counts, coordinates and reward values can differ with New Balance updates; use the linked source record when a build-specific detail matters.",
            searchTags = listOf("loyal people", "masyaf brotherhood - osair", "local quest giver in masyaf brotherhood - osair")
        ),
        Quest(
            id = "CH3-071",
            chapter = 3,
            playOrder = 71,
            title = "Deadly Hunt",
            category = "Masyaf Brotherhood - Tiamant",
            giver = "Local quest giver in Masyaf Brotherhood - Tiamant",
            location = "Masyaf Brotherhood - Tiamant",
            prerequisites = "Chapter 3; complete earlier quests in the same area/faction if the dialogue is not yet available.",
            summary = "Core objective: defeat the target(s) named by the quest and return with any proof/trophy the giver requests.",
            walkthroughSteps = listOf("Core objective: defeat the target(s) named by the quest and return with any proof/trophy the giver requests. Treat Masyaf as a chained storyline: exhaust dialogue with the local leaders and slaves before killing or freeing anyone, because later quests depend on earlier outcomes. Start this quest in Masyaf Brotherhood - Tiamant and exhaust the new dialogue connected with \"Deadly Hunt\". Get the target description from the quest giver, then travel through Masyaf Brotherhood - Tiamant to the marked or described hunting area. Defeat the enemies or named target associated with \"Deadly Hunt\", loot all bodies for proof/items, and search the immediate area for a journal-triggering object. Return to the quest giver and report the kill/clearing only after the objective counter or journal text has updated."),
            reward = "Reward varies by quest/build; exact values should be taken from the current in-game dialogue or source page.",
            warnings = "Named enemies frequently carry keys, notes or trophies used by another quest. Loot them before leaving the area.",
            searchTags = listOf("deadly hunt", "masyaf brotherhood - tiamant", "local quest giver in masyaf brotherhood - tiamant")
        ),
        Quest(
            id = "CH3-072",
            chapter = 3,
            playOrder = 72,
            title = "Uninvited Guests",
            category = "Masyaf Brotherhood - Tiamant",
            giver = "Local quest giver in Masyaf Brotherhood - Tiamant",
            location = "Masyaf Brotherhood - Tiamant",
            prerequisites = "Chapter 3; complete earlier quests in the same area/faction if the dialogue is not yet available.",
            summary = "Treat Masyaf as a chained storyline: exhaust dialogue with the local leaders and slaves before killing or freeing anyone, because later quests depend on earlier outcomes.",
            walkthroughSteps = listOf("Treat Masyaf as a chained storyline: exhaust dialogue with the local leaders and slaves before killing or freeing anyone, because later quests depend on earlier outcomes. Start this quest in Masyaf Brotherhood - Tiamant and exhaust the new dialogue connected with \"Uninvited Guests\". Question the quest giver and every NPC they mention, then investigate the nearby location in Masyaf Brotherhood - Tiamant. Resolve the concrete cause behind \"Uninvited Guests\" - usually a person, creature, stolen item or dispute - and return once the journal records the result. If several dialogue solutions are offered, finish optional conversations before choosing the final resolution."),
            reward = "Reward varies by quest/build; exact values should be taken from the current in-game dialogue or source page.",
            warnings = "Many New Balance side quests chain into later content, so favor dialogue/investigation over immediately killing a named NPC.",
            searchTags = listOf("uninvited guests", "masyaf brotherhood - tiamant", "local quest giver in masyaf brotherhood - tiamant")
        ),
        Quest(
            id = "CH3-073",
            chapter = 3,
            playOrder = 73,
            title = "Kill Hasim",
            category = "Masyaf Brotherhood - Tiamant",
            giver = "Local quest giver in Masyaf Brotherhood - Tiamant",
            location = "Masyaf Brotherhood - Tiamant",
            prerequisites = "Chapter 3; complete earlier quests in the same area/faction if the dialogue is not yet available.",
            summary = "Core objective: defeat the target(s) named by the quest and return with any proof/trophy the giver requests.",
            walkthroughSteps = listOf("Core objective: defeat the target(s) named by the quest and return with any proof/trophy the giver requests. Treat Masyaf as a chained storyline: exhaust dialogue with the local leaders and slaves before killing or freeing anyone, because later quests depend on earlier outcomes. Start this quest in Masyaf Brotherhood - Tiamant and exhaust the new dialogue connected with \"Kill Hasim\". Get the target description from the quest giver, then travel through Masyaf Brotherhood - Tiamant to the marked or described hunting area. Defeat the enemies or named target associated with \"Kill Hasim\", loot all bodies for proof/items, and search the immediate area for a journal-triggering object. Return to the quest giver and report the kill/clearing only after the objective counter or journal text has updated."),
            reward = "Reward varies by quest/build; exact values should be taken from the current in-game dialogue or source page.",
            warnings = "Named enemies frequently carry keys, notes or trophies used by another quest. Loot them before leaving the area.",
            searchTags = listOf("kill hasim", "masyaf brotherhood - tiamant", "local quest giver in masyaf brotherhood - tiamant")
        ),
        Quest(
            id = "CH3-074",
            chapter = 3,
            playOrder = 74,
            title = "Clear the Mine",
            category = "Masyaf Brotherhood - Tiamant",
            giver = "Local quest giver in Masyaf Brotherhood - Tiamant",
            location = "Masyaf Brotherhood - Tiamant",
            prerequisites = "Chapter 3; complete earlier quests in the same area/faction if the dialogue is not yet available.",
            summary = "Core objective: defeat the target(s) named by the quest and return with any proof/trophy the giver requests.",
            walkthroughSteps = listOf("Core objective: defeat the target(s) named by the quest and return with any proof/trophy the giver requests. Treat Masyaf as a chained storyline: exhaust dialogue with the local leaders and slaves before killing or freeing anyone, because later quests depend on earlier outcomes. Start this quest in Masyaf Brotherhood - Tiamant and exhaust the new dialogue connected with \"Clear the Mine\". Get the target description from the quest giver, then travel through Masyaf Brotherhood - Tiamant to the marked or described hunting area. Defeat the enemies or named target associated with \"Clear the Mine\", loot all bodies for proof/items, and search the immediate area for a journal-triggering object. Return to the quest giver and report the kill/clearing only after the objective counter or journal text has updated."),
            reward = "Reward varies by quest/build; exact values should be taken from the current in-game dialogue or source page.",
            warnings = "Named enemies frequently carry keys, notes or trophies used by another quest. Loot them before leaving the area.",
            searchTags = listOf("clear the mine", "masyaf brotherhood - tiamant", "local quest giver in masyaf brotherhood - tiamant")
        ),
        Quest(
            id = "CH3-075",
            chapter = 3,
            playOrder = 75,
            title = "Intrigues of the Masyaf Brotherhood",
            category = "Masyaf Brotherhood - Tiamant",
            giver = "Local quest giver in Masyaf Brotherhood - Tiamant",
            location = "Masyaf Brotherhood - Tiamant",
            prerequisites = "Chapter 3; complete earlier quests in the same area/faction if the dialogue is not yet available.",
            summary = "Treat Masyaf as a chained storyline: exhaust dialogue with the local leaders and slaves before killing or freeing anyone, because later quests depend on earlier outcomes.",
            walkthroughSteps = listOf("Treat Masyaf as a chained storyline: exhaust dialogue with the local leaders and slaves before killing or freeing anyone, because later quests depend on earlier outcomes. Start this quest in Masyaf Brotherhood - Tiamant and exhaust the new dialogue connected with \"Intrigues of the Masyaf Brotherhood\". Follow the dialogue chain for \"Intrigues of the Masyaf Brotherhood\" in Masyaf Brotherhood - Tiamant. Speak to the quest giver and every newly mentioned NPC, inspect the locations or objects added to the journal, and complete the objective that causes the journal to update. Return to the relevant giver/contact after each major update; if no new dialogue appears, complete earlier quests in the same area or faction and check again."),
            reward = "Reward varies by quest/build; exact values should be taken from the current in-game dialogue or source page.",
            warnings = "This is an index-guided quick solution. Exact item counts, coordinates and reward values can differ with New Balance updates; use the linked source record when a build-specific detail matters.",
            searchTags = listOf("intrigues of the masyaf brotherhood", "masyaf brotherhood - tiamant", "local quest giver in masyaf brotherhood - tiamant")
        ),
        Quest(
            id = "CH3-076",
            chapter = 3,
            playOrder = 76,
            title = "Gold Mine",
            category = "Masyaf Brotherhood - Tiamant",
            giver = "Local quest giver in Masyaf Brotherhood - Tiamant",
            location = "Masyaf Brotherhood - Tiamant",
            prerequisites = "Chapter 3; complete earlier quests in the same area/faction if the dialogue is not yet available.",
            summary = "Treat Masyaf as a chained storyline: exhaust dialogue with the local leaders and slaves before killing or freeing anyone, because later quests depend on earlier outcomes.",
            walkthroughSteps = listOf("Treat Masyaf as a chained storyline: exhaust dialogue with the local leaders and slaves before killing or freeing anyone, because later quests depend on earlier outcomes. Start this quest in Masyaf Brotherhood - Tiamant and exhaust the new dialogue connected with \"Gold Mine\". Speak with all merchants/debtors named by the quest and use the available dialogue, payment or persuasion options. Collect the money, goods or signed agreement required by \"Gold Mine\", then return it to the quest giver in Masyaf Brotherhood - Tiamant. If you are offered several settlement choices, resolve the related side quests first so you do not lose a better outcome."),
            reward = "Reward varies by quest/build; exact values should be taken from the current in-game dialogue or source page.",
            warnings = "Commercial quests often branch according to who you support. Save before handing over unique ledgers, contracts or large payments.",
            searchTags = listOf("gold mine", "masyaf brotherhood - tiamant", "local quest giver in masyaf brotherhood - tiamant")
        ),
        Quest(
            id = "CH3-077",
            chapter = 3,
            playOrder = 77,
            title = "Escort the Slaves to the Mine",
            category = "Masyaf Brotherhood - Tiamant",
            giver = "Local quest giver in Masyaf Brotherhood - Tiamant",
            location = "Masyaf Brotherhood - Tiamant",
            prerequisites = "Chapter 3; complete earlier quests in the same area/faction if the dialogue is not yet available.",
            summary = "Core objective: get the relevant NPC safely to the destination and trigger the arrival dialogue.",
            walkthroughSteps = listOf("Core objective: get the relevant NPC safely to the destination and trigger the arrival dialogue. Treat Masyaf as a chained storyline: exhaust dialogue with the local leaders and slaves before killing or freeing anyone, because later quests depend on earlier outcomes. Start this quest in Masyaf Brotherhood - Tiamant and exhaust the new dialogue connected with \"Escort the Slaves to the Mine\". Speak to the person who needs to travel, clear the route before starting the escort if possible, then accompany them through Masyaf Brotherhood - Tiamant to the destination named by the quest. Stay close enough for escort dialogue/triggers to fire and deal with enemies that block the route. At the destination, speak with the escorted NPC and then report back if the journal remains open."),
            reward = "Reward varies by quest/build; exact values should be taken from the current in-game dialogue or source page.",
            warnings = "Save before starting long escorts. If the NPC stops, clear nearby enemies, move back toward them, and trigger any pending dialogue before continuing.",
            searchTags = listOf("escort the slaves to the mine", "masyaf brotherhood - tiamant", "local quest giver in masyaf brotherhood - tiamant")
        ),
        Quest(
            id = "CH3-078",
            chapter = 3,
            playOrder = 78,
            title = "Nrozas's Triumph",
            category = "Masyaf Brotherhood - Tiamant",
            giver = "Local quest giver in Masyaf Brotherhood - Tiamant",
            location = "Masyaf Brotherhood - Tiamant",
            prerequisites = "Chapter 3; complete earlier quests in the same area/faction if the dialogue is not yet available.",
            summary = "Treat Masyaf as a chained storyline: exhaust dialogue with the local leaders and slaves before killing or freeing anyone, because later quests depend on earlier outcomes.",
            walkthroughSteps = listOf("Treat Masyaf as a chained storyline: exhaust dialogue with the local leaders and slaves before killing or freeing anyone, because later quests depend on earlier outcomes. Start this quest in Masyaf Brotherhood - Tiamant and exhaust the new dialogue connected with \"Nrozas's Triumph\". Follow the dialogue chain for \"Nrozas's Triumph\" in Masyaf Brotherhood - Tiamant. Speak to the quest giver and every newly mentioned NPC, inspect the locations or objects added to the journal, and complete the objective that causes the journal to update. Return to the relevant giver/contact after each major update; if no new dialogue appears, complete earlier quests in the same area or faction and check again."),
            reward = "Reward varies by quest/build; exact values should be taken from the current in-game dialogue or source page.",
            warnings = "This is an index-guided quick solution. Exact item counts, coordinates and reward values can differ with New Balance updates; use the linked source record when a build-specific detail matters.",
            searchTags = listOf("nrozas's triumph", "masyaf brotherhood - tiamant", "local quest giver in masyaf brotherhood - tiamant")
        ),
        Quest(
            id = "CH3-079",
            chapter = 3,
            playOrder = 79,
            title = "Gift of Fate",
            category = "Masyaf Brotherhood - Tiamant",
            giver = "Local quest giver in Masyaf Brotherhood - Tiamant",
            location = "Masyaf Brotherhood - Tiamant",
            prerequisites = "Chapter 3; complete earlier quests in the same area/faction if the dialogue is not yet available.",
            summary = "Treat Masyaf as a chained storyline: exhaust dialogue with the local leaders and slaves before killing or freeing anyone, because later quests depend on earlier outcomes.",
            walkthroughSteps = listOf("Treat Masyaf as a chained storyline: exhaust dialogue with the local leaders and slaves before killing or freeing anyone, because later quests depend on earlier outcomes. Start this quest in Masyaf Brotherhood - Tiamant and exhaust the new dialogue connected with \"Gift of Fate\". Follow the dialogue chain for \"Gift of Fate\" in Masyaf Brotherhood - Tiamant. Speak to the quest giver and every newly mentioned NPC, inspect the locations or objects added to the journal, and complete the objective that causes the journal to update. Return to the relevant giver/contact after each major update; if no new dialogue appears, complete earlier quests in the same area or faction and check again."),
            reward = "Reward varies by quest/build; exact values should be taken from the current in-game dialogue or source page.",
            warnings = "This is an index-guided quick solution. Exact item counts, coordinates and reward values can differ with New Balance updates; use the linked source record when a build-specific detail matters.",
            searchTags = listOf("gift of fate", "masyaf brotherhood - tiamant", "local quest giver in masyaf brotherhood - tiamant")
        ),
        Quest(
            id = "CH3-080",
            chapter = 3,
            playOrder = 80,
            title = "Duel of Truth",
            category = "Masyaf Brotherhood - Tiamant",
            giver = "Local quest giver in Masyaf Brotherhood - Tiamant",
            location = "Masyaf Brotherhood - Tiamant",
            prerequisites = "Chapter 3; complete earlier quests in the same area/faction if the dialogue is not yet available.",
            summary = "Treat Masyaf as a chained storyline: exhaust dialogue with the local leaders and slaves before killing or freeing anyone, because later quests depend on earlier outcomes.",
            walkthroughSteps = listOf("Treat Masyaf as a chained storyline: exhaust dialogue with the local leaders and slaves before killing or freeing anyone, because later quests depend on earlier outcomes. Start this quest in Masyaf Brotherhood - Tiamant and exhaust the new dialogue connected with \"Duel of Truth\". Speak with the challenger/trainer in Masyaf Brotherhood - Tiamant and accept the test. Complete the combat, hunting, skill or dialogue condition described in the journal, then speak to the same NPC again for recognition. If the challenge has several opponents or stages, finish them in the order offered and heal/save between stages."),
            reward = "Reward varies by quest/build; exact values should be taken from the current in-game dialogue or source page.",
            warnings = "Some tests are non-lethal; avoid finishing a downed human opponent unless the quest specifically requires a kill.",
            searchTags = listOf("duel of truth", "masyaf brotherhood - tiamant", "local quest giver in masyaf brotherhood - tiamant")
        ),
        Quest(
            id = "CH3-081",
            chapter = 3,
            playOrder = 81,
            title = "Offerings to Haniar",
            category = "Masyaf Brotherhood - Tiamant",
            giver = "Local quest giver in Masyaf Brotherhood - Tiamant",
            location = "Masyaf Brotherhood - Tiamant",
            prerequisites = "Chapter 3; complete earlier quests in the same area/faction if the dialogue is not yet available.",
            summary = "Treat Masyaf as a chained storyline: exhaust dialogue with the local leaders and slaves before killing or freeing anyone, because later quests depend on earlier outcomes.",
            walkthroughSteps = listOf("Treat Masyaf as a chained storyline: exhaust dialogue with the local leaders and slaves before killing or freeing anyone, because later quests depend on earlier outcomes. Start this quest in Masyaf Brotherhood - Tiamant and exhaust the new dialogue connected with \"Offerings to Haniar\". Ask the quest giver for all available clues, then search Masyaf Brotherhood - Tiamant and the locations mentioned in the journal for the named object connected with \"Offerings to Haniar\". Check corpses, locked chests, shelves, caves and camp interiors, and read any notes you find because they often advance the objective. Take the item to the intended owner/quest giver and continue the dialogue until the journal closes."),
            reward = "Reward varies by quest/build; exact values should be taken from the current in-game dialogue or source page.",
            warnings = "Unique equipment can be tied to several quests. Do not sell, forge away or discard it before checking all related dialogue.",
            searchTags = listOf("offerings to haniar", "masyaf brotherhood - tiamant", "local quest giver in masyaf brotherhood - tiamant")
        ),
        Quest(
            id = "CH3-082",
            chapter = 3,
            playOrder = 82,
            title = "Price of Betrayal",
            category = "Masyaf Brotherhood - Tiamant",
            giver = "Local quest giver in Masyaf Brotherhood - Tiamant",
            location = "Masyaf Brotherhood - Tiamant",
            prerequisites = "Chapter 3; complete earlier quests in the same area/faction if the dialogue is not yet available.",
            summary = "Treat Masyaf as a chained storyline: exhaust dialogue with the local leaders and slaves before killing or freeing anyone, because later quests depend on earlier outcomes.",
            walkthroughSteps = listOf("Treat Masyaf as a chained storyline: exhaust dialogue with the local leaders and slaves before killing or freeing anyone, because later quests depend on earlier outcomes. Start this quest in Masyaf Brotherhood - Tiamant and exhaust the new dialogue connected with \"Price of Betrayal\". Follow the dialogue chain for \"Price of Betrayal\" in Masyaf Brotherhood - Tiamant. Speak to the quest giver and every newly mentioned NPC, inspect the locations or objects added to the journal, and complete the objective that causes the journal to update. Return to the relevant giver/contact after each major update; if no new dialogue appears, complete earlier quests in the same area or faction and check again."),
            reward = "Reward varies by quest/build; exact values should be taken from the current in-game dialogue or source page.",
            warnings = "This is an index-guided quick solution. Exact item counts, coordinates and reward values can differ with New Balance updates; use the linked source record when a build-specific detail matters.",
            searchTags = listOf("price of betrayal", "masyaf brotherhood - tiamant", "local quest giver in masyaf brotherhood - tiamant")
        ),
        Quest(
            id = "CH3-083",
            chapter = 3,
            playOrder = 83,
            title = "Dark Secrets",
            category = "Masyaf Brotherhood - Tiamant",
            giver = "Local quest giver in Masyaf Brotherhood - Tiamant",
            location = "Masyaf Brotherhood - Tiamant",
            prerequisites = "Chapter 3; complete earlier quests in the same area/faction if the dialogue is not yet available.",
            summary = "Treat Masyaf as a chained storyline: exhaust dialogue with the local leaders and slaves before killing or freeing anyone, because later quests depend on earlier outcomes.",
            walkthroughSteps = listOf("Treat Masyaf as a chained storyline: exhaust dialogue with the local leaders and slaves before killing or freeing anyone, because later quests depend on earlier outcomes. Start this quest in Masyaf Brotherhood - Tiamant and exhaust the new dialogue connected with \"Dark Secrets\". Collect the exposition from the quest giver, then explore the quest location in Masyaf Brotherhood - Tiamant rather than relying only on combat. For \"Dark Secrets\", inspect switches, inscriptions, books, keys, corpses and unusual interactable objects; read every quest note before operating the next mechanism. When the puzzle/ritual or exploration objective updates, return to the associated scholar, mage or faction contact for the next step."),
            reward = "Reward varies by quest/build; exact values should be taken from the current in-game dialogue or source page.",
            warnings = "Make a manual save before using one-way portals, ritual objects or major temple mechanisms.",
            searchTags = listOf("dark secrets", "masyaf brotherhood - tiamant", "local quest giver in masyaf brotherhood - tiamant")
        )
    )
}
