package com.sliverzfx.gothicquest

object NewBalanceChapter5Data {
    val quests = listOf(
        Quest(
            id = "CH5-001",
            chapter = 5,
            playOrder = 1,
            title = "Lord of the Dragons",
            category = "Main Story",
            giver = "The last dragon / main-story progression",
            location = "Main Story",
            prerequisites = "Chapter 5. Defeat the four main dragons in the Valley of Mines and finish the Chapter 4 dragon hunt.",
            summary = "After the final dragon is defeated, exhaust its dialogue about the master of the dragons and return to Pyrokar. You learn that the enemy is connected with the Halls of Irdorath, a lost eastern temple of Beliar. Enter the monastery basement and obtain the book Halls of Irdorath. The book cannot be opened normally, so travel to Xardas's tower. Lester tells you that Xardas has disappeared and that the tower is occupied by undead; take Lester's letter, clear the tower and follow the clues. Read the recovered material, use the key/note found there and open the hidden library by operating the lamp/lever near the crate. Fight the converted knights and the corrupted Fire Mage Ilkrus, search the secret library, read the almanac and take the book/map that reveals the route to Irdorath. Report back to Talomon and Pyrokar, then begin organizing the ship, captain and crew.",
            walkthroughSteps = listOf("After the final dragon is defeated, exhaust its dialogue about the master of the dragons and return to Pyrokar. You learn that the enemy is connected with the Halls of Irdorath, a lost eastern temple of Beliar. Enter the monastery basement and obtain the book Halls of Irdorath. The book cannot be opened normally, so travel to Xardas's tower. Lester tells you that Xardas has disappeared and that the tower is occupied by undead; take Lester's letter, clear the tower and follow the clues. Read the recovered material, use the key/note found there and open the hidden library by operating the lamp/lever near the crate. Fight the converted knights and the corrupted Fire Mage Ilkrus, search the secret library, read the almanac and take the book/map that reveals the route to Irdorath. Report back to Talomon and Pyrokar, then begin organizing the ship, captain and crew."),
            reward = "Unlocks the final expedition: I Need a Ship, captain/crew preparation and access to Irdorath.",
            warnings = "Do not rush through the secret library. Read every book/almanac and loot the named enemies before leaving. Fire Mages can also obtain the Tears of Innos during this sequence.",
            searchTags = listOf("lord of the dragons", "main story", "the last dragon / main-story progression")
        ),
        Quest(
            id = "CH5-002",
            chapter = 5,
            playOrder = 2,
            title = "I Need a Ship",
            category = "Main Story",
            giver = "Trigger quest",
            location = "Main Story",
            prerequisites = "Discover the route to Irdorath during Lord of the Dragons.",
            summary = "Once the route to Irdorath is known, secure a vessel capable of making the voyage. The exact authorization depends on your main guild. Brotherhood characters must complete Good Connections. Mercenary/Dragon Hunter characters can work through Lee and the required papers; if the normal document route is unavailable in the current state of the game, Lee can provide a forged document. Other guild routes are resolved by completing the captain and crew preparations and obtaining permission to use the paladin ship. When your paperwork, captain and crew are ready, proceed to the Esmeralda and prepare to depart.",
            walkthroughSteps = listOf("Once the route to Irdorath is known, secure a vessel capable of making the voyage. The exact authorization depends on your main guild. Brotherhood characters must complete Good Connections. Mercenary/Dragon Hunter characters can work through Lee and the required papers; if the normal document route is unavailable in the current state of the game, Lee can provide a forged document. Other guild routes are resolved by completing the captain and crew preparations and obtaining permission to use the paladin ship. When your paperwork, captain and crew are ready, proceed to the Esmeralda and prepare to depart."),
            reward = "Permission/access to the Esmeralda and progression toward Chapter 6.",
            warnings = "Departure is effectively the point of no return for normal Khorinis progression. Finish shopping, crafting, guild quests and any side content you still want before sailing.",
            searchTags = listOf("i need a ship", "main story", "automatic / main-story progression")
        ),
        Quest(
            id = "CH5-003",
            chapter = 5,
            playOrder = 3,
            title = "Who Will Be My Captain?",
            category = "Main Story",
            giver = "Main-story preparation",
            location = "Main Story",
            prerequisites = "I Need a Ship has started.",
            summary = "Choose one of the available captains. Jorgen can captain the ship after Pyrokar releases him; complete Return to the Tower for Pyrokar first. Jack agrees after his lighthouse problem is resolved and you find a replacement keeper - Brian, Harad's apprentice, can take the job. Torlof agrees if you open the Valley of Mines castle gate so the orcs can enter, report back to him, and then pay his fee. Once your chosen candidate accepts, return to the ship-preparation dialogue and continue the expedition setup.",
            walkthroughSteps = listOf("Choose one of the available captains. Jorgen can captain the ship after Pyrokar releases him; complete Return to the Tower for Pyrokar first. Jack agrees after his lighthouse problem is resolved and you find a replacement keeper - Brian, Harad's apprentice, can take the job. Torlof agrees if you open the Valley of Mines castle gate so the orcs can enter, report back to him, and then pay his fee. Once your chosen candidate accepts, return to the ship-preparation dialogue and continue the expedition setup."),
            reward = "A captain for the Esmeralda; the current guide lists additional XP for the individual captain tasks and quest completion.",
            warnings = "Torlof's route deliberately causes the orcs to enter the Valley of Mines castle and has karma consequences, so do not choose it casually. Jack and Jorgen are cleaner alternatives for many playthroughs.",
            searchTags = listOf("who will be my captain?", "main story", "main-story preparation")
        ),
        Quest(
            id = "CH5-004",
            chapter = 5,
            playOrder = 4,
            title = "No Voyage Without a Crew",
            category = "Main Story",
            giver = "Main-story preparation",
            location = "Main Story",
            prerequisites = "Prepare the Esmeralda for Irdorath. At least five crew members are required.",
            summary = "Recruit companions for the voyage. Current documented candidates include Diego (after Diego's Business), Lester, Gorn, Milten, Lares, Vatras, Lee, Wolf (only if he was not permanently assigned to Bengar), Bennet, Girion, Biff, Angar (after Angar's Amulet), and Mario. Speak to each desired companion and invite them. Once the minimum crew requirement is met and a captain is chosen, return to the ship and finish the departure preparations.",
            walkthroughSteps = listOf("Recruit companions for the voyage. Current documented candidates include Diego (after Diego's Business), Lester, Gorn, Milten, Lares, Vatras, Lee, Wolf (only if he was not permanently assigned to Bengar), Bennet, Girion, Biff, Angar (after Angar's Amulet), and Mario. Speak to each desired companion and invite them. Once the minimum crew requirement is met and a captain is chosen, return to the ship and finish the departure preparations."),
            reward = "The current walkthrough lists 500 XP per recruited crew member, plus access to their services during Chapter 6.",
            warnings = "Recruit as many useful companions as your route allows before sailing: several provide training, trading, healing or crafting services on Irdorath. The current guide also warns about a duplicate invitation dialogue line; if an NPC has already accepted, do not repeatedly select a redundant second invitation option.",
            searchTags = listOf("no voyage without a crew", "main story", "main-story preparation")
        ),
        Quest(
            id = "CH5-005",
            chapter = 5,
            playOrder = 5,
            title = "Rosie's Disappearance",
            category = "Khorinis Island",
            giver = "Rosie / encounter on the road",
            location = "Khorinis Island",
            prerequisites = "Chapter 5. Rosie and Till must still be available.",
            summary = "Search the road between Orlan's Dead Harpy tavern and the Water Mage excavation area. You will find Rosie with Till. Speak with her and learn that she left Sekob because she could no longer tolerate life with him. Agree to escort her to a safe destination. The destination depends on your main guild: Paladin, Demon Hunter, Scout and Necromancer routes take her to Khorinis; Dragon Hunter and Dark Knight routes take her to Onar's farm; Fire Mage and Water Mage routes take her to the monastery; Guru and Temple Guard routes take her to the Brotherhood camp. Escort her safely and finish the dialogue at the destination.",
            walkthroughSteps = listOf("Search the road between Orlan's Dead Harpy tavern and the Water Mage excavation area. You will find Rosie with Till. Speak with her and learn that she left Sekob because she could no longer tolerate life with him. Agree to escort her to a safe destination. The destination depends on your main guild: Paladin, Demon Hunter, Scout and Necromancer routes take her to Khorinis; Dragon Hunter and Dark Knight routes take her to Onar's farm; Fire Mage and Water Mage routes take her to the monastery; Guru and Temple Guard routes take her to the Brotherhood camp. Escort her safely and finish the dialogue at the destination."),
            reward = "The current quest guide lists 1,250 XP and 200 gold.",
            warnings = "Clear the escort route before starting if possible. Community reports note that combat can make escorted NPCs fall behind or reset. This outcome also conflicts with older Sekob/Rosie quest variants, so save before committing if you want to compare branches.",
            searchTags = listOf("rosie's disappearance", "khorinis island", "rosie / encounter on the road")
        ),
        Quest(
            id = "CH5-006",
            chapter = 5,
            playOrder = 6,
            title = "Dark Order",
            category = "Khorinis - Upper Quarter",
            giver = "Lord Hagen",
            location = "Khorinis - Upper Quarter",
            prerequisites = "Chapter 5; report that all four main dragons are dead.",
            summary = "Khorinis is overrun by undead. First help clear the undead at the city gates, then speak with Lord Hagen and Pyrokar. Pyrokar suspects a deeper source, so visit Kreol; he explains that fallen paladins have risen as servants of Beliar. Return to Pyrokar and receive the keys to three paladin tombs. Clear the tomb of Lord Inubis behind Onar's farm, Lord Ulzar in the cave by the cemetery near the Dead Harpy, and Lord Mirat in the cave between Grimbald and the Sun Circle. Return to Pyrokar. When the plague continues, speak with Hagen about the fallen paladin Ginnok. His tomb lies in the hollow between Khorinis's south and east gates. Clear the converted paladins and defeat Ginnok, loot the area, then report to Hagen.",
            walkthroughSteps = listOf("Khorinis is overrun by undead. First help clear the undead at the city gates, then speak with Lord Hagen and Pyrokar. Pyrokar suspects a deeper source, so visit Kreol; he explains that fallen paladins have risen as servants of Beliar. Return to Pyrokar and receive the keys to three paladin tombs. Clear the tomb of Lord Inubis behind Onar's farm, Lord Ulzar in the cave by the cemetery near the Dead Harpy, and Lord Mirat in the cave between Grimbald and the Sun Circle. Return to Pyrokar. When the plague continues, speak with Hagen about the fallen paladin Ginnok. His tomb lies in the hollow between Khorinis's south and east gates. Clear the converted paladins and defeat Ginnok, loot the area, then report to Hagen."),
            reward = "Large Chapter 5 XP chain; the current walkthrough lists several staged XP rewards through Kreol, Pyrokar and Hagen.",
            warnings = "Do not pre-kill named Shadow Lords if you can avoid it. Older/current forum reports indicate that killing Inubis too early can interfere with the later key/tomb stage in some builds. The Ginnok sequence can also yield a recipe tied to ore armor/black-ore jewelry.",
            searchTags = listOf("dark order", "khorinis - upper quarter", "lord hagen")
        ),
        Quest(
            id = "CH5-007",
            chapter = 5,
            playOrder = 7,
            title = "Urban Bandits",
            category = "Khorinis - Upper Quarter",
            giver = "Trigger quest",
            location = "Khorinis - Upper Quarter",
            prerequisites = "Chapter 5. Relevant Jharkendar bandits must have survived earlier events.",
            summary = "This is a hidden, journal-less Chapter 5 event. Surviving Jharkendar bandits relocate into Khorinis. Find and speak with each survivor: Thorus and Scatty are at the militia barracks, Fisk is in the marketplace, Miguel stands in front of the stage, Tom is near Matteo, and Snaf is in the harbor tavern. The event is complete for practical guide purposes once you have spoken to all available survivors.",
            walkthroughSteps = listOf("This is a hidden, journal-less Chapter 5 event. Surviving Jharkendar bandits relocate into Khorinis. Find and speak with each survivor: Thorus and Scatty are at the militia barracks, Fisk is in the marketplace, Miguel stands in front of the stage, Tom is near Matteo, and Snaf is in the harbor tavern. The event is complete for practical guide purposes once you have spoken to all available survivors."),
            reward = "500 XP per documented survivor conversation; six survivors give 3,000 XP in total.",
            warnings = "There is no quest giver and no journal entry, so it is easy to miss. Do not waste time searching for an enemy group to kill - the objective is simply to find and talk to the relocated survivors.",
            searchTags = listOf("urban bandits", "khorinis - upper quarter", "none - hidden chapter 5 event")
        ),
        Quest(
            id = "CH5-008",
            chapter = 5,
            playOrder = 8,
            title = "Return to the Tower",
            category = "Monastery of Innos",
            giver = "Pyrokar",
            location = "Monastery of Innos",
            prerequisites = "Chapter 5; Who Will Be My Captain? has started and you want Jorgen as captain.",
            summary = "Ask Pyrokar to release Jorgen so he can captain your ship. Pyrokar first requires Xardas's tower to be cleansed. Travel to the tower and eliminate the undead and skeleton warriors throughout the building, including the Demonic Guardian in the library. Once the tower is completely clear, return to Pyrokar and report success. Jorgen can then be released for the voyage.",
            walkthroughSteps = listOf("Ask Pyrokar to release Jorgen so he can captain your ship. Pyrokar first requires Xardas's tower to be cleansed. Travel to the tower and eliminate the undead and skeleton warriors throughout the building, including the Demonic Guardian in the library. Once the tower is completely clear, return to Pyrokar and report success. Jorgen can then be released for the voyage."),
            reward = "The current guide lists 3,000 XP and unlocks Jorgen as a captain candidate.",
            warnings = "Sweep every floor before returning. If Pyrokar does not acknowledge completion, a remaining enemy is usually still alive somewhere in or around the tower.",
            searchTags = listOf("return to the tower", "monastery of innos", "pyrokar")
        ),
        Quest(
            id = "CH5-009",
            chapter = 5,
            playOrder = 9,
            title = "Good Connections",
            category = "Brotherhood",
            giver = "Baal Orun",
            location = "Brotherhood",
            prerequisites = "Chapter 5; Guru or Temple Guard path; I Need a Ship is active.",
            summary = "Ask Baal Orun how you can gain access to the paladin ship. He tells you to wait while he uses his contacts. Return after the required wait/dialogue update and speak with him again. Pay 2,000 gold and receive the document/authorization that allows you to proceed with the ship.",
            walkthroughSteps = listOf("Ask Baal Orun how you can gain access to the paladin ship. He tells you to wait while he uses his contacts. Return after the required wait/dialogue update and speak with him again. Pay 2,000 gold and receive the document/authorization that allows you to proceed with the ship."),
            reward = "The current guide lists 2,500 XP and the document needed for ship access.",
            warnings = "This is the Brotherhood-specific solution to the ship-access problem. If the follow-up dialogue is absent, wait the required in-game time and return rather than assuming the quest is broken.",
            searchTags = listOf("good connections", "brotherhood", "baal orun")
        )
    )
}
