package com.sliverzfx.gothicquest

object NewBalanceChapter3Part2 {
    val quests = listOf(
        Quest(
            id = "CH3-043",
            chapter = 3,
            playOrder = 43,
            title = "A Huge Ruby for Cassia",
            category = "Thieves' Guild",
            giver = "Cassia",
            location = "Thieves' Guild",
            prerequisites = "Act 3; Thieves' Guild membership; speak to Cassia about her valuable ruby.",
            summary = "Steal an enormous ruby from a dangerous chest in the Khorinis Town Hall Upper Quarter.",
            walkthroughSteps = listOf("Ask Cassia what jewel she wants and prepare for a dangerous lock and trap.", "Enter the Upper Quarter Town Hall and locate the chest in the upstairs room used by Larius.", "Pick the lock and disable or survive its powerful trap; the exact Dexterity threshold depends on the build.", "Take the huge ruby and return it to Cassia."),
            reward = "Cassia's completion reward for the enormous ruby; exact XP and gold not confirmed for the current New Balance build.",
            warnings = "The chest is trapped and can kill an unprepared character. Do not rely on Dexterity thresholds quoted for older Returning versions.",
            searchTags = listOf("a huge ruby for cassia", "thieves' guild", "local quest giver in thieves' guild")
        ),
        Quest(
            id = "CH3-044",
            chapter = 3,
            playOrder = 44,
            title = "Antiques",
            category = "Merchants' Guild",
            giver = "Lutero",
            location = "Merchants' Guild",
            prerequisites = "Act 3; Merchants' Guild; complete Contract with Onar.",
            summary = "Recover three black Nordmar statuettes from Gomez's old castle tower for Lutero.",
            walkthroughSteps = listOf("Accept Lutero's antiques commission in Khorinis.", "Travel to Garond's castle in the Valley of Mines. Find the two keys for Gomez's tower: one upstairs in the main castle building and another in the opposite building near Engor's quarters.", "Explore the tower, confront undead Gomez and follow the associated Gomez's Curse quest to obtain the locked statue chest key.", "Retrieve all three black Nordmar statuettes from the tower chest and deliver them to Lutero."),
            reward = "1,500 XP, 1,000 gold, a permanent elixir granting +3 Strength, Dexterity and Mana, plus one Merchants' Guild reputation.",
            warnings = "Gomez's Curse is needed to unlock the statues; merely finding the tower and its external keys does not complete the commission.",
            searchTags = listOf("antiques", "merchants' guild", "local quest giver in merchants' guild")
        ),
        Quest(
            id = "CH3-045",
            chapter = 3,
            playOrder = 45,
            title = "Gomez's Curse",
            category = "Merchants' Guild",
            giver = "Gomez's ghost",
            location = "Merchants' Guild",
            prerequisites = "Act 3; enter Gomez's old tower during Antiques.",
            summary = "Help Gomez's ghost receive forgiveness, cleanse his past, and defeat the dark spirits tied to his curse.",
            walkthroughSteps = listOf("Meet the spirit of Gomez in the old castle tower in the Valley of Mines.", "Seek absolution from Adanos by speaking with Vatras; seek Innos's grace at a shrine and satisfy Beliar through the offered sacrifice or appropriate alternatives.", "Return to the old mine and free the spirits of the miners connected to Gomez's crimes, following their dialogue before fighting.", "At the old Fire Mage wing's pentagram, summon Corristo and follow his lead toward the Cave of Pain.", "Clear the cave and defeat the powerful undead including Dark Reaper and Miragul; report to Corristo and finally Gomez."),
            reward = "Staged XP including 3,000 XP after Corristo's final report and 5,000 XP from Gomez; receives the statue chest key needed for Antiques.",
            warnings = "The Beliar absolution may involve permanent attributes or a substantial gold sacrifice. Preserve a save before making that choice.",
            searchTags = listOf("gomez's curse", "merchants' guild", "local quest giver in merchants' guild")
        ),
        Quest(
            id = "CH3-046",
            chapter = 3,
            playOrder = 46,
            title = "Black Brandy",
            category = "Merchants' Guild",
            giver = "Lutero",
            location = "Merchants' Guild",
            prerequisites = "Act 3; complete Antiques; deliver before noon on the next day.",
            summary = "Rescue merchant courier Benchel and retrieve a time-sensitive shipment of black brandy.",
            walkthroughSteps = listOf("Ask Lutero about a delayed shipment; he supplies 500 gold for expenses.", "Before noon the following day, search the road near Orlan's Dead Harpy tavern for Benchel under attack.", "Help Benchel survive, escort him to Khorinis's eastern gate and accept the shipment when he resigns.", "Deliver the black brandy to Lutero while the job is still valid."),
            reward = "Staged experience, including 1,500 XP on delivery; advances Merchants' Guild standing. The 500 gold from Lutero is travel money.",
            warnings = "STRICT TIME LIMIT: the shipment must reach Lutero by noon the next day. Save before accepting.",
            searchTags = listOf("black brandy", "merchants' guild", "local quest giver in merchants' guild")
        ),
        Quest(
            id = "CH3-047",
            chapter = 3,
            playOrder = 47,
            title = "The Assistant",
            category = "Merchants' Guild",
            giver = "Lutero",
            location = "Merchants' Guild",
            prerequisites = "Act 3; complete Black Brandy.",
            summary = "Recruit a suitable assistant for Lutero; the candidate determines the reward and reputation change.",
            walkthroughSteps = listOf("Ask Lutero about his need for an assistant.", "Interview Gawern at Kardif's tavern, Maxi at the marketplace, and Valeran in the Upper Quarter (his availability depends on the Weapons Supplier to Bandits quest).", "Choose a candidate and introduce them to Lutero.", "For the best Merchants' Guild reputation improvement, recommend Valeran; Maxi offers a reasonable alternative."),
            reward = "Gawern: 200 XP and -1 guild reputation. Maxi: 2,000 XP, 500 gold, +1 reputation. Valeran: 1,000 XP, 1,000 gold, +2 reputation and a Master Swordsman book.",
            warnings = "This is a mutually exclusive candidate decision. Gawern is the inferior choice for guild reputation.",
            searchTags = listOf("the assistant", "merchants' guild", "local quest giver in merchants' guild")
        ),
        Quest(
            id = "CH3-048",
            chapter = 3,
            playOrder = 48,
            title = "Helping Sarah",
            category = "Merchants' Guild",
            giver = "Lutero",
            location = "Merchants' Guild",
            prerequisites = "Act 3; complete The Assistant; Sarah must have been imprisoned via Canthar's earlier scheme.",
            summary = "Free Sarah from prison, help her regain her livelihood and recruit her to the Merchants' Guild.",
            walkthroughSteps = listOf("Ask Lutero about helping Sarah; he provides 500 gold toward her release.", "Ask Lord Andre to release Sarah and pay his faction-dependent bribe, which can exceed Lutero's advance.", "Find Sarah after release near Coragon's tavern and apologize for her imprisonment.", "Help with Food for Sarah, Family Ring and Sarah's Debts.", "Invite Sarah into the Merchants' Guild and return to Lutero to close the chain."),
            reward = "Staged experience, 500 gold at completion, a King's Sorrel Extract and +1 Merchants' Guild reputation; Andre's bribe is a cost.",
            warnings = "Only available if Sarah was actually jailed earlier. Do not assume Lutero's 500-gold advance covers every faction's release fee.",
            searchTags = listOf("helping sarah", "merchants' guild", "local quest giver in merchants' guild")
        ),
        Quest(
            id = "CH3-049",
            chapter = 3,
            playOrder = 49,
            title = "Food for Sarah",
            category = "Merchants' Guild",
            giver = "Sarah",
            location = "Merchants' Guild",
            prerequisites = "Act 3; free Sarah through Helping Sarah.",
            summary = "Bring food to Sarah while she is rebuilding her life after imprisonment.",
            walkthroughSteps = listOf("Find Sarah near Coragon's inn after Lord Andre releases her.", "Ask what food she needs; older guides mention two cooked meat portions and milk, but check the current journal quantity.", "Collect the requested food and hand it to Sarah."),
            reward = "Sarah accepts the food and her rehabilitation questline progresses; precise XP not verified.",
            warnings = "The food requirement may differ between Returning and New Balance revisions; verify exact amounts in the journal.",
            searchTags = listOf("food for sarah", "merchants' guild", "local quest giver in merchants' guild")
        ),
        Quest(
            id = "CH3-050",
            chapter = 3,
            playOrder = 50,
            title = "Family Ring",
            category = "Merchants' Guild",
            giver = "Sarah",
            location = "Merchants' Guild",
            prerequisites = "Act 3; free Sarah through Helping Sarah.",
            summary = "Recover Sarah's family ring from the militia member who took it.",
            walkthroughSteps = listOf("Speak with Sarah about the family ring that was taken while she was imprisoned.", "Confront militia member Boltan at the barracks about the missing ring.", "Depending on your faction, persuade him to return it, pay, or defeat him outside the gaze of witnesses.", "Bring the family ring back to Sarah."),
            reward = "500 XP when Sarah receives her ring; some peaceful faction dialogue also grants 100 XP.",
            warnings = "Do not attack the militia within sight of guards. Persuasion availability varies by faction.",
            searchTags = listOf("family ring", "merchants' guild", "local quest giver in merchants' guild")
        ),
        Quest(
            id = "CH3-051",
            chapter = 3,
            playOrder = 51,
            title = "Sarah's Debts",
            category = "Merchants' Guild",
            giver = "Sarah",
            location = "Merchants' Guild",
            prerequisites = "Act 3; free Sarah through Helping Sarah.",
            summary = "Settle Sarah's outstanding debt with blacksmith Harad.",
            walkthroughSteps = listOf("Ask Sarah about the money she still owes Harad.", "Visit Harad and pay Sarah's outstanding debt of 2,000 gold.", "Accept Harad's Noble Longsword and report that the debt is cleared to Sarah."),
            reward = "300 XP and a Noble Longsword from Harad; 700 XP from Sarah. Costs 2,000 gold to repay the debt.",
            warnings = "The 2,000 gold is the amount you must pay, not a reward.",
            searchTags = listOf("sarah's debts", "merchants' guild", "local quest giver in merchants' guild")
        ),
        Quest(
            id = "CH3-052",
            chapter = 3,
            playOrder = 52,
            title = "Missing Novices",
            category = "Masyaf Brotherhood - Main",
            giver = "Idol Namib",
            location = "Masyaf Brotherhood - Main",
            prerequisites = "Act 3; speak with the guard at the Brotherhood camp and then Idol Namib.",
            summary = "Investigate missing Brotherhood novices, uncover the Masyaf assassins and follow Gonzales into their hidden enclave.",
            walkthroughSteps = listOf("Ask Namib about missing novices and check the swampweed-gatherer camps near the south gate, black troll and Sun Circle, as well as Idol Parvez in Khorinis.", "Find dying guard Gor Hanis below the Sun Circle, track the blood to the nearby wine cave, defeat the wounded masked assassin and collect his unusual sword.", "Show the blade to Namib and the Khorinis smiths, then Darrion in the Valley of Mines forest camp; find Gonzales in Kardif's tavern or the brothel and complete Weapons for Gonzales if he still distrusts you.", "Report the Masyaf assassins to Namib; ask Gor Na Tof to send guards to Balam's camp near the black troll.", "Optional but recommended: complete Balam's and Tirax's camp quests before triggering the attack; defeat four assassins and bring their strange amulet to Namib.", "Find survivor Loki with Parvez in the marketplace. Ask Idol Tyon for a memory potion, obtaining his requested items including spirit elixir, King's Sorrel, minecrawler mandibles and cactus flower.", "Give Loki the potion, follow him to the pedestal near the Brotherhood camp, return to Namib for the amulet and use it on the pedestal to open the hidden way.", "Tell Gonzales and guide him to the passage; complete One of Them and the Masyaf plot, defeat Haniar and later Cor Kalom's demonic remnant, then use his teleport rune.", "Speak to Gonzales and finally Namib for the large questline conclusion; Gonzales later offers special assassin gear."),
            reward = "Major staged experience and Masyaf progression, including 3,000 XP on Cor Kalom's defeat, 1,000 XP from Gonzales and 6,000 XP on reporting final success to Namib.",
            warnings = "ONE-WAY SECTION: entering the passage commits you to the Masyaf questline until it is resolved. At least 30 rhetoric is recommended; preserve Gonzales and use the novice disguise properly.",
            searchTags = listOf("missing novices", "masyaf brotherhood - main", "local quest giver in masyaf brotherhood - main")
        ),
        Quest(
            id = "CH3-053",
            chapter = 3,
            playOrder = 53,
            title = "Mentor for the Guards",
            category = "Masyaf Brotherhood - Main",
            giver = "Tirax",
            location = "Masyaf Brotherhood - Main",
            prerequisites = "Act 3; during Missing Novices, ask Gor Na Tof to assign guards to Balam's gathering camp.",
            summary = "Obtain Gor Na Tof's permission for Tirax to train the swampweed camp guards.",
            walkthroughSteps = listOf("Speak with guard commander Tirax at Balam's camp about training the men.", "Return to the Brotherhood camp and ask Gor Na Tof to authorize the training.", "Report his permission to Tirax."),
            reward = "100 XP on obtaining permission; 300 XP and a Meatbug Transformation scroll from Tirax.",
            warnings = "The Meatbug scroll can be used during the later Noises in the Night quest.",
            searchTags = listOf("mentor for the guards", "masyaf brotherhood - main", "local quest giver in masyaf brotherhood - main")
        ),
        Quest(
            id = "CH3-054",
            chapter = 3,
            playOrder = 54,
            title = "Tirax's Nerves",
            category = "Masyaf Brotherhood - Main",
            giver = "Tirax",
            location = "Masyaf Brotherhood - Main",
            prerequisites = "Act 3; the night after completing Mentor for the Guards.",
            summary = "Help Tirax settle his nerves with three swampweed joints.",
            walkthroughSteps = listOf("Wait until the night after Mentor for the Guards.", "Speak with Tirax, who complains that he has not smoked for some time.", "Bring him three swampweed joints and hand them over."),
            reward = "300 XP.",
            warnings = "The dialogue starts on the following night, not immediately after the training quest.",
            searchTags = listOf("tirax's nerves", "masyaf brotherhood - main", "local quest giver in masyaf brotherhood - main")
        ),
        Quest(
            id = "CH3-055",
            chapter = 3,
            playOrder = 55,
            title = "Swampweed for Balam",
            category = "Masyaf Brotherhood - Gatherers",
            giver = "Balam",
            location = "Masyaf Brotherhood - Gatherers",
            prerequisites = "Act 3; arrive at Balam's camp during Missing Novices.",
            summary = "Collect ten swampweed stalks for Balam beside the lakeshore.",
            walkthroughSteps = listOf("Speak with Balam near the black troll's area and agree to gather swampweed.", "Search the shore around the nearby lake for ten swampweed stalks.", "Hand Balam the ten stalks."),
            reward = "50 XP per stalk and an Elixir of Life after turning in all ten.",
            warnings = "Save ten stalks for Balam rather than consuming or selling them to Fortuno first.",
            searchTags = listOf("swampweed for balam", "masyaf brotherhood - gatherers", "local quest giver in masyaf brotherhood - gatherers")
        ),
        Quest(
            id = "CH3-056",
            chapter = 3,
            playOrder = 56,
            title = "Noises in the Night",
            category = "Masyaf Brotherhood - Gatherers",
            giver = "Balam",
            location = "Masyaf Brotherhood - Gatherers",
            prerequisites = "Act 3; complete Swampweed for Balam.",
            summary = "Investigate a cave's midnight disturbances by slipping through a door as a meatbug.",
            walkthroughSteps = listOf("Ask Balam about the strange noises coming from the cave at night.", "After midnight, go to the cave, take the Meatbug Transformation scroll lying on a barrel and transform near the door.", "Crawl toward the locked door until the journal updates, change back and open the door.", "Defeat the spectral skeleton inside and tell Balam what happened."),
            reward = "1,000 XP and ten swampweed joints.",
            warnings = "The midnight trigger and Meatbug Transformation are important; merely entering the cave during the day may not progress the quest.",
            searchTags = listOf("noises in the night", "masyaf brotherhood - gatherers", "local quest giver in masyaf brotherhood - gatherers")
        ),
        Quest(
            id = "CH3-057",
            chapter = 3,
            playOrder = 57,
            title = "Food for the Gatherers",
            category = "Masyaf Brotherhood - Gatherers",
            giver = "Balam",
            location = "Masyaf Brotherhood - Gatherers",
            prerequisites = "Act 3; complete Noises in the Night.",
            summary = "Hunt ten mountain scavengers across the lake and bring their meat to Balam.",
            walkthroughSteps = listOf("Speak with Balam about food for his swampweed gatherers.", "Circle around to the opposite side of the lake and climb the small hill where ten mountain scavengers have appeared.", "Kill the ten scavengers, collect their special meat and bring as much as possible to Balam."),
            reward = "50 XP per piece. Returning 4–9 pieces grants 75 gold; all ten grant 150 gold and an Elixir of Fall Protection.",
            warnings = "The quest meat is automatically collectable; no meat-harvesting skill is required. Return all ten for the best outcome.",
            searchTags = listOf("food for the gatherers", "masyaf brotherhood - gatherers", "local quest giver in masyaf brotherhood - gatherers")
        ),
        Quest(
            id = "CH3-058",
            chapter = 3,
            playOrder = 58,
            title = "Sheepskins for the Guards",
            category = "Masyaf Brotherhood - Gatherers",
            giver = "Tirax",
            location = "Masyaf Brotherhood - Gatherers",
            prerequisites = "Act 3; complete Food for the Gatherers.",
            summary = "Find warm animal pelts for Tirax's guards; Grimbald offers shadowbeast pelts as an alternative.",
            walkthroughSteps = listOf("Talk to Tirax about cold nights and the guards' need for pelts.", "Ask hunter Grimbald on the upland path; he offers two shadowbeast hides free for Hunters' Camp members or sells them for 200 gold each otherwise.", "Alternatively bring two sheep pelts if the shadowbeast hides cannot be obtained.", "Give Tirax the two pelts and discuss how you acquired them."),
            reward = "500 XP. Two sheep hides: 200 gold. Purchased shadowbeast hides: 800 gold. Free hunter pelts: two Elixirs of Pure Life Energy and two of Pure Magical Energy; 100 optional XP from Grimbald.",
            warnings = "The reward depends on which hides you deliver and whether you got them free as a hunter; the free-hide route gives permanent potions.",
            searchTags = listOf("sheepskins for the guards", "masyaf brotherhood - gatherers", "local quest giver in masyaf brotherhood - gatherers")
        ),
        Quest(
            id = "CH3-059",
            chapter = 3,
            playOrder = 59,
            title = "Escort Gonzales to the Pass",
            category = "Masyaf Brotherhood - Gatherers",
            giver = "Gonzales",
            location = "Masyaf Brotherhood - Gatherers",
            prerequisites = "Act 3; Missing Novices advanced until the hidden Masyaf passage opens.",
            summary = "Take Gonzales to the entrance of the newly opened passage leading to Masyaf.",
            walkthroughSteps = listOf("After opening the hidden passage with Namib's amulet, tell Gonzales in Khorinis about it.", "Return to the newly opened passage near the Brotherhood camp; Gonzales can meet you there without a continuous escort if you teleport nearby.", "Speak with Gonzales at the entrance to finish."),
            reward = "700 XP.",
            warnings = "Talk to Gonzales before entering the passage. Once inside, you may be unable to return until Masyaf is finished.",
            searchTags = listOf("escort gonzales to the pass", "masyaf brotherhood - gatherers", "local quest giver in masyaf brotherhood - gatherers")
        ),
        Quest(
            id = "CH3-060",
            chapter = 3,
            playOrder = 60,
            title = "One of Them",
            category = "Masyaf Brotherhood - Gatherers",
            giver = "Gonzales",
            location = "Masyaf Brotherhood - Gatherers",
            prerequisites = "Act 3; during Missing Novices, enter the hidden Masyaf passage with Gonzales.",
            summary = "Infiltrate Masyaf in novice robes, earn the three priors' trust, uncover the conspiracy and defeat Haniar.",
            walkthroughSteps = listOf("Navigate the caves to the outside valley and meet Gonzales at his campfire. Choose the undercover plan rather than the direct assault to preserve the side quests and training.", "Rest until about 07:00–08:00, then ambush the novice escorting a slave on the path between Osair's cave and the Masyaf temple.", "Wear the novice's Masyaf clothes and UNEQUIP YOUR SHIELD. Avoid talking freely to guards or residents until someone invites you or you become a Shadow.", "Take the captive to Nrozas in the temple's left corridor and speak only through the prescribed nodding dialogue; return to Gonzales.", "Complete Nrozas's, Osair's and Tiamant's tasks to become a murid to each; then accept Haniar's intrigue work and earn Masyaf Shadow status.", "Tell Gonzales of your progress; after Tiamant dies, complete Osair and Nrozas's branching poison/political storyline, ending with Dark Secrets.", "Fight through the temple with Gonzales, retrieve the mysterious scroll from the altar, invoke its words at the Beliar statue to open the inner passage.", "Loot the hidden chamber if desired, use the teleport, defeat Haniar inside and speak with Gonzales."),
            reward = "Large staged XP, access to Masyaf training and side quests; 3,000 XP after Haniar is defeated.",
            warnings = "DO NOT remove the Masyaf disguise, wear a shield, or engage random NPCs during infiltration. A direct attack forfeits much of the storyline; 30+ rhetoric is important.",
            searchTags = listOf("one of them", "masyaf brotherhood - gatherers", "local quest giver in masyaf brotherhood - gatherers")
        ),
        Quest(
            id = "CH3-061",
            chapter = 3,
            playOrder = 61,
            title = "Herb Gatherer",
            category = "Masyaf Brotherhood - Nrozas",
            giver = "Nrozas",
            location = "Masyaf Brotherhood - Nrozas",
            prerequisites = "Act 3; escort the slave to Nrozas during One of Them.",
            summary = "Gather ten healing plants and ten Seraphis herbs for Nrozas.",
            walkthroughSteps = listOf("Meet Nrozas in the Masyaf temple after delivering the captive.", "Collect ten healing plants and ten Seraphis herbs, using your inventory or gathering nearby.", "Hand over the full herb collection to Nrozas."),
            reward = "350 XP.",
            warnings = "The requirement is ten of each plant, not ten in total.",
            searchTags = listOf("herb gatherer", "masyaf brotherhood - nrozas", "local quest giver in masyaf brotherhood - nrozas")
        ),
        Quest(
            id = "CH3-062",
            chapter = 3,
            playOrder = 62,
            title = "Message to Osair",
            category = "Masyaf Brotherhood - Nrozas",
            giver = "Nrozas",
            location = "Masyaf Brotherhood - Nrozas",
            prerequisites = "Act 3; deliver the captive to Nrozas during One of Them.",
            summary = "Ask Osair for stronger slave workers and deliver his written answer to Nrozas.",
            walkthroughSteps = listOf("Accept Nrozas's request that Osair send sturdier workers.", "Visit Osair in his cave and ask him for more suitable slaves.", "Take Osair's letter and deliver it back to Nrozas."),
            reward = "100 XP after speaking to Osair; 500 XP on delivery.",
            warnings = "After completion, look for an opened letter on the bench next to Nrozas to begin Unspoken Concession.",
            searchTags = listOf("message to osair", "masyaf brotherhood - nrozas", "local quest giver in masyaf brotherhood - nrozas")
        ),
        Quest(
            id = "CH3-063",
            chapter = 3,
            playOrder = 63,
            title = "Unspoken Concession",
            category = "Masyaf Brotherhood - Nrozas",
            giver = "Osair's opened letter (automatic on reading)",
            location = "Masyaf Brotherhood - Nrozas",
            prerequisites = "Act 3; complete Message to Osair.",
            summary = "Arrange Osair's secret payment of a black cave troll pelt in exchange for stronger slaves.",
            walkthroughSteps = listOf("Find and read the opened letter on the bench near Nrozas.", "Descend into the mountain passage near the entrance to Masyaf; locate and defeat the young black cave troll.", "Take its pelt to Osair in his cave.", "Report the private agreement to Nrozas, who makes you his murid."),
            reward = "1,000 XP from Osair; 500 XP from Nrozas and murid status.",
            warnings = "The quest starts from the letter, not Nrozas's initial spoken dialogue. Learn trophy harvesting before hunting if necessary.",
            searchTags = listOf("unspoken concession", "masyaf brotherhood - nrozas", "local quest giver in masyaf brotherhood - nrozas")
        ),
        Quest(
            id = "CH3-064",
            chapter = 3,
            playOrder = 64,
            title = "Ingredients for Nrozas",
            category = "Masyaf Brotherhood - Nrozas",
            giver = "Nrozas",
            location = "Masyaf Brotherhood - Nrozas",
            prerequisites = "Act 3; during Payment for the Slaves, when Hasim requests wine.",
            summary = "Fetch Nrozas's ingredient parcel from the temple storeroom, then supply twenty pieces of sulfur.",
            walkthroughSteps = listOf("Ask Nrozas for the storeroom key once Hasim requests wine during Payment for the Slaves.", "Open the temple supply room, take the package and the wine needed for Hasim.", "Bring the parcel to Nrozas.", "He says the supply lacks sulfur; collect twenty sulfur pieces from the mountain passage, or use those already in inventory, and give them to him."),
            reward = "150 XP for the parcel and 500 XP for the sulfur.",
            warnings = "The storeroom access is also needed for Hasim's wine and a weapon bundle for Marius.",
            searchTags = listOf("ingredients for nrozas", "masyaf brotherhood - nrozas", "local quest giver in masyaf brotherhood - nrozas")
        ),
        Quest(
            id = "CH3-065",
            chapter = 3,
            playOrder = 65,
            title = "Pack of Black Glorks",
            category = "Masyaf Brotherhood - Osair",
            giver = "Osair",
            location = "Masyaf Brotherhood - Osair",
            prerequisites = "Act 3; Message to Osair started.",
            summary = "Kill the five black glorks grazing near Osair's cave.",
            walkthroughSteps = listOf("Speak with Osair about proving your usefulness while asking for better slaves.", "Leave his cave and search nearby for five black glorks.", "Kill all five and report the completed hunt to Osair."),
            reward = "1,000 XP.",
            warnings = "Only the specific pack by Osair's cave counts toward the quest.",
            searchTags = listOf("pack of black glorks", "masyaf brotherhood - osair", "local quest giver in masyaf brotherhood - osair")
        ),
        Quest(
            id = "CH3-066",
            chapter = 3,
            playOrder = 66,
            title = "The Conspiring Slave",
            category = "Masyaf Brotherhood - Osair",
            giver = "Osair",
            location = "Masyaf Brotherhood - Osair",
            prerequisites = "Act 3; complete Pack of Black Glorks.",
            summary = "Find the slave planning a rebellion and expose him to Osair, while learning Marius is the organizer.",
            walkthroughSteps = listOf("Osair tasks you with discovering a conspirator in his slave workforce.", "Descend the cave, obtain the access key from the guard and question the slaves twice to find the suspicious one.", "Learn that Marius in the temple is planning an uprising; speak with Marius first and agree to help him later.", "Return to the informant slave, order him to accompany you and deliver him to Osair.", "Osair executes the captive and accepts you as his murid; tell Marius what happened."),
            reward = "150 XP after exposing the informant, 700 XP on delivering him, 200 XP with Marius, plus Osair's murid recognition.",
            warnings = "Speak to Marius before handing the informant to Osair to preserve the linked Weapons for Marius side quest.",
            searchTags = listOf("the conspiring slave", "masyaf brotherhood - osair", "local quest giver in masyaf brotherhood - osair")
        ),
        Quest(
            id = "CH3-067",
            chapter = 3,
            playOrder = 67,
            title = "Weapon Bundles for Marius",
            category = "Masyaf Brotherhood - Osair",
            giver = "Marius",
            location = "Masyaf Brotherhood - Osair",
            prerequisites = "Act 3; during The Conspiring Slave; speak with Marius in the temple.",
            summary = "Collect three hidden bundles of weapons for Marius's planned slave rebellion.",
            walkthroughSteps = listOf("Ask Marius how you can support the slave uprising.", "Take the first weapon bundle from a vase in Tiamant's room.", "Find the second in the temple storeroom, accessible via Ingredients for Nrozas.", "Find the third on a shelf inside Osair's cave.", "Bring all three bundles to Marius."),
            reward = "500 XP.",
            warnings = "This is optional; the anticipated slave rebellion does not actually happen during the storyline.",
            searchTags = listOf("weapon bundles for marius", "masyaf brotherhood - osair", "local quest giver in masyaf brotherhood - osair")
        ),
        Quest(
            id = "CH3-068",
            chapter = 3,
            playOrder = 68,
            title = "Payment for the Slaves",
            category = "Masyaf Brotherhood - Osair",
            giver = "Osair",
            location = "Masyaf Brotherhood - Osair",
            prerequisites = "Act 3; complete The Conspiring Slave.",
            summary = "Deliver payments to Hasim and Narug, then cover up Narug's death with Gonzales's help.",
            walkthroughSteps = listOf("Take Osair's two wage purses for Masyaf Shadows Hasim and Narug.", "Find Hasim smoking in the temple and give him his wage. He says Narug went to see Osair.", "Talk to Gonzales and discover Narug's body after an attempted attack on him. Gonzales suggests letting Hasim accept Narug's payment.", "Pickpocket Hasim's prayer beads using the special dialogue (ordinary pickpocket training is not required).", "Ask Hasim for help with at least 30 rhetoric; he wants wine from the temple storeroom, which Nrozas opens during Ingredients for Nrozas.", "Bring the wine to Hasim, who then accepts the second purse; give the beads to Gonzales and report to Osair."),
            reward = "Staged XP: 1,000 from Hasim's first payment, 500 on learning Narug's fate, 300 for the beads, 1,000 on Hasim's cooperation and 500 from Gonzales.",
            warnings = "At least 30 rhetoric is needed for Hasim. Do not accuse or bribe him as a substitute for obtaining the wine.",
            searchTags = listOf("payment for the slaves", "masyaf brotherhood - osair", "local quest giver in masyaf brotherhood - osair")
        ),
        Quest(
            id = "CH3-069",
            chapter = 3,
            playOrder = 69,
            title = "Moon Blades",
            category = "Masyaf Brotherhood - Osair",
            giver = "Osair",
            location = "Masyaf Brotherhood - Osair",
            prerequisites = "Chapter 3; complete earlier quests in the same area/faction if the dialogue is not yet available.",
            summary = "Treat Masyaf as a chained storyline: exhaust dialogue with the local leaders and slaves before killing or freeing anyone, because later quests depend on earlier outcomes.",
            walkthroughSteps = listOf("Treat Masyaf as a chained storyline: exhaust dialogue with the local leaders and slaves before killing or freeing anyone, because later quests depend on earlier outcomes. Start this quest in Masyaf Brotherhood - Osair and exhaust the new dialogue connected with \"Moon Blades\". Follow the dialogue chain for \"Moon Blades\" in Masyaf Brotherhood - Osair. Speak to the quest giver and every newly mentioned NPC, inspect the locations or objects added to the journal, and complete the objective that causes the journal to update. Return to the relevant giver/contact after each major update; if no new dialogue appears, complete earlier quests in the same area or faction and check again."),
            reward = "Reward varies by quest/build; exact values should be taken from the current in-game dialogue or source page.",
            warnings = "This is an index-guided quick solution. Exact item counts, coordinates and reward values can differ with New Balance updates; use the linked source record when a build-specific detail matters.",
            searchTags = listOf("moon blades", "masyaf brotherhood - osair", "local quest giver in masyaf brotherhood - osair")
        ),
        Quest(
            id = "CH3-070",
            chapter = 3,
            playOrder = 70,
            title = "Loyal People",
            category = "Masyaf Brotherhood - Osair",
            giver = "Osair",
            location = "Masyaf Brotherhood - Osair",
            prerequisites = "Chapter 3; complete earlier quests in the same area/faction if the dialogue is not yet available.",
            summary = "Treat Masyaf as a chained storyline: exhaust dialogue with the local leaders and slaves before killing or freeing anyone, because later quests depend on earlier outcomes.",
            walkthroughSteps = listOf("Treat Masyaf as a chained storyline: exhaust dialogue with the local leaders and slaves before killing or freeing anyone, because later quests depend on earlier outcomes. Start this quest in Masyaf Brotherhood - Osair and exhaust the new dialogue connected with \"Loyal People\". Follow the dialogue chain for \"Loyal People\" in Masyaf Brotherhood - Osair. Speak to the quest giver and every newly mentioned NPC, inspect the locations or objects added to the journal, and complete the objective that causes the journal to update. Return to the relevant giver/contact after each major update; if no new dialogue appears, complete earlier quests in the same area or faction and check again."),
            reward = "Reward varies by quest/build; exact values should be taken from the current in-game dialogue or source page.",
            warnings = "This is an index-guided quick solution. Exact item counts, coordinates and reward values can differ with New Balance updates; use the linked source record when a build-specific detail matters.",
            searchTags = listOf("loyal people", "masyaf brotherhood - osair", "local quest giver in masyaf brotherhood - osair")
        ),
        Quest(
            id = "CH3-071",
            chapter = 3,
            playOrder = 71,
            title = "Deadly Hunt",
            category = "Masyaf Brotherhood - Tiamant",
            giver = "Tiamant",
            location = "Masyaf Brotherhood - Tiamant",
            prerequisites = "Chapter 3; complete earlier quests in the same area/faction if the dialogue is not yet available.",
            summary = "Core objective: defeat the target(s) named by the quest and return with any proof/trophy the giver requests.",
            walkthroughSteps = listOf("Core objective: defeat the target(s) named by the quest and return with any proof/trophy the giver requests. Treat Masyaf as a chained storyline: exhaust dialogue with the local leaders and slaves before killing or freeing anyone, because later quests depend on earlier outcomes. Start this quest in Masyaf Brotherhood - Tiamant and exhaust the new dialogue connected with \"Deadly Hunt\". Get the target description from the quest giver, then travel through Masyaf Brotherhood - Tiamant to the marked or described hunting area. Defeat the enemies or named target associated with \"Deadly Hunt\", loot all bodies for proof/items, and search the immediate area for a journal-triggering object. Return to the quest giver and report the kill/clearing only after the objective counter or journal text has updated."),
            reward = "Reward varies by quest/build; exact values should be taken from the current in-game dialogue or source page.",
            warnings = "Named enemies frequently carry keys, notes or trophies used by another quest. Loot them before leaving the area.",
            searchTags = listOf("deadly hunt", "masyaf brotherhood - tiamant", "local quest giver in masyaf brotherhood - tiamant")
        ),
        Quest(
            id = "CH3-072",
            chapter = 3,
            playOrder = 72,
            title = "Uninvited Guests",
            category = "Masyaf Brotherhood - Tiamant",
            giver = "Tiamant",
            location = "Masyaf Brotherhood - Tiamant",
            prerequisites = "Chapter 3; complete earlier quests in the same area/faction if the dialogue is not yet available.",
            summary = "Treat Masyaf as a chained storyline: exhaust dialogue with the local leaders and slaves before killing or freeing anyone, because later quests depend on earlier outcomes.",
            walkthroughSteps = listOf("Treat Masyaf as a chained storyline: exhaust dialogue with the local leaders and slaves before killing or freeing anyone, because later quests depend on earlier outcomes. Start this quest in Masyaf Brotherhood - Tiamant and exhaust the new dialogue connected with \"Uninvited Guests\". Question the quest giver and every NPC they mention, then investigate the nearby location in Masyaf Brotherhood - Tiamant. Resolve the concrete cause behind \"Uninvited Guests\" - usually a person, creature, stolen item or dispute - and return once the journal records the result. If several dialogue solutions are offered, finish optional conversations before choosing the final resolution."),
            reward = "Reward varies by quest/build; exact values should be taken from the current in-game dialogue or source page.",
            warnings = "Many New Balance side quests chain into later content, so favor dialogue/investigation over immediately killing a named NPC.",
            searchTags = listOf("uninvited guests", "masyaf brotherhood - tiamant", "local quest giver in masyaf brotherhood - tiamant")
        ),
        Quest(
            id = "CH3-073",
            chapter = 3,
            playOrder = 73,
            title = "Kill Hasim",
            category = "Masyaf Brotherhood - Tiamant",
            giver = "Tiamant",
            location = "Masyaf Brotherhood - Tiamant",
            prerequisites = "Chapter 3; complete earlier quests in the same area/faction if the dialogue is not yet available.",
            summary = "Core objective: defeat the target(s) named by the quest and return with any proof/trophy the giver requests.",
            walkthroughSteps = listOf("Core objective: defeat the target(s) named by the quest and return with any proof/trophy the giver requests. Treat Masyaf as a chained storyline: exhaust dialogue with the local leaders and slaves before killing or freeing anyone, because later quests depend on earlier outcomes. Start this quest in Masyaf Brotherhood - Tiamant and exhaust the new dialogue connected with \"Kill Hasim\". Get the target description from the quest giver, then travel through Masyaf Brotherhood - Tiamant to the marked or described hunting area. Defeat the enemies or named target associated with \"Kill Hasim\", loot all bodies for proof/items, and search the immediate area for a journal-triggering object. Return to the quest giver and report the kill/clearing only after the objective counter or journal text has updated."),
            reward = "Reward varies by quest/build; exact values should be taken from the current in-game dialogue or source page.",
            warnings = "Named enemies frequently carry keys, notes or trophies used by another quest. Loot them before leaving the area.",
            searchTags = listOf("kill hasim", "masyaf brotherhood - tiamant", "local quest giver in masyaf brotherhood - tiamant")
        ),
        Quest(
            id = "CH3-074",
            chapter = 3,
            playOrder = 74,
            title = "Clear the Mine",
            category = "Masyaf Brotherhood - Tiamant",
            giver = "Tiamant",
            location = "Masyaf Brotherhood - Tiamant",
            prerequisites = "Chapter 3; complete earlier quests in the same area/faction if the dialogue is not yet available.",
            summary = "Core objective: defeat the target(s) named by the quest and return with any proof/trophy the giver requests.",
            walkthroughSteps = listOf("Core objective: defeat the target(s) named by the quest and return with any proof/trophy the giver requests. Treat Masyaf as a chained storyline: exhaust dialogue with the local leaders and slaves before killing or freeing anyone, because later quests depend on earlier outcomes. Start this quest in Masyaf Brotherhood - Tiamant and exhaust the new dialogue connected with \"Clear the Mine\". Get the target description from the quest giver, then travel through Masyaf Brotherhood - Tiamant to the marked or described hunting area. Defeat the enemies or named target associated with \"Clear the Mine\", loot all bodies for proof/items, and search the immediate area for a journal-triggering object. Return to the quest giver and report the kill/clearing only after the objective counter or journal text has updated."),
            reward = "Reward varies by quest/build; exact values should be taken from the current in-game dialogue or source page.",
            warnings = "Named enemies frequently carry keys, notes or trophies used by another quest. Loot them before leaving the area.",
            searchTags = listOf("clear the mine", "masyaf brotherhood - tiamant", "local quest giver in masyaf brotherhood - tiamant")
        ),
        Quest(
            id = "CH3-075",
            chapter = 3,
            playOrder = 75,
            title = "Intrigues of the Masyaf Brotherhood",
            category = "Masyaf Brotherhood - Tiamant",
            giver = "Tiamant",
            location = "Masyaf Brotherhood - Tiamant",
            prerequisites = "Chapter 3; complete earlier quests in the same area/faction if the dialogue is not yet available.",
            summary = "Treat Masyaf as a chained storyline: exhaust dialogue with the local leaders and slaves before killing or freeing anyone, because later quests depend on earlier outcomes.",
            walkthroughSteps = listOf("Treat Masyaf as a chained storyline: exhaust dialogue with the local leaders and slaves before killing or freeing anyone, because later quests depend on earlier outcomes. Start this quest in Masyaf Brotherhood - Tiamant and exhaust the new dialogue connected with \"Intrigues of the Masyaf Brotherhood\". Follow the dialogue chain for \"Intrigues of the Masyaf Brotherhood\" in Masyaf Brotherhood - Tiamant. Speak to the quest giver and every newly mentioned NPC, inspect the locations or objects added to the journal, and complete the objective that causes the journal to update. Return to the relevant giver/contact after each major update; if no new dialogue appears, complete earlier quests in the same area or faction and check again."),
            reward = "Reward varies by quest/build; exact values should be taken from the current in-game dialogue or source page.",
            warnings = "This is an index-guided quick solution. Exact item counts, coordinates and reward values can differ with New Balance updates; use the linked source record when a build-specific detail matters.",
            searchTags = listOf("intrigues of the masyaf brotherhood", "masyaf brotherhood - tiamant", "local quest giver in masyaf brotherhood - tiamant")
        ),
        Quest(
            id = "CH3-076",
            chapter = 3,
            playOrder = 76,
            title = "Gold Mine",
            category = "Masyaf Brotherhood - Tiamant",
            giver = "Tiamant",
            location = "Masyaf Brotherhood - Tiamant",
            prerequisites = "Chapter 3; complete earlier quests in the same area/faction if the dialogue is not yet available.",
            summary = "Treat Masyaf as a chained storyline: exhaust dialogue with the local leaders and slaves before killing or freeing anyone, because later quests depend on earlier outcomes.",
            walkthroughSteps = listOf("Treat Masyaf as a chained storyline: exhaust dialogue with the local leaders and slaves before killing or freeing anyone, because later quests depend on earlier outcomes. Start this quest in Masyaf Brotherhood - Tiamant and exhaust the new dialogue connected with \"Gold Mine\". Speak with all merchants/debtors named by the quest and use the available dialogue, payment or persuasion options. Collect the money, goods or signed agreement required by \"Gold Mine\", then return it to the quest giver in Masyaf Brotherhood - Tiamant. If you are offered several settlement choices, resolve the related side quests first so you do not lose a better outcome."),
            reward = "Reward varies by quest/build; exact values should be taken from the current in-game dialogue or source page.",
            warnings = "Commercial quests often branch according to who you support. Save before handing over unique ledgers, contracts or large payments.",
            searchTags = listOf("gold mine", "masyaf brotherhood - tiamant", "local quest giver in masyaf brotherhood - tiamant")
        ),
        Quest(
            id = "CH3-077",
            chapter = 3,
            playOrder = 77,
            title = "Escort the Slaves to the Mine",
            category = "Masyaf Brotherhood - Tiamant",
            giver = "Tiamant",
            location = "Masyaf Brotherhood - Tiamant",
            prerequisites = "Chapter 3; complete earlier quests in the same area/faction if the dialogue is not yet available.",
            summary = "Core objective: get the relevant NPC safely to the destination and trigger the arrival dialogue.",
            walkthroughSteps = listOf("Core objective: get the relevant NPC safely to the destination and trigger the arrival dialogue. Treat Masyaf as a chained storyline: exhaust dialogue with the local leaders and slaves before killing or freeing anyone, because later quests depend on earlier outcomes. Start this quest in Masyaf Brotherhood - Tiamant and exhaust the new dialogue connected with \"Escort the Slaves to the Mine\". Speak to the person who needs to travel, clear the route before starting the escort if possible, then accompany them through Masyaf Brotherhood - Tiamant to the destination named by the quest. Stay close enough for escort dialogue/triggers to fire and deal with enemies that block the route. At the destination, speak with the escorted NPC and then report back if the journal remains open."),
            reward = "Reward varies by quest/build; exact values should be taken from the current in-game dialogue or source page.",
            warnings = "Save before starting long escorts. If the NPC stops, clear nearby enemies, move back toward them, and trigger any pending dialogue before continuing.",
            searchTags = listOf("escort the slaves to the mine", "masyaf brotherhood - tiamant", "local quest giver in masyaf brotherhood - tiamant")
        ),
        Quest(
            id = "CH3-078",
            chapter = 3,
            playOrder = 78,
            title = "Nrozas's Triumph",
            category = "Masyaf Brotherhood - Tiamant",
            giver = "Tiamant",
            location = "Masyaf Brotherhood - Tiamant",
            prerequisites = "Chapter 3; complete earlier quests in the same area/faction if the dialogue is not yet available.",
            summary = "Treat Masyaf as a chained storyline: exhaust dialogue with the local leaders and slaves before killing or freeing anyone, because later quests depend on earlier outcomes.",
            walkthroughSteps = listOf("Treat Masyaf as a chained storyline: exhaust dialogue with the local leaders and slaves before killing or freeing anyone, because later quests depend on earlier outcomes. Start this quest in Masyaf Brotherhood - Tiamant and exhaust the new dialogue connected with \"Nrozas's Triumph\". Follow the dialogue chain for \"Nrozas's Triumph\" in Masyaf Brotherhood - Tiamant. Speak to the quest giver and every newly mentioned NPC, inspect the locations or objects added to the journal, and complete the objective that causes the journal to update. Return to the relevant giver/contact after each major update; if no new dialogue appears, complete earlier quests in the same area or faction and check again."),
            reward = "Reward varies by quest/build; exact values should be taken from the current in-game dialogue or source page.",
            warnings = "This is an index-guided quick solution. Exact item counts, coordinates and reward values can differ with New Balance updates; use the linked source record when a build-specific detail matters.",
            searchTags = listOf("nrozas's triumph", "masyaf brotherhood - tiamant", "local quest giver in masyaf brotherhood - tiamant")
        ),
        Quest(
            id = "CH3-079",
            chapter = 3,
            playOrder = 79,
            title = "Gift of Fate",
            category = "Masyaf Brotherhood - Tiamant",
            giver = "Tiamant",
            location = "Masyaf Brotherhood - Tiamant",
            prerequisites = "Chapter 3; complete earlier quests in the same area/faction if the dialogue is not yet available.",
            summary = "Treat Masyaf as a chained storyline: exhaust dialogue with the local leaders and slaves before killing or freeing anyone, because later quests depend on earlier outcomes.",
            walkthroughSteps = listOf("Treat Masyaf as a chained storyline: exhaust dialogue with the local leaders and slaves before killing or freeing anyone, because later quests depend on earlier outcomes. Start this quest in Masyaf Brotherhood - Tiamant and exhaust the new dialogue connected with \"Gift of Fate\". Follow the dialogue chain for \"Gift of Fate\" in Masyaf Brotherhood - Tiamant. Speak to the quest giver and every newly mentioned NPC, inspect the locations or objects added to the journal, and complete the objective that causes the journal to update. Return to the relevant giver/contact after each major update; if no new dialogue appears, complete earlier quests in the same area or faction and check again."),
            reward = "Reward varies by quest/build; exact values should be taken from the current in-game dialogue or source page.",
            warnings = "This is an index-guided quick solution. Exact item counts, coordinates and reward values can differ with New Balance updates; use the linked source record when a build-specific detail matters.",
            searchTags = listOf("gift of fate", "masyaf brotherhood - tiamant", "local quest giver in masyaf brotherhood - tiamant")
        ),
        Quest(
            id = "CH3-080",
            chapter = 3,
            playOrder = 80,
            title = "Duel of Truth",
            category = "Masyaf Brotherhood - Tiamant",
            giver = "Tiamant",
            location = "Masyaf Brotherhood - Tiamant",
            prerequisites = "Chapter 3; complete earlier quests in the same area/faction if the dialogue is not yet available.",
            summary = "Treat Masyaf as a chained storyline: exhaust dialogue with the local leaders and slaves before killing or freeing anyone, because later quests depend on earlier outcomes.",
            walkthroughSteps = listOf("Treat Masyaf as a chained storyline: exhaust dialogue with the local leaders and slaves before killing or freeing anyone, because later quests depend on earlier outcomes. Start this quest in Masyaf Brotherhood - Tiamant and exhaust the new dialogue connected with \"Duel of Truth\". Speak with the challenger/trainer in Masyaf Brotherhood - Tiamant and accept the test. Complete the combat, hunting, skill or dialogue condition described in the journal, then speak to the same NPC again for recognition. If the challenge has several opponents or stages, finish them in the order offered and heal/save between stages."),
            reward = "Reward varies by quest/build; exact values should be taken from the current in-game dialogue or source page.",
            warnings = "Some tests are non-lethal; avoid finishing a downed human opponent unless the quest specifically requires a kill.",
            searchTags = listOf("duel of truth", "masyaf brotherhood - tiamant", "local quest giver in masyaf brotherhood - tiamant")
        ),
        Quest(
            id = "CH3-081",
            chapter = 3,
            playOrder = 81,
            title = "Offerings to Haniar",
            category = "Masyaf Brotherhood - Tiamant",
            giver = "Tiamant",
            location = "Masyaf Brotherhood - Tiamant",
            prerequisites = "Chapter 3; complete earlier quests in the same area/faction if the dialogue is not yet available.",
            summary = "Treat Masyaf as a chained storyline: exhaust dialogue with the local leaders and slaves before killing or freeing anyone, because later quests depend on earlier outcomes.",
            walkthroughSteps = listOf("Treat Masyaf as a chained storyline: exhaust dialogue with the local leaders and slaves before killing or freeing anyone, because later quests depend on earlier outcomes. Start this quest in Masyaf Brotherhood - Tiamant and exhaust the new dialogue connected with \"Offerings to Haniar\". Ask the quest giver for all available clues, then search Masyaf Brotherhood - Tiamant and the locations mentioned in the journal for the named object connected with \"Offerings to Haniar\". Check corpses, locked chests, shelves, caves and camp interiors, and read any notes you find because they often advance the objective. Take the item to the intended owner/quest giver and continue the dialogue until the journal closes."),
            reward = "Reward varies by quest/build; exact values should be taken from the current in-game dialogue or source page.",
            warnings = "Unique equipment can be tied to several quests. Do not sell, forge away or discard it before checking all related dialogue.",
            searchTags = listOf("offerings to haniar", "masyaf brotherhood - tiamant", "local quest giver in masyaf brotherhood - tiamant")
        ),
        Quest(
            id = "CH3-082",
            chapter = 3,
            playOrder = 82,
            title = "Price of Betrayal",
            category = "Masyaf Brotherhood - Tiamant",
            giver = "Tiamant",
            location = "Masyaf Brotherhood - Tiamant",
            prerequisites = "Chapter 3; complete earlier quests in the same area/faction if the dialogue is not yet available.",
            summary = "Treat Masyaf as a chained storyline: exhaust dialogue with the local leaders and slaves before killing or freeing anyone, because later quests depend on earlier outcomes.",
            walkthroughSteps = listOf("Treat Masyaf as a chained storyline: exhaust dialogue with the local leaders and slaves before killing or freeing anyone, because later quests depend on earlier outcomes. Start this quest in Masyaf Brotherhood - Tiamant and exhaust the new dialogue connected with \"Price of Betrayal\". Follow the dialogue chain for \"Price of Betrayal\" in Masyaf Brotherhood - Tiamant. Speak to the quest giver and every newly mentioned NPC, inspect the locations or objects added to the journal, and complete the objective that causes the journal to update. Return to the relevant giver/contact after each major update; if no new dialogue appears, complete earlier quests in the same area or faction and check again."),
            reward = "Reward varies by quest/build; exact values should be taken from the current in-game dialogue or source page.",
            warnings = "This is an index-guided quick solution. Exact item counts, coordinates and reward values can differ with New Balance updates; use the linked source record when a build-specific detail matters.",
            searchTags = listOf("price of betrayal", "masyaf brotherhood - tiamant", "local quest giver in masyaf brotherhood - tiamant")
        ),
        Quest(
            id = "CH3-083",
            chapter = 3,
            playOrder = 83,
            title = "Dark Secrets",
            category = "Masyaf Brotherhood - Tiamant",
            giver = "Tiamant",
            location = "Masyaf Brotherhood - Tiamant",
            prerequisites = "Chapter 3; complete earlier quests in the same area/faction if the dialogue is not yet available.",
            summary = "Treat Masyaf as a chained storyline: exhaust dialogue with the local leaders and slaves before killing or freeing anyone, because later quests depend on earlier outcomes.",
            walkthroughSteps = listOf("Treat Masyaf as a chained storyline: exhaust dialogue with the local leaders and slaves before killing or freeing anyone, because later quests depend on earlier outcomes. Start this quest in Masyaf Brotherhood - Tiamant and exhaust the new dialogue connected with \"Dark Secrets\". Collect the exposition from the quest giver, then explore the quest location in Masyaf Brotherhood - Tiamant rather than relying only on combat. For \"Dark Secrets\", inspect switches, inscriptions, books, keys, corpses and unusual interactable objects; read every quest note before operating the next mechanism. When the puzzle/ritual or exploration objective updates, return to the associated scholar, mage or faction contact for the next step."),
            reward = "Reward varies by quest/build; exact values should be taken from the current in-game dialogue or source page.",
            warnings = "Make a manual save before using one-way portals, ritual objects or major temple mechanisms.",
            searchTags = listOf("dark secrets", "masyaf brotherhood - tiamant", "local quest giver in masyaf brotherhood - tiamant")
        )
    )
}
