package com.sliverzfx.gothicquest

object NewBalanceChapter4Data {
    val quests = listOf(
        Quest(
            id = "CH4-001",
            chapter = 4,
            playOrder = 1,
            title = "Dragon Hunt",
            category = "Chapter 4",
            giver = "Pyrokar",
            location = "Chapter 4",
            prerequisites = "The Eye of Innos has been restored; Chapter 4 begins.",
            summary = "Use the restored Eye of Innos to confront the four dragons in the Valley of Mines, charging it between kills.",
            walkthroughSteps = listOf("After the Eye of Innos ritual, ask Pyrokar how to use the amulet; travel to the Valley of Mines and speak to Garond (500 XP) and Oric for dragon locations.", "Keep the charged Eye in your inventory before speaking to each dragon; you do not need to wear it. Defeat the dragon's summoned elementals promptly because they help it regenerate.", "Recommended order: swamp dragon Pandrodor in the swamp near Cavalorn's old hut (Cypher and Rod may assist), stone dragon Pedrakhan at the ruined Stone Fortress, fire dragon Feomathar in the volcanic crater, then ice dragon Finkregh in the ruins of the former New Camp.", "After each dragon dies, loot its heart and hoard; at an alchemy table recharge the Eye using the heart under the special-potions tab before confronting the next dragon.", "Return to Garond to report each dragon's death. After all four, make the final report to Garond to complete the hunt and advance toward Chapter 5.", "Optionally tell Kurgan, Milten, Pyrokar, Vatras, Lord Hagen and Netbek about the dragons for extra dialogue XP."),
            reward = "500 XP for Garond's first briefing; 5,000 XP and 1,000 gold per dragon reported, plus 5,000 XP for defeating all four. Additional report XP is available from Kurgan (100), Milten (500), Pyrokar (2,000), Vatras (500), Hagen (1,000) and Netbek (1,000).",
            warnings = "A charged Eye must be in your inventory when you SPEAK to each dragon, not equipped. Recharge at an alchemy table with the dragon's heart after each kill; kill spawned elementals to curb dragon regeneration.",
            searchTags = listOf("dragon hunt", "chapter 4", "pyrokar")
        ),
        Quest(
            id = "CH4-002",
            chapter = 4,
            playOrder = 2,
            title = "Lobart's Orc Problem",
            category = "Chapter 4",
            giver = "Lobart",
            location = "Chapter 4",
            prerequisites = "Chapter 4; return to Lobart's farm after the orc invasion begins.",
            summary = "Kill the orcs that have overrun Lobart's farm in Chapter 4 and report to him.",
            walkthroughSteps = listOf("Ask Lobart about the orcs that have invaded his farm during Chapter 4.", "Clear all the orcs threatening the farm and nearby farm approaches; check for survivors before returning.", "Tell Lobart the orcs are gone to receive your payment."),
            reward = "1,000 XP and 100 gold from Lobart after clearing the orcs.",
            warnings = "Orc patrols in Chapter 4 can overlap with lizardmen guarding dragon eggs. Search the bodies and nearby caves instead of leaving immediately after the combat.",
            searchTags = listOf("lobart's orc problem", "chapter 4", "lobart")
        ),
        Quest(
            id = "CH4-003",
            chapter = 4,
            playOrder = 3,
            title = "Orc Squads",
            category = "Chapter 4",
            giver = "Lord Hagen",
            location = "Chapter 4",
            prerequisites = "Chapter 4; the orc invasion of Khorinis has begun.",
            summary = "Defeat the Orc Squad commander near Bartok's hunting forest and turn in more than twenty orc-elder rings to Lord Hagen.",
            walkthroughSteps = listOf("In Chapter 4, speak with Lord Hagen in Khorinis and show an orc elder's ring (300 XP). Hagen assigns the orc squads.", "Ask Ingmar about the commander, then leave through the south gate toward the wooded route used while hunting with Bartok.", "Go through the forest to the cave where Kriks the Razor's bandits were camped; kill the elite orcs and their commander Fangarh, and take his military map.", "Report Fangarh's defeat to Ingmar for 1,500 XP and 500 gold.", "Use the map to find the Orc elder patrols scattered around Khorinis. Collect more than twenty leader rings and deliver them to Hagen to close the quest.", "Hagen continues taking remaining rings for 200 XP each after completion. Reserve one ring for Dar's The Braggart if you plan that route."),
            reward = "300 XP for showing Hagen an early elder ring; 1,500 XP and 500 gold from Ingmar after killing Fangarh; main quest closes once Hagen receives over twenty elder rings; additional rings earn 200 XP each. An optional initial orc conversation grants 100 XP.",
            warnings = "Save at least one Orc Warlord's/elder's ring for Dar's The Braggart quest if available. Fangarh's map reveals additional patrol locations.",
            searchTags = listOf("orc squads", "chapter 4", "lord hagen / ingmar")
        ),
        Quest(
            id = "CH4-004",
            chapter = 4,
            playOrder = 4,
            title = "News for Vatras",
            category = "Chapter 4",
            giver = "Saturas (Vatras directs the visit)",
            location = "Chapter 4",
            prerequisites = "After the Eye of Innos restoration ritual, then Chapter 4 to complete Saturas's Orcs in the Valley quest.",
            summary = "Check on Saturas in Jharkendar for Vatras, defeat the orc occupation and report back.",
            walkthroughSteps = listOf("After restoring the Eye of Innos, speak to Vatras; he asks you to visit Saturas and check on the Water Mages.", "Begin Chapter 4 and travel through the portal to Jharkendar. Speak to Saturas about the valley's orc invasion.", "Complete Saturas's Orcs in the Valley quest by clearing the occupation.", "Return to Khorinis and tell Vatras that the Water Mages are safe."),
            reward = "1,000 XP and 300 gold from Vatras.",
            warnings = "The initial request can be received after restoring the Eye, but Jharkendar's invasion does not begin until Chapter 4. Finish Orcs in the Valley before reporting.",
            searchTags = listOf("news for vatras", "chapter 4", "vatras")
        ),
        Quest(
            id = "CH4-005",
            chapter = 4,
            playOrder = 5,
            title = "Deprivation",
            category = "Chapter 4",
            giver = "Randolph",
            location = "Chapter 4",
            prerequisites = "Chapter 4; paladin only. Randolph must be alive and at Akil's farm.",
            summary = "Find Sagitta's remedy to help Randolph stop drinking.",
            walkthroughSteps = listOf("As a paladin in Chapter 4, speak with Randolph at Akil's farm about his attempt to quit drinking.", "Visit Sagitta's cave and pay 300 gold for her anti-addiction medicine.", "Bring the medicine to Randolph and speak with him again."),
            reward = "500 XP and 150 gold from Randolph. Sagitta's potion costs 300 gold.",
            warnings = "The April 2026 New Balance guide restricts this quest to paladins; buying the cure has a 300-gold cost and yields a net loss of 150 gold.",
            searchTags = listOf("deprivation", "chapter 4", "randolph")
        ),
        Quest(
            id = "CH4-006",
            chapter = 4,
            playOrder = 6,
            title = "Dragon Eggs",
            category = "Chapter 4",
            giver = "Bennet",
            location = "Chapter 4",
            prerequisites = "Chapter 4; obtain a dragon egg and speak with Bennet. Primarily associated with the mercenary/Dragon Hunter route.",
            summary = "Collect dragon eggs from lizardmen-guarded caves, deciding whether to sell them to Bennet or preserve them for the powerful Irdorath potion.",
            walkthroughSteps = listOf("Show Bennet a dragon egg and agree to discuss selling them. He gives you information/a map for the Khorinis caves where eggs can be found. Search the marked caves, kill the lizardmen guarding them and collect the eggs. Bennet will buy the eggs you bring back."),
            reward = "Bennet offers 350 gold and 300 XP for each dragon egg sold. An Irdorath recipe consumes nine eggs per Embarla Firgasto potion; each dose grants warriors +10 Strength or Dexterity, or mages +20 Mana (up to four potions with enough eggs).",
            warnings = "If you intend to brew Embarla Firgasto in Chapter 6, KEEP your eggs: the recipe takes nine per potion and up to four potions can be made. Selling eggs to Bennet is irreversible.",
            searchTags = listOf("dragon eggs", "chapter 4", "bennet")
        ),
        Quest(
            id = "CH4-007",
            chapter = 4,
            playOrder = 7,
            title = "The Braggart",
            category = "Chapter 4",
            giver = "Dar",
            location = "Chapter 4",
            prerequisites = "Chapter 4; Dar alive. The orc-ring route is unavailable to paladins.",
            summary = "Either help Dar boast with an Orc elder's ring or laugh at him and win a fistfight.",
            walkthroughSteps = listOf("Speak to Dar at Onar's farm in Chapter 4.", "If you ask what would impress Lee, Dar requests an orc warlord/elder ring taken from a black-orc leader. Reserve one from Orc Squads and give it to him.", "Choose between the Dexterity Amulet reward or a small gold payment.", "Alternatively, mock Dar instead of helping him; defeat him in the resulting duel to end the quest for a smaller XP reward."),
            reward = "Ring route: Dexterity Amulet and 600 XP, OR 120 gold and 500 XP. Mock/fight route: 100 XP after winning the duel.",
            warnings = "Paladins cannot take the ring-delivery route. The reward is 120 gold, not 1,200; the duel is a distinct route.",
            searchTags = listOf("the braggart", "chapter 4", "dar")
        ),
        Quest(
            id = "CH4-008",
            chapter = 4,
            playOrder = 8,
            title = "A Dragon Egg for Neoras",
            category = "Chapter 4",
            giver = "Neoras",
            location = "Chapter 4",
            prerequisites = "Chapter 4; access to the monastery and at least one dragon egg.",
            summary = "Speak with Neoras and give him one dragon egg for his experiment.",
            walkthroughSteps = listOf("Speak with Neoras and give him one dragon egg for his experiment. After handing it over, allow several in-game days to pass and return to him. He will finish the brew and give you the resulting potion."),
            reward = "The New Balance community guide states that Neoras' completed potion permanently grants +3 Strength.",
            warnings = "Set aside one egg for Neoras before deciding what to do with Bennet's Dragon Eggs quest. Do not sell every egg immediately.",
            searchTags = listOf("a dragon egg for neoras", "chapter 4", "neoras")
        ),
        Quest(
            id = "CH4-009",
            chapter = 4,
            playOrder = 9,
            title = "Ragnar's Trial",
            category = "Chapter 4",
            giver = "Ragnar",
            location = "Chapter 4",
            prerequisites = "Complete Neoras's Assistant from Chapter 2 and reach Chapter 4.",
            summary = "Speak with Ragnar.",
            walkthroughSteps = listOf("Speak with Ragnar. He asks for a Fire Bolt rune. The community guide points to the rune found earlier in the chest at Sekob's farm during the main-story progression. Bring that rune to Ragnar and complete the dialogue."),
            reward = "Ragnar's quest reward and access to Secrets of the Old Book.",
            warnings = "If you sold or misplaced unique runes, check merchants and storage before assuming the quest is broken.",
            searchTags = listOf("ragnar's trial", "chapter 4", "ragnar")
        ),
        Quest(
            id = "CH4-010",
            chapter = 4,
            playOrder = 10,
            title = "Secrets of the Old Book",
            category = "Chapter 4",
            giver = "Ragnar / Ragnar's book",
            location = "Chapter 4",
            prerequisites = "Complete Ragnar's Trial and read the book he gives you.",
            summary = "Read Ragnar's book.",
            walkthroughSteps = listOf("Read Ragnar's book. It describes a wand capable of summoning a dragon and points toward Amon Shen, the tower associated with the Dark Golem/Necronomicon. Search the tower and read the note naming Kreol, then speak with Kreol. The wand requires four fragments: one from the necromancer in the Sleeper Temple, one from Cor Kalom during the Assassin Forest storyline, one from Shadow Lord Inubis (available in Chapter 5), and the final fragment from Kreol after the other three are collected. Kreol also requires four dragon skulls and one dragon eye. The eye can come from powerful dragon-related encounters such as Azgalor or Adanar, with another route tied to Ashtar. Once all materials are collected, forge the wand at an anvil."),
            reward = "The completed dragon-summoning wand.",
            warnings = "This quest starts in Chapter 4 but cannot normally be completed immediately because one fragment is tied to Chapter 5. Keep every fragment, dragon skull and dragon eye you obtain.",
            searchTags = listOf("secrets of the old book", "chapter 4", "ragnar / ragnar's book")
        ),
        Quest(
            id = "CH4-011",
            chapter = 4,
            playOrder = 11,
            title = "Lost?",
            category = "Chapter 4",
            giver = "Scout faction contact (master index)",
            location = "Chapter 4",
            prerequisites = "Chapter 4; Scout path and previous Scout progression.",
            summary = "The verified master index lists this as a Chapter 4 Scout quest, but the current public Scout walkthrough does not expose a separate matching entry under this normalized English title.",
            walkthroughSteps = listOf("The verified master index lists this as a Chapter 4 Scout quest, but the current public Scout walkthrough does not expose a separate matching entry under this normalized English title. Check Allen and the Scout base after finishing the Chapter 3 chain, read every new note/journal entry, and follow the named missing-person or missing-item lead until the journal points you back to the faction contact."),
            reward = "Not independently documented in the current public Scout walkthrough.",
            warnings = "Index-only record: do not confuse it with On the Trail of Betrayal below. This entry is deliberately marked rather than inventing unverified names, coordinates or rewards.",
            searchTags = listOf("lost?", "chapter 4", "scout faction contact (master index)")
        ),
        Quest(
            id = "CH4-012",
            chapter = 4,
            playOrder = 12,
            title = "On the Trail of Betrayal",
            category = "Chapter 4",
            giver = "Allen",
            location = "Chapter 4",
            prerequisites = "Scout path; obtain all four of Fingers' golden keys and open his treasury.",
            summary = "After the treasury is opened, Allen tells you that Nathaniel stole the Horn of Fear and escaped.",
            walkthroughSteps = listOf("After the treasury is opened, Allen tells you that Nathaniel stole the Horn of Fear and escaped. Read the note, speak with Allen and then visit Pyrokar at the monastery. Travel to the cave near the Black Troll - the Fire Trial cave - and defeat the Masters of Darkness, then the Lord of Darkness and his servants. At the end, speak with Nathaniel and decide whether to kill him or spare him. Return to Allen to close the Scout storyline."),
            reward = "Completion of the Scout Chapter 4 storyline and its associated faction rewards.",
            warnings = "Nathaniel's fate is a real choice. Make a manual save before the final conversation if you want to compare outcomes.",
            searchTags = listOf("on the trail of betrayal", "chapter 4", "allen")
        ),
        Quest(
            id = "CH4-013",
            chapter = 4,
            playOrder = 13,
            title = "Mercenaries Near the Manor",
            category = "Chapter 4",
            giver = "Demon Hunter faction contact (master index)",
            location = "Chapter 4",
            prerequisites = "Chapter 4; Demon Hunter path and earlier order quests completed.",
            summary = "The master quest index places this Chapter 4 task in the Demon Hunter line, but the current public Demon Hunter page does not contain a matching standalone walkthrough under this English title.",
            walkthroughSteps = listOf("The master quest index places this Chapter 4 task in the Demon Hunter line, but the current public Demon Hunter page does not contain a matching standalone walkthrough under this English title. Return to the manor and speak with Angel and the other order members, exhaust all new Chapter 4 dialogue, then deal with the mercenary group connected with the estate and report the result to the faction contact."),
            reward = "Not independently documented in the current public Demon Hunter walkthrough.",
            warnings = "Index-only record. The public wiki currently documents the surrounding Demon Hunter chain but not this exact title, so this guide intentionally avoids inventing a named leader, exact spawn point or reward.",
            searchTags = listOf("mercenaries near the manor", "chapter 4", "demon hunter faction contact (master index)")
        ),
        Quest(
            id = "CH4-014",
            chapter = 4,
            playOrder = 14,
            title = "Demon from the Void",
            category = "Chapter 4",
            giver = "Angel",
            location = "Chapter 4",
            prerequisites = "Demon Hunter path; sufficient faction progression to receive the Sleeper Temple assignment.",
            summary = "Angel sends you into the Sleeper Temple.",
            walkthroughSteps = listOf("Angel sends you into the Sleeper Temple. Travel to the area immediately before the Sleeper's former chamber, kill the undead novice found there and loot/read the note from the body. Return to Angel with the information to finish the task."),
            reward = "Demon Hunter faction progression; unlocks the later Lord of the Abyss sequence.",
            warnings = "Loot the corpse before leaving the temple; the note is the quest proof and can be easy to overlook after the fight.",
            searchTags = listOf("demon from the void", "chapter 4", "angel")
        ),
        Quest(
            id = "CH4-015",
            chapter = 4,
            playOrder = 15,
            title = "Lord of the Abyss",
            category = "Chapter 4",
            giver = "Angel",
            location = "Chapter 4",
            prerequisites = "Chapter 4; complete Demon from the Void, then wait until the next day.",
            summary = "Speak with Angel the day after Demon from the Void.",
            walkthroughSteps = listOf("Speak with Angel the day after Demon from the Void. Bring him two pieces of black ore. After handing them over, go with him to the ritual circle in front of the manor. Angel summons a demon and its servants; help the Demon Hunters defeat them. After the victory, Angel sends you to Lord Hagen. Report to Hagen, then return to Angel to finish the quest."),
            reward = "Major Demon Hunter faction progression and the quest rewards from Angel/Hagen.",
            warnings = "Bring the black ore before beginning the ritual sequence and make a manual save before the summoning fight.",
            searchTags = listOf("lord of the abyss", "chapter 4", "angel")
        ),
        Quest(
            id = "CH4-016",
            chapter = 4,
            playOrder = 16,
            title = "Dragon Treasures",
            category = "Chapter 4",
            giver = "Cassia",
            location = "Chapter 4",
            prerequisites = "Chapter 4; membership/progression in the Thieves' Guild.",
            summary = "Cassia is interested in special valuables hidden in the dragons' treasure hoards.",
            walkthroughSteps = listOf("Cassia is interested in special valuables hidden in the dragons' treasure hoards. Kill the four main dragons, open/search their treasure chests and collect the four special items associated with their hoards. Once all four are in your inventory, return to Cassia and hand them over."),
            reward = "Thieves' Guild reward from Cassia; exact current-build values should be read from the hand-in dialogue.",
            warnings = "Do not leave a dragon area until you have searched the treasure chest and surrounding loot. The quest is about the special hoard items, not merely killing the dragons.",
            searchTags = listOf("dragon treasures", "chapter 4", "cassia")
        ),
        Quest(
            id = "CH4-017",
            chapter = 4,
            playOrder = 17,
            title = "Orcs in the Valley",
            category = "Chapter 4",
            giver = "Saturas",
            location = "Chapter 4",
            prerequisites = "Chapter 4; return to Jharkendar and speak with Saturas.",
            summary = "Saturas explains that orcs have occupied the Valley of the Builders.",
            walkthroughSteps = listOf("Saturas explains that orcs have occupied the Valley of the Builders. Kill the five orc shamans stationed at the temple sites where you gathered the stone tablets in Chapter 2. The final leader, Ur-Catan, is in the arena where Raven was fought. Raven's ring from the earlier battle can be used for access, although the area can also be reached normally. After all leaders are dead, return to Saturas. <PARSED TEXT FOR PAGE: 7 / 10> GOTHIC II: NEW BALANCE | CHAPTER 4 QUEST GUIDE SliverzFX Guide Project | Chapter 4 | CH4-001 to CH4-030"),
            reward = "Water Mage/Jharkendar progression and Saturas' reward.",
            warnings = "Loot each shaman and verify the journal update before moving on. This quest is also the key step for News for Vatras.",
            searchTags = listOf("orcs in the valley", "chapter 4", "saturas")
        ),
        Quest(
            id = "CH4-018",
            chapter = 4,
            playOrder = 18,
            title = "Scatty's Gold",
            category = "Chapter 4",
            giver = "Scatty",
            location = "Chapter 4",
            prerequisites = "Chapter 4; Scatty and the surviving bandit/pirate-side NPCs must still be available.",
            summary = "Scatty asks you to recover his gold from the chest he used to guard in the bandit camp.",
            walkthroughSteps = listOf("Scatty asks you to recover his gold from the chest he used to guard in the bandit camp. Go to the old bandit camp, take the 500 gold nuggets from the chest and return to Scatty. Hand over his share to complete the quest."),
            reward = "Scatty gives you half of the recovered 500 nuggets, plus quest XP.",
            warnings = "Finish this in Chapter 4. The current community guide warns that Scatty becomes hostile in Chapter 5 if you keep his share and the quest is cancelled.",
            searchTags = listOf("scatty's gold", "chapter 4", "scatty")
        ),
        Quest(
            id = "CH4-019",
            chapter = 4,
            playOrder = 19,
            title = "Talbin's Escape",
            category = "Chapter 4",
            giver = "Talbin",
            location = "Chapter 4",
            prerequisites = "Chapter 4; find Talbin and ask about Engrom.",
            summary = "Talbin is worried about his missing friend Engrom.",
            walkthroughSteps = listOf("Talbin is worried about his missing friend Engrom. Engrom's body is near Cavalorn's old hut, in the area where Marcos is stationed. Tell Talbin what happened; he leaves for the pass. The community guide recommends teleporting to the pass immediately so Talbin relocates safely instead of walking through danger. Speak with him at the Valley of Mines pass. Once he reaches Khorinis, he can later be recruited to your camp."),
            reward = "Quest XP and Talbin's survival/recruitment availability.",
            warnings = "Talbin can die while travelling if the route is allowed to play out normally. Save first and use the pass/teleport transition promptly. Fire Mage runs can differ because Engrom may still be alive and possessed.",
            searchTags = listOf("talbin's escape", "chapter 4", "talbin")
        ),
        Quest(
            id = "CH4-020",
            chapter = 4,
            playOrder = 20,
            title = "Dragon Hunters",
            category = "Chapter 4",
            giver = "First Dragon Hunter encountered near the pass",
            location = "Chapter 4",
            prerequisites = "Chapter 4; enter the Valley of Mines during the dragon hunt.",
            summary = "This companion quest begins when you speak with the first Dragon Hunter you meet around the Valley pass.",
            walkthroughSteps = listOf("This companion quest begins when you speak with the first Dragon Hunter you meet around the Valley pass. Continue the main dragon-hunting route, speaking with the hunters you encounter and progressing through the Valley. The quest remains active through the hunt and closes when the last of the four main dragons is killed."),
            reward = "Quest XP when the dragon-hunter objective closes, plus normal dragon-hunt loot.",
            warnings = "This is separate from the main Dragon Hunt journal entry even though both progress together.",
            searchTags = listOf("dragon hunters", "chapter 4", "first dragon hunter encountered near the pass")
        ),
        Quest(
            id = "CH4-021",
            chapter = 4,
            playOrder = 21,
            title = "Two Ice Golems for Sylvio",
            category = "Chapter 4",
            giver = "Sylvio",
            location = "Chapter 4",
            prerequisites = "Chapter 4; reach Sylvio's camp at the entrance to the frozen region.",
            summary = "Speak with Sylvio.",
            walkthroughSteps = listOf("Speak with Sylvio. Two ice golems killed his men and block the route into the frozen territory. Kill both ice golems and return to Sylvio to report the result."),
            reward = "Quest XP and Sylvio's reward; exact values depend on the current build.",
            warnings = "After the Ice Dragon is defeated, Sylvio and Bullco will turn on you. Finish any dialogue you want with them before progressing beyond that point.",
            searchTags = listOf("two ice golems for sylvio", "chapter 4", "sylvio")
        ),
        Quest(
            id = "CH4-022",
            chapter = 4,
            playOrder = 22,
            title = "Filthy Sty",
            category = "Chapter 4",
            giver = "Brutus",
            location = "Chapter 4",
            prerequisites = "Chapter 4; access to the castle.",
            summary = "Speak with Brutus in the castle.",
            walkthroughSteps = listOf("Speak with Brutus in the castle. Meatbugs have infested his chamber. Enter the room, kill the insects tied to the quest and return to Brutus once the room is clear."),
            reward = "Quest XP and Brutus' reward.",
            warnings = "Earlier catalogue versions normalized this title rather crudely as \"Stinking Shit\"; \"Filthy Sty\" is the cleaner English title used here.",
            searchTags = listOf("filthy sty", "chapter 4", "brutus")
        ),
        Quest(
            id = "CH4-023",
            chapter = 4,
            playOrder = 23,
            title = "Hunger",
            category = "Chapter 4",
            giver = "Gerold",
            location = "Chapter 4",
            prerequisites = "Chapter 4; access to the castle.",
            summary = "Gerold, the prison guard, is hungry.",
            walkthroughSteps = listOf("Gerold, the prison guard, is hungry. Arrange to meet him at night in the mages' quarters inside the castle, then give him the food requested by the dialogue. Speak with him again if necessary to close the journal entry."),
            reward = "Quest XP and Gerold's reward.",
            warnings = "The meeting is time/location sensitive. If the hand-in dialogue is missing, wait until night and check the mages' building rather than his daytime post.",
            searchTags = listOf("hunger", "chapter 4", "gerold")
        ),
        Quest(
            id = "CH4-024",
            chapter = 4,
            playOrder = 24,
            title = "Theft",
            category = "Chapter 4",
            giver = "Keroloth",
            location = "Chapter 4",
            prerequisites = "Chapter 4; access to the castle.",
            summary = "Keroloth believes the Dragon Hunters stole his purse.",
            walkthroughSteps = listOf("Keroloth believes the Dragon Hunters stole his purse. Search the area around the castle forge; the missing purse is lying nearby. Pick it up and return it to Keroloth."),
            reward = "Quest XP and Keroloth's reward.",
            warnings = "The purse is a world item close to the forge, so search the ground carefully before accusing or attacking anyone.",
            searchTags = listOf("theft", "chapter 4", "keroloth")
        ),
        Quest(
            id = "CH4-025",
            chapter = 4,
            playOrder = 25,
            title = "Feros's Sword",
            category = "Chapter 4",
            giver = "Feros",
            location = "Chapter 4",
            prerequisites = "Chapter 4; speak with Feros in/around the castle.",
            summary = "Feros tells you that he lost his sword.",
            walkthroughSteps = listOf("Feros tells you that he lost his sword. Travel to the cliff where the orc shaman Hosh-Pak is stationed; the sword can be found on that cliff. Pick it up and return it to Feros. <PARSED TEXT FOR PAGE: 9 / 10> GOTHIC II: NEW BALANCE | CHAPTER 4 QUEST GUIDE SliverzFX Guide Project | Chapter 4 | CH4-001 to CH4-030"),
            reward = "Quest XP and Feros's reward.",
            warnings = "This objective is efficient to combine with the Hosh-Pak quest because both use the same area.",
            searchTags = listOf("feros's sword", "chapter 4", "feros")
        ),
        Quest(
            id = "CH4-026",
            chapter = 4,
            playOrder = 26,
            title = "Lost in the Dark",
            category = "Chapter 4",
            giver = "Udar",
            location = "Chapter 4",
            prerequisites = "Chapter 4; access to the castle and dialogue with Udar.",
            summary = "Udar tells you that the paladin Sengrath left the castle and has not returned.",
            walkthroughSteps = listOf("Udar tells you that the paladin Sengrath left the castle and has not returned. Follow the palisade outside the castle until you find Sengrath's body. Take his crossbow and return to Udar with the news."),
            reward = "Quest XP and the associated item/dialogue reward.",
            warnings = "Loot the body before leaving; the crossbow is part of the return sequence.",
            searchTags = listOf("lost in the dark", "chapter 4", "udar")
        ),
        Quest(
            id = "CH4-027",
            chapter = 4,
            playOrder = 27,
            title = "Hosh-Pak",
            category = "Chapter 4",
            giver = "Oric",
            location = "Chapter 4",
            prerequisites = "Chapter 4; speak with Oric in the castle.",
            summary = "Oric orders you to kill the orc shaman Hosh-Pak.",
            walkthroughSteps = listOf("Oric orders you to kill the orc shaman Hosh-Pak. Hosh-Pak is stationed on the cliff near the cave with the stone steps. Kill him, loot the body and return to Oric to report the kill."),
            reward = "Quest XP and progression to Orc Warlords.",
            warnings = "Feros's lost sword is in the same general cliff area, so collect it during this trip. Hosh-Pak is also tied to Ur-Shak's story, so complete any dialogue you want with Ur-Shak before or after the kill as appropriate.",
            searchTags = listOf("hosh-pak", "chapter 4", "oric")
        ),
        Quest(
            id = "CH4-028",
            chapter = 4,
            playOrder = 28,
            title = "Orc Warlords",
            category = "Chapter 4",
            giver = "Oric",
            location = "Chapter 4",
            prerequisites = "Complete Hosh-Pak.",
            summary = "After Hosh-Pak is dead, speak with Oric again.",
            walkthroughSteps = listOf("After Hosh-Pak is dead, speak with Oric again. He asks you to eliminate four named orc leaders commanding the siege around the castle. Hunt down all four leaders in the Valley, loot their bodies for any proof/items and return to Oric once all four are dead."),
            reward = "Quest XP and Oric's completion reward.",
            warnings = "Named orc leaders often carry useful rings or quest items. Loot them before leaving their patrol areas.",
            searchTags = listOf("orc warlords", "chapter 4", "oric")
        ),
        Quest(
            id = "CH4-029",
            chapter = 4,
            playOrder = 29,
            title = "Jan and the Smithy",
            category = "Chapter 4",
            giver = "Jan",
            location = "Chapter 4",
            prerequisites = "Chapter 4; Jan is in the castle and wants access to the forge.",
            summary = "Jan wants to work as the castle smith, but Parcival objects.",
            walkthroughSteps = listOf("Jan wants to work as the castle smith, but Parcival objects. You can speak with Parcival first, but it is not required. Go directly to Garond and ask him to authorize Jan to use the smithy. Once Garond agrees, return to Jan and give him the good news."),
            reward = "Quest XP and access to Jan's smithing-related services/dialogue.",
            warnings = "The community guide notes that Parcival can be skipped entirely; Garond's approval is the decisive step.",
            searchTags = listOf("jan and the smithy", "chapter 4", "jan")
        ),
        Quest(
            id = "CH4-030",
            chapter = 4,
            playOrder = 30,
            title = "No Turning Back",
            category = "Chapter 4",
            giver = "Garond",
            location = "Chapter 4",
            prerequisites = "Chapter 4; speak with Garond after the castle situation advances.",
            summary = "Garond asks you to find the smith Dobar and his assistant Parlaf.",
            walkthroughSteps = listOf("Garond asks you to find the smith Dobar and his assistant Parlaf. Dobar's body is in the territory between the orc battering ram and the palisade. Parlaf is alive and hiding in Gilbert's cave, to the left of the barricade leading into the orc-held lands. Find Parlaf and escort him toward the castle; bringing him to the area in front of the battering ram is sufficient for the safe-arrival trigger. Return to Garond with the news."),
            reward = "Quest XP and Garond's reward; the community guide notes that Parlaf-survival extras are not especially valuable.",
            warnings = "This quest is time-limited: Parlaf can die if you delay too long. Save before starting the search and prioritize his rescue. Older catalogue wording used \"To Run or Not to Run\"; the current guide uses the clearer title \"No Turning Back\".",
            searchTags = listOf("no turning back", "chapter 4", "garond")
        )
    )
}
