package com.sliverzfx.gothicquest

object NewBalanceChapter3Part1 {
    val quests = listOf(
        Quest(
            id = "CH3-001",
            chapter = 3,
            playOrder = 1,
            title = "Bennet Is in Jail",
            category = "Main Story",
            giver = "Bennet or Hodges",
            location = "Main Story",
            prerequisites = "Chapter 3.",
            summary = "Learn that Bennet has been accused of murdering Lothar.",
            walkthroughSteps = listOf("Learn that Bennet has been accused of murdering Lothar. Speak with Lord Andre, Bennet in jail and Lord Hagen, then question Cornelius upstairs in Town Hall. The cleanest route is to pickpocket Cornelius' diary; alternatively pressure/bribe him as available. Read the diary to expose the false testimony, take the proof to Hagen and have Bennet released."),
            reward = "Bennet is freed and can repair the Eye of Innos; substantial XP and related faction rewards.",
            warnings = "Pickpocketing requires the skill but avoids paying Cornelius. Keep the evidence until Hagen has formally cleared Bennet.",
            searchTags = listOf("bennet is in jail", "main story", "bennet or hodges")
        ),
        Quest(
            id = "CH3-002",
            chapter = 3,
            playOrder = 2,
            title = "A Replacement for Vatras",
            category = "Main Story",
            giver = "Vatras",
            location = "Main Story",
            prerequisites = "During The Eye of Innos in Chapter 3.",
            summary = "Vatras cannot leave Khorinis for the Sun Circle until another Water Mage replaces him.",
            walkthroughSteps = listOf("Vatras cannot leave Khorinis for the Sun Circle until another Water Mage replaces him. Travel to Jharkendar and speak with Saturas; he sends Myxir to the city. Return to Vatras, who is now free to join the ritual. You can also speak to Myxir after the move for extra XP."),
            reward = "300 XP for arranging Myxir, 400 XP on returning to Vatras, plus 100 optional XP from Myxir.",
            warnings = "",
            searchTags = listOf("a replacement for vatras", "main story", "vatras")
        ),
        Quest(
            id = "CH3-003",
            chapter = 3,
            playOrder = 3,
            title = "Medicine for Hilda",
            category = "Lobart's Farm",
            giver = "Lobart",
            location = "Lobart's Farm",
            prerequisites = "Act 3; speak to Lobart at his farm.",
            summary = "Fetch Vatras's medicine for Lobart's sick wife Hilda.",
            walkthroughSteps = listOf("At Lobart's farm, ask Lobart about the Seekers and his wife's illness.", "Speak to Vatras in Khorinis and ask for Hilda's medicine.", "Carry the medicine to Hilda in Lobart's house."),
            reward = "200 XP from Vatras; 500 XP and 100 gold when Hilda receives the medicine.",
            warnings = "Lobart is the actual quest giver; do not search for an unidentified trigger NPC.",
            searchTags = listOf("medicine for hilda", "lobart's farm", "local quest giver in lobart's farm")
        ),
        Quest(
            id = "CH3-004",
            chapter = 3,
            playOrder = 4,
            title = "Sagitta's Concern",
            category = "Khorinis Island",
            giver = "Sagitta",
            location = "Khorinis Island",
            prerequisites = "Act 3; finish before Act 4.",
            summary = "Arrange protection for Sagitta against the Seekers.",
            walkthroughSteps = listOf("Find Sagitta at her cave; she fears the Seekers outside and refuses to leave.", "Ask Lee at Onar's farm to send guards to protect her.", "Return to Sagitta with Lee's promise of protection."),
            reward = "150 XP from Lee; 500 XP, two Healing Extracts and a King's Sorrel from Sagitta.",
            warnings = "Time-sensitive: according to the April 2026 guide, Sagitta dies in Act 4 if this is unfinished.",
            searchTags = listOf("sagitta's concern", "khorinis island", "local quest giver in khorinis island")
        ),
        Quest(
            id = "CH3-005",
            chapter = 3,
            playOrder = 5,
            title = "Shadowbeast Horns",
            category = "Khorinis Island",
            giver = "Buster",
            location = "Khorinis Island",
            prerequisites = "Acts 3–4; Buster accepts horns only until Act 5.",
            summary = "Sell shadowbeast horns to Buster for money and experience.",
            walkthroughSteps = listOf("Talk with Buster at Onar's farm in Act 3 to begin selling shadowbeast horns.", "Hunt shadowbeasts and extract their horns using the trophy skill.", "Deliver horns to Buster before Act 5; repeat for each horn."),
            reward = "300 XP per horn plus 50 gold; 100 gold per horn if you gave Buster 5 gold after the earlier duel.",
            warnings = "Buster stops buying horns in Act 5. Do not delay turn-ins.",
            searchTags = listOf("shadowbeast horns", "khorinis island", "local quest giver in khorinis island")
        ),
        Quest(
            id = "CH3-006",
            chapter = 3,
            playOrder = 6,
            title = "By Fire and Sword!",
            category = "Camp Development",
            giver = "Lord Hagen",
            location = "Camp Development",
            prerequisites = "Act 3; speak with Lord Hagen.",
            summary = "Clear the Seekers and their dark master from Dexter's former camp.",
            walkthroughSteps = listOf("Accept Lord Hagen's request in Khorinis to retake Dexter's former bandit camp.", "Return to the camp above Onar's farm and defeat seven Seekers spread around the grounds.", "Climb the adjacent tower; defeat the Dark Master and demonic skeletons.", "Report the cleared camp to Lord Hagen. Torlof's Fear can be finished alongside this quest."),
            reward = "5,000 XP and 1,500 gold; militia/paladins additionally receive the Fine Paladin Sword.",
            warnings = "Do this before My New Domain; clearing the seven Seekers alone is insufficient until the tower master is defeated.",
            searchTags = listOf("by fire and sword!", "camp development", "local quest giver in camp development")
        ),
        Quest(
            id = "CH3-007",
            chapter = 3,
            playOrder = 7,
            title = "My New Domain",
            category = "Camp Development",
            giver = "Lord Hagen",
            location = "Camp Development",
            prerequisites = "Act 3; complete By Fire and Sword!",
            summary = "Secure legal ownership of Dexter's former camp and begin rebuilding it.",
            walkthroughSteps = listOf("Speak with Hagen after clearing Dexter's camp. He provides 2,000 gold for initial expenses.", "Speak optionally to Lee and to Maria at Onar's farm; Maria offers support after the Golden Plate of Onar quest.", "Ask Onar to grant control of the camp. Pay the requested 100 gold rent or, at 50 rhetoric, persuade him to grant it for free.", "Return to Hagen to receive the royal deed and guards for the settlement."),
            reward = "2,000 gold initial funds; 500 XP from Hagen after negotiating; optional 500 XP each for Lee and Maria, plus 500 XP and +1 rhetoric for the successful 50-rhetoric rent negotiation.",
            warnings = "Onar owns the land. The 100 gold is a payment, not a reward; the camp-building storyline continues with People for the Camp.",
            searchTags = listOf("my new domain", "camp development", "local quest giver in camp development")
        ),
        Quest(
            id = "CH3-008",
            chapter = 3,
            playOrder = 8,
            title = "People for the Camp",
            category = "Camp Development",
            giver = "Lord Hagen; then Erol (camp manager)",
            location = "Camp Development",
            prerequisites = "Act 3; complete My New Domain; help Erol in Attack on the Trader.",
            summary = "Hire a manager and supply workers, food, miners and guards for the new camp.",
            walkthroughSteps = listOf("Visit the cleared camp and speak to the gate guard. Recruit Erol from his lakeside house as manager after completing Attack on the Trader.", "Speak to Erol at the camp and give him 5,000 gold startup capital, followed by 50 cooked meat, 25 fish and 5 loaves of bread.", "Recruit Niklas and Farim as food suppliers; Farim needs Problems with the Militia completed. Talbin can join in Act 4.", "Complete What About the Mine? to recruit Viper, then hire Snipes with 50 rhetoric and bring Grimes and Hanti out of the Valley of Mines using two Sleep scrolls.", "Hire Edda as cook after her statuette quest, Carl as blacksmith, and guards Gawern and Alrik; Alrik needs his sword quest.", "After adding the guards, ask Sagitta to be the healer after completing her Act 3 protection quest.", "Find armor blueprints in the abandoned gold mine in the Valley of Mines, hand them to Erol and collect the camp armor."),
            reward = "Staged XP for recruiting and supplying workers; 5,000 XP on final completion, plus steel armor after turning in the guard-armor blueprints.",
            warnings = "Extends into Act 4. Erol is the manager in the current guide; Snipes is necessary for the other miners to work, and each hire affects daily wages and food.",
            searchTags = listOf("people for the camp", "camp development", "local quest giver in camp development")
        ),
        Quest(
            id = "CH3-009",
            chapter = 3,
            playOrder = 9,
            title = "What About the Mine?",
            category = "Camp Development",
            giver = "Lord Hagen; then Viper",
            location = "Camp Development",
            prerequisites = "Act 3; By Fire and Sword! completed and Dexter's former camp secured.",
            summary = "Reopen the camp mine with Viper and negotiate ore sales to Hagen.",
            walkthroughSteps = listOf("Talk to Lord Hagen about developing the small iron/magic ore mine at Dexter's former camp.", "Find Viper in Kardif's tavern, recruit him and clear the minecrawlers from the camp mine.", "Meet Viper by the magical-ore vein; he confirms workable deposits and agrees to remain.", "Return to Lord Hagen and negotiate supplying magical ore at 40 gold per piece, increasing the mine's output."),
            reward = "300 XP for inviting Viper, 500 XP for examining the vein, 400 XP for his employment, and 1,500 XP for the Hagen agreement. Ongoing ore income for the camp.",
            warnings = "The Ore Cargo quest can alter Viper's dialogue. Ensure the minecrawlers are dead before expecting him to work there.",
            searchTags = listOf("what about the mine?", "camp development", "local quest giver in camp development")
        ),
        Quest(
            id = "CH3-010",
            chapter = 3,
            playOrder = 10,
            title = "Candidates for Work at the Camp",
            category = "Camp Development",
            giver = "Erol (camp manager)",
            location = "Camp Development",
            prerequisites = "Act 3; develop the camp under People for the Camp.",
            summary = "Recruit qualified suppliers, miners, a cook, smith and guards to keep the new camp operating.",
            walkthroughSteps = listOf("Install Erol as camp manager. Recruit Niklas and Farim to provide food; Farim needs Problems with the Militia.", "Recruit Viper as miner through What About the Mine?; recruit Snipes with at least 50 rhetoric.", "Bring Grimes and Hanti out of the Valley of Mines once you have two Sleep scrolls; meet them by the Khorinis pass and escort them to camp.", "Hire Edda as cook after Edda's Statuette, Carl as smith, and Gawern and Alrik as guards.", "Complete Sagitta's Concern and offer Sagitta the healer job. Later, Talbin may join after his Act 4 escape.", "Check with Erol after hiring the workers and delivering guard armor blueprints to finish the development chain."),
            reward = "Job recruits improve daily food, ore, forging and guard capacity; exact XP varies per recruit. This overlaps People for the Camp.",
            warnings = "Recruitment is tied to prerequisite quests and recurring upkeep. Avoid promising that every recruit can join during Act 3.",
            searchTags = listOf("candidates for work at the camp", "camp development", "local quest giver in camp development")
        ),
        Quest(
            id = "CH3-011",
            chapter = 3,
            playOrder = 11,
            title = "Diego's Gold",
            category = "Khorinis - Craftsmen's Quarter",
            giver = "Diego",
            location = "Khorinis - Craftsmen's Quarter",
            prerequisites = "Act 3; meet Diego after he returns to Khorinis.",
            summary = "Retrieve Diego's gold purse from the Valley of Mines pass.",
            walkthroughSteps = listOf("Find Diego in Khorinis and ask about his unfinished business and hidden gold.", "Return to the Valley of Mines pass, near the old lift where Diego left his purse.", "Defeat the elite orc berserker Nrukh and recover the heavy purse containing 2,000 gold.", "Deliver the purse to Diego in Khorinis."),
            reward = "1,500 XP for returning Diego's purse.",
            warnings = "The orc carries the purse; do not assume Diego's gold remains lying unguarded by the lift.",
            searchTags = listOf("diego's gold", "khorinis - craftsmen's quarter", "local quest giver in khorinis - craftsmen's quarter")
        ),
        Quest(
            id = "CH3-012",
            chapter = 3,
            playOrder = 12,
            title = "Diego's Business",
            category = "Khorinis - Craftsmen's Quarter",
            giver = "Diego",
            location = "Khorinis - Craftsmen's Quarter",
            prerequisites = "Act 3; complete Diego's Gold.",
            summary = "Deliver Diego's letter to Gerbrandt in the Upper Quarter.",
            walkthroughSteps = listOf("After returning Diego's purse, talk to Diego again and accept his business errand.", "Enter Khorinis's Upper Quarter and give Diego's letter to Gerbrandt.", "Return to Diego for his payment."),
            reward = "400 XP for delivering the letter; 300 XP and 500 gold on reporting to Diego.",
            warnings = "Diego's Gold must be completed before this errand begins.",
            searchTags = listOf("diego's business", "khorinis - craftsmen's quarter", "local quest giver in khorinis - craftsmen's quarter")
        ),
        Quest(
            id = "CH3-013",
            chapter = 3,
            playOrder = 13,
            title = "Dark Web",
            category = "Khorinis - Upper Quarter",
            giver = "Lord Hagen",
            location = "Khorinis - Upper Quarter",
            prerequisites = "Act 3; free Bennet in Bennet Is in Jail.",
            summary = "Investigate Lothar's real murderer through a cursed ring and confront the dark mage Zeld.",
            walkthroughSteps = listOf("Take Hagen's investigation after freeing Bennet. Search beneath the wooden bridge by Khorinis's south gate where Lothar was murdered; pick up the ring.", "Show the ring to Vatras, speak to him again, and learn that its magic points to a dark mage of Beliar.", "Question Bennet at Onar's farm, then Hodges (50 rhetoric) to get an enchanted scroll linked to the culprit.", "Show Hodges's scroll to Vatras to receive the rune that teleports to Lothar's murderer.", "Prepare healing and combat supplies; use the rune, kill dark mage Zeld in the isolated arena and loot his head.", "Use the rune again to leave, then bring Zeld's head to Lord Hagen."),
            reward = "Staged XP from Vatras and Hodges; 4,000 XP and +25 Innos karma at Hagen, plus a choice of paladin shield, knight helmet, blessed ammunition recipe, Robar's Will two-hander or 5,000 gold; paladins may choose holy/healing runes.",
            warnings = "The mage Zeld is difficult for Act 3. Complete Bennet's release first, and have at least 50 rhetoric before confronting Hodges.",
            searchTags = listOf("dark web", "khorinis - upper quarter", "local quest giver in khorinis - upper quarter")
        ),
        Quest(
            id = "CH3-014",
            chapter = 3,
            playOrder = 14,
            title = "Sheep Theft",
            category = "Akil's Farm",
            giver = "Akil",
            location = "Akil's Farm",
            prerequisites = "Act 3; complete Farmer in Need at Akil's farm.",
            summary = "Rescue Akil's stolen sheep from bandits hiding in a forest cave.",
            walkthroughSteps = listOf("Speak with Akil at his farm about sheep that were stolen, supposedly by bandits.", "Follow the downhill forest road to the cave and confront the bandits outside.", "Defeat the bandits, enter the cave and interact with the surviving sheep.", "Lead the sheep back to Akil and report the bandits' defeat."),
            reward = "100 gold and 200 XP for the sheep, plus 150 gold and 500 XP for the bandits.",
            warnings = "Do not kill or lose the sheep while escorting it back to the farm.",
            searchTags = listOf("sheep theft", "akil's farm", "local quest giver in akil's farm")
        ),
        Quest(
            id = "CH3-015",
            chapter = 3,
            playOrder = 15,
            title = "Roscoe's Fears",
            category = "The Dead Harpy Tavern",
            giver = "Roscoe",
            location = "The Dead Harpy Tavern",
            prerequisites = "Act 3; speak with Roscoe outside the Dead Harpy tavern.",
            summary = "Protect the Dead Harpy tavern from the undead and dark Seeker at the cemetery.",
            walkthroughSteps = listOf("Speak to Roscoe outside Orlan's tavern about the frightening Seekers at the nearby cemetery.", "Visit the cemetery, kill the undead there and defeat the Dark Wanderer.", "Return to Roscoe once the cemetery is clear."),
            reward = "1,000 XP and 300 gold from Roscoe.",
            warnings = "Clear both the undead and the Dark Wanderer to satisfy Roscoe's request.",
            searchTags = listOf("roscoe's fears", "the dead harpy tavern", "local quest giver in the dead harpy tavern")
        ),
        Quest(
            id = "CH3-016",
            chapter = 3,
            playOrder = 16,
            title = "A Mountain of Steel for Bennet",
            category = "Onar's Farm",
            giver = "Bennet",
            location = "Onar's Farm",
            prerequisites = "Act 3; complete Bennet Is in Jail.",
            summary = "Supply Bennet with one hundred steel blanks.",
            walkthroughSteps = listOf("Talk to Bennet at Onar's farm after his release. He is running out of steel.", "Obtain 100 steel billets/blanks by mining and smelting, forging or buying them.", "Bring all 100 blanks to Bennet."),
            reward = "2,500 XP, 1,500 gold and +2 Strength.",
            warnings = "Requires 100 blanks, not 100 swords; freeing Bennet from prison is mandatory.",
            searchTags = listOf("a mountain of steel for bennet", "onar's farm", "local quest giver in onar's farm")
        ),
        Quest(
            id = "CH3-017",
            chapter = 3,
            playOrder = 17,
            title = "Torlof's Fear",
            category = "Onar's Farm",
            giver = "Torlof",
            location = "Onar's Farm",
            prerequisites = "Act 3; coordinate with Lord Hagen's By Fire and Sword! quest.",
            summary = "Clear the Seekers out of Dexter's former tower to reassure Torlof.",
            walkthroughSteps = listOf("Speak with Torlof on Onar's farm; he fears the Seekers occupying Dexter's old camp.", "Accept Lord Hagen's By Fire and Sword! first so the Dark Master spawns at the tower.", "Kill seven Seekers in the camp and the Dark Master in the adjacent tower.", "Return to Torlof after clearing the camp."),
            reward = "1,500 XP from Torlof.",
            warnings = "Start Hagen's camp-clearance quest before killing the tower enemies; the objectives overlap.",
            searchTags = listOf("torlof's fear", "onar's farm", "local quest giver in onar's farm")
        ),
        Quest(
            id = "CH3-018",
            chapter = 3,
            playOrder = 18,
            title = "Exiled Farmer",
            category = "Sekob's Farm",
            giver = "Sekob",
            location = "Sekob's Farm",
            prerequisites = "Act 3; visit Sekob's farm after the Seekers arrive.",
            summary = "Expel the Seekers occupying Sekob's farmhouse.",
            walkthroughSteps = listOf("Find Sekob outside his house; he has fled the dark Seekers inside.", "Enter the farmhouse and kill the Seekers occupying it.", "Tell Sekob his house is clear and demand your payment."),
            reward = "1,500 XP and 150 gold.",
            warnings = "Consider collecting the Halls of Irdorath book for Pyrokar while the farm is clear; Sekob dislikes theft from his chest.",
            searchTags = listOf("exiled farmer", "sekob's farm", "local quest giver in sekob's farm")
        ),
        Quest(
            id = "CH3-019",
            chapter = 3,
            playOrder = 19,
            title = "Sekob's Missing Wife",
            category = "Sekob's Farm",
            giver = "Sekob",
            location = "Sekob's Farm",
            prerequisites = "Act 5, after Exiled Farmer; NOT an Act 3 quest in the April 2026 guide.",
            summary = "Find Rosie and Till after they flee Sekob; choose whether to force them home or help them escape.",
            walkthroughSteps = listOf("In Act 5, ask Sekob about Rosie and Till's disappearance.", "Find Rosie on the road between Orlan's tavern and the Water Mages' excavation site.", "Speak to Rosie and decide whether to escort her back to Sekob or help her reach safety through Rosie's Disappearance.", "If you bring her home, report to Sekob for his payment; the alternative can cause Sekob to attack."),
            reward = "Returning Rosie: 100 XP on meeting her, another 100 XP on returning, plus 100 XP and 300 gold from Sekob; helping her instead changes the outcome.",
            warnings = "Misclassified in Chapter 3: the April 2026 New Balance guide explicitly places this quest in Act 5. Retained under the existing ID to avoid disrupting saved progress.",
            searchTags = listOf("sekob's missing wife", "sekob's farm", "local quest giver in sekob's farm")
        ),
        Quest(
            id = "CH3-020",
            chapter = 3,
            playOrder = 20,
            title = "Alone and Defenseless",
            category = "Bengar's Farm",
            giver = "Bengar",
            location = "Bengar's Farm",
            prerequisites = "Act 3; talk to Bengar when his workers flee the Seekers.",
            summary = "Hire Wolf as guard and convince Malak to bring Bengar's frightened workers back.",
            walkthroughSteps = listOf("Visit Bengar's farm and ask why the workers have gone. Bengar needs guards to feel safe.", "Hire Wolf at Onar's farm for 300 gold, then report the security arrangement to Bengar.", "Find Malak and the other workers below Dexter's tower near the Innos shrine.", "Tell Malak that Bengar's farm is now safe and invite them to return.", "Report Malak's decision to Bengar to complete the quest."),
            reward = "300 XP for hiring Wolf; 500 XP and 200 gold from Bengar; 400+300 XP when finding/reassuring Malak; final 200 XP and 150 gold from Bengar.",
            warnings = "Hiring Wolf for Bengar prevents recruiting Wolf for the Chapter 5 ship crew. Fire Mage players may need to resolve Malak's possession.",
            searchTags = listOf("alone and defenseless", "bengar's farm", "local quest giver in bengar's farm")
        ),
        Quest(
            id = "CH3-021",
            chapter = 3,
            playOrder = 21,
            title = "Pack of Biters",
            category = "Hunters' Camp",
            giver = "Trigger quest",
            location = "Hunters' Camp",
            prerequisites = "Chapter 3; complete earlier quests in the same area/faction if the dialogue is not yet available.",
            summary = "Check Falk and the hunters after every hunt; many hunting quests unlock sequentially and depend on trophy skills.",
            walkthroughSteps = listOf("Check Falk and the hunters after every hunt; many hunting quests unlock sequentially and depend on trophy skills. Start this quest in Hunters' Camp and exhaust the new dialogue connected with \"Pack of Biters\". Get the target description from the quest giver, then travel through Hunters' Camp to the marked or described hunting area. Defeat the enemies or named target associated with \"Pack of Biters\", loot all bodies for proof/items, and search the immediate area for a journal-triggering object. Return to the quest giver and report the kill/clearing only after the objective counter or journal text has updated."),
            reward = "Reward varies by quest/build; exact values should be taken from the current in-game dialogue or source page.",
            warnings = "Named enemies frequently carry keys, notes or trophies used by another quest. Loot them before leaving the area.",
            searchTags = listOf("pack of biters", "hunters' camp", "local quest giver in hunters' camp")
        ),
        Quest(
            id = "CH3-022",
            chapter = 3,
            playOrder = 22,
            title = "Luck for the Hunter",
            category = "Hunters' Camp",
            giver = "Trigger quest",
            location = "Hunters' Camp",
            prerequisites = "Chapter 3; complete earlier quests in the same area/faction if the dialogue is not yet available.",
            summary = "Core objective: secure luck and get it to the Hunter.",
            walkthroughSteps = listOf("Core objective: secure luck and get it to the Hunter. Check Falk and the hunters after every hunt; many hunting quests unlock sequentially and depend on trophy skills. Start this quest in Hunters' Camp and exhaust the new dialogue connected with \"Luck for the Hunter\". Get the target description from the quest giver, then travel through Hunters' Camp to the marked or described hunting area. Defeat the enemies or named target associated with \"Luck for the Hunter\", loot all bodies for proof/items, and search the immediate area for a journal-triggering object. Return to the quest giver and report the kill/clearing only after the objective counter or journal text has updated."),
            reward = "Reward varies by quest/build; exact values should be taken from the current in-game dialogue or source page.",
            warnings = "Named enemies frequently carry keys, notes or trophies used by another quest. Loot them before leaving the area.",
            searchTags = listOf("luck for the hunter", "hunters' camp", "local quest giver in hunters' camp")
        ),
        Quest(
            id = "CH3-023",
            chapter = 3,
            playOrder = 23,
            title = "Pedro the Thief",
            category = "Monastery of Innos",
            giver = "Trigger quest",
            location = "Monastery of Innos",
            prerequisites = "Chapter 3; complete earlier quests in the same area/faction if the dialogue is not yet available.",
            summary = "Start this quest in Monastery of Innos and exhaust the new dialogue connected with \"Pedro the Thief\".",
            walkthroughSteps = listOf("Start this quest in Monastery of Innos and exhaust the new dialogue connected with \"Pedro the Thief\". Follow the dialogue chain for \"Pedro the Thief\" in Monastery of Innos. Speak to the quest giver and every newly mentioned NPC, inspect the locations or objects added to the journal, and complete the objective that causes the journal to update. Return to the relevant giver/contact after each major update; if no new dialogue appears, complete earlier quests in the same area or faction and check again."),
            reward = "Reward varies by quest/build; exact values should be taken from the current in-game dialogue or source page.",
            warnings = "This is an index-guided quick solution. Exact item counts, coordinates and reward values can differ with New Balance updates; use the linked source record when a build-specific detail matters.",
            searchTags = listOf("pedro the thief", "monastery of innos", "local quest giver in monastery of innos")
        ),
        Quest(
            id = "CH3-024",
            chapter = 3,
            playOrder = 24,
            title = "Babo's Papers",
            category = "Monastery of Innos",
            giver = "Babo",
            location = "Monastery of Innos",
            prerequisites = "Chapter 3; complete earlier quests in the same area/faction if the dialogue is not yet available.",
            summary = "Start this quest in Monastery of Innos and exhaust the new dialogue connected with \"Babo's Papers\".",
            walkthroughSteps = listOf("Start this quest in Monastery of Innos and exhaust the new dialogue connected with \"Babo's Papers\". Ask the quest giver for all available clues, then search Monastery of Innos and the locations mentioned in the journal for the named object connected with \"Babo's Papers\". Check corpses, locked chests, shelves, caves and camp interiors, and read any notes you find because they often advance the objective. Take the item to the intended owner/quest giver and continue the dialogue until the journal closes."),
            reward = "Reward varies by quest/build; exact values should be taken from the current in-game dialogue or source page.",
            warnings = "Unique equipment can be tied to several quests. Do not sell, forge away or discard it before checking all related dialogue.",
            searchTags = listOf("babo's papers", "monastery of innos", "local quest giver in monastery of innos")
        ),
        Quest(
            id = "CH3-025",
            chapter = 3,
            playOrder = 25,
            title = "Desecrated Statues",
            category = "Monastery of Innos",
            giver = "Trigger quest",
            location = "Monastery of Innos",
            prerequisites = "Chapter 3; complete earlier quests in the same area/faction if the dialogue is not yet available.",
            summary = "Start this quest in Monastery of Innos and exhaust the new dialogue connected with \"Desecrated Statues\".",
            walkthroughSteps = listOf("Start this quest in Monastery of Innos and exhaust the new dialogue connected with \"Desecrated Statues\". Follow the dialogue chain for \"Desecrated Statues\" in Monastery of Innos. Speak to the quest giver and every newly mentioned NPC, inspect the locations or objects added to the journal, and complete the objective that causes the journal to update. Return to the relevant giver/contact after each major update; if no new dialogue appears, complete earlier quests in the same area or faction and check again."),
            reward = "Reward varies by quest/build; exact values should be taken from the current in-game dialogue or source page.",
            warnings = "This is an index-guided quick solution. Exact item counts, coordinates and reward values can differ with New Balance updates; use the linked source record when a build-specific detail matters.",
            searchTags = listOf("desecrated statues", "monastery of innos", "local quest giver in monastery of innos")
        ),
        Quest(
            id = "CH3-026",
            chapter = 3,
            playOrder = 26,
            title = "Energy of the Stars",
            category = "Monastery of Innos",
            giver = "Trigger quest",
            location = "Monastery of Innos",
            prerequisites = "Chapter 3; complete earlier quests in the same area/faction if the dialogue is not yet available.",
            summary = "Start this quest in Monastery of Innos and exhaust the new dialogue connected with \"Energy of the Stars\".",
            walkthroughSteps = listOf("Start this quest in Monastery of Innos and exhaust the new dialogue connected with \"Energy of the Stars\". Follow the dialogue chain for \"Energy of the Stars\" in Monastery of Innos. Speak to the quest giver and every newly mentioned NPC, inspect the locations or objects added to the journal, and complete the objective that causes the journal to update. Return to the relevant giver/contact after each major update; if no new dialogue appears, complete earlier quests in the same area or faction and check again."),
            reward = "Reward varies by quest/build; exact values should be taken from the current in-game dialogue or source page.",
            warnings = "This is an index-guided quick solution. Exact item counts, coordinates and reward values can differ with New Balance updates; use the linked source record when a build-specific detail matters.",
            searchTags = listOf("energy of the stars", "monastery of innos", "local quest giver in monastery of innos")
        ),
        Quest(
            id = "CH3-027",
            chapter = 3,
            playOrder = 27,
            title = "False Ore-Mining Sites",
            category = "Monastery of Innos",
            giver = "Trigger quest",
            location = "Monastery of Innos",
            prerequisites = "Chapter 3; complete earlier quests in the same area/faction if the dialogue is not yet available.",
            summary = "Start this quest in Monastery of Innos and exhaust the new dialogue connected with \"False Ore-Mining Sites\".",
            walkthroughSteps = listOf("Start this quest in Monastery of Innos and exhaust the new dialogue connected with \"False Ore-Mining Sites\". Follow the dialogue chain for \"False Ore-Mining Sites\" in Monastery of Innos. Speak to the quest giver and every newly mentioned NPC, inspect the locations or objects added to the journal, and complete the objective that causes the journal to update. Return to the relevant giver/contact after each major update; if no new dialogue appears, complete earlier quests in the same area or faction and check again."),
            reward = "Reward varies by quest/build; exact values should be taken from the current in-game dialogue or source page.",
            warnings = "This is an index-guided quick solution. Exact item counts, coordinates and reward values can differ with New Balance updates; use the linked source record when a build-specific detail matters.",
            searchTags = listOf("false ore-mining sites", "monastery of innos", "local quest giver in monastery of innos")
        ),
        Quest(
            id = "CH3-028",
            chapter = 3,
            playOrder = 28,
            title = "Death for the Greater Good",
            category = "Monastery of Innos",
            giver = "Trigger quest",
            location = "Monastery of Innos",
            prerequisites = "Chapter 3; complete earlier quests in the same area/faction if the dialogue is not yet available.",
            summary = "Core objective: secure death and get it to the Greater Good.",
            walkthroughSteps = listOf("Core objective: secure death and get it to the Greater Good. Start this quest in Monastery of Innos and exhaust the new dialogue connected with \"Death for the Greater Good\". Speak with the relevant contact in Monastery of Innos to confirm the requested amount or exact variant. Obtain \"Death\" by gathering, buying, crafting, looting or completing the linked prerequisite task, then bring it to the Greater Good. If the quest does not close immediately, return to the NPC who originally sent you."),
            reward = "Reward varies by quest/build; exact values should be taken from the current in-game dialogue or source page.",
            warnings = "Do not sell unique named items, special ingredients, quest letters or unusual trophies until the related quest chain is finished.",
            searchTags = listOf("death for the greater good", "monastery of innos", "local quest giver in monastery of innos")
        ),
        Quest(
            id = "CH3-029",
            chapter = 3,
            playOrder = 29,
            title = "Joining the Paladins",
            category = "Militia / Paladins",
            giver = "Trigger quest",
            location = "Militia / Paladins",
            prerequisites = "Chapter 3; complete earlier quests in the same area/faction if the dialogue is not yet available.",
            summary = "Core objective: complete the admission chain and formally join the group named in Joining the Paladins.",
            walkthroughSteps = listOf("Core objective: complete the admission chain and formally join the group named in Joining the Paladins. This is faction progression. Keep checking the faction leader and trainers after every completed task, and do not assume a missing dialogue is a bug until the earlier faction jobs are closed. Start this quest in Militia / Paladins and exhaust the new dialogue connected with \"Joining the Paladins\". Treat this as a progression quest rather than a single delivery. Complete the introductory jobs offered by the relevant faction or contact in Militia / Paladins, report each result, and keep checking the faction leader or recruiter for new dialogue until the membership/progression option appears. If the dialogue stalls, finish the other Chapter 3 quests in the same faction block first."),
            reward = "Reward varies by quest/build; exact values should be taken from the current in-game dialogue or source page.",
            warnings = "Main-guild admission routes can be mutually exclusive. Finish any optional pre-joining tasks you want before formally committing to a main guild.",
            searchTags = listOf("joining the paladins", "militia / paladins", "local quest giver in militia / paladins")
        ),
        Quest(
            id = "CH3-030",
            chapter = 3,
            playOrder = 30,
            title = "Secret Knowledge",
            category = "Militia / Paladins",
            giver = "Trigger quest",
            location = "Militia / Paladins",
            prerequisites = "Chapter 3; complete earlier quests in the same area/faction if the dialogue is not yet available.",
            summary = "This is faction progression.",
            walkthroughSteps = listOf("This is faction progression. Keep checking the faction leader and trainers after every completed task, and do not assume a missing dialogue is a bug until the earlier faction jobs are closed. Start this quest in Militia / Paladins and exhaust the new dialogue connected with \"Secret Knowledge\". Collect the exposition from the quest giver, then explore the quest location in Militia / Paladins rather than relying only on combat. For \"Secret Knowledge\", inspect switches, inscriptions, books, keys, corpses and unusual interactable objects; read every quest note before operating the next mechanism. When the puzzle/ritual or exploration objective updates, return to the associated scholar, mage or faction contact for the next step."),
            reward = "Reward varies by quest/build; exact values should be taken from the current in-game dialogue or source page.",
            warnings = "Make a manual save before using one-way portals, ritual objects or major temple mechanisms.",
            searchTags = listOf("secret knowledge", "militia / paladins", "local quest giver in militia / paladins")
        ),
        Quest(
            id = "CH3-031",
            chapter = 3,
            playOrder = 31,
            title = "The Judge's Lackey",
            category = "Mercenaries / Dragon Hunters",
            giver = "Trigger quest",
            location = "Mercenaries / Dragon Hunters",
            prerequisites = "Chapter 3; complete earlier quests in the same area/faction if the dialogue is not yet available.",
            summary = "Core objective: locate the named quest item (The Judge's Lackey) and return it to the NPC whose dialogue identifies it.",
            walkthroughSteps = listOf("Core objective: locate the named quest item (The Judge's Lackey) and return it to the NPC whose dialogue identifies it. This is faction progression. Keep checking the faction leader and trainers after every completed task, and do not assume a missing dialogue is a bug until the earlier faction jobs are closed. Start this quest in Mercenaries / Dragon Hunters and exhaust the new dialogue connected with \"The Judge's Lackey\". Follow the dialogue chain for \"The Judge's Lackey\" in Mercenaries / Dragon Hunters. Speak to the quest giver and every newly mentioned NPC, inspect the locations or objects added to the journal, and complete the objective that causes the journal to update. Return to the relevant giver/contact after each major update; if no new dialogue appears, complete earlier quests in the same area or faction and check again."),
            reward = "Reward varies by quest/build; exact values should be taken from the current in-game dialogue or source page.",
            warnings = "This is an index-guided quick solution. Exact item counts, coordinates and reward values can differ with New Balance updates; use the linked source record when a build-specific detail matters.",
            searchTags = listOf("the judge's lackey", "mercenaries / dragon hunters", "local quest giver in mercenaries / dragon hunters")
        ),
        Quest(
            id = "CH3-032",
            chapter = 3,
            playOrder = 32,
            title = "Maleth's Cane",
            category = "Mercenaries / Dragon Hunters",
            giver = "Maleth",
            location = "Mercenaries / Dragon Hunters",
            prerequisites = "Chapter 3; complete earlier quests in the same area/faction if the dialogue is not yet available.",
            summary = "This is faction progression.",
            walkthroughSteps = listOf("This is faction progression. Keep checking the faction leader and trainers after every completed task, and do not assume a missing dialogue is a bug until the earlier faction jobs are closed. Start this quest in Mercenaries / Dragon Hunters and exhaust the new dialogue connected with \"Maleth's Cane\". Follow the dialogue chain for \"Maleth's Cane\" in Mercenaries / Dragon Hunters. Speak to the quest giver and every newly mentioned NPC, inspect the locations or objects added to the journal, and complete the objective that causes the journal to update. Return to the relevant giver/contact after each major update; if no new dialogue appears, complete earlier quests in the same area or faction and check again."),
            reward = "Reward varies by quest/build; exact values should be taken from the current in-game dialogue or source page.",
            warnings = "This is an index-guided quick solution. Exact item counts, coordinates and reward values can differ with New Balance updates; use the linked source record when a build-specific detail matters.",
            searchTags = listOf("maleth's cane", "mercenaries / dragon hunters", "local quest giver in mercenaries / dragon hunters")
        ),
        Quest(
            id = "CH3-033",
            chapter = 3,
            playOrder = 33,
            title = "Dark Wanderers",
            category = "Fire Mages",
            giver = "Trigger quest",
            location = "Fire Mages",
            prerequisites = "Chapter 3; complete earlier quests in the same area/faction if the dialogue is not yet available.",
            summary = "This is faction progression.",
            walkthroughSteps = listOf("This is faction progression. Keep checking the faction leader and trainers after every completed task, and do not assume a missing dialogue is a bug until the earlier faction jobs are closed. Start this quest in Fire Mages and exhaust the new dialogue connected with \"Dark Wanderers\". Follow the dialogue chain for \"Dark Wanderers\" in Fire Mages. Speak to the quest giver and every newly mentioned NPC, inspect the locations or objects added to the journal, and complete the objective that causes the journal to update. Return to the relevant giver/contact after each major update; if no new dialogue appears, complete earlier quests in the same area or faction and check again."),
            reward = "Reward varies by quest/build; exact values should be taken from the current in-game dialogue or source page.",
            warnings = "This is an index-guided quick solution. Exact item counts, coordinates and reward values can differ with New Balance updates; use the linked source record when a build-specific detail matters.",
            searchTags = listOf("dark wanderers", "fire mages", "local quest giver in fire mages")
        ),
        Quest(
            id = "CH3-034",
            chapter = 3,
            playOrder = 34,
            title = "Orc Galley",
            category = "Scouts",
            giver = "Trigger quest",
            location = "Scouts",
            prerequisites = "Chapter 3; complete earlier quests in the same area/faction if the dialogue is not yet available.",
            summary = "This is faction progression.",
            walkthroughSteps = listOf("This is faction progression. Keep checking the faction leader and trainers after every completed task, and do not assume a missing dialogue is a bug until the earlier faction jobs are closed. Start this quest in Scouts and exhaust the new dialogue connected with \"Orc Galley\". Follow the dialogue chain for \"Orc Galley\" in Scouts. Speak to the quest giver and every newly mentioned NPC, inspect the locations or objects added to the journal, and complete the objective that causes the journal to update. Return to the relevant giver/contact after each major update; if no new dialogue appears, complete earlier quests in the same area or faction and check again."),
            reward = "Reward varies by quest/build; exact values should be taken from the current in-game dialogue or source page.",
            warnings = "This is an index-guided quick solution. Exact item counts, coordinates and reward values can differ with New Balance updates; use the linked source record when a build-specific detail matters.",
            searchTags = listOf("orc galley", "scouts", "local quest giver in scouts")
        ),
        Quest(
            id = "CH3-035",
            chapter = 3,
            playOrder = 35,
            title = "Chasing Darkness",
            category = "Scouts",
            giver = "Trigger quest",
            location = "Scouts",
            prerequisites = "Chapter 3; complete earlier quests in the same area/faction if the dialogue is not yet available.",
            summary = "This is faction progression.",
            walkthroughSteps = listOf("This is faction progression. Keep checking the faction leader and trainers after every completed task, and do not assume a missing dialogue is a bug until the earlier faction jobs are closed. Start this quest in Scouts and exhaust the new dialogue connected with \"Chasing Darkness\". Follow the dialogue chain for \"Chasing Darkness\" in Scouts. Speak to the quest giver and every newly mentioned NPC, inspect the locations or objects added to the journal, and complete the objective that causes the journal to update. Return to the relevant giver/contact after each major update; if no new dialogue appears, complete earlier quests in the same area or faction and check again."),
            reward = "Reward varies by quest/build; exact values should be taken from the current in-game dialogue or source page.",
            warnings = "This is an index-guided quick solution. Exact item counts, coordinates and reward values can differ with New Balance updates; use the linked source record when a build-specific detail matters.",
            searchTags = listOf("chasing darkness", "scouts", "local quest giver in scouts")
        ),
        Quest(
            id = "CH3-036",
            chapter = 3,
            playOrder = 36,
            title = "Undead Attack",
            category = "Demon Hunters",
            giver = "Trigger quest",
            location = "Demon Hunters",
            prerequisites = "Chapter 3; complete earlier quests in the same area/faction if the dialogue is not yet available.",
            summary = "This is faction progression.",
            walkthroughSteps = listOf("This is faction progression. Keep checking the faction leader and trainers after every completed task, and do not assume a missing dialogue is a bug until the earlier faction jobs are closed. Start this quest in Demon Hunters and exhaust the new dialogue connected with \"Undead Attack\". Get the target description from the quest giver, then travel through Demon Hunters to the marked or described hunting area. Defeat the enemies or named target associated with \"Undead Attack\", loot all bodies for proof/items, and search the immediate area for a journal-triggering object. Return to the quest giver and report the kill/clearing only after the objective counter or journal text has updated."),
            reward = "Reward varies by quest/build; exact values should be taken from the current in-game dialogue or source page.",
            warnings = "Named enemies frequently carry keys, notes or trophies used by another quest. Loot them before leaving the area.",
            searchTags = listOf("undead attack", "demon hunters", "local quest giver in demon hunters")
        ),
        Quest(
            id = "CH3-037",
            chapter = 3,
            playOrder = 37,
            title = "The Possessed",
            category = "Brotherhood",
            giver = "Trigger quest",
            location = "Brotherhood",
            prerequisites = "Chapter 3; complete earlier quests in the same area/faction if the dialogue is not yet available.",
            summary = "This is faction progression.",
            walkthroughSteps = listOf("This is faction progression. Keep checking the faction leader and trainers after every completed task, and do not assume a missing dialogue is a bug until the earlier faction jobs are closed. Start this quest in Brotherhood and exhaust the new dialogue connected with \"The Possessed\". Follow the dialogue chain for \"The Possessed\" in Brotherhood. Speak to the quest giver and every newly mentioned NPC, inspect the locations or objects added to the journal, and complete the objective that causes the journal to update. Return to the relevant giver/contact after each major update; if no new dialogue appears, complete earlier quests in the same area or faction and check again."),
            reward = "Reward varies by quest/build; exact values should be taken from the current in-game dialogue or source page.",
            warnings = "This is an index-guided quick solution. Exact item counts, coordinates and reward values can differ with New Balance updates; use the linked source record when a build-specific detail matters.",
            searchTags = listOf("the possessed", "brotherhood", "local quest giver in brotherhood")
        ),
        Quest(
            id = "CH3-038",
            chapter = 3,
            playOrder = 38,
            title = "In Search of Lost Recipes",
            category = "Necromancers",
            giver = "Trigger quest",
            location = "Necromancers",
            prerequisites = "Chapter 3; complete earlier quests in the same area/faction if the dialogue is not yet available.",
            summary = "This is faction progression.",
            walkthroughSteps = listOf("This is faction progression. Keep checking the faction leader and trainers after every completed task, and do not assume a missing dialogue is a bug until the earlier faction jobs are closed. Start this quest in Necromancers and exhaust the new dialogue connected with \"In Search of Lost Recipes\". Begin by questioning the NPCs tied to Necromancers and follow every new name or location added to the journal. Search the relevant nearby camps, caves, roads and interiors for the missing person, item or clue named by \"In Search of Lost Recipes\". Read notes and letters you find, then return to the original contact after the journal updates; some investigations require reporting to more than one NPC."),
            reward = "Reward varies by quest/build; exact values should be taken from the current in-game dialogue or source page.",
            warnings = "Do not kill neutral or named NPCs involved in the investigation until you have exhausted their dialogue; New Balance often uses them in follow-up quests.",
            searchTags = listOf("in search of lost recipes", "necromancers", "local quest giver in necromancers")
        ),
        Quest(
            id = "CH3-039",
            chapter = 3,
            playOrder = 39,
            title = "Old Friend",
            category = "Path of the Damned",
            giver = "Trigger quest",
            location = "Path of the Damned",
            prerequisites = "Chapter 3; complete earlier quests in the same area/faction if the dialogue is not yet available.",
            summary = "This is faction progression.",
            walkthroughSteps = listOf("This is faction progression. Keep checking the faction leader and trainers after every completed task, and do not assume a missing dialogue is a bug until the earlier faction jobs are closed. Start this quest in Path of the Damned and exhaust the new dialogue connected with \"Old Friend\". Follow the dialogue chain for \"Old Friend\" in Path of the Damned. Speak to the quest giver and every newly mentioned NPC, inspect the locations or objects added to the journal, and complete the objective that causes the journal to update. Return to the relevant giver/contact after each major update; if no new dialogue appears, complete earlier quests in the same area or faction and check again."),
            reward = "Reward varies by quest/build; exact values should be taken from the current in-game dialogue or source page.",
            warnings = "This is an index-guided quick solution. Exact item counts, coordinates and reward values can differ with New Balance updates; use the linked source record when a build-specific detail matters.",
            searchTags = listOf("old friend", "path of the damned", "local quest giver in path of the damned")
        ),
        Quest(
            id = "CH3-040",
            chapter = 3,
            playOrder = 40,
            title = "Murder Near the City",
            category = "Path of the Damned",
            giver = "Trigger quest",
            location = "Path of the Damned",
            prerequisites = "Chapter 3; complete earlier quests in the same area/faction if the dialogue is not yet available.",
            summary = "This is faction progression.",
            walkthroughSteps = listOf("This is faction progression. Keep checking the faction leader and trainers after every completed task, and do not assume a missing dialogue is a bug until the earlier faction jobs are closed. Start this quest in Path of the Damned and exhaust the new dialogue connected with \"Murder Near the City\". Follow the dialogue chain for \"Murder Near the City\" in Path of the Damned. Speak to the quest giver and every newly mentioned NPC, inspect the locations or objects added to the journal, and complete the objective that causes the journal to update. Return to the relevant giver/contact after each major update; if no new dialogue appears, complete earlier quests in the same area or faction and check again."),
            reward = "Reward varies by quest/build; exact values should be taken from the current in-game dialogue or source page.",
            warnings = "This is an index-guided quick solution. Exact item counts, coordinates and reward values can differ with New Balance updates; use the linked source record when a build-specific detail matters.",
            searchTags = listOf("murder near the city", "path of the damned", "local quest giver in path of the damned")
        ),
        Quest(
            id = "CH3-041",
            chapter = 3,
            playOrder = 41,
            title = "Fateful Encounter",
            category = "Path of the Damned",
            giver = "Trigger quest",
            location = "Path of the Damned",
            prerequisites = "Chapter 3; complete earlier quests in the same area/faction if the dialogue is not yet available.",
            summary = "This is faction progression.",
            walkthroughSteps = listOf("This is faction progression. Keep checking the faction leader and trainers after every completed task, and do not assume a missing dialogue is a bug until the earlier faction jobs are closed. Start this quest in Path of the Damned and exhaust the new dialogue connected with \"Fateful Encounter\". Follow the dialogue chain for \"Fateful Encounter\" in Path of the Damned. Speak to the quest giver and every newly mentioned NPC, inspect the locations or objects added to the journal, and complete the objective that causes the journal to update. Return to the relevant giver/contact after each major update; if no new dialogue appears, complete earlier quests in the same area or faction and check again."),
            reward = "Reward varies by quest/build; exact values should be taken from the current in-game dialogue or source page.",
            warnings = "This is an index-guided quick solution. Exact item counts, coordinates and reward values can differ with New Balance updates; use the linked source record when a build-specific detail matters.",
            searchTags = listOf("fateful encounter", "path of the damned", "local quest giver in path of the damned")
        ),
        Quest(
            id = "CH3-042",
            chapter = 3,
            playOrder = 42,
            title = "Storming the Castle",
            category = "Path of the Damned",
            giver = "Trigger quest",
            location = "Path of the Damned",
            prerequisites = "Chapter 3; complete earlier quests in the same area/faction if the dialogue is not yet available.",
            summary = "This is faction progression.",
            walkthroughSteps = listOf("This is faction progression. Keep checking the faction leader and trainers after every completed task, and do not assume a missing dialogue is a bug until the earlier faction jobs are closed. Start this quest in Path of the Damned and exhaust the new dialogue connected with \"Storming the Castle\". Follow the dialogue chain for \"Storming the Castle\" in Path of the Damned. Speak to the quest giver and every newly mentioned NPC, inspect the locations or objects added to the journal, and complete the objective that causes the journal to update. Return to the relevant giver/contact after each major update; if no new dialogue appears, complete earlier quests in the same area or faction and check again."),
            reward = "Reward varies by quest/build; exact values should be taken from the current in-game dialogue or source page.",
            warnings = "This is an index-guided quick solution. Exact item counts, coordinates and reward values can differ with New Balance updates; use the linked source record when a build-specific detail matters.",
            searchTags = listOf("storming the castle", "path of the damned", "local quest giver in path of the damned")
        )
    )
}
