package com.sliverzfx.gothicquest

object NewBalanceChapter4Data {
    val quests = listOf(
        Quest(
            id = "CH4-001",
            chapter = 4,
            playOrder = 1,
            title = "Dragon Hunt",
            category = "Chapter 4",
            giver = "Pyrokar",
            location = "Chapter 4",
            prerequisites = "The Eye of Innos has been restored; Chapter 4 begins.",
            summary = "Use the restored Eye of Innos to confront the four dragons in the Valley of Mines, charging it between kills.",
            walkthroughSteps = listOf("After the Eye of Innos ritual, ask Pyrokar how to use the amulet; travel to the Valley of Mines and speak to Garond (500 XP) and Oric for dragon locations.", "Keep the charged Eye in your inventory before speaking to each dragon; you do not need to wear it. Defeat the dragon's summoned elementals promptly because they help it regenerate.", "Recommended order: swamp dragon Pandrodor in the swamp near Cavalorn's old hut (Cypher and Rod may assist), stone dragon Pedrakhan at the ruined Stone Fortress, fire dragon Feomathar in the volcanic crater, then ice dragon Finkregh in the ruins of the former New Camp.", "After each dragon dies, loot its heart and hoard; at an alchemy table recharge the Eye using the heart under the special-potions tab before confronting the next dragon.", "Return to Garond to report each dragon's death. After all four, make the final report to Garond to complete the hunt and advance toward Chapter 5.", "Optionally tell Kurgan, Milten, Pyrokar, Vatras, Lord Hagen and Netbek about the dragons for extra dialogue XP."),
            reward = "500 XP for Garond's first briefing; 5,000 XP and 1,000 gold per dragon reported, plus 5,000 XP for defeating all four. Additional report XP is available from Kurgan (100), Milten (500), Pyrokar (2,000), Vatras (500), Hagen (1,000) and Netbek (1,000).",
            warnings = "A charged Eye must be in your inventory when you SPEAK to each dragon, not equipped. Recharge at an alchemy table with the dragon's heart after each kill; kill spawned elementals to curb dragon regeneration.",
            searchTags = listOf("dragon hunt", "chapter 4", "pyrokar")
        ),
        Quest(
            id = "CH4-002",
            chapter = 4,
            playOrder = 2,
            title = "Lobart's Orc Problem",
            category = "Chapter 4",
            giver = "Lobart",
            location = "Chapter 4",
            prerequisites = "Chapter 4; return to Lobart's farm after the orc invasion begins.",
            summary = "Kill the orcs that have overrun Lobart's farm in Chapter 4 and report to him.",
            walkthroughSteps = listOf("Ask Lobart about the orcs that have invaded his farm during Chapter 4.", "Clear all the orcs threatening the farm and nearby farm approaches; check for survivors before returning.", "Tell Lobart the orcs are gone to receive your payment."),
            reward = "1,000 XP and 100 gold from Lobart after clearing the orcs.",
            warnings = "Orc patrols in Chapter 4 can overlap with lizardmen guarding dragon eggs. Search the bodies and nearby caves instead of leaving immediately after the combat.",
            searchTags = listOf("lobart's orc problem", "chapter 4", "lobart")
        ),
        Quest(
            id = "CH4-003",
            chapter = 4,
            playOrder = 3,
            title = "Orc Squads",
            category = "Chapter 4",
            giver = "Lord Hagen",
            location = "Chapter 4",
            prerequisites = "Chapter 4; the orc invasion of Khorinis has begun.",
            summary = "Defeat the Orc Squad commander near Bartok's hunting forest and turn in more than twenty orc-elder rings to Lord Hagen.",
            walkthroughSteps = listOf("In Chapter 4, speak with Lord Hagen in Khorinis and show an orc elder's ring (300 XP). Hagen assigns the orc squads.", "Ask Ingmar about the commander, then leave through the south gate toward the wooded route used while hunting with Bartok.", "Go through the forest to the cave where Kriks the Razor's bandits were camped; kill the elite orcs and their commander Fangarh, and take his military map.", "Report Fangarh's defeat to Ingmar for 1,500 XP and 500 gold.", "Use the map to find the Orc elder patrols scattered around Khorinis. Collect more than twenty leader rings and deliver them to Hagen to close the quest.", "Hagen continues taking remaining rings for 200 XP each after completion. Reserve one ring for Dar's The Braggart if you plan that route."),
            reward = "300 XP for showing Hagen an early elder ring; 1,500 XP and 500 gold from Ingmar after killing Fangarh; main quest closes once Hagen receives over twenty elder rings; additional rings earn 200 XP each. An optional initial orc conversation grants 100 XP.",
            warnings = "Save at least one Orc Warlord's/elder's ring for Dar's The Braggart quest if available. Fangarh's map reveals additional patrol locations.",
            searchTags = listOf("orc squads", "chapter 4", "lord hagen / ingmar")
        ),
        Quest(
            id = "CH4-004",
            chapter = 4,
            playOrder = 4,
            title = "News for Vatras",
            category = "Chapter 4",
            giver = "Saturas (Vatras directs the visit)",
            location = "Chapter 4",
            prerequisites = "After the Eye of Innos restoration ritual, then Chapter 4 to complete Saturas's Orcs in the Valley quest.",
            summary = "Check on Saturas in Jharkendar for Vatras, defeat the orc occupation and report back.",
            walkthroughSteps = listOf("After restoring the Eye of Innos, speak to Vatras; he asks you to visit Saturas and check on the Water Mages.", "Begin Chapter 4 and travel through the portal to Jharkendar. Speak to Saturas about the valley's orc invasion.", "Complete Saturas's Orcs in the Valley quest by clearing the occupation.", "Return to Khorinis and tell Vatras that the Water Mages are safe."),
            reward = "1,000 XP and 300 gold from Vatras.",
            warnings = "The initial request can be received after restoring the Eye, but Jharkendar's invasion does not begin until Chapter 4. Finish Orcs in the Valley before reporting.",
            searchTags = listOf("news for vatras", "chapter 4", "vatras")
        ),
        Quest(
            id = "CH4-005",
            chapter = 4,
            playOrder = 5,
            title = "Deprivation",
            category = "Chapter 4",
            giver = "Randolph",
            location = "Chapter 4",
            prerequisites = "Chapter 4; paladin only. Randolph must be alive and at Akil's farm.",
            summary = "Find Sagitta's remedy to help Randolph stop drinking.",
            walkthroughSteps = listOf("As a paladin in Chapter 4, speak with Randolph at Akil's farm about his attempt to quit drinking.", "Visit Sagitta's cave and pay 300 gold for her anti-addiction medicine.", "Bring the medicine to Randolph and speak with him again."),
            reward = "500 XP and 150 gold from Randolph. Sagitta's potion costs 300 gold.",
            warnings = "The April 2026 New Balance guide restricts this quest to paladins; buying the cure has a 300-gold cost and yields a net loss of 150 gold.",
            searchTags = listOf("deprivation", "chapter 4", "randolph")
        ),
        Quest(
            id = "CH4-006",
            chapter = 4,
            playOrder = 6,
            title = "Dragon Eggs",
            category = "Chapter 4",
            giver = "Bennet",
            location = "Chapter 4",
            prerequisites = "Chapter 4; obtain a dragon egg and speak with Bennet. Primarily associated with the mercenary/Dragon Hunter route.",
            summary = "Collect dragon eggs from lizardmen-guarded caves, deciding whether to sell them to Bennet or preserve them for the powerful Irdorath potion.",
            walkthroughSteps = listOf("Show Bennet a dragon egg and agree to discuss selling them. He gives you information/a map for the Khorinis caves where eggs can be found. Search the marked caves, kill the lizardmen guarding them and collect the eggs. Bennet will buy the eggs you bring back."),
            reward = "Bennet offers 350 gold and 300 XP for each dragon egg sold. An Irdorath recipe consumes nine eggs per Embarla Firgasto potion; each dose grants warriors +10 Strength or Dexterity, or mages +20 Mana (up to four potions with enough eggs).",
            warnings = "If you intend to brew Embarla Firgasto in Chapter 6, KEEP your eggs: the recipe takes nine per potion and up to four potions can be made. Selling eggs to Bennet is irreversible.",
            searchTags = listOf("dragon eggs", "chapter 4", "bennet")
        ),
        Quest(
            id = "CH4-007",
            chapter = 4,
            playOrder = 7,
            title = "The Braggart",
            category = "Chapter 4",
            giver = "Dar",
            location = "Chapter 4",
            prerequisites = "Chapter 4; Dar alive. The orc-ring route is unavailable to paladins.",
            summary = "Either help Dar boast with an Orc elder's ring or laugh at him and win a fistfight.",
            walkthroughSteps = listOf("Speak to Dar at Onar's farm in Chapter 4.", "If you ask what would impress Lee, Dar requests an orc warlord/elder ring taken from a black-orc leader. Reserve one from Orc Squads and give it to him.", "Choose between the Dexterity Amulet reward or a small gold payment.", "Alternatively, mock Dar instead of helping him; defeat him in the resulting duel to end the quest for a smaller XP reward."),
            reward = "Ring route: Dexterity Amulet and 600 XP, OR 120 gold and 500 XP. Mock/fight route: 100 XP after winning the duel.",
            warnings = "Paladins cannot take the ring-delivery route. The reward is 120 gold, not 1,200; the duel is a distinct route.",
            searchTags = listOf("the braggart", "chapter 4", "dar")
        ),
        Quest(
            id = "CH4-008",
            chapter = 4,
            playOrder = 8,
            title = "A Dragon Egg for Neoras",
            category = "Chapter 4",
            giver = "Neoras",
            location = "Chapter 4",
            prerequisites = "Chapter 4; Fire Mage or paladin, with access to the monastery and a dragon egg.",
            summary = "Give Neoras a dragon egg and choose between a permanent potion or alternative rewards.",
            walkthroughSteps = listOf("As a Fire Mage or paladin, talk to Neoras in the monastery cellar about an unusual potion.", "Bring him a dragon egg from the lizardmen-guarded caves of Khorinis.", "Choose your reward: wait one day for a potion increasing your primary attribute by 3, or immediately take three Healing Elixirs or the Ring of Spiritual Power."),
            reward = "1,000 XP plus your choice of a +3 primary-stat potion after one day, three Healing Elixirs, or the Ring of Spiritual Power.",
            warnings = "Fire Mage/paladin only. All Khorinis dragon eggs are useful for four Embarla Firgasto potions on Irdorath; consider saving the egg rather than completing this quest.",
            searchTags = listOf("a dragon egg for neoras", "chapter 4", "neoras")
        ),
        Quest(
            id = "CH4-009",
            chapter = 4,
            playOrder = 9,
            title = "Ragnar's Trial",
            category = "Chapter 4",
            giver = "Ragnar",
            location = "Chapter 4",
            prerequisites = "Complete Neoras's Assistant from Chapter 2 and reach Chapter 4.",
            summary = "Speak with Ragnar.",
            walkthroughSteps = listOf("After completing Neoras's Assistant, speak with Ragnar in the monastery in Chapter 4.", "Ragnar must make a Fire Arrow/Fire Bolt rune for his Fire Trial but cannot create one himself.", "As a Fire Mage, craft the required rune, or recover one from the chest at Sekob's farm that previously held The Halls of Irdorath book.", "Give the rune to Ragnar, then read the book Ghostly Flame that he rewards you with to start Secrets of the Old Book."),
            reward = "2,500 XP and the book Ghostly Flame, which triggers Secrets of the Old Book.",
            warnings = "You may craft a Fire Arrow rune as a Fire Mage or use the rune from Sekob's chest; the rewarded Ghostly Flame book is needed to start the follow-up.",
            searchTags = listOf("ragnar's trial", "chapter 4", "ragnar")
        ),
        Quest(
            id = "CH4-010",
            chapter = 4,
            playOrder = 10,
            title = "Secrets of the Old Book",
            category = "Chapter 4",
            giver = "Reading the book Ghostly Flame (automatic)",
            location = "Chapter 4",
            prerequisites = "Chapter 4; finish Ragnar's Trial and read Ghostly Flame.",
            summary = "Investigate Amon Shen, collect four pieces of the dragon-summoning staff and forge it once Chapter 5 materials are available.",
            walkthroughSteps = listOf("Read Ghostly Flame (+1,000 XP), then find Amon Shen, also called Acheron's Tower, on the Khorinis coast.", "The Shadowfiend guarding the tower is immune to ordinary damage; use holy light magic (available from paladin sources such as Martin or Ingmar). Search the tower and read the note naming Kreol.", "Find Kreol in the Valley of Mines' Cave of Mists; after learning about the staff (+1,000 XP), hunt its three missing pieces: Hoshkar in the Sleeper's Temple, Cor Kalom in the Masyaf storyline, and Shadow Lord Inubis in the crypt beyond Onar's manor (available in Chapter 5).", "Show Kreol the three pieces (+3,000 XP), receive the fourth piece and collect four dragon skulls and one dragon eye.", "Forge the staff at an anvil. Equip it from the ring/accessory inventory to summon a rune dragon that fights for you."),
            reward = "Dragon-summoning staff (equippable accessory); documented staged XP of 1,000 for the book, 1,000 for Kreol's first explanation and 3,000 after showing the pieces.",
            warnings = "Cannot finish before Chapter 5 because Inubis's piece is not available earlier. Dragon skulls are also used for the best armor, so avoid spending them accidentally. The tower guardian needs holy magic.",
            searchTags = listOf("secrets of the old book", "chapter 4", "ragnar / ragnar's book")
        ),
        Quest(
            id = "CH4-011",
            chapter = 4,
            playOrder = 11,
            title = "Lost?",
            category = "Chapter 4",
            giver = "Scout faction contact (master index)",
            location = "Chapter 4",
            prerequisites = "Chapter 4; Scout faction. Listed in the April 2026 master quest index but the standalone walkthrough is not available.",
            summary = "Index-confirmed Chapter 4 Scout entry titled Lost?; exact giver, location and resolution remain unverified.",
            walkthroughSteps = listOf("This quest appears in the April 2026 New Balance Scout index as Lost?, immediately before On the Trail of Betrayal.", "No standalone, corroborated solution was found for this exact entry; check Allen and your Scout journal for its trigger rather than following invented coordinates.", "If it is not in your journal, continue the Scout chapter progression and check after returning to the hideout."),
            reward = "Unverified; the index does not document a specific reward.",
            warnings = "Unresolved reference entry: do not confuse Lost? with the documented On the Trail of Betrayal quest. The guide does not invent a missing NPC.",
            searchTags = listOf("lost?", "chapter 4", "scout faction contact (master index)")
        ),
        Quest(
            id = "CH4-012",
            chapter = 4,
            playOrder = 12,
            title = "On the Trail of Betrayal",
            category = "Chapter 4",
            giver = "Allen",
            location = "Chapter 4",
            prerequisites = "Chapter 4; Scouts; complete Fingers' Treasury and Chasing Darkness.",
            summary = "Recover the Horn of Fear stolen by the possessed Nathaniel and decide whether to save him.",
            walkthroughSteps = listOf("Return to Allen after opening Fingers' Treasury and completing Chasing Darkness. Nathaniel has stolen the Horn of Fear. Read his note and speak with Allen.", "Take the note to Pyrokar for decoding; he identifies the Fire Trial cave near the Black Troll.", "Enter the cave, defeat two Dark Masters, then the Shadow General and his dark-mage guards; recover the Horn of Fear.", "Outside, decide whether to kill Nathaniel (Innos karma -10, Beliar +10) or spare and escort him to Pyrokar (Innos +10).", "Deliver the Horn to Pyrokar, talk with Nathaniel again if spared, and return to Allen to complete the Scout storyline."),
            reward = "Staged XP: 500 on assignment, 100 for the note, 250 from Pyrokar, 500 after Nathaniel, 1,000 for returning the Horn, and optional 100 for speaking with spared Nathaniel; Allen gives 5,000 XP, 1,000 gold and a King's Sorrel Extract.",
            warnings = "Read Nathaniel's note and speak to Pyrokar in the intended order before entering the Fire Trial cave; the cave may not populate correctly if the triggers are skipped.",
            searchTags = listOf("on the trail of betrayal", "chapter 4", "allen")
        ),
        Quest(
            id = "CH4-013",
            chapter = 4,
            playOrder = 13,
            title = "Mercenaries Near the Manor",
            category = "Chapter 4",
            giver = "Mercenary outside Demon Hunters' manor",
            location = "Chapter 4",
            prerequisites = "Chapter 4; Demon Hunters faction. No journal entry is created for this short encounter.",
            summary = "Confront two mercenaries outside the Demon Hunters' manor and speak with Severin and Angel after the fight.",
            walkthroughSteps = listOf("As a Demon Hunter, return to the manor during Chapter 4 and talk to the two mercenaries outside (+300 XP).", "Severin approaches during the conversation; talk to him to trigger a fight (+200 XP).", "Help Severin defeat the two mercenaries if necessary, then speak to him again (+200 XP).", "Report the confrontation to Angel (+100 XP)."),
            reward = "300 XP for talking to the mercenaries, 200 XP as the battle starts, 200 XP for speaking to Severin afterward and 100 XP for reporting to Angel.",
            warnings = "This is an unjournaled encounter, not a missing quest bug. Demon Hunter players only.",
            searchTags = listOf("mercenaries near the manor", "chapter 4", "demon hunter faction contact (master index)")
        ),
        Quest(
            id = "CH4-014",
            chapter = 4,
            playOrder = 14,
            title = "Demon from the Void",
            category = "Chapter 4",
            giver = "Angel",
            location = "Chapter 4",
            prerequisites = "Chapter 4; Demon Hunter faction; complete Challenge of the Demon.",
            summary = "Recover a fallen Brotherhood novice's notes from the Sleeper's Temple for Angel.",
            walkthroughSteps = listOf("Speak with Angel at the Demon Hunters' manor; he asks for ritual research on the demon Azag-Toth.", "Travel through the Sleeper's Temple to the area before the Sleeper's chamber.", "Defeat the zombie of a former Brotherhood novice and loot/read his notes (+300 XP).", "Bring the notes to Angel (+1,000 XP and a King's Sorrel Extract)."),
            reward = "300 XP for the novice's records; 1,000 XP and a King's Sorrel Extract from Angel.",
            warnings = "The prerequisite is Challenge of the Demon (Act 2), not simply entering the Sleeper's Temple. Read and keep the note for the report.",
            searchTags = listOf("demon from the void", "chapter 4", "angel")
        ),
        Quest(
            id = "CH4-015",
            chapter = 4,
            playOrder = 15,
            title = "Lord of the Abyss",
            category = "Chapter 4",
            giver = "Angel",
            location = "Chapter 4",
            prerequisites = "Chapter 4; Demon Hunters faction; complete Demon from the Void and speak with Angel the following day.",
            summary = "Gather two black ore pieces for Angel's ritual to summon and defeat Azag-Toth.",
            walkthroughSteps = listOf("Return to Angel a day after Demon from the Void. He needs two pieces of black ore to complete Cor Kalom's summoning instructions.", "Give Angel the two pieces (1,000 XP); join the Demon Hunters at the manor's courtyard ritual site (1,000 XP).", "During the ritual defeat Azag-Toth and its summoned demons and skeleton fighters (1,000 XP).", "Tell Lord Hagen about the defeat (+500 XP), then return to Angel (+2,000 XP and a King's Sorrel Extract)."),
            reward = "1,000 XP for black ore, 1,000 XP at the ritual, 1,000 XP after the demon, 500 XP from Hagen, and 2,000 XP plus a King's Sorrel Extract from Angel.",
            warnings = "Bring two pieces of black ore before starting. The ritual has a large allied Demon Hunter group; expect close-quarter combat.",
            searchTags = listOf("lord of the abyss", "chapter 4", "angel")
        ),
        Quest(
            id = "CH4-016",
            chapter = 4,
            playOrder = 16,
            title = "Dragon Treasures",
            category = "Chapter 4",
            giver = "Cassia",
            location = "Chapter 4",
            prerequisites = "Chapter 4; join the Thieves' Guild and speak with Cassia before hunting the four dragons.",
            summary = "Recover the four valuable treasures hidden in the dragons' locked hoard chests.",
            walkthroughSteps = listOf("Accept Cassia's request before leaving for the Valley of Mines.", "Kill each of the four main dragons, loot the key from its body and unlock its treasure chest; keep the special treasure item from each.", "Collect the golden dagger, golden horn, diamond necklace and precious crown.", "Bring all four items to Cassia and complete each reward dialogue."),
            reward = "Golden dagger: 1,500 XP and Dexterity Elixir. Golden horn: 1,500 XP and 500 gold. Diamond necklace: 1,000 XP and 1,000 gold. Precious crown: 2,500 XP and 2,000 gold. Final bonus: +1 Dexterity and +5 Thieves' Guild reputation.",
            warnings = "Each dragon carries a key to its separate treasure chest. The four objects are distinct; killing the dragons without looting the hoards does not finish Cassia's quest.",
            searchTags = listOf("dragon treasures", "chapter 4", "cassia")
        ),
        Quest(
            id = "CH4-017",
            chapter = 4,
            playOrder = 17,
            title = "Orcs in the Valley",
            category = "Chapter 4",
            giver = "Saturas",
            location = "Chapter 4",
            prerequisites = "Chapter 4; return to Jharkendar and speak with Saturas.",
            summary = "Eliminate five high shamans and the orc chieftain Ur-Catan occupying Jharkendar.",
            walkthroughSteps = listOf("In Chapter 4, find Saturas beside the Jharkendar portal. He reports that orcs have invaded the Valley of the Builders.", "Kill high shaman Var-Hat at the Scholars' Temple in the canyon; Var-Shat at the Guardians of the Dead temple near the black-troll bridge; Var-Kaz at the Priests' Temple; Var-Hash at the Healers' Temple in the swamp; and Var-Naz at the Warriors' Temple in the bandit camp.", "Enter the final hall of the Temple of Adanos (Raven's former arena), defeat orc chieftain Ur-Catan, and collect any proof.", "Report all six leaders to Saturas."),
            reward = "1,000 XP for each of five high shamans, 2,000 XP for chieftain Ur-Catan, and 5,000 XP plus a King's Sorrel Extract from Saturas (Water Mages receive a Spirit Elixir instead).",
            warnings = "Saturas is found by the portal when the invasion starts. Clear all five Builder temples plus the final hall of the Temple of Adanos; killing only the five shamans is insufficient.",
            searchTags = listOf("orcs in the valley", "chapter 4", "saturas")
        ),
        Quest(
            id = "CH4-018",
            chapter = 4,
            playOrder = 18,
            title = "Scatty's Gold",
            category = "Chapter 4",
            giver = "Scatty",
            location = "Chapter 4",
            prerequisites = "Chapter 4 only; finish before Chapter 5. Talk to Scatty among the surviving bandits on the pirates' northern beach.",
            summary = "Retrieve 500 gold nuggets from Scatty's old mine-entrance chest, keep half and return the rest.",
            walkthroughSteps = listOf("In Chapter 4, find surviving bandits in the cave by the pirates' northern beach; speak with Thorus about the bandit camp (+500 XP).", "Ask Scatty about his abandoned savings and receive the chest key.", "Return to the old bandit camp mine entrance, where Scatty formerly stood; open his chest and take 500 gold nuggets.", "Deliver half (250 nuggets) to Scatty, keeping the other half."),
            reward = "Keep 250 gold nuggets (equivalent to about 3,000 gold after smelting, if you know the method), plus 1,000 XP and a King's Sorrel Extract from Scatty; optional 500 XP from Thorus.",
            warnings = "Complete before Chapter 5. The April 2026 guide reports Scatty turns hostile and cancels the quest if you keep his half too long.",
            searchTags = listOf("scatty's gold", "chapter 4", "scatty")
        ),
        Quest(
            id = "CH4-019",
            chapter = 4,
            playOrder = 19,
            title = "Talbin's Escape",
            category = "Chapter 4",
            giver = "Talbin",
            location = "Chapter 4",
            prerequisites = "Chapter 4; find Talbin and ask about Engrom.",
            summary = "Talbin is worried about his missing friend Engrom.",
            walkthroughSteps = listOf("Talbin is worried about his missing friend Engrom. Engrom's body is near Cavalorn's old hut, in the area where Marcos is stationed. Tell Talbin what happened; he leaves for the pass. The community guide recommends teleporting to the pass immediately so Talbin relocates safely instead of walking through danger. Speak with him at the Valley of Mines pass. Once he reaches Khorinis, he can later be recruited to your camp."),
            reward = "Quest XP and Talbin's survival/recruitment availability.",
            warnings = "Talbin can die while travelling if the route is allowed to play out normally. Save first and use the pass/teleport transition promptly. Fire Mage runs can differ because Engrom may still be alive and possessed.",
            searchTags = listOf("talbin's escape", "chapter 4", "talbin")
        ),
        Quest(
            id = "CH4-020",
            chapter = 4,
            playOrder = 20,
            title = "Dragon Hunters",
            category = "Chapter 4",
            giver = "First Dragon Hunter encountered near the pass",
            location = "Chapter 4",
            prerequisites = "Chapter 4; enter the Valley of Mines during the dragon hunt.",
            summary = "This companion quest begins when you speak with the first Dragon Hunter you meet around the Valley pass.",
            walkthroughSteps = listOf("This companion quest begins when you speak with the first Dragon Hunter you meet around the Valley pass. Continue the main dragon-hunting route, speaking with the hunters you encounter and progressing through the Valley. The quest remains active through the hunt and closes when the last of the four main dragons is killed."),
            reward = "Quest XP when the dragon-hunter objective closes, plus normal dragon-hunt loot.",
            warnings = "This is separate from the main Dragon Hunt journal entry even though both progress together.",
            searchTags = listOf("dragon hunters", "chapter 4", "first dragon hunter encountered near the pass")
        ),
        Quest(
            id = "CH4-021",
            chapter = 4,
            playOrder = 21,
            title = "Two Ice Golems for Sylvio",
            category = "Chapter 4",
            giver = "Sylvio",
            location = "Chapter 4",
            prerequisites = "Chapter 4; reach Sylvio's camp at the entrance to the frozen region.",
            summary = "Speak with Sylvio.",
            walkthroughSteps = listOf("Speak with Sylvio. Two ice golems killed his men and block the route into the frozen territory. Kill both ice golems and return to Sylvio to report the result."),
            reward = "Quest XP and Sylvio's reward; exact values depend on the current build.",
            warnings = "After the Ice Dragon is defeated, Sylvio and Bullco will turn on you. Finish any dialogue you want with them before progressing beyond that point.",
            searchTags = listOf("two ice golems for sylvio", "chapter 4", "sylvio")
        ),
        Quest(
            id = "CH4-022",
            chapter = 4,
            playOrder = 22,
            title = "Filthy Sty",
            category = "Chapter 4",
            giver = "Brutus",
            location = "Chapter 4",
            prerequisites = "Chapter 4; access to the castle.",
            summary = "Speak with Brutus in the castle.",
            walkthroughSteps = listOf("Speak with Brutus in the castle. Meatbugs have infested his chamber. Enter the room, kill the insects tied to the quest and return to Brutus once the room is clear."),
            reward = "Quest XP and Brutus' reward.",
            warnings = "Earlier catalogue versions normalized this title rather crudely as \"Stinking Shit\"; \"Filthy Sty\" is the cleaner English title used here.",
            searchTags = listOf("filthy sty", "chapter 4", "brutus")
        ),
        Quest(
            id = "CH4-023",
            chapter = 4,
            playOrder = 23,
            title = "Hunger",
            category = "Chapter 4",
            giver = "Gerold",
            location = "Chapter 4",
            prerequisites = "Chapter 4; access to the castle.",
            summary = "Gerold, the prison guard, is hungry.",
            walkthroughSteps = listOf("Gerold, the prison guard, is hungry. Arrange to meet him at night in the mages' quarters inside the castle, then give him the food requested by the dialogue. Speak with him again if necessary to close the journal entry."),
            reward = "Quest XP and Gerold's reward.",
            warnings = "The meeting is time/location sensitive. If the hand-in dialogue is missing, wait until night and check the mages' building rather than his daytime post.",
            searchTags = listOf("hunger", "chapter 4", "gerold")
        ),
        Quest(
            id = "CH4-024",
            chapter = 4,
            playOrder = 24,
            title = "Theft",
            category = "Chapter 4",
            giver = "Keroloth",
            location = "Chapter 4",
            prerequisites = "Chapter 4; access to the castle.",
            summary = "Keroloth believes the Dragon Hunters stole his purse.",
            walkthroughSteps = listOf("Keroloth believes the Dragon Hunters stole his purse. Search the area around the castle forge; the missing purse is lying nearby. Pick it up and return it to Keroloth."),
            reward = "Quest XP and Keroloth's reward.",
            warnings = "The purse is a world item close to the forge, so search the ground carefully before accusing or attacking anyone.",
            searchTags = listOf("theft", "chapter 4", "keroloth")
        ),
        Quest(
            id = "CH4-025",
            chapter = 4,
            playOrder = 25,
            title = "Feros's Sword",
            category = "Chapter 4",
            giver = "Feros",
            location = "Chapter 4",
            prerequisites = "Chapter 4; speak with Feros in/around the castle.",
            summary = "Feros tells you that he lost his sword.",
            walkthroughSteps = listOf("Feros tells you that he lost his sword. Travel to the cliff where the orc shaman Hosh-Pak is stationed; the sword can be found on that cliff. Pick it up and return it to Feros. <PARSED TEXT FOR PAGE: 9 / 10> GOTHIC II: NEW BALANCE | CHAPTER 4 QUEST GUIDE SliverzFX Guide Project | Chapter 4 | CH4-001 to CH4-030"),
            reward = "Quest XP and Feros's reward.",
            warnings = "This objective is efficient to combine with the Hosh-Pak quest because both use the same area.",
            searchTags = listOf("feros's sword", "chapter 4", "feros")
        ),
        Quest(
            id = "CH4-026",
            chapter = 4,
            playOrder = 26,
            title = "Lost in the Dark",
            category = "Chapter 4",
            giver = "Udar",
            location = "Chapter 4",
            prerequisites = "Chapter 4; access to the castle and dialogue with Udar.",
            summary = "Udar tells you that the paladin Sengrath left the castle and has not returned.",
            walkthroughSteps = listOf("Udar tells you that the paladin Sengrath left the castle and has not returned. Follow the palisade outside the castle until you find Sengrath's body. Take his crossbow and return to Udar with the news."),
            reward = "Quest XP and the associated item/dialogue reward.",
            warnings = "Loot the body before leaving; the crossbow is part of the return sequence.",
            searchTags = listOf("lost in the dark", "chapter 4", "udar")
        ),
        Quest(
            id = "CH4-027",
            chapter = 4,
            playOrder = 27,
            title = "Hosh-Pak",
            category = "Chapter 4",
            giver = "Oric",
            location = "Chapter 4",
            prerequisites = "Chapter 4; speak with Oric in the castle.",
            summary = "Oric orders you to kill the orc shaman Hosh-Pak.",
            walkthroughSteps = listOf("Oric orders you to kill the orc shaman Hosh-Pak. Hosh-Pak is stationed on the cliff near the cave with the stone steps. Kill him, loot the body and return to Oric to report the kill."),
            reward = "Quest XP and progression to Orc Warlords.",
            warnings = "Feros's lost sword is in the same general cliff area, so collect it during this trip. Hosh-Pak is also tied to Ur-Shak's story, so complete any dialogue you want with Ur-Shak before or after the kill as appropriate.",
            searchTags = listOf("hosh-pak", "chapter 4", "oric")
        ),
        Quest(
            id = "CH4-028",
            chapter = 4,
            playOrder = 28,
            title = "Orc Warlords",
            category = "Chapter 4",
            giver = "Oric",
            location = "Chapter 4",
            prerequisites = "Complete Hosh-Pak.",
            summary = "After Hosh-Pak is dead, speak with Oric again.",
            walkthroughSteps = listOf("After Hosh-Pak is dead, speak with Oric again. He asks you to eliminate four named orc leaders commanding the siege around the castle. Hunt down all four leaders in the Valley, loot their bodies for any proof/items and return to Oric once all four are dead."),
            reward = "Quest XP and Oric's completion reward.",
            warnings = "Named orc leaders often carry useful rings or quest items. Loot them before leaving their patrol areas.",
            searchTags = listOf("orc warlords", "chapter 4", "oric")
        ),
        Quest(
            id = "CH4-029",
            chapter = 4,
            playOrder = 29,
            title = "Jan and the Smithy",
            category = "Chapter 4",
            giver = "Jan",
            location = "Chapter 4",
            prerequisites = "Chapter 4; Jan is in the castle and wants access to the forge.",
            summary = "Jan wants to work as the castle smith, but Parcival objects.",
            walkthroughSteps = listOf("Jan wants to work as the castle smith, but Parcival objects. You can speak with Parcival first, but it is not required. Go directly to Garond and ask him to authorize Jan to use the smithy. Once Garond agrees, return to Jan and give him the good news."),
            reward = "Quest XP and access to Jan's smithing-related services/dialogue.",
            warnings = "The community guide notes that Parcival can be skipped entirely; Garond's approval is the decisive step.",
            searchTags = listOf("jan and the smithy", "chapter 4", "jan")
        ),
        Quest(
            id = "CH4-030",
            chapter = 4,
            playOrder = 30,
            title = "No Turning Back",
            category = "Chapter 4",
            giver = "Garond",
            location = "Chapter 4",
            prerequisites = "Chapter 4; speak with Garond after the castle situation advances.",
            summary = "Garond asks you to find the smith Dobar and his assistant Parlaf.",
            walkthroughSteps = listOf("Garond asks you to find the smith Dobar and his assistant Parlaf. Dobar's body is in the territory between the orc battering ram and the palisade. Parlaf is alive and hiding in Gilbert's cave, to the left of the barricade leading into the orc-held lands. Find Parlaf and escort him toward the castle; bringing him to the area in front of the battering ram is sufficient for the safe-arrival trigger. Return to Garond with the news."),
            reward = "Quest XP and Garond's reward; the community guide notes that Parlaf-survival extras are not especially valuable.",
            warnings = "This quest is time-limited: Parlaf can die if you delay too long. Save before starting the search and prioritize his rescue. Older catalogue wording used \"To Run or Not to Run\"; the current guide uses the clearer title \"No Turning Back\".",
            searchTags = listOf("no turning back", "chapter 4", "garond")
        )
    )
}
