package com.sliverzfx.gothicquest

object NewBalanceChapter4Data {
    val quests = listOf(
        Quest(
            id = "CH4-001",
            chapter = 4,
            playOrder = 1,
            title = "Dragon Hunt",
            category = "Chapter 4",
            giver = "Pyrokar",
            location = "Chapter 4",
            prerequisites = "The Eye of Innos has been restored; Chapter 4 begins.",
            summary = "Use the restored Eye of Innos to confront the four dragons in the Valley of Mines, charging it between kills.",
            walkthroughSteps = listOf("After the Eye of Innos ritual, ask Pyrokar how to use the amulet; travel to the Valley of Mines and speak to Garond (500 XP) and Oric for dragon locations.", "Keep the charged Eye in your inventory before speaking to each dragon; you do not need to wear it. Defeat the dragon's summoned elementals promptly because they help it regenerate.", "Recommended order: swamp dragon Pandrodor in the swamp near Cavalorn's old hut (Cypher and Rod may assist), stone dragon Pedrakhan at the ruined Stone Fortress, fire dragon Feomathar in the volcanic crater, then ice dragon Finkregh in the ruins of the former New Camp.", "After each dragon dies, loot its heart and hoard; at an alchemy table recharge the Eye using the heart under the special-potions tab before confronting the next dragon.", "Return to Garond to report each dragon's death. After all four, make the final report to Garond to complete the hunt and advance toward Chapter 5.", "Optionally tell Kurgan, Milten, Pyrokar, Vatras, Lord Hagen and Netbek about the dragons for extra dialogue XP."),
            reward = "500 XP for Garond's first briefing; 5,000 XP and 1,000 gold per dragon reported, plus 5,000 XP for defeating all four. Additional report XP is available from Kurgan (100), Milten (500), Pyrokar (2,000), Vatras (500), Hagen (1,000) and Netbek (1,000).",
            warnings = "A charged Eye must be in your inventory when you SPEAK to each dragon, not equipped. Recharge at an alchemy table with the dragon's heart after each kill; kill spawned elementals to curb dragon regeneration.",
            searchTags = listOf("dragon hunt", "chapter 4", "pyrokar")
        ),
        Quest(
            id = "CH4-002",
            chapter = 4,
            playOrder = 2,
            title = "Lobart's Orc Problem",
            category = "Chapter 4",
            giver = "Lobart",
            location = "Chapter 4",
            prerequisites = "Chapter 4; return to Lobart's farm after the orc invasion begins.",
            summary = "Kill the orcs that have overrun Lobart's farm in Chapter 4 and report to him.",
            walkthroughSteps = listOf("Ask Lobart about the orcs that have invaded his farm during Chapter 4.", "Clear all the orcs threatening the farm and nearby farm approaches; check for survivors before returning.", "Tell Lobart the orcs are gone to receive your payment."),
            reward = "1,000 XP and 100 gold from Lobart after clearing the orcs.",
            warnings = "Orc patrols in Chapter 4 can overlap with lizardmen guarding dragon eggs. Search the bodies and nearby caves instead of leaving immediately after the combat.",
            searchTags = listOf("lobart's orc problem", "chapter 4", "lobart")
        ),
        Quest(
            id = "CH4-003",
            chapter = 4,
            playOrder = 3,
            title = "Orc Squads",
            category = "Chapter 4",
            giver = "Lord Hagen",
            location = "Chapter 4",
            prerequisites = "Chapter 4; the orc invasion of Khorinis has begun.",
            summary = "Defeat the Orc Squad commander near Bartok's hunting forest and turn in more than twenty orc-elder rings to Lord Hagen.",
            walkthroughSteps = listOf("In Chapter 4, speak with Lord Hagen in Khorinis and show an orc elder's ring (300 XP). Hagen assigns the orc squads.", "Ask Ingmar about the commander, then leave through the south gate toward the wooded route used while hunting with Bartok.", "Go through the forest to the cave where Kriks the Razor's bandits were camped; kill the elite orcs and their commander Fangarh, and take his military map.", "Report Fangarh's defeat to Ingmar for 1,500 XP and 500 gold.", "Use the map to find the Orc elder patrols scattered around Khorinis. Collect more than twenty leader rings and deliver them to Hagen to close the quest.", "Hagen continues taking remaining rings for 200 XP each after completion. Reserve one ring for Dar's The Braggart if you plan that route."),
            reward = "300 XP for showing Hagen an early elder ring; 1,500 XP and 500 gold from Ingmar after killing Fangarh; main quest closes once Hagen receives over twenty elder rings; additional rings earn 200 XP each. An optional initial orc conversation grants 100 XP.",
            warnings = "Save at least one Orc Warlord's/elder's ring for Dar's The Braggart quest if available. Fangarh's map reveals additional patrol locations.",
            searchTags = listOf("orc squads", "chapter 4", "lord hagen / ingmar")
        ),
        Quest(
            id = "CH4-004",
            chapter = 4,
            playOrder = 4,
            title = "News for Vatras",
            category = "Chapter 4",
            giver = "Saturas (Vatras directs the visit)",
            location = "Chapter 4",
            prerequisites = "After the Eye of Innos restoration ritual, then Chapter 4 to complete Saturas's Orcs in the Valley quest.",
            summary = "Check on Saturas in Jharkendar for Vatras, defeat the orc occupation and report back.",
            walkthroughSteps = listOf("After restoring the Eye of Innos, speak to Vatras; he asks you to visit Saturas and check on the Water Mages.", "Begin Chapter 4 and travel through the portal to Jharkendar. Speak to Saturas about the valley's orc invasion.", "Complete Saturas's Orcs in the Valley quest by clearing the occupation.", "Return to Khorinis and tell Vatras that the Water Mages are safe."),
            reward = "1,000 XP and 300 gold from Vatras.",
            warnings = "The initial request can be received after restoring the Eye, but Jharkendar's invasion does not begin until Chapter 4. Finish Orcs in the Valley before reporting.",
            searchTags = listOf("news for vatras", "chapter 4", "vatras")
        ),
        Quest(
            id = "CH4-005",
            chapter = 4,
            playOrder = 5,
            title = "Deprivation",
            category = "Chapter 4",
            giver = "Randolph",
            location = "Chapter 4",
            prerequisites = "Chapter 4; paladin only. Randolph must be alive and at Akil's farm.",
            summary = "Find Sagitta's remedy to help Randolph stop drinking.",
            walkthroughSteps = listOf("As a paladin in Chapter 4, speak with Randolph at Akil's farm about his attempt to quit drinking.", "Visit Sagitta's cave and pay 300 gold for her anti-addiction medicine.", "Bring the medicine to Randolph and speak with him again."),
            reward = "500 XP and 150 gold from Randolph. Sagitta's potion costs 300 gold.",
            warnings = "The April 2026 New Balance guide restricts this quest to paladins; buying the cure has a 300-gold cost and yields a net loss of 150 gold.",
            searchTags = listOf("deprivation", "chapter 4", "randolph")
        ),
        Quest(
            id = "CH4-006",
            chapter = 4,
            playOrder = 6,
            title = "Dragon Eggs",
            category = "Chapter 4",
            giver = "Bennet",
            location = "Chapter 4",
            prerequisites = "Chapter 4; obtain a dragon egg and speak with Bennet. Primarily associated with the mercenary/Dragon Hunter route.",
            summary = "Collect dragon eggs from lizardmen-guarded caves, deciding whether to sell them to Bennet or preserve them for the powerful Irdorath potion.",
            walkthroughSteps = listOf("Show Bennet a dragon egg and agree to discuss selling them. He gives you information/a map for the Khorinis caves where eggs can be found. Search the marked caves, kill the lizardmen guarding them and collect the eggs. Bennet will buy the eggs you bring back."),
            reward = "Bennet offers 350 gold and 300 XP for each dragon egg sold. An Irdorath recipe consumes nine eggs per Embarla Firgasto potion; each dose grants warriors +10 Strength or Dexterity, or mages +20 Mana (up to four potions with enough eggs).",
            warnings = "If you intend to brew Embarla Firgasto in Chapter 6, KEEP your eggs: the recipe takes nine per potion and up to four potions can be made. Selling eggs to Bennet is irreversible.",
            searchTags = listOf("dragon eggs", "chapter 4", "bennet")
        ),
        Quest(
            id = "CH4-007",
            chapter = 4,
            playOrder = 7,
            title = "The Braggart",
            category = "Chapter 4",
            giver = "Dar",
            location = "Chapter 4",
            prerequisites = "Chapter 4; Dar alive. The orc-ring route is unavailable to paladins.",
            summary = "Either help Dar boast with an Orc elder's ring or laugh at him and win a fistfight.",
            walkthroughSteps = listOf("Speak to Dar at Onar's farm in Chapter 4.", "If you ask what would impress Lee, Dar requests an orc warlord/elder ring taken from a black-orc leader. Reserve one from Orc Squads and give it to him.", "Choose between the Dexterity Amulet reward or a small gold payment.", "Alternatively, mock Dar instead of helping him; defeat him in the resulting duel to end the quest for a smaller XP reward."),
            reward = "Ring route: Dexterity Amulet and 600 XP, OR 120 gold and 500 XP. Mock/fight route: 100 XP after winning the duel.",
            warnings = "Paladins cannot take the ring-delivery route. The reward is 120 gold, not 1,200; the duel is a distinct route.",
            searchTags = listOf("the braggart", "chapter 4", "dar")
        ),
        Quest(
            id = "CH4-008",
            chapter = 4,
            playOrder = 8,
            title = "A Dragon Egg for Neoras",
            category = "Chapter 4",
            giver = "Neoras",
            location = "Chapter 4",
            prerequisites = "Chapter 4; Fire Mage or paladin, with access to the monastery and a dragon egg.",
            summary = "Give Neoras a dragon egg and choose between a permanent potion or alternative rewards.",
            walkthroughSteps = listOf("As a Fire Mage or paladin, talk to Neoras in the monastery cellar about an unusual potion.", "Bring him a dragon egg from the lizardmen-guarded caves of Khorinis.", "Choose your reward: wait one day for a potion increasing your primary attribute by 3, or immediately take three Healing Elixirs or the Ring of Spiritual Power."),
            reward = "1,000 XP plus your choice of a +3 primary-stat potion after one day, three Healing Elixirs, or the Ring of Spiritual Power.",
            warnings = "Fire Mage/paladin only. All Khorinis dragon eggs are useful for four Embarla Firgasto potions on Irdorath; consider saving the egg rather than completing this quest.",
            searchTags = listOf("a dragon egg for neoras", "chapter 4", "neoras")
        ),
        Quest(
            id = "CH4-009",
            chapter = 4,
            playOrder = 9,
            title = "Ragnar's Trial",
            category = "Chapter 4",
            giver = "Ragnar",
            location = "Chapter 4",
            prerequisites = "Complete Neoras's Assistant from Chapter 2 and reach Chapter 4.",
            summary = "Speak with Ragnar.",
            walkthroughSteps = listOf("After completing Neoras's Assistant, speak with Ragnar in the monastery in Chapter 4.", "Ragnar must make a Fire Arrow/Fire Bolt rune for his Fire Trial but cannot create one himself.", "As a Fire Mage, craft the required rune, or recover one from the chest at Sekob's farm that previously held The Halls of Irdorath book.", "Give the rune to Ragnar, then read the book Ghostly Flame that he rewards you with to start Secrets of the Old Book."),
            reward = "2,500 XP and the book Ghostly Flame, which triggers Secrets of the Old Book.",
            warnings = "You may craft a Fire Arrow rune as a Fire Mage or use the rune from Sekob's chest; the rewarded Ghostly Flame book is needed to start the follow-up.",
            searchTags = listOf("ragnar's trial", "chapter 4", "ragnar")
        ),
        Quest(
            id = "CH4-010",
            chapter = 4,
            playOrder = 10,
            title = "Secrets of the Old Book",
            category = "Chapter 4",
            giver = "Reading the book Ghostly Flame (automatic)",
            location = "Chapter 4",
            prerequisites = "Chapter 4; finish Ragnar's Trial and read Ghostly Flame.",
            summary = "Investigate Amon Shen, collect four pieces of the dragon-summoning staff and forge it once Chapter 5 materials are available.",
            walkthroughSteps = listOf("Read Ghostly Flame (+1,000 XP), then find Amon Shen, also called Acheron's Tower, on the Khorinis coast.", "The Shadowfiend guarding the tower is immune to ordinary damage; use holy light magic (available from paladin sources such as Martin or Ingmar). Search the tower and read the note naming Kreol.", "Find Kreol in the Valley of Mines' Cave of Mists; after learning about the staff (+1,000 XP), hunt its three missing pieces: Hoshkar in the Sleeper's Temple, Cor Kalom in the Masyaf storyline, and Shadow Lord Inubis in the crypt beyond Onar's manor (available in Chapter 5).", "Show Kreol the three pieces (+3,000 XP), receive the fourth piece and collect four dragon skulls and one dragon eye.", "Forge the staff at an anvil. Equip it from the ring/accessory inventory to summon a rune dragon that fights for you."),
            reward = "Dragon-summoning staff (equippable accessory); documented staged XP of 1,000 for the book, 1,000 for Kreol's first explanation and 3,000 after showing the pieces.",
            warnings = "Cannot finish before Chapter 5 because Inubis's piece is not available earlier. Dragon skulls are also used for the best armor, so avoid spending them accidentally. The tower guardian needs holy magic.",
            searchTags = listOf("secrets of the old book", "chapter 4", "ragnar / ragnar's book")
        ),
        Quest(
            id = "CH4-011",
            chapter = 4,
            playOrder = 11,
            title = "Lost?",
            category = "Chapter 4",
            giver = "Scout faction contact (master index)",
            location = "Chapter 4",
            prerequisites = "Chapter 4; Scout faction. Listed in the April 2026 master quest index but the standalone walkthrough is not available.",
            summary = "Index-confirmed Chapter 4 Scout entry titled Lost?; exact giver, location and resolution remain unverified.",
            walkthroughSteps = listOf("This quest appears in the April 2026 New Balance Scout index as Lost?, immediately before On the Trail of Betrayal.", "No standalone, corroborated solution was found for this exact entry; check Allen and your Scout journal for its trigger rather than following invented coordinates.", "If it is not in your journal, continue the Scout chapter progression and check after returning to the hideout."),
            reward = "Unverified; the index does not document a specific reward.",
            warnings = "Unresolved reference entry: do not confuse Lost? with the documented On the Trail of Betrayal quest. The guide does not invent a missing NPC.",
            searchTags = listOf("lost?", "chapter 4", "scout faction contact (master index)")
        ),
        Quest(
            id = "CH4-012",
            chapter = 4,
            playOrder = 12,
            title = "On the Trail of Betrayal",
            category = "Chapter 4",
            giver = "Allen",
            location = "Chapter 4",
            prerequisites = "Chapter 4; Scouts; complete Fingers' Treasury and Chasing Darkness.",
            summary = "Recover the Horn of Fear stolen by the possessed Nathaniel and decide whether to save him.",
            walkthroughSteps = listOf("Return to Allen after opening Fingers' Treasury and completing Chasing Darkness. Nathaniel has stolen the Horn of Fear. Read his note and speak with Allen.", "Take the note to Pyrokar for decoding; he identifies the Fire Trial cave near the Black Troll.", "Enter the cave, defeat two Dark Masters, then the Shadow General and his dark-mage guards; recover the Horn of Fear.", "Outside, decide whether to kill Nathaniel (Innos karma -10, Beliar +10) or spare and escort him to Pyrokar (Innos +10).", "Deliver the Horn to Pyrokar, talk with Nathaniel again if spared, and return to Allen to complete the Scout storyline."),
            reward = "Staged XP: 500 on assignment, 100 for the note, 250 from Pyrokar, 500 after Nathaniel, 1,000 for returning the Horn, and optional 100 for speaking with spared Nathaniel; Allen gives 5,000 XP, 1,000 gold and a King's Sorrel Extract.",
            warnings = "Read Nathaniel's note and speak to Pyrokar in the intended order before entering the Fire Trial cave; the cave may not populate correctly if the triggers are skipped.",
            searchTags = listOf("on the trail of betrayal", "chapter 4", "allen")
        ),
        Quest(
            id = "CH4-013",
            chapter = 4,
            playOrder = 13,
            title = "Mercenaries Near the Manor",
            category = "Chapter 4",
            giver = "Mercenary outside Demon Hunters' manor",
            location = "Chapter 4",
            prerequisites = "Chapter 4; Demon Hunters faction. No journal entry is created for this short encounter.",
            summary = "Confront two mercenaries outside the Demon Hunters' manor and speak with Severin and Angel after the fight.",
            walkthroughSteps = listOf("As a Demon Hunter, return to the manor during Chapter 4 and talk to the two mercenaries outside (+300 XP).", "Severin approaches during the conversation; talk to him to trigger a fight (+200 XP).", "Help Severin defeat the two mercenaries if necessary, then speak to him again (+200 XP).", "Report the confrontation to Angel (+100 XP)."),
            reward = "300 XP for talking to the mercenaries, 200 XP as the battle starts, 200 XP for speaking to Severin afterward and 100 XP for reporting to Angel.",
            warnings = "This is an unjournaled encounter, not a missing quest bug. Demon Hunter players only.",
            searchTags = listOf("mercenaries near the manor", "chapter 4", "demon hunter faction contact (master index)")
        ),
        Quest(
            id = "CH4-014",
            chapter = 4,
            playOrder = 14,
            title = "Demon from the Void",
            category = "Chapter 4",
            giver = "Angel",
            location = "Chapter 4",
            prerequisites = "Chapter 4; Demon Hunter faction; complete Challenge of the Demon.",
            summary = "Recover a fallen Brotherhood novice's notes from the Sleeper's Temple for Angel.",
            walkthroughSteps = listOf("Speak with Angel at the Demon Hunters' manor; he asks for ritual research on the demon Azag-Toth.", "Travel through the Sleeper's Temple to the area before the Sleeper's chamber.", "Defeat the zombie of a former Brotherhood novice and loot/read his notes (+300 XP).", "Bring the notes to Angel (+1,000 XP and a King's Sorrel Extract)."),
            reward = "300 XP for the novice's records; 1,000 XP and a King's Sorrel Extract from Angel.",
            warnings = "The prerequisite is Challenge of the Demon (Act 2), not simply entering the Sleeper's Temple. Read and keep the note for the report.",
            searchTags = listOf("demon from the void", "chapter 4", "angel")
        ),
        Quest(
            id = "CH4-015",
            chapter = 4,
            playOrder = 15,
            title = "Lord of the Abyss",
            category = "Chapter 4",
            giver = "Angel",
            location = "Chapter 4",
            prerequisites = "Chapter 4; Demon Hunters faction; complete Demon from the Void and speak with Angel the following day.",
            summary = "Gather two black ore pieces for Angel's ritual to summon and defeat Azag-Toth.",
            walkthroughSteps = listOf("Return to Angel a day after Demon from the Void. He needs two pieces of black ore to complete Cor Kalom's summoning instructions.", "Give Angel the two pieces (1,000 XP); join the Demon Hunters at the manor's courtyard ritual site (1,000 XP).", "During the ritual defeat Azag-Toth and its summoned demons and skeleton fighters (1,000 XP).", "Tell Lord Hagen about the defeat (+500 XP), then return to Angel (+2,000 XP and a King's Sorrel Extract)."),
            reward = "1,000 XP for black ore, 1,000 XP at the ritual, 1,000 XP after the demon, 500 XP from Hagen, and 2,000 XP plus a King's Sorrel Extract from Angel.",
            warnings = "Bring two pieces of black ore before starting. The ritual has a large allied Demon Hunter group; expect close-quarter combat.",
            searchTags = listOf("lord of the abyss", "chapter 4", "angel")
        ),
        Quest(
            id = "CH4-016",
            chapter = 4,
            playOrder = 16,
            title = "Dragon Treasures",
            category = "Chapter 4",
            giver = "Cassia",
            location = "Chapter 4",
            prerequisites = "Chapter 4; join the Thieves' Guild and speak with Cassia before hunting the four dragons.",
            summary = "Recover the four valuable treasures hidden in the dragons' locked hoard chests.",
            walkthroughSteps = listOf("Accept Cassia's request before leaving for the Valley of Mines.", "Kill each of the four main dragons, loot the key from its body and unlock its treasure chest; keep the special treasure item from each.", "Collect the golden dagger, golden horn, diamond necklace and precious crown.", "Bring all four items to Cassia and complete each reward dialogue."),
            reward = "Golden dagger: 1,500 XP and Dexterity Elixir. Golden horn: 1,500 XP and 500 gold. Diamond necklace: 1,000 XP and 1,000 gold. Precious crown: 2,500 XP and 2,000 gold. Final bonus: +1 Dexterity and +5 Thieves' Guild reputation.",
            warnings = "Each dragon carries a key to its separate treasure chest. The four objects are distinct; killing the dragons without looting the hoards does not finish Cassia's quest.",
            searchTags = listOf("dragon treasures", "chapter 4", "cassia")
        ),
        Quest(
            id = "CH4-017",
            chapter = 4,
            playOrder = 17,
            title = "Orcs in the Valley",
            category = "Chapter 4",
            giver = "Saturas",
            location = "Chapter 4",
            prerequisites = "Chapter 4; return to Jharkendar and speak with Saturas.",
            summary = "Eliminate five high shamans and the orc chieftain Ur-Catan occupying Jharkendar.",
            walkthroughSteps = listOf("In Chapter 4, find Saturas beside the Jharkendar portal. He reports that orcs have invaded the Valley of the Builders.", "Kill high shaman Var-Hat at the Scholars' Temple in the canyon; Var-Shat at the Guardians of the Dead temple near the black-troll bridge; Var-Kaz at the Priests' Temple; Var-Hash at the Healers' Temple in the swamp; and Var-Naz at the Warriors' Temple in the bandit camp.", "Enter the final hall of the Temple of Adanos (Raven's former arena), defeat orc chieftain Ur-Catan, and collect any proof.", "Report all six leaders to Saturas."),
            reward = "1,000 XP for each of five high shamans, 2,000 XP for chieftain Ur-Catan, and 5,000 XP plus a King's Sorrel Extract from Saturas (Water Mages receive a Spirit Elixir instead).",
            warnings = "Saturas is found by the portal when the invasion starts. Clear all five Builder temples plus the final hall of the Temple of Adanos; killing only the five shamans is insufficient.",
            searchTags = listOf("orcs in the valley", "chapter 4", "saturas")
        ),
        Quest(
            id = "CH4-018",
            chapter = 4,
            playOrder = 18,
            title = "Scatty's Gold",
            category = "Chapter 4",
            giver = "Scatty",
            location = "Chapter 4",
            prerequisites = "Chapter 4 only; finish before Chapter 5. Talk to Scatty among the surviving bandits on the pirates' northern beach.",
            summary = "Retrieve 500 gold nuggets from Scatty's old mine-entrance chest, keep half and return the rest.",
            walkthroughSteps = listOf("In Chapter 4, find surviving bandits in the cave by the pirates' northern beach; speak with Thorus about the bandit camp (+500 XP).", "Ask Scatty about his abandoned savings and receive the chest key.", "Return to the old bandit camp mine entrance, where Scatty formerly stood; open his chest and take 500 gold nuggets.", "Deliver half (250 nuggets) to Scatty, keeping the other half."),
            reward = "Keep 250 gold nuggets (equivalent to about 3,000 gold after smelting, if you know the method), plus 1,000 XP and a King's Sorrel Extract from Scatty; optional 500 XP from Thorus.",
            warnings = "Complete before Chapter 5. The April 2026 guide reports Scatty turns hostile and cancels the quest if you keep his half too long.",
            searchTags = listOf("scatty's gold", "chapter 4", "scatty")
        ),
        Quest(
            id = "CH4-019",
            chapter = 4,
            playOrder = 19,
            title = "Talbin's Escape",
            category = "Chapter 4",
            giver = "Talbin",
            location = "Chapter 4",
            prerequisites = "Chapter 4; find Talbin and ask about Engrom.",
            summary = "Find Engrom, then help Talbin escape from the Valley of Mines to Khorinis.",
            walkthroughSteps = listOf("In Chapter 4, ask Talbin about Engrom. Search for Engrom near Marcos's camp at Cavalorn's old hut; take the snapper hide from his body (or, as a Fire Mage, subdue the possessed Engrom first).", "Tell Talbin of Engrom's fate (+1,000 XP). He flees toward the Valley of Mines mountain pass.", "Find Talbin by the pass entrance, help him kill the snapper threatening him, and agree to escort him through the pass.", "Cross the area transition into Khorinis; Talbin appears beside the pond beyond the gate. Speak with him for the reward.", "Later find Talbin at Akil's farm; if your own camp recruitment quest is active, you may invite him there."),
            reward = "1,000 XP on reporting Engrom's fate; 600 XP and a piece of magic ore after helping Talbin reach Khorinis.",
            warnings = "Talbin must survive his meeting with the snapper by the pass. In Fire Mage runs, Engrom can be alive but possessed; subdue him and retrieve the snapper hide. Talbin can join the player camp after this quest.",
            searchTags = listOf("talbin's escape", "chapter 4", "talbin")
        ),
        Quest(
            id = "CH4-020",
            chapter = 4,
            playOrder = 20,
            title = "Dragon Hunters",
            category = "Chapter 4",
            giver = "Automatic on entering the Valley of Mines in Chapter 4",
            location = "Chapter 4",
            prerequisites = "Chapter 4; enter the Valley of Mines.",
            summary = "Automatic chapter-wide tracker for the four-dragon hunt.",
            walkthroughSteps = listOf("Enter the Valley of Mines during Chapter 4; this quest starts automatically without a speaking quest giver.", "Follow the main Dragon Hunt path and kill the swamp, stone, fire and ice dragons.", "This tracker closes after the fourth dragon dies; Dragon Hunt has its own reporting and Eye of Innos steps."),
            reward = "Progress tracks the defeat of all four dragons; the 2026 guide does not document a separate XP award for this automatic journal entry.",
            warnings = "This is automatic and does not require speaking with a Dragon Hunter near the pass. It is distinct from Pyrokar's Dragon Hunt.",
            searchTags = listOf("dragon hunters", "chapter 4", "first dragon hunter encountered near the pass")
        ),
        Quest(
            id = "CH4-021",
            chapter = 4,
            playOrder = 21,
            title = "Two Ice Golems for Sylvio",
            category = "Chapter 4",
            giver = "Sylvio",
            location = "Chapter 4",
            prerequisites = "Chapter 4; reach Sylvio's camp at the entrance to the frozen region.",
            summary = "Kill the two ice golems blocking Sylvio's approach to the frozen New Camp.",
            walkthroughSteps = listOf("Find Sylvio and Bullco at the campfire beside the route to the former New Camp.", "Accept Sylvio's request to kill the two ice golems at the entrance.", "Defeat both ice golems and return to Sylvio."),
            reward = "1,000 XP from Sylvio.",
            warnings = "Complete Sylvio's dialogue before defeating the Ice Dragon; his relationship with you changes afterward.",
            searchTags = listOf("two ice golems for sylvio", "chapter 4", "sylvio")
        ),
        Quest(
            id = "CH4-022",
            chapter = 4,
            playOrder = 22,
            title = "Filthy Sty",
            category = "Chapter 4",
            giver = "Brutus",
            location = "Chapter 4",
            prerequisites = "Chapter 4; access to the castle.",
            summary = "Clear the meatbugs from Brutus's castle room.",
            walkthroughSteps = listOf("Find Brutus standing outside his chamber inside Garond's castle and ask why he refuses to enter.", "Kill all the meatbugs in his chamber.", "Return to Brutus once the room is clear. He resumes his normal routine."),
            reward = "350 XP and 100 gold; afterward you can frighten Brutus with meatbugs in dialogue.",
            warnings = "The insects are meatbugs inside Brutus's room, not monsters outside the castle.",
            searchTags = listOf("filthy sty", "chapter 4", "brutus")
        ),
        Quest(
            id = "CH4-023",
            chapter = 4,
            playOrder = 23,
            title = "Hunger",
            category = "Chapter 4",
            giver = "Gerold",
            location = "Chapter 4",
            prerequisites = "Chapter 4; access to the castle.",
            summary = "Feed the hungry prison guard Gerold secretly in the castle chapel after 23:30.",
            walkthroughSteps = listOf("Speak with Gerold near Garond's castle prison. He is hungry but refuses food while at his post.", "After 23:30, meet him at the castle chapel rather than the mages' quarters.", "Bring food he accepts—fish soup, stew, ham, cheese, sausage or roasted meat—and keep offering it while his dialogue allows.", "Finish his dialogue to collect the reward; it depends on how much food you provided."),
            reward = "Up to 500 XP and 200 gold, depending on the amount of acceptable food delivered.",
            warnings = "The correct meeting place is the CHAPEL after 23:30, not the mages' building.",
            searchTags = listOf("hunger", "chapter 4", "gerold")
        ),
        Quest(
            id = "CH4-024",
            chapter = 4,
            playOrder = 24,
            title = "Theft",
            category = "Chapter 4",
            giver = "Keroloth",
            location = "Chapter 4",
            prerequisites = "Chapter 4; access to the castle.",
            summary = "Find Keroloth's missing purse by the forge and settle the accusation against the Dragon Hunters.",
            walkthroughSteps = listOf("Speak with Keroloth in the Valley of Mines castle; he believes Dragon Hunters stole his purse.", "Pick up the purse on the ground beside the bench near the forge.", "Return the purse to Keroloth and answer his accusation based on your guild.", "As a Dragon Hunter, you must either fight him or accuse Jan; other factions can generally end the dispute peacefully."),
            reward = "400 XP for returning the purse, plus an optional 50 gold for non-Fire-Mage characters.",
            warnings = "Dragon Hunter dialogue can force a fight with Keroloth or an accusation against Jan. Choose carefully if you want to preserve friendly NPC relations.",
            searchTags = listOf("theft", "chapter 4", "keroloth")
        ),
        Quest(
            id = "CH4-025",
            chapter = 4,
            playOrder = 25,
            title = "Feros's Sword",
            category = "Chapter 4",
            giver = "Feros",
            location = "Chapter 4",
            prerequisites = "Chapter 4; speak with Feros in/around the castle.",
            summary = "Retrieve Feros's sword from the ground beside Hosh-Pak's tent.",
            walkthroughSteps = listOf("Speak to Feros in Garond's castle during Chapter 4.", "Go to Hosh-Pak's encampment on the southeastern cliff near the castle; look on the ground BESIDE his tent for Feros's sword.", "Return the correct named sword to Feros. With 50 rhetoric, ask for his family ring.", "Speak with Feros again if you want his Strength or Dexterity training."),
            reward = "700 XP; with 50 rhetoric, Feros's family ring grants +1 rhetoric. Feros also becomes a Strength/Dexterity trainer.",
            warnings = "The sword is on the ground by Hosh-Pak's tent, not necessarily on Hosh-Pak's body. Requires 50 rhetoric for Feros's extra ring.",
            searchTags = listOf("feros's sword", "chapter 4", "feros")
        ),
        Quest(
            id = "CH4-026",
            chapter = 4,
            playOrder = 26,
            title = "Lost in the Dark",
            category = "Chapter 4",
            giver = "Udar",
            location = "Chapter 4",
            prerequisites = "Chapter 4; access to the castle and dialogue with Udar.",
            summary = "Discover Sengrath's death near the orc palisade and bring his crossbow back to Udar.",
            walkthroughSteps = listOf("Ask Udar in Garond's castle about Sengrath's disappearance after losing his crossbow to an orc.", "Follow the outer palisade toward its beginning, where Sengrath's body lies in the mist.", "Retrieve his crossbow and return it to Udar."),
            reward = "700 XP from Udar.",
            warnings = "You must loot Sengrath's crossbow from his corpse for the return dialogue.",
            searchTags = listOf("lost in the dark", "chapter 4", "udar")
        ),
        Quest(
            id = "CH4-027",
            chapter = 4,
            playOrder = 27,
            title = "Hosh-Pak",
            category = "Chapter 4",
            giver = "Oric",
            location = "Chapter 4",
            prerequisites = "Chapter 4; speak with Oric in the castle.",
            summary = "Kill Hosh-Pak, the orc high shaman commanding the siege, and report back to Oric.",
            walkthroughSteps = listOf("Speak to Oric in Garond's castle about Hosh-Pak; he offers an advance permanent potion choice.", "Leave by the castle battering ram and turn right toward the raised southeastern cliff and Hosh-Pak's camp.", "Defeat the shaman and surviving guards; collect Feros's lost sword lying beside Hosh-Pak's tent if needed.", "Report to Oric. If Hosh-Pak was killed before accepting the quest, Oric can still recognize the result."),
            reward = "2,500 XP from Oric, with a choice of permanent potion available as an advance.",
            warnings = "Hosh-Pak is connected to Ur-Shak's personal storyline. Killing him can change Ur-Shak's attitude and prevent a peaceful reunion route; resolve any Ur-Shak dialogue or objectives first.",
            searchTags = listOf("hosh-pak", "chapter 4", "oric")
        ),
        Quest(
            id = "CH4-028",
            chapter = 4,
            playOrder = 28,
            title = "Orc Warlords",
            category = "Chapter 4",
            giver = "Oric",
            location = "Chapter 4",
            prerequisites = "Complete Hosh-Pak.",
            summary = "Kill the four orc warlords commanding forces around the Valley of Mines castle.",
            walkthroughSteps = listOf("After Hosh-Pak is dead, ask Oric if he has more work. You can take a permanent potion choice as an advance.", "Hunt down the four named warlords around the siege: Nar-Shag, Dur-Kash, Tum-Pak and Nur-Shak.", "Defeat all four and report to Oric; already defeated targets count for the assignment."),
            reward = "4,000 XP from Oric, plus the optional permanent-potion advance.",
            warnings = "These four leaders are separate from Khorinis's Orc Squads, whose elder rings go to Lord Hagen.",
            searchTags = listOf("orc warlords", "chapter 4", "oric")
        ),
        Quest(
            id = "CH4-029",
            chapter = 4,
            playOrder = 29,
            title = "Jan and the Smithy",
            category = "Chapter 4",
            giver = "Jan",
            location = "Chapter 4",
            prerequisites = "Chapter 4, before Chapter 5; meet Jan in the castle.",
            summary = "Get Garond's permission for Jan to operate the castle forge.",
            walkthroughSteps = listOf("Speak with Jan in Garond's castle; he wants to use the forge but distrust from the paladins prevents him.", "Talk directly to Garond and vouch for Jan (Parcival is not required).", "Tell Jan that Garond approved his smithing work.", "Dragon Hunter characters can then ask Jan for instruction in weapons and armor forging."),
            reward = "400 XP; Jan's forging instruction becomes available to Dragon Hunters.",
            warnings = "Complete before Chapter 5. Garond's approval is sufficient; you do not need Parcival's permission.",
            searchTags = listOf("jan and the smithy", "chapter 4", "jan")
        ),
        Quest(
            id = "CH4-030",
            chapter = 4,
            playOrder = 30,
            title = "No Turning Back",
            category = "Chapter 4",
            giver = "Garond",
            location = "Chapter 4",
            prerequisites = "Chapter 4; complete Jan and the Smithy; begin only when ready for a timed rescue (about seven days).",
            summary = "Locate missing smith Dobar and safely guide his assistant Parlaf back to Garond's castle.",
            walkthroughSteps = listOf("After finishing Jan and the Smithy, speak with Garond about missing Dobar and Parlaf (+1,000 XP). This starts a time-limited quest.", "Preferably clear the orc siege near the battering ram before accepting; Parlaf may die if you leave the quest for more than about seven days.", "Find Parlaf alive in Gilbert's cave by the approach from the battering ram, talk to him (+300 XP) and lead him back toward the castle.", "Reach the battering ram with Parlaf for the safe-arrival trigger (+500 XP); he gives five steel billets, or a rune stone if you are a mage.", "Find Dobar's corpse in the small wooded strip between the castle's battering ram and the orc palisade.", "Tell Garond that Dobar died (+150 XP), complete the rescue report (+2,000 XP), and optionally speak to Parlaf in the castle again (+200 XP)."),
            reward = "1,000 XP on accepting, 300 XP for finding Parlaf, 500 XP for safely escorting him, 2,000 XP for final Garond report, optional 150 XP for Dobar and 200 XP for Parlaf's later conversation; five steel billets or a rune stone (mages) from Parlaf.",
            warnings = "TIME LIMIT: Parlaf can die after roughly seven days. Finish Jan and the Smithy first, clear the nearby orcs before starting, and escort him promptly.",
            searchTags = listOf("no turning back", "chapter 4", "garond")
        )
    )
}
