package com.sliverzfx.gothicquest

object NewBalanceChapter5Data {
    val quests = listOf(
        Quest(
            id = "CH5-001",
            chapter = 5,
            playOrder = 1,
            title = "Lord of the Dragons",
            category = "Main Story",
            giver = "Last defeated dragon (automatic after dialogue)",
            location = "Valley of Mines → Monastery of Innos → Xardas's Tower",
            prerequisites = "Chapter 5; defeat all four Valley of Mines dragons and speak to the last one about its master.",
            summary = "Find the way to the Halls of Irdorath by reopening the monastery's forbidden library.",
            walkthroughSteps = listOf("Question the final dragon about the master of dragons. Return to Pyrokar at the monastery; he describes Irdorath as a vanished eastern temple of Beliar.", "Ask Pyrokar about the book Halls of Irdorath. Go to the monastery basement; Talomon lets you pass to the lower library where the book sits on a crate, but it will not yet open.", "Travel to Xardas's tower. Lester explains Xardas has disappeared, warns of undead at the tower and hands over Xardas's letter. Read it for the clue to the book.", "Revisit the book: reading it now gives 2,000 XP and drops a key and note. Read it again to learn of the secret section of the monastery library; the note identifies the lamp beside the library crate as the mechanism.", "Return to the monastery and operate that lamp to open the hidden passage. Fight through the corrupted knights and face the cursed Fire Mage Ilkrus, then reach the secret library.", "Explore the library carefully. Fire Mages can find the Tears of Innos. Read the almanac for 1,000 XP, collect the book and map, inspect the map and read the new book for 2,000 XP.", "Tell Talomon what you found for 1,000 XP, then consult Pyrokar about arranging a ship, choosing a captain and assembling a crew."),
            reward = "2,000 XP from opening the first book, 1,000 XP from the almanac, 2,000 XP from the secret-library book, and 1,000 XP from Talomon; optional 100 XP joking with Pyrokar. Opens ship, captain and crew preparations.",
            warnings = "The first book cannot be opened until you have read Xardas's letter. Do not overlook the lamp switch, dropped key and note, the map, or the Tears of Innos for eligible mages.",
            searchTags = listOf("lord of the dragons", "main story", "the last dragon / main-story progression")
        ),
        Quest(
            id = "CH5-002",
            chapter = 5,
            playOrder = 2,
            title = "I Need a Ship",
            category = "Main Story",
            giver = "Automatic when reading Irdorath material in the secret monastery library",
            location = "Monastery → Town Hall / Brotherhood camp → Esmeralda",
            prerequisites = "Chapter 5; progress Lord of the Dragons until you read the book in the monastery's secret library.",
            summary = "Secure the Esmeralda for the voyage; authorization depends on your guild.",
            walkthroughSteps = listOf("After reading the Irdorath location material in the monastery's hidden library, the need for a ship is recorded automatically.", "Brotherhood members (Guru or Temple Guard): accept Good Connections from Idol Oran, return after he obtains the authorization and buy the permit for 2,000 gold.", "Mercenaries / Dragon Hunters: speak to Lee. If you completed The Judge's Lackey and Judge Rister is available, demand the judge's ship document for 5,000 XP, then tell Lee you obtained it for another 100 XP. If Rister is dead, Lee can provide forged paperwork.", "Other factions: arrange a captain in Who Will Be My Captain? and enlist at least five crew members in No Voyage Without a Crew, then claim use of the paladin ship.", "Go to the Esmeralda in Khorinis harbor with the required authorization (when relevant), captain and crew, and complete the departure dialogue once all unfinished local content is handled."),
            reward = "Access to the Esmeralda and the Chapter 6 expedition; the mercenary judge-document route grants 5,000 XP and 100 XP for reporting to Lee. Other XP depends on the supporting quests.",
            warnings = "The quest starts automatically, not from a generic trigger NPC. Leaving for Irdorath is a practical point of no return; finish any remaining Khorinis, Jharkendar and Valley of Mines quests first.",
            searchTags = listOf("i need a ship", "main story", "automatic / main-story progression")
        ),
        Quest(
            id = "CH5-003",
            chapter = 5,
            playOrder = 3,
            title = "Who Will Be My Captain?",
            category = "Main Story",
            giver = "Jorgen, Jack or Torlof (chosen captain)",
            location = "Monastery / Lighthouse / Onar's Farm → Esmeralda",
            prerequisites = "Chapter 5; I Need a Ship active.",
            summary = "Choose Jorgen, Jack or Torlof as captain, each with a different requirement and outcome.",
            walkthroughSteps = listOf("Jorgen: ask the monk at the monastery to command the Esmeralda. Pyrokar refuses until his work debt is settled; complete Pyrokar's Return to the Tower quest. Then recruit Jorgen for 2,000 XP.", "Jack: finish Bandits in Jack's Lighthouse. Jack agrees to captain only if someone minds the lighthouse; persuade Brian, Harad's apprentice, to replace him, then recruit Jack for 1,000 XP.", "Torlof: find him at Onar's farm. On his route, travel to Garond's Valley of Mines castle and open its main gate so the orcs can invade, then return to Torlof for 200 XP.", "Pay Torlof his required 2,500 gold. His route incurs -200 Innos karma and +100 Beliar karma but he can teach Strength and Dexterity on Irdorath.", "Once ONE captain agrees, continue No Voyage Without a Crew and ship preparations; the captain-selection quest grants 3,000 XP when completed."),
            reward = "2,000 XP for Jorgen, or 1,000 XP for Jack, or 200 XP from Torlof's gate task; 3,000 XP for finishing captain selection. Torlof additionally charges 2,500 gold.",
            warnings = "Opening Garond's gate is an irreversible hostile choice with major karma consequences. Jack or Jorgen avoids that outcome; only one captain is necessary.",
            searchTags = listOf("who will be my captain?", "main story", "main-story preparation")
        ),
        Quest(
            id = "CH5-004",
            chapter = 5,
            playOrder = 4,
            title = "No Voyage Without a Crew",
            category = "Main Story",
            giver = "Any eligible companion invited to the voyage",
            location = "Khorinis / Onar's Farm / Monastery → Esmeralda",
            prerequisites = "Chapter 5; I Need a Ship active. Invite at least five eligible companions.",
            summary = "Recruit at least five companions to staff the Esmeralda, choosing useful allies and services for Irdorath.",
            walkthroughSteps = listOf("Invite a minimum of five eligible companions after the voyage is planned. Each accepted invitation awards 500 XP. A captain is a separate requirement.", "Diego joins after Diego's Business and offers advice and trade. Lester joins and has special dialogue concerning Mario. Gorn, Lee, Lares and Biff can also be invited as available.", "Milten offers potions and magic training; Vatras heals, provides limited cures for possession, teaches magic circles and sells potions.", "Wolf refuses if you previously assigned him to defend Bengar's farm in Alone and Defenseless. Bennet sells weapons and has armor-related follow-up content on Irdorath.", "Girion can receive orc warlord rings. Angar requires completion of Angar's Amulet and helps later on Irdorath. Mario may join but has a dangerous possession-related later storyline.", "After recruiting the desired group, return to the Esmeralda, verify the captain and crew, and initiate departure when ready."),
            reward = "500 XP for EACH recruited companion; at least five are required, plus their respective trading, healing, crafting or training services on Irdorath.",
            warnings = "An accepted NPC may show a duplicate invitation line; avoid mistakenly re-inviting or undoing a choice. Wolf is unavailable after Bengar's guard job, and Mario has a later Seeker-related storyline.",
            searchTags = listOf("no voyage without a crew", "main story", "main-story preparation")
        ),
        Quest(
            id = "CH5-005",
            chapter = 5,
            playOrder = 5,
            title = "Rosie's Disappearance",
            category = "Khorinis — Rosie's Escort",
            giver = "Rosie",
            location = "Road between Dead Harpy and Water Mages' excavation → faction destination",
            prerequisites = "Chapter 5; Rosie and Till must still be alive and available on the road.",
            summary = "Escort Rosie and Till to safety; the destination depends on the hero's guild.",
            walkthroughSteps = listOf("Travel the road from Orlan's Dead Harpy tavern toward the Water Mages' excavation site and find Rosie travelling with Till.", "Speak to Rosie. She has fled Sekob and asks for safe passage away from his farm.", "Paladin, Demon Hunter, Scout or Necromancer: escort her to Khorinis city.", "Dragon Hunter or Dark Knight: escort her to Onar's farm. Fire Mage or Water Mage: escort her to the monastery. Guru or Temple Guard: escort her to the Brotherhood camp.", "Keep both escorts close, clear dangerous enemies on the chosen route and reach the proper destination; Rosie starts her arrival dialogue to finish the quest."),
            reward = "1,250 XP and 200 gold once Rosie reaches the guild-specific destination.",
            warnings = "You cannot use the same destination for every guild. Do not force Rosie and Till back to Sekob unless you deliberately want a different quest outcome.",
            searchTags = listOf("rosie's disappearance", "khorinis island", "rosie / encounter on the road")
        ),
        Quest(
            id = "CH5-006",
            chapter = 5,
            playOrder = 6,
            title = "Dark Order",
            category = "Khorinis — Undead Invasion",
            giver = "Lord Hagen",
            location = "Khorinis → Monastery → Kreol → three tombs → Ginnok's crypt",
            prerequisites = "Chapter 5; report the death of all four dragons and return to Khorinis.",
            summary = "Investigate the undead invasion and put four cursed paladin lords to rest.",
            walkthroughSteps = listOf("After the dragons' defeat, return to Khorinis, where undead now attack the roads and gates. Speak with Lord Hagen; he sends you to Pyrokar at the monastery.", "Pyrokar suspects the artifact Chromanin is linked to the invasion (+2,000 XP). Visit necromancer Kreol in the Valley of Mines (+1,000 XP); he disputes the theory and reveals that cursed paladin lords lead the undead.", "Return to Pyrokar (+2,000 XP) and receive keys to three tombs: Lord Inubis near Onar's farm, Lord Ulzar behind the cemetery near the Dead Harpy, and Lord Mirat in the cave near the Sun Circle.", "Use the tomb keys, defeat each cursed lord and their undead guardians, and search the crypts. Return to Pyrokar after all three (+5,000 XP).", "Because the invasion continues, ask Lord Hagen about another cursed paladin, Ginnok. Go to the depression between the southern and eastern gates of Khorinis, enter Ginnok's crypt and defeat him and the converted paladins he summons.", "Take the forging recipe from Ginnok's body (ore armor and black-ore jewelry) and report final success to Lord Hagen (+5,000 XP). Optionally ask Lee about the undead for 200 XP."),
            reward = "Documented dialogue rewards include 2,000 XP from initial Pyrokar investigation, 1,000 XP from Kreol, 2,000 XP for the return, 5,000 XP after three tombs, and 5,000 XP from Lord Hagen after Ginnok; optionally 200 XP from Lee. Ginnok's forging recipe.",
            warnings = "Some builds have progression trouble if Inubis is killed before Pyrokar's tomb keys are issued. Obtain the keys first; Ulzar/Mirat keyholes may be on a nearby cave wall rather than the door itself.",
            searchTags = listOf("dark order", "khorinis - upper quarter", "lord hagen")
        ),
        Quest(
            id = "CH5-007",
            chapter = 5,
            playOrder = 7,
            title = "Urban Bandits",
            category = "Khorinis — Hidden Encounters",
            giver = "None — unjournaled encounter",
            location = "Khorinis barracks / marketplace / stage / Matteo / harbor tavern",
            prerequisites = "Chapter 5; relevant Jharkendar bandits must have survived the earlier chapter.",
            summary = "Find the six surviving Jharkendar bandits who relocated into Khorinis and speak to each.",
            walkthroughSteps = listOf("Chapter 5 quietly relocates surviving bandits from Jharkendar to Khorinis. This is not a journal quest and requires no formal acceptance.", "Find Thorus and Scatty at the militia barracks and speak to each separately for 500 XP apiece.", "Speak with Fisk in the marketplace (500 XP), Miguel near the stage (500 XP), and Tom near Matteo's workshop (500 XP).", "Find Snaf in the harbor tavern and talk to him (500 XP). The encounter is complete for guide purposes after all available survivors have been addressed."),
            reward = "500 XP per surviving named bandit spoken to; six conversations yield up to 3,000 XP.",
            warnings = "No journal entry or conventional giver exists. These are friendly NPC conversations, not a bandit-clearing combat objective. Some characters may be unavailable if previously killed.",
            searchTags = listOf("urban bandits", "khorinis - upper quarter", "none - hidden chapter 5 event")
        ),
        Quest(
            id = "CH5-008",
            chapter = 5,
            playOrder = 8,
            title = "Return to the Tower",
            category = "Monastery of Innos",
            giver = "Pyrokar",
            location = "Pyrokar → Xardas's Tower → Pyrokar",
            prerequisites = "Chapter 5; Who Will Be My Captain? active and Jorgen proposed as captain.",
            summary = "Earn Pyrokar's permission for Jorgen to captain the Esmeralda by cleansing Xardas's tower.",
            walkthroughSteps = listOf("Speak with Pyrokar and ask him to release Jorgen from monastery service. He requires the tower of Xardas to be cleansed first.", "Travel to Xardas's tower and clear the skeleton warriors throughout the building, including the Demonic Guardian in the library.", "Check each floor thoroughly for surviving enemies, then return to Pyrokar and report the tower cleared.", "Collect 3,000 XP and return to Jorgen to confirm his captain role."),
            reward = "3,000 XP from Pyrokar and Jorgen becomes an available captain, with 2,000 additional XP available through Who Will Be My Captain?.",
            warnings = "The boss is the Demonic Guardian in the tower library. Do not confuse the quest's skeleton-clearing objective with the earlier letter from Lester.",
            searchTags = listOf("return to the tower", "monastery of innos", "pyrokar")
        ),
        Quest(
            id = "CH5-009",
            chapter = 5,
            playOrder = 9,
            title = "Good Connections",
            category = "Brotherhood — Ship Permit",
            giver = "Idol Oran (Baal Oran)",
            location = "Brotherhood camp → Khorinis harbor",
            prerequisites = "Chapter 5; Guru or Temple Guard; I Need a Ship active.",
            summary = "Ask Idol Oran to arrange official access to the paladin ship, then purchase the permit.",
            walkthroughSteps = listOf("As a Guru or Temple Guard in Chapter 5, speak to Idol Oran at the Brotherhood camp about acquiring a ship for Irdorath.", "Oran needs time to arrange a permit through his contacts in Khorinis Town Hall; wait until his promised follow-up conversation becomes available.", "Return to Oran, pay 2,000 gold and take the ship authorization document.", "Show the permit at the Esmeralda, after completing captain and crew preparations, to secure passage."),
            reward = "2,500 XP and the authorization document granting access to the Esmeralda; costs 2,000 gold.",
            warnings = "Only Guru and Temple Guard paths use this quest. The 2,000 gold is a fee, not a payout; speak again to Oran after he finishes his arrangements.",
            searchTags = listOf("good connections", "brotherhood", "baal orun")
        )
    )
}
