package com.sliverzfx.gothicquest

internal object RisenGuidePart6Data {
    val quests: List<Quest> = listOf(
        Quest(
            id = "R1-C2-023",
            chapter = 2,
            playOrder = 23,
            title = "Patty in trouble",
            category = "SAFE — STORY",
            giver = "Balturo / Patty",
            location = "Chapter 2 / World",
            prerequisites = "",
            summary = "Learn that Patty is in danger, then continue her west-coast treasure chain.",
            walkthroughSteps = listOf("Walkthrough. The quest can be triggered by speaking with Balturo in Don Esteban's temple or by progressing Patty's Nameless Graves chain. Speak with Patty about the warning if she is still available. If the grave hunt has already advanced far enough, the quest can resolve through that progression.", "Completion. The objective completes when Patty's danger/disappearance is properly advanced through the treasure chain.", "Related quests: Nameless Graves / Follow Eronga to Romanov"),
            reward = "250 XP",
            warnings = "",
            searchTags = listOf("Patty in trouble", "Balturo / Patty", "Chapter 2 / World", "SAFE — STORY", "Nameless Graves / Follow Eronga to Romanov", "A. PATTY & THE WEST COAST"),
        ),
        Quest(
            id = "R1-C2-024",
            chapter = 2,
            playOrder = 24,
            title = "Off to the west coast",
            category = "SAFE — ESCORT",
            giver = "Patty",
            location = "Chapter 2 / World",
            prerequisites = "",
            summary = "Meet Patty outside Harbour Town and follow her to the western graveyard.",
            walkthroughSteps = listOf("Walkthrough. Speak with Patty and show her the back way out of Harbour Town if necessary. Meet her on the beach outside the city and agree to follow her. She travels toward the graveyard near the crossroads leading toward the swamp. Clearing the road beforehand makes the escort easier.", "Completion. Speak with Patty when she stops at the west-coast graveyard.", "Related quests: Steelbeard's next clue"),
            reward = "300 XP",
            warnings = "",
            searchTags = listOf("Off to the west coast", "Patty", "Chapter 2 / World", "SAFE — ESCORT", "Steelbeard's next clue", "A. PATTY & THE WEST COAST"),
        ),
        Quest(
            id = "R1-C2-025",
            chapter = 2,
            playOrder = 25,
            title = "Steelbeard's next clue",
            category = "SAFE — TREASURE",
            giver = "Patty",
            location = "Chapter 2 / World",
            prerequisites = "",
            summary = "Dig up the grave of the Nameless Scoundrel and recover Steelbeard's old casket.",
            walkthroughSteps = listOf("Walkthrough. After reaching the west-coast graveyard, Patty gives you her master key. Find the grave marked 'Nameless Scoundrel', dig it up and open the hidden chest.", "Completion. Take Steelbeard's casket and return to Patty.", "Related quests: The legacy of the great pirate"),
            reward = "200 XP",
            warnings = "",
            searchTags = listOf("Steelbeard's next clue", "Patty", "Chapter 2 / World", "SAFE — TREASURE", "The legacy of the great pirate", "A. PATTY & THE WEST COAST"),
        ),
        Quest(
            id = "R1-C2-026",
            chapter = 2,
            playOrder = 26,
            title = "The legacy of the great pirate",
            category = "SAFE — PARENT QUEST",
            giver = "Patty",
            location = "Chapter 2 / World",
            prerequisites = "",
            summary = "Complete Patty's five-grave clue hunt, recover Steelbeard's map, rescue Patty and return the map to her.",
            walkthroughSteps = listOf("Walkthrough. This is the umbrella quest for the rest of Patty's Chapter 2 storyline. Complete Nameless Graves, follow Eronga to Romanov, handle Romanov's deal, find Steelbeard's treasure, rescue Patty, and finally recover the nautical map.", "Completion. Give Steelbeard's Nautical Map to Patty.", "Related quests: Nameless Graves / Romanov / Steelbeard's Nautical Map"),
            reward = "500 XP",
            warnings = "⚠ Important: Do not abandon Patty's chain after obtaining the Crystal Disk; the map/rescue steps contain additional quest XP and story.",
            searchTags = listOf("The legacy of the great pirate", "Patty", "Chapter 2 / World", "SAFE — PARENT QUEST", "Nameless Graves / Romanov / Steelbeard's Nautical Map", "A. PATTY & THE WEST COAST"),
        ),
        Quest(
            id = "R1-C2-027",
            chapter = 2,
            playOrder = 27,
            title = "Nameless graves",
            category = "SAFE — FIVE-LOCATION TREASURE HUNT",
            giver = "Patty",
            location = "Chapter 2 / World",
            prerequisites = "",
            summary = "Visit all five marked graves and collect the five Steelbeard mutineer letters.",
            walkthroughSteps = listOf("Walkthrough. Patty marks five graves on the world map. The locations include the small island southeast of Harbour Town, a ledge above Tristan's farm, the western beach near Harbour Town, the area near Leon's hut/farm, and the western route toward Romanov's ruins. Dig up each grave and loot its chest. The grave above Tristan's farm requires dropping down to a ledge; a Levitation effect is useful for getting back.", "Completion. The quest completes after all five grave clues are recovered.", "Related quests: Patty in trouble / Follow Eronga to Romanov"),
            reward = "1000 XP",
            warnings = "⚠ Important: One of the west-coast routes contains many monsters. Vasili can assist during part of the journey.",
            searchTags = listOf("Nameless graves", "Patty", "Chapter 2 / World", "SAFE — FIVE-LOCATION TREASURE HUNT", "Patty in trouble / Follow Eronga to Romanov", "A. PATTY & THE WEST COAST"),
        ),
        Quest(
            id = "R1-C2-028",
            chapter = 2,
            playOrder = 28,
            title = "Follow Eronga to Romanov",
            category = "SAFE — ESCORT",
            giver = "Eronga",
            location = "Chapter 2 / World",
            prerequisites = "",
            summary = "Return to Patty's graveyard, meet Eronga and follow him to the edge of Romanov's ruins.",
            walkthroughSteps = listOf("Walkthrough. After Patty disappears, go back to the graveyard. Eronga appears and offers to take you toward Romanov. Follow him until he stops at the ruins.", "Completion. Eronga points you toward Romanov in the northwest and leaves.", "Related quests: Romanov's deal"),
            reward = "200 XP",
            warnings = "",
            searchTags = listOf("Follow Eronga to Romanov", "Eronga", "Chapter 2 / World", "SAFE — ESCORT", "Romanov's deal", "A. PATTY & THE WEST COAST"),
        ),
        Quest(
            id = "R1-C2-029",
            chapter = 2,
            playOrder = 29,
            title = "Romanov's deal",
            category = "CHOICE — SAVE PATTY RECOMMENDED",
            giver = "Romanov",
            location = "Chapter 2 / World",
            prerequisites = "",
            summary = "Agree to trade Steelbeard's loot/map for Patty, then raid the trapped treasure cave.",
            walkthroughSteps = listOf("Walkthrough. Find Romanov in the far-west ruins. He threatens Patty and demands Steelbeard's treasure. The completionist route is to agree to the exchange because you can still keep most of the treasure and continue Patty's quests.", "Completion. Recover the required treasure/map from Dillinger's chest and return to Romanov for the exchange.", "Related quests: Find Steelbeard's big treasure / Where is Patty?"),
            reward = "500 XP",
            warnings = "⚠ Important: Choose the Patty-rescue route if you want the full Patty storyline. Killing Romanov immediately can shorten or alter the chain.",
            searchTags = listOf("Romanov's deal", "Romanov", "Chapter 2 / World", "CHOICE — SAVE PATTY RECOMMENDED", "Find Steelbeard's big treasure / Where is Patty?", "B. ROMANOV & STEELBEARD'S TREASURE"),
        ),
        Quest(
            id = "R1-C2-030",
            chapter = 2,
            playOrder = 30,
            title = "Find Steelbeard's big treasure",
            category = "SAFE — TREASURE",
            giver = "Romanov / Patty chain",
            location = "Chapter 2 / World",
            prerequisites = "",
            summary = "Reach Dillinger's chest in the west-coast cave and loot the Crystal Disk and Steelbeard's Nautical Map.",
            walkthroughSteps = listOf("Walkthrough. Enter the cave behind/near Romanov's position. Ignore the decoy trapped chests: the important container is Dillinger's chest deeper inside. Fight through the ghouls and dig/open the correct treasure cache.", "Completion. Loot the treasure, including the Golden Crystal Disk and Steelbeard's Nautical Map.", "Related quests: Romanov's deal / Steelbeard's Nautical Map"),
            reward = "1000 XP",
            warnings = "⚠ Important: Several nearby treasure chests are lethal traps. Do not open random chests in the treasure chamber.",
            searchTags = listOf("Find Steelbeard's big treasure", "Romanov / Patty chain", "Chapter 2 / World", "SAFE — TREASURE", "Romanov's deal / Steelbeard's Nautical Map", "B. ROMANOV & STEELBEARD'S TREASURE"),
        ),
        Quest(
            id = "R1-C2-031",
            chapter = 2,
            playOrder = 31,
            title = "Steelbeard's Nautical Map",
            category = "SAFE — STORY",
            giver = "Patty",
            location = "Chapter 2 / World",
            prerequisites = "",
            summary = "After rescuing Patty, recover the nautical map from Romanov and give it to her.",
            walkthroughSteps = listOf("Walkthrough. Once Patty is free, have her follow you toward the beach outside Harbour Town. Confront Romanov and his pirates if the map is still in his possession. Defeat them, loot the map and return it to Patty.", "Completion. Give the map to Patty.", "Related quests: The legacy of the great pirate"),
            reward = "250 XP",
            warnings = "",
            searchTags = listOf("Steelbeard's Nautical Map", "Patty", "Chapter 2 / World", "SAFE — STORY", "The legacy of the great pirate", "B. ROMANOV & STEELBEARD'S TREASURE"),
        ),
        Quest(
            id = "R1-C2-032",
            chapter = 2,
            playOrder = 32,
            title = "Where is Patty?",
            category = "SAFE — RESCUE",
            giver = "Romanov / Patty",
            location = "Chapter 2 / World",
            prerequisites = "",
            summary = "Use Patty's cell key to free her from the ruins south of Romanov's cave.",
            walkthroughSteps = listOf("Walkthrough. If you complete Romanov's deal for Patty's life, ask where she is being held. He gives you the cell key. Return south to the nearby ruined complex and follow the outer cliff/coastal side to the locked cell door.", "Completion. Unlock the door and speak with Patty.", "Related quests: Romanov's deal / Steelbeard's Nautical Map"),
            reward = "400 XP",
            warnings = "",
            searchTags = listOf("Where is Patty?", "Romanov / Patty", "Chapter 2 / World", "SAFE — RESCUE", "Romanov's deal / Steelbeard's Nautical Map", "B. ROMANOV & STEELBEARD'S TREASURE"),
        ),
        Quest(
            id = "R1-C2-033",
            chapter = 2,
            playOrder = 33,
            title = "The gate into the volcano",
            category = "MAIN STORY — CHAPTER FINALE",
            giver = "Inquisitor Mendoza",
            location = "Chapter 2 / World",
            prerequisites = "",
            summary = "Bring all five Crystal Disks to Mendoza and tell him you are ready to open the volcano gate.",
            walkthroughSteps = listOf("Walkthrough. By now you should possess the five disks: Don Esteban's disk, the Eastern Temple disk, the Gyrger's disk, Eldric's repaired disk, and Steelbeard's west-coast disk. Return to Mendoza and hand them over. When ready, tell him to open the gate.", "Completion. The gate opens and the quest completes; speaking with Mendoza afterward begins Chapter 3.", "Related quests: Five Crystal Disks / Chapter 3"),
            reward = "500 XP",
            warnings = "⚠ Important: Finish any Chapter 2 side quests you still care about before deliberately telling Mendoza you are ready.",
            searchTags = listOf("The gate into the volcano", "Inquisitor Mendoza", "Chapter 2 / World", "MAIN STORY — CHAPTER FINALE", "Five Crystal Disks / Chapter 3", "C. FINAL CRYSTAL-DISK HANDOFF"),
        ),
        Quest(
            id = "R1-C2-034",
            chapter = 2,
            playOrder = 34,
            title = "Crystal disks for the Don",
            category = "BANDIT ONLY",
            giver = "Don Esteban",
            location = "Chapter 2 / World",
            prerequisites = "",
            summary = "Collect the remaining Crystal Disks and report your progress to Don Esteban.",
            walkthroughSteps = listOf("Walkthrough. Bandit characters receive a faction-specific journal entry tied to the disk hunt. Don Esteban already controls one disk and expects you to continue the search for the others.", "Completion. Return/report as the disk hunt advances according to the Bandit route.", "Related quests: Main Crystal Disk hunt"),
            reward = "XP / progression",
            warnings = "",
            searchTags = listOf("Crystal disks for the Don", "Don Esteban", "Chapter 2 / World", "BANDIT ONLY", "Main Crystal Disk hunt", "D. BANDIT-ONLY CHAPTER 2 QUESTS"),
        ),
        Quest(
            id = "R1-C2-035",
            chapter = 2,
            playOrder = 35,
            title = "Esteban's return to Harbour Town",
            category = "BANDIT ONLY",
            giver = "Don Esteban",
            location = "Chapter 2 / World",
            prerequisites = "",
            summary = "After the Don's position is secure, complete the faction follow-up concerning his return to Harbour Town.",
            walkthroughSteps = listOf("Walkthrough. This becomes available only on the Bandit path. Speak with Esteban after the Chapter 2 faction conditions are met and follow the dialogue/return sequence.", "Completion. Complete Esteban's faction transition back toward Harbour Town.", "Related quests: Bandit faction progression"),
            reward = "XP / progression",
            warnings = "",
            searchTags = listOf("Esteban's return to Harbour Town", "Don Esteban", "Chapter 2 / World", "BANDIT ONLY", "Bandit faction progression", "D. BANDIT-ONLY CHAPTER 2 QUESTS"),
        ),
        Quest(
            id = "R1-C2-036",
            chapter = 2,
            playOrder = 36,
            title = "The first seal of rune magic",
            category = "MAGE ONLY — 50 WISDOM",
            giver = "Ignatius",
            location = "Chapter 2 / World",
            prerequisites = "",
            summary = "Reach 50 Wisdom and spend 5 Learning Points with Ignatius.",
            walkthroughSteps = listOf("Walkthrough. Speak with Ignatius after becoming a Mage. When your Wisdom reaches 50, buy the first Runic Seal.", "Completion. The seal unlocks after spending 5 Learning Points."),
            reward = "100 XP",
            warnings = "",
            searchTags = listOf("The first seal of rune magic", "Ignatius", "Chapter 2 / World", "MAGE ONLY — 50 WISDOM", "—", "E. MAGE / WARRIOR CHAPTER 2 FOLLOW-UPS"),
        ),
        Quest(
            id = "R1-C2-037",
            chapter = 2,
            playOrder = 37,
            title = "The second seal of rune magic",
            category = "MAGE ONLY — 100 WISDOM",
            giver = "Ignatius",
            location = "Chapter 2 / World",
            prerequisites = "",
            summary = "Reach 100 Wisdom and spend 5 Learning Points with Ignatius.",
            walkthroughSteps = listOf("Walkthrough. Continue collecting Wisdom from books and stone plates. Return to Ignatius at 100 Wisdom.", "Completion. Buy the second Runic Seal."),
            reward = "200 XP",
            warnings = "",
            searchTags = listOf("The second seal of rune magic", "Ignatius", "Chapter 2 / World", "MAGE ONLY — 100 WISDOM", "—", "E. MAGE / WARRIOR CHAPTER 2 FOLLOW-UPS"),
        ),
        Quest(
            id = "R1-C2-038",
            chapter = 2,
            playOrder = 38,
            title = "The third seal of rune magic",
            category = "MAGE ONLY — 150 WISDOM",
            giver = "Ignatius",
            location = "Chapter 2 / World",
            prerequisites = "",
            summary = "Reach 150 Wisdom and spend 5 Learning Points with Ignatius.",
            walkthroughSteps = listOf("Walkthrough. This quest appears in the canonical Chapter 2 Monastery list, but many players naturally reach the Wisdom requirement later. Once you have 150 Wisdom, speak with Ignatius.", "Completion. Spend 5 Learning Points for the third seal."),
            reward = "300 XP",
            warnings = "⚠ Important: Do not treat this as mandatory before opening the volcano gate if your Wisdom is not yet high enough.",
            searchTags = listOf("The third seal of rune magic", "Ignatius", "Chapter 2 / World", "MAGE ONLY — 150 WISDOM", "—", "E. MAGE / WARRIOR CHAPTER 2 FOLLOW-UPS"),
        ),
        Quest(
            id = "R1-C2-039",
            chapter = 2,
            playOrder = 39,
            title = "The fourth seal of rune magic",
            category = "MAGE ONLY — HIGH WISDOM",
            giver = "Ignatius",
            location = "Chapter 2 / World",
            prerequisites = "",
            summary = "Reach the final Wisdom threshold and learn the fourth Runic Seal from Ignatius.",
            walkthroughSteps = listOf("Walkthrough. Continue collecting permanent Wisdom sources and return to Ignatius when the final seal becomes available.", "Completion. Purchase the fourth seal when eligible."),
            reward = "XP / progression",
            warnings = "⚠ Important: This is a Mage progression quest, not a requirement for finishing Chapter 2.",
            searchTags = listOf("The fourth seal of rune magic", "Ignatius", "Chapter 2 / World", "MAGE ONLY — HIGH WISDOM", "—", "E. MAGE / WARRIOR CHAPTER 2 FOLLOW-UPS"),
        ),
        Quest(
            id = "R1-C2-040",
            chapter = 2,
            playOrder = 40,
            title = "The magic bullet",
            category = "WARRIOR / MAGE",
            giver = "Vitus",
            location = "Chapter 2 / World",
            prerequisites = "",
            summary = "Obtain a Magic Crystal and report to Vitus for Magic Bullet training.",
            walkthroughSteps = listOf("Walkthrough. Speak with Vitus after Order/Mage initiation. Bring him the required Magic Crystal and take the training.", "Completion. The crystal-magic quest completes through Vitus."),
            reward = "50 XP",
            warnings = "",
            searchTags = listOf("The magic bullet", "Vitus", "Chapter 2 / World", "WARRIOR / MAGE", "—", "E. MAGE / WARRIOR CHAPTER 2 FOLLOW-UPS"),
        ),
        Quest(
            id = "R1-C2-041",
            chapter = 2,
            playOrder = 41,
            title = "The frost crystal",
            category = "WARRIOR / MAGE",
            giver = "Pallas",
            location = "Chapter 2 / World",
            prerequisites = "",
            summary = "Pay Pallas for Frost Crystal training; a Cold Heart and Small Sapphire reduce the cost.",
            walkthroughSteps = listOf("Walkthrough. Pallas asks 1000 gold. A Bog Body Cold Heart reduces the price by 250 gold and a Small Sapphire reduces it by another 250.", "Completion. Hand over the optional items, pay the remaining cost and receive the Frost Crystal."),
            reward = "100 XP",
            warnings = "",
            searchTags = listOf("The frost crystal", "Pallas", "Chapter 2 / World", "WARRIOR / MAGE", "—", "E. MAGE / WARRIOR CHAPTER 2 FOLLOW-UPS"),
        ),
        Quest(
            id = "R1-C2-042",
            chapter = 2,
            playOrder = 42,
            title = "Assisting the mages",
            category = "MAGE ONLY",
            giver = "Inquisitor Mendoza / Ignatius",
            location = "Chapter 2 / World",
            prerequisites = "",
            summary = "After delivering all five disks, speak with Ignatius as Mendoza requests.",
            walkthroughSteps = listOf("Walkthrough. Mendoza gives this task when the disk hunt is complete. Return to the Monastery and speak with Ignatius.", "Completion. Ignatius completes the quest and gives the Amulet of the Holy Flame.", "Related quests: The gate into the volcano"),
            reward = "50 XP + Amulet of the Holy Flame",
            warnings = "",
            searchTags = listOf("Assisting the mages", "Inquisitor Mendoza / Ignatius", "Chapter 2 / World", "MAGE ONLY", "The gate into the volcano", "E. MAGE / WARRIOR CHAPTER 2 FOLLOW-UPS"),
        ),
    )

    val notes: List<RisenGuideNote> = listOf(
        RisenGuideNote(2, 23, "What this Part covers", listOf("This Part continues the canonical Chapter 2 World quest list from Q23 through Q33. It covers Patty's disappearance, the west-coast treasure hunt, Romanov's deal, Steelbeard's treasure and nautical map, then the final return to Mendoza with all five Crystal Disks. Bandit-only and Mage/Warrior Chapter 2 follow-ups are included afterward.")),
        RisenGuideNote(2, 23, "A. PATTY & THE WEST COAST", listOf()),
        RisenGuideNote(2, 29, "B. ROMANOV & STEELBEARD'S TREASURE", listOf()),
        RisenGuideNote(2, 33, "C. FINAL CRYSTAL-DISK HANDOFF", listOf()),
        RisenGuideNote(2, 34, "D. BANDIT-ONLY CHAPTER 2 QUESTS", listOf()),
        RisenGuideNote(2, 36, "E. MAGE / WARRIOR CHAPTER 2 FOLLOW-UPS", listOf("The canonical Chapter 2 quest catalogue lists the following Volcano Keep faction quests. Some are available immediately, while later Runic Seals depend on Wisdom thresholds and may naturally be completed later.")),
        RisenGuideNote(2, 43, "CHAPTER 2 COMPLETION CHECKLIST", listOf("Patty's west-coast escort and Steelbeard clue quest are complete.", "All five Nameless Graves were opened and their letters recovered.", "Eronga led you to Romanov.", "Romanov's deal was resolved without abandoning Patty's storyline.", "Dillinger's chest was looted for the Golden Crystal Disk and Steelbeard's Nautical Map.", "Patty was rescued and received the map.", "All five Crystal Disks are accounted for.", "Bandit players checked Crystal disks for the Don and Esteban's return to Harbour Town.", "Mage/Warrior players checked their Chapter 2 crystal-magic and Runic Seal quests.", "A permanent save exists before telling Mendoza you are ready.", "The Gate into the Volcano has been opened only after Chapter 2 cleanup is complete.")),
    )
}
