package com.sliverzfx.gothicquest

internal object Risen2GuidePart2Data {
    val quests: List<Quest> = listOf(
        Quest(
            id = "R2-C1-021",
            chapter = 1,
            playOrder = 21,
            title = "Find Steelbeard",
            category = "MAIN STORY",
            giver = "Steelbeard",
            location = "Tacarigua / Pirates' Den",
            prerequisites = "",
            summary = "Enter the Pirates' Den, approach Steelbeard's ship and speak with him.",
            walkthroughSteps = listOf("Walkthrough. Once the Den is accessible, finish any Patty-dependent Puerto Sacarico business first. Then approach the ship. Patty leaves the group as the Steelbeard scene starts. Board or approach the captain and exhaust his dialogue.", "Completion. Steelbeard gives you the chance to prove yourself and starts Become a Pirate.", "Counts for Steelbeard?: Unlocks the test", "Related: Become a Pirate / The Rum's Got to Come"),
            reward = "200 Glory",
            warnings = "⚠ Important: Approaching the ship changes Patty's party state and can cancel Kitchen Help if you left it unresolved.",
            searchTags = listOf("Find Steelbeard", "A. MEET STEELBEARD", "Steelbeard", ""),
        ),
        Quest(
            id = "R2-C1-022",
            chapter = 1,
            playOrder = 22,
            title = "Become a Pirate",
            category = "MAIN STORY — CHAPTER FINALE",
            giver = "Steelbeard",
            location = "Tacarigua / Pirates' Den",
            prerequisites = "",
            summary = "Earn at least five qualifying pirate deeds, report them to Steelbeard where required, then take the oath.",
            walkthroughSteps = listOf("Walkthrough. The safest route is to complete far more than five. Qualifying deeds include the crab hunt, Hank confrontation, Fight for the Hat, freeing Largo, O'Brian's treasure, Pete's treasure, The Traitor and the Beast, Old Grave Plundered and The Rum's Got to Come. Some deeds are reported automatically; others require telling Steelbeard.", "Completion. When Steelbeard accepts that you have done enough, tell him you are ready and take the pirate oath.", "Counts for Steelbeard?: Requires 5 qualifying deeds", "Related: The Pirate Garb"),
            reward = "200 Glory + Pirate title",
            warnings = "⚠ Important: Do NOT take the oath until the entire Part II cleanup checklist is finished. Several quests cannot be obtained or are cancelled afterward.",
            searchTags = listOf("Become a Pirate", "A. MEET STEELBEARD", "Steelbeard", ""),
        ),
        Quest(
            id = "R2-C1-023",
            chapter = 1,
            playOrder = 23,
            title = "Crab Slapping with Blake",
            category = "SAFE — COMBAT",
            giver = "Blake",
            location = "Tacarigua / Pirates' Den",
            prerequisites = "",
            summary = "Kill the giant crabs on Blake's beach; killing more than Blake gives the strongest pirate impression.",
            walkthroughSteps = listOf("Walkthrough. Find Blake at the far northeastern beach beyond the camp. Ask about hunting crabs and follow him. There are five Giant Crabs. Fight aggressively so Blake does not take all the kills; ranged attacks and Kick are useful against their frontal defence.", "Completion. The quest completes once the crab group is dead. Steelbeard hears about the deed automatically.", "Counts for Steelbeard?: YES"),
            reward = "100 Glory + crab kill Glory",
            warnings = "⚠ Important: The deed can still count even if Blake gets some kills; the objective is to clear the crabs.",
            searchTags = listOf("Crab Slapping with Blake", "B. BLAKE & THE CRABS", "Blake", ""),
        ),
        Quest(
            id = "R2-C1-024",
            chapter = 1,
            playOrder = 24,
            title = "The Rum's Got to Come",
            category = "MAIN PIRATE TEST",
            giver = "Steelbeard / Booze",
            location = "Tacarigua / Pirates' Den",
            prerequisites = "",
            summary = "Restore both the sugar and water supply, then get Booze to resume Steelbeard's rum delivery.",
            walkthroughSteps = listOf("Walkthrough. Ask Steelbeard about what would impress him, or talk to Booze after solving the sugar and water problems. Complete The Sugar Shipment and The Water Carriers. Return to Booze and ask about Steelbeard's rum. Booze walks out to negotiate with the captain.", "Completion. After Booze and Steelbeard talk, speak with Steelbeard and tell him the rum problem is solved.", "Counts for Steelbeard?: YES", "Related: The Sugar Shipment / The Water Carriers"),
            reward = "100 Glory",
            warnings = "",
            searchTags = listOf("The Rum's Got to Come", "C. BOOZE'S RUM PROBLEM", "Steelbeard / Booze", ""),
        ),
        Quest(
            id = "R2-C1-025",
            chapter = 1,
            playOrder = 25,
            title = "The Sugar Shipment",
            category = "SUPPLY CHAIN",
            giver = "Booze / Jack",
            location = "Tacarigua / Pirates' Den",
            prerequisites = "",
            summary = "Recover all seven stolen sugar sacks from the termite cave, report to Booze and take the sugar upstairs to Alister.",
            walkthroughSteps = listOf("Walkthrough. Ask Booze about sugar, or learn about the termites from Jack. Travel to the cave near Jack's lighthouse and clear the termites. Collect all seven sugar sacks inside the cave. Return to Booze and then deliver the shipment to Alister upstairs.", "Completion. The shipment is restored; speak with Booze for his extra rum/gold reward.", "Counts for Steelbeard?: NO direct point; enables Rum", "Related: 7 Sacks of Sugar / The Termite Plague"),
            reward = "100 Glory + Booze reward",
            warnings = "",
            searchTags = listOf("The Sugar Shipment", "C. BOOZE'S RUM PROBLEM", "Booze / Jack", ""),
        ),
        Quest(
            id = "R2-C1-026",
            chapter = 1,
            playOrder = 26,
            title = "7 Sacks of Sugar",
            category = "COLLECTION",
            giver = "Trigger quest",
            location = "Tacarigua / Pirates' Den",
            prerequisites = "",
            summary = "Pick up all seven sacks of sugar in the termite cave.",
            walkthroughSteps = listOf("Walkthrough. Search the termite cave carefully after clearing the insects. All seven quest sacks are inside the cave area.", "Completion. The seventh sack completes the quest.", "Counts for Steelbeard?: NO", "Related: The Sugar Shipment"),
            reward = "50 Glory",
            warnings = "",
            searchTags = listOf("7 Sacks of Sugar", "C. BOOZE'S RUM PROBLEM", "Automatic", ""),
        ),
        Quest(
            id = "R2-C1-027",
            chapter = 1,
            playOrder = 27,
            title = "The Termite Plague",
            category = "SAFE — COMBAT",
            giver = "Jack",
            location = "Tacarigua / Pirates' Den",
            prerequisites = "",
            summary = "Kill the termites infesting the area near Jack's lighthouse and sugar cave.",
            walkthroughSteps = listOf("Walkthrough. Speak with Jack and investigate the termite infestation. Clear the insects around the cave and lighthouse route.", "Completion. Report back after the required termites are dead.", "Counts for Steelbeard?: NO", "Related: The Sugar Shipment"),
            reward = "Glory + side-quest reward",
            warnings = "",
            searchTags = listOf("The Termite Plague", "C. BOOZE'S RUM PROBLEM", "Jack", ""),
        ),
        Quest(
            id = "R2-C1-028",
            chapter = 1,
            playOrder = 28,
            title = "The Water Carriers",
            category = "SUPPLY CHAIN",
            giver = "Booze / Colby",
            location = "Tacarigua / Pirates' Den",
            prerequisites = "",
            summary = "Resolve the argument among Colby, Doggs and Foster so the water deliveries resume.",
            walkthroughSteps = listOf("Walkthrough. Find the three water carriers downhill from the Pirates' Den. Speak with Colby and the two arguing men. You may send Doggs or Foster to the gate immediately, or choose Colby. Choosing Colby triggers both Fight Foster and Fight Doggs and gives the most combat Glory.", "Completion. After the chosen solution, speak with Colby, then report to Booze. If Colby was sent to the gate, Fence also has a small reward.", "Counts for Steelbeard?: NO", "Related: Fight Foster / Fight Doggs"),
            reward = "100 Glory + optional 2x fight rewards",
            warnings = "⚠ Important: For maximum Glory, choose Colby and defeat both Doggs and Foster.",
            searchTags = listOf("The Water Carriers", "C. BOOZE'S RUM PROBLEM", "Booze / Colby", ""),
        ),
        Quest(
            id = "R2-C1-029",
            chapter = 1,
            playOrder = 29,
            title = "Fight Foster",
            category = "OPTIONAL SUBQUEST",
            giver = "Foster",
            location = "Tacarigua / Pirates' Den",
            prerequisites = "",
            summary = "Defeat Foster after choosing Colby for gate duty.",
            walkthroughSteps = listOf("Walkthrough. During The Water Carriers, choose Colby. Foster objects and challenges you. Beat him in the duel.", "Completion. The quest completes when Foster is defeated.", "Counts for Steelbeard?: NO", "Related: The Water Carriers"),
            reward = "50 Glory + duel Glory",
            warnings = "",
            searchTags = listOf("Fight Foster", "C. BOOZE'S RUM PROBLEM", "Foster", ""),
        ),
        Quest(
            id = "R2-C1-030",
            chapter = 1,
            playOrder = 30,
            title = "Fight Doggs",
            category = "OPTIONAL SUBQUEST",
            giver = "Doggs",
            location = "Tacarigua / Pirates' Den",
            prerequisites = "",
            summary = "Defeat Doggs after choosing Colby for gate duty.",
            walkthroughSteps = listOf("Walkthrough. During The Water Carriers, choose Colby. Doggs challenges you. Beat him using melee, pistol or dirty tricks.", "Completion. The quest completes when Doggs is defeated.", "Counts for Steelbeard?: NO", "Related: The Water Carriers"),
            reward = "50 Glory + duel Glory",
            warnings = "",
            searchTags = listOf("Fight Doggs", "C. BOOZE'S RUM PROBLEM", "Doggs", ""),
        ),
        Quest(
            id = "R2-C1-031",
            chapter = 1,
            playOrder = 31,
            title = "Settling the Score with Hank",
            category = "PIRATE TEST",
            giver = "Holly / Hank",
            location = "Tacarigua / Pirates' Den",
            prerequisites = "",
            summary = "Talk to Holly, refuse Hank's demand for 100 gold and beat him in a fight.",
            walkthroughSteps = listOf("Walkthrough. Speak with Holly in Booze's tavern. Afterward walk near Hank. He demands payment. Refuse to pay until the confrontation begins.", "Completion. Defeat Hank. Steelbeard learns of the confrontation automatically.", "Counts for Steelbeard?: YES", "Related: Become a Pirate"),
            reward = "100 Glory + fight Glory",
            warnings = "⚠ Important: Paying Hank prevents the quest from being obtained.",
            searchTags = listOf("Settling the Score with Hank", "D. TAVERN TROUBLE & THE TRAITOR", "Holly / Hank", ""),
        ),
        Quest(
            id = "R2-C1-032",
            chapter = 1,
            playOrder = 32,
            title = "Night-time Pursuit",
            category = "INVESTIGATION",
            giver = "Booze",
            location = "Tacarigua / Pirates' Den",
            prerequisites = "",
            summary = "Follow Meeks at night without being spotted.",
            walkthroughSteps = listOf("Walkthrough. Talk to Meeks in the tavern. When you leave, Booze calls you over and asks you to investigate him. Sleep until night, tell Booze you are ready, then follow Meeks at a distance. If he notices you, he returns to the tavern and the attempt must be repeated.", "Completion. On the beach you witness Meeks meeting a Sunken One; the next quest starts immediately.", "Counts for Steelbeard?: Leads to YES deed", "Related: The Traitor and the Beast"),
            reward = "Story progression",
            warnings = "⚠ Important: This quest cannot coexist cleanly with some Hank trigger timing; finish the pursuit, then revisit Holly/Hank if needed.",
            searchTags = listOf("Night-time Pursuit", "D. TAVERN TROUBLE & THE TRAITOR", "Booze", ""),
        ),
        Quest(
            id = "R2-C1-033",
            chapter = 1,
            playOrder = 33,
            title = "The Traitor and the Beast",
            category = "PIRATE TEST — COMBAT",
            giver = "Trigger quest",
            location = "Tacarigua / Pirates' Den",
            prerequisites = "",
            summary = "Kill Meeks and the Sunken One after discovering their secret meeting.",
            walkthroughSteps = listOf("Walkthrough. Once the Sunken One spots you during Night-time Pursuit, fight both enemies. The Sunken One is much tougher than Meeks; use pistol shots, space and retreat if your melee skill is low.", "Completion. Kill both. Steelbeard recognizes the deed; report to Booze for additional gold.", "Counts for Steelbeard?: YES", "Related: Night-time Pursuit"),
            reward = "100 Glory + enemy Glory + Booze reward",
            warnings = "",
            searchTags = listOf("The Traitor and the Beast", "D. TAVERN TROUBLE & THE TRAITOR", "Automatic", ""),
        ),
        Quest(
            id = "R2-C1-034",
            chapter = 1,
            playOrder = 34,
            title = "Fight for the Hat",
            category = "PIRATE TEST — MISSABLE",
            giver = "Morris",
            location = "Tacarigua / Pirates' Den",
            prerequisites = "",
            summary = "Take the hat from the upper tavern walkway, equip it in front of Morris and beat him in a duel.",
            walkthroughSteps = listOf("Walkthrough. Go upstairs in Booze's tavern and find the Hat on the upper walkway. Equip it, then walk near Morris downstairs. He challenges you over ownership of the hat.", "Completion. Defeat Morris and keep the right to wear it.", "Counts for Steelbeard?: YES"),
            reward = "100 Glory + duel Glory",
            warnings = "⚠ Important: This quest cannot be obtained after taking Steelbeard's oath. Do it before Become a Pirate is finalized.",
            searchTags = listOf("Fight for the Hat", "E. FIGHT FOR THE HAT", "Morris", ""),
        ),
        Quest(
            id = "R2-C1-035",
            chapter = 1,
            playOrder = 35,
            title = "Follow Largo",
            category = "OPTIONAL ESCORT",
            giver = "Largo",
            location = "Tacarigua / Pirates' Den",
            prerequisites = "",
            summary = "Escort Largo from Puerto Sacarico to the Pirates' Den.",
            walkthroughSteps = listOf("Walkthrough. After Largo leaves prison he waits nearby. Offer to accompany him. His jungle route crosses animals, termites and possibly the escaped slaves. Largo is unarmed but cannot permanently die; clear enemies for him and watch for the spike trap along the route.", "Completion. The escort ends in front of Booze's tavern.", "Counts for Steelbeard?: NO"),
            reward = "10 Glory",
            warnings = "⚠ Important: Save before the jungle spike trap; the escort route can force you across it.",
            searchTags = listOf("Follow Largo", "F. LARGO'S ESCAPE", "Largo", ""),
        ),
        Quest(
            id = "R2-C1-036",
            chapter = 1,
            playOrder = 36,
            title = "Largo's Clothes",
            category = "SIDE QUEST",
            giver = "Largo",
            location = "Tacarigua / Pirates' Den",
            prerequisites = "",
            summary = "Recover Largo's personal clothing/items and return them to him.",
            walkthroughSteps = listOf("Walkthrough. Continue collecting Largo's Pirate Bandana, worn boots, leather shirt and Black Pearl. Some pieces are useful as proof for Stone, so resolve Freeing Largo before casually giving or gambling away items.", "Completion. Return the required belongings to Largo.", "Counts for Steelbeard?: NO"),
            reward = "Glory / item reward",
            warnings = "⚠ Important: If you lose the Black Pearl as an O'Brian drinking-contest stake, Largo's Clothes can become impossible to finish.",
            searchTags = listOf("Largo's Clothes", "F. LARGO'S ESCAPE", "Largo", ""),
        ),
        Quest(
            id = "R2-C1-037",
            chapter = 1,
            playOrder = 37,
            title = "O'Brian's Treasure Map",
            category = "PIRATE TEST SETUP — MISSABLE",
            giver = "O'Brian",
            location = "Tacarigua / Pirates' Den",
            prerequisites = "",
            summary = "Win O'Brian's treasure map in his drinking contest.",
            walkthroughSteps = listOf("Walkthrough. Talk with O'Brian in Booze's tavern and ask about joining Steelbeard. Stake either 500 Gold, a Monkey or Largo's Black Pearl. You also need a Painkiller to start the drinking contest. Complete the drinking minigame successfully.", "Completion. Winning gives the treasure map and starts O'Brian's Treasure.", "Counts for Steelbeard?: Unlocks YES deed"),
            reward = "50 Glory",
            warnings = "⚠ Important: You get one real attempt and your stake can be lost. This quest cannot be obtained after taking Steelbeard's oath.",
            searchTags = listOf("O'Brian's Treasure Map", "G. O'BRIAN & PETE — TREASURE DEEDS", "O'Brian", ""),
        ),
        Quest(
            id = "R2-C1-038",
            chapter = 1,
            playOrder = 38,
            title = "O'Brian's Treasure",
            category = "PIRATE TEST",
            giver = "O'Brian's map",
            location = "Tacarigua / Pirates' Den",
            prerequisites = "",
            summary = "Use the map, reach the marked north-beach treasure site and dig up the chest with a shovel.",
            walkthroughSteps = listOf("Walkthrough. Activate O'Brian's map and travel to the marked beach behind/near the waterfall. Bring a Shovel; Pete's site provides one, or buy one if necessary.", "Completion. Dig up and loot O'Brian's chest. Tell Steelbeard about the deed if his dialogue requires it.", "Counts for Steelbeard?: YES"),
            reward = "100 Glory + treasure",
            warnings = "",
            searchTags = listOf("O'Brian's Treasure", "G. O'BRIAN & PETE — TREASURE DEEDS", "O'Brian's map", ""),
        ),
        Quest(
            id = "R2-C1-039",
            chapter = 1,
            playOrder = 39,
            title = "Pete's Treasure Map",
            category = "PIRATE TEST SETUP",
            giver = "Holly / Pete",
            location = "Tacarigua / Pirates' Den",
            prerequisites = "",
            summary = "Find Pete's corpse near the temple ruin in the gorge and take his treasure map.",
            walkthroughSteps = listOf("Walkthrough. Buy Pete's information from Holly for 100 Gold, then travel to the central gorge near the old tomb/ruin. Search Pete's corpse for the map and other loot.", "Completion. Taking the map starts Pete's Treasure.", "Counts for Steelbeard?: Unlocks YES deed"),
            reward = "50 Glory + loot",
            warnings = "",
            searchTags = listOf("Pete's Treasure Map", "G. O'BRIAN & PETE — TREASURE DEEDS", "Holly / Pete", ""),
        ),
        Quest(
            id = "R2-C1-040",
            chapter = 1,
            playOrder = 40,
            title = "Pete's Treasure",
            category = "PIRATE TEST",
            giver = "Pete's map",
            location = "Tacarigua / Pirates' Den",
            prerequisites = "",
            summary = "Dig up Pete's nearby Rotten Chest.",
            walkthroughSteps = listOf("Walkthrough. After taking Pete's map, look only a short distance north of his corpse. A Shovel is stuck in the ground nearby if you do not already own one.", "Completion. Dig up and loot the Rotten Chest. Report the achievement to Steelbeard.", "Counts for Steelbeard?: YES"),
            reward = "100 Glory + treasure",
            warnings = "",
            searchTags = listOf("Pete's Treasure", "G. O'BRIAN & PETE — TREASURE DEEDS", "Pete's map", ""),
        ),
        Quest(
            id = "R2-C1-041",
            chapter = 1,
            playOrder = 41,
            title = "Old Grave Plundered",
            category = "PIRATE TEST — EXPLORATION",
            giver = "Trigger quest",
            location = "Tacarigua / Pirates' Den",
            prerequisites = "",
            summary = "Take an Idol from an altar in one of Tacarigua's old tombs/ruins.",
            walkthroughSteps = listOf("Walkthrough. Explore an ancient grave or ruin containing an altar and remove an Idol. The surrounding enemies can be significantly stronger than normal early-game wildlife.", "Completion. Taking the Idol completes the journal entry. Tell Steelbeard about the plunder.", "Counts for Steelbeard?: YES"),
            reward = "100 Glory + Idol",
            warnings = "⚠ Important: This can be done later, but it is a useful Steelbeard point if you want to over-complete Chapter 1.",
            searchTags = listOf("Old Grave Plundered", "G. O'BRIAN & PETE — TREASURE DEEDS", "Automatic", ""),
        ),
        Quest(
            id = "R2-C1-042",
            chapter = 1,
            playOrder = 42,
            title = "A Difficult Chest",
            category = "SIDE QUEST — PRE-DEPARTURE",
            giver = "MacLaine",
            location = "Tacarigua / Pirates' Den",
            prerequisites = "",
            summary = "Get a Lock Pick, learn Lockpicking and open Steelbeard's Sturdy Chest below deck.",
            walkthroughSteps = listOf("Walkthrough. Speak with MacLaine near the ship's wheel. Stone has the Lock Pick; the Largo route can get it free. You also need the Lockpicking skill and enough Thievery to attempt the difficulty-25 chest. Open the chest below deck.", "Completion. Loot the chest and report to MacLaine.", "Counts for Steelbeard?: NO (known bug)"),
            reward = "100 Glory + 300 Gold",
            warnings = "⚠ Important: Despite MacLaine's promise, this quest does not reliably count as a Steelbeard deed. It is cancelled if still active when you cast off from Tacarigua.",
            searchTags = listOf("A Difficult Chest", "H. STEELBEARD'S SHIP & LOCKPICK TEST", "MacLaine", ""),
        ),
        Quest(
            id = "R2-C1-043",
            chapter = 1,
            playOrder = 43,
            title = "The Sugar Trade",
            category = "SIDE QUEST",
            giver = "Booze",
            location = "Tacarigua / Pirates' Den",
            prerequisites = "",
            summary = "Carry Booze's sugar-trade business to the appropriate contact and return the response/result.",
            walkthroughSteps = listOf("Walkthrough. Ask Booze about trade once Pirate Post and the Den conversations are open. Follow the named delivery/contact instructions through the camp.", "Completion. Return to Booze when the trade step is finished.", "Counts for Steelbeard?: NO"),
            reward = "Glory / gold",
            warnings = "",
            searchTags = listOf("The Sugar Trade", "I. EXTRA TACARIGUA QUESTS AROUND THE DEN", "Booze", ""),
        ),
        Quest(
            id = "R2-C1-044",
            chapter = 1,
            playOrder = 44,
            title = "Distract Alister",
            category = "SIDE QUEST",
            giver = "Pirate contact",
            location = "Tacarigua / Pirates' Den",
            prerequisites = "",
            summary = "Distract Alister long enough for the related pirate plan to proceed.",
            walkthroughSteps = listOf("Walkthrough. Pick up the plan from the pirate near the lower dock/fire area, then approach Alister and use the available dialogue/action to occupy him.", "Completion. The distraction succeeds when the related pirate finishes his task.", "Counts for Steelbeard?: NO"),
            reward = "Glory",
            warnings = "",
            searchTags = listOf("Distract Alister", "I. EXTRA TACARIGUA QUESTS AROUND THE DEN", "Pirate contact", ""),
        ),
        Quest(
            id = "R2-C1-045",
            chapter = 1,
            playOrder = 45,
            title = "10 Bloody Roots",
            category = "SIDE QUEST — COLLECTION",
            giver = "Island NPC / collection",
            location = "Tacarigua / Pirates' Den",
            prerequisites = "",
            summary = "Collect ten Bloody Roots and hand them to the relevant quest giver.",
            walkthroughSteps = listOf("Walkthrough. Pick Bloody Roots during your normal Tacarigua exploration rather than farming them at the end. Keep at least ten instead of selling all alchemy plants.", "Completion. Hand over ten roots.", "Counts for Steelbeard?: NO"),
            reward = "Glory / gold",
            warnings = "",
            searchTags = listOf("10 Bloody Roots", "I. EXTRA TACARIGUA QUESTS AROUND THE DEN", "Island NPC / collection", ""),
        ),
        Quest(
            id = "R2-C1-046",
            chapter = 1,
            playOrder = 46,
            title = "The Pirate Garb",
            category = "POST-OATH MAIN QUEST",
            giver = "Steelbeard",
            location = "Tacarigua / Pirates' Den",
            prerequisites = "",
            summary = "Take Steelbeard's oath and equip your pirate clothing.",
            walkthroughSteps = listOf("Walkthrough. Once Become a Pirate is accepted as complete, tell Steelbeard you are ready. The crew gathers and you swear the oath. Your pirate status now allows you to wear the Pirate Garb properly.", "Completion. The quest completes as the pirate outfit/status becomes available.", "Counts for Steelbeard?: N/A"),
            reward = "Pirate status / clothing access",
            warnings = "⚠ Important: Taking the oath can close unfinished Chapter 1 opportunities. Use the checklist below first.",
            searchTags = listOf("The Pirate Garb", "J. THE OATH — CHAPTER 1 END", "Automatic / Steelbeard", ""),
        ),
    )

    val notes: List<RisenGuideNote> = listOf(
        RisenGuideNote(1, 21, "How Steelbeard's test works", listOf("After Find Steelbeard, the captain starts Become a Pirate. He wants proof that you can live like one of his crew. You need at least five qualifying pirate deeds before he will let you take the oath. Some quests around the camp are useful but do not count toward Steelbeard's five; this guide marks them clearly.", "Recommended completionist route: Do every available Pirates' Den quest before taking the oath. The oath closes or cancels several Chapter 1 opportunities, including quests that can no longer be obtained afterward.")),
        RisenGuideNote(1, 21, "A. MEET STEELBEARD", listOf()),
        RisenGuideNote(1, 23, "B. BLAKE & THE CRABS", listOf()),
        RisenGuideNote(1, 24, "C. BOOZE'S RUM PROBLEM", listOf()),
        RisenGuideNote(1, 31, "D. TAVERN TROUBLE & THE TRAITOR", listOf()),
        RisenGuideNote(1, 34, "E. FIGHT FOR THE HAT", listOf()),
        RisenGuideNote(1, 35, "F. LARGO'S ESCAPE", listOf()),
        RisenGuideNote(1, 35, "Freeing Largo — continued quest guidance", listOf("Quick solution: Get Stone's Lock Pick, return to Puerto Sacarico and free Largo.", "Walkthrough. Use Largo's Pirate Bandana or Black Pearl as proof when talking to Stone. Mention Stone's debt to Largo to get the Lock Pick for free. Return to the prison tower. Give Largo the Lock Pick and follow the confrontation with Carter as required.", "Completion. Largo escapes prison; Steelbeard counts the deed.", "⚠ Important: A failed conversation with Stone cannot always be repeated. Save before negotiating. Do not wager Largo's Black Pearl to O'Brian if you still need it for Largo's clothing chain.", "Quest giver: Largo", "Status: PIRATE TEST", "Counts for Steelbeard?: YES", "Reward: 100 Glory", "Related: The Clothes of a Pirate / Follow Largo")),
        RisenGuideNote(1, 37, "G. O'BRIAN & PETE — TREASURE DEEDS", listOf()),
        RisenGuideNote(1, 42, "H. STEELBEARD'S SHIP & LOCKPICK TEST", listOf()),
        RisenGuideNote(1, 43, "I. EXTRA TACARIGUA QUESTS AROUND THE DEN", listOf()),
        RisenGuideNote(1, 46, "J. THE OATH — CHAPTER 1 END", listOf()),
        RisenGuideNote(1, 47, "RECOMMENDED FIVE STEELBEARD DEEDS", listOf("You only need five, but for a first completionist run I recommend doing nearly all of them. A straightforward five with good XP and minimal ambiguity is:", "1. Crab Slapping with Blake", "2. Settling the Score with Hank", "3. Fight for the Hat", "4. Freeing Largo", "5. The Traitor and the Beast", "Then also complete The Rum's Got to Come, Pete's Treasure, O'Brian's Treasure and Old Grave Plundered before the oath.")),
        RisenGuideNote(1, 47, "CHAPTER 1 — FINAL COMPLETIONIST CHECKLIST", listOf("Find Steelbeard is complete.", "The Sugar Shipment and 7 Sacks of Sugar are complete.", "The Water Carriers is complete; maximum-Glory route used Colby plus both fights.", "The Rum's Got to Come has been reported to Steelbeard.", "Night-time Pursuit and The Traitor and the Beast are complete.", "Settling the Score with Hank is complete.", "Fight for the Hat was completed BEFORE the oath.", "Largo is free; Follow Largo and Largo's Clothes were completed if desired.", "O'Brian's Treasure Map was won BEFORE the oath; the treasure was dug up.", "Pete's Treasure Map and Pete's Treasure are complete.", "Old Grave Plundered is complete if you want the extra pirate deed.", "A Difficult Chest is finished before casting off.", "Any remaining Tacarigua side quests you care about are finished.", "Steelbeard recognizes at least five qualifying pirate deeds.", "A permanent save exists before taking the oath.", "Become a Pirate and The Pirate Garb are complete.", "You are ready to tell Steelbeard to cast off for the Sword Coast.")),
    )
}
