package com.sliverzfx.gothicquest

internal object Risen3Chapter3Data {
    val quests: List<Quest> = listOf(
        Quest(
            id = "R3-C3-001",
            chapter = 3,
            playOrder = 1,
            title = "Recruit Eldric",
            aliases = listOf(),
            category = "MAIN STORY — REQUIRED",
            giver = "Eldric",
            location = "Calador",
            prerequisites = "",
            summary = "Activate four western Calador teleporters, travel with Eldric into eastern Calador, kill the Shadow Lord of Doubt, destroy the nearby Crystal Portal, then report back to Eldric.",
            walkthroughSteps = listOf("Chapter 2 — Calador — I. DEFER THESE UNTIL AFTER FACTION / LATER CHAPTERS", "Chapter 3 ritual preparation; eastern Calador. It is a real journal quest but is intentionally excluded from the pre-faction walkthrough.", "Chapter 3 —  — B. CALADOR — RECRUIT ELDRIC", "Quest giver: Eldric", "Area: Calador", "Status: MAIN STORY — REQUIRED", "Reward: 1,000 Glory, plus 400/200/100/600/500 Glory from major steps and fights", "Walkthrough. Eldric agrees to help only if you help clear eastern Calador. First gather at least four Teleporting Stones. Activate the four western teleporters: near the western castle ruins, huntsmen's chalet, tavern and Demon Hunter Citadel. Return to Eldric; he uses the magical network to teleport the Demon Hunters across the lava. Fight the Minions at the eastern teleporter, then regroup with Eldric at the northern camp. Follow the Hunters through Hellhounds, Skeletons and Minions to the Shadow Lord of Doubt. Kill it with their help, then destroy the nearby Crystal Portal.", "Completion. After the portal is destroyed, wait for Eldric to return to the Citadel and speak with him again. He agrees to participate in the ritual.", "Recruit Eldric — efficient route", "Fishing Village teleporter stone / nearby sources.", "Activate the teleporter near western castle ruins.", "Activate the teleporter near the huntsmen's chalet.", "Activate the teleporter near the tavern.", "Activate the teleporter near the Demon Hunter Citadel.", "Report to Eldric and teleport east.", "Clear the first Minion attack.", "Meet Eldric at the eastern camp.", "Kill the Shadow Lord of Doubt.", "Destroy the eastern Crystal Portal.", "Speak with Eldric back at the Citadel.", "Related: The Realm of the Shadows / A Powerful Spell"),
            reward = "1,000 Glory, plus 400/200/100/600/500 Glory from major steps and fights",
            warnings = "⚠ Important: Bring four Teleporting Stones before starting the teleporter circuit. Killing the Lindworm yourself on the eastern route gives substantial extra Glory.",
            searchTags = listOf("Calador", "", "I. DEFER THESE UNTIL AFTER FACTION / LATER CHAPTERS", "B. CALADOR — RECRUIT ELDRIC"),
        ),
        Quest(
            id = "R3-C3-002",
            chapter = 3,
            playOrder = 2,
            title = "A Powerful Spell",
            aliases = listOf(),
            category = "MAIN STORY — REQUIRED",
            giver = "Eldric",
            location = "Calador",
            prerequisites = "",
            summary = "Enter the ancient city ruins in eastern Calador and take the Nekroimortar scroll from the altar in the western building.",
            walkthroughSteps = listOf("Walkthrough. This quest becomes practical after Recruit Eldric unlocks eastern Calador. Approach the ancient city ruins from the southeast for the easiest route. Around ten Skeletons plus several Minions occupy the ruins. Fight methodically and avoid being surrounded. Enter the western building and descend to its lower level.", "Completion. Take Nekroimortar from the altar, then report the recovered spell to Eldric."),
            reward = "400 Glory + 100 Glory for taking the scroll",
            warnings = "⚠ Important: The northwest approach is harder and may require fighting a Soul Eater plus using Parrot Flight. The southeast approach is safer.",
            searchTags = listOf("", "C. CALADOR — A POWERFUL SPELL"),
        ),
        Quest(
            id = "R3-C3-003",
            chapter = 3,
            playOrder = 3,
            title = "Recruit Zacharias",
            aliases = listOf(),
            category = "MAIN STORY — REQUIRED",
            giver = "Eldric / Zacharias",
            location = "Taranis",
            prerequisites = "",
            summary = "Finish The Reactor, follow Zacharias to the portal cave, enter the Underworld, return, kill the Shadow Lord of Hunting, destroy the portal and ask Zacharias to join the ritual.",
            walkthroughSteps = listOf("Chapter 2 — Taranis — I. LATER / POST-FACTION TARANIS QUESTS — DEFER", "Chapter 3 Spirit Ritual preparation. It is a real quest but is intentionally deferred from the Chapter 2 pre-faction route.", "Chapter 3 —  — D. TARANIS — RECRUIT ZACHARIAS", "Quest giver: Eldric / Zacharias", "Area: Taranis", "Status: MAIN STORY — REQUIRED", "Reward: 1,000 Glory + 600 for entering the portal + 200 after Tao + 600 for Shadow Lord + 500 for portal destruction", "Walkthrough. Zacharias becomes available after The Reactor is fully activated. Speak with him about the magical device he is studying and follow him northeast to the cave. Inside, fight Rock Spiders and an Iron Golem. At the inactive Crystal Portal, Zacharias activates it. Interact with the portal and choose to ENTER it rather than destroy it. In the Underworld, collect Soul Dust and speak with Tao. You automatically return to the living world after several hours have passed. A Shadow Lord of Hunting appears with seven Minions of the Chasing Pack. Thin the minions first, then kill the Shadow Lord. Afterward, destroy the Crystal Portal.", "Completion. Speak with Zacharias after the fight and ask him to take part in the ritual.", "Related: The Reactor / The Realm of the Shadows"),
            reward = "1,000 Glory + 600 for entering the portal + 200 after Tao + 600 for Shadow Lord + 500 for portal destruction",
            warnings = "⚠ Important: Do not destroy the portal before entering it. The Underworld visit is part of Zacharias' required story sequence.",
            searchTags = listOf("Taranis", "", "I. LATER / POST-FACTION TARANIS QUESTS — DEFER", "D. TARANIS — RECRUIT ZACHARIAS"),
        ),
        Quest(
            id = "R3-C3-004",
            chapter = 3,
            playOrder = 4,
            title = "Open the Large Gate",
            aliases = listOf(),
            category = "MAIN STORY ACCESS — REQUIRED FOR CHANI",
            giver = "Baraka",
            location = "Kila",
            prerequisites = "",
            summary = "Return to Baraka after obtaining Ancient Knowledge and get access to the Forbidden Valley.",
            walkthroughSteps = listOf("Chapter 2 — Kila — F. LATER KILA QUESTS — DO NOT DO YET", "Baraka only opens the gate after Chapter 3 progression and completion of The Ancient Knowledge. Mud also becomes involved. It is a real canonical quest but is deliberately deferred from the Chapter 2 pre-faction route.", "Chapter 3 —  — E. KILA — OPEN THE LARGE GATE", "Quest giver: Baraka", "Area: Kila", "Status: MAIN STORY ACCESS — REQUIRED FOR CHANI", "Reward: 400 Glory", "Walkthrough. Baraka guards the huge gate leading into the Forbidden Valley. Earlier he refused access because you lacked Ancient Knowledge. After The Ancient Knowledge and Chapter 3 progression, return and speak with him again. Mud may appear southeast of the gate and attach himself to you as part of The Pain in the Neck.", "Completion. Gain access through the Large Gate and enter the Forbidden Valley."),
            reward = "400 Glory",
            warnings = "⚠ Important: Mud is optional comic baggage. You can take him toward the temple or get rid of him depending on your preferred route.",
            searchTags = listOf("Kila", "", "F. LATER KILA QUESTS — DO NOT DO YET", "E. KILA — OPEN THE LARGE GATE"),
        ),
        Quest(
            id = "R3-C3-005",
            chapter = 3,
            playOrder = 5,
            title = "Recruit Chani",
            aliases = listOf(),
            category = "MAIN STORY — REQUIRED",
            giver = "Eldric / Chani",
            location = "Kila",
            prerequisites = "",
            summary = "Find Chani in the Forbidden Valley, find Damaka, kill the five Soldiers of the Oracle, then ask Chani to join the ritual.",
            walkthroughSteps = listOf("Chapter 2 — Kila — F. LATER KILA QUESTS — DO NOT DO YET", "Chapter 3 Spirit Ritual preparation. Chani is beyond the Large Gate in the Forbidden Valley. It is a real canonical quest but is deliberately deferred from the Chapter 2 pre-faction route.", "Chapter 3 —  — F. KILA — RECRUIT CHANI", "Quest giver: Eldric / Chani", "Area: Kila", "Status: MAIN STORY — REQUIRED", "Reward: 1,000 Glory", "Walkthrough. After opening the Large Gate, travel to Chani's cottage in the Forbidden Valley. She refuses to help immediately and starts Lost in the Forbidden Valley plus Speak to the Oracle. For recruitment itself, complete Lost in the Forbidden Valley first: find the dead warrior Damaka and report back. Chani then gives The Oracle's Soldiers. Hunt down and kill all five giant spider 'Soldiers of the Oracle' across the high plains/valley.", "Completion. Return to Chani after all five are dead and ask her to participate. She agrees.", "Related: Lost in the Forbidden Valley / The Oracle's Soldiers / Speak to the Oracle"),
            reward = "1,000 Glory",
            warnings = "⚠ Important: The Right Place is best completed before leaving Kila because you are already in the Forbidden Valley.",
            searchTags = listOf("Kila", "", "F. LATER KILA QUESTS — DO NOT DO YET", "F. KILA — RECRUIT CHANI"),
        ),
        Quest(
            id = "R3-C3-006",
            chapter = 3,
            playOrder = 6,
            title = "Lost in the Forbidden Valley",
            aliases = listOf(),
            category = "MAIN STORY — CHANI SUBQUEST",
            giver = "Chani",
            location = "Kila",
            prerequisites = "",
            summary = "Find the missing warrior Damaka in the Forbidden Valley.",
            walkthroughSteps = listOf("Chapter 2 — Kila — F. LATER KILA QUESTS — DO NOT DO YET", "Chapter 3 Chani/Forbidden Valley content. It is a real canonical quest but is deliberately deferred from the Chapter 2 pre-faction route.", "Chapter 3 —  — F. KILA — RECRUIT CHANI", "Quest giver: Chani", "Area: Kila", "Status: MAIN STORY — CHANI SUBQUEST", "Reward: 200 Glory", "Walkthrough. Search the marked valley area beyond Chani's cottage. The region contains dangerous creatures including Swamp Golems. Reach the indicated corpse cluster and examine Damaka's body.", "Completion. Return to Chani and report Damaka's death.", "Related: The Oracle's Soldiers"),
            reward = "200 Glory",
            warnings = "⚠ Important: The Swamp Golems are optional; avoid fighting them near cliff edges.",
            searchTags = listOf("Kila", "", "F. LATER KILA QUESTS — DO NOT DO YET", "F. KILA — RECRUIT CHANI"),
        ),
        Quest(
            id = "R3-C3-007",
            chapter = 3,
            playOrder = 7,
            title = "The Oracle's Soldiers",
            aliases = listOf(),
            category = "MAIN STORY — CHANI SUBQUEST",
            giver = "Chani",
            location = "Kila",
            prerequisites = "",
            summary = "Kill all five giant spider Soldiers of the Oracle.",
            walkthroughSteps = listOf("Chapter 2 — Kila — F. LATER KILA QUESTS — DO NOT DO YET", "Chapter 3 Forbidden Valley combat chain. It is a real canonical quest but is deliberately deferred from the Chapter 2 pre-faction route.", "Chapter 3 —  — F. KILA — RECRUIT CHANI", "Quest giver: Chani", "Area: Kila", "Status: MAIN STORY — CHANI SUBQUEST", "Reward: 400 Glory", "Walkthrough. After reporting Damaka's death, Chani asks you to wipe out five overgrown spiders scattered around the Forbidden Valley/high plains. Hunt them in any order. Smaller spiders often accompany them, so clear adds first.", "Completion. Return to Chani after all five are dead.", "Related: Recruit Chani"),
            reward = "400 Glory",
            warnings = "",
            searchTags = listOf("Kila", "", "F. LATER KILA QUESTS — DO NOT DO YET", "F. KILA — RECRUIT CHANI"),
        ),
        Quest(
            id = "R3-C3-008",
            chapter = 3,
            playOrder = 8,
            title = "Speak to the Oracle",
            aliases = listOf(),
            category = "MAIN STORY — ACCESS TO RITUAL SITE",
            giver = "Chani",
            location = "Kila",
            prerequisites = "",
            summary = "Cross the Forbidden Valley temple and reach Margoloth's den.",
            walkthroughSteps = listOf("Chapter 2 — Kila — F. LATER KILA QUESTS — DO NOT DO YET", "Chapter 3 Margoloth/Oracle quest. It is a real canonical quest but is deliberately deferred from the Chapter 2 pre-faction route.", "Chapter 3 —  — G. KILA — THE RIGHT PLACE", "Quest giver: Chani", "Area: Kila", "Status: MAIN STORY — ACCESS TO RITUAL SITE", "Reward: Main-story Glory", "Walkthrough. Travel to the northeastern temple entrance. If Mud is still following you, he may finally leave to explore the temple on his own. Inside, use the jade-statue pedestal mechanism to open the next passage. Fight through Guardians, Black Ghouls and temple enemies, using the next pedestal/route mechanisms until you reach Margoloth.", "Completion. Speak with Margoloth, the Oracle.", "Related: The Right Place"),
            reward = "Main-story Glory",
            warnings = "⚠ Important: This quest is required to complete The Right Place.",
            searchTags = listOf("Kila", "", "F. LATER KILA QUESTS — DO NOT DO YET", "G. KILA — THE RIGHT PLACE"),
        ),
        Quest(
            id = "R3-C3-009",
            chapter = 3,
            playOrder = 9,
            title = "The Right Place",
            aliases = listOf(),
            category = "MAIN STORY — REQUIRED",
            giver = "Eldric",
            location = "Kila",
            prerequisites = "",
            summary = "Reach Margoloth's den and confirm it is magically shielded enough for the Spirit Ritual.",
            walkthroughSteps = listOf("Chapter 2 — Kila — F. LATER KILA QUESTS — DO NOT DO YET", "Chapter 3 ritual-location quest in the Forbidden Valley. It is a real canonical quest but is deliberately deferred from the Chapter 2 pre-faction route.", "Chapter 3 —  — G. KILA — THE RIGHT PLACE", "Quest giver: Eldric", "Area: Kila", "Status: MAIN STORY — REQUIRED", "Reward: 400 Glory", "Walkthrough. Eldric says the ritual needs a place shielded from outside magic. The den of an ancient creature fits the requirement. Complete Speak to the Oracle and enter Margoloth's lair.", "Completion. Once the Oracle's den is reached/confirmed, the ritual-site requirement completes."),
            reward = "400 Glory",
            warnings = "⚠ Important: While in this region, also deal with the Shadow Lord of Discord / local Crystal Portal if still active.",
            searchTags = listOf("Kila", "", "F. LATER KILA QUESTS — DO NOT DO YET", "G. KILA — THE RIGHT PLACE"),
        ),
        Quest(
            id = "R3-C3-010",
            chapter = 3,
            playOrder = 10,
            title = "The Tower in the Shadows",
            aliases = listOf(),
            category = "Side quest",
            giver = "",
            location = "Calador",
            prerequisites = "",
            summary = "Chapter 3 content in eastern Calador after access across the lava river. It is a real journal quest but is intentionally excluded from the pre-faction walkthrough.",
            walkthroughSteps = listOf("Chapter 3 content in eastern Calador after access across the lava river. It is a real journal quest but is intentionally excluded from the pre-faction walkthrough."),
            reward = "",
            warnings = "",
            searchTags = listOf("Calador", "I. DEFER THESE UNTIL AFTER FACTION / LATER CHAPTERS"),
        ),
        Quest(
            id = "R3-C3-011",
            chapter = 3,
            playOrder = 11,
            title = "The Spirit Ritual",
            aliases = listOf("The Spirit Ritual — Final Step"),
            category = "CHAPTER 3 FINALE",
            giver = "Eldric",
            location = "Kila",
            prerequisites = "",
            summary = "Recruit Eldric, Chani and Zacharias, recover Nekroimortar, find Margoloth's magically shielded den, then return to Eldric and perform the ritual on Kila.\nReport all five requirements to Eldric, travel to Margoloth's den and start the ritual.",
            walkthroughSteps = listOf("Chapter 2 — Calador — I. DEFER THESE UNTIL AFTER FACTION / LATER CHAPTERS", "Chapter 3 main story, only after The Ancient Knowledge and a faction commitment. It is a real journal quest but is intentionally excluded from the pre-faction walkthrough.", "Chapter 2 — Kila — F. LATER KILA QUESTS — DO NOT DO YET", "Chapter 3 main-story ritual after Eldric, Chani, Zacharias and the ritual components are ready. It is a real canonical quest but is deliberately deferred from the Chapter 2 pre-faction route.", "Chapter 3 —  — A. THE SPIRIT RITUAL — MASTER QUEST", "Quest giver: Eldric", "Area: Calador / Kila", "Status: CHAPTER 3 — MAIN STORY PARENT", "Reward: 2,000 Glory at final completion, plus subquest rewards", "Walkthrough. After The Ancient Knowledge advances, speak with Eldric. The Grimoire reveals the ritual requirements. This starts Recruit Eldric, Recruit Chani, Recruit Zacharias, A Powerful Spell and The Right Place. Complete all five before reporting back to Eldric.", "Completion. Once every requirement is complete, tell Eldric you are ready. Travel to Margoloth's den on Kila and speak with Eldric there to begin the ritual.", "Related: Recruit Eldric / Recruit Chani / Recruit Zacharias / A Powerful Spell / The Right Place", "Chapter 3 —  — J. PERFORM THE SPIRIT RITUAL", "Quest giver: Eldric", "Area: Kila", "Status: CHAPTER 3 FINALE", "Reward: 2,000 Glory, plus 1,000 Glory for the final 'ready' report step", "Walkthrough. Return to Eldric and confirm you are fully prepared. He directs the group to Kila. Travel to Margoloth's den — the nearby teleporter is the fastest route if activated. Approach Eldric and the assembled ritual participants. Speak with Eldric to begin the ceremony.", "Completion. Watch the ritual and the conversation with Nekroloth. The quest completes and Chapter 4 begins.", "Related: The Traitor"),
            reward = "2,000 Glory, plus 1,000 Glory for the final 'ready' report step",
            warnings = "⚠ Important: Completing the ritual ends Chapter 3 and advances the game into Chapter 4. Finish any Chapter 3 cleanup you care about first.\n⚠ Important: This is the real Chapter 3 -> Chapter 4 transition. Make your cleanup save before initiating it.",
            searchTags = listOf("Calador", "Kila", "", "I. DEFER THESE UNTIL AFTER FACTION / LATER CHAPTERS", "F. LATER KILA QUESTS — DO NOT DO YET", "A. THE SPIRIT RITUAL — MASTER QUEST", "J. PERFORM THE SPIRIT RITUAL"),
        ),
    )

    val notes: List<RisenGuideNote> = listOf(
        RisenGuideNote(3, 1, "Chapter 3 overview", listOf("The Spirit Ritual")),
        RisenGuideNote(3, 1, "Chapter 3 objective", listOf("After joining one of the three factions and advancing The Ancient Knowledge with Eldric, the hero finally learns that a Spirit Ritual may restore his missing soul. The ritual requires five things: Eldric, Chani, Zacharias, a powerful spell called Nekroimortar, and a magically shielded ritual site. All five requirements are real journal quests under The Spirit Ritual.", "Recommended route: Do Calador first because Recruit Eldric opens eastern Calador and naturally lets you collect A Powerful Spell. Then do Taranis for Zacharias, and finish on Kila with Chani + The Right Place so you are already standing near the ritual site.")),
        RisenGuideNote(3, 1, "The Spirit Ritual — continued quest guidance", listOf("Quick solution: Recruit Eldric, Chani and Zacharias, recover Nekroimortar, find Margoloth's magically shielded den, then return to Eldric and perform the ritual on Kila.", "Walkthrough. After The Ancient Knowledge advances, speak with Eldric. The Grimoire reveals the ritual requirements. This starts Recruit Eldric, Recruit Chani, Recruit Zacharias, A Powerful Spell and The Right Place. Complete all five before reporting back to Eldric.", "Completion. Once every requirement is complete, tell Eldric you are ready. Travel to Margoloth's den on Kila and speak with Eldric there to begin the ritual.", "⚠ Important: Completing the ritual ends Chapter 3 and advances the game into Chapter 4. Finish any Chapter 3 cleanup you care about first.", "Quest giver: Eldric", "Area: Calador / Kila", "Status: CHAPTER 3 — MAIN STORY PARENT", "Reward: 2,000 Glory at final completion, plus subquest rewards", "Related: Recruit Eldric / Recruit Chani / Recruit Zacharias / A Powerful Spell / The Right Place")),
        RisenGuideNote(3, 11, "H. OPTIONAL BUT EFFICIENT CHAPTER 3 CLEANUP", listOf("These are not extra Spirit Ritual requirements, but they overlap the same routes and are efficient to finish now:", "Destroy the Calador Crystal Portal during Recruit Eldric.", "Destroy the Taranis Crystal Portal after Recruit Zacharias.", "Destroy the Kila Crystal Portal near Margoloth / Shadow Lord of Discord while doing The Right Place.", "If the Crab Coast portal is still open, return later and finish The Shadow Lord of Hate.", "After all portals are destroyed, report to Bones to complete The Realm of the Shadows.")),
        RisenGuideNote(3, 11, "I. FINAL PREPARATION CHECK", listOf("Recruit Eldric — COMPLETE", "Recruit Chani — COMPLETE", "Recruit Zacharias — COMPLETE", "A Powerful Spell / Nekroimortar — COMPLETE", "The Right Place / Margoloth's den — COMPLETE", "Optional portal cleanup completed as desired", "Any Chapter 3 side quests you care about finished", "Permanent save created before starting the ritual")),
        RisenGuideNote(3, 12, "CHAPTER 3 COMPLETION CHECKLIST", listOf("A faction has been joined.", "The Ancient Knowledge has advanced far enough to start The Spirit Ritual.", "Eastern Calador has been unlocked.", "The Shadow Lord of Doubt is dead.", "Eldric has agreed to participate.", "Nekroimortar has been recovered.", "The Reactor on Taranis is complete.", "Zacharias has been recruited.", "The Forbidden Valley is open.", "Damaka was found.", "All five Soldiers of the Oracle were killed.", "Chani has been recruited.", "Margoloth has been reached.", "The Right Place is complete.", "A permanent save exists before the ritual.", "The Spirit Ritual is complete and Chapter 4 has begun.")),
        RisenGuideNote(3, 12, "WHAT COMES NEXT", listOf("The next guide should begin with Chapter 4 and The Traitor. From there the story starts converging toward Skull Island, the alliance fleet, the final assault and Nekroloth.")),
    )
}
