package com.sliverzfx.gothicquest

internal object RisenGuidePart4Data {
    val quests: List<Quest> = listOf(
        Quest(
            id = "R1-C1-045",
            chapter = 1,
            playOrder = 45,
            title = "Beer for Bryn",
            category = "SAFE",
            giver = "Bryn",
            location = "Volcano Keep / Monastery",
            prerequisites = "",
            summary = "Give Bryn one beer.",
            walkthroughSteps = listOf("Walkthrough. Bryn is camped just south of the Volcano Keep entrance. Speak with him and hand over a beer.", "Completion. The quest completes immediately after the delivery."),
            reward = "50 XP",
            warnings = "",
            searchTags = listOf("Beer for Bryn", "Bryn", "Volcano Keep / Monastery", "SAFE", "—", "A. OUTSIDE THE KEEP"),
        ),
        Quest(
            id = "R1-C1-046",
            chapter = 1,
            playOrder = 46,
            title = "Bryn's dangerous monsters",
            category = "SAFE — COMBAT",
            giver = "Bryn",
            location = "Volcano Keep / Monastery",
            prerequisites = "",
            summary = "Kill the three sly gnomes west of Bryn's campfire.",
            walkthroughSteps = listOf("Walkthrough. Take the job from Bryn, move west from his fire and kill the three quest gnomes.", "Completion. Return to Bryn after all three are dead."),
            reward = "150 XP + gold / dialogue XP",
            warnings = "",
            searchTags = listOf("Bryn's dangerous monsters", "Bryn", "Volcano Keep / Monastery", "SAFE — COMBAT", "—", "A. OUTSIDE THE KEEP"),
        ),
        Quest(
            id = "R1-C1-047",
            chapter = 1,
            playOrder = 47,
            title = "Follow Taylor",
            category = "MAGE / VOLUNTARY ENTRY",
            giver = "Taylor",
            location = "Volcano Keep / Monastery",
            prerequisites = "",
            summary = "Follow Taylor to your sleeping quarters and speak with him there.",
            walkthroughSteps = listOf("Walkthrough. If you voluntarily choose the Mage path, Pallas sends you to Taylor. Ask to see your chamber and follow him through the Keep.", "Completion. Speak with Taylor when you reach the room."),
            reward = "50 XP",
            warnings = "⚠ Important: Warriors follow Kalib instead; forced recruits do not receive the same Mage-entry setup.",
            searchTags = listOf("Follow Taylor", "Taylor", "Volcano Keep / Monastery", "MAGE / VOLUNTARY ENTRY", "—", "B. ARRIVAL, QUARTERS & THE KEEP GATE"),
        ),
        Quest(
            id = "R1-C1-048",
            chapter = 1,
            playOrder = 48,
            title = "Follow Kalib",
            category = "WARRIOR OF THE ORDER",
            giver = "Kalib",
            location = "Volcano Keep / Monastery",
            prerequisites = "",
            summary = "Follow Kalib to your quarters.",
            walkthroughSteps = listOf("Walkthrough. If you choose or are forced into the Warrior path, Pallas sends you to Kalib. Ask where you can sleep and follow him.", "Completion. Speak with Kalib at the destination."),
            reward = "50 XP",
            warnings = "⚠ Important: This is the Warrior counterpart to Follow Taylor.",
            searchTags = listOf("Follow Kalib", "Kalib", "Volcano Keep / Monastery", "WARRIOR OF THE ORDER", "—", "B. ARRIVAL, QUARTERS & THE KEEP GATE"),
        ),
        Quest(
            id = "R1-C1-049",
            chapter = 1,
            playOrder = 49,
            title = "The gate to the keep",
            category = "SHARED",
            giver = "Kalib / Ignatius",
            location = "Volcano Keep / Monastery",
            prerequisites = "",
            summary = "Ask about leaving the Monastery, then get Ignatius to authorize Pallas to open the gate.",
            walkthroughSteps = listOf("Walkthrough. Ask Kalib about getting out. He explains that only Ignatius can give the necessary permission. Speak with Ignatius, then return toward Pallas/the gate.", "Completion. The gate becomes available for outside Master-test errands."),
            reward = "100 XP",
            warnings = "⚠ Important: Do this early; Abrax and Cyrus both send you outside.",
            searchTags = listOf("The gate to the keep", "Kalib / Ignatius", "Volcano Keep / Monastery", "SHARED", "—", "B. ARRIVAL, QUARTERS & THE KEEP GATE"),
        ),
        Quest(
            id = "R1-C1-050",
            chapter = 1,
            playOrder = 50,
            title = "The tests of the Masters",
            category = "SHARED — MAIN MONASTERY QUEST",
            giver = "Pallas",
            location = "Volcano Keep / Monastery",
            prerequisites = "",
            summary = "Complete the required tests for Vitus, Abrax, Cyrus, Ignatius and Illumar.",
            walkthroughSteps = listOf("Walkthrough. Vitus requires Dalman's trust and Wisdom in Combat; Abrax requires his plant/test chain; Cyrus requires Severin's artifacts and the crates; Ignatius requires his library test and Fire Crystal; Illumar requires the basics, theory and practical scroll-creation test.", "Completion. After all Masters acknowledge their tests, report the finished set as instructed.", "Related quests: Vitus / Abrax / Cyrus / Ignatius / Illumar"),
            reward = "600 XP",
            warnings = "⚠ Important: Ask Pallas for his own test dialogue as soon as possible; old walkthroughs note a possible progression bug if his dialogue is skipped.",
            searchTags = listOf("The tests of the Masters", "Pallas", "Volcano Keep / Monastery", "SHARED — MAIN MONASTERY QUEST", "Vitus / Abrax / Cyrus / Ignatius / Illumar", "C. THE TESTS OF THE MASTERS — MAIN ORDER CHAIN"),
        ),
        Quest(
            id = "R1-C1-051",
            chapter = 1,
            playOrder = 51,
            title = "Get yourself a fighting staff",
            category = "SHARED — TRAINING",
            giver = "Aric",
            location = "Volcano Keep / Monastery",
            prerequisites = "",
            summary = "Get a novice staff from Karlsen and return to Aric.",
            walkthroughSteps = listOf("Walkthrough. After Aric orders you to arm yourself, speak with smith Karlsen. He gives you a novice staff for free.", "Completion. Return to Aric."),
            reward = "50 XP",
            warnings = "",
            searchTags = listOf("Get yourself a fighting staff", "Aric", "Volcano Keep / Monastery", "SHARED — TRAINING", "—", "D. ARIC'S TRAINING CHAIN"),
        ),
        Quest(
            id = "R1-C1-052",
            chapter = 1,
            playOrder = 52,
            title = "Basic training",
            category = "SHARED — TRAINING HUB",
            giver = "Aric",
            location = "Volcano Keep / Monastery",
            prerequisites = "",
            summary = "Defeat the three trainees and then Aric; report onward to Vitus.",
            walkthroughSteps = listOf("Walkthrough. Aric points you to Tucker, William and Kato. Complete their individual fights, then challenge Aric.", "Completion. After Aric is beaten, speak with Vitus; this also opens the upper Monastery area.", "Related quests: Tucker / William / Kato / Aric"),
            reward = "500 XP",
            warnings = "",
            searchTags = listOf("Basic training", "Aric", "Volcano Keep / Monastery", "SHARED — TRAINING HUB", "Tucker / William / Kato / Aric", "D. ARIC'S TRAINING CHAIN"),
        ),
        Quest(
            id = "R1-C1-053",
            chapter = 1,
            playOrder = 53,
            title = "Fight against Tucker",
            category = "SHARED — ARENA",
            giver = "Tucker",
            location = "Volcano Keep / Monastery",
            prerequisites = "",
            summary = "Beat Tucker in the training fight.",
            walkthroughSteps = listOf("Walkthrough. Challenge Tucker first and knock him out under training rules.", "Completion. The quest completes on victory."),
            reward = "100 XP",
            warnings = "",
            searchTags = listOf("Fight against Tucker", "Tucker", "Volcano Keep / Monastery", "SHARED — ARENA", "—", "D. ARIC'S TRAINING CHAIN"),
        ),
        Quest(
            id = "R1-C1-054",
            chapter = 1,
            playOrder = 54,
            title = "Fight against William",
            category = "SHARED — ARENA",
            giver = "William",
            location = "Volcano Keep / Monastery",
            prerequisites = "",
            summary = "Defeat William after Tucker.",
            walkthroughSteps = listOf("Walkthrough. Once Tucker is beaten, challenge William and win.", "Completion. The quest completes when William is knocked out."),
            reward = "100 XP",
            warnings = "",
            searchTags = listOf("Fight against William", "William", "Volcano Keep / Monastery", "SHARED — ARENA", "—", "D. ARIC'S TRAINING CHAIN"),
        ),
        Quest(
            id = "R1-C1-055",
            chapter = 1,
            playOrder = 55,
            title = "Kato's lesson",
            category = "SHARED — TRAINING",
            giver = "Kato",
            location = "Volcano Keep / Monastery",
            prerequisites = "",
            summary = "Beat Kato in the training-yard lesson.",
            walkthroughSteps = listOf("Walkthrough. After Tucker and William, speak with Kato and fight him in the yard.", "Completion. Defeat him to unlock his proper arena fight."),
            reward = "50 XP",
            warnings = "",
            searchTags = listOf("Kato's lesson", "Kato", "Volcano Keep / Monastery", "SHARED — TRAINING", "—", "D. ARIC'S TRAINING CHAIN"),
        ),
        Quest(
            id = "R1-C1-056",
            chapter = 1,
            playOrder = 56,
            title = "Fight against Kato",
            category = "SHARED — ARENA",
            giver = "Kato",
            location = "Volcano Keep / Monastery",
            prerequisites = "",
            summary = "Beat Kato in the arena after his lesson.",
            walkthroughSteps = listOf("Walkthrough. Challenge him again once the arena fight becomes available.", "Completion. Return to Aric after winning."),
            reward = "100 XP",
            warnings = "",
            searchTags = listOf("Fight against Kato", "Kato", "Volcano Keep / Monastery", "SHARED — ARENA", "—", "D. ARIC'S TRAINING CHAIN"),
        ),
        Quest(
            id = "R1-C1-057",
            chapter = 1,
            playOrder = 57,
            title = "Fight against Aric",
            category = "SHARED — ARENA / STORY",
            giver = "Aric",
            location = "Volcano Keep / Monastery",
            prerequisites = "",
            summary = "Challenge and defeat Aric after beating all three trainees.",
            walkthroughSteps = listOf("Walkthrough. Return to Aric after Tucker, William and Kato are complete. Accept the fight and beat him.", "Completion. The victory closes Aric's combat-training chain."),
            reward = "200 XP",
            warnings = "⚠ Important: Do not kill named trainees after knocking them down.",
            searchTags = listOf("Fight against Aric", "Aric", "Volcano Keep / Monastery", "SHARED — ARENA / STORY", "—", "D. ARIC'S TRAINING CHAIN"),
        ),
        Quest(
            id = "R1-C1-058",
            chapter = 1,
            playOrder = 58,
            title = "Find Hemlar's murderer",
            category = "SHARED — INVESTIGATION",
            giver = "Inquisitor Mendoza",
            location = "Volcano Keep / Monastery",
            prerequisites = "",
            summary = "Investigate Hemlar's death, identify his drug partner, use the weed-dealer trap and expose Aric as the murderer.",
            walkthroughSteps = listOf("Walkthrough. After you are shown to your room, Mendoza assigns the murder case. Examine the room, investigate the knife and weed, identify Ash as Hemlar's partner, distribute the reefers, then use the bathhouse trap.", "Completion. At the bathhouse choose to wait for the killer. Aric appears. Defeat him or escape back to the courtyard; either resolution closes the murder case.", "Related quests: Crime scene / suspects / reefers"),
            reward = "500 XP + permanent-stat potion choice",
            warnings = "⚠ Important: Complete Aric's training/arena content before finishing the murder if you want all related XP.",
            searchTags = listOf("Find Hemlar's murderer", "Inquisitor Mendoza", "Volcano Keep / Monastery", "SHARED — INVESTIGATION", "Crime scene / suspects / reefers", "E. HEMLAR'S MURDER"),
        ),
        Quest(
            id = "R1-C1-059",
            chapter = 1,
            playOrder = 59,
            title = "Investigate the crime scene",
            category = "SHARED — INVESTIGATION",
            giver = "Trigger quest",
            location = "Volcano Keep / Monastery",
            prerequisites = "",
            summary = "Collect Hemlar's purse, the weed packet and the kitchen knife.",
            walkthroughSteps = listOf("Walkthrough. Search the room carefully: purse near the bed, small weed packet on the floor, knife on Hemlar's body.", "Completion. Finding all three pieces completes the scene investigation."),
            reward = "100 XP",
            warnings = "",
            searchTags = listOf("Investigate the crime scene", "Automatic / murder chain", "Volcano Keep / Monastery", "SHARED — INVESTIGATION", "—", "E. HEMLAR'S MURDER"),
        ),
        Quest(
            id = "R1-C1-060",
            chapter = 1,
            playOrder = 60,
            title = "What does Harlock know?",
            category = "SHARED — INVESTIGATION",
            giver = "Caspar / Harlock",
            location = "Volcano Keep / Monastery",
            prerequisites = "",
            summary = "Trace the kitchen knife to Harlock and question him.",
            walkthroughSteps = listOf("Walkthrough. After discussing the murder with Vitus/Caspar and obtaining the relevant suspect information, confront Harlock about the knife.", "Completion. Exhaust Harlock's dialogue for the investigation update."),
            reward = "200 XP",
            warnings = "",
            searchTags = listOf("What does Harlock know?", "Caspar / Harlock", "Volcano Keep / Monastery", "SHARED — INVESTIGATION", "—", "E. HEMLAR'S MURDER"),
        ),
        Quest(
            id = "R1-C1-061",
            chapter = 1,
            playOrder = 61,
            title = "Who is Hemlar's partner?",
            category = "SHARED — INVESTIGATION",
            giver = "Caspar",
            location = "Volcano Keep / Monastery",
            prerequisites = "",
            summary = "Work through the suspect list until Ash admits he was Hemlar's partner.",
            walkthroughSteps = listOf("Walkthrough. Get Pallas's suspect list, question the listed people, use Yoki/Caspar/Taylor information to narrow it down, then confront Ash.", "Completion. Ash admits the partnership and gives the next plan."),
            reward = "150 XP",
            warnings = "",
            searchTags = listOf("Who is Hemlar's partner?", "Caspar", "Volcano Keep / Monastery", "SHARED — INVESTIGATION", "—", "E. HEMLAR'S MURDER"),
        ),
        Quest(
            id = "R1-C1-062",
            chapter = 1,
            playOrder = 62,
            title = "The circle of suspects",
            category = "SHARED — INVESTIGATION",
            giver = "Caspar / Pallas",
            location = "Volcano Keep / Monastery",
            prerequisites = "",
            summary = "Get the official list of people who recently had permission to leave.",
            walkthroughSteps = listOf("Walkthrough. Caspar suggests the murderer may have outside access. Ask Pallas for the list.", "Completion. Receiving the list advances the suspect investigation."),
            reward = "100 XP",
            warnings = "",
            searchTags = listOf("The circle of suspects", "Caspar / Pallas", "Volcano Keep / Monastery", "SHARED — INVESTIGATION", "—", "E. HEMLAR'S MURDER"),
        ),
        Quest(
            id = "R1-C1-063",
            chapter = 1,
            playOrder = 63,
            title = "Access to the cemetery",
            category = "SHARED — ACCESS",
            giver = "Yoki",
            location = "Volcano Keep / Monastery",
            prerequisites = "",
            summary = "Convince Yoki to let you into the cemetery.",
            walkthroughSteps = listOf("Walkthrough. At the cemetery entrance, Yoki blocks entry. Give him Harlock's stew or later use the brugleweed/dealer route.", "Completion. Once Yoki lets you pass, the cemetery and crypt become available."),
            reward = "100 XP",
            warnings = "⚠ Important: The cemetery is needed for Wisdom in Combat.",
            searchTags = listOf("Access to the cemetery", "Yoki", "Volcano Keep / Monastery", "SHARED — ACCESS", "—", "E. HEMLAR'S MURDER"),
        ),
        Quest(
            id = "R1-C1-064",
            chapter = 1,
            playOrder = 64,
            title = "Distribute the weed reefers in the keep",
            category = "SHARED — INVESTIGATION / DELIVERY",
            giver = "Ash",
            location = "Volcano Keep / Monastery",
            prerequisites = "",
            summary = "Sell all ten reefers around the Keep, then report to Caspar.",
            walkthroughSteps = listOf("Walkthrough. After Ash admits being Hemlar's partner, take the ten reefers and sell them to eligible Monastery residents such as Taylor, Harlock, Dalman, Kato, Kalib, Karlsen, Tucker, Yoki and Caspar.", "Completion. When the ten are distributed, speak with Caspar; this sets up the killer trap."),
            reward = "400 XP",
            warnings = "⚠ Important: Do this before the bathhouse confrontation with Aric.",
            searchTags = listOf("Distribute the weed reefers in the keep", "Ash", "Volcano Keep / Monastery", "SHARED — INVESTIGATION / DELIVERY", "—", "E. HEMLAR'S MURDER"),
        ),
        Quest(
            id = "R1-C1-065",
            chapter = 1,
            playOrder = 65,
            title = "Dalman trusts you",
            category = "SHARED — VITUS TEST",
            giver = "Dalman",
            location = "Volcano Keep / Monastery",
            prerequisites = "",
            summary = "Find Dalman a replacement worker by persuading Taylor with 10 apples.",
            walkthroughSteps = listOf("Walkthrough. Ask Dalman what he needs. Speak with Taylor and give him ten apples so he agrees to take the post.", "Completion. Return to Dalman, then report the result for Vitus's test."),
            reward = "100 XP + Fireflush",
            warnings = "",
            searchTags = listOf("Dalman trusts you", "Dalman", "Volcano Keep / Monastery", "SHARED — VITUS TEST", "—", "F. MASTER VITUS"),
        ),
        Quest(
            id = "R1-C1-066",
            chapter = 1,
            playOrder = 66,
            title = "Rufus is seeking Wisdom in Combat",
            category = "SHARED — CEMETERY",
            giver = "Rufus",
            location = "Volcano Keep / Monastery",
            prerequisites = "",
            summary = "Find the Wisdom in Combat book in the cemetery crypt and give it to Rufus.",
            walkthroughSteps = listOf("Walkthrough. After gaining cemetery access, enter the crypt, find Berengir's skeleton and take his key. Use it on the chest at the far end of the passage.", "Completion. Give the book to Rufus."),
            reward = "50 XP",
            warnings = "",
            searchTags = listOf("Rufus is seeking Wisdom in Combat", "Rufus", "Volcano Keep / Monastery", "SHARED — CEMETERY", "—", "F. MASTER VITUS"),
        ),
        Quest(
            id = "R1-C1-067",
            chapter = 1,
            playOrder = 67,
            title = "Wisdom in Combat found",
            category = "SHARED — VITUS TEST",
            giver = "Cemetery discovery",
            location = "Volcano Keep / Monastery",
            prerequisites = "",
            summary = "Recover the Wisdom in Combat book from the crypt.",
            walkthroughSteps = listOf("Walkthrough. Use Berengir's key to open the crypt chest containing the book.", "Completion. Picking up the book completes this journal step."),
            reward = "50 XP",
            warnings = "",
            searchTags = listOf("Wisdom in Combat found", "Cemetery discovery", "Volcano Keep / Monastery", "SHARED — VITUS TEST", "—", "F. MASTER VITUS"),
        ),
        Quest(
            id = "R1-C1-068",
            chapter = 1,
            playOrder = 68,
            title = "The test of Master Vitus",
            category = "SHARED — MASTER TEST",
            giver = "Vitus",
            location = "Volcano Keep / Monastery",
            prerequisites = "",
            summary = "Complete Dalman's trust task and recover Wisdom in Combat.",
            walkthroughSteps = listOf("Walkthrough. Ask Vitus for his test. Finish Dalman's replacement problem and the cemetery book objective.", "Completion. Return to Vitus and ask to be trained / report both accomplishments."),
            reward = "200 XP",
            warnings = "",
            searchTags = listOf("The test of Master Vitus", "Vitus", "Volcano Keep / Monastery", "SHARED — MASTER TEST", "—", "F. MASTER VITUS"),
        ),
        Quest(
            id = "R1-C1-069",
            chapter = 1,
            playOrder = 69,
            title = "Mutual aid",
            category = "SHARED / SCROLL SUPPORT",
            giver = "Jervis",
            location = "Volcano Keep / Monastery",
            prerequisites = "",
            summary = "Bring Jervis two blank scrolls and one illusion scroll.",
            walkthroughSteps = listOf("Walkthrough. Speak with Jervis about training/help. Collect the requested materials and return.", "Completion. Hand over the items."),
            reward = "100 XP",
            warnings = "",
            searchTags = listOf("Mutual aid", "Jervis", "Volcano Keep / Monastery", "SHARED / SCROLL SUPPORT", "—", "G. MASTER ILLUMAR — SCROLL CREATION"),
        ),
        Quest(
            id = "R1-C1-070",
            chapter = 1,
            playOrder = 70,
            title = "The basics of scroll creation",
            category = "SHARED — MASTER TEST",
            giver = "Illumar",
            location = "Volcano Keep / Monastery",
            prerequisites = "",
            summary = "Read Illumar's two instructional bookstands and report back.",
            walkthroughSteps = listOf("Walkthrough. Accept the lesson from Master Illumar and read both required bookstands.", "Completion. Return to Illumar."),
            reward = "100 XP",
            warnings = "",
            searchTags = listOf("The basics of scroll creation", "Illumar", "Volcano Keep / Monastery", "SHARED — MASTER TEST", "—", "G. MASTER ILLUMAR — SCROLL CREATION"),
        ),
        Quest(
            id = "R1-C1-071",
            chapter = 1,
            playOrder = 71,
            title = "Get a quill",
            category = "SHARED — SCROLL TEST",
            giver = "Illumar",
            location = "Volcano Keep / Monastery",
            prerequisites = "",
            summary = "Get a quill, preferably the free one from Caspar.",
            walkthroughSteps = listOf("Walkthrough. After the basics lesson, ask students about a quill. Enzo sells one, while Caspar can provide one without the cost.", "Completion. Obtain the quill and continue Illumar's chain."),
            reward = "100 XP",
            warnings = "",
            searchTags = listOf("Get a quill", "Illumar", "Volcano Keep / Monastery", "SHARED — SCROLL TEST", "—", "G. MASTER ILLUMAR — SCROLL CREATION"),
        ),
        Quest(
            id = "R1-C1-072",
            chapter = 1,
            playOrder = 72,
            title = "Erlan doesn't know what to do",
            category = "SHARED — SCROLL THEORY",
            giver = "Erlan",
            location = "Volcano Keep / Monastery",
            prerequisites = "",
            summary = "Help Erlan determine the Nautilus-scroll ingredient.",
            walkthroughSteps = listOf("Walkthrough. Question Enzo and the other students about scroll ingredients, then return to Erlan with the answer.", "Completion. Give Erlan the information and take the useful ingredient/reward option."),
            reward = "100 XP",
            warnings = "",
            searchTags = listOf("Erlan doesn't know what to do", "Erlan", "Volcano Keep / Monastery", "SHARED — SCROLL THEORY", "—", "G. MASTER ILLUMAR — SCROLL CREATION"),
        ),
        Quest(
            id = "R1-C1-073",
            chapter = 1,
            playOrder = 73,
            title = "The theory of scroll creation",
            category = "SHARED — MASTER TEST",
            giver = "Illumar",
            location = "Volcano Keep / Monastery",
            prerequisites = "",
            summary = "Learn the ingredients for the six first-seal scrolls.",
            walkthroughSteps = listOf("Walkthrough. Collect the formulas from students and bookstands: Magic Light, Light Healing, Telekinesis, Nautilus Transformation, Illusion and Jest.", "Completion. Report the full set of ingredients to Illumar."),
            reward = "100 XP",
            warnings = "",
            searchTags = listOf("The theory of scroll creation", "Illumar", "Volcano Keep / Monastery", "SHARED — MASTER TEST", "—", "G. MASTER ILLUMAR — SCROLL CREATION"),
        ),
        Quest(
            id = "R1-C1-074",
            chapter = 1,
            playOrder = 74,
            title = "Erlan and Enzo's turkey",
            category = "SHARED — SCROLL SUPPORT",
            giver = "Erlan",
            location = "Volcano Keep / Monastery",
            prerequisites = "",
            summary = "Get a turkey for Erlan so he and Enzo can settle their dispute.",
            walkthroughSteps = listOf("Walkthrough. Buy the required turkey from Hemlar/Hemlock's source as directed, then bring it to Erlan.", "Completion. Hand over the turkey."),
            reward = "150 XP + Jest scroll",
            warnings = "",
            searchTags = listOf("Erlan and Enzo's turkey", "Erlan", "Volcano Keep / Monastery", "SHARED — SCROLL SUPPORT", "—", "G. MASTER ILLUMAR — SCROLL CREATION"),
        ),
        Quest(
            id = "R1-C1-075",
            chapter = 1,
            playOrder = 75,
            title = "Enzo is looking for the ingredients for an illusion scroll",
            category = "SHARED — SCROLL THEORY",
            giver = "Enzo",
            location = "Volcano Keep / Monastery",
            prerequisites = "",
            summary = "Give Enzo the information/ingredient he needs so he will tell you the Nautilus recipe.",
            walkthroughSteps = listOf("Walkthrough. Speak with Enzo during the theory quest and satisfy his Illusion-scroll request.", "Completion. He reveals the Nautilus-shell requirement."),
            reward = "100 XP",
            warnings = "",
            searchTags = listOf("Enzo is looking for the ingredients for an illusion scroll", "Enzo", "Volcano Keep / Monastery", "SHARED — SCROLL THEORY", "—", "G. MASTER ILLUMAR — SCROLL CREATION"),
        ),
        Quest(
            id = "R1-C1-076",
            chapter = 1,
            playOrder = 76,
            title = "The test of Master Illumar",
            category = "SHARED — MASTER TEST",
            giver = "Illumar",
            location = "Volcano Keep / Monastery",
            prerequisites = "",
            summary = "Learn scroll creation, make a scroll at a writing bench and show the result to Illumar.",
            walkthroughSteps = listOf("Walkthrough. After finishing the basics and theory, learn the Create Scroll skill, use a writing bench and create a scroll from an available rune.", "Completion. Report your successful scroll to Illumar."),
            reward = "100 XP",
            warnings = "",
            searchTags = listOf("The test of Master Illumar", "Illumar", "Volcano Keep / Monastery", "SHARED — MASTER TEST", "—", "G. MASTER ILLUMAR — SCROLL CREATION"),
        ),
        Quest(
            id = "R1-C1-077",
            chapter = 1,
            playOrder = 77,
            title = "Crates for the Volcano Keep",
            category = "SHARED — MASTER TEST",
            giver = "Cyrus / Severin",
            location = "Volcano Keep / Monastery",
            prerequisites = "",
            summary = "Ask Severin at Tilda's farm about the missing crates, then report to Cyrus.",
            walkthroughSteps = listOf("Walkthrough. Once the gate is open, leave the Keep, go to Tilda's farm and speak with Severin about the delivery.", "Completion. Return to Cyrus with the information."),
            reward = "50 XP + follow-up XP",
            warnings = "",
            searchTags = listOf("Crates for the Volcano Keep", "Cyrus / Severin", "Volcano Keep / Monastery", "SHARED — MASTER TEST", "—", "H. MASTER CYRUS"),
        ),
        Quest(
            id = "R1-C1-078",
            chapter = 1,
            playOrder = 78,
            title = "Severin's artefacts",
            category = "SHARED — MASTER TEST",
            giver = "Cyrus / Severin",
            location = "Volcano Keep / Monastery",
            prerequisites = "",
            summary = "Collect Severin's ring and disk and bring them to Cyrus.",
            walkthroughSteps = listOf("Walkthrough. Speak with Severin at Tilda's farm and obtain the artifacts he has recovered.", "Completion. Return both to Cyrus and choose the minor-artifact reward offered."),
            reward = "200 XP + minor artifact",
            warnings = "",
            searchTags = listOf("Severin's artefacts", "Cyrus / Severin", "Volcano Keep / Monastery", "SHARED — MASTER TEST", "—", "H. MASTER CYRUS"),
        ),
        Quest(
            id = "R1-C1-079",
            chapter = 1,
            playOrder = 79,
            title = "The test of Master Abrax",
            category = "SHARED — MASTER TEST",
            giver = "Abrax",
            location = "Volcano Keep / Monastery",
            prerequisites = "",
            summary = "Bring Abrax 6 healing plants and 4 mana plants; optionally investigate his missing novices for extra reward.",
            walkthroughSteps = listOf("Walkthrough. Ask Abrax for his test. Gather the requested plants, using your stored herbs or collecting them outside once the gate is open.", "Completion. Hand in the plants to pass the test. You can separately find Krayban east of Tilda's farm for extra dialogue/reward."),
            reward = "500 XP",
            warnings = "⚠ Important: Do not sell healing/mana plants before this quest if you can avoid it.",
            searchTags = listOf("The test of Master Abrax", "Abrax", "Volcano Keep / Monastery", "SHARED — MASTER TEST", "—", "I. MASTER ABRAX"),
        ),
        Quest(
            id = "R1-C1-080",
            chapter = 1,
            playOrder = 80,
            title = "The test of Master Ignatius",
            category = "SHARED — MASTER TEST",
            giver = "Ignatius",
            location = "Volcano Keep / Monastery",
            prerequisites = "",
            summary = "Read the three required books in the Monastery library.",
            walkthroughSteps = listOf("Walkthrough. Accept Ignatius's test and follow him to the library.", "Completion. Read all three designated books."),
            reward = "250 XP",
            warnings = "",
            searchTags = listOf("The test of Master Ignatius", "Ignatius", "Volcano Keep / Monastery", "SHARED — MASTER TEST", "—", "J. MASTER IGNATIUS"),
        ),
        Quest(
            id = "R1-C1-081",
            chapter = 1,
            playOrder = 81,
            title = "The Crystal of Fire",
            category = "SHARED — MASTER TEST / RUIN",
            giver = "Ignatius",
            location = "Volcano Keep / Monastery",
            prerequisites = "",
            summary = "Find Nathan's body in the trapped ruin west of the Monastery and recover the Fire Crystal.",
            walkthroughSteps = listOf("Walkthrough. Leave the Keep, head downhill and west past the pond to the ruin guarded by a war cricket. Inside, kill the gnomes and solve the trap route using Telekinesis, Levitation and Nautilus Transformation as needed.", "Completion. Loot the Fire Crystal from Nathan and return it to Ignatius."),
            reward = "300 XP",
            warnings = "⚠ Important: Bring or create the required utility scrolls before entering the ruin.",
            searchTags = listOf("The Crystal of Fire", "Ignatius", "Volcano Keep / Monastery", "SHARED — MASTER TEST / RUIN", "—", "J. MASTER IGNATIUS"),
        ),
        Quest(
            id = "R1-C1-082",
            chapter = 1,
            playOrder = 82,
            title = "A new post for William",
            category = "SHARED — FOLLOW-UP",
            giver = "William / Vitus",
            location = "Volcano Keep / Monastery",
            prerequisites = "",
            summary = "After the murder is solved, help William move into a training role.",
            walkthroughSteps = listOf("Walkthrough. Speak with William after Hemlar's murderer is dealt with. Agree to help, talk to Vitus, then return to William.", "Completion. William's reassignment completes the quest."),
            reward = "100 XP",
            warnings = "",
            searchTags = listOf("A new post for William", "William / Vitus", "Volcano Keep / Monastery", "SHARED — FOLLOW-UP", "—", "K. FINAL MONASTERY STEPS"),
        ),
        Quest(
            id = "R1-C1-083",
            chapter = 1,
            playOrder = 83,
            title = "A worthy weapon",
            category = "SHARED — PRE-INITIATION",
            giver = "Ignatius / Karlsen",
            location = "Volcano Keep / Monastery",
            prerequisites = "",
            summary = "Get the fighting staff ordered by Ignatius.",
            walkthroughSteps = listOf("Walkthrough. After all Master tests are complete, Ignatius sends you to Karlsen. Tell Karlsen that Ignatius sent you.", "Completion. Karlsen gives you the required fighting staff."),
            reward = "50 XP + Fighting Staff",
            warnings = "",
            searchTags = listOf("A worthy weapon", "Ignatius / Karlsen", "Volcano Keep / Monastery", "SHARED — PRE-INITIATION", "—", "K. FINAL MONASTERY STEPS"),
        ),
        Quest(
            id = "R1-C1-084",
            chapter = 1,
            playOrder = 84,
            title = "The Initiation",
            category = "MAGE / ORDER INITIATION",
            giver = "Ignatius / Mendoza",
            location = "Volcano Keep / Monastery",
            prerequisites = "",
            summary = "Complete the initiation ritual in the Hall of the Holy Flame.",
            walkthroughSteps = listOf("Walkthrough. After the Masters' tests and worthy-weapon step, follow Ignatius into the Hall. Answer the ritual questions; the choices grant small permanent Strength, Mana or Life bonuses.", "Completion. The ceremony grants your faction robes and completes formal initiation."),
            reward = "50 XP + faction robe / Mage crystal skill unlocks",
            warnings = "⚠ Important: Mage initiation grants Mage robes and level-1 access to the three crystal-magic schools. Warrior rewards differ in equipment/progression.",
            searchTags = listOf("The Initiation", "Ignatius / Mendoza", "Volcano Keep / Monastery", "MAGE / ORDER INITIATION", "—", "K. FINAL MONASTERY STEPS"),
        ),
        Quest(
            id = "R1-C1-085",
            chapter = 1,
            playOrder = 85,
            title = "Follow the Inquisitor",
            category = "SHARED — CHAPTER TRANSITION",
            giver = "Inquisitor Mendoza",
            location = "Volcano Keep / Monastery",
            prerequisites = "",
            summary = "Follow Mendoza to the gate at the rear of the Hall of the Holy Flame.",
            walkthroughSteps = listOf("Walkthrough. After initiation, Mendoza tells you to come with him. Stay close as he leads you through the newly accessible area.", "Completion. The quest completes at the volcano/temple gate and transitions the main story toward Chapter 2."),
            reward = "50 XP",
            warnings = "",
            searchTags = listOf("Follow the Inquisitor", "Inquisitor Mendoza", "Volcano Keep / Monastery", "SHARED — CHAPTER TRANSITION", "—", "K. FINAL MONASTERY STEPS"),
        ),
        Quest(
            id = "R1-C1-086",
            chapter = 1,
            playOrder = 86,
            title = "The Magic Bullet",
            category = "MAGE ONLY",
            giver = "Vitus",
            location = "Volcano Keep / Monastery",
            prerequisites = "",
            summary = "Obtain the required magic crystal and report to Vitus for Magic Bullet training.",
            walkthroughSteps = listOf("Walkthrough. After becoming a Mage, ask Vitus about Magic Bullet and secure the required crystal.", "Completion. Return to Vitus with the crystal."),
            reward = "50 XP",
            warnings = "",
            searchTags = listOf("The Magic Bullet", "Vitus", "Volcano Keep / Monastery", "MAGE ONLY", "—", "L. MAGE-ONLY EARLY MAGIC QUESTS"),
        ),
        Quest(
            id = "R1-C1-087",
            chapter = 1,
            playOrder = 87,
            title = "The Frost Crystal",
            category = "MAGE ONLY",
            giver = "Pallas",
            location = "Volcano Keep / Monastery",
            prerequisites = "",
            summary = "Pay Pallas for Frost training, reducing the price with a Bog Body's cold heart and a small sapphire.",
            walkthroughSteps = listOf("Walkthrough. Ask Pallas for Frost Crystal training. The base price is 1000 gold; each requested item reduces the cost.", "Completion. Hand over the items, pay the remaining amount and receive the Frost Crystal."),
            reward = "100 XP + Frost Crystal",
            warnings = "",
            searchTags = listOf("The Frost Crystal", "Pallas", "Volcano Keep / Monastery", "MAGE ONLY", "—", "L. MAGE-ONLY EARLY MAGIC QUESTS"),
        ),
        Quest(
            id = "R1-C1-088",
            chapter = 1,
            playOrder = 88,
            title = "The First Seal of Runic Magic",
            category = "MAGE ONLY — 50 WISDOM",
            giver = "Ignatius",
            location = "Volcano Keep / Monastery",
            prerequisites = "",
            summary = "Reach 50 Wisdom and spend 5 learning points with Ignatius.",
            walkthroughSteps = listOf("Walkthrough. Once your Wisdom reaches 50, ask Ignatius about the first Runic Seal.", "Completion. Spend the learning points to unlock it."),
            reward = "100 XP",
            warnings = "⚠ Important: Save permanent Wisdom books/stone tablets strategically; higher seals require more Wisdom.",
            searchTags = listOf("The First Seal of Runic Magic", "Ignatius", "Volcano Keep / Monastery", "MAGE ONLY — 50 WISDOM", "—", "L. MAGE-ONLY EARLY MAGIC QUESTS"),
        ),
        Quest(
            id = "R1-C1-089",
            chapter = 1,
            playOrder = 89,
            title = "The Second Seal of Runic Magic",
            category = "MAGE ONLY — 100 WISDOM",
            giver = "Ignatius",
            location = "Volcano Keep / Monastery",
            prerequisites = "",
            summary = "Reach 100 Wisdom and spend 5 learning points with Ignatius.",
            walkthroughSteps = listOf("Walkthrough. Return to Ignatius after reaching the Wisdom threshold.", "Completion. Spend the learning points to unlock the second seal."),
            reward = "200 XP",
            warnings = "",
            searchTags = listOf("The Second Seal of Runic Magic", "Ignatius", "Volcano Keep / Monastery", "MAGE ONLY — 100 WISDOM", "—", "L. MAGE-ONLY EARLY MAGIC QUESTS"),
        ),
    )

    val notes: List<RisenGuideNote> = listOf(
        RisenGuideNote(1, 45, "Entry routes and faction warning", listOf("Volcano Keep is where the Order and Mage paths separate. If Harbour Town was resolved for the Order and you arrive voluntarily with Carlos's introduction, Pallas can let you choose Mage or Warrior of the Order. If you were captured and forcibly taken to the Monastery, the Mage choice is lost and you can only become a Warrior of the Order.", "Mage requirement: For the broadest Mage route, resolve Harbour Town for the Order and complete Belschwur's medicine work before reporting for voluntary admission.", "Permanent save: Make one before speaking with Pallas about whether you will train as a Mage or Warrior.")),
        RisenGuideNote(1, 45, "A. OUTSIDE THE KEEP", listOf()),
        RisenGuideNote(1, 47, "B. ARRIVAL, QUARTERS & THE KEEP GATE", listOf()),
        RisenGuideNote(1, 50, "C. THE TESTS OF THE MASTERS — MAIN ORDER CHAIN", listOf()),
        RisenGuideNote(1, 51, "D. ARIC'S TRAINING CHAIN", listOf()),
        RisenGuideNote(1, 58, "E. HEMLAR'S MURDER", listOf()),
        RisenGuideNote(1, 65, "F. MASTER VITUS", listOf()),
        RisenGuideNote(1, 69, "G. MASTER ILLUMAR — SCROLL CREATION", listOf()),
        RisenGuideNote(1, 77, "H. MASTER CYRUS", listOf()),
        RisenGuideNote(1, 79, "I. MASTER ABRAX", listOf()),
        RisenGuideNote(1, 80, "J. MASTER IGNATIUS", listOf()),
        RisenGuideNote(1, 82, "K. FINAL MONASTERY STEPS", listOf()),
        RisenGuideNote(1, 86, "L. MAGE-ONLY EARLY MAGIC QUESTS", listOf("These appear only if you actually become a Mage. Warriors of the Order use crystal magic differently and do not receive the full rune-magic progression.")),
        RisenGuideNote(1, 90, "CHAPTER 1 — MONASTERY COMPLETION CHECKLIST", listOf("You entered voluntarily if you wanted the Mage option.", "Pallas's faction-choice/test dialogue was exhausted.", "The Keep gate was opened before outside Master errands.", "Aric's complete training chain was finished before resolving Hemlar's murder.", "The murder investigation, suspect chain and reefer trap were completed.", "Cemetery access and Wisdom in Combat were completed.", "Vitus, Illumar, Cyrus, Abrax and Ignatius all accepted their tests.", "A Worthy Weapon was completed.", "The Initiation was completed with the desired Mage/Warrior path.", "Mage-only players checked Magic Bullet, Frost Crystal and Runic Seal quests.", "Follow the Inquisitor is ready/completed, marking the transition toward Chapter 2.")),
    )
}
