package com.sliverzfx.gothicquest

internal object Risen2GuidePart6Data {
    val quests: List<Quest> = listOf(
        Quest(
            id = "R2-C3-032",
            chapter = 3,
            playOrder = 32,
            title = "Treasure Cave",
            category = "MAIN STORY",
            giver = "Captain Slayne",
            location = "Isle of Thieves / Antigua",
            prerequisites = "",
            summary = "Follow Slayne inland and enter his Treasure Cave.",
            walkthroughSteps = listOf("Walkthrough. After rowing ashore, speak with Slayne beside the rowboat. Tell him you are ready. The journey is split into three real escort quests: Along the Beach, The Way Up and The Cave is Not Far Off. Stay close, help him with Sand Devils and Termites, and follow him all the way to the cave entrance.", "Completion. Enter the Treasure Cave.", "Related: Along the Beach / The Way Up / The Cave is Not Far Off"),
            reward = "50 Glory",
            warnings = "",
            searchTags = listOf("Treasure Cave", "A. SLAYNE'S TREASURE CAVE", "Captain Slayne", "Isle of Thieves / Antigua"),
        ),
        Quest(
            id = "R2-C3-033",
            chapter = 3,
            playOrder = 33,
            title = "Along the Beach",
            category = "MAIN STORY — ESCORT",
            giver = "Captain Slayne",
            location = "Isle of Thieves / Antigua",
            prerequisites = "",
            summary = "Follow Slayne along the beach.",
            walkthroughSteps = listOf("Walkthrough. Stay with Slayne from the landing point and clear any hostile creatures that interrupt the route.", "Completion. The quest completes at Slayne's first scripted stop."),
            reward = "10 Glory",
            warnings = "",
            searchTags = listOf("Along the Beach", "A. SLAYNE'S TREASURE CAVE", "Captain Slayne", "Isle of Thieves / Antigua"),
        ),
        Quest(
            id = "R2-C3-034",
            chapter = 3,
            playOrder = 34,
            title = "The Way Up",
            category = "MAIN STORY — ESCORT",
            giver = "Captain Slayne",
            location = "Isle of Thieves / Antigua",
            prerequisites = "",
            summary = "Follow Slayne up the slope into the jungle.",
            walkthroughSteps = listOf("Walkthrough. Continue from the beach and stay close while climbing inland.", "Completion. Reach the next scripted stop."),
            reward = "10 Glory",
            warnings = "",
            searchTags = listOf("The Way Up", "A. SLAYNE'S TREASURE CAVE", "Captain Slayne", "Isle of Thieves / Antigua"),
        ),
        Quest(
            id = "R2-C3-035",
            chapter = 3,
            playOrder = 35,
            title = "The Cave is Not Far Off",
            category = "MAIN STORY — ESCORT",
            giver = "Captain Slayne",
            location = "Isle of Thieves / Antigua",
            prerequisites = "",
            summary = "Follow Slayne through the trees to the Treasure Cave.",
            walkthroughSteps = listOf("Walkthrough. Continue through the jungle and fight any enemies that get in the way.", "Completion. Reach the Treasure Cave entrance."),
            reward = "10 Glory",
            warnings = "",
            searchTags = listOf("The Cave is Not Far Off", "A. SLAYNE'S TREASURE CAVE", "Captain Slayne", "Isle of Thieves / Antigua"),
        ),
        Quest(
            id = "R2-C3-036",
            chapter = 3,
            playOrder = 36,
            title = "Slayne's Treasure",
            category = "MAIN STORY — BETRAYAL",
            giver = "Captain Slayne",
            location = "Isle of Thieves / Antigua",
            prerequisites = "",
            summary = "Go to the back of the Treasure Cave and open Slayne's Chest.",
            walkthroughSteps = listOf("Walkthrough. Enter the cave and proceed to the large chest at the rear. Open it. The expected artefact is not there and Slayne's betrayal sequence triggers.", "Completion. Opening Slayne's Chest completes the quest and starts A Way Out of the Cave.", "Related: A Way Out of the Cave"),
            reward = "100 Glory",
            warnings = "⚠ Important: From this point you are effectively stranded and must escape on foot.",
            searchTags = listOf("Slayne's Treasure", "A. SLAYNE'S TREASURE CAVE", "Captain Slayne", "Isle of Thieves / Antigua"),
        ),
        Quest(
            id = "R2-C3-037",
            chapter = 3,
            playOrder = 37,
            title = "A Way Out of the Cave",
            category = "MAIN STORY — ESCAPE",
            giver = "Trigger quest",
            location = "Isle of Thieves / Antigua",
            prerequisites = "",
            summary = "Find the rear exit and escape the Sunken One-infested beach.",
            walkthroughSteps = listOf("Walkthrough. Work through the cave's alternate exit. On the far side, fight or avoid the Sunken Ones and move along the coast until you are clear of the enclosed beach area. A message in a bottle can also be found on this route and starts The Treasure in the Cave.", "Completion. Leave the beach/cave area.", "Related: Marooned / The Treasure in the Cave"),
            reward = "200 Glory",
            warnings = "",
            searchTags = listOf("A Way Out of the Cave", "A. SLAYNE'S TREASURE CAVE", "Automatic", "Isle of Thieves / Antigua"),
        ),
        Quest(
            id = "R2-C3-038",
            chapter = 3,
            playOrder = 38,
            title = "Marooned",
            category = "MAIN STORY — ESCAPE PARENT",
            giver = "Jaffar",
            location = "Isle of Thieves / Antigua",
            prerequisites = "",
            summary = "Meet Jaffar, build his raft and use it to escape the island.",
            walkthroughSteps = listOf("Walkthrough. Walk west toward the former rowboat location and meet the gnome Jaffar. Ask him for help. Complete Build a Raft, Meet Jaffar on the Western Beach, then speak with him and use the raft.", "Completion. Using Jaffar's raft completes the quest and deposits you on Tacarigua.", "Related: Build a Raft / Meet Jaffar on the Western Beach"),
            reward = "200 Glory",
            warnings = "",
            searchTags = listOf("Marooned", "B. MAROONED & JAFFAR", "Automatic / Jaffar", "Isle of Thieves / Antigua"),
        ),
        Quest(
            id = "R2-C3-039",
            chapter = 3,
            playOrder = 39,
            title = "Build a Raft",
            category = "MAIN STORY — COLLECTION PARENT",
            giver = "Jaffar",
            location = "Isle of Thieves / Antigua",
            prerequisites = "",
            summary = "Collect 10 Driftwood, 5 Vines and 6 Shirts, then give them to Jaffar.",
            walkthroughSteps = listOf("Walkthrough. Agree to Jaffar's plan. Follow him to his cave, then collect all three material groups. Driftwood is mainly on the northwestern beaches; Vines are around the Gnome Village; Shirts come from the village and its three gnome side quests.", "Completion. Give the Driftwood, Vines and Shirts to Jaffar.", "Related: Follow Jaffar into the Jungle / Driftwood / Vines / Shirts"),
            reward = "100 Glory",
            warnings = "",
            searchTags = listOf("Build a Raft", "B. MAROONED & JAFFAR", "Jaffar", "Isle of Thieves / Antigua"),
        ),
        Quest(
            id = "R2-C3-040",
            chapter = 3,
            playOrder = 40,
            title = "Follow Jaffar into the Jungle",
            category = "MAIN STORY — ESCORT",
            giver = "Jaffar",
            location = "Isle of Thieves / Antigua",
            prerequisites = "",
            summary = "Follow Jaffar to his cave.",
            walkthroughSteps = listOf("Walkthrough. Stay with Jaffar as he leads you from the coast into the jungle and toward the gnome settlement.", "Completion. Reach Jaffar's cave."),
            reward = "10 Glory",
            warnings = "",
            searchTags = listOf("Follow Jaffar into the Jungle", "B. MAROONED & JAFFAR", "Jaffar", "Isle of Thieves / Antigua"),
        ),
        Quest(
            id = "R2-C3-041",
            chapter = 3,
            playOrder = 41,
            title = "Driftwood",
            category = "MAIN STORY — COLLECTION",
            giver = "Trigger quest",
            location = "Isle of Thieves / Antigua",
            prerequisites = "",
            summary = "Collect all 10 pieces of Driftwood.",
            walkthroughSteps = listOf("Walkthrough. Search the northwestern beaches of the Isle of Thieves. The Driftwood pieces lie along the shoreline and are easy to miss among wreck debris.", "Completion. The tenth piece completes the quest."),
            reward = "100 Glory",
            warnings = "",
            searchTags = listOf("Driftwood", "B. MAROONED & JAFFAR", "Automatic", "Isle of Thieves / Antigua"),
        ),
        Quest(
            id = "R2-C3-042",
            chapter = 3,
            playOrder = 42,
            title = "Vines",
            category = "MAIN STORY — COLLECTION",
            giver = "Trigger quest",
            location = "Isle of Thieves / Antigua",
            prerequisites = "",
            summary = "Collect all 5 Vines around the Gnome Village.",
            walkthroughSteps = listOf("Walkthrough. Search around gnome huts, garden areas and nearby cave entrances. Several vines are close to quest-giver homes.", "Completion. The fifth Vine completes the quest."),
            reward = "100 Glory",
            warnings = "",
            searchTags = listOf("Vines", "B. MAROONED & JAFFAR", "Automatic", "Isle of Thieves / Antigua"),
        ),
        Quest(
            id = "R2-C3-043",
            chapter = 3,
            playOrder = 43,
            title = "Shirts",
            category = "MAIN STORY — COLLECTION",
            giver = "Trigger quest",
            location = "Isle of Thieves / Antigua",
            prerequisites = "",
            summary = "Collect all 6 Shirts in the Gnome Village.",
            walkthroughSteps = listOf("Walkthrough. Three Shirts come from The Thief Has Been Robbed, one from Lost in Translation and two can be obtained from Ulvi after The Lost Gnome if you ask him for help. Any remaining shirt can be picked up around the settlement as available.", "Completion. Collect all six Shirts.", "Related: The Thief Has Been Robbed / Lost in Translation / The Lost Gnome"),
            reward = "200 Glory",
            warnings = "",
            searchTags = listOf("Shirts", "B. MAROONED & JAFFAR", "Automatic / Gnome Village", "Isle of Thieves / Antigua"),
        ),
        Quest(
            id = "R2-C3-044",
            chapter = 3,
            playOrder = 44,
            title = "The Thief Has Been Robbed",
            category = "GNOME SIDE QUEST / RAFT SUPPORT",
            giver = "Zeki",
            location = "Isle of Thieves / Antigua",
            prerequisites = "",
            summary = "Recover Zeki's Crown from the termite caves northeast of the village.",
            walkthroughSteps = listOf("Walkthrough. Speak with Zeki and offer to help. Enter the termite cave to the northeast and retrieve his Crown from the loot at the end.", "Completion. Return the Crown to Zeki."),
            reward = "100 Glory + 3 Shirts",
            warnings = "⚠ Important: This is the fastest single source of Shirts for Build a Raft.",
            searchTags = listOf("The Thief Has Been Robbed", "C. GNOME VILLAGE QUESTS", "Zeki", "Isle of Thieves / Antigua"),
        ),
        Quest(
            id = "R2-C3-045",
            chapter = 3,
            playOrder = 45,
            title = "Lost in Translation",
            category = "GNOME SIDE QUEST / RAFT SUPPORT",
            giver = "Nuri",
            location = "Isle of Thieves / Antigua",
            prerequisites = "",
            summary = "Learn what a 'dako balla' is and bring Nuri the Pitch-Black Pearl.",
            walkthroughSteps = listOf("Walkthrough. Speak with Nuri, then ask Kaan about his people and the phrase. Complete The Lost Gnome. Ulvi gives you a Feather; trade the Feather back to Ulvi for the Pitch-Black Pearl, then offer the pearl to Nuri.", "Completion. Give Nuri the Pitch-Black Pearl.", "Related: The Lost Gnome"),
            reward = "100 Glory + 1 Shirt",
            warnings = "",
            searchTags = listOf("Lost in Translation", "C. GNOME VILLAGE QUESTS", "Nuri", "Isle of Thieves / Antigua"),
        ),
        Quest(
            id = "R2-C3-046",
            chapter = 3,
            playOrder = 46,
            title = "The Lost Gnome",
            category = "GNOME SIDE QUEST / RAFT SUPPORT",
            giver = "Ulvi",
            location = "Isle of Thieves / Antigua",
            prerequisites = "",
            summary = "Rescue Kalil from the four Threatening Giant Crabs.",
            walkthroughSteps = listOf("Walkthrough. Speak with Ulvi about his missing friend. Travel to the north-central beach and complete Kill the Threatening Giant Crabs. Then speak with Kalil.", "Completion. Kalil is safe; report back to Ulvi.", "Related: Kill the Threatening Giant Crabs"),
            reward = "100 Glory + Feather",
            warnings = "⚠ Important: Afterward, Ulvi can exchange the Feather for the Pitch-Black Pearl and can give two Shirts if asked for help.",
            searchTags = listOf("The Lost Gnome", "C. GNOME VILLAGE QUESTS", "Ulvi", "Isle of Thieves / Antigua"),
        ),
        Quest(
            id = "R2-C3-047",
            chapter = 3,
            playOrder = 47,
            title = "Kill the Threatening Giant Crabs",
            category = "COMBAT",
            giver = "Kalil",
            location = "Isle of Thieves / Antigua",
            prerequisites = "",
            summary = "Kill all four Threatening Giant Crabs.",
            walkthroughSteps = listOf("Walkthrough. Go to the north-central beach. The crabs are clustered around Kalil's route home. Use Kick/ranged attacks to interrupt their defensive stance.", "Completion. The fourth crab completes the quest."),
            reward = "100 Glory + combat Glory",
            warnings = "",
            searchTags = listOf("Kill the Threatening Giant Crabs", "C. GNOME VILLAGE QUESTS", "Automatic / Kalil", "Isle of Thieves / Antigua"),
        ),
        Quest(
            id = "R2-C3-048",
            chapter = 3,
            playOrder = 48,
            title = "The Gnome Eater",
            category = "OPTIONAL — BOSS",
            giver = "Kaan",
            location = "Isle of Thieves / Antigua",
            prerequisites = "",
            summary = "Kill the Granne Gozzo that has been terrorizing the gnomes.",
            walkthroughSteps = listOf("Walkthrough. Speak with Kaan and offer to help. Travel into the valley where the Gnome Eater lives and fight the Granne Gozzo. Be careful: the creature can swallow equipped weapons during the fight; loot its corpse afterward to recover anything swallowed.", "Completion. Return to Kaan after killing it."),
            reward = "200 Glory + 500 Glory kill",
            warnings = "⚠ Important: Kaan rewards you with the Flask after the report.",
            searchTags = listOf("The Gnome Eater", "C. GNOME VILLAGE QUESTS", "Kaan", "Isle of Thieves / Antigua"),
        ),
        Quest(
            id = "R2-C3-049",
            chapter = 3,
            playOrder = 49,
            title = "The Treasure in the Cave",
            category = "OPTIONAL — TREASURE",
            giver = "Message in a Bottle",
            location = "Isle of Thieves / Antigua",
            prerequisites = "",
            summary = "Open the message found while leaving Slayne's cave, then dig up the treasure near the cave's rear entrance.",
            walkthroughSteps = listOf("Walkthrough. Pick up the Message in a Bottle on the beach after leaving the Treasure Cave and open it. Follow the treasure marker to the big red X just inside the back entrance of the cave.", "Completion. Dig up and loot the chest."),
            reward = "100 Glory",
            warnings = "⚠ Important: The treasure contains the legendary item Parrot Wing plus valuables.",
            searchTags = listOf("The Treasure in the Cave", "D. ISLE OF THIEVES TREASURES", "Message in a Bottle", "Isle of Thieves / Antigua"),
        ),
        Quest(
            id = "R2-C3-050",
            chapter = 3,
            playOrder = 50,
            title = "The Treasure in the Valley of the Gnome Eater",
            category = "OPTIONAL — TREASURE",
            giver = "Ulvi",
            location = "Isle of Thieves / Antigua",
            prerequisites = "",
            summary = "Buy Ulvi's map after The Lost Gnome and dig up the treasure in the Gnome Eater valley.",
            walkthroughSteps = listOf("Walkthrough. Complete The Lost Gnome, then buy the treasure map from Ulvi. Go to the south side of the valley and find the red X.", "Completion. Dig up the chest.", "Related: The Treasure in the Sea"),
            reward = "100 Glory",
            warnings = "⚠ Important: The chest also contains another treasure map.",
            searchTags = listOf("The Treasure in the Valley of the Gnome Eater", "D. ISLE OF THIEVES TREASURES", "Ulvi", "Isle of Thieves / Antigua"),
        ),
        Quest(
            id = "R2-C3-051",
            chapter = 3,
            playOrder = 51,
            title = "The Treasure in the Sea",
            category = "OPTIONAL — TREASURE",
            giver = "Treasure Map",
            location = "Isle of Thieves / Antigua",
            prerequisites = "",
            summary = "Use the map from the Gnome Eater treasure and dig up the chest in the dead-end canal on the north coast.",
            walkthroughSteps = listOf("Walkthrough. Take the second map from the previous treasure chest, then travel to the northern coastal canal marked on the map.", "Completion. Dig up the treasure at the red X."),
            reward = "100 Glory",
            warnings = "",
            searchTags = listOf("The Treasure in the Sea", "D. ISLE OF THIEVES TREASURES", "Treasure Map", "Isle of Thieves / Antigua"),
        ),
        Quest(
            id = "R2-C3-052",
            chapter = 3,
            playOrder = 52,
            title = "Meet Jaffar on the Western Beach",
            category = "MAIN STORY — ESCAPE",
            giver = "Jaffar",
            location = "Isle of Thieves / Antigua",
            prerequisites = "",
            summary = "After building the raft, meet Jaffar at the central western beach.",
            walkthroughSteps = listOf("Walkthrough. Once Build a Raft is complete, travel to the western beach where Jaffar has assembled the raft.", "Completion. Approach Jaffar and the raft."),
            reward = "50 Glory",
            warnings = "",
            searchTags = listOf("Meet Jaffar on the Western Beach", "E. ESCAPE THE ISLE", "Jaffar", "Isle of Thieves / Antigua"),
        ),
        Quest(
            id = "R2-C3-053",
            chapter = 3,
            playOrder = 53,
            title = "Where Is My Ship?",
            category = "MAIN STORY",
            giver = "Patty",
            location = "Isle of Thieves / Antigua",
            prerequisites = "",
            summary = "Escape on the raft, arrive on Tacarigua and speak with Patty aboard your ship at the Pirates' Den.",
            walkthroughSteps = listOf("Walkthrough. Talk to Jaffar and use the raft. You wash ashore in the southeast swamp on Tacarigua. Fast travel or make your way back to the Pirates' Den. Your ship is in the harbor.", "Completion. Board the ship and speak with Patty."),
            reward = "200 Glory",
            warnings = "⚠ Important: Jaffar joins your party/crew from this point.",
            searchTags = listOf("Where Is My Ship?", "E. ESCAPE THE ISLE", "Automatic / Patty", "Isle of Thieves / Antigua"),
        ),
        Quest(
            id = "R2-C3-054",
            chapter = 3,
            playOrder = 54,
            title = "Meet Slayne at Blood Oath Square",
            category = "MAIN STORY — SHOWDOWN SETUP",
            giver = "Trigger quest",
            location = "Isle of Thieves / Antigua",
            prerequisites = "",
            summary = "Sail back to Antigua, enter Alvarez's house, then meet Slayne at Blood Oath Square.",
            walkthroughSteps = listOf("Walkthrough. After speaking with Patty on Tacarigua, sail to Antigua. Enter Admiral Alvarez's house to trigger the Slayne confrontation setup. Then go east to the square/park with the stocks.", "Completion. Approach Slayne.", "Related: Showdown with Slayne"),
            reward = "10 Glory",
            warnings = "",
            searchTags = listOf("Meet Slayne at Blood Oath Square", "F. RETURN TO ANTIGUA — SLAYNE", "Automatic", "Isle of Thieves / Antigua"),
        ),
        Quest(
            id = "R2-C3-055",
            chapter = 3,
            playOrder = 55,
            title = "Showdown with Slayne",
            category = "MAIN STORY — BOSS",
            giver = "Slayne",
            location = "Isle of Thieves / Antigua",
            prerequisites = "",
            summary = "Kill Slayne in the duel at Blood Oath Square.",
            walkthroughSteps = listOf("Walkthrough. Prepare before approaching him: heal, reload and equip your preferred weapon. Slayne is essentially a strong pirate duelist rather than a special-mechanics boss. Musket builds can kite; melee builds should interrupt and counter.", "Completion. Kill Slayne and loot his body.", "Related: The Cunning Captain"),
            reward = "200 Glory + 100 Glory kill",
            warnings = "⚠ Important: Loot the Sacrificial Knife from Slayne. The Cunning Captain parent quest completes here.",
            searchTags = listOf("Showdown with Slayne", "F. RETURN TO ANTIGUA — SLAYNE", "Slayne", "Isle of Thieves / Antigua"),
        ),
        Quest(
            id = "R2-C3-056",
            chapter = 3,
            playOrder = 56,
            title = "The Cunning Captain",
            category = "POST-SHIP MAIN STORY / MAIN STORY — PARENT COMPLETION",
            giver = "Patty",
            location = "Sword Coast / Isle of Thieves / Antigua",
            prerequisites = "",
            summary = "Use your new ship and begin the hunt for Captain Slayne.\nFinish Showdown with Slayne.",
            walkthroughSteps = listOf("Chapter 2 — G. CHAPTER 2 EXIT", "Walkthrough. Once A New Ship completes, talk with Patty about the next lead. Your world opens considerably and you can choose among known destinations.", "Completion. The next major objective becomes finding Captain Slayne.", "Related: Find Captain Slayne / Chapter 3", "Chapter 3 — F. RETURN TO ANTIGUA — SLAYNE", "Walkthrough. This parent quest began after the Earth Titan in Chapter 2 and encompasses finding Slayne, equipping his ship, the Isle of Thieves betrayal and the final duel.", "Completion. Killing Slayne completes the parent quest."),
            reward = "1000 Glory",
            warnings = "⚠ Important: Report to Admiral Alvarez afterward to unlock his Swordmaster training.",
            searchTags = listOf("The Cunning Captain", "G. CHAPTER 2 EXIT", "Patty", "Sword Coast", "F. RETURN TO ANTIGUA — SLAYNE", "Main story", "Isle of Thieves / Antigua"),
        ),
    )

    val notes: List<RisenGuideNote> = listOf(
        RisenGuideNote(3, 32, "Part II overview", listOf("This Part begins immediately after The Journey to the Isle of Thieves. Captain Slayne leads you to his Treasure Cave, betrays you, and leaves you stranded. The chapter then becomes a survival/escape sequence built around Jaffar and the Gnome Village. After escaping by raft to Tacarigua, you recover your ship, return to Antigua and settle the score with Slayne.", "Long-term quest note: Jaffar's Auri Culci starts on the Isle of Thieves but cannot be completed in this Part. Its final objective requires Kill Mara and Steelbeard's Hat, so keep it active.")),
        RisenGuideNote(3, 32, "A. SLAYNE'S TREASURE CAVE", listOf()),
        RisenGuideNote(3, 38, "B. MAROONED & JAFFAR", listOf()),
        RisenGuideNote(3, 44, "C. GNOME VILLAGE QUESTS", listOf()),
        RisenGuideNote(3, 49, "D. ISLE OF THIEVES TREASURES", listOf()),
        RisenGuideNote(3, 52, "Jaffar's Auri Culci — continued quest guidance", listOf("Quick solution: Keep this quest active; it finishes only after Mara is dead and you can give Jaffar Steelbeard's Hat.", "Walkthrough. Speak with Jaffar and Kaan about gnome customs and Jaffar's ambitions. The actual final completion condition is far later in the story.", "Completion. Do not attempt to force completion in Chapter 3 Part II.", "⚠ Important: This quest requires Kill Mara and Steelbeard's Hat, so it intentionally remains open.", "Quest giver: Jaffar", "Status: LONG-TERM — DO NOT EXPECT TO FINISH NOW", "Area: Isle of Thieves / Antigua", "Reward: 200 Glory eventually")),
        RisenGuideNote(3, 52, "E. ESCAPE THE ISLE", listOf()),
        RisenGuideNote(3, 54, "F. RETURN TO ANTIGUA — SLAYNE", listOf()),
        RisenGuideNote(3, 57, "PART II COMPLETION CHECKLIST", listOf("Treasure Cave and all three Slayne escort entries are complete.", "Slayne's Treasure and A Way Out of the Cave are complete.", "Marooned is active/completed through Jaffar's raft.", "All 10 Driftwood and 5 Vines were collected.", "All 6 Shirts were collected.", "The Thief Has Been Robbed, Lost in Translation and The Lost Gnome were completed.", "The Gnome Eater was completed if desired.", "All three Isle of Thieves treasure quests were completed if desired.", "Jaffar's Auri Culci remains active intentionally.", "The raft was built and Jaffar was met on the western beach.", "Where Is My Ship? was completed on Tacarigua.", "Meet Slayne at Blood Oath Square was completed.", "Slayne was killed and his Sacrificial Knife looted.", "The Cunning Captain is complete.")),
        RisenGuideNote(3, 57, "CHAPTER 3 BOUNDARY NOTE", listOf("Defeating Slayne does NOT end all Chapter 3 content. Risen 2's Chapter 3 remains the broad open-seas chapter and also contains the Isle of the Dead, Maracai Bay, Garcia, Steelbeard's Artefact and related questlines. For app clarity, those should be handled in the next Part rather than incorrectly calling this Chapter 4.")),
    )
}
