package com.sliverzfx.gothicquest

internal object RisenGuidePart2Data {
    val quests: List<Quest> = listOf(
        Quest(
            id = "R1-C1-017",
            chapter = 1,
            playOrder = 17,
            title = "Gold fever",
            category = "SAFE — MAIN CAMP CHAIN",
            giver = "Rachel",
            location = "Bandit Camp / swamp",
            prerequisites = "Ask Rachel at the Bandit Camp about why the Don's gold operation is breaking down; complete the linked workers, hunters and power-struggle objectives.",
            summary = "Restore order in the Bandit Camp by resolving the workers, hunters, and power-struggle quest lines, then report to Rachel.",
            walkthroughSteps = listOf("Start. Speak to Rachel about the disorder in the camp; Gold Fever is the overarching quest rather than a direct conversation with Don Esteban.", "Complete the linked quest lines: The workers are to work again, The hunters are to go hunt, and Power struggle. Their individual objectives involve the diggers, hunters, and Brogar.", "Completion. Once these lines are resolved, return to Rachel and report that order has been restored."),
            reward = "200 XP and 100 gold from Rachel after reporting the restored hunters and workers",
            warnings = "⚠ Important: Do not attack named Bandits simply because they are unpleasant. Several are connected to overlapping quests.",
            searchTags = listOf("Gold fever", "Don Esteban / camp progression", "Bandit Camp / swamp", "SAFE — MAIN CAMP CHAIN", "Brogar / workers / diggers", "A. ENTERING THE CAMP & THE DON'S MAIN PROBLEM"),
        ),
        Quest(
            id = "R1-C1-018",
            chapter = 1,
            playOrder = 18,
            title = "Beer for the gang",
            category = "SAFE — DELIVERY",
            giver = "Rhobart",
            location = "Bandit Camp / swamp",
            prerequisites = "Speak with Rhobart at the Bandit Camp swamp and agree to deliver his ten bottles of beer to Rachel.",
            summary = "Take ten bottles of beer from Rhobart to Rachel, collect payment, and settle up with Rhobart.",
            walkthroughSteps = listOf("Start. Speak with Rhobart at the swamp farm and agree to deliver ten bottles of beer to Rachel in the central camp.", "Delivery. Hand all ten beers to Rachel. You can negotiate 50 or 100 gold, or decline payment; the quest's XP does not depend on which payment option you pick.", "Completion. Return to Rhobart and resolve the 50-gold payment. The delivery awards 200 XP, and reporting back awards another 100 XP."),
            reward = "200 XP for delivering the beer; 100 XP when reporting back to Rhobart; gold depends on dialogue choice",
            warnings = "",
            searchTags = listOf("Beer for the gang", "Rhobart", "Rachel", "ten beer", "Bandit Camp", "delivery"),
        ),
        Quest(
            id = "R1-C1-019",
            chapter = 1,
            playOrder = 19,
            title = "The workers are to work again",
            category = "SAFE — WORKER CHAIN",
            giver = "Hawkins",
            location = "Bandit Camp / swamp",
            prerequisites = "Meet Hawkins at the Bandit Camp and investigate why Dwight, Branon and the other diggers are not working.",
            summary = "Return the reluctant Bandit Camp diggers to work by solving their individual problems.",
            walkthroughSteps = listOf("Talk to Hawkins about the idle workers and ask who has stopped digging.", "Get Dwight back to work by challenging his excuses or using Hawkins's authority. Help Branon by dealing with the insects at the digging site and convincing him to resume.", "Check in with Hawkins and Rachel as appropriate; this contributes to the Gold Fever camp-wide objective."),
            reward = "Individual worker and dialogue XP; exact combined payout varies with subquests",
            warnings = "⚠ Important: This chain is best completed before the final Brogar confrontation because his influence is part of the workers' problem.",
            searchTags = listOf("The workers are to keep working", "Sam / Don's work chain", "Bandit Camp / swamp", "SAFE — WORKER CHAIN", "Gold fever / Brogar", "B. THE SWAMP WORKERS"),
        ),
        Quest(
            id = "R1-C1-020",
            chapter = 1,
            playOrder = 20,
            title = "Dwight is to get back to work",
            category = "SAFE — WORKER SUBQUEST",
            giver = "Dwight / Hawkins",
            location = "Bandit Camp / swamp",
            prerequisites = "Talk to Hawkins about inactive diggers; find Dwight at the Bandit Camp.",
            summary = "Convince Dwight to resume his digging duties.",
            walkthroughSteps = listOf("Speak with Dwight and ask why he is not working.", "Insist that he return, press him with Hawkins's instructions, or use the payment/dialogue alternative.", "Finish by getting Dwight to resume work; this advances the larger workers quest."),
            reward = "200 XP",
            warnings = "",
            searchTags = listOf("The lazy worker", "Worker-chain NPC", "Bandit Camp / swamp", "SAFE — WORKER SUBQUEST", "The workers are to keep working", "B. THE SWAMP WORKERS"),
        ),
        Quest(
            id = "R1-C1-021",
            chapter = 1,
            playOrder = 21,
            title = "Protection money in the Bandit Camp",
            category = "CHOICE — BROGAR CHAIN",
            giver = "Brogar",
            location = "Bandit Camp / swamp",
            prerequisites = "Find Dorgan's list from his corpse in the swamp and discuss the scheme with Brogar.",
            summary = "Collect Brogar's protection money from the camp's workers; decide whether to pay him or keep it and undermine him.",
            walkthroughSteps = listOf("Find the dead Dorgan in the cave by Luis and take the collection list; discuss it with Brogar to unlock the collection task.", "Collect payments from the listed workers and traders, including Rhobart, Obel, Luis, Hawkins, Enrico, Dwight, Doug, Branon and Oscar. You may receive small experience rewards from individual conversations.", "For Brogar's route, hand over the proceeds. To challenge his authority, keep them and continue Sam's Power Struggle quest; reporting him to Don Esteban is an additional outcome."),
            reward = "250 XP; gold and follow-up XP depend on Brogar / Don Esteban outcome",
            warnings = "Faction-camp decision: paying Brogar can interfere with the alternative Power Struggle outcome. Save before the final hand-in.",
            searchTags = listOf("Protection money", "Brogar", "Bandit Camp / swamp", "CHOICE — BROGAR CHAIN", "Brogar's arena progression / worker chain", "C. BROGAR'S PROTECTION RACKET"),
        ),
        Quest(
            id = "R1-C1-022",
            chapter = 1,
            playOrder = 22,
            title = "The best fighter in the Bandit Camp",
            category = "SAFE — ARENA HUB",
            giver = "Craig",
            location = "Bandit Camp / swamp",
            prerequisites = "Speak to Craig about arena matches at the Bandit Camp.",
            summary = "Beat Ricardo, Lorenzo, Craig and Domingo in the arena to prove your fighting ability.",
            walkthroughSteps = listOf("Speak to Craig about the arena and its wager system.", "Defeat Ricardo, Lorenzo, Craig and Domingo in their individual bouts; settle any wagers before the next fight.", "Report your victories and complete Craig's fighter challenge. Brogar is a separate, later arena opponent."),
            reward = "200 XP; separate arena wins and optional wagers award additional XP / gold",
            warnings = "⚠ Important: Never finish a downed arena opponent. Killing a named Bandit can break other quests.",
            searchTags = listOf("The fighters in the bandit camp", "Craig / arena chain", "Bandit Camp / swamp", "SAFE — ARENA HUB", "Individual arena fights", "C. BROGAR'S PROTECTION RACKET"),
        ),
        Quest(
            id = "R1-C1-023",
            chapter = 1,
            playOrder = 23,
            title = "Defeat Ricardo in the arena",
            category = "SAFE — ARENA",
            giver = "Ricardo",
            location = "Bandit Camp / swamp",
            prerequisites = "Start. Speak with Ricardo when his challenge becomes available through the arena chain.",
            summary = "Challenge Ricardo and knock him unconscious in the Bandit Camp arena.",
            walkthroughSteps = listOf("Start. Speak with Ricardo when his challenge becomes available through the arena chain.", "Walkthrough. Keep your distance until he commits to an attack, block or sidestep, then counter. Stay within the arena. Once he drops, sheath your weapon and wait for him to recover.", "Finish. Speak with Ricardo after the fight and continue the arena chain.", "Related quests: The fighters in the bandit camp"),
            reward = "100 XP plus 50 XP follow-up; optional wager winnings",
            warnings = "",
            searchTags = listOf("Defeat Ricardo in the arena", "Ricardo", "Bandit Camp / swamp", "SAFE — ARENA", "The fighters in the bandit camp", "C. BROGAR'S PROTECTION RACKET"),
        ),
        Quest(
            id = "R1-C1-024",
            chapter = 1,
            playOrder = 24,
            title = "Defeat Lorenzo in the arena",
            category = "SAFE — ARENA",
            giver = "Lorenzo",
            location = "Bandit Camp / swamp",
            prerequisites = "Start. Progress through the earlier camp/arena conversations until Lorenzo can be challenged.",
            summary = "Accept Lorenzo's arena fight and defeat him without killing him.",
            walkthroughSteps = listOf("Start. Progress through the earlier camp/arena conversations until Lorenzo can be challenged.", "Walkthrough. Use the same non-lethal arena rules. If your character is weak, finish worker and swamp quests first and return with better equipment.", "Finish. Talk to Lorenzo after the knockout.", "Related quests: The fighters in the bandit camp"),
            reward = "100 XP plus 80 XP follow-up; optional wager winnings",
            warnings = "",
            searchTags = listOf("Defeat Lorenzo in the arena", "Lorenzo", "Bandit Camp / swamp", "SAFE — ARENA", "The fighters in the bandit camp", "C. BROGAR'S PROTECTION RACKET"),
        ),
        Quest(
            id = "R1-C1-025",
            chapter = 1,
            playOrder = 25,
            title = "Defeat Brogar in the arena",
            category = "SAFE — ARENA / STORY",
            giver = "Brogar",
            location = "Bandit Camp / swamp",
            prerequisites = "Challenge Brogar after becoming involved in the Bandit Camp arena and his power struggle.",
            summary = "Qualify to challenge Brogar, then beat him in the arena without killing him.",
            walkthroughSteps = listOf("Start. Complete the preceding arena fights and Brogar-related conversations first.", "Walkthrough. Brogar is the important fight in this chain. Block his combinations and punish the recovery rather than trading blows. When he falls, do not execute him. His post-fight dialogue and the reactions of other Bandits matter to the surrounding investigation.", "Finish. Speak with Brogar and re-check the relevant camp NPCs after the victory.", "Related quests: Protection money / arena hub"),
            reward = "300 XP plus 100 XP follow-up; optional wager winnings",
            warnings = "⚠ Important: Do this after harvesting Brogar's available quests, not immediately upon meeting him.",
            searchTags = listOf("Defeat Brogar in the arena", "Brogar", "Bandit Camp / swamp", "SAFE — ARENA / STORY", "Protection money / arena hub", "C. BROGAR'S PROTECTION RACKET"),
        ),
        Quest(
            id = "R1-C1-026",
            chapter = 1,
            playOrder = 26,
            title = "Go hunting with Doug",
            category = "SAFE — HUNT",
            giver = "Doug",
            location = "Bandit Camp / swamp",
            prerequisites = "Talk to Doug at the southern swamp entrance and agree to accompany him on the hunt.",
            summary = "Accompany Doug into the swamp and defeat the dangerous Rotworm.",
            walkthroughSteps = listOf("Speak to Doug at the swamp entrance and ask him about hunting.", "Follow Doug toward the nearby Rotworm. Help him kill it, using distance and avoiding its strong melee attacks.", "Speak to Doug for the promised meat and conclude the hunting job."),
            reward = "200 XP; 30 gold; five raw meat",
            warnings = "",
            searchTags = listOf("Hungry wolves", "Doug / camp hunter", "Bandit Camp / swamp", "SAFE — HUNT", "Camp worker progression", "D. HUNTING & SWAMP-SIDE QUESTS"),
        ),
        Quest(
            id = "R1-C1-027",
            chapter = 1,
            playOrder = 27,
            title = "Dangerous prey",
            category = "SAFE — HUNT",
            giver = "Doug / automatic hunt objective",
            location = "Bandit Camp / swamp",
            prerequisites = "Start Doug's swamp hunting trip and encounter the Rotworm.",
            summary = "Kill the dangerous Rotworm threatening Doug's hunting grounds.",
            walkthroughSteps = listOf("Travel with Doug into the swamp on his hunting quest.", "Defeat the Rotworm; it is the objective of the Dangerous Prey subquest, not a boar hunt.", "Return to Doug to finish any remaining dialogue and the companion hunting quest."),
            reward = "150 XP plus 100 XP follow-up",
            warnings = "",
            searchTags = listOf("Dangerous boars", "Camp hunter / worker", "Bandit Camp / swamp", "SAFE — HUNT", "Camp hunting", "D. HUNTING & SWAMP-SIDE QUESTS"),
        ),
        Quest(
            id = "R1-C1-028",
            chapter = 1,
            playOrder = 28,
            title = "A package for the Don",
            category = "SAFE UNTIL CITY CHOICE — CROSS-REGION",
            giver = "Scordo",
            location = "Bandit Camp / swamp",
            prerequisites = "Meet Scordo in the secret storeroom behind the brothel and accept a package to deliver to Don Esteban.",
            summary = "Carry Scordo's sealed package from Harbour Town to Don Esteban in the Bandit Camp.",
            walkthroughSteps = listOf("Enter Harbour Town and find Scordo behind the secret painting in the brothel.", "Accept Scordo's package and leave the city through the available gate or sewers.", "Return to Don Esteban in the swamp camp and give him the package to complete the delivery."),
            reward = "300 XP",
            warnings = "⚠ Important: Do not use this cross-region quest as an excuse to pick a faction early; Harbour Town contains the decisive influence quests.",
            searchTags = listOf("A package for the Don", "Don/Bandit network", "Bandit Camp / swamp", "SAFE UNTIL CITY CHOICE — CROSS-REGION", "Harbour Town faction quests", "E. THE DON & HARBOUR TOWN CONNECTION"),
        ),
    )

    val notes: List<RisenGuideNote> = listOf(
        RisenGuideNote(1, 17, "Bandit Camp faction advice", listOf("Recommended rule: Complete the camp's internal quest chains before committing to the Don through Harbour Town. Visiting the Bandit Camp and helping its residents does not by itself force the final faction choice.")),
        RisenGuideNote(1, 17, "A. ENTERING THE CAMP & THE DON'S MAIN PROBLEM", listOf()),
        RisenGuideNote(1, 18, "B. THE SWAMP WORKERS", listOf()),
        RisenGuideNote(1, 21, "C. BROGAR'S PROTECTION RACKET", listOf()),
        RisenGuideNote(1, 26, "D. HUNTING & SWAMP-SIDE QUESTS", listOf()),
        RisenGuideNote(1, 28, "E. THE DON & HARBOUR TOWN CONNECTION", listOf()),
        RisenGuideNote(1, 29, "F. CAMP CLEANUP — GUIDE CHECKPOINT (NOT A QUEST)", listOf("Before leaving the swamp, make one final circuit from the low work sites to the arena and then Don Esteban. This is guide advice, not a journal quest. Revisit Rachel, the workers, the hunters, arena opponents, Brogar and the Don. Risen frequently unlocks follow-up dialogue only after another NPC's quest changes state.")),
        RisenGuideNote(1, 29, "FACTION-SAFE EXIT CHECKLIST", listOf("Don Esteban has been met and Gold fever has been advanced as far as the current chapter allows.", "Rachel's worker/delivery content is complete.", "The workers' problems have been resolved before closing Brogar's chain.", "Protection-money conversations have been exhausted.", "Available arena opponents have been defeated non-lethally.", "Brogar remains alive unless a verified later quest explicitly requires otherwise.", "Available hunting/swamp jobs are complete.", "Unique Don/Bandit documents and packages are still in inventory if their destination is Harbour Town.", "No Harbour Town faction victory has yet been finalized.")),
    )
}
