package com.sliverzfx.gothicquest

/** Standalone neutral Harbour Town journal quests absent from the original condensed guide. */
internal object RisenGuidePart10Data {
    val quests: List<Quest> = listOf(
        Quest(
            id = "R1-C1-117",
            chapter = 1,
            playOrder = 117,
            title = "Philus Wants to Sell His Fish Shop",
            category = "HARBOUR TOWN — NEUTRAL SIDE QUEST",
            giver = "Philus",
            location = "Harbour Town",
            prerequisites = "Talk to Philus near the eastern city approach about his failing fish shop.",
            summary = "Ask Philus how much he wants for the business.",
            walkthroughSteps = listOf("Start. Talk to Philus near the eastern city approach about his failing fish shop.", "Walkthrough. Ask Philus how much he wants for the business.", "Completion. Find a buyer in the tavern or negotiate the sale, then return to Philus."),
            reward = "Quest dialogue XP; exact payment depends on the buyer",
            warnings = "",
            searchTags = listOf("Philus Wants to Sell His Fish Shop", "Philus", "Harbour Town", "Chapter 1"),
        ),
        Quest(
            id = "R1-C1-118",
            chapter = 1,
            playOrder = 118,
            title = "The Farmer's Sick Wife",
            category = "HARBOUR TOWN — NEUTRAL SIDE QUEST",
            giver = "Arno",
            location = "Harbour Town",
            prerequisites = "During Medicine for Everyone, give Arno the medicine for Martha and learn that she needs a bed.",
            summary = "Ask Arno about a better place for Martha to recover.",
            walkthroughSteps = listOf("Start. During Medicine for Everyone, give Arno the medicine for Martha and learn that she needs a bed.", "Walkthrough. Ask Arno about a better place for Martha to recover.", "Completion. Arrange a bed in Costa's establishment and return to Arno and Belschwur."),
            reward = "250 XP for helping Arno and Martha; 25 XP and two large healing potions from Belschwur; alternate lodging rewards vary",
            warnings = "",
            searchTags = listOf("The Farmer's Sick Wife", "Arno", "Harbour Town", "Chapter 1"),
        ),
        Quest(
            id = "R1-C1-119",
            chapter = 1,
            playOrder = 119,
            title = "Cole Has His Bow Back",
            category = "HARBOUR TOWN — NEUTRAL SIDE QUEST",
            giver = "Cole",
            location = "Harbour Town",
            prerequisites = "Speak with Cole after meeting him in the harbour chapel.",
            summary = "Learn that Costa has taken Cole's bow.",
            walkthroughSteps = listOf("Start. Speak with Cole after meeting him in the harbour chapel.", "Walkthrough. Learn that Costa has taken Cole's bow.", "Completion. Buy the bow back from Costa for 350 gold and return it to Cole."),
            reward = "200 XP",
            warnings = "",
            searchTags = listOf("Cole Has His Bow Back", "Cole", "Harbour Town", "Chapter 1"),
        ),
        Quest(
            id = "R1-C1-120",
            chapter = 1,
            playOrder = 120,
            title = "Talk to the Commandant in Harbour Town",
            category = "HARBOUR TOWN — NEUTRAL SIDE QUEST",
            giver = "Warrior of the Order / Carlos",
            location = "Harbour Town",
            prerequisites = "Complete Belschwur's Medicine for Everyone task and speak to a patrolling Order warrior.",
            summary = "Obtain directions to Commandant Carlos's fortress.",
            walkthroughSteps = listOf("Start. Complete Belschwur's Medicine for Everyone task and speak to a patrolling Order warrior.", "Walkthrough. Obtain directions to Commandant Carlos's fortress.", "Completion. Visit Carlos and discuss his investigation and the two factions."),
            reward = "100 XP",
            warnings = "",
            searchTags = listOf("Talk to the Commandant in Harbour Town", "Warrior of the Order / Carlos", "Harbour Town", "Chapter 1"),
        ),
        Quest(
            id = "R1-C1-121",
            chapter = 1,
            playOrder = 121,
            title = "The Map of the Island",
            category = "HARBOUR TOWN — NEUTRAL SIDE QUEST",
            giver = "Nelson",
            location = "Harbour Town",
            prerequisites = "Talk to Nelson the cartographer in Harbour Town and learn that he can prepare the island map once the secret exit is discovered.",
            summary = "Ask about purchasing the island map and the information it provides.",
            walkthroughSteps = listOf("Start. Find Nelson the cartographer during the first Harbour Town visit.", "Walkthrough. Ask about purchasing the island map and the information it provides.", "Completion. Purchase or obtain Nelson's island map to complete the related objective."),
            reward = "100 XP; purchase the island map for 250 gold",
            warnings = "",
            searchTags = listOf("The Map of the Island", "Nelson", "Harbour Town", "Chapter 1"),
        ),
        Quest(
            id = "R1-C1-122",
            chapter = 1,
            playOrder = 122,
            title = "Walter Needs a Break",
            category = "HARBOUR TOWN — NEUTRAL SIDE QUEST",
            giver = "Walter",
            location = "Harbour Town",
            prerequisites = "Speak with Walter at the Harbour Town forge about why he cannot take further commissions.",
            summary = "Speak with Alvaro at the nearby smithy shop.",
            walkthroughSteps = listOf("Start. Speak with Walter at the Harbour Town forge about why he cannot take further commissions.", "Walkthrough. Speak with Alvaro at the nearby smithy shop.", "Completion. Arrange for two helpers to cover Walter's workload, then return to Walter."),
            reward = "100 XP and a favour from Walter",
            warnings = "",
            searchTags = listOf("Walter Needs a Break", "Walter", "Harbour Town", "Chapter 1"),
        ),
        Quest(
            id = "R1-C1-123",
            chapter = 1,
            playOrder = 123,
            title = "Send the Servants Home",
            category = "HARBOUR TOWN — NEUTRAL SIDE QUEST",
            giver = "Alvaro",
            location = "Harbour Town",
            prerequisites = "Accept Walter Needs a Break and ask Alvaro for additional smithy help.",
            summary = "Receive 120 gold from Alvaro and find two apprentices around town.",
            walkthroughSteps = listOf("Start. Accept Walter Needs a Break and ask Alvaro for additional smithy help.", "Walkthrough. Receive 120 gold from Alvaro and find two apprentices around town.", "Completion. Pay each apprentice 50 gold, then report back to Alvaro."),
            reward = "50 XP for hiring both, 50 XP from Alvaro and remaining 20 gold",
            warnings = "",
            searchTags = listOf("Send the Servants Home", "Alvaro", "Harbour Town", "Chapter 1"),
        ),
        Quest(
            id = "R1-C1-124",
            chapter = 1,
            playOrder = 124,
            title = "Jack Is in Need of Rum",
            category = "HARBOUR TOWN — NEUTRAL SIDE QUEST",
            giver = "Jack",
            location = "Harbour Town",
            prerequisites = "Talk to Jack at the lighthouse in Harbour Town.",
            summary = "Acquire one bottle of rum from a trader or your inventory.",
            walkthroughSteps = listOf("Start. Talk to Jack at the lighthouse in Harbour Town.", "Walkthrough. Acquire one bottle of rum from a trader or your inventory.", "Completion. Hand the rum to Jack at the lighthouse."),
            reward = "50 XP",
            warnings = "",
            searchTags = listOf("Jack Is in Need of Rum", "Jack", "Harbour Town", "Chapter 1"),
        ),
        Quest(
            id = "R1-C1-125",
            chapter = 1,
            playOrder = 125,
            title = "Jack's Chest",
            category = "HARBOUR TOWN — NEUTRAL SIDE QUEST",
            giver = "Jack / exploration",
            location = "Harbour Town",
            prerequisites = "Explore Jack's lighthouse and find his locked chest upstairs.",
            summary = "Look behind the barrels at ground level for the hidden chest key.",
            walkthroughSteps = listOf("Start. Explore Jack's lighthouse and find his locked chest upstairs.", "Walkthrough. Look behind the barrels at ground level for the hidden chest key.", "Completion. Unlock the upper chest and collect its contents, including a piercing-resistance ring."),
            reward = "100 XP and contents of the chest",
            warnings = "",
            searchTags = listOf("Jack's Chest", "Jack / exploration", "Harbour Town", "Chapter 1"),
        ),
        Quest(
            id = "R1-C1-126",
            chapter = 1,
            playOrder = 126,
            title = "A Night with Olga",
            category = "HARBOUR TOWN — NEUTRAL SIDE QUEST",
            giver = "Sonya",
            location = "Harbour Town",
            prerequisites = "Speak to Sonya in the Harbour Town brothel.",
            summary = "Arrange a visit with Olga by paying Sonya the required 50 gold.",
            walkthroughSteps = listOf("Start. Speak to Sonya in the Harbour Town brothel.", "Walkthrough. Arrange a visit with Olga by paying Sonya the required 50 gold.", "Completion. Speak with Olga and finish the interaction."),
            reward = "100 XP and a Tell Joke scroll",
            warnings = "",
            searchTags = listOf("A Night with Olga", "Sonya", "Harbour Town", "Chapter 1"),
        ),
        Quest(
            id = "R1-C1-127",
            chapter = 1,
            playOrder = 127,
            title = "The Violent One",
            category = "HARBOUR TOWN — NEUTRAL SIDE QUEST",
            giver = "Gwen",
            location = "Harbour Town",
            prerequisites = "Speak with Gwen in the Harbour Town brothel about Erikson's abusive behaviour.",
            summary = "Ask Erikson about how he treated Gwen and challenge him.",
            walkthroughSteps = listOf("Start. Speak with Gwen in the Harbour Town brothel about Erikson's abusive behaviour.", "Walkthrough. Ask Erikson about how he treated Gwen and challenge him.", "Completion. Defeat Erikson and report to Gwen, then optionally report to Sonya."),
            reward = "100 XP from Gwen; 25 XP and 50 gold from Sonya",
            warnings = "",
            searchTags = listOf("The Violent One", "Gwen", "Harbour Town", "Chapter 1"),
        ),
        Quest(
            id = "R1-C1-128",
            chapter = 1,
            playOrder = 128,
            title = "Defeat Erikson",
            category = "HARBOUR TOWN — NEUTRAL SIDE QUEST",
            giver = "Erikson",
            location = "Harbour Town",
            prerequisites = "After Gwen explains the situation, confront Erikson in the Harbour Town brothel.",
            summary = "Provoke Erikson into accepting the fight.",
            walkthroughSteps = listOf("Start. After Gwen explains the situation, confront Erikson in the Harbour Town brothel.", "Walkthrough. Provoke Erikson into accepting the fight.", "Completion. Knock him unconscious and report to Gwen."),
            reward = "50 quest XP plus 80 XP for the knockdown",
            warnings = "",
            searchTags = listOf("Defeat Erikson", "Erikson", "Harbour Town", "Chapter 1"),
        ),
        Quest(
            id = "R1-C1-129",
            chapter = 1,
            playOrder = 129,
            title = "Anything That Heals",
            category = "HARBOUR TOWN — NEUTRAL SIDE QUEST",
            giver = "Leonardo",
            location = "Harbour Town",
            prerequisites = "Speak with Leonardo, the Harbour Town alchemist, about gathering plants.",
            summary = "Collect 10 healing herbs, 5 healing plants and 2 healing roots.",
            walkthroughSteps = listOf("Start. Speak with Leonardo, the Harbour Town alchemist, about gathering plants.", "Walkthrough. Collect 10 healing herbs, 5 healing plants and 2 healing roots.", "Completion. Give all the requested ingredients to Leonardo."),
            reward = "300 XP and a permanent +10 maximum-health potion",
            warnings = "",
            searchTags = listOf("Anything That Heals", "Leonardo", "Harbour Town", "Chapter 1"),
        ),
        Quest(
            id = "R1-C1-130",
            chapter = 1,
            playOrder = 130,
            title = "Everything That Isn't Nailed Down",
            category = "HARBOUR TOWN — NEUTRAL SIDE QUEST",
            giver = "Walter",
            location = "Harbour Town",
            prerequisites = "Ask Walter at the Harbour Town forge about scarce scrap and gnome thefts.",
            summary = "Collect 15 tool bags from gnomes at abandoned farms and camps.",
            walkthroughSteps = listOf("Start. Ask Walter at the Harbour Town forge about scarce scrap and gnome thefts.", "Walkthrough. Collect 15 tool bags from gnomes at abandoned farms and camps.", "Completion. Deliver the 15 bags to Walter."),
            reward = "500 XP, 300 gold and three sword-steel blanks",
            warnings = "",
            searchTags = listOf("Everything That Isn't Nailed Down", "Walter", "Harbour Town", "Chapter 1"),
        ),
        Quest(
            id = "R1-C1-131",
            chapter = 1,
            playOrder = 131,
            title = "Nelson's Ring",
            category = "HARBOUR TOWN — NEUTRAL SIDE QUEST",
            giver = "Nelson",
            location = "Harbour Town",
            prerequisites = "Speak with Nelson about his missing ring.",
            summary = "Find Kayleigh wearing the ring at Cid's home; offer to exchange a pearl necklace.",
            walkthroughSteps = listOf("Start. Speak with Nelson about his missing ring.", "Walkthrough. Find Kayleigh wearing the ring at Cid's home; offer to exchange a pearl necklace.", "Completion. Return the ring to Nelson. He lets you keep the acrobatics ring."),
            reward = "150 XP and the acrobatics ring",
            warnings = "",
            searchTags = listOf("Nelson's Ring", "Nelson", "Harbour Town", "Chapter 1"),
        ),
        Quest(
            id = "R1-C1-132",
            chapter = 1,
            playOrder = 132,
            title = "Pearls for a Lady",
            category = "HARBOUR TOWN — NEUTRAL SIDE QUEST",
            giver = "Kayleigh",
            location = "Harbour Town",
            prerequisites = "Discover that Kayleigh owns Nelson's missing ring.",
            summary = "Obtain a pearl necklace, such as the one at Tristan's farm.",
            walkthroughSteps = listOf("Start. Discover that Kayleigh owns Nelson's missing ring.", "Walkthrough. Obtain a pearl necklace, such as the one at Tristan's farm.", "Completion. Exchange the necklace with Kayleigh for Nelson's ring."),
            reward = "50 XP and Nelson's ring",
            warnings = "",
            searchTags = listOf("Pearls for a Lady", "Kayleigh", "Harbour Town", "Chapter 1"),
        ),
        Quest(
            id = "R1-C1-133",
            chapter = 1,
            playOrder = 133,
            title = "Get Marek's Cell Key",
            category = "HARBOUR TOWN — NEUTRAL SIDE QUEST",
            giver = "Marek",
            location = "Harbour Town",
            prerequisites = "Find Marek guarding Romanov's cell near the harbour prison.",
            summary = "Choose a nonlethal route to acquire the cell key: bribe Marek, defeat him, or arrange an escort for him.",
            walkthroughSteps = listOf("Start. Find Marek guarding Romanov's cell near the harbour prison.", "Walkthrough. Choose a nonlethal route to acquire the cell key: bribe Marek, defeat him, or arrange an escort for him.", "Completion. Unlock the prison cell and speak to Romanov."),
            reward = "150 XP",
            warnings = "",
            searchTags = listOf("Get Marek's Cell Key", "Marek", "Harbour Town", "Chapter 1"),
        ),
        Quest(
            id = "R1-C1-134",
            chapter = 1,
            playOrder = 134,
            title = "Distraction for the Prison Guard",
            category = "HARBOUR TOWN — NEUTRAL SIDE QUEST",
            giver = "Marek / Sonya",
            location = "Harbour Town",
            prerequisites = "Ask Marek about admission to Romanov's cell and offer to arrange company.",
            summary = "Pay Sonya 50 gold and arrange for Anika to visit Marek.",
            walkthroughSteps = listOf("Start. Ask Marek about admission to Romanov's cell and offer to arrange company.", "Walkthrough. Pay Sonya 50 gold and arrange for Anika to visit Marek.", "Completion. Tell Anika about the arrangement, then return to Marek for the key."),
            reward = "200 XP plus 25 XP for arranging the visit",
            warnings = "",
            searchTags = listOf("Distraction for the Prison Guard", "Marek / Sonya", "Harbour Town", "Chapter 1"),
        )
    )
}
