package com.sliverzfx.gothicquest

internal object Risen3Chapter1Data {
    val quests: List<Quest> = listOf(
        Quest(
            id = "R3-C1-001",
            chapter = 1,
            playOrder = 1,
            title = "Ready for the Island",
            aliases = listOf(),
            category = "TUTORIAL — MAIN STORY",
            giver = "Automatic / Patty",
            location = "Crab Coast",
            prerequisites = "",
            summary = "Survive the ship battle, wake aboard your own ship, loot your cabin and use the rowboat to sail to the Crab Coast.",
            walkthroughSteps = listOf("Walkthrough. Follow the combat prompts during the opening attack: dodge, draw your weapon, parry and use the pistol when instructed. Help Patty clear the enemy ship and defeat the stronger Shadow creature. After the vision ends, wake in your cabin. Take the key from the table, open the chest and equip your gear. Go on deck, use the rowboat and choose the Crab Coast.", "Completion. Arriving on the Crab Coast completes the tutorial quest."),
            reward = "100 Glory",
            warnings = "",
            searchTags = listOf("Crab Coast", "A. SHIPBOARD PROLOGUE"),
        ),
        Quest(
            id = "R3-C1-002",
            chapter = 1,
            playOrder = 2,
            title = "Hunting for Treasure",
            aliases = listOf(),
            category = "TUTORIAL — MAIN STORY",
            giver = "Patty",
            location = "Crab Coast",
            prerequisites = "",
            summary = "Follow Patty through the Crab Coast, investigate the pirate trail, enter the ancient temple and reach the Crystal Portal.",
            walkthroughSteps = listOf("Walkthrough. From the landing beach, follow Patty inland. Kill the giant rats, investigate the pirate corpse when Patty points it out, and take the optional treasure-race quest. Continue toward the temple. A Dragon Snapper blocks the route; killing it completes Take Out the Dangerous Carnivore. Use the Parrot Flight tutorial where required, clear the pirate camp, enter the temple, inspect Captain Rawlings' corpse for the treasure race, fight through the temple warriors and kill the Hellhounds near the final approach.", "Completion. Reach the Crystal Portal. The cutscene kills the hero and ends the original treasure hunt.", "Related: Race Against an Unknown Opponent / Creatures From Hell"),
            reward = "100 Glory",
            warnings = "⚠ Important: Patty permanently leaves the active party after the portal sequence. The hero also loses his old captain status, attributes and learned abilities after death.",
            searchTags = listOf("Crab Coast", "B. CRAB COAST — TREASURE EXPEDITION"),
        ),
        Quest(
            id = "R3-C1-003",
            chapter = 1,
            playOrder = 3,
            title = "Take Out the Dangerous Carnivore",
            aliases = listOf(),
            category = "OPTIONAL — COMBAT",
            giver = "Automatic",
            location = "Crab Coast",
            prerequisites = "",
            summary = "Kill the Dragon Snapper on the route to the temple.",
            walkthroughSteps = listOf("Walkthrough. During Hunting for Treasure, a large Dragon Snapper blocks or patrols the main route. Patty can help tank it. Dodge its heavier lunges, attack after its recovery animation and use ranged attacks if your early melee gear is weak.", "Completion. The quest completes when the Dragon Snapper dies."),
            reward = "200 Glory + creature Glory",
            warnings = "⚠ Important: You can run past it, but killing it is recommended for a completionist route.",
            searchTags = listOf("Crab Coast", "B. CRAB COAST — TREASURE EXPEDITION"),
        ),
        Quest(
            id = "R3-C1-004",
            chapter = 1,
            playOrder = 4,
            title = "Race Against an Unknown Opponent",
            aliases = listOf(),
            category = "OPTIONAL — TREASURE RACE",
            giver = "Patty / automatic",
            location = "Crab Coast",
            prerequisites = "",
            summary = "Investigate the pirate corpse, dig up the first treasure, defeat the rival pirates and inspect Captain Rawlings' body.",
            walkthroughSteps = listOf("Walkthrough. After the first pirate corpse is found near the river, search it and follow the treasure clues. Pick up the nearby shovel and dig at the red X for the first cache. Continue toward the temple and kill the three hostile pirates at the glade. Inside the temple, locate and search Captain Rawlings' corpse.", "Completion. Speak with Patty after Rawlings' body has been investigated."),
            reward = "200 Glory + treasure gold",
            warnings = "⚠ Important: Do this during Hunting for Treasure. The quest naturally overlaps the main route and is easiest to finish before the portal scene.",
            searchTags = listOf("Crab Coast", "B. CRAB COAST — TREASURE EXPEDITION"),
        ),
        Quest(
            id = "R3-C1-005",
            chapter = 1,
            playOrder = 5,
            title = "Creatures From Hell",
            aliases = listOf(),
            category = "OPTIONAL — COMBAT",
            giver = "Automatic",
            location = "Crab Coast",
            prerequisites = "",
            summary = "Kill the Hellhounds guarding the final approach to the Crystal Portal.",
            walkthroughSteps = listOf("Walkthrough. Near the end of Hunting for Treasure, a group of Hellhounds blocks the bridge/path. They attack quickly, so dodge rather than trying to absorb their entire combo. Focus one target at a time while Patty distracts the others.", "Completion. The quest completes after the Hellhound group is dead."),
            reward = "100 Glory + individual kill Glory",
            warnings = "",
            searchTags = listOf("Crab Coast", "B. CRAB COAST — TREASURE EXPEDITION"),
        ),
        Quest(
            id = "R3-C1-006",
            chapter = 1,
            playOrder = 6,
            title = "Pull on the Lever",
            aliases = listOf(),
            category = "TUTORIAL — MECHANISM",
            giver = "Automatic",
            location = "Crab Coast",
            prerequisites = "",
            summary = "Activate the required temple lever when the path demands it.",
            walkthroughSteps = listOf("Walkthrough. Inside the Crab Coast ruins/temple, interact with the mechanism highlighted by the tutorial.", "Completion. The mechanism opens or changes the route and the journal entry completes."),
            reward = "Tutorial Glory",
            warnings = "",
            searchTags = listOf("Crab Coast", "C. SMALL TUTORIAL JOURNAL ENTRIES"),
        ),
        Quest(
            id = "R3-C1-007",
            chapter = 1,
            playOrder = 7,
            title = "Found a Powerful Spell",
            aliases = listOf(),
            category = "TUTORIAL — MAGIC",
            giver = "Automatic",
            location = "Crab Coast",
            prerequisites = "",
            summary = "Pick up the powerful spell scroll placed on the tutorial route.",
            walkthroughSteps = listOf("Walkthrough. Explore the ruins rather than rushing through them. The spell is positioned to teach consumable magic and can make the pirate fight easier.", "Completion. Taking the spell completes the entry."),
            reward = "Tutorial Glory",
            warnings = "",
            searchTags = listOf("Crab Coast", "C. SMALL TUTORIAL JOURNAL ENTRIES"),
        ),
        Quest(
            id = "R3-C1-008",
            chapter = 1,
            playOrder = 8,
            title = "A Handful of Parrot Flight Magic",
            aliases = listOf(),
            category = "TUTORIAL — MAGIC",
            giver = "Automatic",
            location = "Crab Coast",
            prerequisites = "",
            summary = "Collect the Parrot Flight spell scrolls.",
            walkthroughSteps = listOf("Walkthrough. Search the tutorial area around the ruined structure. Pick up the Parrot Flight scrolls placed near the climbing/flying lesson.", "Completion. The collection objective completes when the required spell has been obtained.", "Related: Flying Without Wings"),
            reward = "20 Glory",
            warnings = "",
            searchTags = listOf("Crab Coast", "C. SMALL TUTORIAL JOURNAL ENTRIES"),
        ),
        Quest(
            id = "R3-C1-009",
            chapter = 1,
            playOrder = 9,
            title = "Flying Without Wings",
            aliases = listOf(),
            category = "TUTORIAL — MAGIC",
            giver = "Automatic",
            location = "Crab Coast",
            prerequisites = "",
            summary = "Use Parrot Flight to reach the elevated ledge and loot the area.",
            walkthroughSteps = listOf("Walkthrough. Put Parrot Flight on the quickbar and activate it. Use the jump control for extra altitude, fly to the raised platform and land before the effect runs out. Search the shelf/chest and pick up the additional Parrot Flight scroll.", "Completion. Successfully reaching the elevated area completes the quest."),
            reward = "100 Glory",
            warnings = "",
            searchTags = listOf("Crab Coast", "C. SMALL TUTORIAL JOURNAL ENTRIES"),
        ),
        Quest(
            id = "R3-C1-010",
            chapter = 1,
            playOrder = 10,
            title = "Let's Get Out of Here",
            aliases = listOf(),
            category = "CHAPTER 1 FINALE / CHAPTER 2 HANDOFF",
            giver = "Bones",
            location = "Crab Coast",
            prerequisites = "",
            summary = "After Bones revives you, exhaust his dialogue, learn the new systems and return to the sloop.",
            walkthroughSteps = listOf("Walkthrough. Three weeks after the portal incident, Bones revives the hero. Speak with him fully. This is where character development using Glory becomes available again and Astral Vision is unlocked. Talk to Bones a second time and exhaust all dialogue options to unlock Report for Admiral Alvarez, New Allies, Find Jack the Lighthouse Keeper and Find Patty. When ready, tell Bones you want to return to the sloop.", "Completion. Return to the ship and use the wheel to choose your first open-world destination.", "Related: Only Worth Half As Much / New Allies / Report for Admiral Alvarez"),
            reward = "200 Glory",
            warnings = "⚠ Important: Do not leave without exhausting Bones' dialogue; several major and crew quests are started here.",
            searchTags = listOf("Crab Coast", "D. DEATH, REVIVAL & CHAPTER 2 HANDOFF"),
        ),
    )

    val notes: List<RisenGuideNote> = listOf(
        RisenGuideNote(1, 1, "Chapter 1 overview", listOf("Crab Coast • Death & Revival • Chapter 2 Handoff")),
        RisenGuideNote(1, 1, "How Risen 3 actually begins", listOf("The ship battle and first visit to the Crab Coast function as Risen 3's tutorial. The main story changes dramatically at the end of Hunting for Treasure: the hero is killed at the Crystal Portal, Bones revives him three weeks later, and Chapter 1's real open-world structure begins.", "Important structure note: The Shadow Lord of Hate is a real Chapter 1 Crab Coast quest, but it is NOT meant to be completed during the opening visit. You return later after Eldric teaches you how to destroy Crystal Portals.")),
        RisenGuideNote(1, 11, "Only Worth Half As Much — continued quest guidance", listOf("Quick solution: Visit the three major faction headquarters and find someone capable of restoring the hero's soul.", "Walkthrough. This quest starts after the revival. The three major routes are the Demon Hunters on Calador, the Natives on Kila and the Guardians/Mages on Taranis. You are encouraged to visit all three before joining anyone. Meeting a faction leader does NOT automatically commit you.", "Completion. The quest advances as the three faction solutions are investigated; its full resolution occurs later.", "⚠ Important: Do not mistake 'visit all three factions' for 'join one immediately.' Explore their questlines first.", "Quest giver: Bones", "Status: CHAPTER 2 — LONG-TERM FACTION QUEST", "Area: Crab Coast", "Reward: 400 Glory at major milestone", "Related: Find Eldric / faction routes")),
        RisenGuideNote(1, 11, "New Allies", listOf("Quick solution: Build new alliances and recruit useful companions as you travel between islands.", "Walkthrough. Ask Bones about allies after the revival. This umbrella quest develops across several islands and faction storylines. Early companion targets include Jack, Patty and later faction-specific recruits.", "Completion. Keep it active as you build the crew and faction network.", "Quest giver: Bones", "Status: CHAPTER 2 — LONG-TERM CREW / ALLIANCE QUEST", "Area: Crab Coast", "Reward: Long-term progression", "Related: Find Jack the Lighthouse Keeper / Find Patty")),
        RisenGuideNote(1, 11, "Report for Admiral Alvarez — continued quest guidance", listOf("Quick solution: Sail to Antigua and report what happened to Admiral Alvarez.", "Walkthrough. Bones suggests that Admiral Alvarez needs to hear about the disaster and the Shadow threat. This quest is the cleanest reason to make Antigua one of your first destinations after leaving the Crab Coast.", "Completion. Speak with Admiral Alvarez on Antigua.", "Quest giver: Bones", "Status: CHAPTER 2 — ANTIGUA INTRODUCTION", "Area: Crab Coast", "Reward: 100 Glory", "Related: Chaos in Harbour Town")),
        RisenGuideNote(1, 11, "Find Jack the Lighthouse Keeper — continued quest guidance", listOf("Quick solution: Travel to Tacarigua and locate Jack.", "Walkthrough. After the revival, ask Bones about old allies. He points you toward Jack on Tacarigua. Sail there and follow the island route toward his lighthouse/beach position.", "Completion. Speak with Jack.", "Quest giver: Bones", "Status: CHAPTER 2 — CREW QUEST", "Area: Crab Coast", "Reward: 100 Glory")),
        RisenGuideNote(1, 11, "Find Patty — continued quest guidance", listOf("Quick solution: Search for Patty after the Crab Coast disaster.", "Walkthrough. Ask Bones what happened to Patty. Her search becomes a crew objective that continues outside the Crab Coast.", "Completion. Locate Patty through the later island storyline.", "Quest giver: Bones", "Status: CHAPTER 2 — CREW QUEST", "Area: Crab Coast", "Reward: Quest progression", "Related: Sign Patty On")),
        RisenGuideNote(1, 11, "The Shadow Lord of Hate — continued quest guidance", listOf("Quick solution: Return after Eldric teaches portal destruction, kill the Shadow Lord of Hate and destroy the Crab Coast Crystal Portal.", "Walkthrough. After leaving the Crab Coast at least once, speak with Bones about the portal to unlock The Realm of the Shadows. Travel to Calador and ask Eldric about Crystal Portals; he teaches the destruction spell. Then return to the Crab Coast temple, kill the Shadow Lord of Hate, loot its Raw Black Heart, defeat the nearby Black Ghoul and destroy the portal.", "Completion. The local Shadow Lord/portal objective is complete.", "⚠ Important: This is NOT part of the opening tutorial run. The app should show it as a Chapter 1 return visit.", "Quest giver: The Realm of the Shadows chain", "Status: CHAPTER 2 — LATER RETURN", "Area: Crab Coast", "Reward: 200 Glory quest reward + major kill/portal Glory", "Related: The Realm of the Shadows")),
        RisenGuideNote(1, 11, "PART I COMPLETION CHECKLIST", listOf("Ready for the Island is complete.", "Hunting for Treasure is complete.", "Take Out the Dangerous Carnivore was completed if doing a full run.", "Race Against an Unknown Opponent was completed before the portal scene.", "Creatures From Hell is complete.", "Parrot Flight tutorial quests were completed.", "The hero died at the Crystal Portal and was revived by Bones.", "All Bones dialogue was exhausted after revival.", "Let's Get Out of Here is complete.", "Only Worth Half As Much is active.", "New Allies is active.", "Report for Admiral Alvarez is active.", "Find Jack the Lighthouse Keeper and Find Patty are active.", "The Shadow Lord of Hate is intentionally left for a later Crab Coast return after meeting Eldric.")),
        RisenGuideNote(1, 11, "RECOMMENDED NEXT DESTINATION", listOf("For this guide series, Antigua is the cleanest Chapter 2 Part I destination. It immediately advances Report for Admiral Alvarez, introduces Chaos in Harbour Town and Pirate Alliance, and contains a compact set of Chapter 1 quests. After Antigua, we can branch into Calador, Kila and Taranis without locking the player into a faction too early.")),
    )
}
