package com.sliverzfx.gothicquest

internal object Risen3Chapter2Part4Data {
    val quests: List<Quest> = listOf(
        Quest(
            id = "R3-C2-106",
            chapter = 2,
            playOrder = 106,
            title = "Off and Away",
            aliases = listOf(),
            category = "Side quest",
            giver = "",
            location = "Tacarigua",
            prerequisites = "",
            summary = "Tacarigua side quest.",
            walkthroughSteps = listOf(),
            reward = "",
            warnings = "",
            searchTags = listOf("Tacarigua", "TACARIGUA"),
        ),
        Quest(
            id = "R3-C2-107",
            chapter = 2,
            playOrder = 107,
            title = "The Commandant of Tacarigua",
            aliases = listOf(),
            category = "Side quest",
            giver = "",
            location = "Tacarigua",
            prerequisites = "",
            summary = "Tacarigua side quest.",
            walkthroughSteps = listOf(),
            reward = "",
            warnings = "",
            searchTags = listOf("Tacarigua", "TACARIGUA"),
        ),
        Quest(
            id = "R3-C2-108",
            chapter = 2,
            playOrder = 108,
            title = "Rodriguez's Spot of Bother",
            aliases = listOf(),
            category = "Side quest",
            giver = "",
            location = "Tacarigua",
            prerequisites = "",
            summary = "Tacarigua side quest.",
            walkthroughSteps = listOf(),
            reward = "",
            warnings = "",
            searchTags = listOf("Tacarigua", "TACARIGUA"),
        ),
        Quest(
            id = "R3-C2-109",
            chapter = 2,
            playOrder = 109,
            title = "Death to the Deserters",
            aliases = listOf(),
            category = "Side quest",
            giver = "",
            location = "Tacarigua",
            prerequisites = "",
            summary = "Tacarigua side quest.",
            walkthroughSteps = listOf(),
            reward = "",
            warnings = "",
            searchTags = listOf("Tacarigua", "TACARIGUA"),
        ),
        Quest(
            id = "R3-C2-110",
            chapter = 2,
            playOrder = 110,
            title = "Betray Horas",
            aliases = listOf(),
            category = "Side quest",
            giver = "",
            location = "Tacarigua",
            prerequisites = "",
            summary = "Tacarigua side quest.",
            walkthroughSteps = listOf(),
            reward = "",
            warnings = "",
            searchTags = listOf("Tacarigua", "TACARIGUA"),
        ),
        Quest(
            id = "R3-C2-111",
            chapter = 2,
            playOrder = 111,
            title = "The Nameless Captain's Treasure",
            aliases = listOf(),
            category = "Side quest",
            giver = "",
            location = "Tacarigua",
            prerequisites = "",
            summary = "Tacarigua side quest.",
            walkthroughSteps = listOf(),
            reward = "",
            warnings = "",
            searchTags = listOf("Tacarigua", "TACARIGUA"),
        ),
        Quest(
            id = "R3-C2-112",
            chapter = 2,
            playOrder = 112,
            title = "Unfathomable Riches",
            aliases = listOf(),
            category = "Side quest",
            giver = "",
            location = "Tacarigua",
            prerequisites = "",
            summary = "Tacarigua side quest.",
            walkthroughSteps = listOf(),
            reward = "",
            warnings = "",
            searchTags = listOf("Tacarigua", "TACARIGUA"),
        ),
        Quest(
            id = "R3-C2-113",
            chapter = 2,
            playOrder = 113,
            title = "A Stately Chest",
            aliases = listOf(),
            category = "Side quest",
            giver = "",
            location = "Tacarigua",
            prerequisites = "",
            summary = "Tacarigua side quest.",
            walkthroughSteps = listOf(),
            reward = "",
            warnings = "",
            searchTags = listOf("Tacarigua", "TACARIGUA"),
        ),
        Quest(
            id = "R3-C2-114",
            chapter = 2,
            playOrder = 114,
            title = "Parting of Ways",
            aliases = listOf(),
            category = "Side quest",
            giver = "",
            location = "Tacarigua",
            prerequisites = "",
            summary = "Tacarigua side quest.",
            walkthroughSteps = listOf(),
            reward = "",
            warnings = "",
            searchTags = listOf("Tacarigua", "TACARIGUA"),
        ),
        Quest(
            id = "R3-C2-115",
            chapter = 2,
            playOrder = 115,
            title = "Close Enough to Touch",
            aliases = listOf(),
            category = "Side quest",
            giver = "",
            location = "Tacarigua",
            prerequisites = "",
            summary = "Tacarigua side quest.",
            walkthroughSteps = listOf(),
            reward = "",
            warnings = "",
            searchTags = listOf("Tacarigua", "TACARIGUA"),
        ),
        Quest(
            id = "R3-C2-116",
            chapter = 2,
            playOrder = 116,
            title = "The Biggest Treasure",
            aliases = listOf(),
            category = "Side quest",
            giver = "",
            location = "Tacarigua",
            prerequisites = "",
            summary = "Tacarigua side quest.",
            walkthroughSteps = listOf(),
            reward = "",
            warnings = "",
            searchTags = listOf("Tacarigua", "TACARIGUA"),
        ),
        Quest(
            id = "R3-C2-117",
            chapter = 2,
            playOrder = 117,
            title = "The Shadow Lord of Madness",
            aliases = listOf(),
            category = "Side quest",
            giver = "",
            location = "Tacarigua",
            prerequisites = "",
            summary = "Tacarigua side quest.",
            walkthroughSteps = listOf(),
            reward = "",
            warnings = "",
            searchTags = listOf("Tacarigua", "TACARIGUA"),
        ),
        Quest(
            id = "R3-C2-118",
            chapter = 2,
            playOrder = 118,
            title = "Nebulous Suggestions",
            aliases = listOf(),
            category = "Side quest",
            giver = "",
            location = "Fog Island",
            prerequisites = "",
            summary = "Talk to Bones and listen to his vision to learn about Fog Island.",
            walkthroughSteps = listOf("Talk to Bones and listen to his vision to learn about Fog Island."),
            reward = "",
            warnings = "",
            searchTags = listOf("Fog Island", "OPTIONAL REGION — FOG ISLAND"),
        ),
        Quest(
            id = "R3-C2-119",
            chapter = 2,
            playOrder = 119,
            title = "The Terror of the East",
            aliases = listOf(),
            category = "Side quest",
            giver = "",
            location = "Fog Island",
            prerequisites = "",
            summary = "Meet Venturo on the eastern beach, travel with him, kill Soul Eater Rakazor and inspect Rodrigo's corpse.",
            walkthroughSteps = listOf("Meet Venturo on the eastern beach, travel with him, kill Soul Eater Rakazor and inspect Rodrigo's corpse."),
            reward = "",
            warnings = "",
            searchTags = listOf("Fog Island", "OPTIONAL REGION — FOG ISLAND"),
        ),
        Quest(
            id = "R3-C2-120",
            chapter = 2,
            playOrder = 120,
            title = "The Commandant",
            aliases = listOf(),
            category = "Side quest",
            giver = "",
            location = "Fog Island",
            prerequisites = "",
            summary = "Continue toward the Inquisition camp and meet Commandant Carlos.",
            walkthroughSteps = listOf("Continue toward the Inquisition camp and meet Commandant Carlos."),
            reward = "",
            warnings = "",
            searchTags = listOf("Fog Island", "OPTIONAL REGION — FOG ISLAND"),
        ),
        Quest(
            id = "R3-C2-121",
            chapter = 2,
            playOrder = 121,
            title = "Paths to the Afterlife",
            aliases = listOf(),
            category = "Side quest",
            giver = "",
            location = "Fog Island",
            prerequisites = "",
            summary = "Carlos sends you to eliminate five Soul Eaters across the island; combine this with the scattered-soldier encounters.",
            walkthroughSteps = listOf("Carlos sends you to eliminate five Soul Eaters across the island; combine this with the scattered-soldier encounters."),
            reward = "",
            warnings = "",
            searchTags = listOf("Fog Island", "OPTIONAL REGION — FOG ISLAND"),
        ),
        Quest(
            id = "R3-C2-122",
            chapter = 2,
            playOrder = 122,
            title = "The Scattered Soldiers",
            aliases = listOf(),
            category = "Side quest",
            giver = "",
            location = "Fog Island",
            prerequisites = "",
            summary = "Find the separated Inquisition soldiers and help them survive or regroup.",
            walkthroughSteps = listOf("Find the separated Inquisition soldiers and help them survive or regroup."),
            reward = "",
            warnings = "",
            searchTags = listOf("Fog Island", "OPTIONAL REGION — FOG ISLAND"),
        ),
        Quest(
            id = "R3-C2-123",
            chapter = 2,
            playOrder = 123,
            title = "United in the Afterlife",
            aliases = listOf(),
            category = "Side quest",
            giver = "",
            location = "Fog Island",
            prerequisites = "",
            summary = "Resolve the linked soldier/ghost storyline.",
            walkthroughSteps = listOf("Resolve the linked soldier/ghost storyline."),
            reward = "",
            warnings = "",
            searchTags = listOf("Fog Island", "OPTIONAL REGION — FOG ISLAND"),
        ),
        Quest(
            id = "R3-C2-124",
            chapter = 2,
            playOrder = 124,
            title = "The Braggart",
            aliases = listOf(),
            category = "Side quest",
            giver = "",
            location = "Fog Island",
            prerequisites = "",
            summary = "Complete the local boasting/duel side quest.",
            walkthroughSteps = listOf("Complete the local boasting/duel side quest."),
            reward = "",
            warnings = "",
            searchTags = listOf("Fog Island", "OPTIONAL REGION — FOG ISLAND"),
        ),
        Quest(
            id = "R3-C2-125",
            chapter = 2,
            playOrder = 125,
            title = "A Way Out of Darkness",
            aliases = listOf(),
            category = "Side quest",
            giver = "",
            location = "Fog Island",
            prerequisites = "",
            summary = "Finish the island's darkness-related side chain.",
            walkthroughSteps = listOf("Finish the island's darkness-related side chain."),
            reward = "",
            warnings = "",
            searchTags = listOf("Fog Island", "OPTIONAL REGION — FOG ISLAND"),
        ),
        Quest(
            id = "R3-C2-126",
            chapter = 2,
            playOrder = 126,
            title = "Mortimer's Treasure",
            aliases = listOf(),
            category = "Side quest",
            giver = "",
            location = "Fog Island",
            prerequisites = "",
            summary = "Follow the clues and dig up Mortimer's treasure.",
            walkthroughSteps = listOf("Follow the clues and dig up Mortimer's treasure."),
            reward = "",
            warnings = "",
            searchTags = listOf("Fog Island", "OPTIONAL REGION — FOG ISLAND"),
        ),
        Quest(
            id = "R3-C2-127",
            chapter = 2,
            playOrder = 127,
            title = "News on Board",
            aliases = listOf(),
            category = "Side quest",
            giver = "",
            location = "Isle of Thieves",
            prerequisites = "",
            summary = "Learn about the island from the crew/travel conversation.",
            walkthroughSteps = listOf("Learn about the island from the crew/travel conversation."),
            reward = "",
            warnings = "",
            searchTags = listOf("Isle of Thieves", "OPTIONAL REGION — ISLE OF THIEVES"),
        ),
        Quest(
            id = "R3-C2-128",
            chapter = 2,
            playOrder = 128,
            title = "Goblin Invasion",
            aliases = listOf(),
            category = "Side quest",
            giver = "",
            location = "Isle of Thieves",
            prerequisites = "",
            summary = "Help the gnomes repel the goblin threat.",
            walkthroughSteps = listOf("Help the gnomes repel the goblin threat."),
            reward = "",
            warnings = "",
            searchTags = listOf("Isle of Thieves", "OPTIONAL REGION — ISLE OF THIEVES"),
        ),
        Quest(
            id = "R3-C2-129",
            chapter = 2,
            playOrder = 129,
            title = "Speak to Ulvi",
            aliases = listOf(),
            category = "Side quest",
            giver = "",
            location = "Isle of Thieves",
            prerequisites = "",
            summary = "Find Ulvi and begin the central gnome quest chain.",
            walkthroughSteps = listOf("Find Ulvi and begin the central gnome quest chain."),
            reward = "",
            warnings = "",
            searchTags = listOf("Isle of Thieves", "OPTIONAL REGION — ISLE OF THIEVES"),
        ),
        Quest(
            id = "R3-C2-130",
            chapter = 2,
            playOrder = 130,
            title = "Intrusion in the North",
            aliases = listOf(),
            category = "Side quest",
            giver = "",
            location = "Isle of Thieves",
            prerequisites = "",
            summary = "Investigate and clear the hostile northern incursion.",
            walkthroughSteps = listOf("Investigate and clear the hostile northern incursion."),
            reward = "",
            warnings = "",
            searchTags = listOf("Isle of Thieves", "OPTIONAL REGION — ISLE OF THIEVES"),
        ),
        Quest(
            id = "R3-C2-131",
            chapter = 2,
            playOrder = 131,
            title = "Goblin Plague",
            aliases = listOf(),
            category = "Side quest",
            giver = "",
            location = "Isle of Thieves",
            prerequisites = "",
            summary = "Continue eliminating goblin groups threatening the island.",
            walkthroughSteps = listOf("Continue eliminating goblin groups threatening the island."),
            reward = "",
            warnings = "",
            searchTags = listOf("Isle of Thieves", "OPTIONAL REGION — ISLE OF THIEVES"),
        ),
        Quest(
            id = "R3-C2-132",
            chapter = 2,
            playOrder = 132,
            title = "The Lucky Coin",
            aliases = listOf(),
            category = "Side quest",
            giver = "",
            location = "Isle of Thieves",
            prerequisites = "",
            summary = "Recover the missing lucky coin.",
            walkthroughSteps = listOf("Recover the missing lucky coin."),
            reward = "",
            warnings = "",
            searchTags = listOf("Isle of Thieves", "OPTIONAL REGION — ISLE OF THIEVES"),
        ),
        Quest(
            id = "R3-C2-133",
            chapter = 2,
            playOrder = 133,
            title = "A Scatterbrained Gnome",
            aliases = listOf(),
            category = "Side quest",
            giver = "",
            location = "Isle of Thieves",
            prerequisites = "",
            summary = "Help the confused gnome recover the lost objective.",
            walkthroughSteps = listOf("Help the confused gnome recover the lost objective."),
            reward = "",
            warnings = "",
            searchTags = listOf("Isle of Thieves", "OPTIONAL REGION — ISLE OF THIEVES"),
        ),
        Quest(
            id = "R3-C2-134",
            chapter = 2,
            playOrder = 134,
            title = "Escaped",
            aliases = listOf(),
            category = "Side quest",
            giver = "",
            location = "Isle of Thieves",
            prerequisites = "",
            summary = "Track down the escaped target.",
            walkthroughSteps = listOf("Track down the escaped target."),
            reward = "",
            warnings = "",
            searchTags = listOf("Isle of Thieves", "OPTIONAL REGION — ISLE OF THIEVES"),
        ),
        Quest(
            id = "R3-C2-135",
            chapter = 2,
            playOrder = 135,
            title = "Graveyard Gardener",
            aliases = listOf(),
            category = "Side quest",
            giver = "",
            location = "Isle of Thieves",
            prerequisites = "",
            summary = "Resolve the graveyard-related gnome problem.",
            walkthroughSteps = listOf("Resolve the graveyard-related gnome problem."),
            reward = "",
            warnings = "",
            searchTags = listOf("Isle of Thieves", "OPTIONAL REGION — ISLE OF THIEVES"),
        ),
        Quest(
            id = "R3-C2-136",
            chapter = 2,
            playOrder = 136,
            title = "Gnome Riddle",
            aliases = listOf(),
            category = "Side quest",
            giver = "",
            location = "Isle of Thieves",
            prerequisites = "",
            summary = "Solve the local gnome riddle.",
            walkthroughSteps = listOf("Solve the local gnome riddle."),
            reward = "",
            warnings = "",
            searchTags = listOf("Isle of Thieves", "OPTIONAL REGION — ISLE OF THIEVES"),
        ),
        Quest(
            id = "R3-C2-137",
            chapter = 2,
            playOrder = 137,
            title = "The Gnome Eater",
            aliases = listOf(),
            category = "Side quest",
            giver = "",
            location = "Isle of Thieves",
            prerequisites = "",
            summary = "Hunt down the monster threatening the gnomes.",
            walkthroughSteps = listOf("Hunt down the monster threatening the gnomes."),
            reward = "",
            warnings = "",
            searchTags = listOf("Isle of Thieves", "OPTIONAL REGION — ISLE OF THIEVES"),
        ),
        Quest(
            id = "R3-C2-138",
            chapter = 2,
            playOrder = 138,
            title = "New Allies — Demon Hunters",
            aliases = listOf("New Allies"),
            category = "IRREVERSIBLE — DEMON HUNTER INITIATION",
            giver = "Eldric",
            location = "Calador",
            prerequisites = "Faction commitment",
            summary = "Help the scattered Demon Hunters and resolve their crises around western Calador.\nReturn to Eldric after finishing Calador's New Allies objectives and explicitly ask to undergo initiation.",
            walkthroughSteps = listOf("Chapter 2 — Calador — F. NEW ALLIES — DEMON HUNTER SUPPORT CHAIN", "Quest giver: Bones / Eldric", "Status: MAIN STORY — DEMON HUNTER BRANCH", "Area: Calador", "Reward: 1000 Glory + 1000 Gold + 2 Tomes of Ancient Knowledge", "Walkthrough. Offer Eldric your help. The Demon Hunter branch sends you through several linked situations: Wilson's missing assistant Alvito, Hanna's stolen amulet, Porter/Yvette, Mason, the abandoned mine, Cyril and fallen hunters, Fenn/Iona, Winter and the western castle ruins. Follow each lead, rescue/help the Hunters and clear the Shadow threat in the ruins.", "Completion. Return to Eldric after the required Demon Hunter support objectives are resolved.", "Related: The Ancient Knowledge", "Chapter 2 — Calador — 3. DEMON HUNTERS — CALADOR", "Quest giver: Eldric", "Status: IRREVERSIBLE — DEMON HUNTER INITIATION", "Faction: Faction commitment", "Reward: 3,000 Glory for joining + Scout rank and outfit elements; New Allies also pays its normal branch rewards", "Walkthrough. Make sure the permanent pre-faction save exists. Speak with Eldric in the Citadel after meeting Alvarez and completing the Demon Hunter support chain. Choose the dialogue that says you want to undergo initiation/join the Demon Hunters.", "Completion. The hero becomes a Scout. Demon Hunter faction quests, outfit pieces, expanded trainers and Rune Magic access unlock.", "Related: Ghost Eyes / Demon Hunter rank progression / Pirate Alliance"),
            reward = "3,000 Glory for joining + Scout rank and outfit elements; New Allies also pays its normal branch rewards",
            warnings = "⚠ Important: This chain can make you ELIGIBLE to join the Demon Hunters, but eligibility is not the same as joining. Do not choose initiation yet if you want to inspect Kila/Taranis first.\n⚠ POINT OF NO RETURN: Once you confirm initiation with Eldric, Natives and Guardians can no longer be joined.",
            searchTags = listOf("Calador", "F. NEW ALLIES — DEMON HUNTER SUPPORT CHAIN", "3. DEMON HUNTERS — CALADOR"),
        ),
        Quest(
            id = "R3-C2-139",
            chapter = 2,
            playOrder = 139,
            title = "New Allies — Natives",
            aliases = listOf("New Allies"),
            category = "IRREVERSIBLE — NATIVE INITIATION",
            giver = "Hirutu",
            location = "Kila",
            prerequisites = "Faction commitment",
            summary = "Help Tenya gather the materials required for the Scepter of the Ancestors.\nReturn to Hirutu after Tenya receives the Scepter materials and explicitly accept the rite of passage.",
            walkthroughSteps = listOf("Chapter 2 — Kila — C. NEW ALLIES — NATIVE BRANCH", "Quest giver: Bones / Hirutu / Tenya", "Status: MAIN STORY — NATIVE SUPPORT CHAIN", "Area: Kila", "Reward: Major quest Glory", "Walkthrough. Offer Hirutu your help, then speak with Tenya. She sends you to read three stone tablets scattered around Kila. After reading all three, the journal reveals the four materials required for the Scepter: Panther Heart, Sturdy Spider Leg, Shimmering Pearl and Chunk of Jade.", "Completion. Collect all four materials and return to Tenya/Hirutu as directed.", "Related: Panther Heart / Sturdy Spider Leg / Shimmering Pearl / Chunk of Jade", "Chapter 2 — Kila — 4. NATIVES — KILA", "Quest giver: Hirutu", "Status: IRREVERSIBLE — NATIVE INITIATION", "Faction: Faction commitment", "Reward: 3,000 Glory for joining + Scepter of the Ancestors + Voodoo Pirate rank/outfit; Kila New Allies also gives its normal rewards", "Walkthrough. Make a permanent save first. Speak with Hirutu after completing the Kila New Allies requirements and after meeting Alvarez. Choose the dialogue confirming that you want to undergo the initiation ritual.", "Completion. The hero becomes a Voodoo Pirate. Voodoo spells, trainers, apparel and Native-exclusive quests unlock.", "Related: Become a Voodoo Master / Pirate Alliance"),
            reward = "3,000 Glory for joining + Scepter of the Ancestors + Voodoo Pirate rank/outfit; Kila New Allies also gives its normal rewards",
            warnings = "⚠ Important: This entire chain is still faction-neutral.\n⚠ POINT OF NO RETURN: Once Hirutu accepts you, Demon Hunters and Guardians can no longer be joined.",
            searchTags = listOf("Kila", "C. NEW ALLIES — NATIVE BRANCH", "4. NATIVES — KILA"),
        ),
        Quest(
            id = "R3-C2-140",
            chapter = 2,
            playOrder = 140,
            title = "New Allies — Guardians",
            aliases = listOf("New Allies"),
            category = "IRREVERSIBLE — GUARDIAN INITIATION",
            giver = "General Magnus",
            location = "Taranis",
            prerequisites = "Faction commitment",
            summary = "Help Magnus by solving the delayed crystal delivery from the nearby mine.\nReturn to Magnus after the Taranis New Allies mine work and explicitly ask to undergo initiation.",
            walkthroughSteps = listOf("Chapter 2 — Taranis — B. MAGES CAMP & THE THIRD FACTION", "Quest giver: Bones / Magnus", "Status: MAIN STORY — GUARDIAN SUPPORT CHAIN", "Area: Taranis", "Reward: 750 Glory total for the major chain + gold rewards", "Walkthrough. Offer Magnus your help. He sends you to Frink at the mine entrance. Speak with Frink and accept the crystal-delivery job. Search the mine and collect all four Pouches of Crystals; each pouch gives Glory. Before leaving, talk with Garelt about the delay to unlock extra side content. Return to Frink with all four pouches, then report to Magnus.", "Completion. Magnus recognizes your work and grants access toward the inner mage area.", "Related: Clear Rules / Visiting Rights", "Chapter 2 — Taranis — 5. GUARDIANS — TARANIS", "Quest giver: General Magnus", "Status: IRREVERSIBLE — GUARDIAN INITIATION", "Faction: Faction commitment", "Reward: 3,000 Glory for joining + Cadet rank/outfit; Taranis New Allies also gives its normal rewards", "Walkthrough. Make a permanent save first. Speak with Magnus after completing the crystal-mine objective and meeting Alvarez. Choose the dialogue confirming that you want the initiation rite.", "Completion. The hero becomes a Cadet. Crystal Magic, Guardian quests, faction outfit pieces and expanded trainers unlock.", "Related: Advancing Among the Guardians / Pirate Alliance"),
            reward = "3,000 Glory for joining + Cadet rank/outfit; Taranis New Allies also gives its normal rewards",
            warnings = "⚠ Important: Do NOT choose the later initiation dialogue with Magnus yet.\n⚠ POINT OF NO RETURN: Once Magnus initiates you, Demon Hunters and Natives can no longer be joined.",
            searchTags = listOf("Taranis", "B. MAGES CAMP & THE THIRD FACTION", "5. GUARDIANS — TARANIS"),
        ),
    )

    val notes: List<RisenGuideNote> = listOf(
        RisenGuideNote(2, 139, "Important post-join quests", listOf("Ghost Eyes: Drake teaches Vision of the Shadows and sends you through a Demon Hunter-only ghost/vision chain.", "A New Rank: Faction promotion content after proving yourself.", "New Armour: Faction-specific equipment progression.", "The Test of the Righteous: Demon Hunter progression content.")),
        RisenGuideNote(2, 139, "4. NATIVES — KILA", listOf("Choose the Natives if you enjoyed Risen 2's Voodoo system or want the most unusual utility playstyle. Voodoo emphasizes control, poison, possession and creative tools rather than simply throwing direct-damage spells.")),
        RisenGuideNote(2, 140, "Native / Voodoo strengths", listOf("Voodoo Magic opens after joining.", "The spell school emphasizes control, poison and unusual utility.", "Possession/doll-style quest solutions are the most distinctive faction gameplay.", "Parrot Flight and utility magic support exploration.", "Advanced Voodoo promotion later unlocks additional spells through Tenya.")),
        RisenGuideNote(2, 140, "Important post-join quest: Become a Voodoo Master — continued quest guidance", listOf("Hirutu gives Become a Voodoo Master only after the Native initiation. The chain spans Kila, Tacarigua, Antigua and Taranis: Red, Emma and Abbas each become part of the promotion route. After reporting the three situations to Tenya, the hero can return to Hirutu and advance to Voodoo Master.", "Tenya's expanded post-promotion Voodoo teaching includes advanced spells such as Necromancy, Kiss of Death and Bloodlust, while other Native teachers provide additional Voodoo spells.")),
        RisenGuideNote(2, 140, "5. GUARDIANS — TARANIS", listOf("Choose the Guardians if you want Risen 3's most conventional full-mage experience. Crystal Magic is the strongest fit for a player who wants spellcasting itself—not weapons—to be the centre of the build.")),
        RisenGuideNote(2, 141, "Guardian strengths", listOf("Crystal Magic is the strongest pure-caster route.", "Access to powerful direct and area-damage magic expands after joining.", "Spell-focused faction skills reward investing heavily into Magic.", "The faction offers magical utility such as healing/light/lock-related tools depending on learned spells.", "Best choice if you want to solve combat primarily with magic rather than sword/musket damage.")),
        RisenGuideNote(2, 141, "Important post-join quest: Advancing Among the Guardians — continued quest guidance", listOf("Magnus offers Advancing Among the Guardians after you become a Cadet. The promotion route includes work for Mauricio, Ilvar and Gordon, the Waterproof quest, defeating a Golem, gathering Pure Iron Ore from Calador, and can also include proving yourself against the Shadow Lord of Betrayal and Magnus. Completing the required tasks promotes the hero further and unlocks A Guardian's Armor.")),
        RisenGuideNote(2, 141, "6. PIRATE ALLIANCE & THE LARGE SHIP", listOf("Your faction decision also resolves the 'which large ship becomes mine?' issue in Pirate Alliance. Before joining, the relevant first mate refuses to hand over full command. After joining the corresponding faction and completing its requirements, return to that ship and advance the alliance/command step.", "Demon Hunters: Faction ship / first-mate route: Calador faction ship; Practical consequence: Becomes your large-ship route after Demon Hunter commitment.", "Natives: Faction ship / first-mate route: Kila pirate/Native ship with Jake; Practical consequence: Your old pirate-style ship route; Jake accepts you once the faction requirements are met.", "Guardians: Faction ship / first-mate route: Taranis Guardian/Mage ship with Neron; Practical consequence: Neron's command step unlocks after Guardian commitment.")),
        RisenGuideNote(2, 141, "Pick DEMON HUNTERS if...", listOf("you primarily fight with melee/ranged weapons;", "you want Rune Magic as support rather than living entirely on spells;", "you like the anti-Shadow / monster-hunter theme;", "you want Calador and Eldric to feel like your faction home.")),
        RisenGuideNote(2, 141, "Pick NATIVES if...", listOf("you enjoy Voodoo, possession and unconventional solutions;", "you want the most distinctive role-playing flavor;", "you prefer utility/control/poison over straightforward elemental blasting;", "you liked Risen 2's Voodoo path.")),
        RisenGuideNote(2, 141, "Pick GUARDIANS if...", listOf("you want to play a true mage;", "you intend to invest heavily in Magic;", "you want strong direct and area spell damage;", "you want Taranis and the Crystal Mages as your main base.")),
        RisenGuideNote(2, 141, "8. COMPLETIONIST RECOMMENDATION", listOf("There is no universal 'best' faction. For a first completionist playthrough, the best practice is to keep the permanent save made before initiation and create three branch saves. Join each faction once, inspect its appearance, starter rank, trainers, ship and first exclusive quests, then continue the branch you actually enjoy.", "Because faction choice unlocks several hours of exclusive quests, skills, armor progression and dialogue, one single playthrough cannot contain every faction-exclusive journal quest.")),
        RisenGuideNote(2, 141, "9. AFTER YOU CHOOSE — MAIN STORY HANDOFF", listOf("Once one faction has been joined, return to Eldric on Calador and continue The Ancient Knowledge. The Grimoire discussion now advances properly and the story moves into the Spirit Ritual phase. From this point, later Calador, Kila and Taranis quests such as Recruit Eldric, Recruit Chani, Recruit Zacharias, The Right Place and The Spirit Ritual belong in the next story section.")),
        RisenGuideNote(2, 141, "FACTION DECISION CHECKLIST", listOf("Report for Admiral Alvarez is complete.", "Calador New Allies requirements are complete.", "Kila New Allies requirements are complete.", "Taranis New Allies requirements are complete.", "All three faction leaders have been met.", "All faction-neutral side quests you care about are finished.", "A permanent neutral save exists.", "You understand that initiation is irreversible.", "You have chosen Demon Hunters, Natives or Guardians intentionally.", "Your chosen faction's large-ship/Pirate Alliance route is now available.", "The Ancient Knowledge is ready to advance with Eldric.")),
        RisenGuideNote(2, 141, "Chapter 2 transition", listOf("After joining one faction, return to Eldric and continue The Ancient Knowledge. That closes Chapter 2 and begins Chapter 3.")),
    )
}
