package com.sliverzfx.gothicquest

/** Standalone faction-specific Harbour Town quest branches; rival hand-ins are mutually exclusive. */
internal object RisenGuidePart11Data {
    val quests: List<Quest> = listOf(
        Quest(
            id = "R1-C1-135",
            chapter = 1,
            playOrder = 135,
            title = "Protection Money from Costa",
            category = "HARBOUR TOWN — BANDIT BRANCH",
            giver = "Delgado",
            location = "Harbour Town",
            prerequisites = "Speak to Delgado outside Costa's establishment about collecting protection money.",
            summary = "Confront Costa and defeat or bypass Fuller, his bodyguard.",
            walkthroughSteps = listOf("Start. Speak to Delgado outside Costa's establishment about collecting protection money.", "Steps. Confront Costa and defeat or bypass Fuller, his bodyguard.", "Completion. Collect Costa's pouch and give it to Delgado."),
            reward = "100 XP and 150 gold; advances the Don-side city case",
            warnings = "Bandit-aligned completion. The corresponding Order hand-in cannot also be completed.",
            searchTags = listOf("Protection Money from Costa", "Delgado", "Harbour Town", "BANDIT", "Chapter 1"),
        ),
        Quest(
            id = "R1-C1-136",
            chapter = 1,
            playOrder = 136,
            title = "Protection Money from Josh",
            category = "HARBOUR TOWN — BANDIT BRANCH",
            giver = "Delgado",
            location = "Harbour Town",
            prerequisites = "Complete Delgado's Costa collection and request another job.",
            summary = "Visit Josh at his tavern and demand payment.",
            walkthroughSteps = listOf("Start. Complete Delgado's Costa collection and request another job.", "Steps. Visit Josh at his tavern and demand payment.", "Completion. Accept Josh's 100 gold or the alternative information to close this subquest."),
            reward = "100 XP; up to 100 gold",
            warnings = "Bandit-aligned completion. The corresponding Order hand-in cannot also be completed.",
            searchTags = listOf("Protection Money from Josh", "Delgado", "Harbour Town", "BANDIT", "Chapter 1"),
        ),
        Quest(
            id = "R1-C1-137",
            chapter = 1,
            playOrder = 137,
            title = "Sebastian Wants to Know What Delgado Is Planning",
            category = "HARBOUR TOWN — SHARED",
            giver = "Sebastian",
            location = "Harbour Town",
            prerequisites = "Meet Sebastian while investigating Delgado's extortion of Costa.",
            summary = "Ask Delgado about the Costa payment before deciding who should receive it.",
            walkthroughSteps = listOf("Start. Meet Sebastian while investigating Delgado's extortion of Costa.", "Steps. Ask Delgado about the Costa payment before deciding who should receive it.", "Completion. Tell Sebastian what Delgado is planning; this information alone does not lock in the Order."),
            reward = "100 XP",
            warnings = "",
            searchTags = listOf("Sebastian Wants to Know What Delgado Is Planning", "Sebastian", "Harbour Town", "SHARED", "Chapter 1"),
        ),
        Quest(
            id = "R1-C1-138",
            chapter = 1,
            playOrder = 138,
            title = "Pretending to Work for Delgado",
            category = "HARBOUR TOWN — ORDER BRANCH",
            giver = "Sebastian",
            location = "Harbour Town",
            prerequisites = "Tell Sebastian about Delgado's scheme and offer to deceive him.",
            summary = "Collect Costa's protection-money pouch; challenge Fuller beforehand to avoid an extra fight.",
            walkthroughSteps = listOf("Start. Tell Sebastian about Delgado's scheme and offer to deceive him.", "Steps. Collect Costa's protection-money pouch; challenge Fuller beforehand to avoid an extra fight.", "Completion. Give the pouch to Sebastian instead of Delgado."),
            reward = "150 XP; cancels Delgado's Costa hand-in",
            warnings = "Order-aligned completion. The competing Bandit hand-in cannot also be completed.",
            searchTags = listOf("Pretending to Work for Delgado", "Sebastian", "Harbour Town", "ORDER", "Chapter 1"),
        ),
        Quest(
            id = "R1-C1-139",
            chapter = 1,
            playOrder = 139,
            title = "Get Rid of Delgado",
            category = "HARBOUR TOWN — ORDER BRANCH",
            giver = "Sebastian",
            location = "Harbour Town",
            prerequisites = "Give Costa's pouch to Sebastian and agree to remove Delgado.",
            summary = "Tell Delgado that the Order has obtained Costa's money.",
            walkthroughSteps = listOf("Start. Give Costa's pouch to Sebastian and agree to remove Delgado.", "Steps. Tell Delgado that the Order has obtained Costa's money.", "Completion. Report his departure to Sebastian and Carlos."),
            reward = "350 XP for Delgado's departure; 50 XP and 100 gold from Sebastian; additional Carlos reward",
            warnings = "Order-aligned completion. The competing Bandit hand-in cannot also be completed.",
            searchTags = listOf("Get Rid of Delgado", "Sebastian", "Harbour Town", "ORDER", "Chapter 1"),
        ),
        Quest(
            id = "R1-C1-140",
            chapter = 1,
            playOrder = 140,
            title = "What Is Rodriguez Planning?",
            category = "HARBOUR TOWN — SHARED",
            giver = "Cid",
            location = "Harbour Town",
            prerequisites = "Speak to Cid near his home about Rodriguez's new loyalty to the Order.",
            summary = "Find Rodriguez and ask why he changed his allegiance.",
            walkthroughSteps = listOf("Start. Speak to Cid near his home about Rodriguez's new loyalty to the Order.", "Steps. Find Rodriguez and ask why he changed his allegiance.", "Completion. Report Rodriguez's burglary investigation back to Cid."),
            reward = "125 XP",
            warnings = "",
            searchTags = listOf("What Is Rodriguez Planning?", "Cid", "Harbour Town", "SHARED", "Chapter 1"),
        ),
        Quest(
            id = "R1-C1-141",
            chapter = 1,
            playOrder = 141,
            title = "Doyle Must Disappear",
            category = "HARBOUR TOWN — BANDIT BRANCH",
            giver = "Doyle / Cid",
            location = "Harbour Town",
            prerequisites = "Identify Doyle as the burglar's spy while working for Rodriguez, then decide to protect Cid.",
            summary = "Tell Doyle to leave Harbour Town rather than turn himself in.",
            walkthroughSteps = listOf("Start. Identify Doyle as the burglar's spy while working for Rodriguez, then decide to protect Cid.", "Steps. Tell Doyle to leave Harbour Town rather than turn himself in.", "Completion. Report his disappearance to Cid; you can also give Rodriguez a neutral update."),
            reward = "200 XP; additional 150 XP from Cid",
            warnings = "Bandit-aligned completion. The corresponding Order hand-in cannot also be completed.",
            searchTags = listOf("Doyle Must Disappear", "Doyle / Cid", "Harbour Town", "BANDIT", "Chapter 1"),
        ),
        Quest(
            id = "R1-C1-142",
            chapter = 1,
            playOrder = 142,
            title = "Dances with Butchers",
            category = "HARBOUR TOWN — BANDIT BRANCH",
            giver = "Dargel",
            location = "Harbour Town",
            prerequisites = "Accept Cid's butcher extortion objective and confront Dargel.",
            summary = "Refuse to back down when Dargel attacks; defeat him without killing him.",
            walkthroughSteps = listOf("Start. Accept Cid's butcher extortion objective and confront Dargel.", "Steps. Refuse to back down when Dargel attacks; defeat him without killing him.", "Completion. The fight finishes but Cid's protection-payment objective may cancel."),
            reward = "50 quest XP plus 80 knockdown XP",
            warnings = "Bandit-aligned completion. The corresponding Order hand-in cannot also be completed.",
            searchTags = listOf("Dances with Butchers", "Dargel", "Harbour Town", "BANDIT", "Chapter 1"),
        ),
        Quest(
            id = "R1-C1-143",
            chapter = 1,
            playOrder = 143,
            title = "Clean Out Dargel's Chest",
            category = "HARBOUR TOWN — BANDIT BRANCH",
            giver = "Cid",
            location = "Harbour Town",
            prerequisites = "After Dargel refuses Cid's protection-money demand, ask Cid for the follow-up.",
            summary = "Sneak into Dargel's upper floor and pick the chest (right-right-left-left).",
            walkthroughSteps = listOf("Start. After Dargel refuses Cid's protection-money demand, ask Cid for the follow-up.", "Steps. Sneak into Dargel's upper floor and pick the chest (right-right-left-left).", "Completion. Loot the valuables and report to Cid."),
            reward = "150 XP; 50 additional XP from Cid",
            warnings = "Bandit-aligned completion. The corresponding Order hand-in cannot also be completed.",
            searchTags = listOf("Clean Out Dargel's Chest", "Cid", "Harbour Town", "BANDIT", "Chapter 1"),
        ),
        Quest(
            id = "R1-C1-144",
            chapter = 1,
            playOrder = 144,
            title = "Get Rid of Cid",
            category = "HARBOUR TOWN — ORDER BRANCH",
            giver = "Rodriguez",
            location = "Harbour Town",
            prerequisites = "Identify Doyle in the burglary investigation and order him to report to the guards.",
            summary = "Report Doyle's confession and his connection with Cid to Rodriguez.",
            walkthroughSteps = listOf("Start. Identify Doyle in the burglary investigation and order him to report to the guards.", "Steps. Report Doyle's confession and his connection with Cid to Rodriguez.", "Completion. Warn Cid that the Order knows and return to Rodriguez and Carlos."),
            reward = "350 XP on Cid's removal; 50 XP and 150 gold from Rodriguez; additional Carlos reward",
            warnings = "Order-aligned completion. The competing Bandit hand-in cannot also be completed.",
            searchTags = listOf("Get Rid of Cid", "Rodriguez", "Harbour Town", "ORDER", "Chapter 1"),
        ),
        Quest(
            id = "R1-C1-145",
            chapter = 1,
            playOrder = 145,
            title = "Bring the Packages Back to Weasel",
            category = "HARBOUR TOWN — BANDIT BRANCH",
            giver = "Weasel",
            location = "Harbour Town",
            prerequisites = "Speak with Weasel about the missing herb shipment and start following Garth.",
            summary = "Track Garth to his contact Cutter, defeat Cutter and recover the herb packages.",
            walkthroughSteps = listOf("Start. Speak with Weasel about the missing herb shipment and start following Garth.", "Steps. Track Garth to his contact Cutter, defeat Cutter and recover the herb packages.", "Completion. Return the packages to Weasel, not Marcelo."),
            reward = "300 XP and 100 gold; unlocks collection jobs",
            warnings = "Bandit-aligned completion. The corresponding Order hand-in cannot also be completed.",
            searchTags = listOf("Bring the Packages Back to Weasel", "Weasel", "Harbour Town", "BANDIT", "Chapter 1"),
        ),
        Quest(
            id = "R1-C1-146",
            chapter = 1,
            playOrder = 146,
            title = "Follow Garth Inconspicuously!",
            category = "HARBOUR TOWN — SHARED",
            giver = "Weasel",
            location = "Harbour Town",
            prerequisites = "Accept Weasel's request to follow his apprentice Garth.",
            summary = "Trail Garth at a distance through Harbour Town; ignore Lilly's distraction if you want to preserve this task.",
            walkthroughSteps = listOf("Start. Accept Weasel's request to follow his apprentice Garth.", "Steps. Trail Garth at a distance through Harbour Town; ignore Lilly's distraction if you want to preserve this task.", "Completion. Follow Garth to the Gutters meeting place without losing him."),
            reward = "200 XP; canceled by taking Lilly's alternate route",
            warnings = "",
            searchTags = listOf("Follow Garth Inconspicuously!", "Weasel", "Harbour Town", "SHARED", "Chapter 1"),
        ),
        Quest(
            id = "R1-C1-147",
            chapter = 1,
            playOrder = 147,
            title = "Nice Moments with Lilly",
            category = "HARBOUR TOWN — OPTIONAL BRANCH",
            giver = "Lilly",
            location = "Harbour Town",
            prerequisites = "Meet Lilly while tracking Garth through Harbour Town.",
            summary = "Accept her offer and pay 100 gold; abandon the uninterrupted Garth tail.",
            walkthroughSteps = listOf("Start. Meet Lilly while tracking Garth through Harbour Town.", "Steps. Accept her offer and pay 100 gold; abandon the uninterrupted Garth tail.", "Completion. Follow her toward Sonya's establishment; tell Sonya about Lilly afterward."),
            reward = "100 XP and optional 25 XP from Sonya; cancels Garth shadowing",
            warnings = "This optional choice cancels the uninterrupted Garth shadowing route.",
            searchTags = listOf("Nice Moments with Lilly", "Lilly", "Harbour Town", "OPTIONAL", "Chapter 1"),
        ),
        Quest(
            id = "R1-C1-148",
            chapter = 1,
            playOrder = 148,
            title = "Find Garth!",
            category = "HARBOUR TOWN — SHARED",
            giver = "Weasel",
            location = "Harbour Town",
            prerequisites = "Lose Garth after accepting Lilly's diversion and return to Weasel.",
            summary = "Ask Weasel where Garth might have gone.",
            walkthroughSteps = listOf("Start. Lose Garth after accepting Lilly's diversion and return to Weasel.", "Steps. Ask Weasel where Garth might have gone.", "Completion. Find Garth talking with Cutter in the Gutters."),
            reward = "100 XP",
            warnings = "",
            searchTags = listOf("Find Garth!", "Weasel", "Harbour Town", "SHARED", "Chapter 1"),
        ),
        Quest(
            id = "R1-C1-149",
            chapter = 1,
            playOrder = 149,
            title = "Get Cutter!",
            category = "HARBOUR TOWN — SHARED",
            giver = "Cutter",
            location = "Harbour Town",
            prerequisites = "Reach Cutter and Garth's meeting in the Gutters.",
            summary = "Defeat Cutter without killing him and loot his shield.",
            walkthroughSteps = listOf("Start. Reach Cutter and Garth's meeting in the Gutters.", "Steps. Defeat Cutter without killing him and loot his shield.", "Completion. Demand the missing packages from Cutter and speak again with Garth."),
            reward = "100 quest XP plus knockdown XP; 25 XP per follow-up conversation",
            warnings = "",
            searchTags = listOf("Get Cutter!", "Cutter", "Harbour Town", "SHARED", "Chapter 1"),
        ),
        Quest(
            id = "R1-C1-150",
            chapter = 1,
            playOrder = 150,
            title = "Collect Money from Alvaro",
            category = "HARBOUR TOWN — BANDIT BRANCH",
            giver = "Weasel",
            location = "Harbour Town",
            prerequisites = "Give Garth's packages to Weasel and accept a collection job targeting Alvaro.",
            summary = "Complete Walter Needs a Break and learn of Alvaro's secret blade in his locked cellar.",
            walkthroughSteps = listOf("Start. Give Garth's packages to Weasel and accept a collection job targeting Alvaro.", "Steps. Complete Walter Needs a Break and learn of Alvaro's secret blade in his locked cellar.", "Completion. Steal the blade, then sell it back to Alvaro for the original 100 gold without demanding extra."),
            reward = "175 XP",
            warnings = "Bandit-aligned completion. The corresponding Order hand-in cannot also be completed.",
            searchTags = listOf("Collect Money from Alvaro", "Weasel", "Harbour Town", "BANDIT", "Chapter 1"),
        ),
        Quest(
            id = "R1-C1-151",
            chapter = 1,
            playOrder = 151,
            title = "Collect Money from Konrad",
            category = "HARBOUR TOWN — BANDIT BRANCH",
            giver = "Weasel",
            location = "Harbour Town",
            prerequisites = "Finish Weasel's Alvaro collection and accept the job against Konrad.",
            summary = "Kill Konrad's cow Bertha at night, loot its skull and place it on Konrad's bed.",
            walkthroughSteps = listOf("Start. Finish Weasel's Alvaro collection and accept the job against Konrad.", "Steps. Kill Konrad's cow Bertha at night, loot its skull and place it on Konrad's bed.", "Completion. Sleep until the next day; calm Konrad with a Tell Joke scroll and collect his payment, then report to Weasel."),
            reward = "150 XP plus 50 XP from Weasel and 250 gold",
            warnings = "Bandit-aligned completion. The corresponding Order hand-in cannot also be completed.",
            searchTags = listOf("Collect Money from Konrad", "Weasel", "Harbour Town", "BANDIT", "Chapter 1"),
        ),
        Quest(
            id = "R1-C1-152",
            chapter = 1,
            playOrder = 152,
            title = "Evidence for Marcelo",
            category = "HARBOUR TOWN — ORDER BRANCH",
            giver = "Marcelo",
            location = "Harbour Town",
            prerequisites = "Investigate Weasel's missing packages and speak to Marcelo about using them as evidence.",
            summary = "Follow Garth and retrieve the packages from Cutter.",
            walkthroughSteps = listOf("Start. Investigate Weasel's missing packages and speak to Marcelo about using them as evidence.", "Steps. Follow Garth and retrieve the packages from Cutter.", "Completion. Give the packages to Marcelo instead of Weasel."),
            reward = "200 XP; blocks Weasel's package hand-in",
            warnings = "Order-aligned completion. The competing Bandit hand-in cannot also be completed.",
            searchTags = listOf("Evidence for Marcelo", "Marcelo", "Harbour Town", "ORDER", "Chapter 1"),
        ),
        Quest(
            id = "R1-C1-153",
            chapter = 1,
            playOrder = 153,
            title = "Hunt for Weasel",
            category = "HARBOUR TOWN — ORDER BRANCH",
            giver = "Marcelo",
            location = "Harbour Town",
            prerequisites = "Give the herb packages to Marcelo rather than Weasel.",
            summary = "Tell Weasel that the Order has obtained his shipment and he must leave.",
            walkthroughSteps = listOf("Start. Give the herb packages to Marcelo rather than Weasel.", "Steps. Tell Weasel that the Order has obtained his shipment and he must leave.", "Completion. Report his removal to Marcelo, then optionally Carlos."),
            reward = "350 XP; 50 XP and 150 gold from Marcelo; additional Carlos reward",
            warnings = "Order-aligned completion. The competing Bandit hand-in cannot also be completed.",
            searchTags = listOf("Hunt for Weasel", "Marcelo", "Harbour Town", "ORDER", "Chapter 1"),
        ),
        Quest(
            id = "R1-C1-154",
            chapter = 1,
            playOrder = 154,
            title = "Deliver Don's Inheritance to Hernandez",
            category = "HARBOUR TOWN — ORDER BRANCH",
            giver = "Hernandez",
            location = "Harbour Town",
            prerequisites = "Find the Don's heirloom amulet in the secret room behind the painting in his old Harbour Town house.",
            summary = "Tell Hernandez that you located the family heirloom.",
            walkthroughSteps = listOf("Start. Find the Don's heirloom amulet in the secret room behind the painting in his old Harbour Town house.", "Steps. Tell Hernandez that you located the family heirloom.", "Completion. Hand the amulet to Hernandez rather than Toni."),
            reward = "150 XP and 100 gold; blocks Toni's heirloom hand-in",
            warnings = "Order-aligned completion. The competing Bandit hand-in cannot also be completed.",
            searchTags = listOf("Deliver Don's Inheritance to Hernandez", "Hernandez", "Harbour Town", "ORDER", "Chapter 1"),
        ),
        Quest(
            id = "R1-C1-155",
            chapter = 1,
            playOrder = 155,
            title = "Get Rid of Toni",
            category = "HARBOUR TOWN — ORDER BRANCH",
            giver = "Hernandez",
            location = "Harbour Town",
            prerequisites = "Give Don Esteban's amulet to Hernandez and accept his request to send Toni away.",
            summary = "Tell Toni that his master's amulet is now with the Order.",
            walkthroughSteps = listOf("Start. Give Don Esteban's amulet to Hernandez and accept his request to send Toni away.", "Steps. Tell Toni that his master's amulet is now with the Order.", "Completion. Report Toni's departure to Hernandez and Carlos."),
            reward = "350 XP; 50 XP and 100 gold from Hernandez plus Carlos follow-up",
            warnings = "Order-aligned completion. The competing Bandit hand-in cannot also be completed.",
            searchTags = listOf("Get Rid of Toni", "Hernandez", "Harbour Town", "ORDER", "Chapter 1"),
        ),
        Quest(
            id = "R1-C1-156",
            chapter = 1,
            playOrder = 156,
            title = "Three Golden Bowls for Scordo",
            category = "HARBOUR TOWN — BANDIT BRANCH",
            giver = "Scordo",
            location = "Harbour Town",
            prerequisites = "Collect the three golden bowls from Dirk, Dytar and the lighthouse.",
            summary = "Meet Scordo via the brothel painting and secret passage.",
            walkthroughSteps = listOf("Start. Collect the three golden bowls from Dirk, Dytar and the lighthouse.", "Steps. Meet Scordo via the brothel painting and secret passage.", "Completion. Give the bowls to Scordo rather than Carasco."),
            reward = "250 XP and 600 gold; cancels Carasco's bowl hand-in",
            warnings = "Bandit-aligned completion. The corresponding Order hand-in cannot also be completed.",
            searchTags = listOf("Three Golden Bowls for Scordo", "Scordo", "Harbour Town", "BANDIT", "Chapter 1"),
        ),
        Quest(
            id = "R1-C1-157",
            chapter = 1,
            playOrder = 157,
            title = "Good Things Come in Threes",
            category = "HARBOUR TOWN — ORDER BRANCH",
            giver = "Carasco",
            location = "Harbour Town",
            prerequisites = "Recover all three golden bowls; find Carasco at the warehouse.",
            summary = "Give the bowls to Carasco instead of Scordo.",
            walkthroughSteps = listOf("Start. Recover all three golden bowls; find Carasco at the warehouse.", "Steps. Give the bowls to Carasco instead of Scordo.", "Completion. Select a reward and report to Carlos if your Order route is active."),
            reward = "300 XP and a choice of 200 gold, potions or scroll; Carlos follow-up",
            warnings = "Order-aligned completion. The competing Bandit hand-in cannot also be completed.",
            searchTags = listOf("Good Things Come in Threes", "Carasco", "Harbour Town", "ORDER", "Chapter 1"),
        ),
        Quest(
            id = "R1-C1-158",
            chapter = 1,
            playOrder = 158,
            title = "Lukor Wants Five Armour Plates",
            category = "HARBOUR TOWN — BANDIT BRANCH",
            giver = "Lukor",
            location = "Harbour Town",
            prerequisites = "Ask Lukor about buying the five stolen armour plates from Vasili, Ingvar and Duram.",
            summary = "Recover Vasili's plates, Ingvar's plate and Duram's plates from his locked chest.",
            walkthroughSteps = listOf("Start. Ask Lukor about buying the five stolen armour plates from Vasili, Ingvar and Duram.", "Steps. Recover Vasili's plates, Ingvar's plate and Duram's plates from his locked chest.", "Completion. Deliver all five plates to Lukor instead of Carasco."),
            reward = "300 XP and up to 400 gold",
            warnings = "Bandit-aligned completion. The corresponding Order hand-in cannot also be completed.",
            searchTags = listOf("Lukor Wants Five Armour Plates", "Lukor", "Harbour Town", "BANDIT", "Chapter 1"),
        ),
        Quest(
            id = "R1-C1-159",
            chapter = 1,
            playOrder = 159,
            title = "Vasili's Armour Plates",
            category = "HARBOUR TOWN — SHARED",
            giver = "Vasili",
            location = "Harbour Town",
            prerequisites = "Accept Lukor's or Carasco's armour plate investigation.",
            summary = "Meet Vasili at Patty's tavern and demand his armour plates.",
            walkthroughSteps = listOf("Start. Accept Lukor's or Carasco's armour plate investigation.", "Steps. Meet Vasili at Patty's tavern and demand his armour plates.", "Completion. Pay 200 gold or defeat Vasili to collect his plates."),
            reward = "50 XP and Vasili's plates",
            warnings = "",
            searchTags = listOf("Vasili's Armour Plates", "Vasili", "Harbour Town", "SHARED", "Chapter 1"),
        ),
        Quest(
            id = "R1-C1-160",
            chapter = 1,
            playOrder = 160,
            title = "Ingvar's Armour Plate",
            category = "HARBOUR TOWN — SHARED",
            giver = "Ingvar",
            location = "Harbour Town",
            prerequisites = "Start the armour plate collection, then question Ingvar at Patty's tavern.",
            summary = "Offer 50–100 gold for Ingvar's plate or challenge him to a duel.",
            walkthroughSteps = listOf("Start. Start the armour plate collection, then question Ingvar at Patty's tavern.", "Steps. Offer 50–100 gold for Ingvar's plate or challenge him to a duel.", "Completion. Take his plate and continue collecting the set."),
            reward = "50 XP and Ingvar's plate",
            warnings = "",
            searchTags = listOf("Ingvar's Armour Plate", "Ingvar", "Harbour Town", "SHARED", "Chapter 1"),
        ),
        Quest(
            id = "R1-C1-161",
            chapter = 1,
            playOrder = 161,
            title = "Duel with Ingvar",
            category = "HARBOUR TOWN — SHARED",
            giver = "Ingvar",
            location = "Harbour Town",
            prerequisites = "During Ingvar's armour plate negotiation, challenge him to a fight.",
            summary = "Follow him outside behind Patty's tavern.",
            walkthroughSteps = listOf("Start. During Ingvar's armour plate negotiation, challenge him to a fight.", "Steps. Follow him outside behind Patty's tavern.", "Completion. Knock Ingvar out and take the plate."),
            reward = "100 quest XP and 50 XP follow-up",
            warnings = "",
            searchTags = listOf("Duel with Ingvar", "Ingvar", "Harbour Town", "SHARED", "Chapter 1"),
        ),
        Quest(
            id = "R1-C1-162",
            chapter = 1,
            playOrder = 162,
            title = "Duram's Armour Plates",
            category = "HARBOUR TOWN — SHARED",
            giver = "Duram",
            location = "Harbour Town",
            prerequisites = "Start the five armour plate collection and locate Duram at the pier.",
            summary = "Ask Ukkos about Duram's protection and give Ukkos food.",
            walkthroughSteps = listOf("Start. Start the five armour plate collection and locate Duram at the pier.", "Steps. Ask Ukkos about Duram's protection and give Ukkos food.", "Completion. Enter Duram's house and open the locked chest (left-left-right-left-right-right); tell Duram about the theft."),
            reward = "50 XP for chest and 50 XP for reporting to Duram",
            warnings = "",
            searchTags = listOf("Duram's Armour Plates", "Duram", "Harbour Town", "SHARED", "Chapter 1"),
        ),
        Quest(
            id = "R1-C1-163",
            chapter = 1,
            playOrder = 163,
            title = "Meat for Ukkos",
            category = "HARBOUR TOWN — SHARED",
            giver = "Ukkos",
            location = "Harbour Town",
            prerequisites = "Speak to Ukkos while investigating Duram's armour plates.",
            summary = "Buy or cook a portion of fried meat.",
            walkthroughSteps = listOf("Start. Speak to Ukkos while investigating Duram's armour plates.", "Steps. Buy or cook a portion of fried meat.", "Completion. Give the meat to Ukkos to gain access to Duram's stash."),
            reward = "100 XP",
            warnings = "",
            searchTags = listOf("Meat for Ukkos", "Ukkos", "Harbour Town", "SHARED", "Chapter 1"),
        ),
        Quest(
            id = "R1-C1-164",
            chapter = 1,
            playOrder = 164,
            title = "Carasco Wants Five Armour Plates",
            category = "HARBOUR TOWN — ORDER BRANCH",
            giver = "Carasco",
            location = "Harbour Town",
            prerequisites = "Collect all five plates from Vasili, Ingvar and Duram.",
            summary = "Find Carasco at the harbour warehouse.",
            walkthroughSteps = listOf("Start. Collect all five plates from Vasili, Ingvar and Duram.", "Steps. Find Carasco at the harbour warehouse.", "Completion. Deliver the plates to Carasco rather than Lukor."),
            reward = "250 XP plus one chosen reward of gold, potions or a scroll",
            warnings = "Order-aligned completion. The competing Bandit hand-in cannot also be completed.",
            searchTags = listOf("Carasco Wants Five Armour Plates", "Carasco", "Harbour Town", "ORDER", "Chapter 1"),
        ),
        Quest(
            id = "R1-C1-165",
            chapter = 1,
            playOrder = 165,
            title = "Get Rid of Lukor",
            category = "HARBOUR TOWN — ORDER BRANCH",
            giver = "Carasco",
            location = "Harbour Town",
            prerequisites = "Give the five armour plates to Carasco rather than Lukor.",
            summary = "Tell Lukor that the Order now has the plates and he must leave town.",
            walkthroughSteps = listOf("Start. Give the five armour plates to Carasco rather than Lukor.", "Steps. Tell Lukor that the Order now has the plates and he must leave town.", "Completion. Return to Carasco for the remaining item rewards and report to Carlos."),
            reward = "350 XP; optional 50 XP and 150 gold from Carlos",
            warnings = "Order-aligned completion. The competing Bandit hand-in cannot also be completed.",
            searchTags = listOf("Get Rid of Lukor", "Carasco", "Harbour Town", "ORDER", "Chapter 1"),
        ),
        Quest(
            id = "R1-C1-166",
            chapter = 1,
            playOrder = 166,
            title = "Sergio Wants Romanov's Gold",
            category = "HARBOUR TOWN — ORDER BRANCH",
            giver = "Sergio",
            location = "Harbour Town",
            prerequisites = "Obtain Romanov's casket from the loft of the harbour warehouse.",
            summary = "Meet Sergio on the pier near Romanov's prison and ask about the gold.",
            walkthroughSteps = listOf("Start. Obtain Romanov's casket from the loft of the harbour warehouse.", "Steps. Meet Sergio on the pier near Romanov's prison and ask about the gold.", "Completion. Give the casket to Sergio rather than Romanov; report to Carlos."),
            reward = "200 XP and 100 gold from Sergio; Carlos follow-up XP/gold",
            warnings = "Order-aligned completion. The competing Bandit hand-in cannot also be completed.",
            searchTags = listOf("Sergio Wants Romanov's Gold", "Sergio", "Harbour Town", "ORDER", "Chapter 1"),
        ),
        Quest(
            id = "R1-C1-167",
            chapter = 1,
            playOrder = 167,
            title = "Where Are the Artifacts Disappearing To?",
            category = "HARBOUR TOWN — ORDER BRANCH",
            giver = "Carlos",
            location = "Harbour Town",
            prerequisites = "Secure at least four Harbour Town faction cases for the Order and receive Carlos's smuggling inquiry.",
            summary = "Question Sonya at the brothel about smugglers and learn how to find Scordo.",
            walkthroughSteps = listOf("Start. Secure at least four Harbour Town faction cases for the Order and receive Carlos's smuggling inquiry.", "Steps. Question Sonya at the brothel about smugglers and learn how to find Scordo.", "Completion. Open the secret passage behind the painting, confront Scordo and report to Carlos."),
            reward = "500 XP plus dialogue follow-up XP",
            warnings = "Order-aligned completion. The competing Bandit hand-in cannot also be completed.",
            searchTags = listOf("Where Are the Artifacts Disappearing To?", "Carlos", "Harbour Town", "ORDER", "Chapter 1"),
        ),
        Quest(
            id = "R1-C1-168",
            chapter = 1,
            playOrder = 168,
            title = "Get Rid of Scordo",
            category = "HARBOUR TOWN — ORDER BRANCH",
            giver = "Carlos",
            location = "Harbour Town",
            prerequisites = "Finish four Order-aligned Harbour Town cases and investigate the Don's smuggler Scordo.",
            summary = "Enter the hideout behind the brothel painting and defeat Scordo.",
            walkthroughSteps = listOf("Start. Finish four Order-aligned Harbour Town cases and investigate the Don's smuggler Scordo.", "Steps. Enter the hideout behind the brothel painting and defeat Scordo.", "Completion. Finish the fight by killing Scordo as specifically required, then report to Carlos."),
            reward = "500 XP quest reward; optional 100 XP for knocking out Scordo",
            warnings = "Order-aligned completion. The competing Bandit hand-in cannot also be completed.",
            searchTags = listOf("Get Rid of Scordo", "Carlos", "Harbour Town", "ORDER", "Chapter 1"),
        ),
        Quest(
            id = "R1-C1-169",
            chapter = 1,
            playOrder = 169,
            title = "Scordo's Key",
            category = "HARBOUR TOWN — ORDER BRANCH",
            giver = "Scordo / auto discovery",
            location = "Harbour Town",
            prerequisites = "Defeat Scordo in his hidden Harbour Town storeroom on the Order route.",
            summary = "Search Scordo's inventory after the fight.",
            walkthroughSteps = listOf("Start. Defeat Scordo in his hidden Harbour Town storeroom on the Order route.", "Steps. Search Scordo's inventory after the fight.", "Completion. Take Scordo's key to open the sewer exit."),
            reward = "100 XP",
            warnings = "Order-aligned completion. The competing Bandit hand-in cannot also be completed.",
            searchTags = listOf("Scordo's Key", "Scordo / auto discovery", "Harbour Town", "ORDER", "Chapter 1"),
        ),
        Quest(
            id = "R1-C1-170",
            chapter = 1,
            playOrder = 170,
            title = "Knock Out Scordo",
            category = "HARBOUR TOWN — ORDER BRANCH",
            giver = "Scordo",
            location = "Harbour Town",
            prerequisites = "Find Scordo in his hideout during Carlos's smuggling investigation.",
            summary = "Challenge or provoke Scordo and defeat him non-lethally.",
            walkthroughSteps = listOf("Start. Find Scordo in his hideout during Carlos's smuggling investigation.", "Steps. Challenge or provoke Scordo and defeat him non-lethally.", "Completion. Confirm the unconscious state before resolving his other Order objectives."),
            reward = "100 XP plus combat XP",
            warnings = "Order-aligned completion. The competing Bandit hand-in cannot also be completed.",
            searchTags = listOf("Knock Out Scordo", "Scordo", "Harbour Town", "ORDER", "Chapter 1"),
        )
    )
}
