package com.sliverzfx.gothicquest

/** Remaining standalone Risen journal objectives verified against game-specific original quest references. */
internal object RisenGuidePart15Data {
    val quests: List<Quest> = listOf(
        Quest(
            id = "R1-C1-198",
            chapter = 1,
            playOrder = 198,
            title = "Find all the vassal rings",
            category = "CHAPTER 1 — STANDALONE JOURNAL QUEST",
            giver = "Automatic — The Cursed Lords",
            location = "Five ruined towers and Leon's farm",
            prerequisites = "Accept The Cursed Lords from Leon and start gathering the undead vassals' rings.",
            summary = "Collect five rings from undead lords in five ruined fortresses. Leon supplies the sixth ring.",
            walkthroughSteps = listOf("Accept The Cursed Lords from Leon and start gathering the undead vassals' rings.", "Travel to each of the five ruined castles and defeat its undead lord. Collect that lord's ring.", "Return to Leon for the sixth ring. The six-ring collection objective then completes."),
            reward = "500 XP",
            warnings = "The collection requires five undead lords plus Leon's ring, not six undead lords.",
            searchTags = listOf("Find all the vassal rings", "Automatic — The Cursed Lords", "Five ruined towers and Leon's farm", "Risen 1", "journal quest"),
        ),
        Quest(
            id = "R1-C1-199",
            chapter = 1,
            playOrder = 199,
            title = "Find the large temple entrance in the east",
            category = "CHAPTER 1 — STANDALONE JOURNAL QUEST",
            giver = "Automatic — Fincher's eastern temple lead",
            location = "Eastern temple complex",
            prerequisites = "Learn from Fincher about the unusual eastern temple entrance while pursuing the Bandit Camp excavation chain.",
            summary = "Find the entrance of the large temple in the eastern wilderness.",
            walkthroughSteps = listOf("Learn from Fincher about the unusual eastern temple entrance while pursuing the Bandit Camp excavation chain.", "Travel east from the Bandit Camp, following the eastern temple lead.", "Identify the large temple entrance, which awards this discovery quest. Return to Fincher for the separate report."),
            reward = "250 XP",
            warnings = "This Chapter 1 discovery task is separate from the deeper Chapter 2 Eastern Temple expedition.",
            searchTags = listOf("Find the large temple entrance in the east", "Automatic — Fincher's eastern temple lead", "Eastern temple complex", "Risen 1", "journal quest"),
        ),
        Quest(
            id = "R1-C1-200",
            chapter = 1,
            playOrder = 200,
            title = "Report to Master Pallas!",
            category = "CHAPTER 1 — STANDALONE JOURNAL QUEST",
            giver = "Automatic — Order initiation follow-up",
            location = "Volcano Keep",
            prerequisites = "Finish the Order's Harbour Town assistance quest, then receive the instruction to report to Pallas.",
            summary = "Report your completed Harbour Town duties to Pallas at Volcano Keep.",
            walkthroughSteps = listOf("Finish the Order's Harbour Town assistance quest, then receive the instruction to report to Pallas.", "After resolving the required Order cases in Harbour Town, travel to Volcano Keep.", "Find Master Pallas at the entrance/admin area and tell him that you helped the Order to complete the report."),
            reward = "250 XP and 100 gold from Pallas",
            warnings = "Order-route quest; not a Bandit prerequisite.",
            searchTags = listOf("Report to Master Pallas!", "Automatic — Order initiation follow-up", "Volcano Keep", "Risen 1", "journal quest"),
        ),
        Quest(
            id = "R1-C1-201",
            chapter = 1,
            playOrder = 201,
            title = "Take 15 tool bags from the gnomes",
            category = "CHAPTER 1 — STANDALONE JOURNAL QUEST",
            giver = "Automatic collection journal objective",
            location = "Wilderness, gnome camps",
            prerequisites = "Start encountering gnomes carrying stolen bags of tools, during or before Walter's collection request.",
            summary = "Collect fifteen stolen tool bags; delivery to Walter is a separate quest.",
            walkthroughSteps = listOf("Start encountering gnomes carrying stolen bags of tools, during or before Walter's collection request.", "Fight gnomes during exploration and loot those carrying stolen tool bags.", "When you have collected fifteen bags, this subquest ends. Bring them to Walter for Everything That Isn't Nailed Down."),
            reward = "500 XP",
            warnings = "Separate the 15-bag collection objective from Walter's final hand-in.",
            searchTags = listOf("Take 15 tool bags from the gnomes", "Automatic collection journal objective", "Wilderness, gnome camps", "Risen 1", "journal quest"),
        ),
        Quest(
            id = "R1-C1-202",
            chapter = 1,
            playOrder = 202,
            title = "Trick Aric",
            category = "CHAPTER 1 — STANDALONE JOURNAL QUEST",
            giver = "Caspar",
            location = "Volcano Keep training arena",
            prerequisites = "Lose or forfeit an initial duel to Aric during Basic Training, then speak to William and Caspar.",
            summary = "Make Aric easier to beat by getting him drunk and replacing his charmed blade.",
            walkthroughSteps = listOf("Lose or forfeit an initial duel to Aric during Basic Training, then speak to William and Caspar.", "After the lost duel, ask William and then Caspar for advice. Obtain the Fireflush wine from Dalman, two ordinary wines, and the Worst Sword in the World from Karlsen.", "Give Aric the two wines followed by Fireflush; trade him the terrible sword for his charmed weapon. Challenge him again and defeat him."),
            reward = "Training progression; a separate numeric XP reward could not be verified",
            warnings = "Optional alternative to beating Aric fairly; quest only appears on this route.",
            searchTags = listOf("Trick Aric", "Caspar", "Volcano Keep training arena", "Risen 1", "journal quest"),
        ),
        Quest(
            id = "R1-C1-203",
            chapter = 1,
            playOrder = 203,
            title = "Golden fragments",
            category = "CHAPTER 1 — STANDALONE JOURNAL QUEST",
            giver = "Automatic Golden Sword collection",
            location = "Bandit Camp and surrounding swamp",
            prerequisites = "Learn about Oscar's Golden Sword and begin collecting its five broken fragments.",
            summary = "Collect all five Golden Sword pieces before handing them to Oscar.",
            walkthroughSteps = listOf("Learn about Oscar's Golden Sword and begin collecting its five broken fragments.", "Recover one fragment from Luis for two beers; obtain another from Craig by winning or buying; loot Brogar after the arena challenge or pickpocket him.", "Take one fragment from Dorgan's body in the swamp cave and another from the excavation island chest. The five-fragment discovery quest ends; return to Oscar for the separate reforging reward."),
            reward = "400 XP for collecting five fragments; Oscar's reforging gives additional XP",
            warnings = "Do not merge the five-fragment collection reward with Oscar's separate completion reward.",
            searchTags = listOf("Golden fragments", "Automatic Golden Sword collection", "Bandit Camp and surrounding swamp", "Risen 1", "journal quest"),
        )
    )
}
