package com.sliverzfx.gothicquest

internal object Risen3Chapter4Data {
    val quests: List<Quest> = listOf(
        Quest(
            id = "R3-C4-001",
            chapter = 4,
            playOrder = 1,
            title = "The Traitor",
            aliases = listOf(),
            category = "CHAPTER 4 — MAIN STORY",
            giver = "Bones",
            location = "Kila → Taranis",
            prerequisites = "",
            summary = "Talk to Margoloth and Bones after the Spirit Ritual, then travel to Taranis and confront Horas near the Mages Camp.",
            walkthroughSteps = listOf("Chapter 2 — Kila — F. LATER KILA QUESTS — DO NOT DO YET", "Later main-story Kila content. It is a real canonical quest but is deliberately deferred from the Chapter 2 pre-faction route.", "Chapter 2 — Taranis — I. LATER / POST-FACTION TARANIS QUESTS — DEFER", "Later main-story Taranis content. It is a real quest but is intentionally deferred from the Chapter 2 pre-faction route.", "Chapter 4 —  — A. THE TRAITOR", "Quest giver: Bones", "Area: Kila → Taranis", "Status: CHAPTER 4 — MAIN STORY", "Reward: Major Chapter 4 progression", "Walkthrough. Remain in Margoloth's den after the ritual. Speak with Margoloth about Nekroloth, then talk to Bones. Bones identifies Horas as the traitor. Before leaving, visit your faction headquarters and claim any available promotion/armor upgrade. Sail to Taranis, go to the Mages Camp and follow the northern path toward the reactor area. Horas confronts you and knocks you down, triggering the Ore Titan battle.", "Completion. Defeat the Ore Titan using the five magical restraints, then finish the confrontation with Horas.", "Related: Pirate Alliance / final fleet phase"),
            reward = "Major Chapter 4 progression",
            warnings = "⚠ Important: The Ore Titan cannot be beaten by normal damage. The fight is about chaining it with all five magical restraints placed around the arena.",
            searchTags = listOf("Kila", "Taranis", "", "F. LATER KILA QUESTS — DO NOT DO YET", "I. LATER / POST-FACTION TARANIS QUESTS — DEFER", "A. THE TRAITOR"),
        ),
        Quest(
            id = "R3-C4-002",
            chapter = 4,
            playOrder = 2,
            title = "Pirate Alliance",
            aliases = listOf(),
            category = "MAIN STORY — FLEET ASSEMBLY",
            giver = "Admiral Alvarez",
            location = "Antigua / world map",
            prerequisites = "",
            summary = "Gain control/support of the ships belonging to the game's major factions so Alvarez can oppose Crow's ghost fleet.\nMeet Jake aboard the Native ship and learn that he will only hand over command after you recover part of your soul and support the Natives.\nSpeak with Neron and learn that the Taranis ship becomes yours only after joining the Guardians.\nSecure command/support of all five required ships, then report back to Alvarez.",
            walkthroughSteps = listOf("Chapter 2 — Antigua — B. ALVAREZ & THE MAIN STORY", "Quest giver: Admiral Alvarez", "Status: LONG-TERM MAIN STORY — ALLIANCE PARENT", "Area: Antigua", "Reward: 1200 Glory at major completion milestones", "Walkthrough. After Chaos in Harbour Town, Alvarez explains the need for a united fleet. This becomes a long-term parent quest spanning Calador, Kila, Taranis and the other alliance routes. Do not expect to finish it on Antigua.", "Completion. The quest remains active while you visit and gain standing with the main factions.", "Related: Calador / Kila / Taranis faction ships", "Chapter 2 — Kila — E. PIRATE ALLIANCE — KILA SHIP", "Quest giver: Admiral Alvarez / Jake", "Status: LONG-TERM — FACTION SHIP", "Area: Kila", "Reward: 1200 Glory when the ship is eventually secured", "Walkthrough. Swim or row to the ship anchored near the pirates' beach and speak with Jake. He recognizes the hero but refuses to give up command yet.", "Completion. The Kila ship step remains pending until you actually join/support the Natives later.", "Chapter 2 — Taranis — H. PIRATE ALLIANCE — TARANIS SHIP", "Quest giver: Admiral Alvarez / Neron", "Status: LONG-TERM — FACTION SHIP", "Area: Taranis", "Reward: 1200 Glory when eventually secured", "Walkthrough. Find Neron at the Taranis ship and discuss command. He will not hand over the vessel while you are still faction-neutral. After joining the Guardians, return and speak with him again.", "Completion. The Taranis ship step remains pending.", "Chapter 4 —  — B. FINISH PIRATE ALLIANCE", "Quest giver: Admiral Alvarez", "Area: Antigua / world map", "Status: MAIN STORY — FLEET ASSEMBLY", "Reward: 2000 Glory; 200 Glory + 500 Gold reported per vessel in the full fleet sequence", "Walkthrough. Pirate Alliance began on Antigua after Chaos in Harbour Town. By Chapter 4, finish any remaining ship requirements. The fleet consists of the three major faction ships plus the Inquisition vessel and the Renegade Pirate vessel. The faction ship tied to your chosen guild should now be available after your initiation. The Inquisition and Renegade Pirate ships are obtained through their naval battle questlines.", "Completion. Return to Alvarez after all five vessels are secured.", "Related: Sea Battle Against Sebastiano / Sea Battle Against Morgan / Sea Battle Against Crow"),
            reward = "2000 Glory; 200 Glory + 500 Gold reported per vessel in the full fleet sequence",
            warnings = "⚠ Important: Pirate Alliance does not force a faction choice here. Explore the faction islands before committing.\n⚠ Important: You do NOT need to join the Natives during this first visit.\n⚠ Important: Do NOT join the Guardians merely to finish this now. Keep it pending until the dedicated faction-choice section.\n⚠ Important: Do not go after Crow until every ship you want for the alliance has been acquired.",
            searchTags = listOf("Antigua", "Kila", "Taranis", "", "B. ALVAREZ & THE MAIN STORY", "E. PIRATE ALLIANCE — KILA SHIP", "H. PIRATE ALLIANCE — TARANIS SHIP", "B. FINISH PIRATE ALLIANCE"),
        ),
        Quest(
            id = "R3-C4-003",
            chapter = 4,
            playOrder = 3,
            title = "Sea Battle Against Crow",
            aliases = listOf(),
            category = "CHAPTER 4 — MAIN STORY / NAVAL BATTLE",
            giver = "Trigger quest",
            location = "At sea",
            prerequisites = "",
            summary = "Board Crow's ghost ship, defeat the Minions, kill the Shadow Guardian and then defeat Crow.",
            walkthroughSteps = listOf("Walkthrough. Once the fleet is ready, sail and trigger the battle against Crow's ghost fleet. On board, keep moving while clearing the numerous Minions so you are not boxed in. Next comes a Shadow Guardian; dodge or parry its heavy attacks and heal before your health becomes critical. Finally fight Crow. Ranged attacks make the duel easier because Crow is much more dangerous at close range.", "Completion. Kill Crow. Bones finds a map revealing Skull Island.", "Related: Evil's Refuge"),
            reward = "1150 Glory",
            warnings = "⚠ Important: Defeating Crow unlocks Skull Island and the main quest Evil's Refuge.",
            searchTags = listOf("", "B. FINISH PIRATE ALLIANCE"),
        ),
        Quest(
            id = "R3-C4-004",
            chapter = 4,
            playOrder = 4,
            title = "Evil's Refuge",
            aliases = listOf(),
            category = "FINAL MAIN STORY PARENT",
            giver = "Bones",
            location = "Skull Island",
            prerequisites = "",
            summary = "Land on Skull Island, help establish the allied camp, meet My Spirit, rescue the three mages, then return to Nekroloth's cave.",
            walkthroughSteps = listOf("Walkthrough. After Crow dies, speak with Bones to learn Skull Island's location. Sail there and row ashore. Immediately help your allies repel the first Shadow attack, then move north toward the cave entrance where My Spirit waits. The Spirit explains that Eldric, Chani and Zacharias are imprisoned around the island and starts Reunion.", "Completion. After completing Reunion, return to the same northern cave. Enter it to confront Nekroloth, which completes Evil's Refuge and starts Death Incarnate.", "Related: Reunion / Death Incarnate"),
            reward = "1000 Glory",
            warnings = "⚠ Important: Skull Island is NOT a one-way trip at first. You can leave and return until you actually enter Nekroloth's final cave.",
            searchTags = listOf("", "C. SKULL ISLAND — ARRIVAL"),
        ),
        Quest(
            id = "R3-C4-005",
            chapter = 4,
            playOrder = 5,
            title = "To Victory",
            aliases = listOf(),
            category = "OPTIONAL — ALLIED ASSAULT",
            giver = "Kane",
            location = "Skull Island",
            prerequisites = "",
            summary = "Join Kane's assault on the monsters around the two towers and kill the Shadow Lord of Fury.",
            walkthroughSteps = listOf("Walkthrough. Speak with Kane in the allied camp and agree to join the assault. Head north toward the two towers with the group. Focus the Shadow Lord of Fury first, because it is the most dangerous enemy in the group.", "Completion. Clear the tower area and report back to Kane."),
            reward = "Side-quest Glory",
            warnings = "⚠ Important: Completing this makes later routes around the towers much safer.",
            searchTags = listOf("", "D. SKULL ISLAND SIDE QUESTS — DO BEFORE FINAL CAVE"),
        ),
        Quest(
            id = "R3-C4-006",
            chapter = 4,
            playOrder = 6,
            title = "The Minions' Weapons Store",
            aliases = listOf(),
            category = "OPTIONAL — MULTI-AREA COMBAT",
            giver = "Kane",
            location = "Skull Island",
            prerequisites = "",
            summary = "Destroy/secure the Minions' weapon depots around Skull Island and help the allied captains reclaim the supplies.",
            walkthroughSteps = listOf("Walkthrough. Kane points you toward several weapons depots. Talk to Jake, Neron and the other allied commanders as you sweep the island. Each depot is guarded by Shadows or a Shadow Lord. Clear the enemies and secure the area before moving on.", "Completion. Return/report after all required depots are secured."),
            reward = "Quest Glory + choice of powerful reward",
            warnings = "⚠ Important: The reward choice can include a strong melee weapon, firearm, high-level scrolls or gold. Pick the reward that matches your build.",
            searchTags = listOf("", "D. SKULL ISLAND SIDE QUESTS — DO BEFORE FINAL CAVE"),
        ),
        Quest(
            id = "R3-C4-007",
            chapter = 4,
            playOrder = 7,
            title = "Experimental Nutrition",
            aliases = listOf(),
            category = "OPTIONAL — COLLECTION",
            giver = "Rodas",
            location = "Skull Island",
            prerequisites = "",
            summary = "Kill Gorged Ghouls west of the two towers and collect 8 pieces of Shadow Meat.",
            walkthroughSteps = listOf("Walkthrough. Talk to Rodas in the allied camp. Travel north to the two towers, then use the western tower route to reach the target area. Kill Gorged Ghouls and loot every corpse until you have 8 Shadow Meat.", "Completion. Return all 8 pieces to Rodas.", "Related: Grub is Up!"),
            reward = "100 Glory",
            warnings = "⚠ Important: This unlocks Grub is Up!.",
            searchTags = listOf("", "D. SKULL ISLAND SIDE QUESTS — DO BEFORE FINAL CAVE"),
        ),
        Quest(
            id = "R3-C4-008",
            chapter = 4,
            playOrder = 8,
            title = "Grub is Up!",
            aliases = listOf(),
            category = "OPTIONAL — FOLLOW-UP",
            giver = "Rodas",
            location = "Skull Island",
            prerequisites = "",
            summary = "Ask Kidlat to help Rodas prepare the Shadow Meat, then wait a day and return.",
            walkthroughSteps = listOf("Walkthrough. After Experimental Nutrition, talk to Kidlat in camp and ask him to help. Return to Rodas, then sleep or otherwise pass about one day. Speak with Rodas again.", "Completion. Receive the purified meat and complete the quest."),
            reward = "400 Glory + 5 Purified Shadow Meat",
            warnings = "",
            searchTags = listOf("", "D. SKULL ISLAND SIDE QUESTS — DO BEFORE FINAL CAVE"),
        ),
        Quest(
            id = "R3-C4-009",
            chapter = 4,
            playOrder = 9,
            title = "The Decoy",
            aliases = listOf(),
            category = "OPTIONAL — SHADOW LORD",
            giver = "Skull Island ally",
            location = "Skull Island",
            prerequisites = "",
            summary = "Use the decoy plan to draw out and kill the targeted Shadow Lord.",
            walkthroughSteps = listOf("Walkthrough. Accept the plan at the allied camp, travel to the marked area and follow the setup until the Shadow Lord appears. Use your companion/allied support and focus the boss before dealing with lesser adds.", "Completion. Kill the target and report back."),
            reward = "Quest Glory",
            warnings = "",
            searchTags = listOf("", "D. SKULL ISLAND SIDE QUESTS — DO BEFORE FINAL CAVE"),
        ),
        Quest(
            id = "R3-C4-010",
            chapter = 4,
            playOrder = 10,
            title = "Reunion",
            aliases = listOf(),
            category = "FINAL MAIN STORY — RESCUE",
            giver = "My Spirit",
            location = "Skull Island",
            prerequisites = "",
            summary = "Free Zacharias, Chani and Eldric in any order, then return to My Spirit.",
            walkthroughSteps = listOf("Walkthrough. My Spirit starts this quest at the northern cave entrance. The three mages are held in different parts of Skull Island. You can rescue them in any order, but the bridge route to Zacharias is the simplest first objective, followed by Chani's Tower of Torture and finally Eldric's hidden northeastern cave.", "Completion. After all three are free, return to My Spirit at the northern cave entrance.", "Related: Evil's Refuge"),
            reward = "3000 Glory",
            warnings = "⚠ Important: The Tower of Torture is the most navigation-heavy section; use Parrot Flight if you want to shorten some vertical traversal.",
            searchTags = listOf("", "E. REUNION — RESCUE THE THREE MAGES"),
        ),
        Quest(
            id = "R3-C4-011",
            chapter = 4,
            playOrder = 11,
            title = "Death Incarnate",
            aliases = listOf(),
            category = "FINAL QUEST",
            giver = "Trigger quest",
            location = "Nekroloth's cave",
            prerequisites = "",
            summary = "Enter Nekroloth's cave, survive the final battle and drain the Titan of Death's entire health bar.",
            walkthroughSteps = listOf("Walkthrough. After Reunion, enter the cave where My Spirit first appeared. Nekroloth transforms into the Titan of Death and the final battle begins. You fight while controlling the hero's spirit. Keep your attention on Nekroloth and only deal with lesser enemies when they interfere. A pillar/spire of light in the centre of the arena restores health when you pass through it. Use it aggressively instead of wasting all consumables. Summoned creatures such as Hellhounds or Shadow Warriors are excellent distractions if your build supports them.", "Completion. Reduce the Titan of Death's health to zero and watch the ending cutscenes."),
            reward = "2000 Glory",
            warnings = "⚠ Important: Once this quest begins, you cannot leave the final area. There is no New Game Plus or normal post-game free roam after the ending.",
            searchTags = listOf("", "G. FINAL BOSS"),
        ),
    )

    val notes: List<RisenGuideNote> = listOf(
        RisenGuideNote(4, 1, "Chapter 4 overview", listOf("The Traitor • Skull Island • Nekroloth • Finale")),
        RisenGuideNote(4, 1, "Chapter 4 structure", listOf("Chapter 4 begins immediately after the failed Spirit Ritual on Kila. Nekroloth escapes with Eldric, Chani and Zacharias, while Bones identifies Horas as the traitor. From here the main story has three stages: deal with Horas on Taranis, finish the fleet and defeat Crow, then assault Skull Island and rescue the three mages before facing Nekroloth.", "Important cleanup rule: Before chasing Horas, return to your chosen faction headquarters and claim the next rank/armor upgrade if available. Chapter 4 is also the best time to finish faction-exclusive and crew quests before the final Skull Island point of no return.")),
        RisenGuideNote(4, 2, "Ore Titan combat mechanics", listOf("There are five magical restraints/energy anchors around the arena.", "Wait for the Titan to expose a limb or suitable target during its attack animation.", "Use each restraint on the Titan rather than trying to reduce its health normally.", "Bind the arms/limbs first and finish with the final restraint on the upper body/head area.", "Keep moving between anchors; do not stay underneath the Titan.", "After all five restraints are attached, the encounter resolves and Horas can be dealt with.")),
        RisenGuideNote(4, 3, "Fleet checklist", listOf("Demon Hunter / Calador faction ship OR chosen equivalent faction vessel.", "Native / Kila ship with Jake if on the Native route.", "Guardian / Taranis ship with Neron if on the Guardian route.", "Inquisition ship through the Sebastiano naval-battle route.", "Renegade Pirate ship through the Morgan naval-battle route.", "Report full fleet status to Admiral Alvarez.")),
        RisenGuideNote(4, 11, "Zacharias — Berserker Pass bridge", listOf("Approach the large bridge from either side of Berserker Pass.", "Kill the Minions guarding the bridge.", "Find the stairs leading to the bridge's upper level.", "Interact with Zacharias to free him.", "Reward for freeing Zacharias: 500 Glory.")),
        RisenGuideNote(4, 11, "Chani — Tower of Torture", listOf("Reach the western Tower of Torture across the lava area; narrow planks or Parrot Flight both work.", "Climb to the upper exterior balconies and use the first lever to open the tower.", "Inside, fight the Shadow Guardian and use the sequence of levers to rotate the central metal walkways.", "Keep descending until you reach the balconies above Chani's cell.", "Pull the last lever to open the cell.", "Kill or bypass the Soul Eater guarding the entrance.", "Free Chani for 500 Glory.")),
        RisenGuideNote(4, 11, "Eldric — northeastern hidden cave", listOf("Travel to the northeastern islet.", "Climb to the ruins on the highest hill.", "Locate the hidden manhole/ladder in the ruins.", "Descend into the cavern.", "Fight or bypass the two Ore Golems near Eldric.", "Free Eldric for 500 Glory.", "Use the nearby lever to open the exit route.")),
        RisenGuideNote(4, 11, "F. FINAL POINT OF NO RETURN", listOf("After Reunion, My Spirit is restored and the way into Nekroloth's cave is open. THIS is the real final point of no return. Before entering, finish every side quest, buy ammunition/scrolls, repair/equip your best gear, talk to any crew members whose dialogue you care about, and create a permanent manual save.", "Finish Skull Island side quests.", "Finish faction promotion/armor quests.", "Finish crew quests you care about.", "Buy healing consumables.", "Buy ammunition or combat scrolls for your build.", "Equip the best available armor and weapons.", "Create a permanent manual save outside Nekroloth's cave.")),
        RisenGuideNote(4, 12, "FINAL BOSS CHECKLIST", listOf("Use the central light spire whenever health drops.", "Prioritize damage on the Titan of Death.", "Kill lesser enemies only when they block movement or overwhelm you.", "Summons are useful for distracting adds.", "Ranged builds should keep maximum distance and circle the arena.", "Melee builds should attack in short windows and retreat before long counter-combos.", "Do not enter the cave without a permanent pre-fight save.")),
        RisenGuideNote(4, 12, "RISEN 3 — FINAL COMPLETION CHECKLIST", listOf("The Spirit Ritual is complete.", "The Traitor is complete.", "The Ore Titan has been defeated.", "Pirate Alliance is complete.", "Crow has been defeated.", "Skull Island is unlocked.", "Evil's Refuge is active/completed through the cave stage.", "Optional Skull Island side quests were completed as desired.", "Zacharias has been rescued.", "Chani has been rescued.", "Eldric has been rescued.", "Reunion is complete.", "A permanent save exists outside Nekroloth's cave.", "Death Incarnate is complete.", "Risen 3 ending viewed.")),
        RisenGuideNote(4, 12, "CANONICAL SKULL ISLAND QUEST INDEX", listOf("Main quests:", "Evil's Refuge", "Reunion", "Death Incarnate", "Side quests:", "The Minions' Weapons Store", "To Victory", "Experimental Nutrition", "Grub is Up!", "The Decoy")),
    )
}
