package com.sliverzfx.gothicquest

internal object RisenGuidePart5Data {
    val quests: List<Quest> = listOf(
        Quest(
            id = "R1-C2-001",
            chapter = 2,
            playOrder = 1,
            title = "Crystal Disks for the Inquisitor",
            category = "MAIN QUEST",
            giver = "Inquisitor Mendoza",
            location = "World / Chapter 2",
            prerequisites = "",
            summary = "Recover all five Golden Crystal Disks and return them to Mendoza at the volcano gate.",
            walkthroughSteps = listOf("Walkthrough. After following Mendoza at the end of Chapter 1, speak with him at the great sealed gate. Ask about every disk lead. The five-disk hunt is a parent quest: Don Esteban has one, the Gyrger carries one, the Eastern Temple priest carries one, Eldric repairs the damaged disk from Cyrus, and the west-coast Steelbeard/Romanov chain yields the final disk.", "Completion. Do not hand over the full set until all Chapter 2 side content you want is complete; turning in all five disks opens the gate and begins the transition to Chapter 3.", "Related quests: Find the golden crystal disks"),
            reward = "",
            warnings = "⚠ Important: Create a permanent save before giving Mendoza the complete set.",
            searchTags = listOf("Crystal Disks for the Inquisitor", "Inquisitor Mendoza", "World / Chapter 2", "MAIN QUEST", "Find the golden crystal disks", "Chapter 2 objective"),
        ),
        Quest(
            id = "R1-C2-002",
            chapter = 2,
            playOrder = 2,
            title = "Find the golden crystal disks",
            category = "MAIN QUEST / TRACKER",
            giver = "Inquisitor Mendoza",
            location = "World / Chapter 2",
            prerequisites = "",
            summary = "Complete the individual disk branches and keep every Golden Crystal Disk in your inventory.",
            walkthroughSteps = listOf("Walkthrough. Use this as the Chapter 2 checklist. Recommended branches: Don Esteban; Where is the golden delivery? / Gyrger; Cyrus is Late / Eldric; The mystery of the eastern temple; Off to the west coast (Part II).", "Completion. The tracker closes when the complete disk set has been assembled.", "Related quests: Crystal Disks for the Inquisitor"),
            reward = "",
            warnings = "⚠ Important: Do not sell or discard any uniquely named disk-related item.",
            searchTags = listOf("Find the golden crystal disks", "Inquisitor Mendoza", "World / Chapter 2", "MAIN QUEST / TRACKER", "Crystal Disks for the Inquisitor", "Chapter 2 objective"),
        ),
        Quest(
            id = "R1-C2-003",
            chapter = 2,
            playOrder = 3,
            title = "Teleport Stones",
            category = "COLLECTION / FAST TRAVEL",
            giver = "Inquisitor Mendoza / automatic collection",
            location = "World / Chapter 2",
            prerequisites = "",
            summary = "Collect all 14 teleport stones. Mendoza gives the Volcano Keep stone; most others are carried by lizardmen near the destination they unlock.",
            walkthroughSteps = listOf("Walkthrough. The 14 destinations are: Harbour Town (Carlos/Scordo), Bandit Camp (Fincher), Volcano Keep (Mendoza), Eastern Volcano Cave, East Coast, Eastern Temple, Northeastern Temple, Northern Temple, Plains Temple, Southeast Coast, Southern Ruin, Southwestern Ruin, Western Ruin, and West Volcano Cave. When a new lizard group appears near one of these locations, loot every corpse carefully.", "Completion. The journal updates as each stone is found; there is no single final hand-in NPC."),
            reward = "",
            warnings = "⚠ Important: Some stones naturally appear later than this Part. Keep the quest open rather than forcing dangerous late-game areas early.",
            searchTags = listOf("Teleport Stones", "Inquisitor Mendoza / automatic collection", "World / Chapter 2", "COLLECTION / FAST TRAVEL", "—", "Chapter 2 objective"),
        ),
        Quest(
            id = "R1-C2-004",
            chapter = 2,
            playOrder = 4,
            title = "Where is the golden delivery?",
            category = "MAIN DISK BRANCH",
            giver = "Inquisitor Mendoza / Severin",
            location = "World / Chapter 2",
            prerequisites = "",
            summary = "Go to Tilda's farm, help Severin, then follow the stolen-disk trail east to the Gyrger ruins.",
            walkthroughSteps = listOf("Walkthrough. Speak with Severin at Tilda's farm. In Chapter 2 the farm is attacked by gnome looters; help defeat them. Severin explains that the golden delivery/crystal disk has been stolen and points you toward the eastern peninsula. Follow the eastward route through the cave toward the coast, clearing gnomes and undead as you go.", "Completion. The branch continues through Uprising of the gnomes, The stolen crystal disk and The legend of the gyrger until the Gyrger is killed and its Golden Crystal Disk is recovered.", "Related quests: Uprising of the gnomes / The stolen crystal disk / The legend of the gyrger"),
            reward = "",
            warnings = "⚠ Important: This route intersects The Cursed Lords and contains optional high-value loot; clear methodically.",
            searchTags = listOf("Where is the golden delivery?", "Inquisitor Mendoza / Severin", "World / Chapter 2", "MAIN DISK BRANCH", "Uprising of the gnomes / The stolen crystal disk / The legend of the gyrger", "A. SEVERIN, THE GNOMES & THE GYRGER"),
        ),
        Quest(
            id = "R1-C2-005",
            chapter = 2,
            playOrder = 5,
            title = "Uprising of the gnomes",
            category = "COMBAT / DISK BRANCH",
            giver = "Severin",
            location = "World / Chapter 2",
            prerequisites = "",
            summary = "Help Severin defeat the gnome attackers at Tilda's farm and learn where the stolen delivery went.",
            walkthroughSteps = listOf("Walkthrough. When you arrive at the farm in Chapter 2, join Severin against the gnome looters. After the fight, speak with him and ask about the delivery and your map/route.", "Completion. The quest closes after the attack is repelled and Severin explains the theft.", "Related quests: Where is the golden delivery?"),
            reward = "",
            warnings = "",
            searchTags = listOf("Uprising of the gnomes", "Severin", "World / Chapter 2", "COMBAT / DISK BRANCH", "Where is the golden delivery?", "A. SEVERIN, THE GNOMES & THE GYRGER"),
        ),
        Quest(
            id = "R1-C2-006",
            chapter = 2,
            playOrder = 6,
            title = "The stolen crystal disk",
            category = "MAIN DISK BRANCH",
            giver = "Severin / quest chain",
            location = "World / Chapter 2",
            prerequisites = "",
            summary = "Track the stolen disk through the eastern cave and ruins until you learn the Gyrger has it.",
            walkthroughSteps = listOf("Walkthrough. Travel east from Tilda's farm through the cave leading to the East Coast. Fight the gnomes, skeletons and ghouls. The route leads toward Henrik at the rope bridge and then into the Gyrger ruins. Explore chests and side chambers before the boss room.", "Completion. The quest advances into the Gyrger encounter; the disk is recovered from the Gyrger itself.", "Related quests: The legend of the gyrger"),
            reward = "",
            warnings = "⚠ Important: Lord Patroscon is encountered along this route and belongs to The Cursed Lords; loot his ring if that quest is active.",
            searchTags = listOf("The stolen crystal disk", "Severin / quest chain", "World / Chapter 2", "MAIN DISK BRANCH", "The legend of the gyrger", "A. SEVERIN, THE GNOMES & THE GYRGER"),
        ),
        Quest(
            id = "R1-C2-007",
            chapter = 2,
            playOrder = 7,
            title = "The legend of the gyrger",
            category = "BOSS / MAIN DISK BRANCH",
            giver = "Henrik",
            location = "World / Chapter 2",
            prerequisites = "",
            summary = "Cross the rope bridge with Henrik if desired, enter the ruins and kill the Gyrger.",
            walkthroughSteps = listOf("Walkthrough. Meet Henrik at the base of the rope bridge. Ask him about the creature and let him accompany you if you want support. Fight through the gnome groups and descend through the ruin. Before confronting the Gyrger, search the side rooms for a Stone Plate and other valuables. Kill the Gyrger and loot its corpse.", "Completion. Loot the Golden Crystal Disk from the Gyrger, speak with Henrik, and report back to Severin for the branch reward.", "Related quests: Where is the golden delivery?"),
            reward = "",
            warnings = "⚠ Important: Do not leave without looting the boss corpse; the disk is on the Gyrger.",
            searchTags = listOf("The legend of the gyrger", "Henrik", "World / Chapter 2", "BOSS / MAIN DISK BRANCH", "Where is the golden delivery?", "A. SEVERIN, THE GNOMES & THE GYRGER"),
        ),
        Quest(
            id = "R1-C2-008",
            chapter = 2,
            playOrder = 8,
            title = "Cyrus is Late",
            category = "MAIN DISK BRANCH",
            giver = "Inquisitor Mendoza / Cyrus",
            location = "World / Chapter 2",
            prerequisites = "",
            summary = "Find Cyrus in the northeast, trace Eldric with Rufo, enter the northeastern temple, rescue Eldric and have him repair the damaged disk.",
            walkthroughSteps = listOf("Walkthrough. Go to Cyrus at the northeast of the island. Search Eldric's hut for the sleeve/clue, then visit Jasmin and Rufo to the south. Give Rufo meat and use the sleeve so the wolf can track Eldric. Pick up Cyrus as you pass him and follow the trail to the temple. Clear the lizardmen and work through the ruin until you find the prison area and Eldric.", "Completion. After rescuing Eldric, obtain the damaged disk from Cyrus and bring it to Eldric for repair.", "Related quests: Searching the druid's hut / No sign of Eldric / Get the damaged disk from Cyrus / The broken disk"),
            reward = "",
            warnings = "⚠ Important: Take levitation and other utility magic/scrolls; the temple includes lava and gated sections.",
            searchTags = listOf("Cyrus is Late", "Inquisitor Mendoza / Cyrus", "World / Chapter 2", "MAIN DISK BRANCH", "Searching the druid's hut / No sign of Eldric / Get the damaged disk from Cyrus / The broken disk", "B. CYRUS, ELDRIC & THE DAMAGED DISK"),
        ),
        Quest(
            id = "R1-C2-009",
            chapter = 2,
            playOrder = 9,
            title = "Searching the druid's hut",
            category = "INVESTIGATION",
            giver = "Cyrus",
            location = "World / Chapter 2",
            prerequisites = "",
            summary = "Search Eldric's hut for a personal item carrying his scent.",
            walkthroughSteps = listOf("Walkthrough. Enter Eldric's hut near Cyrus and search the interior carefully. Take the sleeve/clothing clue needed for Rufo to track him.", "Completion. Return to Cyrus or proceed to Jasmin/Rufo with the clue.", "Related quests: Cyrus is Late"),
            reward = "",
            warnings = "",
            searchTags = listOf("Searching the druid's hut", "Cyrus", "World / Chapter 2", "INVESTIGATION", "Cyrus is Late", "B. CYRUS, ELDRIC & THE DAMAGED DISK"),
        ),
        Quest(
            id = "R1-C2-010",
            chapter = 2,
            playOrder = 10,
            title = "No sign of Eldric",
            category = "TRACKING",
            giver = "Cyrus / Rufo chain",
            location = "World / Chapter 2",
            prerequisites = "",
            summary = "Use Eldric's scent item with Rufo and follow the wolf toward the northeastern temple.",
            walkthroughSteps = listOf("Walkthrough. Speak with Jasmin, give meat to Rufo, and present the scent item. Follow Rufo rather than cutting across the terrain; the tracking path leads toward Eldric's captors.", "Completion. The tracking phase ends when the temple/capture trail is confirmed.", "Related quests: Cyrus is Late"),
            reward = "",
            warnings = "",
            searchTags = listOf("No sign of Eldric", "Cyrus / Rufo chain", "World / Chapter 2", "TRACKING", "Cyrus is Late", "B. CYRUS, ELDRIC & THE DAMAGED DISK"),
        ),
        Quest(
            id = "R1-C2-011",
            chapter = 2,
            playOrder = 11,
            title = "Druid staff found",
            category = "DISCOVERY",
            giver = "Eldric chain",
            location = "World / Chapter 2",
            prerequisites = "",
            summary = "Recover Eldric's druid staff while following the evidence of his capture.",
            walkthroughSteps = listOf("Walkthrough. Search the areas along Eldric's trail and the temple approach thoroughly. The staff is a story clue confirming what happened to him.", "Completion. Picking up/identifying the staff advances the Eldric investigation.", "Related quests: No sign of Eldric"),
            reward = "",
            warnings = "",
            searchTags = listOf("Druid staff found", "Eldric chain", "World / Chapter 2", "DISCOVERY", "No sign of Eldric", "B. CYRUS, ELDRIC & THE DAMAGED DISK"),
        ),
        Quest(
            id = "R1-C2-012",
            chapter = 2,
            playOrder = 12,
            title = "Get the damaged disk from Cyrus",
            category = "MAIN DISK BRANCH",
            giver = "Cyrus",
            location = "World / Chapter 2",
            prerequisites = "",
            summary = "After locating/rescuing Eldric, ask Cyrus for the damaged Golden Crystal Disk.",
            walkthroughSteps = listOf("Walkthrough. Once Eldric can help, return to Cyrus or speak to him within the temple chain. Ask for the damaged disk the Inquisitor entrusted to him.", "Completion. The quest completes when the damaged disk is in your inventory.", "Related quests: The broken disk"),
            reward = "",
            warnings = "",
            searchTags = listOf("Get the damaged disk from Cyrus", "Cyrus", "World / Chapter 2", "MAIN DISK BRANCH", "The broken disk", "B. CYRUS, ELDRIC & THE DAMAGED DISK"),
        ),
        Quest(
            id = "R1-C2-013",
            chapter = 2,
            playOrder = 13,
            title = "Follow Eldric to his hut",
            category = "ESCORT",
            giver = "Eldric",
            location = "World / Chapter 2",
            prerequisites = "",
            summary = "Escort/follow Eldric back to his hut after freeing him.",
            walkthroughSteps = listOf("Walkthrough. After the rescue, stay near Eldric and follow his route back. Clear remaining threats if necessary and avoid teleporting away before the escort registers.", "Completion. Speak with Eldric at his hut.", "Related quests: The broken disk"),
            reward = "",
            warnings = "",
            searchTags = listOf("Follow Eldric to his hut", "Eldric", "World / Chapter 2", "ESCORT", "The broken disk", "B. CYRUS, ELDRIC & THE DAMAGED DISK"),
        ),
        Quest(
            id = "R1-C2-014",
            chapter = 2,
            playOrder = 14,
            title = "The broken disk",
            category = "MAIN DISK BRANCH",
            giver = "Eldric",
            location = "World / Chapter 2",
            prerequisites = "",
            summary = "Give Eldric the damaged disk and help him restore it.",
            walkthroughSteps = listOf("Walkthrough. Bring the damaged disk from Cyrus to Eldric. He explains that he can repair it but requires a suitable magic crystal.", "Completion. Complete Eldric needs a magic crystal, then return the material so Eldric can restore the Golden Crystal Disk.", "Related quests: Eldric needs a magic crystal"),
            reward = "",
            warnings = "",
            searchTags = listOf("The broken disk", "Eldric", "World / Chapter 2", "MAIN DISK BRANCH", "Eldric needs a magic crystal", "B. CYRUS, ELDRIC & THE DAMAGED DISK"),
        ),
        Quest(
            id = "R1-C2-015",
            chapter = 2,
            playOrder = 15,
            title = "Eldric needs a magic crystal",
            category = "COLLECTION / REPAIR",
            giver = "Eldric",
            location = "World / Chapter 2",
            prerequisites = "",
            summary = "Bring Eldric the magic crystal he requests so he can repair the broken disk.",
            walkthroughSteps = listOf("Walkthrough. After Eldric examines the damaged disk, obtain the specified magic crystal from your inventory, a merchant, or the appropriate magical loot source available in Chapter 2.", "Completion. Hand it to Eldric; he repairs the disk and returns a usable Golden Crystal Disk."),
            reward = "",
            warnings = "⚠ Important: Do not sell rare crystals while this quest is active.",
            searchTags = listOf("Eldric needs a magic crystal", "Eldric", "World / Chapter 2", "COLLECTION / REPAIR", "—", "B. CYRUS, ELDRIC & THE DAMAGED DISK"),
        ),
        Quest(
            id = "R1-C2-016",
            chapter = 2,
            playOrder = 16,
            title = "Report to the druid about the temple",
            category = "FOLLOW-UP",
            giver = "Eldric",
            location = "World / Chapter 2",
            prerequisites = "",
            summary = "After learning what is happening in the temples, report the lizard activity and discoveries to Eldric.",
            walkthroughSteps = listOf("Walkthrough. Return to Eldric after completing the relevant temple exploration and exhaust his new dialogue about the ruins, lizardmen and crystal disks.", "Completion. The report closes the informational follow-up.", "Related quests: Cyrus is Late / temple quests"),
            reward = "",
            warnings = "",
            searchTags = listOf("Report to the druid about the temple", "Eldric", "World / Chapter 2", "FOLLOW-UP", "Cyrus is Late / temple quests", "B. CYRUS, ELDRIC & THE DAMAGED DISK"),
        ),
        Quest(
            id = "R1-C2-017",
            chapter = 2,
            playOrder = 17,
            title = "Lizard Swords",
            category = "CRAFTING UNLOCK",
            giver = "Walter / Karlsen",
            location = "World / Chapter 2",
            prerequisites = "",
            summary = "Show a Lizard Sword to Karlsen, then take one to Walter in Harbour Town to unlock obsidian weapon crafting information.",
            walkthroughSteps = listOf("Walkthrough. Once Chapter 2 lizardmen begin dropping obsidian Lizard Swords, keep at least one. Show the blade to Karlsen at the Monastery; he directs you to Walter. Take the weapon to Walter in Harbour Town and ask about obsidian weapons.", "Completion. Walter explains/opens the obsidian-smithing route. One-handed and bastard obsidian options become relevant before the later two-handed progression."),
            reward = "",
            warnings = "⚠ Important: Do not sell every Lizard Sword before showing one to the smiths.",
            searchTags = listOf("Lizard Swords", "Walter / Karlsen", "World / Chapter 2", "CRAFTING UNLOCK", "—", "B. CYRUS, ELDRIC & THE DAMAGED DISK"),
        ),
        Quest(
            id = "R1-C2-018",
            chapter = 2,
            playOrder = 18,
            title = "The mystery of the eastern temple",
            category = "MAIN DISK BRANCH",
            giver = "Fincher",
            location = "World / Chapter 2",
            prerequisites = "",
            summary = "Investigate the Eastern Temple for Fincher, find the trapped expedition and descend to the Lizard Priest carrying a Golden Crystal Disk.",
            walkthroughSteps = listOf("Walkthrough. At the Bandit Camp, speak with Fincher. He gives you the Bandit Camp teleport stone and sends you to the large Eastern Temple. Speak with Maliko at the entrance, then Adan and Dytar below. Drop through the trapdoor and work through the lower ruin, using levers, winches, old busts, Nautilus Transformation and Levitation where required.", "Completion. At the bottom, defeat the Lizard Priest and loot the Golden Crystal Disk plus the Eastern Temple teleport stone. Return to Maliko and then Fincher.", "Related quests: Find Danilo the fighter / Find an exit from the eastern temple / Lost in the eastern temple / Tell Fincher about debacle at the eastern temple"),
            reward = "",
            warnings = "⚠ Important: Carry Nautilus and Levitation scrolls/spells. The temple contains spike traps and routes that are easy to miss.",
            searchTags = listOf("The mystery of the eastern temple", "Fincher", "World / Chapter 2", "MAIN DISK BRANCH", "Find Danilo the fighter / Find an exit from the eastern temple / Lost in the eastern temple / Tell Fincher about debacle at the eastern temple", "C. THE EASTERN TEMPLE"),
        ),
        Quest(
            id = "R1-C2-019",
            chapter = 2,
            playOrder = 19,
            title = "Find Danilo the fighter",
            category = "EASTERN TEMPLE SUBQUEST",
            giver = "Adan / Dytar",
            location = "World / Chapter 2",
            prerequisites = "",
            summary = "Locate Danilo in the lower Eastern Temple.",
            walkthroughSteps = listOf("Walkthrough. After speaking with the stranded expedition members, explore the lower passages. Continue past the sarcophagi and ghouls until you find Danilo's body.", "Completion. Loot Danilo, including the temple map, and report the discovery when dialogue becomes available.", "Related quests: The mystery of the eastern temple"),
            reward = "",
            warnings = "",
            searchTags = listOf("Find Danilo the fighter", "Adan / Dytar", "World / Chapter 2", "EASTERN TEMPLE SUBQUEST", "The mystery of the eastern temple", "C. THE EASTERN TEMPLE"),
        ),
        Quest(
            id = "R1-C2-020",
            chapter = 2,
            playOrder = 20,
            title = "Find an exit from the eastern temple",
            category = "EASTERN TEMPLE SUBQUEST",
            giver = "Dirk / trapped expedition",
            location = "World / Chapter 2",
            prerequisites = "",
            summary = "Open the route out by using the lever and winch system, then reconnect with the upper temple.",
            walkthroughSteps = listOf("Walkthrough. After falling through the trapdoor, speak with Dirk and clear the adjacent ghoul. Use the lever to raise the first portcullis and the winch in the next section to raise the larger gate. Follow the swamp/outer route back toward the temple entrance.", "Completion. The quest completes when a usable exit from the trapped section has been opened.", "Related quests: The mystery of the eastern temple"),
            reward = "",
            warnings = "",
            searchTags = listOf("Find an exit from the eastern temple", "Dirk / trapped expedition", "World / Chapter 2", "EASTERN TEMPLE SUBQUEST", "The mystery of the eastern temple", "C. THE EASTERN TEMPLE"),
        ),
        Quest(
            id = "R1-C2-021",
            chapter = 2,
            playOrder = 21,
            title = "Lost in the eastern temple",
            category = "EASTERN TEMPLE SUBQUEST",
            giver = "Olf / expedition chain",
            location = "World / Chapter 2",
            prerequisites = "",
            summary = "Find Olf in the deeper temple and help reconnect the scattered treasure hunters.",
            walkthroughSteps = listOf("Walkthrough. Continue past Danilo's area, use the appropriate lever and enter the chamber where Olf is stranded. Speak with him and exhaust the rescue/route dialogue.", "Completion. The journal updates once Olf is found and his situation is resolved.", "Related quests: The mystery of the eastern temple"),
            reward = "",
            warnings = "",
            searchTags = listOf("Lost in the eastern temple", "Olf / expedition chain", "World / Chapter 2", "EASTERN TEMPLE SUBQUEST", "The mystery of the eastern temple", "C. THE EASTERN TEMPLE"),
        ),
        Quest(
            id = "R1-C2-022",
            chapter = 2,
            playOrder = 22,
            title = "Tell Fincher about debacle at the eastern temple",
            category = "REPORT / COMPLETION",
            giver = "Fincher",
            location = "World / Chapter 2",
            prerequisites = "",
            summary = "After clearing the Eastern Temple and discovering what happened to the expedition, report everything to Fincher.",
            walkthroughSteps = listOf("Walkthrough. Return to the Bandit Camp after obtaining the disk and finishing the local expedition subquests. Speak with Fincher about the temple, lizardmen and the fate of his people.", "Completion. Fincher closes the Eastern Temple assignment and provides the final report reward.", "Related quests: The mystery of the eastern temple"),
            reward = "",
            warnings = "",
            searchTags = listOf("Tell Fincher about debacle at the eastern temple", "Fincher", "World / Chapter 2", "REPORT / COMPLETION", "The mystery of the eastern temple", "C. THE EASTERN TEMPLE"),
        ),
    )

    val notes: List<RisenGuideNote> = listOf(
        RisenGuideNote(2, 1, "Chapter 2 objective", listOf("Chapter 2 revolves around recovering five Golden Crystal Disks for Inquisitor Mendoza so the sealed gate in the volcano can be opened. One disk is already associated with the Inquisitor but is damaged; the remaining disks are tied to Don Esteban, the Gyrger/eastern ruins, the Eastern Temple, Eldric/Cyrus, and the west-coast Steelbeard chain. This Part covers the first four branches plus the island-wide Teleport Stones and Lizard Swords quests. The Patty/Romanov west-coast branch is reserved for Part II.", "Recommended order: Mendoza → Severin/Gyrger → Cyrus/Eldric → Eastern Temple → clean-up/teleport stones → Patty west-coast branch in Part II.")),
        RisenGuideNote(2, 4, "A. SEVERIN, THE GNOMES & THE GYRGER", listOf()),
        RisenGuideNote(2, 8, "B. CYRUS, ELDRIC & THE DAMAGED DISK", listOf()),
        RisenGuideNote(2, 18, "C. THE EASTERN TEMPLE", listOf()),
        RisenGuideNote(2, 23, "D. DON ESTEBAN'S DISK — GUIDE STEP (NOT A SEPARATE WORLD QUEST)", listOf("Mendoza explicitly points you toward Don Esteban as one of the disk sources. Return to the Bandit Camp and ask the Don about the Golden Crystal Disk. Depending on your faction path, the surrounding dialogue differs, but the important completionist point is simple: obtain the Don's disk before the final Chapter 2 hand-in. Bandit characters also receive a separate Chapter 2 quest, Crystal disks for the Don, which will be covered in Part II with the other faction-specific content.")),
        RisenGuideNote(2, 23, "PART I COMPLETION CHECKLIST", listOf("Crystal Disks for the Inquisitor and Find the golden crystal disks are active.", "The Volcano Keep teleport stone has been obtained from Mendoza.", "Severin's gnome attack is resolved and the Gyrger is dead.", "The Gyrger's Golden Crystal Disk was looted.", "Eldric has been found and rescued.", "The damaged disk from Cyrus has been repaired by Eldric.", "The Eastern Temple expedition quests are complete.", "The Eastern Temple Lizard Priest's Golden Crystal Disk was looted.", "The Don's Golden Crystal Disk has been obtained or is immediately available.", "At least one Lizard Sword was shown to the smiths before selling extras.", "Teleport Stones remains active for locations not yet reached.", "The remaining west-coast/Patty disk branch is intentionally saved for Chapter 2 Part II.")),
    )
}
