package com.sliverzfx.gothicquest

internal object Risen2GuidePart1Data {
    val quests: List<Quest> = listOf(
        Quest(
            id = "R2-C1-001",
            chapter = 1,
            playOrder = 1,
            title = "Meet the Commandant!",
            category = "PROLOGUE — MAIN STORY",
            giver = "Carlos",
            location = "Caldera",
            prerequisites = "The opening quest starts automatically after the Caldera introductory scene.",
            summary = "Leave your room and speak with Commandant Carlos on the upper parapet.",
            walkthroughSteps = listOf("Walkthrough. At the start, loot/equip what you need in your quarters. Go upstairs from the courtyard and find Carlos looking out toward the sea. Exhaust his dialogue.", "Completion. Talking with Carlos starts the beach investigation."),
            reward = "50 Glory",
            warnings = "",
            searchTags = listOf("Meet the Commandant!", "PROLOGUE — CALDERA", "Automatic / Carlos", "Caldera"),
        ),
        Quest(
            id = "R2-C1-002",
            chapter = 1,
            playOrder = 2,
            title = "Search the Beach",
            category = "PROLOGUE — MAIN STORY",
            giver = "Carlos",
            location = "Caldera beach",
            prerequisites = "Speak with Commandant Carlos on the fortress parapet in Meet the Commandant!; equip your officer's sword when challenged by Juan.",
            summary = "Leave the fortress and walk down to the beach.",
            walkthroughSteps = listOf("Walkthrough. Equip both your sword and pistol if the guard requires it, then leave the fortress and head down the stairs toward the water.", "Completion. The quest updates when you reach the beach and trigger the scene.", "Related: Beach Found"),
            reward = "50 Glory",
            warnings = "",
            searchTags = listOf("Search the Beach", "PROLOGUE — CALDERA", "Carlos", "Caldera beach"),
        ),
        Quest(
            id = "R2-C1-003",
            chapter = 1,
            playOrder = 3,
            title = "Rescue Patty",
            category = "PROLOGUE — COMBAT",
            giver = "Trigger quest",
            location = "Caldera beach",
            prerequisites = "Complete Search the Beach and approach the survivors on Caldera's shore.",
            summary = "Kill the Sand Devils attacking Patty.",
            walkthroughSteps = listOf("Walkthrough. After the beach scene, draw your weapons and defeat the three Sand Devils around Patty. Use the pistol to soften enemies before closing into melee if needed.", "Completion. The quest completes when the attackers are dead and Patty is safe."),
            reward = "100 Glory; 50 Glory per Sand Devil personally killed",
            warnings = "",
            searchTags = listOf("Rescue Patty", "PROLOGUE — CALDERA", "Automatic", "Caldera beach"),
        ),
        Quest(
            id = "R2-C1-004",
            chapter = 1,
            playOrder = 4,
            title = "Flotsam",
            category = "PROLOGUE — MISSABLE SIDE QUEST",
            giver = "Storehouse Master",
            location = "Caldera beach",
            prerequisites = "Rescue Patty from the three Sand Devils, report back to Carlos, and ask the Storehouse Master about the lost cargo before leaving Caldera.",
            summary = "Collect all six pieces of flotsam on the beach and report back before sailing.",
            walkthroughSteps = listOf("Walkthrough. After rescuing Patty, speak with the Storehouse Master. Search the shoreline for six pieces of wreckage/flotsam. Two Sand Devils may attack near the far end of the beach.", "Completion. Return to the Storehouse Master with all six pieces collected.", "Related: Flotsam on the Beach Collected"),
            reward = "50 Glory + 200 Gold",
            warnings = "Finish both the Flotsam and Flotsam on the Beach Collected objectives before To Tacarigua. Return to the Storehouse Master for the separate 200 Gold payout.",
            searchTags = listOf("Flotsam", "PROLOGUE — CALDERA", "Storehouse Master", "Caldera beach"),
        ),
        Quest(
            id = "R2-C1-005",
            chapter = 1,
            playOrder = 5,
            title = "Talk to Carlos",
            category = "PROLOGUE — MAIN STORY",
            giver = "Trigger quest",
            location = "Caldera fortress",
            prerequisites = "Rescue Patty, then return to the Crystal Fortress to report the encounter to Carlos.",
            summary = "Return to Carlos and report what happened on the beach.",
            walkthroughSteps = listOf("Walkthrough. Go back to the command hall and speak with Carlos. This conversation starts the larger Titan Weapon objective and sends you after Steelbeard.", "Completion. The quest completes after the report.", "Related: The Titan Weapon / Find Steelbeard / To Tacarigua"),
            reward = "50 Glory",
            warnings = "",
            searchTags = listOf("Talk to Carlos", "PROLOGUE — CALDERA", "Automatic", "Caldera fortress"),
        ),
        Quest(
            id = "R2-C1-006",
            chapter = 1,
            playOrder = 6,
            title = "To Tacarigua",
            category = "PROLOGUE — POINT OF NO RETURN",
            giver = "Carlos / Sebastiano",
            location = "Caldera docks",
            prerequisites = "Complete Talk to Carlos and finish any desired Caldera tasks, especially Flotsam, before speaking to Sebastiano on the ship.",
            summary = "Finish Caldera business, then tell Sebastiano you are ready to sail.",
            walkthroughSteps = listOf("Walkthrough. Before boarding, finish Flotsam and any exploration you want to do. Speak with Patty, then go to Sebastiano's ship and tell him you are ready.", "Completion. The ship departs for Tacarigua and Chapter 1 begins.", "Related: Find the Pirates' Den"),
            reward = "100 Glory + Adventurer title",
            warnings = "⚠ Important: This is a mini point-of-no-return: Caldera is unavailable for the next part of the story.",
            searchTags = listOf("To Tacarigua", "PROLOGUE — CALDERA", "Carlos / Sebastiano", "Caldera docks"),
        ),
        Quest(
            id = "R2-C1-007",
            chapter = 1,
            playOrder = 7,
            title = "Find the Pirates' Den",
            category = "CHAPTER 1 — MAIN STORY",
            giver = "Trigger quest",
            location = "Tacarigua",
            prerequisites = "Land on Tacarigua after To Tacarigua and receive the mission to contact Steelbeard's pirates.",
            summary = "Prepare in Puerto Sacarico, then reach the Pirates' Den through the main gate or by the coastal route.",
            walkthroughSteps = listOf("Walkthrough. After landing, explore Puerto Sacarico first. Pick up A Map of Tacarigua, Sturdy Clothes and Provisions. The Pirates' Den lies in the northeast. At the main gate, Fence can be handled with Silver Tongue, Intimidate/duel, or by using the alternate beach route near Blake.", "Completion. The quest completes when you enter the Pirates' Den.", "Related: Find Steelbeard"),
            reward = "100 Glory",
            warnings = "⚠ Important: Do the Puerto Sacarico side quests below before rushing to Steelbeard. Reaching the Den is safe; approaching Steelbeard's ship advances Patty's state.",
            searchTags = listOf("Find the Pirates' Den", "CHAPTER 1 — TACARIGUA: PUERTO SACARICO", "Automatic / main story", "Tacarigua"),
        ),
        Quest(
            id = "R2-C1-008",
            chapter = 1,
            playOrder = 8,
            title = "A Map of Tacarigua",
            category = "SAFE — MAIN SUPPORT",
            giver = "Di Fuego",
            location = "Puerto Sacarico",
            prerequisites = "Arrive at Puerto Sacarico on Tacarigua and speak with Governor Di Fuego about obtaining an island map.",
            summary = "Obtain the island map from Governor Di Fuego.",
            walkthroughSteps = listOf("Walkthrough. Speak with Di Fuego in the governor's residence. The simplest solution is to buy the map for 100 Gold. Alternatively, Pirate Post can be used to persuade him to provide it without paying if the sealed letter is still intact.", "Completion. Receive the Tacarigua map."),
            reward = "50 Glory + region map",
            warnings = "⚠ Important: Do not open Roquefort's sealed Pirate Post letter if you want to use it as leverage with Di Fuego.",
            searchTags = listOf("A Map of Tacarigua", "CHAPTER 1 — TACARIGUA: PUERTO SACARICO", "Di Fuego", "Puerto Sacarico"),
        ),
        Quest(
            id = "R2-C1-009",
            chapter = 1,
            playOrder = 9,
            title = "Sturdy Clothes",
            category = "SAFE — MAIN SUPPORT",
            giver = "Pedro / Curtis",
            location = "Puerto Sacarico",
            prerequisites = "Reach Puerto Sacarico; speak with Pedro about clothes and then Curtis about acceptable attire.",
            summary = "Acquire and equip a proper shirt, then speak with Curtis.",
            walkthroughSteps = listOf("Walkthrough. Ask Pedro about clothing, then speak with Curtis near the prison tower. You can buy clothing, or equip a usable shirt you have already found. Once properly dressed, you can deal more comfortably with the governor and merchants.", "Completion. Speak with Curtis after meeting the clothing requirement."),
            reward = "50 Glory + Curtis clothing merchant access",
            warnings = "",
            searchTags = listOf("Sturdy Clothes", "CHAPTER 1 — TACARIGUA: PUERTO SACARICO", "Pedro / Curtis", "Puerto Sacarico"),
        ),
        Quest(
            id = "R2-C1-010",
            chapter = 1,
            playOrder = 10,
            title = "Provisions",
            category = "SAFE — MAIN SUPPORT",
            giver = "Osorio",
            location = "Puerto Sacarico",
            prerequisites = "After arriving at Puerto Sacarico, find Osorio the cook opposite the governor's residence and ask whether he sells food.",
            summary = "Ask Osorio whether he sells food to complete this short quest and unlock his provisions trading.",
            walkthroughSteps = listOf("Find Osorio in the small kitchen building opposite Di Fuego's governor's residence.", "Ask Osorio if he sells food; no provisions hand-in or minimum inventory quantity is required.", "The conversation completes Provisions and opens Osorio's trade inventory."),
            reward = "50 Glory; Osorio's food trading unlocked",
            warnings = "",
            searchTags = listOf("Provisions", "CHAPTER 1 — TACARIGUA: PUERTO SACARICO", "Osorio", "Puerto Sacarico"),
        ),
        Quest(
            id = "R2-C1-011",
            chapter = 1,
            playOrder = 11,
            title = "Kitchen Help",
            category = "MISSABLE / PATTY-DEPENDENT",
            giver = "Osorio",
            location = "Puerto Sacarico",
            prerequisites = "Talk to Osorio about his lack of kitchen help while Patty is still accompanying you in Puerto Sacarico; Silver Tongue 10 is required for the successful Patty dialogue.",
            summary = "Use Silver Tongue 10 to persuade Patty to help Osorio in the kitchen.",
            walkthroughSteps = listOf("Walkthrough. Ask Osorio for work. He cannot use you as a cook, but he wants Patty. Speak with Patty and use the dialogue option based on having a 'plan'; this requires Silver Tongue 10. Then report back to Osorio.", "Completion. Patty begins working for Osorio and Grog for the Guards starts."),
            reward = "50 Glory",
            warnings = "⚠ Important: Finish the follow-up delivery chain before triggering Steelbeard's ship scene, which removes Patty from the group and can cancel Kitchen Help.",
            searchTags = listOf("Kitchen Help", "PUERTO SACARICO SIDE QUESTS — DO BEFORE STEELBEARD", "Osorio", "Puerto Sacarico"),
        ),
        Quest(
            id = "R2-C1-012",
            chapter = 1,
            playOrder = 12,
            title = "Grog for the Guards",
            category = "SAFE — DELIVERY",
            giver = "Osorio",
            location = "Sugar plantation",
            prerequisites = "Complete Kitchen Help so Patty starts working for Osorio, then take Osorio's grog to Gilles at the sugar plantation.",
            summary = "Take five bottles of grog from Osorio to Gilles at the sugar plantation.",
            walkthroughSteps = listOf("Walkthrough. After Kitchen Help, Osorio gives you five Grog. Follow the road north from Puerto Sacarico to the plantation and give the bottles to Gilles.", "Completion. The delivery to Gilles completes this quest.", "Related: Let Thompkins Know!"),
            reward = "Quest Glory",
            warnings = "",
            searchTags = listOf("Grog for the Guards", "PUERTO SACARICO SIDE QUESTS — DO BEFORE STEELBEARD", "Osorio", "Sugar plantation"),
        ),
        Quest(
            id = "R2-C1-013",
            chapter = 1,
            playOrder = 13,
            title = "A Fat Roast",
            category = "SAFE — HUNT",
            giver = "Thompkins",
            location = "Sugar plantation",
            prerequisites = "Reach Thompkins at the sugar plantation on Tacarigua and agree to hunt a nearby warthog.",
            summary = "Hunt the nearby warthog with Thompkins.",
            walkthroughSteps = listOf("Walkthrough. Speak with Thompkins near the plantation and agree to hunt. Follow him up the hill and kill the quest warthog. If you or Patty lands the kill rather than Thompkins, you can gain the creature's normal Glory as well.", "Completion. The quest completes when the warthog is dead."),
            reward = "50 Glory",
            warnings = "",
            searchTags = listOf("A Fat Roast", "PUERTO SACARICO SIDE QUESTS — DO BEFORE STEELBEARD", "Thompkins", "Sugar plantation"),
        ),
        Quest(
            id = "R2-C1-014",
            chapter = 1,
            playOrder = 14,
            title = "Let Thompkins Know!",
            category = "SAFE — DELIVERY",
            giver = "Gilles",
            location = "Sugar plantation",
            prerequisites = "Deliver the five bottles of grog to Gilles, who asks you to inform Thompkins about the supply.",
            summary = "Tell Thompkins that the grog has arrived.",
            walkthroughSteps = listOf("Walkthrough. After delivering the grog to Gilles, agree to inform Thompkins. He is only a short distance away near the plantation.", "Completion. Speak with Thompkins and tell him about the delivery.", "Related: Meat for the Cook"),
            reward = "50 Glory",
            warnings = "⚠ Important: Complete this before returning to Osorio; otherwise the quest can be cancelled and you lose the extra reward chain.",
            searchTags = listOf("Let Thompkins Know!", "PUERTO SACARICO SIDE QUESTS — DO BEFORE STEELBEARD", "Gilles", "Sugar plantation"),
        ),
        Quest(
            id = "R2-C1-015",
            chapter = 1,
            playOrder = 15,
            title = "Meat for the Cook",
            category = "SAFE — DELIVERY",
            giver = "Thompkins",
            location = "Sugar plantation → Puerto Sacarico",
            prerequisites = "Complete Let Thompkins Know! and accept Thompkins's meat delivery for Osorio.",
            summary = "Take Thompkins' fresh meat to Osorio.",
            walkthroughSteps = listOf("Walkthrough. After Let Thompkins Know!, Thompkins gives you fresh meat intended for the cook. Return to Puerto Sacarico and hand it to Osorio.", "Completion. Give Osorio the meat and finish the kitchen-delivery chain."),
            reward = "50 Glory",
            warnings = "",
            searchTags = listOf("Meat for the Cook", "PUERTO SACARICO SIDE QUESTS — DO BEFORE STEELBEARD", "Thompkins", "Sugar plantation → Puerto Sacarico"),
        ),
        Quest(
            id = "R2-C1-016",
            chapter = 1,
            playOrder = 16,
            title = "A Hungry Slave",
            category = "SAFE — CHARITY",
            giver = "Asad",
            location = "Sugar plantation",
            prerequisites = "Talk to the hungry slave Asad while visiting the sugar plantation, and have one set of Provisions available.",
            summary = "Give Asad one set of Provisions.",
            walkthroughSteps = listOf("Walkthrough. Visit the plantation during the day and speak with Asad. He is hungry and asks for food.", "Completion. Give him Provisions."),
            reward = "Quest Glory",
            warnings = "",
            searchTags = listOf("A Hungry Slave", "PUERTO SACARICO SIDE QUESTS — DO BEFORE STEELBEARD", "Asad", "Sugar plantation"),
        ),
        Quest(
            id = "R2-C1-017",
            chapter = 1,
            playOrder = 17,
            title = "Pirate Post",
            category = "SAFE — DELIVERY",
            giver = "Roquefort",
            location = "Puerto Sacarico → Pirates' Den",
            prerequisites = "Wait for the Sebastiano–Roquefort conversation near Di Fuego's headquarters and ask Roquefort about contacting the pirates.",
            summary = "Carry Roquefort's sealed letter to Booze in the Pirates' Den and bring the reply back if desired.",
            walkthroughSteps = listOf("Walkthrough. Speak with Roquefort near the barracks and accept the letter. Keep it sealed. Once you reach the Pirates' Den, give it to Booze in the tavern. He writes a reply you can return to Roquefort for the extra payment.", "Completion. The main delivery completes when Booze receives the sealed letter; returning the reply gives the full payoff."),
            reward = "Gold + quest Glory",
            warnings = "⚠ Important: Keep the letter sealed. Showing the still-sealed letter to Di Fuego can also help with A Map of Tacarigua.",
            searchTags = listOf("Pirate Post", "PUERTO SACARICO SIDE QUESTS — DO BEFORE STEELBEARD", "Roquefort", "Puerto Sacarico → Pirates' Den"),
        ),
        Quest(
            id = "R2-C1-018",
            chapter = 1,
            playOrder = 18,
            title = "Bounty",
            category = "OPTIONAL — MORAL CHOICE / COMBAT",
            giver = "Di Fuego",
            location = "Tacarigua jungle",
            prerequisites = "Meet Governor Di Fuego in Puerto Sacarico and accept his bounty on the three escaped slaves; this is an optional moral choice.",
            summary = "Hunt the three escaped slaves only if you choose to side with the governor's bounty request.",
            walkthroughSteps = listOf("Walkthrough. Ask Di Fuego about escaped slaves and accept the bounty. The fugitives are in the jungle east/downhill from Vasco's Tower and are dangerous early-game opponents.", "Completion. Defeat the three targets, loot the required proof and return to Di Fuego."),
            reward = "Gold bounty + Glory",
            warnings = "⚠ Important: This is optional and morally framed; the app should not mark killing the escaped slaves as the 'best' choice.",
            searchTags = listOf("Bounty", "PUERTO SACARICO SIDE QUESTS — DO BEFORE STEELBEARD", "Di Fuego", "Tacarigua jungle"),
        ),
        Quest(
            id = "R2-C1-019",
            chapter = 1,
            playOrder = 19,
            title = "The Clothes of a Pirate",
            category = "SAFE — COLLECTION",
            giver = "Largo",
            location = "Puerto Sacarico / Tacarigua",
            prerequisites = "Find Largo in the Puerto Sacarico prison tower and ask how to recover his confiscated pirate outfit.",
            summary = "Recover Largo's bandana, boots, leather shirt and black pearl earring.",
            walkthroughSteps = listOf("Walkthrough. Speak with Largo in the prison tower. His belongings are scattered among the guards and island NPCs. The worn boots can be stolen from the barracks; the bandana can be won/taken from Riley at the plantation; the black pearl can be pickpocketed from Carter after learning Pickpocket and using Grog; the shirt is obtained through the related clothing route.", "Completion. Collect all four items. You can later return them through Largo's Clothes.", "Related: Freeing Largo / Largo's Clothes"),
            reward = "200 Glory",
            warnings = "⚠ Important: Do not rush to hand everything away if you still need the bandana or pearl as proof to Stone for the free Lock Pick route.",
            searchTags = listOf("The Clothes of a Pirate", "LARGO — SET UP NOW, FINISH AFTER REACHING THE PIRATES", "Largo", "Puerto Sacarico / Tacarigua"),
        ),
        Quest(
            id = "R2-C1-020",
            chapter = 1,
            playOrder = 20,
            title = "Freeing Largo",
            category = "SAFE — CONTINUED NEXT PART / PIRATE TEST",
            giver = "Largo",
            location = "Puerto Sacarico / Pirates' Den / Tacarigua / Pirates' Den",
            prerequisites = "Speak with imprisoned Largo in Puerto Sacarico, then arrange access to Stone in the Pirates' Den for the lock pick.",
            summary = "Get a Lock Pick from Stone in the Pirates' Den, then bring it back to Largo.\nGet Stone's Lock Pick, return to Puerto Sacarico and free Largo.",
            walkthroughSteps = listOf("Chapter 1 — LARGO — SET UP NOW, FINISH AFTER REACHING THE PIRATES", "Walkthrough. Largo asks you to free him. Stone has the Lock Pick. To prove Largo sent you, show Stone either Largo's bandana or black pearl. Mention Stone's debt to Largo to receive the Lock Pick for free; otherwise Stone can charge 500 Gold.", "Completion. This quest will be completed in Part II after you reach Stone and return to Largo.", "Related: Follow Largo", "Chapter 1 — F. LARGO'S ESCAPE", "Walkthrough. Use Largo's Pirate Bandana or Black Pearl as proof when talking to Stone. Mention Stone's debt to Largo to get the Lock Pick for free. Return to the prison tower. Give Largo the Lock Pick and follow the confrontation with Carter as required.", "Completion. Largo escapes prison; Steelbeard counts the deed.", "Counts for Steelbeard?: YES", "Related: The Clothes of a Pirate / Follow Largo"),
            reward = "100 Glory",
            warnings = "⚠ Important: Do this in Chapter 1. Community documentation notes a later-game lockpick bug involving Follow Largo if you postpone the chain too long.\n⚠ Important: A failed conversation with Stone cannot always be repeated. Save before negotiating. Do not wager Largo's Black Pearl to O'Brian if you still need it for Largo's clothing chain.",
            searchTags = listOf("Freeing Largo", "LARGO — SET UP NOW, FINISH AFTER REACHING THE PIRATES", "Largo", "Puerto Sacarico / Pirates' Den", "F. LARGO'S ESCAPE", ""),
        ),
    )

    val notes: List<RisenGuideNote> = listOf(
        RisenGuideNote(1, 1, "Guide structure", listOf("Risen 2 starts with a short Prologue in Caldera. Chapter 1 begins when Sebastiano sails the Nameless Hero and Patty to Tacarigua. This first Part covers the complete Prologue, Puerto Sacarico, the sugar plantation, Largo's setup, and the route to the Pirates' Den. The next Part will cover the Pirates' Den, Steelbeard, rum production, the pirate tests and the oath.", "Critical missable warning: Finish Flotsam before leaving Caldera. On Tacarigua, finish Kitchen Help and its delivery chain before approaching Steelbeard's ship if you want the cleanest completionist route, because Patty leaves the party when the Steelbeard sequence begins and Kitchen Help can be cancelled.")),
        RisenGuideNote(1, 1, "PROLOGUE — CALDERA", listOf()),
        RisenGuideNote(1, 7, "CHAPTER 1 — TACARIGUA: PUERTO SACARICO", listOf()),
        RisenGuideNote(1, 11, "PUERTO SACARICO SIDE QUESTS — DO BEFORE STEELBEARD", listOf()),
        RisenGuideNote(1, 19, "LARGO — SET UP NOW, FINISH AFTER REACHING THE PIRATES", listOf()),
        RisenGuideNote(1, 21, "PART I EXIT CHECKLIST", listOf("Flotsam was completed before leaving Caldera.", "To Tacarigua was used only after finishing the Prologue cleanup.", "A Map of Tacarigua, Sturdy Clothes and Provisions are complete.", "Kitchen Help, Grog for the Guards, Let Thompkins Know! and Meat for the Cook are complete before meeting Steelbeard.", "A Fat Roast and A Hungry Slave are complete if desired.", "Pirate Post is active or delivered with the letter still sealed.", "Largo's collection/escape quests have been activated.", "The route to the Pirates' Den is open and Find the Pirates' Den is complete or ready to complete.", "You have NOT taken Steelbeard's pirate oath yet.")),
    )
}
