package com.sliverzfx.gothicquest

internal object Risen3Chapter2Part3Data {
    val quests: List<Quest> = listOf(
        Quest(
            id = "R3-C2-071",
            chapter = 2,
            playOrder = 71,
            title = "The Reactor",
            aliases = listOf(),
            category = "SAFE — MAIN STORY / LONGER CHAIN",
            giver = "Erasmus",
            location = "Taranis",
            prerequisites = "",
            summary = "Speak with Erasmus and begin recovering the three Monolith Stones needed by the reactor.",
            walkthroughSteps = listOf("Chapter 2 — Taranis — C. THE REACTOR & ERASMUS", "Quest giver: Erasmus", "Status: SAFE — MAIN STORY / LONGER CHAIN", "Area: Taranis", "Reward: Major story Glory", "Walkthrough. After Visiting Rights, enter the main mage building and go upstairs to Erasmus. He explains the reactor and asks you to find three Monolith Stones. One part of the chain involves missing gnome Kasim and his stones; another sends you to Tacarigua for Horas and the remaining stone.", "Completion. The Reactor remains active while you resolve its cross-island objectives.", "Related: A Follower of Magic", "Chapter 2 — Tacarigua — TACARIGUA", "Return the Monolith Stone and Horas-related progress to Erasmus on Taranis. This remains a cross-island Chapter 2 parent quest."),
            reward = "Major story Glory",
            warnings = "⚠ Important: This is a cross-island quest. Start it now, but do not force the Tacarigua leg into the Taranis-only route.",
            searchTags = listOf("Taranis", "Tacarigua", "C. THE REACTOR & ERASMUS", "TACARIGUA"),
        ),
        Quest(
            id = "R3-C2-072",
            chapter = 2,
            playOrder = 72,
            title = "A Follower of Magic",
            aliases = listOf(),
            category = "SAFE — CROSS-ISLAND MAIN QUEST",
            giver = "Erasmus / Horas",
            location = "Taranis",
            prerequisites = "",
            summary = "Find Horas on Tacarigua, return with him to Taranis and deliver his Monolith Stone to Erasmus.",
            walkthroughSteps = listOf("Chapter 2 — Taranis — C. THE REACTOR & ERASMUS", "Quest giver: Erasmus / Horas", "Status: SAFE — CROSS-ISLAND MAIN QUEST", "Area: Taranis", "Reward: 400 Glory", "Walkthrough. Erasmus' Reactor quest points you toward Horas on Tacarigua. When you later visit Tacarigua, locate Horas west of Puerto Sacarico and bring him back to Taranis. After returning, speak with Horas again; he asks you to deliver his Monolith Stone to Erasmus.", "Completion. Give the Monolith Stone to Erasmus.", "Chapter 2 — Tacarigua — TACARIGUA", "Sail to Tacarigua after Erasmus asks you to find Horas. Speak with Jack near the landing beach, reach Puerto Sacarico, locate Horas and resolve his situation. Horas carries one of the Monolith Stones required by The Reactor."),
            reward = "400 Glory",
            warnings = "⚠ Important: Leave this active until the Tacarigua guide unless you are intentionally doing cross-island cleanup now.",
            searchTags = listOf("Taranis", "Tacarigua", "C. THE REACTOR & ERASMUS", "TACARIGUA"),
        ),
        Quest(
            id = "R3-C2-073",
            chapter = 2,
            playOrder = 73,
            title = "The Cleaner",
            aliases = listOf(),
            category = "SAFE — CLEANUP",
            giver = "Camp worker / mage camp",
            location = "Taranis",
            prerequisites = "",
            summary = "Clear the creatures or mess identified by the quest giver around the Mages Camp.",
            walkthroughSteps = listOf("Walkthrough. Take the job while exploring the outer camp and complete the nearby combat/cleanup objective.", "Completion. Report back to the quest giver."),
            reward = "Quest Glory",
            warnings = "",
            searchTags = listOf("Taranis", "D. GOOD PRE-FACTION TARANIS SIDE QUESTS"),
        ),
        Quest(
            id = "R3-C2-074",
            chapter = 2,
            playOrder = 74,
            title = "Paula Hears Noises",
            aliases = listOf(),
            category = "SAFE — INVESTIGATION",
            giver = "Paula",
            location = "Taranis",
            prerequisites = "",
            summary = "Investigate the noises troubling Paula.",
            walkthroughSteps = listOf("Walkthrough. Talk to Paula and search the nearby building/cellar/area indicated by her dialogue. Deal with the source of the noise and return.", "Completion. Report the result to Paula.", "Related: They All Look the Same"),
            reward = "Quest Glory",
            warnings = "",
            searchTags = listOf("Taranis", "D. GOOD PRE-FACTION TARANIS SIDE QUESTS"),
        ),
        Quest(
            id = "R3-C2-075",
            chapter = 2,
            playOrder = 75,
            title = "They All Look the Same",
            aliases = listOf(),
            category = "SAFE — FOLLOW-UP",
            giver = "Paula / Faris",
            location = "Taranis",
            prerequisites = "",
            summary = "Find the correct person among the similarly dressed workers/guards and report back.",
            walkthroughSteps = listOf("Walkthrough. Use Paula's description and question the relevant NPCs. Faris is tied to the resolution.", "Completion. Return with the identification."),
            reward = "Quest Glory",
            warnings = "",
            searchTags = listOf("Taranis", "D. GOOD PRE-FACTION TARANIS SIDE QUESTS"),
        ),
        Quest(
            id = "R3-C2-076",
            chapter = 2,
            playOrder = 76,
            title = "The Missing Gnome",
            aliases = listOf(),
            category = "SAFE — SEARCH",
            giver = "Taranis NPC",
            location = "Taranis",
            prerequisites = "",
            summary = "Find the missing gnome and resolve what happened to him.",
            walkthroughSteps = listOf("Walkthrough. Search the caves/paths around the Mages Camp according to the clues. Clear hostile creatures on the route and talk to the missing gnome when found.", "Completion. Return/report to the quest giver."),
            reward = "Quest Glory",
            warnings = "",
            searchTags = listOf("Taranis", "D. GOOD PRE-FACTION TARANIS SIDE QUESTS"),
        ),
        Quest(
            id = "R3-C2-077",
            chapter = 2,
            playOrder = 77,
            title = "The Private Store",
            aliases = listOf(),
            category = "SAFE — THEFT / SNEAK",
            giver = "Mage Camp NPC",
            location = "Taranis",
            prerequisites = "",
            summary = "Steal the requested items from the three mages' private storage areas.",
            walkthroughSteps = listOf("Walkthrough. This quest becomes practical after Visiting Rights because you need access to the main mage building. Use Sneak where possible. Nergal's chest is in the basement area, and other targets are inside restricted rooms upstairs.", "Completion. Deliver the stolen items to the quest giver."),
            reward = "Quest Glory",
            warnings = "⚠ Important: Save before stealing. Being seen can create unnecessary hostility.",
            searchTags = listOf("Taranis", "D. GOOD PRE-FACTION TARANIS SIDE QUESTS"),
        ),
        Quest(
            id = "R3-C2-078",
            chapter = 2,
            playOrder = 78,
            title = "The Shadow Lord of Betrayal",
            aliases = listOf(),
            category = "SAFE — DIFFICULT COMBAT",
            giver = "Magnus / exploration",
            location = "Taranis",
            prerequisites = "",
            summary = "Kill the Shadow Lord of Betrayal in southwestern Taranis.",
            walkthroughSteps = listOf("Walkthrough. Travel to the shadow-infested southwestern region. Bring a companion and strong healing because the Shadow Lord and nearby enemies are much stronger than normal wildlife.", "Completion. Kill the Shadow Lord and report the victory if applicable."),
            reward = "Large Glory reward",
            warnings = "⚠ Important: You can leave this until later if your character is under-geared.",
            searchTags = listOf("Taranis", "D. GOOD PRE-FACTION TARANIS SIDE QUESTS"),
        ),
        Quest(
            id = "R3-C2-079",
            chapter = 2,
            playOrder = 79,
            title = "Back to Work",
            aliases = listOf(),
            category = "SAFE — WORKER CHAIN",
            giver = "Mine supervisor",
            location = "Taranis",
            prerequisites = "",
            summary = "Resolve the problems keeping the mine workers from returning to work.",
            walkthroughSteps = listOf("Walkthrough. Question the workers around the mine and complete their small linked requests. Garelt, Dakil and other miners are associated with this cluster.", "Completion. Report once the required workers are back on task."),
            reward = "Quest Glory",
            warnings = "",
            searchTags = listOf("Taranis", "E. MINES & WORKER QUESTS"),
        ),
        Quest(
            id = "R3-C2-080",
            chapter = 2,
            playOrder = 80,
            title = "The Shirker",
            aliases = listOf(),
            category = "SAFE — WORKER SUBQUEST",
            giver = "Mine NPC",
            location = "Taranis",
            prerequisites = "",
            summary = "Find and deal with the worker avoiding his duties.",
            walkthroughSteps = listOf("Walkthrough. Follow the dialogue clues from the mine camp and confront the named worker.", "Completion. Resolve the dispute and report back."),
            reward = "Quest Glory",
            warnings = "",
            searchTags = listOf("Taranis", "E. MINES & WORKER QUESTS"),
        ),
        Quest(
            id = "R3-C2-081",
            chapter = 2,
            playOrder = 81,
            title = "Huge Responsibility, Huge Thirst",
            aliases = listOf(),
            category = "SAFE — DELIVERY",
            giver = "Mine NPC",
            location = "Taranis",
            prerequisites = "",
            summary = "Bring the requested drink to the overworked miner/foreman.",
            walkthroughSteps = listOf("Walkthrough. Keep rum or other requested alcohol in your inventory and hand it over through dialogue.", "Completion. The delivery completes the quest."),
            reward = "Quest Glory",
            warnings = "",
            searchTags = listOf("Taranis", "E. MINES & WORKER QUESTS"),
        ),
        Quest(
            id = "R3-C2-082",
            chapter = 2,
            playOrder = 82,
            title = "Nightcap",
            aliases = listOf(),
            category = "SAFE — DELIVERY",
            giver = "Mine NPC",
            location = "Taranis",
            prerequisites = "",
            summary = "Provide the requested night drink.",
            walkthroughSteps = listOf("Walkthrough. Speak with the worker at the appropriate time and give the required alcohol.", "Completion. Complete the delivery."),
            reward = "Quest Glory",
            warnings = "",
            searchTags = listOf("Taranis", "E. MINES & WORKER QUESTS"),
        ),
        Quest(
            id = "R3-C2-083",
            chapter = 2,
            playOrder = 83,
            title = "Throwing Education",
            aliases = listOf(),
            category = "SAFE — KNIFE THROWING",
            giver = "Taranis trainer",
            location = "Taranis",
            prerequisites = "",
            summary = "Complete the knife-throwing lesson/challenge.",
            walkthroughSteps = listOf("Walkthrough. Accept the throwing challenge and use the same timing principles as previous island minigames.", "Completion. Reach the required score."),
            reward = "Quest Glory",
            warnings = "",
            searchTags = listOf("Taranis", "F. TRAINING & MINIGAMES"),
        ),
        Quest(
            id = "R3-C2-084",
            chapter = 2,
            playOrder = 84,
            title = "Dead On",
            aliases = listOf(),
            category = "SAFE — TARGET CHALLENGE",
            giver = "Taranis trainer",
            location = "Taranis",
            prerequisites = "",
            summary = "Hit the required targets accurately.",
            walkthroughSteps = listOf("Walkthrough. Start the shooting/throwing challenge and focus on accuracy rather than speed.", "Completion. Beat the required score."),
            reward = "Quest Glory",
            warnings = "",
            searchTags = listOf("Taranis", "F. TRAINING & MINIGAMES"),
        ),
        Quest(
            id = "R3-C2-085",
            chapter = 2,
            playOrder = 85,
            title = "Strong Arms",
            aliases = listOf(),
            category = "SAFE — ARM WRESTLING",
            giver = "Taranis NPC",
            location = "Taranis",
            prerequisites = "",
            summary = "Win the arm-wrestling contest.",
            walkthroughSteps = listOf("Walkthrough. Challenge the NPC at the arm-wrestling table and follow the displayed input sequence.", "Completion. Win the contest."),
            reward = "Quest Glory",
            warnings = "",
            searchTags = listOf("Taranis", "F. TRAINING & MINIGAMES"),
        ),
        Quest(
            id = "R3-C2-086",
            chapter = 2,
            playOrder = 86,
            title = "Squashed",
            aliases = listOf(),
            category = "SAFE — COMBAT / MINIGAME",
            giver = "Taranis NPC",
            location = "Taranis",
            prerequisites = "",
            summary = "Complete the local challenge associated with the quest.",
            walkthroughSteps = listOf("Walkthrough. Accept the challenge and follow its combat/minigame objective.", "Completion. Report the win."),
            reward = "Quest Glory",
            warnings = "",
            searchTags = listOf("Taranis", "F. TRAINING & MINIGAMES"),
        ),
        Quest(
            id = "R3-C2-087",
            chapter = 2,
            playOrder = 87,
            title = "The Treasure on the Beach of Taranis",
            aliases = listOf(),
            category = "SAFE — TREASURE",
            giver = "Treasure Map",
            location = "Taranis",
            prerequisites = "",
            summary = "Take the Treasure Map from the main mage building, then dig up the chest on the northern islet.",
            walkthroughSteps = listOf("Walkthrough. After Visiting Rights, go upstairs in the main mage building and take the Treasure Map. Bring a Shovel, travel to the small northern islet and look for the red X.", "Completion. Dig up and loot the chest."),
            reward = "100 Glory + treasure",
            warnings = "",
            searchTags = listOf("Taranis", "G. TREASURES & CROSS-ISLAND HOOKS"),
        ),
        Quest(
            id = "R3-C2-088",
            chapter = 2,
            playOrder = 88,
            title = "The Swordmaster's Treasure",
            aliases = listOf(),
            category = "CROSS-ISLAND TREASURE",
            giver = "Swordmaster book",
            location = "Taranis",
            prerequisites = "",
            summary = "Read the Swordmaster book in the mage building, then follow the treasure quest to Kila.",
            walkthroughSteps = listOf("Walkthrough. After Visiting Rights, go upstairs and read the Swordmaster book. This starts a treasure quest whose actual dig site is on Kila.", "Completion. Leave it active until the Kila return route."),
            reward = "Quest progression",
            warnings = "⚠ Important: Do not force a Kila treasure into the Taranis-only walkthrough.",
            searchTags = listOf("Taranis", "G. TREASURES & CROSS-ISLAND HOOKS"),
        ),
        Quest(
            id = "R3-C2-089",
            chapter = 2,
            playOrder = 89,
            title = "The Gourmet",
            aliases = listOf(),
            category = "CROSS-ISLAND COLLECTION",
            giver = "Taranis quest chain",
            location = "Taranis",
            prerequisites = "",
            summary = "Start/advance the gourmet ingredient hunt and keep any exquisite food items you find.",
            walkthroughSteps = listOf("Chapter 2 — Antigua — H. CROSS-ISLAND / FACTION QUESTS TO LEAVE FOR LATER", "Started on Taranis; Antigua provides the Dainty Mussels in the tavern's upper floor. This is a real journal quest, but it is intentionally deferred rather than half-completed in the Antigua-first route.", "Chapter 2 — Taranis — G. TREASURES & CROSS-ISLAND HOOKS", "Quest giver: Taranis quest chain", "Status: CROSS-ISLAND COLLECTION", "Area: Taranis", "Reward: Quest Glory", "Walkthrough. The Gourmet spans multiple islands. Taranis has some required items, while Antigua/Kila provide others.", "Completion. Keep it active until the full ingredient set is complete."),
            reward = "Quest Glory",
            warnings = "",
            searchTags = listOf("Antigua", "Taranis", "H. CROSS-ISLAND / FACTION QUESTS TO LEAVE FOR LATER", "G. TREASURES & CROSS-ISLAND HOOKS"),
        ),
        Quest(
            id = "R3-C2-090",
            chapter = 2,
            playOrder = 90,
            title = "Evil Eye",
            aliases = listOf(),
            category = "CROSS-ISLAND COLLECTION",
            giver = "Taranis quest chain",
            location = "Taranis",
            prerequisites = "",
            summary = "Collect the required prisms/items across the islands.",
            walkthroughSteps = listOf("Chapter 2 — Antigua — H. CROSS-ISLAND / FACTION QUESTS TO LEAVE FOR LATER", "Started on Taranis; one of the required prisms is on Antigua. This is a real journal quest, but it is intentionally deferred rather than half-completed in the Antigua-first route.", "Chapter 2 — Taranis — G. TREASURES & CROSS-ISLAND HOOKS", "Quest giver: Taranis quest chain", "Status: CROSS-ISLAND COLLECTION", "Area: Taranis", "Reward: Quest Glory", "Walkthrough. Taranis contains one of the required quest components. Preserve it and continue the chain when visiting the other regions.", "Completion. Complete only when all cross-island components are collected."),
            reward = "Quest Glory",
            warnings = "",
            searchTags = listOf("Antigua", "Taranis", "H. CROSS-ISLAND / FACTION QUESTS TO LEAVE FOR LATER", "G. TREASURES & CROSS-ISLAND HOOKS"),
        ),
        Quest(
            id = "R3-C2-091",
            chapter = 2,
            playOrder = 91,
            title = "Advancing Among the Guardians",
            aliases = listOf("Important post-join quest: Advancing Among the Guardians"),
            category = "Side quest",
            giver = "",
            location = "Taranis",
            prerequisites = "",
            summary = "Guardian-only progression after joining the faction. It is a real quest but is intentionally deferred from the Chapter 2 pre-faction route.",
            walkthroughSteps = listOf("Chapter 2 — Taranis — I. LATER / POST-FACTION TARANIS QUESTS — DEFER", "Guardian-only progression after joining the faction. It is a real quest but is intentionally deferred from the Chapter 2 pre-faction route.", "Chapter 2 — Taranis — 5. GUARDIANS — TARANIS", "Magnus offers Advancing Among the Guardians after you become a Cadet. The promotion route includes work for Mauricio, Ilvar and Gordon, the Waterproof quest, defeating a Golem, gathering Pure Iron Ore from Calador, and can also include proving yourself against the Shadow Lord of Betrayal and Magnus. Completing the required tasks promotes the hero further and unlocks A Guardian's Armor."),
            reward = "",
            warnings = "",
            searchTags = listOf("Taranis", "I. LATER / POST-FACTION TARANIS QUESTS — DEFER", "5. GUARDIANS — TARANIS"),
        ),
        Quest(
            id = "R3-C2-092",
            chapter = 2,
            playOrder = 92,
            title = "A New Rank — Guardians",
            aliases = listOf("A New Rank"),
            category = "Side quest",
            giver = "",
            location = "Taranis",
            prerequisites = "",
            summary = "Guardian promotion chain; requires Cadet/Guardian progression. It is a real quest but is intentionally deferred from the Chapter 2 pre-faction route.",
            walkthroughSteps = listOf("Guardian promotion chain; requires Cadet/Guardian progression. It is a real quest but is intentionally deferred from the Chapter 2 pre-faction route."),
            reward = "",
            warnings = "",
            searchTags = listOf("Taranis", "I. LATER / POST-FACTION TARANIS QUESTS — DEFER"),
        ),
        Quest(
            id = "R3-C2-093",
            chapter = 2,
            playOrder = 93,
            title = "A Guardian's Armor / New Armour",
            aliases = listOf(),
            category = "Side quest",
            giver = "",
            location = "Taranis",
            prerequisites = "",
            summary = "Post-faction equipment progression. It is a real quest but is intentionally deferred from the Chapter 2 pre-faction route.",
            walkthroughSteps = listOf("Post-faction equipment progression. It is a real quest but is intentionally deferred from the Chapter 2 pre-faction route."),
            reward = "",
            warnings = "",
            searchTags = listOf("Taranis", "I. LATER / POST-FACTION TARANIS QUESTS — DEFER"),
        ),
        Quest(
            id = "R3-C2-094",
            chapter = 2,
            playOrder = 94,
            title = "Waterproof",
            aliases = listOf(),
            category = "Side quest",
            giver = "",
            location = "Taranis",
            prerequisites = "",
            summary = "Guardian progression quest. It is a real quest but is intentionally deferred from the Chapter 2 pre-faction route.",
            walkthroughSteps = listOf("Guardian progression quest. It is a real quest but is intentionally deferred from the Chapter 2 pre-faction route."),
            reward = "",
            warnings = "",
            searchTags = listOf("Taranis", "I. LATER / POST-FACTION TARANIS QUESTS — DEFER"),
        ),
        Quest(
            id = "R3-C2-095",
            chapter = 2,
            playOrder = 95,
            title = "Bring Zakir's Auri Culci Back",
            aliases = listOf(),
            category = "Side quest",
            giver = "",
            location = "Taranis",
            prerequisites = "",
            summary = "Later/cross-island gnome quest. It is a real quest but is intentionally deferred from the Chapter 2 pre-faction route.",
            walkthroughSteps = listOf("Later/cross-island gnome quest. It is a real quest but is intentionally deferred from the Chapter 2 pre-faction route."),
            reward = "",
            warnings = "",
            searchTags = listOf("Taranis", "I. LATER / POST-FACTION TARANIS QUESTS — DEFER"),
        ),
        Quest(
            id = "R3-C2-096",
            chapter = 2,
            playOrder = 96,
            title = "Bring Zakir's Auri Culci Back Again",
            aliases = listOf(),
            category = "Side quest",
            giver = "",
            location = "Taranis",
            prerequisites = "",
            summary = "Follow-up to the Auri Culci chain. It is a real quest but is intentionally deferred from the Chapter 2 pre-faction route.",
            walkthroughSteps = listOf("Follow-up to the Auri Culci chain. It is a real quest but is intentionally deferred from the Chapter 2 pre-faction route."),
            reward = "",
            warnings = "",
            searchTags = listOf("Taranis", "I. LATER / POST-FACTION TARANIS QUESTS — DEFER"),
        ),
        Quest(
            id = "R3-C2-097",
            chapter = 2,
            playOrder = 97,
            title = "Alliance with the Inquisition",
            aliases = listOf(),
            category = "Side quest",
            giver = "",
            location = "Tacarigua",
            prerequisites = "",
            summary = "Work through Sebastiano and the Inquisition route so their vessel can later contribute to Pirate Alliance.",
            walkthroughSteps = listOf("Work through Sebastiano and the Inquisition route so their vessel can later contribute to Pirate Alliance."),
            reward = "",
            warnings = "",
            searchTags = listOf("Tacarigua", "TACARIGUA"),
        ),
        Quest(
            id = "R3-C2-098",
            chapter = 2,
            playOrder = 98,
            title = "News from Puerto Sacarico",
            aliases = listOf(),
            category = "Side quest",
            giver = "",
            location = "Tacarigua",
            prerequisites = "",
            summary = "Tacarigua side quest.",
            walkthroughSteps = listOf(),
            reward = "",
            warnings = "",
            searchTags = listOf("Tacarigua", "TACARIGUA"),
        ),
        Quest(
            id = "R3-C2-099",
            chapter = 2,
            playOrder = 99,
            title = "Kicking Ass",
            aliases = listOf(),
            category = "Side quest",
            giver = "",
            location = "Tacarigua",
            prerequisites = "",
            summary = "Tacarigua side quest.",
            walkthroughSteps = listOf(),
            reward = "",
            warnings = "",
            searchTags = listOf("Tacarigua", "TACARIGUA"),
        ),
        Quest(
            id = "R3-C2-100",
            chapter = 2,
            playOrder = 100,
            title = "Wet Behind the Ears",
            aliases = listOf(),
            category = "Side quest",
            giver = "",
            location = "Tacarigua",
            prerequisites = "",
            summary = "Tacarigua side quest.",
            walkthroughSteps = listOf(),
            reward = "",
            warnings = "",
            searchTags = listOf("Tacarigua", "TACARIGUA"),
        ),
        Quest(
            id = "R3-C2-101",
            chapter = 2,
            playOrder = 101,
            title = "The Treasure in the Deadlands of Tacarigua",
            aliases = listOf(),
            category = "Side quest",
            giver = "",
            location = "Tacarigua",
            prerequisites = "",
            summary = "Tacarigua side quest.",
            walkthroughSteps = listOf(),
            reward = "",
            warnings = "",
            searchTags = listOf("Tacarigua", "TACARIGUA"),
        ),
        Quest(
            id = "R3-C2-102",
            chapter = 2,
            playOrder = 102,
            title = "Vasco's Stuff",
            aliases = listOf(),
            category = "Side quest",
            giver = "",
            location = "Tacarigua",
            prerequisites = "",
            summary = "Tacarigua side quest.",
            walkthroughSteps = listOf(),
            reward = "",
            warnings = "",
            searchTags = listOf("Tacarigua", "TACARIGUA"),
        ),
        Quest(
            id = "R3-C2-103",
            chapter = 2,
            playOrder = 103,
            title = "Menacing Shadows",
            aliases = listOf(),
            category = "Side quest",
            giver = "",
            location = "Tacarigua",
            prerequisites = "",
            summary = "Tacarigua side quest.",
            walkthroughSteps = listOf(),
            reward = "",
            warnings = "",
            searchTags = listOf("Tacarigua", "TACARIGUA"),
        ),
        Quest(
            id = "R3-C2-104",
            chapter = 2,
            playOrder = 104,
            title = "Di Fuego's Corpse",
            aliases = listOf(),
            category = "Side quest",
            giver = "",
            location = "Tacarigua",
            prerequisites = "",
            summary = "Tacarigua side quest.",
            walkthroughSteps = listOf(),
            reward = "",
            warnings = "",
            searchTags = listOf("Tacarigua", "TACARIGUA"),
        ),
        Quest(
            id = "R3-C2-105",
            chapter = 2,
            playOrder = 105,
            title = "The Treasure in the Tacariguan Backcountry",
            aliases = listOf(),
            category = "Side quest",
            giver = "",
            location = "Tacarigua",
            prerequisites = "",
            summary = "Tacarigua side quest.",
            walkthroughSteps = listOf(),
            reward = "",
            warnings = "",
            searchTags = listOf("Tacarigua", "TACARIGUA"),
        ),
    )

    val notes: List<RisenGuideNote> = listOf(
        RisenGuideNote(2, 69, "New Allies — continued quest guidance", listOf("Quick solution: Help Magnus by solving the delayed crystal delivery from the nearby mine.", "Walkthrough. Offer Magnus your help. He sends you to Frink at the mine entrance. Speak with Frink and accept the crystal-delivery job. Search the mine and collect all four Pouches of Crystals; each pouch gives Glory. Before leaving, talk with Garelt about the delay to unlock extra side content. Return to Frink with all four pouches, then report to Magnus.", "Completion. Magnus recognizes your work and grants access toward the inner mage area.", "⚠ Important: Do NOT choose the later initiation dialogue with Magnus yet.", "Quest giver: Bones / Magnus", "Status: MAIN STORY — GUARDIAN SUPPORT CHAIN", "Area: Taranis", "Reward: 750 Glory total for the major chain + gold rewards", "Related: Clear Rules / Visiting Rights")),
        RisenGuideNote(2, 91, "Pirate Alliance — continued quest guidance", listOf("Quick solution: Speak with Neron and learn that the Taranis ship becomes yours only after joining the Guardians.", "Walkthrough. Find Neron at the Taranis ship and discuss command. He will not hand over the vessel while you are still faction-neutral. After joining the Guardians, return and speak with him again.", "Completion. The Taranis ship step remains pending.", "⚠ Important: Do NOT join the Guardians merely to finish this now. Keep it pending until the dedicated faction-choice section.", "Quest giver: Admiral Alvarez / Neron", "Status: LONG-TERM — FACTION SHIP", "Area: Taranis", "Reward: 1200 Glory when eventually secured")),
        RisenGuideNote(2, 95, "Recruit Zacharias — continued quest guidance", listOf("Chapter 3 Spirit Ritual preparation. It is a real quest but is intentionally deferred from the Chapter 2 pre-faction route.")),
        RisenGuideNote(2, 95, "The Traitor — continued quest guidance", listOf("Later main-story Taranis content. It is a real quest but is intentionally deferred from the Chapter 2 pre-faction route.")),
        RisenGuideNote(2, 97, "PRE-FACTION STOPPING POINT", listOf("At this stage you have now investigated all three major factions: Demon Hunters on Calador, Natives on Kila and Guardians/Crystal Mages on Taranis. You have also helped each faction enough to understand its culture, quests and combat style without locking yourself in.")),
        RisenGuideNote(2, 97, "PART V COMPLETION CHECKLIST", listOf("Speak to Baker is complete.", "Tour of Taranis is complete.", "Mages Camp has been discovered.", "Magnus has been met and the Taranis step of Only Worth Half As Much advanced.", "New Allies' crystal-mine task is complete.", "Clear Rules is complete.", "Visiting Rights is complete.", "The Reactor has been started.", "A Follower of Magic is active or intentionally deferred to Tacarigua.", "Useful Taranis side quests were completed as desired.", "The Shadow Lord of Betrayal was defeated or intentionally left for later.", "Pirate Alliance's Taranis ship step is known but still pending.", "NO Guardian initiation dialogue has been accepted.", "A permanent pre-faction save exists.")),
        RisenGuideNote(2, 97, "WHAT COMES NEXT", listOf("Next should be a dedicated Faction Choice document rather than another island guide. We can compare Demon Hunters, Natives and Guardians side by side, show their unique skills/magic, armour, quest chains and ship consequences, then document the exact irreversible dialogue for each path. After that, Chapter 3's Spirit Ritual route becomes much cleaner.")),
        RisenGuideNote(2, 97, "TACARIGUA", listOf("Tacarigua is mandatory for the Taranis Reactor route because Erasmus sends the hero here to find Horas and his Monolith Stone. It also contains the Inquisition alliance route and a large collection of side quests.")),
        RisenGuideNote(2, 97, "A Follower of Magic — continued quest guidance", listOf("Sail to Tacarigua after Erasmus asks you to find Horas. Speak with Jack near the landing beach, reach Puerto Sacarico, locate Horas and resolve his situation. Horas carries one of the Monolith Stones required by The Reactor.")),
        RisenGuideNote(2, 97, "The Reactor — continued quest guidance", listOf("Return the Monolith Stone and Horas-related progress to Erasmus on Taranis. This remains a cross-island Chapter 2 parent quest.")),
        RisenGuideNote(2, 98, "Canonical Tacarigua side quests", listOf("News from Puerto Sacarico", "Kicking Ass", "Wet Behind the Ears", "The Treasure in the Deadlands of Tacarigua", "Vasco's Stuff", "Menacing Shadows", "Di Fuego's Corpse", "The Treasure in the Tacariguan Backcountry", "Off and Away", "The Commandant of Tacarigua", "Rodriguez's Spot of Bother", "Death to the Deserters", "Betray Horas", "The Nameless Captain's Treasure", "Unfathomable Riches", "A Stately Chest", "Parting of Ways", "Close Enough to Touch", "The Biggest Treasure", "The Shadow Lord of Madness", "The Happy Pirate's Treasure", "Become a Voodoo Master", "Recommended route: Puerto Sacarico first, then the central/backcountry deserter and Shadow quests, then treasure cleanup. Become a Voodoo Master is Native-only post-initiation content.")),
        RisenGuideNote(2, 118, "OPTIONAL REGION — FOG ISLAND", listOf("Fog Island is optional but worth clearing during Chapter 2 for Glory, equipment and Inquisition story content.")),
        RisenGuideNote(2, 127, "OPTIONAL REGION — ISLE OF THIEVES", listOf("The Isle of Thieves is optional but contains a dense gnome quest hub, strong loot and a useful amount of Glory.")),
        RisenGuideNote(2, 138, "THE MOST IMPORTANT SAVE IN CHAPTER 2", listOf("Make a permanent manual save NOW. This guide assumes you have already completed the neutral first visits to Calador, Kila and Taranis, met Admiral Alvarez on Antigua, and advanced each island's New Allies chain far enough to qualify for initiation. Joining any one of the three factions is irreversible: the other two initiation paths permanently close.", "This Part is primarily a decision guide. It does not invent journal quests merely to organize the comparison. Only the actual initiation/progression quests are treated as quests; everything else is guide advice.")),
        RisenGuideNote(2, 138, "1. QUICK COMPARISON", listOf("Home: Demon Hunters: Calador; Natives: Kila; Guardians: Taranis", "Leader: Demon Hunters: Eldric; Natives: Hirutu; Guardians: Magnus", "Starting rank: Demon Hunters: Scout; Natives: Voodoo Pirate; Guardians: Cadet", "Magic school: Demon Hunters: Rune Magic; Natives: Voodoo Magic; Guardians: Crystal Magic", "General style: Demon Hunters: Melee/rune hybrid, anti-Shadow; Natives: Utility, control, poison, possession; Guardians: Dedicated offensive/utility caster", "Ship for Pirate Alliance: Demon Hunters: Demon Hunter ship; Natives: Old pirate/Native ship; Guardians: Guardian/Mage ship", "Post-join progression: Demon Hunters: Ghost Eyes, ranks, armor; Natives: Become a Voodoo Master, ranks, apparel; Guardians: Advancing Among the Guardians, ranks, armor", "Best fit: Demon Hunters: Weapons + buffs/runes; Natives: Creative control / Voodoo; Guardians: Magic-heavy character")),
        RisenGuideNote(2, 138, "2. WHAT ALL THREE CHOICES HAVE IN COMMON", listOf("You must first complete the relevant New Allies branch and have met Admiral Alvarez on Antigua.", "The final initiation dialogue is irreversible.", "Joining gives 3,000 Glory in addition to branch-specific rewards.", "New faction-exclusive quests become available.", "Faction clothing/armor progression opens.", "Additional trainers and faction spells/abilities become available.", "The other two factions can no longer be joined.", "Pirate Alliance can now progress through your chosen faction's large ship.", "The Ancient Knowledge can finally be advanced with Eldric after you have joined one faction, which moves the main story toward the next chapter.")),
        RisenGuideNote(2, 138, "3. DEMON HUNTERS — CALADOR", listOf("Choose the Demon Hunters if you like conventional weapon combat backed by Rune Magic and abilities designed around hunting Shadows/demons. They are the most natural thematic continuation of Eldric's portal/Shadow storyline and fit a melee-focused hero especially well.")),
        RisenGuideNote(2, 139, "Demon Hunter strengths", listOf("Rune Magic becomes the faction spell school.", "Strong thematic synergy with melee weapons and anti-Shadow play.", "Faction-exclusive skills include Shadow-oriented hunting/survival options.", "Good choice if you prefer using weapons as your main damage source and magic as support.", "Calador's later quests and promotions feel tightly integrated with the main Shadow storyline.")),
    )
}
