package com.sliverzfx.gothicquest

internal object RisenGuidePart7Data {
    val quests: List<Quest> = listOf(
        Quest(
            id = "R1-C3-001",
            chapter = 3,
            playOrder = 1,
            title = "Secure the volcano keep",
            category = "SAFE — CHAPTER 3 HUB",
            giver = "Master Ignatius",
            location = "Chapter 3",
            prerequisites = "",
            summary = "Clear the Monastery invasion and complete the linked defence quests before returning to Mendoza.",
            walkthroughSteps = listOf("Walkthrough. After the volcano gate is opened, return to Volcano Keep. Fight through the Lizardmen and reach Ignatius. Complete Orders for the mages, The Lizard Warrior, Drive out the intruders!, The supplies from the library and Secure the gate! where available.", "Completion. Report to Ignatius after the Keep is secure.", "Related quests: Orders for the mages / Drive out the intruders! / The Lizard Warrior"),
            reward = "1000 XP",
            warnings = "",
            searchTags = listOf("Secure the volcano keep", "Master Ignatius", "", "SAFE — CHAPTER 3 HUB", "Orders for the mages / Drive out the intruders! / The Lizard Warrior", "A. VOLCANO KEEP — DO THIS BEFORE THE DEEP TEMPLE"),
        ),
        Quest(
            id = "R1-C3-002",
            chapter = 3,
            playOrder = 2,
            title = "Orders for the mages",
            category = "SAFE — DEFENCE",
            giver = "Master Ignatius",
            location = "Chapter 3",
            prerequisites = "",
            summary = "Find the surviving Masters and send them to the Hall of Flames.",
            walkthroughSteps = listOf("Walkthrough. Speak with Ignatius, then locate Cyrus, Illumar, Vitus and Abrax. Pallas is dead; loot his belongings/book for the follow-up with Ignatius. Tell each surviving Mage to gather in the Hall of Flames.", "Completion. Return to Ignatius after all surviving Masters have been rallied."),
            reward = "750 XP + small follow-up XP",
            warnings = "⚠ Important: Do not leave without looting Pallas; his book has a useful hand-in.",
            searchTags = listOf("Orders for the mages", "Master Ignatius", "", "SAFE — DEFENCE", "—", "A. VOLCANO KEEP — DO THIS BEFORE THE DEEP TEMPLE"),
        ),
        Quest(
            id = "R1-C3-003",
            chapter = 3,
            playOrder = 3,
            title = "The Lizard Warrior",
            category = "SAFE — COMBAT",
            giver = "Master Vitus",
            location = "Chapter 3",
            prerequisites = "",
            summary = "Kill the powerful Steadfast Lizard Warrior in the cemetery crypt.",
            walkthroughSteps = listOf("Walkthrough. Speak with Vitus during the siege. Enter the cemetery crypt and defeat the Lizard Warrior commanding the attackers there.", "Completion. Return to Vitus after the kill."),
            reward = "400 XP + report XP",
            warnings = "",
            searchTags = listOf("The Lizard Warrior", "Master Vitus", "", "SAFE — COMBAT", "—", "A. VOLCANO KEEP — DO THIS BEFORE THE DEEP TEMPLE"),
        ),
        Quest(
            id = "R1-C3-004",
            chapter = 3,
            playOrder = 4,
            title = "Drive out the intruders!",
            category = "SAFE — COMBAT",
            giver = "Master Abrax",
            location = "Chapter 3",
            prerequisites = "",
            summary = "Kill all ten Lizardman intruders inside the library.",
            walkthroughSteps = listOf("Walkthrough. Find Abrax near the rear library entrance. Use the secret/broken entrance and clear every marked intruder from the library rooms.", "Completion. The quest completes after all ten are dead; report back to Abrax.", "Related quests: The supplies from the library"),
            reward = "500 XP + report XP",
            warnings = "",
            searchTags = listOf("Drive out the intruders!", "Master Abrax", "", "SAFE — COMBAT", "The supplies from the library", "A. VOLCANO KEEP — DO THIS BEFORE THE DEEP TEMPLE"),
        ),
        Quest(
            id = "R1-C3-005",
            chapter = 3,
            playOrder = 5,
            title = "The supplies from the library",
            category = "SAFE — COLLECTION",
            giver = "Master Abrax",
            location = "Chapter 3",
            prerequisites = "",
            summary = "Recover Abrax's notes and three packages of alchemical supplies from the invaded library.",
            walkthroughSteps = listOf("Walkthrough. While clearing the library, loot the Lizardmen and search the rooms. Collect Abrax's notes plus all three alchemical-supply packages.", "Completion. Return the supplies to Abrax, or use the Sirius route if you want his linked quest.", "Related quests: Sirius has Problems with Abrax"),
            reward = "500 XP",
            warnings = "⚠ Important: If you want Sirius has Problems with Abrax, speak with Sirius before handing everything directly to Abrax.",
            searchTags = listOf("The supplies from the library", "Master Abrax", "", "SAFE — COLLECTION", "Sirius has Problems with Abrax", "A. VOLCANO KEEP — DO THIS BEFORE THE DEEP TEMPLE"),
        ),
        Quest(
            id = "R1-C3-006",
            chapter = 3,
            playOrder = 6,
            title = "Sirius has Problems with Abrax",
            category = "OPTIONAL — NOT BANDIT IN SOME VERSIONS",
            giver = "Sirius",
            location = "Chapter 3",
            prerequisites = "",
            summary = "Give Sirius Abrax's notes and alchemical supplies so he can finally impress his master.",
            walkthroughSteps = listOf("Walkthrough. Find Sirius deeper in/near the library after recovering Abrax's materials. Speak with him about being ignored by Abrax.", "Completion. Give him the notes and supplies; you can give them freely or charge him gold."),
            reward = "500 XP",
            warnings = "⚠ Important: Some walkthroughs report Sirius does not appear here on the Bandit route.",
            searchTags = listOf("Sirius has Problems with Abrax", "Sirius", "", "OPTIONAL — NOT BANDIT IN SOME VERSIONS", "—", "A. VOLCANO KEEP — DO THIS BEFORE THE DEEP TEMPLE"),
        ),
        Quest(
            id = "R1-C3-007",
            chapter = 3,
            playOrder = 7,
            title = "Secure the gate!",
            category = "MAGE / ROUTE-DEPENDENT",
            giver = "Santiago",
            location = "Chapter 3",
            prerequisites = "",
            summary = "Find Kalib inside the invaded Keep and send him to Santiago at the main gate.",
            walkthroughSteps = listOf("Walkthrough. Speak with Santiago at the front gate. Go inside the Keep and find Kalib hiding near the southwest/interior section, then tell him to help Santiago.", "Completion. The quest completes when Kalib heads to the gate."),
            reward = "Quest XP",
            warnings = "⚠ Important: This quest is known to be route/version-sensitive and historically buggy if Kalib dies during the invasion.",
            searchTags = listOf("Secure the gate!", "Santiago", "", "MAGE / ROUTE-DEPENDENT", "—", "A. VOLCANO KEEP — DO THIS BEFORE THE DEEP TEMPLE"),
        ),
        Quest(
            id = "R1-C3-008",
            chapter = 3,
            playOrder = 8,
            title = "Spying Scouts",
            category = "ORDER-SIDE / WORLD",
            giver = "Magnus",
            location = "Chapter 3",
            prerequisites = "",
            summary = "Kill the three Lizardman scouts near Harbour Town's secret entrance.",
            walkthroughSteps = listOf("Walkthrough. Speak with Magnus outside the front gate after Carlos sends you to check the city's defences. Go around to the beach/secret-entrance side and kill all three scouts.", "Completion. Report to Magnus."),
            reward = "300 XP",
            warnings = "",
            searchTags = listOf("Spying Scouts", "Magnus", "", "ORDER-SIDE / WORLD", "—", "B. HARBOUR TOWN — ORDER-SIDE LIZARD CLEANUP"),
        ),
        Quest(
            id = "R1-C3-009",
            chapter = 3,
            playOrder = 9,
            title = "The lizard leader outside Harbour Town",
            category = "ORDER-SIDE / WORLD",
            giver = "Carlos / Magnus",
            location = "Chapter 3",
            prerequisites = "",
            summary = "Kill the Lizard Leader threatening the front side of Harbour Town.",
            walkthroughSteps = listOf("Walkthrough. Talk to Carlos, then Magnus. Follow the road outside the main gate and fight through the Lizardmen to the leader.", "Completion. Kill the leader and report back."),
            reward = "500 XP",
            warnings = "",
            searchTags = listOf("The lizard leader outside Harbour Town", "Carlos / Magnus", "", "ORDER-SIDE / WORLD", "—", "B. HARBOUR TOWN — ORDER-SIDE LIZARD CLEANUP"),
        ),
        Quest(
            id = "R1-C3-010",
            chapter = 3,
            playOrder = 10,
            title = "The lizard leader behind Harbour Town",
            category = "ORDER-SIDE / WORLD",
            giver = "Carlos / Leto",
            location = "Chapter 3",
            prerequisites = "",
            summary = "Kill the Lizard Leader attacking the rear/eastern side of Harbour Town.",
            walkthroughSteps = listOf("Walkthrough. Speak with Leto at the eastern/rear side of the city. Clear the nearby groups and defeat their leader.", "Completion. Report the result to the relevant Order NPC."),
            reward = "500 XP",
            warnings = "",
            searchTags = listOf("The lizard leader behind Harbour Town", "Carlos / Leto", "", "ORDER-SIDE / WORLD", "—", "B. HARBOUR TOWN — ORDER-SIDE LIZARD CLEANUP"),
        ),
        Quest(
            id = "R1-C3-011",
            chapter = 3,
            playOrder = 11,
            title = "The leader of the lizard warriors",
            category = "ORDER-SIDE / WORLD",
            giver = "Carlos",
            location = "Chapter 3",
            prerequisites = "",
            summary = "Kill the remaining two Lizard Leaders elsewhere on the island.",
            walkthroughSteps = listOf("Walkthrough. After the Harbour Town leaders, hunt the additional leaders near the Plains Temple above Severin's farm and on the western side of the island. Each is accompanied by strong Lizardmen/Elite Warriors.", "Completion. After the required leaders are dead, report to Carlos."),
            reward = "500 XP + report reward",
            warnings = "⚠ Important: Bandits/Mages can still kill the leaders for combat/completion XP, but Carlos-specific reporting is Order-route content.",
            searchTags = listOf("The leader of the lizard warriors", "Carlos", "", "ORDER-SIDE / WORLD", "—", "B. HARBOUR TOWN — ORDER-SIDE LIZARD CLEANUP"),
        ),
        Quest(
            id = "R1-C3-012",
            chapter = 3,
            playOrder = 12,
            title = "Talk with Don Esteban in Harbour Town",
            category = "BANDIT ONLY",
            giver = "Don Esteban",
            location = "Chapter 3",
            prerequisites = "",
            summary = "After Esteban returns to Harbour Town, meet him in his former house.",
            walkthroughSteps = listOf("Walkthrough. Complete the Bandit route that restores Esteban to Harbour Town, then visit the Don in town.", "Completion. Speak with him to complete the Chapter 3 Bandit follow-up."),
            reward = "300 XP",
            warnings = "",
            searchTags = listOf("Talk with Don Esteban in Harbour Town", "Don Esteban", "", "BANDIT ONLY", "—", "C. BANDIT-ONLY HARBOUR TOWN FOLLOW-UP"),
        ),
        Quest(
            id = "R1-C3-013",
            chapter = 3,
            playOrder = 13,
            title = "Open the great gate",
            category = "MAIN STORY",
            giver = "Inquisitor Mendoza",
            location = "Chapter 3",
            prerequisites = "",
            summary = "Use Nautilus Transformation, a pickaxe, two Old Busts and the temple winch to open the Great Gate.",
            walkthroughSteps = listOf("Walkthrough. Follow Mendoza into the volcano. After the first fights, head north/right and climb the ledges to a tiny Nautilus hole. Transform and crawl through. Work through the trapped passages: avoid/drop through floor traps as required, kill the Lizardmen/Brontoks and use the mechanisms. A Watchman carries an Old Bust; another Watchman later carries the second. Break the thin wall with your pickaxe to bypass the trap corridor. Place both Old Busts on the two altars, pass through the opened grate and turn the winch.", "Completion. Return to Mendoza, speak with him and read the Inscribed Column near his former position.", "Related quests: The tunnel"),
            reward = "1000 XP",
            warnings = "⚠ Important: Chapter 3 contains five important Inscribed Columns in the temple. Read each one as you encounter it; they matter for Eldric's later temple report.",
            searchTags = listOf("Open the great gate", "Inquisitor Mendoza", "", "MAIN STORY", "The tunnel", "D. VOLCANO TEMPLE — OPENING THE GREAT GATE"),
        ),
        Quest(
            id = "R1-C3-014",
            chapter = 3,
            playOrder = 14,
            title = "The tunnel",
            category = "MAIN STORY — TRAP",
            giver = "Inquisitor Mendoza",
            location = "Chapter 3",
            prerequisites = "",
            summary = "Disable the crushing-block trap with Telekinesis.",
            walkthroughSteps = listOf("Walkthrough. After the Great Gate opens, Mendoza tells you to scout ahead. Walk only far enough to see the trap mechanism. Do not run to the end of the passage. Target the distant lever with Telekinesis and activate it.", "Completion. The trap shuts down and Mendoza's group moves forward."),
            reward = "500 XP",
            warnings = "⚠ Important: Running directly through the tunnel can get you crushed.",
            searchTags = listOf("The tunnel", "Inquisitor Mendoza", "", "MAIN STORY — TRAP", "—", "D. VOLCANO TEMPLE — OPENING THE GREAT GATE"),
        ),
        Quest(
            id = "R1-C3-015",
            chapter = 3,
            playOrder = 15,
            title = "Open the large drawbridge",
            category = "MAIN STORY — MULTI-STAGE",
            giver = "Inquisitor Mendoza",
            location = "Chapter 3",
            prerequisites = "",
            summary = "Reach the inner temple, obtain the map, enter the crypt complex and operate the Gatekeeper's winch to lower the drawbridge.",
            walkthroughSteps = listOf("Walkthrough. From Mendoza's blocked drawbridge, take the right-hand route. At the lava gap, use Telekinesis/ranged attack on the winch across the chasm to lower the small bridge. Continue to Brent, then complete The search for the map. Return to Mendoza and follow the expedition deeper. Eventually reach the crypt complex, defeat the Gatekeeper, loot the Crypt Key and turn the nearby winch.", "Completion. The large drawbridge lowers and Mendoza's men can enter.", "Related quests: The search for the map / The opening to the crypt / The crypt has been reached"),
            reward = "1000 XP",
            warnings = "",
            searchTags = listOf("Open the large drawbridge", "Inquisitor Mendoza", "", "MAIN STORY — MULTI-STAGE", "The search for the map / The opening to the crypt / The crypt has been reached", "E. THE DRAWBRIDGE & MAP HUNT"),
        ),
        Quest(
            id = "R1-C3-016",
            chapter = 3,
            playOrder = 16,
            title = "The search for the map",
            category = "MAIN STORY — EXPLORATION",
            giver = "Brent",
            location = "Chapter 3",
            prerequisites = "",
            summary = "Find Jorgensen, track the Lizard hunting party and take the temple map from their Leader.",
            walkthroughSteps = listOf("Walkthrough. Speak with Brent beyond the small drawbridge. Descend into the swamp and find Jorgensen. Follow his directions uphill toward the temple exit. Kill the Watchman near the exit and take his cell key; free Drok if desired for extra combat help. Continue outside, speak with Eldric on the route, then head to Jasmin and Henrik's hut. Kill the Lizard hunting party and their Leader.", "Completion. Loot the map from the Leader and show it to Mendoza.", "Related quests: Lizard invasion"),
            reward = "750 XP",
            warnings = "",
            searchTags = listOf("The search for the map", "Brent", "", "MAIN STORY — EXPLORATION", "Lizard invasion", "E. THE DRAWBRIDGE & MAP HUNT"),
        ),
        Quest(
            id = "R1-C3-017",
            chapter = 3,
            playOrder = 17,
            title = "Lizard invasion",
            category = "MAIN STORY / COMBAT",
            giver = "World / Jasmin-Henrik area",
            location = "Chapter 3",
            prerequisites = "",
            summary = "Kill the Lizard hunting group and Leader attacking the east-coast hunter area.",
            walkthroughSteps = listOf("Walkthrough. This overlaps directly with The search for the map. Follow the route out of the temple toward Jasmin and Henrik's hut and defeat the Lizardmen there.", "Completion. The invasion objective completes when the group and Leader are dead."),
            reward = "200 XP",
            warnings = "",
            searchTags = listOf("Lizard invasion", "World / Jasmin-Henrik area", "", "MAIN STORY / COMBAT", "—", "E. THE DRAWBRIDGE & MAP HUNT"),
        ),
        Quest(
            id = "R1-C3-018",
            chapter = 3,
            playOrder = 18,
            title = "The opening to the crypt",
            category = "MAIN STORY",
            giver = "Inquisitor Mendoza",
            location = "Chapter 3",
            prerequisites = "",
            summary = "Find the digger working on the weak wall, report back and use the Old Bust/altar route to progress.",
            walkthroughSteps = listOf("Walkthrough. After giving Mendoza the map, follow him deeper. He asks you to check the weak wall. Walk back to the digger working there — walkthroughs note that the journal/dialogue may refer to Ethan while the actual NPC is Vince. Report his progress to Mendoza, then follow the next route. Use the Old Bust on the altar and clear the enemies around the Inscribed Column.", "Completion. Report the opened/advanced crypt route to Mendoza."),
            reward = "Quest XP",
            warnings = "⚠ Important: NPC naming around Ethan/Vince is inconsistent in older English walkthroughs; follow the active digger at the weak wall.",
            searchTags = listOf("The opening to the crypt", "Inquisitor Mendoza", "", "MAIN STORY", "—", "F. OPENING THE CRYPT"),
        ),
        Quest(
            id = "R1-C3-019",
            chapter = 3,
            playOrder = 19,
            title = "The crypt has been reached",
            category = "MAIN STORY — NAUTILUS",
            giver = "Inquisitor Mendoza",
            location = "Chapter 3",
            prerequisites = "",
            summary = "Use Nautilus Transformation to crawl through the opening made in the crypt wall.",
            walkthroughSteps = listOf("Walkthrough. After the digger creates a small gap, Mendoza tells you to use the transformation spell. Turn into a Nautilus and crawl through the opening.", "Completion. Entering the crypt complex completes the quest."),
            reward = "1000 XP",
            warnings = "",
            searchTags = listOf("The crypt has been reached", "Inquisitor Mendoza", "", "MAIN STORY — NAUTILUS", "—", "F. OPENING THE CRYPT"),
        ),
        Quest(
            id = "R1-C3-020",
            chapter = 3,
            playOrder = 20,
            title = "Free the Ghost of Ursegor",
            category = "MAIN STORY — THREE SERVANTS",
            giver = "Ursegor",
            location = "Chapter 3",
            prerequisites = "",
            summary = "Kill Zul Utur, Zel Zeret and Zal Zaran, collect their Soul Splinters and skulls, then return to Ursegor.",
            walkthroughSteps = listOf("Walkthrough. Use the Gatekeeper's Crypt Key to open Ursegor's chamber. Speak with the ghost, then take the Lizard Bust near his sarcophagus. Use that same bust on each of the three servant-room altars — remember to take it back after each room. Kill Zul Utur (undead priest), Zel Zeret (undead beast) and Zal Zaran (undead guardian). Loot each Soul Splinter and corresponding skull.", "Completion. Return all three Soul Splinters to Ursegor and free his spirit. Take Ursegor's skull from the sarcophagus afterward.", "Related quests: The Titan trap"),
            reward = "1000 XP",
            warnings = "⚠ Important: Do not leave the Lizard Bust on an altar; you reuse the same one for all three doors.",
            searchTags = listOf("Free the Ghost of Ursegor", "Ursegor", "", "MAIN STORY — THREE SERVANTS", "The Titan trap", "G. URSEGOR"),
        ),
        Quest(
            id = "R1-C3-021",
            chapter = 3,
            playOrder = 21,
            title = "The Titan trap",
            category = "MAIN STORY — CHAPTER END",
            giver = "Inquisitor Mendoza / Ursegor",
            location = "Chapter 3",
            prerequisites = "",
            summary = "Place the four skulls on the Golden Gate altars in the correct order and trigger Mendoza's betrayal.",
            walkthroughSteps = listOf("Walkthrough. At the Golden Gate, face the four altars. Place the skulls from left to right as follows: 1) Skull of the Undead Beast, 2) Skull of the Undead Priest, 3) Skull of the Undead Guardian, 4) Skull of Ursegor.", "Completion. The gate opens. Mendoza reveals his intentions and the Chapter 3 finale triggers, leading directly into Chapter 4."),
            reward = "Major story progression",
            warnings = "⚠ Important: Make a permanent save before opening the Golden Gate. Chapter 4 begins immediately afterward.",
            searchTags = listOf("The Titan trap", "Inquisitor Mendoza / Ursegor", "", "MAIN STORY — CHAPTER END", "—", "G. URSEGOR"),
        ),
    )

    val notes: List<RisenGuideNote> = listOf(
        RisenGuideNote(3, 1, "Chapter 3 overview", listOf("Chapter 3 begins after the five Crystal Disks open the volcano gate and Mendoza leads the expedition into the temple. Before committing to the deep temple route, a completionist should return to Volcano Keep and clean up the Lizardman invasion. The chapter then follows Mendoza through the Great Gate, the temple tunnels, the large drawbridge, the map hunt, the crypt and finally Ursegor.", "Essential preparation: Carry several Levitation, Telekinesis and Nautilus Transformation scrolls/spells, plus a pickaxe. Chapter 3 repeatedly requires all four.")),
        RisenGuideNote(3, 1, "A. VOLCANO KEEP — DO THIS BEFORE THE DEEP TEMPLE", listOf()),
        RisenGuideNote(3, 8, "B. HARBOUR TOWN — ORDER-SIDE LIZARD CLEANUP", listOf()),
        RisenGuideNote(3, 12, "C. BANDIT-ONLY HARBOUR TOWN FOLLOW-UP", listOf()),
        RisenGuideNote(3, 13, "D. VOLCANO TEMPLE — OPENING THE GREAT GATE", listOf()),
        RisenGuideNote(3, 15, "E. THE DRAWBRIDGE & MAP HUNT", listOf()),
        RisenGuideNote(3, 18, "F. OPENING THE CRYPT", listOf()),
        RisenGuideNote(3, 20, "G. URSEGOR", listOf()),
        RisenGuideNote(3, 22, "CHAPTER 3 COMPLETION CHECKLIST", listOf("Volcano Keep was secured before committing to the deep temple expedition.", "Orders for the mages, The Lizard Warrior, Drive out the intruders!, and library supplies were completed.", "Sirius's quest was checked before handing Abrax's supplies away.", "Order-route players cleared the Harbour Town Lizard leaders/scouts.", "Bandit-route players spoke with Don Esteban in Harbour Town.", "You entered the temple with Levitation, Telekinesis, Nautilus Transformation and a pickaxe.", "The Great Gate and tunnel trap were solved.", "All five temple Inscribed Columns encountered so far were read for Eldric's later report.", "The map was recovered from the Lizard Leader near Jasmin/Henrik.", "The large drawbridge was lowered.", "Ursegor was freed and all four required skulls were obtained.", "A permanent save exists before The Titan Trap.", "The Golden Gate was opened only when ready to begin Chapter 4.")),
    )
}
