package com.sliverzfx.gothicquest

internal object Risen3ItemData {
    val entries: List<ToolReferenceEntry> = listOf(part0(), part1(), part2()).flatten()

    private fun part0(): List<ToolReferenceEntry> = listOf(
        ToolReferenceEntry("r3_legendary_booze_for_aiming", "LEGENDARY • CALADOR", "Booze for Aiming", "Permanent bonus: Critical Hit +10\n\nCitadel: southern shelf beside the upstairs stairway.", command = null, source = "https://www.gamepressure.com/risen3/calador-legendary-items/za668f", codeCategory = CodeCategory.ITEMS),
        ToolReferenceEntry("r3_legendary_tuning_fork", "LEGENDARY • CALADOR", "Tuning Fork", "Permanent bonus: Spirit +5\n\nCemetery north of the citadel: behind a northern grave.", command = null, source = "https://www.gamepressure.com/risen3/calador-legendary-items/za668f", codeCategory = CodeCategory.ITEMS),
        ToolReferenceEntry("r3_legendary_blunt_ritual_knife", "LEGENDARY • CALADOR", "Blunt Ritual Knife", "Permanent bonus: Daggers +10\n\nWin Henrik’s nighttime arm-wrestling contest, The Muscle Man.", command = null, source = "https://www.gamepressure.com/risen3/calador-legendary-items/za668f", codeCategory = CodeCategory.ITEMS),
        ToolReferenceEntry("r3_legendary_broken_lock_pick", "LEGENDARY • CALADOR", "Broken Lock Pick", "Permanent bonus: Lockpicking +10\n\nFenn’s attacked mountain farm: inside the hut.", command = null, source = "https://www.gamepressure.com/risen3/calador-legendary-items/za668f", codeCategory = CodeCategory.ITEMS),
        ToolReferenceEntry("r3_legendary_intractable_liana", "LEGENDARY • CALADOR", "Intractable Liana", "Permanent bonus: Slashing Weapons +10\n\nTirion’s beach camp; resolve Dangerous Liaison, then search the ground.", command = null, source = "https://www.gamepressure.com/risen3/calador-legendary-items/za668f", codeCategory = CodeCategory.ITEMS),
        ToolReferenceEntry("r3_legendary_ornamental_belt", "LEGENDARY • CALADOR", "Ornamental Belt", "Permanent bonus: Toughness +5\n\nJohn’s Treasure: buried chest in western castle ruins.", command = null, source = "https://www.gamepressure.com/risen3/calador-legendary-items/za668f", codeCategory = CodeCategory.ITEMS),
        ToolReferenceEntry("r3_legendary_diamond_grinder", "LEGENDARY • CALADOR", "Diamond Grinder", "Permanent bonus: Piercing Weapons +10\n\nWilson’s reward for The Engagement Ring.", command = null, source = "https://www.gamepressure.com/risen3/calador-legendary-items/za668f", codeCategory = CodeCategory.ITEMS),
        ToolReferenceEntry("r3_legendary_crankshaft", "LEGENDARY • CALADOR", "Crankshaft", "Permanent bonus: Crossbows +10\n\nEastern lighthouse, bottom floor. Chapter 3: Recruit Eldric opens access.", command = null, source = "https://www.gamepressure.com/risen3/calador-legendary-items/za668f", codeCategory = CodeCategory.ITEMS),
        ToolReferenceEntry("r3_legendary_monocle", "LEGENDARY • KILA", "Monocle", "Permanent bonus: Astral Vision +10\n\nWin Buddy’s knife-throwing contest, Streamlined, at the beach shipwreck.", command = null, source = "https://www.gamepressure.com/risen3/kila-legendary-items/z466e3", codeCategory = CodeCategory.ITEMS),
        ToolReferenceEntry("r3_legendary_old_bow", "LEGENDARY • KILA", "Old Bow", "Permanent bonus: Muskets +10\n\nEastern section of the spider cave south of the pirate beach.", command = null, source = "https://www.gamepressure.com/risen3/kila-legendary-items/z466e3", codeCategory = CodeCategory.ITEMS),
        ToolReferenceEntry("r3_legendary_pestle", "LEGENDARY • KILA", "Pestle", "Permanent bonus: Alchemy +10\n\nEastern beach reached through the spider cave; watch for the Silverback.", command = null, source = "https://www.gamepressure.com/risen3/kila-legendary-items/z466e3", codeCategory = CodeCategory.ITEMS),
        ToolReferenceEntry("r3_legendary_tattered_scabbard", "LEGENDARY • KILA", "Tattered Scabbard", "Permanent bonus: Swords +10\n\nThe Swordmaster’s Treasure: buried chest on the offshore islet’s hill.", command = null, source = "https://www.gamepressure.com/risen3/kila-legendary-items/z466e3", codeCategory = CodeCategory.ITEMS),
        ToolReferenceEntry("r3_legendary_black_cats_paw", "LEGENDARY • KILA", "Black Cat’s Paw", "Permanent bonus: Voodoo Magic +10\n\nBuy from Bahati in the native village. Base price: 1800 gold.", command = null, source = "https://www.gamepressure.com/risen3/kila-legendary-items/z466e3", codeCategory = CodeCategory.ITEMS),
        ToolReferenceEntry("r3_legendary_pirate_flag", "LEGENDARY • KILA", "Pirate Flag", "Permanent bonus: Intimidate +10\n\nChapter 3: Capt’n Finch’s Treasure, northwestern Forbidden Valley. Bring a shovel.", command = null, source = "https://www.gamepressure.com/risen3/kila-legendary-items/z466e3", codeCategory = CodeCategory.ITEMS),
        ToolReferenceEntry("r3_legendary_glass_eye", "LEGENDARY • KILA", "Glass Eye", "Permanent bonus: Ranged +5\n\nChapter 3: highest spider-cave level near Margoloth; chest guarded by an Iron Golem.", command = null, source = "https://www.gamepressure.com/risen3/kila-legendary-items/z466e3", codeCategory = CodeCategory.ITEMS),
        ToolReferenceEntry("r3_legendary_small_gripping_pliers", "LEGENDARY • TARANIS", "Small Gripping Pliers", "Permanent bonus: Pickpocketing +10\n\nNightcap: beat Gordon at drinking in the mages’ nighttime tavern.", command = null, source = "https://www.gamepressure.com/risen3/taranis-legendary-items/z86756", codeCategory = CodeCategory.ITEMS),
        ToolReferenceEntry("r3_legendary_vague_promises", "LEGENDARY • TARANIS", "Vague Promises", "Permanent bonus: Influence +5\n\nLumbrok’s private chamber chest; access through Agila’s The Private Store.", command = null, source = "https://www.gamepressure.com/risen3/taranis-legendary-items/z86756", codeCategory = CodeCategory.ITEMS),
        ToolReferenceEntry("r3_legendary_blood_soaked_cloth", "LEGENDARY • TARANIS", "Blood-soaked Cloth", "Permanent bonus: Resist Magic +10\n\nSoutheastern offshore islet: western cave with rats and bats.", command = null, source = "https://www.gamepressure.com/risen3/taranis-legendary-items/z86756", codeCategory = CodeCategory.ITEMS),
        ToolReferenceEntry("r3_legendary_blue_quill", "LEGENDARY • TARANIS", "Blue Quill", "Permanent bonus: Silver Tongue +10\n\nOpen wooden crate on the northeastern beach.", command = null, source = "https://www.gamepressure.com/risen3/taranis-legendary-items/z86756", codeCategory = CodeCategory.ITEMS),
        ToolReferenceEntry("r3_legendary_gilded_orb", "LEGENDARY • TARANIS", "Gilded Orb", "Permanent bonus: Pistols +10\n\nBuy from Agila at the mages’ camp. Base price: 1800 gold.", command = null, source = "https://www.gamepressure.com/risen3/taranis-legendary-items/z86756", codeCategory = CodeCategory.ITEMS),
        ToolReferenceEntry("r3_legendary_sun_crystal", "LEGENDARY • TARANIS", "Sun Crystal", "Permanent bonus: Crystal Magic +10\n\nChapter 3: chest upstairs in Zacharias’s tower.", command = null, source = "https://www.gamepressure.com/risen3/taranis-legendary-items/z86756", codeCategory = CodeCategory.ITEMS),
        ToolReferenceEntry("r3_legendary_small_stone_tablet", "LEGENDARY • TARANIS", "Small Stone Tablet", "Permanent bonus: Rune Magic +10\n\nLumbrok’s The Gourmet: deliver four delicacies.", command = null, source = "https://www.gamepressure.com/risen3/taranis-legendary-items/z86756", codeCategory = CodeCategory.ITEMS),
        ToolReferenceEntry("r3_legendary_target", "LEGENDARY • TACARIGUA", "Target", "Permanent bonus: Shotguns +10\n\nGovernor’s rooftop, Puerto Sacarico. Climb the wall’s vine or use Parrot Flight.", command = null, source = "https://www.gamepressure.com/risen3/tacarigua-legendary-items/z96793", codeCategory = CodeCategory.ITEMS),
        ToolReferenceEntry("r3_legendary_plan_of_holm_the_great", "LEGENDARY • TACARIGUA", "Plan of Holm the Great", "Permanent bonus: Cunning +5\n\nGovernor’s first-floor chest. Sneak in at night, away from Sebastiano.", command = null, source = "https://www.gamepressure.com/risen3/tacarigua-legendary-items/z96793", codeCategory = CodeCategory.ITEMS),
        ToolReferenceEntry("r3_legendary_vial", "LEGENDARY • TACARIGUA", "Vial", "Permanent bonus: Magic +5\n\nThe Nameless Captain’s Treasure: buried chest near the central beach; shovel required.", command = null, source = "https://www.gamepressure.com/risen3/tacarigua-legendary-items/z96793", codeCategory = CodeCategory.ITEMS),
    )

    private fun part1(): List<ToolReferenceEntry> = listOf(
        ToolReferenceEntry("r3_legendary_finger_bone", "LEGENDARY • ANTIGUA", "Finger Bone", "Permanent bonus: Dexterity +5\n\nUpstairs shelf in Alvarez’s building; sneak into the restricted room.", command = null, source = "https://www.gamepressure.com/risen3/antigua-legendary-items/z567ce", codeCategory = CodeCategory.ITEMS),
        ToolReferenceEntry("r3_legendary_glass_sword", "LEGENDARY • ANTIGUA", "Glass Sword", "Permanent bonus: Melee +5\n\nPort: search shallow water alongside the wooden walkways.", command = null, source = "https://www.gamepressure.com/risen3/antigua-legendary-items/z567ce", codeCategory = CodeCategory.ITEMS),
        ToolReferenceEntry("r3_legendary_damaged_cuirass", "LEGENDARY • ANTIGUA", "Damaged Cuirass", "Permanent bonus: Bladeproof +10\n\nThe Happy Pirate’s Treasure: buried chest in the northern backcountry.", command = null, source = "https://www.gamepressure.com/risen3/antigua-legendary-items/z567ce", codeCategory = CodeCategory.ITEMS),
        ToolReferenceEntry("r3_legendary_hardened_crab_shell", "LEGENDARY • CRAB COAST", "Hardened Crab Shell", "Permanent bonus: Bulletproof +10\n\nEastern offshore island: climb to the hilltop camp and open its unlocked chest.", command = null, source = "https://www.gamepressure.com/risen3/crab-coast/z9668e", codeCategory = CodeCategory.ITEMS),
        ToolReferenceEntry("r3_legendary_freddies_shackles", "LEGENDARY • FOG ISLAND • DLC", "Freddie’s Shackles", "Permanent bonus: Glory +10%\n\nSouthwestern shipwrecks. Requires Fog Island DLC content; watch for traps.", command = null, source = "https://www.gamepressure.com/risen3/fog-island-legendary-items/z366f1", codeCategory = CodeCategory.ITEMS),
        ToolReferenceEntry("r3_potion_swordthorn_essence", "PERMANENT POTIONS", "Swordthorn Essence", "Melee +5 permanently.\n\nIngredients: 1 Swordthorn + 2 Potion of Blades.\n\nRequires Brew Potions, the recipe and a potion workstation.", command = null, source = "https://steamcommunity.com/sharedfiles/filedetails/?id=723232144 | https://www.abcgames.net/?cast=3&id=16001&p=navody_zobraz", codeCategory = CodeCategory.ITEMS),
        ToolReferenceEntry("r3_plant_swordthorn", "RARE PLANTS", "Swordthorn", "Melee +2 if consumed. Keep for Swordthorn Essence to obtain +5 instead.", command = null, source = "https://www.abcgames.net/?cast=3&id=16001&p=navody_zobraz", codeCategory = CodeCategory.ITEMS),
        ToolReferenceEntry("r3_potion_tincture_of_toughness", "PERMANENT POTIONS", "Tincture of Toughness", "Toughness +5 permanently.\n\nIngredients: 1 Hero’s Crown + 2 Defence Potion.\n\nRequires Brew Potions, the recipe and a potion workstation.", command = null, source = "https://steamcommunity.com/sharedfiles/filedetails/?id=723232144 | https://www.abcgames.net/?cast=3&id=16001&p=navody_zobraz", codeCategory = CodeCategory.ITEMS),
        ToolReferenceEntry("r3_plant_heros_crown", "RARE PLANTS", "Hero’s Crown", "Toughness +2 if consumed. Keep for Tincture of Toughness to obtain +5 instead.", command = null, source = "https://www.abcgames.net/?cast=3&id=16001&p=navody_zobraz", codeCategory = CodeCategory.ITEMS),
        ToolReferenceEntry("r3_potion_essence_of_persuasion", "PERMANENT POTIONS", "Essence of Persuasion", "Influence +5 permanently.\n\nIngredients: 1 Tree Strangler + 1 Potion of Persuasion + 1 Potion of Awe.\n\nRequires Brew Potions, the recipe and a potion workstation.", command = null, source = "https://steamcommunity.com/sharedfiles/filedetails/?id=723232144 | https://www.abcgames.net/?cast=3&id=16001&p=navody_zobraz", codeCategory = CodeCategory.ITEMS),
        ToolReferenceEntry("r3_plant_tree_strangler", "RARE PLANTS", "Tree Strangler", "Influence +2 if consumed. Keep for Essence of Persuasion to obtain +5 instead.", command = null, source = "https://www.abcgames.net/?cast=3&id=16001&p=navody_zobraz", codeCategory = CodeCategory.ITEMS),
        ToolReferenceEntry("r3_potion_soul_potion", "PERMANENT POTIONS", "Soul Potion", "Magic +5 permanently.\n\nIngredients: 1 Soul Lichen + 1 Potion of Magic + 1 Ritual Potion.\n\nRequires Brew Potions, the recipe and a potion workstation.", command = null, source = "https://steamcommunity.com/sharedfiles/filedetails/?id=723232144 | https://www.abcgames.net/?cast=3&id=16001&p=navody_zobraz", codeCategory = CodeCategory.ITEMS),
        ToolReferenceEntry("r3_plant_soul_lichen", "RARE PLANTS", "Soul Lichen", "Magic +2 if consumed. Keep for Soul Potion to obtain +5 instead.", command = null, source = "https://www.abcgames.net/?cast=3&id=16001&p=navody_zobraz", codeCategory = CodeCategory.ITEMS),
        ToolReferenceEntry("r3_potion_potion_of_the_eternal_hunter", "PERMANENT POTIONS", "Potion of the Eternal Hunter", "Ranged +5 permanently.\n\nIngredients: 1 Hunter’s Root + 2 Sharp Eye.\n\nRequires Brew Potions, the recipe and a potion workstation.", command = null, source = "https://steamcommunity.com/sharedfiles/filedetails/?id=723232144 | https://www.abcgames.net/?cast=3&id=16001&p=navody_zobraz", codeCategory = CodeCategory.ITEMS),
        ToolReferenceEntry("r3_plant_hunters_root", "RARE PLANTS", "Hunter’s Root", "Ranged +2 if consumed. Keep for Potion of the Eternal Hunter to obtain +5 instead.", command = null, source = "https://www.abcgames.net/?cast=3&id=16001&p=navody_zobraz", codeCategory = CodeCategory.ITEMS),
        ToolReferenceEntry("r3_potion_shadow_elixir", "PERMANENT POTIONS", "Shadow Elixir", "Cunning +5 permanently.\n\nIngredients: 1 Shadow Fire + 1 Potion of Blades + 1 Marksman’s Potion.\n\nRequires Brew Potions, the recipe and a potion workstation.", command = null, source = "https://steamcommunity.com/sharedfiles/filedetails/?id=723232144 | https://www.abcgames.net/?cast=3&id=16001&p=navody_zobraz", codeCategory = CodeCategory.ITEMS),
        ToolReferenceEntry("r3_plant_shadow_fire", "RARE PLANTS", "Shadow Fire", "Cunning +2 if consumed. Keep for Shadow Elixir to obtain +5 instead.", command = null, source = "https://www.abcgames.net/?cast=3&id=16001&p=navody_zobraz", codeCategory = CodeCategory.ITEMS),
        ToolReferenceEntry("r3_potion_potion_of_dexterity", "PERMANENT POTIONS", "Potion of Dexterity", "Dexterity +5 permanently.\n\nIngredients: 1 Thief’s Herb + 1 Thief’s Potion.\n\nRequires Brew Potions, the recipe and a potion workstation.", command = null, source = "https://steamcommunity.com/sharedfiles/filedetails/?id=723232144 | https://www.abcgames.net/?cast=3&id=16001&p=navody_zobraz", codeCategory = CodeCategory.ITEMS),
        ToolReferenceEntry("r3_plant_thiefs_herb", "RARE PLANTS", "Thief’s Herb", "Dexterity +2 if consumed. Keep for Potion of Dexterity to obtain +5 instead.", command = null, source = "https://www.abcgames.net/?cast=3&id=16001&p=navody_zobraz", codeCategory = CodeCategory.ITEMS),
        ToolReferenceEntry("r3_potion_spirit_paste", "PERMANENT POTIONS", "Spirit Paste", "Spirit +5 permanently.\n\nIngredients: 1 Bloodcap + 1 Potion of Will + 1 Potion of Magic.\n\nRequires Brew Potions, the recipe and a potion workstation.", command = null, source = "https://steamcommunity.com/sharedfiles/filedetails/?id=723232144 | https://www.abcgames.net/?cast=3&id=16001&p=navody_zobraz", codeCategory = CodeCategory.ITEMS),
        ToolReferenceEntry("r3_plant_bloodcap", "RARE PLANTS", "Bloodcap", "Spirit +2 if consumed. Keep for Spirit Paste to obtain +5 instead.", command = null, source = "https://www.abcgames.net/?cast=3&id=16001&p=navody_zobraz", codeCategory = CodeCategory.ITEMS),
        ToolReferenceEntry("r3_weapon_caladors_coronation_sword", "WEAPON PARTS • SWORDS", "Calador’s Coronation Sword", "Swords damage: 45–90.\n\nBlade: western Calador castle ruins near the Shadow Lord of Cowardice. Chapter 3 hilt: eastern ruins across the lava river; use Parrot Flight to reach the upper altar.\n\nWith both parts and Blacksmith training, combine them at an anvil.", command = null, source = "https://www.gamepressure.com/risen3/re-forge-caladors-coronation-sword/zf6810 | https://www.gamepressure.com/risen3/introduction/z4680f", codeCategory = CodeCategory.WEAPONS),
        ToolReferenceEntry("r3_weapon_sphere_torn", "WEAPON PARTS • PIERCING WEAPONS", "Sphere Torn", "Piercing Weapons damage: 55–90.\n\nChapter 3: blade across Calador’s lava river, far north. Hilt: northern Puerto Sacarico building on Tacarigua; Monkey Trainer required.\n\nWith both parts and Blacksmith training, combine them at an anvil.", command = null, source = "https://www.gamepressure.com/risen3/re-forge-sphere-torn/z16812 | https://www.gamepressure.com/risen3/introduction/z4680f", codeCategory = CodeCategory.WEAPONS),
        ToolReferenceEntry("r3_weapon_kraken_eye", "WEAPON PARTS • SLASHING WEAPONS", "Kraken Eye", "Slashing Weapons damage: 45–110.\n\nChapter 3: blade in Kila’s Forbidden Valley water. Hilt in Taranis’s crystal-portal cave: take the left fork and use Parrot Flight across the gap.\n\nWith both parts and Blacksmith training, combine them at an anvil.", command = null, source = "https://www.gamepressure.com/risen3/re-forge-kraken-eye/z36814 | https://www.gamepressure.com/risen3/introduction/z4680f", codeCategory = CodeCategory.WEAPONS),
        ToolReferenceEntry("r3_weapon_maras_fame", "WEAPON PARTS • SWORDS", "Mara’s Fame", "Swords damage: 30–60.\n\nBlade: water by Shax’s southern Taranis swamp and monolith. Hilt: palm tree at the northeastern Taranis beach’s end.\n\nWith both parts and Blacksmith training, combine them at an anvil.", command = null, source = "https://www.gamepressure.com/risen3/re-forge-maras-fame/z06811 | https://www.gamepressure.com/risen3/introduction/z4680f", codeCategory = CodeCategory.WEAPONS),
    )

    private fun part2(): List<ToolReferenceEntry> = listOf(
        ToolReferenceEntry("r3_weapon_wound_tearer", "WEAPON PARTS • PIERCING WEAPONS", "Wound Tearer", "Piercing Weapons damage: 30–40.\n\nFragile Past Sins: Flynn on Antigua has the blade; Quinn on Kila has the hilt.\n\nWith both parts and Blacksmith training, combine them at an anvil.", command = null, source = "https://www.gamepressure.com/risen3/re-forge-wound-tearer/z26813 | https://www.gamepressure.com/risen3/introduction/z4680f", codeCategory = CodeCategory.WEAPONS),
        ToolReferenceEntry("r3_armor_guardians_armor", "FACTION ARMOR", "Guardian’s Armor", "Guardians only. Complete Advancing Among the Guardians; Magnus sends you to Gordon in Taranis’s mages’ camp to collect the armor.", command = null, source = "https://www.gamepressure.com/risen3/a-guardians-armor/z667d5", codeCategory = CodeCategory.ARMOR),
        ToolReferenceEntry("r3_armor_demon_hunters_armor", "FACTION ARMOR", "Demon Hunter’s Armor", "Demon Hunters only. Complete A New Rank; Drake sends you to Wilson in Calador’s citadel for the armor.", command = null, source = "https://www.gamepressure.com/risen3/new-armour/z667ed", codeCategory = CodeCategory.ARMOR),
    )
}
