package com.sliverzfx.gothicquest

internal object RisenGuidePart3Data {
    val quests: List<Quest> = listOf(
        Quest(
            id = "R1-C1-029",
            chapter = 1,
            playOrder = 29,
            title = "In Harbour Town",
            category = "SAFE",
            giver = "Automatic on entering Harbour Town",
            location = "Harbour Town gate",
            prerequisites = "Reach Harbour Town by the permitted eastern entrance; ordinary travelers may have to pay the gate guard.",
            summary = "Enter Harbour Town and receive the arrival quest completion.",
            walkthroughSteps = listOf("Reach the eastern city gate without being forcibly conscripted into the Order along the road.", "Pay the entrance fee or use an eligible entrance arrangement and pass into town.", "The arrival quest completes when you enter; you can then pursue the city's faction cases."),
            reward = "100 XP",
            warnings = "⚠ Important: Entering the city is safe; resolving four of its seven faction cases for one side is the real commitment mechanism.",
            searchTags = listOf("Get into Harbour Town", "Guards / city-entry route", "Harbour Town gate", "SAFE", "—", "1. GETTING INSIDE"),
        ),
        Quest(
            id = "R1-C1-030",
            chapter = 1,
            playOrder = 30,
            title = "Leaving Harbour Town — access guide",
            category = "GUIDE — ROUTE REFERENCE (NOT VERIFIED JOURNAL QUEST)",
            giver = "Not a distinct quest giver",
            location = "Harbour Town",
            prerequisites = "Enter Harbour Town. Leaving routes become available after faction and gate progression.",
            summary = "Reference guide: arrange permission or obtain the sewer access key before attempting to leave the town freely.",
            walkthroughSteps = listOf("Start. After entering, ask citizens and guards about leaving the sealed town.", "Walkthrough. Talk to people near the gates and faction representatives. The purpose is to understand the city's lockdown and establish your future exit route without yet choosing who controls the town.", "Completion. The objective updates/completes when the required route or permission is established."),
            reward = "No separate journal-quest reward verified",
            warnings = "This is a route reference, not independently confirmed as a separate in-game journal quest. Do not count it as completionist quest progress.",
            searchTags = listOf("Find a way out of Harbour Town", "City inhabitants / gate situation", "Harbour Town", "SAFE / TRAVEL", "—", "2. NEUTRAL CITY QUESTS — DO THESE EARLY"),
        ),
        Quest(
            id = "R1-C1-031",
            chapter = 1,
            playOrder = 31,
            title = "Medicine for everyone",
            category = "SAFE / DELIVERY",
            giver = "Master Belschwur",
            location = "Harbour Town — the Gutters",
            prerequisites = "Speak to Master Belschwur in the Gutters and offer to help sick townspeople.",
            summary = "Deliver Belschwur's five medicine portions to Elias, Cole, Finn, Josh and Martha via Arno, then report back.",
            walkthroughSteps = listOf("Speak to Belschwur in the Gutters to obtain medicine and the names of people who need it.", "Deliver the potions to Elias, Cole, Finn, Josh and Arno (for Martha); each completed delivery contributes its own experience.", "Return to Belschwur once all five are helped."),
            reward = "100 XP for completion plus 50 XP for each of five deliveries",
            warnings = "",
            searchTags = listOf("Medicine for everyone", "Leonardo", "Harbour Town", "SAFE / DELIVERY", "Harbour Town civilian quests", "2. NEUTRAL CITY QUESTS — DO THESE EARLY"),
        ),
        Quest(
            id = "R1-C1-032",
            chapter = 1,
            playOrder = 32,
            title = "Skins for meat",
            category = "SAFE / COLLECTION",
            giver = "Flavio",
            location = "Harbour Town — the Gutters / Flavio's warehouse",
            prerequisites = "Speak to Flavio about work and accept the trade involving wolf and boar skins.",
            summary = "Collect five wolf skins and five boar skins, arrange the trade through Baxter, and report to Flavio.",
            walkthroughSteps = listOf("Speak to Flavio to accept the request for five wolf skins and five boar skins.", "Find the skins around town or gather them from beasts. Several can be obtained from houses and nearby stores without needing the skinning skill.", "Give the required skins to Baxter as directed, then report back to Flavio. Follow up with Belschwur if you are also arranging shelter for the sick farmer's wife."),
            reward = "200 XP plus 50 XP and two healing potions from Flavio",
            warnings = "⚠ Important: If skinning requires a learned hunting skill in your version/build, obtain it before selling creature corpses/loot opportunities.",
            searchTags = listOf("Skins for Costa", "Costa", "Harbour Town", "SAFE / COLLECTION", "—", "2. NEUTRAL CITY QUESTS — DO THESE EARLY"),
        ),
        Quest(
            id = "R1-C1-033",
            chapter = 1,
            playOrder = 33,
            title = "The sons of Tilda",
            category = "SAFE / CROSS-REGION",
            giver = "Tilda",
            location = "Harbour Town",
            prerequisites = "Ask Tilda near Konrad's store about her three missing sons.",
            summary = "Speak to Beppo in Bandit Camp, Leon at the northern farm and William at Volcano Keep, then report back to Tilda.",
            walkthroughSteps = listOf("Find Tilda near Konrad's shop in Harbour Town and ask her about her family.", "Meet Beppo at the Bandit Camp, Leon on his farm north of Harbour Town, and William at the Volcano Keep. Ask each about Tilda.", "Return to Tilda with news of all three sons; she also has information about a buried farm chest."),
            reward = "150 XP for each of Beppo, Leon and William; 300 XP on reporting to Tilda",
            warnings = "",
            searchTags = listOf("The sons of Tilda", "Tilda", "Harbour Town", "SAFE / CROSS-REGION", "Later island exploration", "2. NEUTRAL CITY QUESTS — DO THESE EARLY"),
        ),
        Quest(
            id = "R1-C1-034",
            chapter = 1,
            playOrder = 34,
            title = "Find the burglar's spy",
            category = "SAFE / INVESTIGATION",
            giver = "Rodriguez",
            location = "Harbour Town — slaughterhouse and the Gutters",
            prerequisites = "Speak to Rodriguez near the slaughterhouse about the recent burglaries.",
            summary = "Question the burglary victims and suspects until Doyle is identified as the spy.",
            walkthroughSteps = listOf("Ask Rodriguez about the recent break-ins and agree to investigate.", "Interview Baxter, Nelson and Flavio. Compare their accounts and question Mo, Pavel, Vasili and Doyle.", "Confront Doyle upstairs at Costa's hotel, obtain his confession, and decide whether to report his connection to Cid to Rodriguez or help the Bandits."),
            reward = "200 XP",
            warnings = "This investigation links to the Cid/Rodriguez faction decision. Your final report affects which side gains influence in Harbour Town.",
            searchTags = listOf("Find the burglar", "Harbour Town investigation NPC", "Harbour Town", "SAFE / INVESTIGATION", "—", "2. NEUTRAL CITY QUESTS — DO THESE EARLY"),
        ),
        Quest(
            id = "R1-C1-035",
            chapter = 1,
            playOrder = 35,
            title = "The family heirloom",
            category = "CHOICE — CASE 1 OF 7",
            giver = "Toni / Hernandez",
            location = "Don's house / Harbour Town",
            prerequisites = "Start. Speak with Toni about recovering the Don's property and with Hernandez, the Order man guarding/searching the house.",
            summary = "Locate the Don's valuable heirloom in his old house, then decide whether Toni or Hernandez receives the result.",
            walkthroughSteps = listOf("Start. Speak with Toni about recovering the Don's property and with Hernandez, the Order man guarding/searching the house.", "Walkthrough. Investigate the house carefully and locate the quest object. Do not immediately hand it over. Save, then choose which side gets the successful resolution.", "Completion. The recipient you support records one Harbour Town victory for that faction.", "Faction outcome", "DON / BANDIT: Help Toni/the Don's network recover the heirloom.", "ORDER: Turn the matter over to Hernandez/the Order."),
            reward = "Bandit route: 150 XP and 150 gold from Toni; alternative Hernandez/Order hand-in awards different rewards",
            warnings = "Toni and Hernandez want the same amulet. Turning it in to one side blocks the competing route.",
            searchTags = listOf("The family heirloom", "Toni / Hernandez", "Don's house / Harbour Town", "CHOICE — CASE 1 OF 7", "—", "3. THE SEVEN HARBOUR TOWN DECISION CASES"),
        ),
        Quest(
            id = "R1-C1-036",
            chapter = 1,
            playOrder = 36,
            title = "Find the three golden bowls",
            category = "CHOICE — CASE 2 OF 7",
            giver = "Carasco / Scordo",
            location = "Harbour Town",
            prerequisites = "Speak to Carasco at the Harbour Town warehouse, or pursue Scordo's competing Bandit collection objective.",
            summary = "Recover the three golden bowls from the treasure-hunter brothers and lighthouse; hand them to the chosen faction.",
            walkthroughSteps = listOf("Speak with Carasco at the warehouse about the missing golden bowls. You can also investigate the competing Bandit interest in them.", "Acquire the bowls from Dytar and Dirk by payment or theft; learn from Olf that the third is up on a beam in the lighthouse.", "Return the three bowls to the chosen faction representative. The final hand-in advances the associated Harbour Town faction quest."),
            reward = "100 XP for finding the bowls; faction hand-in bonuses vary",
            warnings = "The Carasco and Scordo hand-ins support opposing factions. Avoid presenting both choices as simultaneously completable.",
            searchTags = listOf("The three golden bowls", "Scordo / Order-side investigation", "Harbour Town", "CHOICE — CASE 2 OF 7", "Scordo / Don's network", "3. THE SEVEN HARBOUR TOWN DECISION CASES"),
        ),
        Quest(
            id = "R1-C1-037",
            chapter = 1,
            playOrder = 37,
            title = "The drug dealer",
            category = "GUIDE — FACTION ROUTE OVERVIEW",
            giver = "Weasel / Marcelo",
            location = "Harbour Town",
            prerequisites = "Start. Speak with both the Bandit-side dealer/contact and the Order-side investigator before acting.",
            summary = "Investigate the weed/brugleweed trade and decide whether to protect the Don's operation or help the Order shut it down.",
            walkthroughSteps = listOf("Start. Speak with both the Bandit-side dealer/contact and the Order-side investigator before acting.", "Walkthrough. Follow the suspects, question the involved citizens and obtain the incriminating goods/information. Keep the evidence until you have heard both faction solutions.", "Completion. Hand the evidence/result to the faction you want to credit with the case.", "Faction outcome", "DON / BANDIT: Protect/assist the Don's smuggling network and resolve the problem for Weasel's side.", "ORDER: Expose the operation to Marcelo/the Order."),
            reward = "Faction-dependent Weasel / Marcelo rewards; exact payout for this combined reference not independently verified",
            warnings = "Reference-only overview. The separate Bandit and Order journal objectives appear later in this chapter. Do not mark this overview as an extra completed quest.",
            searchTags = listOf("The drug dealer", "Weasel / Marcelo", "Harbour Town", "CHOICE — CASE 3 OF 7", "—", "3. THE SEVEN HARBOUR TOWN DECISION CASES"),
        ),
        Quest(
            id = "R1-C1-038",
            chapter = 1,
            playOrder = 38,
            title = "Protection money",
            category = "GUIDE — FACTION ROUTE OVERVIEW",
            giver = "Delgado / Sebastian",
            location = "Harbour Town",
            prerequisites = "Start. Speak with Delgado and the affected merchants/citizens; also locate the Order counterpart.",
            summary = "Investigate the Don's protection-money collection and decide whether Delgado's operation continues or the Order receives the case.",
            walkthroughSteps = listOf("Start. Speak with Delgado and the affected merchants/citizens; also locate the Order counterpart.", "Walkthrough. Collect information and money only after hearing what each person says. Before the final turn-in, check your current city score.", "Completion. Resolve the collection for Delgado or turn the scheme/evidence over to the Order.", "Faction outcome", "DON / BANDIT: Complete the protection-money business for Delgado/the Don.", "ORDER: Break the racket and support the Order's representative."),
            reward = "Delgado/Bandit route: 100 XP and 150 gold; Sebastian/Order route: different reward for exposing Delgado",
            warnings = "Reference-only overview. The separate Bandit and Order journal objectives appear later in this chapter. Do not mark this overview as an extra completed quest.",
            searchTags = listOf("Protection money", "Delgado / Sebastian", "Harbour Town", "CHOICE — CASE 4 OF 7", "—", "3. THE SEVEN HARBOUR TOWN DECISION CASES"),
        ),
        Quest(
            id = "R1-C1-039",
            chapter = 1,
            playOrder = 39,
            title = "Fleecing the butcher",
            category = "BANDIT-SIDE / Cid chain",
            giver = "Cid",
            location = "Harbour Town",
            prerequisites = "Speak to Cid and investigate his protection racket at the slaughterhouse.",
            summary = "Confront the butcher's defender Dargel over Cid's protection-money demand.",
            walkthroughSteps = listOf("Speak to Cid about collecting money from the slaughterhouse.", "Go to the butcher and question Dargel about the demand. Be prepared to fight Dargel if the dispute escalates.", "Return to Cid to discuss the outcome. Some walkthroughs document this quest as canceling or becoming impossible to finish instead of reliably awarding completion."),
            reward = "No reliable completion payout documented (quest may cancel)",
            warnings = "Classic walkthroughs report that this specific Cid side quest may cancel rather than complete. Treat it as conditional rather than a guaranteed completed journal quest.",
            searchTags = listOf("The butcher's meat / meat dispute", "Doyle-side network / Order contact", "Harbour Town", "CHOICE — CASE 5 OF 7", "—", "3. THE SEVEN HARBOUR TOWN DECISION CASES"),
        ),
        Quest(
            id = "R1-C1-040",
            chapter = 1,
            playOrder = 40,
            title = "Romanov's seaman's chest",
            category = "CHOICE / CROSS-REGION",
            giver = "Romanov",
            location = "Harbour Town docks / upper warehouse",
            prerequisites = "Obtain access to Captain Romanov's cell by bribery, theft or assisting the prison guard, then speak with Romanov.",
            summary = "Retrieve Romanov's locked chest from the warehouse loft and decide whether to deliver it to Romanov or Sergio.",
            walkthroughSteps = listOf("Speak to Romanov in the Harbour Town prison and accept his request for his chest; get the key from him.", "Sneak into the upstairs warehouse or reach the loft via the roof near Durham's room. Find and open Romanov's chest.", "Deliver it to Romanov for the Bandit-aligned completion, or to Sergio for the competing Order-aligned solution."),
            reward = "Romanov route: 250 XP and 300 gold; Sergio's competing task: 200 XP and 100 gold",
            warnings = "This chest is part of the Romanov / Sergio faction decision. The two hand-ins are mutually exclusive.",
            searchTags = listOf("Romanov's seaman / Patty's search chain", "Patty / city contacts", "Harbour Town docks", "CHOICE / CROSS-REGION", "—", "3. THE SEVEN HARBOUR TOWN DECISION CASES"),
        ),
        Quest(
            id = "R1-C1-041",
            chapter = 1,
            playOrder = 41,
            title = "Peace and order",
            category = "ORDER — FACTION DECISION TRACKER",
            giver = "Carlos",
            location = "Commandant's building",
            prerequisites = "Meet Commandant Carlos and agree to support the Order's investigation of the Don's agents.",
            summary = "Resolve four of the contested Harbour Town cases for the Order and report to Carlos.",
            walkthroughSteps = listOf("Start. Meet Carlos after exploring the city and ask about the Order's objectives.", "Walkthrough. Carlos represents the Order's side of the Harbour Town struggle. Finish investigations first; when you resolve a contested case for him or his men, it contributes toward Order control.", "Completion. At the required number of successful cases, the Order-side city outcome advances.", "Faction outcome", "ORDER: Four successful decisions for the Order secure their Harbour Town outcome."),
            reward = "1,000 XP for the faction hub; additional case rewards vary",
            warnings = "The four Order-aligned decisions are mutually exclusive with the corresponding Bandit-aligned hand-ins; choose deliberately before committing.",
            searchTags = listOf("The commandant wants peace and order", "Carlos", "Commandant's building", "ORDER HUB / DECISION TRACKER", "—", "3. THE SEVEN HARBOUR TOWN DECISION CASES"),
        ),
        Quest(
            id = "R1-C1-042",
            chapter = 1,
            playOrder = 42,
            title = "All power to the Don",
            category = "BANDIT HUB / DECISION TRACKER",
            giver = "Scordo",
            location = "Harbour Town",
            prerequisites = "Meet Scordo in his secret storeroom and commit to helping the Bandits regain Harbour Town.",
            summary = "Complete the required Don-aligned Harbour Town decision quests and return to Scordo.",
            walkthroughSteps = listOf("Start. Locate the Don's underground network, including Scordo and the individual agents handling city business.", "Walkthrough. For each contested case, choose the Don-side hand-in. Keep a manual count rather than relying on memory.", "Completion. Four successful decisions for the Don advance the Bandit-side Harbour Town outcome.", "Faction outcome", "DON / BANDIT: Four victories secure the Don's side of the city struggle."),
            reward = "500 XP",
            warnings = "Scordo's overarching quest calls for five Don-aligned missions in the classic guide; it is not limited to the four required Order choices.",
            searchTags = listOf("The Don's men need control of Harbour Town", "Scordo / Don's agents", "Harbour Town", "BANDIT HUB / DECISION TRACKER", "—", "3. THE SEVEN HARBOUR TOWN DECISION CASES"),
        ),
        Quest(
            id = "R1-C1-043",
            chapter = 1,
            playOrder = 43,
            title = "Find the secret access to Harbour Town",
            category = "SAFE UNTIL HAND-IN",
            giver = "Scordo",
            location = "Harbour Town",
            prerequisites = "Obtain Scordo's sewer key through the Bandit route or his defeat during the Order investigation.",
            summary = "Open the hidden sewer door that provides a route into and out of Harbour Town.",
            walkthroughSteps = listOf("Reach Scordo in the hidden storeroom behind the brothel painting.", "Obtain his key by the appropriate faction route and enter the tunnel beyond the storeroom.", "Unlock the sewer door to establish the secret access route and complete this specific access objective."),
            reward = "400 XP",
            warnings = "⚠ Important: Accessing the Don's network is not itself the same as giving him four victories.",
            searchTags = listOf("Find the secret entrance", "Don's agents / Scordo chain", "Harbour Town", "SAFE UNTIL HAND-IN", "—", "4. SCORDO & THE SECRET NETWORK"),
        ),
        Quest(
            id = "R1-C1-044",
            chapter = 1,
            playOrder = 44,
            title = "Talk to the Bandit chief of Harbour Town",
            category = "SAFE / HUB",
            giver = "Scordo",
            location = "Secret Bandit base",
            prerequisites = "Locate the brothel's concealed passage by interacting with the painting in the side room.",
            summary = "Meet Scordo and discuss the Don's seven-city-case struggle.",
            walkthroughSteps = listOf("Enter the Harbour Town brothel and enter the room off the main hall.", "Interact with the painting to reveal the entrance behind the bookcase.", "Follow the corridor and talk to Scordo to complete this introduction quest."),
            reward = "100 XP",
            warnings = "",
            searchTags = listOf("Talk to the bandit chief in Harbour Town", "Scordo", "Secret Bandit base", "SAFE / HUB", "Don-side decision tracker", "4. SCORDO & THE SECRET NETWORK"),
        ),
    )

    val notes: List<RisenGuideNote> = listOf(
        RisenGuideNote(1, 29, "Harbour Town is Chapter 1's decisive hub", listOf("Harbour Town contains seven major faction-decision cases. In each case you can generally resolve the problem in favour of Don Esteban's people or Commandant Carlos and the Order. Once four of the seven cases are decided for one side, that faction effectively wins the city power struggle and your progression changes. Therefore: investigate first, finish neutral quests, and delay the fourth decisive result until you intentionally want a side to win.", "Completionist save point: Make a permanent manual save while the score is still 3–3 or earlier and before resolving your fourth case for either faction.")),
        RisenGuideNote(1, 29, "1. GETTING INSIDE", listOf()),
        RisenGuideNote(1, 30, "2. NEUTRAL CITY QUESTS — DO THESE EARLY", listOf()),
        RisenGuideNote(1, 35, "3. THE SEVEN HARBOUR TOWN DECISION CASES", listOf("The following section is the heart of Harbour Town. Treat every case as a two-sided investigation. Speak to both the Don's representative and the Order-side NPC before handing over evidence, contraband or prisoners.")),
        RisenGuideNote(1, 43, "4. SCORDO & THE SECRET NETWORK", listOf()),
        RisenGuideNote(1, 45, "5. RECOMMENDED COMPLETIONIST DECISION METHOD", listOf("This section is guide advice, not a journal quest.", "1. Enter Harbour Town and activate every neutral quest you encounter.", "2. Find Carlos and Scordo so both faction perspectives are available.", "3. For each contested case, investigate both solutions before handing anything in.", "4. Resolve no more than three cases for your preferred side at first.", "5. Finish civilian, Patty, trader and investigation quests that do not determine the city struggle.", "6. Create a permanent save.", "7. Resolve the fourth counted case for the faction you actually want.", "8. Finish the remaining compatible city quests and report to the winning faction's leader.")),
        RisenGuideNote(1, 45, "6. WHICH FACTION SHOULD THE GUIDE PRESERVE?", listOf("For a completionist guide, there is no universal 'correct' winner. Supporting the Don leads naturally toward the Bandit path. Supporting the Order is the route toward the Order/Monastery progression and is also relevant if the player ultimately wants to become a Mage. The app should therefore never label one result as the best choice; it should show the exact consequences and let the player decide.")),
        RisenGuideNote(1, 45, "PART III EXIT CHECKLIST", listOf("Every accessible neutral Harbour Town quest has been activated/completed.", "Carlos and Scordo have both been met.", "Both sides of each contested case were investigated before the final hand-in.", "The player knows the current Don-vs-Order score.", "A permanent save exists before the fourth victory.", "Patty's Chapter 1 dialogue/investigation has been advanced.", "Unique bowls, heirlooms, packages, evidence and pirate documents were not sold.", "The desired faction has intentionally received its fourth victory.", "Harbour Town's outcome is now ready to feed into the final Chapter 1 faction/joining section.")),
    )
}
