package com.sliverzfx.gothicquest

internal object Risen2TipsData {
    val entries: List<ToolReferenceEntry> = listOf(part0()).flatten()

    private fun part0(): List<ToolReferenceEntry> = listOf(
        ToolReferenceEntry("r2_tip_glory", "CHARACTER BUILDING", "Spend Glory deliberately", "Earn Glory from quests and enemies. Higher attribute levels cost more.", command = null, source = "https://cdn.akamai.steamstatic.com/steam/apps/40390/manuals/Risen2_PC_Manual_EN_ESRB.pdf", codeCategory = null),
        ToolReferenceEntry("r2_tip_attributes", "CHARACTER BUILDING", "Choose your combat emphasis", "Blades, Firearms, Toughness, Cunning and Voodoo improve their associated talents.", command = null, source = "https://cdn.akamai.steamstatic.com/steam/apps/40390/manuals/Risen2_PC_Manual_EN_ESRB.pdf", codeCategory = null),
        ToolReferenceEntry("r2_tip_teachers", "CHARACTER BUILDING", "Budget for training", "Skills require a teacher, sufficient attributes and gold. Attribute increases alone do not unlock every skill.", command = null, source = "https://cdn.akamai.steamstatic.com/steam/apps/40390/manuals/Risen2_PC_Manual_EN_ESRB.pdf", codeCategory = null),
        ToolReferenceEntry("r2_tip_factions", "FACTIONS", "Plan before committing", "Firearms and voodoo paths offer different training. Console skills do not replace faction permission.", command = null, source = "https://gamefaqs.gamespot.com/boards/622499-risen-2-dark-waters/62714857", codeCategory = null),
        ToolReferenceEntry("r2_tip_provisions", "RECOVERY", "Keep provisions ready", "Provisions restore Blood over time; liquor provides different recovery options.", command = null, source = "https://cdn.akamai.steamstatic.com/steam/apps/40390/manuals/Risen2_PC_Manual_EN_ESRB.pdf", codeCategory = null),
        ToolReferenceEntry("r2_tip_voodoo", "VOODOO", "Use an altar", "Voodoo crafting needs its recipe, ingredients and an altar.", command = null, source = "https://cdn.akamai.steamstatic.com/steam/apps/40390/manuals/Risen2_PC_Manual_EN_ESRB.pdf", codeCategory = null),
        ToolReferenceEntry("r2_tip_dolls", "VOODOO", "Dolls and possession", "Specific voodoo dolls let you control the corresponding NPC. Follow the quest’s intended sequence.", command = null, source = "https://cdn.akamai.steamstatic.com/steam/apps/40390/manuals/Risen2_PC_Manual_EN_ESRB.pdf", codeCategory = null),
        ToolReferenceEntry("r2_tip_gunsmith", "CRAFTING", "Learn gunsmithing", "Firearms 6 opens gunsmith training. Craft with a schematic, parts and workbench.", command = null, source = "https://cdn.akamai.steamstatic.com/steam/apps/40390/manuals/Risen2_PC_Manual_EN_ESRB.pdf", codeCategory = null),
        ToolReferenceEntry("r2_tip_distill", "CRAFTING", "Distill liquor", "Train distilling, then use a pot still with the recipe and ingredients.", command = null, source = "https://cdn.akamai.steamstatic.com/steam/apps/40390/manuals/Risen2_PC_Manual_EN_ESRB.pdf", codeCategory = null),
        ToolReferenceEntry("r2_tip_locks", "THIEVERY", "Bring a lockpick", "Learn lockpicking and carry a pick. Key-only locks still need their key.", command = null, source = "https://cdn.akamai.steamstatic.com/steam/apps/40390/manuals/Risen2_PC_Manual_EN_ESRB.pdf", codeCategory = null),
        ToolReferenceEntry("r2_tip_pockets", "THIEVERY", "Pickpocket through dialogue", "The skill opens dialogue opportunities. Select your target item within the time limit.", command = null, source = "https://cdn.akamai.steamstatic.com/steam/apps/40390/manuals/Risen2_PC_Manual_EN_ESRB.pdf", codeCategory = null),
        ToolReferenceEntry("r2_tip_persuasion", "DIALOGUE", "Silver Tongue helps", "Higher Silver Tongue can open persuasion options and avoid bribery or combat.", command = null, source = "https://cdn.akamai.steamstatic.com/steam/apps/40390/manuals/Risen2_PC_Manual_EN_ESRB.pdf", codeCategory = null),
        ToolReferenceEntry("r2_tip_permanent", "PLANTS", "Save rare permanent plants", "Swordthorn, Sharpeye, Hero’s Crown and Graveroot grant lasting talent bonuses; also keep them for potion crafting.", command = null, source = "https://www.risen.cz/risen-2/predmety/herbar/", codeCategory = null),
        ToolReferenceEntry("r2_tip_parts", "CRAFTING", "Keep matching weapon parts", "Legendary swords need the corresponding blade and hilt. Assemble them with smithing rather than discarding a seemingly useless part.", command = null, source = "https://www.risen.cz/risen-2/predmety/secne-zbrane/", codeCategory = null),
        ToolReferenceEntry("r2_tip_legendary", "COLLECTIBLES", "Legendary references", "Search Codes for LEGENDARY ITEMS to see their exact IDs and the available finding clues.", command = null, source = "https://www.supercheats.com/guides/risen-2-dark-waters/legendary-items-sidequests", codeCategory = null),
        ToolReferenceEntry("r2_tip_clothing", "EQUIPMENT", "Compare clothing bonuses", "Protection is not the only benefit: some clothes improve intimidation or persuasion. Compare the offline statistics on each equipment card.", command = null, source = "https://www.risen.cz/risen-2/predmety/kosile-plaste/", codeCategory = null),
        ToolReferenceEntry("r2_tip_patch", "TROUBLESHOOTING", "Match your PC version", "The item catalogue identifies PC version 1.0.1210.0, Change 201663. Mods and other patches can change item behaviour. Use Tab completion to check your installation.", command = null, source = "https://gamefaqs.gamespot.com/pc/622499-risen-2-dark-waters/faqs/77368/all-item-console-commands", codeCategory = null),
        ToolReferenceEntry("r2_tip_questcodes", "CONSOLE SAFETY", "Items are not quest completion", "Adding quest items or legendary weapons can skip rewards or disrupt progression. Keep a separate save; avoid bulk item requests.", command = null, source = "https://gamefaqs.gamespot.com/boards/622499-risen-2-dark-waters/62714857", codeCategory = null),
    )
}
