package com.sliverzfx.gothicquest

internal object Risen2GuidePart5Data {
    val quests: List<Quest> = listOf(
        Quest(
            id = "R2-C3-001",
            chapter = 3,
            playOrder = 1,
            title = "Find Captain Slayne",
            category = "MAIN STORY",
            giver = "Main story",
            location = "Antigua / Chapter 3",
            prerequisites = "",
            summary = "Sail to Antigua, enter Admiral Alvarez's house and speak with Captain Slayne.",
            walkthroughSteps = listOf("Walkthrough. After Chapter 2, set course for Antigua. Walk from the docks into Harbour Town and visit Admiral Alvarez's residence. Slayne is there. Speak with him and ask about the artefact connected to Steelbeard's larger treasure hunt.", "Completion. The quest completes after the conversation with Slayne.", "Related: The Cunning Captain / Follow Slayne Outside"),
            reward = "200 Glory",
            warnings = "",
            searchTags = listOf("Find Captain Slayne", "A. ARRIVE ON ANTIGUA", "Main story", "Antigua / Chapter 3"),
        ),
        Quest(
            id = "R2-C3-002",
            chapter = 3,
            playOrder = 2,
            title = "Follow Slayne Outside",
            category = "MAIN STORY — ESCORT",
            giver = "Captain Slayne",
            location = "Antigua / Chapter 3",
            prerequisites = "",
            summary = "Follow Slayne out of Alvarez's house.",
            walkthroughSteps = listOf("Walkthrough. After discussing the artefact, Slayne asks you to come with him. Stay near him as he leaves the house.", "Completion. The first escort stage completes at his scripted stop.", "Related: Follow Slayne"),
            reward = "10 Glory",
            warnings = "",
            searchTags = listOf("Follow Slayne Outside", "A. ARRIVE ON ANTIGUA", "Captain Slayne", "Antigua / Chapter 3"),
        ),
        Quest(
            id = "R2-C3-003",
            chapter = 3,
            playOrder = 3,
            title = "Follow Slayne",
            category = "MAIN STORY — ESCORT",
            giver = "Captain Slayne",
            location = "Antigua / Chapter 3",
            prerequisites = "",
            summary = "Continue following Slayne through Antigua.",
            walkthroughSteps = listOf("Walkthrough. Resume the escort and stay with him through the next section of Harbour Town.", "Completion. The second escort stage completes when he stops again.", "Related: Follow Slayne to His Ship"),
            reward = "10 Glory",
            warnings = "",
            searchTags = listOf("Follow Slayne", "A. ARRIVE ON ANTIGUA", "Captain Slayne", "Antigua / Chapter 3"),
        ),
        Quest(
            id = "R2-C3-004",
            chapter = 3,
            playOrder = 4,
            title = "Follow Slayne to His Ship",
            category = "MAIN STORY — ESCORT",
            giver = "Captain Slayne",
            location = "Antigua / Chapter 3",
            prerequisites = "",
            summary = "Follow Slayne all the way to his ship.",
            walkthroughSteps = listOf("Walkthrough. Continue the final escort stage until you reach Slayne's vessel at the docks.", "Completion. The quest completes at the ship and unlocks Ship's Equipment.", "Related: Ship's Equipment"),
            reward = "10 Glory",
            warnings = "",
            searchTags = listOf("Follow Slayne to His Ship", "A. ARRIVE ON ANTIGUA", "Captain Slayne", "Antigua / Chapter 3"),
        ),
        Quest(
            id = "R2-C3-005",
            chapter = 3,
            playOrder = 5,
            title = "Ship's Equipment",
            category = "MAIN STORY — PARENT QUEST",
            giver = "Captain Slayne",
            location = "Antigua / Chapter 3",
            prerequisites = "",
            summary = "Secure a cannon, powder kegs, water barrels, fresh fish and a helmsman, then report to Slayne.",
            walkthroughSteps = listOf("Walkthrough. Slayne refuses to sail until his ship is fully supplied. Complete The Cannon, Powder Kegs, Water Barrels, Fresh Fish and The Helmsman. These five quests can be completed in almost any order while exploring Antigua.", "Completion. Return to Slayne after all five requirements are marked complete.", "Related: The Cannon / Powder Kegs / Water Barrels / Fresh Fish / The Helmsman"),
            reward = "200 Glory",
            warnings = "⚠ Important: Before telling Slayne you are ready to depart, finish any Antigua quests you want to do with full freedom of travel.",
            searchTags = listOf("Ship's Equipment", "B. SHIP'S EQUIPMENT — MASTER QUEST", "Captain Slayne", "Antigua / Chapter 3"),
        ),
        Quest(
            id = "R2-C3-006",
            chapter = 3,
            playOrder = 6,
            title = "The Cannon",
            category = "SHIP EQUIPMENT",
            giver = "Wilson",
            location = "Antigua / Chapter 3",
            prerequisites = "",
            summary = "Help Wilson through either Pure Luxury or the pistol route, then report back to him.",
            walkthroughSteps = listOf("Walkthrough. Find blacksmith Wilson and ask about his cannon. He will part with it after you solve one of his personal problems. The simplest money route is Pure Luxury. The alternate route is The Pawned Pistol, which itself depends on Wilson's Pistol.", "Completion. Complete one accepted solution and return to Wilson.", "Related: Pure Luxury / The Pawned Pistol"),
            reward = "200 Glory",
            warnings = "",
            searchTags = listOf("The Cannon", "C. THE CANNON", "Wilson", "Antigua / Chapter 3"),
        ),
        Quest(
            id = "R2-C3-007",
            chapter = 3,
            playOrder = 7,
            title = "Pure Luxury",
            category = "CANNON SOLUTION — MONEY/SILVER TONGUE",
            giver = "Wilson",
            location = "Antigua / Chapter 3",
            prerequisites = "",
            summary = "Convince Grace to visit Wilson, paying 1000 gold or 500 with Silver Tongue 60.",
            walkthroughSteps = listOf("Walkthrough. Ask Wilson what he does for fun. Then speak with Grace outside Admiral Alvarez's house about Wilson. She agrees to visit him for 1000 gold; Silver Tongue 60 reduces the fee to 500.", "Completion. Pay Grace and return/report to Wilson as needed."),
            reward = "100 Glory",
            warnings = "⚠ Important: This route is expensive but straightforward.",
            searchTags = listOf("Pure Luxury", "C. THE CANNON", "Wilson", "Antigua / Chapter 3"),
        ),
        Quest(
            id = "R2-C3-008",
            chapter = 3,
            playOrder = 8,
            title = "The Pawned Pistol",
            category = "CANNON SOLUTION — PISTOL ROUTE",
            giver = "Wilson",
            location = "Antigua / Chapter 3",
            prerequisites = "",
            summary = "Recover Wilson's Pistol, then give it back to Wilson.",
            walkthroughSteps = listOf("Walkthrough. Ask Wilson about his pawned pistol and offer to retrieve it. Complete Wilson's Pistol, then return to Wilson and hand over the weapon.", "Completion. Wilson accepts the pistol and the cannon route is resolved.", "Related: Wilson's Pistol"),
            reward = "100 Glory",
            warnings = "⚠ Important: Completing this gives a one-time opportunity to access Wilson as a blade-weapons merchant.",
            searchTags = listOf("The Pawned Pistol", "C. THE CANNON", "Wilson", "Antigua / Chapter 3"),
        ),
        Quest(
            id = "R2-C3-009",
            chapter = 3,
            playOrder = 9,
            title = "Wilson's Pistol",
            category = "CANNON SUBQUEST",
            giver = "Henri",
            location = "Antigua / Chapter 3",
            prerequisites = "",
            summary = "Get Wilson's Pistol from Henri by winning the shooting route and buying it for 1000 gold, or steal it with a trained monkey.",
            walkthroughSteps = listOf("Walkthrough. Speak with Henri about something special. You can complete Shooting Match with Henri and then buy Wilson's Pistol for 1000 gold. Alternatively, if you know Monkey Trainer, send your monkey through the window on the north side of Henri's building and steal the pistol.", "Completion. Obtain Wilson's Pistol.", "Related: Shooting Match with Henri"),
            reward = "100 Glory",
            warnings = "",
            searchTags = listOf("Wilson's Pistol", "C. THE CANNON", "Henri", "Antigua / Chapter 3"),
        ),
        Quest(
            id = "R2-C3-010",
            chapter = 3,
            playOrder = 10,
            title = "Shooting Match with Henri",
            category = "OPTIONAL / PISTOL ROUTE",
            giver = "Henri",
            location = "Antigua / Chapter 3",
            prerequisites = "",
            summary = "Follow Henri to the range and hit at least 8 of 10 shots.",
            walkthroughSteps = listOf("Walkthrough. Ask Henri about proving your honour and accept the shooting contest. Follow him to the range, then complete the ten-shot challenge.", "Completion. Score at least eight hits.", "Related: Follow Henri to the Shooting Range"),
            reward = "100 Glory",
            warnings = "",
            searchTags = listOf("Shooting Match with Henri", "C. THE CANNON", "Henri", "Antigua / Chapter 3"),
        ),
        Quest(
            id = "R2-C3-011",
            chapter = 3,
            playOrder = 11,
            title = "Follow Henri to the Shooting Range",
            category = "ESCORT",
            giver = "Henri",
            location = "Antigua / Chapter 3",
            prerequisites = "",
            summary = "Follow Henri to the shooting range.",
            walkthroughSteps = listOf("Walkthrough. Stay close to Henri after starting the shooting contest.", "Completion. Reach the range with him."),
            reward = "10 Glory",
            warnings = "",
            searchTags = listOf("Follow Henri to the Shooting Range", "C. THE CANNON", "Henri", "Antigua / Chapter 3"),
        ),
        Quest(
            id = "R2-C3-012",
            chapter = 3,
            playOrder = 12,
            title = "Powder Kegs",
            category = "SHIP EQUIPMENT",
            giver = "Rick",
            location = "Antigua / Chapter 3",
            prerequisites = "",
            summary = "Either complete A Treasure on Antigua for Rick or use Intimidate 55.",
            walkthroughSteps = listOf("Walkthrough. Speak with Rick about the powder kegs. If your Intimidate is 55, you can pressure him immediately. Otherwise ask about his work and agree to help, which starts A Treasure on Antigua.", "Completion. Return to Rick after satisfying one of the two routes.", "Related: A Treasure on Antigua"),
            reward = "200 Glory",
            warnings = "",
            searchTags = listOf("Powder Kegs", "D. POWDER KEGS", "Rick", "Antigua / Chapter 3"),
        ),
        Quest(
            id = "R2-C3-013",
            chapter = 3,
            playOrder = 13,
            title = "A Treasure on Antigua",
            category = "POWDER-KEG SUBQUEST",
            giver = "Rick",
            location = "Antigua / Chapter 3",
            prerequisites = "",
            summary = "Start any one of Antigua's three treasure-map quests, then report back to Rick.",
            walkthroughSteps = listOf("Walkthrough. Rick wants proof that treasure is still worth pursuing. Start at least one of these real treasure quests: The Treasure on Antigua's Western Beach, The Treasure on a Rocky Plateau on Antigua, or The Treasure in the Grotto on Antigua. You do not need to finish the treasure itself merely to satisfy Rick's condition.", "Completion. Return to Rick after one qualifying treasure quest has been started."),
            reward = "100 Glory",
            warnings = "",
            searchTags = listOf("A Treasure on Antigua", "D. POWDER KEGS", "Rick", "Antigua / Chapter 3"),
        ),
        Quest(
            id = "R2-C3-014",
            chapter = 3,
            playOrder = 14,
            title = "Water Barrels",
            category = "SHIP EQUIPMENT — BRANCHING",
            giver = "Miles / Butch",
            location = "Antigua / Chapter 3",
            prerequisites = "",
            summary = "Get Butch out of the way so Miles can move the water, or possess Butch on the Voodoo route.",
            walkthroughSteps = listOf("Walkthrough. Talk with Miles and Butch near the water supply. Standard route: start Butch Has Got to Go, lure Butch into the cave and either use the Nuff Said skill or beat him. Natives/Voodoo route: create a Butch Voodoo Doll, possess him and order Miles to haul the water while you are in Butch's body.", "Completion. Report back to Miles, or complete the possession solution.", "Related: Butch Has Got to Go / The Butch Puppet"),
            reward = "200 Glory",
            warnings = "",
            searchTags = listOf("Water Barrels", "E. WATER BARRELS", "Miles / Butch", "Antigua / Chapter 3"),
        ),
        Quest(
            id = "R2-C3-015",
            chapter = 3,
            playOrder = 15,
            title = "Butch Has Got to Go",
            category = "WATER SUBQUEST",
            giver = "Miles",
            location = "Antigua / Chapter 3",
            prerequisites = "",
            summary = "Lure Butch into the cave and neutralize him, or use Voodoo.",
            walkthroughSteps = listOf("Walkthrough. After discussing Butch with Miles, persuade Butch that exploring a cave would be more pirate-like. Follow him through Down into the Cave. Inside, use Nuff Said if available, or trigger Give Butch a Thrashing. Natives can instead use The Butch Puppet route.", "Completion. Approach/report after Butch has been dealt with.", "Related: Down into the Cave / Give Butch a Thrashing / The Butch Puppet"),
            reward = "50 Glory",
            warnings = "⚠ Important: Give Butch a Thrashing cannot be obtained after Butch Has Got to Go is already completed.",
            searchTags = listOf("Butch Has Got to Go", "E. WATER BARRELS", "Miles", "Antigua / Chapter 3"),
        ),
        Quest(
            id = "R2-C3-016",
            chapter = 3,
            playOrder = 16,
            title = "Down into the Cave",
            category = "WATER SUBQUEST — ESCORT",
            giver = "Butch",
            location = "Antigua / Chapter 3",
            prerequisites = "",
            summary = "Follow Butch into the cave.",
            walkthroughSteps = listOf("Walkthrough. Convince Butch to go treasure hunting and follow him to the cave.", "Completion. The escort stage completes once you reach the confrontation area."),
            reward = "10 Glory",
            warnings = "",
            searchTags = listOf("Down into the Cave", "E. WATER BARRELS", "Butch", "Antigua / Chapter 3"),
        ),
        Quest(
            id = "R2-C3-017",
            chapter = 3,
            playOrder = 17,
            title = "Give Butch a Thrashing",
            category = "WATER SUBQUEST — FIGHT",
            giver = "Butch",
            location = "Antigua / Chapter 3",
            prerequisites = "",
            summary = "Beat Butch in a fight inside/after the cave sequence.",
            walkthroughSteps = listOf("Walkthrough. If you do not use the Nuff Said skill, provoke the fight and defeat Butch.", "Completion. Let him recover, then continue the water-barrel chain."),
            reward = "100 Glory",
            warnings = "",
            searchTags = listOf("Give Butch a Thrashing", "E. WATER BARRELS", "Butch", "Antigua / Chapter 3"),
        ),
        Quest(
            id = "R2-C3-018",
            chapter = 3,
            playOrder = 18,
            title = "The Butch Puppet",
            category = "NATIVES ONLY — VOODOO SOLUTION",
            giver = "Miles / Butch",
            location = "Antigua / Chapter 3",
            prerequisites = "",
            summary = "Make a Butch doll, possess him and order Miles to load the water.",
            walkthroughSteps = listOf("Walkthrough. Tell Miles you have a Voodoo solution. Take a strand of Butch's hair and complete Create Butch's Voodoo Doll. Use the doll on Butch, speak to Miles while possessing him and complete Water Barrels.", "Completion. Depossess Butch after the water has been secured.", "Related: Create Butch's Voodoo Doll"),
            reward = "50 Glory",
            warnings = "",
            searchTags = listOf("The Butch Puppet", "E. WATER BARRELS", "Miles / Butch", "Antigua / Chapter 3"),
        ),
        Quest(
            id = "R2-C3-019",
            chapter = 3,
            playOrder = 19,
            title = "Create Butch's Voodoo Doll",
            category = "NATIVES ONLY — CRAFTING",
            giver = "Butch",
            location = "Antigua / Chapter 3",
            prerequisites = "",
            summary = "Craft the Butch doll from jade, teeth, an eye, a Voodoo Doll base and his hair.",
            walkthroughSteps = listOf("Walkthrough. Take a strand of Butch's hair, then use a Voodoo Altar with the required ingredients.", "Completion. Create the doll."),
            reward = "50 Glory",
            warnings = "",
            searchTags = listOf("Create Butch's Voodoo Doll", "E. WATER BARRELS", "Butch", "Antigua / Chapter 3"),
        ),
        Quest(
            id = "R2-C3-020",
            chapter = 3,
            playOrder = 20,
            title = "Fresh Fish",
            category = "SHIP EQUIPMENT",
            giver = "Eddie",
            location = "Antigua / Chapter 3",
            prerequisites = "",
            summary = "Kill the Hobgoblin in the grotto north of the Fisherman's Hut and report to Eddie.",
            walkthroughSteps = listOf("Walkthrough. Find Eddie at the Fisherman's Hut. Ask about fish and his missing companion/problem. Enter the grotto north of the hut and defeat the Hobgoblin.", "Completion. Return to Eddie after The Hobgoblin is complete.", "Related: The Hobgoblin / The Missing Fisherman"),
            reward = "200 Glory",
            warnings = "",
            searchTags = listOf("Fresh Fish", "F. FRESH FISH", "Eddie", "Antigua / Chapter 3"),
        ),
        Quest(
            id = "R2-C3-021",
            chapter = 3,
            playOrder = 21,
            title = "The Hobgoblin",
            category = "COMBAT",
            giver = "Eddie / Duncan",
            location = "Antigua / Chapter 3",
            prerequisites = "",
            summary = "Kill the Hobgoblin in the grotto north of the Fisherman's Hut.",
            walkthroughSteps = listOf("Walkthrough. Enter the grotto and fight the Hobgoblin. It is worth significant Glory and carries useful loot, including an Oyster Shell, Black Pearl and Emerald.", "Completion. The quest completes when the Hobgoblin dies.", "Related: Fresh Fish / The Missing Fisherman"),
            reward = "100 Glory + 200 kill Glory",
            warnings = "",
            searchTags = listOf("The Hobgoblin", "F. FRESH FISH", "Eddie / Duncan", "Antigua / Chapter 3"),
        ),
        Quest(
            id = "R2-C3-022",
            chapter = 3,
            playOrder = 22,
            title = "The Helmsman",
            category = "SHIP EQUIPMENT",
            giver = "Morgan",
            location = "Antigua / Chapter 3",
            prerequisites = "",
            summary = "Beat Morgan in at least two events in his pirate triathlon.",
            walkthroughSteps = listOf("Walkthrough. Find Morgan in the Witch's Cauldron. Ask him to become Slayne's helmsman. He demands a pirate triathlon first.", "Completion. Complete Pirate Triathlon with Morgan; Morgan agrees to serve as helmsman.", "Related: Pirate Triathlon with Morgan"),
            reward = "200 Glory",
            warnings = "",
            searchTags = listOf("The Helmsman", "G. THE HELMSMAN", "Morgan", "Antigua / Chapter 3"),
        ),
        Quest(
            id = "R2-C3-023",
            chapter = 3,
            playOrder = 23,
            title = "Pirate Triathlon with Morgan",
            category = "MINIGAME / DUEL",
            giver = "Morgan",
            location = "Antigua / Chapter 3",
            prerequisites = "",
            summary = "Win at least two of three events: duel, drinking contest and shooting contest.",
            walkthroughSteps = listOf("Walkthrough. Accept Morgan's challenge. The three contests are a melee duel, the bottle-grabbing drinking minigame and a shooting challenge. You only need two wins, so losing one event does not fail the quest.", "Completion. Win two of the three contests."),
            reward = "200 Glory + 100 Glory for defeating Morgan in the duel",
            warnings = "",
            searchTags = listOf("Pirate Triathlon with Morgan", "G. THE HELMSMAN", "Morgan", "Antigua / Chapter 3"),
        ),
        Quest(
            id = "R2-C3-024",
            chapter = 3,
            playOrder = 24,
            title = "Beat 'Em Up",
            category = "OPTIONAL — DUEL",
            giver = "Zak",
            location = "Antigua / Chapter 3",
            prerequisites = "",
            summary = "Annoy Zak until he challenges you, then defeat him.",
            walkthroughSteps = listOf("Walkthrough. Keep asking Zak irritating questions until he threatens you, then ask one more. Fight and beat him.", "Completion. The quest completes when Zak loses."),
            reward = "100 Glory + 100 fight Glory",
            warnings = "⚠ Important: Using Intimidate 60 or polite dialogue avoids the fight and its associated Glory.",
            searchTags = listOf("Beat 'Em Up", "H. ANTIGUA SIDE QUESTS WORTH DOING NOW", "Zak", "Antigua / Chapter 3"),
        ),
        Quest(
            id = "R2-C3-025",
            chapter = 3,
            playOrder = 25,
            title = "Procure Fresh Supplies from Tacarigua",
            category = "OPTIONAL — CROSS-ISLAND",
            giver = "Spencer",
            location = "Antigua / Chapter 3",
            prerequisites = "",
            summary = "Sail to Tacarigua and arrange a rum shipment with Booze.",
            walkthroughSteps = listOf("Walkthrough. Speak with Spencer in the Witch's Cauldron and offer to help with rum. Sail back to Tacarigua and talk to Booze.", "Completion. The first delivery step completes and Take the Rum to Antigua starts.", "Related: Take the Rum to Antigua"),
            reward = "100 Glory",
            warnings = "",
            searchTags = listOf("Procure Fresh Supplies from Tacarigua", "H. ANTIGUA SIDE QUESTS WORTH DOING NOW", "Spencer", "Antigua / Chapter 3"),
        ),
        Quest(
            id = "R2-C3-026",
            chapter = 3,
            playOrder = 26,
            title = "Take the Rum to Antigua",
            category = "OPTIONAL — CROSS-ISLAND",
            giver = "Spencer",
            location = "Antigua / Chapter 3",
            prerequisites = "",
            summary = "Return to Antigua after arranging the rum and report to Spencer.",
            walkthroughSteps = listOf("Walkthrough. After Booze handles the supply, sail back to Antigua.", "Completion. Speak with Spencer."),
            reward = "100 Glory + 1000 Gold",
            warnings = "",
            searchTags = listOf("Take the Rum to Antigua", "H. ANTIGUA SIDE QUESTS WORTH DOING NOW", "Spencer", "Antigua / Chapter 3"),
        ),
        Quest(
            id = "R2-C3-027",
            chapter = 3,
            playOrder = 27,
            title = "The Missing Fisherman",
            category = "OPTIONAL — GROTTO",
            giver = "Eddie / Duncan",
            location = "Antigua / Chapter 3",
            prerequisites = "",
            summary = "Kill the Hobgoblin and speak with Duncan deep in the grotto.",
            walkthroughSteps = listOf("Walkthrough. Take the quest from Eddie, or find Duncan directly inside the grotto. Complete The Hobgoblin, then talk with Duncan about the threat.", "Completion. Duncan is safe and gives you a treasure map.", "Related: The Hobgoblin"),
            reward = "100 Glory + Treasure Map",
            warnings = "",
            searchTags = listOf("The Missing Fisherman", "H. ANTIGUA SIDE QUESTS WORTH DOING NOW", "Eddie / Duncan", "Antigua / Chapter 3"),
        ),
        Quest(
            id = "R2-C3-028",
            chapter = 3,
            playOrder = 28,
            title = "A Package for Mac",
            category = "OPTIONAL — DELIVERY",
            giver = "Mac / Rick",
            location = "Antigua / Chapter 3",
            prerequisites = "",
            summary = "Listen to Mac's stories, get his package from Rick and bring it back.",
            walkthroughSteps = listOf("Walkthrough. Exhaust Mac's stories and offer to help. Speak with Rick in Harbour Town to receive the Small Package.", "Completion. Return the package to Mac."),
            reward = "100 Glory",
            warnings = "",
            searchTags = listOf("A Package for Mac", "H. ANTIGUA SIDE QUESTS WORTH DOING NOW", "Mac / Rick", "Antigua / Chapter 3"),
        ),
        Quest(
            id = "R2-C3-029",
            chapter = 3,
            playOrder = 29,
            title = "The Password",
            category = "LATER STORY HOOK / MAIN STORY — PASSWORD",
            giver = "Strange Gate",
            location = "Antigua / Chapter 3 / Chapter 3",
            prerequisites = "",
            summary = "Examine the Strange Gate behind the large waterfall; the password is learned later from Garcia's Logbook.\nLearn the password to Antigua's waterfall gate from Garcia's Logbook or Steelbeard's Ghost.",
            walkthroughSteps = listOf("Chapter 3 — H. ANTIGUA SIDE QUESTS WORTH DOING NOW", "Walkthrough. Explore behind the large waterfall and inspect the Strange Gate. This activates the quest but it cannot be completed yet in this Part.", "Completion. Leave it active until the Garcia storyline provides the password.", "Chapter 3 — E. STEELBEARD'S ARTEFACT", "Walkthrough. If you already inspected the gate behind Antigua's large waterfall, this quest is active. Read Garcia's Logbook on his Maracai Bay ship, or on the Native route ask Steelbeard's Ghost.", "Completion. Learning the password completes the quest."),
            reward = "100 Glory",
            warnings = "⚠ Important: Do not waste time trying random answers; this intentionally continues into a later Chapter 3 storyline.",
            searchTags = listOf("The Password", "H. ANTIGUA SIDE QUESTS WORTH DOING NOW", "Strange Gate", "Antigua / Chapter 3", "E. STEELBEARD'S ARTEFACT", "Strange Gate / Garcia's Logbook", "Chapter 3"),
        ),
        Quest(
            id = "R2-C3-030",
            chapter = 3,
            playOrder = 30,
            title = "The Treasure on Antigua's Western Beach",
            category = "OPTIONAL — TREASURE",
            giver = "Treasure Map",
            location = "Antigua / Chapter 3",
            prerequisites = "",
            summary = "Steal the treasure map from Alvarez's bedroom chest, then dig at the western beach X.",
            walkthroughSteps = listOf("Walkthrough. Pick the difficulty-30 chest in Admiral Alvarez's bedroom and take the map. Follow the map marker to the western beach and use a shovel on the red X.", "Completion. Loot the buried chest."),
            reward = "100 Glory + treasure",
            warnings = "⚠ Important: Starting this quest also qualifies for A Treasure on Antigua.",
            searchTags = listOf("The Treasure on Antigua's Western Beach", "H. ANTIGUA SIDE QUESTS WORTH DOING NOW", "Treasure Map", "Antigua / Chapter 3"),
        ),
        Quest(
            id = "R2-C3-031",
            chapter = 3,
            playOrder = 31,
            title = "The Journey to the Isle of Thieves",
            category = "MAIN STORY — PART I END",
            giver = "Captain Slayne",
            location = "Antigua / Chapter 3",
            prerequisites = "",
            summary = "Finish Ship's Equipment, tell Slayne you are ready and sail to the Isle of Thieves.",
            walkthroughSteps = listOf("Walkthrough. After The Cannon, Powder Kegs, Water Barrels, Fresh Fish and The Helmsman are all complete, report to Slayne. Finish any remaining Antigua business you want, make a permanent save, then tell him you are ready to go.", "Completion. Sail to the Isle of Thieves and row ashore.", "Related: Treasure Cave / Chapter 3 Part II"),
            reward = "200 Glory",
            warnings = "⚠ Important: Talking to Patty after this quest starts also unlocks the Isle of Thieves as a known destination.",
            searchTags = listOf("The Journey to the Isle of Thieves", "I. READY TO SAIL", "Captain Slayne", "Antigua / Chapter 3"),
        ),
    )

    val notes: List<RisenGuideNote> = listOf(
        RisenGuideNote(3, 1, "Why Chapter 3 is split", listOf("Chapter 3 opens the sea map and contains several full island questlines. This Part covers Antigua and the complete preparation of Captain Slayne's ship. Part II will begin with The Journey to the Isle of Thieves and continue through Slayne's betrayal, the gnome island, the raft escape and the showdown back on Antigua.", "Recommended stopping point: Finish the Antigua side quests you care about, complete all five Ship's Equipment requirements, then make a permanent save before telling Slayne you are ready to sail for the Isle of Thieves.")),
        RisenGuideNote(3, 1, "A. ARRIVE ON ANTIGUA", listOf()),
        RisenGuideNote(3, 5, "B. SHIP'S EQUIPMENT — MASTER QUEST", listOf()),
        RisenGuideNote(3, 6, "C. THE CANNON", listOf()),
        RisenGuideNote(3, 12, "D. POWDER KEGS", listOf()),
        RisenGuideNote(3, 14, "E. WATER BARRELS", listOf()),
        RisenGuideNote(3, 20, "F. FRESH FISH", listOf()),
        RisenGuideNote(3, 22, "G. THE HELMSMAN", listOf()),
        RisenGuideNote(3, 24, "H. ANTIGUA SIDE QUESTS WORTH DOING NOW", listOf()),
        RisenGuideNote(3, 31, "I. READY TO SAIL", listOf()),
        RisenGuideNote(3, 32, "PART I COMPLETION CHECKLIST", listOf("Find Captain Slayne and all three Slayne escort entries are complete.", "The Cannon is complete through either Pure Luxury or the pistol route.", "Powder Kegs is complete.", "Water Barrels is complete through the combat/skill or Voodoo solution.", "Fresh Fish and The Hobgoblin are complete.", "Morgan is recruited through Pirate Triathlon with Morgan.", "Ship's Equipment is complete.", "Antigua side quests you care about were finished or intentionally left for later.", "The Password is allowed to remain active; it is a later Garcia-story quest.", "A permanent save exists before sailing with Slayne.", "The Journey to the Isle of Thieves is ready to begin Part II.")),
    )
}
