package com.sliverzfx.gothicquest

internal object RisenGuidePart1Data {
    val quests: List<Quest> = listOf(
        Quest(
            id = "R1-C1-001",
            chapter = 1,
            playOrder = 1,
            title = "Find survivors of the shipwreck",
            category = "PROLOGUE",
            giver = "Automatic",
            location = "Shipwreck beach",
            prerequisites = "Start. The quest begins immediately after the opening cinematic.",
            summary = "Search the beach until you find Sara alive.",
            walkthroughSteps = listOf("Start. The quest begins immediately after the opening cinematic.", "Steps. Loot the beach as you move. Pick up weapons, food, potions and valuables; Risen has no inventory weight limit. Find Sara among the wreck survivors and speak with her.", "Completion. Talking with Sara advances the survival sequence."),
            reward = "Early XP / survival progression",
            warnings = "",
            searchTags = listOf("Find survivors of the shipwreck", "Automatic", "Shipwreck beach", "PROLOGUE", "", "PROLOGUE — THE SHIPWRECK"),
        ),
        Quest(
            id = "R1-C1-002",
            chapter = 1,
            playOrder = 2,
            title = "Take some fried meat to Sara",
            category = "PROLOGUE",
            giver = "Sara",
            location = "Abandoned house near the beach",
            prerequisites = "Start. After reaching the abandoned shelter with Sara, she needs food.",
            summary = "Find raw meat and a frying pan, cook the meat at a fire, then give one piece to Sara.",
            walkthroughSteps = listOf("Start. After reaching the abandoned shelter with Sara, she needs food.", "Steps. Loot the house and nearby area. Use a frying pan at a fire to turn raw meat into fried meat. Keep some raw meat in reserve because later quests use it. Give Sara one fried meat.", "Completion. Sara accepts the food; the prologue can then transition into Chapter 1."),
            reward = "25 XP",
            warnings = "",
            searchTags = listOf("Take some fried meat to Sara", "Sara", "Abandoned house near the beach", "PROLOGUE", "", "PROLOGUE — THE SHIPWRECK"),
        ),
        Quest(
            id = "R1-C1-003",
            chapter = 1,
            playOrder = 3,
            title = "Alone and abandoned",
            category = "SAFE",
            giver = "Sara / automatic",
            location = "Beach shelter → inland road",
            prerequisites = "Start. After Sara decides to remain at the shelter, Chapter 1 begins.",
            summary = "Leave Sara at the shelter, follow the uphill road inland and enter the next abandoned house where Jan is waiting.",
            walkthroughSteps = listOf("Start. After Sara decides to remain at the shelter, Chapter 1 begins.", "Steps. Take the zig-zag path uphill. A small ruin with Grave Moths lies along the route; you may explore it carefully for loot. Continue along the main path until you reach another isolated house. Enter it.", "Completion. Entering the house and meeting Jan completes the quest."),
            reward = "50 XP",
            warnings = "⚠ Important: Do not deliberately wander into heavily guarded Order positions yet; Chapter 1 is designed to let you investigate both factions first.",
            searchTags = listOf("Alone and abandoned", "Sara / automatic", "Beach shelter → inland road", "SAFE", "", "CHAPTER 1 — THE FORBIDDEN ISLAND"),
        ),
        Quest(
            id = "R1-C1-004",
            chapter = 1,
            playOrder = 4,
            title = "Get yourself a decent weapon",
            category = "SAFE",
            giver = "Jan",
            location = "Jan's abandoned house",
            prerequisites = "Start. Jan gives this immediately after meeting you.",
            summary = "Search Jan's house: take the key downstairs, open the upstairs chest and take the sword and map.",
            walkthroughSteps = listOf("Start. Jan gives this immediately after meeting you.", "Steps. Search the lower floor and cupboard for the chest key. Go upstairs, unlock the chest and take the sword plus the crude island map. Equip the sword, then speak with Jan again and ask him about the island and its factions.", "Completion. The weapon pickup completes the journal objective; speaking with Jan gives the useful follow-up information."),
            reward = "50 XP + follow-up XP",
            warnings = "",
            searchTags = listOf("Get yourself a decent weapon", "Jan", "Jan's abandoned house", "SAFE", "", "CHAPTER 1 — THE FORBIDDEN ISLAND"),
        ),
        Quest(
            id = "R1-C1-005",
            chapter = 1,
            playOrder = 5,
            title = "Rescue Sara from the wilderness",
            category = "SAFE / ALTERNATIVE RESOLUTION",
            giver = "Jan OR Tristan",
            location = "Sara's shelter",
            prerequisites = "Start. After meeting Jan, tell him that Sara is still at the first shelter. If you skip Jan's solution, Tristan at the Novice Farm can arrange help instead.",
            summary = "Tell either Jan or Tristan where Sara is; then return to Sara and tell her help is coming.",
            walkthroughSteps = listOf("Start. After meeting Jan, tell him that Sara is still at the first shelter. If you skip Jan's solution, Tristan at the Novice Farm can arrange help instead.", "Steps. Choose one rescuer. Jan's route later places Sara with the Bandits; Tristan's route later places her with the novices/Order-side people. Return to Sara if the dialogue option is available and tell her about the arrangement.", "Completion. The rescue arrangement completes the objective and Sara will relocate later."),
            reward = "50 XP; Sara follow-up reward",
            warnings = "⚠ Important: The choice does not decide your faction. It mainly changes where Sara later appears, so either route is safe.",
            searchTags = listOf("Rescue Sara from the wilderness", "Jan OR Tristan", "Sara's shelter", "SAFE / ALTERNATIVE RESOLUTION", "", "CHAPTER 1 — THE FORBIDDEN ISLAND"),
        ),
        Quest(
            id = "R1-C1-006",
            chapter = 1,
            playOrder = 6,
            title = "Follow Jan to the west",
            category = "SAFE",
            giver = "Jan",
            location = "Jan's house → western road",
            prerequisites = "Start. After finishing Jan's introductory dialogue, ask for the route west.",
            summary = "Ask Jan to show you the way to the Bandit Camp and follow him until his first stop near the Order-held ruins.",
            walkthroughSteps = listOf("Start. After finishing Jan's introductory dialogue, ask for the route west.", "Steps. Stay close to Jan. At the first stopping point he points out ruins occupied by Warriors of the Order and warns you about them.", "Completion. The first escort journal entry completes when Jan stops and explains the danger."),
            reward = "25 XP",
            warnings = "⚠ Important: Do not walk into the Order group if you want to preserve free faction choice.",
            searchTags = listOf("Follow Jan to the west", "Jan", "Jan's house → western road", "SAFE", "", "CHAPTER 1 — THE FORBIDDEN ISLAND"),
        ),
        Quest(
            id = "R1-C1-007",
            chapter = 1,
            playOrder = 7,
            title = "Follow Jan farther to the west",
            category = "SAFE",
            giver = "Jan",
            location = "Western road → Bandit Camp approach",
            prerequisites = "Start. Continue the westward escort after Jan's first warning.",
            summary = "Tell Jan to continue and follow him until he shows you the route into the swamp/Bandit Camp.",
            walkthroughSteps = listOf("Start. Continue the westward escort after Jan's first warning.", "Steps. Follow him farther along the road. At the final stop he explains how to continue toward the Bandit Camp, then eventually returns toward his house.", "Completion. The second westward escort entry completes at Jan's final stop."),
            reward = "25 XP",
            warnings = "⚠ Important: Visiting and questing in the Bandit Camp does NOT by itself commit you to becoming a Bandit.",
            searchTags = listOf("Follow Jan farther to the west", "Jan", "Western road → Bandit Camp approach", "SAFE", "", "CHAPTER 1 — THE FORBIDDEN ISLAND"),
        ),
        Quest(
            id = "R1-C1-008",
            chapter = 1,
            playOrder = 8,
            title = "Follow Jan to the novices' farm in the east",
            category = "SAFE",
            giver = "Jan",
            location = "Jan's house → Tristan's Farm",
            prerequisites = "Start. Return to Jan or catch him as he heads back and ask about the eastern route.",
            summary = "Ask Jan for the Harbour Town route and follow him east until he points you toward Tristan's Novice Farm.",
            walkthroughSteps = listOf("Start. Return to Jan or catch him as he heads back and ask about the eastern route.", "Steps. Follow Jan east. He leads you toward the farm used by the novices and leaves you close enough to continue alone.", "Completion. The escort completes when Jan finishes showing the eastern route."),
            reward = "50 XP",
            warnings = "",
            searchTags = listOf("Follow Jan to the novices' farm in the east", "Jan", "Jan's house → Tristan's Farm", "SAFE", "", "CHAPTER 1 — THE FORBIDDEN ISLAND"),
        ),
        Quest(
            id = "R1-C1-009",
            chapter = 1,
            playOrder = 9,
            title = "Help the novices' farm",
            category = "SAFE / HUB QUEST",
            giver = "Tristan",
            location = "Tristan's Novice Farm",
            prerequisites = "Start. Speak with Tristan outside the farmhouse and ask for work or help reaching Harbour Town.",
            summary = "Help Thomas harvest grain, help Henson with five hungry wolves, speak with Tellur, then report all three results to Tristan.",
            walkthroughSteps = listOf("Start. Speak with Tristan outside the farmhouse and ask for work or help reaching Harbour Town.", "Steps. Tristan wants you to make yourself useful. Complete Thomas's field job and Henson's wolf problem. Speak with Tellur as well; he has no work for you, but reporting that fact is part of Tristan's checklist. Return to Tristan after all three conversations/objectives.", "Completion. Tell Tristan that there is nothing else to do on the farm. He rewards you and authorizes Tellur to guide you toward Harbour Town."),
            reward = "75 XP + 2 small healing potions + bread + water, plus subquest rewards",
            warnings = "",
            searchTags = listOf("Help the novices' farm", "Tristan", "Tristan's Novice Farm", "SAFE / HUB QUEST", "", "TRISTAN'S NOVICE FARM"),
        ),
        Quest(
            id = "R1-C1-010",
            chapter = 1,
            playOrder = 10,
            title = "Help Thomas in the fields",
            category = "SAFE",
            giver = "Thomas",
            location = "Novice Farm grain field",
            prerequisites = "Start. Speak with Thomas while he is working in the field.",
            summary = "Pick 10 grain plants from Thomas's own field and return to him.",
            walkthroughSteps = listOf("Start. Speak with Thomas while he is working in the field.", "Steps. Walk through Thomas's tilled patch and pick the ten slightly greener grain plants. All ten are in his field; you do not need to search the opposite field.", "Completion. Return to Thomas after collecting all ten."),
            reward = "50 XP + healing potion",
            warnings = "",
            searchTags = listOf("Help Thomas in the fields", "Thomas", "Novice Farm grain field", "SAFE", "", "TRISTAN'S NOVICE FARM"),
        ),
        Quest(
            id = "R1-C1-011",
            chapter = 1,
            playOrder = 11,
            title = "Grain harvest",
            category = "SAFE / SUBQUEST",
            giver = "Automatic / Thomas",
            location = "Novice Farm grain field",
            prerequisites = "Start. This journal sub-entry progresses while doing “Help Thomas in the fields.”",
            summary = "Collect all 10 grain plants in Thomas's field.",
            walkthroughSteps = listOf("Start. This journal sub-entry progresses while doing “Help Thomas in the fields.”", "Steps. Pick each of the ten grain plants. Use the item labels/highlight if one is difficult to see among the crop.", "Completion. The tenth grain pickup completes the harvest entry; then speak to Thomas to finish his parent quest."),
            reward = "50 XP",
            warnings = "",
            searchTags = listOf("Grain harvest", "Automatic / Thomas", "Novice Farm grain field", "SAFE / SUBQUEST", "", "TRISTAN'S NOVICE FARM"),
        ),
        Quest(
            id = "R1-C1-012",
            chapter = 1,
            playOrder = 12,
            title = "Kill the hungry wolves",
            category = "SAFE — WITH ARREST WARNING",
            giver = "Henson",
            location = "Cave beside Novice Farm",
            prerequisites = "Start. Speak with Henson near the farm/barn and agree to deal with the wolves attacking the livestock.",
            summary = "Kill all 5 hungry wolves—one around the cave entrance and four inside—then avoid the arriving Order warrior, sleep in the barn/storehouse and speak with Henson the next morning.",
            walkthroughSteps = listOf("Start. Speak with Henson near the farm/barn and agree to deal with the wolves attacking the livestock.", "Steps. Go to the cave immediately beside/east of the farm. Kill the hungry wolves, preferably one or two at a time. There are five quest wolves in total. Loot the cave, but the rear exit leads into more dangerous territory and is unnecessary now. When you return toward the farm, Henson warns that a Warrior of the Order has arrived. Follow Henson's advice: avoid the warrior, enter the barn/storehouse and sleep until the next morning. Then speak with Henson again.", "Completion. The kill counter completes after all five wolves die; Henson's next-morning conversation provides the full reward."),
            reward = "50 XP + Henson follow-up XP + Strong Magic Healing scroll",
            warnings = "⚠ Important: If the Order warrior catches you, you can be forcibly taken to the Monastery. Avoid him if you want the broadest possible Bandit/Order/Mage choice later.",
            searchTags = listOf("Kill the hungry wolves", "Henson", "Cave beside Novice Farm", "SAFE — WITH ARREST WARNING", "", "TRISTAN'S NOVICE FARM"),
        ),
        Quest(
            id = "R1-C1-013",
            chapter = 1,
            playOrder = 13,
            title = "Follow Tellur",
            category = "SAFE / ESCORT",
            giver = "Tellur",
            location = "Novice Farm → lake bridge",
            prerequisites = "Start. Complete “Help the novices' farm,” report back to Tristan, then speak with Tellur.",
            summary = "After Tristan authorizes him, ask Tellur to guide you toward Harbour Town and follow him to the bridge/lake.",
            walkthroughSteps = listOf("Start. Complete “Help the novices' farm,” report back to Tristan, then speak with Tellur.", "Steps. Follow Tellur down from the farm. Do not sprint far ahead; let him reach his scripted stopping point near the lake walkway.", "Completion. The first escort entry completes when Tellur stops and warns you about the dangerous lake."),
            reward = "50 XP",
            warnings = "",
            searchTags = listOf("Follow Tellur", "Tellur", "Novice Farm → lake bridge", "SAFE / ESCORT", "", "TRISTAN'S NOVICE FARM"),
        ),
        Quest(
            id = "R1-C1-014",
            chapter = 1,
            playOrder = 14,
            title = "Follow Tellur across the dangerous lake",
            category = "SAFE / ESCORT",
            giver = "Tellur",
            location = "Lake crossing",
            prerequisites = "Start. Tell Tellur to continue after his first stop.",
            summary = "Continue across the lake with Tellur until the next crossroads.",
            walkthroughSteps = listOf("Start. Tell Tellur to continue after his first stop.", "Steps. Cross using the safe route Tellur demonstrates. At the far side he stops and explains the road toward Harbour Town and why the guarded entrance is a problem.", "Completion. The journal entry completes at the crossroads."),
            reward = "50 XP",
            warnings = "",
            searchTags = listOf("Follow Tellur across the dangerous lake", "Tellur", "Lake crossing", "SAFE / ESCORT", "", "TRISTAN'S NOVICE FARM"),
        ),
        Quest(
            id = "R1-C1-015",
            chapter = 1,
            playOrder = 15,
            title = "Keep following Tellur",
            category = "SAFE / ESCORT",
            giver = "Tellur",
            location = "Crossroads → Monastery-road junction",
            prerequisites = "Start. Continue the guided route after the lake.",
            summary = "Ask Tellur to keep going and follow him uphill until he points out the road to the Monastery.",
            walkthroughSteps = listOf("Start. Continue the guided route after the lake.", "Steps. Stay with Tellur up the road. At his next scripted stop he identifies the branch leading toward the Monastery.", "Completion. The quest completes when his explanation finishes."),
            reward = "50 XP",
            warnings = "⚠ Important: Knowing the Monastery road is useful, but do not walk into an Order arrest if you have not chosen that path.",
            searchTags = listOf("Keep following Tellur", "Tellur", "Crossroads → Monastery-road junction", "SAFE / ESCORT", "", "TRISTAN'S NOVICE FARM"),
        ),
        Quest(
            id = "R1-C1-016",
            chapter = 1,
            playOrder = 16,
            title = "Follow Tellur one more time",
            category = "SAFE / ESCORT",
            giver = "Tellur",
            location = "Monastery-road junction → Harbour Town rear-route junction",
            prerequisites = "Start. At Tellur's Monastery-road stop, ask him to continue one final time.",
            summary = "Tell Tellur you still need him and follow him to the final junction, where he identifies the safer rear/east entrance to Harbour Town.",
            walkthroughSteps = listOf("Start. At Tellur's Monastery-road stop, ask him to continue one final time.", "Steps. Follow him to the next crossroads. He explains which road reaches the less dangerous city entrance. The main/front gate is controlled by the Order; the alternative entrance is the route a faction-neutral newcomer should use.", "Completion. Tellur's final explanation completes the fourth escort entry."),
            reward = "50 XP",
            warnings = "⚠ Important: This is the natural stopping point for Part I. Do not let an Order patrol forcibly recruit you before we handle the Harbour Town faction quests.",
            searchTags = listOf("Follow Tellur one more time", "Tellur", "Monastery-road junction → Harbour Town rear-route junction", "SAFE / ESCORT", "", "TRISTAN'S NOVICE FARM"),
        ),
    )

    val notes: List<RisenGuideNote> = listOf(
        RisenGuideNote(1, 1, "Before you begin", listOf("Completionist warning: Do not allow an Order warrior to arrest you on the road or at Tristan's farm if you want to preserve the widest faction choice. Forced recruitment into the Monastery can restrict later options. Save before approaching Order patrols.")),
        RisenGuideNote(1, 1, "PROLOGUE — THE SHIPWRECK", listOf("The game begins before Chapter 1. These opening objectives teach looting, combat and cooking and lead directly into the first official Chapter 1 journal quest.")),
        RisenGuideNote(1, 3, "CHAPTER 1 — THE FORBIDDEN ISLAND", listOf()),
        RisenGuideNote(1, 9, "TRISTAN'S NOVICE FARM", listOf("The farm is an excellent early-game stop because its jobs are faction-neutral and provide XP, supplies and a safe guided route toward Harbour Town.")),
        RisenGuideNote(1, 17, "PART I — COMPLETION CHECKLIST", listOf("Sara has been fed and a rescuer (Jan or Tristan) has been arranged.", "Jan's sword/map quest is complete.", "Both western Jan escort entries are complete if you wanted the Bandit Camp route marked.", "Jan's eastern Novice Farm escort is complete.", "Thomas's 10 grain and Henson's 5 hungry wolves are complete.", "The Order warrior at the farm did not forcibly arrest you.", "Tristan's farm hub quest is complete.", "All four Tellur escort journal entries are complete.", "You now know the safe approach to Harbour Town, but have not yet committed to Bandits, Order or Mages.")),
    )
}
