package com.sliverzfx.gothicquest

/** Standalone Bandit Camp and excavation quests omitted from the original condensed walkthrough. */
internal object RisenGuidePart12Data {
    val quests: List<Quest> = listOf(
        Quest(
            id = "R1-C1-171",
            chapter = 1,
            playOrder = 171,
            title = "Take the Golden Fragment from Brogar",
            category = "BANDIT CAMP — SIDE QUEST",
            giver = "Brogar / arena loot",
            location = "Bandit Camp / swamp",
            prerequisites = "Defeat Brogar in the Bandit Camp arena during his challenge.",
            summary = "Search Brogar while he is unconscious.",
            walkthroughSteps = listOf("Start. Defeat Brogar in the Bandit Camp arena during his challenge.", "Steps. Search Brogar while he is unconscious.", "Completion. Take the Golden Sword fragment needed for Oscar's sword quest."),
            reward = "100 XP",
            warnings = "",
            searchTags = listOf("Take the Golden Fragment from Brogar", "Brogar / arena loot", "Bandit Camp", "swamp", "Chapter 1"),
        ),
        Quest(
            id = "R1-C1-172",
            chapter = 1,
            playOrder = 172,
            title = "Forbidden Games",
            category = "BANDIT CAMP — SIDE QUEST",
            giver = "Craig / Rachel",
            location = "Bandit Camp / swamp",
            prerequisites = "Speak to Craig about underground arena gambling; progress through the arena fights.",
            summary = "Tell Rachel about Craig's illegal wagers and return to Craig.",
            walkthroughSteps = listOf("Start. Speak to Craig about underground arena gambling; progress through the arena fights.", "Steps. Tell Rachel about Craig's illegal wagers and return to Craig.", "Completion. Persuade Craig to stop the games, report to Rachel, then speak to Craig again."),
            reward = "100 XP plus 50 XP and 30 gold from Rachel",
            warnings = "",
            searchTags = listOf("Forbidden Games", "Craig / Rachel", "Bandit Camp", "swamp", "Chapter 1"),
        ),
        Quest(
            id = "R1-C1-173",
            chapter = 1,
            playOrder = 173,
            title = "To the Temple Ruins with Lorenzo",
            category = "BANDIT CAMP — SIDE QUEST",
            giver = "Lorenzo",
            location = "Bandit Camp / swamp",
            prerequisites = "Agree to Lorenzo's invitation near the Bandit Camp arena.",
            summary = "Follow Lorenzo up the trail toward the plateau and ruined temple.",
            walkthroughSteps = listOf("Start. Agree to Lorenzo's invitation near the Bandit Camp arena.", "Steps. Follow Lorenzo up the trail toward the plateau and ruined temple.", "Completion. When he ambushes you, pay 50 gold or fight him to resolve the trap."),
            reward = "150 XP when Lorenzo reveals his ambush",
            warnings = "",
            searchTags = listOf("To the Temple Ruins with Lorenzo", "Lorenzo", "Bandit Camp", "swamp", "Chapter 1"),
        ),
        Quest(
            id = "R1-C1-174",
            chapter = 1,
            playOrder = 174,
            title = "Get Branon to Go Back to Digging",
            category = "BANDIT CAMP — SIDE QUEST",
            giver = "Branon",
            location = "Bandit Camp / swamp",
            prerequisites = "While helping Hawkins, find Branon at the upper Bandit Camp digsite.",
            summary = "Clear the grave moths near Ricardo's island so the worksite is safe.",
            walkthroughSteps = listOf("Start. While helping Hawkins, find Branon at the upper Bandit Camp digsite.", "Steps. Clear the grave moths near Ricardo's island so the worksite is safe.", "Completion. Tell Branon it is safe to resume digging and report to Hawkins."),
            reward = "125 XP",
            warnings = "",
            searchTags = listOf("Get Branon to Go Back to Digging", "Branon", "Bandit Camp", "swamp", "Chapter 1"),
        ),
        Quest(
            id = "R1-C1-175",
            chapter = 1,
            playOrder = 175,
            title = "Artefact Delivery",
            category = "BANDIT CAMP — SIDE QUEST",
            giver = "Beppo",
            location = "Bandit Camp / swamp",
            prerequisites = "Talk to Beppo about delays with the artifact crates in the swamp.",
            summary = "Convince Dwight to go back to work using Hawkins's authority.",
            walkthroughSteps = listOf("Start. Talk to Beppo about delays with the artifact crates in the swamp.", "Steps. Convince Dwight to go back to work using Hawkins's authority.", "Completion. Return to Beppo and tell him the crate workers have resumed."),
            reward = "150 XP and 20 gold; 25 XP and 20 gold extra from Rachel",
            warnings = "",
            searchTags = listOf("Artefact Delivery", "Beppo", "Bandit Camp", "swamp", "Chapter 1"),
        ),
        Quest(
            id = "R1-C1-176",
            chapter = 1,
            playOrder = 176,
            title = "Gone with the Gold",
            category = "BANDIT CAMP — SIDE QUEST",
            giver = "Brogar",
            location = "Bandit Camp / swamp",
            prerequisites = "After finishing Lazy Dog, ask Brogar about his missing man Dorgan.",
            summary = "Question Luis if desired; find Dorgan's corpse in the grave-moth cave and loot his list.",
            walkthroughSteps = listOf("Start. After finishing Lazy Dog, ask Brogar about his missing man Dorgan.", "Steps. Question Luis if desired; find Dorgan's corpse in the grave-moth cave and loot his list.", "Completion. Show Rachel the list before reporting Dorgan's death to Brogar."),
            reward = "50 XP on report; optional 50 XP from Rachel",
            warnings = "",
            searchTags = listOf("Gone with the Gold", "Brogar", "Bandit Camp", "swamp", "Chapter 1"),
        ),
        Quest(
            id = "R1-C1-177",
            chapter = 1,
            playOrder = 177,
            title = "An Audience with Don Esteban",
            category = "BANDIT CAMP — SIDE QUEST",
            giver = "Rachel",
            location = "Bandit Camp / swamp",
            prerequisites = "Help Rachel restore order in the camp and obtain Oscar's reforged Golden Sword.",
            summary = "Show the sword to Rachel and ask her for admission to the Don.",
            walkthroughSteps = listOf("Start. Help Rachel restore order in the camp and obtain Oscar's reforged Golden Sword.", "Steps. Show the sword to Rachel and ask her for admission to the Don.", "Completion. Present Rachel's approval to the temple guard; take the sword inside to Esteban."),
            reward = "400 XP from Rachel and 25 XP from temple guard",
            warnings = "",
            searchTags = listOf("An Audience with Don Esteban", "Rachel", "Bandit Camp", "swamp", "Chapter 1"),
        ),
        Quest(
            id = "R1-C1-178",
            chapter = 1,
            playOrder = 178,
            title = "Situation Report for the Don",
            category = "BANDIT CAMP — SIDE QUEST",
            giver = "Don Esteban",
            location = "Bandit Camp / swamp",
            prerequisites = "After gaining access to Don Esteban in the swamp temple, ask about his men in Harbour Town.",
            summary = "Travel to Harbour Town and speak with Scordo in his secret storeroom.",
            walkthroughSteps = listOf("Start. After gaining access to Don Esteban in the swamp temple, ask about his men in Harbour Town.", "Steps. Travel to Harbour Town and speak with Scordo in his secret storeroom.", "Completion. Return to Esteban with Scordo's report."),
            reward = "300 XP from Scordo; further Don dialogue reward varies",
            warnings = "",
            searchTags = listOf("Situation Report for the Don", "Don Esteban", "Bandit Camp", "swamp", "Chapter 1"),
        ),
        Quest(
            id = "R1-C1-179",
            chapter = 1,
            playOrder = 179,
            title = "Conquest of the Artifact Camp",
            category = "BANDIT CAMP — SIDE QUEST",
            giver = "Fincher",
            location = "Bandit Camp / swamp",
            prerequisites = "Complete the Don's prerequisites, then agree to reclaim the Order excavation site with Fincher.",
            summary = "Recruit Craig, Lorenzo, Domingo, Phil and Ricardo if desired; storm the nearby Order artifact camp.",
            walkthroughSteps = listOf("Start. Complete the Don's prerequisites, then agree to reclaim the Order excavation site with Fincher.", "Steps. Recruit Craig, Lorenzo, Domingo, Phil and Ricardo if desired; storm the nearby Order artifact camp.", "Completion. Defeat the defending Order troops and report the success to Fincher."),
            reward = "500 XP",
            warnings = "Bandit-aligned military quest; hostile action against the Order can cut off competing paths.",
            searchTags = listOf("Conquest of the Artifact Camp", "Fincher", "Bandit Camp", "swamp", "Chapter 1"),
        ),
        Quest(
            id = "R1-C1-180",
            chapter = 1,
            playOrder = 180,
            title = "Tell the Don about the Success in the Artifact Camp",
            category = "BANDIT CAMP — SIDE QUEST",
            giver = "Don Esteban",
            location = "Bandit Camp / swamp",
            prerequisites = "Capture the Order's nearby artifact excavation on Fincher's instructions.",
            summary = "Speak to Fincher after the battle and confirm the site has been reclaimed.",
            walkthroughSteps = listOf("Start. Capture the Order's nearby artifact excavation on Fincher's instructions.", "Steps. Speak to Fincher after the battle and confirm the site has been reclaimed.", "Completion. Report to Don Esteban in the swamp temple."),
            reward = "Additional XP and gold; exact quantities not independently confirmed",
            warnings = "",
            searchTags = listOf("Tell the Don about the Success in the Artifact Camp", "Don Esteban", "Bandit Camp", "swamp", "Chapter 1"),
        ),
        Quest(
            id = "R1-C1-181",
            chapter = 1,
            playOrder = 181,
            title = "Salvage Work",
            category = "BANDIT CAMP — SIDE QUEST",
            giver = "Fincher",
            location = "Bandit Camp / swamp",
            prerequisites = "Recapture the Order artifact excavation and speak to Fincher about restarting the salvage.",
            summary = "Talk to Hawkins, Enrico, Branon and Dwight; convince all four to resume moving the crates.",
            walkthroughSteps = listOf("Start. Recapture the Order artifact excavation and speak to Fincher about restarting the salvage.", "Steps. Talk to Hawkins, Enrico, Branon and Dwight; convince all four to resume moving the crates.", "Completion. Return to Fincher once the workers are ready."),
            reward = "200 XP",
            warnings = "",
            searchTags = listOf("Salvage Work", "Fincher", "Bandit Camp", "swamp", "Chapter 1"),
        ),
        Quest(
            id = "R1-C1-182",
            chapter = 1,
            playOrder = 182,
            title = "Tell Fincher about the Strange Temple Entrance in the East",
            category = "BANDIT CAMP — SIDE QUEST",
            giver = "Fincher",
            location = "Bandit Camp / swamp",
            prerequisites = "After the artifact camp is secured, ask Fincher about an unusual eastern ruin.",
            summary = "Use Fincher's island map to travel to the sealed temple entrance in the far east.",
            walkthroughSteps = listOf("Start. After the artifact camp is secured, ask Fincher about an unusual eastern ruin.", "Steps. Use Fincher's island map to travel to the sealed temple entrance in the far east.", "Completion. Return to Fincher and report what you found."),
            reward = "100 XP",
            warnings = "",
            searchTags = listOf("Tell Fincher about the Strange Temple Entrance in the East", "Fincher", "Bandit Camp", "swamp", "Chapter 1"),
        ),
        Quest(
            id = "R1-C1-183",
            chapter = 1,
            playOrder = 183,
            title = "Treasure Hunter Wanted",
            category = "BANDIT CAMP — SIDE QUEST",
            giver = "Fincher",
            location = "Bandit Camp / swamp",
            prerequisites = "Report the eastern temple entrance to Fincher and offer to recruit skilled treasure hunters.",
            summary = "Find Olf, Dytar and Dirk in Harbour Town or the beach where they regroup.",
            walkthroughSteps = listOf("Start. Report the eastern temple entrance to Fincher and offer to recruit skilled treasure hunters.", "Steps. Find Olf, Dytar and Dirk in Harbour Town or the beach where they regroup.", "Completion. Tell them about Fincher's eastern-temple expedition and obtain Olf's agreement."),
            reward = "Story progression; exact standalone XP unconfirmed",
            warnings = "",
            searchTags = listOf("Treasure Hunter Wanted", "Fincher", "Bandit Camp", "swamp", "Chapter 1"),
        ),
        Quest(
            id = "R1-C1-184",
            chapter = 1,
            playOrder = 184,
            title = "A Job for the Triplets",
            category = "BANDIT CAMP — SIDE QUEST",
            giver = "Olf / Fincher",
            location = "Bandit Camp / swamp",
            prerequisites = "Rescue or reunite Olf, Dytar and Dirk, and complete Fincher's eastern temple scouting.",
            summary = "Return to Olf on the Bandit Camp beach.",
            walkthroughSteps = listOf("Start. Rescue or reunite Olf, Dytar and Dirk, and complete Fincher's eastern temple scouting.", "Steps. Return to Olf on the Bandit Camp beach.", "Completion. Ask the triplets to join Fincher's expedition to the Eastern Temple."),
            reward = "Story progression; exact standalone XP unconfirmed",
            warnings = "",
            searchTags = listOf("A Job for the Triplets", "Olf / Fincher", "Bandit Camp", "swamp", "Chapter 1"),
        ),
        Quest(
            id = "R1-C1-185",
            chapter = 1,
            playOrder = 185,
            title = "Talk to Master Illumar",
            category = "BANDIT CAMP — SIDE QUEST",
            giver = "Cormac",
            location = "Bandit Camp / swamp",
            prerequisites = "On the Don-aligned route, talk to Cormac at the Bandit Camp.",
            summary = "Obtain Don Esteban's diplomatic permission to enter Volcano Keep.",
            walkthroughSteps = listOf("Start. On the Don-aligned route, talk to Cormac at the Bandit Camp.", "Steps. Obtain Don Esteban's diplomatic permission to enter Volcano Keep.", "Completion. Visit Illumar inside the monastery and report the meeting."),
            reward = "50 XP",
            warnings = "Order-aligned players can be left with an unfinishable entry; avoid starting after committing to the Order.",
            searchTags = listOf("Talk to Master Illumar", "Cormac", "Bandit Camp", "swamp", "Chapter 1"),
        ),
        Quest(
            id = "R1-C1-186",
            chapter = 1,
            playOrder = 186,
            title = "Negotiating with the Volcano Keep",
            category = "BANDIT CAMP — SIDE QUEST",
            giver = "Don Esteban",
            location = "Bandit Camp / swamp",
            prerequisites = "Support Don Esteban and finish the principal Bandit Camp and Harbour Town business.",
            summary = "Take the Don's letter to Volcano Keep and present it to Mendoza's guards.",
            walkthroughSteps = listOf("Start. Support Don Esteban and finish the principal Bandit Camp and Harbour Town business.", "Steps. Take the Don's letter to Volcano Keep and present it to Mendoza's guards.", "Completion. Meet Mendoza, explain the Don's position and continue to the Chapter 2 story transition."),
            reward = "Chapter progression; precise XP may vary",
            warnings = "",
            searchTags = listOf("Negotiating with the Volcano Keep", "Don Esteban", "Bandit Camp", "swamp", "Chapter 1"),
        )
    )
}
