package com.sliverzfx.gothicquest

internal object RisenGuidePart8Data {
    val quests: List<Quest> = listOf(
        Quest(
            id = "R1-C4-001",
            chapter = 4,
            playOrder = 1,
            title = "Find all the pieces of the Titan Armour",
            category = "MAIN STORY — MASTER QUEST",
            giver = "Ursegor",
            location = "Chapter 4",
            prerequisites = "Finish Chapter 3, free Ursegor and survive Mendoza opening the Golden Gate; ask Ursegor about defeating the Titan.",
            summary = "Recover the five Titan Lord equipment pieces from the ancient temples, then take them to Eldric.",
            walkthroughSteps = listOf("Walkthrough. After Mendoza disappears through the gate and his men are defeated, speak with Ursegor. He explains that the Titan can only be fought with the Titan Lord equipment. This parent quest remains active while you complete A Piece of the Titan Armour, The Titan Boots, The Titan Hammer, The Titan Helmet and The Titan Shield.", "Completion. The quest completes when the final required equipment piece is looted.", "Related quests: Five Titan equipment quests"),
            reward = "5000 XP",
            warnings = "",
            searchTags = listOf("Find all the pieces of the Titan Armour", "Ursegor", "", "MAIN STORY — MASTER QUEST", "Five Titan equipment quests", "A. CHAPTER 4 OPENING"),
        ),
        Quest(
            id = "R1-C4-002",
            chapter = 4,
            playOrder = 2,
            title = "Get the rune from Ursegor's sarcophagus",
            category = "MAIN STORY",
            giver = "Ursegor",
            location = "Chapter 4",
            prerequisites = "Accept Ursegor's Chapter 4 instructions in the Volcano Temple and search his sarcophagus again.",
            summary = "Loot the Destroy Magic Barrier rune from Ursegor's sarcophagus.",
            walkthroughSteps = listOf("Walkthrough. After speaking with Ursegor, search his sarcophagus again. Take the Destroy Magic Barrier rune. Mages can cast it directly; non-Mages need scrolls created from the rune.", "Completion. The quest completes when the rune is taken."),
            reward = "100 XP",
            warnings = "⚠ Important: Bandits cannot use the rune directly and should speak with Illumar for Destroy Magic Barrier scrolls.",
            searchTags = listOf("Get the rune from Ursegor's sarcophagus", "Ursegor", "", "MAIN STORY", "—", "A. CHAPTER 4 OPENING"),
        ),
        Quest(
            id = "R1-C4-003",
            chapter = 4,
            playOrder = 3,
            title = "Talk to Esteban about the Volcano Temple",
            category = "SAFE — STORY",
            giver = "Ignatius / Don Esteban",
            location = "Chapter 4",
            prerequisites = "In Chapter 4 after Mendoza's betrayal, speak to Ignatius about informing Don Esteban and then visit Esteban.",
            summary = "Tell Don Esteban about Mendoza's plan and the Titan threat.",
            walkthroughSteps = listOf("Walkthrough. After speaking with Ignatius about the situation, visit Don Esteban. Explain Mendoza's plan.", "Completion. The conversation completes the quest."),
            reward = "500 XP + permanent Strength potion",
            warnings = "",
            searchTags = listOf("Talk to Esteban about the Volcano Temple", "Ignatius / Don Esteban", "", "SAFE — STORY", "—", "A. CHAPTER 4 OPENING"),
        ),
        Quest(
            id = "R1-C4-004",
            chapter = 4,
            playOrder = 4,
            title = "Talk to Carlos about the Volcano Temple",
            category = "SAFE — STORY",
            giver = "Ignatius / Carlos",
            location = "Chapter 4",
            prerequisites = "In Chapter 4 after Mendoza's betrayal, ask Ignatius about Carlos and return to the Commandant in Harbour Town.",
            summary = "Tell Carlos about Mendoza's betrayal and plans.",
            walkthroughSteps = listOf("Walkthrough. Visit Carlos in Harbour Town and explain what happened inside the Volcano Temple.", "Completion. Carlos acknowledges Mendoza's corruption and gives assistance."),
            reward = "500 XP + Berserker scrolls",
            warnings = "⚠ Important: Warriors of the Order may also receive the Inquisitor promotion here.",
            searchTags = listOf("Talk to Carlos about the Volcano Temple", "Ignatius / Carlos", "", "SAFE — STORY", "—", "A. CHAPTER 4 OPENING"),
        ),
        Quest(
            id = "R1-C4-005",
            chapter = 4,
            playOrder = 5,
            title = "Find a mage who can help you",
            category = "BANDIT ONLY",
            giver = "Ursegor → Illumar",
            location = "Chapter 4",
            prerequisites = "You are a non-mage (especially Bandit) in Chapter 4 and have Ursegor's Destroy Magic Barrier rune; take it to Illumar for scrolls.",
            summary = "Ask Illumar to create Destroy Magic Barrier scrolls from Ursegor's rune.",
            walkthroughSteps = listOf("Walkthrough. Bandits cannot cast runes. Go to Illumar in the Hall of Flames and show him the barrier rune. Have him create the scrolls; established walkthroughs note that five are enough for the mandatory barriers if none are wasted.", "Completion. Receive the Destroy Magic Barrier scrolls.", "Related quests: Titan equipment temples"),
            reward = "200 XP; Destroy Magic Barrier scrolls",
            warnings = "",
            searchTags = listOf("Find a mage who can help you", "Illumar", "", "BANDIT ONLY", "Titan equipment temples", "A. CHAPTER 4 OPENING"),
        ),
        Quest(
            id = "R1-C4-006",
            chapter = 4,
            playOrder = 6,
            title = "Master of Magic",
            category = "MAGE ONLY",
            giver = "Ignatius",
            location = "Chapter 4",
            prerequisites = "Mage faction only: reach Chapter 4 and report Mendoza's betrayal to Ignatius, then attend the promotion ritual.",
            summary = "Accept promotion to Master of Magic after reporting Mendoza's betrayal.",
            walkthroughSteps = listOf("Walkthrough. Speak with Ignatius, then follow him into the Hall of Flames for the promotion ritual.", "Completion. Complete the oath/ritual."),
            reward = "1000 XP + Heavy Mage Robes",
            warnings = "",
            searchTags = listOf("Master of Magic", "Ignatius", "", "MAGE ONLY", "—", "A. CHAPTER 4 OPENING"),
        ),
        Quest(
            id = "R1-C4-007",
            chapter = 4,
            playOrder = 7,
            title = "Lizard invasion!",
            category = "CHAPTER 4 — SIDE QUEST",
            giver = "Severin",
            location = "Severin's farm / camp",
            prerequisites = "Reach Chapter 4 and speak to Severin at his farm; defend the farm from the five newly arrived lizardmen.",
            summary = "Speak to Severin at the farm in Chapter 4, defeat the five attacking lizardmen, then report back to him.",
            walkthroughSteps = listOf(
                "Start. At the beginning of Chapter 4, travel to Severin's farm and speak with Severin about the renewed lizard threat.",
                "Combat. Five hostile lizardmen appear. Defeat all five around the farm; prepare for a group fight rather than pulling enemies into the nearby workers.",
                "Completion. Kill all five lizardmen, then speak with Severin again for the follow-up XP reward."
            ),
            reward = "500 XP for the quest; 100 XP for reporting back to Severin (classic walkthrough)",
            warnings = "A different 'Lizard invasion' encounter occurs near Jasmin and Henrik's hut in Chapter 3; do not confuse the two. Exact triggers can vary with earlier progress.",
            searchTags = listOf("Lizard invasion!", "Severin", "Severin's farm", "Chapter 4", "five lizardmen"),
        ),
        Quest(
            id = "R1-C4-008",
            chapter = 4,
            playOrder = 8,
            title = "A piece of the Titan Armour",
            category = "MAIN STORY — ARMOUR",
            giver = "Ursegor / Plains Temple",
            location = "Chapter 4",
            prerequisites = "Receive Ursegor's Chapter 4 equipment objective; carry Destroy Magic Barrier magic and enter the Plains Temple.",
            summary = "Enter the Plains Temple, break the magic barriers, solve the bust/altar puzzle and loot the Titan Lord breastplate.",
            walkthroughSteps = listOf("Walkthrough. Travel to the Plains Temple near Severin's farm. Enter the previously inaccessible section. Use Destroy Magic Barrier on the blue barrier. Break the thin stone wall with a pickaxe, use Telekinesis to take the bust from the high shelf, and place the correct priest bust on the altar to open the stone door. Continue to the illuminated sarcophagus chamber.", "Completion. Loot the Titan Lord armour from the sarcophagus."),
            reward = "1000 XP",
            warnings = "⚠ Important: The same chamber also contains a Titan staff, useful for staff users but not required for the master quest.",
            searchTags = listOf("A piece of the Titan Armour", "Ursegor / Plains Temple", "", "MAIN STORY — ARMOUR", "—", "B. TITAN LORD ARMOUR — PLAINS TEMPLE"),
        ),
        Quest(
            id = "R1-C4-009",
            chapter = 4,
            playOrder = 9,
            title = "To the big waterfall with Patty",
            category = "OPTIONAL ESCORT / STORY",
            giver = "Patty",
            location = "Chapter 4",
            prerequisites = "Rescue Patty and complete her pirate storyline earlier; during Chapter 4 find her on the road to the western waterfall.",
            summary = "If Patty survived Chapter 2, meet her on the west coast and escort her to the large waterfall.",
            walkthroughSteps = listOf("Walkthrough. Patty waits in the western region near your previous Romanov adventure. Agree to travel together. Clear the Lizardmen on the route. At the large waterfall she stays outside to guard the entrance.", "Completion. Reach the waterfall entrance with Patty.", "Related quests: The Titan Boots"),
            reward = "400 XP",
            warnings = "⚠ Important: This quest only appears if Patty survived and her Chapter 2 storyline was completed appropriately.",
            searchTags = listOf("To the big waterfall with Patty", "Patty", "", "OPTIONAL ESCORT / STORY", "The Titan Boots", "C. TITAN BOOTS — WATERFALL TEMPLE"),
        ),
        Quest(
            id = "R1-C4-010",
            chapter = 4,
            playOrder = 10,
            title = "A piece of the Titan Armour (The Titan Boots)",
            category = "MAIN STORY — BOOTS",
            giver = "Waterfall Temple",
            location = "Chapter 4",
            prerequisites = "Receive Ursegor's equipment quest and travel to the western waterfall temple, with Patty as an optional companion.",
            summary = "Solve the hidden waterfall temple and loot the Titan Boots from the final chest.",
            walkthroughSteps = listOf("Walkthrough. Enter behind the large waterfall. Fight through ghouls and the ashbeast, then reach the ancient temple. Break the blue barrier. The temple requires multiple mechanisms: cross the spike trap with Levitation, operate the first and second winches, break the thin wall with a pickaxe, use Nautilus Transformation through the tiny opening, use a ranged attack through the crack to activate the distant winch, and lower all three layers of the final gate.", "Completion. Open the final chest and take the Titan Boots.", "Related quests: To the big waterfall with Patty"),
            reward = "1000 XP",
            warnings = "⚠ Important: Bring Levitation, Nautilus Transformation, Telekinesis/ranged capability and a pickaxe before entering.",
            searchTags = listOf("A piece of the Titan Armour (The Titan Boots)", "Waterfall Temple", "", "MAIN STORY — BOOTS", "To the big waterfall with Patty", "C. TITAN BOOTS — WATERFALL TEMPLE"),
        ),
        Quest(
            id = "R1-C4-011",
            chapter = 4,
            playOrder = 11,
            title = "The Titan Hammer",
            category = "MAIN STORY — WEAPON",
            giver = "Don's Temple",
            location = "Chapter 4",
            prerequisites = "Receive Ursegor's equipment quest and return to the ruins beneath the Don's Bandit Camp; bring Destroy Magic Barrier.",
            summary = "Explore the sealed rear section of Don Esteban's temple and recover the Titan Hammer.",
            walkthroughSteps = listOf("Walkthrough. Speak with Fincher and Cormac for information, then climb into the back section of the temple near the campfire/dancing area. Break the blue barrier and fight through undead warriors and skeletons. The temple uses two altar/bust routes; explore both sides to open the blocked central way. Continue until you reach the guardian carrying the weapon.", "Completion. Defeat the guardian and loot the Titan Hammer."),
            reward = "1000 XP",
            warnings = "⚠ Important: Do not forget to report the discovery to Cormac and Fincher for extra dialogue/rewards.",
            searchTags = listOf("The Titan Hammer", "Don's Temple", "", "MAIN STORY — WEAPON", "—", "D. TITAN HAMMER — DON ESTEBAN'S TEMPLE"),
        ),
        Quest(
            id = "R1-C4-012",
            chapter = 4,
            playOrder = 12,
            title = "The Titan Helmet",
            category = "MAIN STORY — HELMET",
            giver = "Volcano Caves",
            location = "Chapter 4",
            prerequisites = "Receive Ursegor's equipment quest and access the western volcanic caves; prepare transformation and barrier-breaking spells.",
            summary = "Enter the Volcano Caves, collect the two king busts and use them to open the helmet chamber.",
            walkthroughSteps = listOf("Walkthrough. Enter from the eastern or western Volcano Cave entrance and obtain the cave map from the skeleton/miner's body. Use Levitation to reach the winch and continue behind the blue barrier. Use Telekinesis to take the first bust without trapping yourself behind the grate. Break a thin wall with the pickaxe, fight the ashbeasts, then use Nautilus Transformation through the small hole. Defeat Mortares for the second bust. Use Telekinesis again to retrieve it safely, then place both busts on the two altars in the main chamber.", "Completion. Defeat the two Lizard Priests and take the Titan Helmet from the illuminated chamber.", "Related quests: Take care of Brogar for good"),
            reward = "1000 XP",
            warnings = "⚠ Important: Brogar can appear in these caves if he survived Chapter 1.",
            searchTags = listOf("The Titan Helmet", "Volcano Caves", "", "MAIN STORY — HELMET", "Take care of Brogar for good", "E. TITAN HELMET — VOLCANO CAVES"),
        ),
        Quest(
            id = "R1-C4-013",
            chapter = 4,
            playOrder = 13,
            title = "Take care of Brogar for good",
            category = "BANDIT CAMP / CONDITIONAL",
            giver = "Brogar",
            location = "Chapter 4",
            prerequisites = "Only if Brogar survives the earlier Bandit Camp Power Struggle chain and appears later; this outcome is conditional.",
            summary = "If Brogar survived earlier chapters, kill him when he confronts you in the Volcano Caves.",
            walkthroughSteps = listOf("Walkthrough. During the Titan Helmet route, Brogar may appear in the caves. Exhaust his dialogue, then defeat him.", "Completion. The quest completes when Brogar is killed."),
            reward = "500 XP",
            warnings = "⚠ Important: This quest does not appear if Brogar was already killed earlier.",
            searchTags = listOf("Take care of Brogar for good", "Brogar", "", "BANDIT CAMP / CONDITIONAL", "—", "E. TITAN HELMET — VOLCANO CAVES"),
        ),
        Quest(
            id = "R1-C4-014",
            chapter = 4,
            playOrder = 14,
            title = "The Titan Shield",
            category = "MAIN STORY — SHIELD",
            giver = "Eastern Volcano Caves",
            location = "Chapter 4",
            prerequisites = "Receive Ursegor's equipment quest and explore the eastern Volcano Cave; have access to Destroy Magic Barrier scrolls/rune.",
            summary = "Solve the Eastern Volcano Cave temple, collect the busts and open the final shield chamber.",
            walkthroughSteps = listOf("Walkthrough. Enter the eastern Volcano Caves, get the cave map from the skeleton and proceed past the ashbeast to the blue barrier. Inside, read the map column and explore the two routes for the required busts. Use levers to disable traps, a pickaxe on thin walls, Nautilus Transformation for the small opening, and Telekinesis where necessary to avoid being trapped by grates. Place the recovered busts on the altars to open the last section.", "Completion. Reach the final chamber and take the Titan Shield."),
            reward = "1000 XP",
            warnings = "⚠ Important: This is another utility-heavy temple; carry Levitation, Nautilus Transformation, Telekinesis and a pickaxe.",
            searchTags = listOf("The Titan Shield", "Eastern Volcano Caves", "", "MAIN STORY — SHIELD", "—", "F. TITAN SHIELD — EASTERN VOLCANO CAVES"),
        ),
        Quest(
            id = "R1-C4-015",
            chapter = 4,
            playOrder = 15,
            title = "Eldric must reforge the Titan Lord Armour",
            category = "MAIN STORY",
            giver = "Eldric",
            location = "Chapter 4",
            prerequisites = "Gather all five required Titan Lord equipment pieces, then return to druid Eldric so he can reforge the armour.",
            summary = "Bring all Titan Lord pieces to Eldric and follow him to his druid shrine.",
            walkthroughSteps = listOf("Walkthrough. Once all required pieces are collected, return to Eldric. Tell him you have the complete equipment and need its magic restored. Follow him to the nearby druid shrine and watch the ritual.", "Completion. Eldric reforges/restores the Titan Lord equipment."),
            reward = "500 XP for Eldric reforging the Titan Lord armour",
            warnings = "⚠ Important: Equip the full Titan Lord set before returning to the volcano.",
            searchTags = listOf("Eldric must reforge the Titan Lord Armour", "Eldric", "", "MAIN STORY", "—", "G. TITAN ARMOUR REFORGING"),
        ),
        Quest(
            id = "R1-C4-016",
            chapter = 4,
            playOrder = 16,
            title = "The Inquisitor is dead!",
            category = "MAIN STORY — BOSS",
            giver = "Ursegor / Mendoza",
            location = "Chapter 4",
            prerequisites = "Reforge the complete Titan Lord set with Eldric and return to the Golden Gate where Mendoza is waiting.",
            summary = "Return to Ursegor in full Titan equipment, confront Mendoza and kill him.",
            walkthroughSteps = listOf("Walkthrough. Go back to the Golden Gate and speak with Ursegor. He confirms that you are ready. Approach Mendoza. He explains that the Ocular is required to perceive the Titan and refuses to surrender it. Fight him.", "Completion. Kill Mendoza and loot his body.", "Related quests: The ocular"),
            reward = "1000 XP",
            warnings = "⚠ Important: Loot everything from Mendoza, especially the Ocular and Ursegor's skull.",
            searchTags = listOf("The Inquisitor is dead!", "Ursegor / Mendoza", "", "MAIN STORY — BOSS", "The ocular", "H. FINAL RETURN TO THE VOLCANO"),
        ),
        Quest(
            id = "R1-C4-017",
            chapter = 4,
            playOrder = 17,
            title = "Retrieve the Ocular",
            category = "MAIN STORY — KEY ITEM",
            giver = "Mendoza (loot after defeat)",
            location = "Chapter 4",
            prerequisites = "Defeat Mendoza at the Golden Gate and search his body for the Ocular needed to continue.",
            summary = "Loot Mendoza after defeating him and recover the Ocular needed to proceed through the Golden Gate.",
            walkthroughSteps = listOf("Walkthrough. After defeating Mendoza, search his body and take the Ocular. He also carries Ursegor's skull.", "Completion. Taking the Ocular completes the quest."),
            reward = "200 XP",
            warnings = "⚠ Important: Return Ursegor's skull to the empty altar to reopen the final gate.",
            searchTags = listOf("The ocular", "Mendoza", "", "MAIN STORY — KEY ITEM", "—", "H. FINAL RETURN TO THE VOLCANO"),
        ),
    )

    val notes: List<RisenGuideNote> = listOf(
        RisenGuideNote(4, 1, "Chapter 4 overview", listOf("Chapter 4 begins immediately after Mendoza passes through the Golden Gate and orders his followers to attack you. Ursegor then explains that you must recover the Titan Lord equipment from ancient temples across Faranga. The main hunt consists of five equipment quests: armour, boots, hammer, helmet and shield. After all pieces are collected, Eldric restores their magic, you return to Ursegor, defeat Mendoza for the Ocular and enter the final Titan arena.", "Endgame warning: Once you have the reforged Titan Lord equipment and return to the Golden Gate, finish any remaining exploration or side content before opening the final arena.")),
        RisenGuideNote(4, 1, "A. CHAPTER 4 OPENING", listOf()),
        RisenGuideNote(4, 8, "B. TITAN LORD ARMOUR — PLAINS TEMPLE", listOf()),
        RisenGuideNote(4, 9, "C. TITAN BOOTS — WATERFALL TEMPLE", listOf()),
        RisenGuideNote(4, 11, "D. TITAN HAMMER — DON ESTEBAN'S TEMPLE", listOf()),
        RisenGuideNote(4, 12, "E. TITAN HELMET — VOLCANO CAVES", listOf()),
        RisenGuideNote(4, 14, "F. TITAN SHIELD — EASTERN VOLCANO CAVES", listOf()),
        RisenGuideNote(4, 15, "G. TITAN ARMOUR REFORGING", listOf()),
        RisenGuideNote(4, 16, "H. FINAL RETURN TO THE VOLCANO", listOf()),
        RisenGuideNote(4, 18, "I. FINAL TITAN BATTLE — GUIDE SECTION, NOT A JOURNAL QUEST", listOf("The final Titan encounter does not need a fabricated quest heading. Equip the Titan Lord equipment and carry the Ocular. Place Ursegor's skull back on the altar and enter the Titan arena. Once you cross into the arena, there is no meaningful reason to return, so make your final save first.", "Keep moving. Individual floor tiles periodically light up and collapse; do not stand still on a marked tile.", "When the Titan channels its sweeping energy beam, run sideways around the arena rather than directly away from it.", "If the Titan releases a close-range energy wave, jump over the wave.", "The key attack is the Titan's white magic missiles. Raise the Titan Shield and reflect the missiles back at him.", "When reflected missiles stun the Titan, rush in and strike with the Titan Hammer.", "Retreat immediately after the hit and repeat the shield-reflect-stun-hammer cycle.", "The Titan usually requires roughly five successful Hammer hits before the ending sequence triggers.")),
        RisenGuideNote(4, 18, "CHAPTER 4 / GAME COMPLETION CHECKLIST", listOf("Destroy Magic Barrier rune or enough scrolls were obtained.", "The Titan Lord armour/breastplate was recovered.", "The Titan Boots were recovered from the waterfall temple.", "The Titan Hammer was recovered from Don Esteban's temple.", "The Titan Helmet was recovered from the Volcano Caves.", "The Titan Shield was recovered from the Eastern Volcano Caves.", "Find all the pieces of the Titan Armour completed.", "Eldric reforged the complete Titan Lord equipment.", "Any remaining island side quests/exploration were finished before the final return.", "Mendoza was defeated and looted.", "The Ocular and Ursegor's skull were recovered.", "A permanent final save exists before entering the Titan arena.", "The Titan was defeated by reflecting missiles with the shield and attacking with the hammer.")),
    )
}
