package com.sliverzfx.gothicquest

internal object Risen2GuidePart7Data {
    val quests: List<Quest> = listOf(
        Quest(
            id = "R2-C3-057",
            chapter = 3,
            playOrder = 57,
            title = "Steelbeard's Ghost",
            category = "MAIN STORY — ALTERNATE INFORMATION ROUTE",
            giver = "Chani or Admiral Alvarez",
            location = "Chapter 3",
            prerequisites = "",
            summary = "Reach the Isle of the Dead, complete The Skull Sceptre and speak with Steelbeard's Ghost.",
            walkthroughSteps = listOf("Walkthrough. If you sided with the Natives, Chani can point you toward the Isle of the Dead after the Earth Titan. If you sided with the Inquisition, this route generally opens only after all four Titan Artefacts and the later Alvarez conversation. On the Isle, speak with Tao and complete the underworld ritual before summoning or speaking with Steelbeard.", "Completion. Complete The Skull Sceptre and finish the conversation with Steelbeard's Ghost.", "Related: The Journey to the Underworld / The Skull Sceptre"),
            reward = "500 Glory",
            warnings = "⚠ Important: Native players can do this very early in Chapter 3, but the island is much more dangerous than Tacarigua/Sword Coast.",
            searchTags = listOf("Steelbeard's Ghost", "A. STEELBEARD'S GHOST — NATIVE EARLY ROUTE / LATE UNIVERSAL ROUTE", "Chani or Admiral Alvarez", "Chapter 3"),
        ),
        Quest(
            id = "R2-C3-058",
            chapter = 3,
            playOrder = 58,
            title = "The Journey to the Underworld",
            category = "ISLE OF THE DEAD — MAIN STORY",
            giver = "Tao",
            location = "Chapter 3",
            prerequisites = "",
            summary = "Complete Tao's ritual and drink the Potion of False Death to enter the spirit world.",
            walkthroughSteps = listOf("Walkthrough. At the Isle of the Dead entrance, speak with Tao and exhaust his dialogue. Complete the required ritual/preparation quests, obtain the potion and drink it.", "Completion. Your character crosses into the underworld/spirit version of the island."),
            reward = "Story Glory",
            warnings = "⚠ Important: Save before drinking the potion so you have a clean return point.",
            searchTags = listOf("The Journey to the Underworld", "A. STEELBEARD'S GHOST — NATIVE EARLY ROUTE / LATE UNIVERSAL ROUTE", "Tao", "Chapter 3"),
        ),
        Quest(
            id = "R2-C3-059",
            chapter = 3,
            playOrder = 59,
            title = "The Skull Sceptre",
            category = "ISLE OF THE DEAD — MAIN STORY",
            giver = "Tao / Isle of the Dead",
            location = "Chapter 3",
            prerequisites = "",
            summary = "Complete the spirit-world tasks needed to assemble/obtain the Skull Sceptre.",
            walkthroughSteps = listOf("Walkthrough. Work through the Isle's ghost quests and collect the required components or blessings as directed by Tao. The sceptre is the key item used to summon or access Steelbeard's Ghost.", "Completion. Obtain the Skull Sceptre and use it as required.", "Related: Steelbeard's Ghost"),
            reward = "Quest Glory",
            warnings = "⚠ Important: Natives retain access to the Skull Sceptre for later ghost summoning according to the main walkthrough references.",
            searchTags = listOf("The Skull Sceptre", "A. STEELBEARD'S GHOST — NATIVE EARLY ROUTE / LATE UNIVERSAL ROUTE", "Tao / Isle of the Dead", "Chapter 3"),
        ),
        Quest(
            id = "R2-C3-060",
            chapter = 3,
            playOrder = 60,
            title = "Talk to Steelbeard's Ghost",
            category = "NATIVES ONLY — OPTIONAL STORY",
            giver = "Patty / Steelbeard",
            location = "Chapter 3",
            prerequisites = "",
            summary = "Before completing Steelbeard's Artefact, speak with Steelbeard's Ghost on the Isle of the Dead.",
            walkthroughSteps = listOf("Walkthrough. Sail to the Isle before finishing Steelbeard's Artefact, complete Steelbeard's Ghost and bring Patty's story into the conversation where applicable.", "Completion. Finish the ghost conversation.", "Related: Steelbeard's Artefact"),
            reward = "200 Glory",
            warnings = "⚠ Important: This quest is cancelled if Steelbeard's Artefact is completed first and is not available on the Inquisition route.",
            searchTags = listOf("Talk to Steelbeard's Ghost", "A. STEELBEARD'S GHOST — NATIVE EARLY ROUTE / LATE UNIVERSAL ROUTE", "Patty / Steelbeard", "Chapter 3"),
        ),
        Quest(
            id = "R2-C3-061",
            chapter = 3,
            playOrder = 61,
            title = "The Split Soul",
            category = "OPTIONAL — COMPANION QUEST",
            giver = "Bones",
            location = "Chapter 3",
            prerequisites = "",
            summary = "Recruit Bones in Maracai Bay, then reunite him with his Confused Ghost on the Isle of the Dead.",
            walkthroughSteps = listOf("Walkthrough. First complete Unwanted Sermon in Maracai Bay and recruit Bones. Ask why he believes he is dead. Later, after entering the spirit world on the Isle of the Dead, find the Confused Ghost in/near the Thief's Temple and speak with him.", "Completion. Return to Bones after delivering the afterlife message.", "Related: A message from the Afterlife"),
            reward = "200 Glory",
            warnings = "⚠ Important: This quest spans Maracai Bay and the Isle of the Dead, so do not expect to finish it the moment you receive it.",
            searchTags = listOf("The Split Soul", "B. ISLE OF THE DEAD SIDE CONTENT", "Bones", "Chapter 3"),
        ),
        Quest(
            id = "R2-C3-062",
            chapter = 3,
            playOrder = 62,
            title = "A message from the World of the Living",
            category = "OPTIONAL — UNDERWORLD",
            giver = "Spirit-world NPC",
            location = "Chapter 3",
            prerequisites = "",
            summary = "Carry a message between the living world and a ghost on the Isle of the Dead.",
            walkthroughSteps = listOf("Walkthrough. Accept the message while in the appropriate realm, then speak with the named counterpart after crossing between living/spirit states as instructed.", "Completion. Deliver the message."),
            reward = "Quest Glory",
            warnings = "",
            searchTags = listOf("A message from the World of the Living", "B. ISLE OF THE DEAD SIDE CONTENT", "Spirit-world NPC", "Chapter 3"),
        ),
        Quest(
            id = "R2-C3-063",
            chapter = 3,
            playOrder = 63,
            title = "A message from the Afterlife",
            category = "OPTIONAL — UNDERWORLD",
            giver = "Confused Ghost / Bones",
            location = "Chapter 3",
            prerequisites = "",
            summary = "Speak with Bones' ghostly counterpart and carry his message back to Bones.",
            walkthroughSteps = listOf("Walkthrough. While in the spirit world, locate the Confused Ghost who resembles Bones. Exhaust his dialogue.", "Completion. Return to the living world and speak with Bones.", "Related: The Split Soul"),
            reward = "Quest Glory",
            warnings = "",
            searchTags = listOf("A message from the Afterlife", "B. ISLE OF THE DEAD SIDE CONTENT", "Confused Ghost / Bones", "Chapter 3"),
        ),
        Quest(
            id = "R2-C3-064",
            chapter = 3,
            playOrder = 64,
            title = "Following Garcia's Trail",
            category = "MAIN STORY — INVESTIGATION",
            giver = "Caldera council / archives",
            location = "Chapter 3",
            prerequisites = "",
            summary = "Gain access to the archives, read the High Council Rulings and discover that Garcia is in Maracai Bay.",
            walkthroughSteps = listOf("Walkthrough. Back in Caldera, work through the council/clerks route until you can enter the archives. The Voodoo route can use Mauregato possession; non-Voodoo players can use the formal messenger/forged-pass route. Read the High Council Rulings in the archives.", "Completion. The quest completes and Maracai Bay becomes the next Garcia destination.", "Related: Access to the Archives / Maracai Bay"),
            reward = "Story Glory",
            warnings = "⚠ Important: Steal/read any incriminating documents you need before advancing the council sequence, because some access opportunities are temporary.",
            searchTags = listOf("Following Garcia's Trail", "C. FOLLOWING GARCIA'S TRAIL — CALDERA / MARACAI SETUP", "Caldera council / archives", "Chapter 3"),
        ),
        Quest(
            id = "R2-C3-065",
            chapter = 3,
            playOrder = 65,
            title = "Access to the Archives",
            category = "MAIN STORY — ACCESS",
            giver = "Caldera officials",
            location = "Chapter 3",
            prerequisites = "",
            summary = "Secure permission or a disguise/pass to enter the archives.",
            walkthroughSteps = listOf("Walkthrough. Use your faction's available path: Voodoo players can manipulate Mauregato; others can complete the messenger route with attire and signet ring. Enter the cathedral/archive area legitimately or through the forged access chain.", "Completion. Reach the archive reading room."),
            reward = "Quest Glory",
            warnings = "",
            searchTags = listOf("Access to the Archives", "C. FOLLOWING GARCIA'S TRAIL — CALDERA / MARACAI SETUP", "Caldera officials", "Chapter 3"),
        ),
        Quest(
            id = "R2-C3-066",
            chapter = 3,
            playOrder = 66,
            title = "Maracai Bay",
            category = "MAIN STORY — GARCIA HUNT",
            giver = "Trigger quest",
            location = "Chapter 3",
            prerequisites = "",
            summary = "Sail to Maracai Bay, expose Garcia's masquerade and kill him.",
            walkthroughSteps = listOf("Walkthrough. After reading High Council Rulings, set course for Maracai Bay. Investigate the settlement, rescue Angus and/or work with Osamu to expose the false Corrientes identity. Once Garcia's Masquerade Uncovered is complete, pursue Garcia to his true position and kill him.", "Completion. Garcia dies and the Maracai Bay hunt resolves.", "Related: Garcia's Masquerade Uncovered / Search Garcia's Possessions"),
            reward = "500 Glory",
            warnings = "⚠ Important: If Garcia's masquerade is exposed by rescuing Angus, Garcia's final position can differ from the alternate Osamu route.",
            searchTags = listOf("Maracai Bay", "C. FOLLOWING GARCIA'S TRAIL — CALDERA / MARACAI SETUP", "Automatic / archives", "Chapter 3"),
        ),
        Quest(
            id = "R2-C3-067",
            chapter = 3,
            playOrder = 67,
            title = "Garcia's Masquerade Uncovered",
            category = "MAIN STORY — INVESTIGATION",
            giver = "Osamu / Angus route",
            location = "Chapter 3",
            prerequisites = "",
            summary = "Prove that Corrientes is Garcia, either through Osamu's Blood of the Ancestors route or by rescuing Angus.",
            walkthroughSteps = listOf("Walkthrough. Talk with Osamu after finding the secret entrance and confronting Corrientes, or complete Angus is Rescued. The false identity collapses once enough evidence is revealed.", "Completion. Garcia is exposed.", "Related: The Blood of the Ancestors / Angus is Rescued"),
            reward = "200 Glory",
            warnings = "⚠ Important: Completing this can cancel The Deserter.",
            searchTags = listOf("Garcia's Masquerade Uncovered", "D. MARACAI BAY — GARCIA", "Osamu / Angus route", "Chapter 3"),
        ),
        Quest(
            id = "R2-C3-068",
            chapter = 3,
            playOrder = 68,
            title = "The Blood of the Ancestors",
            category = "MAIN STORY — PURSUIT",
            giver = "Osamu",
            location = "Chapter 3",
            prerequisites = "",
            summary = "Use Osamu's Blood of the Ancestors to pass the wall of fire and pursue Garcia's men.",
            walkthroughSteps = listOf("Walkthrough. After Garcia's deception is exposed through Osamu, receive the Blood of the Ancestors. Travel to the southeast cave, kill Egas and Palomo, then pass through the magical fire barrier. Fight the Ghoul and Grave Spider inside and use the upper button/door mechanism to reopen access for companions.", "Completion. Pass through the barrier and continue Garcia's pursuit."),
            reward = "Quest Glory",
            warnings = "",
            searchTags = listOf("The Blood of the Ancestors", "D. MARACAI BAY — GARCIA", "Osamu", "Chapter 3"),
        ),
        Quest(
            id = "R2-C3-069",
            chapter = 3,
            playOrder = 69,
            title = "Search Garcia's Possessions",
            category = "MAIN STORY — ARTEFACT INFORMATION",
            giver = "Patty / Garcia route",
            location = "Chapter 3",
            prerequisites = "",
            summary = "Board Garcia's ship, read his Logbook and take the map in his cabin.",
            walkthroughSteps = listOf("Walkthrough. Use the rowboat on the Maracai coast to reach Garcia's ship. Complete Seize Garcia's Ship by defeating his thugs. Enter Garcia's cabin and read Garcia's Logbook on the desk; take the nearby treasure map too.", "Completion. Return to Patty after reading the logbook.", "Related: Seize Garcia's Ship / Garcia's Logbook / The Password"),
            reward = "Story Glory",
            warnings = "⚠ Important: This route can replace Steelbeard's Ghost as the source for the password/location needed for Steelbeard's Artefact.",
            searchTags = listOf("Search Garcia's Possessions", "D. MARACAI BAY — GARCIA", "Patty / Garcia route", "Chapter 3"),
        ),
        Quest(
            id = "R2-C3-070",
            chapter = 3,
            playOrder = 70,
            title = "Seize Garcia's Ship",
            category = "MAIN STORY — COMBAT",
            giver = "Garcia",
            location = "Chapter 3",
            prerequisites = "",
            summary = "Defeat Garcia's pirates aboard his ship.",
            walkthroughSteps = listOf("Walkthrough. Reach the ship using the rowboat. Bring a companion if possible because the group fight is difficult.", "Completion. Kill or defeat the hostile crew and gain access to Garcia's cabin.", "Related: Search Garcia's Possessions"),
            reward = "Combat Glory",
            warnings = "",
            searchTags = listOf("Seize Garcia's Ship", "D. MARACAI BAY — GARCIA", "Automatic / Garcia", "Chapter 3"),
        ),
        Quest(
            id = "R2-C3-071",
            chapter = 3,
            playOrder = 71,
            title = "Garcia's Logbook",
            category = "MAIN STORY — DOCUMENT",
            giver = "Garcia's cabin",
            location = "Chapter 3",
            prerequisites = "",
            summary = "Read Garcia's Logbook to learn the hidden-gate password and treasure location.",
            walkthroughSteps = listOf("Walkthrough. After seizing the ship, enter Garcia's cabin and read the logbook on the desk.", "Completion. The document reveals the information needed for Open Sesame / The Password and Garcia's Treasure.", "Related: The Password / Open Sesame / Garcia's Treasure"),
            reward = "Quest Glory",
            warnings = "",
            searchTags = listOf("Garcia's Logbook", "D. MARACAI BAY — GARCIA", "Garcia's cabin", "Chapter 3"),
        ),
        Quest(
            id = "R2-C3-072",
            chapter = 3,
            playOrder = 72,
            title = "Steelbeard's Artefact",
            category = "MAIN STORY — TITAN ARTEFACT",
            giver = "Booze / Admiral Alvarez / Garcia route",
            location = "Chapter 3",
            prerequisites = "",
            summary = "Learn the world's best hiding place, open the hidden Antigua gate and recover Steelbeard's artefact.",
            walkthroughSteps = listOf("Walkthrough. Ask Booze or Admiral Alvarez about Steelbeard's hiding habits, or use the Garcia/Steelbeard's Ghost information path. The key destination is the hidden gate behind Antigua's large waterfall. Learn the password from Garcia's Logbook or Steelbeard's Ghost, then return to Antigua and open the gate.", "Completion. Reach Garcia's Treasure and take Steelbeard's Titan Artefact.", "Related: The World's Best Hiding Place / The Password / Open Sesame / Garcia's Treasure"),
            reward = "1000 Glory",
            warnings = "⚠ Important: If you want Talk to Steelbeard's Ghost on the Native route, complete that BEFORE taking Steelbeard's Artefact.",
            searchTags = listOf("Steelbeard's Artefact", "E. STEELBEARD'S ARTEFACT", "Booze / Admiral Alvarez / Garcia route", "Chapter 3"),
        ),
        Quest(
            id = "R2-C3-073",
            chapter = 3,
            playOrder = 73,
            title = "The World's Best Hiding Place",
            category = "MAIN STORY — CLUE",
            giver = "Booze or Admiral Alvarez",
            location = "Chapter 3",
            prerequisites = "",
            summary = "Ask where Steelbeard would hide something no pirate could find.",
            walkthroughSteps = listOf("Walkthrough. Speak with Booze on Tacarigua or Admiral Alvarez on Antigua about Steelbeard's habits and artefact hiding place.", "Completion. The clue points you toward Antigua's hidden waterfall gate."),
            reward = "500 Glory",
            warnings = "",
            searchTags = listOf("The World's Best Hiding Place", "E. STEELBEARD'S ARTEFACT", "Booze or Admiral Alvarez", "Chapter 3"),
        ),
        Quest(
            id = "R2-C3-074",
            chapter = 3,
            playOrder = 74,
            title = "Open Sesame",
            category = "MAIN STORY — ACCESS",
            giver = "Strange Gate",
            location = "Chapter 3",
            prerequisites = "",
            summary = "Return to Antigua's waterfall gate and say the learned password.",
            walkthroughSteps = listOf("Walkthrough. Travel behind the large waterfall, approach the Strange Gate and use the password learned from Garcia's Logbook/Steelbeard's Ghost.", "Completion. The gate opens."),
            reward = "200 Glory",
            warnings = "⚠ Important: The commonly documented password is learned in-game; the app should display it only inside the quest solution, not as an exploration spoiler before activation.",
            searchTags = listOf("Open Sesame", "E. STEELBEARD'S ARTEFACT", "Strange Gate", "Chapter 3"),
        ),
        Quest(
            id = "R2-C3-075",
            chapter = 3,
            playOrder = 75,
            title = "Garcia's Treasure",
            category = "MAIN STORY — TREASURE",
            giver = "Hidden Antigua cave",
            location = "Chapter 3",
            prerequisites = "",
            summary = "Pass through the hidden gate and dig up Garcia/Steelbeard's treasure.",
            walkthroughSteps = listOf("Walkthrough. Follow the passage beyond the opened gate to the outside treasure area. Find the large red X and use a shovel.", "Completion. Loot the buried treasure and take Steelbeard's Artefact."),
            reward = "Quest Glory + Titan Artefact",
            warnings = "",
            searchTags = listOf("Garcia's Treasure", "E. STEELBEARD'S ARTEFACT", "Hidden Antigua cave", "Chapter 3"),
        ),
    )

    val notes: List<RisenGuideNote> = listOf(
        RisenGuideNote(3, 57, "How this Part branches", listOf("Chapter 3 no longer has one fixed island order. The Natives route can unlock Steelbeard's Ghost on the Isle of the Dead much earlier, while the Inquisition route usually learns the Isle's relevance only after the four Titan Artefacts are assembled. Maracai Bay provides the alternative Garcia/logbook route to the same Steelbeard's Artefact information.", "Best completionist method: Do both Maracai Bay and the Isle of the Dead before the final Water Temple sequence. That preserves the maximum story, companions and side quests.")),
        RisenGuideNote(3, 57, "A. STEELBEARD'S GHOST — NATIVE EARLY ROUTE / LATE UNIVERSAL ROUTE", listOf()),
        RisenGuideNote(3, 61, "B. ISLE OF THE DEAD SIDE CONTENT", listOf()),
        RisenGuideNote(3, 64, "C. FOLLOWING GARCIA'S TRAIL — CALDERA / MARACAI SETUP", listOf()),
        RisenGuideNote(3, 67, "D. MARACAI BAY — GARCIA", listOf()),
        RisenGuideNote(3, 72, "E. STEELBEARD'S ARTEFACT", listOf()),
        RisenGuideNote(3, 74, "The Password — continued quest guidance", listOf("Quick solution: Learn the password to Antigua's waterfall gate from Garcia's Logbook or Steelbeard's Ghost.", "Walkthrough. If you already inspected the gate behind Antigua's large waterfall, this quest is active. Read Garcia's Logbook on his Maracai Bay ship, or on the Native route ask Steelbeard's Ghost.", "Completion. Learning the password completes the quest.", "Quest giver: Strange Gate / Garcia's Logbook", "Status: MAIN STORY — PASSWORD", "Area: Chapter 3", "Reward: 100 Glory")),
        RisenGuideNote(3, 76, "F. FOUR TITAN ARTEFACTS — CHAPTER 3 CHECKPOINT", listOf("By the end of this open-seas phase, the story expects four Titan Artefacts to be assembled. Steelbeard's Artefact is one of the crucial pieces, while Slayne's Sacrificial Knife and other artefacts come from the parallel island arcs already completed or still active.")),
        RisenGuideNote(3, 76, "The Water Temple — continued quest guidance", listOf("Quick solution: After obtaining all four Titan Artefacts, learn the Water Temple's location.", "Walkthrough. With all four artefacts, speak with Admiral Alvarez. Native players who completed Steelbeard's Ghost can alternatively get the location directly from Steelbeard's Ghost.", "Completion. The final Water Temple route becomes available.", "⚠ Important: Do NOT rush into the Water Temple if you still want to finish Chapter 3 side quests, companion quests or exploration.", "Quest giver: Admiral Alvarez / Steelbeard's Ghost", "Status: LATE CHAPTER 3 — FINAL ROUTE UNLOCK", "Area: Chapter 3", "Reward: Major story progression", "Related: Defeat the Kraken / final chapter")),
        RisenGuideNote(3, 76, "PART III COMPLETION CHECKLIST", listOf("Steelbeard's Ghost was completed if available/desired.", "The Journey to the Underworld and Skull Sceptre chain were completed.", "Talk to Steelbeard's Ghost was completed before Steelbeard's Artefact if playing the Native route.", "Bones was recruited and The Split Soul was completed or intentionally left active until the Isle visit.", "Following Garcia's Trail and Access to the Archives were completed.", "Maracai Bay was fully investigated.", "Garcia's Masquerade was uncovered.", "Garcia was killed.", "Garcia's ship was seized and his Logbook read.", "The Password was learned.", "Antigua's hidden waterfall gate was opened.", "Garcia's Treasure / Steelbeard's Artefact was recovered.", "All four Titan Artefacts are accounted for before starting The Water Temple.", "A permanent save exists before the final Water Temple route.")),
    )
}
