package com.sliverzfx.gothicquest

/** Original PC Risen 1; local factual reference, no online content loading. */
internal object RisenToolsData {
    val codes: List<ToolReferenceEntry> = RisenCommandData.entries + RisenItemData.entries + RisenActorData.entries
    val items: List<ToolReferenceEntry> = emptyList() // Item details already belong to their code cards.
    val tips: List<ToolReferenceEntry> = listOf(
        ToolReferenceEntry("r1_tip_saving", "GETTING STARTED", "Keep several manual saves", "Save before travelling into unfamiliar areas, committing to a faction or attempting a difficult encounter. Keep an older slot so a single mistake does not become your only saved state.", source = "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/40300/manuals/GfW%20Risen%20Manual%20US%20PRINT.pdf"),
        ToolReferenceEntry("r1_tip_danger", "EXPLORATION", "Come back to strong enemies", "Early encounters are not all meant to be won immediately. Retreat from enemies that overwhelm you, train and improve your equipment, then return. Many animals display a threat animation before attacking.", source = "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/40300/manuals/GfW%20Risen%20Manual%20US%20PRINT.pdf"),
        ToolReferenceEntry("r1_tip_train", "CHARACTER BUILDING", "Train a focused character", "Level gains award learning points. Spend them with trainers on the attributes and skills your chosen weapons need. Strength supports melee damage; dexterity supports ranged damage and bow access.", source = "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/40300/manuals/GfW%20Risen%20Manual%20US%20PRINT.pdf"),
        ToolReferenceEntry("r1_tip_bonuses", "CHARACTER BUILDING", "Plan permanent bonuses", "Trainers have limits. Save permanent attribute potions and valuable plants until you have finished the relevant training where practical. Bookstands and stone tablets increase wisdom; ogre roots benefit strength.", source = "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/40300/manuals/GfW%20Risen%20Manual%20US%20PRINT.pdf"),
        ToolReferenceEntry("r1_tip_wisdom", "MAGIC", "Wisdom and seals", "Wisdom supports understanding magical seals. Rune use requires the appropriate seal; wisdom alone does not grant the rune or replace seal training.", source = "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/40300/manuals/GfW%20Risen%20Manual%20US%20PRINT.pdf"),
        ToolReferenceEntry("r1_tip_crystals", "MAGIC", "Develop crystal magic", "Magic Bullet, Fireball and Frost each have ten training levels. Choose the spell you intend to use and improve that discipline rather than spreading points without a plan.", source = "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/40300/manuals/GfW%20Risen%20Manual%20US%20PRINT.pdf"),
        ToolReferenceEntry("r1_tip_blocking", "COMBAT", "Separate blocking and attacking", "Use your configured block control to defend, then attack during an opening. Blocking and striking cannot happen simultaneously. More weapon training unlocks additional attacks and combinations.", source = "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/40300/manuals/GfW%20Risen%20Manual%20US%20PRINT.pdf"),
        ToolReferenceEntry("r1_tip_equipment", "EQUIPMENT", "Check requirements before buying", "Compare damage, required strength or dexterity, protection and skill bonuses. An item in your inventory is not automatically equipped; check the character equipment screen.", source = "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/40300/manuals/GfW%20Risen%20Manual%20US%20PRINT.pdf"),
        ToolReferenceEntry("r1_tip_factions", "FACTIONS", "Explore before choosing a faction", "Chapter 1 establishes your faction path. Bandits, Order warriors and mages offer different training and quest routes. Review the quest guide before decisions that commit you to a path.", source = "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/40300/manuals/GfW%20Risen%20Manual%20US%20PRINT.pdf"),
        ToolReferenceEntry("r1_tip_sleep", "RECOVERY", "Use beds for recovery", "A free bed can replenish health and mana when there are no nearby enemies. A claimed hut or house makes a convenient recovery stop.", source = "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/40300/manuals/GfW%20Risen%20Manual%20US%20PRINT.pdf"),
        ToolReferenceEntry("r1_tip_food", "RECOVERY", "Cook your raw food", "Carry a frying pan and use a fire or stove to prepare raw meat and fish. More elaborate meals may require a recipe, ingredients, a ladle and a cauldron; some dishes offer lasting bonuses.", source = "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/40300/manuals/GfW%20Risen%20Manual%20US%20PRINT.pdf"),
        ToolReferenceEntry("r1_tip_alchemy", "CRAFTING", "Prepare for alchemy", "Potion brewing requires the appropriate alchemy level, a recipe, its ingredients and an alchemy table. Keep empty vials, wine and useful plants instead of selling them indiscriminately.", source = "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/40300/manuals/GfW%20Risen%20Manual%20US%20PRINT.pdf"),
        ToolReferenceEntry("r1_tip_smith", "CRAFTING", "Follow the smithing steps", "Weapon smithing requires training, tools and a suitable blank. Heat it at the forge, work it on the anvil, quench it and sharpen it. Jewellery uses goldsmith tools and gems.", source = "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/40300/manuals/GfW%20Risen%20Manual%20US%20PRINT.pdf"),
        ToolReferenceEntry("r1_tip_scrolls", "CRAFTING", "Make your own scrolls", "Scroll creation requires the talent, the corresponding rune, parchment, a quill and a writing desk. Keep unusual materials such as bones or wing dust because recipes may need them.", source = "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/40300/manuals/GfW%20Risen%20Manual%20US%20PRINT.pdf"),
        ToolReferenceEntry("r1_tip_mining", "CRAFTING", "Bring a pickaxe", "Ore deposits need the prospecting skill and a pickaxe. Mining materials can support weapon and jewellery crafting.", source = "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/40300/manuals/GfW%20Risen%20Manual%20US%20PRINT.pdf"),
        ToolReferenceEntry("r1_tip_trophies", "CRAFTING", "Tools matter for animal trophies", "Trophy extraction requires its training and the relevant tool. Claws, teeth, horns and wings do not all use the same implement; check the recipe details on the related item card.", source = "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/40300/manuals/GfW%20Risen%20Manual%20US%20PRINT.pdf"),
        ToolReferenceEntry("r1_tip_locks", "THIEVERY", "Learn the required lock level", "Locks have three difficulty levels. Training and a lockpick are required; the normal sequences have four, six or eight moves. A wrong move breaks a pick. Key-only locks need their intended key.", source = "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/40300/manuals/GfW%20Risen%20Manual%20US%20PRINT.pdf"),
        ToolReferenceEntry("r1_tip_crime", "THIEVERY", "Watch who can see you", "Trespassing, stealing, threatening people and attacking their livestock can provoke reactions. Sneaking helps avoid notice but does not make every crime consequence-free.", source = "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/40300/manuals/GfW%20Risen%20Manual%20US%20PRINT.pdf"),
        ToolReferenceEntry("r1_tip_joke", "SOCIAL", "Repair some hostile reactions", "Tell Joke can help after certain offences. It does not reverse every permanent decision or faction outcome; use an earlier save if a major commitment was unintended.", source = "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/40300/manuals/GfW%20Risen%20Manual%20US%20PRINT.pdf"),
        ToolReferenceEntry("r1_tip_teleports", "EXPLORATION", "Keep teleport stones", "As the story advances, collect teleport stones for repeated journeys. They save travelling time without replacing the quests that open new routes.", source = "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/40300/manuals/GfW%20Risen%20Manual%20US%20PRINT.pdf"),
        ToolReferenceEntry("r1_tip_journal", "QUESTS", "Check the journal when stuck", "Read the active quest entries for your next lead. Follow the matching chapter in this app for the full route, especially when a task depends on your faction or another completed quest.", source = "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/40300/manuals/GfW%20Risen%20Manual%20US%20PRINT.pdf"),
    )

    fun entries(section: ToolSection): List<ToolReferenceEntry> = when (section) {
        ToolSection.MARVIN_CODES -> codes
        ToolSection.ITEMS -> items
        ToolSection.USEFUL_TIPS -> tips
    }
}
