package com.sliverzfx.gothicquest

// Chapter 1 optional/side-quest completionist appendix. Stable legacy quest IDs remain untouched.
internal object RisenGuidePart9Data {
    val quests: List<Quest> = listOf(
        Quest(
            id = "R1-C1-090",
            chapter = 1,
            playOrder = 90,
            title = "Thieving Gnomes",
            category = "ORDER — FARM",
            giver = "Severin",
            location = "Severin's Farm",
            prerequisites = "Bring Carlos's letter to Severin at his farm and offer to help defend his supplies.",
            summary = "Clear the gnomes that have been stealing from Severin's farm.",
            walkthroughSteps = listOf("Show Severin your Order letter and ask about the missing artefacts.", "Climb to the cliff overlooking the farm and defeat the six gnomes guarding the stolen supplies. Draw them toward the workers if overwhelmed.", "Report the cleared camp to Severin and collect Rufus's payment."),
            reward = "300 XP plus 50 XP and 200 gold on report",
            warnings = "",
            searchTags = listOf("Thieving Gnomes", "Severin", "Severin's Farm", "Chapter 1", "optional side quests"),
        ),
        Quest(
            id = "R1-C1-091",
            chapter = 1,
            playOrder = 91,
            title = "Overdue Situation Report",
            category = "ORDER — DELIVERY",
            giver = "Severin",
            location = "Severin's Farm → Rudolf's excavation",
            prerequisites = "Complete Severin's introduction with Carlos's letter and ask after the other Order excavation camp.",
            summary = "Check Rudolf's expedition and report its situation.",
            walkthroughSteps = listOf("Leave Severin's farm and travel west to Rudolf's excavation camp.", "Talk with Rudolf if he is alive; otherwise examine the camp and return with news of his death.", "Report the situation to Severin. This overlaps Lost Cause when Rudolf has fallen."),
            reward = "300 XP for reaching Rudolf (if alive); exact alternative outcome may differ",
            warnings = "",
            searchTags = listOf("Overdue Situation Report", "Severin", "Severin's Farm → Rudolf's excavation", "Chapter 1", "optional side quests"),
        ),
        Quest(
            id = "R1-C1-092",
            chapter = 1,
            playOrder = 92,
            title = "Lost Cause",
            category = "ORDER — REPORT",
            giver = "Rudolf",
            location = "Rudolf's camp → Severin's Farm",
            prerequisites = "Reach Rudolf's excavation camp while working for Severin and learn the situation there.",
            summary = "Report the expedition's condition to Severin.",
            walkthroughSteps = listOf("Speak with Rudolf or discover the fate of his excavation team.", "Return to Severin at the farm and deliver the news.", "Collect Severin's supplies as thanks for the report."),
            reward = "50 XP, two healing potions and a Tell Joke scroll",
            warnings = "",
            searchTags = listOf("Lost Cause", "Rudolf", "Rudolf's camp → Severin's Farm", "Chapter 1", "optional side quests"),
        ),
        Quest(
            id = "R1-C1-093",
            chapter = 1,
            playOrder = 93,
            title = "Fluttering Grave Moths",
            category = "SAFE — HUNT",
            giver = "Derry",
            location = "Severin's Farm",
            prerequisites = "Talk to Derry who looks after the pigs at Severin's farm.",
            summary = "Kill the grave moths threatening Derry's pigs.",
            walkthroughSteps = listOf("Ask Derry about insects attacking his animals.", "Travel west to the cliff and defeat all seven grave moths.", "Return to Derry for payment."),
            reward = "250 XP on clearing the moths; 50 XP and 25 gold on report",
            warnings = "",
            searchTags = listOf("Fluttering Grave Moths", "Derry", "Severin's Farm", "Chapter 1", "optional side quests"),
        ),
        Quest(
            id = "R1-C1-094",
            chapter = 1,
            playOrder = 94,
            title = "The Cursed Lords",
            category = "SAFE — EXPLORATION",
            giver = "Leon",
            location = "Island ruins / northern farm",
            prerequisites = "Find Leon at his northern farm and ask about the undead threatening him.",
            summary = "Break Leon's curse by taking the vassal rings from all six undead lords.",
            walkthroughSteps = listOf("Ask Leon about his stolen temple ring and accept his curse investigation.", "Hunt the six undead vassal lords in the ruined towers and crypts around Faranga; Lord Patroscon is in an underground crypt. Collect each lord's ring.", "Return with all six rings and report to Leon; his curse is lifted."),
            reward = "500 XP for obtaining the rings; 500 XP and three scrolls from Leon",
            warnings = "High-level undead and groups of skeletons; safe to postpone beyond Chapter 1.",
            searchTags = listOf("The Cursed Lords", "Leon", "Island ruins / northern farm", "Chapter 1", "optional side quests"),
        ),
        Quest(
            id = "R1-C1-095",
            chapter = 1,
            playOrder = 95,
            title = "Kill Lord Patroscon",
            category = "SAFE — SUBQUEST",
            giver = "Automatic near Lord Patroscon",
            location = "Island crypt near Leon",
            prerequisites = "Investigate The Cursed Lords and find Lord Patroscon in the underground crypt.",
            summary = "Destroy the undead Lord Patroscon.",
            walkthroughSteps = listOf("Enter the crypt where Lord Patroscon hides among skeletons and clear an approach.", "Defeat Lord Patroscon and loot his body, including his vassal ring.", "Tell Leon that Patroscon has been defeated."),
            reward = "300 XP for killing Patroscon plus 50 XP from Leon",
            warnings = "",
            searchTags = listOf("Kill Lord Patroscon", "Automatic near Lord Patroscon", "Island crypt near Leon", "Chapter 1", "optional side quests"),
        ),
        Quest(
            id = "R1-C1-096",
            chapter = 1,
            playOrder = 96,
            title = "The Sword Stormwind",
            category = "SAFE — EQUIPMENT",
            giver = "Discovery",
            location = "East of Harbour Town and undead lord ruins",
            prerequisites = "Explore remote chests to discover a broken legendary sword fragment.",
            summary = "Find both broken parts of the sword Stormwind.",
            walkthroughSteps = listOf("Search the cave beneath the island east of Harbour Town for the sword's base in a locked chest.", "Explore an undead vassal lord's dungeon to find the sword's tip.", "Keep both pieces for the separate Reforging Stormwind objective."),
            reward = "100 XP when both pieces are collected",
            warnings = "Some chests require Lockpicking 3 and the undead lords are difficult.",
            searchTags = listOf("The Sword Stormwind", "Discovery", "East of Harbour Town and undead lord ruins", "Chapter 1", "optional side quests"),
        ),
        Quest(
            id = "R1-C1-097",
            chapter = 1,
            playOrder = 97,
            title = "Reforging Stormwind",
            category = "SAFE — CRAFTING",
            giver = "Automatic after collecting sword pieces",
            location = "Any forge",
            prerequisites = "Collect both Stormwind fragments and learn at least level 1 Smithing.",
            summary = "Reforge Stormwind from the two broken halves.",
            walkthroughSteps = listOf("Carry both fragments to a forge with level 1 Smithing.", "Heat the weapon at the forge, shape it at the anvil, quench it and sharpen it.", "Claim the restored Stormwind sword (60 damage; 55 Strength requirement)."),
            reward = "200 XP and Stormwind sword",
            warnings = "",
            searchTags = listOf("Reforging Stormwind", "Automatic after collecting sword pieces", "Any forge", "Chapter 1", "optional side quests"),
        ),
        Quest(
            id = "R1-C1-098",
            chapter = 1,
            playOrder = 98,
            title = "The Sword Souldrinker",
            category = "SAFE — EQUIPMENT",
            giver = "Discovery",
            location = "Northeastern cliffs and northwestern beach",
            prerequisites = "Explore Faranga's remote ruins and recover one piece of Souldrinker.",
            summary = "Find both parts of the legendary two-handed sword Souldrinker.",
            walkthroughSteps = listOf("Search the northeast of the island beyond dangerous creatures for the sword base in a locked chest.", "Search a separate chest on the northwest coast below the undead ruins for the sword tip.", "Keep both fragments to reforge the sword later."),
            reward = "200 XP when both halves are found",
            warnings = "Dangerous monsters and locked chests; can be completed in a later chapter.",
            searchTags = listOf("The Sword Souldrinker", "Discovery", "Northeastern cliffs and northwestern beach", "Chapter 1", "optional side quests"),
        ),
        Quest(
            id = "R1-C1-099",
            chapter = 1,
            playOrder = 99,
            title = "Reforging Souldrinker",
            category = "SAFE — CRAFTING",
            giver = "Automatic after collecting sword pieces",
            location = "Any forge",
            prerequisites = "Collect both Souldrinker halves and learn level 3 Smithing.",
            summary = "Reforge Souldrinker into a usable two-handed sword.",
            walkthroughSteps = listOf("Bring both Souldrinker fragments to a forge.", "Perform the forge, anvil, water-trough and whetstone steps with Smithing level 3.", "Equip the restored Souldrinker if you meet its 72 Strength requirement."),
            reward = "300 XP and Souldrinker sword (75 damage)",
            warnings = "",
            searchTags = listOf("Reforging Souldrinker", "Automatic after collecting sword pieces", "Any forge", "Chapter 1", "optional side quests"),
        ),
        Quest(
            id = "R1-C1-100",
            chapter = 1,
            playOrder = 100,
            title = "A Bottle of Beer for the Drunkard",
            category = "SAFE — DELIVERY",
            giver = "Luis",
            location = "Bandit Camp outskirts",
            prerequisites = "Speak to Luis outside the Bandit Camp and offer to bring him beer.",
            summary = "Give Luis a bottle of beer and unlock his hunting-related dialogue.",
            walkthroughSteps = listOf("Speak to Luis about drinking and agree to fetch him a beer.", "Buy or loot one bottle of beer from the camp and give it to Luis.", "Finish the dialogue to earn XP; his training additionally requires completing Doug's hunting quest."),
            reward = "100 XP",
            warnings = "",
            searchTags = listOf("A Bottle of Beer for the Drunkard", "Luis", "Bandit Camp outskirts", "Chapter 1", "optional side quests"),
        ),
        Quest(
            id = "R1-C1-101",
            chapter = 1,
            playOrder = 101,
            title = "Disgusting Insects",
            category = "SAFE — HUNT",
            giver = "Ricardo",
            location = "Bandit Camp swamp digging site",
            prerequisites = "Speak with Ricardo at the entrance to the Bandit Camp about insects near the diggers.",
            summary = "Kill the four grave moths at Ricardo's excavation site.",
            walkthroughSteps = listOf("Accept Ricardo's job to remove the dangerous insects.", "Cross the wooden path to the excavation island and kill all four grave moths.", "Report the cleared site to Ricardo for payment."),
            reward = "250 XP for kills; 50 XP and 30 gold from Ricardo",
            warnings = "",
            searchTags = listOf("Disgusting Insects", "Ricardo", "Bandit Camp swamp digging site", "Chapter 1", "optional side quests"),
        ),
        Quest(
            id = "R1-C1-102",
            chapter = 1,
            playOrder = 102,
            title = "Meat for the Gang",
            category = "SAFE — DELIVERY",
            giver = "Rachel",
            location = "Bandit Camp",
            prerequisites = "Speak to Rachel after arriving at the Bandit Camp; Doug may mention the need for meat.",
            summary = "Bring ten pieces of raw meat to Rachel to feed the camp.",
            walkthroughSteps = listOf("Ask Rachel about food supplies.", "Collect ten raw meat from animals such as wolves and stingrats; Doug's hunting quest also provides some.", "Give Rachel the ten pieces and claim the reward."),
            reward = "200 XP and 30 gold",
            warnings = "",
            searchTags = listOf("Meat for the Gang", "Rachel", "Bandit Camp", "Chapter 1", "optional side quests"),
        ),
        Quest(
            id = "R1-C1-103",
            chapter = 1,
            playOrder = 103,
            title = "Rhobart Needs Weed",
            category = "SAFE — COLLECTION",
            giver = "Rhobart",
            location = "Bandit Camp swamp plateau",
            prerequisites = "Speak to Rhobart at his swamp farm about brewing beer.",
            summary = "Gather ten Bruggleweed plants for Rhobart's brewing.",
            walkthroughSteps = listOf("Agree to collect herbs for Rhobart and search the nearby plateau and swamp paths.", "Give Rhobart ten Bruggleweed plants to finish the main task.", "Optional: turn in further Bruggleweed for repeat payments."),
            reward = "50 XP and 70 gold for the first ten; subsequent herbs 5 XP and 7 gold each",
            warnings = "",
            searchTags = listOf("Rhobart Needs Weed", "Rhobart", "Bandit Camp swamp plateau", "Chapter 1", "optional side quests"),
        ),
        Quest(
            id = "R1-C1-104",
            chapter = 1,
            playOrder = 104,
            title = "Brogar's Lackey",
            category = "SAFE — DELIVERY",
            giver = "Brogar",
            location = "Bandit Camp",
            prerequisites = "Speak with Brogar at the Bandit Camp about working for him.",
            summary = "Fetch the meat Brogar demands from Rachel.",
            walkthroughSteps = listOf("Let Brogar assign his request for food.", "Ask Rachel for the cooked meat intended for Brogar; do not substitute your own fried meat.", "Bring Rachel's portion back to Brogar."),
            reward = "50 XP",
            warnings = "Giving Brogar your own fried meat instead can trigger aggression and fail the quest.",
            searchTags = listOf("Brogar's Lackey", "Brogar", "Bandit Camp", "Chapter 1", "optional side quests"),
        ),
        Quest(
            id = "R1-C1-105",
            chapter = 1,
            playOrder = 105,
            title = "Lazy Dog",
            category = "SAFE — WORKER",
            giver = "Phil / Brogar",
            location = "Bandit Camp",
            prerequisites = "Speak to Phil or Brogar about Clay neglecting his guard shift.",
            summary = "Get Clay to return to his guard post.",
            walkthroughSteps = listOf("Find Clay resting at the Bandit Camp fire after taking the complaint from Phil or Brogar.", "Convince Clay to return to work, either with a small payment or by defeating him in a non-lethal fight.", "Report to Phil to collect the additional reward."),
            reward = "200 XP; 25 XP and 25 gold from Phil",
            warnings = "",
            searchTags = listOf("Lazy Dog", "Phil / Brogar", "Bandit Camp", "Chapter 1", "optional side quests"),
        ),
        Quest(
            id = "R1-C1-106",
            chapter = 1,
            playOrder = 106,
            title = "Defeat Craig in the Arena",
            category = "SAFE — ARENA",
            giver = "Craig",
            location = "Bandit Camp arena",
            prerequisites = "Join Craig's arena tournament and arrange a bout with Craig.",
            summary = "Knock Craig unconscious in a legal arena fight.",
            walkthroughSteps = listOf("Speak to Craig about fighting him and place a wager if desired.", "Defeat Craig in the arena without killing him.", "Loot the Golden Sword fragment from him; it is needed for Golden Fragments for Oscar."),
            reward = "150 XP plus Golden Sword fragment; wager depends on stake",
            warnings = "",
            searchTags = listOf("Defeat Craig in the Arena", "Craig", "Bandit Camp arena", "Chapter 1", "optional side quests"),
        ),
        Quest(
            id = "R1-C1-107",
            chapter = 1,
            playOrder = 107,
            title = "Defeat Domingo in the Arena",
            category = "SAFE — ARENA",
            giver = "Domingo",
            location = "Bandit Camp arena",
            prerequisites = "Progress through the Bandit Camp arena challengers and bring Domingo a beer to accept his bout.",
            summary = "Defeat Domingo in a non-lethal duel.",
            walkthroughSteps = listOf("Speak to Craig about the fight and, if desired, wager up to 100 gold.", "Give Domingo beer and challenge him to an arena fight.", "Defeat him and collect the payout from Craig."),
            reward = "200 XP; optional wager up to 200 gold",
            warnings = "",
            searchTags = listOf("Defeat Domingo in the Arena", "Domingo", "Bandit Camp arena", "Chapter 1", "optional side quests"),
        ),
        Quest(
            id = "R1-C1-108",
            chapter = 1,
            playOrder = 108,
            title = "Branon Needs Help",
            category = "SAFE — WORKER",
            giver = "Branon",
            location = "Bandit Camp upper dig site",
            prerequisites = "Ask Hawkins about the idle diggers and meet Branon near the upper excavation.",
            summary = "Help Branon by addressing Ricardo's neglect of the grave moths.",
            walkthroughSteps = listOf("Climb the arena path to Branon's campfire and ask why he refuses to dig.", "Talk to Ricardo about the grave moths and clear the insects if necessary. Tell Ricardo Branon has no protection.", "Inform Branon of Ricardo's refusal, then follow up with Brogar if available."),
            reward = "150 XP after speaking to Ricardo; 25 XP from Branon and optional 25 XP from Brogar",
            warnings = "",
            searchTags = listOf("Branon Needs Help", "Branon", "Bandit Camp upper dig site", "Chapter 1", "optional side quests"),
        ),
        Quest(
            id = "R1-C1-109",
            chapter = 1,
            playOrder = 109,
            title = "Protection Against the Ghost of the Ancestors",
            category = "SAFE — WORKER",
            giver = "Enrico",
            location = "Bandit Camp excavation",
            prerequisites = "Ask Hawkins about idle workers and speak with Enrico about the frightening ruins.",
            summary = "Give Enrico the supposedly protective amulet to get him working again.",
            walkthroughSteps = listOf("Hear Enrico's fear of ancient ghosts at the digging site.", "Retrieve the worthless amulet from the excavation chest near the grave moths.", "Convince Enrico that it protects him from ghosts and return him to work."),
            reward = "100 XP",
            warnings = "",
            searchTags = listOf("Protection Against the Ghost of the Ancestors", "Enrico", "Bandit Camp excavation", "Chapter 1", "optional side quests"),
        ),
        Quest(
            id = "R1-C1-110",
            chapter = 1,
            playOrder = 110,
            title = "Scurrying Rats",
            category = "SAFE — HUNT",
            giver = "Luis",
            location = "Bandit Camp outskirts",
            prerequisites = "Ask Sam to get the hunters working; speak to Luis about why he will not hunt.",
            summary = "Eliminate the stringrats near Luis's hunting area.",
            walkthroughSteps = listOf("Question Luis about the hunters' absence and accept the request to kill stringrats.", "Search south of his camp and kill the rats.", "Return to Luis to get him hunting again and report to Sam."),
            reward = "200 XP plus 50 XP and 25 gold from Luis",
            warnings = "",
            searchTags = listOf("Scurrying Rats", "Luis", "Bandit Camp outskirts", "Chapter 1", "optional side quests"),
        ),
        Quest(
            id = "R1-C1-111",
            chapter = 1,
            playOrder = 111,
            title = "Dorgan's List",
            category = "SAFE — DISCOVERY",
            giver = "Dorgan's corpse / Brogar",
            location = "Swamp cave and Bandit Camp",
            prerequisites = "Investigate Brogar's missing man Dorgan in the swamp cave.",
            summary = "Recover Dorgan's list of protection-money debtors and hand it in.",
            walkthroughSteps = listOf("Find Dorgan's corpse in a cave guarded by grave moths and loot his list.", "Show the list to Rachel before giving it to Brogar if you want to expose the extortion scheme.", "Bring the list to Brogar to complete this objective."),
            reward = "100 XP; optional 50 XP for showing the list to Rachel",
            warnings = "",
            searchTags = listOf("Dorgan's List", "Dorgan's corpse / Brogar", "Swamp cave and Bandit Camp", "Chapter 1", "optional side quests"),
        ),
        Quest(
            id = "R1-C1-112",
            chapter = 1,
            playOrder = 112,
            title = "Rhobart's Bog Bodies",
            category = "SAFE — HUNT",
            giver = "Rhobart",
            location = "Swamp waterfall",
            prerequisites = "Try to collect protection money from Rhobart on Brogar's behalf.",
            summary = "Destroy the three bog bodies near Rhobart's swamp farm.",
            walkthroughSteps = listOf("Ask Rhobart about Brogar's collection; he requests help with bog bodies.", "Lure the three bog bodies near the waterfall toward friendly farm guards if you need help, then defeat them.", "Report back to Rhobart before taking his protection-money payment."),
            reward = "250 XP for killing them; 50 XP and 50 gold on report",
            warnings = "",
            searchTags = listOf("Rhobart's Bog Bodies", "Rhobart", "Swamp waterfall", "Chapter 1", "optional side quests"),
        ),
        Quest(
            id = "R1-C1-113",
            chapter = 1,
            playOrder = 113,
            title = "Power Struggle",
            category = "BANDIT CAMP — CHOICE",
            giver = "Sam",
            location = "Bandit Camp",
            prerequisites = "Speak to Brogar about the camp and ask Sam about Brogar's abuse of authority.",
            summary = "End Brogar's intimidation and restore Sam's position.",
            walkthroughSteps = listOf("Discuss Brogar with Sam and complete Protection Money in the Bandit Camp.", "Tell Rachel what Brogar has been doing, then confront Brogar and threaten to expose him.", "When he backs down, return to Rachel for your reward and Brogar's hut."),
            reward = "350 XP; 50 XP and 150 gold from Rachel, plus Brogar's hut",
            warnings = "",
            searchTags = listOf("Power Struggle", "Sam", "Bandit Camp", "Chapter 1", "optional side quests"),
        ),
        Quest(
            id = "R1-C1-114",
            chapter = 1,
            playOrder = 114,
            title = "The Hunters Are to Hunt Again",
            category = "SAFE — HUNTER QUEST",
            giver = "Sam",
            location = "Bandit Camp",
            prerequisites = "Learn that Sam is cutting wood for Brogar and ask about getting hunters back to work.",
            summary = "Get Doug, Luis and finally Sam back to hunting.",
            walkthroughSteps = listOf("Complete Go Hunting with Doug and Scurrying Rats for Luis, then report these improvements to Sam.", "Complete Power Struggle so Brogar can no longer force Sam to cut wood.", "Tell Brogar to free Sam, then speak to Sam and report to Rachel."),
            reward = "200 XP and 50 gold from Sam; extra reports award XP",
            warnings = "",
            searchTags = listOf("The Hunters Are to Hunt Again", "Sam", "Bandit Camp", "Chapter 1", "optional side quests"),
        ),
        Quest(
            id = "R1-C1-115",
            chapter = 1,
            playOrder = 115,
            title = "Golden Fragments for Oscar",
            category = "SAFE — COLLECTION",
            giver = "Oscar",
            location = "Bandit Camp swamp",
            prerequisites = "Talk to Oscar about forging the Golden Sword to gain an audience with the Don.",
            summary = "Collect five Golden Sword fragments and get Oscar to reforge the blade.",
            walkthroughSteps = listOf("Find one piece from Luis in exchange for beer, one in the excavation island chest and one each by defeating Craig and Brogar in the arena.", "Loot Dorgan's corpse in the swamp cave for the fifth piece.", "Give all five parts to Oscar to reforge the Golden Sword; consider whether you want to buy it from him."),
            reward = "400 XP for assembling pieces; 200 XP and 50 gold from Oscar",
            warnings = "",
            searchTags = listOf("Golden Fragments for Oscar", "Oscar", "Bandit Camp swamp", "Chapter 1", "optional side quests"),
        ),
        Quest(
            id = "R1-C1-116",
            chapter = 1,
            playOrder = 116,
            title = "Take the Golden Sword to Esteban",
            category = "SAFE — STORY",
            giver = "Don Esteban",
            location = "Bandit Camp temple",
            prerequisites = "Obtain the reforged Golden Sword from Oscar and Rachel's approval to see the Don.",
            summary = "Present the Golden Sword to Don Esteban as a gift.",
            walkthroughSteps = listOf("Complete Golden Fragments for Oscar and ask Rachel for access to the Don.", "Show the sword at the temple gate and tell the guard Rachel sent you.", "Give the Golden Sword to Don Esteban to finish the audience sequence."),
            reward = "1,150 XP and 150 gold",
            warnings = "",
            searchTags = listOf("Take the Golden Sword to Esteban", "Don Esteban", "Bandit Camp temple", "Chapter 1", "optional side quests"),
        )
    )
}
